### ISSUE TITLE
encountering " protocol Enumerable not implemented for nil of type Atom" while running the docker-compose with external database

### ISSUE THREAD

**Issue by SorrawitRUNGRUJEE** [blockscout/blockscout#10007]
### Description

I am trying to run blockscout with docker-compose -f external-db.yml up  and then the following error shows up from the attached console

stats            | 2024-05-02T06:30:23.959183Z ERROR stats_server: service failed with error: Connection Error: error communicating with database: failed to lookup address information: Name or service not known
stats            | Error: Connection Error: error communicating with database: failed to lookup address information: Name or service not known
stats            |
stats            | Caused by:
stats            |     error communicating with database: failed to lookup address information: Name or service not known 

backend          | Starting dependencies..
backend          | Starting repos..
backend          | ** (EXIT from #PID<0.132.0>) an exception was raised:
backend          |     ** (Protocol.UndefinedError) protocol Enumerable not implemented for nil of type Atom. This protocol is implemented for the following type(s): Cldr.Unit.Range, DBConnection.PrepareStream, DBConnection.Stream, Date.Range, Ecto.Adapters.SQL.Stream, File.Stream, Floki.HTMLTree, Flow, Function, GenEvent.Stream, HashDict, HashSet, IO.Stream, Indexer.BoundQueue, Jason.OrderedObject, List, Map, MapSet, Postgrex.Stream, Range, Stream, Timex.Interval

### Type of the installation

Docker-compose

### Type of the JSON RPC archive node

Geth

### Steps to reproduce

1. clone blockscout from master branch 
2. change the env in common-blockscout as follow
DATABASE_URL
postgresql://postgres:<password>@test-explorer.crnrz7sdkd7c.ap-southeast-1.rds.amazonaws.com:5432

ETHEREUM_JSONRPC_HTTP_URL=http://188.166.205.207

ETHEREUM_JSONRPC_TRACE_URL=http://188.166.205.207

3. run the docker-compose

### Backend version

latest

### Frontend version

latest

### Elixir & Erlang/OTP versions

Elixir 1.14.5 (compiled with Erlang/OTP 25)

### Operating system

Linux

**Comment by vbaranov** [comment]
@SorrawitRUNGRUJEE you should put the db name at the end of the URI. So the full URI should look like your_uri + `/${db_name}`. E.g.

```
postgresql://postgres:***@test-explorer.crnrz7sdkd7c.ap-southeast-1.rds.amazonaws.com:5432/blockscout
```

**Comment by SorrawitRUNGRUJEE** [comment]
Thank you for your advice

I've changed the database URL as you have suggested as follow

postgresql://postgres:************@test-explorer.crnrz7sdkd7c.ap-southeast-1.rds.amazonaws.com:5432/blockscout

but there are still error that is showing up

![error_1](https://github.com/blockscout/blockscout/assets/139847674/891b1f44-4d7b-4f92-b5de-580a8d8d64d2)

![error_2](https://github.com/blockscout/blockscout/assets/139847674/d6483755-5520-4ea4-b8b0-03bdd3a9fe9f)

![error_3](https://github.com/blockscout/blockscout/assets/139847674/d687f169-614a-44ed-8747-28e9e2160326)

![error_4](https://github.com/blockscout/blockscout/assets/139847674/900a708b-0683-44ed-83df-cd9890809341)

![error_5](https://github.com/blockscout/blockscout/assets/139847674/4de6ed27-7fdc-4b51-80f2-56e71ffff304)

 
I have test the connection with DBeaver and pg_isready command line, both connection test were normal

**Comment by fslmultiservice22** [comment]
Cerco una collaborazione.

**Comment by yohanelly95** [comment]
> @SorrawitRUNGRUJEE you should put the db name at the end of the URI. So the full URI should look like your_uri + `/${db_name}`. E.g.
> 
> ```
> postgresql://postgres:***@test-explorer.crnrz7sdkd7c.ap-southeast-1.rds.amazonaws.com:5432/blockscout
> ```

hey @vbaranov, I am running postgres db on the same vm (not external). But still getting the error that 
```
Starting dependencies..
Starting repos..
** (EXIT from #PID<0.132.0>) an exception was raised:
    ** (Protocol.UndefinedError) protocol Enumerable not implemented for nil of type Atom. This protocol is implemented for the following type(s): Cldr.Unit.Range, DBConnection.PrepareStream, DBConnection.Stream, Date.Range, Ecto.Adapters.SQL.Stream, File.Stream, Floki.HTMLTree, Flow, Function, GenEvent.Stream, HashDict, HashSet, IO.Stream, Indexer.BoundQueue, Jason.OrderedObject, List, Map, MapSet, Postgrex.Stream, Range, Stream, Timex.Interval
        (elixir 1.14.5) lib/enum.ex:1: Enumerable.impl_for!/1
        (elixir 1.14.5) lib/enum.ex:166: Enumerable.reduce/3
        (elixir 1.14.5) lib/enum.ex:4307: Enum.reverse/1
        (elixir 1.14.5) lib/keyword.ex:202: Keyword.new/2
        lib/explorer/repo/config_helper.ex:61: Explorer.Repo.ConfigHelper.extract_parameters/1
        lib/explorer/repo/config_helper.ex:26: Explorer.Repo.ConfigHelper.get_db_config/1
        lib/explorer/repo.ex:20: Explorer.Repo.init/2
        (ecto 3.11.2) lib/ecto/repo/supervisor.ex:25: Ecto.Repo.Supervisor.runtime_config/4
        ```

**Comment by yohanelly95** [comment]
![Screenshot 2024-05-08 at 1 00 05 PM](https://github.com/blockscout/blockscout/assets/33081891/f67527b6-e196-4ece-8caa-3fd3f4112d2f)
attaching logs of `stats`. I have updated the same username and password on `services/stats.yml` and `services/db.yml`. Not sure what could be causing this issue. Tested connection to the db manually seems to work fine.

**Comment by vbaranov** [comment]
> @vbaranov Thank you for your advice
> 
> I've changed the database URL as you have suggested as follow
> 
> postgresql://postgres:************@test-explorer.crnrz7sdkd7c.ap-southeast-1.rds.amazonaws.com:5432/blockscout
> 
> but there are still error that is showing up
> 
> ![error_1](https://private-user-images.githubusercontent.com/139847674/327636770-891b1f44-4d7b-4f92-b5de-580a8d8d64d2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUzMzU3NjYsIm5iZiI6MTcxNTMzNTQ2NiwicGF0aCI6Ii8xMzk4NDc2NzQvMzI3NjM2NzcwLTg5MWIxZjQ0LTRkN2ItNGY5Mi1iNWRlLTU4MGE4ZDhkNjRkMi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTEwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUxMFQxMDA0MjZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04YWQ5YTk4YTc0NjMwZjFlMDZjZDdhYmY2NGU1MDg1M2M4YTM4NTQ4ZjM3NzYyOWRjMzk4YmQyODkwMjNiYzM3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.P9u-YgEnC3-U2dsrgf5OvVChBEmE10TwNeegcDLjHrQ)
> 
> ![error_2](https://private-user-images.githubusercontent.com/139847674/327636825-d6483755-5520-4ea4-b8b0-03bdd3a9fe9f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUzMzU3NjYsIm5iZiI6MTcxNTMzNTQ2NiwicGF0aCI6Ii8xMzk4NDc2NzQvMzI3NjM2ODI1LWQ2NDgzNzU1LTU1MjAtNGVhNC1iOGIwLTAzYmRkM2E5ZmU5Zi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTEwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUxMFQxMDA0MjZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wNTBlODJkMTY3NDlmZDM4ZmUwMTJmYmY2YTAwMmM5MWIyNjZiY2E3YTY3YWU3MDJjYzE4MmVhNDZmZTZjNzJiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.QvhtIEHeEmRbrppSkzm3OgbzwYfQzabF5qz_Bo6Nf-o)
> 
> ![error_3](https://private-user-images.githubusercontent.com/139847674/327636877-d687f169-614a-44ed-8747-28e9e2160326.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUzMzU3NjYsIm5iZiI6MTcxNTMzNTQ2NiwicGF0aCI6Ii8xMzk4NDc2NzQvMzI3NjM2ODc3LWQ2ODdmMTY5LTYxNGEtNDRlZC04NzQ3LTI4ZTllMjE2MDMyNi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTEwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUxMFQxMDA0MjZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02MTliZDFjOTMwMWE5MDcxNmRhMmE3YmIwMjQwYTI0OWEyMjQyNTczMzI5ZTgyNTBjY2Q2M2NlNTkwOGNmNDAxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.caJlQ8FCwynXXy03B45jI_zdcxeCdykhMh3NRvym5W4)
> 
> ![error_4](https://private-user-images.githubusercontent.com/139847674/327636950-900a708b-0683-44ed-83df-cd9890809341.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUzMzU3NjYsIm5iZiI6MTcxNTMzNTQ2NiwicGF0aCI6Ii8xMzk4NDc2NzQvMzI3NjM2OTUwLTkwMGE3MDhiLTA2ODMtNDRlZC04M2RmLWNkOTg5MDgwOTM0MS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTEwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUxMFQxMDA0MjZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mYzY4M2Q3MmE3MmQ3MzYwOTdiNDNkYWViMDY1NGM0YjUwMzdlODg0MjBkZWRjNDMwZWQwNTkzMzNlNTZhOWM3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.9OhPih2-sBt8SyF-Jky8qdCjo1fdcaMAmdRTw53fCY8)
> 
> ![error_5](https://private-user-images.githubusercontent.com/139847674/327637070-4de6ed27-7fdc-4b51-80f2-56e71ffff304.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUzMzU3NjYsIm5iZiI6MTcxNTMzNTQ2NiwicGF0aCI6Ii8xMzk4NDc2NzQvMzI3NjM3MDcwLTRkZTZlZDI3LTdmZGMtNGI1MS04MGYyLTU2ZTcxZmZmZjMwNC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTEwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUxMFQxMDA0MjZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03Y2YyNTc4OWJjMjFiNmExZTU2MGYwOTFlODRmNTQ2MTMxY2Q0NGI3Y2JjZTFkMDc1ZDZiMGZjN2RjMTdiMjI2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.vg8JJDugPp9euG1iZNiJ3tgbShw2V_0frevpRGQGjBc)
> 
> I have test the connection with DBeaver and pg_isready command line, both connection test were normal

@SorrawitRUNGRUJEE please check your DB URL to follow this regexp pattern (see comment https://github.com/blockscout/blockscout/issues/10047#issuecomment-2104287368). Most likely it doesn't follow this pattern.
