### ISSUE TITLE
Bridge BNB 4 day unfinished3

### ISSUE THREAD

**Issue by vanty225339** [blockscout/blockscout#10013]
### Description

Bridge BNB 4 day unfinished2

### Type of the installation

Docker-compose

### Type of the JSON RPC archive node

bridge BNB 4 day unfinished

### Link to the page

https://xterscan.io/tx/0x746b6ed1d038067a6e0fdb17c5b0f375bb3a05c64392c4cffb318cb5c479ca45

### Steps to reproduce

bridge BNB 4 day unfinished1

### Backend version

v6.5.0-beta

### Elixir & Erlang/OTP versions

Elixir & Erlang/OTP versions.

### Additional information

**User Agent:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36

**Comment by fslmultiservice22** [comment]
Buongiorno,
Cerco una collaborazione per la gestione di mio programma, sono in difficoltà.

**Comment by vbaranov** [comment]
Blockscout team doesn't manage this instance of Blockscout. You should ask the question to the team, which supports this chain.
