### ISSUE TITLE
transaction stuck

### ISSUE THREAD

**Issue by Softelauch** [blockscout/blockscout#10016]
### Description

When trying to swap a token, the transaction froze, accelerating the transaction did not help, the transaction waits for more than an hour
![photo_2024-05-03_10-45-17](https://github.com/blockscout/blockscout/assets/145222630/18ae1629-b354-4ac0-8748-c82988050f16)

### Type of the installation

Docker-compose

### Type of the JSON RPC archive node

geth

### Link to the page

https://swap.hekla.taiko.xyz/#/swap

### Steps to reproduce

When trying to swap a token, the transaction froze, accelerating the transaction did not help, the transaction waits for more than an hour

### Backend version

6.3.0

### Elixir & Erlang/OTP versions

Elixir 1.14.5 Erlang/OTP 24

### Operating system

Windows  10

### Additional information

The issue happened at hekla Blockscout instance

**Comment by Softelauch** [comment]
![photo_2024-05-03_11-05-41](https://github.com/blockscout/blockscout/assets/145222630/21ccb68e-8732-4cb8-b1ff-ccf4250ccc82)

**Comment by Softelauch** [comment]
id tranz -  0x30111e4893f4e34605296332d973e9a1508a3de375bf581c1cb79f1bb822e265

**Comment by vbaranov** [comment]
This chat is for Blockscout-related questions. Your question is out of scope, where the Blockscout team can help.
