### ISSUE TITLE
Transfer Error: ETH sent to incorrect account

### ISSUE THREAD

**Issue by AshtonGuitard** [blockscout/blockscout#10024]
### Description

I transferred ETH to an account but it was incorrect, how do I go about retrieving my funds? 

### Type of the installation

Docker-compose

### Type of the JSON RPC archive node

Open

### Link to the page

https://explorer.zora.energy/address/0x5308EAF04047482C69fFb1bf0E4A6F38295FCcab?tab=txs

### Backend version

v6.5.0-beta.+commit.819702fb

### Elixir & Erlang/OTP versions

Elixir 1.14.5

### Additional information

**User Agent:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36

**Comment by vbaranov** [comment]
This chat is for Blockscout-related questions. Your question is out of scope, where the Blockscout team can help.
