### ISSUE TITLE
Incorrect Txn Count in the Explorer

### ISSUE THREAD

**Issue by ykchong45** [blockscout/blockscout#10021]
### Description

![image](https://github.com/blockscout/blockscout/assets/50497617/a059b09e-b689-41fa-966c-0aabebe8d837)

I refreshed the webpage several times (with shift+f5) too, but you can see the count being 0 even when there is a token transfer.

The transaction is triggered from [this USDC faucet](https://faucet.circle.com/). This is a new wallet, and this transaction was the first token transaction of the wallet.

### Type of the installation

Docker-compose

### Type of the JSON RPC archive node

I don't know

### Link to the page

https://base-sepolia.blockscout.com/address/0xBfCfC784A901918757d57cD956782d6C72e7c933?tab=token_transfers

### Backend version

v6.5.0-beta

### Frontend version

v1.29.2+c4b58cf0

### Elixir & Erlang/OTP versions

I don't know

### Additional information

**User Agent:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36 Edg/124.0.0.0

**Comment by vbaranov** [comment]
Tab counters are updated asynchronously. Delay might happen. Currently, the value is more than 0.

**Comment by Bartletti** [comment]
⚡️⚡️⚡️⚡️⚡️
