### ISSUE TITLE
By mistake sent ETH on SHIB address and never received 

### ISSUE THREAD

**Issue by Ankitdrana** [blockscout/blockscout#10022]
### Description

By mistake sent ETH on SHIB address and never received 

### Type of the installation

Docker-compose

### Type of the JSON RPC archive node

By mistake sent ETH on SHIB address and never received 

### Type of the chain

By mistake sent ETH on SHIB address and never received 

### Link to the page

https://etc.blockscout.com/tx/0xbeb01dbd1e91a484ae66dcec001b0ead14212ac40480763e056eb2a61131b45f

### Steps to reproduce

By mistake sent ETH on SHIB address and never received 

### Backend version

v6.5.0-beta

### Frontend version

v1.29.2+c4b58cf0

### Elixir & Erlang/OTP versions

By mistake sent ETH on SHIB address and never received 

### Operating system

By mistake sent ETH on SHIB address and never received 

### Additional information

**User Agent:** Mozilla/5.0 (iPhone; CPU iPhone OS 17_4_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.4.1 Mobile/15E148 Safari/604.1

**Comment by vbaranov** [comment]
This chat is for Blockscout-related questions. Your question is out of scope, where the Blockscout team can help.
