### ISSUE TITLE
I sent EAI from Nakachain to Uniswap

### ISSUE THREAD

**Issue by Yousuf7890** [blockscout/blockscout#10026]
### Description

Hi, I sent EAI from nakachain to uniswap, vut I didn’t get any in my Uniswap wallet.

### Type of the installation

Docker-compose

### Type of the JSON RPC archive node

Idk

### Backend version

Idk

### Elixir & Erlang/OTP versions

Idk

**Comment by Yousuf7890** [comment]
This is transaction HAsh 0x09030f8dafac189d9e7214aca4fb8c90a2ff7380510e92c04678fd0b4f423887

**Comment by vbaranov** [comment]
This chat is for Blockscout-related questions. Your question is out of scope, where the Blockscout team can help.
