### ISSUE TITLE
Withdrawal issue

### ISSUE THREAD

**Issue by Abdoulhy** [blockscout/blockscout#10025]
### Description

I have submitted a withdrawal request successiful, but not received in my trust wallet. 
![Screenshot_20240505-214548](https://github.com/blockscout/blockscout/assets/145406335/a5a2122a-c25a-45e2-88a3-43eec40a94aa)

### Type of the installation

Docker-compose

### Type of the JSON RPC archive node

geth

### Backend version

v5.3.1-beta.+commit.c472f7bb

### Elixir & Erlang/OTP versions

Elixir 1.14.5 Erlang/OTP 24

### Operating system

unix linux

### Additional information

The issue happened at Vigor Chain Mainnet Blockscout instance

**Comment by vbaranov** [comment]
This chat is for Blockscout-related questions. Your question is out of scope, where the Blockscout team can help.
