### ISSUE TITLE
Failed Transaction 

### ISSUE THREAD

**Issue by Dheekir23** [blockscout/blockscout#10037]
### Description

Sent token my islm token from keplr to Kucoin exchange since yesterday and still haven't received it up till now and the transaction is not even on the haqq explorer but the token has left my keplr wallet. Please help me 

### Type of the installation

Docker-compose

### Type of the JSON RPC archive node

0

### Type of the chain

L1

### Link to the page

https://explorer.haqq.network/address/0xA89FE53E02C8fd1D56CA676dBAFc636F7208e6E2?tab=coin_balance_history

### Steps to reproduce

Nil

### Backend version

v6.3.0-beta

### Frontend version

v1.27.0+5a63649f

### Elixir & Erlang/OTP versions

OTP25

### Operating system

Windows

### Additional information

**User Agent:** Mozilla/5.0 (Linux; Android 14; SM-A346E Build/UP1A.231005.007; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/124.0.6367.123 Mobile Safari/537.36 KeplrWalletMobile/2.0.43

**Comment by vbaranov** [comment]
This chat is for Blockscout-related questions. Your question is out of scope, where the Blockscout team can help.
