### ISSUE TITLE
Erros in the transfer from OP mainnet to Mode network using Jumper.Exchange

### ISSUE THREAD

**Issue by andersongalecki** [blockscout/blockscout#10043]
### Description

I was transfer 0.09 ETH from Optmism to Mode network using the Jumper.Exchage and do not complet. Please sand the 0.9 ETH back to my adreess 0x0A8738a060987F61d2feA461b02ee074F3483651.
<img width="924" alt="jumper" src="https://github.com/blockscout/blockscout/assets/142410375/8fcebdaf-2c13-43ad-b953-2ff2a21af2b5">
<img width="276" alt="metamask" src="https://github.com/blockscout/blockscout/assets/142410375/a25bec98-2d99-49b2-808a-158130058dc2">
<img width="938" alt="mode scream 1" src="https://github.com/blockscout/blockscout/assets/142410375/a9b3cdb1-7509-44fd-a4db-c81a5fedd7d6">
<img width="937" alt="mode scream 2" src="https://github.com/blockscout/blockscout/assets/142410375/8e1a0a27-69b7-4ada-93cf-24d7b739c057">

### Type of the installation

Docker-compose

### Type of the JSON RPC archive node

OP Mainnet (Optmism)

### Type of the chain

L2

### Link to the page

https://explorer.mode.network/tx/0x870bed823a3d422b5c43e0e5b61b82d3c281263df688412077ce4b3658538e66?tab=index

### Backend version

v6.5.0-beta.+commit.819702fb

### Elixir & Erlang/OTP versions

Elixir 1.14.5

### Operating system

Windows

### Additional information

**User Agent:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36

**Comment by vbaranov** [comment]
This chat is for Blockscout-related questions. Your question is out of scope, where the Blockscout team can help.
