### ISSUE TITLE
no tokens in metamasc

### ISSUE THREAD

**Issue by 456642** [blockscout/blockscout#10040]
### Description

I gathered around 140 tokens in retia and now they are gone

### Type of the installation

Docker-compose

### Type of the JSON RPC archive node

ERIGON

### Type of the chain

L1

### Link to the page

https://testnet.photonchain.io/contract-verification

### Steps to reproduce

I gathered around 140 tokens in retia and now they are gone

### Backend version

v6.5.0-beta

### Frontend version

1;11;1

### Elixir & Erlang/OTP versions

elixir

### Operating system

windows

### Additional information

**User Agent:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36 Edg/124.0.0.0

**Comment by 456642** [comment]
I gathered around 140 tokens in retia and now they are gone

**Comment by vbaranov** [comment]
This chat is for Blockscout-related questions. Your question is out of scope, where the Blockscout team can help.
