### ISSUE TITLE
Mixed Email linking on Satoshi app 

### ISSUE THREAD

**Issue by Yushauatata** [blockscout/blockscout#10055]
### Description

I opened my Satoshi app with yushaumumini.atata@gmail.com but when I was doing missions project on OEX app I mistakenly linked yushauatata@gmail.com which is probably the reason why my OEX Satoshi Balance is not yet confirmed green. I have linked wallet during the wallet linking process and also install latest app, I imported my backup keys and did face verification as instructed but yet my Satoshi OEX point is not showing and not turned green yet on my OEX app. 
![Screenshot_20240511-151225](https://github.com/blockscout/blockscout/assets/169544714/39f0f98f-b28d-4675-b3bb-997d5c595379)
![Screenshot_20240511-152423](https://github.com/blockscout/blockscout/assets/169544714/dc164105-6d5e-4c72-928a-1ea9f70f62d8)

### Type of the installation

Manual from the source code

### Type of the JSON RPC archive node

Writing/geth

### Link to the page

https://scan.long.openex.network/address/0x723F581680A15F4323De5Fd969654100d56EE0D4

### Backend version

V6.1.0

### Frontend version

v1.30.0-alpha+4b906f03

### Elixir & Erlang/OTP versions

Elixir 1.145

### Additional information

**User Agent:** Mozilla/5.0 (Linux; Android 11; Nokia C30 Build/RP1A.201005.001; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/124.0.6367.159 Mobile Safari/537.36

**Comment by vbaranov** [comment]
This chat is for Blockscout-related questions. Your question is out of scope, where the Blockscout team can help.
