### ISSUE TITLE
ETH Transation

### ISSUE THREAD

**Issue by Kingdalua** [blockscout/blockscout#10054]
### Description

I send 0.0055 ETH to this adress 0xea994f084c648f8bfecfac1f942567a572a42c52. This amount is not received, I check the transation and the adress is change to this 0xEa994f084C648f8bfeCFAC1F942567A572A42C52. It change all letter to Capital.

https://explorer.apex.proofofplay.com/tx/0x81ca763a3ee42077fc78a514fccb815324807b542df10034118879e522d49b1c

### Type of the installation

Docker-compose

### Type of the JSON RPC archive node

ETH

### Type of the chain

L2

### Link to the page

https://explorer.apex.proofofplay.com/tx/0x81ca763a3ee42077fc78a514fccb815324807b542df10034118879e522d49b1c

### Steps to reproduce

In my metamask i just send ETH to correct copy adress 0xea994f084c648f8bfecfac1f942567a572a42c52

![send](https://github.com/blockscout/blockscout/assets/169540063/d736ed08-e4b2-496c-9056-59b94039f850)

### Backend version

v6.5.0-beta

### Elixir & Erlang/OTP versions

Elixir 1.14.5

### Operating system

Windows

### Additional information

**User Agent:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36

**Comment by vbaranov** [comment]
Blockscout team doesn't manage this instance of Blockscout. You should ask the question to the team, which supports this chain.
