### ISSUE TITLE
My currency address has not been transacted but can you assist me in getting it back

### ISSUE THREAD

**Issue by nguyenducloc2002** [blockscout/blockscout#10052]
### Description

Transaction details : 0xdafa35a570c4a2a481e88adce0bdf0f2f3a9aca394f1d7113555da2f5f16b875 My currency address has not been transacted but can you assist me in getting it back.     wallet address: 0xf16f3cBDFA83CC88676971B5A37752abEd0F13cC

### Type of the installation

Docker-compose

### Type of the JSON RPC archive node

PNG

### Type of the chain

L1

### Link to the page

https://bnb.xterscan.io/tx/0xdafa35a570c4a2a481e88adce0bdf0f2f3a9aca394f1d7113555da2f5f16b875

### Steps to reproduce

Transaction details : 0xdafa35a570c4a2a481e88adce0bdf0f2f3a9aca394f1d7113555da2f5f16b875 My currency address has not been transacted but can you assist me in getting it back.     wallet address: 0xf16f3cBDFA83CC88676971B5A37752abEd0F13cC

### Backend version

v6.5.0-beta

### Frontend version

V1111

### Elixir & Erlang/OTP versions

1.12.5

### Operating system

WINDOW

### Additional information

![Annotation 2024-05-10 235032](https://github.com/blockscout/blockscout/assets/169480395/a0d220c8-3eec-41f3-9cb9-d198e8815ba6)

**Comment by vbaranov** [comment]
This chat is for Blockscout-related questions. Your question is out of scope, where the Blockscout team can help.
