### ISSUE TITLE
Transaction issue 

### ISSUE THREAD

**Issue by grizzlie123** [blockscout/blockscout#10068]
### Description

the bridge from bnb xterio to binance smart chain has been delayed by 7 days

### Type of the installation

Docker-compose

### Type of the JSON RPC archive node

Xterio 

### Link to the page

https://bnb.xterscan.io/tx/0xf1556e77efe1852478c73b138993c7220543721ef8871fac1def6c12820aeeff

### Backend version

v6.5.0-beta

### Elixir & Erlang/OTP versions

Xterio 

### Additional information

**User Agent:** Mozilla/5.0 (Linux; Android 4.4.2; Nexus 4 Build/KOT49H) MathWallet/1.0 AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.130 Mobile Safari/537.36; BitKeep Android/8.13.1

**Comment by vbaranov** [comment]
This chat is for Blockscout-related questions. Your question is out of scope, where the Blockscout team can help.
