### ISSUE TITLE
ETERNAL AI 

### ISSUE THREAD

**Issue by Hussein222666** [blockscout/blockscout#10066]
### Description

Hi i need help in eternal ai project i import eternal ai private key in naka wallet the EAI Token was disappear i dont know what happen i need help to get them back i have all the information

### Type of the installation

Docker-compose

### Type of the JSON RPC archive node

BNB ETH USDT 

### Type of the chain

L2 

### Link to the page

https://eternalai.org/eai

### Steps to reproduce

in the second picture down i was see the token but when i click on them they put that i have 0 token from EAI

### Backend version

v6.1.0

### Frontend version

v.1.11.1

### Elixir & Erlang/OTP versions

ELixir 1.14.5

### Operating system

account, wallet 

### Additional information

![Screenshot 2024-05-14 202853](https://github.com/blockscout/blockscout/assets/156383432/6040d41f-2417-44e6-90ee-4c803c196d61)
![Screenshot 2024-05-14 203100](https://github.com/blockscout/blockscout/assets/156383432/90bbc212-3e99-4fc5-a996-bdd5098146c8)

**Comment by vbaranov** [comment]
This chat is for Blockscout-related questions. Your question is out of scope, where the Blockscout team can help.
