### ISSUE TITLE
BRIDGE XTERIO TO BNB chain ISSUE

### ISSUE THREAD

**Issue by lydiawen381** [blockscout/blockscout#10078]
### Description

I made a withdrawal from Xterio to the BNB network, it's been 3 days and it hasn't been approved.
Please help with this problem, maybe it's not just me who experiences it, maybe other people also experience the same thing
![Screenshot 2024-05-17 145028](https://github.com/blockscout/blockscout/assets/170081231/f08ea64a-851b-4cc9-bb74-7b772ee4bcfa)

### Type of the installation

Docker-compose

### Type of the JSON RPC archive node

XTERIO

### Link to the page

https://bnb.xterscan.io/tx/0xd1e1b4b8e9452ac03ffe5b9c4cfa16691bc6051a2b734720d10898d684958332

### Steps to reproduce

1. Fix current network problems.
2. Increase community support, currently there has been no response from the admin regarding the problem I experienced.

### Backend version

v6.5.0-beta

### Elixir & Erlang/OTP versions

Elixir 

### Additional information

**User Agent:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36

**Comment by vbaranov** [comment]
Blockscout team doesn't manage this instance of Blockscout. You should ask the question to the team, which supports this chain.
