### ISSUE TITLE
Want to ask

### ISSUE THREAD

**Issue by Bolalla** [blockscout/blockscout#10079]
### Description

Today i was staking my manta coin, but my omni.ls account said my staking is zero balance. The blockchain said the transaction confirmed and succeed. I tried second time but the result still my balance staking is zero. May I know why my staking wallet in omni website still zero and my metamask wallet doesn't have my coins

### Type of the installation

Manual from the source code

### Type of the JSON RPC archive node

none

### Type of the chain

L2

### Link to the page

https://pacific-explorer.manta.network/tx/0xcb2db0660234c0be76e96ae2f8d00032c7b7d69f1f18ecdc301af5f4afe934e4?tab=token_transfers

### Backend version

v6.1.10

### Frontend version

v1.11.1

### Elixir & Erlang/OTP versions

-

### Additional information

**User Agent:** Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.0.0 Safari/537.36

**Comment by vbaranov** [comment]
Blockscout team doesn't manage this instance of Blockscout. You should ask the question to the team, which supports this chain.

**Comment by Bolalla** [comment]
> Blockscout team doesn't manage this instance of Blockscout. You should ask the question to the team, which supports this chain.

i don't know where to ask. I'm not familiar with this github too
