### ISSUE TITLE
Transactions stuck on "pending"-placed a couple days before Degen L3 outage

### ISSUE THREAD

**Issue by jmf17004** [blockscout/blockscout#10082]
### Description

![Screen Shot 2024-05-17 at 2 43 01 PM](https://github.com/blockscout/blockscout/assets/161660546/ba3ae6e5-bcf0-458b-a47f-4df2d7ef1dfd)

Hi,

Writing to submit an issue with the Degen L3. I recently placed a transaction to swap Degen into DINU. Initially, the transaction went through; however, when the L3 went out, the tokens no longer showed in my wallet, and they are still not showing in my wallet. I also placed a mint for DEPE around the same time, which also never went through. The transactions never reverted (I wasn't refunded my Degen tokens). When I look on block explorer, the transactions are stuck "pending." 

And I'm sorry if this is not the right place to submit the issue. I have truly no idea where to submit my concerns.

Thank you for all your help!

### Type of the installation

Docker-compose

### Type of the JSON RPC archive node

https://eth-goerli.blockscout.com

### Type of the chain

L3

### Link to the page

https://explorer.degen.tips/address/0xE0BF32a4e6B3aE0E42b7c873b87bB0b35F55064a?tab=txs

### Backend version

v6.5.0-beta.+commit.477b156f

### Elixir & Erlang/OTP versions

huh?

### Additional information

**User Agent:** Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36

**Comment by sl1depengwyn** [comment]
This repo is for Blockscout-related questions. Blockscout is an open source blockchain explorer. Thus, your question is out of scope, where the Blockscout team can help, you better contact the chain support directly.
