### ISSUE TITLE
My Transaction not received 

### ISSUE THREAD

**Issue by Edoardoiop** [blockscout/blockscout#10081]
### Description

I bridged, on May 05 2024 17:26:57 PM
 But it was not transferred to mu bnb network until now!

### Type of the installation

Docker-compose

### Type of the JSON RPC archive node

None?

### Type of the chain

Exterior chain

### Link to the page

https://bnb.xterscan.io/tx/0xa905057df571ff13430461c9e5bb5adb4cb8ddee3e7138979fb1db9e05fd62c3

### Steps to reproduce

Plz  

### Backend version

v6.5.0-beta

### Elixir & Erlang/OTP versions

I can't understand 

### Additional information

**User Agent:** Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Mobile Safari/537.36

**Comment by vbaranov** [comment]
The Blockscout team doesn't manage this instance of Blockscout. It would be best if you asked the question to the team, which supports this chain.
