### ISSUE TITLE
Not received BONE to my Ledger

### ISSUE THREAD

**Issue by 1natin** [blockscout/blockscout#10083]
### Description

I sent BONE from Gate io to my ledger and choosed Bone-shibarium network to send and not Etherium network... I did submit the Etherium address ... My tokens are stuck in Bone-shibarium network ... how can this be fixed so I receive my Bone to my Ledger?
It is sent with this address 0x29D435ac03Cc0079A50ef287c04B97d5D88FD0F2 and it´s my Etherium address!
Here is the link to the transfer: https://www.shibariumscan.io/address/0x29D435ac03Cc0079A50ef287c04B97d5D88FD0F2

### Type of the installation

Docker-compose

### Type of the JSON RPC archive node

?

### Link to the page

https://www.shibariumscan.io/address/0x29D435ac03Cc0079A50ef287c04B97d5D88FD0F2

### Steps to reproduce

I sent BONE from Gate io to my ledger and choosed Bone-shibarium network to send and not Etherium network... I did submit the Etherium address ... My tokens are stuck in Bone-shibarium network ... how can this be fixed so I receive my Bone to my Ledger?
It is sent with this address 0x29D435ac03Cc0079A50ef287c04B97d5D88FD0F2 and it´s my Etherium address!
Here is the link to the transfer: https://www.shibariumscan.io/address/0x29D435ac03Cc0079A50ef287c04B97d5D88FD0F2

### Backend version

?

### Frontend version

?

### Elixir & Erlang/OTP versions

?

### Additional information

I sent BONE from Gate io to my ledger and choosed Bone-shibarium network to send and not Etherium network... I did submit the Etherium address ... My tokens are stuck in Bone-shibarium network ... how can this be fixed so I receive my Bone to my Ledger?
It is sent with this address 0x29D435ac03Cc0079A50ef287c04B97d5D88FD0F2 and it´s my Etherium address!
Here is the link to the transfer: https://www.shibariumscan.io/address/0x29D435ac03Cc0079A50ef287c04B97d5D88FD0F2

**Comment by vbaranov** [comment]
This chat is for Blockscout-related questions. Your question is out of scope, where the Blockscout team can help.

**Comment by 1natin** [comment]
That was NOT helpful... on shibariumscan it says: Submit an issue ... Well, I submitted an issue  ... So what is the link to shibariumscan HELPDESK  ?   Thanks
