### ISSUE TITLE
0xaA88518157736f39DD41EDfa26C7BE1deeaB5531

### ISSUE THREAD

**Issue by badrsantos** [blockscout/blockscout#10088]
### Description

Bonjour l'équipe d'assistance, je suis confronté à un problème. J'ai envoyé l'argent mais il n'est pas arrivé et le processus est terminé. Pouvez-vous m'aider ? Je pense que l'argent est en attente.
![Screenshot_2024-05-19-10-07-15-663_com gateio gateio](https://github.com/blockscout/blockscout/assets/134295423/701503f1-a737-45a7-b5f7-d6367a596dce)

### Type of the installation

Docker-compose

### Type of the JSON RPC archive node

0x152e2D2b11bb9C69FF9197bfAf89D68C4456FBF1

### Type of the chain

0x7130d2a12b9bcbfae4f2634d864a1ee1ce3ead9c

### Link to the page

https://scan.bevm.io/

### Steps to reproduce

![Screenshot_2024-05-18-11-59-49-067_com binance dev](https://github.com/blockscout/blockscout/assets/134295423/5d251ae0-4a0f-4107-8d7f-d1cf885ffaa3)
![Screenshot_2024-05-18-11-59-56-282_com binance dev](https://github.com/blockscout/blockscout/assets/134295423/04d141fb-4270-4561-9fc8-e7d41f97da1b)
![Screenshot_2024-05-18-12-00-15-165_com binance dev](https://github.com/blockscout/blockscout/assets/134295423/4e993fe6-5d2c-49be-8980-9f7a6d5a303d)
![Screenshot_2024-05-18-12-17-08-898_com binance dev](https://github.com/blockscout/blockscout/assets/134295423/dd0a9ddb-b196-439e-8f20-9cd79155e437)
![Screenshot_2024-05-18-12-39-49-291_com binance dev](https://github.com/blockscout/blockscout/assets/134295423/ed2eb6fa-c07d-481a-8684-38226eb936f3)

### Backend version

v6.4.0-beta

### Elixir & Erlang/OTP versions

Block #995203

### Operating system

Android

### Additional information

**User Agent:** Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Mobile Safari/537.36

**Comment by vbaranov** [comment]
This chat is for Blockscout-related questions. Your question is out of scope, where the Blockscout team can help.
