### ISSUE TITLE
Besu private network warnings with bonsai storage

### ISSUE THREAD

**Issue by carlossrp** [blockscout/blockscout#10106]
### Description

We're trying to set up Blockscout 6.5.0 with a private Besu 24.3.3 network but we're facing hundreads of warning messages per second about bonsai back layer limits.

Error message: vert.x-worker-thread-11 | WARN  | BonsaiWorldStateProvider | Exceeded the limit of back layers that can be loaded (512)

Bonsai is default since Besu 24.3.0 (https://github.com/hyperledger/besu/releases/tag/24.3.0).

We found #9560, but it seems the fix is not working.

We find out Blockscout 6.3.0 incorporated #9560 (https://github.com/blockscout/blockscout/releases/tag/v6.3.0-beta), but we tried different combinations without success.

We first tried Blockscout 6.5.0. We noticed the error message, then we tried 6.3.0, 6.2.2, 6.1.0, 6.0.0 and 5.4.0 with no succes. We always droped blockscout database between downgrades. In our understanding, pre 6.3.0 releases shouldn't have problems because the pending transaction fetcher would be disabled, that's why we tested then, but oddly enough, the log messages still appears on log, like it's still enabled or it's other indexer that causes the error.

We're also using this two variables:

- ETHEREUM_JSONRPC_VARIANT: "besu"
- INDEXER_DISABLE_PENDING_TRANSACTIONS_FETCHER: "true"

On docker-compose.yml to try to enforce disabling the indexer but with no luck. We're able to "sh" into the running backend container and confirm that both variables are correctly set inside the container and on the runtime $PATH.

We waited a 6.5.0 deploy to complete the index proccess (no more "x% index blocks" message) but still have lots of warning bonsai messages on Besu log.

We have other networks running Besu 23.x with forest and Blockscout 5.4.0 for more than a year without any issues.

Can you please help us? Thanks!

### Type of the installation

Docker-compose

### Type of the JSON RPC archive node

Besu

### Type of the chain

L1

### Link to the page

private network

### Steps to reproduce

Set up Besu 24.3.3 private network
Set up Blockscout version 6.5.0 with docker-compose deployment to fetch Besu RPC node
bonsai warning messages start to flood Besu log

### Backend version

6.5.0

### Frontend version

1.30.1

### Elixir & Erlang/OTP versions

Elixir 1.14.5 (compiled with Erlang/OTP 24

### Operating system

linux

**Comment by vbaranov** [comment]
@carlossrp could you try [6.7.2](https://github.com/blockscout/blockscout/releases/tag/v6.7.2-beta)? It contains https://github.com/blockscout/blockscout/pull/10117, which might help your case.

**Comment by MASDXI** [comment]
> ### Description
> We're trying to set up Blockscout 6.5.0 with a private Besu 24.3.3 network but we're facing hundreads of warning messages per second about bonsai back layer limits.
> 
> Error message: vert.x-worker-thread-11 | WARN | BonsaiWorldStateProvider | Exceeded the limit of back layers that can be loaded (512)
> 
> Bonsai is default since Besu 24.3.0 (https://github.com/hyperledger/besu/releases/tag/24.3.0).
> 
> We found #9560, but it seems the fix is not working.
> 
> We find out Blockscout 6.3.0 incorporated #9560 (https://github.com/blockscout/blockscout/releases/tag/v6.3.0-beta), but we tried different combinations without success.
> 
> We first tried Blockscout 6.5.0. We noticed the error message, then we tried 6.3.0, 6.2.2, 6.1.0, 6.0.0 and 5.4.0 with no succes. We always droped blockscout database between downgrades. In our understanding, pre 6.3.0 releases shouldn't have problems because the pending transaction fetcher would be disabled, that's why we tested then, but oddly enough, the log messages still appears on log, like it's still enabled or it's other indexer that causes the error.
> 
> We're also using this two variables:
> 
> * ETHEREUM_JSONRPC_VARIANT: "besu"
> * INDEXER_DISABLE_PENDING_TRANSACTIONS_FETCHER: "true"
> 
> On docker-compose.yml to try to enforce disabling the indexer but with no luck. We're able to "sh" into the running backend container and confirm that both variables are correctly set inside the container and on the runtime $PATH.
> 
> We waited a 6.5.0 deploy to complete the index proccess (no more "x% index blocks" message) but still have lots of warning bonsai messages on Besu log.
> 
> We have other networks running Besu 23.x with forest and Blockscout 5.4.0 for more than a year without any issues.
> 
> Can you please help us? Thanks!
> 
> ### Type of the installation
> Docker-compose
> 
> ### Type of the JSON RPC archive node
> Besu
> 
> ### Type of the chain
> L1
> 
> ### Link to the page
> private network
> 
> ### Steps to reproduce
> Set up Besu 24.3.3 private network Set up Blockscout version 6.5.0 with docker-compose deployment to fetch Besu RPC node bonsai warning messages start to flood Besu log
> 
> ### Backend version
> 6.5.0
> 
> ### Frontend version
> 1.30.1
> 
> ### Elixir & Erlang/OTP versions
> Elixir 1.14.5 (compiled with Erlang/OTP 24
> 
> ### Operating system
> linux
> 
> ### Additional information
> _No response_

Can you provide the error log that would be helpful.

**Comment by carlossrp** [comment]
> @carlossrp could you try [6.7.2](https://github.com/blockscout/blockscout/releases/tag/v6.7.2-beta)? It contains #10117, which might help your case.

Hi @vbaranov, I'll try in one of our development envirnments. 
We froze Blockscout at 6.5.0 because we faced performance issues with 6.6.0. From time to time, even after being full synced with the network, Blockscout displayed the "x% blocks indexed" banner.
We didn't noticed this behaviour with 6.5.0 in 2 months, 3M+ blocks network.
As a workaround, we added an "archive" node to our network, using forest instead of bonsai.

**Comment by MASDXI** [comment]
> > Error message: vert.x-worker-thread-11 | WARN | BonsaiWorldStateProvider | Exceeded the limit of back layers that can be loaded (512)
> 
> Hi @MASDXI, which error you reffering to? Because the only error line that shows up (hundreads of thousands of time) on Besu log is the one provided, there's no error log from Blockscout side.
> 
> The other questions:
> 
> - curl pending transaction from the besu node the bonsai max limiter still occur or not. > It think I didn't get the idea, but the node had no pending transactions checking txpool_besuTransactions, txpool_besuPendingTransactions or txpool_besuStatistics. It's a healty node that works fine when blockscout is not connected to it.
> 
> - increasing more limit more than 512 still occur or not. > Still occurs, and at some point makes the node unstable. We reached something around 64k before the node becoming unstable, and the same error message showed up on Besu log, with the 64k value instead of the 512.
> 
> - is "TRACE" api enable? > Yes

For the error, I have seen some developer have issue when using QBFT with Bonsai storage. 
https://github.com/hyperledger/besu/issues/7153#issuecomment-2175422987 .

curl is to check the "txpool" enable and working correctly and focus on datastructure problems not the from the pending transaction call.

I found on discord channel that for the private network suggest to use forest rather than bonsai cause IBFT and QBFT not fully supported.

**Comment by MASDXI** [comment]
@vbaranov this issue can be closed. The root cause came from the besu client not from the blockscout.

**Comment by vbaranov** [comment]
@carlossrp could you confirm, that the issue resolved?

**Comment by vbaranov** [comment]
Closing due to no response from the author.
