### ISSUE TITLE
L2 Optimism Based, Lost Data On-Chain

### ISSUE THREAD

**Issue by avenbreaks** [blockscout/blockscout#10108]
### Description

Previously we encountered full Storage on the server hosting the blockscout explorer, and have an analysis of the data before it went down and after it was fixed. we use docker-compose 

`DOCKER_REPO = blockscout-optimism docker compose -f geth.yml up -d`

Old numbers before down:

```
Traction: Testnet Stats 

•Completed txns : 3.349M
•Total accounts : 9.1K
•Total blocks : 3.267M
•Total addresses : 125.769K
•Total tokens : 265
```

New numbers after fix it: 

```
•Completed txns : 5M
•Total accounts : 3.6K
•Total blocks : 4.8M
•Total addresses : 122K
•Total tokens : 105
```

Here is the difference, something is missing after we restarted explorer after increasing storage 

1. Total accounts
2. Total tokens
3. Total addresses

Logs backend : 
```
{"time":"2024-05-18T14:02:50.482Z","severity":"info","message":"Start handling L1 block range 5924359..5924608. Target range: 5870859..5928296.","metadata":{"fetcher":"optimism_output_roots"}}
{"time":"2024-05-18T14:02:50.491Z","severity":"info","message":"Finish handling L1 block range 5272175..5272424. Found 0 WithdrawalProven/WithdrawalFinalized event(s). Target range: 5210675..5928296. Progress: 8.60%","metadata":{"fetcher":"optimism_withdrawal_events"}}
{"time":"2024-05-18T14:02:50.491Z","severity":"info","message":"Finish handling L1 block range 5924359..5924608. Found 0 OutputProposed event(s). Target range: 5870859..5928296. Progress: 93.58%","metadata":{"fetcher":"optimism_output_roots"}}
{"time":"2024-05-18T14:02:50.491Z","severity":"info","message":"Start handling L1 block range 5272425..5272674. Target range: 5210675..5928296.","metadata":{"fetcher":"optimism_withdrawal_events"}}
{"time":"2024-05-18T14:02:50.491Z","severity":"info","message":"Start handling L1 block range 5924609..5924858. Target range: 5870859..5928296.","metadata":{"fetcher":"optimism_output_roots"}}
{"time":"2024-05-18T14:02:50.492Z","severity":"info","message":"tx/per day chart: num of transactions 43288","metadata":{}}
{"time":"2024-05-18T14:02:50.518Z","severity":"info","message":"Finish handling L1 block range 5924609..5924858. Found 0 OutputProposed event(s). Target range: 5870859..5928296. Progress: 94.01%","metadata":{"fetcher":"optimism_output_roots"}}
{"time":"2024-05-18T14:02:50.518Z","severity":"info","message":"Start handling L1 block range 5924859..5925108. Target range: 5870859..5928296.","metadata":{"fetcher":"optimism_output_roots"}}
{"time":"2024-05-18T14:02:50.520Z","severity":"info","message":"Finish handling L1 block range 5272425..5272674. Found 0 WithdrawalProven/WithdrawalFinalized event(s). Target range: 5210675..5928296. Progress: 8.64%","metadata":{"fetcher":"optimism_withdrawal_events"}}
```

Logs frontend: 
```
Starting Next.js application
  ▲ Next.js 14.2.3
  - Local:        http://1194921d7az2:3000
  - Network:      http://x.xx.0.xx:3000

 ✓ Starting...
Unable to initialize instrumentation for lambda. Cannot identify lambda handler or task root. { taskRoot: undefined, handlerDef: undefined }
 ✓ Ready in 926ms
Failed extracting version /app/node_modules/@walletconnect/logger/node_modules/pino
Failed extracting version /app/node_modules/@walletconnect/logger/node_modules/pino
Failed extracting version /app/node_modules/@walletconnect/logger/node_modules/pino
Failed extracting version /app/node_modules/@walletconnect/logger/node_modules/pino
Failed extracting version /app/node_modules/@walletconnect/logger/node_modules/pino
```

### Type of the installation

Docker-compose

### Type of the JSON RPC archive node

Geth

### Type of the chain

L2

### Link to the page

https://onlyscan.info

### Steps to reproduce

`DOCKER_REPO = blockscout-optimism docker compose -f geth.yml up -d`

### Backend version

v6.4.0

### Elixir & Erlang/OTP versions

-

### Operating system

Linux

### Additional information

docker-compose.yml : `RELEASE_VERSION: 6.4.0`

But after restart explorer on UI Explorer we got new version : 

Backend: [v6.5.0-beta](https://github.com/blockscout/blockscout/tree/v6.5.0-beta)
Frontend: [v1.30.1](https://github.com/blockscout/frontend/tree/v1.30.1)

**Comment by avenbreaks** [comment]
@vbaranov @GimluCom

**Comment by vbaranov** [comment]
@avenbreaks there is a delay in counter cache values re-calculation, but finally, the values should be equal for the same chain. If you can find the concrete address/token/transaction which is missing in the new version and exists in the old one please let us know.

**Comment by avenbreaks** [comment]
> @avenbreaks there is a delay in counter cache values re-calculation, but finally, the values should be equal for the same chain. If you can find the concrete address/token/transaction which is missing in the new version and exists in the old one please let us know.

What is a suitable cache value for a heavy transaction in an optimism-based L2 network?

**Comment by vbaranov** [comment]
> > @avenbreaks there is a delay in counter cache values re-calculation, but finally, the values should be equal for the same chain. If you can find the concrete address/token/transaction which is missing in the new version and exists in the old one please let us know.
> 
> What is a suitable cache value for a heavy transaction in an optimism-based L2 network?

It depends, on the number of items in the DB. But the general rule would be:
the value of cache invalidation period should be greater than execution time of query like: `SELECT COUNT(*) FROM TRANSACTIONS` (or similar for other object types, which have counters for).

For the reference:
- Total Transactions cache is managed by `CACHE_TXS_COUNT_PERIOD` variable with default value `2 hrs`.
- Total Blocks cache is managed by `CACHE_BLOCK_COUNT_PERIOD` variable with default value `2 hrs`.
- Total Accounts cache is managed by `CACHE_ADDRESS_WITH_BALANCES_UPDATE_INTERVAL` variable with default value `30 min`.
