### ISSUE TITLE
Add the `implementation_address` field to all relevant resource responses for proxy contracts.

### ISSUE THREAD

**Issue by tom2drum** [blockscout/blockscout#10100]
The API currently returns information about the implementation address of the proxy contract only in the `/address/{hash}` resource response.

For example, the response from https://eth.blockscout.com/api/v2/addresses/0x3154Cf16ccdb4C6d922629664174b904d80F2C35 includes this information.

To display the implementation contract information in the UI, we need the same information in all relevant list resource responses, such as `/address/{hash}/transactions`, `/address/{hash}/token-transfers`, `/transactions` and so on.

The current response from https://eth.blockscout.com/api/v2/addresses/0x3154Cf16ccdb4C6d922629664174b904d80F2C35/transactions does not include this information.

[Mock-up](https://www.figma.com/design/4In0X8UADoZaTfZ34HaZ3K/Blockscout_2.0?m=dev&node-id=20288%3A28861)
[Frontend task](https://github.com/blockscout/frontend/issues/1798)

**Comment by vbaranov** [comment]
Resolved by https://github.com/blockscout/blockscout/pull/10113
