### ISSUE TITLE
0xfaef1188d40da419d3b41a8b14daf9217e7dd15ee287505b0870af02e3aea4c1

### ISSUE THREAD

**Issue by abdouferraq** [blockscout/blockscout#10119]
### Description

لقد ارسلت عملة wbtc شبكة BEVM بالغلط الى wbtc شبكة ERC20
المرجوا حل المشكل اريد إسترجاع المبلغ
![Screenshot_2024-05-25-04-26-51-783_com binance dev](https://github.com/blockscout/blockscout/assets/170783134/59d29844-c1ee-4282-a27a-db3933e1f4b8)
![Screenshot_2024-05-25-04-27-00-530_com blockabc cctip](https://github.com/blockscout/blockscout/assets/170783134/56f4dd1e-7f7d-46d2-864b-04bc21e44c53)

### Type of the installation

Manual from the source code

### Type of the JSON RPC archive node

من محفظة Wbtc bevm الى محفظة wbtc ERC20 

### Type of the chain

L1

### Link to the page

https://scan-mainnet.bevm.io/tx/0xfaef1188d40da419d3b41a8b14daf9217e7dd15ee287505b0870af02e3aea4c1?tab=index

### Steps to reproduce

محفظة المرسل عملة wbtc شبكة bevm
0xeb9191509067a182Db54ad1b46d185150e8fe598
محفظة المرسل اليه عملة wbtc شبكة Ethereum (ERC20)
0xCbe74C0A6f831aE15892d94fB581143c64834765
![Screenshot_2024-05-25-04-44-14-976_com binance dev](https://github.com/blockscout/blockscout/assets/170783134/a6eaddad-2b99-41ee-ae79-3f4023c424d6)
![Screenshot_2024-05-25-04-44-08-134_com binance dev](https://github.com/blockscout/blockscout/assets/170783134/d09d99b2-915f-4724-85b8-0e790a5b50ab)
![Screenshot_2024-05-25-04-43-33-663_com binance dev](https://github.com/blockscout/blockscout/assets/170783134/cec187cc-d2b2-4a00-aa53-ffe2c5ef275e)

### Backend version

v6.4.0-beta

### Frontend version

لا اعلم

### Elixir & Erlang/OTP versions

لا اعلم

### Operating system

Android

### Additional information

**User Agent:** Mozilla/5.0 (Linux; Android 12; M2007J20CG Build/SKQ1.211019.001; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/124.0.6367.123 Mobile Safari/537.36 BNC/2.83.5 BMP/4.27.0 NetType/WIFI  Language/ar

**Comment by vbaranov** [comment]
This chat is for Blockscout-related questions. Your question is out of scope, where the Blockscout team can help.
