### ISSUE TITLE
I CAN'T SEND MY FUND FROM MY WALLET 

### ISSUE THREAD

**Issue by Emonthe112** [blockscout/blockscout#10118]
### Description

My wallet address is :- 0xBf9cAe0f0Aee95989e3295db7E82E2C34C77A639 I can't send my fund from my wallet 

### Type of the installation

Docker-compose

### Type of the JSON RPC archive node

geth

### Link to the page

https://www.ftnscan.com/address/0xBf9cAe0f0Aee95989e3295db7E82E2C34C77A639

### Steps to reproduce

I send my fund normally but it's also pending for 2 hour + and yet not transfered 

### Backend version

3.0

### Elixir & Erlang/OTP versions

Elixir 1.14.5 Erlang/OTP 25

### Operating system

unix linux

### Additional information

The issue happened at Bahamut Blockscout instance

**Comment by vbaranov** [comment]
This chat is for Blockscout-related questions. Your question is out of scope, where the Blockscout team can help.
