### ISSUE TITLE
Dok

### ISSUE THREAD

**Issue by Kukmana** [blockscout/blockscout#10126]
### Description

Forke

### Type of the installation

Manual from the source code

### Type of the JSON RPC archive node

Erigon

### Type of the chain

L1

### Link to the page

https://fit-betelgeuse.explorer.mainnet.skalenodes.com/token/0xb5D8201e187Fd68aF4B54C7662124D93506dE505?tab=contract

### Steps to reproduce

Setelah ck

### Backend version

V6.2

### Frontend version

v1.28.1+caf6a837

### Elixir & Erlang/OTP versions

Elixir

### Operating system

Linux

### Additional information

**User Agent:** Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/116.0.0.0 Mobile Safari/537.36

**Comment by vbaranov** [comment]
This chat is for Blockscout-related questions. Your question is out of scope, where the Blockscout team can help.

**Comment by Kukmana** [comment]
No thanks
