### ISSUE TITLE
stats API return gas_prices null

### ISSUE THREAD

**Issue by walterzhu29** [blockscout/blockscout#10124]
### Description

Started blocksount with geth.yml and stats api returns null:

```
"gas_prices": {
        "average": null,
        "fast": null,
        "slow": null
},
```
Can someone help what might be the root cause?
Transactions and other stats looks good.

### Type of the installation

Docker-compose

### Type of the JSON RPC archive node

Geth

### Type of the chain

L2

### Link to the page

https://optimism.blockscout.com/gas-tracker

### Backend version

v6.5.0-beta-59-g88394ff6fb

### Frontend version

v1.30.1+0eca4f3a

### Elixir & Erlang/OTP versions

Elixir 1.14.5

### Additional information

**User Agent:** Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36

**Comment by sl1depengwyn** [comment]
Please check if there any errors in logs?

**Comment by walterzhu29** [comment]
From the source code, I'm able to target where the problem at:
```
new_acc = fee_query |> Repo.all(timeout: :infinity) |> merge_gas_prices(acc, from_block_actual)
gas_prices = new_acc |> process_fee_data_from_db()
```
and `new_acc` is nil which makes the entire `gas_prices` becomes nil tuple by the function
```
defp process_fee_data_from_db([]) do
    %{
      slow: nil,
      average: nil,
      fast: nil
    }
  end
  ```
  However, still not able to figure our why  `new_acc` return null list, looks like it's just a simple block number filter

**Comment by axonvm** [comment]
Turn out found my gas_price are 0, been filtered by queries
```
fee_query =
      from(
        block in Block,
        left_join: transaction in assoc(block, :transactions),
        where: block.consensus == true,
        where: is_nil(transaction.gas_price) or transaction.gas_price > ^0,
```

**Comment by walterzhu29** [comment]
Turn out my gas_price are all 0, been filtered by query:
```
fee_query =
      from(
        block in Block,
        left_join: transaction in assoc(block, :transactions),
        where: block.consensus == true,
        where: is_nil(transaction.gas_price) or transaction.gas_price > ^0,
```

**Comment by sl1depengwyn** [comment]
We do filter zero gas price transactions because such transactions are usually some service transactions, so they should not affect gas price prediction for the user

**Comment by walterzhu29** [comment]
Make a lot sense, thanks for your confirmation!
