### ISSUE TITLE
Error during JSON encoding in API call due to invalid byte sequence

### ISSUE THREAD

**Issue by xux1217** [blockscout/blockscout#10122]
### Description

I encountered an error while making a GET request to the /api/v2/transactions endpoint. It seems like there is an issue with JSON encoding when handling certain byte sequences. Below is the detailed error log:

> {"time":"2024-05-26T06:54:36.172Z","severity":"error","message":"#PID<0.19409.1> running BlockScoutWeb.Endpoint (connection #PID<0.19408.1>, stream id 1) terminated\nServer: 43.199.24.212:80 (http)\nRequest: GET /api/v2/transactions?filter=validated\n** (exit) an exception was raised:\n    ** (Jason.EncodeError) invalid byte 0xB9 in <<185, 254, 207, 163, 204, 236, 204, 195, 201, 189, 188, 185>>\n        (jason 1.4.1) lib/jason.ex:213: Jason.encode_to_iodata!/2\n        (phoenix 1.5.14) lib/phoenix/controller.ex:777: Phoenix.Controller.render_and_send/4\n        (block_scout_web 6.5.0) lib/block_scout_web/controllers/api/v2/transaction_controller.ex:1: BlockScoutWeb.API.V2.TransactionController.action/2\n        (block_scout_web 6.5.0) lib/block_scout_web/controllers/api/v2/transaction_controller.ex:1: BlockScoutWeb.API.V2.TransactionController.phoenix_controller_pipeline/2\n        (phoenix 1.5.14) lib/phoenix/router.ex:352: Phoenix.Router.__call__/2\n        (phoenix 1.5.14) lib/phoenix/router/route.ex:41: Phoenix.Router.Route.call/2\n        (phoenix 1.5.14) lib/phoenix/router.ex:352: Phoenix.Router.__call__/2\n        (block_scout_web 6.5.0) lib/block_scout_web/endpoint.ex:1: BlockScoutWeb.Endpoint.plug_builder_call/2","metadata":{"error":{"initial_call":null,"reason":"** (Jason.EncodeError) invalid byte 0xB9 in <<185, 254, 207, 163, 204, 236, 204, 195, 201, 189, 188, 185>>\n    (jason 1.4.1) lib/jason.ex:213: Jason.encode_to_iodata!/2\n    (phoenix 1.5.14) lib/phoenix/controller.ex:777: Phoenix.Controller.render_and_send/4\n    (block_scout_web 6.5.0) lib/block_scout_web/controllers/api/v2/transaction_controller.ex:1: BlockScoutWeb.API.V2.TransactionController.action/2\n    (block_scout_web 6.5.0) lib/block_scout_web/controllers/api/v2/transaction_controller.ex:1: BlockScoutWeb.API.V2.TransactionController.phoenix_controller_pipeline/2\n    (phoenix 1.5.14) lib/phoenix/router.ex:352: Phoenix.Router.__call__/2\n    (phoenix 1.5.14) lib/phoenix/router/route.ex:41: Phoenix.Router.Route.call/2\n    (phoenix 1.5.14) lib/phoenix/router.ex:352: Phoenix.Router.__call__/2\n    (block_scout_web 6.5.0) lib/block_scout_web/endpoint.ex:1: BlockScoutWeb.Endpoint.plug_builder_call/2\n"}}}

The content `invalid byte 0xB9 in <<185, 254, 207, 163, 204, 236, 204, 195, 201, 189, 188, 185>>\n ` is GBK encoding.

Could you please look into this issue? It seems related to how binary data is being encoded to JSON, potentially needing a handling mechanism for non-UTF-8 byte sequences or a validation to prevent such errors.

### Type of the installation

Docker-compose

### Type of the JSON RPC archive node

private testnet

### Backend version

docker image: blockscout/blockscout:6.5.0 

### Frontend version

docker image: v1.29.2

### Elixir & Erlang/OTP versions

same with docker image

### Operating system

linux

**Comment by vbaranov** [comment]
@xux1217 which chain are you indexing? and what JSON RPC client && version do you use? Please could you also try updating to 6.6.0 release?

**Comment by xux1217** [comment]
Sorry for the late reply.

I use the geth client, version is: ethereum/client-go:alltools-v1.13.15

I tested it in my private chain, I would upgrade to 6.6.0 and test it, please wait some times.

> @xux1217 which chain are you indexing? and what JSON RPC client && version do you use? Please could you also try updating to 6.6.0 release?

**Comment by vbaranov** [comment]
@xux1217 was the update passed fine? I'd even recommend updating to [6.7.2](https://github.com/blockscout/blockscout/releases/tag/v6.7.2-beta).

**Comment by vbaranov** [comment]
Closing due to no response from the author.
