### ISSUE TITLE
incomplete node count across all blockscout explorers

### ISSUE THREAD

**Issue by Phoenix1969** [blockscout/blockscout#10120]
### Description

Every network I check using blockscout has an incomplete node count. ETH, ETC, ETCPOW, Larissa... 
we need accurate metrics please!

### Type of the installation

Manual from the source code

### Type of the JSON RPC archive node

all

### Type of the chain

both l1 and l2

### Link to the page

https://scan.larissa.network/stats

### Steps to reproduce

check ANY blockscout explorer and compare to actual metrics

### Backend version

v6.5.0-beta

### Frontend version

v1.29.1+3944283d

### Elixir & Erlang/OTP versions

unknown

### Operating system

all

### Additional information

**User Agent:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36

**Comment by vbaranov** [comment]
I am closing the issue due to no response from the author.
