### ISSUE TITLE
Invalid arguments; neither block nor hash specified

### ISSUE THREAD

**Issue by SurenFTN** [blockscout/blockscout#10125]
### Description

In indexer's logs I am having this error.Meanwhile on archive node which is on the same host as indexer manually fetching specific block with number or with hash has normal response 
```
2024-05-27T04:52:14.980 application=indexer fetcher=coin_balance_catchup count=140 error_count=140 [error] failed to fetch: 0xa75b0578446510f4e168d8e5a32cf6e885c454f3@2839619: (-32000) invalid arguments; neither block nor hash specified
0x5f4950b0aa7cf9baff7cf1f1d046177a7997ee25@2839621: (-32000) invalid arguments; neither block nor hash specified
0x4497a4d97e41f1ffebc1da4c1fee89270e7d23a6@2839621: (-32000) invalid arguments; neither block nor hash specified
0x534c3232376d2a10cb7cdfeb8380615db3b7a171@2839621: (-32000) invalid arguments; neither block nor hash specified
0x868e6def75e3b2079c55b9cb07c15d2a6bf2dcd4@2839617: (-32000) invalid arguments; neither block nor hash specified
0x1300339298f955a74f8ca909af2f8fb299c168d2@2839617: (-32000) invalid arguments; neither block nor hash specified

```

### Type of the installation

Manual from the source code

### Type of the JSON RPC archive node

Geth

### Type of the chain

L1

### Link to the page

https://www.ftnscan.com/

### Backend version

v6.5.0

### Elixir & Erlang/OTP versions

elixir 1.14.5-otp-25 erlang 25.3.2.8

### Operating system

Linux

**Comment by Qwerty5Uiop** [comment]
Hi @SurenFTN! Could you please try to execute this request and check if there is the same error?
```
curl \
  -H "Content-Type:application/json;charset=utf-8" \
  -d "{
      \"jsonrpc\": \"2.0\",
      \"id\": 1,
      \"method\": \"eth_getBalance\",
      \"params\": [\"0xa75b0578446510f4e168d8e5a32cf6e885c454f3\", \"0x2B5443\"]
  }" \
<your node>
```

Also, do you use custom backend version or is it original master?

**Comment by SurenFTN** [comment]
@Qwerty5Uiop  I have already mentioned in my comment that the check manually has already done and the response with GETH is ok

**Comment by Qwerty5Uiop** [comment]
@SurenFTN Yes, you mentioned that manually fetching specific block with number or with hash has normal response. But this error comes from the balance request, so could you please show the response for this particular request?

**Comment by SurenFTN** [comment]
@Qwerty5Uiop  Double check the issue is Smart Contract related thank you
