### ISSUE TITLE
Please cancel any transaction coming from this wallet address it has been hacked it's mine Please 🙏 thanks for ur help 0x6cb73CAAaf1462facC9fbBAb44c0cda257dbb68A

### ISSUE THREAD

**Issue by Bettergoscar** [blockscout/blockscout#10137]
### Description

Please cancel any transaction coming from this wallet address it has been hacked it's mine Please 🙏 thanks for ur help 0x6cb73CAAaf1462facC9fbBAb44c0cda257dbb68A

### Type of the installation

Docker-compose

### Type of the JSON RPC archive node

OpenEx

### Type of the chain

0x6cb73CAAaf1462facC9fbBAb44c0cda257dbb68A

### Link to the page

https://scan.long.openex.network/contract-verification

### Steps to reproduce

Please cancel any transaction coming from this wallet address it has been hacked it's mine Please 🙏 thanks for ur help0x6cb73CAAaf1462facC9fbBAb44c0cda257dbb68A

### Backend version

v6.6.0-beta

### Frontend version

v1.30.1+0eca4f3a

### Elixir & Erlang/OTP versions

Elixir 863278

### Operating system

Linus/macOS/window

### Additional information

**User Agent:** Mozilla/5.0 (Linux; Android 12; SM-G973F Build/SP1A.210812.016; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/124.0.6367.179 Mobile Safari/537.36

**Comment by vbaranov** [comment]
This chat is for Blockscout-related questions. Your question is out of scope, where the Blockscout team can help.
