### ISSUE TITLE
bridge amount not received

### ISSUE THREAD

**Issue by talha493919** [blockscout/blockscout#10139]
### Description

i bridge amount from this chain to bnb. it show that it will take 7 day to receive. but now 3 week

### Type of the installation

Docker-compose

### Type of the JSON RPC archive node

xterio

### Link to the page

https://bnb.xterscan.io/tx/0x986ab93904c90a4e7a472a17c09b12a31d6d645cc8f38155f1c1902e9c0bed88

### Steps to reproduce

check transection and send my bnb

### Backend version

v6.5.0-beta

### Elixir & Erlang/OTP versions

v6.5.0-beta

### Operating system

windows

### Additional information

**User Agent:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36 OPR/110.0.0.0

**Comment by sl1depengwyn** [comment]
This repo is for Blockscout-related questions. Blockscout is an open source blockchain explorer. Thus, your question is out of scope, where the Blockscout team can help, you better contact the chain support directly.
