### ISSUE TITLE
Unnamed ERC-1155 tokens

### ISSUE THREAD

**Issue by vbaranov** [blockscout/blockscout#10145]
Often, ERC-1155 tokens don't provide `name` getter since it is not a part of the standard. However, each token ID contains the' name' attribute in `tokenURI` getter. Thus, while Blockscout fetches metadata from tokenURI, it could update the token's name from it.

As an additional option, we could try getting token's name from [contractURI](https://eips.ethereum.org/EIPS/eip-7572) property - some smart-contracts use it.

**Comment by pop-yev** [comment]
+1 feature request to this. For ERC1155 tokens to include the name of the token alongside the collection, since ERC-1155s typically have multiple tokens defined. 🙏 
Ex: 5 of Wood , 30 of Cotton, etc.
