### ISSUE TITLE
Minting

### ISSUE THREAD

**Issue by rahmanto75** [blockscout/blockscout#10148]
### Description

I have minted Vigor NFT on my metamask wallet but still showing not minted on my Vigor application.

### Type of the installation

Docker-compose

### Type of the JSON RPC archive node

geth

### Backend version

v5.3.1-beta.+commit.c472f7bb

### Elixir & Erlang/OTP versions

Elixir 1.14.5 Erlang/OTP 24

### Operating system

unix linux

### Additional information

The issue happened at Vigor Chain Mainnet Blockscout instance

**Comment by vbaranov** [comment]
The Blockscout team doesn't manage this instance of Blockscout. It would be best if you asked the question to the team, which supports this chain.
