### ISSUE TITLE
Token transfers shows Something went wrong. Try refreshing the page or come back later 

### ISSUE THREAD

**Issue by JOY** [blockscout/blockscout#10158]
### Description

Token transfers tab always shows Something went wrong. Try refreshing the page or come back later 
![image](https://github.com/blockscout/blockscout/assets/5027251/f74a490f-2673-4d63-9241-b5455e1a8048)

### Type of the installation

Docker-compose

### Type of the JSON RPC archive node

Geth

### Type of the chain

L1

### Link to the page

https://doscan.io/

### Steps to reproduce

Open any token page, ex: https://doscan.io/address/0x8291F1C6aEf2acBC58F3fe11C9e4EC0d3D4aE904?tab=token_transfers.
Notice that it shows  Something went wrong. Try refreshing the page or come back later 

### Backend version

v6.5.0

### Frontend version

v1.30.0-alpha

### Elixir & Erlang/OTP versions

Elixir 1.16.1

### Operating system

Linux

**Comment by fedor-ivn** [comment]
Hi,

It may have been a temporary problem. When I checked, it worked for me.

The address you provided shows no token transfers:

![image](https://github.com/blockscout/blockscout/assets/34605001/862bd378-39a1-4b2d-9949-f70495ae4aa3)

I also found [another address](https://doscan.io/address/0x9a0938d2D2B873Ce40a831569aC0B65a0Cd70Ee7?tab=token_transfers) with some token transfers:

![image](https://github.com/blockscout/blockscout/assets/34605001/2562cece-a62d-4e44-a3ba-ebde7b8444e3)

Please try again and if the issue does not persist, kindly close the issue.

Thank you!

**Comment by JOY** [comment]
> Hi,
> 
> It may have been a temporary problem. When I checked, it worked for me.
> 
> The address you provided shows no token transfers:
> 
> ![image](https://private-user-images.githubusercontent.com/34605001/335874354-862bd378-39a1-4b2d-9949-f70495ae4aa3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc0NzU3NDUsIm5iZiI6MTcxNzQ3NTQ0NSwicGF0aCI6Ii8zNDYwNTAwMS8zMzU4NzQzNTQtODYyYmQzNzgtMzlhMS00YjJkLTk5NDktZjcwNDk1YWU0YWEzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjA0VDA0MzA0NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk5MGI1OTE2YjM4Y2VjZGVhODJkZGU0MjJiZGJjNGFlYjM2OWQyZGZlYjBkMDM2OTQxMmVkOTE5ZmQ1NjU1OGYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.f93SK3vHEkw7KGzsFL6YPJ3fJZ4CIwDk6w3Mj1bKgXQ)
> 
> I also found [another address](https://doscan.io/address/0x9a0938d2D2B873Ce40a831569aC0B65a0Cd70Ee7?tab=token_transfers) with some token transfers:
> 
> ![image](https://private-user-images.githubusercontent.com/34605001/335874490-2562cece-a62d-4e44-a3ba-ebde7b8444e3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc0NzU3NDUsIm5iZiI6MTcxNzQ3NTQ0NSwicGF0aCI6Ii8zNDYwNTAwMS8zMzU4NzQ0OTAtMjU2MmNlY2UtYTYyZC00ZTQ0LWEzYmEtZWJkZTdiODQ0NGUzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjA0VDA0MzA0NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWEwYTBiYzFlZmUxN2RlNTU5ZGQ1MTU4N2FmZTY5YmExYzRmODg0ZjY4M2MzY2YzNmUxZmIwY2RiNmMyNjI0ZDkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.5UqtcEd5YcpqwmzdIodEO5K9_206qSONKg7hwtqZHtg)
> 
> Please try again and if the issue does not persist, kindly close the issue.
> 
> Thank you!

We had to revert to v6.4.0-beta to solve the issue as you can see.

**Comment by vbaranov** [comment]
@JOY could you please update to the latest release [6.7.2](https://github.com/blockscout/blockscout/releases/tag/v6.7.2-beta) and let us know if the issue resolved there?

**Comment by JOY** [comment]
> @JOY could you please update to the latest release [6.7.2](https://github.com/blockscout/blockscout/releases/tag/v6.7.2-beta) and let us know if the issue resolved there?

Cannot re-produce on v6.7.2-beta
https://staging.doscan.io/address/0x5b8671aea1b84F697427eabB204ffE4BB342333F?tab=token_transfers
