### ISSUE TITLE
Purchased Sepolia's NFT using Arbitrum One

### ISSUE THREAD

**Issue by xixihahax** [blockscout/blockscout#10165]
### Description

I used the wrong link and lost 20u. The NFT transaction failed, but my u did not come back
![775e8ba9158eca8761a3532b3cb5067](https://github.com/blockscout/blockscout/assets/171365601/e659f83d-1aad-42f7-8688-fffe788066f6)
![016118a92976de3e2061733997eeee2](https://github.com/blockscout/blockscout/assets/171365601/d4b900ac-79af-41d8-ae20-b8e9389ea9d8)
![1a34f2fdc2c314ccf4a5246874acd96](https://github.com/blockscout/blockscout/assets/171365601/85588926-42ae-4a89-bdda-5f1bec3ada8e)
![1bb09e9563e2a38e4605d73486bd719](https://github.com/blockscout/blockscout/assets/171365601/d6cf1b0a-6d6a-441d-b5e6-7dabbc022561)
![bd8cbb995d7f25b309f85df4b4a60c7](https://github.com/blockscout/blockscout/assets/171365601/576ca9d9-35cd-4a3d-941c-72796f06e674)
![bf9543714ee36b92b75db3a7eec002c](https://github.com/blockscout/blockscout/assets/171365601/4bdcef6f-bad1-4a27-b6ec-b60ca054a116)

Arbitrum One:0x13114b95aBd4E8D49277a55785eaa6C356F56936
Sepolia:0x13114b95aBd4E8D49277a55785eaa6C356F56936

I hope you can help me handle it. Thank you very much

### Type of the installation

Docker-compose

### Type of the JSON RPC archive node

Transaction issues

### Backend version

Transaction issues

### Elixir & Erlang/OTP versions

Transaction issues

**Comment by vbaranov** [comment]
This chat is for Blockscout-related questions. Your question is out of scope, where the Blockscout team can help.
