### ISSUE TITLE
Today VPN server address give me please 

### ISSUE THREAD

**Issue by mdsohagparis** [blockscout/blockscout#10162]
### Description

VPN server 

### Type of the installation

Docker

### Type of the JSON RPC archive node

geth

### Backend version

3.0

### Elixir & Erlang/OTP versions

Elixir 1.14.5 Erlang/OTP 25

### Operating system

unix linux

### Additional information

The issue happened at Bahamut Blockscout instance

**Comment by vbaranov** [comment]
This chat is for Blockscout-related questions. Your question is out of scope, where the Blockscout team can help.
