### ISSUE TITLE
Facing Transaction issue

### ISSUE THREAD

**Issue by shamoggy** [blockscout/blockscout#10167]
### Description

Hey!!! Hope you're doing well..
I Withdrawal 0.00027848 amount of ETH from my Binance Account to my Phantom Wallet via Manta Network on 2024-05-31 23:25. The issue I'm facing right now is, Binance shows that the Withdrawal have been successfully proceed, but i haven't receive yet. I double-checked my phantom wallet address if I put wrong but it's correct, and I also track my Txid, it also shows the transaction is sucessfully completed. but the same issue I haven't receive in my phantom wallet.
![Screenshot 2024-06-01 132051](https://github.com/blockscout/blockscout/assets/171413276/91cbd16d-26a6-47f8-96c9-0bf1b5931ba5)
![Screenshot 2024-06-01 132606](https://github.com/blockscout/blockscout/assets/171413276/a9a73e00-9bad-4ddb-888d-dd6f47322282)

### Type of the installation

Docker-compose

### Type of the JSON RPC archive node

EIP-1559

### Link to the page

https://pacific-explorer.manta.network/address/0xE4F6B1967184D4C4ed866f175154388fCA0231A2

### Backend version

1.1.3

### Elixir & Erlang/OTP versions

OTP25

### Operating system

LG-R490

### Additional information

**User Agent:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0.0.0 Safari/537.36

**Comment by fedor-ivn** [comment]
Hello! This repository is specifically dedicated to Blockscout, an open-source blockchain explorer.

Unfortunately, your question appears to be outside the scope of Blockscout. We recommend reaching out directly to the support team of the specific blockchain and/or exchange you're inquiring about for more accurate assistance.
