### ISSUE TITLE
Blockscout for Testnet Geth Network

### ISSUE THREAD

**Issue by yohanelly95** [blockscout/blockscout#10163]
### Description

I am running a private geth network which seems to be running fine. While running the geth.yml docker-compose build the `backend` service is syncing to slowly! And the front end does not show any information since the APIs do not respond at all. 

`backend`:
```
{"time":"2024-05-31T09:49:46.712Z","severity":"info","message":"Checking if index needs to catch up in 2500ms.","metadata":{"fetcher":"block_catchup"}}
{"time":"2024-05-31T09:49:49.366Z","severity":"info","message":"Index had to catch up.","metadata":{"fetcher":"block_catchup","first_block_number":47854,"last_block_number":32012,"missing_block_count":5,"shrunk":false}}
{"time":"2024-05-31T09:49:49.366Z","severity":"info","message":"Checking if index needs to catch up in 2500ms.","metadata":{"fetcher":"block_catchup"}}
{"time":"2024-05-31T09:49:49.541Z","severity":"info","message":"Start sanitizing of empty blocks. Batch size is 100","metadata":{"fetcher":"empty_blocks_to_refetch"}}
{"time":"2024-05-31T09:49:50.446Z","severity":"info","message":"Batch of empty blocks is sanitized","metadata":{"fetcher":"empty_blocks_to_refetch"}}
{"time":"2024-05-31T09:49:52.006Z","severity":"info","message":"Index had to catch up.","metadata":{"fetcher":"block_catchup","first_block_number":47853,"last_block_number":32011,"missing_block_count":5,"shrunk":false}}
{"time":"2024-05-31T09:49:52.006Z","severity":"info","message":"Checking if index needs to catch up in 2500ms.","metadata":{"fetcher":"block_catchup"}}
{"time":"2024-05-31T09:49:54.639Z","severity":"info","message":"Index had to catch up.","metadata":{"fetcher":"block_catchup","first_block_number":47852,"last_block_number":32010,"missing_block_count":5,"shrunk":false}}
{"time":"2024-05-31T09:49:54.639Z","severity":"info","message":"Checking if index needs to catch up in 2500ms.","metadata":{"fetcher":"block_catchup"}}
{"time":"2024-05-31T09:49:55.448Z","severity":"info","message":"Start sanitizing of empty blocks. Batch size is 100","metadata":{"fetcher":"empty_blocks_to_refetch"}}
{"time":"2024-05-31T09:49:56.125Z","severity":"info","message":"Batch of empty blocks is sanitized","metadata":{"fetcher":"empty_blocks_to_refetch"}}
{"time":"2024-05-31T09:49:57.261Z","severity":"info","message":"Index had to catch up.","metadata":{"fetcher":"block_catchup","first_block_number":47851,"last_block_number":32009,"missing_block_count":5,"shrunk":false}}
```
Is this the expected logs? 
How do I increase the speed of the sync?

### Type of the installation

Docker-compose

### Type of the JSON RPC archive node

Geth

### Type of the chain

L1

### Steps to reproduce

docker-compose -f geth.yml up -d

### Backend version

latest

### Frontend version

latest

### Elixir & Erlang/OTP versions

Elixir 1.14.5 (compiled with Erlang/OTP 25)

### Operating system

macOS

**Comment by yohanelly95** [comment]
This could be because the node was not an archival node. I have switched to an archival node now. 

Getting this error though, what does it mean?
```
{"time":"2024-06-03T05:47:09.608Z","severity":"error","message":"failed to fetch: 0x123463a4b065722e99115d6c222f267d9cabb524@29848: (-32000) header not found\n0x123463a4b065722e99115d6c222f267d9cabb524@45690: (-32000) header not found\n0x123463a4b065722e99115d6c222f267d9cabb524@45584: (-32000) header not found\n","metadata":{"count":3,"error_count":3,"fetcher":"coin_balance_catchup"}}
```

**Comment by sl1depengwyn** [comment]
Probably simply switching to an archive node is not enough. This error indicates that som data is not found on the node, so you probably need to resync your json rpc node

**Comment by yohanelly95** [comment]
> Probably simply switching to an archive node is not enough. This error indicates that som data is not found on the node, so you probably need to resync your json rpc node

I see, this is geth node related. Will look into this and get back, thanks!

**Comment by yohanelly95** [comment]
@sl1depengwyn we have fixed the geth node and now the block explorer is working. But it always says that `X% Blocks Indexed – We're indexing this chain right now. Some of the counts may be inaccurate.`. But the Last blocks are the latest blocks of the chain. What is causing the lag here? How do I improve this

**Comment by sl1depengwyn** [comment]
Try to decrease `CACHE_BLOCK_COUNT_PERIOD`
This way the alert would update more frequently

**Comment by vbaranov** [comment]
I am closing this issue for now. @yohanelly95 please let us know if you have further requests.
