### ISSUE TITLE
Contract verify failed on docker smart-contract-verifier

### ISSUE THREAD

**Issue by walterzhu29** [blockscout/blockscout#10180]
### Description

Hi, 

I'm getting trouble on verify my sepolia testnet contract 0x559e3182A7c72B450E341B72cdE7eFECB0F8545c

I am able to verify it on https://eth-sepolia.blockscout.com/address/0x559e3182A7c72B450E341B72cdE7eFECB0F8545c?tab=contract

But once I start the docker smart-contract-verifier (ports looks ok I'm able to check microservers healthy), I keep getting error:
```
backend           | {"time":"2024-06-03T05:01:54.450Z","severity":"error","message":"Smart-contract verification error: No contract could be verified with provided data","metadata":{}}
backend           | {"time":"2024-06-03T05:01:54.450Z","severity":"error","message":"Solidity smart-contract verification 0x604444968378333f9af10775545b093b7833b9b1 failed because of the error No contract could be verified with provided data","metadata":{}}
backend           | {"time":"2024-06-03T05:01:54.450Z","severity":"error","message":"Solidity smart-contract verification 0x604444968378333f9af10775545b093b7833b9b1 failed because of the error: #Ecto.Changeset<action: :insert, changes: %{address_hash: %Explorer.Chain.Hash{byte_count: 20, bytes: <<96, 68, 68, 150, 131, 120, 51, 63, 154, 241, 7, 117, 84, 91, 9, 59, 120, 51, 185, 177>>}, autodetect_constructor_args: false, compiler_version: \"v0.8.25+commit.b61c2a91\", contract_code_md5: \"8289abf476aba4b9ba0ab28e67cc8315\", contract_source_code: \"// SPDX-License-Identifier: GPL-3.0\\n\\npragma solidity >=0.8.24 <0.9.0;\\n\\ncontract GetNum2 {\\n\\n    /**\\n     * @dev Return value \\n     * @return value 2\\n     */\\n    function get() public pure returns (uint256){\\n        return 2;\\n    }\\n}\\n\\n\\n\", evm_version: \"default\", is_vyper_contract: false, license_type: :gnu_gpl_v3, optimization: false, partially_verified: false, verified_via_eth_bytecode_db: false, verified_via_sourcify: false, verified_via_verifier_alliance: false}, errors: [contract_source_code: {\"No contract could be verified with provided data\", []}], data: #Explorer.Chain.SmartContract<>, valid?: false>","metadata":{}}
```
Is there any setup I am missing to cause this error? Thanks lot!

### Type of the installation

Docker-compose

### Type of the JSON RPC archive node

Geth

### Type of the chain

L2

### Backend version

v6.5.0-beta-59-g88394ff6fb

### Elixir & Erlang/OTP versions

Elixir 1.14.5

**Comment by walterzhu29** [comment]
From the error msg looks like the backend won't be able to find which contract it has to verify with before send to sc_verifier, is there any config I set as wrong might cause this? 

I'm using my own L2 rpc node and chain id, from the explorer I can find the contract

**Comment by GimluCom** [comment]
Are you sure the solidity source code is identical to the contract you have deployed?

There is a discrepancy between the source code you are trying to verify with
```solidity
    function get() public pure returns (uint256){
        return 2;
    }
```
and the [contract on sepolia](https://eth-sepolia.blockscout.com/address/0x559e3182A7c72B450E341B72cdE7eFECB0F8545c?tab=contract).
```solidity
    function get() public pure returns (uint256){
        return 1;
    }
```

**Comment by axonvm** [comment]
Thanks for reply @GimluCom ! I deployed `return 1` contract on sepolia and able to verify it, also deployed both `return 1` and `return 2` contract on my L2 chain (that's why from the request log it's return 2). I'm pretty sure I was trying to verify the same contract.

I download the sc_verifier docker image and host on my machine, from the log I can see backend sent request to sc_verifier, from the sc_verifier docker logs I still got error msg:
`No contract could be verified with provided data` 

Any idea for what might be the root cause? I checked the backend db, contract is available in table.

**Comment by axonvm** [comment]
From the sc_verifier (https://github.com/blockscout/blockscout-rs/blob/main/smart-contract-verifier/smart-contract-verifier/src/solidity/multi_part.rs#L87)

No matching Contracts raised here, can I get some insights for what might cause this raise? So I can debug from my end.

**Comment by walterzhu29** [comment]
Thanks for reply @GimluCom ! I deployed return 1 contract on sepolia and able to verify it, also deployed both return 1 and return 2 contract on my L2 chain (that's why from the request log it's return 2). I'm pretty sure I was trying to verify the same contract.

I download the sc_verifier docker image and host on my machine, from the log I can see backend sent request to sc_verifier, from the sc_verifier docker logs I still got error msg:
No contract could be verified with provided data

Any idea for what might be the root cause? I checked the backend db, contract is available in table.

**Comment by walterzhu29** [comment]
From the sc_verifier (https://github.com/blockscout/blockscout-rs/blob/main/smart-contract-verifier/smart-contract-verifier/src/solidity/multi_part.rs#L87)

No matching Contracts raised here, can I get some insights for what might cause this raise? So I can debug from my end.

**Comment by walterzhu29** [comment]
One thing I've noticed is, even if I choose verification method as "Solidity (Flattened source code)"

The backend still sent request to endpoint: /api/v2/verifier/solidity/sources:verify-multi-part
Is that expected?
