### ISSUE TITLE
Need to force TokenID Metadata refresh

### ISSUE THREAD

**Issue by lcfr-eth** [blockscout/blockscout#10196]
### Description

Hello our team has launched an NFT project on DEGEN chain which is similar to ENS which generates metadata of a token after the transaction has landed. 

I'm noticing newly minted tokens aren't being assigned the metadata correctly on the block explorer even though metadata is set correctly on contract. 

I am thinking this is because blockscouts explorer's request to our tokens metadata may be racing against our metadata generation which hasn't completed by the time the metadata request is sent to the url. 

Similarly previously minted tokens which do have metadata - the metadata is not updated when the url is available and working. 

I tested this by redeploying an exact copy of the nft project setting the baseURI to the metadata URI for the previous contracts mints and verified that if i mint a previously minted name on the new contract that metadata exists for it works/displays the metadata upon mint/tx finalization on the explorer.

Both of these issues could be fixed with a force update metadata which will re-request the tokenIDs metadata URI.

### Type of the installation

Manual from the source code

### Type of the JSON RPC archive node

DEGEN CHAIN

### Type of the chain

L3

### Link to the page

https://explorer.degen.tips/

### Steps to reproduce

Create an ERC721 NFT project which creates metadata AFTER mint transaction.

Deploy to any blockscout chain - mint a token and observe the metadata is never updated.

### Backend version

DEGEN CHAIN

### Elixir & Erlang/OTP versions

DEGEN CHAIN

**Comment by sl1depengwyn** [comment]
This is probably solves your problem https://github.com/blockscout/blockscout/issues/9743, if it does please close the issue, otherwise elaborate how you'd solve this problem
