### ISSUE TITLE
USDB transfer to Boatport.

### ISSUE THREAD

**Issue by Mentor1880** [blockscout/blockscout#10206]
### Description

Hello sir,
I mistakenly returned the USDB worth 2000USDB and 3000USDB respectively back to USDB port, after swap.
my contract address USDB

0xe662d1c8A56806623A071B832DB1588A53C3571F

returned to boatport address: 
0x31be5a9860a5cf546bbc4e33515b3b8cbc0416a4c6c86ca4ecb5d4078c1202a0
Kindly help me check and return to my address.
Thank you with kind regards

### Type of the installation

Manual from the source code

### Type of the JSON RPC archive node

Erigon

### Type of the chain

0xA24C4F7C681C6E9E13092e19b43067a47946705e

### Link to the page

https://scan.come.boats/token/0x76e37f363287cCB0Bd511ED284D3924FaeD4a3a0

### Steps to reproduce

![Screenshot_20240606_164808_network openex hub](https://github.com/blockscout/blockscout/assets/166797152/6ca389ad-32df-4a32-a5df-99d241214e81)
![Screenshot_20240606_164753_network openex hub](https://github.com/blockscout/blockscout/assets/166797152/51e623a6-fba1-4e06-85e2-d4b8a587be02)

### Backend version

v6.6.0-beta

### Frontend version

v1.30.1+0eca4f3a

### Elixir & Erlang/OTP versions

android version 10

### Operating system

Android 

### Additional information

**User Agent:** Mozilla/5.0 (Linux; Android 10; CLT-L29 Build/HUAWEICLT-L29; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/125.0.6422.83 Mobile Safari/537.36

**Comment by vbaranov** [comment]
This chat is for Blockscout-related questions. Your question is out of scope, where the Blockscout team can help.
