### ISSUE TITLE
Verifier not working for Botanix

### ISSUE THREAD

**Issue by 0x2me** [blockscout/blockscout#10209]
### Description

When I click verify a contract I get an error message

"Something went wrong. Try refreshing the page or come back later."

### Type of the installation

Helm charts (k8s)

### Type of the JSON RPC archive node

Na

### Type of the chain

L2

### Link to the page

https://blockscout.botanixlabs.dev/contract-verification

### Steps to reproduce

Click through the UI

### Backend version

v6.6.0-beta

### Frontend version

v1.31.0+3061166c

### Elixir & Erlang/OTP versions

NA

### Operating system

MAc

### Additional information

**User Agent:** Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36

**Comment by GimluCom** [comment]
This Blockscout instance is not managed by the Blockscout team. Please contact Botanix about this issue.
