### ISSUE TITLE
Tokens burnt rather than being withdrawn 

### ISSUE THREAD

**Issue by naigeong** [blockscout/blockscout#10213]
### Description

I wanted to withdraw 0,11 WETH and I saw they disappeared because they were burnt. Nowhere I was advised I was sending them to a death wallet. Could you help me to recover them please ?

### Type of the installation

Docker-compose

### Type of the JSON RPC archive node

Geth 

### Type of the chain

L2

### Link to the page

https://www.shibariumscan.io/tx/0x4156b5bc8177b012ca3a661d0eedb5309f9fa56b961d7f45388f7263f2544f81

### Steps to reproduce

To withdraw from my Shibarium wallet to my ETH wallet doesn’t have to mean that I burn my tokens.

### Backend version

v6.6.0-beta

### Frontend version

v1.31.0+3061166c

### Elixir & Erlang/OTP versions

Elixir 1.14.5

### Operating system

macOS

### Additional information

**User Agent:** Mozilla/5.0 (iPhone; CPU iPhone OS 17_1_2 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Mobile/15E148

**Comment by vbaranov** [comment]
This chat is for Blockscout-related questions. Your question is out of scope, where the Blockscout team can help.
