### ISSUE TITLE
CSV export

### ISSUE THREAD

**Issue by iw4p** [blockscout/blockscout#10229]
### Description

Hello! I tried to export CSV for different wallet addresses but I faced with this error
![Screenshot 2024-06-11 at 8 52 35 AM](https://github.com/blockscout/blockscout/assets/30632761/4f83e17e-7d76-4a76-9255-a5a3d1c88bab)
I tried with small range dates and disabling ReCaptcha (modified both env and the code to just bypass the ReCaptcha checking, always TRUE).

### Type of the installation

Docker-compose

### Type of the JSON RPC archive node

Geth

### Backend version

v5.2.3-beta

### Elixir & Erlang/OTP versions

1.14.5-otp-25

**Comment by vbaranov** [comment]
@iw4p you're at the pretty old version of backend. Please migrate to [v6](https://github.com/blockscout/blockscout/releases).

**Comment by iw4p** [comment]
Also another version of BlockScout [v6.3.0-beta](https://github.com/blockscout/blockscout/releases/tag/v6.3.0-beta) is tested but no `Download CSV` button is shown.
![Screenshot 2024-06-11 at 11 25 20 AM](https://github.com/blockscout/blockscout/assets/30632761/2699cfb5-de64-429b-a2ea-f0fa440b0011)

**Comment by vbaranov** [comment]
You should configure CSV export on the new frontend via https://github.com/blockscout/frontend/blob/main/docs/ENVS.md#export-data-to-csv-file.
