### ISSUE TITLE
Cannot start v2 UI

### ISSUE THREAD

**Issue by 3ierratango** [blockscout/blockscout#10220]
### Description

Using the latest release/ master branch I am only able to run the old UI

Steps taken:
- Clone master branch
- cd docker-compose
- `sudo docker compose up -d`

Still get the old UI everytime

### Type of the installation

Docker-compose

### Type of the JSON RPC archive node

Substrate

### Type of the chain

L1

### Backend version

v6.6.0-beta

### Elixir & Erlang/OTP versions

0

### Operating system

Linux

### Additional information

Hosted at : https://ghostnet.dev.svcs.ferrumnetwork.io/

**Comment by 3ierratango** [comment]
its port 4000, no changes, using the nginx config in docs

**Comment by vbaranov** [comment]
The new UI is at 80 port.

**Comment by 3ierratango** [comment]
thankyou, that was indeed the issue
