### ISSUE TITLE
Remove `Indexer.Block.Catchup.Sequence`

### ISSUE THREAD

**Issue by fedor-ivn** [blockscout/blockscout#10237]
Since `Indexer.Block.Catchup.Sequence` module was deprecated and is currently kept as dead code, we should remove it.

The module is located here: https://github.com/blockscout/blockscout/blob/master/apps/indexer/lib/indexer/block/catchup/sequence.ex

**Comment by Shobhitsingh-2503** [comment]
@fedor-ivn Is this issue still open? I would love to contribute to this issue.

**Comment by fedor-ivn** [comment]
@Shobhitsingh-2503 sure!

**Comment by Khaliq88** [comment]
> @Shobhitsingh-2503 sure!

Yes
