### ISSUE TITLE
500 for fetching transactions

### ISSUE THREAD

**Issue by pangwa** [blockscout/blockscout#10232]
### Description

The api `api/v2/main-page/transactions` reports 500 on my server:

### Type of the installation

Docker-compose

### Type of the JSON RPC archive node

Geth

### Type of the chain

L1

### Steps to reproduce

visit the homepage and transactions not loaded, there is an error in the backend log.

> backend  | {"time":"2024-06-11T09:47:23.840Z","severity":"error","message":"#PID<0.6341.0> running BlockScoutWeb.Endpoint (connection #PID<0.6340.0>, stream id 1) terminated\nServer: mysite.com:80 (http)\nRequest: GET /api/v2/main-page/transactions\n** (exit) an exception was raised:\n    ** (RuntimeError) proxy_implementations is not loaded for address\n        (block_scout_web 6.6.0) lib/block_scout_web/views/api/v2/helper.ex:61: BlockScoutWeb.API.V2.Helper.address_with_info/2\n        (block_scout_web 6.6.0) lib/block_scout_web/views/api/v2/helper.ex:35: BlockScoutWeb.API.V2.Helper.address_with_info/5\n        (block_scout_web 6.6.0) lib/block_scout_web/views/api/v2/transaction_view.ex:422: BlockScoutWeb.API.V2.TransactionView.prepare_transaction/6\n        (elixir 1.14.5) lib/enum.ex:1658: Enum.\"-map/2-lists^map/1-0-\"/2\n        (elixir 1.14.5) lib/enum.ex:1658: Enum.\"-map/2-lists^map/1-0-\"/2\n        (phoenix 1.5.14) lib/phoenix/view.ex:472: Phoenix.View.render_to_iodata/3\n        (phoenix 1.5.14) lib/phoenix/controller.ex:777: Phoenix.Controller.render_and_send/4\n        (block_scout_web 6.6.0) lib/block_scout_web/controllers/api/v2/main_page_controller.ex:1: BlockScoutWeb.API.V2.MainPageController.action/2","metadata":{"error":{"initial_call":null,"reason":"** (RuntimeError) proxy_implementations is not loaded for address\n    (block_scout_web 6.6.0) lib/block_scout_web/views/api/v2/helper.ex:61: BlockScoutWeb.API.V2.Helper.address_with_info/2\n    (block_scout_web 6.6.0) lib/block_scout_web/views/api/v2/helper.ex:35: BlockScoutWeb.API.V2.Helper.address_with_info/5\n    (block_scout_web 6.6.0) lib/block_scout_web/views/api/v2/transaction_view.ex:422: BlockScoutWeb.API.V2.TransactionView.prepare_transaction/6\n    (elixir 1.14.5) lib/enum.ex:1658: Enum.\"-map/2-lists^map/1-0-\"/2\n    (elixir 1.14.5) lib/enum.ex:1658: Enum.\"-map/2-lists^map/1-0-\"/2\n    (phoenix 1.5.14) lib/phoenix/view.ex:472: Phoenix.View.render_to_iodata/3\n    (phoenix 1.5.14) lib/phoenix/controller.ex:777: Phoenix.Controller.render_and_send/4\n    (block_scout_web 6.6.0) lib/block_scout_web/controllers/api/v2/main_page_controller.ex:1: BlockScoutWeb.API.V2.MainPageController.action/2\n"}}}

### Backend version

d231ca62

### Frontend version

d231ca62

### Elixir & Erlang/OTP versions

default

### Operating system

Linux

**Comment by sl1depengwyn** [comment]
Should be fixed by https://github.com/blockscout/blockscout/pull/10225
