### ISSUE TITLE
Money was transfered and never received.

### ISSUE THREAD

**Issue by AshtonGuitard** [blockscout/blockscout#10242]
### Description

About a month ago I attempted to transfer about 0.077ETH, or ~250USD at the time from my Rainbow wallet to my Coinbase account. According to everyone the transfer was a success, but I never received the money in my Coinbase. 

### Type of the installation

Docker-compose

### Type of the JSON RPC archive node

Eth

### Link to the page

https://explorer.zora.energy/address/0x5308EAF04047482C69fFb1bf0E4A6F38295FCcab

### Backend version

v6.6.0-beta

### Frontend version

v1.31.0+3061166c

### Elixir & Erlang/OTP versions

N/A

### Additional information

**User Agent:** Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0.0.0 Mobile Safari/537.36

**Comment by vbaranov** [comment]
This chat is for Blockscout-related questions. Your question is out of scope, where the Blockscout team can help.
