### ISSUE TITLE
Shibuya blockchain contract verification Compiler not added 

### ISSUE THREAD

**Issue by zulfi125** [blockscout/blockscout#10248]
### Description

Shibuya blockchain contract verification Compiler not added pleae add
https://shibuya.blockscout.com/contract-verification

### Type of the installation

Manual from the source code

### Type of the JSON RPC archive node

https://shibuya.blockscout.com/contract-verification

### Type of the chain

L2

### Link to the page

https://shibuya.blockscout.com/contract-verification

### Backend version

v6.6.0-beta

### Frontend version

v1.31.0+3061166c

### Elixir & Erlang/OTP versions

compiler 

### Operating system

Windows

### Additional information

**User Agent:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36 OPR/110.0.0.0

**Comment by vbaranov** [comment]
At the moment smart-contract verification should be working fine.
