### ISSUE TITLE
Problem with loading 

### ISSUE THREAD

**Issue by Dreepe** [blockscout/blockscout#10253]
### Description

I cannot launch the game interface. 
![Screenshot_20240617_094319_Telegram](https://github.com/blockscout/blockscout/assets/173020794/fd62cfbd-63f5-4f1b-b827-a2c34e184d36)

### Type of the installation

Docker-compose

### Type of the JSON RPC archive node

geth

### Backend version

3.0

### Elixir & Erlang/OTP versions

Elixir 1.14.5 Erlang/OTP 25

### Operating system

unix linux

### Additional information

The issue happened at Bahamut Blockscout instance

**Comment by vbaranov** [comment]
This chat is for Blockscout-related questions. Your question is out of scope, where the Blockscout team can help.
