### ISSUE TITLE
I swapped 900k $enjoy but any ethereum was  added to my wallet

### ISSUE THREAD

**Issue by isaac1370** [blockscout/blockscout#10250]
### Description

Wallet Address: 0x1051C0928D21b3645A2D1484F664e225bAA87267
Txn Hash: 0x150ff939d40f01e3ff1fd408075236cfdb5f9a0a054fe18fc1b59545f8028cda
Source Chain: zora
Destination Chain: zora

### Type of the installation

Docker-compose

### Type of the JSON RPC archive node

1

### Type of the chain

l2

### Link to the page

https://explorer.zora.energy/tx/0x48a39c4bhttps://explorer.zora.energy/tx/0x150ff939d40f01e3ff1fd408075236cfdb5f9a0a054fe18fc1b59545f8028cda31af42fc3611f471e4e03755ac470e0cbf010ac86fc2e61e492822c7

### Backend version

1

### Frontend version

v1.31.0+3061166c

### Elixir & Erlang/OTP versions

1

**Comment by vbaranov** [comment]
This chat is for Blockscout-related questions. Your question is out of scope, where the Blockscout team can help.
