### ISSUE TITLE
Successful Transfer but now showing on my Wallet

### ISSUE THREAD

**Issue by JayLawww** [blockscout/blockscout#10278]
### Description

I transferred a USDC Token to my Ronin Wallet last Jun 16 2024 11:10:24 AM (+08:00 UTC), and it show on transaction is success but the USDC toke still not showing on my Ronin Wallet.
![Transaction](https://github.com/blockscout/blockscout/assets/102605552/c38b41cf-aa18-46c3-ab43-25174cea02ac)

### Type of the installation

Docker-compose

### Type of the JSON RPC archive node

Immutable

### Type of the chain

L1

### Link to the page

https://explorer.immutable.com/address/0xE73125AB2d66A3A7b049b45f3ee59d95D06e772e?tab=token_transfers

### Steps to reproduce

I transferred a USDC Token to my Ronin Wallet last Jun 16 2024 11:10:24 AM (+08:00 UTC), and it show on transaction is success but the USDC toke still not showing on my Ronin Wallet.
![Transaction](https://github.com/blockscout/blockscout/assets/102605552/c38b41cf-aa18-46c3-ab43-25174cea02ac)

### Backend version

v6.6.0-beta

### Frontend version

v1.31.0+3061166c

### Elixir & Erlang/OTP versions

USDC Token

### Operating system

Windows

### Additional information

Chrome/125.0.0.0

**Comment by sl1depengwyn** [comment]
This repo is for Blockscout-related questions. Blockscout is an open source blockchain explorer. Thus, your question is out of scope, where the Blockscout team can help, you better contact the chain support directly.
