### ISSUE TITLE
Error trying to add linea testnet to metamask 

### ISSUE THREAD

**Issue by GustavoRSSilva** [blockscout/blockscout#10271]
### Description

Hi everyone, I am trying to explore the linea test network and trying to add the network directly to metamask, I get the following error `Expected an array with at least one valid string HTTPS url 'rpcUrls', Received:\n`

The config should be missing some information.

More information:

`{
    "code": -32602,
    "message": "Expected an array with at least one valid string HTTPS url 'rpcUrls', Received:\n",
    "stack": "{\n  \"code\": -32602,\n  \"message\": \"Expected an array with at least one valid string HTTPS url 'rpcUrls', Received:\\n\",\n  \"stack\": \"Error: Expected an array with at least one valid string HTTPS url 'rpcUrls', Received:\\n\\n    at new i (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-3.js:7:272625)\\n    at a (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-3.js:7:275565)\\n    at Object.invalidParams (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-3.js:7:276072)\\n    at implementation (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background-5.js:1:211604)\\n    at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background-5.js:1:209170\\n    at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background-4.js:3:61732\\n    at new Promise (<anonymous>)\\n    at o._runMiddleware (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background-4.js:3:61389)\\n    at o._runAllMiddleware (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background-4.js:3:61295)\\n    at async o._processRequest (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background-4.js:3:61076)\\n    at async o._handle (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background-4.js:3:60917)\"\n}\n  at new i (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-3.js:7:272625)\n  at a (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-3.js:7:275565)\n  at Object.invalidParams (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-3.js:7:276072)\n  at implementation (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background-5.js:1:211604)\n  at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background-5.js:1:209170\n  at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background-4.js:3:61732\n  at new Promise (<anonymous>)\n  at o._runMiddleware (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background-4.js:3:61389)\n  at o._runAllMiddleware (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background-4.js:3:61295)\n  at async o._processRequest (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background-4.js:3:61076)\n  at async o._handle (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background-4.js:3:60917)"
}`

Screenshot:
![Screenshot 2024-06-18 at 09 40 01](https://github.com/blockscout/blockscout/assets/8384988/62e470d9-35bb-4b5a-8c1d-357ca113bd5b)

### Type of the installation

Docker-compose

### Type of the JSON RPC archive node

geth

### Type of the chain

L2

### Link to the page

https://explorer.goerli.linea.build/

### Steps to reproduce

Go to _https://explorer.goerli.linea.build/_
Scroll to the footer
Click on the button _Add Linea Testnet_

### Backend version

v6.2.2-beta

### Elixir & Erlang/OTP versions

Elixir 1.14.5 Erlang/OTP 24

### Operating system

unix linux

### Additional information

The issue happened at Linea Testnet Blockscout instance

**Comment by vbaranov** [comment]
The Blockscout team doesn't manage this instance of Blockscout. It would be best if you asked the question to the team, which supports this chain.
