### ISSUE TITLE
Transaction Page take long time to load

### ISSUE THREAD

**Issue by BlockgenStudio** [blockscout/blockscout#10286]
### Description

Hi

we deployed the blockscout block explorer for one of our private appchain network through the manual deployment based on
https://docs.blockscout.com/for-developers/deployment/manual-deployment-guide 6 month back

the transaction page seems taking longer and longer time to load (30s)
http://supernettestnet.explorer.arianee.com/tx/0xe846c3b9a0f15ab8c86d06ceb3b2f123bb9e32cb900bcbde80a0a4adecdf6e43

is there any way we can improve this?

### Type of the installation

Manual from the source code

### Type of the JSON RPC archive node

Polgyon Edge

### Type of the chain

L2

### Link to the page

http://supernettestnet.explorer.arianee.com/tx/0xe846c3b9a0f15ab8c86d06ceb3b2f123bb9e32cb900bcbde80a0a4adecdf6e43

### Backend version

v6.2

### Frontend version

v1.26.0-alpha

### Elixir & Erlang/OTP versions

1.14.5

### Operating system

linux

**Comment by vbaranov** [comment]
@BlockgenStudio Currently, your front end is running in developer mode. Instead of `yarn dev` launch it with `yarn start`. This will enable production mode.

**Comment by BlockgenStudio** [comment]
ok thanks let me try!

**Comment by vbaranov** [comment]
I am closing this. Please let me know, if suggested re-configuration didn't help.
