### ISSUE TITLE
Did not receive money from the transaction

### ISSUE THREAD

**Issue by denys021** [blockscout/blockscout#10293]
### Description

I have a problem with my transaction. The money was not credited to the wallet after the withdrawal attempt. Here is the transaction hash 0xe59c9238a7ce483381e7995ba1bf7949a72e7a8ec3f703c93266658213fbdeec

### Type of the installation

Docker-compose

### Type of the JSON RPC archive node

Ancient8

### Type of the chain

L2

### Link to the page

https://scan.ancient8.gg/tx/0xe59c9238a7ce483381e7995ba1bf7949a72e7a8ec3f703c93266658213fbdeec

### Backend version

v6.5.0-beta.+commit.819702fb

### Elixir & Erlang/OTP versions

OTP25

### Operating system

Windows 

### Additional information

**User Agent:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36

**Comment by sl1depengwyn** [comment]
This repo is for Blockscout-related questions. Blockscout is an open source blockchain explorer. Thus, your question is out of scope, where the Blockscout team can help, you better contact the chain support directly.
