### ISSUE TITLE
Shahrozshahzad

### ISSUE THREAD

**Issue by Shahrozshahzad** [blockscout/blockscout#10304]
### Description

Shahroz

### Type of the installation

Docker-compose

### Type of the JSON RPC archive node

geth

### Backend version

3.0

### Elixir & Erlang/OTP versions

Elixir 1.14.5 Erlang/OTP 25

### Operating system

unix linux

### Additional information

The issue happened at Bahamut Blockscout instance

**Comment by GimluCom** [comment]
Please clarify exactly what the issue is. Alternatively close this issue if it has been resolved.
