### ISSUE TITLE
My transferred usdt was not entered to my recipient wallet 

### ISSUE THREAD

**Issue by makk2001** [blockscout/blockscout#10306]
### Description

I send usdt from my oex wallet to binance and okx wallet but the token 

was not received to my wallet.

### Type of the installation

Docker-compose

### Type of the JSON RPC archive node

Ethereum and polygon 

### Link to the page

https://scan.long.openex.network/address/0xb13b987c1D7B4E30636B4A9e1F9D81a058ba42a8

### Steps to reproduce

1 enter to oex wallet 
2 click in send 
3 Ok entered my recipient wallet address 
4 I have confirmed the transition 

### Backend version

v6.6.0-beta

### Frontend version

v1.30.1+0eca4f3a

### Elixir & Erlang/OTP versions

Beta

### Operating system

Android phone os 11

### Additional information

**User Agent:** Mozilla/5.0 (Linux; Android 11; TECNO KG7h Build/RP1A.200720.011; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/125.0.6422.165 Mobile Safari/537.36

**Comment by GimluCom** [comment]
Blockscout is an open-source explorer that allows you to view transactions and blockchain data. However, Blockscout does not have control over transactions and thus your question is out of scope.

Please contact your exchange or chain about your issue.
