### ISSUE TITLE
Bug in bridge

### ISSUE THREAD

**Issue by Bogreksbp** [blockscout/blockscout#10305]
### Description

Found some problem when doing bridge. I still have 8 HYB, i try to bridge 2 and 4 HYB. but its failed. I think its a bug. Please repair it

### Type of the installation

Manual from the source code

### Type of the JSON RPC archive node

Geth

### Type of the chain

L2

### Link to the page

https://explorer.buildonhybrid.com/

### Steps to reproduce

Found some problem when doing bridge. I still have 8 HYB, i try to bridge 2 and 4 HYB. but its failed. I think its a bug. Please repair it

### Backend version

v6.6.0

### Frontend version

3.2.0+79e63e39

### Elixir & Erlang/OTP versions

Elixir

### Operating system

Windows

### Additional information

**User Agent:** Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Mobile Safari/537.36

**Comment by GimluCom** [comment]
This repo is for Blockscout related issues, thus your question is out of scrope.
Please contact your bridge's team directly.
