### ISSUE TITLE
My 138 islm coin transfer to unknown address by mistakes need to recover it again

### ISSUE THREAD

**Issue by Mohammadkhan0** [blockscout/blockscout#10310]
### Description

[
    {
        "action": {
            "callType": "call",
            "from": "0xca7683d256ccd802fbbf54ecde0ac88a2a4cfe98",
            "gas": "0x2DF0",
            "input": "0x",
            "to": "0x5eafefaa56b21535ad1b49360b9060d2ccf1ff2b",
            "value": "0x77FDA690B138A0000"
        },
        "result": {
            "gasUsed": "0x0",
            "output": "0x"
        },
        "subtraces": 0,
        "traceAddress": [],
        "type": "call"
    }
]

### Type of the installation

Docker-compose

### Type of the JSON RPC archive node

Haqq Network

### Type of the chain

Blockchain

### Link to the page

https://explorer.haqq.network/tx/0xA35364E77129DEE6061258670DBFE6BA6AB7957BD5560E2DF9F33D7F89AA3E34?tab=index

### Steps to reproduce

[
    {
        "action": {
            "callType": "call",
            "from": "0xca7683d256ccd802fbbf54ecde0ac88a2a4cfe98",
            "gas": "0x2DF0",
            "input": "0x",
            "to": "0x5eafefaa56b21535ad1b49360b9060d2ccf1ff2b",
            "value": "0x77FDA690B138A0000"
        },
        "result": {
            "gasUsed": "0x0",
            "output": "0x"
        },
        "subtraces": 0,
        "traceAddress": [],
        "type": "call"
    }
]

### Backend version

v6.3.0-beta

### Frontend version

v1.27.0+5a63649f

### Elixir & Erlang/OTP versions

1.14.5

### Operating system

Linux

### Additional information

**User Agent:** Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Mobile Safari/537.36

**Comment by GimluCom** [comment]
Blockscout is an open-source explorer that allows you to view transactions and blockchain data. However, Blockscout does not have control over transactions and thus your question is out of scope.

If you have questions about a specific chain, please contact the chain's team directly.
