### ISSUE TITLE
update documentation for Arb Blockscout managment

### ISSUE THREAD

**Issue by InoMurko** [blockscout/blockscout#10329]
### Description

https://docs.blockscout.com/for-developers/information-and-settings/env-variables/backend-envs-chain-specific#arbitrum-rollup-management

says version TBD -> it's in release 6.7.0 onwards

### Type of the installation

Docker-compose

### Type of the JSON RPC archive node

/

### Type of the chain

l2

### Link to the page

/

### Steps to reproduce

docs

### Backend version

6.7.0

### Frontend version

/

### Elixir & Erlang/OTP versions

1.14

### Operating system

linux

**Comment by vbaranov** [comment]
Thank you. Documentation updated.
