### ISSUE TITLE
Arb Blockscout 6.7.0

### ISSUE THREAD

**Issue by InoMurko** [blockscout/blockscout#10328]
### Description

```
{"time":"2024-06-27T11:22:20.762Z","severity":"error","message":"#PID<0.9107.0> running BlockScoutWeb.Endpoint (connection #PID<0.9106.0>, stream id 1) terminated\nServer: hybrid-testnet.explorer.caldera.xyz:80 (http)\nRequest: GET /api/v2/transactions/0x1ffe8e5a93f65ff1f5c134205aa0c63da747b79880f26ffe61e57dda5fe3dc99\n** (exit) an exception was raised:\n    ** (FunctionClauseError) no function clause matching in Decimal.decimal/1\n        (decimal 2.1.1) lib/decimal.ex:1910: Decimal.decimal(nil)\n        (decimal 2.1.1) lib/decimal.ex:302: Decimal.sub/2\n        (block_scout_web 6.7.0) lib/block_scout_web/views/api/v2/arbitrum_view.ex:396: BlockScoutWeb.API.V2.ArbitrumView.extend_with_transaction_info/2\n        (block_scout_web 6.7.0) lib/block_scout_web/views/api/v2/arbitrum_view.ex:161: BlockScoutWeb.API.V2.ArbitrumView.extend_transaction_json_response/2\n        (phoenix 1.5.14) lib/phoenix/view.ex:472: Phoenix.View.render_to_iodata/3\n        (phoenix 1.5.14) lib/phoenix/controller.ex:777: Phoenix.Controller.render_and_send/4\n        (block_scout_web 6.7.0) lib/block_scout_web/controllers/api/v2/transaction_controller.ex:1: BlockScoutWeb.API.V2.TransactionController.action/2\n        (block_scout_web 6.7.0) lib/block_scout_web/controllers/api/v2/transaction_controller.ex:1: BlockScoutWeb.API.V2.TransactionController.phoenix_controller_pipeline/2","metadata":{"error":{"initial_call":null,"reason":"** (FunctionClauseError) no function clause matching in Decimal.decimal/1\n    (decimal 2.1.1) lib/decimal.ex:1910: Decimal.decimal(nil)\n    (decimal 2.1.1) lib/decimal.ex:302: Decimal.sub/2\n    (block_scout_web 6.7.0) lib/block_scout_web/views/api/v2/arbitrum_view.ex:396: BlockScoutWeb.API.V2.ArbitrumView.extend_with_transaction_info/2\n    (block_scout_web 6.7.0) lib/block_scout_web/views/api/v2/arbitrum_view.ex:161: BlockScoutWeb.API.V2.ArbitrumView.extend_transaction_json_response/2\n    (phoenix 1.5.14) lib/phoenix/view.ex:472: Phoenix.View.render_to_iodata/3\n    (phoenix 1.5.14) lib/phoenix/controller.ex:777: Phoenix.Controller.render_and_send/4\n    (block_scout_web 6.7.0) lib/block_scout_web/controllers/api/v2/transaction_controller.ex:1: BlockScoutWeb.API.V2.TransactionController.action/2\n    (block_scout_web 6.7.0) lib/block_scout_web/controllers/api/v2/transaction_controller.ex:1: BlockScoutWeb.API.V2.TransactionController.phoenix_controller_pipeline/2\n"}}}
```

### Type of the installation

Docker-compose

### Type of the JSON RPC archive node

geth arb

### Type of the chain

l2

### Link to the page

hybrid-testnet.explorer.caldera.xyz

### Steps to reproduce

Sync the chain

### Backend version

v6.7.0

### Frontend version

latest

### Elixir & Erlang/OTP versions

1.14.5

### Operating system

Linux

### Additional information

/

**Comment by vbaranov** [comment]
@InoMurko would you please check with 6.7.1? Is the issue still replicated there?

**Comment by InoMurko** [comment]
> @InoMurko would you please check with 6.7.1? Is the issue still replicated there?

Yep!

{"time":"2024-07-03T10:24:30.189Z","severity":"error","message":"#PID<0.12416.257> running BlockScoutWeb.Endpoint (connection #PID<0.12270.257>, stream id 1) terminated\nServer: alienx.calderaexplorer.xyz:80 (http)\nRequest: GET /api/v2/transactions/0x393f326d494c0ef7be88224ecf024e07d22f1dbaa065b0c5aaf87e68ee8b4b2e\n** (exit) an exception was raised:\n    ** (FunctionClauseError) no function clause matching in Decimal.decimal/1\n        (decimal 2.1.1) lib/decimal.ex:1910: Decimal.decimal(nil)\n        (decimal 2.1.1) lib/decimal.ex:302: Decimal.sub/2\n        (block_scout_web 6.7.1) lib/block_scout_web/views/api/v2/arbitrum_view.ex:396: BlockScoutWeb.API.V2.ArbitrumView.extend_with_transaction_info/2\n        (block_scout_web 6.7.1) lib/block_scout_web/views/api/v2/arbitrum_view.ex:161: BlockScoutWeb.API.V2.ArbitrumView.extend_transaction_json_response/2\n        (phoenix 1.5.14) lib/phoenix/view.ex:472: Phoenix.View.render_to_iodata/3\n        (phoenix 1.5.14) lib/phoenix/controller.ex:777: Phoenix.Controller.render_and_send/4\n        (block_scout_web 6.7.1) lib/block_scout_web/controllers/api/v2/transaction_controller.ex:1: BlockScoutWeb.API.V2.TransactionController.action/2\n        (block_scout_web 6.7.1) lib/block_scout_web/controllers/api/v2/transaction_controller.ex:1: BlockScoutWeb.API.V2.TransactionController.phoenix_controller_pipeline/2","metadata":{"error":{"initial_call":null,"reason":"** (FunctionClauseError) no function clause matching in Decimal.decimal/1\n    (decimal 2.1.1) lib/decimal.ex:1910: Decimal.decimal(nil)\n    (decimal 2.1.1) lib/decimal.ex:302: Decimal.sub/2\n    (block_scout_web 6.7.1) lib/block_scout_web/views/api/v2/arbitrum_view.ex:396: BlockScoutWeb.API.V2.ArbitrumView.extend_with_transaction_info/2\n    (block_scout_web 6.7.1) lib/block_scout_web/views/api/v2/arbitrum_view.ex:161: BlockScoutWeb.API.V2.ArbitrumView.extend_transaction_json_response/2\n    (phoenix 1.5.14) lib/phoenix/view.ex:472: Phoenix.View.render_to_iodata/3\n    (phoenix 1.5.14) lib/phoenix/controller.ex:777: Phoenix.Controller.render_and_send/4\n    (block_scout_web 6.7.1) lib/block_scout_web/controllers/api/v2/transaction_controller.ex:1: BlockScoutWeb.API.V2.TransactionController.action/2\n    (block_scout_web 6.7.1) lib/block_scout_web/controllers/api/v2/transaction_controller.ex:1: BlockScoutWeb.API.V2.TransactionController.phoenix_controller_pipeline/2\n"}}}

**Comment by InoMurko** [comment]
Acually, no.

**Comment by InoMurko** [comment]
This fixed it: https://github.com/blockscout/blockscout/commit/a28a508c43cefa9fda5ec2ec66fa92a9d75d8cd9
