### ISSUE TITLE
Ftn fee could not received 

### ISSUE THREAD

**Issue by ahsanaliaa7885021** [blockscout/blockscout#10327]
### Description

Hello sir . Ftn fee could not received my account and ftn fee received in show to history but can't swapped token 
![Screenshot_20240627-114442](https://github.com/blockscout/blockscout/assets/150162490/7a3b0c1e-55d8-424d-868b-dbb86d09059a)
![Uploading Screenshot_20240627-114357.jpg…]()

### Type of the installation

Docker-compose

### Type of the JSON RPC archive node

geth

### Backend version

3.0

### Elixir & Erlang/OTP versions

Elixir 1.14.5 Erlang/OTP 25

### Operating system

unix linux

### Additional information

The issue happened at Bahamut Blockscout instance

**Comment by vbaranov** [comment]
This chat is for Blockscout-related questions. Your question is out of scope, where the Blockscout team can help.
