### ISSUE TITLE
I can't recieve hyb tst tokens in my wallet   0x4F9f013B0bA72355d67e5De3C75FA627dC3B8407

### ISSUE THREAD

**Issue by Hamadakebsa** [blockscout/blockscout#10336]
### Description

Hello admin wish you are ok 
could you help me please i can't recieve test HYB tokens in my wallet it show you are already reciece tokens but i didn't recieve anything and i use faucet once in 24H so if you can help me please i am so interested with project
thank you
<img width="347" alt="Screenshot 2024-06-28 144022" src="https://github.com/blockscout/blockscout/assets/124448548/e3d41cae-6cc9-4730-a89a-b14c2f932e47">

### Type of the installation

Docker-compose

### Type of the JSON RPC archive node

Erigon

### Type of the chain

L2

### Link to the page

https://explorer.buildonhybrid.com/address/0x4F9f013B0bA72355d67e5De3C75FA627dC3B8407

### Steps to reproduce

Hello admin wish you are ok 
could you help me please i can't recieve test HYB tokens in my wallet it show you are already reciece tokens but i didn't recieve anything and i use faucet once in 24H so if you can help me please i am so interested with project
thank you

### Backend version

v6.7.0

### Frontend version

3.2.0+79e63e39

### Elixir & Erlang/OTP versions

OTP versions

### Operating system

Windows

### Additional information

**User Agent:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36

**Comment by vbaranov** [comment]
This chat is for Blockscout-related questions. Your question is out of scope, where the Blockscout team can help.
