### ISSUE TITLE
HYBRID BRIDGE TO SEPOLIA

### ISSUE THREAD

**Issue by adcmp** [blockscout/blockscout#10332]
### Description

there any some problem when webridging HYB token to Sepolia Chain,we have succesfuly and mark success transaction but HYB token dont reflexing on Sepolia Chain. when we check transaction on caldera.bride it doesnt showing any transaction history.

### Type of the installation

Docker-compose

### Type of the JSON RPC archive node

Hybrid testnet

### Type of the chain

L2

### Link to the page

https://explorer.buildonhybrid.com/tx/0x69d07bc4a144e07b71ce807d5a18ba6c5e82da6b18a1ef001e8910f759b0b0ac?tab=token_transfers

### Steps to reproduce

we have to compact the contract address on sepolia or we can use omni system that no change any route of ca

### Backend version

v6.7.0

### Frontend version

3.2.0+79e63e39

### Elixir & Erlang/OTP versions

Elixir 1.14.5

### Operating system

windows

### Additional information

**User Agent:** Mozilla/5.0 (Linux; Android 10; M2006C3MG Build/QP1A.190711.020; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/126.0.6478.134 Mobile Safari/537.36 WebView MetaMaskMobile

**Comment by vbaranov** [comment]
This chat is for Blockscout-related questions. Your question is out of scope, where the Blockscout team can help.
