### ISSUE TITLE
Unapproved transaction

### ISSUE THREAD

**Issue by Mrrklassic** [blockscout/blockscout#10349]
### Description

I made a transaction for vote 3days ago and since then though it has been sign but it has not been approved yet.
![Screenshot_20240701_160753_com kiwibrowser browser](https://github.com/blockscout/blockscout/assets/140518825/0c5e8d85-a4ab-4e64-94ff-d6989e189b45)
![Screenshot_20240701_160644_com kiwibrowser browser](https://github.com/blockscout/blockscout/assets/140518825/8eb9b3a0-aacf-4f34-936e-a328e4397b37)
![Screenshot_20240701_160705_com kiwibrowser browser](https://github.com/blockscout/blockscout/assets/140518825/68f43b72-d236-4c2c-9eeb-8c7a54efac1c)
![Screenshot_20240701_164943_com kiwibrowser browser](https://github.com/blockscout/blockscout/assets/140518825/1c48ca70-6d54-4e59-8734-046c051bbd80)

### Type of the installation

Docker-compose

### Type of the JSON RPC archive node

Don't know

### Link to the page

https://scan-mainnet.bevm.io/tx/undefined

### Backend version

v6.7.0-beta

### Elixir & Erlang/OTP versions

Don't know

### Additional information

**User Agent:** Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Mobile Safari/537.36

**Comment by vbaranov** [comment]
This chat is for Blockscout-related questions. Your question is out of scope, where the Blockscout team can help.
