### ISSUE TITLE
I transferred the wrong viva coins to the mexc exchange address. If I haven't swapped them through the game, is there any way to get them back?

### ISSUE THREAD

**Issue by duatv01** [blockscout/blockscout#10341]
### Description

I transferred the wrong viva coins to the mexc exchange address. If I haven't swapped them through the game, is there any way to get them back?

### Type of the installation

Docker-compose

### Type of the JSON RPC archive node

geth

### Backend version

3.0

### Elixir & Erlang/OTP versions

Elixir 1.14.5 Erlang/OTP 25

### Operating system

unix linux

### Additional information

The issue happened at Ocean Blockscout instance

**Comment by vbaranov** [comment]
This chat is for Blockscout-related questions. Your question is out of scope, where the Blockscout team can help.
