### ISSUE TITLE
Incorrect page display

### ISSUE THREAD

**Issue by Paparazzi69** [blockscout/blockscout#10367]
### Description

https://scan.gmnetwork.ai/api-docs 

This page does not display correctly. I tried through 2 different browsers

### Type of the installation

Manual from the source code

### Type of the JSON RPC archive node

manually

### Link to the page

https://scan.gmnetwork.ai/api-docs

### Steps to reproduce

fix display)

### Backend version

v6.6.0-beta.+commit.5a0668c3

### Elixir & Erlang/OTP versions

i dont know what to answer there

### Operating system

Windows

### Additional information

**User Agent:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36

**Comment by vbaranov** [comment]
The Blockscout team doesn't manage this instance of Blockscout. It would be best if you asked the question to the team, which supports this chain.
