### ISSUE TITLE
Some blocks not processe in the pending_block_operations table.

### ISSUE THREAD

**Issue by hhhroot** [blockscout/blockscout#10361]
### Description

```SQL
SELECT *
FROM pending_block_operations;

-- result
|    block_hash    |    inserted_at    |    updated_at    |    block_number    |
|------------------|-------------------|------------------|--------------------|
| binary(32 bytes) | 2024-06-30 ...    | 2024-06-30 ...   | 4889153            |
| binary(32 bytes) | 2024-06-30 ...    | 2024-06-30 ...   | 4889120            |
```

```SQL
SELECT *
FROM internal_transactions
WHERE block_hash = (SELECT hash FROM blocks WHERE number=4889153) 
    OR block_hash = (SELECT hash FROM blocks WHERE number=4889120);

-- result
nothing
```

The rows is not processed even though today is 2024-07-02.

### Type of the installation

Docker-compose

### Type of the JSON RPC archive node

Geth

### Type of the chain

L2

### Backend version

v6.6.0

### Elixir & Erlang/OTP versions

hexpm/elixir:1.14.5-erlang24.2.2-alpine-3.18.2

### Operating system

Linux

**Comment by vbaranov** [comment]
@hhhroot are any errors in the logs in regard those blocks?

**Comment by vbaranov** [comment]
Closing due to no response from the author.
