### ISSUE TITLE
blouckscout chat starts no data

### ISSUE THREAD

**Issue by jhkangah** [blockscout/blockscout#10363]
### Description

BlockScout Chat&Stats Page No Data Stats Service Error Message
![df56cc8c-ebc1-4492-b655-f1f68f9a7bfe](https://github.com/blockscout/blockscout/assets/95907416/b29dd34f-b7e6-4757-b22d-bce4b3e98161)
![屏幕截图 2024-07-02 171607](https://github.com/blockscout/blockscout/assets/95907416/7953158f-9321-45bb-8680-ec230204cf48)

### Type of the installation

Docker-compose

### Type of the JSON RPC archive node

evmosd

### Backend version

v6.7.0

### Elixir & Erlang/OTP versions

1.14.4

### Operating system

linux

**Comment by jhkangah** [comment]
curl http://myip/api/v2/stats

{"average_block_time":5010.0,"coin_image":null,"coin_price":"3449.85","coin_price_change_percentage":0.3,"gas_price_updated_at":"2024-07-02T07:40:53.924789Z","gas_prices":{"average":null,"fast":null,"slow":null},"gas_prices_update_in":30000,"gas_used_today":null,"market_cap":"0","network_utilization_percentage":0.0,"secondary_coin_price":null,"static_gas_price":null,"total_addresses":"1","total_blocks":"124464","total_gas_used":"0","total_transactions":"0","transactions_today":"0","tvl":null}

**Comment by vbaranov** [comment]
@jhkangah did you make changes to Nginx config?

**Comment by vbaranov** [comment]
Closing due to no response from the author.
