### ISSUE TITLE
Besu private network with QBFT / (CaseClauseError) no case clause matching: []

### ISSUE THREAD

**Issue by lesaux** [blockscout/blockscout#10376]
### Description

backend logs for 6.7.2 spam the following message

```
** (CaseClauseError) no case clause matching: []
    (hackney 1.20.1) /app/deps/hackney/src/hackney_url.erl:248: :hackney_url.parse_netloc/2
    (hackney 1.20.1) /app/deps/hackney/src/hackney.erl:351: :hackney.request/5
    (httpoison 2.2.1) lib/httpoison/base.ex:888: HTTPoison.Base.request/6
    (ethereum_jsonrpc 6.7.2) lib/ethereum_jsonrpc/http/httpoison.ex:12: EthereumJSONRPC.HTTP.HTTPoison.json_rpc/4
    (ethereum_jsonrpc 6.7.2) lib/ethereum_jsonrpc/http.ex:73: EthereumJSONRPC.HTTP.chunked_json_rpc/3
    (ethereum_jsonrpc 6.7.2) lib/ethereum_jsonrpc/request_coordinator.ex:89: anonymous fn/4 in EthereumJSONRPC.RequestCoordinator.perform/4
    (ethereum_jsonrpc 6.7.2) lib/ethereum_jsonrpc/request_coordinator.ex:109: EthereumJSONRPC.RequestCoordinator.trace_request/2
    (ethereum_jsonrpc 6.7.2) lib/ethereum_jsonrpc.ex:454: EthereumJSONRPC.json_rpc/2
```

### Type of the installation

Helm charts (k8s)

### Type of the JSON RPC archive node

Besu

### Type of the chain

private qbft

### Steps to reproduce

launch a backend configure to point to a besu private archive node:
following vars were set:

    MIX_ENV: "prod"
    ECTO_USE_SSL: "false"
    ETHEREUM_JSONRPC_VARIANT: "besu"
    ETHEREUM_JSONRPC_HTTP_URL: "http://10.128.0.4:8545/"
    ETHEREUM_JSONRPC_WS_URL: "ws://10.128.0.4:8546/"
    ETHEREUM_JSONRPC_TRACE_URL: "http://10.128.0.4:8545/"

### Backend version

v6.7.2

### Elixir & Erlang/OTP versions

From published docker images

### Operating system

GKE

**Comment by vbaranov** [comment]
Most likely archive node JSON RPC or/and WS endpoints are unavailable at this IP from the explorer host.

**Comment by lesaux** [comment]
Indeed, I had some connectivity issues.
Does the Besu node I use necessarily needs to be an archive node - or can some just exist on the network?
features I enable on the API are:
`--rpc-ws-api=ADMIN,DEBUG,QBFT,ETH,NET,WEB3,TRACE,TXPOOL`
`--rpc-http-api=ADMIN,DEBUG,QBFT,ETH,NET,WEB3,TRACE,TXPOOL`
I am still seeing weird logs like the following:

```
Batch of empty blocks is sanitized
URL "http://besu-tx.besu-tx:8545" is unavailable, and no fallback is set
%{code: -32602, message: "Invalid params"}
URL "http://besu-tx.besu-tx:8545" is available now
%{code: -32602, message: "Invalid params"}
%{code: -32602, message: "Invalid params"}
%{code: -32602, message: "Invalid params"}
URL "http://besu-tx.besu-tx:8545" is unavailable, and no fallback is set
URL "http://besu-tx.besu-tx:8545" is available now
%{code: -32602, message: "Invalid params"}
%{code: -32602, message: "Invalid params"}
%{code: -32602, message: "Invalid params"}
```

**Comment by vbaranov** [comment]
> Indeed, I had some connectivity issues. Does the Besu node I use necessarily needs to be an archive node - or can some just exist on the network? features I enable on the API are: `--rpc-ws-api=ADMIN,DEBUG,QBFT,ETH,NET,WEB3,TRACE,TXPOOL` `--rpc-http-api=ADMIN,DEBUG,QBFT,ETH,NET,WEB3,TRACE,TXPOOL` I am still seeing weird logs like the following:
> 
> ```
> Batch of empty blocks is sanitized
> URL "http://besu-tx.besu-tx:8545" is unavailable, and no fallback is set
> %{code: -32602, message: "Invalid params"}
> URL "http://besu-tx.besu-tx:8545" is available now
> %{code: -32602, message: "Invalid params"}
> %{code: -32602, message: "Invalid params"}
> %{code: -32602, message: "Invalid params"}
> URL "http://besu-tx.besu-tx:8545" is unavailable, and no fallback is set
> URL "http://besu-tx.besu-tx:8545" is available now
> %{code: -32602, message: "Invalid params"}
> %{code: -32602, message: "Invalid params"}
> %{code: -32602, message: "Invalid params"}
> ```
> 
> Edit: seems that going back to v6.4.0 for the backend gets rid of errors, and indexing works again. Edit2: actually indexing seems to get stuck shortly after. each time I restart the backend, a few new blocks get added to "Total Blocks" in the ui, but when I leave it running it stalls.

@lesaux please update backend to the [latest release](https://github.com/blockscout/blockscout/releases), and such messages in the logs should stop to appear.

> Does the Besu node I use necessarily needs to be an archive node - or can some just exist on the network?

Archival state is required for fetching traces and balances at historical blocks. If the node is not archival you should disable corresponding fetchers:
```
ETHEREUM_JSONRPC_DISABLE_ARCHIVE_BALANCES=true
INDEXER_DISABLE_INTERNAL_TRANSACTIONS_FETCHER=true
```

I am closing the issue. Please let me know, if you still have questions.
