### ISSUE TITLE
Not able to finalize withdrawal on Caldera Bridge

### ISSUE THREAD

**Issue by agatha427** [blockscout/blockscout#10379]
### Description

I did a few transactions 12 hrs ago(5th July 2024) from hybrid-testnet to Sepolia. Now, I am trying to finalize withdrawal from "Transactions" tab but I am getting error **"Failed to send transaction".**
On chrome inspector console getting error - 
```
_app-fbbd2a776872a5eb.js:416 Uncaught (in promise) 
Error: Failed to fetch transaction data from L1 RPC
```

This is the transaction hash - 0x0a4cad361aa2c1044c04f1814dc83e4b6795785fb8a3c705523caf8cd6464562
This is my wallet address - 0x161859D2dcb6438754C382272EA6fD55a2c88428
Amounts and transaction timestamps are visible in screenshots. Please check and revert.

<img width="1440" alt="Screenshot 2024-07-05 at 2 23 55 PM" src="https://github.com/blockscout/blockscout/assets/174786311/2c5c1f73-2ca2-43c9-9450-f29321ff7754">
<img width="1189" alt="Screenshot 2024-07-05 at 2 02 10 PM" src="https://github.com/blockscout/blockscout/assets/174786311/66978fd1-20c5-4ee0-8f72-c3331164381a">

### Type of the installation

Docker-compose

### Type of the JSON RPC archive node

Ethereum

### Link to the page

https://hybrid-testnet.bridge.caldera.xyz/

### Steps to reproduce

1. Open https://hybrid-testnet.bridge.caldera.xyz/
2. Connected wallet
3. Did the transaction from hybrid-testnet to Sepolia
4. Now, go to transactions tab.
5. Click on finalize withdrawal from actions
6. Getting error and transaction is failed.
<img width="1189" alt="Screenshot 2024-07-05 at 2 02 10 PM" src="https://github.com/blockscout/blockscout/assets/174786311/e7fae065-9a45-46cf-af71-9e43c161fa69">
<img width="1440" alt="Screenshot 2024-07-05 at 2 23 55 PM" src="https://github.com/blockscout/blockscout/assets/174786311/77ac2bfc-0098-4dae-aafa-e8b93c29caa3">

### Backend version

v6.7.0

### Frontend version

3.2.0+79e63e39

### Elixir & Erlang/OTP versions

1.16

### Additional information

**User Agent:** Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36

**Comment by vbaranov** [comment]
This chat is for Blockscout-related questions. Your question is out of scope, where the Blockscout team can help.
