### ISSUE TITLE
API key limit bug

### ISSUE THREAD

**Issue by GimluCom** [blockscout/blockscout#10389]
### Description

The account based API key limit can be bypassed by making multiple "Add API key" requests in parallel.

### Type of the installation

Docker-compose

### Type of the JSON RPC archive node

Geth

### Backend version

v6.7.2

### Elixir & Erlang/OTP versions

Elixir 1.16.3

**Comment by Khaliq88** [comment]
[Welcome.pdf](https://github.com/user-attachments/files/16131620/Welcome.pdf)
