### ISSUE TITLE
Transfer to Binance

### ISSUE THREAD

**Issue by AmiKocharyan** [blockscout/blockscout#10388]
### Description

I transferred my money to Binance yesterday and I still didn’t receive my money on my Binance wallet

### Type of the installation

Docker-compose

### Type of the JSON RPC archive node

geth

### Type of the chain

BEP20

### Backend version

3.0

### Elixir & Erlang/OTP versions

Elixir 1.14.5 Erlang/OTP 25

### Operating system

unix linux

### Additional information

The issue happened at Bahamut Blockscout instance

**Comment by sl1depengwyn** [comment]
This repo is for Blockscout-related questions. Blockscout is an open source blockchain explorer. Thus, your question is out of scope, where the Blockscout team can help, you better contact the chain support directly.
