### ISSUE TITLE
Número de teléfono 

### ISSUE THREAD

**Issue by VanyLui** [blockscout/blockscout#10385]
### Description

Me llaman de este número 12722882 que no aparece como original. Que significa ese número? 

### Type of the installation

Docker-compose

### Type of the JSON RPC archive node

geth

### Backend version

v6.3.0-beta

### Elixir & Erlang/OTP versions

Elixir 1.14.5 Erlang/OTP 24

### Operating system

unix linux

### Additional information

The issue happened at GDCC Blockscout instance

**Comment by vbaranov** [comment]
This chat is for Blockscout-related questions. Your question is out of scope, where the Blockscout team can help.
