### ISSUE TITLE
OTP releases

### ISSUE THREAD

**Issue by InoMurko** [blockscout/blockscout#1039]
Deploying applications should be done with OTP releases

### Environment

* Elixir & Erlang/OTP versions (`elixir -version`): ALL
* Operating System: ALL

### Expected behaviour

The release should not contain source files.
https://hexdocs.pm/distillery/home.html%20compile%20eats%20memory
### Actual behaviour

The release contains source files and the target machine need to have installed dependencies.

**Comment by acravenho** [comment]
Thanks @InoMurko, we plan to use Distillery in the future. We don't currently have an ETA on this but it's on our radar.

**Comment by InoMurko** [comment]
Awesome @acravenho ! If you have any questions I'm happy to help.

**Comment by acravenho** [comment]
Thanks! When we start on this issue, I'll be sure to reach out for your input. :1st_place_medal:

**Comment by atoulme** [comment]
I have tried to use BlockScout as part of our project QbC (https://github.com/consensys/qbc) and hit this issue, as it is difficult to ship BlockScout as a tarball, and deploy that tarball into a Docker container right now.
