### ISSUE TITLE
Miss

### ISSUE THREAD

**Issue by Iekafaudzi92** [blockscout/blockscout#10414]
### Description

Thanks 

### Type of the installation

Docker-compose

### Type of the JSON RPC archive node

geth

### Steps to reproduce

Thanks 

### Backend version

v6.6.0-beta

### Elixir & Erlang/OTP versions

Elixir 1.14.5 Erlang/OTP 24

### Operating system

unix linux

### Additional information

The issue happened at Linea Blockscout instance

**Comment by vbaranov** [comment]
This chat is for Blockscout-related questions. Your question is out of scope, where the Blockscout team can help.
