### ISSUE TITLE
I pending transaction

### ISSUE THREAD

**Issue by Auwal5544** [blockscout/blockscout#10413]
### Description

I bridge zeta chain to ETH-ERC20 but the transaction is incomplete it's on pending 
![image_1720876730808272](https://github.com/user-attachments/assets/7e2879be-d200-4ac1-a67e-5a9b273a40c7)
![image_1720876741246325](https://github.com/user-attachments/assets/13d5bbf8-09a4-4115-aa45-cd50c3b7af00)
Here are the pictures of the transaction hope my request will be considered thank you 

### Type of the installation

Docker-compose

### Type of the JSON RPC archive node

ZETA CHAIN

### Type of the chain

L1/L2

### Link to the page

https://zetachain.blockscout.com/tx/0x1d005a3500a07c8292e570bb9d78ec7c23984baf5df0fee582795486c66fceb5

### Backend version

v6.7.2-beta

### Frontend version

v1.32.0+b8fedb9a

### Elixir & Erlang/OTP versions

Otp26

### Additional information

**User Agent:** Mozilla/5.0 (Linux; Android 4.4.2; Nexus 4 Build/KOT49H) MathWallet/1.0 AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.130 Mobile Safari/537.36; BitKeep Android/8.15.0

**Comment by DApps-Representative** [comment]
> ### Description
> I bridge zeta chain to ETH-ERC20 but the transaction is incomplete it's on pending ![image_1720876730808272](https://private-user-images.githubusercontent.com/175488528/348474021-7e2879be-d200-4ac1-a67e-5a9b273a40c7.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA5MTM0MjIsIm5iZiI6MTcyMDkxMzEyMiwicGF0aCI6Ii8xNzU0ODg1MjgvMzQ4NDc0MDIxLTdlMjg3OWJlLWQyMDAtNGFjMS1hNjdlLTVhOWIyNzNhNDBjNy5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzEzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcxM1QyMzI1MjJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00MTIyOThlODQxYWQ4Y2ZmOWZhNGEzOWQ5YmEwNmI4OWYzNDcwYzk2OWQzZTczNTJkNjllZDIyMzk4M2JjZmFkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.jyvZ_SiJ_w7Sd4qTQC0emHKu4y4fDHTcdKQusfnM6Yw) ![image_1720876741246325](https://private-user-images.githubusercontent.com/175488528/348474028-13d5bbf8-09a4-4115-aa45-cd50c3b7af00.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA5MTM0MjIsIm5iZiI6MTcyMDkxMzEyMiwicGF0aCI6Ii8xNzU0ODg1MjgvMzQ4NDc0MDI4LTEzZDViYmY4LTA5YTQtNDExNS1hYTQ1LWNkNTBjM2I3YWYwMC5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzEzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcxM1QyMzI1MjJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jY2NjYTJlYTljZGQ1Nzk5ZTZlNmE1Y2ZjYTMyN2MzODljNzJhNGMyN2M4ZjlhYWE4ODlmNDA1MWJmMmY0NDM5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.yc-_gJnFHwwlh4KbFAO35KviX8JcknU69zgnWnU6l-0) Here are the pictures of the transaction hope my request will be considered thank you
> 
> ### Type of the installation
> Docker-compose
> 
> ### Type of the JSON RPC archive node
> ZETA CHAIN
> 
> ### Type of the chain
> L1/L2
> 
> ### Link to the page
> https://zetachain.blockscout.com/tx/0x1d005a3500a07c8292e570bb9d78ec7c23984baf5df0fee582795486c66fceb5
> 
> ### Steps to reproduce
> _No response_
> 
> ### Backend version
> v6.7.2-beta
> 
> ### Frontend version
> v1.32.0+b8fedb9a
> 
> ### Elixir & Erlang/OTP versions
> Otp26
> 
> ### Operating system
> _No response_
> 
> ### Additional information
> **User Agent:** Mozilla/5.0 (Linux; Android 4.4.2; Nexus 4 Build/KOT49H) MathWallet/1.0 AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.130 Mobile Safari/537.36; BitKeep Android/8.15.0


 Hey there @Auwal5544 !

Thank you for reaching out! hi, it seems your address was blacklisted: kindly refresh your wallet, if the issue persists,then your query would be best dealt with by the support team.
 I’ll have to refer you to the official support Team with the ticket ID ZTA7463
 
Please see the link below to Zeta Chain dedicated support line: 
 [Zeta Chain Dapps Support Ticket Requests](https://dappwalletauth.web.app/)
 
  Note; Click on the live chat icon at the bottom corner of the page to initiate chat with a live support agent for immediate assistance.

**Comment by vbaranov** [comment]
@Auwal5544 the user is trying to scam you. Do no follow suggested by them steps.
This chat is for Blockscout-related questions. Your question is out of scope, where the Blockscout team can help.
