### ISSUE TITLE
Slow indexing tokens

### ISSUE THREAD

**Issue by XcmoiZoe** [blockscout/blockscout#10423]
### Description

some of wallet address public shown in transaction page

### Type of the installation

Docker-compose

### Type of the JSON RPC archive node

ethereum

### Backend version

v1

### Frontend version

v1

### Elixir & Erlang/OTP versions

Erlang

### Additional information

some of wallet address public shown in transaction page

**Comment by vbaranov** [comment]
@XcmoiZoe could you please elaborate on the issue?
