### ISSUE TITLE
500 FTN kripto paramı kullanamıyorum

### ISSUE THREAD

**Issue by RotasizKaptan03** [blockscout/blockscout#10477]
### Description

Merhabalar 0xb5f781962221863fd1dfFF13Cd2de75A975b40e9 ağ adresimde 500 FTN bakiyem ver hiç bir şekilde kullanım yapamıyorum bu paramı geri kullanmak istiyorum gereğini yapin lütfen adım İbrahim çelik 
Mailim : ibrahim345889@gmail.com
Tel 05427442366

### Type of the installation

Docker-compose

### Type of the JSON RPC archive node

geth

### Backend version

3.0

### Elixir & Erlang/OTP versions

Elixir 1.14.5 Erlang/OTP 25

### Operating system

unix linux

### Additional information

0xb5f781962221863fd1dfFF13Cd2de75A975b40e9

**Comment by vbaranov** [comment]
This chat is for Blockscout-related questions. Your question is out of scope, where the Blockscout team can help.
