### ISSUE TITLE
Internal transaction CSV export returns `404` on Immutable

### ISSUE THREAD

**Issue by yvaskov** [blockscout/blockscout#10474]
## Description

There's an issue with CSV export when selecting a wide `From/To` period for an address with a large number of internal transactions.

### Steps to reproduce

1. Open https://explorer.immutable.com/csv-export?type=internal-transactions&filterType=address&filterValue=undefined&address=0x99F1117F13e072b299942037E6A5d1469912B47A
2. Select from `June 1, 2024` to `June 30, 2024`
3. Solve captcha, press `Download`

Results in 404 after a long delay.

## Version

[v6.7.2-beta](https://github.com/blockscout/blockscout/tree/v6.7.2-beta)

**Comment by nikitosing** [comment]
as far as I know this instance does not belong to the splited setup, and now issue is not reproducible
