### ISSUE TITLE
Duplicate logs in API response due to `allow_non_consensus` flag

### ISSUE THREAD

**Issue by yvaskov** [blockscout/blockscout#10498]
## Description

Logs from reorged blocks are returned in API response, resulting in identical duplicates (no block hash is returned). This leads to duplicates on the frontend as well, as the behaviour is the same in API v2.
[Client example for RPC API](https://rootstock-testnet.blockscout.com/api?module=logs&action=getLogs&address=0x00ca74491d9493bfe5451246c8c72849ba4a7f9d&toBlock=latest&fromBlock=5338249&topic0=0x7d84a6263ae0d98d3329bd7b46bb4e8d6f98cd35a7adb45c274c8b7fd5ebd5e0)

## Version

[v6.7.2-beta](https://github.com/blockscout/blockscout/tree/v6.7.2-beta)

**Comment by SurenFTN** [comment]
@vbaranov  I have same issue. How can solve it ?
