### ISSUE TITLE
¿Por qué no se pueden cambiar mis monedas vivaFTN y dzook por monedas FTN?

### ISSUE THREAD

**Issue by MainhiLe** [blockscout/blockscout#10496]
### Description

¿Por qué no se pueden cambiar mis monedas vivaFTN y dzook por monedas FTN?

### Type of the installation

Docker-compose

### Type of the JSON RPC archive node

geth

### Backend version

3.0

### Elixir & Erlang/OTP versions

Elixir 1.14.5 Erlang/OTP 25

### Operating system

unix linux

### Additional information

¿Por qué no se pueden cambiar mis monedas vivaFTN y dzook por monedas FTN?

**Comment by MainhiLe** [comment]
¿Por qué no se pueden cambiar mis monedas vivaFTN y dzook por monedas FTN?

**Comment by vbaranov** [comment]
@MainhiLe Please formulate your problem in English.
