### ISSUE TITLE
CSV export IOTAEVM

### ISSUE THREAD

**Issue by borninchb** [blockscout/blockscout#10490]
### Description

Why do the transaction of wIOTA arent shown in the csv export?

### Type of the installation

Manual from the source code

### Type of the JSON RPC archive node

where do i find this

### Type of the chain

l2

### Link to the page

https://explorer.evm.iota.org/tx/0xe478c61c45fee22807a9bbe38490a40b497e04149686529a97630eb91386cb44

### Steps to reproduce

export a csv file of this or any other address https://explorer.evm.iota.org/address/0xf93932634472496c556a9BabD3135fb30996A7F2

### Backend version

v6.7.2-beta

### Frontend version

v1.32.0

### Elixir & Erlang/OTP versions

i dont know

### Operating system

Windows 11

### Additional information

**User Agent:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/127.0.0.0 Safari/537.36

**Comment by vbaranov** [comment]
Probably, it was a temporary issue. I made CSV export for this address for the last4 days, and mentioned tx hash is included there.

[transactions_0xf93932634472496c556a9BabD3135fb30996A7F2_2024-07-25_2024-07-29.csv](https://github.com/user-attachments/files/16411504/transactions_0xf93932634472496c556a9BabD3135fb30996A7F2_2024-07-25_2024-07-29.csv)

**Comment by borninchb** [comment]
[token_transfers_0xf93932634472496c556a9BabD3135fb30996A7F2_2024-06-01_2024-07-29.csv](https://github.com/user-attachments/files/16411927/token_transfers_0xf93932634472496c556a9BabD3135fb30996A7F2_2024-06-01_2024-07-29.csv)
This is true in the transactions the wiota txs appear. But not in the token_transfer csv. Why is that the case?

**Comment by vbaranov** [comment]
Token transfers are included into the export for the given address, if token transferred to of from given address. As far as i see, wIOTA transfers are between:
burn address -> 0x531777F8c35fDe8DA9baB6cC7093A7D14a99D73E
0x531777F8c35fDe8DA9baB6cC7093A7D14a99D73E -> 0x8F9a72d8F56479903ae386849e290d49389e41F9

addresses. This is why they're invisible in the export for address `0xf93932634472496c556a9BabD3135fb30996A7F2`.

<img width="635" alt="Screenshot 2024-07-29 at 15 17 19" src="https://github.com/user-attachments/assets/52ee2772-d991-47fb-8efd-33d942ba0146">

**Comment by borninchb** [comment]
I dont I understand what xou are describing! 
I am talking about eg. this transfer 0x987bc1e57e6f0b605ebb4da6bb15d5de1b7bed738299ca6862b52c28fe5bb3fc
![image](https://github.com/user-attachments/assets/c52b9fd8-a729-47ba-81db-2e0778f8f482)
I am providing liquidy in RUST and w IOTA but in the export only the transction could be seen.
[token_transfers_0xf93932634472496c556a9BabD3135fb30996A7F2_2024-07-11_2024-07-11.csv](https://github.com/user-attachments/files/16415780/token_transfers_0xf93932634472496c556a9BabD3135fb30996A7F2_2024-07-11_2024-07-11.csv)

**Comment by vbaranov** [comment]
> I dont I understand what xou are describing! I am talking about eg. this transfer 0x987bc1e57e6f0b605ebb4da6bb15d5de1b7bed738299ca6862b52c28fe5bb3fc
 I am providing liquidy in RUST and w IOTA but in the export only the transction could be seen. [token_transfers_0xf93932634472496c556a9BabD3135fb30996A7F2_2024-07-11_2024-07-11.csv](https://github.com/user-attachments/files/16415780/token_transfers_0xf93932634472496c556a9BabD3135fb30996A7F2_2024-07-11_2024-07-11.csv)

According to the event logs of the transaction there is no transfer of wIOTA token to or from address `0xf93932634472496c556a9BabD3135fb30996A7F2` - this is why it is not in the export for this address, it is not in the UI. Export only shows token transfers to/from given address. If you require another filter of exporting data please describe it via [request](https://blockscout.canny.io/feature-requests).

**Comment by borninchb** [comment]
I dont know how to view the logs and they doesnt help me record my transaktions. My wIOTA were transfered to a smartcontract of a dex from this address. 
Thans for your help and explanations.
