### ISSUE TITLE
trace_block method does not exist/is not available 

### ISSUE THREAD

**Issue by dijareoracle** [blockscout/blockscout#10517]
I have referenced the blockscout-stack helm chart in my helm chart to be able to deploy it via ArgoCD. 

My setup includes having Polygon edge nodes deployed in K8s and rpc is exposed. 

I have added all the following variables for blockscout: 

```
  ethereumJsonrpcHttpUrl: xxx
  ethereumJsonrpcTraceUrl: xxx
  chainId: xxx
  subnetwork: xxx
  ethereumJsonrpcDisableArchiveBalances: xxx
  indexerDisablePendingTransactionsFetcher: xxx
  indexerDisableInternalTransactionsFetcher: xxx
  indexerTxActionsReindexFirstBlock: xxx
  indexerTxActionsReindexLastBlock: xxx
  indexerInternalTransactionsTracerType: polygon_edge
  txsStatsEnabled: xxx
  showTxsChart: xxx
  reCaptchaDisabled: xxx
  solidityscanChainId: xxx
  logo: xxx
  nextPublicApiHost: xxx
  nextPublicApiProtocol: xxx
  nextPublicStatsApiHost: xxx
  nextPublicNetworkName: xxx
  nextPublicNetworkId: xxx
  nextPublicAppHost: xxx
  nextPublicAppProtocol: xxx
  nextPublicHomepageCharts: xxx
  nextPublicVisualizeApiHost: xxx
  nextPublicIsTestnet: xxx
  nextPublicApiWebsocketProtocol: xxx
  nextPublicNetworkLogo: xxx
  nextPublicNetworkIcon: xxx
  nextPublicHomepagePlateBackground: xxx
```

So my tracertype is polygon_edge, and both my frontend and blockscout-stats are working as intended. Blockscout stats can connect to db, same as blockscout itself, but I get these logs in Blockscout:

```
{"time":"2024-07-29T08:43:32.148Z","severity":"error","message":"failed to fetch: @80524: (-32601) the method trace_block does not exist/is not available\n@80487: (-32601) the method trace_block does not exist/is not available\n@80485: (-32601) the method trace_block does not exist/is not available\n@80484: (-32601) the method trace_block does not exist/is not available\n@80483: (-32601) the method trace_block does not exist/is not available\n@80482: (-32601) the method trace_block does not exist/is not available\n@80481: (-32601) the method trace_block does not exist/is not available\n@80480: (-32601) the method trace_block does not exist/is not available\n@80478: (-32601) the method trace_block does not exist/is not available\n@79129: (-32601) the method trace_block does not exist/is not available\n","metadata":{"count":10,"fetcher":"block_reward","error_count":10}}
```
This above log is repeated constantly and no data is being shown in blockscout. 

I am able to run curl:
```
curl -X POST --data '{"jsonrpc":"2.0","method":"debug_traceBlockByNumber","params":["0x65885", {}],"id":424242}' https://my.rpc
```

Q1. Is this something unusual with my nodes or with Blockscout trace_block method?
Q2. Is it possible to change the request method that is making requests on my nodes? Not only via the tracer type variable.

I apologize if the question is not really well defined and if it's a dumb question overall but I've been looking into this for days and I couldn't find the resolution on my own. 

Your help is greatly appreciated, thank you!

**Comment by nzenchik** [comment]
Transferring issue here, as it is not related to helm chart

**Comment by gordonswing** [comment]
Yeah, we have the same issue, bumping this kindly

**Comment by RonTuretzky** [comment]
Bumping this as we have the same issue

**Comment by vbaranov** [comment]
Polygon Edge does support [debug](https://github.com/0xPolygon/polygon-edge/blob/0504fa79632b0a2797a7598d87f6743cb9a1cd01/jsonrpc/debug_endpoint.go) module. However, this [guide](https://polygon-edge-v063.evmbuilder.com/docs/get-started/json-rpc-commands/) doesn't provide instructions how to enable it. If `debug` module is disabled on the JSON RPC node, you have to disable internal transactions fetcher by setting `INDEXER_DISABLE_INTERNAL_TRANSACTIONS_FETCHER=true`.

**Comment by dijareoracle** [comment]
Hello! Yes we have already added that variable, but our backend is still filled with logs for trace_block method not available/not found.

We managed to get our blockscout up and running by fixing another issue with communication between the frontend and the backend. But as mentioned, the backend logs are filling up quickly and constantly throw this error even with the 
`INDEXER_DISABLE_INTERNAL_TRANSACTIONS_FETCHER=true` enabled

**Comment by vbaranov** [comment]
@dijareoracle could you please also set `INDEXER_DISABLE_BLOCK_REWARD_FETCHER=true` (it uses `trace_block` request under the hood).

**Comment by dijareoracle** [comment]
Yes we just added this variable as well, now the trace_block logs are not showing up anymore but we're getting a ton of these logs now: 

`error fetching block number 103257 header\n","metadata":{"count":20,"fetcher":"coin_balance_catchup","error_count":20}}` 

This might be something on our side but would you mind just elaborating on what is happening here? 
Also thank you very much for your help so far!

**Comment by vbaranov** [comment]
@dijareoracle The latest error means that `eth_getBalance` request failed for specific block number due to the fact, that the node is not archival. In order to stop sending such requests you can set `ETHEREUM_JSONRPC_DISABLE_ARCHIVE_BALANCES=true`. In this case, only requests with `latest` tag will be whitelisted.

**Comment by dijareoracle** [comment]
This variable is also set to true on our side, to not have you come here back and forth I will send you the list of all our current values:

```
  ethereumJsonrpcHttpUrl: "xxxxx"
  ethereumJsonrpcTraceUrl: "xxxxx"
  chainId: "xxx"
  subnetwork: "xxxx"
  ethereumJsonrpcDisableArchiveBalances: "true"
  indexerDisablePendingTransactionsFetcher: "true"
  indexerDisableInternalTransactionsFetcher: "true"
  indexerDisableBlockRewardFetcher: "true"
  indexerTxActionsReindexFirstBlock: "1"
  indexerTxActionsReindexLastBlock: "10000"
  indexerInternalTransactionsTracerType: "polygon_edge"
  txsStatsEnabled: "false"
  showTxsChart: "false"
  reCaptchaDisabled: "true"
  solidityscanChainId: "100"
  logo: "xxxx"
  nextPublicApiHost: "xxxxx"
  nextPublicApiProtocol: "https"
  nextPublicStatsApiHost: "xxxxx"
  nextPublicNetworkName: "xxxx"
  nextPublicNetworkId: "xxxxx"
  nextPublicAppHost: "xxxxx"
  nextPublicAppProtocol: "https"
  nextPublicHomepageCharts: '[]'
  nextPublicVisualizeApiHost: "xxxxx"
  nextPublicIsTestnet: "true"
  nextPublicApiWebsocketProtocol: wss
  nextPublicNetworkLogo: xxxxx
  nextPublicNetworkIcon: xxxxx
  nextPublicHomepagePlateBackground: '#1B7263'
```

Ignore the lowercaps here because these values are correctly defined in all caps elsewhere and we are only referencing the values here.

**Comment by Qwerty5Uiop** [comment]
Hi @dijareoracle! There is one more variable you should set along with `ETHEREUM_JSONRPC_DISABLE_ARCHIVE_BALANCES`, it's `ETHEREUM_JSONRPC_ARCHIVE_BALANCES_WINDOW`.
If `ETHEREUM_JSONRPC_DISABLE_ARCHIVE_BALANCES` is set to `true`, balances fetcher will skip requests with `block_number <= latest - window`. The default value of this window is 200. So most likely you are getting errors like this because there is no state for `latest - 200` height.
So please set this variable for something more suitable or, if you want only `latest` balances requests, just set it to `0`

**Comment by dijareoracle** [comment]
Hello again! I just set this variable but we still get the same logs, the value for "ETHEREUM_JSONRPC_ARCHIVE_BALANCES_WINDOW=0"

I will cleanup some resources on my side and also the blockscout database and will write here again in case the error keeps popping up, thanks again!

**Comment by dijareoracle** [comment]
After cleanup everything looks more normal so I will close this issue as I do not require any more assistance for the moment. Thank you for all the help!
