### ISSUE TITLE
nft

### ISSUE THREAD

**Issue by Silent-netuzen** [blockscout/blockscout#10524]
### Description

cant add image when create nft

### Type of the installation

Docker-compose

### Type of the JSON RPC archive node

prom testnet

### Backend version

v6.10

### Elixir & Erlang/OTP versions

elixir

**Comment by vbaranov** [comment]
@Silent-netuzen Please elaborate on the issue.

**Comment by vbaranov** [comment]
Closing due to no response from the author.
