### ISSUE TITLE
Error display the internal transaction status

### ISSUE THREAD

**Issue by yxsec** [blockscout/blockscout#10526]
### Description

Failed internal transactions will be displayed as successful.

Example
https://eth.blockscout.com/tx/0x468dfc854bed2d71fd94e2f72842df42a42c527f111284c5f00d90ea72ef9f83?tab=internal

<img width="1069" alt="image" src="https://github.com/user-attachments/assets/f48178d4-b00f-4178-9c73-ff1638fd66ec">
The transaction was failed, so all internal transaction should be failed.
But the blockscout recorded these as successful.
<img width="1200" alt="image" src="https://github.com/user-attachments/assets/0c4c448d-7ef1-4c77-93f5-624ce87e92bf">

### Type of the installation

Docker-compose

### Type of the JSON RPC archive node

https://eth.blockscout.com/

### Backend version

 v6.7.2-beta

### Frontend version

v1.32.1

### Elixir & Erlang/OTP versions

https://eth.blockscout.com/

**Comment by vbaranov** [comment]
@yxsec this bug has been fixed in https://github.com/blockscout/blockscout/pull/9212. However, it is applied to new instances of transactions. Transaction, which you mentioned, has been re-fetched - currently internal trasnactions are marked as failed. If you have more examples please let us know. At the same time, we'll try to find such instances by ourselves and refetch related blocks as well.

**Comment by yxsec** [comment]
> @yxsec this bug has been fixed in #9212. However, it is applied to new instances of transactions. Transaction, which you mentioned, has been re-fetched - currently internal trasnactions are marked as failed. If you have more examples please let us know. At the same time, we'll try to find such instances by ourselves and refetch related blocks as well.

Example:
https://eth.blockscout.com/tx/0x235d55b89fc84075ea5fb886f9f14305310cd6b0042b2a27dff9ccb890b1ef79?tab=internal

**Comment by yxsec** [comment]
> @yxsec this bug has been fixed in #9212. However, it is applied to new instances of transactions. Transaction, which you mentioned, has been re-fetched - currently internal trasnactions are marked as failed. If you have more examples please let us know. At the same time, we'll try to find such instances by ourselves and refetch related blocks as well.

More Example: https://eth.blockscout.com/tx/0x235d55b89fc84075ea5fb886f9f14305310cd6b0042b2a27dff9ccb890b1ef79?tab=internal
@vbaranov

**Comment by Qwerty5Uiop** [comment]
Incorrect statuses in internal transactions for older blocks were fixed in https://github.com/blockscout/blockscout/pull/10654
