### ISSUE TITLE
Issue of failed transaction (my evm address :0xb2EC97b4b7CAA409A569ABE4794BBb9C0cb6C24C )

### ISSUE THREAD

**Issue by misbahjk13** [blockscout/blockscout#10523]
### Description

Hey! I am facing problem proceeding with my daily check in and other transactions on plume testnet because a previous transaction is still being signed or submitted by the other contract side.  Two transactions of predict price movement failed by contract address : 
1. [0xc414c73db4...f73e](https://testnet-explorer.plumenetwork.xyz/tx/0xc414c73db45fd67704a801beb59503a42b630d487624b68a0069ce8cb6faf73e) 
 2. [0x444ebcd818...42e2](https://testnet-explorer.plumenetwork.xyz/tx/0x444ebcd818771528321043fc52b37c8102d5d72c2daed6959f4c40fdca2e42e2)

### Type of the installation

Docker-compose

### Type of the JSON RPC archive node

...

### Type of the chain

...

### Link to the page

https://testnet-explorer.plumenetwork.xyz/address/0xb2EC97b4b7CAA409A569ABE4794BBb9C0cb6C24C

### Steps to reproduce

...

### Backend version

v6.7.2

### Frontend version

3.3.2+93dd5b18

### Elixir & Erlang/OTP versions

...

### Operating system

...

### Additional information

**User Agent:** Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36

**Comment by vbaranov** [comment]
@misbahjk13 what is your issue about? Could you elaborate?

**Comment by misbahjk13** [comment]
I can’t make transactions on plume testnet because my previous transaction
failed due to some unknown cause. Kindly look into this matter. I am facing
real serious problem.

**Comment by vbaranov** [comment]
This chat is for Blockscout-related questions. Your question is out of scope, where the Blockscout team can help.
