### ISSUE TITLE
plume testnet

### ISSUE THREAD

**Issue by subhash123121** [blockscout/blockscout#10549]
### Description

**plume testnet does not connect by email and metamask.
on email it just loading and nothing happen
on metamask it says not detected however email and metamask both are fine running on other networks,
but at blockscout plume testnet is not running
i tried on both browsers**

### Type of the installation

Docker

### Type of the JSON RPC archive node

plume testnet

### Link to the page

https://testnet-explorer.plumenetwork.xyz/block/8029589

### Backend version

v6.7.2

### Frontend version

3.3.2+93dd5b18

### Elixir & Erlang/OTP versions

elixir

### Operating system

windows

### Additional information

**User Agent:** Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:109.0) Gecko/20100101 Firefox/115.0

**Comment by vbaranov** [comment]
The Blockscout team doesn't manage this instance of the explorer. Please, ask the question to the team, which supports this chain.
