### ISSUE TITLE
There is an unknown transaction

### ISSUE THREAD

**Issue by Viorest00** [blockscout/blockscout#10554]
### Description

I just opened the omni.ls platform where I am staking MANTA coins. When I opened it, my Vmanta coins became 0. After investigating, I found a transaction to another wallet from one week ago, even though my MANTA was supposed to be staked. I am really confused and do not understand how this could happen, so I need assistance for an explanation.

### Type of the installation

Docker-compose

### Type of the JSON RPC archive node

Manta Pasific

### Link to the page

https://pacific-explorer.manta.network/address/0x6414A7f1706C9f8b5a6E1920ce7a7Eb8702c6B04

### Backend version

v6.7.2

### Frontend version

3.3.2+93dd5b18

### Elixir & Erlang/OTP versions

Elixir 1.16.2

### Operating system

Windows

### Additional information

537.36 (KHTML, like Gecko) Chrome

**Comment by vbaranov** [comment]
The Blockscout team doesn't manage this instance of the explorer. Please, ask the question to the team, which supports this Manta chain.
