### ISSUE TITLE
Halo sir not rasewd my staking fair token plz halp me

### ISSUE THREAD

**Issue by Kamran42401** [blockscout/blockscout#10569]
### Description

Halo sir not rasewd my staking fair token plz halp me

### Type of the installation

Docker-compose

### Type of the JSON RPC archive node

Halo sir not rasewd my staking fair token plz halp me

### Type of the chain

Fair 

### Link to the page

https://scan.come.boats/address/0x5C38B8DCF65aFB1c6fb89B09001969C96D3fe485?tab=tokens

### Steps to reproduce

Halo sir not rasewd my staking fair token plz halp me

### Backend version

v6.7.2-beta

### Frontend version

v1.32.1+0c82ce15

### Elixir & Erlang/OTP versions

Halo sir not rasewd my staking fair token plz halp me

### Operating system

Halo sir not rasewd my staking fair token plz halp me

### Additional information

**User Agent:** Mozilla/5.0 (Linux; Android 11; TECNO CE7j Build/RP1A.200720.011; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/126.0.6478.186 Mobile Safari/537.36

**Comment by Kamran42401** [comment]
Halo sir not rasewd my staking fair token plz halp me

**Comment by Kamran42401** [comment]
![Screenshot_20240807-044946](https://github.com/user-attachments/assets/4d2caf54-80f4-4135-b99c-258532f1edd0)
![Screenshot_20240807-044946](https://github.com/user-attachments/assets/ee5aba3d-6c66-49c0-babb-c7511a6eb219)

**Comment by Kamran42401** [comment]
Not rasewd my staking rewad clam fair token plz halp me

**Comment by vbaranov** [comment]
This chat is for Blockscout-related questions. Your question is out of scope, where the Blockscout team can help.
