### ISSUE TITLE
Missed token 

### ISSUE THREAD

**Issue by Kamran42401** [blockscout/blockscout#10572]
### Description

Halo sir not rasewd my staking reward for Clam fair token miss token plz halp me 

### Type of the installation

Docker-compose

### Type of the JSON RPC archive node

Halo sir not rasewd my staking reward for Clam fair token miss token plz halp me 

### Type of the chain

Core

### Link to the page

https://scan.come.boats/token/0x4E86DDa44D0f4F04188ff0D96cd8140DC861aFa2

### Steps to reproduce

Halo sir not rasewd my staking reward for Clam fair token miss token plz halp me 

### Backend version

v6.7.2-beta

### Frontend version

v1.32.1+0c82ce15

### Elixir & Erlang/OTP versions

Halo sir not rasewd my staking reward for Clam fair token miss token plz halp me 

### Operating system

Halo sir not rasewd my staking reward for Clam fair token miss token plz halp me 

### Additional information

**User Agent:** Mozilla/5.0 (Linux; Android 11; TECNO CE7j Build/RP1A.200720.011; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/126.0.6478.186 Mobile Safari/537.36

**Comment by vbaranov** [comment]
The Blockscout team doesn't manage this instance of the explorer. Please, ask the question to the team, which supports this chain.

**Comment by Kamran42401** [comment]
My Fair token miss y
