### ISSUE TITLE
Plume Testnet error

### ISSUE THREAD

**Issue by k1w1v3rd3** [blockscout/blockscout#10582]
### Description

![plume](https://github.com/user-attachments/assets/a32464fc-f63e-471c-8fdf-4070b08c8d9e)
hi
as you can see in the attached screenshot, i'm seeing a wrong message of a pending transaction... this is causing me not being able to perform any other transactions.
if you look at the wallet activity, you'll see all transactions were finished so i don't understand the reason of this: https://testnet-explorer.plumenetwork.xyz/address/0xdC726e6d2948F9dC6c2bD57B914F60d16B6779Df
hope you help me solve this in order to continue using plume testnet
have a nice weekend

### Type of the installation

Docker-compose

### Type of the JSON RPC archive node

openethereum

### Type of the chain

l1

### Link to the page

https://testnet-explorer.plumenetwork.xyz/address/0xdC726e6d2948F9dC6c2bD57B914F60d16B6779Df

### Backend version

v6.7.2

### Frontend version

3.3.2+93dd5b18

### Elixir & Erlang/OTP versions

elixir 1.16.3

### Operating system

windows11

### Additional information

**User Agent:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/127.0.0.0 Safari/537.36 Edg/127.0.0.0

**Comment by vbaranov** [comment]
This chat is for Blockscout-related questions. Your question is out of scope, where the Blockscout team can help.
