### ISSUE TITLE
Transaction issues 

### ISSUE THREAD

**Issue by clintbjr** [blockscout/blockscout#10583]
### Description

Transaction payout was supposed to 964 but it paid out only 11 dollars 

### Type of the installation

Manual from the source code

### Type of the JSON RPC archive node

Peipei/ eth

### Type of the chain

https://eth.blockscout.com/block/20427143

### Link to the page

https://eth.blockscout.com/block/20427143

### Backend version

v6.7.2-beta

### Frontend version

v1.33.1+cec56f19

### Elixir & Erlang/OTP versions

Elixir 1.164

### Operating system

Macos

### Additional information

**User Agent:** Mozilla/5.0 (iPhone; CPU iPhone OS 17_5_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.5 Mobile/15E148 Safari/604.1

**Comment by vbaranov** [comment]
This chat is for Blockscout-related questions. Your question is out of scope, where the Blockscout team can help.
