### ISSUE TITLE
RSK returns empty token items sometimes

### ISSUE THREAD

**Issue by 0xtzData** [blockscout/blockscout#10594]
Environment: https://rootstock-testnet.blockscout.com/
Backend: [v6.7.2-beta](https://github.com/blockscout/blockscout/tree/v6.7.2-beta)
Frontend: [v1.33.0](https://github.com/blockscout/frontend/tree/v1.33.0)

Expected behavior:
`addresses/$addr/tokens` always returns tokens if they exist.

Actual behavior:
Sometimes it returns no items
https://rootstock-testnet.blockscout.com/api/v2/addresses/0x7b8549C04710fC3b9187e7FD36538E65066Dd98F/tokens
```
{"items":[],"next_page_params":null}
```

**Comment by vbaranov** [comment]
The issue is unreproducible anymore.
