### ISSUE TITLE
Issue in confirmation daily check-ins and staking as well

### ISSUE THREAD

**Issue by jshaturaev** [blockscout/blockscout#10596]
### Description

My daily check-in transaction has stuck. I cannot confirm daily check-ins and staking operations. Could you please assist in the following case?
![11](https://github.com/user-attachments/assets/aefb0b02-5e9a-4ff0-ab4c-9d4791e13e1f)
  

### Type of the installation

Docker-compose

### Type of the JSON RPC archive node

Plume Testnet

### Steps to reproduce

As if there is a transaction in the row, it gets stuck and cannot confirm any transactions.
![11](https://github.com/user-attachments/assets/7526039d-e4f6-4c07-b11b-0f4057cccaa5)

### Backend version

v6.1.0

### Frontend version

v1.1.1

### Elixir & Erlang/OTP versions

Elixir 1.16.1

### Operating system

Windows

### Additional information

![11](https://github.com/user-attachments/assets/1cbc82ad-41bf-481f-9ba2-a4c5f8aa9211)

**Comment by vbaranov** [comment]
This chat is for Blockscout-related questions. Your question is out of scope, where the Blockscout team can help.
