### ISSUE TITLE
kyc still not done 

### ISSUE THREAD

**Issue by 1mhaseeb** [blockscout/blockscout#10609]
### Description

My name is Muhammad Haseeb and i am currently studying . I have applied for kyc two months ago my kyc still not verified and i need my account verified to withdraw money to pay my university fee. It is kindly requested to you that please do my kyc . I will be very thankful to you for this act of kindness .

### Type of the installation

Docker-compose

### Type of the JSON RPC archive node

Sidra

### Backend version

v6.1.1.0

### Elixir & Erlang/OTP versions

Elixir

**Comment by vbaranov** [comment]
This chat is for Blockscout-related questions. Your question is out of scope, where the Blockscout team can help.

**Comment by 1mhaseeb** [comment]
So where i will contact

**Comment by 1mhaseeb** [comment]
Provide me the offical male of sidra
