### ISSUE TITLE
Não recebi meu token 

### ISSUE THREAD

**Issue by Paulo-jor** [blockscout/blockscout#10605]
### Description

Enviei meu token de gooddolar para truswallet até então de sucesso mas não recebi...

### Type of the installation

Docker-compose

### Type of the JSON RPC archive node

Fuse

### Type of the chain

E1

### Link to the page

https://explorer.fuse.io/tx/0x7f133befcdd4843a14b4cdf304f534cafd6badd2257c392a269532372fcf4357

### Steps to reproduce

![Screenshot_2024-08-16-13-49-50-481_com android chrome](https://github.com/user-attachments/assets/134e74c8-906c-46d8-a6e4-22f445829278)

### Backend version

v6.7.2-beta.+commit.208b0a20

### Frontend version

v1.33.0+b53a425d

### Elixir & Erlang/OTP versions

Erc20

### Additional information

**User Agent:** Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/127.0.0.0 Mobile Safari/537.36

**Comment by vbaranov** [comment]
@Paulo-jor please describe the issue in English.

**Comment by Paulo-jor** [comment]
![Screenshot_2024-08-16-13-49-50-481_com android chrome](https://github.com/user-attachments/assets/beae9638-d2f4-42b2-ae4f-954bbbf95b81)
I made a transaction but so far I have not received it and the transaction was successful

**Comment by Paulo-jor** [comment]
I want help removing sensation send from fuse to truswallet fuse

**Comment by vbaranov** [comment]
This chat is for Blockscout-related questions. Your question is out of scope, where the Blockscout team can help.
