### ISSUE TITLE
Scammers 

### ISSUE THREAD

**Issue by Sudaney** [blockscout/blockscout#10613]
### Description

0x2F54605Ffd6b9151dF9C6fd49bc2A74413Ee0F3a
Someone with the above address hacked my sidra account and packed all my sidra please do something 

### Type of the installation

Docker-compose

### Type of the JSON RPC archive node

Geth

### Type of the chain

L1

### Link to the page

Sidrachain

### Steps to reproduce

0x2F54605Ffd6b9151dF9C6fd49bc2A74413Ee0F3a
Someone with the above address stole my sidra coins 

### Backend version

v6.0.1

### Frontend version

v1.11.1

### Elixir & Erlang/OTP versions

OTP versions

### Operating system

Linux 

### Additional information

0x2F54605Ffd6b9151dF9C6fd49bc2A74413Ee0F3a

**Comment by vbaranov** [comment]
This chat is for Blockscout-related questions. Your question is out of scope, where the Blockscout team can help.
