### ISSUE TITLE
Set timeouts or rewrite potentially slow queries detected on Optimism

### ISSUE THREAD

**Issue by 0xtzData** [blockscout/blockscout#10615]
Environment: https://optimism.blockscout.com/
Backend: [v6.7.2-beta.+commit.7437aa16](https://github.com/blockscout/blockscout/commit/7437aa16)
Frontend: [v1.33.1](https://github.com/blockscout/frontend/tree/v1.33.1)

**Expected behavior**: Queries that can potentially hang are terminated after some period without causing performance degradation to the application.

**Actual behavior**: Some queries were hanging for several days, as a result DB connections were staved.

List of slow queries:
https://app.pganalyze.com/servers/4bmofqhwfvcfdbaphgslvxkb3y/checks/connections/active_query/resolved

DB metrics when it happened:
https://grafana.k8s-prod-1.blockscout.com/d/000000039/postgresql-database?orgId=1&var-DS_PROMETHEUS=prometheus&var-interval=$__auto_interval_interval&var-namespace=optimism-mainnet-postgresql&var-release=&var-instance=10.42.158.189:9187&var-datname=All&var-mode=All&from=1722512691016&to=1724008886138

**Comment by vbaranov** [comment]
@0xtzData please re-check. Slow queries are gone with backend 6.9.0.
