### ISSUE TITLE
Fund not received 

### ISSUE THREAD

**Issue by Gagan677** [blockscout/blockscout#10610]
### Description

I do transaction of 720 manta to arbitrum but transaction got canceled and my manta not received back

### Type of the installation

Docker-compose

### Type of the JSON RPC archive node

Geth

### Type of the chain

L2

### Link to the page

https://pacific-explorer.manta.network/address/0x598165784B108b5156117A213d1bcD9915AF83e7

### Steps to reproduce

Please give my manta back

### Backend version

v6.7.2

### Frontend version

3.3.2 93dd5b18

### Elixir & Erlang/OTP versions

Otp26

### Operating system

MacOS

### Additional information

![IMG_0828](https://github.com/user-attachments/assets/8ba4ad93-bf40-4f72-810b-2dd131fba158)

**Comment by vbaranov** [comment]
This chat is for Blockscout-related questions. Your question is out of scope, where the Blockscout team can help.
