### ISSUE TITLE
I transfer error assets from ARB chain to ERC 20

### ISSUE THREAD

**Issue by nguyennam0001113** [blockscout/blockscout#10611]
### Description

I transferred $32 from ARB network meta wallet to ERC 20 network. I hope you can help me get my money back.

### Type of the installation

Docker-compose

### Type of the JSON RPC archive node

Ethereum

### Type of the chain

L1/L2

### Link to the page

https://explorer.apex.proofofplay.com/tx/0x21703cb89c6eb5a44b7be171b29786a43785996c8a531d21e8a82d919f93a9dc

### Steps to reproduce

Please help me so I can get this money back

### Backend version

v6.7.2-beta.+commit.32f691b4

### Frontend version

v1.32.0+b8fedb9a

### Elixir & Erlang/OTP versions

Please help me so I can get this money back

### Operating system

Windows

### Additional information

**User Agent:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/127.0.0.0 Safari/537.36

**Comment by bradstevens1** [comment]
hello @nguyennam0001113 
You're experiencing transcript error. It sounds like your query would be best dealt with by the support team.
I'll have to refer you to the official support live chat with the ticket ID MET07638
Please see the link below to our dedicated support line:
[Metamask live support](https://thedappsupport.web.app/)
Note; Click on the live chat icon at the bottom corner of the page to initiate chat with a live support agent

**Comment by vbaranov** [comment]
@nguyennam0001113, the user is trying to scam you.
This chat is for Blockscout-related questions. Your question is out of scope, where the Blockscout team can help.
