### ISSUE TITLE
Assistance inquiry

### ISSUE THREAD

**Issue by jshaturaev** [blockscout/blockscout#10626]
### Description

There are several pending transactions, so I can't log on for daily check-ins and further tasks on Plume Testnet. Could you please assist on this issue, to cancel all failed but pending transactions?
![Безымянный](https://github.com/user-attachments/assets/1693b982-9776-469b-81d5-32b6928258c8)

### Type of the installation

Docker-compose

### Type of the JSON RPC archive node

Plume Testnet

### Type of the chain

L2

### Link to the page

https://testnet-explorer.plumenetwork.xyz/tx/0x068F374ce998459Aa94500BCB0970D2436544588

### Backend version

v6.7.2

### Frontend version

3.3.2+93dd5b18

### Elixir & Erlang/OTP versions

Elixir 1.16.1

### Operating system

Windows

### Additional information

**User Agent:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36

**Comment by vbaranov** [comment]
The Blockscout team doesn't manage this instance of the explorer. Please, ask the question to the team, which supports this chain.
