### ISSUE TITLE
Assistance inquiry

### ISSUE THREAD

**Issue by jshaturaev** [blockscout/blockscout#10627]
### Description

Please help on this issue. There are several failed/pending transactions 
so I cannot make daily check-ins and other tasks on Plume Testnet. 
![Безымянный](https://github.com/user-attachments/assets/216b095e-4680-4cf5-ba51-9abf48515cf8)

### Type of the installation

Docker-compose

### Type of the JSON RPC archive node

Plume Testnet

### Type of the chain

L2

### Link to the page

https://testnet-explorer.plumenetwork.xyz/tx/0xb4ae69ac2a6505e3dad3db558ec1128f3437fdca0103aa53dbeec53014659e38

### Backend version

v6.7.2

### Frontend version

3.3.2+93dd5b18

### Elixir & Erlang/OTP versions

Elixir 1.16.1

### Operating system

Windows

### Additional information

**User Agent:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36

**Comment by vbaranov** [comment]
The Blockscout team doesn't manage this instance of the explorer. Please, ask the question to the team, which supports this chain.
