### ISSUE TITLE
Someone illegally logged into my sidra portal and withdrew my tokens

### ISSUE THREAD

**Issue by OuyaEnoch** [blockscout/blockscout#10633]
### Description

0x285a82A8e6c61a636A1210D221d510828Ed820a9

Kindly help me trace the user of this sidra address 
He sent to me a spam link which he used to join my account and withdrew my sidra coins 

### Type of the installation

Manual from the source code

### Type of the JSON RPC archive node

Erigon

### Backend version

V6.1.0

### Elixir & Erlang/OTP versions

Elixir 1.6.13

**Comment by vbaranov** [comment]
This chat is for Blockscout-related questions. Your question is out of scope, where the Blockscout team can help.
