### ISSUE TITLE
Scam token flag and filtering

### ISSUE THREAD

**Issue by NikitaSavik** [blockscout/blockscout#10677]
[Product task](https://www.notion.so/blockscout/b4b4eb6b579048cbb22c52f794537832?v=151e5e91bb06485da5d1cf2c65f484ad&p=5fe329c6d4bd47f4b0e51fa432e0d8ec&pm=c)
In order to support "Hide scam tokens" toggle on the frontend, we need

- new 'spam' flag for token
- - flag should be returned in API requests
- new API handle to update this flag. Protected by API key
- filtering functionality, depending on the frontend cookie presence
- - spam tokens should be hidden from the lists and search but still accessible with direct links

**Comment by alialobidm** [comment]
[](url)
