### ISSUE TITLE
Urgent: Arm64 image not found 

### ISSUE THREAD

**Issue by SagarKarmoker** [blockscout/blockscout#10686]
### Description

linux/Arm64 image not found 

### Type of the installation

Docker-compose

### Type of the JSON RPC archive node

Geth

### Type of the chain

L1

### Backend version

latest

### Elixir & Erlang/OTP versions

latest

### Operating system

linux

**Comment by vbaranov** [comment]
Closing due to no response from the author.

**Comment by SagarKarmoker** [comment]
it was frontend image
