### ISSUE TITLE
Ethereum tokens are not awarded after completing a bridge

### ISSUE THREAD

**Issue by Val-Valentin** [blockscout/blockscout#10696]
### Description

6 days have already passed since the completion of the bridge from the Base network to the B3 network. Perhaps I did something wrong. And all my friends’ tokens were credited with minimal delay. 
<img width="1228" alt="Screenshot at Sep 03 10-15-08" src="https://github.com/user-attachments/assets/e16f1b23-2750-4524-81e5-bfcb0c6f38c7">

### Type of the installation

Helm charts (k8s)

### Type of the JSON RPC archive node

Erigon

### Link to the page

https://explorer.b3.fun/tx/0x8a6686a5aaf7097e957516210d0002ae3d0a89d1cf45d79d0fc28a0a3c469b56?tab=index

### Backend version

v6.7.2

### Frontend version

3.3.2+93dd5b18

### Elixir & Erlang/OTP versions

1/22

### Operating system

macOS

### Additional information

**User Agent:** Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/128.0.0.0 Safari/537.36

**Comment by vbaranov** [comment]
This chat is for Blockscout-related questions. Your question is out of scope, where the Blockscout team can help.
