### ISSUE TITLE
O was not verified and I mistakely contributed 200 SDA. Plz how van I get get my SDA returned.

### ISSUE THREAD

**Issue by Abunaseer1** [blockscout/blockscout#10709]
O was not verified and I mistakely contributed 200 SDA. Plz how van I get get my SDA returned.

_Originally posted by @Ismaildnice in https://github.com/blockscout/blockscout/discussions/10612#discussioncomment-10387922_

**Comment by vbaranov** [comment]
This chat is for Blockscout-related questions. Your question is out of scope, where the Blockscout team can help.
