### ISSUE TITLE
Loss Fund

### ISSUE THREAD

**Issue by RoseGoldWhite** [blockscout/blockscout#10716]
### Description

I sold the boss skin galleon on insta sell for 0.08 eth

### Type of the installation

Docker-compose

### Type of the JSON RPC archive node

OpenEthereum

### Type of the chain

L1

### Link to the page

https://explorer-proofofplay-boss-mainnet.t.conduit.xyz/tx/0x28ee9f62086d159e9e6def12ef3035489e62f49328c4621b861668c27ba5ac4e

### Steps to reproduce

I sold the boss skin galleon on insta sell for 0.08 eth but no eth came to my wallet. This is the Transaction details 
0x28ee9f62086d159e9e6def12ef3035489e62f49328c4621b861668c27ba5ac4e

Here is my wallet address 
0x15C8da3B8c5bEDb9cCFEB33Aa4b3a2F72573d67c

### Backend version

v6.7.2-beta.+commit.8fd2df30

### Frontend version

v1.32.0+b8fedb9a

### Elixir & Erlang/OTP versions

Elixir

### Additional information

**User Agent:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/128.0.0.0 Safari/537.36

**Comment by vbaranov** [comment]
This chat is for Blockscout-related questions. Your question is out of scope, where the Blockscout team can help.
