### ISSUE TITLE
Transaction 

### ISSUE THREAD

**Issue by Ussyofficial** [blockscout/blockscout#10721]
### Description

I send 150 sidra to this  0x0fa370Eb3dDc331FD24837D8b8d737b1d5c3A233 address and it didn't affect in the account 

### Type of the installation

Docker-compose

### Type of the JSON RPC archive node

Erigon

### Type of the chain

L1

### Backend version

6

### Frontend version

1

### Elixir & Erlang/OTP versions

Compiled

### Operating system

Linux

**Comment by vbaranov** [comment]
This chat is for Blockscout-related questions. Your question is out of scope, where the Blockscout team can help.
