### ISSUE TITLE
can't use ENV SESSION_COOKIE_DOMAIN

### ISSUE THREAD

**Issue by Pasha-tort** [blockscout/blockscout#10727]
### Description

Hello
I am not a developer Elixir, so I can't figure out what the problem is myself.
Our team is working with the developments of another team. And we got this stack.
I did some experiments with [this value](https://github.com/blockscout/blockscout/blob/11d6a2e9a93dfb0d2d5a975f778be7d702e67ffb/apps/block_scout_web/lib/block_scout_web/endpoint.ex#L63).
And I came to the conclusion that it works well if you specify this env variable in [the docker file](https://github.com/blockscout/blockscout/blob/master/docker/Dockerfile). And it does not work if you specify this env variable in [this file](https://github.com/blockscout/blockscout/blob/master/docker-compose/envs/common-blockscout.env), it is then equal to nil.
I read that env variables in Elixir are divided into compilation variables and runtime variables. This is clearly a compilation variable. But the thing is that my application has several working environments and for each environment I would like to set a different value.
Also I would not like the docker container build command to specify a value for this variable every time.
My question is:
How can I use this variable in the same code and specify its value in [this file](https://github.com/blockscout/blockscout/blob/master/docker-compose/envs/common-blockscout.env).

I need this variable because my client side application and server side application are hosted on different subdomains and I wanted to use cookies with a password that I could specify in this variable.

### Type of the installation

Docker-compose

### Type of the JSON RPC archive node

dont'now

### Type of the chain

don't now

### Link to the page

there is not

### Steps to reproduce

I can't reproduce it because the code is local to me

### Backend version

6.1.0

### Elixir & Erlang/OTP versions

dont'now

### Operating system

windows

**Comment by GimluCom** [comment]
Duplicate #10728
Please close one of them.

**Comment by Pasha-tort** [comment]
@GimluCom 
i am sorry, I closed the them

**Comment by GimluCom** [comment]
> I would not like the docker container build command to specify a value for this variable every time

It should be sufficient to set the variable in the [`args:`](https://github.com/blockscout/blockscout/blob/v6.8.0-beta/docker-compose/docker-compose.yml#L32-L40) attribute of your compose file.
You may then run `docker compose up -d --build`

**Comment by Pasha-tort** [comment]
it helped me
