### ISSUE TITLE
set CORS origin by using ENV

### ISSUE THREAD

**Issue by Pasha-tort** [blockscout/blockscout#10729]
### Description

Hello
I am not a developer Elixir, so I can't figure out what the problem is myself.
Our team is working with the developments of another team. And we got this stack.

My client application and server application are hosted on different subdomains, so I have cors errors in authorization paths (for example - api/account/v1
/user
/info), due to the header access-control-allow-origin = * and credentials mode = include, and this cannot be done, the browser blocks such requests. I would like to return the access-controll-allow-origin header in such requests and specify the desired domain in it, and take the value for this domain from the env variable.
What I tried to do:
in [this file](https://github.com/blockscout/blockscout/blob/11d6a2e9a93dfb0d2d5a975f778be7d702e67ffb/apps/block_scout_web/lib/block_scout_web/routers/account_router.ex#L124) I tried to create a new pipeline and in it to write rules for domain restriction. This code works well if I write values ​​with the string type (for example - "https://my-domain.com"), but does not work if I try to get values ​​from the ENV variable.
![image](https://github.com/user-attachments/assets/2ac1bbfe-9eca-419e-852a-3329d29d0b69).
How do I use ENV variables correctly?

I read that env variables in Elixir are divided into compilation variables and runtime variables. This is clearly a compilation variable. But the thing is that my application has several working environments and for each environment I would like to set a different value.

I also have a question - how to properly configure the cors for one end point, and not for the scope. For example - api/account/v2/get_csrf

### Type of the installation

Docker-compose

### Type of the JSON RPC archive node

dont'now

### Link to the page

there is not

### Steps to reproduce

I can't reproduce it because the code is local to me

### Backend version

6.1.0

### Elixir & Erlang/OTP versions

dont'now

### Operating system

windows

**Comment by GimluCom** [comment]
Duplicate #10730
Please close one of them.

**Comment by Pasha-tort** [comment]
@GimluCom 
i am sorry, I closed the them

**Comment by GimluCom** [comment]
I believe the recommended setup when using the account feature is to put [a proxy](https://github.com/blockscout/blockscout/blob/v6.8.0-beta/docker-compose/proxy/default.conf.template#L12-L33) in front of the frontend and backend, meaning they both are accessed by the same domain/subdomain.
