### ISSUE TITLE
metrics can not export at port 6060

### ISSUE THREAD

**Issue by caoshanhuyi** [blockscout/blockscout#10720]
### Description

I set envs such as
STATS__METRICS__ENABLED=true
STATS__METRICS__ADDR=0.0.0.0:6060
STATS__METRICS__ROUTE=/metrics

SMART_CONTRACT_VERIFIER__METRICS__ENABLED=false
SMART_CONTRACT_VERIFIER__METRICS__ADDR=0.0.0.0:6060
SMART_CONTRACT_VERIFIER__METRICS__ROUTE=/metrics

USER_OPS_INDEXER__METRICS__ENABLED=true
USER_OPS_INDEXER__METRICS__ADDR=0.0.0.0:6060
USER_OPS_INDEXER__METRICS__ROUTE=/metrics

then i use  "sh -c "bin/blockscout eval \"Elixir.Explorer.ReleaseTasks.create_and_migrate()\" && bin/blockscout start"" to start blockscout service， However, when I access ‘localhost:6006/metrics’, there is no response. I want all metrics to be accessible on port 6060. Is this configuration incorrect?

### Type of the installation

Docker-compose

### Type of the JSON RPC archive node

Geth

### Type of the chain

L2

### Backend version

v6.7.1

### Frontend version

v2.0.6

### Elixir & Erlang/OTP versions

1.14.5-otp-25

### Operating system

macOS

### Additional information

I want to make Prometheus metrics accessible on port 6060, and I configured it according to the environment variable mentioned above, but when I access port 6006, there is no response.

**Comment by GimluCom** [comment]
In your [`services/stats.yml`](https://github.com/blockscout/blockscout/blob/v6.8.0-beta/docker-compose/services/stats.yml#L37-L51) file, add this:
```yml
    ports:
      - target: 6060
        published: 6061
```
and in your [`services/user-ops-indexer.yml`](https://github.com/blockscout/blockscout/blob/v6.8.0-beta/docker-compose/services/user-ops-indexer.yml#L4-L17) file, add this:
```yml
    ports:
      - target: 6060
        published: 6062
```
Then try to access "localhost:6061/metrics" or "localhost:6062/metrics".
