### ISSUE TITLE
Unable to download BONE holder list

### ISSUE THREAD

**Issue by Uzbaba** [blockscout/blockscout#10741]
### Description

Unable to download BONE holder list
Unable to download BONE holder list
Unable to download BONE holder list

Unable to download BONE holder list - to excel

### Type of the installation

Helm charts (k8s)

### Type of the JSON RPC archive node

Geth

### Type of the chain

L2

### Link to the page

https://www.shibariumscan.io/accounts

### Backend version

v6.8.0-beta

### Frontend version

v1.34.0+758ca379

### Elixir & Erlang/OTP versions

Elixir

### Operating system

windows

### Additional information

Unable to download BONE holder list

**Comment by GimluCom** [comment]
Currently Blockscout does not support downloading the list of native coin holders as CSV.
However you may use the [`/api/v2/addresses`](https://www.shibariumscan.io/api-docs#operations-default-get_addresses) API endpoint to fetch addresses holding native coins.
