### ISSUE TITLE
Sidra Chain: <Issue Title>unknown transaction from wallet 

### ISSUE THREAD

**Issue by alifarhan739** [blockscout/blockscout#10769]
*Describe your issue here.*
The transaction occur without my consent is it hacked or something 

### Environment

* Backend Version/branch/commit: v6.8.0-beta
* Frontend Version+commit: 
* User Agent: Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/128.0.0.0 Mobile Safari/537.36

### Steps to reproduce

*Tell us how to reproduce this issue.  ❤️ if you can push up a branch to your fork with a regression test we can run to reproduce locally.*

### Expected behaviour

*Tell us what should happen.*

### Actual behaviour

*Tell us what happens instead.*

**Comment by sl1depengwyn** [comment]
This repo is for Blockscout-related questions. Blockscout is an open source blockchain explorer. Thus, your question is out of scope, where the Blockscout team can help, you better contact the chain support directly.
