### ISSUE TITLE
The problem with updating token balance.

### ISSUE THREAD

**Issue by agnitiy** [blockscout/blockscout#10760]
### Description

Hello, what could be the problem with token balances not updating, even though transactions are immediately visible?
The explorer is connected to our own PolygonEdge sidechain.
![image](https://github.com/user-attachments/assets/11a30cd7-24dd-4e7c-9bbc-25084912fcd1)
![image](https://github.com/user-attachments/assets/1d612692-66da-41f6-b206-becc38e2f705)

### Type of the installation

Docker-compose

### Type of the JSON RPC archive node

PolygonEdge

### Type of the chain

L1

### Backend version

v6.8.0

### Frontend version

v1.31.0-alpha

### Elixir & Erlang/OTP versions

Elixir & Erlang/OTP versions.

### Operating system

Linux

**Comment by vbaranov** [comment]
@agnitiy token balances fetching performance improved in the master branch with these two PRs:  https://github.com/blockscout/blockscout/pull/10694 and https://github.com/blockscout/blockscout/pull/10745. However both not released yet. You can switch to `master` tag of backend Docker image to try them out in action.

**Comment by vbaranov** [comment]
@agnitiy both PR have been included into [6.8.1](https://github.com/blockscout/blockscout/releases/tag/v6.8.1-beta) version.
