### ISSUE TITLE
Sidra Chain: <Issue Title>

### ISSUE THREAD

**Issue by 96279258** [blockscout/blockscout#10768]
I'm in here.Global Logistics Network

September 12Month cast 100 sidra,14th SeptemberTwo strokes were cast in the afternoon, one was 400 sidra, one was 1 sidra, In total, my contribution should be 501 sidra, but it only shows my contribution is 101, which means that one of the 400 is not shown in my contribution total, but the block chain browser has shown your ecological wallet.

**Comment by sl1depengwyn** [comment]
This repo is for Blockscout-related questions. Blockscout is an open source blockchain explorer. Thus, your question is out of scope, where the Blockscout team can help, you better contact the chain support directly.
