### ISSUE TITLE
blockscout can't shutdown normally sometimes

### ISSUE THREAD

**Issue by blockchaindevsh** [blockscout/blockscout#10788]
### Description

<img width="1669" alt="image" src="https://github.com/user-attachments/assets/7cff042b-7b79-4571-8f8a-34c49d2698d8">

### Type of the installation

Docker-compose

### Type of the JSON RPC archive node

Geth

### Type of the chain

L2

### Link to the page

https://explorer.testnet.l2.quarkchain.io

### Steps to reproduce

N/A

### Backend version

https://github.com/blockscout/blockscout/tree/production-optimism

### Elixir & Erlang/OTP versions

docker builtin

**Comment by blockchaindevsh** [comment]
I can't stop the containers with ctrl-c, and have to force it with `docker-compose kill`. It's triggered the first time after running for a long time(several month).

**Comment by GimluCom** [comment]
Which container is not stopping? Is `docker compose down` not working?

Please ensure your version of Docker ![](https://img.shields.io/github/v/tag/docker/cli?label=&color=000000) and Docker Compose ![](https://img.shields.io/github/v/tag/docker/compose?label=&color=000000) are up to date.

**Comment by blockchaindevsh** [comment]
I don't have any more information besides the screenshot above.

According to the screenshot, it seems all 12 containers are stopped, but it doesn't quit, no even if I press ctrl-c.

The versions are as follows:

```bash
# docker version
Client:
 Version:           24.0.5
 API version:       1.43
 Go version:        go1.20.3
 Git commit:        24.0.5-0ubuntu1~22.04.1
 Built:             Mon Aug 21 19:50:14 2023
 OS/Arch:           linux/amd64
 Context:           default

Server:
 Engine:
  Version:          24.0.5
  API version:      1.43 (minimum version 1.12)
  Go version:       go1.20.3
  Git commit:       24.0.5-0ubuntu1~22.04.1
  Built:            Mon Aug 21 19:50:14 2023
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.7.2
  GitCommit:        
 runc:
  Version:          1.1.7-0ubuntu1~22.04.2
  GitCommit:        
 docker-init:
  Version:          0.19.0
  GitCommit:        

# docker-compose version
Docker Compose version v2.26.1
```

**Comment by GimluCom** [comment]
Please try staring with `docker compose up -d` and stopping with `docker compose down`
