### ISSUE TITLE
Pending Tx

### ISSUE THREAD

**Issue by rockmoney** [blockscout/blockscout#10809]
### Description

Tx has been pending for months. From the logs, it fails on last step and gives me the following:

1498775129716509638656

Mode Tokens sent to:

0x3D8250Ac679dcfd1E90c29E7a64AB5013645E579

Tx hash:
0x8614fc8e77109eef5c46f22f02155d8eb5d7041058d9ed2831d7cb2913045451

### Type of the installation

Docker-compose

### Type of the JSON RPC archive node

Unknown

### Type of the chain

Mode

### Link to the page

https://explorer.mode.network/tx/0x8614fc8e77109eef5c46f22f02155d8eb5d7041058d9ed2831d7cb2913045451?tab=logs

### Steps to reproduce

View pending tx for 0x3D8250Ac679dcfd1E90c29E7a64AB5013645E579 

### Backend version

v6.7.2-beta.+commit.dd64f308

### Frontend version

v1.32.0+b8fedb9a

### Elixir & Erlang/OTP versions

Unknown

### Operating system

Linux

### Additional information

**User Agent:** Mozilla/5.0 (Linux; Android 14; SM-S918U1 Build/UP1A.231005.007; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/128.0.6613.146 Mobile Safari/537.36

**Comment by vbaranov** [comment]
The Blockscout team doesn't manage this instance of the explorer. Please, ask the question to the team, which supports this chain.
