### ISSUE TITLE
TX pendiente

### ISSUE THREAD

**Issue by Karttikeyan** [blockscout/blockscout#10839]
### Description

hash 0x0b3861d7b50b65a216fcfa7673528c197abedf7cadce15b7d1a3a653cca43ae0

### Type of the installation

Docker

### Type of the JSON RPC archive node

x

### Link to the page

https://molten.calderaexplorer.xyz/tx/0x0b3861d7b50b65a216fcfa7673528c197abedf7cadce15b7d1a3a653cca43ae0

### Backend version

v6.7.2

### Frontend version

3.3.2+93dd5b18

### Elixir & Erlang/OTP versions

x

### Additional information

**User Agent:** Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:130.0) Gecko/20100101 Firefox/130.0

**Comment by Karttikeyan** [comment]
Transaccion pendiente mas de 16 horas, puente utilizado https://molten.bridge.caldera.xyz/
hash: 0x0b3861d7b50b65a216fcfa7673528c197abedf7cadce15b7d1a3a653cca43ae0 
envio de prueba del token Molten desde la red Molten destino Arbitrum

**Comment by GimluCom** [comment]
This Github is for Blockscout related issues. You should contact caldera about your transaction.
