### ISSUE TITLE
Yet to receive ATH Token in my wallet 

### ISSUE THREAD

**Issue by Almusty254** [blockscout/blockscout#10841]
### Description

Hello admin, I tried transferring my Ath to my wallet address, the first one went successfully, then after trying again the second batch has failed to drop into my wallet. Kindly assist.
0x21aaB3EE875179d230a5d6FD470171089020bFd0
![Screenshot_20240929-143826](https://github.com/user-attachments/assets/9ed73ee5-4e29-4667-8226-cc071c6c8bd5)

### Type of the installation

Manual from the source code

### Type of the JSON RPC archive node

0x21aaB3EE875179d230a5d6FD470171089020bFd0

### Link to the page

https://parthenon.athenescan.io/address/0x21aaB3EE875179d230a5d6FD470171089020bFd0?tab=tokens

### Steps to reproduce

0x21aaB3EE875179d230a5d6FD470171089020bFd0

### Backend version

v6.7.2-beta

### Frontend version

v1.34.1+96191dfb

### Elixir & Erlang/OTP versions

0x21aaB3EE875179d230a5d6FD470171089020bFd0

### Additional information

**User Agent:** Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Mobile Safari/537.36

**Comment by GimluCom** [comment]
This Github repository is for Blockscout related inquiries. Please contact the chain or platform you made the transaction on for help with this issue.
