### ISSUE TITLE
I couldn’t connect  my matchain mini app on telegram to bitget

### ISSUE THREAD

**Issue by Oyeyemi19** [blockscout/blockscout#10840]
### Description

Whenever I tried to connect my matchain to my bitget wallet it’s saying declined

### Type of the installation

Docker-compose

### Type of the JSON RPC archive node

I don’t know 

### Type of the chain

Matchain

### Link to the page

https://matchscan.io/address/0x2CdEdf833BFDFc458Cb7Ea51d01cf047f4EC9936

### Backend version

v6.7.2-beta.+commit.7437aa16

### Frontend version

v1.33.1+cec56f19

### Elixir & Erlang/OTP versions

I don’t know 

### Additional information

**User Agent:** Mozilla/5.0 (iPhone; CPU iPhone OS 11_0 like Mac OS X) MathWallet/1.0 AppleWebKit/604.1.38 (KHTML, like Gecko) Version/13.0 Mobile/15A372 Safari/604.1; BitKeep iOS/8.23.0

**Comment by GimluCom** [comment]
Which device and browser are you using?

**Comment by vbaranov** [comment]
Closing due to no response from the author.
