### ISSUE TITLE
Payment not received 

### ISSUE THREAD

**Issue by Akes12** [blockscout/blockscout#10868]
### Description

I’ve checked multiple times but still no credit in my wallet for this payment

### Type of the installation

Docker-compose

### Type of the JSON RPC archive node

geth

### Backend version

3.0

### Elixir & Erlang/OTP versions

Elixir 1.14.5 Erlang/OTP 25

### Operating system

unix linux

### Additional information

The issue happened at Bahamut Blockscout instance

**Comment by GimluCom** [comment]
Your issue is not related to the Blockscout explorer.
Please contact the platform where you made the transaction to get help with your issue.
