### ISSUE TITLE
Wrong | Duplicate Respone in API 's ETH_LOGS endpoint

### ISSUE THREAD

**Issue by SurenFTN** [blockscout/blockscout#10866]
### Description

While querying https://api.ftnscan.com/api?module=logs&action=getLogs&fromBlock=0&toBlock=latest&address=0xd46abc87e29c1172e9ab8e1149ca70d6ffcd1f7c&topic0=0xedfcc1c7a2b6816d07d82b5efa0a9d4469dcc3cafc5a5faed3dc3d0d94d81960
For the TRX 0x046814be5d4f82a41b76d2a10ea20710978808a610f9766b07917b8f832ea91b the response has duplicate value , only difference is the logIndex but while querying directly to IPC the actual response  is the one which logIndex is 13(0xd) 
I am attaching also responses

### Type of the installation

Manual from the source code

### Type of the JSON RPC archive node

Geth

### Type of the chain

L1

### Link to the page

https://ftnscan.com/

### Backend version

v6.5.0

### Elixir & Erlang/OTP versions

elixir 1.14.5-otp-25  erlang 25.3.2.8

### Operating system

Linux

**Comment by SurenFTN** [comment]
[blockcsout_api_logs.txt](https://github.com/user-attachments/files/17230541/blockcsout_api_logs.txt)
[logs_from_IPC.txt](https://github.com/user-attachments/files/17230543/logs_from_IPC.txt)

**Comment by GimluCom** [comment]
This has likely already been fixed with #10545 
Please check if you are able to reproduce it in v6.8.0 or a later release.

**Comment by SurenFTN** [comment]
@GimluCom While updating to 6.8.1 I have received an error on db .
[error.log](https://github.com/user-attachments/files/17266935/error.log)
Are there any migrations need to be done before switching to 6.8.1

**Comment by GimluCom** [comment]
```sh
mix do ecto.create, ecto.migrate
```
For technical support with deploying it is best to use [Discord](https://discord.gg/blockscout).

**Comment by SurenFTN** [comment]
switching to 6.8.1 solved the issue
