### ISSUE TITLE
I did not receive the withdrawal I took 

### ISSUE THREAD

**Issue by Hamzach02** [blockscout/blockscout#10876]
### Description

I withdraw Ethereum from MetaMask to binnce .But I didn't find my withdraw in binance.

![Screenshot_20241004_160617](https://github.com/user-attachments/assets/85fdcbfd-ad8f-4b73-9f4a-feeae8b67d4b)

### Type of the installation

Docker-compose

### Type of the JSON RPC archive node

Ethereum 

### Type of the chain

From .  .  .  0xE07bA9beC31b34dC72955521aeb507851E3079F5     / (to) .   0x56f3A1CEd7610f8113E9CF399e26c790065eb144 

### Link to the page

https://parthenon.athenescan.io/tx/0xd4f217b0c8f791246da6bf1a15213151cc8d645a21fc5412efd565db971aa9d8?tab=index

### Backend version

v6.7.2-beta

### Frontend version

v1.34.1+96191dfb

### Elixir & Erlang/OTP versions

I don't know 

### Operating system

Android 

### Additional information

**User Agent:** Mozilla/5.0 (Linux; Android 12; vivo 1907_19 Build/SP1A.210812.003; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/129.0.6668.81 Mobile Safari/537.36

**Comment by vbaranov** [comment]
This chat is for Blockscout-related questions. Your question is out of scope, where the Blockscout team can help.

**Comment by Hamzach02** [comment]
My withdrew can't receive
