### ISSUE TITLE
Jogo e carteira b3 

### ISSUE THREAD

**Issue by wilcordeiro** [blockscout/blockscout#10874]
### Description

Ola boa noite eu jogo Etherun blast , ela no jogo tem o botão dessa carteira aparece quanto eu tenho e tem uma conta e uma senha mas não sei o que fazer porquê já procurei nas plataformas do coinbase e não dá pra add essa carteira fui na wallet coinbase crie a carteira conforme o app dos senhores informa mas até agora não aparece o ETH não , o que eu devo fazer, então eu só brasileiro se possível pode responder em português . Agradeço des de já pela compreensão.

### Type of the installation

Manual from the source code

### Type of the JSON RPC archive node

Reth

### Link to the page

https://explorer.b3.fun/address/0x402c1378F194837ddDF35be853b879844eAEa144?tab=token_transfers

### Steps to reproduce

No jogo Etherun blast podia está junto na mesma plataforma porque e complicado saber o que fazer com a informação que dá lá .

### Backend version

V3.06

### Frontend version

3.4.0+b8a163a5f

### Elixir & Erlang/OTP versions

3.0.6(224)

### Operating system

Macos

### Additional information

**User Agent:** Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Mobile Safari/537.36

**Comment by vbaranov** [comment]
This chat is for Blockscout-related questions. Your question is out of scope, where the Blockscout team can help.
