### ISSUE TITLE
My USDT not receive

### ISSUE THREAD

**Issue by Mrprinceprf** [blockscout/blockscout#10873]
### Description

My not receive

### Type of the installation

Docker-compose

### Type of the JSON RPC archive node

0x9098026774ce2e6135ace75e7bd35f99190ff513a64698a26d4b7a6034b4cc21

### Type of the chain

L1

### Link to the page

https://explorer.ebi.xyz/tx/0x9098026774ce2e6135ace75e7bd35f99190ff513a64698a26d4b7a6034b4cc21

### Steps to reproduce

My USD not receive within three days order place

### Backend version

v6.7.2-beta.+commit.8fd2df30

### Frontend version

v1.34.2+7c6bbd78

### Elixir & Erlang/OTP versions

..??

### Operating system

iOS 

### Additional information

**User Agent:** Mozilla/5.0 (iPhone; CPU iPhone OS 18_0 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) CriOS/129.0.6668.69 Mobile/15E148 Safari/604.1

**Comment by vbaranov** [comment]
This chat is for Blockscout-related questions. Your question is out of scope, where the Blockscout team can help.
