### ISSUE TITLE
Bitget connection not responding 

### ISSUE THREAD

**Issue by BBALI2** [blockscout/blockscout#10882]
### Description

I have tried my wallet connection many times but it not responding,I don't know what is wrong 

### Type of the installation

Docker-compose

### Type of the JSON RPC archive node

Bsc

### Link to the page

https://matchscan.io/

### Backend version

v6.7.2-beta.+commit.7437aa16

### Frontend version

v1.34.2+7c6bbd78

### Elixir & Erlang/OTP versions

Otp

### Additional information

**User Agent:** Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.6668.71 Mobile Safari/537.36

**Comment by vbaranov** [comment]
The Blockscout team doesn't manage this instance of the explorer. Please, ask the question to the team, which supports this chain.
