### ISSUE TITLE
I cannot claim the USDT.s tokens from the faucet in SONEFI. 

### ISSUE THREAD

**Issue by Mastan1123360** [blockscout/blockscout#10891]
### Description

 Whenever I try to claim the transaction is failing. I tried more than three times the transaction is failing always. It shows the transaction is replaced or dropped. why can't I claim the tokens from the faucet?
![Screenshot 2024-10-09 184250](https://github.com/user-attachments/assets/3cb097b4-0a29-4451-bd48-43294bdb535c)

### Type of the installation

Docker-compose

### Type of the JSON RPC archive node

Minato ETH

### Link to the page

https://explorer-testnet.soneium.org/tx/0x11e4ed26c875b15d8ae4a9de657ab0f8e50c4ff033b40174776e41cd4020fd3b

### Backend version

v6.7.2-beta

### Frontend version

v1.33.2+089ef89e

### Elixir & Erlang/OTP versions

Elixir

### Operating system

Windows

### Additional information

**User Agent:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36 Edg/129.0.0.0

**Comment by sl1depengwyn** [comment]
This repo is for Blockscout-related questions. Blockscout is an open source blockchain explorer. Thus, your question is out of scope, where the Blockscout team can help, you better contact the chain support directly.
