### ISSUE TITLE
Metadata fetch consistency

### ISSUE THREAD

**Issue by mvanmeerbeck** [blockscout/blockscout#10897]
### Description

Hello,

I'm having consistency issue when minting tokens, blockscout (sepolia) doesn't _always_ display the metadata whereas there is no problem on opensea:
blockscout: https://eth-sepolia.blockscout.com/token/0xc8E55918ec5e3d88EE8Ace3e6EF5E037e607E9bC
opensea: https://testnets.opensea.io/fr/collection/unidentified-contract-6a90e80f-0552-48f6-854e-673c

Also, I noticed the button to refresh the metadata on blockscout is not there if it was not initially indexed.
(https://github.com/blockscout/blockscout/pull/10878 ?)

Is there a problem with my metadata or with blockscout indexing ?

Thank you for your help

#10795 looks related

### Type of the installation

Helm charts (k8s)

### Type of the JSON RPC archive node

Geth

### Type of the chain

Sepolia

### Link to the page

https://eth-sepolia.blockscout.com/token/0xc8E55918ec5e3d88EE8Ace3e6EF5E037e607E9bC

### Backend version

v6.8.1-beta

### Frontend version

v1.35.0

### Elixir & Erlang/OTP versions

I don't know

### Operating system

Linux

**Comment by vbaranov** [comment]
> Also, I noticed the button to refresh the metadata on blockscout is not there if it was not initially indexed.
(https://github.com/blockscout/blockscout/pull/10878 ?)

We extended area of ​​action for "Refresh metadata" button - it is currently can be used even if the metadata is not initialized for the NFT. For the NFT collection, which you mentioned, almost all images fetched except 2 items - and those 2 contain broken link to the image. Please let me know if you still experience issues with other collections.
