### ISSUE TITLE
Issue with transaction 

### ISSUE THREAD

**Issue by Trooper2090** [blockscout/blockscout#10896]
### Description

I have an issue with transaction done 
Transaction feom Bnb match chain to bnb base an still not shown to the other wallet 

### Type of the installation

Manual from the source code

### Type of the JSON RPC archive node

Transaction 

### Type of the chain

Wallet 

### Link to the page

https://www.matchscan.io/tx/0xc36f0913c21257cbb99dd8a6f3bee731e208bd1c2074e16c9daffcb1e806cdb0

### Steps to reproduce

I have an issue with transaction done 
Transaction feom Bnb match chain to bnb base an still not shown to the other wallet 

### Backend version

v6.7.2-beta.+commit.7437aa16

### Frontend version

v1.35.0+a9d18fbe

### Elixir & Erlang/OTP versions

Transaction 

### Operating system

Transaction 

### Additional information

**User Agent:** Mozilla/5.0 (Linux; Android 6.0; Nexus 5 Build/MRA58N) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/115.0.0.0 Mobile Safari/537.36; BitKeep Android/8.23.0

**Comment by sl1depengwyn** [comment]
This repo is for Blockscout-related questions. Blockscout is an open source blockchain explorer. Thus, your question is out of scope, where the Blockscout team can help, you better contact the chain support directly.
