### ISSUE TITLE
problem with exchange

### ISSUE THREAD

**Issue by zaushichin** [blockscout/blockscout#10892]
### Description

0xbb5a0f301a40e67dcb0c876ed1e609204e72ac11908f5a36f55849ba247b66a6
0x279e1bb665d49ecdfc1a97bbce2d8b0dee18fb546a9ff1e7a0a64f478200667a
transaction is not processed for more than 7 hours, tokens have not arrived in 0x8A92e1E34E991cE8d6c8778CE7A93635607843db

### Type of the installation

Docker-compose

### Type of the JSON RPC archive node

Zeta

### Type of the chain

L2

### Link to the page

https://zetachain.blockscout.com/token/0x306b45478294166931998d34a3d87ebe2c54657d/instance/1385

### Steps to reproduce

0xbb5a0f301a40e67dcb0c876ed1e609204e72ac11908f5a36f55849ba247b66a6
0x279e1bb665d49ecdfc1a97bbce2d8b0dee18fb546a9ff1e7a0a64f478200667a
transaction is not processed for more than 7 hours, tokens have not arrived in 0x8A92e1E34E991cE8d6c8778CE7A93635607843db

### Backend version

v6.8.1-beta

### Frontend version

v1.35.0+a9d18fbe

### Elixir & Erlang/OTP versions

Elixir и Erlang/OTP

### Operating system

windows

### Additional information

**User Agent:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36

**Comment by GimluCom** [comment]
Your question is not related to the Blockscout explorer, please instead contact the exchange you have used.
