### ISSUE TITLE
Token failed to reflect to my account 

### ISSUE THREAD

**Issue by Obwocha3457** [blockscout/blockscout#10899]
### Description

I sent world coin to my binance account but it did not reflect at all since morning . 

### Type of the installation

Docker-compose

### Type of the JSON RPC archive node

Polygon edge 

### Type of the chain

L1/L2

### Link to the page

https://worldchain-mainnet.explorer.alchemy.com/tx/0x044613b8702bbd80f9b33bcaf9f773841bd37d33ec6b4d32a9355340ade85b53

### Steps to reproduce

If it is possible please return it to the sender .
I sent it from a world coin app . 

### Backend version

v6.8.1-beta

### Frontend version

v1.35.1+2ce0c41e

### Elixir & Erlang/OTP versions

Otp version 

### Operating system

Macos

### Additional information

**User Agent:** Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/127.0.0.0 Mobile Safari/537.36

**Comment by Elvischege** [comment]
0x044613b8702bbd80f9b33bcaf9f773841bd37d33ec6b4d32a9355340ade85b53

 help how to trace the tokens on binance

**Comment by sl1depengwyn** [comment]
This repo is for Blockscout-related questions. Blockscout is an open source blockchain explorer. Thus, your question is out of scope, where the Blockscout team can help, you better contact the chain support directly.
