### ISSUE TITLE
Create a config file for when a user deploys explorer on a new chain

### ISSUE THREAD

**Issue by acravenho** [blockscout/blockscout#109]
We will need to implement this config file throughout the frontend to match certain aspects such as symbol, logo, endpoint, ect...

This config file will have the following elements and more to come:

- Chain name
- Symbol
- RPC Endpoint
- Coinmarketcap api data
- Trading view data for homepage graph
- Logo
- Skin colors 
- Validated (Validator)/ Mined (Miner)
- Unit of Measure (POA, ETH)

**Comment by acravenho** [comment]
I think adding the variables to `apps/explorer/config/dev.secret.exs` and `apps/explorer_web/config/dev.secret.exs` files accordingly would work.

**Comment by acravenho** [comment]
As @KronicDeth mentioned, this file should also include `unit of measure` (i.e. POA, ETH, ect..)

**Comment by jimmay5469** [comment]
When we do this work we should restructure the README to include instructions on how to use/deploy for a new sidechain at the top of the README and move the current README into a `Contributing` section at the bottom.

**Comment by KronicDeth** [comment]
@jimmay5469 we can break the `Contributing` section into a `CONTRIBUTING.md` and GitHub will pick it up and link to it when people open PRs.  We could leave a `Contributing` section in the README only to link to that file for people that don't know to look for a `CONTRIBUTING.md` file in GitHub repos.

**Comment by ulyanas** [comment]
Implemented via Front-end and Back-end ENVs 
https://github.com/blockscout/frontend/blob/main/docs/ENVS.md 
https://github.com/blockscout/blockscout?tab=readme-ov-file
