### ISSUE TITLE
Funds Not Reflect on my Binance Account

### ISSUE THREAD

**Issue by ansh1733** [blockscout/blockscout#10900]
### Description

I sent world coin to my binance account but it did not reflect at all since 2 Hours. 
![Screenshot_20241012-221215](https://github.com/user-attachments/assets/bc1ae79a-5c2b-4987-b5aa-3b5b50fe14af)
![Screenshot_20241012-222052](https://github.com/user-attachments/assets/1d0b9382-9d2c-4819-b311-b872a8886fae)

### Type of the installation

Docker-compose

### Type of the JSON RPC archive node

Polygon

### Type of the chain

L1/L2...

### Steps to reproduce

Please check and review my funds are not reflect on my binance account hope it will retrive successfull. 

### Backend version

v6. 1.0

### Frontend version

Mobile Phone

### Elixir & Erlang/OTP versions

OTP version

### Operating system

Mobile

### Additional information

I sent world coin to my binance account but it did not reflect at all since morning .
![Screenshot_20241012-221215](https://github.com/user-attachments/assets/8cae8b53-573b-459c-ac96-7a60644c5a55)
![Screenshot_20241012-222302](https://github.com/user-attachments/assets/8973392e-23dd-46ca-a2e4-6f13303983f0)

**Comment by sl1depengwyn** [comment]
This repo is for Blockscout-related questions. Blockscout is an open source blockchain explorer. Thus, your question is out of scope, where the Blockscout team can help, you better contact the chain support directly.
