### ISSUE TITLE
transferencia no realizada

### ISSUE THREAD

**Issue by diego2024753** [blockscout/blockscout#10904]
### Description

hice una transferencia de la moneda wld a binance y no me llego todavia 

### Type of the installation

Docker-compose

### Type of the JSON RPC archive node

.

### Type of the chain

.

### Link to the page

https://worldchain-mainnet.explorer.alchemy.com/tx/0x1f5735b74fcd8e71fa605f9cba42a8617fc5ecc0d6ac5a34e394d7e5b1ed3c6e

### Steps to reproduce

retire mis monedas de worldcoin hacia mi binance y todavia no llego

### Backend version

v6.8.1-beta

### Frontend version

v1.35.1+2ce0c41e

### Elixir & Erlang/OTP versions

.

### Operating system

.

### Additional information

**User Agent:** Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Mobile Safari/537.36

**Comment by sl1depengwyn** [comment]
This repo is for Blockscout-related questions. Blockscout is an open source blockchain explorer. Thus, your question is out of scope, where the Blockscout team can help, you better contact the chain support directly.
