### ISSUE TITLE
Transaction shows success but deposit hasn't arrived in my wallet four hours later 

### ISSUE THREAD

**Issue by Josephbuuri** [blockscout/blockscout#10903]
### Description

Transaction shows success but deposit hasn't arrived in my wallet four hours later.The withdrawal was to an optimism address.The hash transaction is as follows:
0xc5d8f0739f7cf53d1043690143e4075c803f381dc80c1b868e754b8b5704b0cd
![Screenshot_2024-10-13-13-18-04-371_com android chrome](https://github.com/user-attachments/assets/98fd0e42-5aba-43c9-ae19-5474da147186)

### Type of the installation

Docker-compose

### Type of the JSON RPC archive node

https://testnode.dioneprotocol.com/ext/bc/D/rpc

### Type of the chain

L1/L2...

### Link to the page

https://worldchain-mainnet.explorer.alchemy.com/tx/0xc5d8f0739f7cf53d1043690143e4075c803f381dc80c1b868e754b8b5704b0cd

### Steps to reproduce

Transaction shows success but deposit hasn't arrived in my wallet four hours later.The withdrawal was to an optimism address.The hash transaction is as follows:
0xc5d8f0739f7cf53d1043690143e4075c803f381dc80c1b868e754b8b5704b0cd
![Screenshot_2024-10-13-13-18-04-371_com android chrome](https://github.com/user-attachments/assets/2458c8cc-179a-4e4e-bd68-5db48a2fe324)

### Backend version

v6.8.1-beta

### Frontend version

v1.35.1+2ce0c41e

### Elixir & Erlang/OTP versions

No response 

### Operating system

Android version 13

### Additional information

**User Agent:** Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Mobile Safari/537.36

**Comment by sl1depengwyn** [comment]
This repo is for Blockscout-related questions. Blockscout is an open source blockchain explorer. Thus, your question is out of scope, where the Blockscout team can help, you better contact the chain support directly.

**Comment by Josephbuuri** [comment]
Thanks a lot for your help how do I contact the chain support?
