### ISSUE TITLE
Transaction problem 

### ISSUE THREAD

**Issue by Shan370** [blockscout/blockscout#10909]
### Description

Description
I recently used the World App to transfer WLD coins to my boyfriend 's account via the Optimism network, intending for them to reach his   binance account. However, I wasn’t aware that the account had been switched to the World Chain. The transaction shows as successful, but my boyfriend has yet to receive the funds. The address used was correct and linked to his  binance account, but when I checked the transaction details on the World Chain, it appeared that there were no funds in that account. Could you please help me retrieve or reverse the transaction?

### Type of the installation

Manual from the source code

### Type of the JSON RPC archive node

OpenEthereum 

### Type of the chain

L2

### Link to the page

0x957f201075970f71f0a4e22be9dae50ab9c2fa52

### Backend version

V.6.8.1- beta

### Frontend version

V1.35.1

### Elixir & Erlang/OTP versions

OTP versions

### Operating system

Android 

### Additional information

![Screenshot_2024-10-14-18-27-41-760_com worldcoin](https://github.com/user-attachments/assets/1b562d52-37e4-437d-826c-c54cd7811b91)

**Comment by sl1depengwyn** [comment]
This repo is for Blockscout-related questions. Blockscout is an open source blockchain explorer. Thus, your question is out of scope, where the Blockscout team can help, you better contact the chain support directly.
