### ISSUE TITLE
docker compose failing on start with stats error

### ISSUE THREAD

**Issue by Chuseuiti** [blockscout/blockscout#10902]
### Description

After cloning the repo and running:

`docker compose up --build`

The logs display the following error:

```
user-ops-indexer                | 2024-10-13T12:02:47.422204Z  INFO sea_orm_migration::migrator: Applying migration 'm20220101_000001_initial_tables'
db                              | 2024-10-13 12:02:47.425 UTC [30] LOG:  unexpected EOF on client connection with an open transaction
user-ops-indexer                | Error: Migration Error: Table blocks does not exist in the database
user-ops-indexer exited with code 1
stats-db                        | 2024-10-13 12:02:48.570 UTC [51] ERROR:  database "stats" already exists

```

Also the following error appears:

My understanding is that it is related to the stats incorrect initialization:
```

stats                           | 2024-10-13T12:02:48.770222Z ERROR stats_server: service failed with error: Blockscout API URL has not been provided. Please specify it with corresponding env variable (`STATS__BLOCKSCOUT_API_URL`) or set `STATS__IGNORE_BLOCKSCOUT_API_ABSENCE=true` to disable functionality depending on the API.    
stats                           | Error: Blockscout API URL has not been provided. Please specify it with corresponding env variable (`STATS__BLOCKSCOUT_API_URL`) or set `STATS__IGNORE_BLOCKSCOUT_API_ABSENCE=true` to disable functionality depending on the API.
```

`backend                         | {"time":"2024-10-13T12:12:10.650Z","severity":"error","message":"Could not create schema migrations table. This error usually happens due to the following:\n\n  * The database does not exist\n  * The \"schema_migrations\" table, which Ecto uses for managing\n    migrations, was defined by another library\n  * There is a deadlock while migrating (such as using concurrent\n    indexes with a migration_lock)\n\nTo fix the first issue, run \"mix ecto.create\" for the desired MIX_ENV.\n\nTo address the second, you can run \"mix ecto.drop\" followed by\n\"mix ecto.create\", both for the desired MIX_ENV. Alternatively you may\nconfigure Ecto to use another table and/or repository for managing\nmigrations:\n\n    config :explorer, Explorer.Repo,\n      migration_source: \"some_other_table_for_schema_migrations\",\n      migration_repo: AnotherRepoForSchemaMigrations\n\nThe full error report is shown below.\n","metadata":{}}`

The result is that the localhost frontend doesnt display any content:

![blockscout](https://github.com/user-attachments/assets/36643302-7dd7-4c57-a34b-33efe723cf91)

### Type of the installation

Docker-compose

### Type of the JSON RPC archive node

Ganache

### Type of the chain

Arbitrum

### Steps to reproduce

Run:

`docker compose up --build`

### Backend version

master

### Frontend version

master

### Elixir & Erlang/OTP versions

Elixir 1.13.4 (compiled with Erlang/OTP 25)

### Operating system

Linux

**Comment by GimluCom** [comment]
The stats microservice is likely not the cause of an issue with the main page.
We recommend using the [Discord server](https://discord.gg/blockscout) for assistance with deploying Blockscout.
