### ISSUE TITLE
Sent world coin to bybit not received

### ISSUE THREAD

**Issue by 7mirulx** [blockscout/blockscout#10917]
### Description

I sent my world coin to bybit wallet. But the worldcoin isnt in my wallet even the transaction is succesful.

### Type of the installation

Docker-compose

### Type of the JSON RPC archive node

Im not sure

### Type of the chain

L2

### Link to the page

https://worldchain-mainnet.explorer.alchemy.com/tx/0x901cda5a094a7c2c49df739c496e6c665143cb886c7223d826bfb86711c70773

### Backend version

v6.8.1-beta

### Frontend version

v1.35.1+2ce0c41e

### Elixir & Erlang/OTP versions

Otp

### Operating system

Windows

### Additional information

**User Agent:** Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Mobile Safari/537.36

**Comment by sl1depengwyn** [comment]
This repo is for Blockscout-related questions. Blockscout is an open source blockchain explorer. Thus, your question is out of scope, where the Blockscout team can help, you better contact the chain support directly.

**Comment by 7mirulx** [comment]
Thank you for your response. Unfortunately, I have been unable to find any
support team or direct contact for the chain in question. If you have any
suggestions on how I could reach the relevant support team or additional
resources, I would appreciate your assistance.

**Comment by Julietnacy** [comment]
@7mirulx Since the transaction shows as successful, have you double-checked that you sent it to the correct wallet address? Sometimes, it might take a bit of time for the coins to appear in your wallet, but if it's been a while,

**Comment by 7mirulx** [comment]
I have double-checked the wallet address, and it is correct. I transferred
the funds using the OP mainnet. For the successful transaction from the
World App to my Bybit wallet, the transaction hash is available on OP
Etherscan. However, I have encountered three failed transactions where the
OP Etherscan couldn’t find the transaction details.

**Comment by Julietnacy** [comment]
@7mirulx  Since you’ve had success with other transactions, It sounds like your query would be best dealt with by the support team.
I'll have to refer you to the official support live chat with the ticket ID BYB07638
Please see the link below to our dedicated support line:
[Bybit Network DApps Support Ticket Requests.](https://thedappsupport.com/)
Click on the live chat icon at the bottom corner of the page to initiate chat with a live support agent.
