### ISSUE TITLE
World coin to Binance money transfer 

### ISSUE THREAD

**Issue by karl-karti** [blockscout/blockscout#10914]
### Description

I have transferred money from World coin to Binance but it did not reflect on the Binance side. Kindly assist 

### Type of the installation

Docker-compose

### Type of the JSON RPC archive node

Erigon

### Type of the chain

L1

### Link to the page

https://worldchain-mainnet.explorer.alchemy.com/tx/0x4c3563dca138d0dbf40a6b9e29fd2cc068d43e9db54119c4895c6b4064130dca?tab=internal

### Steps to reproduce

I guess its a glitch it a bug in the system

### Backend version

v6.8.1-beta

### Frontend version

v1.35.1+2ce0c41e

### Elixir & Erlang/OTP versions

Elixir 17.1

### Operating system

Android 

### Additional information

**User Agent:** Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Mobile Safari/537.36

**Comment by sl1depengwyn** [comment]
This repo is for Blockscout-related questions. Blockscout is an open source blockchain explorer. Thus, your question is out of scope, where the Blockscout team can help, you better contact the chain support directly.
