### ISSUE TITLE
La transacción se marcó como exitosa en la aplicación worldcoin pero no llegó a la billetera de Binance.

### ISSUE THREAD

**Issue by Johanvilla892** [blockscout/blockscout#10928]
### Description

La transacción se marcó como exitosa en la aplicación worldcoin pero no llegó a la billetera de Binance.

### Type of the installation

Manual from the source code

### Type of the JSON RPC archive node

Op

### Type of the chain

Nivel 1

### Link to the page

https://worldchain-mainnet.explorer.alchemy.com/tx/0x2ca8894f67128410c408c35570432a6eaa6bcb8a485fe044985e624c3a82d8ee

### Steps to reproduce

Devolviendo las monedas o haciendo que lleguen a la billetera de binance 
![Screenshot_2024-10-15-15-05-21-790_com worldcoin](https://github.com/user-attachments/assets/2a4d7ec1-c174-4015-afe2-4d3eb3919185)

### Backend version

v6.8.1-beta

### Frontend version

v1.35.1+2ce0c41e

### Elixir & Erlang/OTP versions

Elixir 1.17.3

### Operating system

Windows 

### Additional information

**User Agent:** Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Mobile Safari/537.36

**Comment by GimluCom** [comment]
This repository is for Blockscout related inqueries.

Ha contactado a Blockscout. No gestionamos transacciones. Por favor, contacte al soporte de la plataforma que estaba utilizando para asistencia con su problema.
