### ISSUE TITLE
Sent WLD not recieved by the reciever

### ISSUE THREAD

**Issue by chinmayk6363** [blockscout/blockscout#10923]
### Description

I sent 10 WLD to my friend through optimism wallet, but the sent amount isn't received. It's reflecting in my history, but not found in his history. The optimism wallet address is right and there's no human error. The transaction hash is 0x66e4b7148ca4f3662cb3f5d393cbf89e951302f9b2381035998bf47fdab5fbec . Can you please find what's the mistake here and find us the lost amount...?

### Type of the installation

Docker-compose

### Type of the JSON RPC archive node

Don't know 

### Type of the chain

Don't know 

### Link to the page

https://worldchain-mainnet.explorer.alchemy.com/tx/0x66e4b7148ca4f3662cb3f5d393cbf89e951302f9b2381035998bf47fdab5fbec?tab=index

### Steps to reproduce

...

### Backend version

v6.8.1-beta 

### Frontend version

v1.35.1+2ce0c41e

### Elixir & Erlang/OTP versions

Don't know 

### Operating system

Android 

### Additional information

**User Agent:** Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Mobile Safari/537.36

**Comment by sl1depengwyn** [comment]
This repo is for Blockscout-related questions. Blockscout is an open source blockchain explorer. Thus, your question is out of scope, where the Blockscout team can help, you better contact the chain support directly.
