### ISSUE TITLE
BTCNXT Launch

### ISSUE THREAD

**Issue by Vasuak** [blockscout/blockscout#10926]
### Description

Dear Sir, 
You are taking so many more times to the BTCNXT launch. Please let us know when it will be launched, and we can transfer, tell me how to create a wallet as well.

### Type of the installation

Manual from the source code

### Type of the JSON RPC archive node

BTCNXT

### Link to the page

https://bnxtscan.com/

### Steps to reproduce

Please reply.

### Backend version

v6.8.1-beta

### Frontend version

v1.34.1+96191dfb

### Elixir & Erlang/OTP versions

BTCNXT

### Additional information

**User Agent:** Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36
we are waiting.

**Comment by vbaranov** [comment]
The Blockscout team doesn't manage this instance of the explorer. Please, ask the question to the team, which supports this chain.
