### ISSUE TITLE
Wordcoin 

### ISSUE THREAD

**Issue by Tatiana-1709** [blockscout/blockscout#10920]
### Description

Hola buenas tardes yo envié 6 monedas wordcoin a esta dirección 0x718e445fc992e22ce9b40c46e3f80bb9490d61c2 
Pero nunca llegó quería que me solucionen el problema o me devuelvan las monedas wordcoin por favor y gracias 

### Type of the installation

Docker-compose

### Type of the JSON RPC archive node

Jb

### Type of the chain

Nivel 1 

### Link to the page

https://worldchain-mainnet.explorer.alchemy.com/address/0x718e445fC992E22CE9b40c46e3f80bB9490D61c2

### Backend version

v6.8.1-beta

### Frontend version

v1.35.1+2ce0c41e

### Elixir & Erlang/OTP versions

B

### Operating system

Windows 

### Additional information

**User Agent:** Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Mobile Safari/537.36

**Comment by vbaranov** [comment]
This chat is for Blockscout-related questions. Your question is out of scope, where the Blockscout team can help.
