### ISSUE TITLE
Envío de WLD Coin a BINANCE Billetera

### ISSUE THREAD

**Issue by KitsuneChrise** [blockscout/blockscout#10921]
### Description

Envié  15 de octubre de 2024 15:58:23 p.m. WLD 21 Coins a BINANCE y los WLD no me aparecen en la Billetera solicitud saber dodne estan mis coins. 

WLD
0x96f52b4e4d3634675bb1788f58c26adad1d5853a

BINANCE 
0xa9908f7b4a481b32af030dbe947948f048d7b5cc

Hash Transacción WORLDCHAIN
0xc7a4da08b5dba9e1af9e3a75e4825de16c28a71dff8bbf3e52f3943247e5c264

Todo fue por Optimist, espero una pronta respuesta porfavor 

Gracias 
![Screenshot_2024-10-15-19-09-18-730_com worldcoin](https://github.com/user-attachments/assets/8e0bf1a2-8838-4491-9aa4-9a59bdc8756d)
![Screenshot_2024-10-15-19-09-38-017_com android chrome](https://github.com/user-attachments/assets/efe7d501-63af-443f-a3a5-c1b772c513dd)

### Type of the installation

Docker-compose

### Type of the JSON RPC archive node

BINANCE 

### Type of the chain

WLD

### Link to the page

https://worldchain-mainnet.explorer.alchemy.com/tx/0xc7a4da08b5dba9e1af9e3a75e4825de16c28a71dff8bbf3e52f3943247e5c264

### Steps to reproduce

Enviar a mi correo ctckitsune@gmail.com

### Backend version

v6.8.1-beta

### Frontend version

v1.35.1+2ce0c41e

### Elixir & Erlang/OTP versions

Elixir

### Operating system

Windows 

### Additional information

**User Agent:** Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, 
![Screenshot_2024-10-15-19-09-38-017_com android chrome](https://github.com/user-attachments/assets/0d786624-0294-4034-9ced-77d8a258116b)
![Screenshot_2024-10-15-19-11-24-724_com android chrome](https://github.com/user-attachments/assets/95c519c2-f656-40f8-9aad-7e823944f3a4)
![Screenshot_2024-10-15-19-09-18-730_com worldcoin](https://github.com/user-attachments/assets/36b4a397-7d1a-422b-9e28-a945f215ce3d) Gecko) Chrome/129.0.0.0 Mobile Safari/537.36

**Comment by Franciscop2105** [comment]
Buenas, te dieron alguna respuesta sobre esto? Me pasó exactamente lo mismo y veo q hay muchos le pas igual.. saludos

**Comment by sl1depengwyn** [comment]
This repo is for Blockscout-related questions. Blockscout is an open source blockchain explorer. Thus, your question is out of scope, where the Blockscout team can help, you better contact the chain support directly.
