### ISSUE TITLE
Error de transacción 

### ISSUE THREAD

**Issue by Facudr97** [blockscout/blockscout#10922]
### Description

Necesito el reintegro de la transacción ya que quedó las monedas perdidas y necesito recibirlas nuevamente 

### Type of the installation

Docker-compose

### Type of the JSON RPC archive node

Geth

### Link to the page

https://worldchain-mainnet.explorer.alchemy.com/tx/0xe9eff6154029d80e6c4ad94a687764320d561cde28bed7c59ddeb72abfed6097?tab=state

### Backend version

v6.8.1-beta

### Frontend version

v1.35.1+2ce0c41e

### Elixir & Erlang/OTP versions

Elixir

### Operating system

Windows

### Additional information

**User Agent:** Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Mobile Safari/537.36

**Comment by sl1depengwyn** [comment]
This repo is for Blockscout-related questions. Blockscout is an open source blockchain explorer. Thus, your question is out of scope, where the Blockscout team can help, you better contact the chain support directly.
