### ISSUE TITLE
Uncredited deposit 

### ISSUE THREAD

**Issue by Kenyanlad** [blockscout/blockscout#10925]
### Description

The transaction is marked success in the worldcoin app but did not reach the binance wallet

### Type of the installation

Manual from the source code

### Type of the JSON RPC archive node

Optimism

### Type of the chain

L1

### Link to the page

https://worldchain-mainnet.explorer.alchemy.com/tx/0x5b4aecde54ddf479db2de89cd6062e51bc1378258da67d7577bb0e61b4e7fd5d

### Steps to reproduce

Get the funds back to worldcoin 

### Backend version

V6.1.0

### Frontend version

V1.11.1

### Elixir & Erlang/OTP versions

Elixir 

### Operating system

Windows

### Additional information

The transaction was a success

**Comment by vbaranov** [comment]
This chat is for Blockscout-related questions. Your question is out of scope, where the Blockscout team can help.

**Comment by Kenyanlad** [comment]
I really don't understand what you mean but I just hoped I could get some
help
