### ISSUE TITLE
Transaction from world app to binance not successful 

### ISSUE THREAD

**Issue by nganga-254** [blockscout/blockscout#10930]
### Description

I sent money from world app to binance in this address 0xB0b8c2F6BDd692D1a610e441B49a7F3f518084b7
Transaction hash was
0x8036bb3ecba7481a3d5c24286646b8b1cca4caf7cb0d996ed21effc2268cde32
I need your help to retrieve the money since I can't find them on my binance account. 

### Type of the installation

Docker-compose

### Type of the JSON RPC archive node

Erigon

### Type of the chain

L1

### Link to the page

https://worldchain-mainnet.explorer.alchemy.com/tx/0x8036bb3ecba7481a3d5c24286646b8b1cca4caf7cb0d996ed21effc2268cde32

### Steps to reproduce

Copy the issue and then paste it

### Backend version

v6.8.1-beta

### Frontend version

v1.35.1+2ce0c41e

### Elixir & Erlang/OTP versions

Elixir

### Operating system

Windows

### Additional information

**User Agent:** Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Mobile Safari/537.36

**Comment by sl1depengwyn** [comment]
This repo is for Blockscout-related questions. Blockscout is an open source blockchain explorer. Thus, your question is out of scope, where the Blockscout team can help, you better contact the chain support directly.
