### ISSUE TITLE
problema para recibir monedas en plataforma de binance 

### ISSUE THREAD

**Issue by grc288** [blockscout/blockscout#10931]
### Description

![Captura de pantalla 2024-10-16 145307](https://github.com/user-attachments/assets/2002714a-f3ff-42dd-ab8a-2d612827c06e)

### Type of the installation

Docker-compose

### Type of the JSON RPC archive node

eth

### Type of the chain

nivel 1

### Link to the page

https://worldchain-mainnet.explorer.alchemy.com/address/0xAA7A70839B3CacC8943E6C95fD4742493cE75d8F?tab=token_transfers

### Backend version

v6.8.1-beta

### Frontend version

v1.35.1+2ce0c41e

### Elixir & Erlang/OTP versions

elixir

### Additional information

![Captura de pantalla 2024-10-16 145307](https://github.com/user-attachments/assets/ac62998a-cb47-4dd6-9751-57f400b31bed)

**Comment by Onasisb** [comment]
A mi tampoco me ha llegado mis monedas a Binance, ayuda
![Screenshot_20241016_193405_Chrome](https://github.com/user-attachments/assets/67ea9174-b7e2-4598-962d-7af1ad6edb6b)

**Comment by GimluCom** [comment]
https://github.com/blockscout/blockscout/issues/10928#issuecomment-2417168260
