### ISSUE TITLE
Word coin o token

### ISSUE THREAD

**Issue by Jhonn32** [blockscout/blockscout#10948]
### Description

Hola el dia de ayer realice una transferencia el cual no llego a la billetera, los datos son correctos al envió, pero este nunca llegaron 
![Screenshot_20241018_094348_World App](https://github.com/user-attachments/assets/5fd63721-8384-4943-881f-4a6624d3577d)

### Type of the installation

Manual from the source code

### Type of the JSON RPC archive node

0xa49dd922f6d77e0d2e282c1091540417f2e999d6

### Type of the chain

Nivel 1

### Link to the page

https://worldchain-mainnet.explorer.alchemy.com/block/4940893

### Backend version

v6.8.1-beta

### Frontend version

v1.35.2+08de20eb

### Elixir & Erlang/OTP versions

0xa49dd922f6d77e0d2e282c1091540417f2e999d6

### Additional information

**User Agent:** Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Mobile Safari/537.36

**Comment by GimluCom** [comment]
Please read this comment: https://github.com/blockscout/blockscout/issues/10928#issuecomment-2417168260
