### ISSUE TITLE
quiero saber que paso con la trancicion 

### ISSUE THREAD

**Issue by daniel200222** [blockscout/blockscout#10945]
### Description

nunca llego a destino 
![Screenshot_20241015-231342](https://github.com/user-attachments/assets/62a8af5c-3562-4db7-8a54-8afaeff7679b)
![Screenshot_20241015-231150](https://github.com/user-attachments/assets/8d64f8e4-6eaf-49a0-a502-0b6453f7823d)

### Type of the installation

Docker-compose

### Type of the JSON RPC archive node

jsonrpc

### Type of the chain

nivel1

### Link to the page

https://worldchain-mainnet.explorer.alchemy.com/tx/0x364234eb4414127aab7d4c91cb2a8d8f875b5134548bfe4a1f950c5ecfd08730

### Steps to reproduce

quiero una solucion

### Backend version

v6.8.1-beta

### Frontend version

v1.35.2+08de20eb

### Elixir & Erlang/OTP versions

estaria buenonsaber 

### Operating system

linux debe ser 

### Additional information

**User Agent:** Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Mobile Safari/537.36

**Comment by daniel200222** [comment]
![Screenshot_20241018-093516](https://github.com/user-attachments/assets/0cb484e2-3930-4a4e-991b-5d8751b9d698)

**Comment by GimluCom** [comment]
Please read this comment: https://github.com/blockscout/blockscout/issues/10928#issuecomment-2417168260
