### ISSUE TITLE
Para çekimi neden yapılmıyor 

### ISSUE THREAD

**Issue by Akpolat7900** [blockscout/blockscout#10940]
### Description

Bahamut hesabımda 39 ftn var çekim yapamıyorum 

### Type of the installation

Docker-compose

### Type of the JSON RPC archive node

geth

### Type of the chain

L1

### Link to the page

https://ocean.ftnscan.com/pending-transactions

### Steps to reproduce

Çekim yapamıyorum ya 

### Backend version

3.0

### Elixir & Erlang/OTP versions

Elixir 1.14.5 Erlang/OTP 25

### Operating system

unix linux

### Additional information

The issue happened at Ocean Blockscout instance

**Comment by vbaranov** [comment]
This chat is for Blockscout-related questions. Your question is out of scope, where the Blockscout team can help.
