### ISSUE TITLE
Cryptocurrency worldcoin

### ISSUE THREAD

**Issue by 0794183371** [blockscout/blockscout#10941]
### Description

I sent a worldcoin token to a wrong binance address, please,  help me reverse the coins to my worl coin app

### Type of the installation

Docker-compose

### Type of the JSON RPC archive node

PolygonEdge

### Type of the chain

L1

### Link to the page

https://worldchain-mainnet.explorer.alchemy.com/address/0x2cFc85d8E48F8EAB294be644d9E25C3030863003?tab=txs

### Steps to reproduce

**I will advice them to be keen when sending crypto currency coins to different networks**

### Backend version

v6.8.1-beta

### Frontend version

v1.35.2+08de20eb

### Elixir & Erlang/OTP versions

Elixir 1.17.3

### Operating system

Android

### Additional information

**User Agent:** Mozilla/5.0 (Linux; U; Android 12; SM-A032F Build/SP1A.210812.016; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/129.0.6668.81 Mobile Safari/537.36 OPR/84.0.2254.73823

**Comment by vbaranov** [comment]
This chat is for Blockscout-related questions. Your question is out of scope, where the Blockscout team can help.
