### ISSUE TITLE
Transaction mistake 

### ISSUE THREAD

**Issue by Hysaj9** [blockscout/blockscout#10949]
### Description

Good morning 
I hope this message finds you well, with due respect and honour, I'm writing to regretfully inform you about the mistakes I made .

I sent 0.0022 $BNB matchain network to $BNB bep20 address.

Here is the transaction ID and the addresses for your review please 

Txid= 0x5e3613035a4f5f4db6e94749eea1a161c0f29472bfd4d9e680eab4346c7c5185
From: 0xb26BeD6543FE2C0aB53F1B1c707CD387bF7FeFF0
To: 0xa48800DB97cFc08b0B53Ff2536133b944724d36a

Thank you 

### Type of the installation

Docker-compose

### Type of the JSON RPC archive node

Erigon

### Link to the page

https://www.matchscan.io/tx/0x5e3613035a4f5f4db6e94749eea1a161c0f29472bfd4d9e680eab4346c7c5185

### Backend version

v6.8.1-beta

### Frontend version

v1.35.0+a9d18fbe

### Elixir & Erlang/OTP versions

Compiled 

### Additional information

**User Agent:** Mozilla/5.0 (Linux; Android 6.0; Nexus 5 Build/MRA58N) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/115.0.0.0 Mobile Safari/537.36; BitKeep Android/8.23.0

**Comment by vbaranov** [comment]
This chat is for Blockscout-related questions. Your question is out of scope, where the Blockscout team can help.
