### ISSUE TITLE
Fehlerhafte Transaktion

### ISSUE THREAD

**Issue by Lurche1000** [blockscout/blockscout#10959]
### Description

Falsches Netzwerk angegeben... Transaktions Hash: 0x0e1d18b407f68913b4f422c69ebca00415b61bb4fdf72fcfdb4dded9db5341c7

### Type of the installation

Docker-compose

### Type of the JSON RPC archive node

????

### Type of the chain

???

### Link to the page

https://scan.bitcoincode.technology/tx/0x0e1d18b407f68913b4f422c69ebca00415b61bb4fdf72fcfdb4dded9db5341c7

### Backend version

???

### Frontend version

???

### Elixir & Erlang/OTP versions

???

### Operating system

Windows

**Comment by sl1depengwyn** [comment]
This repo is for Blockscout-related questions. Blockscout is an open source blockchain explorer. Thus, your question is out of scope, where the Blockscout team can help, you better contact the chain support directly.
