### ISSUE TITLE
No me a llegad9 mi dinero

### ISSUE THREAD

**Issue by Rosangela27** [blockscout/blockscout#10953]
### Description

Envíe dinero por octumus a binance y no a llegado
![share_2024-10-18_21_14_58_672](https://github.com/user-attachments/assets/ff24c3ac-14ac-4ca6-8508-4437b45d378c)

### Type of the installation

Manual from the source code

### Type of the JSON RPC archive node

0x000300f8c8f1aa7f986f595f3184b0abf774b9a1

### Type of the chain

1

### Link to the page

https://worldchain-mainnet.explorer.alchemy.com/tx/0xee5047f7678e5ec35d383e44095344e0b60b22636e70b3438efd538708098ff1

### Steps to reproduce

Transferir de worcoin a binance y ni me a llegado nada

### Backend version

v6.8.1-beta

### Frontend version

v1.35.2+08de20eb

### Elixir & Erlang/OTP versions

0x000300f8c8f1aa7f986f595f3184b0abf774b9a1

### Operating system

Optimus

### Additional information

**User Agent:** Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Mobile Safari/537.36

**Comment by sl1depengwyn** [comment]
This repo is for Blockscout-related questions. Blockscout is an open source blockchain explorer. Thus, your question is out of scope, where the Blockscout team can help, you better contact the chain support directly.
