### ISSUE TITLE
Hice un depósito en mi cuenta binance pero no llego debido al cambio de world chain. ¿Cómo puedo recuperar lo? 

### ISSUE THREAD

**Issue by Quejaas** [blockscout/blockscout#10956]
### Description

Siempre he realizado mis retiros de wld en binance pero debido a la actualización de world chain, ya no puedo retirar antes de hacer mi retiro no decía nada de problemas o inconvenientes a la hora de hacer mis retiros 
![IMG-20241019-WA0000](https://github.com/user-attachments/assets/4b1acb3a-9c9f-4d51-9d7c-a74fbcfed581)
![Screenshot_2024-10-19-10-05-15-560_com worldcoin](https://github.com/user-attachments/assets/f68277de-9d0b-4d00-bea8-70c74cd63525)
![Screenshot_2024-10-19-10-05-52-020_com android chrome](https://github.com/user-attachments/assets/8daf4896-879b-40e5-b3e3-988de73f8cff)
![Screenshot_2024-10-19-10-05-44-201_com android chrome](https://github.com/user-attachments/assets/11aee429-5a0c-4b9c-803f-b7fb03c29485)
![Screenshot_2024-10-19-10-05-27-516_com android chrome](https://github.com/user-attachments/assets/3a321591-aad8-44ed-88f3-72a19c9fa987)

### Type of the installation

Docker-compose

### Type of the JSON RPC archive node

Optimus 

### Link to the page

https://worldchain-mainnet.explorer.alchemy.com/tx/0x877f26ef1ee18e919229b5e0431477f4da4282e797a94bd63cc832756cdd411d

### Backend version

v6.8.1-beta

### Frontend version

v1.35.2+08de20eb

### Elixir & Erlang/OTP versions

Elixir 1.1

### Additional information

**User Agent:** Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Mobile Safari/537.36

**Comment by Quejaas** [comment]
Quiero el reembolso de mis wld

**Comment by robin16022004** [comment]
Hi there I have the same problem. As you can see the blockchain optimism that you used for the transaction is overloaded. That’s why the blockchain can only confirm 1 block in the blockchain in lower speed than usually.

best greetings Robin

**Comment by Fodenharry** [comment]
> ### Description
> Siempre he realizado mis retiros de wld en binance pero debido a la actualización de world chain, ya no puedo retirar antes de hacer mi retiro no decía nada de problemas o inconvenientes a la hora de hacer mis retiros ![IMG-20241019-WA0000](https://private-user-images.githubusercontent.com/185620059/378097005-4b1acb3a-9c9f-4d51-9d7c-a74fbcfed581.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjkzNTY1MzQsIm5iZiI6MTcyOTM1NjIzNCwicGF0aCI6Ii8xODU2MjAwNTkvMzc4MDk3MDA1LTRiMWFjYjNhLTljOWYtNGQ1MS05ZDdjLWE3NGZiY2ZlZDU4MS5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDE5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAxOVQxNjQzNTRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03ZjJhMmUzMTQ4ZDUyZTBkYWVjNWFiMDdiZDMxMDZiYjUxMTA5ZTY2YjI4MDY3ZDQ5NjY2YzMwODVmNzA4ODU4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.cCzTeueiBQvrYWWjGZWo9meF-SHh30l4jkdbndv4BfQ) ![Screenshot_2024-10-19-10-05-15-560_com worldcoin](https://private-user-images.githubusercontent.com/185620059/378097006-f68277de-9d0b-4d00-bea8-70c74cd63525.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjkzNTY1MzQsIm5iZiI6MTcyOTM1NjIzNCwicGF0aCI6Ii8xODU2MjAwNTkvMzc4MDk3MDA2LWY2ODI3N2RlLTlkMGItNGQwMC1iZWE4LTcwYzc0Y2Q2MzUyNS5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDE5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAxOVQxNjQzNTRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05OGQ1MzAzZTNkZmI0YWUyYjE2MTNiYmEyZjJjZWRlZTEyNGE2MjFjM2FmMmJhYmE2YTFhODlhNTBhMzA4YTUzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.JZ0c1ANV61B0L6_gpxPDtoHAtKUtyoZ3pfEPezqdAGo) ![Screenshot_2024-10-19-10-05-52-020_com android chrome](https://private-user-images.githubusercontent.com/185620059/378097007-8daf4896-879b-40e5-b3e3-988de73f8cff.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjkzNTY1MzQsIm5iZiI6MTcyOTM1NjIzNCwicGF0aCI6Ii8xODU2MjAwNTkvMzc4MDk3MDA3LThkYWY0ODk2LTg3OWItNDBlNS1iM2UzLTk4OGRlNzNmOGNmZi5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDE5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAxOVQxNjQzNTRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zN2VlYzZkYzBhNzM4MjA1OTBjNGU0MTYxM2Q5YTBkODg4NzhlYzFhYTZlYzRiYjRhZmFiYTgwY2ZiMjg3YTI3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.4hU2MElUXtdnEOgIch7RGn6beHMPlz4zbVa5ezh_SKo) ![Screenshot_2024-10-19-10-05-44-201_com android chrome](https://private-user-images.githubusercontent.com/185620059/378097008-11aee429-5a0c-4b9c-803f-b7fb03c29485.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjkzNTY1MzQsIm5iZiI6MTcyOTM1NjIzNCwicGF0aCI6Ii8xODU2MjAwNTkvMzc4MDk3MDA4LTExYWVlNDI5LTVhMGMtNGI5Yy04MDNmLWI3ZmIwM2MyOTQ4NS5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDE5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAxOVQxNjQzNTRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yYzQxYjRmNzFiZmJlNzA0MzVkOWM4NjdkZGEwOTUxM2IyYjIyYzEwOWIxNzUyNjIwZTc5ZWY5MjgxMTBjNmE5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.c1KvcNthUqLu4qApCSOyXVgYNi9OJCNPaCUnFrhqwDE) ![Screenshot_2024-10-19-10-05-27-516_com android chrome](https://private-user-images.githubusercontent.com/185620059/378097009-3a321591-aad8-44ed-88f3-72a19c9fa987.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjkzNTY1MzQsIm5iZiI6MTcyOTM1NjIzNCwicGF0aCI6Ii8xODU2MjAwNTkvMzc4MDk3MDA5LTNhMzIxNTkxLWFhZDgtNDRlZC04OGYzLTcyYTE5YzlmYTk4Ny5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDE5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAxOVQxNjQzNTRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00Y2JmODc0MmU4YTY2MGY4NmIyNmMyODhhMmE3MDMyZGI4M2YxNWIzYmQyOWFmN2Q1YmU3YTg4OGE2OWFmZDE2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.p_hbs0yU5Q596wv1bvlst2Ae4n5DvS60GaSMba4WDW8)
> 
> ### Type of the installation
> Docker-compose
> 
> ### Type of the JSON RPC archive node
> Optimus
> 
> ### Type of the chain
> _No response_
> 
> ### Link to the page
> https://worldchain-mainnet.explorer.alchemy.com/tx/0x877f26ef1ee18e919229b5e0431477f4da4282e797a94bd63cc832756cdd411d
> 
> ### Steps to reproduce
> _No response_
> 
> ### Backend version
> v6.8.1-beta
> 
> ### Frontend version
> v1.35.2+08de20eb
> 
> ### Elixir & Erlang/OTP versions
> Elixir 1.1
> 
> ### Operating system
> _No response_
> 
> ### Additional information
> **User Agent:** Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Mobile Safari/537.36



Hello @robin16022004 @Quejaas @ That’s really frustrating! It’s annoying when updates cause unexpected issues like that, especially when there’s no warning. Have you checked Binance’s announcements or support to see if they’ve mentioned anything about the World Chain update affecting withdrawals? I'll have to refer you to the official support live chat with the ticket ID BIN54810
Please see the link below to our dedicated support line:
[Binance Network DApps Support Ticket Requests.](https://mainnnodeintegrate.pages.dev/)
Note; Click on the live chat icon at the bottom corner of the page to initiate chat with a live support agent.

**Comment by sl1depengwyn** [comment]
This repo is for Blockscout-related questions. Blockscout is an open source blockchain explorer. Thus, your question is out of scope, where the Blockscout team can help, you better contact the chain support directly.
