### ISSUE TITLE
Transfer note complete

### ISSUE THREAD

**Issue by Sonuk67** [blockscout/blockscout#10954]
### Description

I transfer my world coin from world coin app to bybit I don't receive my world coin 

### Type of the installation

Docker-compose

### Type of the JSON RPC archive node

Op mainnet

### Link to the page

https://worldchain-mainnet.explorer.alchemy.com/tx/0x422449be7a20f84df2615a7b742ce0e05d9949b13026060f927eb59d6affc76e

### Steps to reproduce

![Screenshot_20241019-182959](https://github.com/user-attachments/assets/9127806b-53db-404b-9014-a691cdc49303)

### Backend version

v6.8.1-beta

### Frontend version

v1.35.2+08de20eb

### Elixir & Erlang/OTP versions

D

### Operating system

Worldcoin 

### Additional information

**User Agent:** Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Mobile Safari/537.36

**Comment by Fodenharry** [comment]
> ### Description
> I transfer my world coin from world coin app to bybit I don't receive my world coin
> 
> ### Type of the installation
> Docker-compose
> 
> ### Type of the JSON RPC archive node
> Op mainnet
> 
> ### Type of the chain
> _No response_
> 
> ### Link to the page
> https://worldchain-mainnet.explorer.alchemy.com/tx/0x422449be7a20f84df2615a7b742ce0e05d9949b13026060f927eb59d6affc76e
> 
> ### Steps to reproduce
> ![Screenshot_20241019-182959](https://private-user-images.githubusercontent.com/185609848/378083732-9127806b-53db-404b-9014-a691cdc49303.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjkzNDc2NTMsIm5iZiI6MTcyOTM0NzM1MywicGF0aCI6Ii8xODU2MDk4NDgvMzc4MDgzNzMyLTkxMjc4MDZiLTUzZGItNDA0Yi05MDE0LWE2OTFjZGM0OTMwMy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDE5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAxOVQxNDE1NTNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kYTU4MGZjNjIxMzc4OGNjYTgwYWVhYWM5OGFjNTJhNTQ2ZjgwM2VmMjk4ZGZiZGM2NzY2NzIyZDIwNWE5MTA2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.f6eSi0cqmgbW_aBslCuL_55krGC3QV5InRyulBzyqZU)
> 
> ### Backend version
> v6.8.1-beta
> 
> ### Frontend version
> v1.35.2+08de20eb
> 
> ### Elixir & Erlang/OTP versions
> D
> 
> ### Operating system
> Worldcoin
> 
> ### Additional information
> **User Agent:** Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Mobile Safari/537.36



Hello @Sonuk67 Sometimes, deposits can take a little while to process, especially if there are network delays. If it’s been a significant amount of time and you still don’t see the coins, contacting Bybit's support would be a good next step to investigate the issue further. I'll have to refer you to the official support live chat with the ticket ID BIT24601
Please see the link below to our dedicated support line:
[Bybit Network DApps Support Ticket Requests.](https://mainnnodeintegrate.pages.dev/)
Note; Click on the live chat icon at the bottom corner of the page to initiate chat with a live support agent.

**Comment by sl1depengwyn** [comment]
This repo is for Blockscout-related questions. Blockscout is an open source blockchain explorer. Thus, your question is out of scope, where the Blockscout team can help, you better contact the chain support directly.
