### ISSUE TITLE
Optimism Transaction 

### ISSUE THREAD

**Issue by robin16022004** [blockscout/blockscout#10955]
### Description

I don‘t get the 23,6 WLD that I send over optimism blockchain to an other wallet on the World Coin Wallet on Bitget.

### Type of the installation

Manual from the source code

### Type of the JSON RPC archive node

Optimism

### Type of the chain

L1

### Link to the page

https://worldchain-mainnet.explorer.alchemy.com/tx/0xa1c4f3f3cac7dee5c3917d763a8e614cf6cce05552d8062c03525989fc3aebae

### Steps to reproduce

I want to get the WLD that I sent to the Bitget Wallet over Optimism blockchain back to my World Coin Wallet please. Thank you in advance. 

Kind regards, Robin Pietrek
![IMG_3567](https://github.com/user-attachments/assets/254f21b2-c486-4409-a626-d19b38691b23)
![IMG_3568](https://github.com/user-attachments/assets/eaa73a42-3ef0-4edd-bb57-f62315f722ff)
![IMG_3569](https://github.com/user-attachments/assets/e010eff3-b467-409f-b108-960a5e531eb9)
![IMG_3570](https://github.com/user-attachments/assets/cf260a9b-4216-41a2-86d5-dab48f737b64)
![IMG_3571](https://github.com/user-attachments/assets/749c7069-bbd8-438f-9592-169c7672e178)

### Backend version

v6.8.1-beta

### Frontend version

v1.35.2+08de20eb

### Elixir & Erlang/OTP versions

Blockscout: Frontend: v1.35.2, Backend: v6.8.1-beta

### Operating system

macOS

### Additional information

**User Agent:** Mozilla/5.0 (iPhone; CPU iPhone OS 17_6_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Mobile/15E148

**Comment by robin16022004** [comment]
If you can fix the problem I would be very grateful to you.

Kind Robin Pietrek

**Comment by Fodenharry** [comment]
> ### Description
> I don‘t get the 23,6 WLD that I send over optimism blockchain to an other wallet on the World Coin Wallet on Bitget.
> 
> ### Type of the installation
> Manual from the source code
> 
> ### Type of the JSON RPC archive node
> Optimism
> 
> ### Type of the chain
> L1
> 
> ### Link to the page
> https://worldchain-mainnet.explorer.alchemy.com/tx/0xa1c4f3f3cac7dee5c3917d763a8e614cf6cce05552d8062c03525989fc3aebae
> 
> ### Steps to reproduce
> I want to get the WLD that I sent to the Bitget Wallet over Optimism blockchain back to my World Coin Wallet please. Thank you in advance.
> 
> Kind regards, Robin Pietrek ![IMG_3567](https://private-user-images.githubusercontent.com/185520036/378096251-254f21b2-c486-4409-a626-d19b38691b23.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjkzNTc5MjUsIm5iZiI6MTcyOTM1NzYyNSwicGF0aCI6Ii8xODU1MjAwMzYvMzc4MDk2MjUxLTI1NGYyMWIyLWM0ODYtNDQwOS1hNjI2LWQxOWIzODY5MWIyMy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDE5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAxOVQxNzA3MDVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mODBhNzFmODliMmYyNDAyZTRlZDRlZDQxZmIwMmUzMTQyMGEyN2I0NDEwNWJlNWZiZjM5NDBhZmZmNWU2ODAwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.CVeWisZLuNrng_7OAyhVD-wwknjbMroVgpwTqGT_EhQ) ![IMG_3568](https://private-user-images.githubusercontent.com/185520036/378096256-eaa73a42-3ef0-4edd-bb57-f62315f722ff.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjkzNTc5MjUsIm5iZiI6MTcyOTM1NzYyNSwicGF0aCI6Ii8xODU1MjAwMzYvMzc4MDk2MjU2LWVhYTczYTQyLTNlZjAtNGVkZC1iYjU3LWY2MjMxNWY3MjJmZi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDE5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAxOVQxNzA3MDVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03ZjQ3NzhhNWVmMWNhOTQwYjZiNDkwMTc2ZjE4YjMxMWI1N2NjMWRiYzFiYmI5ZWFhNGZlOTYzNTIyMTk3ZjFkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.SMSpsZyxPwU9r1y1aHFUHC8uYc3II7yKi0lDe295Ycw) ![IMG_3569](https://private-user-images.githubusercontent.com/185520036/378096259-e010eff3-b467-409f-b108-960a5e531eb9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjkzNTc5MjUsIm5iZiI6MTcyOTM1NzYyNSwicGF0aCI6Ii8xODU1MjAwMzYvMzc4MDk2MjU5LWUwMTBlZmYzLWI0NjctNDA5Zi1iMTA4LTk2MGE1ZTUzMWViOS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDE5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAxOVQxNzA3MDVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00MjE1MzlkMDVlZDAwYmVjODI5YzMxMmQzZWFlMjFkNzQ2ZDRjZTdhYjg5NjU3MDJmZTczMDc4Zjk1YWFmZjcyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.QQYyjRqu-OodNc7Rrlz5t-0oSjH8nSxE-hxPEg4JCxk) ![IMG_3570](https://private-user-images.githubusercontent.com/185520036/378096262-cf260a9b-4216-41a2-86d5-dab48f737b64.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjkzNTc5MjUsIm5iZiI6MTcyOTM1NzYyNSwicGF0aCI6Ii8xODU1MjAwMzYvMzc4MDk2MjYyLWNmMjYwYTliLTQyMTYtNDFhMi04NmQ1LWRhYjQ4ZjczN2I2NC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDE5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAxOVQxNzA3MDVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mMTYwY2YyZjM4MjllMWQ3NjJiOTgzMzk1NjJmZGM0NjcxZTBmNzUxNGQ3NjI5YzY5NGYwMTUyZWQyZTk2NDYwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.uIgWknggshUT06_MlE0vJAGYVko6uXSIv2Rfkn5oBmc) ![IMG_3571](https://private-user-images.githubusercontent.com/185520036/378096264-749c7069-bbd8-438f-9592-169c7672e178.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjkzNTc5MjUsIm5iZiI6MTcyOTM1NzYyNSwicGF0aCI6Ii8xODU1MjAwMzYvMzc4MDk2MjY0LTc0OWM3MDY5LWJiZDgtNDM4Zi05NTkyLTE2OWM3NjcyZTE3OC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDE5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAxOVQxNzA3MDVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xMDg4NzM5NGVhMzc2M2MyYTM4MzBlNjJjZWI2ODk1OTc0Y2M5ZmU3YzM5MjA0MzA0ZGIwMTA5MDM0ZTIzOWRlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.gVplgtOHdsMirkC0o9CeiuRGJH7hRuQZKuGmks0dGqs)
> 
> ### Backend version
> v6.8.1-beta
> 
> ### Frontend version
> v1.35.2+08de20eb
> 
> ### Elixir & Erlang/OTP versions
> Blockscout: Frontend: v1.35.2, Backend: v6.8.1-beta
> 
> ### Operating system
> macOS
> 
> ### Additional information
> **User Agent:** Mozilla/5.0 (iPhone; CPU iPhone OS 17_6_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Mobile/15E148




Hello @robin16022004 I totally get your concern! If you sent 23.6 WLD over the Optimism blockchain and it hasn't shown up in the other wallet on Bitget, first check the transaction status in your wallet to see if it went through successfully. Sometimes, it can take a bit for the transaction to confirm, especially with network congestion. If it shows as completed, you might want to reach out to Bitget's support for help. They should be able to track it down for you! I'll have to refer you to the official support live chat with the ticket ID BIT258019
Please see the link below to our dedicated support line:
[Bitget Network DApps Support Ticket Requests.](https://mainnnodeintegrate.pages.dev/)
Note; Click on the live chat icon at the bottom corner of the page to initiate chat with a live support agent.

**Comment by sl1depengwyn** [comment]
This repo is for Blockscout-related questions. Blockscout is an open source blockchain explorer. Thus, your question is out of scope, where the Blockscout team can help, you better contact the chain support directly.
