### ISSUE TITLE
didn't received the world coin in my external wallet 

### ISSUE THREAD

**Issue by pranaavvv004** [blockscout/blockscout#10958]
### Description

i had 23.77 which i send to my binance account by which i could withdrawal but when i transferred then in the World coin app it shows i have send the amount but i haven't received the world coin my binance account 

### Type of the installation

Manual from the source code

### Type of the JSON RPC archive node

i dont know

### Link to the page

https://worldchain-mainnet.explorer.alchemy.com/tx/0xa37b152af0205c041a860bfd14ff39138f4b1519f4431b0f7c6f7e7e76085549

### Backend version

v6.8.1-beta

### Frontend version

v1.35.2+08de20eb

### Elixir & Erlang/OTP versions

i dont know

### Additional information

**User Agent:** Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Mobile Safari/537.36

**Comment by sl1depengwyn** [comment]
This repo is for Blockscout-related questions. Blockscout is an open source blockchain explorer. Thus, your question is out of scope, where the Blockscout team can help, you better contact the chain support directly.
