### ISSUE TITLE
Transaction not reached 

### ISSUE THREAD

**Issue by Kingliams** [blockscout/blockscout#10951]
### Description

Am having an issue i sent my world coin to a binance a account and i haven't received it yet 
![Screenshot_20241018_182451_World App](https://github.com/user-attachments/assets/d0613085-238b-421f-91b7-a783f7216cba)
![Screenshot_20241019_114140_WhatsApp](https://github.com/user-attachments/assets/8000c928-dc45-4089-b0a0-97d161cc178d)

### Type of the installation

Docker-compose

### Type of the JSON RPC archive node

0x45bc9c4f0a4bc4bd32fe1ca7cf206766f67859310abeae68140184f54b2bf03a

### Type of the chain

0xd3cd9e27208d2911f79f7f938dd8ef397df42be7

### Link to the page

https://worldchain-mainnet.explorer.alchemy.com/tx/0x45bc9c4f0a4bc4bd32fe1ca7cf206766f67859310abeae68140184f54b2bf03a

### Backend version

v6.8.1-beta

### Frontend version

v1.35.2+08de20eb

### Elixir & Erlang/OTP versions

0xd3cd9e27208d2911f79f7f938dd8ef397df42be7

### Additional information

**User Agent:** Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Mobile Safari/537.36

**Comment by Peter254-prog** [comment]
I have the same issue pal let me know when you receive feedback please

**Comment by robin16022004** [comment]
Hi there, I have the same problem as you. I also already report the issue. I think the blockchain World App used wich is Optimism is overloaded. Bitget, the platform I use for trading has already send a message to me that the blockchain is overloaded. So therefore, bitget must suspend the withdrawal services until a later date. I think in the world app there is the same problem as Bitget.
Best regards

**Comment by sl1depengwyn** [comment]
This repo is for Blockscout-related questions. Blockscout is an open source blockchain explorer. Thus, your question is out of scope, where the Blockscout team can help, you better contact the chain support directly.
