### ISSUE TITLE
Red de cadena de bloques esta tardando demasiado estoy esperando hace 4 dias

### ISSUE THREAD

**Issue by Veronica197** [blockscout/blockscout#10957]
### Description

![Screenshot_20241019-131032](https://github.com/user-attachments/assets/e24b2bfb-13ed-4657-8b1d-90720b8134d3)
La red de cadena de bloques es de 4 millones estoy esperando hace 4 dias ya necesito la transferencia hecha ya por favor 

### Type of the installation

Docker-compose

### Type of the JSON RPC archive node

I dont now

### Type of the chain

4 millones

### Link to the page

https://worldchain-mainnet.explorer.alchemy.com/block/4837548

### Steps to reproduce

Ya lo hice arriba

### Backend version

v6.8.1-beta

### Frontend version

v1.35.2+08de20eb

### Elixir & Erlang/OTP versions

No lo se

### Operating system

Android

### Additional information

**User Agent:** Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Mobile Safari/537.36

**Comment by sl1depengwyn** [comment]
This repo is for Blockscout-related questions. Blockscout is an open source blockchain explorer. Thus, your question is out of scope, where the Blockscout team can help, you better contact the chain support directly.
