### ISSUE TITLE
Worldcoins not recieved 

### ISSUE THREAD

**Issue by Sandhya1281** [blockscout/blockscout#10950]
### Description

No sent my worldcoins to a person who has wallet adress outside worldcoin .But he hasn't received it .. He got this message Please note that the wld coin deposits via world coin network are not supported and unretrievable at the moment .please deposit via supported networks. What does it mean?? Will I get my money back 

### Type of the installation

Docker-compose

### Type of the JSON RPC archive node

Lumia 

### Link to the page

https://worldchain-mainnet.explorer.alchemy.com/address/0xA36e77178331dEDfA6fAD62A05Da76431EEB7E83

### Backend version

v6.8.1-beta

### Frontend version

v1.35.2+08de20eb

### Elixir & Erlang/OTP versions

0xA36e77178331dEDfA6fAD62A05Da76431EEB7E83

### Additional information

**User Agent:** Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Mobile Safari/537.36

**Comment by Carlos4483** [comment]
Estimad@ lamentablemente aun no esta disponible la red

**Comment by Carlos4483** [comment]
Puede ser que cuando la red se encuentre operativa quizás lleguen a la otra billetera, pero es poco probable

**Comment by vbaranov** [comment]
This chat is for Blockscout-related questions. Your question is out of scope, where the Blockscout team can help.
