### ISSUE TITLE
No llego transferencia 

### ISSUE THREAD

**Issue by Jpaorp95** [blockscout/blockscout#10961]
### Description

Envié monedas por transfiya a nequi y no llegaron monedas 

### Type of the installation

Docker-compose

### Type of the JSON RPC archive node

R

### Link to the page

https://worldchain-mainnet.explorer.alchemy.com/address/0x4200000000000000000000000000000000000011

### Steps to reproduce

U

### Backend version

v6.8.1-betah

### Frontend version

v1.35.2+08de20eb

### Elixir & Erlang/OTP versions

Y

### Operating system

U

### Additional information

**User Agent:** Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Mobile Safari/537.36

**Comment by sl1depengwyn** [comment]
This repo is for Blockscout-related questions. Blockscout is an open source blockchain explorer. Thus, your question is out of scope, where the Blockscout team can help, you better contact the chain support directly.
