### ISSUE TITLE
Mis WLD no han llegado a Binance.

### ISSUE THREAD

**Issue by CarlosFoxy15** [blockscout/blockscout#10962]
### Description

Tengo entendido que han cambiado el sistema de WLD al enviar las monedas y ahora no tengo manera de poder recuperarlas, pero quiero reclamarlas porque son parte de mi dinero y este cambio no se me avisó con antelación.

### Type of the installation

Docker-compose

### Type of the JSON RPC archive node

Idk

### Type of the chain

SafeL2

### Link to the page

https://worldchain-mainnet.explorer.alchemy.com/tx/0xf28f2f76a63cebec5c3b69cf023d1913c8e2452ba252ae38a171ad58362c7a0e

### Steps to reproduce

Al enviar mis WLD a mi cuenta de Binance, supuestamente no me han llegado porque la cartera no es compatible.

### Backend version

v6.8.1-beta

### Frontend version

v1.35.2+08de20eb

### Elixir & Erlang/OTP versions

Idk

### Operating system

Linux

### Additional information

**User Agent:** Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Mobile Safari/537.36 EdgA/129.0.0.0

**Comment by sl1depengwyn** [comment]
This repo is for Blockscout-related questions. Blockscout is an open source blockchain explorer. Thus, your question is out of scope, where the Blockscout team can help, you better contact the chain support directly.
