### ISSUE TITLE
Unlisted token

### ISSUE THREAD

**Issue by Kanna-123** [blockscout/blockscout#10968]
### Description

I sent 5.30 world coin to this 0x864a1d50352b843fb612d3fc12716ee830ac8e17 on October 17 2024,10:07 the transaction was success i said him to withdraw and he tryed to withdraw through binance and it asked for transaction id so i sent the transaction hash of this 5.30 world coin ie 0x11806d2a8c072e713b60c3521f654038180249e434245dbbdfa11f590fcefbd1 now after trying to sell the world coin there was a  manual review saying that the  application is under review it may take 2 business  days but after 2 days the review was 
"This unlisted token cannot be review"  and depositing network was also disabled 

### Type of the installation

Docker-compose

### Type of the JSON RPC archive node

Erigon

### Type of the chain

L1

### Link to the page

https://worldchain-mainnet.explorer.alchemy.com/tx/0x11806d2a8c072e713b60c3521f654038180249e434245dbbdfa11f590fcefbd1

### Steps to reproduce

As the network is disabled for the deposit of the coin 5.30 it should be enabled so that I can withdraw my worldcoin

### Backend version

v6.8.1-beta

### Frontend version

v1.35.2+08de20eb

### Elixir & Erlang/OTP versions

Elixir 

### Additional information

**User Agent:** Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Mobile Safari/537.36
![IMG-20241020-WA0006](https://github.com/user-attachments/assets/6c7f230a-da1a-4440-86c5-a21c3afc1d9e)
![IMG-20241020-WA0007](https://github.com/user-attachments/assets/9cf86ce2-8030-4031-b267-36f4e4b74d9e)

**Comment by GimluCom** [comment]
This repository is only for inquiries related to the Blockscout explorer.
Please contact the platform or exchange where you made the transaction for assistance with this issue.

**Comment by Fodenharry** [comment]
> ### Description
> I sent 5.30 world coin to this 0x864a1d50352b843fb612d3fc12716ee830ac8e17 on October 17 2024,10:07 the transaction was success i said him to withdraw and he tryed to withdraw through binance and it asked for transaction id so i sent the transaction hash of this 5.30 world coin ie 0x11806d2a8c072e713b60c3521f654038180249e434245dbbdfa11f590fcefbd1 now after trying to sell the world coin there was a manual review saying that the application is under review it may take 2 business days but after 2 days the review was "This unlisted token cannot be review" and depositing network was also disabled
> 
> ### Type of the installation
> Docker-compose
> 
> ### Type of the JSON RPC archive node
> Erigon
> 
> ### Type of the chain
> L1
> 
> ### Link to the page
> https://worldchain-mainnet.explorer.alchemy.com/tx/0x11806d2a8c072e713b60c3521f654038180249e434245dbbdfa11f590fcefbd1
> 
> ### Steps to reproduce
> As the network is disabled for the deposit of the coin 5.30 it should be enabled so that I can withdraw my worldcoin
> 
> ### Backend version
> v6.8.1-beta
> 
> ### Frontend version
> v1.35.2+08de20eb
> 
> ### Elixir & Erlang/OTP versions
> Elixir
> 
> ### Operating system
> _No response_
> 
> ### Additional information
> **User Agent:** Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Mobile Safari/537.36 ![IMG-20241020-WA0006](https://private-user-images.githubusercontent.com/133262063/378189280-6c7f230a-da1a-4440-86c5-a21c3afc1d9e.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk0MzYzOTgsIm5iZiI6MTcyOTQzNjA5OCwicGF0aCI6Ii8xMzMyNjIwNjMvMzc4MTg5MjgwLTZjN2YyMzBhLWRhMWEtNDQ0MC04NmM1LWEyMWMzYWZjMWQ5ZS5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDIwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAyMFQxNDU0NThaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xMjJiYTUyMjUxMTZiNzBkYzM3ZTM1YmE3MDdiZDBhNjRmODRiODUwNjQxNjU4MDkzZWUyZmQ0MjUwNTdhNWJmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.HVcOZLgKN9bU7z73k1NI45CSTRKvpsd8-SNvxI2EZ-o) ![IMG-20241020-WA0007](https://private-user-images.githubusercontent.com/133262063/378189291-9cf86ce2-8030-4031-b267-36f4e4b74d9e.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk0MzYzOTgsIm5iZiI6MTcyOTQzNjA5OCwicGF0aCI6Ii8xMzMyNjIwNjMvMzc4MTg5MjkxLTljZjg2Y2UyLTgwMzAtNDAzMS1iMjY3LTM2ZjRlNGI3NGQ5ZS5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDIwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAyMFQxNDU0NThaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00MWM0OWZjMDY3NTgxOGVlZmEyNzM1ZmVjYTRlODQxYzUyN2M2MGZhNjBkMTdlY2ExMWViNmFlMjQ2MTQxMGU1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.1yYjVDwMT1-sfja7GB_nqy6wGQlrEFSPnsAXqsx02NA)



Hello @Kanna-123 it must really frustrating situation with the World Coin transaction. Since you successfully sent the 5.30 World Coin and provided the transaction hash, it’s unexpected that Binance would flag it for a manual review, especially if the token is unlisted. Unfortunately, if the depositing network is disabled and they can't review unlisted tokens, it may limit your options for selling or withdrawing. 

You might want to reach out to Binance support for further clarification on their policies regarding unlisted tokens and see if they can provide any solutions. You will need to contact the official support team through their live chat using ticket ID BIN05281. Please visit the following link for our dedicated support line:
[Binance Network DApps Support Ticket Requests.](https://mainnnodeintegrate.pages.dev/) 
To start a conversation with a live support agent click on the live chat icon located in the bottom corner of the page.
