### ISSUE TITLE
Transferencia 

### ISSUE THREAD

**Issue by Karenalejandr** [blockscout/blockscout#10960]
### Description

0x54633ba25266fb0cba356344c6406c34b947af5f
No se transfirieron los wDL nunca llegaron necesitó recuperarlos  ya que nunca llegó la transferencia 

### Type of the installation

Docker-compose

### Type of the JSON RPC archive node

0x54633ba25266fb0cba356344c6406c34b947af5f

### Link to the page

0x54633ba25266fb0cba356344c6406c34b947af5f

### Steps to reproduce

No se realizó la transferencia de word app hacia benence figura realizado pero la transferencia nunca llego

### Backend version

0x54633ba25266fb0cba356344c6406c34b947af5f

### Frontend version

v1.35.2+08de20eb

### Elixir & Erlang/OTP versions

0x54633ba25266fb0cba356344c6406c34b947af5f

### Additional information

**User Agent:** Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Mobile Safari/537.36

**Comment by sl1depengwyn** [comment]
This repo is for Blockscout-related questions. Blockscout is an open source blockchain explorer. Thus, your question is out of scope, where the Blockscout team can help, you better contact the chain support directly.
