### ISSUE TITLE
Monedas Word coin no me llego

### ISSUE THREAD

**Issue by Calurolon28** [blockscout/blockscout#10967]
### Description

Mande monedas Word coin y todavía no me llegaron quisiera que se cancelara el envío 

### Type of the installation

Docker-compose

### Type of the JSON RPC archive node

Android 

### Link to the page

https://worldchain-mainnet.explorer.alchemy.com/tx/0x33fa9ae04a099c6c6544e5de917849352db9b36f9eeeedf7a6c8c209455bd3be

### Steps to reproduce

Cancelar envíos recuperar monedas Word coin 

### Backend version

v6.8.1-beta

### Frontend version

v1.35.2+08de20eb

### Elixir & Erlang/OTP versions

Otp

### Operating system

Android

### Additional information

Quiero mis monedas Word coin

**Comment by sl1depengwyn** [comment]
This repo is for Blockscout-related questions. Blockscout is an open source blockchain explorer. Thus, your question is out of scope, where the Blockscout team can help, you better contact the chain support directly.
