### ISSUE TITLE
Envío de monedas sin finalizar 

### ISSUE THREAD

**Issue by Mariana1601** [blockscout/blockscout#10963]
### Description

Envié 16 monedas Worldcoin vía worldchain a Binance, debido a la actualización de la aplicación no me llegaron a mi cartera Binance. 
![Screenshot_2024-10-19-20-49-27-52_935d84e4b0855a74e938869b4229c90d](https://github.com/user-attachments/assets/de6baa99-d2d5-41ac-862f-297b8cf8973c)

### Type of the installation

Docker-compose

### Type of the JSON RPC archive node

.

### Type of the chain

.

### Link to the page

https://worldchain-mainnet.explorer.alchemy.com/block/4966595

### Steps to reproduce

Envié 16 monedas desde Worldcoin - worldchain a Binance, debido a la actualización de la aplicación no me han llegado a mi cartera. 

### Backend version

v6.8.1-beta

### Frontend version

v1.35.2+08de20eb

### Elixir & Erlang/OTP versions

.

### Operating system

.

### Additional information

**User Agent:** Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Mobile Safari/537.36

**Comment by sl1depengwyn** [comment]
This repo is for Blockscout-related questions. Blockscout is an open source blockchain explorer. Thus, your question is out of scope, where the Blockscout team can help, you better contact the chain support directly.
