### ISSUE TITLE
World coin sent rong address 

### ISSUE THREAD

**Issue by 01632930984** [blockscout/blockscout#10964]
### Description

I trying to sent my binance account and i copy also my binance account id i dont know how to go this  address 
![Screenshot_2024-10-20-12-44-38-790_com android chrome](https://github.com/user-attachments/assets/f34b3c27-0edf-4207-a09e-a8f836a28211)
![Screenshot_2024-10-20-12-44-48-136_com android chrome](https://github.com/user-attachments/assets/29a08257-b0b6-43b3-a2a6-a58f3da1c507)

### Type of the installation

Docker-compose

### Type of the JSON RPC archive node

OpenE

### Type of the chain

L1/L2/L3

### Link to the page

https://worldchain-mainnet.explorer.alchemy.com/tx/0x9bdd325d377baf5aad822e4eb1b233224083d461becae76977203d08a195adcd

### Backend version

v6.8.1-beta

### Frontend version

v1.35.2+08de20eb

### Elixir & Erlang/OTP versions

2.8.66033

### Additional information

**User Agent:** Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Mobile Safari/537.36

**Comment by sl1depengwyn** [comment]
This repo is for Blockscout-related questions. Blockscout is an open source blockchain explorer. Thus, your question is out of scope, where the Blockscout team can help, you better contact the chain support directly.

**Comment by 01632930984** [comment]
I don't understand please help me
