### ISSUE TITLE
Wld not received to binance wallet

### ISSUE THREAD

**Issue by Bhqiwi** [blockscout/blockscout#10965]
### Description

I sent my wld to the binance wallet but they were not received to the binance wallet but deducted from my wld account i want to rend it urgently

### Type of the installation

Docker-compose

### Type of the JSON RPC archive node

Erigon/geth

### Link to the page

https://worldchain-mainnet.explorer.alchemy.com/tx/0x7ffd7691b3213088a30a6912b156dea0a4e7ede382be51a171f05ae94413a581

### Backend version

v6.8.1-beta

### Frontend version

v1.35.2+08de20eb

### Elixir & Erlang/OTP versions

Complied 

### Additional information

**User Agent:** Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Mobile Safari/537.36

**Comment by sl1depengwyn** [comment]
This repo is for Blockscout-related questions. Blockscout is an open source blockchain explorer. Thus, your question is out of scope, where the Blockscout team can help, you better contact the chain support directly.

**Comment by WeInParix** [comment]
And how do we contact the chain support team?
