### ISSUE TITLE
No llega el dinero wld al código que generó trust wallet 

### ISSUE THREAD

**Issue by Joha4rtas** [blockscout/blockscout#10972]
### Description

De la cuenta de mi prima de wld 0x6136ed3089a748776e8416960cfc914a2852336b envié 5.222451 a la cuenta de Trust wallet mía al código que me generó al darle recibir y seleccionar wld optimism 0x999578848117be3d5a09bd4c089b58abaa2edc0c, y ya son varias horas y nada que cargan, no sé qué pasó y siendo sincera es la primera vez que uso esa opción de trust y no soy experta en estos casos.

### Type of the installation

Manual from the source code

### Type of the JSON RPC archive node

0x6136ed3089a748776e8416960cfc914a2852336b

### Type of the chain

1

### Link to the page

https://worldchain-mainnet.explorer.alchemy.com/address/0x999578848117Be3d5A09Bd4C089b58AbAA2Edc0C

### Backend version

v6.8.1-beta

### Frontend version

v1.35.2+08de20eb

### Elixir & Erlang/OTP versions

0x999578848117be3d5a09bd4c089b58abaa2edc0c

### Operating system

Android

### Additional information

**User Agent:** Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36

**Comment by Sebastian180057** [comment]
Envié critomonedas ala cuenta de binance de mi hermano y no llego ala cuenta de binance

**Comment by vbaranov** [comment]
This chat is for Blockscout-related questions. Your question is out of scope, where the Blockscout team can help.
