### ISSUE TITLE
Crypto lost

### ISSUE THREAD

**Issue by Jykim0129** [blockscout/blockscout#10973]
### Description

![Screenshot_20241021_102017_Samsung Internet](https://github.com/user-attachments/assets/7792907b-ce29-456e-b247-89470503d148)

### Type of the installation

Docker-compose

### Type of the JSON RPC archive node

0x17096B30C1e4f52C98EFF8a189f013944E24C884

### Type of the chain

L1

### Link to the page

https://worldchain-mainnet.explorer.alchemy.com/block/5067328

### Backend version

v6.8.1-beta

### Frontend version

v1.35.2+08de20eb

### Elixir & Erlang/OTP versions

0xe5E8D1BaD16A69beb0B650a61474e25CfEd8455A

### Operating system

Android

### Additional information

**User Agent:** Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) SamsungBrowser/26.0 Chrome/122.0.0.0 Mobile Safari/537.36

**Comment by WeInParix** [comment]
I'm having the same problem

**Comment by vbaranov** [comment]
This chat is for Blockscout-related questions. Your question is out of scope, where the Blockscout team can help.

**Comment by Fabinholit1012** [comment]
![Screenshot_20241020_140543_Chrome](https://github.com/user-attachments/assets/843cb30f-5f6e-4874-ac8e-c7d482883c3f)
![Screenshot_20241020_140454_Chrome](https://github.com/user-attachments/assets/f730bb7b-c3e1-44d3-828d-65d97be45975)
![Screenshot_20241020_141932_Chrome](https://github.com/user-attachments/assets/00048424-c51f-4cd6-83ff-b1512251b67c)
![Screenshot_20241020_140817_World App](https://github.com/user-attachments/assets/46cc35e9-6e30-42b1-b2d3-a08fb9c081a1)
![Screenshot_20241021_122318_Chrome](https://github.com/user-attachments/assets/41353bd8-a114-4d98-a035-2e5be972ebdf)
![Screenshot_20241020_133843_Chrome](https://github.com/user-attachments/assets/b5f9f1cf-eb7a-4ffd-a769-b12c0feb9d96)

**Comment by Fabinholit1012** [comment]
Boa tarde, fiz um levantamento da minha app Wolrd Coin de 22.44 moedas para
a minha conta Gate.io e não foram creditados o valor de 50 euros.
Porque?

Em seg., 21 de out. de 2024 13:07, Victor Baranov ***@***.***>
escreveu:
