### ISSUE TITLE
Wordcoins nao chegam ao destino

### ISSUE THREAD

**Issue by tvrs33** [blockscout/blockscout#10970]
### Description

Bom dia, enviei wordecois e dinheiro para uma outra conta da aplicação mãe e não aparecem em lado algum. Fiz a passagem com. o QR em modo pagamento. Estou muto desapontado com a situação!

### Type of the installation

Docker-compose

### Type of the JSON RPC archive node

não sei

### Link to the page

https://worldchain-mainnet.explorer.alchemy.com/tx/0x1b7ebab0cf7f335141c114a1c9044c4f14ca592d182aa7fa33266cc7b5e3a5a0

### Backend version

v6.8.1-beta

### Frontend version

v1.35.2+08de20eb

### Elixir & Erlang/OTP versions

não sei

### Operating system

androide para Apple 

### Additional information

**User Agent:** Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Mobile Safari/537.36

**Comment by vbaranov** [comment]
This chat is for Blockscout-related questions. Your question is out of scope, where the Blockscout team can help.

**Comment by tvrs33** [comment]
não está concluído pois o dinheiro desapareceu?

A segunda, 21/10/2024, 12:08, Victor Baranov ***@***.***>
escreveu:
