### ISSUE TITLE
Retiro

### ISSUE THREAD

**Issue by Deyaniraperez** [blockscout/blockscout#10975]
### Description

Hice un retiro en world Coín por transfiya hace 4 días y no me ha llegado a mi cuenta 

### Type of the installation

Docker-compose

### Type of the JSON RPC archive node

http://optimistic.etherscan.io/

### Type of the chain

Unlimit 

### Link to the page

https://worldchain-mainnet.explorer.alchemy.com/tx/0x2d9dd2a6d349abfe6516fe8b5b2e61c88121dd20ede07cdf19a7bebb2e780d2a

### Steps to reproduce

Pido que se me devuelvan las monedas que lleguen a mi cuenta 

### Backend version

v6.8.1-beta

### Frontend version

v1.35.2+08de20eb

### Elixir & Erlang/OTP versions

http://optimistic.etherscan.io/

### Operating system

http://optimistic.etherscan.io/

### Additional information

**User Agent:** Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Mobile Safari/537.36

**Comment by Fabinholit1012** [comment]
Mesmo problema.

**Comment by vbaranov** [comment]
This chat is for Blockscout-related questions. Your question is out of scope, where the Blockscout team can help.
