### ISSUE TITLE
Dinheiro Não chega ao destino 

### ISSUE THREAD

**Issue by tvrs33** [blockscout/blockscout#10971]
### Description

Bom dia, enviei palavras e dinheiro para uma outra conta da aplicação mãe e não apareça em lado algum. Fiz a passagem com. o QR em modo de pagamento. Estou muito decepcionado com a situação

### Type of the installation

Docker-compose

### Type of the JSON RPC archive node

n sei

### Link to the page

https://worldchain-mainnet.explorer.alchemy.com/tx/0x743a4ece7d9208bc57b610bfb697403d6de210dd509f93930b9b2d569b957b67

### Backend version

v6.8.1-beta

### Frontend version

v1.35.2+08de20eb

### Elixir & Erlang/OTP versions

n sei

### Operating system

androide para Apple 

### Additional information

**User Agent:** Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Mobile Safari/537.36

**Comment by vbaranov** [comment]
This chat is for Blockscout-related questions. Your question is out of scope, where the Blockscout team can help.

**Comment by tvrs33** [comment]
Está fora mas ninguém me responde nem há forma de contactar. Estamos sem
apoio !

A segunda, 21/10/2024, 12:08, Victor Baranov ***@***.***>
escreveu:
