### ISSUE TITLE
Transferencia incorrecta

### ISSUE THREAD

**Issue by Jairosas516** [blockscout/blockscout#10978]
### Description

Ise una transferencia a mi billetera metamask y no me llegó la transferencia ya pasaron 2 días 
![Screenshot_20241021_054852_com_worldcoin_MainActivity](https://github.com/user-attachments/assets/70a45be8-acc2-44a7-a251-000a17f7429e)

### Type of the installation

Docker-compose

### Type of the JSON RPC archive node

0x5C2B8a3e565DdD738a31417f68eb8524891F0066

### Type of the chain

Nivel 1

### Link to the page

0x5C2B8a3e565DdD738a31417f68eb8524891F0066

### Steps to reproduce

Ise mi transferencia a mi billetera digital pero ya pasaron 2 días y no me llaga mi transferencia 
![Screenshot_20241021_054852_com_worldcoin_MainActivity](https://github.com/user-attachments/assets/1abba4b8-c4f5-4b36-b235-ab1a5f21afd5)

### Backend version

V61.1.1

### Frontend version

1.1.1.

### Elixir & Erlang/OTP versions

E

### Operating system

Metemask

### Additional information

![Screenshot_20241021_054852_com_worldcoin_MainActivity](https://github.com/user-attachments/assets/d5b0905b-b9a9-4ce7-9914-f34ad3217239)
![Screenshot_20241021_055228_io_metamask_MainActivity](https://github.com/user-attachments/assets/c5d04479-4b2f-4ba5-98cd-073da1748907)

**Comment by vbaranov** [comment]
This chat is for Blockscout-related questions. Your question is out of scope, where the Blockscout team can help.
