### ISSUE TITLE
No llegaron los fondos a binance

### ISSUE THREAD

**Issue by Kjimena221** [blockscout/blockscout#10984]
### Description

Hola 
He tratado de retirar por medio de binance con optimus y no me han llegado los fondos y la transferencia dice que es exitosa 
![Screenshot_2024-10-21-10-45-29-651_com worldcoin](https://github.com/user-attachments/assets/f351bfc8-16e2-44ea-ab90-07b2d45ebace)

### Type of the installation

Docker-compose

### Type of the JSON RPC archive node

.

### Link to the page

https://worldchain-mainnet.explorer.alchemy.com/tx/0xa656f1199275b1a9be88532ff040ea59eeeda56e421f843b950751869273bbeb

### Backend version

v6.8.1-beta

### Frontend version

v1.35.2+08de20eb

### Elixir & Erlang/OTP versions

.

### Additional information

**User Agent:** Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Mobile Safari/537.36

**Comment by Milton6611** [comment]
Hola amigo me pasa igual me podes ayudar?

**Comment by Milton6611** [comment]
![Uploading Screenshot_20241022_053157_World App.jpg…]()

**Comment by sl1depengwyn** [comment]
This repo is for Blockscout-related questions. Blockscout is an open source blockchain explorer. Thus, your question is out of scope, where the Blockscout team can help, you better contact the chain support directly.
