### ISSUE TITLE
Envié los dólares a mí mama a su otra cuenta y me aparece que se envió exitosamente pero nunca le llegó no pueden cancelar el envío y hacerlo de nuevo?

### ISSUE THREAD

**Issue by Nikolaszl** [blockscout/blockscout#10983]
### Description

Envié los dólares a mí mama a su otra cuenta y me aparece que se envió exitosamente pero nunca le llegó no pueden cancelar el envío y hacerlo de nuevo?

### Type of the installation

Manual from the source code

### Type of the JSON RPC archive node

.

### Type of the chain

2

### Link to the page

https://worldchain-mainnet.explorer.alchemy.com/tx/0xe79d65f3a2e436fb504acba38dbefb2e0a2d731c4139ea5004880aa3d544f455

### Steps to reproduce

Envié los dólares a mí mama a su otra cuenta y me aparece que se envió exitosamente pero nunca le llegó no pueden cancelar el envío y hacerlo de nuevo?

### Backend version

v6.8.1-beta

### Frontend version

v1.35.2+08de20eb

### Elixir & Erlang/OTP versions

.

### Operating system

Fue en envío 

### Additional information

**User Agent:** Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Mobile Safari/537.36

**Comment by sl1depengwyn** [comment]
This repo is for Blockscout-related questions. Blockscout is an open source blockchain explorer. Thus, your question is out of scope, where the Blockscout team can help, you better contact the chain support directly.
