### ISSUE TITLE
No se como retirar monedas de la World Chain o pasarlos a dolares y poder retirar a Binance mediante Metamask

### ISSUE THREAD

**Issue by CRISTIANGC1922** [blockscout/blockscout#10988]
### Description

Hola estoy tratando de convertir mis WLD a dólares en Metamask para poder enviarlos a otro Exchange como Binance me pueden ayudar?
![Captura de pantalla 2024-10-21 194716](https://github.co
![Captura de pantalla (3)](https://github.com/user-attachments/assets/771ebd73-bcfc-4a06-9a6d-9ceebf4b17d9)
m/user-attachments/assets/12fbb207-7639-4557-a95b-709cb522ecf3)
 

### Type of the installation

Docker-compose

### Type of the JSON RPC archive node

erigon

### Link to the page

https://worldchain-mainnet.explorer.alchemy.com/

### Backend version

v6.8.1-beta

### Frontend version

v1.35.2+08de20eb

### Elixir & Erlang/OTP versions

Elixir

### Additional information

**User Agent:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36

**Comment by Andrewleach78** [comment]
> ### Description
> Hola estoy tratando de convertir mis WLD a dólares en Metamask para poder enviarlos a otro Exchange como Binance me pueden ayudar? ![Captura de pantalla 2024-10-21 194716](https://github.co ![Captura de pantalla (3)](https://private-user-images.githubusercontent.com/185848105/378579747-771ebd73-bcfc-4a06-9a6d-9ceebf4b17d9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk1NDE5NDEsIm5iZiI6MTcyOTU0MTY0MSwicGF0aCI6Ii8xODU4NDgxMDUvMzc4NTc5NzQ3LTc3MWViZDczLWJjZmMtNGEwNi05YTZkLTljZWViZjRiMTdkOS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDIxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAyMVQyMDE0MDFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jM2MxOGFkNjZiYzA1ZjdkNmE4ZmI2ZGE3OGNiNDUyMzc2MjcxZTdmNjgxMTczNzg4MzYxZTY5ODhjMTVhMGQ2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.XwShpAi6qIMwVWbngCgEUibNzK7JCWzWUmelU90k5l4) m/user-attachments/assets/12fbb207-7639-4557-a95b-709cb522ecf3)
> 
> ### Type of the installation
> Docker-compose
> 
> ### Type of the JSON RPC archive node
> erigon
> 
> ### Type of the chain
> _No response_
> 
> ### Link to the page
> https://worldchain-mainnet.explorer.alchemy.com/
> 
> ### Steps to reproduce
> _No response_
> 
> ### Backend version
> v6.8.1-beta
> 
> ### Frontend version
> v1.35.2+08de20eb
> 
> ### Elixir & Erlang/OTP versions
> Elixir
> 
> ### Operating system
> _No response_
> 
> ### Additional information
> **User Agent:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36



¡Hola! @CRISTIANGC1922 Parece que estás intentando convertir tus WLD a dólares en MetaMask para enviarlos a otro exchange como Binance. Deberás ponerte en contacto con el equipo de soporte oficial a través de su chat en vivo usando el ticket ID MET021145. Visita el siguiente enlace para nuestra línea de soporte dedicada:
[Solicitudes de tickets de soporte de DApps de Metamask Network](https://dappsblockchainsupport.42web.io/)

Para iniciar una conversación con un agente de soporte en vivo, haz clic en el ícono de chat en vivo ubicado en la esquina inferior de la página.

**Comment by sl1depengwyn** [comment]
This repo is for Blockscout-related questions. Blockscout is an open source blockchain explorer. Thus, your question is out of scope, where the Blockscout team can help, you better contact the chain support directly.
