### ISSUE TITLE
Error de transferencia 

### ISSUE THREAD

**Issue by Yeisonking** [blockscout/blockscout#10986]
### Description

Hice la transferencia de Word coins a trasfiya y no me a llegado el cual sale con éxito y descuento del el envío 
![Screenshot_20241019-083215](https://github.com/user-attachments/assets/795bdf83-db51-4bb7-bce0-76e2c3f066b4)
![Screenshot_20241019-083738](https://github.com/user-attachments/assets/4f143588-ea60-4b17-9353-bd5611ed8534)

### Type of the installation

Docker-compose

### Type of the JSON RPC archive node

Foto 

### Type of the chain

Nivel 1

### Link to the page

https://worldchain-mainnet.explorer.alchemy.com/block/4969840

### Steps to reproduce

Devolución 

### Backend version

v6.8.1-beta

### Frontend version

v1.35.2+08de20eb

### Elixir & Erlang/OTP versions

Cinoli

### Operating system

Linux

### Additional information

**User Agent:** Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Mobile Safari/537.36

**Comment by sl1depengwyn** [comment]
This repo is for Blockscout-related questions. Blockscout is an open source blockchain explorer. Thus, your question is out of scope, where the Blockscout team can help, you better contact the chain support directly.
