### ISSUE TITLE
No me llega la transacción

### ISSUE THREAD

**Issue by Milton6611** [blockscout/blockscout#10995]
### Description

No me llega la transacción que hice hace 4 días 

### Type of the installation

Docker-compose

### Type of the JSON RPC archive node

Erigon

### Type of the chain

Nivel 2

### Link to the page

https://worldchain-mainnet.explorer.alchemy.com/address/0x4b67BeF2ED04070fb58bC5a16cC66E14c4e9Df6E?tab=token_transfers

### Steps to reproduce

Hice la transferencia a binance de la App de worldcoin y no me llega hace 4 dias

### Backend version

v6.8.1-beta

### Frontend version

v1.35.2+08de20eb

### Additional information

**User Agent:** Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Mobile Safari/537.36

**Comment by Milton6611** [comment]
Quiero mis monedas

**Comment by Milton6611** [comment]
![Uploading Screenshot_20241022_053157_World App.jpg…]()

**Comment by sl1depengwyn** [comment]
This repo is for Blockscout-related questions. Blockscout is an open source blockchain explorer. Thus, your question is out of scope, where the Blockscout team can help, you better contact the chain support directly.
