### ISSUE TITLE
Wrong network transaction 

### ISSUE THREAD

**Issue by Erickem86** [blockscout/blockscout#11001]
### Description

Hi, please reverse the hash transaction :0xee19543f4056ac155b9d5695afdb80ccc731252ab673972656dec378ff38c302

### Type of the installation

Docker-compose

### Type of the JSON RPC archive node

PolygonEdge

### Type of the chain

Block chain 

### Link to the page

https://worldchain-mainnet.explorer.alchemy.com/tx/0xee19543f4056ac155b9d5695afdb80ccc731252ab673972656dec378ff38c302

### Steps to reproduce

World coin 

### Backend version

v6.8.1-beta

### Frontend version

v1.35.2+08de20eb

### Elixir & Erlang/OTP versions

OTP 27

### Operating system

Android 

### Additional information

**User Agent:** Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Mobile Safari/537.36

**Comment by vbaranov** [comment]
This chat is for Blockscout-related questions. Your question is out of scope, where the Blockscout team can help.
