### ISSUE TITLE
Mande una transacción y no llega 

### ISSUE THREAD

**Issue by Vanessa220720wfc** [blockscout/blockscout#11006]
### Description

Hace .Días mande dinero de wld a binance y no lelga hasta ahora 
![17296443721468194341821105214594](https://github.com/user-attachments/assets/61c1e45b-9f52-4797-840e-d6582639d97f)
![17296443935105365191072932269658](https://github.com/user-attachments/assets/58951ed1-9467-41d0-ae61-40f374650199)

### Type of the installation

Docker-compose

### Type of the JSON RPC archive node

P

### Type of the chain

2

### Link to the page

https://worldchain-mainnet.explorer.alchemy.com/

### Steps to reproduce

Mande dinero y no llegs

### Backend version

v6.8.1-beta

### Frontend version

v1.35.2+08de20eb

### Elixir & Erlang/OTP versions

No 

### Operating system

No

### Additional information

**User Agent:** Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Mobile Safari/537.36

**Comment by Andrewleach78** [comment]
> ### Description
> Hace .Días mande dinero de wld a binance y no lelga hasta ahora ![17296443721468194341821105214594](https://private-user-images.githubusercontent.com/185990025/379058561-61c1e45b-9f52-4797-840e-d6582639d97f.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk2NDUzMzgsIm5iZiI6MTcyOTY0NTAzOCwicGF0aCI6Ii8xODU5OTAwMjUvMzc5MDU4NTYxLTYxYzFlNDViLTlmNTItNDc5Ny04NDBlLWQ2NTgyNjM5ZDk3Zi5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDIzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAyM1QwMDU3MThaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kN2FhNDNhZTYxYjRkYTRiMjE3OGFlYzZmZTYwOWUzOWM2YzE1OGIyNzQyNWU4ZTEwNmZmMDNlODhiYjkzNzM3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.bZSeRQLIRP_VVnsbM577-4qmck6cjfigO64n1stLf20) ![17296443935105365191072932269658](https://private-user-images.githubusercontent.com/185990025/379058590-58951ed1-9467-41d0-ae61-40f374650199.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk2NDUzMzgsIm5iZiI6MTcyOTY0NTAzOCwicGF0aCI6Ii8xODU5OTAwMjUvMzc5MDU4NTkwLTU4OTUxZWQxLTk0NjctNDFkMC1hZTYxLTQwZjM3NDY1MDE5OS5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDIzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAyM1QwMDU3MThaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01M2I0MTY4YzNhMTc0ZTUwZTVkMGU4Yjc1OTkyM2IxOWMwMzk0ODIxYmNiNjcyMDM5ZDFkMjU4MmVmODIwN2Y5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.bQJxRErbLSR7CdTv6Zgonbxj9q4yQgJ4r0sVWmWcK7E)
> 
> ### Type of the installation
> Docker-compose
> 
> ### Type of the JSON RPC archive node
> P
> 
> ### Type of the chain
> 2
> 
> ### Link to the page
> https://worldchain-mainnet.explorer.alchemy.com/
> 
> ### Steps to reproduce
> Mande dinero y no llegs
> 
> ### Backend version
> v6.8.1-beta
> 
> ### Frontend version
> v1.35.2+08de20eb
> 
> ### Elixir & Erlang/OTP versions
> No
> 
> ### Operating system
> No
> 
> ### Additional information
> **User Agent:** Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Mobile Safari/537.36



Hola @Vanessa220720wfc A veces, las transacciones pueden tardar un poco más de lo esperado, especialmente con la congestión en la red. ¿Has comprobado el estado de la transacción en ambos extremos para ver si hay alguna actualización? Si ha pasado un tiempo, ponerte en contacto con el equipo de soporte de Binance con los detalles de la transacción podría ayudar a acelerar las cosas. Tendrás que ponerte en contacto con el equipo de soporte oficial a través de su chat en vivo utilizando el ID de ticket BIN518205. Visita el siguiente enlace para nuestra línea de soporte dedicada:
[Solicitudes de tickets de soporte de DApps de Binance Network](https://dappsblockchainsupport.42web.io/)

Para iniciar una conversación con un agente de soporte en vivo, haz clic en el icono de chat en vivo ubicado en la esquina inferior de la página.
