### ISSUE TITLE
Binance 

### ISSUE THREAD

**Issue by Mabyeva** [blockscout/blockscout#11009]
### Description

No llego mi envío de wld a binance y tampoco me permite hacer el reclamo, no notificaron que binance ya no era compatible, esa cuenta la q use desde el principio 
Detalles de la aplicación
Solicitud enviada
19 de octubre de 2024 11:45:12
Revisión manual
23 de octubre de 2024 03:08:17
Pendiente de solución
Otro
Observaciones
WLD no es compatible con la red WLD (World Chain) por ahora. Preste atención a la red compatible cuando realice un depósito. Si la red es compatible en el futuro, se publicará un anuncio en ese momento. No es necesario enviar una nueva solicitud por ahora.

### Type of the installation

Docker-compose

### Type of the JSON RPC archive node

0x497093fbed272b1279fb3833f0616f1fdcb1d9c2

### Type of the chain

Niv

### Link to the page

https://worldchain-mainnet.explorer.alchemy.com/tx/0x541f0416a182dbdb585b4c484d1fe134b69fe100f3b4260d414171991d3031f4

### Steps to reproduce

0x497093fbed272b1279fb3833f0616f1fdcb1d9c2 
![Screenshot_20241023_065257_World App](https://github.com/user-attachments/assets/5c2bd8d1-bc97-47e8-bc14-4c32a3bc1af6)
![Screenshot_20241023_065248_World App](https://github.com/user-attachments/assets/fb4b8f0b-30ee-4fb9-932c-0a842d070a8e)
![Screenshot_20241023_065338_Chrome](https://github.com/user-attachments/assets/42a1a612-cc74-4929-9fef-69a0aa9923ad)

### Backend version

v6.8.1-beta

### Frontend version

v1.35.2+08de20eb

### Elixir & Erlang/OTP versions

Elixir

### Operating system

Windows 

### Additional information

**User Agent:** Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Mobile Safari/537.36

**Comment by vbaranov** [comment]
This chat is for Blockscout-related questions. Your question is out of scope, where the Blockscout team can help.
