### ISSUE TITLE
WRONG ADDRESS FOR TRANSFER

### ISSUE THREAD

**Issue by Rohaan4you** [blockscout/blockscout#11002]
### Description

Hi Sir, 

I have an issue regarding I have made the transaction of worldcoin by BINANCE. I have selected the optimism block chain for withdrawing the world coins. However the transaction was successful in world coin app but I haven't receive the coins in my BINANCE App.  I have already made multiple times transaction through the same app and also I have recieved the coins before too.

I request you to please return my coins in my BINANCE App or my worldcoin app.   

I have attached the images for your reference and also mentioned the optimism block chain.

optimism blockchain using for transfer - 0xb365edc6d1083f7e133a57669edefc627a0a3fcf
![Screenshot_2024-10-22-22-39-33-08_935d84e4b0855a74e938869b4229c90d](https://github.com/user-attachments/assets/af149607-df11-4b8c-a45d-10158883e441)
![Screenshot_2024-10-22-22-42-27-43_40deb401b9ffe8e1df2f1cc5ba480b12](https://github.com/user-attachments/assets/2821c8ab-d76a-4cf7-a4dd-03583c6dfb62)
![Screenshot_2024-10-22-22-42-38-88_40deb401b9ffe8e1df2f1cc5ba480b12](https://github.com/user-attachments/assets/75d4f175-14c8-411c-a317-68defea9e187)
![Screenshot_2024-10-22-22-42-44-71_40deb401b9ffe8e1df2f1cc5ba480b12](https://github.com/user-attachments/assets/77402fb3-0d5c-49c6-9aaf-d6b30f1eaefe)
![Screenshot_2024-10-22-22-43-36-12_ee1cec40dcf6eb3919ecbfc5d87e6719](https://github.com/user-attachments/assets/21a72d8d-be02-4945-80e4-57cbdc71ef7f)

### Type of the installation

Docker-compose

### Type of the JSON RPC archive node

BINANCE/Worldcoin/deposit/optimism 

### Type of the chain

OPTIMISM 

### Link to the page

https://worldchain-mainnet.explorer.alchemy.com/tx/0x1c4ed6a2a3ca9de5bf2c5810b4177dcfa55a691e9da4d2c9b82c4c913dcb329e

### Steps to reproduce

![Screenshot_2024-10-22-22-39-27-95_935d84e4b0855a74e938869b4229c90d](https://github.com/user-attachments/assets/7261d9f5-4b8e-4975-9a7b-1f89a8404782)
![Screenshot_2024-10-22-22-42-27-43_40deb401b9ffe8e1df2f1cc5ba480b12](https://github.com/user-attachments/assets/debcfdf4-3da5-4a30-a6d6-427d4cb1005c)
![Screenshot_2024-10-22-22-42-38-88_40deb401b9ffe8e1df2f1cc5ba480b12](https://github.com/user-attachments/assets/a959bcb0-1ee5-43a8-8edf-392d461d5a77)
![Screenshot_2024-10-22-22-42-44-71_40deb401b9ffe8e1df2f1cc5ba480b12](https://github.com/user-attachments/assets/2b7f2fe2-99d5-4dea-8057-3d4fc50b70d6)
![Screenshot_2024-10-22-22-43-36-12_ee1cec40dcf6eb3919ecbfc5d87e6719](https://github.com/user-attachments/assets/433055c1-5eff-414a-b079-86360b103cb1)

I request you to please return my coins in my BINANCE App or my worldcoin app.   

I have attached the images for your reference and also mentioned the optimism block chain.

optimism blockchain using for transfer - 0xb365edc6d1083f7e133a57669edefc627a0a3fcf

### Backend version

v6.8.1-beta

### Frontend version

v1.35.2+08de20eb

### Elixir & Erlang/OTP versions

Na

### Operating system

Android 

### Additional information

**User Agent:** Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Mobile Safari/537.36

**Comment by vbaranov** [comment]
This chat is for Blockscout-related questions. Your question is out of scope, where the Blockscout team can help.

**Comment by Rohaan4you** [comment]
Please suggest me how to contact with Blockscout team ?
ASAP
