### ISSUE TITLE
Mal retiro

### ISSUE THREAD

**Issue by Dani587** [blockscout/blockscout#11016]
### Description

Envie el dinero a binance , nunca llego necesitaría en reintegro a la cuenta original 
![Screenshot_20241023_154026_World App](https://github.com/user-attachments/assets/e4e2c0c9-c00c-43f9-aa71-ddcd9bbf30f5)

### Type of the installation

Docker-compose

### Type of the JSON RPC archive node

Erigin

### Type of the chain

Nivel 1

### Link to the page

https://worldchain-mainnet.explorer.alchemy.com/tx/0x91cfa33306416b04c1668f681cf54c4b51e41f2112760847fa056877a87256bb

### Steps to reproduce

Retire el dinero de woldcoin, solo quería envía mi moneda a binance cometí en error ahora mi dinero no se donde quedo

### Backend version

v6.8.1-beta

### Frontend version

v1.35.2+08de20eb

### Elixir & Erlang/OTP versions

Elixir 1.7

### Operating system

Android 

### Additional information

**User Agent:** Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Mobile Safari/537.36

**Comment by sl1depengwyn** [comment]
This repo is for Blockscout-related questions. Blockscout is an open source blockchain explorer. Thus, your question is out of scope, where the Blockscout team can help, you better contact the chain support directly.
