### ISSUE TITLE
No me a llegado mi dinero 

### ISSUE THREAD

**Issue by Diegoaguirre07** [blockscout/blockscout#11018]
### Description

Buenas tardes, no me a llegado mi dinero que hize el 21 de octubre a las 21: 56 por worldcoin por el proveedor Alfred.

### Type of the installation

Manual from the source code

### Type of the JSON RPC archive node

Por favor, busque problemas abiertos o cerrados antes de enviar. ¡Quizás alguien haya tenido un problema similar antes!

### Type of the chain

Worldcoin 

### Link to the page

https://worldchain-mainnet.explorer.alchemy.com/tx/0xb67c403ea024f1d8717b58534e4cce3bdf3782cfeb021a03c7ee8d66a43a4650

### Steps to reproduce

Por favor, busque problemas abiertos o cerrados antes de enviar. ¡Quizás alguien haya tenido un problema similar antes!

### Backend version

v6.8.1-beta

### Frontend version

v1.35.2+08de20eb

### Elixir & Erlang/OTP versions

Erlang

### Operating system

Windows 

### Additional information

**User Agent:** Mozilla/5.0 (Linux; Android 12; M2003J15SC) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.0.0 Mobile Safari/537.36

**Comment by Fabinholit1012** [comment]
Fiz um transferência Wolrd Coin e não foi creditado em minha conta Gate.io. 
![Screenshot_20241020_140454_Chrome](https://github.com/user-attachments/assets/2d2e8fa5-47c4-4526-b98a-d3eb32305f20)
![Screenshot_20241020_140817_World App](https://github.com/user-attachments/assets/5ec06112-c067-45da-98d5-261677a12d68)
![Screenshot_20241021_122318_Chrome](https://github.com/user-attachments/assets/9d7f352b-c08f-4532-85c9-b22b75af8094)

**Comment by Fabinholit1012** [comment]
Preciso do meu dinheiro.

Em qui., 24 de out. de 2024 12:58, Victor Baranov ***@***.***>
escreveu:
