### ISSUE TITLE
Retire mal mis monedas

### ISSUE THREAD

**Issue by Dani587** [blockscout/blockscout#11017]
### Description

Debía enviar las moneda a binance y no hice eso si no que por error las retire ,la dirección de de binance pero ellos dice que no tiene nada
![Screenshot_20241023_154026_World App](https://github.com/user-attachments/assets/111d3e4f-b60e-4461-8056-544ed3703850)

### Type of the installation

Docker-compose

### Type of the JSON RPC archive node

Erigin

### Type of the chain

Nivel 1

### Link to the page

https://worldchain-mainnet.explorer.alchemy.com/

### Steps to reproduce

Retire mal mis monedas

### Backend version

v6.8.1-beta

### Frontend version

v1.35.2+08de20eb

### Elixir & Erlang/OTP versions

Elixir 1.7

### Operating system

Android 

### Additional information

**User Agent:** Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Mobile Safari/537.36

**Comment by vbaranov** [comment]
This chat is for Blockscout-related questions. Your question is out of scope, where the Blockscout team can help.
