### ISSUE TITLE
WLD RESERVE

### ISSUE THREAD

**Issue by Eliasnzvavaye2** [blockscout/blockscout#11011]
### Description

Please give back my coin to my WLD address 0xf2d4e771f8dd5cd3a39d89dc662da6aebeff23ab
I need my coins
![Screenshot_20241023-111639_World App](https://github.com/user-attachments/assets/462c44c2-fe63-470a-8c92-e6f78b638bed)
 please 

### Type of the installation

Docker-compose

### Type of the JSON RPC archive node

OpenI

### Type of the chain

L1/L2

### Link to the page

https://worldchain-mainnet.explorer.alchemy.com/tx/0x95648be5342f2ca64188537bc0c99d60351b5e6b5b329a9f9d50acb179e126ab

### Steps to reproduce

Please admin accept my request that I need back my coins of WLD 

### Backend version

v6.8.1-beta

### Frontend version

v1.35.2+08de20eb

### Elixir & Erlang/OTP versions

N/A

### Operating system

Linus

### Additional information

**User Agent:** Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Mobile Safari/537.36

**Comment by sl1depengwyn** [comment]
This repo is for Blockscout-related questions. Blockscout is an open source blockchain explorer. Thus, your question is out of scope, where the Blockscout team can help, you better contact the chain support directly.
