### ISSUE TITLE
Levantamento não creditado. 

### ISSUE THREAD

**Issue by Fabinholit1012** [blockscout/blockscout#11029]
### Description

Fiz um levantamento da minha app Wolrd Coin para a minha conta Gate.io e não foi creditado. 
![Screenshot_20241020_140543_Chrome](https://github.com/user-attachments/assets/b014469a-dfa1-484f-8e7f-0309402a0584)
![Screenshot_20241020_141932_Chrome](https://github.com/user-attachments/assets/25634b66-65e4-4b0a-942f-72925cd154da)
![Screenshot_20241020_140817_World App](https://github.com/user-attachments/assets/6bca0047-075d-4395-9103-29b514fd7b66)
![Screenshot_20241020_134435_Chrome](https://github.com/user-attachments/assets/0735703d-8760-4e04-8ad7-8ed32e6fbc3c)

### Type of the installation

Docker-compose

### Type of the JSON RPC archive node

Erigon

### Type of the chain

E1

### Link to the page

https://worldchain-mainnet.explorer.alchemy.com/address/0x248C5d2c01557Dc827804A27a85Bd9A502574890?tab=token_transfers

### Backend version

v6.1.0

### Frontend version

v1.11.1

### Elixir & Erlang/OTP versions

Elixir

### Operating system

Android

**Comment by vbaranov** [comment]
This chat is for Blockscout-related questions. Your question is out of scope, where the Blockscout team can help.

**Comment by Fabinholit1012** [comment]
Bom dia preciso do meu dinheiro, fiz a transferência e não foi creditado. 
Porque???
