### ISSUE TITLE
No me llega mi dinero 

### ISSUE THREAD

**Issue by Dpool2128** [blockscout/blockscout#11022]
### Description

No me llega mi dinero ya pasó 3 días y nada que me llega y tambien quiciera saber cuál es mi ID de transacción porfabor , gracias.

### Type of the installation

Docker-compose

### Type of the JSON RPC archive node

Ok

### Type of the chain

1

### Link to the page

https://worldchain-mainnet.explorer.alchemy.com/tx/0x5c9015a435286c15a44ec287e41e249e3e74df4592b5287e49a81a8f8c7e608f

### Steps to reproduce

Ayuda porfavor quiero mi dineroo

### Backend version

v6.8.1-beta

### Frontend version

v1.35.2+08de20eb

### Elixir & Erlang/OTP versions

Ok

### Operating system

Windows

### Additional information

**User Agent:** Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Mobile Safari/537.36

**Comment by vbaranov** [comment]
This chat is for Blockscout-related questions. Your question is out of scope, where the Blockscout team can help.
