### ISSUE TITLE
Swamp token from BVM Shards Airdrop 

### ISSUE THREAD

**Issue by Lotar01** [blockscout/blockscout#11028]
### Description

Hello,
I receive the equivalent of 127 Dollar of your token in Airdrop a couple of months ago. To date i cannot see them in my wallet. I claimed these token, but they are nowhere to be seen or found. Tell please what to do 

### Type of the installation

Docker-compose

### Type of the JSON RPC archive node

geth

### Backend version

v6.2.2-beta.+commit.a2527887

### Elixir & Erlang/OTP versions

Elixir 1.14.5 Erlang/OTP 24

### Operating system

unix linux

### Additional information

The issue happened at swamps_net Blockscout instance

**Comment by vbaranov** [comment]
This chat is for Blockscout-related questions. Your question is out of scope, where the Blockscout team can help.
