### ISSUE TITLE
Coins reflection 

### ISSUE THREAD

**Issue by 52981097** [blockscout/blockscout#11030]
### Description

I have withdrawn my coins but has not yet reflected on the wallet 

### Type of the installation

Manual from the source code

### Type of the JSON RPC archive node

Polygon edge

### Type of the chain

Polygon 

### Link to the page

https://worldchain-mainnet.explorer.alchemy.com/tx/0x0a67dea2825f7220f49481024641cdf203216cc6a0f438a15d6f5de903ade44d

### Steps to reproduce

0x0a67dea2825f7220f49481024641cdf203216cc6a0f438a15d6f5de903ade44d

### Backend version

v6.8.1-beta

### Frontend version

v1.35.2+08de20eb

### Elixir & Erlang/OTP versions

716482

### Operating system

Window s

### Additional information

**User Agent:** Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36

**Comment by vbaranov** [comment]
This chat is for Blockscout-related questions. Your question is out of scope, where the Blockscout team can help.
