### ISSUE TITLE
A donde fue el dinero

### ISSUE THREAD

**Issue by Felixp94** [blockscout/blockscout#11031]
### Description

Hola... Envie dolares en world app a binance pero los mismos ahora no estan en ningun lugar y figura como exitosa la transaccion

### Type of the installation

Docker-compose

### Type of the JSON RPC archive node

Edge

### Link to the page

https://worldchain-mainnet.explorer.alchemy.com/tx/0x530ae16553c3cc9e31c7ac2eed8a6965884650cd7ac329472ab7d47230884cf2?tab=state

### Steps to reproduce

Me podrian ayudar con el problema

### Backend version

v6.8.1-beta.

### Frontend version

v1.35.2+08de20eb

### Elixir & Erlang/OTP versions

Elixir 1.17.13 2

### Operating system

Androide

### Additional information

**User Agent:** Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Mobile Safari/537.36
![Screenshot_20241024-140734_World App](https://github.com/user-attachments/assets/1afad444-f49e-4ea9-82c4-5b073e560e94)
![Screenshot_20241024-140706_World App](https://github.com/user-attachments/assets/92614bba-6b13-4bbd-b2b2-618d6ec1c035)

**Comment by vbaranov** [comment]
This chat is for Blockscout-related questions. Your question is out of scope, where the Blockscout team can help.
