### ISSUE TITLE
Transaction issues 

### ISSUE THREAD

**Issue by 1slx274** [blockscout/blockscout#11034]
### Description

I made transaction for 54 usdc, but I did not receive it yet.
It has been 2 days((( and now I got 82k block confirmation 

### Type of the installation

Docker-compose

### Type of the JSON RPC archive node

I don't know 

### Type of the chain

L2

### Link to the page

https://worldchain-mainnet.explorer.alchemy.com/

### Backend version

v6.8.1-beta

### Frontend version

v1.35.2+08de20eb

### Elixir & Erlang/OTP versions

1.17.3

### Additional information

**User Agent:** Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Mobile Safari/537.36

**Comment by vbaranov** [comment]
This chat is for Blockscout-related questions. Your question is out of scope, where the Blockscout team can help.
