### ISSUE TITLE
Importante

### ISSUE THREAD

**Issue by Ezequiel0x** [blockscout/blockscout#11038]
### Description

No me llegó la trasferencia de la plata necesito ayuda 
Número de hash:0xf87e66b0dddb9ed2f8d0f729dc5475c117c3bb8935a5d09d00a723c7c4adbffe

### Type of the installation

Docker-compose

### Type of the JSON RPC archive node

.

### Type of the chain

2

### Link to the page

https://worldchain-mainnet.explorer.alchemy.com/tx/0xf87e66b0dddb9ed2f8d0f729dc5475c117c3bb8935a5d09d00a723c7c4adbffe

### Steps to reproduce

![Screenshot_2024-10-25-20-34-26-840](https://github.com/user-attachments/assets/f22c3d5a-e652-4aaf-8fab-7eac8b37e55f)

### Backend version

v6.8.1-beta

### Frontend version

v1.35.2+08de20eb

### Elixir & Erlang/OTP versions

.

### Operating system

.

### Additional information

..

**Comment by sl1depengwyn** [comment]
This repo is for Blockscout-related questions. Blockscout is an open source blockchain explorer. Thus, your question is out of scope, where the Blockscout team can help, you better contact the chain support directly.
