### ISSUE TITLE
Ativo não caiu na Minha Carteira 

### ISSUE THREAD

**Issue by Everton22694** [blockscout/blockscout#11039]
### Description

Enviei Worldcoin para a Carteira Kucoin e não caiu nesta carteira, já são três dias se passaram.

### Type of the installation

Docker-compose

### Type of the JSON RPC archive node

.

### Type of the chain

E1

### Link to the page

https://worldchain-mainnet.explorer.alchemy.com/tx/0xec98e666666528b0b6063afb4c435d6cb34fd899e8ba12603d63045268166264?tab=logs

### Steps to reproduce

Tentei enviar para a carteira Kucoin 

### Backend version

v6.8.1-beta

### Frontend version

v1.35.2+08de20eb

### Elixir & Erlang/OTP versions

.

### Operating system

.

### Additional information

**User Agent:** Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Mobile Safari/537.36

**Comment by sl1depengwyn** [comment]
This repo is for Blockscout-related questions. Blockscout is an open source blockchain explorer. Thus, your question is out of scope, where the Blockscout team can help, you better contact the chain support directly.
