### ISSUE TITLE
Transaction failed

### ISSUE THREAD

**Issue by robin16022004** [blockscout/blockscout#11032]
### Description

I sent my WLD (amount:23.6 WLD) over the world chain network to my brothers address and he didn’t receive the WLD

### Type of the installation

Docker-compose

### Type of the JSON RPC archive node

World chain

### Type of the chain

L2

### Link to the page

https://worldchain-mainnet.explorer.alchemy.com/tx/0xe44c2326543f8b350e90dd1c1a35878da8af6228b62e29f50684cd96f3bacd23

### Steps to reproduce

I want my WLD back please

### Backend version

v6.8.1-beta

### Frontend version

v1.35.2+08de20eb

### Elixir & Erlang/OTP versions

?

### Operating system

macOS

### Additional information

**User Agent:** Mozilla/5.0 (iPhone; CPU iPhone OS 17_6_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Mobile/15E148

**Comment by vbaranov** [comment]
This chat is for Blockscout-related questions. Your question is out of scope, where the Blockscout team can help.
