### ISSUE TITLE
withdrawals last 11 days

### ISSUE THREAD

**Issue by Svirin86** [blockscout/blockscout#11048]
### Description

My funds are not being returned to me in any way.

### Type of the installation

Docker-compose

### Type of the JSON RPC archive node

Bese

### Link to the page

https://explorer.b3.fun/tx/0xc9251db8f78bb78ccadc61afdb9ab26d77b132965e007aa273d78050a4bc92db

### Backend version

v6.8.1

### Frontend version

3.4.0+b8a163a5f

### Elixir & Erlang/OTP versions

B3 transaction

### Additional information

**User Agent:** Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:131.0) Gecko/20100101 Firefox/131.0

**Comment by vbaranov** [comment]
This chat is for Blockscout-related questions. Your question is out of scope, where the Blockscout team can help.
