### ISSUE TITLE
Money has not reflected dlon my wallet

### ISSUE THREAD

**Issue by Obrrrr** [blockscout/blockscout#11045]
### Description

It has been more than week since I made my withdrawal and it still hasn't shown

### Type of the installation

Helm charts (k8s)

### Type of the JSON RPC archive node

Erigon

### Link to the page

https://worldchain-mainnet.explorer.alchemy.com/tx/0x0ace08be89988aa2916e4dfdcf8e0b7e6a67cbfc5efc7bfe4b0b2559c6a7c97d

### Backend version

v6.8.1-beta

### Frontend version

v1.35.2+08de20eb

### Elixir & Erlang/OTP versions

Elixir 1.17.3

### Additional information

**User Agent:** Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Mobile Safari/537.36

**Comment by vbaranov** [comment]
This chat is for Blockscout-related questions. Your question is out of scope, where the Blockscout team can help.
