### ISSUE TITLE
Failed transaction 

### ISSUE THREAD

**Issue by Gha33em** [blockscout/blockscout#11041]
### Description

The transaction shows it’s done but never reached to my wallet 

### Type of the installation

Docker-compose

### Type of the JSON RPC archive node

Worldchain

### Type of the chain

L2

### Link to the page

https://worldchain-mainnet.explorer.alchemy.com/tx/0x2493a2b7e44e4f95d88078ff5c92a220af5bbc8a4f14e4c02c3847b0a42fe68d

### Backend version

v6.8.1-beta

### Frontend version

v1.35.2+08de20eb

### Elixir & Erlang/OTP versions

Elixir

### Operating system

IOS

### Additional information

**User Agent:** Mozilla/5.0 (iPhone; CPU iPhone OS 18_0_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/18.0.1 Mobile/15E148 Safari/604.1

**Comment by sl1depengwyn** [comment]
This repo is for Blockscout-related questions. Blockscout is an open source blockchain explorer. Thus, your question is out of scope, where the Blockscout team can help, you better contact the chain support directly.
