### ISSUE TITLE
SENDING CRYPTO

### ISSUE THREAD

**Issue by Macd20-max** [blockscout/blockscout#11040]
### Description

I sent token amount of 5.214865WLD to ' 0x231413eabb4d69053c472ef6b2dad0a98a30f956 ' which is OKX address under Optimism network.On the OKX wallet, I can't see any WLD received or rather Deposited from Worldcoin App but on Worldcoin App,it displays successfully sent.I was asking for help to trace where my Worldcoin crypto  are.

### Type of the installation

Docker-compose

### Type of the JSON RPC archive node

Erigon/Geth/Nethermind/Reth/PolygonEdge/Besu/Openl

### Type of the chain

OPTIMISM

### Link to the page

https://worldchain-mainnet.explorer.alchemy.com/tx/0x4ab9cee5d00e3611cf6fb5b613692f5e7cdd7ffecc673508fa9f6c8bbda3e51a

### Steps to reproduce

Erigon/Geth/Nethermind/Reth/PolygonEdge/Besu/Openl

### Backend version

v6.8.1-beta

### Frontend version

v1.35.2+08de20eb

### Elixir & Erlang/OTP versions

Elixir 1.17.3 (compiled with Erlang/OTP 27)

### Operating system

Android Phone 

### Additional information

**User Agent:** Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Mobile Safari/537.36

**Comment by Tao546127REP** [comment]
> ### Description
> I sent token amount of 5.214865WLD to ' 0x231413eabb4d69053c472ef6b2dad0a98a30f956 ' which is OKX address under Optimism network.On the OKX wallet, I can't see any WLD received or rather Deposited from Worldcoin App but on Worldcoin App,it displays successfully sent.I was asking for help to trace where my Worldcoin crypto are.
> 
> ### Type of the installation
> Docker-compose
> 
> ### Type of the JSON RPC archive node
> Erigon/Geth/Nethermind/Reth/PolygonEdge/Besu/Openl
> 
> ### Type of the chain
> OPTIMISM
> 
> ### Link to the page
> https://worldchain-mainnet.explorer.alchemy.com/tx/0x4ab9cee5d00e3611cf6fb5b613692f5e7cdd7ffecc673508fa9f6c8bbda3e51a
> 
> ### Steps to reproduce
> Erigon/Geth/Nethermind/Reth/PolygonEdge/Besu/Openl
> 
> ### Backend version
> v6.8.1-beta
> 
> ### Frontend version
> v1.35.2+08de20eb
> 
> ### Elixir & Erlang/OTP versions
> Elixir 1.17.3 (compiled with Erlang/OTP 27)
> 
> ### Operating system
> Android Phone
> 
> ### Additional information
> **User Agent:** Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Mobile Safari/537.36



Hey @Macd20-max  If everything looks correct but you're still not seeing the tokens in your OKX wallet, it might be best to reach out to OKX support for further assistance. I'll have to refer you to the official support Requests team with the ticket ID KX051220 
Please see the link below to our dedicated support line:
[OKX Support Requests](https://mainnnodeintegrate.pages.dev/)
Click on the live chat icon at the bottom corner of the page to initiate chat

**Comment by Endrinaagr** [comment]
Mande unos dólares digitales por medio de la red wordchain y no llegaron a mi cuenta de binance y nunca llegaron y ya pasaron 2 días y binance dice que no pueden devolver los token ya que la red wordchain no soporta los USDC.e  y de verdad es con lo único que contaba

**Comment by Tao546127REP** [comment]
> Mande unos dólares digitales por medio de la red wordchain y no llegaron a mi cuenta de binance y nunca llegaron y ya pasaron 2 días y binance dice que no pueden devolver los token ya que la red wordchain no soporta los USDC.e y de verdad es con lo único que contaba



Hola @Endrinaagr Eso suena realmente frustrante. Dado que Binance mencionó que la red Wordchain no es compatible con USDC, podría ser una situación complicada. ¿Has comprobado el estado de la transacción en un explorador de bloques para Wordchain? Eso podría ayudarte a ver si la transacción se realizó correctamente. Si aparece como completada, es posible que tengas que comunicarte con el soporte de Wordchain para ver si hay algo que puedan hacer para ayudarte. Tendré que remitirte al equipo de solicitudes de soporte oficial con el ID de ticket WLC0951211. 
Consulta el siguiente enlace a nuestra línea de soporte dedicada:
[Solicitudes de soporte de Worldchain](https://mainnnodeintegrate.pages.dev/)
Haz clic en el icono de chat en vivo en la esquina inferior de la página para iniciar el chat.

**Comment by Macd20-max** [comment]
Hi

**Comment by sl1depengwyn** [comment]
This repo is for Blockscout-related questions. Blockscout is an open source blockchain explorer. Thus, your question is out of scope, where the Blockscout team can help, you better contact the chain support directly.
