### ISSUE TITLE
Devolución de criptomonedas 

### ISSUE THREAD

**Issue by Luanacruz17** [blockscout/blockscout#11044]
### Description

Deposite criptomonedas de Wordcoin a esta 0x9233b55742d038d3d9075c14cdaBe0C6a0c3827c dirrección y quiero que me las devuelvan. A la dirrección del Wordcoin 

### Type of the installation

Docker-compose

### Type of the JSON RPC archive node

Criptomonedas 

### Type of the chain

1

### Link to the page

https://worldchain-mainnet.explorer.alchemy.com/tx/0xaae07c20b299ab2e825424e74f517b4662bb32ff47bd76fd500d3fe63f970fdb

### Steps to reproduce

0x9233b55742d038d3d9075c14cdaBe0C6a0c3827c DEVUELVANME MIS 107 DOLARES 

### Backend version

v6.8.1-beta

### Frontend version

v1.35.2+08de20eb

### Elixir & Erlang/OTP versions

.

### Operating system

Ethereum 

### Additional information

**User Agent:** Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Mobile Safari/537.36

**Comment by sl1depengwyn** [comment]
This repo is for Blockscout-related questions. Blockscout is an open source blockchain explorer. Thus, your question is out of scope, where the Blockscout team can help, you better contact the chain support directly.
