### ISSUE TITLE
Transfer from degen network to base network

### ISSUE THREAD

**Issue by ham-ta** [blockscout/blockscout#11046]
### Description

Hello dear supporter
Can you check my transaction ?
I’ve send degen from degen network to base address, my transaction was commited but not 
Confirmed on base , please check and tell me the soloution 

Thank you if the transaction is canceled.
Rainbow app answer:

I would recommend you to write to Degen Chain support team for appropriate assistance.

Transaction tracker:

https://explorer.degen.tips/tx/0x86e360e655f78d88ed81420293162d2fb850491e8158c870b1cc668fa228ce91

### Type of the installation

Docker-compose

### Type of the JSON RPC archive node

.

### Type of the chain

.

### Link to the page

https://explorer.degen.tips/tx/0x86e360e655f78d88ed81420293162d2fb850491e8158c870b1cc668fa228ce91

### Steps to reproduce

.

### Backend version

.v6.8.1-beta

### Frontend version

v1.35.2+08de20eb

### Elixir & Erlang/OTP versions

.

### Operating system

.

### Additional information

**User Agent:** Mozilla/5.0 (iPhone; CPU iPhone OS 18_0_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Mobile/15E148

**Comment by vbaranov** [comment]
This chat is for Blockscout-related questions. Your question is out of scope, where the Blockscout team can help.

**Comment by ham-ta** [comment]
Can you send me a Blockscout team link ?
