### ISSUE TITLE
Transacción 

### ISSUE THREAD

**Issue by Lameravena10** [blockscout/blockscout#11062]
### Description

No sé por qué no llega mi transferencia si la dice hace como 5 horas
![Screenshot_20241028_233357](https://github.com/user-attachments/assets/e6548ab9-e484-4d05-9302-974ed10ab17a)

### Type of the installation

Docker-compose

### Type of the JSON RPC archive node

Geht

### Link to the page

https://worldchain-mainnet.explorer.alchemy.com/tx/0x382a7f6ef07834b32f5685ebdf95dd66e3b5295d0339af090493652d5d6f519d

### Backend version

v6.8.1-beta

### Frontend version

v1.35.2+08de20eb

### Elixir & Erlang/OTP versions

Otp

### Operating system

Android 

### Additional information

**User Agent:** Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Mobile Safari/537.36

**Comment by vbaranov** [comment]
This chat is for Blockscout-related questions. Your question is out of scope, where the Blockscout team can help.

**Comment by Lameravena10** [comment]
Culero
