### ISSUE TITLE
Recuperar meu dinheiro 

### ISSUE THREAD

**Issue by Fabinholit1012** [blockscout/blockscout#11071]
### Description

Fiz um transferência de uma conta no Wolrd Coin de 50 euros e não foi creditado em minha conta Gate.io. 

### Type of the installation

Docker-compose

### Type of the JSON RPC archive node

Erigon

### Type of the chain

E1

### Link to the page

https://worldchain-mainnet.explorer.alchemy.com/address/0x248C5d2c01557Dc827804A27a85Bd9A502574890?tab=tokens

### Backend version

v6.8.1-beta

### Frontend version

v1.35.2+08de20eb

### Elixir & Erlang/OTP versions

Elixir

### Operating system

Android 

### Additional information

Android 
![Screenshot_20241020_140454_Chrome](https://github.com/user-attachments/assets/dbf9621b-306e-4829-a923-ce69743b2bd2)
![Screenshot_20241020_141932_Chrome](https://github.com/user-attachments/assets/4f3ee4ea-0dd3-43ff-8c44-24f411f434cf)
![Screenshot_20241020_140817_World App](https://github.com/user-attachments/assets/bd372b9f-36c9-454e-907a-d05a5cd9535c)
![Screenshot_20241020_134435_Chrome](https://github.com/user-attachments/assets/2bc4f66e-f220-4dfa-a56d-b0200778dd34)
![Screenshot_20241020_134834_Gateio](https://github.com/user-attachments/assets/7730d2dd-0b9c-4577-80cc-c0eadc8217e6)

**Comment by vbaranov** [comment]
This chat is for Blockscout-related questions. Your question is out of scope, where the Blockscout team can help.
