### ISSUE TITLE
0x268a9dec722fad4a541a3dffa625fb9d72a05cd9

### ISSUE THREAD

**Issue by 0805200504** [blockscout/blockscout#11078]
### Description

Has enviado dólares a bainance y no me llegan 
![Screenshot_2024-10-30-14-49-01-376_com worldcoin](https://github.com/user-attachments/assets/f93bab64-b6a5-4cbb-84fa-64199e0ba281)

### Type of the installation

Docker-compose

### Type of the JSON RPC archive node

Usdt

### Link to the page

https://worldchain-mainnet.explorer.alchemy.com/tx/0x161a161e316fdebad86921b081342c2c60625a4345e07df83c77403bf2e5d4b6?tab=token_transfers

### Backend version

v6.8.1-beta

### Frontend version

v1.35.2+08de20eb

### Elixir & Erlang/OTP versions

World 

### Operating system

Bainance 

### Additional information

**User Agent:** Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Mobile Safari/537.36

**Comment by vbaranov** [comment]
This chat is for Blockscout-related questions. Your question is out of scope, where the Blockscout team can help.
