### ISSUE TITLE
Connection Error with Private Geth Chain

### ISSUE THREAD

**Issue by HsuQ** [blockscout/blockscout#11079]
### Description

My Geth node is a private chain deployed using the instructions found [here](https://geth.ethereum.org/docs/fundamentals/kurtosis). 
I only changed `ETHEREUM_JSONRPC_HTTP_URL` and `ETHEREUM_JSONRPC_TRACE_URL` in `common-blockscount.env`. 
Then I `docker-compose up --build` and got error like this
<img width="1319" alt="image" src="https://github.com/user-attachments/assets/d98362e7-fc2a-4191-94e6-5ead90abf16d">
Please let me know how to resolve this issue or if further information is needed. Thanks!

### Type of the installation

Docker-compose

### Type of the JSON RPC archive node

Geth

### Type of the chain

L1

### Backend version

latest

### Frontend version

latest

### Elixir & Erlang/OTP versions

docker

### Operating system

Ubuntu

**Comment by GimluCom** [comment]
Ensure your RPC node is reachable from Docker using
```sh
docker run --rm --add-host host.docker.internal:host-gateway curlimages/curl -X POST -H "Content-Type: application/json" --data '{"method":"eth_blockNumber","params":[],"id":1,"jsonrpc":"2.0"}' http://172.19.0.8:32895
```

**Comment by HsuQ** [comment]
@GimluCom 
I successfully tested the RPC connection from Docker. 
<img width="1042" alt="image" src="https://github.com/user-attachments/assets/acc8473e-154a-4232-a621-499984a2235f">

**Comment by GimluCom** [comment]
Check the RPC URLs in [docker-compose.yml](https://github.com/blockscout/blockscout/blob/v6.9.0-beta/docker-compose/docker-compose.yml#L44-L46).
```sh
docker compose exec backend sh -c 'env | grep JSONRPC'
```
Did you set the necessary variables in [envs/common-user-ops-indexer.env](https://github.com/blockscout/blockscout/blob/v6.9.0-beta/docker-compose/envs/common-user-ops-indexer.env#L14)?

**Comment by HsuQ** [comment]
@GimluCom Thanks, It’s working now!
