### ISSUE TITLE
Subsecond block chains should be optimized for better usability 

### ISSUE THREAD

**Issue by acravenho** [blockscout/blockscout#1108]
Viewing Blockscout here: https://blockexplorer.oasiscloud.io/, it's difficult to click or read the data coming in. Not all chains have set block times, this can vary and needs to be tracked. An example of this is with HBBFT, transactions can be sent to induce an extremely fast block rate. If this occurs, we should show a Twitter notification bar similar to when we see > 10 transactions come in on an address page.

**Comment by KronicDeth** [comment]
We might also need to tune the fade-in time on the animation based on the speed stuff is coming in or it is off screen by the time fade-in finishes.

**Comment by ulyanas** [comment]
Implemented for Tx lists. There were no user complaints about the blocks animation, closing for now. Check https://explorer.degen.tips/
