### ISSUE TITLE
Didn't receive my withdrawal on the deposit platform 

### ISSUE THREAD

**Issue by Rohan-blip944** [blockscout/blockscout#11085]
### Description

In my world app I have withdrawn $15.06 11hours ago and have used optimism address for depositing on my deposit platform but in their support system it says that I have not used optimism address and it is true if I check in OPmainnet website but I have even provided the screenshots of all my transactions and the address does match the opitimism address. I need a confirmation from the worldapp that is the payment still processing or undergoing blockchain confirmations
![Screenshot_20241030_213718](https://github.com/user-attachments/assets/3df67421-41d0-4ad9-91c0-142cdd9ad90d)
![Screenshot_20241030_213808](https://github.com/user-attachments/assets/7ffc3483-9e36-4045-a0f5-e81417024552)
![Screenshot_20241030_224248](https://github.com/user-attachments/assets/aca75cbc-10ff-45f6-91c8-7664562bd83b)
![Screenshot_20241030_224257](https://github.com/user-attachments/assets/b19ddce4-bec6-4f6b-beae-b5ae6d6d0c24)
![Screenshot_20241030_224310](https://github.com/user-attachments/assets/e72ff82b-8139-4bec-8e0f-e6125e964077)

### Type of the installation

Docker-compose

### Type of the JSON RPC archive node

Optimism 

### Type of the chain

L1

### Link to the page

https://optimistic.etherscan.io/

### Steps to reproduce

Please make sure to reach out to customers with live contact support .

### Backend version

v6.8.1-beta

### Frontend version

v1.35.2+08de20eb

### Elixir & Erlang/OTP versions

OTP27

### Operating system

Android 

### Additional information

**User Agent:** Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Mobile Safari/537.36

**Comment by vbaranov** [comment]
This chat is for Blockscout-related questions. Your question is out of scope, where the Blockscout team can help.
