### ISSUE TITLE
Blockscout Optimism L3 (rollup to Optimism ) optimism_txn_batches error 

### ISSUE THREAD

**Issue by dome** [blockscout/blockscout#11086]
### Description

I deploy opstack rollup to optimism mainnet 
Blockscout optimism backend got error 
8<
(elixir 1.16.3) lib/enum.ex:1700: Enum.\"-map/2-lists^map/1-1-\"/2\n    (elixir 1.16.3) lib/enum.ex:1700: Enum.\"-map/2-lists^map/1-1-\"/2\n    (ethereum_jsonrpc 6.8.1) lib/ethereum_jsonrpc/blocks.ex:54: EthereumJSONRPC.Blocks.from_responses/2\n    (ethereum_jsonrpc 6.8.1) lib/ethereum_jsonrpc.ex:586: EthereumJSONRPC.fetch_blocks_by_params/3\n    (indexer 6.8.1) lib/indexer/fetcher/optimism/txn_batch.ex:438: Indexer.Fetcher.Optimism.TxnBatch.get_txn_batches/8\n    (indexer 6.8.1) lib/indexer/fetcher/optimism/txn_batch.ex:257: anonymous fn/12 in Indexer.Fetcher.Optimism.TxnBatch.handle_info/2\nLast message: :continue\nState: %{chunk_size: 4, json_rpc_named_arguments: [transport: EthereumJSONRPC.HTTP, transport_options: [http: EthereumJSONRPC.HTTP.HTTPoison, url: \"http://135.181.62.40:4545/\", http_options: [recv_timeout: 600000, timeout: 600000, hackney: [pool: :ethereum_jsonrpc]]]], end_block: 127379098, start_block: 127252520, block_check_interval: 1000, json_rpc_named_arguments_l2: [transport: EthereumJSONRPC.HTTP, transport_options: [http: EthereumJSONRPC.HTTP.HTTPoison, url: \"http://37.27.95.120:9545/\", fallback_url: nil, fallback_trace_url: nil, fallback_eth_call_url: nil, method_to_url: [eth_call: \"http://37.27.95.120:9545/\", eth_getBalance: \"http://37.27.95.120:9545/\", trace_block: \"http://37.27.95.120:9545/\", trace_replayBlockTransactions: \"http://37.27.95.120:9545/\", trace_replayTransaction: \"http://37.27.95.120:9545/\"], http_options: [recv_timeout: 600000, timeout: 600000, hackney: [pool: :ethereum_jsonrpc]]], variant: EthereumJSONRPC.Erigon], genesis_block_l2: 0, eip4844_blobs_api_url: \"\", celestia_blobs_api_url: \"\", batch_inbox: \"0xff00000000000000000000000000000000007117\", batch_submitter: \"0xce8d872b617677773266a5f1018af27815c35212\", incomplete_channels: %{}}","metadata":{"error":{"initial_call":null,"reason":"** (FunctionClauseError) no function clause matching in EthereumJSONRPC.Transaction.do_elixir_to_params/1\n    (ethereum_jsonrpc 6.8.1) lib/ethereum_jsonrpc/transaction.ex:284: EthereumJSONRPC.Transaction.do_elixir_to_params(%{:ignore => :ignore, \"blockHash\" => \"0x5a5ce23677749cd855cda178e98dd03cbc71ae6fea5961a595b0a806653a964b\", \"blockNumber\" => 127252521, \"block_timestamp\" => ~U[2024-10-28 08:23:39Z], \"chainId\" => 10, \"from\" => \"0x506ecb4c214c7eb712dc709cc4789dfa58cf513f\", \"gas\" => 6760224, \"gasPrice\" => 2007, \"hash\" => \"0x51253da81fcfc90d9159da0b4075aee4d0688248c63e5c94c9ce646295e80fc2\", \"input\" => \"0x6101c06040523480156200001257600080fd5b506040516200648a3803806200648a833981016040819052620000359162000436565b620000436001607e6200050d565b60ff168811156200006757604051633beff19960e11b815260040160405180910390fd5b600019871480620000845750876200008188600162000533565b10155b15620000a35760405163e62ccf3960e01b815260040160405180910390fd5b6002871015620000c65760405163e62ccf3960e01b815260040160405180910390fd5b6001600160401b038016846001600160a01b0316637dc0d1d06040518163ffffffff1660e01b8152600401602060405180830381865afa1580156200010f573d6000803e3d6000fd5b505050506040513d601f19601f820116820180604052508101906200013591906200054e565b6001600160a01b031663f3f480d96040518163ffffffff1660e01b8152600401602060405180830381865afa15801562000173573d6000803e3d6000fd5b505050506040513d601f19601f820116820180604052508101906200019991906200056e565b1115620001b95760405163b4e1243360e01b815260040160405180910390fd5b6000620001da876001600160401b0316620003e260201b62000c891760201c565b620001f0906001600160401b0316600262000588565b90506000856001600160a01b0316637dc0d1d06040518163ffffffff1660e01b8152600401602060405180830381865afa15801562000233573d6000803e3d6000fd5b505050506040513d601f19601f820116820180604052508101906200025991906200054e565b6001600160a01b031663f3f480d96040518163ffffffff1660e01b8152600401602060405180830381865afa15801562000297573d6000803e3d6000fd5b505050506040513d601f19601f82011682018060405250810190620002bd91906200056e565b620002dc896001600160401b0316620003e260201b62000c891760201c565b6001600160401b0316620002f1919062000533565b905060006200030c8383620003e560201b62003a261760201c565b90506001600160401b03811115620003375760405163235dfb2b60e21b815260040160405180910390fd5b62000356886001600160401b0316620003e260201b62000c891760201c565b6001600160401b0316816001600160401b03161115620003895760405163235dfb2b60e21b815260040160405180910390fd5b50505063ffffffff9099166101205260809790975260a09590955260c0939093526001600160401b039182166101a0521660e0526001600160a01b039081166101005290811661014052166101605261018052620005aa565b90565b600081831015620003f75781620003f9565b825b9392505050565b80516001600160401b03811681146200041857600080fd5b919050565b6001600160a01b03811681146200043357600080fd5b50565b6000806000806000806000806000806101408b8d0312156200045757600080fd5b8a5163ffffffff811681146200046c57600080fd5b809a505060208b0151985060408b0151975060608b015196506200049360808c0162000400565b9550620004a360a08c0162000400565b945060c08b0151620004b5816200041d565b60e08c0151909450620004c8816200041d565b6101008c0151909350620004dc816200041d565b809250506101208b015190509295989b9194979a5092959850565b634e487b7160e01b600052601160045260246000fd5b600060ff821660ff8416808210156200052a576200052a620004f7565b90039392505050565b60008219821115620005495762000549620004f7565b500190565b6000602082840312156200056157600080fd5b8151620003f9816200041d565b6000602082840312156200058157600080fd5b5051919050565b6000816000190483118215151615620005a557620005a5620004f7565b500290565b60805160a05160c05160e05161010051610120516101405161016051610180516101a051615d5a62000730600039600081816106bb01528181611fbb015281816120260152612059015260008181610a1e01526139390152600081816106130152818161178a01526125e80152600081816105270152818161194c01528181612480015281816129ea0152613e1401526000818161088d015281816125a701526139c80152600081816104b401528181611eba015281816132420152613597015260008181610a7101528181610f6001528181611e2a01528181612089015281816120e801528181612bf60152612c38015260008181610aa401528181611c7301528181611d9901528181611ff7015281816130950152818161379601528181613f0b015281816146280152818161475601528181614857015261492c015260008181610b4b01528181611d3c01528181611e8e01528181612d0601528181612d8c01528181612f8b01526130b601526000818161078601526131540152615d5a6000f3fe6080604052600436106102f25760003560e01c806370872aa51161018f578063c6f0308c116100e1578063ec5e63081161008a578063fa24f74311610064578063fa24f74314610b18578063fa315aa914610b3c578063fe2bbeb214610b6f57600080fd5b8063ec5e630814610a95578063eff0f59214610ac8578063f8f43ff614610af857600080fd5b8063d6ae3cd5116100bb578063d6ae3cd514610a0f578063d8cc1a3c14610a42578063dabd396d14610a6257600080fd5b8063c6f0308c14610937578063cf09e0d01461\" <> ..., \"maxFeePerGas\" => 3573, \"maxPriorityFeePerGas\" => 391, \"nonce\" => 179, \"r\" => 43769802731070106562765197556704287304059180149295212089060318352419902184439, \"s\" => 35761639927990214445707326122236426691259284566370176614307069298012022263231, \"transactionIndex\" => 17, \"type\" => 2, \"v\" => 0, \"value\" => 0})\n    (ethereum_jsonrpc 6.8.1) lib/ethereum_jsonrpc/transaction.ex:280: EthereumJSONRPC.Transaction.elixir_to_params/1\n    (elixir 1.16.3) lib/enum.ex:1700: Enum.\"-map/2-lists^map/1-1-\"/2\n    (elixir 1.16.3) lib/enum.ex:1700: Enum.\"-map/2-lists^map/1-1-\"/2\n    (ethereum_jsonrpc 6.8.1) lib/ethereum_jsonrpc/blocks.ex:54: EthereumJSONRPC.Blocks.from_responses/2\n    (ethereum_jsonrpc 6.8.1) lib/ethereum_jsonrpc.ex:586: EthereumJSONRPC.fetch_blocks_by_params/3\n    (indexer 6.8.1) lib/indexer/fetcher/optimism/txn_batch.ex:438: Indexer.Fetcher.Optimism.TxnBatch.get_txn_batches/8\n    (indexer 6.8.1) lib/indexer/fetcher/optimism/txn_batch.ex:257: anonymous fn/12 in Indexer.Fetcher.Optimism.TxnBatch.handle_info/2\n"},"fetcher":"optimism_txn_batches"}}

### Type of the installation

Docker-compose

### Type of the JSON RPC archive node

op-reth

### Type of the chain

L3 (opstack roll up to Optimism mainnet)

### Backend version

6.8.1

### Frontend version

account 2.4

### Elixir & Erlang/OTP versions

elixir:1.17.3-erlang-27.1

### Operating system

Linux

**Comment by varasev** [comment]
It looks like the response doesn't contain the `to` field. The current Blockscout implementation doesn't support such responses, but we'll add the support in https://github.com/blockscout/blockscout/pull/11073

**Comment by dome** [comment]
It's  work fine on op-reth 
![Screenshot 2567-11-01 at 17 53 39](https://github.com/user-attachments/assets/5f76f8d7-4465-4319-902a-fd2ce21d3980)
