### ISSUE TITLE
Money not receive in my wallet

### ISSUE THREAD

**Issue by Mishal-kumar** [blockscout/blockscout#11098]
### Description

My money is deducted but not receive my bybit wallet account. 
![Screenshot_2024-11-01-17-11-54-243_com worldcoin](https://github.com/user-attachments/assets/fc1295b6-72f5-4b9d-a5e7-ad2c206a3bc4)
![Screenshot_2024-11-01-17-11-46-659_com android chrome](https://github.com/user-attachments/assets/aff4a01e-7aa8-4544-aaf9-44118d202b8d)
![Screenshot_2024-11-01-17-11-38-209_com android chrome](https://github.com/user-attachments/assets/9d1b2c1c-79da-42c7-b2ed-7a875110e66c)

### Type of the installation

Docker

### Type of the JSON RPC archive node

Polygen 

### Link to the page

https://worldchain-mainnet.explorer.alchemy.com/tx/0xb1049f73806583677a15667dc70fd08f34790ad1ac0f060c3890c4540374d4a8

### Backend version

v6.8.1-beta

### Frontend version

v1.35.2+08de20eb

### Elixir & Erlang/OTP versions

Elixire

### Additional information

**User Agent:** Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Mobile Safari/537.36

**Comment by vbaranov** [comment]
This chat is for Blockscout-related questions. Your question is out of scope, where the Blockscout team can help.
