### ISSUE TITLE
Pérdida de USD Wordcoin 

### ISSUE THREAD

**Issue by Oscarch02** [blockscout/blockscout#11104]
### Description

Buenas tardes, envié USD desde Wordcoin a Binance por el valor de 61.56 y aún no ha llegado necesito que se vuelva a acreditar a mi cuenta porfavor.

### Type of the installation

Docker-compose

### Type of the JSON RPC archive node

Wordcoin 

### Type of the chain

0xbfcdc6859e07168c9f106b96d557f40ad9d7a48d26b0d43c663df227835af4f9

### Link to the page

https://worldchain-mainnet.explorer.alchemy.com/tx/0xbfcdc6859e07168c9f106b96d557f40ad9d7a48d26b0d43c663df227835af4f9

### Steps to reproduce

Verificar el retorno del Wordcoin a la cuenta destino.

### Backend version

v6.8.1-beta

### Frontend version

v1.35.2+08de20eb

### Elixir & Erlang/OTP versions

Elixir 17.1

### Operating system

Windows

### Additional information

**User Agent:** Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Mobile Safari/537.36

**Comment by vbaranov** [comment]
This chat is for Blockscout-related questions. Your question is out of scope, where the Blockscout team can help.
