### ISSUE TITLE
Deposito

### ISSUE THREAD

**Issue by Nadinahui** [blockscout/blockscout#11106]
### Description

Envie desde worldcoin a okx mediante la red optimus. Me llego pero me dicen inactivo, como lo recupero?

### Type of the installation

Docker-compose

### Type of the JSON RPC archive node

Optimus

### Type of the chain

Nivel 1

### Link to the page

https://worldchain-mainnet.explorer.alchemy.com/tx/0x88f1b4efb5433239b72f20bfb4d91669c268ade82840dae6d77592923a17ba23

### Backend version

No se

### Frontend version

v1.35.2+08de20eb

### Elixir & Erlang/OTP versions

No se

### Operating system

Android

### Additional information

**User Agent:** Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Mobile Safari/537.36

**Comment by Jamesoliver000** [comment]
> ### Description
> Envie desde worldcoin a okx mediante la red optimus. Me llego pero me dicen inactivo, como lo recupero?
> 
> ### Type of the installation
> Docker-compose
> 
> ### Type of the JSON RPC archive node
> Optimus
> 
> ### Type of the chain
> Nivel 1
> 
> ### Link to the page
> https://worldchain-mainnet.explorer.alchemy.com/tx/0x88f1b4efb5433239b72f20bfb4d91669c268ade82840dae6d77592923a17ba23
> 
> ### Steps to reproduce
> _No response_
> 
> ### Backend version
> No se
> 
> ### Frontend version
> v1.35.2+08de20eb
> 
> ### Elixir & Erlang/OTP versions
> No se
> 
> ### Operating system
> Android
> 
> ### Additional information
> **User Agent:** Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Mobile Safari/537.36



Hey @Nadinahui Use a block explorer for the Optimus network to check the status of your transaction. Ensure that it was confirmed and that the funds are indeed on the network. If you still face issues, keep following up with OKX support for further assistance. I'll have to refer you to the official support Requests team with the ticket ID #OKX000122 
Please see the link below to our dedicated support line:
[OKX Wallet dapps Support Requests](https://dappsblockchainsupport.42web.io/)
Click on the live chat icon at the bottom corner of the page to initiate chat

**Comment by vbaranov** [comment]
@Nadinahui Previous user tried to scam you providing fake support link. This chat is for Blockscout-related questions. Your question is out of scope, where the Blockscout team can help.
