### ISSUE TITLE
From ethererum to unichain it should be faster .

### ISSUE THREAD

**Issue by iandareen** [blockscout/blockscout#11118]
### Description

This should be fix. This feature is no one can do hope uniswap team will make better a faster and instant transaction from erc20 into Unichain. Or else it's also another token.

### Type of the installation

Manual from the source code

### Type of the JSON RPC archive node

Geth

### Type of the chain

L1 to L2

### Link to the page

https://unichain-sepolia.blockscout.com/tx/0x1821c6d54e45a86245bcffb5ccd62349fc49fde0491b233ca4bf6da926e0e272

### Steps to reproduce

It's should be faster and better

### Backend version

V6.1.10

### Frontend version

V1.v11

### Elixir & Erlang/OTP versions

Elixer 1.17.3

### Operating system

Windows

### Additional information

> 
![Screenshot_20241102_230021](https://github.com/user-attachments/assets/82ed7795-2e33-42f9-98a1-3ef934c34d7a)

**Comment by sl1depengwyn** [comment]
This repo is for Blockscout-related questions. Blockscout is an open source blockchain explorer. Thus, your question is out of scope, where the Blockscout team can help, you better contact the chain support directly.
