### ISSUE TITLE
Erreur 

### ISSUE THREAD

**Issue by JFbubba** [blockscout/blockscout#11124]
### Description

Good morning, This is actually an error, can you recover it please? THANKS

### Type of the installation

Docker-compose

### Type of the JSON RPC archive node

0

### Link to the page

https://explorer.fuse.io/tx/0x68db2d38e923c72b47007f317642915f596f976935aef79871bd75935ea6980b

### Backend version

v6.8.1-beta

### Frontend version

v1.35.2+08de20eb

### Elixir & Erlang/OTP versions

O

### Additional information

**User Agent:** Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Mobile Safari/537.36

**Comment by vbaranov** [comment]
@JFbubba Previous user tried to scam you providing fake support link. This chat is for Blockscout-related questions. Your question is out of scope, where the Blockscout team can help.
