### ISSUE TITLE
Suspensión 

### ISSUE THREAD

**Issue by Jessip12** [blockscout/blockscout#11129]
### Description

Quiero eliminar las encriptadas de la cuenta de maadeleiinn2001@gmail.com las copias para poder realizar la restauración a cual Me suspendieron la cuenta 
Porque me habían robado el celular y ya pude recuperarlo graciasssss a los policías 

### Type of the installation

Docker-compose

### Type of the JSON RPC archive node

.

### Type of the chain

.

### Link to the page

https://worldchain-mainnet.explorer.alchemy.com/

### Steps to reproduce

Quiero eliminar las encriptadas de la cuenta de maadeleiinn2001@gmail.com las copias de seguridad para poder realizar la restauración a cual Me suspendieron la cuenta 
Porque me habían robado el celular y ya pude recuperarlo graciasssss a los policías 

### Backend version

v6.8.1-beta

### Frontend version

v1.35.2+08de20eb

### Elixir & Erlang/OTP versions

.

### Operating system

.

### Additional information

Quiero eliminar las encriptadas de la cuenta de maadeleiinn2001@gmail.com las copias para poder realizar la restauración a cual Me suspendieron la cuenta 
Porque me habían robado el celular y ya pude recuperarlo graciasssss a los policías

**Comment by vbaranov** [comment]
This chat is for Blockscout-related questions. Your question is out of scope, where the Blockscout team can help.
