### ISSUE TITLE
Transaction not complete

### ISSUE THREAD

**Issue by Gvsa2012** [blockscout/blockscout#11125]
### Description

I'll sand my asset my my asset no come

### Type of the installation

Manual from the source code

### Type of the JSON RPC archive node

Chrome 

### Type of the chain

Optimize 

### Link to the page

https://worldchain-mainnet.explorer.alchemy.com/tx/0xe5b4de9034eb9e5987841655411e6165e2978efcb2a67dd8b83004676e4d1a55

### Backend version

Online sides 

### Frontend version

v1.35.2+08de20eb

### Elixir & Erlang/OTP versions

0x5deab623f32f1a2b42d0d9869a819c859d648aca

### Operating system

Windows 

### Additional information

**User Agent:** Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Mobile Safari/537.36

**Comment by vbaranov** [comment]
@Gvsa2012 Previous user tried to scam you providing fake support link. This chat is for Blockscout-related questions. Your question is out of scope, where the Blockscout team can help.
