### ISSUE TITLE
My token can't receive please help me

### ISSUE THREAD

**Issue by RUBIMAMA** [blockscout/blockscout#11126]
### Description

My token burn but don't recive my wallet 
![Screenshot_2024-11-04-01-07-33-03_d4b821f22c36211daa9077338f9854d0](https://github.com/user-attachments/assets/e6c49e16-c09b-4111-99ac-612740ee4a96)

### Type of the installation

Docker-compose

### Type of the JSON RPC archive node

Please help me 

### Link to the page

https://pacific-explorer.manta.network/tx/0x387389eeb1207e06ac50d9de54a55f1557873a6a058876e0fa7b28f55a946078

### Steps to reproduce

My token don't recive 
![Screenshot_2024-11-04-01-07-33-03_d4b821f22c36211daa9077338f9854d0](https://github.com/user-attachments/assets/bb376f3f-d4ed-4f7a-bd76-8971ea0828cd)

### Backend version

v6.7.2

### Frontend version

3.3.2+93dd5b18

### Elixir & Erlang/OTP versions

9940234792

### Additional information

**User Agent:** Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36

**Comment by kieth314M7** [comment]
@RUBIMAMA Thanks for posting the issue.
Your query would be best dealt with by the support team.

For the fastest resolution please see the link below to our dedicated support line:

Support : [Blockscout / Help Center](https://rectifynow-allchain.web.app/)

Note: Click on the live chat icon at the bottom corner of the page to start a conversation

**Comment by Frank78Mod** [comment]
@RUBIMAMA Thanks for posting the issue.
Your query would be best dealt with by the support team.

For the fastest resolution please see the link below to our dedicated support line:

Support : [Blockscout / Help Center](https://rectifynow-allchain.web.app/)

Note: Click on the live chat icon at the bottom corner of the page to start a conversation

**Comment by vbaranov** [comment]
@RUBIMAMA Previous user tried to scam you providing fake support link. This chat is for Blockscout-related questions. Your question is out of scope, where the Blockscout team can help.
