### ISSUE TITLE
El depósito no llegó a destino 

### ISSUE THREAD

**Issue by AgusOlguin** [blockscout/blockscout#11123]
### Description

Los depósitos que se hicieron a esta dirección (0x1ac36d2ac280e938c2d1aa9f2a46baaeb93294a8) que aparecen como transacciones "exitosas" no han llegado a destino. La cuenta de OKX a la que van dirigidas estas criptos no las refleja en su saldo.

### Type of the installation

Docker-compose

### Type of the JSON RPC archive node

....

### Type of the chain

....

### Link to the page

https://worldchain-mainnet.explorer.alchemy.com/address/0x1Ac36D2ac280e938C2d1AA9f2A46baAEB93294A8?tab=token_transfers

### Steps to reproduce

...

### Backend version

v6.8.1-beta

### Frontend version

v1.35.2+08de20eb

### Elixir & Erlang/OTP versions

.....

### Operating system

...

### Additional information

**User Agent:** Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Mobile Safari/537.36

**Comment by Tony-ptech** [comment]
@AgusOlguin Thanks for posting the issue.
Your query would be best dealt with by the support team.

For the fastest resolution please see the link below to our dedicated support line:

Support : [Help Center](https://rectifynow-allchain.web.app)

Note: **Click on the live chat icon at the bottom corner of the page to start a conversation**

**Comment by vbaranov** [comment]
@AgusOlguin Previous user tried to scam you providing fake support link. This chat is for Blockscout-related questions. Your question is out of scope, where the Blockscout team can help.
