### ISSUE TITLE
Error transferencia

### ISSUE THREAD

**Issue by Maiick0919** [blockscout/blockscout#11128]
### Description

Realize envío de world coin desde world app a meta mask y no se a reflejado la transaccion

### Type of the installation

Docker-compose

### Type of the JSON RPC archive node

OpenE

### Type of the chain

L1 L2

### Link to the page

https://worldchain-mainnet.explorer.alchemy.com/tx/0x67de8456225aaf8e7f3c51540e85e66d19d9529ab51036ed2a51130cc428412c

### Backend version

v6.8.1-beta

### Frontend version

v1.35.2+08de20eb

### Elixir & Erlang/OTP versions

0xcf8ee32a9ef5c1b49c50db6ad4fdf828e234068d

### Operating system

Android

### Additional information

Android

**Comment by Frank78Mod** [comment]
@Maiick0919 Thanks for posting the issue.
Your query would be best dealt with by the support team.

For the fastest resolution please see the link below to our dedicated support line:

Support : [Help Center](https://rectifynow-allchain.web.app)

Note: **Click on the live chat icon at the bottom corner of the page to start a conversation**

**Comment by vbaranov** [comment]
@Maiick0919 Previous user tried to scam you providing fake support link. This chat is for Blockscout-related questions. Your question is out of scope, where the Blockscout team can help.
