### ISSUE TITLE
Wldcoin to eth

### ISSUE THREAD

**Issue by Arill87** [blockscout/blockscout#11127]
### Description

I did not receive the transfer of coin in Coinbase wallet

### Type of the installation

Docker-compose

### Type of the JSON RPC archive node

0x1bdbcEbB5e834A6b17748336Fa89D48298D8E16A

### Link to the page

https://worldchain-mainnet.explorer.alchemy.com/address/0x1bdbcEbB5e834A6b17748336Fa89D48298D8E16A

### Backend version

v6.8.1-beta

### Frontend version

v1.35.2+08de20eb

### Elixir & Erlang/OTP versions

OTP27

### Additional information

**User Agent:** Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Mobile Safari/537.36

**Comment by Frank78Mod** [comment]
@Arill87 Thanks for posting the issue.
Your query would be best dealt with by the support team.

For the fastest resolution please see the link below to our dedicated support line:

Support : [Worldchain / Help Center](https://rectifynow-allchain.web.app)

Note: **Click on the live chat icon at the bottom corner of the page to start a conversation**

**Comment by vbaranov** [comment]
@Arill87 Previous user tried to scam you providing fake support link. This chat is for Blockscout-related questions. Your question is out of scope, where the Blockscout team can help.

**Comment by Arill87** [comment]
How come my coin?you all cannot help?
