### ISSUE TITLE
My transfer never arrived from the sale of my currencies.

### ISSUE THREAD

**Issue by David32553** [blockscout/blockscout#11133]
### Description

On day 01 I made the respective sale of my worldcoin currencies, to which they have not yet reached my account, 3 days have passed, and the payment is still not reflected.

### Type of the installation

Docker-compose

### Type of the JSON RPC archive node

Besu

### Type of the chain

Level 2

### Link to the page

https://worldchain-mainnet.explorer.alchemy.com/tx/0xa3004b24d0c4c1a8139ea160bf798b42996c7d58e7d06bc68f47ad67868b5525

### Steps to reproduce

see that according to the transaction it was successful

### Backend version

v6.8.1-beta

### Frontend version

v1.35.2+08de20eb

### Elixir & Erlang/OTP versions

1.17.3

### Additional information

**User Agent:** Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Mobile Safari/537.36

**Comment by sl1depengwyn** [comment]
This repo is for Blockscout-related questions. Blockscout is an open source blockchain explorer. Thus, your question is out of scope, where the Blockscout team can help, you better contact the chain support directly.
