### ISSUE TITLE
Error en la dirección de transferencia 

### ISSUE THREAD

**Issue by Jorge0413** [blockscout/blockscout#11142]
### Description

Lamentablemente, envié un token deslistado hacia una cuenta (también mía) de binance, por lo cual, quedó atascada. La cuenta es una world chain pero sólo admite world coin y cometí el error de enviar " USDC.e", desearía ayuda con el proceso para poder reembolsarlo. Hash " 0x7b3fcbe3aab9c8c564aed2f18898c2614c560c77335617a1f308271e98dcef2c ".

### Type of the installation

Manual from the source code

### Type of the JSON RPC archive node

Geth

### Type of the chain

Nivel 1

### Link to the page

https://worldchain-mainnet.explorer.alchemy.com/tx/0x7b3fcbe3aab9c8c564aed2f18898c2614c560c77335617a1f308271e98dcef2c?tab=token_transfers

### Steps to reproduce

Hash " 0x7b3fcbe3aab9c8c564aed2f18898c2614c560c77335617a1f308271e98dcef2c "

### Backend version

v6.10

### Frontend version

v1.35.2+08de20eb

### Elixir & Erlang/OTP versions

Elixir 1.17.3 (Compilado con Elrang/OTP 27)

### Operating system

Android

### Additional information

**User Agent:** Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Mobile Safari/537.36

**Comment by vbaranov** [comment]
This chat is for Blockscout-related questions. Your question is out of scope, where the Blockscout team can help.
