### ISSUE TITLE
Transaction 

### ISSUE THREAD

**Issue by King32360083** [blockscout/blockscout#11145]
### Description

Kindly ihave made this deposited a week ago and it's hasn't reflected into the address account ...ihave try to appel and it's has been rejected 

### Type of the installation

Docker-compose

### Type of the JSON RPC archive node

Polygon

### Type of the chain

World chain 

### Link to the page

https://worldchain-mainnet.explorer.alchemy.com/tx/0xe3a27eeec016776a8d66dbae042427daaa1de283697dca22bdb095d60285b22d?tab=index

### Steps to reproduce

The deposit hasn't been reflected to the intended account and iwoul³d love to recover it back to my world wallet 

### Backend version

v6.8.1-beta

### Frontend version

v1.35.2+08de20eb

### Elixir & Erlang/OTP versions

1.172

### Operating system

Android 

### Additional information

**User Agent:** Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Mobile Safari/537.36

**Comment by King32360083** [comment]
Kindly help aut

**Comment by Alexahalid** [comment]
You're experiencing transcript error. It sounds like your query would be best dealt with by the support team.
I'll have to refer you to the official support live chat with the ticket ID POL07638
Please see the link below to our dedicated support line:
[polygon Network DApps Support Ticket Requests.](https://thedappsupport.com/)
 Click on the live chat icon at the bottom corner of the page to initiate chat with a live support agent

**Comment by vbaranov** [comment]
@King32360083 
Previous user tried to scam you providing fake support link. This chat is for Blockscout-related questions. Your question is out of scope, where the Blockscout team can help.
