### ISSUE TITLE
Parthenon Athene

### ISSUE THREAD

**Issue by Sanctusvitus** [blockscout/blockscout#11152]
### Description

I can not add Parthenon Athene to my meta mask account it always comes with an error please look into it thank you.

### Type of the installation

Docker-compose

### Type of the JSON RPC archive node

Ethereum 

### Type of the chain

L1

### Link to the page

https://parthenon.athenescan.io/address/0xA65bB81f25721b2c0053C6EFe147fEAEEE3babc7

### Steps to reproduce

Please I cannot add Athens to my meta mask account.

### Backend version

v6.7.2-beta

### Frontend version

v1.34.1+96191dfb

### Elixir & Erlang/OTP versions

Elixir 1

### Operating system

Android 

### Additional information

**User Agent:** Mozilla/5.0 (Linux; Android 13; 23106RN0DA Build/TP1A.220624.014; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/130.0.6723.60 Mobile Safari/537.36 WebView MetaMaskMobile

**Comment by vbaranov** [comment]
The Blockscout team doesn't manage this instance of the explorer. Please, ask the question to the team, which supports this chain.
