### ISSUE TITLE
I have not received my usdc

### ISSUE THREAD

**Issue by Bbygirlnaa** [blockscout/blockscout#11159]
### Description

I have not received my usdc

### Type of the installation

Docker-compose

### Type of the JSON RPC archive node

Polygonedge

### Type of the chain

BSC(BEP20)

### Link to the page

https://worldchain-mainnet.explorer.alchemy.com/tx/0xdc9842cc6a51952c748ac072fd0ca1e4c7b974243cf5ad846572c366ef381ccd?tab=index

### Steps to reproduce

Please I deposited the usdc nine hours ago and haven’t received anything

### Backend version

v6.9.0-beta

### Frontend version

v1.35.2+08de20eb

### Elixir & Erlang/OTP versions

Otp

### Operating system

IOS

### Additional information

**User Agent:** Mozilla/5.0 (iPhone; CPU iPhone OS 17_5_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Mobile/15E148

**Comment by sl1depengwyn** [comment]
This repo is for Blockscout-related questions. Blockscout is an open source blockchain explorer. Thus, your question is out of scope, where the Blockscout team can help, you better contact the chain support directly.
