### ISSUE TITLE
"There are no blocks."

### ISSUE THREAD

**Issue by wighawag** [blockscout/blockscout#11151]
### Description

I am using blockscout locally against geth

I tried both 

```
docker compose -f geth-clique-consensus.yml up -d
```

and

```
docker compose -f geth.yml up -d
```

But I get "There are no blocks" even though I can make treansaction on 0.0.0.0:8545

When I looks at the log, I don't see any clear error

any way to get more ifno ?

### Type of the installation

Docker-compose

### Type of the JSON RPC archive node

Geth

### Type of the chain

Local (--dev)

### Backend version

latest github master

### Frontend version

latest github master

### Elixir & Erlang/OTP versions

latest github master

### Operating system

Linux

**Comment by GimluCom** [comment]
Did you run geth with the flags `--http.addr 0.0.0.0 --ws.addr 0.0.0.0` ?
For support with deploying Blockscout we recommend using the Discord server [discord.gg/blockscout](https://discord.gg/blockscout)

**Comment by wighawag** [comment]
yes, done that. any flag I could set to see more what is wrong ?

**Comment by wighawag** [comment]
The issues was actually that my system had a firewall that also block docker use of `host.docker.internal`
Disabling the firewall made it all works
