### ISSUE TITLE
No han llegado 13USDC a mi cuenta de binance

### ISSUE THREAD

**Issue by Andrea-gg-79** [blockscout/blockscout#11154]
### Description

El día 30 de octubre del año 2024 a las 13:00 horas realice una transferencia de 13USDC a mi cuenta personal de binance y hoy jueves 7 de noviembre reviso mi cuenta y verifico que los 13USDC no se han reflejado o nisiquiera han llegado, pido de antemano que se me regresen los 13USDC perdidos o que se me devuelvan a mi cuenta de worldcoin

### Type of the installation

Docker-compose

### Type of the JSON RPC archive node

Geth

### Type of the chain

2

### Link to the page

https://worldchain-mainnet.explorer.alchemy.com/tx/0x3f7a600aa275bd8a0955524a35678656a9d857e7b4ae2058f6d3de3514b45554

### Steps to reproduce

El día 30 de octubre del año 2024 a las 13:00 horas realice una transferencia de 13USDC a mi cuenta personal de binance y hoy jueves 7 de noviembre reviso mi cuenta y verifico que los 13USDC no se han reflejado o nisiquiera han llegado, pido de antemano que se me regresen los 13USDC perdidos o que se me devuelvan a mi cuenta de worldcoin

### Backend version

v6.9.0-beta

### Frontend version

v1.35.2+08de20eb

### Elixir & Erlang/OTP versions

Elixir 1.17.3

### Operating system

Android

### Additional information

**User Agent:** Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Mobile Safari/537.36
![Screenshot_20241107-123644](https://github.com/user-attachments/assets/be6434dd-f5ae-4db1-8f30-470e62a3d571)

**Comment by vbaranov** [comment]
This chat is for Blockscout-related questions. Your question is out of scope, where the Blockscout team can help.
