### ISSUE TITLE
Withdrawal issue from Athene to Binance 

### ISSUE THREAD

**Issue by Sajid5533765** [blockscout/blockscout#11158]
### Description

Dear Athen Support,

I'm writing to report a withdrawal issue. On [date], I initiated a withdrawal of [4998795.328] from my Athen account (ID: [account ID alinizamani120@gmail.com]) to my Binance account. However, the funds have not been credited to my Binance account.

Transaction ID: [transaction ID1083080512]
Athen Account ID: [account ID]
Binance Account 0x715bea4aa7a9e190f05a8ccf39603d2d93230c775eafa000368cc20127a003ceDetails: [account details]

Please investigate and resolve this issue.

Thank you,
[Sajid Ali]"

I'm writing to report a withdrawal issue. On [18:46

07/11/2024, I initiated a withdrawal of [4998795.328] from my Athen account (ID: [account ID alinizamani120@gmail.com]) to my Binance account. However, the funds have not been credited to my Binance account.

Transaction ID: [transaction ID1083080512]
Athen Account ID: [account ID]
Binance Account 0x715bea4aa7a9e190f05a8ccf39603d2d93230c775eafa000368cc20127a003ceDetails: [account details]

Please investigate and resolve this issue.

Thank you,
[Sajid Ali]"

Show quoted text

### Type of the installation

Manual from the source code

### Type of the JSON RPC archive node

Binance 

### Type of the chain

0x715bea4aa7a9e190f05a8ccf39603d2d93230c775eafa000368cc20127a003ce

### Link to the page

https://parthenon.athenescan.io/block/2153919

### Steps to reproduce

Dear Athen Support,

I'm writing to report a withdrawal issue. On [date], I initiated a withdrawal of [4998795.328] from my Athen account (ID: [account ID alinizamani120@gmail.com]) to my Binance account. However, the funds have not been credited to my Binance account.

Transaction ID: [transaction ID1083080512]
Athen Account ID: [account ID]
Binance Account 0x715bea4aa7a9e190f05a8ccf39603d2d93230c775eafa000368cc20127a003ceDetails: [account details]

Please investigate and resolve this issue.

Thank you,
[Sajid Ali]"

I'm writing to report a withdrawal issue. On [18:46

07/11/2024, I initiated a withdrawal of [4998795.328] from my Athen account (ID: [account ID alinizamani120@gmail.com]) to my Binance account. However, the funds have not been credited to my Binance account.

Transaction ID: [transaction ID1083080512]
Athen Account ID: [account ID]
Binance Account 0x715bea4aa7a9e190f05a8ccf39603d2d93230c775eafa000368cc20127a003ceDetails: [account details]

Please investigate and resolve this issue.

Thank you,
[Sajid Ali]"

Show quoted text

### Backend version

v6.7.2-beta

### Frontend version

v1.34.1+96191dfb

### Elixir & Erlang/OTP versions

Gmail

### Operating system

Mobile app

### Additional information

**User Agent:** Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Mobile Safari/537.36

**Comment by sl1depengwyn** [comment]
This repo is for Blockscout-related questions. Blockscout is an open source blockchain explorer. Thus, your question is out of scope, where the Blockscout team can help, you better contact the chain support directly.
