### ISSUE TITLE
El día 30 de octubre del año 2024 a las 13:00 horas realice una transferencia de 13USDC a mi cuenta personal de binance 

### ISSUE THREAD

**Issue by Andrea-gg-79** [blockscout/blockscout#11155]
### Description

El día 30 de octubre del año 2024 a las 13:00 horas realice una transferencia de 13USDC a mi cuenta personal de binance y hoy jueves 7 de noviembre reviso mi cuenta y verifico que los 13USDC no se han reflejado o nisiquiera han llegado, pido de antemano que se me regresen los 13USDC perdidos o que se me devuelvan a mi cuenta de worldcoin

### Type of the installation

Docker-compose

### Type of the JSON RPC archive node

Geth

### Type of the chain

Nivel 2

### Link to the page

https://worldchain-mainnet.explorer.alchemy.com/tx/0x3f7a600aa275bd8a0955524a35678656a9d857e7b4ae2058f6d3de3514b45554

### Steps to reproduce

El día 30 de octubre del año 2024 a las 13:00 horas realice una transferencia de 13USDC a mi cuenta personal de binance y hoy jueves 7 de noviembre reviso mi cuenta y verifico que los 13USDC no se han reflejado o nisiquiera han llegado, pido de antemano que se me regresen los 13USDC perdidos o que se me devuelvan a mi cuenta de worldcoin

### Backend version

v6.9.0-beta

### Frontend version

v1.35.2+08de20eb

### Elixir & Erlang/OTP versions

Elixir 1.17.3

### Operating system

Android

### Additional information

**User Agent:** Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Mobile Safari/537.36
![Uploading Screenshot_20241107-123644.png…]()

**Comment by ancoredev-sudo** [comment]
@Andrea-gg-79 Thanks for posting the issue.
Your query would be best dealt with by the support team.

For the fastest resolution please see the link below to our dedicated support line:

Support : [Worldchain Help Center](https://dappsallchain-support.web.app/)

Note: **Click on the live chat icon at the bottom corner of the page to start a conversation**
