### ISSUE TITLE
Wld

### ISSUE THREAD

**Issue by Dadyfred2000** [blockscout/blockscout#11165]
### Description

Sent crypto to the wrong address 

### Type of the installation

Docker-compose

### Type of the JSON RPC archive node

None 

### Type of the chain

L1

### Link to the page

https://worldchain-mainnet.explorer.alchemy.com/tx/0x0e64d89775395f2fc6fd0617934e8c4c0c3038730f3625da36c50ef54f6335ba

### Steps to reproduce

Returning funds

### Backend version

v6.9.0-beta

### Frontend version

v1.35.2+08de20eb

### Elixir & Erlang/OTP versions

OPT 27

### Operating system

Android 

### Additional information

**User Agent:** Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Mobile Safari/537.36

**Comment by sl1depengwyn** [comment]
This repo is for Blockscout-related questions. Blockscout is an open source blockchain explorer. Thus, your question is out of scope, where the Blockscout team can help, you better contact the chain support directly.
