### ISSUE TITLE
Wrong network send wld coin

### ISSUE THREAD

**Issue by manpower2u** [blockscout/blockscout#11164]
### Description

Pls help mee I just send wrong network 
To ERC20 not using world chain network

To ERC20 0x73ffc1982176b2bf58dacc3a175f34d330c3cab6

cont you refend back to my wallet...
Has no is transition
0x0c18c5e71e1c855237ca578e23e75dbf72044c4b5d4f3b0dae77be41b42bf481

Wallet WLD
0x649aedb441ccde8436f47ebc5c2340a812ae9dbf

### Type of the installation

Docker

### Type of the JSON RPC archive node

Wrong send network

### Link to the page

https://worldchain-mainnet.explorer.alchemy.com/tx/0x059c639d53941eec90ca893d44fc7114812deb29ab93da4cc36c08fe2c647d83

### Steps to reproduce

cont you refend back to my wallet...
Has no is transition
0x0c18c5e71e1c855237ca578e23e75dbf72044c4b5d4f3b0dae77be41b42bf481

Wallet WLD
0x649aedb441ccde8436f47ebc5c2340a812ae9dbf

### Backend version

v6.9.0-beta

### Frontend version

v1.35.2+08de20eb

### Elixir & Erlang/OTP versions

Send

### Additional information

**User Agent:** Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Mobile Safari/537.36

**Comment by sl1depengwyn** [comment]
This repo is for Blockscout-related questions. Blockscout is an open source blockchain explorer. Thus, your question is out of scope, where the Blockscout team can help, you better contact the chain support directly.
