### ISSUE TITLE
My wld tokens never arrived in my bybit account

### ISSUE THREAD

**Issue by Kibeslime** [blockscout/blockscout#11161]
### Description

My wld tokens never arrived in my bybit account****

### Type of the installation

Docker-compose

### Type of the JSON RPC archive node

Polygonedge

### Type of the chain

L2 mainet 

### Link to the page

0x450d33aef9f9332dbdd9905d653e846b9c0ff769

### Steps to reproduce

Swnd my wls tokens to my bybit 

### Backend version

v6.9.0-beta

### Frontend version

v1.35.2+08de20eb

### Elixir & Erlang/OTP versions

OP mainet

### Operating system

Android 

### Additional information

**User Agent:** Mozilla/5.0 (Linux; U; Android 10; TECNO KD6 Build/QP1A.190711.020; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/130.0.6723.106 Mobile Safari/537.36 OPR/85.0.2254.74549

**Comment by sl1depengwyn** [comment]
This repo is for Blockscout-related questions. Blockscout is an open source blockchain explorer. Thus, your question is out of scope, where the Blockscout team can help, you better contact the chain support directly.
