### ISSUE TITLE
Me

### ISSUE THREAD

**Issue by Nguyenhung078** [blockscout/blockscout#11166]
Check multichain info for this address here on Blockscan. Here's the link: https://blockscan.com/address/0x55d398326f99059ff775485246999027b3197955

**Comment by Nguyenhung078** [comment]
> Check multichain info for this address here on Blockscan. Here's the link: https://blockscan.com/address/0x55d398326f99059ff775485246999027b3197955

**Comment by vbaranov** [comment]
This chat is for Blockscout-related questions. Your question is out of scope, where the Blockscout team can help.
