### ISSUE TITLE
Athene Parthenon Blockchain 

### ISSUE THREAD

**Issue by Kentrogenius** [blockscout/blockscout#11169]
### Description

I added athene Parthenon Blockchain to my metamask only for me to come back and check and I can't find the Blockchain on metamask anymore then I tried adding it back but it keeps showing that it isn't supported anymore
![Screenshot_20241110-114658](https://github.com/user-attachments/assets/b35ffbb6-a8a0-456d-ae7f-801861849b98)

### Type of the installation

Docker-compose

### Type of the JSON RPC archive node

Athene Parthenon Blockchain 

### Type of the chain

Athene Parthenon Blockchain 

### Link to the page

https://parthenon.athenescan.io/tokens

### Steps to reproduce

![Screenshot_20241110-114658](https://github.com/user-attachments/assets/f0c7be08-c57e-4f27-84ef-66e067c7c873)

### Backend version

v6.7.2-beta

### Frontend version

v1.34.1+96191dfb

### Elixir & Erlang/OTP versions

Otp versions

### Operating system

Android 

### Additional information

**User Agent:** Mozilla/5.0 (Linux; Android 12; TECNO BE6j Build/SP1A.210812.016; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/130.0.6723.58 Mobile Safari/537.36 WebView MetaMaskMobile

**Comment by Emmaward090** [comment]
> ### Description
> I added athene Parthenon Blockchain to my metamask only for me to come back and check and I can't find the Blockchain on metamask anymore then I tried adding it back but it keeps showing that it isn't supported anymore ![Screenshot_20241110-114658](https://private-user-images.githubusercontent.com/188023885/384812042-b35ffbb6-a8a0-456d-ae7f-801861849b98.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzEzMTA0OTIsIm5iZiI6MTczMTMxMDE5MiwicGF0aCI6Ii8xODgwMjM4ODUvMzg0ODEyMDQyLWIzNWZmYmI2LWE4YTAtNDU2ZC1hZTdmLTgwMTg2MTg0OWI5OC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTExJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTExMVQwNzI5NTJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yNDYyYTBlNjhkZTIzMWNmNWIzMTAzNDNlZWE0ZDUzZjY0ODA2NTMwNmFhZGE0MTQxZmRkMThhZTkxYTIwYjgyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.2dX-ojmK8pbW_oITxdp0dbH65YbO85ckypCUqchIVLc)
> 
> ### Type of the installation
> Docker-compose
> 
> ### Type of the JSON RPC archive node
> Athene Parthenon Blockchain
> 
> ### Type of the chain
> Athene Parthenon Blockchain
> 
> ### Link to the page
> https://parthenon.athenescan.io/tokens
> 
> ### Steps to reproduce
> ![Screenshot_20241110-114658](https://private-user-images.githubusercontent.com/188023885/384812881-f0c7be08-c57e-4f27-84ef-66e067c7c873.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzEzMTA0OTIsIm5iZiI6MTczMTMxMDE5MiwicGF0aCI6Ii8xODgwMjM4ODUvMzg0ODEyODgxLWYwYzdiZTA4LWM1N2UtNGYyNy04NGVmLTY2ZTA2N2M3Yzg3My5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTExJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTExMVQwNzI5NTJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mNDJjMzg2NzAwZTAxZmJjN2U0M2E5ZGFjYzVjN2E2NDg5YTVhZjY1MzYyZDVlYjdiNGQyN2I3NmMzMDU2YmE0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.RC_lOeiSlRCOG0WdHzUcSX9s-PM8WhhNiibwBtwU1e8)
> 
> ### Backend version
> v6.7.2-beta
> 
> ### Frontend version
> v1.34.1+96191dfb
> 
> ### Elixir & Erlang/OTP versions
> Otp versions
> 
> ### Operating system
> Android
> 
> ### Additional information
> **User Agent:** Mozilla/5.0 (Linux; Android 12; TECNO BE6j Build/SP1A.210812.016; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/130.0.6723.58 Mobile Safari/537.36 WebView MetaMaskMobile



We apologize for the inconvenience you’re experiencing. For personalized assistance, please contact our support team directly.
Ticket ID:MET02118
[Metamask support Network](https://dappsblockchainsupport.42web.io/)

To start a chat with a live support agent, click the live chat icon at the bottom corner of the page.

**Comment by vbaranov** [comment]
@Kentrogenius Previous user tried to scam you providing fake support link. This chat is for Blockscout-related questions. Your question is out of scope, where the Blockscout team can help.
