### ISSUE TITLE
Problema de transacción 

### ISSUE THREAD

**Issue by Geovanipes** [blockscout/blockscout#11167]
### Description

El 25 de octubre hice una transacción y hasta el momento no e recibido el monto por dicha transacción 

0xe489e4F2ca3C3A7C55bB91c36b2AC4E65dE4dDC6

Ese es código de la transacción 

### Type of the installation

Docker-compose

### Type of the JSON RPC archive node

OpenEnther

### Backend version

V6.1.0

### Frontend version

Versión 1.11.1

### Elixir & Erlang/OTP versions

Elixir 1.17.3

**Comment by vbaranov** [comment]
This chat is for Blockscout-related questions. Your question is out of scope, where the Blockscout team can help.
