### ISSUE TITLE
Coin is debited in this account. But not received at receiver 

### ISSUE THREAD

**Issue by Dhakreg** [blockscout/blockscout#11173]
### Description

I send 5.2 world coin to bybit application. But it was not received yet

### Type of the installation

Manual from the source code

### Type of the JSON RPC archive node

0xe4acf33cfd48ed5926dc987264728934feaddb33

### Type of the chain

Optimization 

### Link to the page

https://worldchain-mainnet.explorer.alchemy.com/tx/0xd080e506fed08e55116ef81598a51ebb7ef84544f3e4dd18567b5ab604e00639

### Steps to reproduce

.

### Backend version

v6.9.0-beta

### Frontend version

v1.35.2+08de20eb

### Elixir & Erlang/OTP versions

.

### Additional information

**User Agent:** Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Mobile Safari/537.36

**Comment by vbaranov** [comment]
This chat is for Blockscout-related questions. Your question is out of scope, where the Blockscout team can help.
