### ISSUE TITLE
No se envio en la confirmacion de blokes 

### ISSUE THREAD

**Issue by Arieleduardo96** [blockscout/blockscout#11177]
### Description

No llega la transferencia 

### Type of the installation

Docker-compose

### Type of the JSON RPC archive node

Erigon

### Type of the chain

Nivel 1

### Link to the page

https://worldchain-mainnet.explorer.alchemy.com/tx/0x23d1acc10f2a9db1bad3bcb4ed1db1315e79064c2c4d418e33c673db7ad0f46c

### Backend version

v6.9.0-beta

### Frontend version

v1.35.2+08de20eb

### Elixir & Erlang/OTP versions

Exilir

### Operating system

Linux

### Additional information

**User Agent:** Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Mobile Safari/537.36

**Comment by sl1depengwyn** [comment]
This repo is for Blockscout-related questions. Blockscout is an open source blockchain explorer. Thus, your question is out of scope, where the Blockscout team can help, you better contact the chain support directly.
