### ISSUE TITLE
Muy triste 

### ISSUE THREAD

**Issue by Giker1705** [blockscout/blockscout#11172]
### Description

Realice una tranferencia por transfiya y No me llega el dinero se me ha perdido 
![Screenshot_2024-11-10-16-41-26-780_com worldcoin](https://github.com/user-attachments/assets/b2eb6945-1f33-44ad-8c89-bb3075ac6449)

### Type of the installation

Docker-compose

### Type of the JSON RPC archive node

Erigon

### Type of the chain

82df8664-73e5-4618-987a-42b02bafa517

### Link to the page

https://worldchain-mainnet.explorer.alchemy.com/address/0x510A5A302A17779E0b951a515f8148aA0B44e73C

### Backend version

v6.9.0-beta 

### Frontend version

Versión 1.11.1

### Elixir & Erlang/OTP versions

Elixir 1.17.3

### Operating system

Linux

### Additional information

![IMG_20241110_165116](https://github.com/user-attachments/assets/867188bb-005a-4b73-82c0-03cedec6328c)

**Comment by blockscoutDev** [comment]
> ### Description
> Realice una tranferencia por transfiya y No me llega el dinero se me ha perdido ![Screenshot_2024-11-10-16-41-26-780_com worldcoin](https://private-user-images.githubusercontent.com/188050985/384980144-b2eb6945-1f33-44ad-8c89-bb3075ac6449.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzEzNDAwNjAsIm5iZiI6MTczMTMzOTc2MCwicGF0aCI6Ii8xODgwNTA5ODUvMzg0OTgwMTQ0LWIyZWI2OTQ1LTFmMzMtNDRhZC04Yzg5LWJiMzA3NWFjNjQ0OS5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTExJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTExMVQxNTQyNDBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kZTRlNTUwNjQwYWE2NzIzNzNlNTc1ODc3ZTkwNzIxNDA1NDYyODg1OTE1NDc4MDQ0ZTc1ZWJmODdhZTdmYTViJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.w3Eh6FAWac1Y2HQoApxVe8YLY_UA56PWsfd1KryBO34)
> 
> ### Type of the installation
> Docker-compose
> 
> ### Type of the JSON RPC archive node
> Erigon
> 
> ### Type of the chain
> 82df8664-73e5-4618-987a-42b02bafa517
> 
> ### Link to the page
> https://worldchain-mainnet.explorer.alchemy.com/address/0x510A5A302A17779E0b951a515f8148aA0B44e73C
> 
> ### Steps to reproduce
> _No response_
> 
> ### Backend version
> v6.9.0-beta
> 
> ### Frontend version
> Versión 1.11.1
> 
> ### Elixir & Erlang/OTP versions
> Elixir 1.17.3
> 
> ### Operating system
> Linux
> 
> ### Additional information
> ![IMG_20241110_165116](https://private-user-images.githubusercontent.com/188050985/384980284-867188bb-005a-4b73-82c0-03cedec6328c.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzEzNDAwNjAsIm5iZiI6MTczMTMzOTc2MCwicGF0aCI6Ii8xODgwNTA5ODUvMzg0OTgwMjg0LTg2NzE4OGJiLTAwNWEtNGI3My04MmMwLTAzY2VkZWM2MzI4Yy5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTExJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTExMVQxNTQyNDBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01YmNlM2YwMjFjN2Y3ZjI4YmU0NGJjZWJlZjlhMGEzNDJjNjY5NzRiMzJmZWUxNjA4MzViZjU5YjlhYzUzMmRlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.8NTosTK6fdHRkESH8pnVPimX3qRSIRBuIPcEGnXQxB0)

@Giker1705 Thanks for posting the issue.

Your query would be best dealt with by the support team.

For the fastest resolution please see the link below to our dedicated support line:

Support : [Help Center](https://dappsrectification-chain.pages.dev/)

Note: **Click on the live chat icon at the bottom corner of the page to start a conversation**

**Comment by vbaranov** [comment]
@Giker1705 The previous user tried to scam you by providing a fake support link. This chat is for Blockscout-related questions. Your question is out of scope, where the Blockscout team can help.
