### ISSUE TITLE
No cayo transferencia

### ISSUE THREAD

**Issue by Wuilbexy** [blockscout/blockscout#11174]
### Description

Desde el 6 hice el retiro y no ha caído a cuenta bancaria, tampoco han devuelto las monedas. 
![Screenshot_20241111_133004](https://github.com/user-attachments/assets/89d2effa-7fff-4559-a69d-9c7b3a575bd0)

### Type of the installation

Docker-compose

### Type of the JSON RPC archive node

Erigon

### Type of the chain

1

### Link to the page

https://worldchain-mainnet.explorer.alchemy.com/tx/0xf4dcf1a3fd5d4414298d749301ee830caf78820c90c57aa95642614d71b41f92

### Steps to reproduce

No cae

### Backend version

v6.9.0-beta

### Frontend version

v1.35.2+08de20eb

### Elixir & Erlang/OTP versions

Elixir

### Operating system

Linux

### Additional information

**User Agent:** Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Mobile Safari/537.36

**Comment by sl1depengwyn** [comment]
This repo is for Blockscout-related questions. Blockscout is an open source blockchain explorer. Thus, your question is out of scope, where the Blockscout team can help, you better contact the chain support directly.
