### ISSUE TITLE
Pending transaction that will not clear

### ISSUE THREAD

**Issue by Jok2404** [blockscout/blockscout#11189]
### Description

0x288ad07174891232f03ae1e83001b58eda9de85ec8502db6b1b2e8bc45111e2e.  This transaction ID is pending despite several attempts to speed it up/cancel it.

### Type of the installation

Docker-compose

### Type of the JSON RPC archive node

not known

### Type of the chain

Neurochain

### Link to the page

https://ncnscan.com/tx/0x288ad07174891232f03ae1e83001b58eda9de85ec8502db6b1b2e8bc45111e2e?tab=index

### Backend version

5.1.4

### Frontend version

v1.33.2+089ef89e

### Elixir & Erlang/OTP versions

n/a

### Operating system

macOS

### Additional information

**User Agent:** Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36

**Comment by GimluCom** [comment]
Most likely the issue is your earlier pending transaction, which has a much lower gas price.

Please note:
> This repo is for Blockscout-related questions. Blockscout is an open source blockchain explorer. Thus, your question is out of scope, where the Blockscout team can help. You may instead contact the chain or platform which you are using.
