### ISSUE TITLE
Mi retiro no me ah llegado 

### ISSUE THREAD

**Issue by luzgreci** [blockscout/blockscout#11190]
### Description

Mi retiro no me ah llegado a mi cuenta que puedo hacer para devolver mi retiro 

### Type of the installation

Manual from the source code

### Type of the JSON RPC archive node

.......

### Type of the chain

Nivel 1

### Link to the page

https://worldchain-mainnet.explorer.alchemy.com/tx/0xd0e5a2fdcdaf8791d49effe00f97d552cb291507fb8560d8d2f1ae37e6e835d5

### Steps to reproduce

Mi retiro no me ah llegado a mi cuenta que puedo hacer para devolver mi retiro 

### Backend version

v6.9.0-beta

### Frontend version

v1.35.2+08de20eb

### Elixir & Erlang/OTP versions

?????

### Operating system

Teléfono Android 

### Additional information

**User Agent:** Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Mobile Safari/537.36 mi retiro no ah llegado

**Comment by vbaranov** [comment]
This chat is for Blockscout-related questions. Your question is out of scope, where the Blockscout team can help.
