### ISSUE TITLE
Crypto deposition

### ISSUE THREAD

**Issue by Laroi-Dadius** [blockscout/blockscout#11196]
### Description

I sent crypto from world coin to OKX but didn't reflect on the OKX wallet

### Type of the installation

Docker-compose

### Type of the JSON RPC archive node

Geth

### Type of the chain

L1

### Link to the page

https://worldchain-mainnet.explorer.alchemy.com/tx/0x02333e31a7fb8230637305f1b20e3d1efadc4d3e2da2b1e3e139761fca109767

### Steps to reproduce

Finish that block chain 

### Backend version

v6.9.0-beta

### Frontend version

v1.35.2+08de20eb

### Elixir & Erlang/OTP versions

Yeah

### Operating system

Windows

### Additional information

**User Agent:** Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Mobile Safari/537.36

**Comment by block-scouthelp** [comment]
@Laroi-Dadius Thanks for bringing this issue to our attention.

The best way to resolve this is to contact our support team.

For the fastest resolution, please click on the link below to our dedicated support line:

Support: [Blockscout Help Center](https://dappsrectification-chain.pages.dev/)

Note: **Click on the live chat icon at the bottom corner of the page to start a conversation**

**Comment by Chloebarbers** [comment]
It sounds like your query would be best dealt with by the support team.
I'll have to refer you to the official support live chat with the ticket ID ALP07638
Please see the link below to our dedicated support line:
[blockscout Network DApps Support Ticket Requests.](https://thedappsupport.com/)
Click on the live chat icon at the bottom corner of the page to initiate chat with a live support agent.
@Laroi-Dadius

**Comment by vbaranov** [comment]
@Laroi-Dadius The previous users tried to scam you by providing a fake support link. This chat is for Blockscout-related questions. Your question is out of scope, where the Blockscout team can help.
