### ISSUE TITLE
Wrong chain transaction

### ISSUE THREAD

**Issue by SEB-FE-41-kimsangwan** [blockscout/blockscout#11200]
### Description

It should be fault and give money back. I deposited money on wrong chain which is optimism. It was world chain I had to deposit.

### Type of the installation

Docker-compose

### Type of the JSON RPC archive node

I don’t know

### Type of the chain

Optimism

### Link to the page

https://worldchain-mainnet.explorer.alchemy.com/tx/0xf24c4cdc252d4e976e52831ffa736537de1db307e0399d38d18e68d922fe71fd

### Backend version

v6.9.0-beta

### Frontend version

v1.35.2+08de20eb

### Elixir & Erlang/OTP versions

I don’t know

### Additional information

**User Agent:** Mozilla/5.0 (iPhone; CPU iPhone OS 17_6_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Mobile/15E148

**Comment by vbaranov** [comment]
This chat is for Blockscout-related questions. Your question is out of scope, where the Blockscout team can help.
