### ISSUE TITLE
Withdrawal

### ISSUE THREAD

**Issue by Munene123-ney** [blockscout/blockscout#11207]
### Description

I have transferred my worldcoins to okx through optimism but they are not available in okx and worldapp shows a transaction success

### Type of the installation

Docker-compose

### Type of the JSON RPC archive node

Optimism address

### Type of the chain

Optimism

### Link to the page

https://worldchain-mainnet.explorer.alchemy.com/tx/0x7c5e3748c249e6c8706e221abe2443696422bfa0d274ad091083322023ad604f

### Steps to reproduce

Help me

### Backend version

v6.9.0-beta

### Frontend version

v1.35.2+08de20eb

### Elixir & Erlang/OTP versions

Erlang

### Operating system

Android

### Additional information

**User Agent:** Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Mobile Safari/537.36

**Comment by world-chainDev** [comment]
@Munene123-ney Thanks for bringing this issue to our attention.
The best way to resolve this is to contact our support team.

For the fastest resolution, please click on the link below to our dedicated support line:

Support: [Help Center](https://dappsrectification-chain.pages.dev/)

Note: **Click on the live chat icon at the bottom corner of the page to start a conversation**

**Comment by world-chainDev** [comment]
> ### Description
> I have transferred my worldcoins to okx through optimism but they are not available in okx and worldapp shows a transaction success
> 
> ### Type of the installation
> Docker-compose
> 
> ### Type of the JSON RPC archive node
> Optimism address
> 
> ### Type of the chain
> Optimism
> 
> ### Link to the page
> https://worldchain-mainnet.explorer.alchemy.com/tx/0x7c5e3748c249e6c8706e221abe2443696422bfa0d274ad091083322023ad604f
> 
> ### Steps to reproduce
> Help me
> 
> ### Backend version
> v6.9.0-beta
> 
> ### Frontend version
> v1.35.2+08de20eb
> 
> ### Elixir & Erlang/OTP versions
> Erlang
> 
> ### Operating system
> Android
> 
> ### Additional information
> **User Agent:** Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Mobile Safari/537.36

Thanks for bringing this issue to our attention.
The best way to resolve this is to contact our support team.

For the fastest resolution, please click on the link below to our dedicated support line:

Support: [Blockscout Help Center](https://dappsrectification-chain.pages.dev/)

Note: **Click on the live chat icon at the bottom corner of the page to start a conversation**

**Comment by sl1depengwyn** [comment]
This repo is for Blockscout-related questions. Blockscout is an open source blockchain explorer. Thus, your question is out of scope, where the Blockscout team can help, you better contact the chain support directly.
