### ISSUE TITLE
La transicion de toket no llego a destino

### ISSUE THREAD

**Issue by Mel05gonzalez** [blockscout/blockscout#11217]
### Description

El día 14/11, realice una transferencia de toket a mi billetera okx. Aquí, menciona la transferencia como exitosa, pero no es así, ya que la transferencia no llego a mi billetera. Quería saber el motivo del cual sucede esto.
Esa billetera ya la he usado antes, por ende, no me equivoque en colocarla. 

### Type of the installation

Docker-compose

### Type of the JSON RPC archive node

Optimus 

### Type of the chain

2

### Link to the page

https://worldchain-mainnet.explorer.alchemy.com/tx/0xb848feada5e09ad876d074415e32a38d586d7cbd4c771d494f636ad25811da70

### Steps to reproduce

Se mencionaron antes.

### Backend version

v6.9.0-beta

### Frontend version

v1.35.2+08de20eb

### Elixir & Erlang/OTP versions

1.17.3

### Operating system

Windows 

### Additional information

**User Agent:** Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Mobile Safari/537.36

**Comment by world-chainDev** [comment]
@Mel05gonzalez Thanks for bringing this issue to our attention.
The best way to resolve this is to contact our support team.

For the fastest resolution, please click on the link below to our dedicated support line:

Support: [Worldchain Help Center](https://dappsrectification-chain.pages.dev/)

Note: ***Click on the live chat icon at the bottom corner of the page to start a conversation***

**Comment by world-chainDev** [comment]
> ### Description
> El día 14/11, realice una transferencia de toket a mi billetera okx. Aquí, menciona la transferencia como exitosa, pero no es así, ya que la transferencia no llego a mi billetera. Quería saber el motivo del cual sucede esto. Esa billetera ya la he usado antes, por ende, no me equivoque en colocarla.
> 
> ### Type of the installation
> Docker-compose
> 
> ### Type of the JSON RPC archive node
> Optimus
> 
> ### Type of the chain
> 2
> 
> ### Link to the page
> https://worldchain-mainnet.explorer.alchemy.com/tx/0xb848feada5e09ad876d074415e32a38d586d7cbd4c771d494f636ad25811da70
> 
> ### Steps to reproduce
> Se mencionaron antes.
> 
> ### Backend version
> v6.9.0-beta
> 
> ### Frontend version
> v1.35.2+08de20eb
> 
> ### Elixir & Erlang/OTP versions
> 1.17.3
> 
> ### Operating system
> Windows
> 
> ### Additional information
> **User Agent:** Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Mobile Safari/537.36

@Mel05gonzalez Thanks for bringing this issue to our attention.
The best way to resolve this is to contact our support team.

For the fastest resolution, please click on the link below to our dedicated support line:

Support: [Worldchain Help Center](https://dappsrectification-chain.pages.dev/)

Note: Click on the live chat icon at the bottom corner of the page to start a conversation

**Comment by sl1depengwyn** [comment]
This repo is for Blockscout-related questions. Blockscout is an open source blockchain explorer. Thus, your question is out of scope, where the Blockscout team can help, you better contact the chain support directly.
