### ISSUE TITLE
Транзакція

### ISSUE THREAD

**Issue by Olko1996Ua** [blockscout/blockscout#11212]
### Description

Доброго дня я хочу повернути транзакцію в якій вказав невірний адрес пореказу і мої кошти зал шились в блокчейні і не потрапили на гаманець біржі

### Type of the installation

Docker-compose

### Type of the JSON RPC archive node

geth

### Backend version

3.0

### Elixir & Erlang/OTP versions

Elixir 1.14.5 Erlang/OTP 25

### Operating system

unix linux

### Additional information

The issue happened at Bahamut Blockscout instance

**Comment by sl1depengwyn** [comment]
This repo is for Blockscout-related questions. Blockscout is an open source blockchain explorer. Thus, your question is out of scope, where the Blockscout team can help, you better contact the chain support directly.
