### ISSUE TITLE
Ingreso de cuenta worldcoin 

### ISSUE THREAD

**Issue by Leonel9626** [blockscout/blockscout#11215]
### Description

Perdí el celular y no puedo ingresar a worldcoin de otro celular 

### Type of the installation

Manual from the source code

### Type of the JSON RPC archive node

Optimismo 

### Type of the chain

1

### Link to the page

www.wordlcoin.com

### Backend version

v6. 1.0

### Frontend version

Versión 1.1.1

### Elixir & Erlang/OTP versions

Elixir 

### Operating system

Android

**Comment by vbaranov** [comment]
This chat is for Blockscout-related questions. Your question is out of scope, where the Blockscout team can help.
