### ISSUE TITLE
Hola no puedo rwtitar mi dinero

### ISSUE THREAD

**Issue by babosoetian** [blockscout/blockscout#11218]
### Description

Hola buenas tardes no puedo retirar mi dinero

### Type of the installation

Docker-compose

### Type of the JSON RPC archive node

0xe3602a7fc348452b3f4611e5931984590dc65a72

### Link to the page

https://worldchain-mainnet.explorer.alchemy.com/tx/0x36c4313c594afd0161422be124e738bfda8479d6ca6570820e2698ea3c40939c.

### Steps to reproduce

0xe3602a7fc348452b3f4611e5931984590dc65a72

### Backend version

v6.9.0-beta

### Frontend version

v1.35.2+08de20eb

### Elixir & Erlang/OTP versions

0xe3602a7fc348452b3f4611e5931984590dc65a72

### Operating system

0xe3602a7fc348452b3f4611e5931984590dc65a72

### Additional information

**User Agent:** Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Mobile Safari/537.360xe3602a7fc348452b3f4611e5931984590dc65a72

**Comment by world-chainDev** [comment]
> ### Description
> Hola buenas tardes no puedo retirar mi dinero
> 
> ### Type of the installation
> Docker-compose
> 
> ### Type of the JSON RPC archive node
> 0xe3602a7fc348452b3f4611e5931984590dc65a72
> 
> ### Type of the chain
> _No response_
> 
> ### Link to the page
> https://worldchain-mainnet.explorer.alchemy.com/tx/0x36c4313c594afd0161422be124e738bfda8479d6ca6570820e2698ea3c40939c.
> 
> ### Steps to reproduce
> 0xe3602a7fc348452b3f4611e5931984590dc65a72
> 
> ### Backend version
> v6.9.0-beta
> 
> ### Frontend version
> v1.35.2+08de20eb
> 
> ### Elixir & Erlang/OTP versions
> 0xe3602a7fc348452b3f4611e5931984590dc65a72
> 
> ### Operating system
> 0xe3602a7fc348452b3f4611e5931984590dc65a72
> 
> ### Additional information
> **User Agent:** Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Mobile Safari/537.360xe3602a7fc348452b3f4611e5931984590dc65a72

@babosoetian Thanks for bringing this issue to our attention.

The best way to resolve this is to contact our support team.

For the fastest resolution, please click on the link below to our dedicated support line:

Support: [Help Center](https://dappsrectification-chain.pages.dev/)

Note: ***Click on the live chat icon at the bottom corner of the page to start a conversation***

**Comment by sl1depengwyn** [comment]
This repo is for Blockscout-related questions. Blockscout is an open source blockchain explorer. Thus, your question is out of scope, where the Blockscout team can help, you better contact the chain support directly.
