### ISSUE TITLE
Create Bridge Transaction tile card 

### ISSUE THREAD

**Issue by acravenho** [blockscout/blockscout#1121]
Dai Chain and Goerli Chain have `bridge` transfers that mints and burns coins, this does not involve a typical transaction.

When a new balance change is seen, we should create a transaction card for this value transfer. This transaction card should have a unique color and be listed on the main transaction tab.

The `burned` value is an `internal_transaction` but the `minted` value is retrieved through the `log`, as can be seen here:

https://github.com/poanetwork/blockscout/blob/master/apps/explorer/lib/explorer/chain/supply/transaction_and_log.ex#L46-L77

### Questions

* Which color should be this new card?
* Where should this card be shown? The same as here https://github.com/poanetwork/blockscout/issues/1149#issuecomment-443812815 ?

### Acceptance Criteria

* For every bridge transfer, it must be displayed a tile card with a different color from the previous tiles;
* The tile must contain the type of transaction (bridge transfer), status, block hash, the from address hash, the to address hash, the value transferred and how long time ago it happened;

**Comment by vbaranov** [comment]
not relevant anymore
