### ISSUE TITLE
Quiero retirar dinero

### ISSUE THREAD

**Issue by babosoetian** [blockscout/blockscout#11221]
### Description

Hola envié mi dinero y lo quiero retirar 

### Type of the installation

Docker-compose

### Type of the JSON RPC archive node

0xe3602a7fc348452b3f4611e5931984590dc65a72

### Type of the chain

1

### Link to the page

https://worldchain-mainnet.explorer.alchemy.com/block/6099458

### Steps to reproduce

Necesito ni dinero eran 29000 ahora va en 19000 

### Backend version

v6.9.1-beta

### Frontend version

v1.36.2+f793609b

### Elixir & Erlang/OTP versions

0xe3602a7fc348452b3f4611e5931984590dc65a72

### Operating system

0xe3602a7fc348452b3f4611e5931984590dc65a72

### Additional information

**User Agent:** Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Mobile Safari/537.36

**Comment by sl1depengwyn** [comment]
This repo is for Blockscout-related questions. Blockscout is an open source blockchain explorer. Thus, your question is out of scope, where the Blockscout team can help, you better contact the chain support directly.
