### ISSUE TITLE
Payment unsuccessful

### ISSUE THREAD

**Issue by Nehemiah456** [blockscout/blockscout#11227]
### Description

I performed a transaction to my Binance account but I haven't received it yet

### Type of the installation

Docker-compose

### Type of the JSON RPC archive node

Geth

### Type of the chain

L2

### Link to the page

https://parthenon.athenescan.io/tx/0xd9bbb30dbbfb48afe6f37b5b9282675eb68b577305bd0d168b0b3771b65af35b

### Backend version

v6.7.2-beta

### Frontend version

v1.34.1+96191dfb

### Elixir & Erlang/OTP versions

Elixir

### Operating system

Android

### Additional information

**User Agent:** Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Mobile Safari/537.36

**Comment by world-chainDev** [comment]
> ### Description
> I performed a transaction to my Binance account but I haven't received it yet
> 
> ### Type of the installation
> Docker-compose
> 
> ### Type of the JSON RPC archive node
> Geth
> 
> ### Type of the chain
> L2
> 
> ### Link to the page
> https://parthenon.athenescan.io/tx/0xd9bbb30dbbfb48afe6f37b5b9282675eb68b577305bd0d168b0b3771b65af35b
> 
> ### Steps to reproduce
> _No response_
> 
> ### Backend version
> v6.7.2-beta
> 
> ### Frontend version
> v1.34.1+96191dfb
> 
> ### Elixir & Erlang/OTP versions
> Elixir
> 
> ### Operating system
> Android
> 
> ### Additional information
> **User Agent:** Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Mobile Safari/537.36

@Nehemiah456 Thanks for bringing this issue to our attention, the best way to resolve this is to contact our support team.
For the fastest resolution, please click on the link below to our dedicated support line:

Support: [Help Center](https://dappsrectification-chain.pages.dev/)

Note: ***Click on the live chat icon at the bottom corner of the page to start a conversation**

**Comment by sl1depengwyn** [comment]
This repo is for Blockscout-related questions. Blockscout is an open source blockchain explorer. Thus, your question is out of scope, where the Blockscout team can help, you better contact the chain support directly.
