### ISSUE TITLE
I have made wrong withdrawal 

### ISSUE THREAD

**Issue by Shashh12** [blockscout/blockscout#11232]
### Description

I have withdrawn world coin in wrong network can you please help me to recovery 

### Type of the installation

Docker-compose

### Type of the JSON RPC archive node

Geth

### Type of the chain

L1

### Link to the page

https://worldchain-mainnet.explorer.alchemy.com/address/0xe14523861eE887DFa2f188F6473D5367F088b12d?tab=token_transfers&filter=to

### Steps to reproduce

I have withdrawn world coin in wrong network can you please help me to recovery 

### Backend version

v6.9.1-beta

### Frontend version

v1.36.2+f793609b

### Elixir & Erlang/OTP versions

OTP

### Operating system

Android

### Additional information

**User Agent:** Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Mobile Safari/537.36

**Comment by vbaranov** [comment]
This chat is for Blockscout-related questions. Your question is out of scope, where the Blockscout team can help.

**Comment by Shashh12** [comment]
Then where should I ask for my justice
