### ISSUE TITLE
No me dan mis monedas 

### ISSUE THREAD

**Issue by AngiedeJ** [blockscout/blockscout#11238]
### Description

El mes pasado retire mis monedas y todavía no me las dan podría, cambiar la dirección de la cuenta de banco para recibirlas 

### Type of the installation

Docker-compose

### Type of the JSON RPC archive node

No se

### Type of the chain

No se

### Link to the page

https://worldchain-mainnet.explorer.alchemy.com/tx/0xfc49353e4bc83a06a48d9e28b4ff027326ed8305e10d3ee51116a2637f6112ef

### Backend version

v6.9.1-beta

### Frontend version

v1.36.2+f793609b

### Elixir & Erlang/OTP versions

No se

### Operating system

No se

### Additional information

**User Agent:** Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Mobile Safari/537.36

**Comment by vbaranov** [comment]
This chat is for Blockscout-related questions. Your question is out of scope, where the Blockscout team can help.
