### ISSUE TITLE
COIN NOT RECEIVED..

### ISSUE THREAD

**Issue by cryptomann99** [blockscout/blockscout#11234]
### Description

TRANSFER 2 WORLDCOIN BUT NIT RECEIVED IN MY WALLET

### Type of the installation

Docker-compose

### Type of the JSON RPC archive node

Geth

### Type of the chain

L1

### Link to the page

https://worldchain-mainnet.explorer.alchemy.com/tx/0xda9c11c54e3a558072447aa402dd04db3151d200e76979ea4bc7d8c95b3bdd25

### Steps to reproduce

![Screenshot_20241120_214448_Chrome](https://github.com/user-attachments/assets/0d3dc9b2-fd5d-4415-ba89-ed625ca506ab)
Transaction Hash 0xda9c11c54e3a558072447aa402dd04db3151d200e76979ea4bc7d8c95b3bdd25

### Backend version

v6.9.1-beta

### Frontend version

v1.36.2+f793609b

### Elixir & Erlang/OTP versions

OTP 7

### Operating system

windows

### Additional information

**User Agent:** Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Mobile Safari/537.36

**Comment by sl1depengwyn** [comment]
This repo is for Blockscout-related questions. Blockscout is an open source blockchain explorer. Thus, your question is out of scope, where the Blockscout team can help, you better contact the chain support directly.
