### ISSUE TITLE
La plata que envíe a mi cuenta no me refleja  hacerte por el número y no me sale a mi saldo

### ISSUE THREAD

**Issue by Vigail** [blockscout/blockscout#11249]
### Description

La plata de me llega a mi tranfiya

### Type of the installation

Docker-compose

### Type of the JSON RPC archive node

0x3bb6a48bfddf6eb4e7d444d143aa1440db55aefd

### Type of the chain

3

### Link to the page

https://worldchain-mainnet.explorer.alchemy.com/tx/0xd5eee6f91178fb168b1a96bbd2db826acee04e82153a0b3e51b448b16953f9df

### Steps to reproduce

No llega la plata 

### Backend version

v6.9.1-beta

### Frontend version

v1.36.2+f793609b

### Elixir & Erlang/OTP versions

0x3bb6a48bfddf6eb4e7d444d143aa1440db55aefd

### Operating system

0x3bb6a48bfddf6eb4e7d444d143aa1440db55aefd

### Additional information

**User Agent:** Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Mobile Safari/537.36

**Comment by sl1depengwyn** [comment]
This repo is for Blockscout-related questions. Blockscout is an open source blockchain explorer. Thus, your question is out of scope, where the Blockscout team can help, you better contact the chain support directly.
