### ISSUE TITLE
Advertising on our Explorer

### ISSUE THREAD

**Issue by mikevitruveo** [blockscout/blockscout#11250]
### Description

Vitruveo is currently using Blockscout and we see advertising on the platform, how do we have that removed?

### Type of the installation

Docker-compose

### Type of the JSON RPC archive node

?

### Type of the chain

L1

### Link to the page

https://explorer.vitruveo.xyz/txs

### Steps to reproduce

https://explorer.vitruveo.xyz/txs

### Backend version

6.1

### Frontend version

v1.34.1

### Elixir & Erlang/OTP versions

1.17

### Operating system

Linus

### Additional information

**User Agent:** Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36

**Comment by GimluCom** [comment]
Configuration options can be found at https://github.com/blockscout/frontend/blob/main/docs/ENVS.md#banner-ads
