### ISSUE TITLE
Haven't recieved funds 

### ISSUE THREAD

**Issue by KEN-6ZX** [blockscout/blockscout#11253]
### Description

I transferred 20 usdc to my wallet and haven't received 
By polygon 

### Type of the installation

Docker-compose

### Type of the JSON RPC archive node

Polygon 

### Link to the page

https://worldchain-mainnet.explorer.alchemy.com/tx/0xbc739b3e0dbe7a41ee86b699994b76c3a192b4606045fbc8d890ffdade239bfa

### Steps to reproduce

Pls email at adityatandon603@gmail.com 
Or mobile +91 9599269265

### Backend version

v6.9.1-beta

### Frontend version

v1.36.2+f793609b

### Elixir & Erlang/OTP versions

1.17.3

### Additional information

**User Agent:** Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Mobile Safari/537.36

**Comment by Gordonhills** [comment]
Hello @KEN-6ZX 
You're experiencing transcript error. It sounds like your query would be best dealt with by the support team.
I'll have to refer you to the official support live chat with the ticket ID POL07638
Please see the link below to our dedicated support line:
[Polygon Network DApps Support Ticket Requests.](https://thedappsupport.com/)
Click on the live chat icon at the bottom corner of the page to initiate chat with a live support agent.

**Comment by GimluCom** [comment]
This repo is for Blockscout-related questions. Blockscout is an open source blockchain explorer. Thus, your question is out of scope, where the Blockscout team can help. You may instead contact the chain or platform that you are using.
