### ISSUE TITLE
Tengo problema

### ISSUE THREAD

**Issue by Mathiascaceres** [blockscout/blockscout#11258]
### Description

No me llego el deposito a mi cuenta binance quiero recuperarlo 0xa279261a8e45f6e1f9830b8ce71804529ed0cc77a5ec8d7cecfaf401d03368b0

### Type of the installation

Docker-compose

### Type of the JSON RPC archive node

Nose

### Type of the chain

Nivel 2

### Link to the page

https://worldchain-mainnet.explorer.alchemy.com/tx/0xa279261a8e45f6e1f9830b8ce71804529ed0cc77a5ec8d7cecfaf401d03368b0

### Steps to reproduce

Realice transferencia desde mi wordcoin a binance y no me llego en binance

### Backend version

v6.9.1-beta

### Frontend version

v1.36.2+f793609b

### Elixir & Erlang/OTP versions

Nose

### Operating system

Android

### Additional information

**User Agent:** Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Mobile Safari/537.36

**Comment by sl1depengwyn** [comment]
This repo is for Blockscout-related questions. Blockscout is an open source blockchain explorer. Thus, your question is out of scope, where the Blockscout team can help, you better contact the chain support directly.
