### ISSUE TITLE
Token tidak masuk

### ISSUE THREAD

**Issue by Squisymoe** [blockscout/blockscout#11252]
### Description

Saya mengirim usdc tetapi tidak masuk (tetapi sukses)

### Type of the installation

Docker-compose

### Type of the JSON RPC archive node

Ethereum

### Type of the chain

L3

### Link to the page

https://explorer.immutable.com/address/0x17Ff541094de1b369f0263c85af0d6a48B49B22D?tab=token_transfers

### Steps to reproduce

Tolong di bantu

### Backend version

v6.9.1-beta

### Frontend version

v1.36.2+f793609b

### Elixir & Erlang/OTP versions

Elixir 1.17.3

### Operating system

Android

### Additional information

**User Agent:** Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Mobile Safari/537.36

**Comment by GimluCom** [comment]
This repo is for Blockscout-related questions. Blockscout is an open source blockchain explorer. Thus, your question is out of scope, where the Blockscout team can help. You may instead contact the chain or platform that you are using.
