### ISSUE TITLE
MainNet 

### ISSUE THREAD

**Issue by Everton22694** [blockscout/blockscout#11255]
### Description

Bom Dia tbm?
Fiz a transação para está conta na Kucoin e não sabia que a Worldcoin tinha Virado Chain e o valor de transferência não caiu na Conta Kucoin e me informaram que foi para MainNet e quero resgastar este valor, a Worldcoin falou para falar com a Kucoin e a Kucoin pediu para falar com a MainNet fica difícil é um recurso que preciso já faz dias está novela, 

### Type of the installation

Docker-compose

### Type of the JSON RPC archive node

0x2cFc85d8E48F8EAB294be644d9E25C3030863003

### Type of the chain

0x51D59fd45d672F773050c805313a35BC99E1f7c0

### Link to the page

https://worldchain-mainnet.explorer.alchemy.com/tx/0xec98e666666528b0b6063afb4c435d6cb34fd899e8ba12603d63045268166264?tab=raw_trace

### Steps to reproduce

A Worldcoin passou a ser Chain e não informou que mudou para Chain e a Kucoin não tinha Disponível está modalidade nova de conta e sempre usei e não tinha dado problema.

### Backend version

v6.9.1-beta

### Frontend version

v1.36.2+f793609b

### Elixir & Erlang/OTP versions

0x253bA702BF73bbBE3422120C12283435A73B5856

### Operating system

0x2cFc85d8E48F8EAB294be644d9E25C3030863003

### Additional information

**User Agent:** Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Mobile Safari/537.36

**Comment by vbaranov** [comment]
This chat is for Blockscout-related questions. Your question is out of scope, where the Blockscout team can help.
