### ISSUE TITLE
Eretheum 

### ISSUE THREAD

**Issue by Tc3434** [blockscout/blockscout#11259]
### Description

How do I possibly get rid of my eretheum? I want to transfer 20 I have out and cash it out but I have to first deposit 60 to take out 20 makes no sense. Hope this makes sense
![Screenshot_20241124-235212_Chrome](https://github.com/user-attachments/assets/2edabe07-eada-497c-96fc-9d0288c4cca1)

### Type of the installation

Docker-compose

### Type of the JSON RPC archive node

Eretheum 

### Type of the chain

L1

### Link to the page

https://keys.coinbase.com/sign/eth-send-transaction

### Backend version

v6.9.1-beta

### Frontend version

v1.36.2+f793609b

### Elixir & Erlang/OTP versions

Elixir

### Operating system

Android 14

### Additional information

**User Agent:** Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Mobile Safari/537.36
https://keys.coinbase.com/sign/eth-send-transaction

**Comment by sl1depengwyn** [comment]
This repo is for Blockscout-related questions. Blockscout is an open source blockchain explorer. Thus, your question is out of scope, where the Blockscout team can help, you better contact the chain support directly.
