### ISSUE TITLE
Retraso 

### ISSUE THREAD

**Issue by Matyas-galeto** [blockscout/blockscout#11260]
### Description

Realize una transferencia a mi cuenta y no se me ah llegado 

### Type of the installation

Manual from the source code

### Type of the JSON RPC archive node

Ethereum 

### Type of the chain

Nivel 2

### Link to the page

https://worldchain-mainnet.explorer.alchemy.com/tx/0x996f7e7a53d364bac805502318b0927c0d6683c5404cbb1b97accbd9557dc312

### Steps to reproduce

Realize el depósito pero más tarde se me notifico que había excedido el límite de transferencias a mi tarjeta por lo cual no llego, el día de hoy se hizo la actualización de cada mes y el pago aún no se refleja en mi estado de cuenta 

### Backend version

v6.9.1-beta

### Frontend version

v1.36.2+f793609b

### Elixir & Erlang/OTP versions

Desconozco 

### Operating system

Worldchain

### Additional information

Estos son los supuestos códigos de rastreo para supervisar el estado del movimiento (si se realizó, no se realizó o está pendiente) 59b5ec03-7ec4-4b1c-95ac-3073e6202a8f y f3ec8800-a05f-4b96-aa2b-95d7fd01b5ee pero al ingresarlo al buscador no identifica ninguno de los dos 
![Screenshot_20241125-024559](https://github.com/user-attachments/assets/598b26dd-3057-481d-9eb7-2c2a8dcc8f7b)
![Screenshot_20241125-024609](https://github.com/user-attachments/assets/25f0da30-9c72-4604-b8df-3103b971450a)

**Comment by sl1depengwyn** [comment]
This repo is for Blockscout-related questions. Blockscout is an open source blockchain explorer. Thus, your question is out of scope, where the Blockscout team can help, you better contact the chain support directly.
