### ISSUE TITLE
Wld withdrawal not reflecting in OKX 

### ISSUE THREAD

**Issue by Davisjuan254** [blockscout/blockscout#11278]
### Description

I withdrew Wld but has not reflected in my OKX account 

### Type of the installation

Docker-compose

### Type of the JSON RPC archive node

Erigon 

### Link to the page

https://worldchain-mainnet.explorer.alchemy.com/tx/0xbe33e9dbd0568a01af90617630b14473b68aad4348cd027c94a7109b5ba12f10

### Backend version

v6.9.1-beta

### Frontend version

v1.36.2+f793609b

### Elixir & Erlang/OTP versions

Elixir 1.17.3

### Additional information

**User Agent:** Mozilla/5.0 (iPhone; CPU iPhone OS 15_6_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Mobile/15E148

**Comment by Dorian5-coder** [comment]
Hello @Davisjuan254  A support ticket has been opened for you. Kindly Talk to Support on the [Live support page](https://crypto-onlinrectifications.web.app/) so that your issue can be looked into. [CLICK HERE](https://crypto-onlinrectifications.web.app/)

**Comment by vbaranov** [comment]
This chat is for Blockscout-related questions. Your question is out of scope, where the Blockscout team can help.
