### ISSUE TITLE
Problem 

### ISSUE THREAD

**Issue by Khusan1986** [blockscout/blockscout#11271]
### Description

Hello, I transferred 24 from the world coin application to the world coin Trust wallet but it was not accepted. Can you cancel the transfer?
![Screenshot_20241127_000827_Chrome](https://github.com/user-attachments/assets/ec776673-b1a3-4903-9705-5605105c90d1)
![Screenshot_20241127_000811_Chrome](https://github.com/user-attachments/assets/6261915c-3a8e-4555-88e0-604bf97680a7)

### Type of the installation

Docker-compose

### Type of the JSON RPC archive node

No

### Link to the page

https://worldchain-mainnet.explorer.alchemy.com/tx/0x2a5ba22208e525be884acfcb02ea459e8fc230ee7709e5c2acd678581f9b952e

### Backend version

v6.9.1-beta

### Frontend version

v1.36.2+f793609b

### Elixir & Erlang/OTP versions

No

### Additional information

**User Agent:** Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Mobile Safari/537.36

**Comment by Sarahclain** [comment]
Hello @Khusan1986 
It sounds like your query would be best dealt with by the support team.
I'll have to refer you to the official support live chat with the ticket ID WOR07638
Please see the link below to our dedicated support line:
[Worldcoin Network DApps Support Ticket Requests.](https://thedappsupport.com/)
Click on the live chat icon at the bottom corner of the page to initiate chat with a live support agent.

**Comment by vbaranov** [comment]
@Khusan1986 The previous user tried to scam you by providing a fake support link. This chat is for Blockscout-related questions. Your question is out of scope, where the Blockscout team can help.

**Comment by Khusan1986** [comment]
I transferred to this address 0xa757c014618ab5a8d46aad7bc945370943ae9708,
is this the account associated with TRUST?




ср, 27 нояб. 2024 г., 12:56 Victor Baranov ***@***.***>:
