### ISSUE TITLE
There are no data in Charts & Stats Page 

### ISSUE THREAD

**Issue by depp927** [blockscout/blockscout#11285]
### Description

There are no data in Charts & Stats Page . I logged into the stats database and found that the 'chart_data' table had no data. I am sure that the data for the charts & stats page comes from table 'chart_data'. There are no obvious error logs for backend and stats and NEXT_PUBLIC_APP_HOST and NEXT_PUBLIC_API_HOST are both set. The links are: https://testnet.xscscan.com/stats

### Type of the installation

Docker-compose

### Type of the JSON RPC archive node

Geth

### Type of the chain

L1

### Link to the page

https://testnet.xscscan.com/stats

### Backend version

v6.9.0-beta-47-g6b5f4e62b7

### Frontend version

v6.9.0-beta-47-g6b5f4e62b7

### Elixir & Erlang/OTP versions

Whatis that

### Operating system

Server: Ubuntu22.04 Client: Chrome Explore

**Comment by GimluCom** [comment]
I am seeing stats and charts in the page you linked. Please close this issue if it has been resolved or provide further details/screenshots of the error.

**Comment by depp927** [comment]
> I am seeing stats and charts in the page you linked. Please close this issue if it has been resolved or provide further details/screenshots of the error.

There are no obvious error logs

**Comment by depp927** [comment]
> I am seeing stats and charts in the page you linked. Please close this issue if it has been resolved or provide further details/screenshots of the error.

![image](https://github.com/user-attachments/assets/a545cc6f-46c3-4165-a8f4-f9d2f499873f)
Look the logs of stats service, It seems normal

**Comment by depp927** [comment]
No solution, no one responded
