### ISSUE TITLE
Transactions blocks shows 4 days old

### ISSUE THREAD

**Issue by bluepeacock-lab** [blockscout/blockscout#11286]
### Description

Team, 
when i see https://testnet.cypherscan.ai/ today at 28_11_24, the last block generated is 4 days ago. Can u pls chk out

### Type of the installation

Docker-compose

### Type of the JSON RPC archive node

NA

### Link to the page

https://testnet.cypherscan.ai/

### Steps to reproduce

Also post connecting wallet to https://cypher.z1labs.ai/testnet/. All the buttons are disabled.
The testnet explorer https://testnet.cypherscan.ai/ blocks are not being generated

### Backend version

NA

### Frontend version

App

### Elixir & Erlang/OTP versions

NA

### Operating system

Windows

### Additional information

**User Agent:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36

**Comment by vbaranov** [comment]
The Blockscout team doesn't manage this instance of the explorer. Please, ask the question to the team, which supports this chain.
