### ISSUE TITLE
Retiro de monedas no exitosa 

### ISSUE THREAD

**Issue by K25697413** [blockscout/blockscout#11284]
### Description

Retire 25 monedas el 21 de noviembre y esta es la fecha y aún no a caído a mi trafiya 
![Screenshot_20241121_193338_com worldcoin](https://github.com/user-attachments/assets/b92bdf22-75e2-40a4-8e40-936c1230a5e5)
![Screenshot_20241121_193349_com worldcoin](https://github.com/user-attachments/assets/9f219408-946b-4e14-a91d-e88db92dc8ee)

### Type of the installation

Manual from the source code

### Type of the JSON RPC archive node

Trasfiya

### Type of the chain

Nivel 1

### Link to the page

https://worldchain-mainnet.explorer.alchemy.com/tx/0xaefb0cd17c9d0493686c17ff26a3cc22b74ffe09579406e6edd032d3be86bc20

### Steps to reproduce

Aún no se me hacen efectivo el retiro de las monedas 
![Screenshot_20241121_191745_com worldcoin](https://github.com/user-attachments/assets/e00635b4-3fdd-4e31-a760-f422d1b681b3)
![Screenshot_20241121_193338_com worldcoin](https://github.com/user-attachments/assets/b0f40b05-d4e0-4af6-9ed8-a6b3d1b9b7c3)
![Screenshot_20241121_193349_com worldcoin](https://github.com/user-attachments/assets/36962536-b81c-4da6-957f-1e8ce6373b9c)

### Backend version

v6.9.1-beta

### Frontend version

v1.36.2+f793609b

### Elixir & Erlang/OTP versions

1.17

### Operating system

Linux

### Additional information

**User Agent:** Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Mobile Safari/537.36

**Comment by K25697413** [comment]
Me yudan

**Comment by vbaranov** [comment]
This chat is for Blockscout-related questions. Your question is out of scope, where the Blockscout team can help.
