### ISSUE TITLE
I never received my qubetics 

### ISSUE THREAD

**Issue by erikhinla** [blockscout/blockscout#11283]
### Description

I swapped dogwithinme for qubetics on 11/11/24 and never received them!

here’s the contract:
0xc0f434ca286de4e912eaddb93f5c707952bcfc28

### Type of the installation

Manual from the source code

### Type of the JSON RPC archive node

I don’t know 

### Type of the chain

Here’s my contract link: 0xc0f434ca286de4e912eaddb93f5c707952bcfc28

### Link to the page

https://base.blockscout.com/tx/0x3014211e09ac0d1107bf59a44622bdc5c277c707a1ea4b7dbb4ed397e99590c0

### Backend version

v6.9.2-beta

### Frontend version

v1.36.3+fb1e3bf9

### Elixir & Erlang/OTP versions

Idk

### Additional information

**User Agent:** Mozilla/5.0 (iPhone; CPU iPhone OS 18_1_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/18.1.1 Mobile/15E148 Safari/604.1

**Comment by vbaranov** [comment]
This chat is for Blockscout-related questions. Your question is out of scope, where the Blockscout team can help.
