### ISSUE TITLE
Did not receive my USD

### ISSUE THREAD

**Issue by JorgeGFI** [blockscout/blockscout#11297]
### Description

16 hours I sent from Worldcoin App to Coinbase some USD, it is something I do regularly every month so I know I used the correct direction, usually it just takes a few minutes to appear in Coinbase, but not this time. This is the hash ID: 0x44c7f8abe09290f1cc4403da0f89f7ad7fe371aec9744ef0a600f05356202580

### Type of the installation

Docker-compose

### Type of the JSON RPC archive node

Erigon 

### Type of the chain

L1

### Link to the page

https://worldchain-mainnet.explorer.alchemy.com/tx/0x44c7f8abe09290f1cc4403da0f89f7ad7fe371aec9744ef0a600f05356202580

### Backend version

v6.9.1-beta

### Frontend version

v1.36.2+f793609b

### Elixir & Erlang/OTP versions

Elixir 

### Operating system

MacOS

### Additional information

**User Agent:** Mozilla/5.0 (iPhone; CPU iPhone OS 18_0_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Mobile/15E148

**Comment by vbaranov** [comment]
This chat is for Blockscout-related questions. Your question is out of scope, where the Blockscout team can help.
