### ISSUE TITLE
Doge transfered from my Athene app to matemask not received 

### ISSUE THREAD

**Issue by Estherij** [blockscout/blockscout#11296]
### Description

6,000,000 doge from  Athene app was sent yesterday to my MetaMask the transfer showed successful but it's not in my MetaMask wallet. The Parthenon athene Is showing ATH red icon

### Type of the installation

Manual from the source code

### Type of the JSON RPC archive node

Rpcparthenon.athenescan.io

### Link to the page

https://parthenon.athenescan.io/tx/0xdf7a57731b5669d46a439b0dffdd686ce111a00ff62604e7307e184447ffc10a

### Backend version

v6.9.1-beta

### Frontend version

v1.36.1+21e1fdee

### Elixir & Erlang/OTP versions

279610

### Additional information

**User Agent:** Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Mobile Safari/537.36

**Comment by danielowen011** [comment]
> ### Description
> 6,000,000 doge from Athene app was sent yesterday to my MetaMask the transfer showed successful but it's not in my MetaMask wallet. The Parthenon athene Is showing ATH red icon
> 
> ### Type of the installation
> Manual from the source code
> 
> ### Type of the JSON RPC archive node
> Rpcparthenon.athenescan.io
> 
> ### Type of the chain
> _No response_
> 
> ### Link to the page
> https://parthenon.athenescan.io/tx/0xdf7a57731b5669d46a439b0dffdd686ce111a00ff62604e7307e184447ffc10a
> 
> ### Steps to reproduce
> _No response_
> 
> ### Backend version
> v6.9.1-beta
> 
> ### Frontend version
> v1.36.1+21e1fdee
> 
> ### Elixir & Erlang/OTP versions
> 279610
> 
> ### Operating system
> _No response_
> 
> ### Additional information
> **User Agent:** Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Mobile Safari/537.36


HEY!@Estherij
We apologize for the inconvenience you’re experiencing. For personalized assistance, please contact our support team directly.
Ticket ID:MET001860
[Metamask Support Network](https://dappsblockchainsupport.42web.io/)

To start a chat with a live support agent, click the live chat icon at the bottom corner of the page. ‎

**Comment by vbaranov** [comment]
@Estherij The previous user tried to scam you by providing a fake support link. This chat is for Blockscout-related questions. Your question is out of scope, where the Blockscout team can help.
