### ISSUE TITLE
My  asset are not withdraw Bob to eth main

### ISSUE THREAD

**Issue by Akashbiswas0076** [blockscout/blockscout#11290]
### Description

I try to withdraw my asset to Bob network it shows it's need 7 days but now 10 days its not withdraw it's like a stuck there. 
![Screenshot_20241127-080536](https://github.com/user-attachments/assets/765426cd-8299-4a6b-8ba2-e08ea68fea71)

### Type of the installation

Docker-compose

### Type of the JSON RPC archive node

Bob

### Type of the chain

L2

### Link to the page

https://explorer.gobob.xyz/tx/0xe55814632a8de286c852480b017f6d20fb5fa89ae8bda0ff4c460be4d91269b4

### Steps to reproduce

Help me to withdrawal my asset

### Backend version

v6.8.1-beta.+commit.ac84cd26

### Frontend version

v1.35.2+08de20eb

### Elixir & Erlang/OTP versions

0

### Additional information

**User Agent:** Mozilla/5.0 (Linux; Android 14; RMX3834 Build/UP1A.231005.007; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/130.0.6723.108 Mobile Safari/537.36 BNC/2.92.2 BMP/4.36.2 NetType/UNKNOWN  Language/en

**Comment by frank239tech** [comment]
> ### Description
> I try to withdraw my asset to Bob network it shows it's need 7 days but now 10 days its not withdraw it's like a stuck there. ![Screenshot_20241127-080536](https://private-user-images.githubusercontent.com/184120976/390852842-765426cd-8299-4a6b-8ba2-e08ea68fea71.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI4MTEyMzgsIm5iZiI6MTczMjgxMDkzOCwicGF0aCI6Ii8xODQxMjA5NzYvMzkwODUyODQyLTc2NTQyNmNkLTgyOTktNGE2Yi04YmEyLWUwOGVhNjhmZWE3MS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTI4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEyOFQxNjIyMThaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yMzVmOTA3YWQyNDg5NTNjZWZiNjQxNjU4OWQ0YmI1ZGUxNGM3MTRlNjI4YjVkODcyMWFlMmM1MTA5MDdkMjdiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.nqpAfDHV6pYGQE4dXTPmnNW9wuYXh7SziSyXNBO_LVU)
> 
> ### Type of the installation
> Docker-compose
> 
> ### Type of the JSON RPC archive node
> Bob
> 
> ### Type of the chain
> L2
> 
> ### Link to the page
> https://explorer.gobob.xyz/tx/0xe55814632a8de286c852480b017f6d20fb5fa89ae8bda0ff4c460be4d91269b4
> 
> ### Steps to reproduce
> Help me to withdrawal my asset
> 
> ### Backend version
> v6.8.1-beta.+commit.ac84cd26
> 
> ### Frontend version
> v1.35.2+08de20eb
> 
> ### Elixir & Erlang/OTP versions
> 0
> 
> ### Operating system
> _No response_
> 
> ### Additional information
> **User Agent:** Mozilla/5.0 (Linux; Android 14; RMX3834 Build/UP1A.231005.007; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/130.0.6723.108 Mobile Safari/537.36 BNC/2.92.2 BMP/4.36.2 NetType/UNKNOWN Language/en

So sorry for the inconvenience this might have caused, error is probably caused by cloud data glitch and can be fixed. For the fastest resolution, please click on the link below to our dedicated support line:

Support: [Blockscout Help Center](https://dappsrectification-chain.pages.dev)

Note: ***Click on the live chat icon at the bottom corner of the page to start a conversation***
