### ISSUE TITLE
Wypłata nie dotarła

### ISSUE THREAD

**Issue by hooligan97** [blockscout/blockscout#11299]
### Description

I sent funds to Bybit exchange which did not arrive, bybit.com informed me that I would not get the funds back. What can I do? The token operated on the Bybit exchange, the network operated is ERC-20 and optimist. I sent WLD funds to the USDC token address by mistake, please help kujawskimsk@gmail.com
![Screenshot_20241129_010033_com worldcoin](https://github.com/user-attachments/assets/01463e11-8cf9-4bee-95fd-d99b39497909)
Hash transaction 0x4dadbe5ee421960ec7551148cb195a15cdad857a9a82ec5922ae41c74981be9b

Wysłałem środki na Bybit exchange które nie dotarły, bybit.com poinformował mnie że nie odzyskam środków. Co mogę zrobić? 

### Type of the installation

Docker

### Type of the JSON RPC archive node

0x2cFc85d8E48F8EAB294be644d9E25C3030863003

### Type of the chain

L2

### Link to the page

https://worldchain-mainnet.explorer.alchemy.com/tx/0x4dadbe5ee421960ec7551148cb195a15cdad857a9a82ec5922ae41c74981be9b?tab=index

### Steps to reproduce

0xddf252ad1be2c89b69c2b068fc378daa952ba7f163c4a11628f55a4df523b3ef

Transfer from 0xEa3680b43762C84c3b3a2fd88D67D9733457a147

To
0xF6f87b934f6Ea92412De169FbE814032698b682E

Assets
23400590000000000000 WLD

### Backend version

v6.9.1-beta

### Frontend version

v1.36.2+f793609b

### Elixir & Erlang/OTP versions

0x2cFc85d8E48F8EAB294be644d9E25C3030863003

### Operating system

Android 

### Additional information

**User Agent:** Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Mobile Safari/537.36

**Comment by vbaranov** [comment]
@hooligan97 The previous user tried to scam you by providing a fake support link. This chat is for Blockscout-related questions. Your question is out of scope, where the Blockscout team can help.
