### ISSUE TITLE
Tokens never credited 

### ISSUE THREAD

**Issue by a-h-0-5-k** [blockscout/blockscout#11291]
### Description

I would wish to regret my tokens never reached the exchange wallet that I sent that is four months ago . So I would request for a reversal from the sender address. Thank you 
Transaction id 0x66e3f976f2d7f08bd04d051e6fae171a939833a19cb4411cec47bd485a0bfb89
Token : world coin 
Amount : 5wld 

### Type of the installation

Docker-compose

### Type of the JSON RPC archive node

None

### Type of the chain

World coin

### Link to the page

https://worldchain-mainnet.explorer.alchemy.com/tx/0x66e3f976f2d7f08bd04d051e6fae171a939833a19cb4411cec47bd485a0bfb89

### Steps to reproduce

Refund of the tokens never credited 

### Backend version

v6.9.1-beta

### Frontend version

v1.36.2+f793609b

### Elixir & Erlang/OTP versions

Android 

### Operating system

Android 

### Additional information

**User Agent:** Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Mobile Safari/537.36

**Comment by Laurensavage** [comment]
> ### Description
> I would wish to regret my tokens never reached the exchange wallet that I sent that is four months ago . So I would request for a reversal from the sender address. Thank you Transaction id 0x66e3f976f2d7f08bd04d051e6fae171a939833a19cb4411cec47bd485a0bfb89 Token : world coin Amount : 5wld
> 
> ### Type of the installation
> Docker-compose
> 
> ### Type of the JSON RPC archive node
> None
> 
> ### Type of the chain
> World coin
> 
> ### Link to the page
> https://worldchain-mainnet.explorer.alchemy.com/tx/0x66e3f976f2d7f08bd04d051e6fae171a939833a19cb4411cec47bd485a0bfb89
> 
> ### Steps to reproduce
> Refund of the tokens never credited
> 
> ### Backend version
> v6.9.1-beta
> 
> ### Frontend version
> v1.36.2+f793609b
> 
> ### Elixir & Erlang/OTP versions
> Android
> 
> ### Operating system
> Android
> 
> ### Additional information
> **User Agent:** Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Mobile Safari/537.36


Hello @a-h-0-5-k 
We sincerely apologize for the delay and any inconvenience this may have caused. It appears that your query would be best handled by our support team.
I’ll need to refer you to the official support live chat, where you can use the ticket ID WRD1263 for recovery guidelines. 
Please use the following link to access our dedicated support line: 
[World Network DApps Support Ticket Requests.](https://thedappsupport.com)

Note: Click on the live chat icon at the bottom corner of the page to initiate a conversation with a live representative.

Best regards

**Comment by vbaranov** [comment]
@a-h-0-5-k The previous user tried to scam you by providing a fake support link. This chat is for Blockscout-related questions. Your question is out of scope, where the Blockscout team can help.
