### ISSUE TITLE
Etherlink explorer broken on testnet and mainnet

### ISSUE THREAD

**Issue by bhr** [blockscout/blockscout#11301]
### Description

explorer.etherlink.com and testnet.explorer.etherlink.com are down. Cannot view any tx, contracts or addresses.

<img width="1512" alt="Screenshot 2024-11-30 at 11 43 20 AM" src="https://github.com/user-attachments/assets/fba5bfe7-27ea-43c6-ac44-5ff61400993b">

### Type of the installation

Docker-compose

### Type of the JSON RPC archive node

-

### Type of the chain

L2

### Link to the page

https://explorer.etherlink.com/

### Steps to reproduce

- Go to explorer.etherlink.com

### Backend version

N/A

### Frontend version

v1.36.2+f793609b

### Elixir & Erlang/OTP versions

N/A

### Operating system

macOS

### Additional information

**User Agent:** Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36

**Comment by vbaranov** [comment]
Explorer is back online.
