### ISSUE TITLE
MEU SAQUE NÃO  CAIU!!!

### ISSUE THREAD

**Issue by Alann63** [blockscout/blockscout#11304]
### Description

Realizei o resgate das minhas moedas na data do dia 29 de novembro as 18:45, porém até agora meu saque não caiu , e minhas moedas não voltaram para conta da wordcoin , quer saber oque aconteceu? Heeeeelp
![Screenshot_20241201-082128_World App](https://github.com/user-attachments/assets/c76bd720-496e-4447-8173-343c2f11be4f)

### Type of the installation

Docker-compose

### Type of the JSON RPC archive node

Alfred

### Type of the chain

E1

### Link to the page

https://worldchain-mainnet.explorer.alchemy.com/tx/0x55681e298cd036a58f47b1fcd2cbdc3cd3416db95ba8315f59516338b8d701b7

### Steps to reproduce

.

### Backend version

v6.9.1-beta

### Frontend version

v1.36.2+f793609b

### Elixir & Erlang/OTP versions

1

### Operating system

Android 

### Additional information

**User Agent:** Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Mobile Safari/537.36

**Comment by vbaranov** [comment]
This chat is for Blockscout-related questions. Your question is out of scope, where the Blockscout team can help.
