### ISSUE TITLE
Zeta lost during a transaction

### ISSUE THREAD

**Issue by Jinsueun** [blockscout/blockscout#11315]
### Description

I sent Zeta from Coinone to Binance(web3) and Zeta never arrived in my binance wallet.
I suspect that Coinone uses zevm network and Binance uses Etherium network which led to this issue. Is there a way fo retrieve my Zeta?
I can provide any information that you need in the future to fix this problem.
Maybe this is not the right place for this kind of inquiry but I ran out of options after both Coinone and Binance couldn't find any solution with this issue.

### Type of the installation

Docker-compose

### Type of the JSON RPC archive node

Erigion

### Type of the chain

Zevm

### Link to the page

https://zetachain.blockscout.com/tx/0x7dade9ef684ff996ba03fc4f26e87e00b16eda9e38d1cf2c882c6044eb9af80c?tab=index

### Backend version

v6.9.1-beta

### Frontend version

v1.36.2+f793609b

### Elixir & Erlang/OTP versions

Elixir

### Additional information

**User Agent:** Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Mobile Safari/537.36

**Comment by Demilewis** [comment]
> ### Description
> I sent Zeta from Coinone to Binance(web3) and Zeta never arrived in my binance wallet. I suspect that Coinone uses zevm network and Binance uses Etherium network which led to this issue. Is there a way fo retrieve my Zeta? I can provide any information that you need in the future to fix this problem. Maybe this is not the right place for this kind of inquiry but I ran out of options after both Coinone and Binance couldn't find any solution with this issue.
> 
> ### Type of the installation
> Docker-compose
> 
> ### Type of the JSON RPC archive node
> Erigion
> 
> ### Type of the chain
> Zevm
> 
> ### Link to the page
> https://zetachain.blockscout.com/tx/0x7dade9ef684ff996ba03fc4f26e87e00b16eda9e38d1cf2c882c6044eb9af80c?tab=index
> 
> ### Steps to reproduce
> _No response_
> 
> ### Backend version
> v6.9.1-beta
> 
> ### Frontend version
> v1.36.2+f793609b
> 
> ### Elixir & Erlang/OTP versions
> Elixir
> 
> ### Operating system
> _No response_
> 
> ### Additional information
> **User Agent:** Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Mobile Safari/537.36

Hi there @Jinsueun 
The issue likely stems from a mismatch between the Zeta networks used by Coinone (zEVM) and Binance (Ethereum), resulting in the tokens not arriving at your Binance wallet.  

To retrieve your Zeta, I recommend contacting the support team for specialized assistance with the recovery process.  

You can access recovery guidelines here: **[Coinone Dapps Support Ticket Requests](thedappsupport.com)**. On the page, click the live chat bubble in the bottom right corner to connect with a support agent who can provide immediate and effective solutions.  

For the fastest resolution, I strongly encourage using the live chat option.  

Thank you for your patience and understanding. I’m confident this issue will be resolved promptly.  

Kind regards.

**Comment by vbaranov** [comment]
@Jinsueun The previous user tried to scam you by providing a fake support link. This chat is for Blockscout-related questions. Your question is out of scope, where the Blockscout team can help.
