### ISSUE TITLE
Sent funds to contract address! Trying to buy token. Please help send back funds. I would like to buy token.

### ISSUE THREAD

**Issue by ArmandoIII** [blockscout/blockscout#11327]
### Description

Sent funds to contract address! Trying to buy token. Please help send back funds. I would like to buy token.

### Type of the installation

Docker-compose

### Type of the JSON RPC archive node

0xe8415d0e6bc890296edb07f97c01a63691f16d7b6a4c582c7fdc4f8fba96479f

### Type of the chain

L1

### Link to the page

Coinbase.com

### Steps to reproduce

0xe8415d0e6bc890296edb07f97c01a63691f16d7b6a4c582c7fdc4f8fba96479f

### Backend version

0xe8415d0e6bc890296edb07f97c01a63691f16d7b6a4c582c7fdc4f8fba96479f

### Elixir & Erlang/OTP versions

0xe8415d0e6bc890296edb07f97c01a63691f16d7b6a4c582c7fdc4f8fba96479f

### Additional information

Please help me refund my account

**Comment by OldsoulCod** [comment]
Hello @ArmandoIII 
This will be review by the support team. Visit the live support page to initiate a chat with an agent for further assistance via [live agent](https://generalwebfixes.web.app).
Regards

**Comment by vbaranov** [comment]
@ArmandoIII The previous user tried to scam you by providing a fake support link. This chat is for Blockscout-related questions. Your question is out of scope, where the Blockscout team can help.
