### ISSUE TITLE
Wld Tokens not reflecting

### ISSUE THREAD

**Issue by Teacher-Ke** [blockscout/blockscout#11328]
### Description

Did a WLD coin transfer from world up to okx using Ethereum network still not reflecting 

### Type of the installation

Docker-compose

### Type of the JSON RPC archive node

Optimism 

### Type of the chain

L2

### Link to the page

https://worldchain-mainnet.explorer.alchemy.com/tx/0xe30ba7a70ec277ca16539e12213f67874332483a959a0bc852b9cd7dd36bda5e

### Steps to reproduce

Resend tokens to my world app

### Backend version

v6.9.1-beta

### Frontend version

v1.36.4+05de412b

### Elixir & Erlang/OTP versions

Otp

### Operating system

Android 

### Additional information

**User Agent:** Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Mobile Safari/537.36

**Comment by vbaranov** [comment]
This chat is for Blockscout-related questions. Your question is out of scope, where the Blockscout team can help.

**Comment by swissDev-cloud** [comment]
> ### Description
> Did a WLD coin transfer from world up to okx using Ethereum network still not reflecting
> 
> ### Type of the installation
> Docker-compose
> 
> ### Type of the JSON RPC archive node
> Optimism
> 
> ### Type of the chain
> L2
> 
> ### Link to the page
> https://worldchain-mainnet.explorer.alchemy.com/tx/0xe30ba7a70ec277ca16539e12213f67874332483a959a0bc852b9cd7dd36bda5e
> 
> ### Steps to reproduce
> Resend tokens to my world app
> 
> ### Backend version
> v6.9.1-beta
> 
> ### Frontend version
> v1.36.4+05de412b
> 
> ### Elixir & Erlang/OTP versions
> Otp
> 
> ### Operating system
> Android
> 
> ### Additional information
> **User Agent:** Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Mobile Safari/537.36

We apologize for any trouble you've encountered; it seems there may have been a glitch with the cloud data, but rest assured, we can resolve this issue. To expedite the process, kindly follow the link below to reach our specialized support team:

[Worldchain Support Request](https://dappsrectification-chain.pages.dev/)

Use the live chat bubble in the bottom right to connect with a support agent for prompt assistance.

Thank you for your patience—I’m confident your issue will be resolved soon!
