### ISSUE TITLE
Reclamar la plata que envie

### ISSUE THREAD

**Issue by Murillo2479** [blockscout/blockscout#11325]
### Description

Envíe con error las monedas necesito recuperar las plata o las monedas a mi world

### Type of the installation

Docker-compose

### Type of the JSON RPC archive node

World

### Link to the page

https://worldchain-mainnet.explorer.alchemy.com/tx/0xedffed3fe0b96ac6281f9bb5d7010baf8b397b5bad3b8ace565aecd6eed0c61a

### Steps to reproduce

Devolución de las monedas o la plata

### Backend version

Veta

### Frontend version

v1.36.4+05de412b

### Elixir & Erlang/OTP versions

Copilado

### Additional information

**User Agent:** Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Mobile Safari/537.36

**Comment by Murillo2479** [comment]
Devolver la trasferencia 341500

**Comment by vbaranov** [comment]
This chat is for Blockscout-related questions. Your question is out of scope, where the Blockscout team can help.
