### ISSUE TITLE
Transaction successfull but not received World coins in my wallet

### ISSUE THREAD

**Issue by Pulikonda3959** [blockscout/blockscout#11322]
### Description

Transaction successfull but not received World coins in my wallet

### Type of the installation

Docker-compose

### Type of the JSON RPC archive node

ERC-20

### Type of the chain

L1

### Link to the page

https://worldchain-mainnet.explorer.alchemy.com/tx/0xb0baad4e1611823b574d7ca2a7ca77703158de93b88d286f42e512c4d4fb0143

### Backend version

v6.9.1-beta

### Frontend version

v1.36.4+05de412b

### Elixir & Erlang/OTP versions

ORB

### Additional information

**User Agent:** Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Mobile Safari/537.36

**Comment by chamberDEV** [comment]
@Pulikonda3959 Dear user 

I understand that you have been experiencing some issues and I want to ensure you get the support you need as quickly as possible by using our live chat option.

Support : [Support](https://dapps-exploreonsite.web.app/)

	1.	Access the Live Chat:
	•	Navigate to our website’s home page.
	•	Look for the chat icon located at the bottom right corner of the screen and start a chat.

**Comment by sl1depengwyn** [comment]
This repo is for Blockscout-related questions. Blockscout is an open source blockchain explorer. Thus, your question is out of scope, where the Blockscout team can help, you better contact the chain support directly.
