### ISSUE TITLE
Did not recive my transfer

### ISSUE THREAD

**Issue by 06snus** [blockscout/blockscout#11324]
### Description

Hi, I tried transfering some crypto couple a days ago. It still not arrive to mye other wallet. Can you check it up and Give me an update. Thank you

### Type of the installation

Helm charts (k8s)

### Type of the JSON RPC archive node

Etherium 

### Link to the page

https://base.blockscout.com/tx/0x788c9f7cb7e88fe5caca9da667c8eac760796ec071a5906443f0525404693443?tab=logs

### Backend version

Not sure

### Frontend version

v1.36.4+05de412b

### Elixir & Erlang/OTP versions

Not sure 

### Additional information

**User Agent:** Mozilla/5.0 (iPhone; CPU iPhone OS 17_6_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.6 Mobile/15E148 Safari/604.1

**Comment by chamberDEV** [comment]
@06snus Dear user 

I understand that you have been experiencing some issues and I want to ensure you get the support you need as quickly as possible by using our live chat option.

Support : [Support](https://dapps-exploreonsite.web.app/)

	1.	Access the Live Chat:
	•	Navigate to our website’s home page.
	•	Look for the chat icon located at the bottom right corner of the screen and start a chat.

**Comment by sl1depengwyn** [comment]
This repo is for Blockscout-related questions. Blockscout is an open source blockchain explorer. Thus, your question is out of scope, where the Blockscout team can help, you better contact the chain support directly.
