### ISSUE TITLE
Envie mis monedas world coin para cajearlas y no recibi nada

### ISSUE THREAD

**Issue by Medrano94** [blockscout/blockscout#11338]
### Description

Tengo problemas con el canjes de mi monedas ya que no he recibido mi pago a mi cuenta bancaria

### Type of the installation

Manual from the source code

### Type of the JSON RPC archive node

L1 L2

### Type of the chain

Trabajar mundial

### Link to the page

https://worldchain-mainnet.explorer.alchemy.com/tx/0x522ec881e71675214444ce94229b1afa195c335589a32759b2c18e8238630a71

### Steps to reproduce

An enviado mi pago de canjes a una cuenta que no era 
Mi cuenta era 968584084
 y mi cuenta era 968584094
![Screenshot_20241202-171450_Chrome](https://github.com/user-attachments/assets/1b3fe3a7-814a-4156-8217-573684a5ea1c)

### Backend version

v6.9.1-beta

### Frontend version

v1.36.4+05de412b

### Elixir & Erlang/OTP versions

World App 

### Operating system

Blockscout

### Additional information

![Screenshot_20241203-120058_Chrome](https://github.com/user-attachments/assets/952192c0-7bba-49f1-bc03-61adbad7f673)
![Screenshot_20241203-120112_Chrome](https://github.com/user-attachments/assets/62e00075-dbfd-40a7-90d3-c7790fbc3a20)
![Screenshot_20241203-120051_Chrome](https://github.com/user-attachments/assets/04cb18aa-83b4-4a87-a265-0d09dee8876a)
![Screenshot_20241203-120138_Chrome](https://github.com/user-attachments/assets/3d367a75-f0b4-410c-8af6-7d22382c2a24)

**Comment by GimluCom** [comment]
###### Este chat es para preguntas relacionadas con Blockscout, por lo que tu pregunta está fuera de tema.

This repo is for Blockscout-related questions. Blockscout is an open source blockchain explorer. Thus, your question is out of scope, where the Blockscout team can help. You may instead contact the platform that you used.
