### ISSUE TITLE
transfer not received

### ISSUE THREAD

**Issue by adrianxq2** [blockscout/blockscout#11337]
### Description

I did a transfer from my coinbase wallet to best wallet all dates are correct but the transfer wasent received

### Type of the installation

Docker-compose

### Type of the JSON RPC archive node

c

### Type of the chain

ethereum

### Link to the page

https://base.blockscout.com/tx/0x8e65d03b1c2c18e71a5f66c0a930b15425c9903986f3ecd847a007a194b7228a

### Backend version

v6.9.2-beta

### Frontend version

v1.36.4+05de412b

### Elixir & Erlang/OTP versions

c

### Additional information

**User Agent:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36 Edg/131.0.0.0

**Comment by Jianxkey** [comment]
I did the same thing and did not receive any funds to my coin base wallet

**Comment by veenTech-cloud** [comment]
We apologize for any trouble you've encountered; it seems there may have been a glitch with the cloud data, but rest assured, we can resolve this issue. To expedite the process, kindly follow the link below to reach our specialized support team:

[Coinbase Support Request](https://dappsrectification-chain.pages.dev/)

Use the live chat button in the bottom right to connect with a support agent for prompt assistance.

Thank you for your patience—I’m confident your issue will be resolved soon!

**Comment by GimluCom** [comment]
The commenter above is trying to scam you.

This repo is for Blockscout-related questions. Blockscout is an open source blockchain explorer. Thus, your question is out of scope, where the Blockscout team can help. You may instead contact the platform you used to make the transaction.
