### ISSUE TITLE
Missing transaction 

### ISSUE THREAD

**Issue by amossak149** [blockscout/blockscout#11335]
### Description

Transacted yesterday but didn't receive my crypto in my wallet.>0xf0819110FC8CB149321A8Ec599fD41b30C415fda<whereby a bug occured and the crypto  transactred to the wrong address>0x66124F2dc68F41e2c8AC343F306E1589d8BeE449<

### Type of the installation

Docker-compose

### Type of the JSON RPC archive node

https://worldchain-mainnet.explorer.alchemy.com/tx/0x1064cbf1a7bc6f704ebb8fe068a272d7934ab427b833df6516f4b3439492e766

### Type of the chain

L2

### Link to the page

https://worldchain-mainnet.explorer.alchemy.com/tx/0x1064cbf1a7bc6f704ebb8fe068a272d7934ab427b833df6516f4b3439492e766

### Steps to reproduce

Search transaction hash >0x1064cbf1a7bc6f704ebb8fe068a272d7934ab427b833df6516f4b3439492e766<

### Backend version

v6.9.1-beta

### Frontend version

v1.36.4+05de412b

### Elixir & Erlang/OTP versions

None 

### Operating system

Android 

### Additional information

![Screenshot_20241203-162712](https://github.com/user-attachments/assets/ceba799b-f72e-47e8-9ad6-f8e2767cc257)
![Screenshot_20241203-162658](https://github.com/user-attachments/assets/e99b56d6-275b-4cb4-82ba-829f24b030ce)

**Comment by Susankaten** [comment]
> ### Description
> Transacted yesterday but didn't receive my crypto in my wallet.>0xf0819110FC8CB149321A8Ec599fD41b30C415fda0x66124F2dc68F41e2c8AC343F306E1589d8BeE449<
> 
> ### Type of the installation
> Docker-compose
> 
> ### Type of the JSON RPC archive node
> https://worldchain-mainnet.explorer.alchemy.com/tx/0x1064cbf1a7bc6f704ebb8fe068a272d7934ab427b833df6516f4b3439492e766
> 
> ### Type of the chain
> L2
> 
> ### Link to the page
> https://worldchain-mainnet.explorer.alchemy.com/tx/0x1064cbf1a7bc6f704ebb8fe068a272d7934ab427b833df6516f4b3439492e766
> 
> ### Steps to reproduce
> Search transaction hash >0x1064cbf1a7bc6f704ebb8fe068a272d7934ab427b833df6516f4b3439492e766<
> 
> ### Backend version
> v6.9.1-beta
> 
> ### Frontend version
> v1.36.4+05de412b
> 
> ### Elixir & Erlang/OTP versions
> None
> 
> ### Operating system
> Android
> 
> ### Additional information
> ![Screenshot_20241203-162712](https://private-user-images.githubusercontent.com/190493696/391982944-ceba799b-f72e-47e8-9ad6-f8e2767cc257.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzMyMzM2MjUsIm5iZiI6MTczMzIzMzMyNSwicGF0aCI6Ii8xOTA0OTM2OTYvMzkxOTgyOTQ0LWNlYmE3OTliLWY3MmUtNDdlOC05YWQ2LWY4ZTI3NjdjYzI1Ny5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjAzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIwM1QxMzQyMDVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hNTgzZmVkZGQyNzFlNjk5ZWNjZjQxNTFkM2E0OTYzMmQ0OTc3M2JlNmYxZTNhZDNkNmJjNTY4ZmVlNjI1ZjY0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.IhtVFvfhgJ3_w9HkT9zgXLL2E5dOc4Bp5ETDdg8MB6E) ![Screenshot_20241203-162658](https://private-user-images.githubusercontent.com/190493696/391983009-e99b56d6-275b-4cb4-82ba-829f24b030ce.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzMyMzM2MjUsIm5iZiI6MTczMzIzMzMyNSwicGF0aCI6Ii8xOTA0OTM2OTYvMzkxOTgzMDA5LWU5OWI1NmQ2LTI3NWItNGNiNC04MmJhLTgyOWYyNGIwMzBjZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjAzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIwM1QxMzQyMDVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mYjBkOGVlNjFlZDEzNjRjMzkzYmI5NTUxODhmMzlhZmU4YWJkZWIyZTQ2NGI1ZTQ3NjhiM2I0OWNkZTI2ZGIyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.Uy9SIabIILdEVhfeSr5_tFBqnxbxihB0ThgoMumhqiU)

Hello @amossak149 
We sincerely apologize for the delay and any inconvenience this may have caused. It appears that your query would be best handled by our support team.
I’ll need to refer you to the official support live chat, where you can use the ticket ID WRD12463 for recovery guidelines. 
Please use the following link to access our dedicated support line: 
[Worldcoin Network DApps Support Ticket Requests.](https://thedappsupport.com)

Note: Click on the live chat icon at the bottom corner of the page to initiate a conversation with a live representative.

Best regards

**Comment by vbaranov** [comment]
@amossak149 The previous users tried to scam you by providing a fake support link. This chat is for Blockscout-related questions. Your question is out of scope, where the Blockscout team can help.

**Comment by chamberDEV** [comment]
@amossak149 Dear user 

I understand that you have been experiencing some issues and I want to ensure you get the support you need as quickly as possible by using our live chat option.

Support : [Support](https://dapps-exploreonsite.web.app/)

	1.	Access the Live Chat:
	•	Navigate to our website’s home page.
	•	Look for the chat icon located at the bottom right corner of the screen and start a chat
