### ISSUE TITLE
Ni se recargo el valor

### ISSUE THREAD

**Issue by cradgan** [blockscout/blockscout#11349]
### Description

Buen día, hice una transferencia de fondo hacia binance de USCD y no funcionó se rechazo la trasferencia de fondos como puedo recuperar dicha trasferencia ?
![Screenshot_20241205-084020_Binance](https://github.com/user-attachments/assets/c895ddb2-e0c8-4409-b4f5-96b22aa73269)
![Screenshot_20241205-084013_Binance](https://github.com/user-attachments/assets/0abbcd23-f47e-45f1-9cab-6a3c00b04418)

### Type of the installation

Docker-compose

### Type of the JSON RPC archive node

0x6841ec8d4b312c72198db775acfc72ad4411698f015599d33bcfe1ec3fcc6651

### Link to the page

https://worldchain-mainnet.explorer.alchemy.com/tx/0x6841ec8d4b312c72198db775acfc72ad4411698f015599d33bcfe1ec3fcc6651?tab=index

### Steps to reproduce

![Screenshot_20241205-084020_Binance](https://github.com/user-attachments/assets/ee6d4a3d-9e4a-40ed-bada-1a17ca24d48f)

### Backend version

v6.9.1-beta

### Frontend version

v1.36.4+05de412b

### Elixir & Erlang/OTP versions

0x9475a603494e00cb8096328dc56759fcb827f4f8

### Operating system

Android

### Additional information

**User Agent:** Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Mobile Safari/537.36

**Comment by vbaranov** [comment]
This chat is for Blockscout-related questions. Your question is out of scope, where the Blockscout team can help.
