### ISSUE TITLE
Dinheiro nao recebido do world

### ISSUE THREAD

**Issue by Klatlyn** [blockscout/blockscout#11342]
### Description

Eu fiz aquele processo sacar coloquei meu pix porém nao caiu o dinheiro mas lá no aplicativo está falando que caiu o que faço.

### Type of the installation

Docker-compose

### Type of the JSON RPC archive node

Não sei 

### Type of the chain

E1

### Link to the page

https://worldchain-mainnet.explorer.alchemy.com/tx/0x9a46e70fda1c00f13983cba99598469a1480c5543be104a66fd944af091ce7d9

### Steps to reproduce

Eu queria saber pra onde foi o dinheiro 
![Screenshot_20241204_081222_World App](https://github.com/user-attachments/assets/e968bb2e-25e9-4e57-84a8-bfac1b1d59ae)

### Backend version

v6.9.1-beta

### Frontend version

v1.36.4+05de412b

### Elixir & Erlang/OTP versions

Elixir 

### Operating system

Windows 

### Additional information

**User Agent:** Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Mobile Safari/537.36

**Comment by vbaranov** [comment]
This chat is for Blockscout-related questions. Your question is out of scope, where the Blockscout team can help.
