### ISSUE TITLE
Necesito mis monedas porque se las quedaron 

### ISSUE THREAD

**Issue by Luna645** [blockscout/blockscout#11354]
### Description

Necesito mis monedas ya por favor 

### Type of the installation

Docker-compose

### Type of the JSON RPC archive node

Mi cuenta

### Type of the chain

Nivel 1

### Link to the page

https://worldchain-mainnet.explorer.alchemy.com/tx/0x4f36aff0ca8596c0a1aae112a9e87e3f41149e31f7d4576bf37f5f9da6093ceb?tab=index

### Steps to reproduce

Mis monedas que las hicieron 

### Backend version

v6.9.1-beta

### Frontend version

v1.36.4+05de412b

### Elixir & Erlang/OTP versions

Me robaron mis monedas

### Operating system

Me robaron mis monedas 

### Additional information

**User Agent:** Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Mobile Safari/537.36

**Comment by vbaranov** [comment]
This chat is for Blockscout-related questions. Your question is out of scope, where the Blockscout team can help.
