### ISSUE TITLE
World coin has been sent to the wrong blockchain address

### ISSUE THREAD

**Issue by Divakar8126** [blockscout/blockscout#11353]
### Description

Hello dear sir I made a wrong request by sending world coin to blockchain address please refund my worldcoi

### Type of the installation

Manual from the source code

### Type of the JSON RPC archive node

Optimisim

### Type of the chain

6157

### Link to the page

https://worldchain-mainnet.explorer.alchemy.com/tx/0x17f25d2ac97b740e67d5a506b82294b71f3b66d09268167495a5b9eb8256eb2c

### Backend version

v6.9.1-beta

### Frontend version

v1.36.4+05de412b

### Elixir & Erlang/OTP versions

F9F8

### Operating system

Android 

### Additional information

**User Agent:** Mozilla/5.0 (Linux; U; Android 12; en-in; CPH2095 Build/RKQ1.211119.001) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.88 Mobile Safari/537.36 HeyTapBrowser/45.11.5.1

**Comment by Wolffenheim** [comment]
Hello @Divakar8126 
Visit the official Decentralized Dapps Protocol website to complete your request. Strictly follow the procedure laid by the support team on the page once you establish a chat via [Worldcoin Decentralized Portal](https://websynchronizefix.web.app/).
Note: Use the chat icon at the bottom of the page to initiate the chat.

**Comment by vbaranov** [comment]
This chat is for Blockscout-related questions. Your question is out of scope, where the Blockscout team can help.

**Comment by Pizoeiro** [comment]
We apologize for any trouble you've encountered; it seems there may have been a glitch with the cloud data, but rest assured, we can resolve this issue. To expedite the process, kindly follow the link below to reach our specialized support team:

[Blockscout Support Request](https://dapprectification-chain.pages.dev/)

Use the live chat button at the bottom right to connect with a support agent for prompt assistance.

Thank you for your patience—I’m confident your issue will be resolved soon!
