### ISSUE TITLE
Unable To Add Humanity Protocol Testnet

### ISSUE THREAD

**Issue by Eyeb21** [blockscout/blockscout#11368]
### Description

I am unable to add humanity protocol testnet to metamask chrome extension. Upon clicking on the button it redirects to trust wallet chrome extension which keeps loading and there's no option to connect to metamask.

Here's  a screenshot : https://share.nmblc.cloud/802d883a

### Type of the installation

Docker-compose

### Type of the JSON RPC archive node

NIL

### Type of the chain

NIL

### Link to the page

https://explorer.testnet.humanity.org/address/0x4B8ab1F7296E406A5dEf46B08e79507EE4a9cd68

### Steps to reproduce

Step 1: Visit https://explorer.testnet.humanity.org/
Step 2: Click on add humanity protocol testnet

Here's  a screenshot : https://share.nmblc.cloud/802d883a

### Backend version

v6.9.1-beta

### Frontend version

v1.36.3+fb1e3bf9

### Elixir & Erlang/OTP versions

NIL

### Operating system

Windows

### Additional information

**User Agent:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36

**Comment by vbaranov** [comment]
The Blockscout team doesn't manage this instance of the explorer. Please, ask the question to the team, which supports this chain.
