### ISSUE TITLE
Jutu is taking too much ip faucet 

### ISSUE THREAD

**Issue by mirbilal** [blockscout/blockscout#11364]
### Description

Why jatsu is taking too much ip to confirm transaction.if this is running on same story protocol then why is the transaction fee in ip so high .it is asking for more than 20 ip to claim jatsu faucet 

### Type of the installation

Docker-compose

### Type of the JSON RPC archive node

Dhudhduu.bxdj/

### Type of the chain

L2

### Steps to reproduce

Go to jutsu and tryto claim faucet 

### Backend version

V6.1.0

### Frontend version

V.1.11.1

### Elixir & Erlang/OTP versions

Elixer 1.2

### Operating system

Windows

**Comment by mirbilal** [comment]
Looks like there the base fee is more than 20 now

**Comment by vbaranov** [comment]
This chat is for Blockscout-related questions. Your question is out of scope, where the Blockscout team can help.
