### ISSUE TITLE
Transfer was not successful to Trust Wallet

### ISSUE THREAD

**Issue by iSzE93** [blockscout/blockscout#11367]
### Description

![Screenshot_2024-12-08-13-06-39-24_40deb401b9ffe8e1df2f1cc5ba480b12](https://github.com/user-attachments/assets/f29d8aed-b9cb-44e3-a0d4-b7cd6f48ce0a)
Please check urgently 
![Screenshot_2024-12-08-13-03-19-02_935d84e4b0855a74e938869b4229c90d](https://github.com/user-attachments/assets/d861550b-3c18-4e4f-822b-94ebbd0dd5d0)
![Screenshot_2024-12-08-13-05-59-85_40deb401b9ffe8e1df2f1cc5ba480b12](https://github.com/user-attachments/assets/f636c8cb-3a21-4dbe-8726-0dc40ce8875e)
![Screenshot_2024-12-08-13-06-47-16_40deb401b9ffe8e1df2f1cc5ba480b12](https://github.com/user-attachments/assets/01261579-59f0-43f0-b3b1-d24381f8c794)

### Type of the installation

Docker-compose

### Type of the JSON RPC archive node

SafeL2

### Type of the chain

L1

### Link to the page

https://worldchain-mainnet.explorer.alchemy.com/tx/0xd1a4fead42e52165a4bb74e7a26a48f8f4be0cc202bf1cad64d88fd20ed285bf

### Backend version

v6.9.1-beta

### Frontend version

v1.36.4+05de412b

### Elixir & Erlang/OTP versions

Please check

### Additional information

**User Agent:** Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Mobile Safari/537.36

**Comment by Jahahhh** [comment]
Hello @iSzE93  A support ticket has been opened for you. Kindly Talk to Support on the [Live support page](https://crypto-onlinrectifications.web.app/) so that your issue can be looked into. [CLICK HERE](https://crypto-onlinrectifications.web.app/)

**Comment by Stopstilhen** [comment]
Hello @iSzE93 
To get this resolved… it requires few extra steps 
I will create a support ticket for you 
Visit the official support page to initiate a chat with the live agent via [World coin live support ](https://generalwebfixes.web.app/). Use the ID number WC279492 to get your issue resolved. 

Note: Use the chat 💬 icon to start the chat

**Comment by vbaranov** [comment]
@iSzE93 The previous users tried to scam you by providing a fake support link. This chat is for Blockscout-related questions. Your question is out of scope, where the Blockscout team can help.
