### ISSUE TITLE
गलत एंड्रेस पे कॉइन भेजे गए

### ISSUE THREAD

**Issue by Vinodkumarkajla** [blockscout/blockscout#11362]
### Description

मेरे वर्ड कॉइन गलत एंड्रेस पे भेजे गए है 

### Type of the installation

Docker-compose

### Type of the JSON RPC archive node

Non

### Link to the page

https://worldchain-mainnet.explorer.alchemy.com/tx/0xbecb873d2d7aee8f4a720e8ac9e38e892943e31b41d6b5cdace6e9fbfdb1c715

### Steps to reproduce

![Screenshot_2024-12-07-15-04-12-74_935d84e4b0855a74e938869b4229c90d](https://github.com/user-attachments/assets/29e571ef-dfa6-486b-9a26-dee3b7d95ebc)

### Backend version

v6.9.1-beta

### Frontend version

v1.36.4+05de412b

### Elixir & Erlang/OTP versions

Non

### Operating system

Non

### Additional information

**User Agent:** Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Mobile Safari/537.36

**Comment by vbaranov** [comment]
This chat is for Blockscout-related questions. Your question is out of scope, where the Blockscout team can help.
