### ISSUE TITLE
Reclamo monedas

### ISSUE THREAD

**Issue by Murillo2479** [blockscout/blockscout#11360]
### Description

Buenas noches por favor devolver las 25 monedas fue un error enviar la necesito quiero que me las devuelva tengo que entregarlas por favor 
![Screenshot_20241206-222800_Chrome](https://github.com/user-attachments/assets/dcebc5b7-ddc5-4ec1-b9af-bcb0c8391c62)
![Uploading Screenshot_20241206-222842_Chrome.jpg…]()

### Type of the installation

Docker

### Type of the JSON RPC archive node

https://worldchain-mainnet.explorer.alchemy.com/tx/0xedffed3fe0b96ac6281f9bb5d7010baf8b397b5bad3b8ace565aecd6eed0c61a

### Link to the page

https://worldchain-mainnet.explorer.alchemy.com/tx/0xedffed3fe0b96ac6281f9bb5d7010baf8b397b5bad3b8ace565aecd6eed0c61a

### Steps to reproduce

Se envió por equivocación a este enlace  quiero que me las devuelva por favor las 25 monedas
![Screenshot_20241205-202526_World App](https://github.com/user-attachments/assets/8478a33c-4b7e-4108-a3df-64fdc2784448)
![Screenshot_20241206-222800_Chrome](https://github.com/user-attachments/assets/e0bfab94-91a2-459f-8f8b-09497b38d0a2)
![Screenshot_20241206-222842_Chrome](https://github.com/user-attachments/assets/795afc08-fb1e-485e-a34c-2648591d8075)

### Backend version

v6.9.1-beta

### Frontend version

v1.36.4+05de412b

### Elixir & Erlang/OTP versions

Reclamo las.monedas

### Operating system

Reclamo

### Additional information

**User Agent:** Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Mobile Safari/537.36

**Comment by vbaranov** [comment]
This chat is for Blockscout-related questions. Your question is out of scope, where the Blockscout team can help.
