### ISSUE TITLE
The block confirmations are taking too much time

### ISSUE THREAD

**Issue by Nashon44** [blockscout/blockscout#11361]
### Description

I send my world coin to OKX and the coins have not been released 

### Type of the installation

Docker-compose

### Type of the JSON RPC archive node

Polygon 

### Type of the chain

L1

### Link to the page

https://worldchain-mainnet.explorer.alchemy.com/contract-verification

### Backend version

v6.9.1-beta

### Frontend version

v1.36.4+05de412b

### Elixir & Erlang/OTP versions

Elixir 1.17.1

### Additional information

**User Agent:** Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Mobile Safari/537.36

**Comment by vbaranov** [comment]
This chat is for Blockscout-related questions. Your question is out of scope, where the Blockscout team can help.
