### ISSUE TITLE
 swap or Exchange to Tether USD (USDT not functional on Gravity Chain (does not work)

### ISSUE THREAD

**Issue by 4u2hear3000** [blockscout/blockscout#11369]
### Description

Exchange or swap into USDT from any other coin (G, WETH, USDC.e, ..) is not working on any platform (iZumi, StarGate, Symbiosis)
Checking the contract address for USDT on 
[0x816E810f9F787d669FB71932DeabF6c83781Cd48](https://explorer.gravity.xyz/token/0x816E810f9F787d669FB71932DeabF6c83781Cd48)

### Type of the installation

Docker-compose

### Type of the JSON RPC archive node

app.symbiosis.finance/swap

### Type of the chain

L1

### Link to the page

https://app.symbiosis.finance/swap?chainIn=Gravity&chainOut=Gravity&tokenIn=G&tokenOut=0x816E810f9F787d669FB71932DeabF6c83781Cd48

### Steps to reproduce

Try to swap any coin to USDT (G or WETH) :
https://app.symbiosis.finance/swap?chainIn=Gravity&chainOut=Gravity&tokenIn=G&tokenOut=0x816E810f9F787d669FB71932DeabF6c83781Cd48

### Backend version

app.symbiosis.finance/swap

### Frontend version

app.symbiosis.finance/swap

### Elixir & Erlang/OTP versions

app.symbiosis.finance/swap

### Operating system

Chrome browser

### Additional information

https://explorer.gravity.xyz/address/0x816E810f9F787d669FB71932DeabF6c83781Cd48

**Comment by vbaranov** [comment]
This chat is for Blockscout-related questions. Your question is out of scope, where the Blockscout team can help.
