### ISSUE TITLE
World coin don't deposit my exchange 

### ISSUE THREAD

**Issue by Panther0034** [blockscout/blockscout#11371]
### Description

Bybit exchange pr world coin chain don't available please my coin refund my account 

### Type of the installation

Docker-compose

### Type of the JSON RPC archive node

Optimism 

### Type of the chain

Optimism 

### Link to the page

https://worldchain-mainnet.explorer.alchemy.com/tx/0xad411666b9a3dee6951101fc2619104d0cdb6bf637c624bfe950b5faa5828c35

### Steps to reproduce

Bybit exchange don't update world chain not available world chain my world coin gon 😭

### Backend version

v6.9.1-beta

### Frontend version

v1.36.4+05de412b

### Elixir & Erlang/OTP versions

5246693

### Operating system

Phone 

### Additional information

**User Agent:** Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Mobile Safari/537.36

**Comment by vbaranov** [comment]
This chat is for Blockscout-related questions. Your question is out of scope, where the Blockscout team can help.
