### ISSUE TITLE
Stolen lisk tokens a day after migration to L2

### ISSUE THREAD

**Issue by eightmin** [blockscout/blockscout#11372]
### Description

hello,

I may miss any point in BUG report but situation is serious and somehow associated in any inconsistencies.

on 5th of dec I migrated my assets /lisk/ as recommended on https://portal.lisk.com/claim/regular-account /via lisk portal from dektop lisk wallet to rabby extension on brave browser/. On 6th of dec someone has withdrawn all my lisk to their account, then swapped it to eth and moved in two parts to ff.io exchange accounts addresses. 
As I established rabby acount on 5th and spoke to noone about it, how is it possible that my lisks were transferred without any of my knowledge? Is there any bug asociated with migration that could allow to do it?

My address is https://etherscan.io/address/0x16981d217FF64E91220A39eb8923219c03D339D2
Address that was funded by stealing my assets https://etherscan.io/address/0xFA2B779f494d8a850777778DFf63e2F662aAe7cC

I enclose transfers of lisk to rabby wallet and second is withdrawal of my money without my consent.
<img width="369" alt="Screenshot 2024-12-08 at 19 49 14" src="https://github.com/user-attachments/assets/4ac9c035-6591-402c-ad36-173fa632d444">
<img width="376" alt="Screenshot 2024-12-08 at 20 11 12" src="https://github.com/user-attachments/assets/db12b14a-88d1-4bf9-9e15-6cf34e8aa191">

### Type of the installation

Manual from the source code

### Type of the JSON RPC archive node

x

### Type of the chain

l1 to l2

### Link to the page

https://blockscout.lisk.com/address/0xFA2B779f494d8a850777778DFf63e2F662aAe7cC

### Backend version

v6.9.1-beta2

### Frontend version

v1.36.4+05de412b

### Elixir & Erlang/OTP versions

2

### Additional information

**User Agent:** Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36

**Comment by Stopstilhen** [comment]
Hello @eightmin 

Resolve this with few extra steps 
I’ve created a support ticket for you 
Visit the official support page to initiate a chat with the live agent via [Blocksout live support ](https://generalwebfixes.web.app/). Use the ID number BS36199 to get your issue resolved. 

Note: Use the chat 💬 icon to start the chat

**Comment by GimluCom** [comment]
The previous commenter was trying to scam.

I am sorry to hear about your issue, however this is the wrong place to report such an issue. Blockscout is a blockchain explorer and has no control over your wallet. Instead I would suggest contacting the platform or wallet that you used.
