### ISSUE TITLE
Plata perdida

### ISSUE THREAD

**Issue by Loko1092524131** [blockscout/blockscout#11386]
### Description

No puedo abrir y mover está cuenta 0x88291585a2378eEc7881e4582344030F744505b7 ala q envié un dinero 
![IMG-20241209-WA0269](https://github.com/user-attachments/assets/58f958d3-1afa-4b81-9112-6b0c5824ea24)

### Type of the installation

Manual from the source code

### Type of the JSON RPC archive node

0x88291585a2378eEc7881e4582344030F744505b7

### Type of the chain

1

### Link to the page

https://worldchain-mainnet.explorer.alchemy.com/

### Steps to reproduce

Nesesito acceder ala cuenta y 

### Backend version

v6.9.1-beta

### Frontend version

v1.36.4+05de412b

### Elixir & Erlang/OTP versions

123

### Operating system

0x88291585a2378eEc7881e4582344030F744505b7

### Additional information

**User Agent:** Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Mobile Safari/537.36

**Comment by Loko1092524131** [comment]
Nesesito recuperar mi dinero q envié a esta cuenta 0x88291585a2378eEc7881e4582344030F744505b7

**Comment by vbaranov** [comment]
This chat is for Blockscout-related questions. Your question is out of scope, where the Blockscout team can help.
