### ISSUE TITLE
Myself

### ISSUE THREAD

**Issue by NameNoQuality** [blockscout/blockscout#11403]
### Description

0xb5d85cbf7cb3ee0d56b3bb207d5fc4b82f43f511

### Type of the installation

Docker-compose

### Type of the JSON RPC archive node

 Erigon/Geth/Nethermind/Reth/PolygonEdge/Besu/O  Feedback

### Type of the chain

L1/L2/L3/L4/L5/L6/L7/L8

### Link to the page

https://testnet2.photonchain.io/contract-verification

### Backend version

v6.8.1-beta.+commit.3fcfb664

### Frontend version

v1.35.2+08de20eb

### Elixir & Erlang/OTP versions

Elixir 1.17.3 (compiled with Erlang/OTP 27)

### Operating system

Linux

### Additional information

**User Agent:** Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/133.0.0.0 Mobile Safari/537.36

**Comment by vbaranov** [comment]
This chat is for Blockscout-related questions. Your question is out of scope, where the Blockscout team can help.
