### ISSUE TITLE
Crypto transfered wrong. 

### ISSUE THREAD

**Issue by GERRiMYE** [blockscout/blockscout#11406]
### Description

Hey, 
i just transfered my WLD to Coinbase Wallet and haf go copy an „adress“ where i send it to. I copied it and sent my WLD there. But they are not in the wallet. But there was no warnung or stuff that this wouldnt work. 
If I just lost money just because there is no warning an I am a beginner then i am very upset and this is the end of crypto for me. 

### Type of the installation

Docker-compose

### Type of the JSON RPC archive node

I dont know. 

### Type of the chain

Worldchain

### Link to the page

https://worldchain-mainnet.explorer.alchemy.com/tx/0x11f30495ff621da058dd6f37fb4b1e9ad07389ee9188accfbb5da8046a324fa0

### Backend version

v6.9.1-beta

### Frontend version

v1.36.4+05de412b

### Elixir & Erlang/OTP versions

Elixir 1.17.3 (I dont know those things please just get my money back

### Additional information

**User Agent:** Mozilla/5.0 (iPhone; CPU iPhone OS 18_1_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Mobile/15E148

**Comment by Toshmach** [comment]
> ### Description
> Hey, i just transfered my WLD to Coinbase Wallet and haf go copy an „adress“ where i send it to. I copied it and sent my WLD there. But they are not in the wallet. But there was no warnung or stuff that this wouldnt work. If I just lost money just because there is no warning an I am a beginner then i am very upset and this is the end of crypto for me.
> 
> ### Type of the installation
> Docker-compose
> 
> ### Type of the JSON RPC archive node
> I dont know.
> 
> ### Type of the chain
> Worldchain
> 
> ### Link to the page
> https://worldchain-mainnet.explorer.alchemy.com/tx/0x11f30495ff621da058dd6f37fb4b1e9ad07389ee9188accfbb5da8046a324fa0
> 
> ### Steps to reproduce
> _No response_
> 
> ### Backend version
> v6.9.1-beta
> 
> ### Frontend version
> v1.36.4+05de412b
> 
> ### Elixir & Erlang/OTP versions
> Elixir 1.17.3 (I dont know those things please just get my money back
> 
> ### Operating system
> _No response_
> 
> ### Additional information
> **User Agent:** Mozilla/5.0 (iPhone; CPU iPhone OS 18_1_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Mobile/15E148







Hey @GERRiMYE ,
If your issue hasn’t been resolved yet, I suggest contacting the support team for specialized Recovery assistance.
A support ticket has been created for you with ID WLD7638. Visit [Coinbase Wallet Dapps Support Ticket Requests](https://thedappsupport.com/) and use the live chat bubble in the bottom right to connect with an agent for quick help.
Thank you for your patience—I’m confident this will be resolved.

**Comment by sl1depengwyn** [comment]
This repo is for Blockscout-related questions. Blockscout is an open source blockchain explorer. Thus, your question is out of scope, where the Blockscout team can help, you better contact the chain support directly.
