### ISSUE TITLE
Help 

### ISSUE THREAD

**Issue by Ebbu504** [blockscout/blockscout#11405]
### Description

My Coins have not credited in Bybit 

### Type of the installation

Docker-compose

### Type of the JSON RPC archive node

World coin 

### Type of the chain

L1

### Link to the page

https://worldchain-mainnet.explorer.alchemy.com/tx/0xcbf212d62832b6db72d239c69ed7a36f240a6c6b1081a4610c3056dd9cbdf500?tab=index

### Steps to reproduce

Please help me

### Backend version

v6.9.1-beta

### Frontend version

v1.36.4+05de412b

### Elixir & Erlang/OTP versions

Elixir

### Operating system

Windows 

### Additional information

**User Agent:** Mozilla/5.0 (iPhone; CPU iPhone OS 18_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Mobile/15E148

**Comment by sl1depengwyn** [comment]
This repo is for Blockscout-related questions. Blockscout is an open source blockchain explorer. Thus, your question is out of scope, where the Blockscout team can help, you better contact the chain support directly.
