### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by KATERYNA215** [blockscout/blockscout#11401]
### Description

why i can not claim Pton?

### Type of the installation

Manual from the source code

### Type of the JSON RPC archive node

Photon aurora tesnet

### Type of the chain

L1

### Link to the page

https://testnet2.photonchain.io/contract-verification

### Steps to reproduce

i dont know

### Backend version

v6.8.1-beta.+commit.3fcfb664

### Frontend version

v1.35.2+08de20eb

### Elixir & Erlang/OTP versions

Elixir

### Additional information

**User Agent:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36

**Comment by sl1depengwyn** [comment]
This repo is for Blockscout-related questions. Blockscout is an open source blockchain explorer. Thus, your question is out of scope, where the Blockscout team can help, you better contact the chain support directly.
