### ISSUE TITLE
Cannot proceed with the Get Merits

### ISSUE THREAD

**Issue by Galmic** [blockscout/blockscout#11404]
### Description

wallet is connected & when i click Merits and "Get Started" i have and Error
![Screenshot 2024-12-12 104637](https://github.com/user-attachments/assets/ba1d1d59-46ac-4f37-a7e9-94f0cce1baf1)

### Type of the installation

Docker-compose

### Type of the JSON RPC archive node

n/a

### Link to the page

https://eth.blockscout.com/account/verified-addresses

### Steps to reproduce

Click Merit
Click Get Started

### Backend version

v6.9.2-beta

### Frontend version

v1.36.4+05de412b

### Elixir & Erlang/OTP versions

n/a

### Additional information

**User Agent:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/110.0.0.0 Safari/537.36 Tangled/1.22.3

**Comment by MALDOVILA** [comment]
Hola.
No me llegan mis token.

**Comment by sl1depengwyn** [comment]
@Galmic are you still encountering this error? If so, which browser do you use?

**Comment by Galmic** [comment]
problem has been solved. Thank you for your reply.

**Comment by MALDOVILA** [comment]
Pero no aparece en mi monedero
