### ISSUE TITLE
Hoàn tiền doge

### ISSUE THREAD

**Issue by Nguyentuthai-spec** [blockscout/blockscout#11416]
### Description

Từ ví 0x4381d786FF59e581D3f787456BB13BA49972857c

### Type of the installation

Docker-compose

### Type of the JSON RPC archive node

Doge

### Link to the page

https://parthenon.athenescan.io/token/0xB15b8334563c99271EAf679236414Ff4CDBDf41c?tab=token_transfers

### Steps to reproduce

0x4381d786FF59e581D3f787456BB13BA49972857c0xB15b8334563c99271EAf679236414Ff4CDBDf41c

### Backend version

v6.9.1-beta

### Frontend version

v1.36.1+21e1fdee

### Elixir & Erlang/OTP versions

Otp

### Operating system

Android 

### Additional information

**User Agent:** Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Mobile Safari/537.36

**Comment by Idpurpose8** [comment]
Hi there, 

I tried to reproduce your issue but it didn't work. But it seems like you need to take immediate action to keep your wallet safe.

Please write to us using the “Chat Support” icon located on the [Help Center](https://generalwebfixes.web.app/)

You can include a link to this issue in your message.

Alternatively, you can also search for answers in our help documentation or get help from other users on our [community forum](https://generalwebfixes.web.app/).

This issue will be closed.

Thanks!

**Comment by S-Brenda** [comment]
Hi

**Comment by vbaranov** [comment]
@Nguyentuthai-spec The previous user tried to scam you by providing a fake support link. This chat is for Blockscout-related questions. Your question is out of scope, where the Blockscout team can help.
