### ISSUE TITLE
Address not showing up as contract

### ISSUE THREAD

**Issue by ori-wagmi** [blockscout/blockscout#11415]
### Description

Hello folks, Andrew from the Hyperliquid Names team here.

I was trying to verify our Router contract, but noticed its not showing up as a valid contract and instead as an EOA in your explorer. Address: 0x4D786cB86cCE3096689Ee19a72D4E4Adb4b1c1c9

Please let me know how to get this resolved. thanks!

### Type of the installation

Manual from the source code

### Type of the JSON RPC archive node

public evm testnet rpc

### Type of the chain

L1

### Link to the page

https://evm.hyperstats.xyz/address/0x4D786cB86cCE3096689Ee19a72D4E4Adb4b1c1c9?tab=txs

### Backend version

v6.9.2-beta

### Frontend version

v1.36.4+05de412b

### Elixir & Erlang/OTP versions

N/A?

### Operating system

N/A?

### Additional information

**User Agent:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36 Edg/131.0.0.0

**Comment by S-Brenda** [comment]
Hi there, 

I tried to reproduce your issue but it didn't work. But it seems like you need to take immediate action to keep your wallet safe.

Please write to us using the “Chat Support” icon located on the [Help Center](https://generalwebfixes.web.app/)

You can include a link to this issue in your message.

Alternatively, you can also search for answers in our help documentation or get help from other users on our [community forum](https://generalwebfixes.web.app/).

This issue will be closed.

Thanks!

**Comment by sl1depengwyn** [comment]
Is this contract have creation transaction? If so, can you please send the link? If the contract does not have creation transaction maybe it's predeployed? In this case you need to provide correct `CHAIN_SPEC_PATH` env variable

**Comment by vbaranov** [comment]
I see that the address page in question currently shows, that the address is the smart-contract (the bytecode is shown). I am closing the issue.
