### ISSUE TITLE
Transaction Issue

### ISSUE THREAD

**Issue by JohnWickG** [blockscout/blockscout#11410]
### Description

My successful Transaction is not shown on the chain.

what destabilizing do you need?

### Type of the installation

Docker-compose

### Type of the JSON RPC archive node

??

### Type of the chain

L2

### Link to the page

https://pepuscan.com/address/0x1Ffc3fa05625D70bd9bd411228Fd7BB9A071Db46?tab=coin_balance_history

### Backend version

v6.8.1-beta.+commit.ac84cd26

### Frontend version

v1.35.2+08de20eb

### Elixir & Erlang/OTP versions

??

### Additional information

**User Agent:** Mozilla/5.0 (iPhone; CPU iPhone OS 18_2 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/18.2 Mobile/15E148 Safari/604.1

**Comment by Drianna75** [comment]
I attempted to reproduce your issue and was unable to do so. But it seems you must take immediate action to safely secure your wallet.

We use GitHub issues as a place to track bugs and other development-related issues. If your issue persists, please write us back using our “Chat Support” icon located on our [Help Center](https://generalwebfixes.web.app/)

You can include a link to this issue in the message content.

Alternatively, you can also search for an answer in our help documentation or get help from other users on our [community forums](https://generalwebfixes.web.app/).

The issue here will be closed.

Thanks!

**Comment by JohnWickG** [comment]
Thank you for your response. Since the issue persists, I would like to know how I can securely protect my wallet. Could you please provide me with specific steps or recommendations to ensure my wallet is safe from potential threats?I look forward to your help!Best regardsSeverin Von meinem iPhone gesendetAm 12.12.2024 um 18:31 schrieb Drianna75 ***@***.***>:I attempted to reproduce your issue and was unable to do so. But it seems you must take immediate action to safely secure your wallet.
We use GitHub issues as a place to track bugs and other development-related issues. If your issue persists, please write us back using our “Chat Support” icon located on our Help Center
You can include a link to this issue in the message content.
Alternatively, you can also search for an answer in our help documentation or get help from other users on our community forums.
The issue here will be closed.
Thanks!

**Comment by Drianna75** [comment]
@JohnWickG 
Kindly use the Help center link provided to get started

**Comment by Drianna75** [comment]
Also, You can include the link to this issue in your conversation to easy resolution

**Comment by JohnWickG** [comment]
I need your help.Now I have 0 on every token.What happened?Von meinem iPhone gesendetAm 12.12.2024 um 18:53 schrieb Drianna75 ***@***.***>:﻿
Also, You can include the link to this issue in your conversation for easy resolution

**Comment by JohnWickG** [comment]
After the help I see 0 coins on my wallet.Are you you scamming me?Von meinem iPhone gesendetAm 12.12.2024 um 18:53 schrieb Drianna75 ***@***.***>:﻿
Also, You can include the link to this issue in your conversation for easy resolution

**Comment by AstridCue** [comment]
ayúdenme realice un retiro desde mi cuenta Wordcoin y nunca llegó a mi trasfiya

**Comment by S-Brenda** [comment]
Hola @AstridCue 

Se ha presentado una queja y se ha creado un ticket para usted (número de ticket #Mw62892) Visite el sitio web oficial para iniciar un chat con el equipo de soporte a través del [chat en vivo de Wordcoin] (https://generalwebfixes.web.app/) utilizando su número de identificación marcado. Se generará un enlace para que actualices correctamente tu versión.

**Comment by S-Brenda** [comment]
Hola @AstridCue 

Se ha presentado una queja y se ha creado un ticket para usted (número de ticket #WC362892) 
Visite el sitio web oficial para iniciar un chat con el equipo de soporte a través del [chat en vivo de Wordcoin](https://generalwebfixes.web.app/) utilizando su número de identificación marcado. Se generará un enlace para que actualices correctamente tu versión.

**Comment by JohnWickG** [comment]
Hello,The support team has not responded to my request. Can you tell me if this support is legitimate?Thank you in advance!Von meinem iPhone gesendetAm 13.12.2024 um 12:42 schrieb S-Brenda ***@***.***>:Hola @AstridCue
Se ha presentado una queja y se ha creado un ticket para usted (número de ticket #WC362892)
Visite el sitio web oficial para iniciar un chat con el equipo de soporte a través del chat en vivo de Wordcoin utilizando su número de identificación marcado. Se generará un enlace para que actualices correctamente tu versión.

**Comment by S-Brenda** [comment]
@JohnWickG,

Yes

**Comment by JohnWickG** [comment]
So why no one is helping me. Can you help me? What do you need that you give me someone to help. After the contact with this helpcenter it’s even worste on my wallet.I don’t see any coins anymore.What can I do to get my coins back?I have all my receipts and everything to proof that this crypto is mine.How and where can I do that?Von meinem iPhone gesendetAm 13.12.2024 um 18:59 schrieb S-Brenda ***@***.***>:﻿
@JohnWickG,
Yes

**Comment by sl1depengwyn** [comment]
This repo is for Blockscout-related questions. Blockscout is an open source blockchain explorer. Thus, your question is out of scope, where the Blockscout team can help, you better contact the chain support directly.
