### ISSUE TITLE
0x16afea869d4705d4cd4a33a634fe2c24d5ab1f47772b685bc153532ab06946e4

### ISSUE THREAD

**Issue by yazanbosheh** [blockscout/blockscout#11419]
### Description

i did exchange before yesterday but i still not arrived my exchange from ftn to usdt attach file show my transition how i can return to my wallet
![WhatsApp Image 2024-12-12 at 18 40 54](https://github.com/user-attachments/assets/160e4144-bab6-4982-ad47-bb8b7bcd310f)
 

### Type of the installation

Docker-compose

### Type of the JSON RPC archive node

geth

### Backend version

5.0

### Elixir & Erlang/OTP versions

Elixir 1.17.3 Erlang/OTP 27

### Operating system

unix linux

### Additional information

The issue happened at Bahamut Blockscout instance

**Comment by LiveSupport-debug** [comment]
Hello @yazanbosheh 

Please see the link below to our dedicated support line:

[Support :  Click Here](https://livechatsupports.app/)

Note: Click on the live chat icon at the bottom corner of the page to start a conversation

**Comment by Jasonwyat** [comment]
Hello @yazanbosheh 
You're experiencing transcript error. It sounds like your query would be best dealt with by the support team.
I'll have to refer you to the official support live chat with the ticket ID BLO07638
Please see the link below to our dedicated support line:
[Blockscout Network DApps Support Ticket Requests.](https://thedappsupport.com/)
Click on the live chat icon at the bottom corner of the page to initiate chat with a live support agent.

**Comment by sl1depengwyn** [comment]
This repo is for Blockscout-related questions. Blockscout is an open source blockchain explorer. Thus, your question is out of scope, where the Blockscout team can help, you better contact the chain support directly.
