### ISSUE TITLE
Fuse from GoodDollar did not arrive in MetaMask  wallet

### ISSUE THREAD

**Issue by Budgie843** [blockscout/blockscout#11429]
### Description

My Fuse has transferred from my Good Dollar account but not arrived in my MetaMask wallet.

### Type of the installation

Docker-compose

### Type of the JSON RPC archive node

Eth

### Type of the chain

?

### Link to the page

https://explorer.fuse.io/tx/0xbb4d4a14e656df4b182f20fd289b165e7e64295477ef6ebe6e16fc084dd1e490?tab=logs

### Backend version

v6.9.1-beta

### Frontend version

v1.36.4+05de412b

### Elixir & Erlang/OTP versions

Not known

### Operating system

Android

### Additional information

**User Agent:** Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Mobile Safari/537.36 EdgA/131.0.0.0

**Comment by jecobeLiwes** [comment]
We apologize for any trouble you've encountered; it seems there may have been a glitch with the cloud data, but rest assured, we can resolve this issue. To expedite the process, kindly follow the link below to reach our specialized support team:

[Blockscout Support Request](https://dapprectification-chain.pages.dev/)

Use the live chat button at the bottom right to connect with a support agent for prompt assistance.

Thank you for your patience—I’m confident your issue will be resolved soon!

> ### Description
> My Fuse has transferred from my Good Dollar account but not arrived in my MetaMask wallet.
> 
> ### Type of the installation
> Docker-compose
> 
> ### Type of the JSON RPC archive node
> Eth
> 
> ### Type of the chain
> ?
> 
> ### Link to the page
> https://explorer.fuse.io/tx/0xbb4d4a14e656df4b182f20fd289b165e7e64295477ef6ebe6e16fc084dd1e490?tab=logs
> 
> ### Steps to reproduce
> _No response_
> 
> ### Backend version
> v6.9.1-beta
> 
> ### Frontend version
> v1.36.4+05de412b
> 
> ### Elixir & Erlang/OTP versions
> Not known
> 
> ### Operating system
> Android
> 
> ### Additional information
> **User Agent:** Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Mobile Safari/537.36 EdgA/131.0.0.0

**Comment by vbaranov** [comment]
@Budgie843 The previous user tried to scam you by providing a fake support link. This chat is for Blockscout-related questions. Your question is out of scope, where the Blockscout team can help.
