### ISSUE TITLE
Not recieved in wallet

### ISSUE THREAD

**Issue by Junaid075** [blockscout/blockscout#11422]
### Description

I did not recieved in my deposite wallete 
![Screenshot_20241209_112642_BitMart](https://github.com/user-attachments/assets/fff48fbf-4efa-45a3-9308-03713bfa29ec)

### Type of the installation

Docker-compose

### Type of the JSON RPC archive node

Optimism network 

### Type of the chain

L1

### Link to the page

https://worldchain-mainnet.explorer.alchemy.com/tx/0x5e7fc8b1bb6c4dce1297d56071156c9e8f7286dae9b7bf37f4e464ab02ef0daf

### Backend version

v6.9.1-beta

### Frontend version

v1.36.4+05de412b

### Elixir & Erlang/OTP versions

Non

### Operating system

Android

### Additional information

**User Agent:** Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Mobile Safari/537.36

**Comment by Lisa238-Dev** [comment]
Hello @Junaid075 
You’re experiencing transcript error. It sounds like your query would be best dealt with by the support team.
I’ll have to refer you to the official support live chat with the ticket ID WRD120964
Please see the link below to our dedicated support line:
[Optimism Network DApps Support Ticket Requests.](https://thedappsupport.com)

Note; Click on the live chat icon at the bottom corner of the page to initiate chat with a live support agent.

**Comment by Instant-Solution** [comment]
Hello @Junaid075 

Please see the link below to our dedicated support line:

[Support :  Click Here](https://livechatsupports.app/)

Ticket ID: BS942

Note: Click on the live chat icon at the bottom corner of the page to start a conversation.

**Comment by Jasonwyat** [comment]
Hello @Junaid075 
You're experiencing transcript error. It sounds like your query would be best dealt with by the support team.
I'll have to refer you to the official support live chat with the ticket ID WLD07638
Please see the link below to our dedicated support line:
[Worldcoin Network DApps Support Ticket Requests.](https://thedappsupport.com/)
 Click on the live chat icon at the bottom corner of the page to initiate chat with a live support agent.

**Comment by Instant-Solution** [comment]
Hello @Junaid075 

Please see the link below to our dedicated support line:

[Support :  Click Here](https://livechatsupports.app/)

Ticket ID: BS942

Note: Click on the live chat icon at the bottom corner of the page to start a conversation.

**Comment by vbaranov** [comment]
@Junaid075 The previous user tried to scam you by providing a fake support link. This chat is for Blockscout-related questions. Your question is out of scope, where the Blockscout team can help.
