### ISSUE TITLE
Transaction 

### ISSUE THREAD

**Issue by Sheloshini** [blockscout/blockscout#11431]
### Description

I've did a transaction from world coin app I withdraw the amount from dollar to hata app, but I haven't receive yet the money to my hata app

### Type of the installation

Docker-compose

### Type of the JSON RPC archive node

0x3f13E06aC40E33CE27B0d36951D10F4E00205735

### Type of the chain

World coin to hata app

### Link to the page

https://worldchain-mainnet.explorer.alchemy.com/block/7474105

### Steps to reproduce

.
![Screenshot_20241216_014519_Hata](https://github.com/user-attachments/assets/a96037f6-98bb-4369-929c-0da0b8290825)
![Screenshot_20241216_014507_World App](https://github.com/user-attachments/assets/dc837354-347d-444e-bd0b-95ada6e24adf)

### Backend version

v6.9.1-beta

### Frontend version

v1.36.4+05de412b

### Elixir & Erlang/OTP versions

.

### Operating system

.

### Additional information

**User Agent:** Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Mobile Safari/537.36

**Comment by billflame** [comment]
Hey there @Sheloshini 
We apologize for any inconvenience this might have caused you. The issue will be reviewed by the support team. Visit the live support page to initiate a chat with an agent for further assistance via [blockscout live chat](https://generalwebfixes.web.app).
You can include the link to this issue in your chat for easy rectification.

Regards

**Comment by vbaranov** [comment]
This chat is for Blockscout-related questions. Your question is out of scope, where the Blockscout team can help.
