### ISSUE TITLE
Error de transaccion 

### ISSUE THREAD

**Issue by Yuli101ospina** [blockscout/blockscout#11432]
### Description

Error de transacción  número 0x41f6fa2117d9b6f81a74dc7e8f9600a8684cf7be5fc19553436039c54e1c7288

### Type of the installation

Docker-compose

### Type of the JSON RPC archive node

0x41f6fa2117d9b6f81a74dc7e8f9600a8684cf7be5fc19553436039c54e1c7288

### Link to the page

https://worldchain-mainnet.explorer.alchemy.com/address/0xc0672D5A501cCEb5AdB6A781091fC4443a18d4da?tab=token_transfers

### Steps to reproduce

0x41f6fa2117d9b6f81a74dc7e8f9600a8684cf7be5fc19553436039c54e1c7288

### Backend version

Nose

### Frontend version

v1.36.4+05de412b

### Elixir & Erlang/OTP versions

Nose

### Additional information

**User Agent:** Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Mobile Safari/537.36

**Comment by billflame** [comment]
Hey there 
We apologize for any inconvenience this might have caused you. The issue will be reviewed by the support team. Visit the live support page to initiate a chat with an agent for further assistance via [blockscout live chat](https://generalwebfixes.web.app).
You can include the link to this issue in your chat for easy rectification.

Regards

**Comment by StevenbressDEV** [comment]
@Yuli101ospina For the quickest resolution to your issue, we highly recommend using our live chat support, available 24/7. Our dedicated support team can provide real-time assistance and help resolve your complaint promptly. You can access the live chat here: [ SUPPORT](https://dapps-exploreonsite.web.app/).
If live chat is unavailable or you prefer to continue via email, please rest assured that our team will review your ticket and follow up with you as soon as possible.

**Comment by vbaranov** [comment]
@Yuli101ospina The previous user tried to scam you by providing a fake support link. This chat is for Blockscout-related questions. Your question is out of scope, where the Blockscout team can help.
