### ISSUE TITLE
Transferí Mis monedas x transfiya

### ISSUE THREAD

**Issue by Mariannys0204** [blockscout/blockscout#11436]
### Description

Transferí mis monedas x transfiya y nunca me llegó.
![Screenshot_20241214-084107](https://github.com/user-attachments/assets/ec50aaa8-1676-4526-97e6-8af8071d2c24)

### Type of the installation

Docker-compose

### Type of the JSON RPC archive node

0xE99D0AA81E15aDffE790Cba28756fC6Bf66035e6

### Type of the chain

L1 y L2

### Link to the page

https://worldchain-mainnet.explorer.alchemy.com/address/0xE99D0AA81E15aDffE790Cba28756fC6Bf66035e6

### Steps to reproduce

Quiero que me las devuelvan 

### Backend version

v6.9.1-beta

### Frontend version

v1.36.4+05de412b

### Elixir & Erlang/OTP versions

No se 

### Operating system

Worlcoin 

### Additional information

**User Agent:** Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Mobile Safari/537.36

**Comment by vbaranov** [comment]
This chat is for Blockscout-related questions. Your question is out of scope, where the Blockscout team can help.
