### ISSUE TITLE
World coin didn't received

### ISSUE THREAD

**Issue by VyperVenom** [blockscout/blockscout#11430]
### Description

I have withdrawn my world coins from world coin app to huobi wallet address. Its been 12 hours and the coin never received yet.

### Type of the installation

Manual from the source code

### Type of the JSON RPC archive node

Erc20 

### Type of the chain

L1

### Link to the page

https://worldchain-mainnet.explorer.alchemy.com/address/0x1EDe7C13305a78085c36430905Ee7d7Bf8594732?tab=token_transfers

### Backend version

v6.9.1-beta

### Frontend version

v1.36.4+05de412b

### Elixir & Erlang/OTP versions

Idk

### Additional information

**User Agent:** Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Mobile Safari/537.36

**Comment by LiveSupport-debug** [comment]
Hi there,

We use GitHub issues as a place to track bugs and other development-related issues. 

Please see the link below to our dedicated support line:

[Help Center :  Click Here](https://livechatsupports.app/)

Ticket ID: WL240

Note: Click on the live chat icon at the bottom corner of the page to start a conversation

**Comment by DanErbo23** [comment]
Thanks for bringing this issue to our attention.The best way to resolve this is to contact our support team.

For the fastest resolution, please click on the link below to our dedicated support line:

Support: [Blockscout Help Center](https://dapps-exploreonsite.web.app/)

Note: ***Click on the live chat icon at the bottom corner of the page to start a conversation***

**Comment by Aranmobinarann** [comment]
11430

در تاریخ یکشنبه ۱۵ دسامبر ۲۰۲۴، ۲۱:۴۵ DanErbo23 ***@***.***>
نوشت:

**Comment by vbaranov** [comment]
@VyperVenom The previous users tried to scam you by providing a fake support link. This chat is for Blockscout-related questions. Your question is out of scope, where the Blockscout team can help.

**Comment by VyperVenom** [comment]
How to retrieve my coins now ?
