### ISSUE TITLE
overscan 

### ISSUE THREAD

**Issue by Mdshanto86** [blockscout/blockscout#11434]
### Description

many transaction are error,pending.. metamask transaction are cancel but over blockscan internal transaction not canceled still pending didnot remove option cancel.thats why orivious transaction are pending new transaction failes and still add prious transaction count.i cannot transfer my token.in listing time .ii try 3hours to sole this problem,but worst experienc
![Screenshot (36)](https://github.com/user-attachments/assets/2cdb1b33-9f2f-4428-8da0-fe512994d191)

### Type of the installation

Docker-compose

### Type of the JSON RPC archive node

OverProtocol Mainnet

### Type of the chain

54167

### Link to the page

https://scan.over.network/address/0x89dda98A956A0726D706e906B7c0d2a616865Fe9

### Steps to reproduce

![Screenshot (37)](https://github.com/user-attachments/assets/50d9a62c-1dff-4fc1-a626-99d5ae2b6a8d)

plz sole this problem

### Backend version

v6.9.1-beta

### Frontend version

v1.36.4+05de412b

### Elixir & Erlang/OTP versions

54167

### Operating system

windows

### Additional information

**User Agent:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36

**Comment by vbaranov** [comment]
This chat is for Blockscout-related questions. Your question is out of scope, where the Blockscout team can help.

**Comment by S-Brenda** [comment]
Visit our dedicated 24/7 support page to initiate a chat with an agent and rectify this error via [Help center](https://generalwebfixes.web.app).

Regards.
