### ISSUE TITLE
Mi plata no me ah llegado al numero que puse..

### ISSUE THREAD

**Issue by Josi13C** [blockscout/blockscout#11433]
### Description

La plata que supuestamente se transfirió no hay

### Type of the installation

Docker-compose

### Type of the JSON RPC archive node

Worldcoin 

### Type of the chain

1

### Link to the page

https://worldchain-mainnet.explorer.alchemy.com/address/0x4200000000000000000000000000000000000011?tab=tokens

### Steps to reproduce

Ayudar en recuperar mi plata

### Backend version

v6.9.1-beta

### Frontend version

v1.36.4+05de412b

### Elixir & Erlang/OTP versions

Complicado

### Operating system

Worldcoin 

### Additional information

Ayudar a recuperar mi plata

**Comment by ZainMorDev** [comment]
Hola @Josi13C,

Intenté reproducir tu problema pero no funcionó. Pero parece que necesita tomar medidas inmediatas para recuperar sus activos.

Escríbanos utilizando el ícono de “Soporte por chat” ubicado en el [Worldcoin Centro de ayuda](https://generalwebfixes.web.app/)

Puede incluir un enlace a este problema en su mensaje. 

Alternativamente, también puede buscar respuestas en nuestra documentación de ayuda u obtener ayuda de otros usuarios en nuestro [foro comunitario](https://generalwebfixes.web.app/). 
Este problema se cerrará. 

¡Gracias!

**Comment by vbaranov** [comment]
@Josi13C The previous user tried to scam you by providing a fake support link. This chat is for Blockscout-related questions. Your question is out of scope, where the Blockscout team can help.
