### ISSUE TITLE
Deposit not credit 

### ISSUE THREAD

**Issue by christianic7** [blockscout/blockscout#11447]
### Description

I have deposited DOGE on Binance but the amount has not credit yet

### Type of the installation

Manual from the source code

### Type of the JSON RPC archive node

Athene

### Backend version

V2.1.8

### Elixir & Erlang/OTP versions

OTP

**Comment by kriddreak** [comment]
Hi there, 

I tried to reproduce your issue but it didn't work. But it seems like you need to take immediate action and resolve this.

Please write to us using the “Chat Support” icon located on the [Blockscout Help Center](https://generalwebfixes.web.app/)

You can include a link to this issue in your message.

Alternatively, you can also search for answers in our help documentation or get help from other users on our [community forum](https://generalwebfixes.web.app/).

This issue will be closed.

Thanks!

**Comment by vbaranov** [comment]
@christianic7 The previous user tried to scam you by providing a fake support link. This chat is for Blockscout-related questions. Your question is out of scope, where the Blockscout team can help.
