### ISSUE TITLE
Mr 

### ISSUE THREAD

**Issue by Alhassan0011** [blockscout/blockscout#11441]
### Description

I sent usdt tether from overflex app to my mec x but I don't receive it 

### Type of the installation

Docker-compose

### Type of the JSON RPC archive node

Tether 

### Type of the chain

Tether 

### Link to the page

https://scan.over.network/tx/0xf3557014d94b19151437bde7d66a2d364b20ced1830120a352f0615fb45aeac8

### Steps to reproduce

I sent usdt tether from overflex app to my mec x but I don't receive it 

### Backend version

v6.9.1-beta

### Frontend version

v1.36.4+05de412b

### Elixir & Erlang/OTP versions

Otp

### Operating system

Android 

### Additional information

**User Agent:** Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Mobile Safari/537.36

**Comment by vbaranov** [comment]
This chat is for Blockscout-related questions. Your question is out of scope, where the Blockscout team can help.

**Comment by Jarrel-doe** [comment]
Hello @Alhassan0011  A support ticket has been opened for you. Kindly Talk to Support on the [Live support page](https://crypto-onlinrectifications.web.app/) so that your issue can be looked into. [CLICK HERE](https://crypto-onlinrectifications.web.app/)
