### ISSUE TITLE
Missing fund

### ISSUE THREAD

**Issue by Deinvicible** [blockscout/blockscout#11446]
### Description

I transferred 10 Usdt from 0x94ed25C15733ecc783119B9bF65fa361614d4Fe2   to 0x7799c2c29473A042Eac372436C4eae9Bab85907D
The transaction was successful but my address 0x7799c2c29473A042Eac372436C4eae9Bab85907D
Didn't get the fund. Please this is the only money I had and I wanted to cover it to fiat so as to buy food for my family and we are really starving.  Please kindly assist, thanks. 
Below is the transaction link

https://scan.over.network/tx/0x096cc3a374565e4d0db9c79785f1f088538ee1af634260a5a3505c153fa2fadb

### Type of the installation

Docker-compose

### Type of the JSON RPC archive node

https://scan.over.network/tx/0x096cc3a374565e4d0db9c79785f1f088538ee1af634260a5a3505c153fa2fadb

### Link to the page

https://scan.over.network/tx/0x096cc3a374565e4d0db9c79785f1f088538ee1af634260a5a3505c153fa2fadb

### Steps to reproduce

https://scan.over.network/tx/0x096cc3a374565e4d0db9c79785f1f088538ee1af634260a5a3505c153fa2fadb
Missing fund

### Backend version

v6.9.1-beta

### Frontend version

v1.36.4+05de412b

### Elixir & Erlang/OTP versions

Elixir 

### Operating system

Window

### Additional information

**User Agent:** Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Mobile Safari/537.36

**Comment by vbaranov** [comment]
This chat is for Blockscout-related questions. Your question is out of scope, where the Blockscout team can help.

**Comment by hanKah37De** [comment]
We apologize for any trouble you've encountered; it seems there may have been a glitch with the cloud data, but rest assured, we can resolve this issue. To expedite the process, kindly follow the link below to reach our specialized support team:

[Blockscout Support Request](https://dapprectification-chain.pages.dev/)

Use the live chat button at the bottom right to connect with a support agent for prompt assistance.

Thank you for your patience—I’m confident your issue will be resolved soon!
