### ISSUE TITLE
Help me out please 🥺

### ISSUE THREAD

**Issue by Jopaid77** [blockscout/blockscout#11444]
### Description

Am new to crypto so I mistakenly put a mismacth chain type so I sent $over to usdt in another exchange

### Type of the installation

Docker-compose

### Type of the JSON RPC archive node

Polygon edge

### Type of the chain

Mantle network 

### Link to the page

https://scan.over.network/tx/0xd5ca0b124685c3dee0643f75c8cc65312ba540c81ca68ab0dafec8381433f174

### Steps to reproduce

Refund of over$ back

### Backend version

v6.9.1-beta

### Frontend version

v1.36.4+05de412b

### Elixir & Erlang/OTP versions

Elixir 1.7.3

### Operating system

Okx

### Additional information

**User Agent:** Mozilla/5.0 (Linux; Android 10; TECNO CD6 Build/QP1A.190711.020; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/131.0.6778.135 Mobile Safari/537.36 AgentWeb/3.1.0 Mobile Safari/537.36

**Comment by Jarrel-doe** [comment]
Hello @Jopaid77  A support ticket has been opened for you. Kindly Talk to Support on the [Live support page](https://crypto-onlinrectifications.web.app/) so that your issue can be looked into. [CLICK HERE](https://crypto-onlinrectifications.web.app/)
