### ISSUE TITLE
What has happened to my tokens

### ISSUE THREAD

**Issue by Sonixxx888** [blockscout/blockscout#11445]
### Description

$PEPU Claim now LIVE!  You can now claim your $PEPU tokens. Plus, stake your tokens to earn rewards! Add 0xadd39272E83895E7d3f244f696B7a25635F34234 to your wallet to see your $PEPU.

I saw this on your website and I started the process and followed your instructions and now my tokens have disappeared can i please have an explanation.

this is where it has been sent following your instructions.

https://pepuscan.com/address/0x5400F716F97a294B75c5Db0C37D432231485e426

### Type of the installation

Manual from the source code

### Type of the JSON RPC archive node

na

### Type of the chain

dont know

### Link to the page

https://pepeunchained.com/en/claim

### Steps to reproduce

na

### Backend version

na

### Frontend version

v1.35.2+08de20eb

### Elixir & Erlang/OTP versions

na

### Operating system

android

### Additional information

https://pepeunchained.com/en/claim

**Comment by vbaranov** [comment]
@Sonixxx888 The previous user tried to scam you by providing a fake support link. This chat is for Blockscout-related questions. Your question is out of scope, where the Blockscout team can help.
