### ISSUE TITLE
Token Not Delivered in my designated wallet 

### ISSUE THREAD

**Issue by KEENACITA** [blockscout/blockscout#11456]
### Description

I made a transfer of about 9USDT from my OVERPROTOCOL WALLET to My Bybit Wallet and its not reflecting yet. 

### Type of the installation

Docker-compose

### Type of the JSON RPC archive node

I don't know 

### Type of the chain

Blockchain

### Link to the page

https://scan.over.network/tx/0xebb52d7fa4df335ebc7d8b6fc7da676ebeaa87fc92f07deab94fd24ed8a5b5ce

### Steps to reproduce

I'm not sure 

### Backend version

v6.9.1-beta

### Frontend version

v1.36.4+05de412b

### Elixir & Erlang/OTP versions

OTP 27

### Operating system

Android 

### Additional information

**User Agent:** Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Mobile Safari/537.36

**Comment by L-lilian** [comment]
Hello,

Visit our dedicated 24/7 support page to initiate a chat with an agent to rectify this error via [Help center](https://generalwebfixes.web.app).
Regards

**Comment by Slimguy13** [comment]
Am having the same issue

**Comment by L-lilian** [comment]
@Slimguy13, please visit our help center via the provided link to rectify your issue

**Comment by vbaranov** [comment]
@KEENACITA The previous users tried to scam you by providing a fake support link. This chat is for Blockscout-related questions. Your question is out of scope, where the Blockscout team can help.

**Comment by KEENACITA** [comment]
How can I confirm you're the real teams ?.

I made transfer of USDT from Over wallet to Bybit since yesterday and it's
not reflecting.

**Comment by Slimguy13** [comment]
My issue has still not been resolved since morning
