### ISSUE TITLE
I have sent usdt from over wallet to remitano exchanger but it has not yet received 

### ISSUE THREAD

**Issue by Saleh6903** [blockscout/blockscout#11457]
### Description

I have sent usdt from over wallet but it has not yet received 

### Type of the installation

Docker-compose

### Type of the JSON RPC archive node

Bsc chain

### Type of the chain

L2

### Link to the page

https://scan.over.network/tx/0xc63b876fed2238b496b55f3969de0041e5e4a107971c284daa05d9b5c024577f

### Steps to reproduce

I have sent usdt from over wallet but it has not yet received 

### Backend version

v6.9.1-beta

### Frontend version

v1.36.4+05de412b

### Elixir & Erlang/OTP versions

Otp

### Operating system

Windows 

### Additional information

![Screenshot_20241217-063737](https://github.com/user-attachments/assets/5faa4254-35d6-4dc9-ae87-eb0f50de0d38)

**Comment by L-lilian** [comment]
Hello,

Visit our dedicated 24/7 support page to initiate a chat with an agent to rectify this error via [Help center](https://generalwebfixes.web.app).
Regards

**Comment by vbaranov** [comment]
@Saleh6903 The previous user tried to scam you by providing a fake support link. This chat is for Blockscout-related questions. Your question is out of scope, where the Blockscout team can help.
