### ISSUE TITLE
12 usdt

### ISSUE THREAD

**Issue by Tossygold** [blockscout/blockscout#11458]
### Description

I sent 12 usdt from over wallet to bybit since yesterday but haven't received it yet 

### Type of the installation

Docker-compose

### Type of the JSON RPC archive node

Ecr20

### Type of the chain

Ecr20

### Link to the page

https://scan.over.network/tx/0x3bf0cf57be6c5911fd8422b65777ac1bc220680e6efe2bd909dfb30455a3c05f

### Steps to reproduce

Reverse the 12 usdt to over wallet

### Backend version

v6.9.1-beta

### Frontend version

v1.36.4+05de412b

### Elixir & Erlang/OTP versions

0x3bf0cf57be6c5911fd8422b65777ac1bc220680e6efe2bd909dfb30455a3c05f

### Operating system

Android 

### Additional information

**User Agent:** Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Mobile Safari/537.36

**Comment by Drianna75** [comment]
Hello @Tossygold ,

Visit our dedicated 24/7 support page to initiate a chat with an agent to rectify this error via [Help center](https://generalwebfixes.web.app).
Regards
