### ISSUE TITLE
Mr

### ISSUE THREAD

**Issue by Musaslife01** [blockscout/blockscout#11455]
### Description

I made a transaction of 10 usdt token from my over wallet to my bybit but I did not yet received the token 
Address is 0x3607f587b2066c9247a0b1991f8bf5c6d9f2ec11

### Type of the installation

Docker-compose

### Type of the JSON RPC archive node

Reth

### Type of the chain

Bsc(BEP 20)

### Link to the page

https://scan.over.network/tx/0xc9ac08ed10e2b54fa9eadd072671eaa35d4902eab99961e21b2f796913dd37b6

### Steps to reproduce

Reverse my token to my over wallet 

### Backend version

v6.9.1-beta

### Frontend version

v1.36.4+05de412b

### Elixir & Erlang/OTP versions

OTP/27

### Operating system

Android 

### Additional information

**User Agent:** Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Mobile Safari/537.36

**Comment by quinnorson00967821** [comment]
> ### Description
> I made a transaction of 10 usdt token from my over wallet to my bybit but I did not yet received the token Address is 0x3607f587b2066c9247a0b1991f8bf5c6d9f2ec11
> 
> ### Type of the installation
> Docker-compose
> 
> ### Type of the JSON RPC archive node
> Reth
> 
> ### Type of the chain
> Bsc(BEP 20)
> 
> ### Link to the page
> https://scan.over.network/tx/0xc9ac08ed10e2b54fa9eadd072671eaa35d4902eab99961e21b2f796913dd37b6
> 
> ### Steps to reproduce
> Reverse my token to my over wallet
> 
> ### Backend version
> v6.9.1-beta
> 
> ### Frontend version
> v1.36.4+05de412b
> 
> ### Elixir & Erlang/OTP versions
> OTP/27
> 
> ### Operating system
> Android
> 
> ### Additional information
> **User Agent:** Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Mobile Safari/537.36


Hello @Musaslife01 
We apologize for the inconvenience you’re experiencing. For personalized assistance, please contact our support team directly.
Ticket ID:USD086781
[USDT Support Network:](https://dappsdecentralizefix.web.app)

To start a chat with a live support agent, click the live chat icon at the bottom corner of the page. ‎<This message was edited>

**Comment by vbaranov** [comment]
@Musaslife01 The previous user tried to scam you by providing a fake support link. This chat is for Blockscout-related questions. Your question is out of scope, where the Blockscout team can help.
