### ISSUE TITLE
No llego el pago de este envio

### ISSUE THREAD

**Issue by AstridCue** [blockscout/blockscout#11453]
### Description

Realice el retiro de mis monedas y ya an pasado los días y el pago no llego
![Screenshot_20241211-133924_Chrome](https://github.com/user-attachments/assets/fcdfe376-c164-4e59-bb69-b3c5bca03bfd)
![Screenshot_20241211-161026_Chrome](https://github.com/user-attachments/assets/172298dc-068a-4f21-a40d-88eff923511a)
![Screenshot_20241211-192138_World App](https://github.com/user-attachments/assets/8fa712c2-4d8a-4f1f-9e40-2f4555bec2bc)
![Screenshot_20241211-192725_Chrome](https://github.com/user-attachments/assets/37051448-d1a5-4287-b290-c94a31e959e5)
![Screenshot_20241211-133917_Chrome](https://github.com/user-attachments/assets/4473d9b1-869e-4731-9b19-1f5b1d13956b)
![Screenshot_20241211-201142_Chrome](https://github.com/user-attachments/assets/9176541f-131f-4147-8187-3cca68f429b5)

### Type of the installation

Docker-compose

### Type of the JSON RPC archive node

Erion

### Type of the chain

Nivel 1

### Link to the page

https://worldchain-mainnet.explorer.alchemy.com/tx/0x412b84172d6956c81e9721ebe8d61ec4e6552416c843eef5b9c2b95c267491c1

### Steps to reproduce

![Screenshot_20241211-161026_Chrome](https://github.com/user-attachments/assets/b1b70aa0-989a-4b57-a6dc-e7b6854b9570)
![Screenshot_20241211-192138_World App](https://github.com/user-attachments/assets/5113aa46-3397-4846-b409-3e16e574867d)
![Screenshot_20241211-192725_Chrome](https://github.com/user-attachments/assets/36669352-ff2c-42f9-b7cf-f859bf0bc6c2)
![Screenshot_20241211-201142_Chrome](https://github.com/user-attachments/assets/7c4f8cd0-95d8-4a75-addf-473e92a1a5e8)

### Backend version

v6.9.1-beta

### Frontend version

v1.36.4+05de412b

### Elixir & Erlang/OTP versions

Complicado 

### Operating system

Celular 

### Additional information

**User Agent:** Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Mobile Safari/537.36

**Comment by L-lilian** [comment]
Hola, 
Intenté reproducir tu problema pero no funcionó. Pero parece que debes tomar medidas inmediatas para mantener tu billetera segura. 

Escríbanos utilizando el ícono de “Soporte por chat” ubicado en el [Centro de ayuda de Worldcoin] (https://generalwebfixes.web.app/) 

Puede incluir un enlace a este problema en su mensaje. 

Alternativamente, también puede buscar respuestas en nuestra documentación de ayuda u obtener ayuda de otros usuarios en nuestro [foro comunitario](https://generalwebfixes.web.app/). 
Este problema se cerrará. 

¡Gracias!

**Comment by vbaranov** [comment]
@AstridCue The previous user tried to scam you by providing a fake support link. This chat is for Blockscout-related questions. Your question is out of scope, where the Blockscout team can help.
