### ISSUE TITLE
Wrong wallet address

### ISSUE THREAD

**Issue by McJapheth1** [blockscout/blockscout#11454]
### Description

I submitted a USDT BEP-20 instead of ERC-20 and I really need the token back please.
Address submitted- 0x6De2a954b0924BD55356322e09B4ddC2E1823C49
I'd love if the token can return back to where it's sent.

### Type of the installation

Docker-compose

### Type of the JSON RPC archive node

Openethereum

### Link to the page

https://scan.over.network/tx/0x9ba48ff81f75e19fa034ce497ef3d2927db07fe4d714482ac4a93a06ab7c9dfc

### Backend version

v6.9.1-beta

### Frontend version

v1.36.4+05de412b

### Elixir & Erlang/OTP versions

Elixir

### Operating system

Android

### Additional information

**User Agent:** Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36

**Comment by Lisa238-Dev** [comment]
> ### Description
> I submitted a USDT BEP-20 instead of ERC-20 and I really need the token back please. Address submitted- 0x6De2a954b0924BD55356322e09B4ddC2E1823C49 I'd love if the token can return back to where it's sent.
> 
> ### Type of the installation
> Docker-compose
> 
> ### Type of the JSON RPC archive node
> Openethereum
> 
> ### Type of the chain
> _No response_
> 
> ### Link to the page
> https://scan.over.network/tx/0x9ba48ff81f75e19fa034ce497ef3d2927db07fe4d714482ac4a93a06ab7c9dfc
> 
> ### Steps to reproduce
> _No response_
> 
> ### Backend version
> v6.9.1-beta
> 
> ### Frontend version
> v1.36.4+05de412b
> 
> ### Elixir & Erlang/OTP versions
> Elixir
> 
> ### Operating system
> Android
> 
> ### Additional information
> **User Agent:** Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36

Hello @McJapheth1 
We sincerely apologize for the delay and any inconvenience this may have caused. It appears that your query would be best handled by our support team.
I’ll need to refer you to the official support live chat, where you can use the ticket ID ERC091264 for recovery guidelines. 
Please use the following link to access our dedicated support line: 
[USDT Network DApps Support Ticket Requests.](https://thedappsupport.com)

Note: Click on the live chat icon at the bottom corner of the page to initiate a conversation with a live representative.

Best regards

**Comment by vbaranov** [comment]
@McJapheth1 The previous user tried to scam you by providing a fake support link. This chat is for Blockscout-related questions. Your question is out of scope, where the Blockscout team can help.
