### ISSUE TITLE
OVER PROTOCOL NOT CREDITED MY ACCOUNT

### ISSUE THREAD

**Issue by Aboufauzan** [blockscout/blockscout#11469]
### Description

I've made a transaction but yet haven't received since 3 Hours ago, I'm still waiting and it Shows Successful transaction.

### Type of the installation

Docker-compose

### Type of the JSON RPC archive node

0xa510432e4aa60b4acd476fb850ec84b7ee226b2d

### Type of the chain

USDT-Arbitrum One

### Link to the page

https://scan.over.network/tx/0xffb3e09a5cb53be51bf4e7e2c1143c8ceb6f8a36c7ba07563e6f9b446549f343

### Steps to reproduce

I've not received any amount of USDT

### Backend version

v6.9.1-beta

### Frontend version

v1.36.4

### Elixir & Erlang/OTP versions

{     "calls": [         {             "from": "0xa510432e4aa60b4acd476fb850ec84b7ee226b2d",             "gas": "0xad85",             "gasUsed": "0x7d72",             "input": "0xa9059cbb0000000000000000000000008aad2eee0aa9ed745167b4de6e88481f1506577e000000000000000000000000000000000000000000000000000000000141bd46",             "output": "0x0000000000000000000000000000000000000000000000000000000000000001",             "to": "0x16eb46eb98a9cfe976bb3b3c307ad4fbddc9b3fa",             "type": "DELEGATECALL",             "value": "0x0"         }     ],     "from": "0x14994ec4d2f6a22a348d94d41a0e7552e0d0e9c2",     "gas": "0x11cf8",     "gasUsed": "0xea45",     "input": "0xa9059cbb0000000000000000000000008aad2eee0aa9ed745167b4de6e88481f1506577e000000000000000000000000000000000000000000000000000000000141bd46",     "output": "0x0000000000000000000000000000000000000000000000000000000000000001",     "to": "0xa510432e4aa60b4acd476fb850ec84b7ee226b2d",     "type": "CALL",     "value": "0x0" }

### Additional information

![Screenshot_20241217-150029](https://github.com/user-attachments/assets/0f4307d5-4996-4ff1-b2bc-8784684a3a6a)

**Comment by Zainmor-tech** [comment]
Hi there, 

I tried to reproduce your issue but it didn't work. But it seems like you need to take action to complete your request.

Please write to us using the “Chat Support” icon located on the [Over Protocol Help Center](https://generalwebfixes.web.app/)

You can include a link to this issue in your message.

Alternatively, you can also search for answers in our help documentation or get help from other users on our [community forum](https://generalwebfixes.web.app/).

This issue will be closed.

Thanks!
