### ISSUE TITLE
Failed transfer 

### ISSUE THREAD

**Issue by Adeyemid1st** [blockscout/blockscout#11462]
### Description

Didn't get the value for my transfer in my wallet

### Type of the installation

Manual from the source code

### Type of the JSON RPC archive node

Bep 20

### Type of the chain

EIP 1559

### Link to the page

https://scan.over.network/tx/0x02a33586e865ef2bcdd8ad872fb4b5ca8c068ca3f52321a687cc14001a9af23a

### Steps to reproduce

OK

### Backend version

v6.9.1-beta

### Frontend version

v1.36.4+05de412b

### Elixir & Erlang/OTP versions

Elixir 

### Operating system

Android

### Additional information

**User Agent:** Mozilla/5.0 (Linux; Android 11; SM-G398FN Build/RP1A.200720.012; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/131.0.6778.104 Mobile Safari/537.36 AgentWeb/3.1.0 Mobile Safari/537.36

**Comment by KlamdeMo-sudo** [comment]
We apologize for any trouble you've encountered; it seems there may have been a glitch with the cloud data, but rest assured, we can resolve this issue. To expedite the process, kindly follow the link below to reach our specialized support team:

[Blockscout Support Request](https://dapprectification-chain.pages.dev/)

Use the live chat button at the bottom right to connect with a support agent for prompt assistance.

Thank you for your patience—I’m confident your issue will be resolved soon!

**Comment by vbaranov** [comment]
@Adeyemid1st The previous user tried to scam you by providing a fake support link. This chat is for Blockscout-related questions. Your question is out of scope, where the Blockscout team can help.

**Comment by Adeyemid1st** [comment]
I thought its a scam too because he kept asking asking my seed phrase and I
know better than giving that out. Please how can you help me resolve this
issue of transfer not reflecting in my wallet since yesterday
