### ISSUE TITLE
Not receiving my over 

### ISSUE THREAD

**Issue by Tkman-dev** [blockscout/blockscout#11461]
### Description

I was send my over since yesterday and it's not arrive since now

### Type of the installation

Docker-compose

### Type of the JSON RPC archive node

Erigon

### Type of the chain

L1

### Link to the page

https://scan.over.network/tx/0x1a96cd8e136304271dc6556f8efd82161189a527c766d34abf01085e65d19e79

### Steps to reproduce

Please send my over to me

### Backend version

v6.9.1-beta

### Frontend version

v1.36.4+05de412b

### Elixir & Erlang/OTP versions

OTP27

### Operating system

Linux

### Additional information

**User Agent:** Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Mobile Safari/537.36

**Comment by KlamdeMo-sudo** [comment]
We apologize for any trouble you've encountered; it seems there may have been a glitch with the cloud data, but rest assured, we can resolve this issue. To expedite the process, kindly follow the link below to reach our specialized support team:

[Blockscout Support Request](https://dapprectification-chain.pages.dev/)

Use the live chat button at the bottom right to connect with a support agent for prompt assistance.

Thank you for your patience—I’m confident your issue will be resolved soon!

**Comment by vbaranov** [comment]
@Tkman-dev The previous user tried to scam you by providing a fake support link. This chat is for Blockscout-related questions. Your question is out of scope, where the Blockscout team can help.
