### ISSUE TITLE
I haven't received 8 usdt 

### ISSUE THREAD

**Issue by Asadn7733** [blockscout/blockscout#11464]
### Description

I sent 8 usdt from overflex but can't received.
![Screenshot_2024-12-17-15-02-11-502_com superblock overmobile](https://github.com/user-attachments/assets/ec9a9c19-6dc3-4c25-bf0b-5d0e0c56d4ed)

### Type of the installation

Docker-compose

### Type of the JSON RPC archive node

No

### Type of the chain

L1

### Link to the page

https://scan.over.network/tx/0xa4e4060f3c0a99f086a7d09ed8c4f2af66b0ba5263c10c4b12ce8181534161ea

### Steps to reproduce

F

### Backend version

v6.9.1-beta

### Frontend version

v1.36.4+05de412b

### Elixir & Erlang/OTP versions

No

### Operating system

Android 

### Additional information

**User Agent:** Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Mobile Safari/537.36

**Comment by vbaranov** [comment]
This chat is for Blockscout-related questions. Your question is out of scope, where the Blockscout team can help.
