### ISSUE TITLE
I mistakenly send to wrong Blockchain please reverse my usdt

### ISSUE THREAD

**Issue by Abumysab** [blockscout/blockscout#11463]
### Description

I mistakely send my usdt eth to usdt arb address please help me reverse my usdt please 

### Type of the installation

Docker-compose

### Type of the JSON RPC archive node

Erigon

### Type of the chain

L2

### Link to the page

https://scan.over.network/tx/0xa0c34d52986db228786ef011aa1235c81b0f5fb4f6bd785de391323be2156933

### Steps to reproduce

Please reverse my usdt or send it as usdt arb to the provided address 0x7867e66f9A0d83E4a71B012b95b8bCE7AdE33D79

### Backend version

v6.9.1-beta

### Frontend version

v1.36.4+05de412b

### Elixir & Erlang/OTP versions

Elexi 1.27.3

### Operating system

Phone

### Additional information

**User Agent:** Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Mobile Safari/537.36

**Comment by vbaranov** [comment]
This chat is for Blockscout-related questions. Your question is out of scope, where the Blockscout team can help.
