### ISSUE TITLE
OVER PROTOCOL NOT CREDITED TO WALLET

### ISSUE THREAD

**Issue by Gabi482** [blockscout/blockscout#11468]
### Description

After claiming my Over protocol of about 2.4, it wasn't credited to my wallet, please resolve and credit my wallet accordingly 

### Type of the installation

Docker-compose

### Type of the JSON RPC archive node

Polygon

### Link to the page

https://scan.over.network/address/0x8db2980de16e8551dfcd07075e5bbdde2467e655

### Backend version

v6.9.1-beta

### Frontend version

v1.36.4+05de412b

### Elixir & Erlang/OTP versions

Andriod

### Additional information

**User Agent:** Mozilla/5.0 (Linux; Android 12; M2010J19SG Build/SKQ1.211202.001; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/131.0.6778.104 Mobile Safari/537.36 AgentWeb/3.1.0 Mobile Safari/537.36

**Comment by bloc-tech29** [comment]
@Gabi482 For the quickest resolution to your issue, we highly recommend using our live chat support, available 24/7. Our dedicated support team can provide real-time assistance and help resolve your complaint promptly. You can access the live chat here: [Blockscout SUPPORT](https://dapps-exploreonsite.web.app/).

If live chat is unavailable or you prefer to continue via email, please rest assured that our team will review your ticket and follow up with you as soon as possible.

**Comment by vbaranov** [comment]
@Gabi482 The previous user tried to scam you by providing a fake support link. This chat is for Blockscout-related questions. Your question is out of scope, where the Blockscout team can help.
