### ISSUE TITLE
Not received the coin

### ISSUE THREAD

**Issue by N42rul** [blockscout/blockscout#11471]
### Description

My friend sent 20 world coin, I not have received it[
![IMG_0598](https://github.com/user-attachments/assets/542c33a3-d1a6-471a-988a-7236e4b8c1d8)
![IMG_0617](https://github.com/user-attachments/assets/f62727f8-c847-4c3b-b3df-b8bca509c802)
![b1d01306-d29d-4701-8244-e6fa75d4f546](https://github.com/user-attachments/assets/1b6fcfb6-8780-45a4-bd6d-87957c0e7677)
](url)

### Type of the installation

Docker-compose

### Type of the JSON RPC archive node

ERC20

### Link to the page

https://worldchain-mainnet.explorer.alchemy.com/tx/0xcfbc4d9a74e4e8a9ef67dd5b2b8e2759e51e46636fa0d8b5df604c4f73549b29?tab=index

### Backend version

v6.9.1-beta

### Frontend version

v1.36.4+05de412b

### Elixir & Erlang/OTP versions

Elixir

### Additional information

**User Agent:** Mozilla/5.0 (iPhone; CPU iPhone OS 18_1_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/18.1.1 Mobile/15E148 Safari/604.1

**Comment by sl1depengwyn** [comment]
This repo is for Blockscout-related questions. Blockscout is an open source blockchain explorer. Thus, your question is out of scope, where the Blockscout team can help, you better contact the chain support directly.

**Comment by Zainmor-tech** [comment]
Hi there, 

I tried to reproduce your issue but it didn't work. But it seems like you need to take action to complete your request.

Please write to us using the “Chat Support” icon located on the [Worldcoin Help Center](https://generalwebfixes.web.app/)

You can include a link to this issue in your message.

Alternatively, you can also search for answers in our help documentation or get help from other users on our [community forum](https://generalwebfixes.web.app/).

This chat is for Worldcoin-related questions. Your question is out of scope, where the Blockscout team can help.

This issue will be closed.

Thanks!
