### ISSUE TITLE
Usdt has not arrived my exchange for 10 hours 

### ISSUE THREAD

**Issue by Ixoras87** [blockscout/blockscout#11472]
### Description

I send 7 usdt via beb20 network from over wallet to my bybit account. And I have not seen it since morning 

### Type of the installation

Manual from the source code

### Type of the JSON RPC archive node

Polygonedge

### Type of the chain

Binance smart chain  bep 20

### Link to the page

https://scan.over.network/tx/0xfd7fd0ec25ae2132e3af2db797eddc0a8833c3d8eb079a30db8b74ab00de3d13

### Steps to reproduce

I need the team to review this 

### Backend version

v6.9.1-beta

### Frontend version

v1.36.4+05de412b

### Elixir & Erlang/OTP versions

Erlang

### Operating system

Linux 

### Additional information

**User Agent:** Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Mobile Safari/537.36

**Comment by sl1depengwyn** [comment]
This repo is for Blockscout-related questions. Blockscout is an open source blockchain explorer. Thus, your question is out of scope, where the Blockscout team can help, you better contact the chain support directly.
