### ISSUE TITLE
PROBLEMA CON UNA TRANSFERENCIA

### ISSUE THREAD

**Issue by Nicolas0303** [blockscout/blockscout#11470]
### Description

REALICE UNA TRANSACCIÓN DESDE DICIEMBRE 08 - 2024 A LAS 9:49 DE LA MAÑANA POR UN VALOR DE 277.931 PESOS  CON EL HASH SE LA TRANSACCIÓN 0xce57d7ef5d6f98cdc5b58ef2d7e3a05b629ebd3a692262d761c0f35540043018  Y HASTA LA FECHA AUN NO HE RECIBIDO EL PAGO A MI CUENTA, AGRADEZCO PRONTA SOLUCIÓN CON ESTE PROBLEMA, GRACIAS .

### Type of the installation

Docker-compose

### Type of the JSON RPC archive node

World Coín 

### Type of the chain

1

### Link to the page

https://worldchain-mainnet.explorer.alchemy.com/tx/0xce57d7ef5d6f98cdc5b58ef2d7e3a05b629ebd3a692262d761c0f35540043018

### Steps to reproduce

X

### Backend version

v6.9.1-beta

### Frontend version

v1.36.4+05de412b

### Elixir & Erlang/OTP versions

World Coín 

### Operating system

World Coín 

### Additional information

![Screenshot_2024-12-10-20-27-22-794_com worldcoin](https://github.com/user-attachments/assets/10b6ffee-a6c8-41d2-8757-fa968260906e)

**Comment by sl1depengwyn** [comment]
This repo is for Blockscout-related questions. Blockscout is an open source blockchain explorer. Thus, your question is out of scope, where the Blockscout team can help, you better contact the chain support directly.
