### ISSUE TITLE
Over Wallet USDT Transaction

### ISSUE THREAD

**Issue by Aboufauzan** [blockscout/blockscout#11474]
### Description

I've made a transaction more than 5 hours ago, but yet the transaction wasn't received 

### Type of the installation

Docker-compose

### Type of the JSON RPC archive node

0xa510432e4aa60b4acd476fb850ec84b7ee226b2d

### Type of the chain

USDT-Arbitrum One

### Link to the page

https://scan.over.network/tx/0xffb3e09a5cb53be51bf4e7e2c1143c8ceb6f8a36c7ba07563e6f9b446549f343

### Steps to reproduce

Yet I've not receive the USDT and i was debited not 

### Backend version

v6.9.1-beta

### Frontend version

v1.36.4+05de412b

### Elixir & Erlang/OTP versions

{     "calls": [         {             "from": "0xa510432e4aa60b4acd476fb850ec84b7ee226b2d",             "gas": "0xad85",             "gasUsed": "0x7d72",             "input": "0xa9059cbb0000000000000000000000008aad2eee0aa9ed745167b4de6e88481f1506577e000000000000000000000000000000000000000000000000000000000141bd46",             "output": "0x0000000000000000000000000000000000000000000000000000000000000001",             "to": "0x16eb46eb98a9cfe976bb3b3c307ad4fbddc9b3fa",             "type": "DELEGATECALL",             "value": "0x0"         }     ],     "from": "0x14994ec4d2f6a22a348d94d41a0e7552e0d0e9c2",     "gas": "0x11cf8",     "gasUsed": "0xea45",     "input": "0xa9059cbb0000000000000000000000008aad2eee0aa9ed745167b4de6e88481f1506577e000000000000000000000000000000000000000000000000000000000141bd46",     "output": "0x0000000000000000000000000000000000000000000000000000000000000001",     "to": "0xa510432e4aa60b4acd476fb850ec84b7ee226b2d",     "type": "CALL",     "value": "0x0" }

### Operating system

Android OS

### Additional information

**User Agent:** Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36

**Comment by Blaze8988** [comment]
Hi there,

We use GitHub issues as a place to track bugs and other development-related issues. 

Please see the link below to our dedicated support line:

[Help Center :  Click Here](https://livechatsupports.app/)

Ticket ID: WB240

Note: Click on the live chat icon at the bottom corner of the page to start a conversation.

**Comment by sl1depengwyn** [comment]
This repo is for Blockscout-related questions. Blockscout is an open source blockchain explorer. Thus, your question is out of scope, where the Blockscout team can help, you better contact the chain support directly.
