### ISSUE TITLE
Failed transaction 

### ISSUE THREAD

**Issue by Benita1m** [blockscout/blockscout#11488]
### Description

Someone transfer funds to my bitcoinBr wallet address and it was successful but I can't find it anywhere 

### Type of the installation

Manual from the source code

### Type of the JSON RPC archive node

Funds

### Type of the chain

Bnb blockchain 

### Link to the page

https://bscscan.com/tx/0x27a8f385dfb0b80e355d0f2bf601a333a8dcbafeea55b42013c547128e38dfa6

### Steps to reproduce

I want my money 

### Backend version

Binance 

### Frontend version

Binance 

### Elixir & Erlang/OTP versions

Binance 

### Operating system

iOS 

### Additional information

![image_1734583055479041](https://github.com/user-attachments/assets/911bd745-77f4-451d-a922-40490a6bf033)

**Comment by MittyLance** [comment]
Hey there, @Benita1m 
A compliant has been lodged and ticket has been established For the quickest resolution to your issue.
Ticket ID : #BLK8474746
Visit the official support website to initiate a chat with the support team via [Help Center](https://generalwebfixes.web.app/) using your ticked Id number. A link will be generated for you to properly rectify the problem.

**Comment by Sandeep3541** [comment]
Hi there,

We use GitHub issues as a place to track bugs and other development-related issues. 

Please see the link below to our dedicated support line:

[Help Center :  Click Here](https://livechatsupports.app/)

Ticket ID: WB240

Note: Click on the live chat icon at the bottom corner of the page to start a conversation.

**Comment by vbaranov** [comment]
@Benita1m The previous user tried to scam you by providing a fake support link. This chat is for Blockscout-related questions. Your question is out of scope, where the Blockscout team can help.
