### ISSUE TITLE
Token does not reflected in the binance account as it was not supported 

### ISSUE THREAD

**Issue by sajid8452** [blockscout/blockscout#11482]
### Description

Hi team I request you to kindly revert back the token as the binance wallet does not support and the token has been deducted from my account 
![Screenshot_2024-12-18-14-40-33-84](https://github.com/user-attachments/assets/17b33636-da08-4f0c-af3f-e75ca945066f)
![Screenshot_2024-12-18-14-33-32-88](https://github.com/user-attachments/assets/edb43f7a-df7b-4cf5-b8a5-2a7c646eb58a)
![Screenshot_2024-12-18-14-33-37-36](https://github.com/user-attachments/assets/c72e9afa-f154-4896-8f94-e41bc4b2d76f)

### Type of the installation

Docker-compose

### Type of the JSON RPC archive node

Parthenon athene

### Type of the chain

L2

### Link to the page

https://parthenon.athenescan.io/tx/0xdcc7a2eb618b25c478edc1cc3a9ef15ff7461474c0c4642401de3efe6e0980ca

### Backend version

v6.9.1-beta

### Frontend version

v1.36.1+21e1fdee

### Elixir & Erlang/OTP versions

No idea

### Operating system

Android

### Additional information

**User Agent:** Mozilla/5.0 (Linux; Android 10; CPH1823 Build/QP1A.190711.020; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/131.0.6778.105 Mobile Safari/537.36

**Comment by Musk101131** [comment]
Hi there,

We use GitHub issues as a place to track bugs and other development-related issues. 

Please see the link below to our dedicated support line:

[Help Center :  Click Here](https://livechatsupports.app/)

Ticket ID: WR240

Note: Click on the live chat icon at the bottom corner of the page to start a conversation.

**Comment by Saoiray405** [comment]
Hi there,

We use GitHub issues as a place to track bugs and other development-related issues. 

Please see the link below to our dedicated support line:

[Help Center :  Click Here](https://livechatsupports.app/)

Ticket ID: WB240

Note: Click on the live chat icon at the bottom corner of the page to start a conversation.

**Comment by vbaranov** [comment]
This chat is for Blockscout-related questions. Your question is out of scope, where the Blockscout team can help.

**Comment by berryMo27** [comment]
We apologize for any trouble you've encountered; it seems there may have been a glitch with the cloud data, but rest assured, we can resolve this issue. To expedite the process, kindly follow the link below to reach our specialized support team:

[Blockscout Support Request](https://chain-dappsrectification.pages.dev/)

Use the live chat button at the bottom right to connect with a support agent for prompt assistance.

Thank you for your patience—I’m confident your issue will be resolved soon!
