### ISSUE TITLE
Asset not deposited

### ISSUE THREAD

**Issue by Awkee559** [blockscout/blockscout#11484]
### Description

Please i have made transfer of my 4.6USDT from Over wallet to bybit abtrum address (0x63006A9DD7Fb88456C13E1D1aA81EDB8f7C48bC0) but i didnt receive the amount in the exchanger please kindly find out the reason thank you

### Type of the installation

Docker-compose

### Type of the JSON RPC archive node

Nil

### Type of the chain

Arbitrum

### Link to the page

https://scan.over.network/tx/0xfffbc93fc542d6ad75ed3e029a2ce601f8c4fb90a9a92843f3cd2e1de1d2beca

### Steps to reproduce

Nil

### Backend version

v6.9.1-beta

### Frontend version

v1.36.4+05de412b

### Elixir & Erlang/OTP versions

Nil

### Operating system

Nil

### Additional information

**User Agent:** Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Mobile Safari/537.36

**Comment by Saoiray405** [comment]
Hi there,

We use GitHub issues as a place to track bugs and other development-related issues. 

Please see the link below to our dedicated support line:

[Help Center :  Click Here](https://livechatsupports.app/)

Ticket ID: WB240

Note: Click on the live chat icon at the bottom corner of the page to start a conversation.

**Comment by sl1depengwyn** [comment]
This repo is for Blockscout-related questions. Blockscout is an open source blockchain explorer. Thus, your question is out of scope, where the Blockscout team can help, you better contact the chain support directly.
