### ISSUE TITLE
Translation issues 

### ISSUE THREAD

**Issue by Sadikumar123** [blockscout/blockscout#11489]
### Description

[](url)
![IMG_0167](https://github.com/user-attachments/assets/57d794fa-abb1-4386-857e-5e02c24b3531)

### Type of the installation

Docker-compose

### Type of the JSON RPC archive node

0xccd43dd4896c6ce4a5b84f37f6ee457f767a543a

### Type of the chain

0xccd43dd4896c6ce4a5b84f37f6ee457f767a543a

### Link to the page

https://scan.over.network/tx/0xfca179922c3583a4f7c99e9d6f0cc5fff2046444bc35165a5ad2d8995f1ef04a

### Steps to reproduce

![IMG_0167](https://github.com/user-attachments/assets/fcac30bf-c1a7-4a3b-8d21-663b6c92d39e)

### Backend version

v6.9.1-beta

### Frontend version

v1.36.4+05de412b

### Elixir & Erlang/OTP versions

0.9

### Operating system

Translation issues 

### Additional information

**User Agent:** Mozilla/5.0 (iPhone; CPU iPhone OS 18_2 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/18.2 Mobile/15E148 Safari/604.1

**Comment by vbaranov** [comment]
This chat is for Blockscout-related questions. Your question is out of scope, where the Blockscout team can help.
