### ISSUE TITLE
ASSETS STUCK 

### ISSUE THREAD

**Issue by SHEERAZ1988** [blockscout/blockscout#11487]
### Description

I have sent a assets from meta mask to bitget exchange,but the transaction has stuck,and I have not received in bitget exchange 
![Screenshot_2024-12-19-07-14-06-200_io metamask](https://github.com/user-attachments/assets/f1a3e073-5c61-44d8-bfa1-7c38c4e6e93a)

### Type of the installation

Docker

### Type of the JSON RPC archive node

ERC

### Type of the chain

L1

### Link to the page

https://parthenon.athenescan.io/tx/0x7dbf9861670228c1d098f3053bcbcb6aac015cb145d61c2e235a7e48f3ec4508

### Backend version

v10.0

### Frontend version

v1.36.1+21e1fdee

### Elixir & Erlang/OTP versions

Android 

### Additional information

**User Agent:** Mozilla/5.0 (Linux; Android 12; Redmi Note 9 Pro Max Build/SKQ1.211019.001; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/131.0.6778.104 Mobile Safari/537.36

**Comment by vbaranov** [comment]
This chat is for Blockscout-related questions. Your question is out of scope, where the Blockscout team can help.
