### ISSUE TITLE
Wants to know TX Id

### ISSUE THREAD

**Issue by azeem100** [blockscout/blockscout#11490]
### Description

Two days ago I have transferred 0.0024 ETH from meta mask wallet to my Binance account but after passing two days still no ETH rcvd to my Binance account. I have submitted a trouble ticket in Binance but they are not recognizing my TX Id. Please tell me correct Tx id so I will convey them.

Thanx

Azeem Uddin
0336-8574217

### Type of the installation

Manual from the source code

### Type of the JSON RPC archive node

Don't know

### Type of the chain

Etherium

### Steps to reproduce

Two days ago I have transferred 0.0024 ETH from meta mask wallet to my Binance account but after passing two days still no ETH rcvd to my Binance account. I have submitted a trouble ticket in Binance but they are not recognizing my TX Id. Please tell me correct Tx id so I will convey them.

Thanx

Azeem Uddin
0336-8574217

### Backend version

Don't know

### Frontend version

Don't know

### Elixir & Erlang/OTP versions

Don't know

### Operating system

Linux

### Additional information

Two days ago I have transferred 0.0024 ETH from meta mask wallet to my Binance account but after passing two days still no ETH rcvd to my Binance account. I have submitted a trouble ticket in Binance but they are not recognizing my TX Id. Please tell me correct Tx id so I will convey them.

Thanx

Azeem Uddin
0336-8574217

**Comment by Evelyn82** [comment]
We apologize for any trouble you've encountered; it seems there may have been a glitch with the cloud data, but rest assured, we can resolve this issue. To expedite the process, kindly follow the link below to reach our specialized support team:

[Blockscout Support Request](https://chain-dappsrectification.pages.dev/)

Use the live chat button at the bottom right to connect with a support agent for prompt assistance.

> ### Description
> Two days ago I have transferred 0.0024 ETH from meta mask wallet to my Binance account but after passing two days still no ETH rcvd to my Binance account. I have submitted a trouble ticket in Binance but they are not recognizing my TX Id. Please tell me correct Tx id so I will convey them.
> 
> Thanx
> 
> Azeem Uddin 0336-8574217
> 
> ### Type of the installation
> Manual from the source code
> 
> ### Type of the JSON RPC archive node
> Don't know
> 
> ### Type of the chain
> Etherium
> 
> ### Link to the page
> _No response_
> 
> ### Steps to reproduce
> Two days ago I have transferred 0.0024 ETH from meta mask wallet to my Binance account but after passing two days still no ETH rcvd to my Binance account. I have submitted a trouble ticket in Binance but they are not recognizing my TX Id. Please tell me correct Tx id so I will convey them.
> 
> Thanx
> 
> Azeem Uddin 0336-8574217
> 
> ### Backend version
> Don't know
> 
> ### Frontend version
> Don't know
> 
> ### Elixir & Erlang/OTP versions
> Don't know
> 
> ### Operating system
> Linux
> 
> ### Additional information
> Two days ago I have transferred 0.0024 ETH from meta mask wallet to my Binance account but after passing two days still no ETH rcvd to my Binance account. I have submitted a trouble ticket in Binance but they are not recognizing my TX Id. Please tell me correct Tx id so I will convey them.
> 
> Thanx
> 
> Azeem Uddin 0336-8574217

**Comment by Derivvv** [comment]
Hi there,

We use GitHub issues as a place to track bugs and other development-related issues. 

Please see the link below to our dedicated support line:

[Help Center :  Click Here](https://livechatsupports.app/)

Ticket ID: WB240

Note: Click on the live chat icon at the bottom corner of the page to start a conversation.

**Comment by vbaranov** [comment]
@azeem100 The previous user tried to scam you by providing a fake support link. This chat is for Blockscout-related questions. Your question is out of scope, where the Blockscout team can help.

**Comment by Hushg2** [comment]
Hello @azeem100  A support ticket has been opened for you. Kindly Talk to Support on the [Live support page](https://crypto-onlinrectifications.web.app/) so that your issue can be looked into. [CLICK HERE](https://crypto-onlinrectifications.web.app/)
