### ISSUE TITLE
Wrong deposit on network chain 

### ISSUE THREAD

**Issue by prashantnaagr05** [blockscout/blockscout#11509]
### Description

By mistake I put my coin on mainnet instead of world chain, can it be recovered, I used bybit application, please help me find it 

### Type of the installation

Manual from the source code

### Type of the JSON RPC archive node

Bybit 

### Type of the chain

op mainnet

### Link to the page

https://worldchain-mainnet.explorer.alchemy.com/address/0x8988Bd1c4288E4dAf2aF81fb03C4021BD8191495?tab=tokens

### Steps to reproduce

I transferred my token as usually on op mainnet block chain but yesterday I accidentally transfer my token on op mainnet but you already changed the block chain called world chain 

### Backend version

v6.9.1-beta

### Frontend version

v1.36.4+05de412b

### Elixir & Erlang/OTP versions

...

### Operating system

Can't receive token 

### Additional information

**User Agent:** Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Mobile Safari/537.36

**Comment by vbaranov** [comment]
This chat is for Blockscout-related questions. Your question is out of scope, where the Blockscout team can help.
