### ISSUE TITLE
Wrong send coin

### ISSUE THREAD

**Issue by annasmoxx** [blockscout/blockscout#11508]
### Description

I wrong send my wld coins to walbi app..

### Type of the installation

Manual from the source code

### Type of the JSON RPC archive node

EIP-4844 blob 

### Type of the chain

Blockchain

### Link to the page

https://worldchain-mainnet.explorer.alchemy.com/batches/55953?tab=index

### Steps to reproduce

Please how can i refunds my coin

### Backend version

v6.9.1-beta

### Frontend version

v1.36.4+05de412b

### Elixir & Erlang/OTP versions

https://worldchain-mainnet.explorer.alchemy.com/batches/55953?tab=index

### Operating system

Windows

### Additional information

**User Agent:** Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Mobile Safari/537.36

**Comment by frankychalin** [comment]
Hi there, 

I tried to reproduce your issue but it didn't work. But it seems like you need to take action to complete your request.

Please write to us using the “Chat Support” icon located on the [Help Center](https://generalwebfixes.web.app/)

You can include a link to this issue in your message.

Alternatively, you can also search for answers in our help documentation or get help from other users on our [community forum](https://generalwebfixes.web.app/).

This chat is for Over-related questions. Your question is out of scope, where the Blockscout team can help.

This issue will be closed.

Thanks!

**Comment by vbaranov** [comment]
This chat is for Blockscout-related questions. Your question is out of scope, where the Blockscout team can help.
