### ISSUE TITLE
usdt not receved 

### ISSUE THREAD

**Issue by NirajanBist393** [blockscout/blockscout#11507]
### Description

![Screenshot_2024-12-20-08-48-55-412_com superblock overmobile](https://github.com/user-attachments/assets/ef465065-2b0b-44a3-82bb-7a80df15e3f9)
 not receved usdt

### Type of the installation

Docker

### Type of the JSON RPC archive node

Arb

### Type of the chain

Usdt

### Link to the page

https://scan.over.network/tx/0x86c7356e502ea1e23e6c80d03e695ce687bd00322efdd59655502d198606f07f

### Backend version

v6.9.1-beta

### Frontend version

v1.37.0-alpha.1+79ab2272

### Elixir & Erlang/OTP versions

not receved 

### Operating system

usdt not receved 

### Additional information

**User Agent:** Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/127.0.0.0 Mobile Safari/537.36

**Comment by frankychalin** [comment]
Hi there, 

I tried to reproduce your issue but it didn't work. But it seems like you need to take action to complete your request.

Please write to us using the “Chat Support” icon located on the [Overnetwork Help Center](https://generalwebfixes.web.app/)

You can include a link to this issue in your message.

Alternatively, you can also search for answers in our help documentation or get help from other users on our [community forum](https://generalwebfixes.web.app/).

This chat is for Over-related questions. Your question is out of scope, where the Blockscout team can help.

This issue will be closed.

Thanks!

**Comment by vbaranov** [comment]
This chat is for Blockscout-related questions. Your question is out of scope, where the Blockscout team can help.
