### ISSUE TITLE
No llego trasferencia trasfiya 

### ISSUE THREAD

**Issue by karol12345h** [blockscout/blockscout#11517]
### Description

No llego la trasferencia de world coin por trasfiya.  Provedor unlimit. Necesito soporte de la transferencia o solución al tema 
envia a  0x641ae2e320255d5693267179601bc6668d4f7a50
Id transferencia 
fd09aa99-07cc-4b49-a2a0-922d71e961de

### Type of the installation

Docker-compose

### Type of the JSON RPC archive node

Unlimit 

### Type of the chain

3

### Link to the page

https://worldchain-mainnet.explorer.alchemy.com/tx/0x8a881222e1e383deb9162283887a8046cc2c12a86dae4e5f8640a98a9f385453

### Backend version

v6.9.1-beta

### Frontend version

v1.36.4+05de412b

### Elixir & Erlang/OTP versions

Unlimit 

### Operating system

App store

### Additional information

**User Agent:** Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Mobile Safari/537.36

**Comment by MuahZain-Tech** [comment]
Hola, lo siento, no estoy disponible para atender su problema en este momento, por favor proporcione su dirección de correo electrónico en esta publicación, le escribiré en unas horas sobre qué hacer para resolver su problema.

**Comment by vbaranov** [comment]
This chat is for Blockscout-related questions. Your question is out of scope, where the Blockscout team can help.

**Comment by karol12345h** [comment]
***@***.***
