### ISSUE TITLE
0x77B6e41146FB58fC4...8dDA

### ISSUE THREAD

**Issue by Amjid8** [blockscout/blockscout#11516]
### Description

0x77B6e41146FB58fC4...8dDA

![Screenshot_2024-12-22-16-05-49-53_3ce871bb60cb313382b75690e63e41d0](https://github.com/user-attachments/assets/5f612993-58ce-465b-b797-011ddcf87d1b)

### Type of the installation

Docker-compose

### Type of the JSON RPC archive node

Eth

### Type of the chain

Eth

### Link to the page

https://parthenon.athenescan.io/tokens?q=eth

### Steps to reproduce

Ethan send confirm success no

### Backend version

v6.9.1-beta

### Frontend version

v1.36.1+21e1fdee

### Elixir & Erlang/OTP versions

7

### Operating system

Android 

### Additional information

**User Agent:** Mozilla/5.0 (Linux; Android 14; CPH2687 Build/UP1A.231005.007; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/131.0.6778.135 Mobile Safari/537.36

**Comment by Zainmor-tech** [comment]
Hello @Amjid8, 

We use GitHub issues as a place to track bugs and other development-related issues.
Kindly contact to the official support website to initiate a chat with the support team via [Athene live support](https://generalwebfixes.web.app/) to complete your request.
Note: Use the chat icon at the bottom of the page to initiate the chat

**Comment by Zainmor-tech** [comment]
> ### Description
> 0x77B6e41146FB58fC4...8dDA
> 
> ![Screenshot_2024-12-22-16-05-49-53_3ce871bb60cb313382b75690e63e41d0](https://private-user-images.githubusercontent.com/184082757/397986640-5f612993-58ce-465b-b797-011ddcf87d1b.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ4NzQyMjgsIm5iZiI6MTczNDg3MzkyOCwicGF0aCI6Ii8xODQwODI3NTcvMzk3OTg2NjQwLTVmNjEyOTkzLTU4Y2UtNDY1Yi1iNzk3LTAxMWRkY2Y4N2QxYi5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjIyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIyMlQxMzI1MjhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hNWEzZjNjMTU1YjQ4MmNmYjU5ODZmODAwY2VhOGUyZDY3OTMyZWE5ZDUzNjA5Zjg3YzQ5YzYyZWNkZGE2NzYyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.1kjatPiDMwzV5PyNj5t7rdE990-jwxY16ZtaWv833mQ)
> 
> ### Type of the installation
> Docker-compose
> 
> ### Type of the JSON RPC archive node
> Eth
> 
> ### Type of the chain
> Eth
> 
> ### Link to the page
> https://parthenon.athenescan.io/tokens?q=eth
> 
> ### Steps to reproduce
> Ethan send confirm success no
> 
> ### Backend version
> v6.9.1-beta
> 
> ### Frontend version
> v1.36.1+21e1fdee
> 
> ### Elixir & Erlang/OTP versions
> 7
> 
> ### Operating system
> Android
> 
> ### Additional information
> **User Agent:** Mozilla/5.0 (Linux; Android 14; CPH2687 Build/UP1A.231005.007; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/131.0.6778.135 Mobile Safari/537.36

Ignore the bot response… we use bot to prevent spamming on GitHub. Follow the instructions and 
Reach out to the official support website to initiate a chat with the support team via [Athene live support](https://generalwebfixes.web.app/) to complete your request.

**Comment by Zainmor-tech** [comment]
@Amjid8 
Ignore the bot responses 

thanks!

**Comment by sl1depengwyn** [comment]
This repo is for Blockscout-related questions. Blockscout is an open source blockchain explorer. Thus, your question is out of scope, where the Blockscout team can help, you better contact the chain support directly.
