### ISSUE TITLE
Token transfer

### ISSUE THREAD

**Issue by zam1109** [blockscout/blockscout#11518]
### Description

My token transfer hasn't gotten true 

### Type of the installation

Manual from the source code

### Type of the JSON RPC archive node

Ethereum

### Type of the chain

L1

### Link to the page

https://worldchain-mainnet.explorer.alchemy.com/tx/0xed5e5634662e869a8bb0e7f6a8fcaf69e575a63dbc6bf77cee83e3a3c09a8d88

### Backend version

v6.9.1-beta

### Frontend version

v1.36.4+05de412b

### Elixir & Erlang/OTP versions

Elixir 1.18

### Operating system

Android 13

### Additional information

**User Agent:** Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Mobile Safari/537.36

**Comment by vbaranov** [comment]
This chat is for Blockscout-related questions. Your question is out of scope, where the Blockscout team can help.

**Comment by zam1109** [comment]
It been two days and the token that i transfer hasn't gotten into my wallet

**Comment by zam1109** [comment]
It been two days and the token that i transfer hasn't gotten into my wallet
