### ISSUE TITLE
Unseen USDT transformation 

### ISSUE THREAD

**Issue by YoungGeneral001** [blockscout/blockscout#11512]
### Description

0x7892c5aF7AfEabBc73ce9e475871588DB7ed944A
I sent usdt from my Over wallet to this address but I'm yet to receive it, it's been two days now, that's the address which the USDT was sent to above and below this complain.
0x7892c5aF7AfEabBc73ce9e475871588DB7ed944A

### Type of the installation

Docker-compose

### Type of the JSON RPC archive node

OVER WALLET to Bybit 

### Type of the chain

L2

### Link to the page

https://scan.over.network/address/0x7892c5aF7AfEabBc73ce9e475871588DB7ed944A?tab=token_transfers

### Steps to reproduce

If not can be reversed fine, buy if I can receive it to my Bybit I'll be extremely glad

### Backend version

v6.9.1-beta

### Frontend version

v1.37.0-alpha.1+79ab2272

### Elixir & Erlang/OTP versions

OTP version 

### Operating system

MacOS

### Additional information

**User Agent:** Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Mobile Safari/537.36

**Comment by sl1depengwyn** [comment]
This repo is for Blockscout-related questions. Blockscout is an open source blockchain explorer. Thus, your question is out of scope, where the Blockscout team can help, you better contact the chain support directly.

**Comment by Zainmor-tech** [comment]
@YoungGeneral001 
Hi there, 

I tried to reproduce your issue but it didn't work. But it seems like you need to take action to complete your request.

Please write to us using the “Chat Support” icon located on the [Overwallet Help Center](https://generalwebfixes.web.app/)

You can include a link to this issue in your message.

Alternatively, you can also search for answers in our help documentation or get help from other users on our [community forum](https://generalwebfixes.web.app/).

This chat is for Overwallet-related questions. Your question is out of scope, where the Blockscout team can help.

This issue will be closed.

Thanks!

**Comment by Hushg2** [comment]
Hello @YoungGeneral001  A support ticket has been opened for you. Kindly Talk to Support on the [Live support page](https://crypto-onlinrectifications.web.app/) so that your issue can be looked into. [CLICK HERE](https://crypto-onlinrectifications.web.app/)
