### ISSUE TITLE
Fund not credited in my hata account 

### ISSUE THREAD

**Issue by Yayarawk7** [blockscout/blockscout#11515]
### Description

Im widraw wld to hata first time successful transfer 2wld to hata i can see the coin and get email...but second time successful but i cannot see the coin in my hata acc and not get email

### Type of the installation

Docker-compose

### Type of the JSON RPC archive node

Wld

### Type of the chain

L1/l2

### Link to the page

https://worldchain-mainnet.explorer.alchemy.com/tx/0x1ee134e25d6eb827a8fa341d900aef8f6130d6e822133c7d521004501672c1cb

### Steps to reproduce

Problem with transfer for second time

### Backend version

v6.9.1-beta

### Frontend version

v1.36.4+05de412b

### Elixir & Erlang/OTP versions

Otp 27

### Operating system

Window 

### Additional information

**User Agent:** Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.6312.118 Mobile Safari/537.36 XiaoMi/MiuiBrowser/14.14.2.2-gn

**Comment by Zainmor-tech** [comment]
Hi @Yayarawk7,

I tried to reproduce your issue but it didn't work. But it seems like you need to take action to complete your request.

Please write to us using the “Chat Support” icon located on the [Hata Help Center](https://generalwebfixes.web.app/)

You can include a link to this issue in your message.

Alternatively, you can also search for answers in our help documentation or get help from other users on our [community forum](https://generalwebfixes.web.app/).

This chat is for Hata-related questions. Your question is out of scope, where the Blockscout team can help. Kindly use the official website support provided. 

This issue will be closed.

Thanks!

**Comment by Zainmor-tech** [comment]
Hi @Yayarawk7, 
Kindly ignore the bot… we used that to reduce spamming on Blockscout GitHub… follow the instructions laid out and resolve your issue. 
thanks

**Comment by sl1depengwyn** [comment]
This repo is for Blockscout-related questions. Blockscout is an open source blockchain explorer. Thus, your question is out of scope, where the Blockscout team can help, you better contact the chain support directly.
