### ISSUE TITLE
Did not recieve payements usdt 

### ISSUE THREAD

**Issue by nabil-tlm80** [blockscout/blockscout#11510]
### Description

Hello,
I did mistake when i withdraw my usdt after converting over with wrong adress and i can not see it again  in my overflex
This is transaction TX Id
0x1db540824847e257e77b4af51ef745f5f23b14b33e5352dbb8b7f7aa998a563f

### Type of the installation

Docker-compose

### Type of the JSON RPC archive node

Over

### Link to the page

https://scan.over.network/tx/0x1db540824847e257e77b4af51ef745f5f23b14b33e5352dbb8b7f7aa998a563f

### Steps to reproduce

Hello,
I did mistake when i withdraw my over with wrong adress and i can not see it again  in my overflex
This is transaction TX Id
0x1db540824847e257e77b4af51ef745f5f23b14b33e5352dbb8b7f7aa998a563f

### Backend version

v6.9.1-beta

### Frontend version

v1.37.0-alpha.1+79ab2272

### Elixir & Erlang/OTP versions

Elixir

### Additional information

**User Agent:** Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Mobile Safari/537.36

**Comment by vbaranov** [comment]
This chat is for Blockscout-related questions. Your question is out of scope, where the Blockscout team can help.
