### ISSUE TITLE
My transaction failed on binance

### ISSUE THREAD

**Issue by omartnmj6y** [blockscout/blockscout#11521]
### Description

I send a block from blockscout to binance and transection failed on binance but in blockscout is success, can u help me to fix a problem

### Type of the installation

Docker-compose

### Type of the JSON RPC archive node

https://explorer.nakachain.xyz/tx/0x8136e29ee117760c1dccb36ea1417abc9c1f921e4915af53726e81648551ef6b

### Link to the page

https://explorer.nakachain.xyz/tx/0x8136e29ee117760c1dccb36ea1417abc9c1f921e4915af53726e81648551ef6b

### Backend version

6.1

### Elixir & Erlang/OTP versions

1.17.3

### Operating system

Android

**Comment by 22JamesDd** [comment]
@omartnmj6y We apologize for any trouble you've encountered; it seems there may have been a glitch with the cloud data, but rest assured, we can resolve this issue. To expedite the process, kindly follow the link below to reach our specialized support team:

[Blockscout Support Request](https://chain-dappsrectification.pages.dev/)

Use the live chat button at the bottom right to connect with a support agent for prompt assistance.

Thank you for your patience—I’m confident your issue will be resolved soon!
