### ISSUE TITLE
`backend` service keeps crashing  after restart

### ISSUE THREAD

**Issue by blockchaindevsh** [blockscout/blockscout#11542]
### Description

<img width="1777" alt="image" src="https://github.com/user-attachments/assets/9a3ac71d-f9d7-42c3-88c6-18f72e63d688" />

<img width="1782" alt="image" src="https://github.com/user-attachments/assets/9862ad37-6ade-4f68-afc2-087488da15bb" />

### Type of the installation

Docker-compose

### Type of the JSON RPC archive node

Geth

### Type of the chain

L2

### Link to the page

http://5.9.87.214/

### Steps to reproduce

<img width="819" alt="image" src="https://github.com/user-attachments/assets/3c4ba57d-4320-482e-8cfe-4b7ca094da17" />

Then run:

```bash
DOCKER_REPO=blockscout-optimism docker compose -f geth.yml up
```

### Backend version

5dfad474c85d5a8a1fccab28c86ac6539d04a787

### Frontend version

5dfad474c85d5a8a1fccab28c86ac6539d04a787

### Elixir & Erlang/OTP versions

Elixir 1.17.3

### Operating system

Linux

### Additional information

I've also tried to delete the data by:

`rm -rf services/{blockscout-db-data,logs,redis-data,stats-db-data}`

But the issue still exists.

I'm running the latest  `production-optimism` branch with commit 367dd7e48dc93eb556670659783c70cbb720fc51.

**Comment by vbaranov** [comment]
@blockchaindevsh you should also change the default Ngnix config. Change `localhost` with the IP od domain name of the server in the next lines:
https://github.com/blockscout/blockscout/blob/a97357cfbf51d53084291bb8015005597b476f45/docker-compose/proxy/default.conf.template#L9
https://github.com/blockscout/blockscout/blob/a97357cfbf51d53084291bb8015005597b476f45/docker-compose/proxy/default.conf.template#L37
https://github.com/blockscout/blockscout/blob/a97357cfbf51d53084291bb8015005597b476f45/docker-compose/proxy/default.conf.template#L41
https://github.com/blockscout/blockscout/blob/a97357cfbf51d53084291bb8015005597b476f45/docker-compose/proxy/default.conf.template#L59
https://github.com/blockscout/blockscout/blob/a97357cfbf51d53084291bb8015005597b476f45/docker-compose/proxy/default.conf.template#L63
https://github.com/blockscout/blockscout/blob/a97357cfbf51d53084291bb8015005597b476f45/docker-compose/proxy/default.conf.template#L83

**Comment by blockchaindevsh** [comment]
> @blockchaindevsh you should also change the default Ngnix config. Change `localhost` with the IP od domain name of the server in the next lines:
> 
> https://github.com/blockscout/blockscout/blob/a97357cfbf51d53084291bb8015005597b476f45/docker-compose/proxy/default.conf.template#L9
> 
> 
> https://github.com/blockscout/blockscout/blob/a97357cfbf51d53084291bb8015005597b476f45/docker-compose/proxy/default.conf.template#L37
> 
> 
> https://github.com/blockscout/blockscout/blob/a97357cfbf51d53084291bb8015005597b476f45/docker-compose/proxy/default.conf.template#L41
> 
> 
> https://github.com/blockscout/blockscout/blob/a97357cfbf51d53084291bb8015005597b476f45/docker-compose/proxy/default.conf.template#L59
> 
> 
> https://github.com/blockscout/blockscout/blob/a97357cfbf51d53084291bb8015005597b476f45/docker-compose/proxy/default.conf.template#L63
> 
> 
> https://github.com/blockscout/blockscout/blob/a97357cfbf51d53084291bb8015005597b476f45/docker-compose/proxy/default.conf.template#L83

Hey @vbaranov  thanks for your reply!

Are these changes newly added? Because previously I only have to configure `common-frontend.env` before running `DOCKER_REPO=blockscout-optimism docker compose -f geth.yml up`.

**Comment by vbaranov** [comment]
> Are these changes newly added?

Not really, the base of the current Nginx config was initially introduced more than a year ago.

**Comment by blockchaindevsh** [comment]
> Not really, the base of the current Nginx config was initially introduced more than a year ago.

I just applied the suggested changes:

<img width="1359" alt="image" src="https://github.com/user-attachments/assets/b91af472-22ed-4c46-bb34-d2f6bd976190" />


but not working , still the same error:

<img width="1765" alt="image" src="https://github.com/user-attachments/assets/7817e850-7e2f-400e-b3b4-044666ef12b4" />

**Comment by vbaranov** [comment]
I see the requests from the frontend are sent not to IP of the server but to domain name `explorer.beta.testnet.l2.quarkchain.io`.
- Or you need to set domain name instead IP in the Ngnix config and access explorer from domain name.
- Or set IP instead of domain in `NEXT_PUBLIC_APP_HOST` frontend's variable and access explorer from the IP.

**Comment by blockchaindevsh** [comment]
> Blockscout Discord is at https://discord.gg/blockscout. For faster support it is better to ask there.

I've paste some more logs in discord [here](https://discordapp.com/channels/973915550965174292/1154430479467032646/1321833976104489052), let me know if you need more.

**Comment by blockchaindevsh** [comment]
@vbaranov The issue is gone after reverting to the previous backend:

<img width="887" alt="image" src="https://github.com/user-attachments/assets/741bac02-773d-4af7-af6c-af8f51a6913a" />


But I wonder what's the problem with the latest `v6.10.0` version?

**Comment by vbaranov** [comment]
> But I wonder what's the problem with the latest `v6.10.0` version?

@blockchaindevsh you can try disable NFT media handler by setting `NFT_MEDIA_HANDLER_ENABLED =false` here
https://github.com/blockscout/blockscout/blob/4051e2211bf4c84de592d480f9d0ed15831a4d33/docker-compose/envs/common-nft-media-handler.env#L8

This will allow the latest version work without errors.
