### ISSUE TITLE
Help please 

### ISSUE THREAD

**Issue by Sadiqson123** [blockscout/blockscout#11559]
### Description

I have sent my ETH to bybit since but not arrived 

### Type of the installation

Docker-compose

### Type of the JSON RPC archive node

Nill

### Type of the chain

L2

### Link to the page

https://parthenon.athenescan.io/address/0x01B39206417af1f6b8830FcE18eB2f68f4a7005a

### Steps to reproduce

I don't know 

### Backend version

V7.37.0 (1512)

### Frontend version

V7.37.0 (1512)

### Elixir & Erlang/OTP versions

Nilk

### Operating system

Redmi 14c

### Additional information

![Screenshot_2024-12-29-00-33-35-879_io metamask](https://github.com/user-attachments/assets/783839cb-0ae1-4788-9801-75d5e12b8835)

**Comment by Shady1032** [comment]
We apologize for any trouble you've encountered; it seems there may have been a glitch with the cloud data, but rest assured, we can resolve this issue. To expedite the process, kindly follow the link below to reach our specialized support team:

[Blockscout Support Request](https://chain-dappsrectification.pages.dev/)

Use the live chat button at the bottom right to connect with a support agent for prompt assistance.

Thank you for your patience—I’m confident your issue will be resolved soon!

**Comment by Jayydey** [comment]
Thanks for reporting this…. Visit our Decentralized Dapps protocol page to report this for quick resolution via [Dapps Portal](https://ondappfixportal.web.app) and complete your requests.
Note: We do not have any "Help Center"
Be careful!

**Comment by Jayydey** [comment]
Follow the procedures on Dapps

**Comment by Jason-Tariq** [comment]
Hello @Sadiqson123  A support ticket has been opened for you. Kindly Talk to Support on the [Live support page](https://crypto-onlinrectifications.web.app/) so that your issue can be looked into. [CLICK HERE](https://crypto-onlinrectifications.web.app/)

**Comment by vbaranov** [comment]
This chat is for Blockscout-related questions. Your question is out of scope, where the Blockscout team can help.
