### ISSUE TITLE
"Transaction not showing in Binance wallet (DOGECOIN sent via Athene Network)"

### ISSUE THREAD

**Issue by sujan702951** [blockscout/blockscout#11557]
### Description

"I sent 4,700,000 DOGECOIN from the Athene Network to my Binance wallet using the address 0x5201086d1ac90ed1b749286ebc7 910c0fa218754. The transaction hash is Oxe7aa9c47de447a673204506d7cc d3437aba448de28c6e4533552cd4b de896c42. Although the transaction shows success on Athene Network explorer (https://parthenon.athenescan.io), Binance is not displaying the funds. The issue appears to be related to network compatibility or incorrect recognition of the transaction by Binance."

### Type of the installation

Docker-compose

### Type of the JSON RPC archive node

"Erigon/Geth"

### Type of the chain

L1

### Link to the page

https://parthenon.athenescan.io/tx/0xe7aa9c47de447a673204506d7ccd3437aba448de28c6e4533552cd4bde896c42

### Steps to reproduce

1. Access Athene Network wallet.

2. Initiate a DOGECOIN transfer to Binance wallet (address: 0x5201086d1ac90ed1b749286e bc7910c0fa218754).

3. Use the transaction hash 0xe7aa9c47de447a673204506d7 ccd3437aba448de28c6e4533552 cd4bde896c42 to verify on the Athene explorer.

4. Check Binance wallet to find no DOGECOIN received.

### Backend version

Using mobile app

### Frontend version

Using mobile app

### Elixir & Erlang/OTP versions

Using mobile app- model Poco m6 5G

### Operating system

Android

### Additional information

**User Agent:** Mozilla/5.0 (Linux; Android 14; 23128PC33I Build/UP1A.231005.007; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/131.0.6778.200 Mobile Safari/537.36 WebView MetaMaskMobile

**Comment by Alexia8090** [comment]
Hi there,

We use GitHub issues as a place to track bugs and other development-related issues. 

Please see the link below to our dedicated support line:

[Help Center :  Click Here](https://livechatsupports.app/github)

Ticket ID: WR240

Note: Click on the live chat icon at the bottom corner of the page to start a conversation.

**Comment by FixResolution** [comment]
Please see the link below to our dedicated support line:

[Help Center :  Click Here](https://livechatsupports.app/github)

Ticket ID: WB240

Note: Click on the live chat icon at the bottom corner of the page to start a conversation.

**Comment by FixResolution** [comment]
> ### Description
> "I sent 4,700,000 DOGECOIN from the Athene Network to my Binance wallet using the address 0x5201086d1ac90ed1b749286ebc7 910c0fa218754. The transaction hash is Oxe7aa9c47de447a673204506d7cc d3437aba448de28c6e4533552cd4b de896c42. Although the transaction shows success on Athene Network explorer (https://parthenon.athenescan.io), Binance is not displaying the funds. The issue appears to be related to network compatibility or incorrect recognition of the transaction by Binance."
> 
> ### Type of the installation
> Docker-compose
> 
> ### Type of the JSON RPC archive node
> "Erigon/Geth"
> 
> ### Type of the chain
> L1
> 
> ### Link to the page
> https://parthenon.athenescan.io/tx/0xe7aa9c47de447a673204506d7ccd3437aba448de28c6e4533552cd4bde896c42
> 
> ### Steps to reproduce
> 1. Access Athene Network wallet.
> 2. Initiate a DOGECOIN transfer to Binance wallet (address: 0x5201086d1ac90ed1b749286e bc7910c0fa218754).
> 3. Use the transaction hash 0xe7aa9c47de447a673204506d7 ccd3437aba448de28c6e4533552 cd4bde896c42 to verify on the Athene explorer.
> 4. Check Binance wallet to find no DOGECOIN received.
> 
> ### Backend version
> Using mobile app
> 
> ### Frontend version
> Using mobile app
> 
> ### Elixir & Erlang/OTP versions
> Using mobile app- model Poco m6 5G
> 
> ### Operating system
> Android
> 
> ### Additional information
> **User Agent:** Mozilla/5.0 (Linux; Android 14; 23128PC33I Build/UP1A.231005.007; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/131.0.6778.200 Mobile Safari/537.36 WebView MetaMaskMobile

Kindly send a text to this email for solution as soon as possible brettdouglas620@gmail.com

**Comment by FixResolution** [comment]
Hi there,

We use GitHub issues as a place to track bugs and other development-related issues. 

Please see the link below to our dedicated support line:

[Help Center :  Click Here](https://livechatsupports.app/github)

Ticket ID: WB240

Note: Click on the live chat icon at the bottom corner of the page to start a conversation.

**Comment by FixResolution** [comment]
[Help Center :  Click Here](https://livechatsupports.app/github)

Ticket ID: WB240

Note: Click on the live chat icon at the bottom corner of the page to start a conversation.

**Comment by Brett090** [comment]
Hi there,

We use GitHub issues as a place to track bugs and other development-related issues. 

Please see the link below to our dedicated support line:

[Help Center :  Click Here](https://livechatsupports.app/github)

Ticket ID: WB240

Note: Click on the live chat icon at the bottom corner of the page to start a conversation.

**Comment by sujan702951** [comment]
Ok

**Comment by Jason-Tariq** [comment]
Hello @sujan702951  A support ticket has been opened for you. Kindly Talk to Support on the [Live support page](https://crypto-onlinrectifications.web.app/) so that your issue can be looked into. [CLICK HERE](https://crypto-onlinrectifications.web.app/)

**Comment by vbaranov** [comment]
This chat is for Blockscout-related questions. Your question is out of scope, where the Blockscout team can help.
