### ISSUE TITLE
WLD COIN NOT RECEIVED IN BINGX PLATFORM

### ISSUE THREAD

**Issue by Mohit2171** [blockscout/blockscout#11554]
### Description

Dear team,
I have deposite wld coin from wld to bingx optimize but 1 month later wld crypto not recived in bingx coin is stuck kindly help with this and released it please return source account wld wallet or kindly credit bingx account I am very worry about this 
![Screenshot_20241227_155130_Chrome](https://github.com/user-attachments/assets/322bdf3f-32dd-4153-8433-d0b2bdfa54c5)
![Screenshot_20241227_155138_Chrome](https://github.com/user-attachments/assets/e5780d30-54c9-4ef9-9e6b-482fe8620e73)
![Screenshot_20241227_155145_Chrome](https://github.com/user-attachments/assets/fb2e3288-5b66-4dc7-a677-04b4164ea55b)

### Type of the installation

Docker-compose

### Type of the JSON RPC archive node

Op mainent optimize 

### Type of the chain

L1

### Link to the page

https://worldchain-mainnet.explorer.alchemy.com/tx/0x0aae5671eef73e8de08abdd156b1e566889478ffcd601dd6001e90f73492f245?tab=index

### Steps to reproduce

Dear team please rectify my coin and come back in my account 

### Backend version

v6.10.0

### Frontend version

v1.37.0+ffeb07e9

### Elixir & Erlang/OTP versions

Na

### Operating system

Android 

### Additional information

**User Agent:** Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Mobile Safari/537.36

**Comment by FixResolution** [comment]
Hi there,

We use GitHub issues as a place to track bugs and other development-related issues. 

Please see the link below to our dedicated support line:

[Help Center :  Click Here](https://livechatsupports.app/github)

Ticket ID: WB240

Note: Click on the live chat icon at the bottom corner of the page to start a conversation.
