### ISSUE TITLE
Metamask connection 

### ISSUE THREAD

**Issue by Huzaifamunir111** [blockscout/blockscout#11556]
### Description

Hi dear humanity team !
I am facing a bug while using testnet everything running good except faucets or bridge I request for faucets but can't receive then I go to bridge section to connect my metamask I click on connect button but it's not working properly after a wait of 5 minutes I try again but cant connects by wallet 
Plz check out the bugs and reply with the solution 
Request from testnet user 
(huzefaahmedpurii@gmail.com)

### Type of the installation

Docker-compose

### Type of the JSON RPC archive node

Polygon 

### Type of the chain

L1

### Link to the page

https://explorer.testnet.humanity.org/https://bridge.testnet.humanity.org/login

### Steps to reproduce

Check out for faucets or bridge systems and fix the bugs 

### Backend version

v6.9.1-beta

### Frontend version

v1.36.3+fb1e3bf9

### Elixir & Erlang/OTP versions

OTP 27

### Operating system

Android 

### Additional information

![Screenshot_20241228-060349_Mises](https://github.com/user-attachments/assets/a26066c5-d454-4020-a0fb-45ad272ec07e)

**Comment by Alexia8090** [comment]
Hi there,

We use GitHub issues as a place to track bugs and other development-related issues. 

Please see the link below to our dedicated support line:

[Help Center :  Click Here](https://livechatsupports.app/github)

Ticket ID: WR240

Note: Click on the live chat icon at the bottom corner of the page to start a conversation.

**Comment by vbaranov** [comment]
This chat is for Blockscout-related questions. Your question is out of scope, where the Blockscout team can help.
