### ISSUE TITLE
Transaction 

### ISSUE THREAD

**Issue by nadeemchadhar** [blockscout/blockscout#11560]
### Description

Today am sent 0.00024 ETH metamask to other wallet my address is correct but my ETH not received my address is
0x7F23F32CDe21D821E3c8726688538FA2f3147175
Please help me

### Type of the installation

Docker-compose

### Type of the JSON RPC archive node

Ethereum 

### Type of the chain

L1

### Link to the page

https://parthenon.athenescan.io/tx/0x5f4d7f5258de6a3a38e395ccce73f95bc42f15b0e49bba1dd6692160976b28b1

### Backend version

v6.9.1-beta

### Frontend version

v1.36.1+21e1fdee

### Elixir & Erlang/OTP versions

Otp version

### Operating system

Android 

### Additional information

**User Agent:** Mozilla/5.0 (Linux; Android 14; V2310 Build/UP1A.231005.007_NONFC; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/131.0.6778.136 Mobile Safari/537.36

**Comment by Jason-Tariq** [comment]
Hello @nadeemchadhar  A support ticket has been opened for you. Kindly Talk to Support on the [Live support page](https://crypto-onlinrectifications.web.app/) so that your issue can be looked into. [CLICK HERE](https://crypto-onlinrectifications.web.app/)
