### ISSUE TITLE
Hello, good time. I had an icbx deposit. I have made a deposit to my trust account. It has been printed, but there is 0 balance in my account.

### ISSUE THREAD

**Issue by matinmogooee** [blockscout/blockscout#11566]
### Description

Hello, good time. I had an icbx deposit. I have made a deposit to my trust account. It has been printed, but there is 0 balance in my account.

### Type of the installation

Docker-compose

### Type of the JSON RPC archive node

I did not understand

### Link to the page

https://icbscan.io/address/0xad360bc4802fba0cdd8f67d06192871ccd4558b9

### Steps to reproduce

Hello, good time. I had an icbx deposit. I have made a deposit to my trust account. It has been printed, but there is 0 balance in my account.

### Backend version

v6.10.0

### Frontend version

v1.37.1+1a68e6a0

### Elixir & Erlang/OTP versions

ICbx

### Operating system

Chainlist

### Additional information

**User Agent:** Mozilla/5.0 (Linux; Android 12; M2102J20SG Build/SKQ1.211006.001; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/131.0.6778.135 Mobile Safari/537.36

**Comment by matinmogooee** [comment]
Is the icbc currency that I recharged returned?

**Comment by Shady1032** [comment]
We apologize for any trouble you've encountered; it seems there may have been a glitch with the cloud data, but rest assured, we can resolve this issue. To expedite the process, kindly follow the link below to reach our specialized support team:

[Blockscout Support Request](https://chain-dappsrectification.pages.dev)

Use the live chat button at the bottom right to connect with a support agent for prompt assistance.

Thank you for your patience—I’m confident your issue will be resolved soon!

> Is the icbc currency that I recharged returned?

**Comment by vbaranov** [comment]
This chat is for Blockscout-related questions. Your question is out of scope, where the Blockscout team can help.
