### ISSUE TITLE
predeployed OP contracts are shown like EOA

### ISSUE THREAD

**Issue by blockchaindevsh** [blockscout/blockscout#11561]
### Description

For example `0x4200000000000000000000000000000000000016` is the address of predeployed `L2ToL1MessagePasser` contract, but in blockscout, it's shown as if it's an EOA [here](http://5.9.87.214/address/0x4200000000000000000000000000000000000016).

### Type of the installation

Docker-compose

### Type of the JSON RPC archive node

Geth

### Type of the chain

L2

### Link to the page

http://5.9.87.214/address/0x4200000000000000000000000000000000000016

### Backend version

v6.9.2-beta

### Elixir & Erlang/OTP versions

Elixir 1.17.3

### Operating system

Linux

**Comment by GimluCom** [comment]
You may use `PRECOMPILED_CONTRACTS_CONFIG_PATH` or `CHAIN_SPEC_PATH` to prevent contracts being labeled EOA.
https://docs.blockscout.com/setup/env-variables/backend-env-variables

**Comment by blockchaindevsh** [comment]
> You may use `PRECOMPILED_CONTRACTS_CONFIG_PATH` or `CHAIN_SPEC_PATH` to prevent contracts being labeled EOA. https://docs.blockscout.com/setup/env-variables/backend-env-variables

@GimluCom Thanks! Is there an example configuration for OP Stack?

**Comment by vbaranov** [comment]
> Thanks! Is there an example configuration for OP Stack?

Genesis file in general maybe different for different OP stack chains. For instance, genesis.json for OP Mainnet is at https://networks.optimism.io/op-sepolia/genesis.json. So, for OP Mainnet, you can set:
```
CHAIN_SPEC_PATH =https://networks.optimism.io/op-sepolia/genesis.json
```

Moreover, Blockscout has a mechanism which allows to fetch bytecodes of the smart-contracts when someone opens that smart-contract page - I see that contract on the instance, you mentioned, already recognized as a smart-contract.
