### ISSUE TITLE
Mi transición no se hizo

### ISSUE THREAD

**Issue by YowShy** [blockscout/blockscout#11571]
### Description

Acabo de hacer una transacción a mi billetera virtual y no me ha llegado nada, devuélvame el dinero

### Type of the installation

Docker-compose

### Type of the JSON RPC archive node

Geth

### Type of the chain

1

### Link to the page

https://explorer.mtt.network/tx/0x2515ec685125574121ce1fd428abb0fc3ef173a5f0bca02ebdf602d2d6f2aee2?tab=index

### Steps to reproduce

Mi transacción no me llegó a mi billetera, por favor cancelen la transacción y devuélvame el dinero

### Backend version

v6.9.1-beta

### Frontend version

rollbar+742e3815

### Elixir & Erlang/OTP versions

Elixir 1.17.3

### Operating system

Android

### Additional information

**User Agent:** Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Mobile Safari/537.36

**Comment by vbaranov** [comment]
This chat is for Blockscout-related questions. Your question is out of scope, where the Blockscout team can help.

**Comment by YowShy** [comment]
Mi transición a mi billetera wallet no se envió, necesito un reembolso
