### ISSUE TITLE
Internal Transactions not being fetched on Failed Transactions

### ISSUE THREAD

**Issue by acravenho** [blockscout/blockscout#1367]
With our new set of internal transactions rules, we should always fetch the internal transactions on a failed transaction to determine the reason behind the failed transaction. 

Here is a list of 19 recent failed transactions that do not have the internal transactions fetched.

```
0x67129aabc1cc62995e735f7fd6e5a3eefb7c7a4961ff5966bf1622128f0b75c5
0x44862c761382ddc2e7e7268a1d4f3c79295f51d3aef5b67ec06f19d66b00eded
0x17832e641618075ab7e94e936a2957111ab7a2240107f40929fda7e5c44c49ad
0x31d16aff7fa8574c6059b5b3886fb3af23c3322dfbc70674ae5227ab4d6084d9
0xcafe2d84bed41a8fc4431862fd367e348fc42e122924739b48e0cf0e1b7990f2
0xec13c4d5b7a8d1417e689571603e3346ba3d73fb3d31203cd6b8b5a50caaf843
0xb3f8a48a281c36cd71521b3129b46c0cf3f65a6cce8eb35d4ad0be9152e3727b
0xf315d5c92dd2e215bb1417d35a025529f2991faebde893feb52c61dd3d827ab3
0xd8d8f7b7eed042e616bb567ae9768e95e57e5b8dc9a48552ca65327eb441dc58
0x2ef1833c7365fa4f1ec044a6a5e77433d35d1d78dee805c730aca0a09007e403
0xaf59a055c5cbc8010ad18f13217daabf38698452f1e949dca8ed7f27e2fb10d2
0x719afd4e1e4826838869c3645726cdac0c4179006baf6c5dec8c4d842645040d
0x04eac5a650292274303e3210bfb59919ae90ad0d70d4606a0e8503e1a021d997
0x0d57532529e11a8d7209a3bc3cead92a3ceb67f582254623dcf3f3cb982d7d86
0x3fdb0811da6ff79b3bec952e4375862dd2e0983196c1f5f83db24207e393b56c
0x2a9d103450c5caa90833ec02b27db391f58a42db45762150efa636873026b53f
0xf24e0166b7973fbf1cb80e9bd1fe25651860cfdf9b45ed8f51bb83a19b388c0c
0x35a2a618360f8f7d0fe92d51fde135474736dd487f4cfeb7c566ce7624f76721
0x4fe10469ac2789cb613792d038c9dcc6801ebd0ea86dd270d63d6292305daaff
```

These particular contracts are not specific to token contracts so the recent internal transaction rules may not be playing a part here. 

There are no error logs to justify a specific reason why we are not fetching these internal transactions. The only errors that I am currently seeing in the logs are related to #1337. 

### Environment

* Chain: `POA Core`
* Operating System: Linux

### Steps to reproduce

1. Interaction with a contract fails.
2. The internal transaction should be fetched to provide the reason for the failure.

**Comment by acravenho** [comment]
Here is another example on xDai chain: https://blockscout.com/poa/dai/tx/0x95330fed50476fdc740699a671f0d85ce712ecb8f17ba659c0b2dcdabbf06978/internal_transactions

Internal transactions are being fetched but the error field isn't being set.

**Comment by vbaranov** [comment]
Works as expected now.
