### ISSUE TITLE
Contributor sees Stats Page with Graphs about Network Data

### ISSUE THREAD

**Issue by acravenho** [blockscout/blockscout#137]
Graphs should include the following:
- [ ] Block time
- [ ] Price USD/POA (config file)
- [ ] Transactions per block
- [ ] Address growth chart
- [ ] Market Capitalization Chart (config file)
- [ ] Top Validators/Miners Pie Chart
- [ ] Total Daily Gas Used Chart
- [ ] Average Block Size Chart

**Comment by vbaranov** [comment]
Implemented in the frame of Rust stats service https://github.com/blockscout/blockscout-rs/tree/main/stats
