### ISSUE TITLE
Add eWASM Support to POA-explorer

### ISSUE THREAD

**Issue by zixuanzh** [blockscout/blockscout#169]
Hi, I am interested in working on this. May I know how I can get started and which person to talk to? Thanks

**Comment by KronicDeth** [comment]
@zixuanzh can you outline the feature more?  Use the `- [ ]` checkboxes to define a feature set of how you want the feature to work and link to documentation (like https://github.com/ewasm/design) and design for the server and client side rendering.

@igorffs how does this interact with your team's contract verification work?

**Comment by zixuanzh** [comment]
We are still ideating different features but we plan to have it before we launch eWASM on testnet. Here is a feature set that we are considering.

- [ ] Deploy ewasm contracts (paste in wast code and deploy it as a contract).
- [ ] Toggle to switch between WAST and wasm bytecode or EVM bytecode / opcodes.
- [ ] Calculate new address and metering when deploying a contract.
- [ ] Optimization: only fetch data when an account is selected.

**Comment by acravenho** [comment]
@zixuanzh Feel free to keep adding them here. I'll break them out into individual issues for our team to work on once we're ready for them. We are bringing on two new devs to specifically work on this integration for eWASM.

**Comment by zixuanzh** [comment]
@acravenho I am interested in helping out with this too this month. Please let me know how I can be involved.

**Comment by d10r** [comment]
I suggest to also allow adding just the ABI of a contract in order to enable the "Read Contract" tab.

**Comment by acravenho** [comment]
How do we very that the ABI is accurate without first verifying the source code?

**Comment by d10r** [comment]
That may indeed be a problem.  
I'm not familiar enough with the internals in order to give a qualified answer.
How much can be verified based on the ABI alone? I guess it should be possible to at determine if the claimed variables are a valid (!= the correct) view onto the contract's storage and that there's executable code where a function is pointing to. Is that the case?
Depending on how much can be verified, it may make sense to allow that (maybe with a big warning that it's not verified) or not.

Btw. can source code verification of EVM contracts prevent somebody from uploading a semantically correct version of the code with manipulated, misleading variable names?

**Comment by acravenho** [comment]
It's possible to decode the bytecode to provide function names and arguments, in turn, we could provide an ABI for these decoded functions. I'm familiar with a project that plans on open sourcing their code. Once they do so we can implement this feature to provide an ABI for unverified smart contracts. 

Yes, source code verification of EVM contracts do prevent someone from uploading a semantically correcto version of the with manipulated and misleading variable names. Adding an extra space anywhere in the contract is enough to invalidate the verification process.

**Comment by d10r** [comment]
So, the ABI could even be extracted automatically with that project you mention? That would be even better than an option to upload it!

**Comment by acravenho** [comment]
Yes, I'm really excited about it and would make for a great user experience. As I receive more information regarding the project, I'll post it here.

**Comment by ulyanas** [comment]
eWASM hasn't been fully implemented on the EVM chains, closing the issue
