### ISSUE TITLE
Certain Addresses are not showing up as Contracts

### ISSUE THREAD

**Issue by acravenho** [blockscout/blockscout#1797]
While verifying contracts I am noticing a number of addresses that are showing a `404` on the verification page which is due to the address not being recognized as a smart contract. 

I'll keep an ongoing list here as they appear this afternoon.

* 0x8bf0a15a3fe06d440158ea86d7aff9251f462e4d
* 0xf277f6da5f453c2ace81a6e8f1d2cd3908e45194
* 0xe880b566ca08603b1e45baa58360187c738c0604
* 0x9dc2d6e59efb0cd835e036fe3fb2ae28c6183bd2
* 0x541ea2050e2108ae23a58bc4ec64ae67ab8b614f
* 0x2e7cebd17bd14674d88317155044731e8e932e23
* 0xfe72406e440234d6115958fe104677fec0d80450
* 0xebd72442d9d916bc9263cca52593401b64b11857
* 0x76426c98c7e78ee67f3fa950865a064640d15d88
* 0x3a982de3e470d81eb60b4c6019d88242dc676909
* 0xd200287ef6d2ea12dfd9233d3654ac6540d4ddc7
* 0x0b60174b0a0f0897781a757ba0ded4b8986b3879
* 0x3c1f3bdffd3ff6ba385b4700eface997adcaf8db
* 0xea097a2b1db00627b2fa17460ad260c016016977
* 0xcdc86951097c670ba909eac7eb2aad93e04709e5
* 0x387159880f9b6fa1bc73d0a366410ae1917c8def
* 0xfec0cf7fe078a500abf15f1284958f22049c2c7e
* 0x420167d87d35c3a249b32ef6225872fbd9ab85d2
* 0xccaca999be06df2dd72b15f5827c1a329a5b5f59
* 0x0cfbed1bd80bd8a740f24ec5fca8e8d1a9f87052
* 0x659c6a81afa57a75a3e512587e920b97304d330a
* 0xaf090f535f7fc85f4f2fa1ec5406e9f1a8957f16
* 0x6ebeaf8e8e946f0716e6533a6f2cefc83f60e8ab
* 0x6885fc6a8166d6b875cc9884ea9fcf76745f8b51
* 0xcca36039cfdd0753d3aa9f1b4bf35b606c8ed971
* 0x64d2d66050c540116a02a49aeda827af67bb1475
* 0x5508870e2e47ece5284e2c51360f591d820fd1d5
* 0x814f67fa286f7572b041d041b1d99b432c9155ee

### Steps to reproduce

1. Visit the verification page of an address where the problem occurs.
2. User should see a 404 page.

### Expected behaviour

The form to verify a contract should show.

### Actual behaviour

404 error

**Comment by goodsoft** [comment]
So far I found that `create` internal transactions that create these contracts were erroneously marked as failed with different errors (`Out of gas`, `Reverted`, `Bad instruction`, probably others).
Interestingly, "outer" transactions are still considered successful.

Moreover, re-running import of a corresponding block yields successful internal transactions and properly detected contract address.

I even found a recent transaction from April 17th, which was properly imported [on production server](https://blockscout.com/eth/mainnet/tx/0x6fc51dd43a60b85f336c0749a29e849d44f1ffc1bf1f1161b84655842ec7ba64/internal_transactions), while the same exact transaction had all but the root internal transaction marked as `Out of gas` on staging.

**Comment by acravenho** [comment]
Thanks for taking a look at this so quickly. I can keep track of all the blocks where this anomaly in the `create` internal transaction occurred and then provide a master list once completed.

**Comment by vbaranov** [comment]
@acravenho there were 8 from 28 contracts addresses you supplied, there was no *Code* tab. I reindexed corresponding blocks where those contracts were created in order to get missing internal transactions. Now, all of them have *Code* tab.

And 18 of the list already verified. Should I close the issue or you have other examples of missing *Code* tab?

**Comment by acravenho** [comment]
Here are a few more contracts that are not listed as contracts: 

* 0x9508505ad0ad7a39d2a20287f36e2d5ef046bf4d
* 0xd540a3d5b922b8dab71ed8978ee74b1749d147ca
* 0x4ab5d9c7ad1a31ebe04ad6d8ce11db46faac44f5
* 0x6888d3ab3d9e603801fee15b0e6e1068cb3e02c7
* 0x73e50f7a81d7a97ac4355ed339ab53ad3886b66f
* 0x266733498f29981e2393b70554b4138cf7bc3be5
* 0x3033423021d476728b0f2abd31156c20acdfe134
* 0x67c9f9cb58c526f28c3a1a4ed0e6fe983b7bed85
* 0x7a6d52bff63f506c8ebfff16599265deaa0a8eba

As I see more, I'll add them to the list.

**Comment by vbaranov** [comment]
not relevant anymore
