### ISSUE TITLE
Add loader for long tasks

### ISSUE THREAD

**Issue by vbaranov** [blockscout/blockscout#2003]
We need a common to all pages loader for pagination operations, tabs switching etc.

**Comment by pashagonchar** [comment]
@vbaranov 


[active_pools_loader_animation.mp4.zip](https://github.com/poanetwork/blockscout/files/3210567/active_pools_loader_animation.mp4.zip)
<img width="1280" alt="active_pools_loader_@2x" src="https://user-images.githubusercontent.com/16716926/58230112-0bbdab00-7d3c-11e9-9ac8-70b5ec9705d3.png">

**Comment by vbaranov** [comment]
Implemented in the new UI
