### ISSUE TITLE
Add ERC1155 Support

### ISSUE THREAD

**Issue by nickjuntilla** [blockscout/blockscout#2355]
*Describe your issue here.*

### Environment

Any

### Steps to reproduce

Any

### Expected behaviour

On etherescan ERC721 tokens can be linked to directly. They also don't yet have support for ERC1155. ERC1155 standard has been finalized here: https://eips.ethereum.org/EIPS/eip-1155 
It would be useful for my app Receiptchain to be able to link directly to a token since we use the ERC1155 standard. It would look much like the ERC721 individual link etherscan has, example:
https://etherscan.io/token/0x06012c8cf97bead5deae237070f9587f8e7a266d?a=1470604

The difference between ERC721 and ERC1155 is that each transfer also contains an amount since tokens can be sub-divisible. An example of an ERC1155 contract with sourcecode is here: 

https://etherscan.io/address/0x559604845ffc64a05f780ead75249c377b1dae57

### Actual behaviour

N/A

**Comment by karelstriegel** [comment]
Upvote +1

**Comment by timdierckxsens** [comment]
+2

**Comment by chejazi** [comment]
+3!

**Comment by alexsyo** [comment]
+4

**Comment by vbaranov** [comment]
Implemented as a premium feature and available on xDai instance.
https://docs.blockscout.com/for-projects/premium-features/erc-1155-support
