### ISSUE TITLE
Current page for paginated tables is reset after refresh

### ISSUE THREAD

**Issue by goodsoft** [blockscout/blockscout#2453]
Pagination in Web UI is implemented using common component.
Current page parameters are correctly retained between refreshes, and you see the same page you were on, but page indicator is being reset to `Page 1`.

### Steps to reproduce

- Open some page with a table with more than 50 items, e.g. https://blockscout.com/poa/core/address/0xe87e46032847e097f5bb51404d19a0449c704ee8/transactions
- Switch to page 2.
- Note currently displayed transactions and block numbers.
- Refresh page.
- Note that transactions are the same as before refresh.

### Expected behaviour

Page indicator stays at `Page 2` after refresh.

### Actual behaviour

Page indicator is being reset to `Page 1`.

**Comment by saneery** [comment]
@goodsoft @vbaranov 
Maybe we should reset filter after refresh? Just show the first page with an actual list?

We can pass page number by param, but if we, for example, show `Page 3` after a refresh, we need to calculate `Prev` url

**Comment by vbaranov** [comment]
Fixed in the new UI.
