### ISSUE TITLE
Filter addresses in transactions/transfers list

### ISSUE THREAD

**Issue by vbaranov** [blockscout/blockscout#2542]
Add the ability to filter by address on

- *transactions* tab of address page
- *token transfers* tab of token page

![Screenshot 2019-08-09 at 15 28 55](https://user-images.githubusercontent.com/4341812/62778905-6b656000-baba-11e9-9e04-e1ee76b9e6fc.png)

Relates to https://github.com/poanetwork/blockscout/issues/425

**Comment by ulyanas** [comment]
In the works with "Advanced filters" feature
