### ISSUE TITLE
Add the list of JSON RPC calls Blockscout makes to the node

### ISSUE THREAD

**Issue by vbaranov** [blockscout/blockscout#2571]
Add *.md* document to the `./docs` folder with the list of JSON RPC calls Blockscout makes to Ethereum node

**Comment by Dbhardwaj99** [comment]
Yo is this issue still open? Would love to contribute

**Comment by vbaranov** [comment]
https://docs.blockscout.com/for-developers/information-and-settings/node-tracing-json-rpc-requirements
