### ISSUE TITLE
[Feature request] Display full timestamps

### ISSUE THREAD

**Issue by phahulin** [blockscout/blockscout#2630]
In addition to relative timestamps (`5 seconds ago`, `10 seconds ago`, etc) of blocks and transactions, please display the full actual timestamp. It'd be great to have it near relative timestamp, but if there's not enough free space on the page, mouse hover also seems OK.

Example:
  * list of recent blocks - only relative timestamps are displayed :cry: 

![Blocks list](http://i.imgur.com/W9RhctB.png)

  * page of a single block - both relative and absolute timestamp are displayed :+1: 
![Individual block](http://i.imgur.com/6VuFVfY.png)

-----

Other pages where I've seen only relative timestamps
  - [ ] https://blockscout.com/poa/core/blocks :grey_exclamation:  please don't use hover here
  - [ ] https://blockscout.com/poa/core/reorgs :grey_exclamation: please don't use hover here
  - [ ] https://blockscout.com/eth/mainnet/uncles
  - [ ] https://blockscout.com/eth/mainnet/txs
  - [ ] https://blockscout.com/poa/core/address/0x28e7605a631441870e80a283aa43ae4145f82cc3/validations
  - [ ] https://blockscout.com/eth/mainnet/address/0x71d8bb4a2695407983f309d7b22cf552fbdad0e4/transactions
  - [ ] https://blockscout.com/poa/core/address/0xe87e46032847e097f5bb51404d19a0449c704ee8/internal_transactions

**Comment by vbaranov** [comment]
This has been implemented in the new UI. Live example https://eth.blockscout.com/blocks.
