### ISSUE TITLE
"Go to last page" button

### ISSUE THREAD

**Issue by SiddigZeidan** [blockscout/blockscout#2739]
BlockScout already has "First page" button and functionality, but no "Last Page" button. 

![image](https://user-images.githubusercontent.com/4807398/65773298-09b09200-e10a-11e9-8c5d-1dd981847240.png)

It would be useful especially in pages like this where there are 100k+ transactions, and the viewer would want to see when the first transactions happened.

https://blockscout.com/poa/core/address/0xdead88167bd06cbc251fb8336b44259c6407dd07/transactions

**Comment by pricillapb** [comment]
Help

**Comment by vbaranov** [comment]
The last missing piece of #1930
