### ISSUE TITLE
A few improvements

### ISSUE THREAD

**Issue by zmitton** [blockscout/blockscout#2774]
### Environment
Ethereum Classic

### Steps to reproduce
I have made thousands of transactions the past week (for a required ETC network process) and Blockscout was a life saver - Thank you.

### Features / Bugs
Some issues I came across when dealing with very "busy" accounts:
They do not always show their balance properly ([this account](https://blockscout.com/etc/mainnet/address/0x4830ddf0cb309944b39633e97e673f81fb20a798/transactions) should have at least 5 Ether in it). It would be nice to know that it is _loading_ (if thats whats happening) instead of displaying zero.

Also, the pdf does not download for large lists of transactions. It usually gives some sort of error after waiting a while. Maybe this is hard to fix. A useful workaround would be to have an _exact_ transaction count displayed, or a way to page far, far ahead (i.e. to see the txs in the opposite order, because often the first few did some useful setup, and the next x thousand were all the same).

finally a few features that no other block explorers seem to have (which I think would be useful), is transactionRoot, storageRoot, ReceiptsRoot, or stateRoots. It would be nice to see them displayed, and even better if they were searchable. Just some ideas, feel free to close if not interested. Thanks!

**Comment by vbaranov** [comment]
@zmitton thanks for the feature request and bugs report

>They do not always show their balance properly (this account should have at least 5 Ether in it). It would be nice to know that it is loading (if thats whats happening) instead of displaying zero.

The account's balance depends on internal transactions fetcher. However, internal transactions fetcher works independently from transactions fetcher and thus it can be some delay in displaying of a proper account balance. For now, I see a positive balance on that account. We could display a warning under an account balance if not all internal transactions are fetched. But it should be researched, whether it will cause performance problems or not.

>Also, the pdf does not download for large lists of transactions. It usually gives some sort of error after waiting a while. Maybe this is hard to fix. A useful workaround would be to have an exact transaction count displayed, or a way to page far, far ahead (i.e. to see the txs in the opposite order, because often the first few did some useful setup, and the next x thousand were all the same).

Yes, I agree, that there is a lack of the "Last" button in the pagination. It is the last missing piece of pagination feature. Related issues https://github.com/poanetwork/blockscout/issues/1930, https://github.com/poanetwork/blockscout/issues/2739

>finally a few features that no other block explorers seem to have (which I think would be useful), is transactionRoot, storageRoot, ReceiptsRoot, or stateRoots. It would be nice to see them displayed, and even better if they were searchable.

I've created a separate issue for that https://github.com/poanetwork/blockscout/issues/2778

**Comment by zmitton** [comment]
Awesome Victor!
> The account's balance depends on internal transactions fetcher

That makes sense to me. The problem here is that the account has ~30,000 transactions. Unlike bitcoin, you can easily get the current balance from the state (rpc method `eth_getBalance`) which might be less strain on your servers.
