### ISSUE TITLE
Add "Verify with other explorers" to "Tx not found" page

### ISSUE THREAD

**Issue by phahulin** [blockscout/blockscout#2861]
Tx page has "Verify with other explorers" section
![jW4lzhU](https://user-images.githubusercontent.com/2278876/68929906-51fd3f80-079e-11ea-8c2b-88d995d5a2f9.png)

Please add the same section on the page which is displayed when tx is not found in blockscout.
![miNhf4b](https://user-images.githubusercontent.com/2278876/68929960-70633b00-079e-11ea-9016-5e5299595ec4.png)

**Comment by vbaranov** [comment]
Implemented in the new UI 😉.

**Comment by phahulin** [comment]
:laughing:
But... is the new UI already deployed to https://eth.blockscout.com/ ? I can't find any buttons/links:

![image](https://github.com/blockscout/blockscout/assets/2278876/17770729-d705-4542-8c81-bc1dbd61c5ce)

**Comment by vbaranov** [comment]
Pardon, too early to close.
