### ISSUE TITLE
Errors and Timeouts when indexing

### ISSUE THREAD

**Issue by ImrieA** [blockscout/blockscout#2919]
I have a fully synced archive Parity node that I am trying to use with Blockscout. However I get many errors like the below three when Blockscout is running. 

What can I do to mitigate this? Is this a non-optimised Postgres issue?  

Will the indexer eventually fully index the chain despite these errors? (i.e. keep retrying after a timeout)

The first error happens frequently - several times per 10 mins

`2019-12-10T23:15:12.554 application=ethereum_jsonrpc [error] 413 Request Entity Too Large returned from single request batch.  Cannot shrink batch further.`

`2019-12-10T23:12:38.699 application=indexer fetcher=block_catchup first_block_number=9052787 last_block_number=9052778 step=receipts [error] failed to fetch: :timeout. Retrying.`

`2019-12-10T23:18:09.786 application=indexer fetcher=block_realtime block_number=9085403 step=balances [error] failed to fetch: :timeout.  Block will be retried by catchup indexer.`

In terms of physical hardware it should not be a bottleneck: 64GB RAM with modern multi core CPU and enterprise SSD disks.

### Environment

* Elixir & Erlang/OTP versions (`elixir -version`): 1.9.4
* Operating System: Ubuntu 18
* Blockscout Version/branch: 2.1.1 Beta

Thanks

**Comment by vbaranov** [comment]
Eventually, the Blockscout indexer should index the whole chain. You can track the progress on DB level with this query:
```
SELECT COUNT(1) FROM blocks WHERE internal_transactions_indexed_at IS NULL and consensus;
```

This count should tend to 0 ideally.

Your hardware, indeed, is strong enough, if it has >= 4 vCPU.
To mitigate the issue I would suggest taking a look at the Parity archive node configuration. Specifically, to the number of `server_threads`. As far as I know, for the best performance of JSON requests to the node someone should keep `server_threads` parameter equal to the number of virtual CPU that hardware provides. And also be sure that your Parity node uses all of the available memory on the server, eg. you have no `cache_size` parameter configured or if it is configured it is not highly limited. Also, if your node and the application are on the same machine you can use IPC transport instead of JSON RPC https://github.com/poanetwork/blockscout/pull/2791.

**Comment by ImrieA** [comment]
Thanks for the feedback. I have increased the `server_threads` but the error is not  stopped or reduced. `cache_size` was already setup to use 40+ GB RAM.
I'm now trying to take the `ipc` route however reaching more problems. Parity and Blockscout are on the same machine and the .ipc file is at `/mnt/volumes/parity/jsonrpc.ipc`

So I try and run blockscout with:
`export ETHEREUM_JSONRPC_JSON_RPC_TRANSPORT=ipc`
`export IPC_PATH=/mnt/volumes/parity/jsonrpc.ipc`
`mix phx.server`


I then get an ocean of errors in the console (multiple errors like this per second). Parity is now running with `ipc-apis=all` . When blockscout is running despite all the errors I can see the Parity console increase in `req/s` when blockscout starts so I think it is connecting okay and not a node issue.

Any tips to resolve this?
`
2019-12-11T21:21:35.417 fetcher=block_reward count=10 [error] Task #PID<0.854.0> started from Indexer.Fetcher.BlockReward terminating
** (stop) exited in: GenServer.call(#PID<0.402.0>, {:request, "[{\"id\":0,\"jsonrpc\":\"2.0\",\"method\":\"trace_block\",\"params\":[\"0x8AB432\"]},{\"id\":1,\"jsonrpc\":\"2.0\",\"method\":\"trace_block\",\"params\":[\"0x8AB43A\"]},{\"id\":2,\"jsonrpc\":\"2.0\",\"method\":\"trace_block\",\"params\":[\"0x8AB43B\"]},{\"id\":3,\"jsonrpc\":\"2.0\",\"method\":\"trace_block\",\"params\":[\"0x8AB450\"]},{\"id\":4,\"jsonrpc\":\"2.0\",\"method\":\"trace_block\",\"params\":[\"0x8AB451\"]},{\"id\":5,\"jsonrpc\":\"2.0\",\"method\":\"trace_block\",\"params\":[\"0x8AB452\"]},{\"id\":6,\"jsonrpc\":\"2.0\",\"method\":\"trace_block\",\"params\":[\"0x8AB453\"]},{\"id\":7,\"jsonrpc\":\"2.0\",\"method\":\"trace_block\",\"params\":[\"0x8AB454\"]},{\"id\":8,\"jsonrpc\":\"2.0\",\"method\":\"trace_block\",\"params\":[\"0x8AB455\"]},{\"id\":9,\"jsonrpc\":\"2.0\",\"method\":\"trace_block\",\"params\":[\"0x8AB458\"]}]"}, 5000)
    ** (EXIT) time out
    (elixir) lib/gen_server.ex:1009: GenServer.call/3
    (ethereum_jsonrpc) lib/ethereum_jsonrpc/ipc.ex:66: EthereumJSONRPC.IPC.request/2
    (poolboy) /ethUser/blockscout2/blockscout/deps/poolboy/src/poolboy.erl:84: :poolboy.transaction/3
    (ethereum_jsonrpc) lib/ethereum_jsonrpc/request_coordinator.ex:86: anonymous fn/3 in EthereumJSONRPC.RequestCoordinator.perform/4
    (ethereum_jsonrpc) lib/ethereum_jsonrpc/request_coordinator.ex:106: EthereumJSONRPC.RequestCoordinator.trace_request/2
    (ethereum_jsonrpc) lib/ethereum_jsonrpc/parity.ex:24: EthereumJSONRPC.Parity.fetch_beneficiaries/2
    (indexer) lib/indexer/fetcher/block_reward.ex:94: Indexer.Fetcher.BlockReward.run/2
    (elixir) lib/task/supervised.ex:90: Task.Supervised.invoke_mfa/2
    (elixir) lib/task/supervised.ex:35: Task.Supervised.reply/5
    (stdlib) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
1`

**Comment by vbaranov** [comment]
@ImrieA does the count from the query, I posted before, tends to zero?

**Comment by ImrieA** [comment]
@vbaranov the result of this command is currently 24623 and yes it is reducing

**Comment by vbaranov** [comment]
It is a good sign. After the chain will be fully indexed, the number of requests to the node will significantly reduce and, I suppose, the errors will disappear.

**Comment by ImrieA** [comment]
I was expecting the result of the query to be a much larger number (in the millions)? This is the Ethereum main net and my Blockscout has only been running a few days

**Comment by vbaranov** [comment]
Oh, it is Mainnet... Yes, there should be > 9 millions blocks in the table. It means that not all blocks are imported yet. The full indexing of Mainnet chain will take 30 - 40 days.

**Comment by vbaranov** [comment]
Why no to use https://blockscout.com/eth/mainnet ?

**Comment by ImrieA** [comment]
Really I am curious to set up Blockscout locally on my own network as a project.

Do you have any tips on the challenge of syncing 9,000,000 blocks? Any lessons learnt from syncing your one . Thanks

Will keep updating here about the above errors and if they go away. Still can’t use IPC

**Comment by vbaranov** [comment]
Please update Blockscout backend to [v6](https://github.com/blockscout/blockscout/releases/tag/v6.5.0-beta) - it has more efficient indexer.
