### ISSUE TITLE
Indexer fails to send Postgres notification due to excessive payload size

### ISSUE THREAD

**Issue by enlight** [blockscout/blockscout#2945]
We've been using Blockscout at Loom Network to index a few of our blockchains, it's been a bit tricky to keep the Blockscout indexer from blowing up because our Web3 JSON-RPC interface doesn't perfectly emulate either geth or parity. After https://github.com/poanetwork/blockscout/pull/2449 was merged in we could finally decouple the webapp from the indexer, but unfortunately we quickly ran into a pretty big limitation in the Postgres based event broadcasting.

The indexer frequently errors out with `payload string too long` when attempting to send the event payload via Postgres [`select pg_notify`](https://github.com/poanetwork/blockscout/blob/master/apps/explorer/lib/explorer/chain/events/db_sender.ex#L24). It seems that Postgres limits the notification payload size to 8000 bytes, and the payloads in Blockscout frequently exceed that size. The typical block/tx data size on our chains is probably smaller than on Ethereum so I expect that this issue isn't limited to our blockchains. From my brief investigation of `pg_notify` it appears that it was intended to broadcast row IDs that have been inserted/updated rather than the data in those rows.

### Environment

* Elixir & Erlang/OTP versions (`elixir -version`): Elixir 1.9.0, Erlang/OTP 22 [erts-10.4.3] [source] [64-bit] [smp:2:2] [ds:2:2:10] [async-threads:1] [hipe]
* Operating System: Alpine Linux
* Blockscout Version/branch: https://github.com/poanetwork/blockscout/commit/a4e6eebac93c60d80aa01a9f133d51b05aeb38d7

### Steps to reproduce

Start separate instances of the indexer & webapp as mentioned in https://github.com/poanetwork/blockscout/pull/2449 and point them at Ethereum mainnet, or Rinkeby.

### Expected behaviour

The indexer should successfully send all blocks & txs it fetches through the Postgres notification mechanism.

### Actual behaviour

The indexer frequently errors out with `payload string too long` while attempting to execute `select pg_notify`.

**Comment by adean-consensys** [comment]
Adding comment that this directly correlates with issue https://github.com/blockscout/blockscout/issues/4736 in that when the `payload string too long` message comes across, the dynamic updates in the UI fails and will only catch up when the SQL call returns without error

**Comment by 0x13e** [comment]
I also just started hitting this after running the indexer headless for a few days. At this point the Indexer.Block.Realtime.Fetcher is just in an infinite termination loop as the large pgsql notification will never complete.
