### ISSUE TITLE
Blockscout doesn't catch account ETH balance change.

### ISSUE THREAD

**Issue by chebykin** [blockscout/blockscout#2998]
Blockscout doesn't catch up account ETH balance. I tried v2.1.1-beta and v3.0.0-beta. The latest one is still syncing, so I'm not sure, probably it will fetch the balance later. I will update the ticket when it finishes.
The case is when an address receives 1 ETH inside an internal transaction.

## v2.1.1 (already synced blockscout)

Blockscout says 0 balance
`
ubuntu@explorer:~$ curl -H "content-type: application/json" -X POST --data '{"id":0,"jsonrpc":"2.0","method":"eth_getBalance","params":["0x5489905ac8fac07b9b6ad40f4293c370c71c9f6a","latest"]}' http://localhost:4001/api/eth_rpc
{"jsonrpc":"2.0","result":"0x0","id":0}
`

Parity responds correctly
`
ubuntu@explorer:~$ curl -H "content-type: application/json" -X POST --data '{"id":0,"jsonrpc":"2.0","method":"eth_getBalance","params":["0x5489905ac8fac07b9b6ad40f4293c370c71c9f6a","latest"]}' http://localhost:8545
{"jsonrpc":"2.0","result":"0xde0b6b3a7640000","id":0}
`

The TX when the address received 1 ETH https://explorer.yalland.com/address/0x5489905ac8fac07b9b6ad40f4293c370c71c9f6a/internal_transactions

## v3.0.0 (blockscout still syncing)
Here is CLI check log for syncing blockscout deployment:

Blockscout says "Balance not found"
`
ubuntu@explorer:~/blockscout$ curl -H "content-type: application/json" -X POST --data '{"id":0,"jsonrpc":"2.0","method":"eth_getBalance","params":["0x5489905ac8fac07b9b6ad40f4293c370c71c9f6a","latest"]}' http://localhost:4001/api/eth_rpc
{"jsonrpc":"2.0","error": "Balance not found","id": 0}
`

Parity responds correctly
`
ubuntu@explorer:~/blockscout$ curl -H "content-type: application/json" -X POST --data '{"id":0,"jsonrpc":"2.0","method":"eth_getBalance","params":["0x5489905ac8fac07b9b6ad40f4293c370c71c9f6a","latest"]}' http://localhost:8545
{"jsonrpc":"2.0","result":"0xde0b6b3a7640000","id":0}
`

The TX when the address received 1 ETH http://167.71.37.90:4001/address/0x5489905ac8fac07b9b6ad40f4293c370c71c9f6a/internal_transactions

### Environment 1st

* Elixir & Erlang/OTP versions (`elixir -version`): Elixir 1.9.1 (compiled with Erlang/OTP 21)
* Operating System: Ubuntu 18.04.3 LTS
* Blockscout Version/branch: tag: v2.1.1-beta

### Environment 2nd

* Elixir & Erlang/OTP versions (`elixir -version`): Elixir 1.10.0 (compiled with Erlang/OTP 21)
* Operating System: Ubuntu 18.04.4 LTS
* Blockscout Version/branch: tag: v3.0.0-beta

**Comment by chebykin** [comment]
The problem was solved by sending more ETH to the account 😀

**Comment by chebykin** [comment]
Actually, I'm not sure about keeping this ticket closed or not

**Comment by vbaranov** [comment]
@chebykin thanks, for letting us know. Let's keep it open for a while. We will try to reproduce this issue.

**Comment by vbaranov** [comment]
This should be fixed. Let us know if you still experience the issue with the latest [release](https://github.com/blockscout/blockscout/releases).
