### ISSUE TITLE
ERC-721 Token Ids not indexed

### ISSUE THREAD

**Issue by ShabanShaame** [blockscout/blockscout#3050]
*Describe your issue here.*

### Environment

* Elixir & Erlang/OTP versions (`elixir -version`):
* Operating System: All Not Relevant
* Blockscout Version/branch: Ethereum/Mainet

### Steps to reproduce

This address has for example 2 blockchaincuties (ERC-721)
https://www.orbexplorer.com/address/?address=0x7f7EED1fcBb2C2cf64d055eED1Ee051DD649C8e7

on contract : 0xd73be539d6b2076bab83ca6ba62dfe189abc6bbe

When query balance on blockscout API
https://blockscout.com/eth/mainnet/api?module=account&action=tokenbalance&contractaddress=0xd73be539d6b2076bab83ca6ba62dfe189abc6bbe&address=0x7f7EED1fcBb2C2cf64d055eED1Ee051DD649C8e7

We get a result of "2" Which is the sum of tokens but not the tokens themselves

### Expected behaviour

Get a list of tokenId's instead of SUM token Id

### Actual behaviour

For ERC-721 tokens the total number of owned token are not very relevant. While query for a balance a list of token ids would be much more useful

**Comment by xxsodapopxx5** [comment]
Has there been any progress made on this? I am trying to access this data via the database and I don't believe it is indexed properly. 

I am looking at the blockscout postgres database in the address_current_token_balances table and the token_id value is null for all records. I still see the field 'value' containing the sum balance of the NFT's per address per NFT contract - I believe this balance should always be 1, and the token_id field should be populated. Currently this is not the case.
