### ISSUE TITLE
Wrong constructor arguments for verified contract on Mainnet

### ISSUE THREAD

**Issue by varasev** [blockscout/blockscout#3082]
I've verified a contract https://blockscout.com/eth/mainnet/address/0x9BC4a93883C522D3C79c81c2999Aab52E2268d03/contracts

But currently `Constructor Arguments` displays wrong points:

Arg [0] (address) : 0xe338b8fc6e994ca210c9bb7bdca249b465942250
Arg [1] (address) : 0x14b4d2ee5aeaea9505df5e855c9210bf472495af
Arg [2] (address) : 0x86edd0c110d1fc7f8a5e1108623b3b1b4e3740f9
Arg [3] (address) : 0x0df05adac0159e215111696339ad4998e5871b3d
Arg [4] (address) : 0x3cfe51b61e25750ab1426b0072e5d0cc5c30aafa
Arg [5] (address) : 0x0218b706898d234b85d2494df21eb0677eaea918

These actually should be

Arg [0] (address) : 0x86edd0c110D1Fc7F8A5e1108623b3B1B4E3740f9
Arg [1] (address) : 0x0DF05ADaC0159e215111696339AD4998e5871B3D
Arg [2] (address) : 0x3cFE51b61E25750ab1426b0072e5D0cc5C30aAfA
Arg [3] (address) : 0x0218B706898d234b85d2494DF21eB0677EaEa918
Arg [4] (address) : 0x86edd0c110D1Fc7F8A5e1108623b3B1B4E3740f9
Arg [5] (address) : 0x0DF05ADaC0159e215111696339AD4998e5871B3D

**Comment by vbaranov** [comment]
One more example: https://blockscout.com/poa/xdai/address/0x857DD07866C1e19eb2CDFceF7aE655cE7f9E560d/contracts

**Comment by rabib** [comment]
I'm having the same issue. https://cchain.explorer.avax.network/address/0xe1376DeF383D1656f5a40B6ba31F8C035BFc26Aa/contracts

Constructor arguments should display:
```Arg [0] (address) : 0xFC0829E792b0D10DF95B895d56FaD4712DA30B25
Arg [1] (uint256) : 10000000000000000000
Arg [2] (uint32) : 20```
