### ISSUE TITLE
error on pending tx in besu

### ISSUE THREAD

**Issue by Matias-Gallardo** [blockscout/blockscout#3117]
I have a problem with internal transactions, it would be a good option to disable it easily.

### Environment

* Elixir & Erlang/OTP versions (`elixir -version`): 
Erlang: Installed: 1:22.3.2-1
Elixir Installed: **1.10.3-1**
* Operating System: Ubuntu
* Blockscout Version/branch: master

### Steps to reproduce

Connect the explorer to a besu hyperledger node (private blockchain).  
You will get this error: 
fetcher=pending_transaction [error] Task Indexer.Fetcher.PendingTransaction started from #PID<0.23210.1> terminating
** (CaseClauseError) no case clause matching: {:error, %{"error" => %{"code" => -32601, "message" => "Method not found"}, "id" => 1, "jsonrpc" => "2.0"}}
    (indexer 0.1.0) lib/indexer/fetcher/pending_transaction.ex:120: Indexer.Fetcher.PendingTransaction.task/1
    (elixir 1.10.3) lib/task/supervised.ex:90: Task.Supervised.invoke_mfa/2
    (elixir 1.10.3) lib/task/supervised.ex:35: Task.Supervised.reply/5
    (stdlib 3.12.1) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
Function: #Function<2.75598939/0 in Indexer.Fetcher.PendingTransaction.handle_info/2>
    Args: []

TxPool and debug are enabled in the api (ws and http) of the node.

### Expected behaviour

i should not get this error

### Actual behaviour

I get an error and pending transaction fail

**Comment by vbaranov** [comment]
There is an option to disable pending transactions fetcher via runtime variable `INDEXER_DISABLE_PENDING_TRANSACTIONS_FETCHER=true`.
