### ISSUE TITLE
Unable to "Verify&Publish" source code

### ISSUE THREAD

**Issue by drortirosh** [blockscout/blockscout#3211]
*Describe your issue here.*

The "Verify&Publish" for blockscout suggests to use source flattener, and upload the entire source as a single file.
However, with the latest solc version (0.6.x), this is sometimes NOT possible:

The "opengsn" project uses the ABIEncoderV2, but some external sources don't use it.
As a result, when flattening the file the "pragma ABIEncoderV2" is applied to entire code, instead of just parts.
The consequence is that the generated bytecode for flattened file is different.
We already deployed the contract to **mainnet**, **kovan**, **ropsten** along with source code - but currently we found out that we **can't upload source code** for the XDAI deployment.

For deployment to ethereum network, we uploaded the "standard-json" file that was used to compile, and thus kept the separate files separate.
https://kovan.etherscan.io/address/0xA17C8F25668a5748E9B80ED8Ff842f8909258bF6#code
The same contract was deployed to xDAI, but currently we can't upload its sources: https://blockscout.com/poa/xdai/address/0xA58B6fC9264ce507d0B0B477ceE31674341CB27e/contracts

### Steps to reproduce
```
git clone https://github.com/opengsn/gsn.git && cd gsn && yarn && truffle compile
```

the code is generated in build/contracts/RelayHub.sol

Then if you flatten the contracts/RelayHub.sol (and remove duplicate SPDX comments and "pragma ABIEncoderV2" , since flatteners don't recognize them yet) and compile it, you get slightly different output, enough to be rejected by "Verify&Publish" ... 

### Expected behaviour

Verify&Publish should accept a single "json-standard" file instead of input file.
Simply, if the input starts with ` {"language":"Solidity","sources":... `
try to parse it as a **json-standard** input.

**Comment by vbaranov** [comment]
@drortirosh thanks for a thorough description. Sounds like it is time to allow verification with **standard JSON input** in Blockscout. I will start working on it soon.

**Comment by acrylix** [comment]
@vbaranov any updates on accepting solidity standard JSON inputs for contract verifications?

**Comment by vbaranov** [comment]
@drortirosh @acrylix we added integration with Sourcify tool. Now it is possible to verify contracts by attaching source files without flattening them together with JSON with compilation metadata. This feature is available on xDai instance of Blockscout.

**Comment by xuhcc** [comment]
@vbaranov Compilation metadata and standard JSON input are different things. Unfortunately Sourcify doesn't yet support the latter: https://github.com/ethereum/sourcify/issues/319

**Comment by vbaranov** [comment]
@xuhcc
 
> Compilation metadata and standard JSON input are different things

yeah, that is right. Though, I like Sourcify's approach with a single files drop zone. It makes the verification process faster. From your perspective, is it harder to get JSON with metadata vs Solidity Standard JSON input file? Just from curiosity, why do you like the second approach more?

**Comment by xuhcc** [comment]
I'm using buidler/hardhat for development and it generates standard JSON input during the compilation, so it's really easy for me to provide standard JSON to a verification service. There's also a tool called [solt](https://github.com/hjubb/solt) that can generate standard JSON. But I'm not aware of a simple way to generate metadata JSON in my development environment.

Another reason is that dapp I'm currently working on consists of ~40 contracts and it's tedious to upload them one by one. With standard JSON you can upload just one file which includes all sources.

**Comment by drortirosh** [comment]
All is true.
The idea is not to optimize the verification time, but the DEVELOPER time: 
The compilers (hardhat, truffle) uses a "standard json input" file, and save it.
I don't want to have yet another tool to generate the input for the source verifier - it should be able to use the development toolchain.
The only drawback of the "standard json" is that it doesn't comain the compiler version, and as developers we have to enter it manually.

I really don't care to use the OUTPUT of the compiler instead (it contains all source code, binaries - and also metadata info, such as compiler version in use) - but in that it differs between hardhat and truffle.

**Comment by mudgen** [comment]
Any progress on this?   I made a duplicate issue here: #3587

**Comment by rkalis** [comment]
I want to add to this thread that I'll gladly add blockscout verification to [truffle-plugin-verify](https://github.com/rkalis/truffle-plugin-verify) if you guys add a verify API that uses Solidity Standard Input JSON (similar to Etherscan). That's what I use for the Etherscan verification, and I don't want the usage between Etherscan and Blockscout verification in the plugin to differ too much.

@vbaranov by integration with sourcify, do you mean that if it's verified in sourcify, that any Blockscout explorer automatically picks that up as well? I've been wanting to add sourcify verification to the plugin as well, so if that automatically propagates to blockscout that'd be very cool.

**Comment by hellwolf** [comment]
whelp, it's so painful to verify sources at the moment.

**Comment by d10r** [comment]
> @vbaranov by integration with sourcify, do you mean that if it's verified in sourcify, that any Blockscout explorer automatically picks that up as well? I've been wanting to add sourcify verification to the plugin as well, so if that automatically propagates to blockscout that'd be very cool.

+1 for this

**Comment by d10r** [comment]
[Here's an example](https://blockscout.com/poa/xdai/address/0x63e62989D9EB2d37dfDB1F93A22f063635b07d51/contracts) for a contract I failed to verify on Blockscout (multiple attempts in both single flattened file and multi-file mode), but succeeded to verify through https://sourcify.dev/.  
[Entry on sourcify](https://repo.sourcify.dev/contracts/partial_match/100/0x63e62989D9EB2d37dfDB1F93A22f063635b07d51/sources/)

Would love to get this verified on blockscout too in order to see the full beauty of [txs like this](https://blockscout.com/xdai/mainnet/tx/0x604287cbf6cefeb9e4813d4887ffc408fd1f841d43f2327568731812e1efa15a/logs) (starts an _airstreem_ / streaming airdrop).

**Comment by DaveAppleton** [comment]
Can I add to all this, that with Blockscout  being the default explorer on Polygon this issue has become way more important.

**Comment by heri16** [comment]
Is blockscout project dead?

**Comment by helderjnpinto** [comment]
any development in this part verify and publish smart contracts ? also read from proxy implementations?
