### ISSUE TITLE
Production Ready Docker Image

### ISSUE THREAD

**Issue by bahadirbb** [blockscout/blockscout#3332]
On documentation, it is mentioned that the current generated docker image should not be used in production. We are planning to use Blockscout in a kubernetes environment and we will be happy to do steps that are required to create a production-ready docker image.

Why is the current docker image tagged as "not production-ready"? And what needs to be done to make it ready for production?

**Comment by RilRil** [comment]
Any comments on the above ? 

Still seeing this 
```# BlockScout Docker Integration

This integration is not production ready, and should be used for local BlockScout deployment only.
```

**Comment by jacobhjkim** [comment]
https://hub.docker.com/r/blockscout/blockscout

Is this the official docker image?

**Comment by vbaranov** [comment]
> Is this the official docker image?

yes

**Comment by vbaranov** [comment]
Docker integration is production-ready. We provide various docker-compose configs for different clients https://github.com/blockscout/blockscout/tree/master/docker-compose.
