### ISSUE TITLE
Ethereum Classic: 504 Gateway Time-out while trying to verify contract in Kotti Network

### ISSUE THREAD

**Issue by racetrack0616** [blockscout/blockscout#3338]
Trying to use an API to verify contract but always results 504 Gateway Time Out

`?module=contract&action=verify&addressHash={addressHash}&name={name}&compilerVersion={compilerVersion}&optimization={false}&contractSourceCode={contractSourceCode}
`

**Comment by racetrack0616** [comment]
None of you are interested in answering my concerns? Pathetic

**Comment by sirpy** [comment]
i also get 504 when trying to verify contracts via API on a explorer.fuse.io
verifying through UI works but also takes long time
1. where could we increase the api timeout?
2. is verification supposed to take long  time? anything to make it faster?

**Comment by habdelra** [comment]
In my experience we have a slew of contracts that we verify for each deployment. The first one that tries to verify fails with a 504 and the rest succeed. If I reverify the failed one a few minutes later it succeeds. I wonder if the problem is that there is an async job that is trying to verify and the web server just times out waiting for that async job to finish...

**Comment by sirpy** [comment]
@vbaranov this must be some kind of timeout definition, it stops after 1 minute.
where are the timeout settings for blockscout?

**Comment by vbaranov** [comment]
@sirpy you can set idle_timeout as described here https://elixirforum.com/t/request-to-phoenix-server-times-out-after-60-seconds/20851/2. By default, it is not set up and the default value is 60 seconds.

**Comment by eric-convergence** [comment]
> @sirpy you can set idle_timeout as described here https://elixirforum.com/t/request-to-phoenix-server-times-out-after-60-seconds/20851/2. By default, it is not set up and the default value is 60 seconds.

Hi @vbaranov , I did the same and was able to resolve the issue. However, is it a must to keep the connection alive for the contract to be verified? I am think if it's possible for the request to be async.

**Comment by vbaranov** [comment]
The issue with contract verification on ETC instances of Blockscout should be resolved. Please try to verify the contracts.
