### ISSUE TITLE
Failed to compile priv/libsecp256k1_nif.so' failed

### ISSUE THREAD

**Issue by zalam003** [blockscout/blockscout#3593]
Code deployed from 2 days ago (aff90fb) is not compiling.  It is throwing an error when compiling ibsecp256k1.

### Environment

* Elixir & Erlang/OTP versions (`elixir -version`):

```
Erlang/OTP 23 [erts-11.1] [source] [64-bit] [smp:4:4] [ds:4:4:10] [async-threads:1] [hipe]
Elixir 1.11.2 (compiled with Erlang/OTP 21)
```

* Operating System:  Ubuntu 18.04.5 LTS
* Blockscout Version/branch: master / aff90fb

### Steps to reproduce

While running:
```
mix do deps.get, local.rebar --force, deps.compile, compile
```

get the following errors:
```
checking for gcc... gcc
checking whether the C compiler works... no
configure: error: in `/opt/blockscout/deps/libsecp256k1/c_src/secp256k1':
configure: error: C compiler cannot create executables
See `config.log' for more details
make: *** [priv/libsecp256k1_nif.so] Error 77
Makefile:30: recipe for target 'priv/libsecp256k1_nif.so' failed
==> libsecp256k1
warning: Mix compiler :make_bindings was supposed to return {:ok | :noop | :error, [diagnostic]} but it returned :error
Compiling 1 file (.erl)
src/libsecp256k1.erl:146: Warning: function not_loaded/1 is unused
Generated libsecp256k1 app

...

warning: :libsecp256k1.ecdsa_recover_compact/4 is undefined (module :libsecp256k1 is not available or is yet to be defined)
  lib/indexer/transform/blocks.ex:84: Indexer.Transform.Blocks.recover_pub_key/2

20:59:07.713 [warn]  The on_load function for module libsecp256k1 returned:
{:error,
 {:load_failed,
  'Failed to load NIF library: \'/opt/blockscout/_build/prod/lib/libsecp256k1/priv/libsecp256k1_nif.so: cannot open shared object file: No such file or directory\''}}

Compilation failed due to warnings while using the --warnings-as-errors option
```

### Expected behaviour

Compile without any errors

### Actual behaviour

I am upgrading from a previous 3.5.1-beta release (a week ago or so).  I did not see this error in code from recent past.  I have seen it on older version (v1.x).

The error details are noted above.

**Comment by vbaranov** [comment]
@zalam003 you should try https://github.com/poanetwork/blockscout/issues/1352#issuecomment-454580893 if you didn't yet.

**Comment by zalam003** [comment]
@vbaranov I am not running on a docker.  I downgraded Elixir to 1.10.4 an kept Erlang/OTP 23, which is the recommended version.  It still gives the same error.  I did not have any issues before the last merge.

**Comment by vbaranov** [comment]
@zalam003 try clean dependencies before compiling:
`mix deps.clean --all`

**Comment by zalam003** [comment]
@vbaranov  I get the same error.  

I normally run `rm -rf _build deps` before compiling.  But I have also run `mix deps.clean --all`.

**Comment by zalam003** [comment]
@vbaranov I think I have a work around:
After I ran `mix deps.get`, I compiled `secp256k1`.  Then I continued with `mix do deps.get, local.rebar --force, deps.compile, compile`.  This seemed to work and I can not start blockscout.

**Comment by zalam003** [comment]
I get this error:
```
Feb 03 23:52:30 blockscout bash[28814]: warning: :libsecp256k1.ecdsa_recover_compact/4 is undefined (module :libsecp256k1 is not available or is yet to be defined)
Feb 03 23:52:30 blockscout bash[28814]:   lib/indexer/transform/blocks.ex:84: Indexer.Transform.Blocks.recover_pub_key/2
Feb 03 23:52:30 blockscout bash[28814]: 23:52:30.765 [warn]  The on_load function for module libsecp256k1 returned:
Feb 03 23:52:30 blockscout bash[28814]: {:error, {:load_failed, 'Failed to load NIF library: \'/opt/blockscout/_build/prod/lib/libsecp256k1/priv/libsecp256k1_nif.so: undefined symbol: secp256k1_ecdsa_recoverable_signature_parse_compact\''}}
```
But blockscout is running

**Comment by zalam003** [comment]
## Here are the steps that resolve the issue.  My base installation is in `/opt/blockscout`.  Update the path as needed.

### Download dependencies
```
mix deps.get
```
### There is a bug with the compilation of secp256k1 module.  Manually compile first.
```
cd /opt/blockscout/deps/libsecp256k1/c_src; ./build_deps.sh; cd -
```
### Compile remaining dependencies
```
cd /opt/blockscout; mix do deps.get, local.rebar --force, deps.compile, compile
```

**Comment by bilogate** [comment]
problem is 
sudo apt-get install libgmp3-dev
after that libsecp256k1_nif.so error will be gone
