### ISSUE TITLE
showing source code/abi of WRONG contract.

### ISSUE THREAD

**Issue by drortirosh** [blockscout/blockscout#3642]
*Describe your issue here.*

Tried to see verified code of RelayHub contract, but it claims it is the same bytecode (and thus same source) as another contract.

### Environment
* Elixir Version: 1.11.0
* Erlang Version: 23
* BlockScout Version: v3.5.1-beta

* User Agent: `Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.150 Safari/537.36`

### Steps to reproduce

open https://explorer-mainnet.maticvigil.com/address/0x8aA57981F63a38D527DB699135bE69a48Ca103b0/contracts
This is a RelayHub contract, much like https://blockscout.com/poa/xdai/address/0x63DD60B79cb8E3d2FA20A6d2EC92e101553a3920/contracts which was verified correctly.

### Expected Behaviour

Show the right source code, or at least don't claim its source is of another contract (and let Verify&Publish)

### Actual Behaviour

However, it claims it has the same code and some other contract named "EACAggregatorProxy"
Which it obviously isn't. (try the "[Read Contract](https://explorer-mainnet.maticvigil.com/address/0x8aA57981F63a38D527DB699135bE69a48Ca103b0/read-contract)" page - the ABI is completely wrong, so all methods fail)

Somehow, it got it all wrong and think these contracts share code - which they don't.

**Comment by vbaranov** [comment]
> Show the right source code, or at least don't claim its source is of another contract (and let Verify&Publish)

@drortirosh You have to ask Matic team about returning `Verify&Publish` button on this page. Original Blockscout allows users to verify contract manually, even if it has source code sibling. You can check, for instance, here https://blockscout.com/poa/xdai/address/0x76e76F7E73F3BD42E3c2b4282B50b36E78130B4A/contracts.

**Comment by drortirosh** [comment]
Do you have a contact at the Matic team? I use the tool (blockscout), and the problem report points here..

**Comment by vbaranov** [comment]
> Do you have a contact at the Matic team? I use the tool (blockscout), and the problem report points here..

I would try to report the problem on their fork of Blockscout https://github.com/maticnetwork/blockscout
