### ISSUE TITLE
contracts api to return info about proxy contracts

### ISSUE THREAD

**Issue by sirpy** [blockscout/blockscout#3691]
If a contract is detected as proxy getsourcecode or some other api should return details about it such as
{
isProxy:true,
proxy:0x....
proxySourceCode:
}

**Comment by vbaranov** [comment]
@sirpy could you clarify what is the application of the requirement of breaking the interface of the response in case of proxy contracts and display `proxySourceCode` instead of `SourceCode`, as it is now? Is it not enough to add a boolean flag `isProxy:true` in case of proxy contract?

**Comment by sirpy** [comment]
i guess isproxy + implementatio address so its possible to fetch the implementation source, would be enough

**Comment by sirpy** [comment]
@vbaranov

**Comment by bernatfp** [comment]
@vbaranov I second this. An indication of whether it's a proxy + the implementation address should suffice. That's what Etherscan's API exposes https://docs.etherscan.io/api-endpoints/contracts#get-contract-source-code-for-verified-contract-source-codes
