### ISSUE TITLE
Mainnet: Transferring USDC from Matic network back to ETH

### ISSUE THREAD

**Issue by CallWhy816** [blockscout/blockscout#3733]
Submitted bridge transfer this morning (roughly 8 hours ago) from Matic back to ETH, USDC has not shown up.

0xeafd118ea7e2f0efa3a3a82c226aca3ada1db6589b4dcfa86e67388709d79950

Thank you 

### Environment
* Elixir Version: 1.11.0
* Erlang Version: 23
* BlockScout Version: v3.5.1-beta

* User Agent: `Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.90 Safari/537.36`

### Steps to reproduce

*Tell us how to reproduce this issue. If possible, push up a branch to your fork with a regression test we can run to reproduce locally.*

### Expected Behaviour

*Tell us what should happen.*

### Actual Behaviour

*Tell us what happens instead.*

**Comment by vbaranov** [comment]
There is no Matic support here.
