### ISSUE TITLE
POA Sokol: Getting "Internal server error" response when querying logs

### ISSUE THREAD

**Issue by pizzarob** [blockscout/blockscout#3746]
Hello. 

I am using the Blockscout ETH RPC API. I am using the `eth_getLogs` method but I receive an "Internal server error" response:

To reproduce:

```
curl -H "content-type: application/json" -X POST --data '{"id":0,"jsonrpc":"2.0","method":"eth_getLogs","params":[{"fromBlock":19959378,"toBlock":20045041,"topics":["0xdeaa91b6123d068f5821d0fb0678463d1a8a6079fe8af5de3ce5e896dcf9133d",null,null,"0x0000000000000000000000002D2C46D26c8FEc693586e067c4fC2b2DDC2b4cb3"]}]}' https://blockscout.com/poa/sokol/api/eth-rpc
```

Could anyone tell me why this is happening? If my input is not formatted correctly it seems that a different error code should be returned.

**Comment by vbaranov** [comment]
@pizzarob null values in input were causing the error. Patched with https://github.com/blockscout/blockscout/pull/3748
