### ISSUE TITLE
Energy Web Chain: Pending sends, cancels, sends from Metamask (no gas fees allowed) to no avail

### ISSUE THREAD

**Issue by Tucker13** [blockscout/blockscout#3749]
I have managed to store EWT on my Metamask account under the Energyweb RPC. I am now trying to move them to an exchange. The send to address had a pending send for about 6 hours, in which, I tried to cancel to resubmit. Cancelling posed a problem and now finally shifted to cancelling pending, I used mycrypto to try and resend and everything remains pending as if frozen. I cannot send the transaction with any gas fees from the main network. How can I get confirmations and resolve this issue and get the tokens sent???

Current Tx Hash:  0x212b3dbe227ef224632220c1ec1f06b8c6e1dbbf913b458cebb8463c75740a5f
Original (in) TX Hash: 0x81571b10bfbaa193a04d3db205456b9afdf96c9c69b8681052a5e50c1f9de00f

Thank you.

**Comment by vbaranov** [comment]
There is no EWT support here. Try to ask in https://github.com/energywebfoundation/blockscout
