### ISSUE TITLE
Aave LendingPool Verification

### ISSUE THREAD

**Issue by Aveesh52** [blockscout/blockscout#3752]
### Verify LendingPool 

solidity compiler: 0.6.12
address: 0xa77014Be67fb4A116Ed5c7E3D5d63f9A1e26DA10
contract name: LendingPool
code - https://gist.github.com/Aveesh52/480d76a027806d7191e8130a6704533c
network: Matic mainnet
Explorer Link - https://explorer-mainnet.maticvigil.com/
Network RPC - https://rpc-mainnet.maticvigil.com/

Also have no way to verify Proxy contracts deployed by other smart contracts, due the Blockgivil explorer does not index these as contracts. If is not indexed as a contract, the "manuall verify button" is missing, them i can not even manually verify it, . Here is the proxy contract of the LendingPool: 0x48BbBCFee0b49A8061Bf513c606E3BB9f149De39

**Comment by kartojal** [comment]
Hi @vbaranov,

The source of the LendingPool contract is:
https://github.com/aave/protocol-v2/blob/polygon-verifier/contracts/protocol/lendingpool/LendingPool.sol

The main issue is to verify contracts compiled and deployed with Hardhat and pragma ABIEncoderV2.

Optimization: yes
Runs: 200

**Comment by vbaranov** [comment]
Hi @kartojal 

>The main issue is to verify contracts compiled and deployed with Hardhat and pragma ABIEncoderV2.

That could cause issues with verification from flattened code, indeed. Taking in mind such issues, we added integration with the Sourcify tool as an option for verification. However, it is part of [premium features](https://docs.blockscout.com/for-projects/premium-features) and it doesn't support Sourcify's partial matching at the moment. So, there are no guarantees that enabling it in Matic Mainnet instance will solve the issue with this concrete contract. I suppose that this proposal https://github.com/blockscout/blockscout/issues/3211 could solve the issue, but there is no implementation for it yet.

**Comment by DaveAppleton** [comment]
The only way I have found to get around this is to flatten the file THEN compile it and deploy from the flattened file.

It is a PITA but it works

**Comment by vbaranov** [comment]
Blockscout now supports verification through Standard JSON Input #4908. It has been added to https://github.com/blockscout/blockscout/releases/tag/v4.1.0-beta. Since Polygon is not powered by Blockscout anymore, I am closing the issue.
