### ISSUE TITLE
Missing tried node lastest branch updated code, after mix php.server

### ISSUE THREAD

**Issue by gk5king** [blockscout/blockscout#3753]
*i have already cloned blockscout, and manually deployment in ubuntu, i got some error when i'm trying to finishing it. the error says 0x0000000000000000000000000000000000000000@砯: (-32000) missing trie node 815a55de5f0fe347ea58ca7740a40d4eb533e4244be1bfc97d17714c40b88075 (path )*

### Environment

* Elixir & Erlang/OTP versions (`elixir -version`): 1.11.3/OTP 21
* Operating System: Ubuntu 18
* Blockscout Version/branch:  master

### Steps to reproduce

*Tell us how to reproduce this issue.  ❤️ if you can push up a branch to your fork with a regression test we can run to reproduce locally.*

### Expected behaviour

*Tell us what should happen.*

### Actual behaviour
![Screen Shot 2021-03-31 at 15 54 17](https://user-images.githubusercontent.com/81680285/113118669-e2c0a800-9239-11eb-8293-e30126a529ff.png)

*Tell us what happens instead.*

**Comment by vbaranov** [comment]
@gk5king the node should be launched in the archive mode. You can examine the required params to accomplish that for different Ethereum clients from this link https://docs.blockscout.com/for-developers/information-and-settings/client-settings-parity-geth-ganache

**Comment by gk5king** [comment]
@vbaranov , I've replaced all the env variables and added the parameters according to the documentation.
here is my env config:
export ETHEREUM_JSONRPC_HTTP_URL=http://localhost:9191
export ETHEREUM_JSONRPC_VARIANT=geth
export ETHEREUM_JSONRPC_WS_URL=ws://localhost:8546
export coin... 
export DATABASE_URL..

and i used to geth for JSONRPCVARIANT 
here geth command 
**sudo /usr/bin/geth --rpc --rpcaddr 0.0.0.0 --port 30303 --rpcport 8545 --rpcapi debug,net,eth,shh,web3,txpool --wsapi "eth,net,web3,network,debug,txpool" --ws --wsaddr 0.0.0.0 --wsport 8546 --wsorigins "*" --rinkeby --datadir=/rinkeby --syncmode=full --gcmode=archive --rpcvhosts=***

and still the same get error, please help @vbaranov

**Comment by vbaranov** [comment]
@gk5king you should resync your node in archive mode from the genesis block.
Also, `ETHEREUM_JSONRPC_TRACE_URL` env var is missing.

**Comment by gk5king** [comment]
> @gk5king you should resync your node in archive mode from the genesis block.
> Also, `ETHEREUM_JSONRPC_TRACE_URL` env var is missing.

**@vbaranov okay, finally the explorer come out, after resync node..
thanks**
