### ISSUE TITLE
xDai: <tx request is not being deployed on xdai mainnet>

### ISSUE THREAD

**Issue by DavidJangJeongHyeon** [blockscout/blockscout#3759]
*Describe your issue here.*
I submitted swap requests on the Baoswap from ENJ to BAO. However, my tx requests was not deployed to the xdai mainnet. 
After that, I tried to interact with smart contracts by claiming rewards, swapping tokens, etc.
It has been 4 hours since tx request was made.
Please check and let me know how to solve or when I expect to see this problem would be fixed.

### Environment
* Elixir Version: 1.11.3
* Erlang Version: 23
* BlockScout Version: v3.6.0-beta

* User Agent: `Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.114 Safari/537.36`

### Steps to reproduce

*Tell us how to reproduce this issue. If possible, push up a branch to your fork with a regression test we can run to reproduce locally.*

### Expected Behaviour

*Tell us what should happen.*

### Actual Behaviour

*Tell us what happens instead.*

**Comment by DavidJangJeongHyeon** [comment]
FYI, I am not a developer but just a user.

**Comment by vbaranov** [comment]
I am closing this because of a duplicate request in the forum https://forum.poa.network/t/tx-request-does-not-seem-to-be-deployed-on-xdai-mainnet/5272
