### ISSUE TITLE
Changing the Browser Theme

### ISSUE THREAD

**Issue by pinswap** [blockscout/blockscout#3764]
What should I do if I want to replace the current theme after the browser is deployed? I can't find the change theme to method on the document!

**Comment by vbaranov** [comment]
CSS presets are located in `apps/block_scout_web/assets/css/theme` folder. You can create your own there. And then change path to it `apps/block_scout_web/assets/css/theme/_variables.scss`.

*Note*: In order to digest new assets run `mix phx.digest`

Sources:
https://docs.blockscout.com/for-developers/configuration-options/css-configuration-and-presets
https://docs.blockscout.com/for-developers/aws-marketplace/customizing-css

**Comment by pinswap** [comment]
> CSS presets are located in `apps/block_scout_web/assets/css/theme` folder. You can create your own there. And then change path to it `apps/block_scout_web/assets/css/theme/_variables.scss`.
> 
> _Note_: In order to digest new assets run `mix phx.digest`
> 
> Sources:
> https://docs.blockscout.com/for-developers/configuration-options/css-configuration-and-presets
> https://docs.blockscout.com/for-developers/aws-marketplace/customizing-css

I modified the file _variables.scss. The changes are as follows
//import "base_variables";
//import "neutral_variables";
// @import "dai_variables";
@import "ethereum_classic_variables";
@import "ethereum_variables";
// @import "ether1_variables";
// @import "expanse_variables";
// @import "gochain_variables";
// @import "goerli_variables";
// @import "kovan_variables";
// @import "lukso_variables";
// @import "musicoin_variables";
// @import "pirl_variables";
// @import "poa_variables";
// @import "posdao_variables";
// @import "rinkeby_variables";
// @import "ropsten_variables";
// @import "social_variables";
// @import "sokol_variables";
// @import "tobalaba_variables";
// @import "tomochain_variables";
// @import "rsk_variables";

It then restarted Docker, but it didn't work

**Comment by vbaranov** [comment]
>It then restarted Docker, but it didn't work

You should rebuild Docker image after the changes

**Comment by pinswap** [comment]
> You should rebuild Docker image after the changes
I need to re-delete the image. And then I'm going to run make start, right?
In addition, I did not understand the service of setting and restarting the browser. Could you please explain in detail how to operate it?
Please forgive me for being new to this business. I still have a lot to learn
