### ISSUE TITLE
(MatchError) no match of right hand side value: [] 

### ISSUE THREAD

**Issue by SVINCHAIN** [blockscout/blockscout#3765]
(MatchError) no match of right hand side value: []

### Environment

* Elixir & Erlang/OTP versions (`elixir -version`):
  Erlang/OTP 23 [erts-11.1.4] [source] [64-bit] [smp:4:4] [ds:4:4:10] [async-threads:1] [hipe]
  Elixir 1.7.2 (compiled with Erlang/OTP 19)

* Operating System:centos 7.8
* Blockscout Version/branch: v3.6.0 beta

### Steps to reproduce
I have prepared the env ,but when I exec mix do deps.get ,the error happend...

### Expected behaviour

*Tell us what should happen.*

### Actual behaviour

*Tell us what happens instead.*

**Comment by vbaranov** [comment]
>Erlang/OTP 23 [erts-11.1.4] [source] [64-bit] [smp:4:4] [ds:4:4:10] [async-threads:1] [hipe]
Elixir 1.7.2 (compiled with Erlang/OTP 19)

Elixir 1.11.x and Erlang/OTP 23 are required https://docs.blockscout.com/for-developers/information-and-settings/requirements

**Comment by SVINCHAIN** [comment]
thanks very much,all compile passed
