### ISSUE TITLE
Mainnet: matic tranfured from coinbase not received 

### ISSUE THREAD

**Issue by aboreone** [blockscout/blockscout#3766]
Iv transfured matic to my account address and they have not been received In my account, iv checked again and again to ensure the my address was entered correctly, they are identical yet the funds are not in my account.

### Environment
* Elixir Version: 1.11.3
* Erlang Version: 23
* BlockScout Version: v3.5.1-beta

* User Agent: `Mozilla/5.0 (Linux; Android 11; SM-G981B) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.105 Mobile Safari/537.36 Wombat/1.47.0`

### Steps to reproduce

*Tell us how to reproduce this issue. If possible, push up a branch to your fork with a regression test we can run to reproduce locally.*

### Expected Behaviour

*Tell us what should happen.*

### Actual Behaviour

*Tell us what happens instead.*

**Comment by vbaranov** [comment]
There is no Matic support here
