### ISSUE TITLE
Could not convert receipt to elixir

### ISSUE THREAD

**Issue by SVINCHAIN** [blockscout/blockscout#3768]
Hello, the browser can run normally, but all transactions cannot view transaction details. The following is the specific terminal error details, please assist

Errors:
  {:unknown_key, %{key: "type", value: "0x0"}}

    (ethereum_jsonrpc 0.1.0) lib/ethereum_jsonrpc/receipt.ex:236: EthereumJSONRPC.Receipt.ok!/2
    (elixir 1.11.4) lib/enum.ex:1411: Enum."-map/2-lists^map/1-0-"/2
    (ethereum_jsonrpc 0.1.0) lib/ethereum_jsonrpc/receipts.ex:138: EthereumJSONRPC.Receipts.fetch/2
    (elixir 1.11.4) lib/task/supervised.ex:90: Task.Supervised.invoke_mfa/2
    (elixir 1.11.4) lib/task/supervised.ex:35: Task.Supervised.reply/5
    (stdlib 3.14) proc_lib.erl:226: :proc_lib.init_p_do_apply/3
Last message: {:EXIT, #PID<0.1461.2>, {%ArgumentError{message: "Could not convert receipt to elixir\n\nReceipt:\n  %{\"blockHash\" => \"0x6a34672955dd0bae7b494bb4394e9331d94667ad63f8b2280dd2d7517cfaee51\", \"blockNumber\" => \"0x16949\", \"contractAddress\" => nil, \"cumulativeGasUsed\" => \"0x5208\", \"from\" => \"0xf8e4ba11e7669aa580523344a0d986c33eaea260\", \"gas\" => 21000, \"gasUsed\" => \"0x5208\", \"logs\" => [], \"logsBloom\" => 

### Environment

* Elixir & Erlang/OTP versions (`elixir -version`):
* Erlang/OTP 23 [erts-11.1.4] [source] [64-bit] [smp:4:4] [ds:4:4:10] [async-threads:1] [hipe]
  Elixir 1.11.4 (compiled with Erlang/OTP 21)

* Operating System: centos 7.8 postsql12
* Blockscout Version/branch: 3.6.0 beta

### Steps to reproduce

*Tell us how to reproduce this issue.  ❤️ if you can push up a branch to your fork with a regression test we can run to reproduce locally.*

### Expected behaviour
![bug2](https://user-images.githubusercontent.com/35824091/113687123-97efd600-96fa-11eb-8ce1-1277c3a17700.png)
![bugs](https://user-images.githubusercontent.com/35824091/113687130-99210300-96fa-11eb-88c2-6346f0f8e793.png)

*Tell us what should happen.*

### Actual behaviour

*Tell us what happens instead.*

**Comment by vbaranov** [comment]
@SVINCHAIN which Ethereum client do you use for archive node and version?

**Comment by SVINCHAIN** [comment]
geth v1.10.1

**Comment by SVINCHAIN** [comment]
> @SVINCHAIN which Ethereum client do you use for archive node and version?

geth v1.10.1

**Comment by SVINCHAIN** [comment]
> @SVINCHAIN which Ethereum client do you use for archive node and version?

geth v1.10.1

**Comment by SVINCHAIN** [comment]
> @vbaranov  which Ethereum client do you use for archive node and version?
geth v1.10.1

**Comment by SVINCHAIN** [comment]
> > @vbaranov  Hello,I've solved the problem util  i change the geth version from 1.10.1 to 1.09.24.
