### ISSUE TITLE
Can't do migration

### ISSUE THREAD

**Issue by Kapranov** [blockscout/blockscout#3769]
I got error by mix ecto.migration

execute "CREATE INDEX IF NOT EXISTS decompiled_smart_contracts_address_hash_index ON decompiled_smart_contracts(address_hash);\n"

** (Postgrex.Error) ERROR 42601 (syntax_error) syntax error at or near "NOT"

query: CREATE INDEX IF NOT EXISTS decompiled_smart_contracts_address_hash_index ON decompiled_smart_contracts(address_hash);

into file: 20190516140202_add_address_hash_index_to_decompiled_smart_contracts.exs

![screenshots](https://user-images.githubusercontent.com/1867781/113688848-64af3780-9665-11eb-8d55-2d1d61d5f547.png)

**Comment by vbaranov** [comment]
@Kapranov could you disclose, which version of Postgres is in question?

**Comment by Kapranov** [comment]
psql (PostgreSQL) 9.4.26

**Comment by Kapranov** [comment]
> @Kapranov could you disclose, which version of Postgres is in question?
psql (PostgreSQL) 9.4.26

**Comment by vbaranov** [comment]
It is not supported. You should upgrade at least up to 10.3. Reference: https://docs.blockscout.com/for-developers/information-and-settings/requirements
