### ISSUE TITLE
trouble catching up with geth

### ISSUE THREAD

**Issue by xoffey** [blockscout/blockscout#3776]
Blockscout, installed via CloudFormation, logs a lot of errors and could not fully index a geth-based private clique network

### Environment

* Elixir & Erlang/OTP versions (`elixir -version`): Elixir 1.10.3 (compiled with Erlang/OTP 21)
* Operating System: amazon linux
* Blockscout Version/branch:  4 (the one installed via ClouydFormation)

### Steps to reproduce

*Tell us how to reproduce this issue.  ❤️ if you can push up a branch to your fork with a regression test we can run to reproduce locally.*

### Expected behaviour

Should sync and index fully (this blockchain does not have much activity yet)

### Actual behaviour

Got to "99% complete" indexing, listed some transactions "pending" even though they were approved, never showed any approved transactiuons (even though there were some, logged a ton of errors.

A lot of errors like the following in the logs:
`
Apr 06 18:26:59 ip-10-0-1-59.ec2.internal explorer[2551]: ** (ArgumentError) Could not convert receipt to elixir
Apr 06 18:26:59 ip-10-0-1-59.ec2.internal explorer[2551]: Receipt:
Apr 06 18:26:59 ip-10-0-1-59.ec2.internal explorer[2551]: %{"blockHash" => "0xfe20fb0beb0ae36725297c9e3c15d0d02b26b9768c885b9f714744dc06b70d3e",
Apr 06 18:26:59 ip-10-0-1-59.ec2.internal explorer[2551]: Errors:
Apr 06 18:26:59 ip-10-0-1-59.ec2.internal explorer[2551]: {:unknown_key, %{key: "type", value: "0x0"}}
Apr 06 18:26:59 ip-10-0-1-59.ec2.internal explorer[2551]: (ethereum_jsonrpc 0.1.0) lib/ethereum_jsonrpc/receipt.ex:236: EthereumJSONRPC.Receipt.
Apr 06 18:26:59 ip-10-0-1-59.ec2.internal explorer[2551]: (elixir 1.10.3) lib/enum.ex:1396: Enum."-map/2-lists^map/1-0-"/2
Apr 06 18:26:59 ip-10-0-1-59.ec2.internal explorer[2551]: (ethereum_jsonrpc 0.1.0) lib/ethereum_jsonrpc/receipts.ex:138: EthereumJSONRPC.Receipt
Apr 06 18:26:59 ip-10-0-1-59.ec2.internal explorer[2551]: (elixir 1.10.3) lib/task/supervised.ex:90: Task.Supervised.invoke_mfa/2
Apr 06 18:26:59 ip-10-0-1-59.ec2.internal explorer[2551]: (elixir 1.10.3) lib/task/supervised.ex:35: Task.Supervised.reply/5
Apr 06 18:26:59 ip-10-0-1-59.ec2.internal explorer[2551]: (stdlib 3.9) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
Apr 06 18:26:59 ip-10-0-1-59.ec2.internal explorer[2551]: Last message: {:EXIT, #PID<0.9498.2>, {%ArgumentError{message: "Could not convert rece
Apr 06 18:26:59 ip-10-0-1-59.ec2.internal explorer[2551]: State: %Indexer.Block.Catchup.Sequence{bound_queue: %Indexer.BoundQueue{maximum_size:
Apr 06 18:26:59 ip-10-0-1-59.ec2.internal explorer[2551]: 2021-04-06T18:26:59.370 [error] Task #PID<0.9513.2> started from #PID<0.9521.2> termin
`

**Comment by xoffey** [comment]
The geth command I use to start my node is:
geth --config netconfig/priv_5.config.toml --nat extip:34.222.xx.yy --http --http.addr 0.0.0.0 --http.port 8646 --http.api clique,debug,net,eth,web3,txpool,personal --http.corsdomain blockscout-2.neocortix.net --http.vhosts '*' --syncmode full --gcmode archive

**Comment by xoffey** [comment]
Most likely, this is an incompatibility problem with respect to geth 1.10.1. I switched over to geth 1.9.25 on my archive node, and blockscout started working.

**Comment by vbaranov** [comment]
> Most likely, this is an incompatibility problem with respect to geth 1.10.1. I switched over to geth 1.9.25 on my archive node, and blockscout started working.

You're right. Blockscout has not been tested with Geth 1.10 yet.
