### ISSUE TITLE
Mumbai: Unauthorised when using write contract

### ISSUE THREAD

**Issue by tobowers** [blockscout/blockscout#3777]
When using https://explorer-mumbai.maticvigil.com/address/0xDCb209532108D794e837906eE67317C9ffB61318/write-contract and the addLiquidityMATIC method, I get an "unauthorised" box popping up when I click Write.

<img width="301" alt="Screen Shot 2021-04-06 at 22 23 47" src="https://user-images.githubusercontent.com/1274/113778747-14031180-972d-11eb-9905-0b6c461bf7ce.png">

### Environment
* Elixir Version: 1.11.3
* Erlang Version: 23
* BlockScout Version: v3.5.1-beta

* User Agent: `Mozilla/5.0 (Macintosh; Intel Mac OS X 11_2_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.114 Safari/537.36`

### Steps to reproduce

*Tell us how to reproduce this issue. If possible, push up a branch to your fork with a regression test we can run to reproduce locally.*

### Expected Behaviour

Meta mask pops up to send the Tx

### Actual Behaviour

Unauthorized box pops up.

**Comment by vbaranov** [comment]
@tobowers 3.5.1 is not the latest release. Please ask the Polygon team to install https://github.com/blockscout/blockscout/releases/tag/v3.6.0-beta
