### ISSUE TITLE
Erlang NIF C libsecp256k1 -  Failed

### ISSUE THREAD

**Issue by Kapranov** [blockscout/blockscout#3779]
If you see  https://github.com/exthereum/libsecp256k1
how I can compile source without it error
![screenshots](https://user-images.githubusercontent.com/1867781/113921612-ebf1cd80-9781-11eb-8555-879a9b2e6c3b.png)

**Comment by vbaranov** [comment]
Which version of Elixir, Erlang/OTP do you use? The minimum acceptable versions Elixir 1.11.x and Erlang/OTP 23.

If versions are correct, can you try this tip:

https://github.com/blockscout/blockscout/issues/954#issuecomment-432124337

**Comment by Kapranov** [comment]
**Versions**
 **elixir - Elixir 1.11.3 (compiled with Erlang/OTP 23)**
**Erlang/OTP 23 [erts-11.1.8] [source] [64-bit] [smp:4:4] [ds:4:4:10] [async-threads:1] [hipe]**
![screenshots](https://user-images.githubusercontent.com/1867781/114040156-0d54c700-981f-11eb-9e9f-21e0c2d53eaf.png)

**Comment by vbaranov** [comment]
>If versions are correct, can you try this tip:

#954 (comment)

Does this tip help to resolve the issue?

**Comment by Kapranov** [comment]
All packages have been checked - automake libtool inotify-tools autoconf
If follow instruction for rebar3 edit deps/libsecp256k1/rebar3.config and added the following to the top:
```
{plugins, [pc]}.

{provider_hooks,
 [
  {pre,
   [
    {compile, {pc, compile}},
    {clean, {pc, clean}}
   ]
  }
 ]
}.
```
then `cd deps/libsecp256k1; rebar3 compile`

![screenshots](https://user-images.githubusercontent.com/1867781/114064319-38e2ac00-9835-11eb-9c51-2aa74aa8f2ab.png)
**I had the same error without being changed**

**Comment by vbaranov** [comment]
The application was updated to work with Elixir 1.12.x version. You can try starting from the current master branch of commit https://github.com/blockscout/blockscout/commit/478af7d8d6ebecfe993880dfb8cbe87b8eb87a56. The issue shouldn't appear again. Otherwise, please, let us know.
