### ISSUE TITLE
Mainnet: Ox matic deposit issue

### ISSUE THREAD

**Issue by yuben81** [blockscout/blockscout#3781]
Hello
My name is Ben. I deposit $500 matic from coinbase to 0x wallet for 0xuniverse. I have the confirmation from coinbase but the account on 0x wallet still shows 0. Please help

Ben
323-899-8862

### Environment
* Elixir Version: 1.11.3
* Erlang Version: 23
* BlockScout Version: v3.5.1-beta

* User Agent: `Mozilla/5.0 (iPhone; CPU iPhone OS 14_4_2 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.0.3 Mobile/15E148 Safari/604.1`

### Steps to reproduce

*Tell us how to reproduce this issue. If possible, push up a branch to your fork with a regression test we can run to reproduce locally.*

### Expected Behaviour

*Tell us what should happen.*

### Actual Behaviour

*Tell us what happens instead.*

**Comment by vbaranov** [comment]
There is no Matic support here. Try to ask at their fork https://github.com/maticnetwork/blockscout.

**Comment by imflurlancer** [comment]
i have this proplem can you help me
