### ISSUE TITLE
Multi-server deployment

### ISSUE THREAD

**Issue by unqjohnny** [blockscout/blockscout#3782]
I want Multi-server deployment production env. 

how to config?

should have multi postgres?  or use one postgres with multi deployment?

**Comment by vbaranov** [comment]
>should have multi postgres? or use one postgres with multi deployment?

The application is connected to a single Postgres URL via `DATABASE_URL` environment variable. However, you can try to run API Server separately from the main application (web UI and indexer) and connect it to DB read-replica.

An example of how to split API server and main UI: https://github.com/blockscout/blockscout/pull/2376

List of supported env vars: https://docs.blockscout.com/for-developers/information-and-settings/env-variables
<img width="843" alt="Screenshot 2021-04-08 at 14 54 37" src="https://user-images.githubusercontent.com/4341812/114022367-5a19bb80-987a-11eb-96a1-8f8c3654188e.png">

**Comment by unqjohnny** [comment]
Thanks a lot
