### ISSUE TITLE
xDai: <Issue Title>

### ISSUE THREAD

**Issue by mrmamorris** [blockscout/blockscout#3793]
I mistakenly sent 615 xdai to a contract.   0xb5c0730d3c300b240d5e9328e4927722b0e1749f

If possible please return or reverse this mistake.  

Thank You Monty Morris  mrmamorris@gmail.com

![image](https://user-images.githubusercontent.com/82231429/114216162-c7cdf200-9923-11eb-8d3a-adab835648e0.png)

### Environment
* Elixir Version: 1.11.3
* Erlang Version: 23
* BlockScout Version: v3.6.0-beta

* User Agent: `Mozilla/5.0 (X11; CrOS x86_64 13729.56.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.95 Safari/537.36`

### Steps to reproduce

*Tell us how to reproduce this issue. If possible, push up a branch to your fork with a regression test we can run to reproduce locally.*

### Expected Behaviour

*Tell us what should happen.*

### Actual Behaviour

*Tell us what happens instead.*

**Comment by vbaranov** [comment]
<img width="904" alt="Screenshot 2021-04-11 at 22 21 19" src="https://user-images.githubusercontent.com/4341812/114318127-3ec9dd00-9b14-11eb-83db-ea616ad9e25c.png">


As far as I can see recipient address is a regular address, not a contract. Owner only of that address can return your funds.
