### ISSUE TITLE
Mainnet: <Issue Title>

### ISSUE THREAD

**Issue by spencercweiss** [blockscout/blockscout#3794]
*Describe your issue here.*

Not receiving anything despite the completed transaction. 378.362287 MATIC was sent to 0x7b72060422f27d33db7e59efa533c100894d2cdc but "There are no transactions for this address." I am certain I copy-pasted the information so this thankfully was not a case of being dumb - it's just been 10 minutes since the exchange completed and there isn't a transaction history for the account. If I'm bugging and receiving just takes a while, I'm really sorry and please disregard. But if not please help :( thank you!

### Environment
* Elixir Version: 1.11.3
* Erlang Version: 23
* BlockScout Version: v3.6.0-beta

* User Agent: `Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.114 Safari/537.36`

### Steps to reproduce

*Tell us how to reproduce this issue. If possible, push up a branch to your fork with a regression test we can run to reproduce locally.*

Send money to a MATIC wallet.

### Expected Behaviour

*Tell us what should happen.*

You should receive your MATIC.

### Actual Behaviour

*Tell us what happens instead.*

You don't.

**Comment by vbaranov** [comment]
There is no Matic support here. Try to ask at their fork https://github.com/maticnetwork/blockscout.
