### ISSUE TITLE
Can't see transaction record

### ISSUE THREAD

**Issue by lzmmcns** [blockscout/blockscout#3795]
After the deployment of Docker browser has been reported errors and can not see the transaction records
![20210411131633](https://user-images.githubusercontent.com/67579674/114293448-a6f2d180-9ac8-11eb-90b0-2d579bc7d817.png)
![20210411131653](https://user-images.githubusercontent.com/67579674/114293449-a823fe80-9ac8-11eb-8274-b186e8ce51f9.png)
![20210411131749](https://user-images.githubusercontent.com/67579674/114293451-a823fe80-9ac8-11eb-94e9-65dbfc52e03a.png)
![20210411131812](https://user-images.githubusercontent.com/67579674/114293452-a8bc9500-9ac8-11eb-8f77-9399c1f0bc20.png)

**Comment by vbaranov** [comment]
What archive node do you use?

**Comment by vbaranov** [comment]
The issue should be resolved with this fix https://github.com/blockscout/blockscout/pull/3831. Merged to master branch.

**Comment by starbsc** [comment]
Because it's using the latest Ethereum package. That's why the error was reported. Not in the previous version

**Comment by starbsc** [comment]
> The issue should be resolved with this fix #3831. Merged to master branch.

Because it's using the latest Ethereum package. That's why the error was reported. Not in the previous version
