### ISSUE TITLE
retrieving metadata through api, no modules return token uri address. 

### ISSUE THREAD

**Issue by Sparda-Inc** [blockscout/blockscout#3797]
No tokenURI in listed in return for "gettoken" and "tokenlist" api modules. 

### Environment

* Elixir & Erlang/OTP versions (`elixir -version`):
* Operating System:
* Blockscout Version/branch: 

### Expected behaviour

I would like to request the tokenURI JSON file for the metadata for minted erc721 tokens.  

### Actual behaviour No tokenURI

{
  "message": "OK",
  "result": {
    "cataloged": true,
    "contractAddress": "0xa42d556b53f267890b2f67f4f16ce533fd8a863d",
    "decimals": "",
    "name": "Cat Lines 2",
    "symbol": "CAT2",
    "totalSupply": "",
    "type": "ERC-721"
  },
  "status": "1"
}

**Comment by vbaranov** [comment]
You can request it through corresponding API v2 endpoint:

```
/api/v2/tokens/:token_address_hash/instances/:token_id
```

E.g.
https://eth.blockscout.com/api/v2/tokens/0x95987b0cdC7F65d989A30B3B7132a38388c548Eb/instances/57896044618658097711785492504343953926634992332820282019728792003956564820002

```
{"animation_url":null,"external_app_url":null,"id":"57896044618658097711785492504343953926634992332820282019728792003956564820002","image_url":"https://nftstorage.link/ipfs/QmafiZY7bUmEBwfDd8Ztv5BaLjmnmPtzggxNxeHvyDy5kq/0.gif","is_unique":true,"media_type":null,"media_url":"ipfs://QmafiZY7bUmEBwfDd8Ztv5BaLjmnmPtzggxNxeHvyDy5kq/0.gif","metadata":{"attributes":[{"trait_type":"color","value":"unknown"},{"trait_type":"box","value":"unknown"},{"trait_type":"background","value":"unknown"}],"description":"A collection 10000 PURSE 404 NFT on ETH blockchain.","image":"ipfs://QmafiZY7bUmEBwfDd8Ztv5BaLjmnmPtzggxNxeHvyDy5kq/0.gif","name":"Purse #57896044618658097711785492504343953926634992332820282019728792003956564820002"},"owner":{"ens_domain_name":null,"hash":"0x610551A9c5B8944E27a2999442Cc2d707223e6cb","implementations":[],"is_contract":false,"is_scam":false,"is_verified":false,"metadata":null,"name":null,"private_tags":[],"proxy_type":null,"public_tags":[],"watchlist_names":[]},"thumbnails":null,"token":{"address":"0x95987b0cdC7F65d989A30B3B7132a38388c548Eb","circulating_market_cap":"3063149.800190668","decimals":"18","exchange_rate":"0.0001115","holders":"604","icon_url":"https://assets.coingecko.com/coins/images/20419/small/HobiV7k__400x400.jpg?1696519827","name":"PURSE TOKEN","symbol":"PURSE","total_supply":"9632344941349840072872579249","type":"ERC-721","volume_24h":"34465.480342841875"}}
```

You can play with all API v2 endpoints at [API docs](https://eth.blockscout.com/api-docs) page.
