### ISSUE TITLE
IGG Stuck

### ISSUE THREAD

**Issue by dkcotter7** [blockscout/blockscout#3798]
I recently transferred some IGG Gold from iggalaxy,com to my Matic wallet. However, it never made it to the wallet even though it shows on here as successful transfer.

Please let me know what info you need to help and I will get it over to you,

Thank you!

### Environment
* Elixir Version: 1.11.3
* Erlang Version: 23
* BlockScout Version: v3.6.0-beta

* User Agent: `Mozilla/5.0 (X11; CrOS x86_64 13597.94.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.186 Safari/537.36`

### Steps to reproduce

*Tell us how to reproduce this issue. If possible, push up a branch to your fork with a regression test we can run to reproduce locally.*

### Expected Behaviour

*Tell us what should happen.*

### Actual Behaviour

*Tell us what happens instead.*

**Comment by vbaranov** [comment]
There is no Matic support here. Try to ask at their fork https://github.com/maticnetwork/blockscout.
