### ISSUE TITLE
Mainnet: change Holyheld (HH) to Mover (MOVE)

### ISSUE THREAD

**Issue by CRYPTOCOINS2018** [blockscout/blockscout#3804]
The project has been rebranded.

https://www.coingecko.com/en/coins/mover

### Environment
* Elixir Version: 1.11.3
* Erlang Version: 23
* BlockScout Version: v3.6.0-beta

* User Agent: `Mozilla/5.0 (Linux; Android 10; ONEPLUS A6003) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.105 Mobile Safari/537.36`

### Steps to reproduce

*Tell us how to reproduce this issue. If possible, push up a branch to your fork with a regression test we can run to reproduce locally.*

### Expected Behaviour

*Tell us what should happen.*

### Actual Behaviour

*Tell us what happens instead.*

**Comment by vbaranov** [comment]
What is the address of the bridged token in xDai?

**Comment by vbaranov** [comment]
Closing due to no response

**Comment by CRYPTOCOINS2018** [comment]
It is not on xdai? It is on matic

**Comment by vbaranov** [comment]
There is no Matic support here. You should reach their team. Try to ask at their fork https://github.com/maticnetwork/blockscout.
