### ISSUE TITLE
The Requested path was not found on Blockscout

### ISSUE THREAD

**Issue by LJ404now** [blockscout/blockscout#3806]
*Describe your issue here.*

0x8898c0a23594f30c158964ebc4feed5216802becf6189bc4e8384b0d3201bfa1

### Environment

* Elixir & Erlang/OTP versions (`elixir -version`):
* Operating System:
* Blockscout Version/branch: 

### Steps to reproduce

![](https://user-images.githubusercontent.com/8782666/65834756-e989fa00-e2e6-11e9-9841-bf9fb7f7e491.png)

*Tell us how to reproduce this issue.  ❤️ if you can push up a branch to your fork with a regression test we can run to reproduce locally.*

### Expected behaviour

*Tell us what should happen.*

### Actual behaviour

*Tell us what happens instead.* nothing is confirmed for deposit

**Comment by vbaranov** [comment]
This is the intended response. How did you get to that page?
