### ISSUE TITLE
Ethereum Classic: ETC transfer never arrived 

### ISSUE THREAD

**Issue by nbowen30** [blockscout/blockscout#3808]
*Describe your issue here.*
I transferred a test payment of $2.01 to my Celsius account and it never arrived.  I received a confirmation saying it was successful.  However,  the money never arrived in my account.
### Environment
* Elixir Version: 1.11.0
* Erlang Version: 23
* BlockScout Version: v3.5.0-beta

* User Agent: `Mozilla/5.0 (iPhone; CPU iPhone OS 13_7 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.1.2 Mobile/15E148 Safari/604.1`

### Steps to reproduce

*Tell us how to reproduce this issue. If possible, push up a branch to your fork with a regression test we can run to reproduce locally.*

### Expected Behaviour

*Tell us what should happen.*

### Actual Behaviour

*Tell us what happens instead.*

**Comment by vbaranov** [comment]
Regarding your question try to reach out ETC team, for instance, on their Discord https://discord.com/invite/hQs894U.
