### ISSUE TITLE
RPC API getTokenHolders pagination broken

### ISSUE THREAD

**Issue by PeterTheOne** [blockscout/blockscout#3809]
`https://blockscout.com/xdai/mainnet/api?module=token&action=getTokenHolders&contractaddress=0x63e62989D9EB2d37dfDB1F93A22f063635b07d51&page=1&offset=1`

returns the same as

`https://blockscout.com/xdai/mainnet/api?module=token&action=getTokenHolders&contractaddress=0x63e62989D9EB2d37dfDB1F93A22f063635b07d51&page=2&offset=1`

### Environment

* Elixir & Erlang/OTP versions (`elixir -version`): ?
* Operating System: ?
* Blockscout Version/branch: Version: v3.6.0-beta

### Expected behaviour

I expect to be able to load different pages of token holders.

### Actual behaviour

I only see the first page.

**Comment by vbaranov** [comment]
Thank you. That was fixed in https://github.com/blockscout/blockscout/pull/3835 and deployed to xDai.
