### ISSUE TITLE
Mainnet: My contract is verified with wrong constructor params

### ISSUE THREAD

**Issue by ninjadev101** [blockscout/blockscout#3813]
My contract is verified with wrong constructor params

### Environment
* MacOS
* Chrome 89.0.4389.114
* Truffle: 5.1.21
* solidity: 0.6.6

### Steps to reproduce

I deployed contract using these params: 

`const proxy = "0xA6FA4fB5f76172d178d61B04b0ecd319C5d1C0aa";
  developer.deploy(
    ChildMintableERC1155,
    "6ix9ine Digital Collection",
    "69DC",
    "https://api.tk69.xyz/api/item/",
    proxy
  );`

### Expected Behaviour

Found similar contract but I need to reverify to request mapping. So I did the same as before. Metadata uri must use https://api.tk69.xyz/api/item/

### Actual Behaviour

Constructor used for contract:
`0000000000000000000000000000000000000000000000000000000000000040000000000000000000000000b5505a6d998549090530911180f38ac5130101c6000000000000000000000000000000000000000000000000000000000000002868747470733a2f2f6170692e6d6176657269636b6368616d702e636f6d2f6170692f6d617469632f000000000000000000000000000000000000000000000000

Arg [0] (string) : https://api.maverickchamp.com/api/matic/
Arg [1] (address) : 0xb5505a6d998549090530911180f38ac5130101c6`

*Tell us what happens instead.*

**Comment by vbaranov** [comment]
You should ask Matic team to enable "Verify" button in case of finding a similar contract. We do not disable it in the Blockscout Core product.
