### ISSUE TITLE
Mainnet: <Issue Title>

### ISSUE THREAD

**Issue by robertaustinmasters** [blockscout/blockscout#3815]
*Describe your issue here.*
I am trying to cancel or reverse my previous transaction so I can adjust the terms to cover the fee slippage or find out why my transaction was rejected.
### Environment
* Elixir Version: 1.11.3
* Erlang Version: 23
* BlockScout Version: v3.6.0-beta

* User Agent: `Mozilla/5.0 (iPhone; CPU iPhone OS 13_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) CriOS/76.0.3809.123 Mobile/15E148 Safari/605.1`

### Steps to reproduce
1) Add ETH to Metamask.

2)Went to the Matic V2 wallet and connected MetaMask wallet. 

3) added Matic Mainnet to MetaMask networks.

4) Clicked on the swap to Matic Bridge link 

5) I made sure I was sending from etherium network and into Matic network. 

6) I was intending to swap my etherium to the Matic network and then swap it for MATIC. 

7) I was given “ Wrapped ETh(Pos) “ and was unable to locate it in main area of my wallet until I stumbled across where it said I could send it to my MetaMask.

8) I made sure my MetaMask wallet was on Matic Network and copy and pasted my address from Wrapped ETH from Matic and made sure it was the address I needed.

9) I attempted to send the funds from my Matic V2 wallet to my Matic wallet on my MetaMask that was running on the Matic Network.

Tell us how to reproduce this issue. If possible, push up a branch to your fork with a regression test we can run to reproduce locally.*

### Expected Behaviour

*Tell us what should happen.*

### Actual Behaviour

*Tell us what happens instead.*

**Comment by vbaranov** [comment]
There is no Matic support here. Try to ask at their fork https://github.com/maticnetwork/blockscout.
