### ISSUE TITLE
Ethereum Classic: <Issue Title>

### ISSUE THREAD

**Issue by Jessielynn0218** [blockscout/blockscout#3816]
Sent ethereum classic to the wrong address.  I sent it to ethereum.  I do not have an etherum wallet.  Is there a way to get this fixed? Or refunded or sent to a new wallet address?  Screen shot of transaction below. 

![Screenshot_20210416-084200_Gallery](https://user-images.githubusercontent.com/82600407/115027222-6fea3a80-9e91-11eb-8f6f-d9dcbd53e402.jpg)

### Environment
* Elixir Version: 1.11.0
* Erlang Version: 23
* BlockScout Version: v3.5.0-beta

* User Agent: `Mozilla/5.0 (Linux; Android 11; SAMSUNG SM-G991U1) AppleWebKit/537.36 (KHTML, like Gecko) SamsungBrowser/13.2 Chrome/83.0.4103.106 Mobile Safari/537.36`

### Expected 
send ethereum classic worth 379.14 to etherum classic wallet

*Tell us what should happen.*
Should have been sent to etc wallet

### Actual Behaviour
Was sent to my eth wallet address instead.  TxnHash number is 
0xa081510ebcb8fcf3a5c7d7c99d9d8db76be936781bf1f93a1e9391863c1b6c42

*Tell us what happens instead.*
Should have been sent to etc wallet but sent to wrong wallet address.   The wrong wallet was an address for eth.  I mixed up etc from eth.

**Comment by vbaranov** [comment]
Regarding your question try to reach out ETC team, for instance, on their Discord https://discord.com/invite/hQs894U.
