### ISSUE TITLE
Ethereum classic already 4 days unsuccessful transaction. We are unable to locate this transaction hash

### ISSUE THREAD

**Issue by vannko** [blockscout/blockscout#3819]
Hello. 4 days ago, I tried to send ETC to my ledger wallet from my trust wallet. Still the transaction is not completed. Also if I click on more details the following message appears - "We are unable to locate this transaction Hash". 
Glad If you could help me. 
Best regards!

**Comment by vannko** [comment]
![Screenshot_20210417-084600_Chrome](https://user-images.githubusercontent.com/82695920/115103411-4f39e780-9f5a-11eb-8b45-55eba15ce65b.jpg)
![Uploading Screenshot_20210417-084552_Trust Wallet.jpg…]()

**Comment by vbaranov** [comment]
Regarding your question try to reach out ETC team, for instance, on their Discord https://discord.com/invite/hQs894U.
