### ISSUE TITLE
Mainnet: <Transaction Between Accounts>

### ISSUE THREAD

**Issue by SoloEvoX** [blockscout/blockscout#3825]
*Sending Mana from my Matic Mainnet network on MetaMask to Ethereum Mainnet and it failed, received "Error: (Awaiting internal transactions for reason)".*

Transaction Details here:

*https://explorer-mainnet.maticvigil.com/tx/0x9717d87d03f89eeb3c576e265392afee87d1cac065b9d98a5644f29f2b4acfa6/internal-transactions*

### Environment
* Elixir Version: 1.11.3
* Erlang Version: 23
* BlockScout Version: v3.6.0-beta

* User Agent: `Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.128 Safari/537.36`

### Steps to reproduce

*In MetaMask extension select Matic MainNet network where MANA is being held. Select Mana Token and select Send. Select "Transfer Between my Accounts". Select the main account in this case (Ethereum Mainnet network account). Select the amount you want send over and pay a gas fee. Select the Next button and wait. *

### Expected Behaviour

*Supposed to send and receive MANA from Matic MainNet to Ethereum MainNet.*

### Actual Behaviour

*Transaction failed and lost MANA in transaction.*

**Comment by vbaranov** [comment]
There is no Matic support here. Try to ask at their fork https://github.com/maticnetwork/blockscout.
