### ISSUE TITLE
Ethereum Classic: <Issue Title>

### ISSUE THREAD

**Issue by williammosley398** [blockscout/blockscout#3826]
Not sure where my money was sent.  Was trying to send it to my abbra  account*Describe your issue here.*

### Environment
* Elixir Version: 1.11.0
* Erlang Version: 23
* BlockScout Version: v3.5.0-beta

* User Agent: `Mozilla/5.0 (Linux; Android 10; SAMSUNG SM-S111DL) AppleWebKit/537.36 (KHTML, like Gecko) SamsungBrowser/11.0 Chrome/75.0.3770.143 Mobile Safari/537.36`

### Steps to reproduce

*Tell us how to reproduce this issue. If possible, push up a branch to your fork with a regression test we can run to reproduce locally.*

### Expected Behaviour

*Tell us what should happen.*

### Actual Behaviour

*Tell us what happens instead.*

**Comment by williammosley398** [comment]
> Not sure where my money was sent. Was trying to send it to my abbra account_Describe your issue here._
> 
> ### Environment
> * Elixir Version: 1.11.0
> * Erlang Version: 23
> * BlockScout Version: v3.5.0-beta
> * User Agent: `Mozilla/5.0 (Linux; Android 10; SAMSUNG SM-S111DL) AppleWebKit/537.36 (KHTML, like Gecko) SamsungBrowser/11.0 Chrome/75.0.3770.143 Mobile Safari/537.36`
> 
> ### Steps to reproduce
> _Tell us how to reproduce this issue. If possible, push up a branch to your fork with a regression test we can run to reproduce locally._
> 
> ### Expected Behaviour
> _Tell us what should happen._
> 
> ### Actual Behaviour
> _Tell us what happens instead._
Please help

**Comment by williammosley398** [comment]
Help

**Comment by vbaranov** [comment]
Regarding your question try to reach out ETC team, for instance, on their Discord https://discord.com/invite/hQs894U.
