### ISSUE TITLE
Cannot see code of EIP1167 contract

### ISSUE THREAD

**Issue by georgeroman** [blockscout/blockscout#3832]
I've recently deployed some EIP1167 contracts on Matic Mumbai (eg. https://explorer-mumbai.maticvigil.com/address/0x497540be7d6a3d0c7543e6F174348463AF9746b3/transactions). For some reason, the UI doesn't give me an option to see the code of the contract nor verify it. I managed to workaround the verification issue by going directly to `https://explorer-mumbai.maticvigil.com/address/0x1335f881a68ecea9a81fc3d256a49300a9ea53b0/contract_verifications/new` and it succeeded. However, the UI still doesn't seem to work: going to the 'Read Contract' or 'Write Contract' tabs (in https://explorer-mumbai.maticvigil.com/address/0x1335F881a68eCEA9a81FC3D256A49300A9ea53b0/transactions) results in a 'Page Not Found' error.

Matic's Mumbai explorer is on version 3.6.0 which should support EIP1167 (https://github.com/blockscout/blockscout/pull/3743) - reach out to them and it seems to be an issue with BlockScout.

**Comment by vbaranov** [comment]
We have no official suport of Matic instance. In order to speed-up the resolution of your issue please deploy the same contracts to xDai or Sokol Testnet.

**Comment by georgeroman** [comment]
The Sokol Testnet explorer correctly shows EIP1167 contracts - this seems to be an issue on Matic explorer's side.
