### ISSUE TITLE
Ethereum Classic: transaction not reached

### ISSUE THREAD

**Issue by muhammad786-star** [blockscout/blockscout#3833]
*Describe your issue here.*

### Environment
* Elixir Version: 1.11.0
* Erlang Version: 23
* BlockScout Version: v3.5.0-beta

* User Agent: `Mozilla/5.0 (Linux; Android 11; SAMSUNG SM-G975F) AppleWebKit/537.36 (KHTML, like Gecko) SamsungBrowser/14.0 Chrome/87.0.4280.141 Mobile Safari/537.36`

### Steps to reproduce

*Tell us how to reproduce this issue. If possible, push up a branch to your fork with a regression test we can run to reproduce locally.*

### Expected Behaviour

*Tell us what should happen.*

### Actual Behaviour

*Tell us what happens instead.*
Hi,

I made a payment to purchase STC COINS but i did not recive anh coins but here it says that the transaction was succesfull could you please confirm back,
Transaction number:
0x29c0dcda64798cc06c93d56eda72057a94757e8aa1cb711b7f3d72725bf426f4

Thank you
Regards
Muhammad akbar

**Comment by vbaranov** [comment]
Regarding your question try to reach out ETC team, for instance, on their Discord https://discord.com/invite/hQs894U.
