### ISSUE TITLE
Transfer shows success but not received

### ISSUE THREAD

**Issue by jmeps** [blockscout/blockscout#3837]
*Describe your issue here.*

Transfer of 25.69 CEL shows successful but not received. Is there a way that I can have this cancelled and put back into my mainnet account? If not, how can this be retrieved?

Transaction details can be found in the link below:

https://explorer-mainnet.maticvigil.com/tx/0x5028f0d6f002fc3e2740b75f310873681d86865b72183d9b8ed868295553c645/raw-trace

Thank you in advance for your help and assistance

### Environment
* Elixir Version: 1.11.3
* Erlang Version: 23
* BlockScout Version: v3.6.0-beta

* User Agent: `Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.72 Safari/537.36`

### Steps to reproduce

*Tell us how to reproduce this issue. If possible, push up a branch to your fork with a regression test we can run to reproduce locally.*

### Expected Behaviour

*Tell us what should happen.*

### Actual Behaviour

*Tell us what happens instead.*

**Comment by vbaranov** [comment]
There is no Matic support here. Try to ask at their fork https://github.com/maticnetwork/blockscout.
