### ISSUE TITLE
Ethereum Classic: <Issue Title>

### ISSUE THREAD

**Issue by kingcambo88** [blockscout/blockscout#3839]
*Describe your issue here.*

### Environment
* Elixir Version: 1.11.0
* Erlang Version: 23
* BlockScout Version: v3.5.0-beta

* User Agent: `Mozilla/5.0 (iPhone; CPU iPhone OS 14_4 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.0.3 Mobile/15E148 Safari/604.1`

Hi there i am new to this and I sent my etc to eth this morning on trust wallet and I till haven’t seen it in my eth account yet? I was wondering if you help me with this thanks here my 

0x252655def234112bd01c56120fbdd0e7765ca2dac3ff9eb1093806df153e5d60

**Comment by vbaranov** [comment]
Regarding your question try to reach out ETC team, for instance, on their Discord https://discord.com/invite/hQs894U.
