### ISSUE TITLE
How to reduce the usage of blockscout CPU?

### ISSUE THREAD

**Issue by bitbeb** [blockscout/blockscout#3840]
How to reduce the usage of blockscout CPU?

How to reduce the usage of blockscout CPU?
beam.smp    CPU98%

**Comment by vbaranov** [comment]
Can you tell me a little bit more about application setup? Do you have DB and application on the same machine? If yes, you can split them into different pods. Archive node also is recommended to be on a separate machine. If all these application components are distributed and you still see high CPU usage on the application server then the server is not strong enough to withstand Blockscout loading. In that case, consider migrating to a more powerful instance.

**Comment by bitbeb** [comment]
Hello, teacher, I use / opt / blockscout / docker make start
For deployment

**Comment by vbaranov** [comment]
You can set `DISABLE_INDEXER=true` env variable for dev purposes. It will stop indexing (no new data will appear), but UI will still be available.

**Comment by bitbeb** [comment]
Thank you very much

**Comment by cdivitotawela** [comment]
> You can set `DISABLE_INDEXER=true` env variable for dev purposes. It will stop indexing (no new data will appear), but UI will still be available.

Setting `DISABLE_INDEXER=true`  cause start errors as per the issue #3849
