### ISSUE TITLE
Energy Web Chain: <Issue Title>

### ISSUE THREAD

**Issue by 8313fa** [blockscout/blockscout#3841]
*Describe your issue here.* I sent EWT to bridge address 

### Environment
* Elixir Version: 1.11.0
* Erlang Version: 23
* BlockScout Version: v3.5.1-beta

* User Agent: `Mozilla/5.0 (iPhone; CPU iPhone OS 14_4_2 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.0.3 Mobile/15E148 Safari/604.1`

### Steps to reproduce

*Tell us how to reproduce this issue. If possible, push up a branch to your fork with a regression test we can run to reproduce locally.*

### Expected Behaviour

*Tell us what should happen.*how can get my tokens?

### Actual Behaviour
Not received 
*Tell us what happens instead.* should receive in my address

**Comment by vbaranov** [comment]
There is no support of EWT here
