### ISSUE TITLE
Ethereum Classic: <Issue Title>

### ISSUE THREAD

**Issue by kingbee0** [blockscout/blockscout#3842]
Hi,

I sent ETC crypto from MY coinbase app, to Safemoon crypto in MY Bitmart app, and I wasn't aware of the specific process to correctly purchase what I wanted. The send amount is to myself, and I can't claim it at all.. Can you please help me, it's greatly appreciated!

### Environment
* Elixir Version: 1.11.0
* Erlang Version: 23
* BlockScout Version: v3.5.0-beta

* User Agent: `Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.85 Safari/537.36`

### Steps to reproduce

*Tell us how to reproduce this issue. If possible, push up a branch to your fork with a regression test we can run to reproduce locally.*

### Expected Behaviour

*Tell us what should happen.*
I was supposed to convert ETC to ETH and then send the ETH to the new wallet

### Actual Behaviour
I sent ETC directly to "safemoon" crypto, in BitMart wallet & now cannot retrieve
*Tell us what happens instead.*

**Comment by vbaranov** [comment]
Regarding your question try to reach out ETC team, for instance, on their Discord https://discord.com/invite/hQs894U.
