### ISSUE TITLE
Mainnet: Unable to verify code at Contract Address 0x4A73218eF2e820987c59F838906A82455F42D98b

### ISSUE THREAD

**Issue by AndoryuRenoa** [blockscout/blockscout#3843]
Contract address 0x4A73218eF2e820987c59F838906A82455F42D98b has no code tab in the UI. The code returned from 
```
curl https://rpc-mainnet.maticvigil.com -H 'Content-Type: application/json' --data '{"jsonrpc":"2.0","method":"eth_getCode","params":["0x4A73218eF2e820987c59F838906A82455F42D98b", "latest"],"id":1}'
```
does not match code generated when using the same source file, compiler, optimization, and constructor args provided by the original contract deployer.

I've recreated the contract in both the mumbai test network and again on the matic main net. In both cases code tab is visible in the UI and bytecode is the same as each other, but different than the originally deployed contract. I'm struggling to understand what is happening here. Without being able to reproduce I cannot tell if bytecode being returned from the original mainnet has mutated. If it has mutated then without understanding exactly how, it is not possible to manually verify contract code for deployments that have experienced this issue.

Details:

Mumbai Test Network Deployment:
https://explorer-mumbai.maticvigil.com/address/0x282b1ae522132C6256fAb9C5aAf406613e222b2e/contracts

Original Deployment on Mainnet:
https://explorer-mainnet.maticvigil.com/address/0x4A73218eF2e820987c59F838906A82455F42D98b/contracts

Bytecode diff:

original mainnet address:
...c322ba88562bdec7ebb3d5d1adca9437e9d31218e4f8288f93c7a548433b0b3b64736f6c63430005110032

mumbai test address:
...b87a08c916d76b56cafffaff01ce87e07530d37ef1f07f70b2b13f3818a8ea5864736f6c63430005110032

### Environment
* Elixir Version: 1.11.3
* Erlang Version: 23
* BlockScout Version: v3.6.0-beta

* User Agent: `Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.87 Safari/537.36`

### Expected Behaviour

https://explorer-mainnet.maticvigil.com/address/0x4A73218eF2e820987c59F838906A82455F42D98b should have code tab in UI

### Actual Behaviour

https://explorer-mainnet.maticvigil.com/address/0x4A73218eF2e820987c59F838906A82455F42D98b is missing code tab in UI. curling for the bytecode is potentially also returning different bytecode than what was deployed, although I cannot replicate the code visibility issue on matic mainnet so there is no way to be sure on my end

**Comment by vbaranov** [comment]
Ask Polygon team to install this update https://github.com/blockscout/blockscout/pull/3715 to their instances. It should help with missing code tab for the contract.

**Comment by AndoryuRenoa** [comment]
Looks like polygon has updated to 3.6.0-beta which includes pull/3715 and this issue for the afore mentioned contract address persists.

**Comment by fluidsonic** [comment]
Many addresses aren't recognized as contracts.
Another example: https://explorer-mainnet.maticvigil.com/address/0x8FF56b5325446aAe6EfBf006a4C1D88e4935a914
