### ISSUE TITLE
Energy Web Chain: "This transaction is pending confirmation"

### ISSUE THREAD

**Issue by jugonautica** [blockscout/blockscout#3846]
Hi!

Last two days I can not send the assets from my Metamask when I am in the EWC (SLR, EWT...). It says "This transaction is pending confirmation". Here is the last transaction (removing liquidity) that is still pending and nothing happens... 0x871d04588492b1be6786b6212dcd8d1c68c137b08d0171ab8941a6b5a0c0e066

I have no idea why this is the case. Before reseting my MM account, I wanted to write to you, maybe you have a solution.

Would be great if you could help me with the issue, I am kind of lost here. xD

Thanks!

![Hvataj1](https://user-images.githubusercontent.com/30313674/115742297-d17a3f80-a390-11eb-83aa-18e67c15fc08.JPG)

**Comment by vbaranov** [comment]
There is no EWT support here.
