### ISSUE TITLE
Error in lib/explorer/staking/contract_state.ex:106

### ISSUE THREAD

**Issue by Kapranov** [blockscout/blockscout#3848]
I got error when starrt - mix phx.server
![screenshots](https://user-images.githubusercontent.com/1867781/115855616-29cc3400-a3c7-11eb-8ba3-d8f38a037fde.png)

**Comment by vbaranov** [comment]
@Kapranov Which application environment variables did you set?

**Comment by Kapranov** [comment]
env = development

**Comment by vbaranov** [comment]
I mean how the full set of application env variables for the application does look like? Please hide sensitive data.

**Comment by Kapranov** [comment]
export ETHEREUM_JSONRPC_VARIANT=ganache
export ETHEREUM_JSONRPC_HTTP_URL=https://explorer.velas.com/rpc
export POS_STAKING_CONTRACT=null
export POOL_SIZE=500
export BLOCKSCOUT_PROTOCOL=http
export DATABASE_URL=postgresql://my_login:my_pass@localhost:5432/blockscout
export ETHEREUM_JSONRPC_TRACE_URL=null
export ETHEREUM_JSONRPC_WS_URL=wss://explorer.velas.com/ws/rpc
export VALIDATORS_CONTRACT=null
export CHAIN_SPEC_PATH=null
export BLOCKSCOUT_HOST=0.0.0.0
export ELIXIR_VERSION=v1.11.4
export PORT=4000
export COIN=VLX
export COINGECKO_COIN_ID=velas

**Comment by Kapranov** [comment]
may be is not correct POS_STAKING_CONTRACT=null

**Comment by Kapranov** [comment]
or export VALIDATORS_CONTRACT=null

**Comment by vbaranov** [comment]
Yes, Just remove `POS_STAKING_CONTRACT` and `VALIDATORS_CONTRACT`:
```
unset POS_STAKING_CONTRACT
unset VALIDATORS_CONTRACT
```

It should resolve this issue

**Comment by Kapranov** [comment]
Thank you did help
