### ISSUE TITLE
xDai: Blockscout fetches read functions on page load

### ISSUE THREAD

**Issue by Agilulfo1820** [blockscout/blockscout#3851]
I have a contract that returns and array of structs. On page load Blockscout automatically fetches functions and I have a page fool of text.

Image: https://ibb.co/jWqrQm0
smart contract: https://blockscout.com/xdai/mainnet/tokens/0x3E5d55162db958E6C00c59a6e81587C153E18f7b/read-contract

### Environment
* Elixir Version: 1.11.3
* Erlang Version: 23
* BlockScout Version: v3.6.0-beta

* User Agent: `Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.72 Safari/537.36`

### Steps to reproduce

Create a function that returns an array of structs.

You can test here on my staging smart contract: https://blockscout.com/xdai/mainnet/tokens/0x3E5d55162db958E6C00c59a6e81587C153E18f7b/read-contract

### Expected Behaviour

It would be better that the user choose to obtain that info. With 1000 rows it would become really difficult for the user to scroll.

### Actual Behaviour

You get all te result on page loading.

**Comment by vbaranov** [comment]
Implemented in PR above ☝️ and deployed to xDai Blockscout instance.
