### ISSUE TITLE
Ethereum Classic: <Issue Title>0x84c79fa426ecceb77a603f4c058ebc8ff411ea4e630616e387e9259e4bdad724

### ISSUE THREAD

**Issue by alexsison** [blockscout/blockscout#3855]
*Describe your issue here.*

### Environment
* Elixir Version: 1.11.0
* Erlang Version: 23
* BlockScout Version: v3.5.0-beta

* User Agent: `Mozilla/5.0 (Linux; Android 10; RMX2001 Build/QP1A.190711.020; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/90.0.4430.82 Mobile Safari/537.36`

### Steps to reproduce

*Tell us how to reproduce this issue. If possible, push up a branch to your fork with a regression test we can run to reproduce locally.*

### Expected Behaviour

*Tell us what should happen.*

### Actual Behaviour

*Tell us what happens instead.*

I haven't receive my etc withdrawal in my kucoin wallet

**Comment by vbaranov** [comment]
Regarding your question try to reach out ETC team, for instance, on their Discord https://discord.com/invite/hQs894U.
