### ISSUE TITLE
Ethereum Classic: <9 hours and waiting >

### ISSUE THREAD

**Issue by thajuice765** [blockscout/blockscout#3856]
* well I have been transferring from safe wallet just fine and all of a sudden I don't get my money from transferring ETC to my coinbase from trust wallet just says pending can you please help me. It's been over 9 hours I have never waited this long before earlier was fast then boom 90 stuck in cryptoland. It says I have received but pending please help*

### Environment
* Elixir Version: 1.11.0
* Erlang Version: 23
* BlockScout Version: v3.5.0-beta

* User Agent: `Mozilla/5.0 (Linux; Android 10; STK-LX3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.66 Mobile Safari/537.36`

### Steps to reproduce

*Tell us how to reproduce this issue. If possible, push up a branch to your fork with a regression test we can run to reproduce locally.*

### Expected Behaviour

*Tell us what should happen.*

### Actual Behaviour

*Tell us what happens instead.*

**Comment by vbaranov** [comment]
Regarding your question try to reach out ETC team, for instance, on their Discord https://discord.com/invite/hQs894U.
