### ISSUE TITLE
Ethereum Classic: <long wait? 9 hours!>

### ISSUE THREAD

**Issue by thajuice765** [blockscout/blockscout#3857]
Transaction 
0x1a6edf44290b14a7676326a1085b0d0305f092ede4cf707b38222454564c55b6

I need help. Says received my ETC from trust wallet in coinbase but pending for 9 hours. Never had this happen. I was actually transferring just fine then this one is stuck? Please help.

### Environment
* Elixir Version: 1.11.0
* Erlang Version: 23
* BlockScout Version: v3.5.0-beta

* User Agent: `Mozilla/5.0 (Linux; Android 10; STK-LX3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.66 Mobile Safari/537.36`

### Steps to reproduce

*Tell us how to reproduce this issue. If possible, push up a branch to your fork with a regression test we can run to reproduce locally.*

### Expected Behaviour

*Tell us what should happen.*

### Actual Behaviour

*Tell us what happens instead.*

**Comment by vbaranov** [comment]
Regarding your question try to reach out ETC team, for instance, on their Discord https://discord.com/invite/hQs894U.
