### ISSUE TITLE
Ethereum Classic: <Issue Title> Mistake transaction

### ISSUE THREAD

**Issue by legion231** [blockscout/blockscout#3860]
*Describe your issue here.*
I actually sent ETC to ETH address. How do I recover it?
### Environment
* Elixir Version: 1.11.0
* Erlang Version: 23
* BlockScout Version: v3.5.0-beta

* User Agent: `Mozilla/5.0 (iPhone; CPU iPhone OS 14_0 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.0 Mobile/15E148 Safari/604.1`

### Steps to reproduce

*Tell us how to reproduce this issue. If possible, push up a branch to your fork with a regression test we can run to reproduce locally.*

### Expected Behaviour

*Tell us what should happen.*

### Actual Behaviour

*Tell us what happens instead.*

**Comment by legion231** [comment]
I mistakingly sent ETC to an ETH address. Pls how do I recover it?

**Comment by vbaranov** [comment]
Regarding your question try to reach out ETC team, for instance, on their Discord https://discord.com/invite/hQs894U.
