### ISSUE TITLE
Ethereum Classic: Contract Verify Not Working

### ISSUE THREAD

**Issue by recepaltas** [blockscout/blockscout#3861]
https://blockscout.com/etc/mainnet/address/0xb7f68207BF3cFe6282d9e8Dd9d283C10B9Ec7548/contract_verifications/new

I have "Connection Lost" error every time. I cant verify the contract. Why?

### Environment
* Elixir Version: 1.11.0
* Erlang Version: 23
* BlockScout Version: v3.5.0-beta

* User Agent: `Mozilla/5.0 (Macintosh; Intel Mac OS X 11_1_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.128 Safari/537.36`

### Steps to reproduce

*Tell us how to reproduce this issue. If possible, push up a branch to your fork with a regression test we can run to reproduce locally.*

### Expected Behaviour

*Tell us what should happen.*

### Actual Behaviour

*Tell us what happens instead.*

**Comment by vbaranov** [comment]
It looks like this address is rather EOA. If you insist, that this is a contract, please provide transaction hash whare it has been created. Closing for now.
