### ISSUE TITLE
Support exploring ERC-721 and ERC-1155 tokens

### ISSUE THREAD

**Issue by danimesq** [blockscout/blockscout#3864]

**Comment by vbaranov** [comment]
Could you elaborate on how do you see exploring these token types?

**Comment by DaniellMesquita** [comment]
Some people claim its difficult to explore ERC-1155 tokens on Etherscan.
Reference: https://twitter.com/Werekitty1/status/1333025326859956226

**Comment by vbaranov** [comment]
Blockscout supports exploring ERC-721, ERC-1155 tokens from the box. I am closing this issue. Please, let me know, if you still have questions.
