### ISSUE TITLE
How to change currency names in Blockscout? 

### ISSUE THREAD

**Issue by rogerganga** [blockscout/blockscout#3866]
I want to change the currency names (ETH and Ether) to a different currency name

![image](https://user-images.githubusercontent.com/34466964/116362073-3ff94a80-a834-11eb-8861-d6fd491fdca2.png)

Where should I update this config? And if I were to restart the instance in the AWS deployment what should be the code used?

**Comment by vbaranov** [comment]
https://docs.blockscout.com/for-users/faqs/how-can-i-customize-the-coin-symbol

**Comment by rogerganga** [comment]
Thanks @vbaranov I did try this. But the problem is once I go to the instance and type

`sudo systemctl restart explorer.service`

I cannot see the explorer and the service keeps restarting

I am not sure once I changed the files what code to type in inside the EC2 instance to reboot the explorer.

I use the AWS cloudfront template to deploy the explorer. Pl assist me here.

**Comment by rogerganga** [comment]
Hi @vbaranov I tried the link and it worked fine. We can close this issue. Thank you!
