### ISSUE TITLE
Mainnet: <Issue Title>

### ISSUE THREAD

**Issue by Einargn** [blockscout/blockscout#3867]
*Describe your issue here.*

### Environment
* Elixir Version: 1.11.3
* Erlang Version: 23
* BlockScout Version: v3.6.0-beta

* User Agent: `Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.93 Safari/537.36`

### Steps to reproduce

*Tell us how to reproduce this issue. If possible, push up a branch to your fork with a regression test we can run to reproduce locally.*

### Expected Behaviour

*Tell us what should happen.*

### Actual Behaviour

*Tell us what happens instead.*
0xbc796ecdd565669e67dab67494c2f536d639a5321b8a1b275a48684320350af5
0x6f6672d438f32aa2bc4c3e52ed2ef6d280f7c584495d780e200cf83138b43b19
0xeb002f793b366da0e2758f9690954a0f594a21ff74a3c0e1c898c75f22a3807c
0xe00c2c73058c0edda8da294073be3015f9467ec1020fc779a90eb19a108740bc

all of four transacction failed and charge gas equally

can we do anithing please¿
My matics are flying and I cannot claim rewards for the continued failure of the transaction

**Comment by Einargn** [comment]
0x9319ecfd25d2f8fb8dc2e828063aec2cef8199678db3e2c3366851e944eb6299

5 five transacctions fail! what happend¿¿

**Comment by vbaranov** [comment]
There is no Matic support here. Try to ask at their fork https://github.com/maticnetwork/blockscout.
