### ISSUE TITLE
Cannot customize front when deploying with AWS Marketplace

### ISSUE THREAD

**Issue by gperezalba** [blockscout/blockscout#3868]
### Environment

* Elixir & Erlang/OTP versions (`elixir -version`): Elixir 1.10.3 (compiled with Erlang/OTP 21)
* Operating System: Linux/UNIX

I deploy blockscout using AWS Marketplace. Everything goes fine. I open port 22 (SSH) to connect to EC2 in order to customize CSS. I follow the procedure in https://docs.blockscout.com/for-developers/aws-marketplace/customizing-css and no change is made in my front. I've also uncommented the poa_variables import in _variables.scss file. _variables.scss file:

`@import "theme/base_variables";
//@import "neutral_variables";
@import "poa_variables";

// responsive breakpoints
$breakpoint-xs: 320px;
$breakpoint-sm: 480px;
$breakpoint-md: 768px;
$breakpoint-lg: 992px;
$breakpoint-xl: 1024px;
$breakpoint-xxl: 1280px;
$breakpoint-xxxl: 1366px;`

I would like to change colours and images. Also I would like to hide the graph with the exchange price because my coind isn't in coinmarketcap and is confusing.

Any help is appreciated to know the right procedure to customize front when using AWS Marketplace.

Thanks in advance

**Comment by vbaranov** [comment]
>I follow the procedure in https://docs.blockscout.com/for-developers/aws-marketplace/customizing-css and no change is made in my front

You should run `mix phx.digest` at the very end to apply frontend changes.

>Also I would like to hide the graph with the exchange price because my coind isn't in coinmarketcap and is confusing.

Yes, you can disable price chart and price fetching. Take a look at https://forum.poa.network/t/customization-disable-graph/5660

**Comment by gperezalba** [comment]
Thanks for your answer, but a couple of questions more:

I've achieved to change icons, texts and customize charts. But I dont know why the changes to the theme don't apply. 

I run `mix phx.digest` so the app runs with this command so `sudo systemctl start explorer.service` won't be used anymore, isn't it?
