### ISSUE TITLE
Polygon/Matic Mainnet - HH has rebranded to MOVE

### ISSUE THREAD

**Issue by CRYPTOCOINS2018** [blockscout/blockscout#3869]
The ticker needs to be updated

https://www.coingecko.com/en/coins/mover

Polygon token address is 0x521cddc0cba84f14c69c1e99249f781aa73ee0bc

**Comment by vbaranov** [comment]
There is no Matic support here. Try to ask at their fork https://github.com/maticnetwork/blockscout.
