### ISSUE TITLE
the token balance is not accurate when retrieving data from api

### ISSUE THREAD

**Issue by eklureuil** [blockscout/blockscout#3872]
the token balance is not accurate when retrieving data from api.
I'm using the API endpoint : **api?module=account&action=tokenlist**

### Environment

* Operating System: linux
* Blockscout Version/branch: API https://blockscout.com/xdai/mainnet/api?module=account&action=tokenlist&address=

### Steps to reproduce

- use a dex to exchange tokens
- check the value on blockscout
- use the API to retrieve the balance : https://blockscout.com/xdai/mainnet/api?module=account&action=tokenlist&address=XXXX
- see that the balance is not the same between the webUI and the API

### Expected behaviour

The token balance should be the same webUI = API and the balance should be accurate

### Actual behaviour

Currently the value is different. i had empty value in the API and the value in the webUI is inaccurate.

I can provide my address if needed ..

**Comment by eklureuil** [comment]
looks like the data is fine now. but isn't supposed to be synched right after the blockchain tx ?
thanks for the feedback

**Comment by vbaranov** [comment]
`tokenlist` API endpoint should be fixed with this PR https://github.com/blockscout/blockscout/pull/4028. This is deployed to xDai instance.
