### ISSUE TITLE
when I run the blockscout, It's not right

### ISSUE THREAD

**Issue by FierceDog** [blockscout/blockscout#3875]
*Describe your issue here.*

### Environment
* Elixir & Erlang/OTP versions (`elixir -version`):23
* Operating System: centos7
* Blockscout Version/branch:  3.6.0

### Steps to reproduce

when I run mix phx.digest，it appears below, Is this wrong?
==> ethereum_jsonrpc
The input path "priv/static" does not exist
==> explorer
The input path "priv/static" does not exist
==> indexer
The input path "priv/static" does not exist
==> block_scout_web

### Expected behaviour

when I run mix phx.server,the cli appears below, I think something is wrong ?  I'm not sure, can you give me some answer?
2021-04-30T17:58:36.497 application=indexer fetcher=internal_transaction count=10 error_count=10 [error] failed to fetch internal transactions for blocks: :econnrefused
2021-04-30T17:58:36.498 application=indexer fetcher=internal_transaction count=10 error_count=10 [error] failed to fetch internal transactions for blocks: :econnrefused
2021-04-30T17:58:36.499 application=indexer fetcher=internal_transaction count=10 error_count=10 [error] failed to fetch internal transactions for blocks: :econnrefused

### Actual behaviour
the page  Average block time 、Total transaction and Wallet addresses are 0. Total blocks is not right 

*Tell us what happens instead.*

**Comment by fiexer** [comment]
Same error
With indexer missing the `mix phx.server` gives an error.

**Comment by vbaranov** [comment]
>when I run mix phx.digest，it appears below, Is this wrong?

No, that is expected behavior.

>when I run mix phx.server,the cli appears below, I think something is wrong ? I'm not sure, can you give me some answer?

Please elaborate on what archive node do you use? And what is the set of environment variables you provided for the application?

**Comment by FierceDog** [comment]
the archive node that I run is docker image openethereum/openethereum&nbsp; v3.0.0
the config in /etc/prifile is:
#blockscout
export PATH="$PATH:/opt/elixir/bin"
export PATH="/usr/pgsql-10/bin:$PATH"
export LD_LIBRARY_PATH="/usr/pgsql-10/lib"
export LD_LIBRARY_PATH=/usr/local/lib:$LD_LIBRARY_PATH
export PKG_CONFIG_PATH=/usr/local/lib/pkgconfig


export ***@***.***:5432/blockscout"
export DB_HOST=x.x.x.x
export DB_PASSWORD=123456
export DB_PORT=5432
export DB_USERNAME=postgres


export SECRET_KEY_BASE="VTIB3uHDNbvrY0+60ZWgUoUBKDn9ppLR8MI4CpRz4/qLyEFs54ktJfaNT6Z221No"


export ETHEREUM_JSONRPC_VARIANT=parity
export ETHEREUM_JSONRPC_HTTP_URL="http://x.x.x.x:8541"


#Elixir 使用 Hex 管理依赖设置：
export HEX_MIRROR="https://hexpm.upyun.com"
export HEX_CDN="https://hexpm.upyun.com"





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "blockscout/blockscout"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年5月3日(星期一) 晚上7:08
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [blockscout/blockscout] when I run the blockscout, It's not  wor right (#3875)





  
when I run mix phx.digest，it appears below, Is this wrong?
  
No, that is expected behavior.
  
when I run mix phx.server,the cli appears below, I think something is wrong ? I'm not sure, can you give me some answer?
  
Please elaborate on what archive node do you use? And what is the set of environment variables you provided for the application?

**Comment by vbaranov** [comment]
>the archive node that I run is docker image openethereum/openethereum&nbsp; v3.0.0

Did you enable `traces` on the archive node? Recommended parameters for the node are described here https://docs.blockscout.com/for-developers/information-and-settings/client-settings-parity-geth-ganache

**Comment by FierceDog** [comment]
yes, trace is on.


 the config toml file is : 

***@***.*** node1]# cat node1.toml 
[parity]
chain = "/root/.local/share/demo-spec.json"
[network]
port = 30301
[rpc]
port = 8541
apis = ["web3", "eth", "net", "pubsub", "personal", "parity", "parity_set", "traces", "rpc", "parity_accounts"]
cors = ["*"]
interface = "all"
[ui]
port = 8880
[websockets]
port = 8456
interface = "all"
apis = ["web3", "eth", "net", "pubsub", "personal", "parity", "parity_set", "traces", "rpc", "parity_accounts"]
origins = ["all "]
hosts = ["all "]

[ipc]
disable=false
[account]
password=["/root/.local/share/node.pwds"]
[mining]
engine_signer="0x4ab5623cc4a6f7176b29bbcefbd97a02376ea9c2"
reseal_on_txs="none"
usd_per_tx="0"
force_sealing = false
min_gas_price =&nbsp; 2

[footprint]
pruning = "archive"
tracing = "on"
fat_db = "on"


I use this config toml. but the question still exist.


when I run mix phx.server, cli appear:

2021-05-07T09:32:32.375 application=indexer fetcher=internal_transaction count=10 error_count=10 [error] failed to fetch internal transactions for blocks: :econnrefused
2021-05-07T09:32:32.403 application=indexer fetcher=internal_transaction count=10 error_count=10 [error] failed to fetch internal transactions for blocks: :econnrefused
2021-05-07T09:32:32.422 application=indexer fetcher=internal_transaction count=10 error_count=10 [error] failed to fetch internal transactions for blocks: :econnrefused
2021-05-07T09:32:32.478 application=indexer fetcher=internal_transaction count=10 error_count=10 [error] failed to fetch internal transactions for blocks: :econnrefused
2021-05-07T09:32:32.478 application=indexer fetcher=block_reward count=10 error_count=10 [error] failed to fetch: :econnrefused



------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "blockscout/blockscout"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年5月4日(星期二) 下午3:43
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [blockscout/blockscout] when I run the blockscout, It's not  wor right (#3875)





  
the archive node that I run is docker image openethereum/openethereum&nbsp; v3.0.0
  
Did you enable traces on the archive node? Recommended parameters for the node are described here https://docs.blockscout.com/for-developers/information-and-settings/client-settings-parity-geth-ganache

**Comment by FierceDog** [comment]
when Ichanged the file ，it works. very beautiful.
		apps/block_scout_web/mix.exs
			{:wobserver, "~> 0.2.0", github: "poanetwork/wobserver", branch: "support-https"},
			{:wobserver, "~> 0.2.0", git: "https://hub.fastgit.org/poanetwork/wobserver", branch: "support-https"},
		apps/explorer/config/dev.exs


		apps/indexer/config/dev.exs apps/indexer/config/dev.exs
			is_nil(System.get_env("ETHEREUM_JSONRPC_VARIANT")) do
		    	"ganache"
		    is_nil(System.get_env("ETHEREUM_JSONRPC_VARIANT")) do
	    		"parity"

**Comment by xrpdevs** [comment]
I ran into this issue too.

Cause was webpack.js used all of the system memory and filled swap.

Quadrupled swap size and no issues.
