### ISSUE TITLE
Energy Web Chain:TX Pending 

### ISSUE THREAD

**Issue by releonq** [blockscout/blockscout#3876]
First Transfer WETH, but no commision (0), need recovery WETH, help me.
https://explorer.energyweb.org/tx/0x96101a86e171ddb1dfff977d497b22f36a1cbd46bde49ccf199a281f83674749/raw-trace

### Environment
* Elixir Version: 1.11.0
* Erlang Version: 23
* BlockScout Version: v3.5.1-beta

* User Agent: `Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.90 Safari/537.36`

### Steps to reproduce

*Tell us how to reproduce this issue. If possible, push up a branch to your fork with a regression test we can run to reproduce locally.*

### Expected Behaviour

*Tell us what should happen.*

### Actual Behaviour

*Tell us what happens instead.*

**Comment by vbaranov** [comment]
Where is no support of Energy web chain here.
