### ISSUE TITLE
Where’s my 100$ ?

### ISSUE THREAD

**Issue by Rklangley1975** [blockscout/blockscout#3878]
I put 100$ worth of ETC in a wallet to transfer to 'Bitmart to buy ,Safemoon shares, and it says the transaction is pending. Will the money transfer or will it be put back into my ,Coinbase wallet? (I'm new at this)..

**Comment by vbaranov** [comment]
Regarding your question try to reach out ETC team, for instance, on their Discord https://discord.com/invite/hQs894U.
