### ISSUE TITLE
Ethereum Classic: <Issue Title> Please send my coins back 

### ISSUE THREAD

**Issue by owills14** [blockscout/blockscout#3879]
*Describe your issue here.*

Hello 
I have mistakenly sent you my coins. Could I have them back please? Thanks 

https://blockscout.com/etc/mainnet/tx/0xdf64a107ac7bd5474d1cb5cf1aa999ef768476df8e32eeca71949121a591bd43/internal-transactions

### Environment
* Elixir Version: 1.11.3
* Erlang Version: 23
* BlockScout Version: v3.5.0-beta

* User Agent: `Mozilla/5.0 (iPhone; CPU iPhone OS 14_4_2 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.0.3 Mobile/15E148 Safari/604.1`

### Steps to reproduce

*Tell us how to reproduce this issue. If possible, push up a branch to your fork with a regression test we can run to reproduce locally.*

### Expected Behaviour

*Tell us what should happen.*

### Actual Behaviour

*Tell us what happens instead.*

**Comment by vbaranov** [comment]
Regarding your question try to reach out ETC team, for instance, on their Discord https://discord.com/invite/hQs894U.
