### ISSUE TITLE
Mainnet: transfer in progress

### ISSUE THREAD

**Issue by Tbomboni** [blockscout/blockscout#3884]
i'm transfer usdc to matic network but after 1 hour transaction is still in progress
eth transaction was success completed
0xc9442f18c3c3fd2b06adf05adbcb5b1fee56323f933796607e5574fe05965b09

but matic wallet v2 is still "action required"

### Environment
* Elixir Version: 1.11.3
* Erlang Version: 23
* BlockScout Version: v3.6.0-beta

* User Agent: `Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.93 Safari/537.36`

### Steps to reproduce

*Tell us how to reproduce this issue. If possible, push up a branch to your fork with a regression test we can run to reproduce locally.*

### Expected Behaviour

*Tell us what should happen.*

### Actual Behaviour

*Tell us what happens instead.*

**Comment by vbaranov** [comment]
There is no Matic support here. Try to ask at their fork https://github.com/maticnetwork/blockscout.
