### ISSUE TITLE
funds lost in limbo

### ISSUE THREAD

**Issue by Oceangr0wn** [blockscout/blockscout#3890]
was transferring 466 usdc from matic to eth network using the official bridge. my funds were stuck waiting for the burn confirmation for several hours. I passed out because i waited so long. i woke up and tried to confirm on the eth end but it wont let me, keeps erroring. i understand if nothing can be done, but it was an unusual wiat time so perhaps it wasnt all user error.
im just going to write inside this because im a noob and dont know how to furthur describe the situation i know the coins got burnt so im tryimg to finalize the send
### Environment

* Elixir & Erlang/OTP versions (`elixir -version`):
* Operating System: windows 10
* Blockscout Version/branch: 

### Steps to reproduce

*Tell us how to reproduce this issue.  ❤️ if you can push up a branch to your fork with a regression test we can run to reproduce locally.*

### Expected behaviour

*Tell us what should happen.*

### Actual behaviour

*Tell us what happens instead.*

**Comment by vbaranov** [comment]
There is no Matic support here. Try to ask at their fork https://github.com/maticnetwork/blockscout.
