### ISSUE TITLE
Mainnet: <Issue Title>

### ISSUE THREAD

**Issue by tetemtotem** [blockscout/blockscout#3891]
*Describe your issue here.*

Dear Developer!  I have an issue with Matic ETH bridge. I would like to bridge some ETH from Matic Mainnet to ETH Mainnet. I have switched to Matic network, set up the amount, and started the bridge. The first chackmark appeared (Initialized) Then I have to wait for chackpoint. After 1,5 hour I have left the coumputer and swiched to the mainnet again after 5 hour. That time I have seen chackpoint arrived and the bridge platform wrote this: "Your transaction is checkpointed on Ethereum network. You need to confirm one more transaction to get your funds in your Ethereum account." I have signed the transaction and in metamask, when I check the Activity it is red, then I go to Etherscan from there, and it says: "Oops! An invalid Txn hash has been entered: 
undefined"  

...and the MAtic network says it is chackpointed, and Matic wallet asks to continue, but when I swith that button it says to change network from Matic to ETH, and when i change, the Matic wallet indicate a network error...

and my funds are there. My funds should have arrived into my account, but that transaction where my funds are on ETH chain it is an invalid transaction hash, but Matic chain says it has seen chaeckpoint so it has burned the matic ETH. Would you be so kind to help me understand how can I cancel this transaction?

### Environment
* Elixir Version: 1.11.3
* Erlang Version: 23
* BlockScout Version: v3.6.0-beta

* User Agent: `Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.93 Safari/537.36`

### Steps to reproduce

*Tell us how to reproduce this issue. If possible, push up a branch to your fork with a regression test we can run to reproduce locally.*

### Expected Behaviour

*Tell us what should happen.*

### Actual Behaviour

*Tell us what happens instead.*

**Comment by tetemtotem** [comment]
Somehow it is solved. My funds has arrived, but it is interesting, that Etherscan can not trac my activity... the status is: Fail with error 'RootChainManager: EXIT_ALREADY_PROCESSED'

**Comment by vbaranov** [comment]
There is no Matic support here. Try to ask at their fork https://github.com/maticnetwork/blockscout.
