### ISSUE TITLE
Mainnet: Connection Lost Everytime Verifying a Contract

### ISSUE THREAD

**Issue by cakesafe** [blockscout/blockscout#3896]
*Describe your issue here.*

### Environment
* Elixir Version: 1.11.3
* Erlang Version: 23
* BlockScout Version: v3.6.0-beta

### Steps to reproduce

Connection Lost every time trying to verify contract

### Expected Behaviour

The contract is verified

### Actual Behaviour

I get connection lost everytime we go to verify the contract. I believe there is an issue with the node running the explorer or server to verify contracts

**Comment by vbaranov** [comment]
On which instance of Blockscout do you observer this issue?

**Comment by OakFarm** [comment]
@vbaranov I am also getting this issue as well in Blockscout: v3.6.0-beta

**Comment by vbaranov** [comment]
@OakFarm the same question, on which instance?

**Comment by OakFarm** [comment]
> @OakFarm the same question, on which instance?

What do you mean by instance?

**Comment by vbaranov** [comment]
@OakFarm do you have a public URL where the issue can be reproduced?

**Comment by OakFarm** [comment]
> @OakFarm do you have a public URL where the issue can be reproduced?

https://explorer-mainnet.maticvigil.com/ 
I have tried to do code verification with a different deployment and having same issue. I am seeing `Connection Lost` as well in top left


![image](https://user-images.githubusercontent.com/83669429/118421895-ad580880-b687-11eb-889a-b03f994e8b08.png)

**Comment by vbaranov** [comment]
There is no Matic support here. Try to ask at their fork https://github.com/maticnetwork/blockscout.
