### ISSUE TITLE
How to get the rewards in Celo Blockchain

### ISSUE THREAD

**Issue by debasish22** [blockscout/blockscout#3900]
Hi Team,

I have set up my own celo node and was trying to map the details along with celo explorer, I did not find a way to get teh rewards from explorer. Is there any way to get the rewards from node itself using some node apis.

**Comment by vbaranov** [comment]
Blockscout provides an API endpoint to get reward per block number:

>Get block reward by block number.
?module=block&action=getblockreward&blockno={blockNumber}

Regarding Celo node, probably, you should ask at Celo forum instead. This GitHub repository is for Blockscout Core.
