### ISSUE TITLE
Ethereum Classic: typo error

### ISSUE THREAD

**Issue by nadirmaa** [blockscout/blockscout#3901]
Hello 

i would like to change the address after a typo error 
The new adress is 0xf8674c998cca814042182d7652a15a246fccedee 

thanks for help 

regards
Nadir 
![4347E2EE-36A3-4680-A039-8943683BA5EB](https://user-images.githubusercontent.com/83693862/117108684-d6bd8e00-ad83-11eb-8749-15ae211d3e83.png)

### Environment
* Elixir Version: 1.11.3
* Erlang Version: 23
* BlockScout Version: v3.5.0-beta

* User Agent: `Mozilla/5.0 (iPhone; CPU iPhone OS 14_4_2 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.0.3 Mobile/15E148 Safari/604.1`

### Steps to reproduce

*Tell us how to reproduce this issue. If possible, push up a branch to your fork with a regression test we can run to reproduce locally.*

### Expected Behaviour

*Tell us what should happen.*

### Actual Behaviour

*Tell us what happens instead.*

**Comment by vbaranov** [comment]
Regarding your question try to reach out ETC team, for instance, on their Discord https://discord.com/invite/hQs894U.
