### ISSUE TITLE
Etc transfer hasn't been completed 

### ISSUE THREAD

**Issue by Nishantjoshi9** [blockscout/blockscout#3904]
0x88344f9423215ee3567d6ba8dff7390ceebaadb1d87eaa7107b8b6faa693f996 transaction id

**Comment by Nishantjoshi9** [comment]
![Screenshot_20210505-183807_Chrome.jpg](https://user-images.githubusercontent.com/41967585/117145944-4f970700-add1-11eb-88c4-93193c18619e.jpg)

**Comment by vbaranov** [comment]
Regarding your question try to reach out ETC team, for instance, on their Discord https://discord.com/invite/hQs894U.
