### ISSUE TITLE
Ethereum Classic: <Issue Title> available balance

### ISSUE THREAD

**Issue by chris575menzer** [blockscout/blockscout#3905]
*Describe your issue here.*
0xef3bb01c2838239ef7673a64635191407ddf3bf734e5866617d713799ac822ee
### Environment
* Elixir Version: 1.11.3
* Erlang Version: 23
* BlockScout Version: v3.5.0-beta

* User Agent: `Mozilla/5.0 (Linux; Android 9; G60) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.91 Mobile Safari/537.36`

### Steps to reproduce

*Tell us how to reproduce this issue. If possible, push up a branch to your fork with a regression test we can run to reproduce locally.*

### Expected Behaviour
To be able to use my money
*Tell us what should happen.*

### Actual Behaviour

*Tell us what happens instead.*

**Comment by vbaranov** [comment]
Regarding your question try to reach out ETC team, for instance, on their Discord https://discord.com/invite/hQs894U.
