### ISSUE TITLE
Ethereum Classic: <Issue Title>It has been almost 3 hours and I have not received my etc 0x3f5a418b3f1dab4c660452330575da893c0929a28a1331ff788dcff784d0666b

### ISSUE THREAD

**Issue by giothepro** [blockscout/blockscout#3908]
*Describe your issue here.*

### Environment
* Elixir Version: 1.11.3
* Erlang Version: 23
* BlockScout Version: v3.5.0-beta

* User Agent: `Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.93 Safari/537.36`

### Steps to reproduce

*Tell us how to reproduce this issue. If possible, push up a branch to your fork with a regression test we can run to reproduce locally.*

### Expected Behaviour

*Tell us what should happen.*
Ethereum Classic: <Issue Title>It has been almost 3 hours and I have not received my etc 0x3f5a418b3f1dab4c660452330575da893c0929a28a1331ff788dcff784d0666b

### Actual Behaviour

*Tell us what happens instead.*

**Comment by giothepro** [comment]
Ethereum Classic: <Issue Title>It has been almost 3 hours and I have not received my etc 0x3f5a418b3f1dab4c660452330575da893c0929a28a1331ff788dcff784d0666b

**Comment by vbaranov** [comment]
Regarding your question try to reach out ETC team, for instance, on their Discord https://discord.com/invite/hQs894U.
