### ISSUE TITLE
Incorrect address send

### ISSUE THREAD

**Issue by afisher16** [blockscout/blockscout#3910]
I was trying to send my ethereum classic tokens to my Nano ledger cold wallet and was under the impression that all ethereum coins, ie; eth-20,would need to be sent to the ethereum wallet. I just need to know if there is a way to undo the send or if there is a way to find the person who I sent the ethereum classic to?

**Comment by vbaranov** [comment]
Regarding your question try to reach out ETC team, for instance, on their Discord https://discord.com/invite/hQs894U.
