### ISSUE TITLE
How to disable dark theme in blockscout and hide the dark theme icon in front end? 

### ISSUE THREAD

**Issue by rogerganga** [blockscout/blockscout#3922]
Is there a way to hide dark theme and use only one theme? 

If there is none, can we add a feature for the user to enable or disable dark theme as per their convenience?

**Comment by rogerganga** [comment]
For now I have removed the following line of code from _topanv.html.eex

`
      
      <button class="dark-mode-changer" id="dark-mode-changer">
        <svg xmlns="http://www.w3.org/2000/svg" width="15" height="16">
            <path fill="#9B62FF" fill-rule="evenodd" d="M14.88 11.578a.544.544 0 0 0-.599-.166 5.7 5.7 0 0 1-1.924.321c-3.259 0-5.91-2.632-5.91-5.866 0-1.947.968-3.759 2.59-4.849a.534.534 0 0 0-.225-.97A5.289 5.289 0 0 0 8.059 0C3.615 0 0 3.588 0 8s3.615 8 8.059 8c2.82 0 5.386-1.423 6.862-3.806a.533.533 0 0 0-.041-.616z"/>
        </svg>
      </button>
`

![image](https://user-images.githubusercontent.com/34466964/117264889-4320b600-ae86-11eb-9e4d-b9cdfb709b34.png)


We can set up a feature where the user can choose whether or not to have dark theme switcher using an env variable. Open for comments

**Comment by rogerganga** [comment]
@vbaranov 

There might be a need where companies would prefer to stick to their only company theme. They might not need dark theme all the time.

Could be added as a flag to enable or disable dark theme

**Comment by vbaranov** [comment]
@rogerganga it is now possible with `PERMANENT_LIGHT_MODE_ENABLED=true` environment variable.
