### ISSUE TITLE
Ethereum Classic: <Issue Title>

### ISSUE THREAD

**Issue by api187** [blockscout/blockscout#3923]
My crypto is stuck in pending 
Now 11 hours since sending 
3.033 ETC 
Please help
![8603BFCE-6FB1-4DB9-AACA-4E8D3B61EB88](https://user-images.githubusercontent.com/83752725/117259380-e30a1f80-ae45-11eb-823f-60cf1aadfa53.png)
![F737257E-35CB-4A5F-8638-C7EEF405A701](https://user-images.githubusercontent.com/83752725/117259384-e43b4c80-ae45-11eb-89d6-4e5a157b46fb.png)

### Environment
* Elixir Version: 1.11.3
* Erlang Version: 23
* BlockScout Version: v3.5.0-beta

* User Agent: `Mozilla/5.0 (iPhone; CPU iPhone OS 14_4_2 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.0.3 Mobile/15E148 Safari/604.1`

### Steps to reproduce

*Tell us how to reproduce this issue. If possible, push up a branch to your fork with a regression test we can run to reproduce locally.*

### Expected Behaviour

*Tell us what should happen.*

### Actual Behaviour

*Tell us what happens instead.*

**Comment by vbaranov** [comment]
Regarding your question try to reach out ETC team, for instance, on their Discord https://discord.com/invite/hQs894U.
