### ISSUE TITLE
Ethereum Classic:  Have not received transfer to coinbase

### ISSUE THREAD

**Issue by ccraimer** [blockscout/blockscout#3924]
Transferred ETC from gate.iO to coinbase

Says  pending  for over 10 hrs
Transaction Details

0x0b9776f8f57f3034b22a5e7ede715529945ad633eea7a2a5d4931fb59a640c2e

0x0d07–b492fe → 0x3456–be283a
Transaction
Success
18 hours ago (May-05-2021 11:16:24 AM +-4 UTC)
Block Number
12682724
Block Confirmations
5,091
Nonce
41617
TX Fee
0.000021 ETC ($0.001985 USD)
Transaction Speed
<= 12.737 seconds

**Comment by vbaranov** [comment]
Regarding your question try to reach out ETC team, for instance, on their Discord https://discord.com/invite/hQs894U.
