### ISSUE TITLE
Ethereum Classic: Refund request

### ISSUE THREAD

**Issue by willington510** [blockscout/blockscout#3925]
Hello my name's william Nieves I sent crypto to a casino online and I'm new to crypto. I guess I sent etc instead of eth I didn't know there was a difference. They don't accept etc only eth and I was wondering if I could get my crypto back please

### Environment
* Elixir Version: 1.11.3
* Erlang Version: 23
* BlockScout Version: v3.5.0-beta

* User Agent: `Mozilla/5.0 (Linux; Android 10; LM-K500) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.91 Mobile Safari/537.36`

### Steps to reproduce

*Tell us how to reproduce this issue. If possible, push up a branch to your fork with a regression test we can run to reproduce locally.*

### Expected Behaviour

*Tell us what should happen.*

### Actual Behaviour

*Tell us what happens instead.*

**Comment by willington510** [comment]
I don't understand

**Comment by willington510** [comment]
I don't understand

**Comment by vbaranov** [comment]
Regarding your question try to reach out ETC team, for instance, on their Discord https://discord.com/invite/hQs894U.
