### ISSUE TITLE
Ethereum Classic: <Issue Title>

### ISSUE THREAD

**Issue by api187** [blockscout/blockscout#3930]
*Describe your issue here.*

### Environment
* Elixir Version: 1.11.3
* Erlang Version: 23
* BlockScout Version: v3.5.0-beta

* User Agent: `Mozilla/5.0 (iPhone; CPU iPhone OS 14_4_2 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.0.3 Mobile/15E148 Safari/604.1`

### Steps to reproduce

*Tell us how to reproduce this issue. If possible, push up a branch to your fork with a regression test we can run to reproduce locally.*

### Expected Behaviour

*Tell us what should happen.*

### Actual Behaviour

*Tell us what happens instead.*
0x73816100cc0c5b9b0cd53a1b043c38b66d3e15bbcab987ad87ebf29dd8db28fa
My etc is pending in Coinbase it has sent correctly and received correctly 100% fine 
Now I have pending and I am unable to access my crypto 
I would like to know how long it will require pending and become live or whether something can be done to remove pending status 
Many thanks

**Comment by api187** [comment]
0x73816100cc0c5b9b0cd53a1b043c38b66d3e15bbcab987ad87ebf29dd8db28fa

**Comment by vbaranov** [comment]
Regarding your question try to reach out ETC team, for instance, on their Discord https://discord.com/invite/hQs894U.
