### ISSUE TITLE
Transaction completion time.

### ISSUE THREAD

**Issue by mogochips** [blockscout/blockscout#3932]
I sent ETC from my ledger wallet to coin base yesterday and although the transaction has been confirmed over 12,000 times it is still labeled as 'pending' on coinbase. Is this normal? Or the result of the increased activity surrounding the ETC token over the past few days. How long will this Transaction take so that I see the funds in my Coinbase ETC wallet?

### Environment

* Elixir & Erlang/OTP versions (`elixir -version`):
* Operating System:
* Blockscout Version/branch: 

### Steps to reproduce

*Tell us how to reproduce this issue.  ❤️ if you can push up a branch to your fork with a regression test we can run to reproduce locally.*

### Expected behaviour

*Tell us what should happen.*

### Actual behaviour

*Tell us what happens instead.*

**Comment by vbaranov** [comment]
Regarding your question try to reach out ETC team, for instance, on their Discord https://discord.com/invite/hQs894U.
