### ISSUE TITLE
Mainnet: <USDC tokens not showing from my transaction>

### ISSUE THREAD

**Issue by nimbus1030** [blockscout/blockscout#3935]
*Describe your issue here.*
Used Xpollinate app to bridge usdc tokens from bsc network to matic network. TX shows that it went through (https://explorer-mainnet.maticvigil.com/tx/0xc3660bc408c85739232ffab7bf3fcddcc24aed070cda909d3056a72f60b4439c/token-transfers) but the token never showed on my metamask wallet (https://explorer-mainnet.maticvigil.com/address/0xD748e6C561197076D4E93330E59c613D86a72613/transactions) . 
Need help recovering funds.

### Environment
* Elixir Version: 1.11.3
* Erlang Version: 23
* BlockScout Version: v3.6.0-beta

* User Agent: `Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.128 Safari/537.36`

### Steps to reproduce

Used Xpollinate to bridge USDC from BSC to Matic (https://www.xpollinate.io/). It got timed out in between but now the USDC is not on my wallet even though it shows the tx went through

### Expected Behaviour

I should have 101.501243 USDC in my metamask wallet under the matic network

### Actual Behaviour

not sure where my USDC went.

**Comment by vbaranov** [comment]
There is no Matic support here. Try to ask at their fork https://github.com/maticnetwork/blockscout.
