### ISSUE TITLE
xDai: <Issue Title>

### ISSUE THREAD

**Issue by Zatara555** [blockscout/blockscout#3939]
*Describe your issue here.*
A couple of days ago I tried to receive my .10xdai to my MetaMask and it looked like it normally did but then I received an error. When I tried again it told me I already received my .10xdai which never made it to my MetaMask. Now when I tried today it tells me I haven’t spent the last .10xdai so I can’t send more. I’m in a loop because I never received the first but can’t continue without spending money I didn’t receive. Please if you have any help for me that would be greatly appreciated. Thank you in advance
### Environment
* Elixir Version: 1.11.3
* Erlang Version: 23
* BlockScout Version: v3.6.0-beta

* User Agent: `Mozilla/5.0 (iPhone; CPU iPhone OS 14_4_2 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.0.3 Mobile/15E148 Safari/604.1`

### Steps to reproduce

*Tell us how to reproduce this issue. If possible, push up a branch to your fork with a regression test we can run to reproduce locally.*

### Expected Behaviour

*Tell us what should happen.*

### Actual Behaviour

*Tell us what happens instead.*

**Comment by vbaranov** [comment]
Here is the issue tracker for Blockscout only. Try to ask your question in the Forum https://forum.poa.network/
