### ISSUE TITLE
Ethereum Classic: <Issue Title>

### ISSUE THREAD

**Issue by isa0823** [blockscout/blockscout#3955]
My ETC payment of 250 to TELCOIN has not went through to my account and it’s saying the payment was completed.. can I please be refunded of my transaction or swap the funds for me please.

**Comment by isa0823** [comment]
Why was this closed with an explanation??? So you guys aren’t willing to help me out with my issues ?

**Comment by vbaranov** [comment]
This is not ETC chat. Regarding your question try to reach out ETC team, for instance, on their Discord https://discord.com/invite/hQs894U.
