### ISSUE TITLE
Mobile Address page API endpoints

### ISSUE THREAD

**Issue by acravenho** [blockscout/blockscout#397]
Below is information we should be displaying with regards to the mobile view address page:

- [x] balances
- [ ] tokens (no db schema yet)
- [ ] social links for token info (no db schema yet) 
- [ ] usd balance
- [ ] transactions (`to_address_hash`, `from_address_hash`, `block_number`, `status`, `value`, `hash`) If missing `to` field we should be grabbing the `created_contract_address_hash` from internal_transactions
- [ ] internal transactions (`type = call > 0`, all other `type`, `to_address_hash`, `from_address_hash`, `value`, `transaction_hash`)

**Comment by vbaranov** [comment]
Not relevant due to migration to the new UI.
