### ISSUE TITLE
Requested ordering of token transfers is not respected

### ISSUE THREAD

**Issue by patriksletmo** [blockscout/blockscout#3988]
Because of how inner joins are handled in SQL, the requested ordering of token transfers is sometimes lost in the final step of the database query. It appears that usage of INNER JOIN makes the database engine free to scramble previously ordered data in an effort to make the database query execute faster.

Adding the following patch appears to fix the issue:
```diff
--- a/apps/explorer/lib/explorer/etherscan.ex
+++ b/apps/explorer/lib/explorer/etherscan.ex
@@ -461,6 +461,7 @@ defmodule Explorer.Etherscan do
         inner_join: t in Transaction,
         on: tt.transaction_hash == t.hash and tt.block_number == t.block_number and tt.block_hash == t.block_hash,
         inner_join: b in assoc(t, :block),
+        order_by: [{^options.order_by_direction, b.number}],
         select: %{
           token_contract_address_hash: tt.token_contract_address_hash,
           transaction_hash: tt.transaction_hash,
```

During testing I also found that the tests related to token transfer ordering are broken. The list of found token transfers appears to be empty, which can be revealed by the below patch:

```diff
--- a/apps/explorer/test/explorer/etherscan_test.exs
+++ b/apps/explorer/test/explorer/etherscan_test.exs
@@ -1182,6 +1182,7 @@ defmodule Explorer.EtherscanTest do

       block_numbers_order = Enum.map(found_token_transfers, & &1.block_number)

+      assert Enum.count(block_numbers_order) == 3
       assert block_numbers_order == Enum.sort(block_numbers_order, &(&1 >= &2))
     end

@@ -1216,6 +1217,7 @@ defmodule Explorer.EtherscanTest do

       block_numbers_order = Enum.map(found_token_transfers, & &1.block_number)

+      assert Enum.count(block_numbers_order) == 3
       assert block_numbers_order == Enum.sort(block_numbers_order, &(&1 >= &2))
     end
```

It looks like the bug was introduced in #3012, and it's possible that the bug wasn't caught because the above test cases were not failing the way they should've. At the same time, this bug appears to be dependent on the environment so it's possible that the bug wouldn't have been caught anyway.

### Environment

* Elixir & Erlang/OTP versions (`elixir -version`):
```
Erlang/OTP 23 [erts-11.2] [source] [64-bit] [smp:4:4] [ds:4:4:10] [async-threads:1] [hipe]

Elixir 1.11.2 (compiled with Erlang/OTP 23)
```
* Operating System: Ubuntu 18.04.3 LTS
* Blockscout Version/branch: v3.7.0-beta
* PostgreSQL: psql (PostgreSQL) 10.16 (Ubuntu 10.16-0ubuntu0.18.04.1)

### Steps to reproduce
I wanted to find an instance of this issue on an official Blockscout instance, but wasn't able to. Given the nature of this bug, it doesn't seem to happen in every environment, making it difficult to reproduce. However, I think that the definition should be enough to motivate a fix.

### Expected behaviour
Token transfers should be returned in the requested order (ascending or descending).

### Actual behaviour
The requested ordering is sometimes not respected, which makes the token transfers be returned in ascending order regardless of preference.

**Comment by vbaranov** [comment]
Hi @patriksletmo, thank you! Let me check your fix. Probably, you want to create a Pull request with a suggested fix? If it, indeed fixes the issue with ordering, I would love to merge it.

**Comment by patriksletmo** [comment]
@vbaranov Thanks! I created a pull request just now. Let me know if I should change anything.
