### ISSUE TITLE
I sent my ETC TO ETH address 

### ISSUE THREAD

**Issue by gelare88** [blockscout/blockscout#3991]
#I sent my ETC TO ETH address can you tell me how i can recover my ETC 0x8dc7594ae5ef698e8b30ddfaf3df1a9df65cd80447a9c4c0ce25e31f7b130562*Describe your issue here.*

### Environment

* Elixir & Erlang/OTP versions (`elixir -version`):
* Operating System:
* Blockscout Version/branch: 

### Steps to reproduce

*Tell us how to reproduce this issue.  ❤️ if you can push up a branch to your fork with a regression test we can run to reproduce locally.*

### Expected behaviour

*Tell us what should happen.*

### Actual behaviour

*Tell us what happens instead.*

**Comment by memo747** [comment]
I did the same think. Would like to know how to get back Tokens

**Comment by vbaranov** [comment]
Regarding your question try to reach out ETC team, for instance, on their Discord https://discord.com/invite/hQs894U.
