### ISSUE TITLE
Mainnet: Contract address is showing up as Externally Owned Address

### ISSUE THREAD

**Issue by Moonster-BSC** [blockscout/blockscout#4006]
Here's the contract address:
https://explorer-mainnet.maticvigil.com/address/0x251d9837a13F38F3Fe629ce2304fa00710176222/transactions

### Environment
* Elixir Version: 1.11.3
* Erlang Version: 23
* BlockScout Version: v3.6.0-beta

* User Agent: `Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.93 Safari/537.36`

### Steps to reproduce

This is a quickswap reward pool. Use this link to interact with it: https://quickswap.exchange/#/quick/0x2791Bca1f2de4661ED88A30C99A7a9449Aa84174/0xc2132D05D31c914a87C6611C10748AEb04B58e8F/0x251d9837a13F38F3Fe629ce2304fa00710176222
### Expected Behaviour

maticvigil should show a code tab to see the contract code as well as other contract related tabs.
### Actual Behaviour
Shows Externally owned address tabs

**Comment by vbaranov** [comment]
There is no Matic support here. Try to ask at their fork https://github.com/maticnetwork/blockscout.
