### ISSUE TITLE
Validator's metadata in custom PoA chain

### ISSUE THREAD

**Issue by gperezalba** [blockscout/blockscout#4013]
After deploying Blockscout using AWS Marketplace for a PoA custom chain I would like to show validator's metadata. What would be the process to be able to show it (as in POA)? Is it enough to deploy contracts and set env var with it's address?

### Environment

* Elixir & Erlang/OTP versions (`elixir -version`):
Erlang/OTP 22 [erts-10.7.2.3] [source] [64-bit] [smp:2:2] [ds:2:2:10] [async-threads:1] [hipe]

Elixir 1.10.3 (compiled with Erlang/OTP 21)

* Operating System: Amazon Linux AMI
* Blockscout Version/branch: v3.7.0-beta

**Comment by vbaranov** [comment]
You need to set 2 ENV vars:
```
export VALIDATORS_CONTRACT=0x...
export METADATA_CONTRACT=0x...
```

> VALIDATORS_CONTRACT 
> This environment variable is specifically used by POA Network to obtain the list of current validators.

> METADATA_CONTRACT
> This environment variable is specifically used by POA Network to obtain Validators information to display in the UI.

Reference https://docs.blockscout.com/for-developers/information-and-settings/env-variables

Validators contract should have this interface:
https://github.com/poanetwork/poa-chain-spec/blob/core/abis/PoaNetworkConsensus.abi.json

Metadata contract should have this interface:
https://github.com/poanetwork/poa-chain-spec/blob/core/abis/ValidatorMetadata.abi.json
