### ISSUE TITLE
Ethereum Classic: sent to 1inch eth wallet

### ISSUE THREAD

**Issue by cj600** [blockscout/blockscout#4016]
I accidentally sent my ETC to 1inch wallet that accepts ETH. It appears the transaction was successful however I don’t see anything in the destination wallet. What should I do? 

### Environment
* Elixir Version: 1.11.3
* Erlang Version: 23
* BlockScout Version: v3.5.0-beta

* User Agent: `Mozilla/5.0 (iPhone; CPU iPhone OS 14_4_2 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.0.3 Mobile/15E148 Safari/604.1`

### Steps to reproduce

*Tell us how to reproduce this issue. If possible, push up a branch to your fork with a regression test we can run to reproduce locally.*

### Expected Behaviour

*Tell us what should happen.*

### Actual Behaviour

*Tell us what happens instead.*

**Comment by kourtzlii** [comment]
same issue here

**Comment by cj600** [comment]
Why was this closed @vbaranov?

**Comment by vbaranov** [comment]
Because this is not related to Blockscout. Regarding your question try to reach out ETC team, for instance, on their Discord https://discord.com/invite/hQs894U.
