### ISSUE TITLE
Ethereum Classic: <Issue Title>

### ISSUE THREAD

**Issue by kondr88** [blockscout/blockscout#4027]
*Transferred crypto to wrong address Etherium wallet on a Trust wallet*

### Environment
* Elixir Version: 1.11.3
* Erlang Version: 23
* BlockScout Version: v3.5.0-beta

* User Agent: `Mozilla/5.0 (iPhone; CPU iPhone OS 14_4_2 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.0.3 Mobile/15E148 Safari/604.1`

### Steps to reproduce

*please cancel the transfer.
0xe4455eb39e39529745589a97488e637fbb328bdaac50a1adf4c0308169a80193*

### Expected Behaviour

*Id like to cancel the transaction*

### Actual Behaviour

*Transaction still pending*

**Comment by kondr88** [comment]
Hi can you help out with my issue

**Comment by vbaranov** [comment]
Regarding your question try to reach out ETC team, for instance, on their Discord https://discord.com/invite/hQs894U.
