### ISSUE TITLE
Internal server error on the verify-via-flattened-code screen

### ISSUE THREAD

**Issue by uncutest** [blockscout/blockscout#4029]
`Internal server error `on the **_verify via flattened code_** screen
after using verify & Publish button  on RSK mainnet explorer.

![image](https://user-images.githubusercontent.com/45270124/118176134-62c85900-b407-11eb-8479-dba94bb0c03b.png)
I have the same issue with different contracts.

**Comment by vbaranov** [comment]
@uncutest thanks for bringing this up. It should be fixed. Please check on your side.
