### ISSUE TITLE
Ethereum Classic: transaction ID - 0xeb36934147a783f9cb8b48e08a89e9b4beb1a66e06ea128fdd739fa4f91cdd1e

### ISSUE THREAD

**Issue by Crorick30** [blockscout/blockscout#4034]
Good evening. 

Re: transaction ID#:

0xeb36934147a783f9cb8b48e08a89e9b4beb1a66e06ea128fdd739fa4f91cdd1e

I am trying to find out what is going on with a transaction I sent from exodus to Celsius involving my ethereum classic. Exodus is showing it as sent and Celsius is showing is as confirmed but it’s not there and I spoke with Celsius and they said the transaction failed amd to send again. I can’t send again because exodus is showing it as sent 

 
### Environment
* Elixir Version: 1.11.3
* Erlang Version: 23
* BlockScout Version: v3.5.0-beta

* User Agent: `Mozilla/5.0 (iPhone; CPU iPhone OS 14_4_2 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.0.3 Mobile/15E148 Safari/604.1`

### Steps to reproduce

*Tell us how to reproduce this issue. If possible, push up a branch to your fork with a regression test we can run to reproduce locally.*

### Expected Behaviour

*Tell us what should happen.*

### Actual Behaviour

*Tell us what happens instead.*

**Comment by Crorick30** [comment]
Hi Victor. 

Sorry I’m nee to this. Was there a response to this?  I just see that it was closed. What do I do about my missing money 

Chris

**Comment by vbaranov** [comment]
Your question doesn't relate to Blockscout. Regarding your question try to reach out ETC team, for instance, on their Discord https://discord.com/invite/hQs894U.

**Comment by Crorick30** [comment]
Sorry I’m nee to all this but the transaction ID led me to blockscout. So from my angle it appears that you blocks out is involved somehow and looks like blocks out is the middle entity in the process so I am confused as to how it doesn’t relate to blockscout especially when my Money is stuck somewhere in the middle
