### ISSUE TITLE
xDai: <Issue Title>

### ISSUE THREAD

**Issue by ILOVEJESUSTOO** [blockscout/blockscout#4040]
*Describe your issue here.*

### Environment
* Elixir Version: 1.11.3
* Erlang Version: 23
* BlockScout Version: v3.7.0-beta

* User Agent: `Mozilla/5.0 (iPhone; CPU iPhone OS 14_4 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) CriOS/87.0.4280.163 Mobile/15E148 Safari/604.1`

### Steps to reproduce

*Tell us how to reproduce this issue. If possible, push up a branch to your fork with a regression test we can run to reproduce locally.*

### Expected Behaviour

*Tell us what should happen.*

### Actual Behaviour

*Tell us what happens instead.*

**Comment by ILOVEJESUSTOO** [comment]
Dear Sir or Madam, can you please tell me if you could give me another faucet? This one is empty:  https://blockscout.com/xdai/mainnet/faucet?__cf_chl_jschl_tk__=2e28f4b2cb20f126bc9052b560f5677e9f40471e-1619971247-0-AcU8cC1nfUyklQkqgDp3Hg6NhYZH9OFFFQn-nfKTeLM0WC1gp0OFQTDXGQVLlWwh6k0KXN81-GWYDU_r9KUINg7gasG44ao3-2Jc56Z5Zf5ZUSkVcPkY-dLi7f5BvxbAZoWeifIpK4Bbk0_fd4nJNalAOskZcSeUHgEHuaeR9Zc4W7qMy1zgYLGUMy-u3lx0phUCbNw3ajYZrukn8pTT54_r1t3Mq6U_jtY6hPU42X4xhrrTvjAYwTbWZtfEUlJbUB4EetWCJBmBxxwB5EWP2c9pFn2zWsOhJqlulxVR2GhUhMJMggez8-ZEcHdSySRiVkfzd4Oqbw9MW6XFhufOSGR72GqQo-B17Zviv2FxS7ixxVYdA4OXxvlX4hate6a2-ZyMQKUEJuuZwK4RgHddX5gUNSjPka1nnM9uf9uMhMGZr6y38Sm5VmLn_R_bkSpsnAcO4z1q5yz1tFBn2seXTl96rV-ZI6Fo1kgBNlN159Ct  

Thank you

**Comment by vbaranov** [comment]
Try https://xdai-app.herokuapp.com/faucet

**Comment by ILOVEJESUSTOO** [comment]
Dear Sir or Madam,
 
 Thank you for this link. However it did not work. I really appreciate you trying though. Can you please give me a list of faucets? 


Thank you
