### ISSUE TITLE
Ethereum Classic:  Ethereum Classic withdrawal from Binance since 6th May

### ISSUE THREAD

**Issue by Okonna** [blockscout/blockscout#4058]
*Describe your issue here.*
Hi. I withdrew some ETC from the Binance exchange to the Binance Smart chain wallet on the 6th of May,2021 but the transaction is still being confirmed on the blockscout network. Please, advise me on what to do to have the ETC in my wallet.
Here is the transaction id: 0x1ee798a5fbe6f01756ec84f1399c38186c9f980d8edd7a9f486496948008964e.
My laptop is using windows 10 and chrome browser. Attached is a screenshot of the transaction on blockscout
![evidence_of_transaction_](https://user-images.githubusercontent.com/41548746/118403465-58f06100-b666-11eb-828f-a5c95076f388.png)

### Environment
* Elixir Version: 1.11.3
* Erlang Version: 23
* BlockScout Version: v3.5.0-beta

* User Agent: `Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.212 Safari/537.36`

### Steps to reproduce

*Tell us how to reproduce this issue. If possible, push up a branch to your fork with a regression test we can run to reproduce locally.*

### Expected Behaviour

*Tell us what should happen.*

### Actual Behaviour

*Tell us what happens instead.*

**Comment by vbaranov** [comment]
You should ask Binance exchange
