### ISSUE TITLE
didnt receive my matic to my other wallet i sent it to 

### ISSUE THREAD

**Issue by onlyphans1** [blockscout/blockscout#4059]
https://explorer-mainnet.maticvigil.com/address/0xe01397eb84ccCa7882BB6e69f75b6B9E35D7d9Da/transactions
### Environment
* Elixir Version: 1.11.3
* Erlang Version: 23
* BlockScout Version: v3.6.0-beta

* User Agent: `Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.212 Safari/537.36 Edg/90.0.818.62`

### Steps to reproduce

*Tell us how to reproduce this issue. If possible, push up a branch to your fork with a regression test we can run to reproduce locally.*

### Expected Behaviour

*Tell us what should happen.*

### Actual Behaviour

*Tell us what happens instead.*

**Comment by vbaranov** [comment]
There is no Matic support here. Try to ask at their fork https://github.com/maticnetwork/blockscout.
