### ISSUE TITLE
Energy Web Chain: lost wETH

### ISSUE THREAD

**Issue by jcrisosto** [blockscout/blockscout#4060]
*Describe your issue here.*
I  was attempting to supply liquidity to a wEWT/wETH pool but inadvertently sent EWT and wETH. My EWT was retained but I lost roughly .6 wETH. How do I get the wETH back? I received no CLP token once I completed the transaction. Details can be seen below:

0xa6a796b37da42ab4830774e641202e6421ccfc268b333fbc2c900d250b4b2073

### Environment
* Elixir Version: 1.11.3
* Erlang Version: 23
* BlockScout Version: v3.6.0-beta

* User Agent: `Mozilla/5.0 (iPhone; CPU iPhone OS 13_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) CriOS/76.0.3809.123 Mobile/15E148 Safari/605.1`

### Steps to reproduce

*Tell us how to reproduce this issue. If possible, push up a branch to your fork with a regression test we can run to reproduce locally.*

### Expected Behaviour

*Tell us what should happen.*

### Actual Behaviour

*Tell us what happens instead.*

**Comment by vbaranov** [comment]
There is no support of Energy Web Chain here. Try ask their team. For instance, in their fork of Blockscout.
