### ISSUE TITLE
Mainnet: Not possible to save source code for a contract

### ISSUE THREAD

**Issue by sullof** [blockscout/blockscout#4070]
*Describe your issue here.*

When I try to add the source code to a contract the process does not work because there is a problem with the web sockets.

### Environment
* Elixir Version: 1.11.3
* Erlang Version: 23
* BlockScout Version: v3.6.0-beta

* User Agent: `Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.212 Safari/537.36`

### Steps to reproduce

I opened https://explorer-mainnet.maticvigil.com/address/0x9F0F2fC519F3169C51081d54D9f8E484BDeC36F7/contract_verifications/new to verify the source code. If you do the same, you will see that the connection gets lost after few seconds. If you inspect the console, you can see an error like this:
```
chain-cc3701c66c65a4752c57cd9573059f2c.js?vsn=d:2 WebSocket connection to 'wss://explorer-mainnet.maticvigil.com/socket/websocket?locale=en&vsn=2.0.0' failed: 
```

### Expected Behaviour

It should verify the source code.

### Actual Behaviour

It gets stuck after pressing _Verify & Publish_.

**Comment by PaulMuller** [comment]
Same problem here. Cant verify any contract around 2 weeks

**Comment by vbaranov** [comment]
The problem has been resolved. For third party maintainers: please use this guide to configure smart-contract verification microservice https://docs.blockscout.com/for-developers/information-and-settings/smart-contract-verification.
