### ISSUE TITLE
Mumbai: "Connection Lost" verifying contract source code

### ISSUE THREAD

**Issue by raugfer** [blockscout/blockscout#4071]
Cannot verify the source code of a contract on Mumbai.

### Environment

* BlockScout Version: v3.7.0-beta
* User Agent: `Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.90 Safari/537.36`

### Steps to reproduce

Just try to verify the source code of any contract.

### Expected Behaviour

Contract should be verified by the explorer.

### Actual Behaviour

Nothing happens an a message "Connection Lost" in printed on the page header.

**Comment by danilowhk** [comment]
I am also having the same connection problem

**Comment by vbaranov** [comment]
@raugfer does the issue still exist? The instance of Blockscout was updated to the latest 4.1.1 release. Could you share verification details if the issue still persists?
