### ISSUE TITLE
xDai: <cant speed up or cancel the transaction>

### ISSUE THREAD

**Issue by saikohli** [blockscout/blockscout#4074]
Transaction created with a value of 0 xDai at 07:04 on 5/18/2021.
Transaction submitted with gas fee of 0 WEI at 07:05 on 5/18/2021.
Transaction cancel attempted with gas fee of 0.001 ETH at 07:07 on 5/18/2021
Transaction cancel attempted with gas fee of 0.001 ETH at 07:09 on 5/18/2021
Transaction cancel attempted with gas fee of 0.002 ETH at 07:12 on 5/18/2021
Speed up this cancellation
 waited for more than 12 hrs still not apering on explorer, cant cancel or speed up the transaction
### Environment
* Elixir Version: 1.11.3
* Erlang Version: 23
* BlockScout Version: v3.7.0-beta

* User Agent: `Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:88.0) Gecko/20100101 Firefox/88.0`

### Steps to reproduce

*Tell us how to reproduce this issue. If possible, push up a branch to your fork with a regression test we can run to reproduce locally.*

### Expected Behaviour

*Tell us what should happen.*

### Actual Behaviour

*Tell us what happens instead.*

**Comment by vbaranov** [comment]
The issue is not related to Blockscout. Try to ask at https://forum.poa.network/c/support/xdai-support/34
