### ISSUE TITLE
Polygon: "Connection Lost" while verifying contract source code

### ISSUE THREAD

**Issue by exhyn** [blockscout/blockscout#4076]
I've been trying to validate a smart contract without luck for the past 24 hours.
This is very important for us as it's the main TimelockController of the protocol.

[Unverified TimelockController](https://explorer-mainnet.maticvigil.com/address/0x00B0CaBD76fe5913D6CDF1d3A216b808B118F06d/contracts)

[Same code deployed on BSC](https://bscscan.com/address/0x00B0CaBD76fe5913D6CDF1d3A216b808B118F06d#code)

### Environment
* BlockScout Version: v3.6.0-beta
* Compiler: v0.8.4
* Chain: Polygon
* User-agent:  Mozilla/5.0 (X11; Fedora; Linux x86_64; rv:88.0) Gecko/20100101 Firefox/88.0

### Steps to reproduce

1. Navigate to the [contract page](https://explorer-mainnet.maticvigil.com/address/0x00B0CaBD76fe5913D6CDF1d3A216b808B118F06d/contracts)
2. Click "Verify & Publish"
3. Fill the details:
  name: TimelockController
  compiler: 0.8.4
  optimization: 200
  source: [source code](https://bscscan.com/address/0x00B0CaBD76fe5913D6CDF1d3A216b808B118F06d#code)
  fetch arguments: true
4. Click "Verify & Publish"

Alternatively, passing the params manually encoded should work:
`0000000000000000000000000000000000000000000000000000000000093a80000000000000000000000000000000000000000000000000000000000000006000000000000000000000000000000000000000000000000000000000000000c0000000000000000000000000000000000000000000000000000000000000000200000000000000000000000042a426a3ee01d8d1a9a0a3724a532fd582efe402000000000000000000000000fa38503c35d5bf7b91a47c46f02a0aa0b6ab02eb000000000000000000000000000000000000000000000000000000000000000200000000000000000000000042a426a3ee01d8d1a9a0a3724a532fd582efe402000000000000000000000000fa38503c35d5bf7b91a47c46f02a0aa0b6ab02eb`

### Expected behaviour

The code of the smart contract should be validated. 

### Actual behaviour

A 204 response is received without content, the message "Connection Lost" appears on the page header.
The smart contract remains unverified.

**Comment by peterbajwa** [comment]
Facing the same issue. any help is appreciated

**Comment by vbaranov** [comment]
This issue should be resolved with Blockscout 4.1.1.
