### ISSUE TITLE
Mainnet: Adress 0x6084Fa7C1Bb29fdF9a4e991e12e515FAD6c336B1

### ISSUE THREAD

**Issue by NunoFunico** [blockscout/blockscout#4077]
Hi, I lost my acess to this adress and I made an transaction to it 2 months ago, of 1881 Matic, is t possibe to recover the acess to that adress?

### Environment
* Elixir Version: 1.11.3
* Erlang Version: 23
* BlockScout Version: v3.6.0-beta

* User Agent: `Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.212 Safari/537.36`

### Steps to reproduce

*Tell us how to reproduce this issue. If possible, push up a branch to your fork with a regression test we can run to reproduce locally.*

### Expected Behaviour

*Tell us what should happen.*

### Actual Behaviour

*Tell us what happens instead.*

**Comment by vbaranov** [comment]
There is no Matic support here. Try to ask at their fork https://github.com/maticnetwork/blockscout.
