### ISSUE TITLE
[MATIC] - Transaction / Block is missing / not being indexed appropriately 

### ISSUE THREAD

**Issue by hilmarx** [blockscout/blockscout#4084]
*Describe your issue here.*

Some blocks / transactions are not getting indexed, which gives users the impression that funds are missing in their account as no token receive transactions are shown on their explorer account page.

For example, this transactions which sent 0.007 WETH to a user:
0x51484a8276243f48c63def1e6c5788e1b22c0b3d53c4d26f9bc9d91e1691c43b

On the official matic explorer it is missing:
https://explorer-mainnet.maticvigil.com/tx/0x51484a8276243f48c63def1e6c5788e1b22c0b3d53c4d26f9bc9d91e1691c43b

On tenderly it is actually shown:
0x51484a8276243f48c63def1e6c5788e1b22c0b3d53c4d26f9bc9d91e1691c43b

### Environment

https://explorer-mainnet.maticvigil.com/

**Comment by vbaranov** [comment]
There is no Matic support here. Try to ask at their fork https://github.com/maticnetwork/blockscout.
