### ISSUE TITLE
Mainnet: <Issue Title> Tra

### ISSUE THREAD

**Issue by Honeydrop12** [blockscout/blockscout#4085]
*Describe your issue here.*
Please help me! I mistakenly transferred usdt from my matic network to erc20. Now the token was not delivered. Here’s the tx Id- 0x829bc76342c1e9205649089ce05053fc7c98429d37a46e48a2e006ce82e48c32

Please help me- I beg you, please help me.

### Environment
* Elixir Version: 1.11.3
* Erlang Version: 23
* BlockScout Version: v3.7.0-beta

* User Agent: `Mozilla/5.0 (iPhone; CPU iPhone OS 14_4_2 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Mobile/15E148`

### Steps to reproduce

*Tell us how to reproduce this issue. If possible, push up a branch to your fork with a regression test we can run to reproduce locally.*

### Expected Behaviour

*Tell us what should happen.*

### Actual Behaviour

*Tell us what happens instead.*

**Comment by Honeydrop12** [comment]
Why did you close this?

**Comment by vbaranov** [comment]
There is no Matic support here. Try to ask at their fork https://github.com/maticnetwork/blockscout.
