### ISSUE TITLE
Matic coins transfer unable to receive on OKEx exchange

### ISSUE THREAD

**Issue by Rajeshap241063** [blockscout/blockscout#4089]
I processed transfer from Matic network from metamask platform to OXEx exchange.

Please assist to get back my token back to my metamask matic wallet  0xffAd791Ad8955e619AE722de64aB72E6cCD84954 

Please see below details

Thank  you for your assistance.

Thanks & regards

Rajesh

Transaction details

0x44ae7dbc51a37f6e50dd76706f270c84860b67f22540be1845cc13ee87d90cf7

token name -  Matic

Amount $419

From    0xffAd791Ad8955e619AE722de64aB72E6cCD84954 

To    0x362033192118aAeC96e741c74e37432E95e492Db

State Logs - Browser -  In attached

Background Logs (Chrome)
bg-libs.js:16 Invalid asm.js: Unexpected token
![Untitled](https://user-images.githubusercontent.com/84398401/118998426-12bd3980-b9a7-11eb-92e7-828297cb5fcc.png)

**Comment by vbaranov** [comment]
There is no Matic support here. Try to ask at their fork https://github.com/maticnetwork/blockscout.
