### ISSUE TITLE
Matic Token sent to Smart Wallet not received

### ISSUE THREAD

**Issue by GreatMoh** [blockscout/blockscout#4091]
Hi,

I have sent Matic Token, I haven't received it. is it possible to recover?

Transaction Details
0xc56af6f05bf9145743097df29ebb57218cfe1bfea8bddb27e0886680bae2138a
0x727D8639783D400C5eA7d18ca2A4F40Cc84f54Cf → 0xdb5365aB88FFA430050236D9fE8Af5DCd7eB3691
Transaction
Success
15 days ago (May-05-2021 07:40:09 PM +1 UTC)
Block Number
14130992
Block Confirmations
598,342
Nonce
1
TX Fee
0.000105 MATIC ($0.000184 USD)
Transaction Speed
<= 2.061 seconds

Regards,
Moh

### Environment
* Elixir Version: 1.11.3
* Erlang Version: 23
* BlockScout Version: v3.6.0-beta

* User Agent: `Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.212 Safari/537.36`

### Steps to reproduce

*Tell us how to reproduce this issue. If possible, push up a branch to your fork with a regression test we can run to reproduce locally.*

### Expected Behaviour

*Tell us what should happen.*

### Actual Behaviour

*Tell us what happens instead.*

**Comment by vbaranov** [comment]
There is no Matic support here. Try to ask at their fork https://github.com/maticnetwork/blockscout.
