### ISSUE TITLE
Mainnet: I withdrawed my funds to Matic Network hours ago and I still haven't received them

### ISSUE THREAD

**Issue by alphalcoholico** [blockscout/blockscout#4093]
I withdrawed my funds (5449 USDC) to my Matic Network wallet on the Metamask extension (0x7c89c5d8A72caE858Ee18bc14AE85c464674B48D). It's been hours and I still haven't received them. 

![image](https://user-images.githubusercontent.com/82844448/119067086-aa2a8880-b9b7-11eb-8762-3ee9cb180501.png)

As you can see, it shows as "Success". But I still haven't got my money, and my Matic explorer is BLANK.

![image](https://user-images.githubusercontent.com/82844448/119067177-de9e4480-b9b7-11eb-89a8-dd9aa4f3233c.png)

It's no small amount. I WANT MY MONEY BACK.

I don't know how Github works. I don't use it either. So PLEASE contact me on my email tobimocc@gmail.com

### Environment
* Elixir Version: 1.11.3
* Erlang Version: 23
* BlockScout Version: v3.7.0-beta

* User Agent: `Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.212 Safari/537.36`

### Steps to reproduce

*Tell us how to reproduce this issue. If possible, push up a branch to your fork with a regression test we can run to reproduce locally.*

### Expected Behaviour

*Tell us what should happen.*

### Actual Behaviour

*Tell us what happens instead.*

**Comment by mayuriprjpt** [comment]
Did you got any uodate from team,

**Comment by vbaranov** [comment]
There is no Matic support here. Try to ask at their fork https://github.com/maticnetwork/blockscout.
