### ISSUE TITLE
Mainnet: transaction pending for 4 days

### ISSUE THREAD

**Issue by anilgk** [blockscout/blockscout#4098]
I had swapped Matic to get Polydoge using quickswap and my metamask wallet but the transaction is pending since 4 days.
Please check Block #14611258

### Environment
* Elixir Version: 1.11.3
* Erlang Version: 23
* BlockScout Version: v3.7.0-beta

* User Agent: `Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:88.0) Gecko/20100101 Firefox/88.0`

### Steps to reproduce

*Tell us how to reproduce this issue. If possible, push up a branch to your fork with a regression test we can run to reproduce locally.*

### Expected Behaviour

Transaction should be completed.

### Actual Behaviour

Transaction is pending

**Comment by vbaranov** [comment]
There is no Matic support here. Try to ask at their fork https://github.com/maticnetwork/blockscout.
