### ISSUE TITLE
Mainnet: Can't withdraw my MATIC or ETH

### ISSUE THREAD

**Issue by zachblaustone** [blockscout/blockscout#4099]
Can't withdraw my MATIC or ETH from ape.community. 

User Agent: Chrome/90.0.4430.212 

### Expected Behaviour

I should be able to withdraw my tokens.

### Actual Behaviour

An error occurs and no token is transferred back to my wallet.

**Comment by vbaranov** [comment]
There is no Matic support here. Try to ask at their fork https://github.com/maticnetwork/blockscout.
