### ISSUE TITLE
Mainnet: <an issue with sending sum to a matic erc20 address>

### ISSUE THREAD

**Issue by Houssem-dot** [blockscout/blockscout#4101]
*I sent my Matic from Matic network on Metamask to Binance on the Erc20 network and I'm still waiting... it's been 5 days now. is that mean my Matic was gone*
transaction details 
https://explorer.matic.network//tx/0xe70c281d1302814f682f89be0686b806be4d3d5dd8ea20dc452bd454fd4161f7

### Environment
* Elixir Version: 1.11.3
* Erlang Version: 23
* BlockScout Version: v3.7.0-beta

* User Agent: `Mozilla/5.0 (Linux; Android 11; CPH2159 Build/RKQ1.200903.002; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/90.0.4430.210 Mobile Safari/537.36`

### Steps to reproduce

*Tell us how to reproduce this issue. If possible, push up a branch to your fork with a regression test we can run to reproduce locally.*

### Expected Behaviour

* receive my coin*

### Actual Behaviour

* i didn't receive my Matic.*

**Comment by vbaranov** [comment]
There is no Matic support here. Try to ask at their fork https://github.com/maticnetwork/blockscout.

**Comment by Houssem-dot** [comment]
oh okey thank you dear
