### ISSUE TITLE
Mainnet: METAMASK MAINNET TO WAZIRX TRANSFERRED METIC TOKEN NOT RECEIVED

### ISSUE THREAD

**Issue by mayuriprjpt** [blockscout/blockscout#4104]
![Screenshot_20210522-135802_MetaMask](https://user-images.githubusercontent.com/84618872/119220195-f9330380-bb06-11eb-995a-cd2f88a8575a.jpg)

Transaction Hash - 0x55479db478969d5eae31e8ebdf1e22bed2c3e3bfaaefb9e0fdbffa8ceec29029

I have transferred 58 MATIC from metamask to wazirX, its been 10days but token is not received in my wazirX wallet. Please reverse the transaction and credit metic in my metic mainnet wallet.
Please help me, i am very poon girl and I need money for medicine.

### Environment
* Elixir Version: 1.11.3
* Erlang Version: 23
* BlockScout Version: v3.7.0-beta

* User Agent: `Mozilla/5.0 (Linux; Android 10; SM-J600G Build/QP1A.190711.020; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/90.0.4430.210 Mobile Safari/537.36`

### Steps to reproduce

*Tell us how to reproduce this issue. If possible, push up a branch to your fork with a regression test we can run to reproduce locally.*

### Expected Behaviour

*Tell us what should happen.*

### Actual Behaviour

*Tell us what happens instead.*

**Comment by mayuriprjpt** [comment]
I dont know how this github is work.. please email me on abksss.ly@gmail.com or mayuriprjpt@gmail.com

**Comment by vbaranov** [comment]
There is no Matic support here. Try to ask at their fork https://github.com/maticnetwork/blockscout.
