### ISSUE TITLE
Transfer from Metamask to OKEx exchange still no available 

### ISSUE THREAD

**Issue by Rajeshap241063** [blockscout/blockscout#4106]
Transaction Details
0x44ae7dbc51a37f6e50dd76706f270c84860b67f22540be1845cc13ee87d90cf7

From 0xffAd791Ad8955e619AE722de64aB72E6cCD84954 ( Meta mask ) 
To  0x362033192118aAeC96e741c74e37432E95e492Db ( OKEx exchange) 

Block Number
14637707
Block Confirmations
165,573
Nonce
28
TX Fee
0.000021 MATIC ($0.000028 USD)
Transaction Speed
<= 2.29 seconds

USD $266.67 USD

Matic value 203.566270077359551542

Please assist to transfer back to Metamask

**Comment by Rajeshap241063** [comment]
![image](https://user-images.githubusercontent.com/84398401/119255493-c574de00-bbd9-11eb-970c-8d66179140b1.png)
![Untitled](https://user-images.githubusercontent.com/84398401/119255514-e3dad980-bbd9-11eb-8dc9-bad29f605247.png)
![Untitled](https://user-images.githubusercontent.com/84398401/119255531-fe14b780-bbd9-11eb-8b23-235d9759c8a5.png)

**Comment by Rajeshap241063** [comment]
![Untitled 1](https://user-images.githubusercontent.com/84398401/119255583-3b794500-bbda-11eb-97ad-74ec943cdfe1.png)
![Untitled 2](https://user-images.githubusercontent.com/84398401/119255608-55b32300-bbda-11eb-88ae-c776e2733cab.png)

**Comment by vbaranov** [comment]
There is no Matic support here. Try to ask at their fork https://github.com/maticnetwork/blockscout.
