### ISSUE TITLE
Mainnet: maticvigil transaction not reported

### ISSUE THREAD

**Issue by xrentech** [blockscout/blockscout#4115]
Hello, maticvigil failed to take into account one of my transaction that I did 3 days ago.
I have sent all my USDT tokens from my matic adresss A to my matic addresse B created on instadapp.io, 
and i used the matic address B to spent those USDT token on the platform.
However maticvigil doesn't report the outgoing transaction on my matic address A and I still see my usdt tokens in the token balance page. Metamask show the correct balance which is 0.

### Environment

https://explorer-mainnet.maticvigil.com/

* User Agent: `Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.212 Safari/537.36`

### Steps to reproduce

Don't know how to reproduce it

### Expected Behaviour

Matic vigil track all transaction

### Actual Behaviour

Matic vigil misses some transactions

**Comment by vbaranov** [comment]
There is no Matic support here. Try to ask at their fork https://github.com/maticnetwork/blockscout.
