### ISSUE TITLE
Mainnet: <Issue Title>metamask to coinbase

### ISSUE THREAD

**Issue by drosmjrl** [blockscout/blockscout#4119]
*Describe your issue here.*
Tried to send my token from metamask to my coinbase account but during the transaction it said "user rejected". My token was then removed from my account even though it wasn't process.

### Environment
* Elixir Version: 1.11.3
* Erlang Version: 23
* BlockScout Version: v3.7.0-beta

* User Agent: `Mozilla/5.0 (Linux; Android 11; Pixel 4a) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.210 Mobile Safari/537.36`

### Steps to reproduce

*Tell us how to reproduce this issue. If possible, push up a branch to your fork with a regression test we can run to reproduce locally.*
Not sure how other then I have lost all transactions process in my metamask wallet.

### Expected Behaviour

*Tell us what should happen.*
Been trying to solve this issue for months now with metamask and now I am here trying to find some more answer on why I can't see my time or why it disappeared. Tried sending from metamask to coinbase lost token after saying user rejected
### Actual Behaviour

*Tell us what happens instead.*
Token disappeared but I can see it on the Matic network.

**Comment by vbaranov** [comment]
There is no Matic support here. Try to ask at their fork https://github.com/maticnetwork/blockscout.
