### ISSUE TITLE
ETC Classic was sent from Coinbase through blockchain in an attempt to be sent to my ETH wallet on trust wallet

### ISSUE THREAD

**Issue by leyMarc** [blockscout/blockscout#4124]
*Describe your issue here.*

### Environment
* Elixir Version: 1.11.3
* Erlang Version: 23
* BlockScout Version: v3.5.0-beta

* User Agent: `Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.212 Safari/537.36 Edg/90.0.818.66`

### Steps to reproduce

*Tell us how to reproduce this issue. If possible, push up a branch to your fork with a regression test we can run to reproduce locally.*

### Expected Behaviour

*Tell us what should happen.*

### Actual Behaviour

*Tell us what happens instead.*

**Comment by leyMarc** [comment]
They are telling me to contact trust wallet but the funds show pending through coinbase and still pending.

**Comment by vbaranov** [comment]
Yes, please, contract Trust wallet.

**Comment by leyMarc** [comment]
I did and I completed the steps and the funds are not in the ETH Trust wallet ? I dont see it there .
