### ISSUE TITLE
Claim interest from Aave but token doesnt how up in my wallet.

### ISSUE THREAD

**Issue by ZKO8** [blockscout/blockscout#4126]
Dear team,

Please be informed that i've claim matic token from Aave, however token doesnt show up in my wallet.

Hereunder TX for your further assistance.

Token Transfer
0.088025682934341954 WMATIC

**Input
Failed to decode input data.**

Transaction Details
0x4486458d10bcdb5a568e87e29f4c195a0416e709637616e4bd3f677b458c6c44
0xfda34a–5bf46a → Initiali..xy (0x357d51–d8bc23)

### Environment
* Elixir Version: 1.11.3
* Erlang Version: 23
* BlockScout Version: v3.7.0-beta

* User Agent: `Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.212 Safari/537.36`

### Steps to reproduce

*Tell us how to reproduce this issue. If possible, push up a branch to your fork with a regression test we can run to reproduce locally.*

### Expected Behaviour

*Tell us what should happen.*

### Actual Behaviour

*Tell us what happens instead.*

**Comment by vbaranov** [comment]
There is no Matic support here. Try to ask at their fork https://github.com/maticnetwork/blockscout.
