### ISSUE TITLE
Mainnet: <Issue Title>

### ISSUE THREAD

**Issue by Hoffstruck2014** [blockscout/blockscout#4134]
*Describe your issue here.*
Trying to send MATIC from MATIC Mainnet to coinbase and have not seen it come through although the transaction says it has been confirmed. Txn Hash is 0xb30a27aac76960a56b535df487876f7d7957abf512f8bc9a60eba3fa88fea113. I can't figure out the issue as I copied the address I was sending to and it was confirmed valid after double checking. Please help! 

Thank you

### Environment
* Elixir Version: 1.11.3
* Erlang Version: 23
* BlockScout Version: v3.7.0-beta

* User Agent: `Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.212 Safari/537.36`

### Steps to reproduce

*Tell us how to reproduce this issue. If possible, push up a branch to your fork with a regression test we can run to reproduce locally.*

### Expected Behaviour

*Tell us what should happen.*

### Actual Behaviour

*Tell us what happens instead.*

**Comment by parisbs77** [comment]
My coinbase is doing the same thing....
