### ISSUE TITLE
Mainnet: sent funds but not received 

### ISSUE THREAD

**Issue by hanleduong** [blockscout/blockscout#4136]
*Describe your issue here.*
Hi, I sent some funds to an exchanged. It showed that its successful but have not received it. Tranasaction: 0x2c0516cc5d5106196dcdbd1edbf85b3e1f014e5588084598ede650cdb3de9fa3

### Environment
* Elixir Version: 1.11.3
* Erlang Version: 23
* BlockScout Version: v3.7.0-beta

* User Agent: `Mozilla/5.0 (iPhone; CPU iPhone OS 14_4_2 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Mobile/15E148`

### Steps to reproduce

*Tell us how to reproduce this issue. If possible, push up a branch to your fork with a regression test we can run to reproduce locally.*

### Expected Behaviour

*Tell us what should happen.*

### Actual Behaviour

*Tell us what happens instead.*

**Comment by vbaranov** [comment]
There is no Matic support here. Try to ask at their fork https://github.com/maticnetwork/blockscout.
