### ISSUE TITLE
POA Sokol: Contracts deployed to sokol are being treated as EOA in the block explorer

### ISSUE THREAD

**Issue by habdelra** [blockscout/blockscout#4139]
*Describe your issue here.*

### Environment
https://blockscout.com/poa/sokol/address/0xf7D6bd5e40E4836f0a5b892B0D62F2BE85AcB345

* User Agent: `Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.69 Safari/537.36`
### Steps to reproduce

Deploy an open zeppelin upgradeable contract proxy to sokol, and then visit the contract address in blockscout. For example we deployed this open zeppelin proxy contract to sokol: https://blockscout.com/poa/sokol/address/0xf7D6bd5e40E4836f0a5b892B0D62F2BE85AcB345

### Expected Behaviour

Normally what happens is that blockscout indicates that the address is a contract and that it is a proxy, and provides tabs to view the source and verify, read the proxy, write to the proxy, and write to the contract.

### Actual Behaviour

Blockscout is indicating that the address is an EOA, and none of the normal contract tabs (nor contract proxy tabs) are visible. Here is a screenshot of a proxy contract's address in sokol as viewed from blockscout: ![Screen Shot 2021-05-25 at 11 34 19 AM](https://user-images.githubusercontent.com/61075/119526186-2a047a00-bd4d-11eb-823c-f267ff6f6a1b.png)

**Comment by habdelra** [comment]
You can actually verify this is a contract by calling the function `cardProtocolVersion()` on it.

**Comment by habdelra** [comment]
It looks like the Berlin fork tripped me up. We are using our own hosted sokol node for contract deployments (because of _reasons_) and it is using Open Ethereum v3.0.0 which has a known issue with the Berlin fork. I'm guessing blockscout never saw these contracts because they were deployed on a fork.

**Comment by vbaranov** [comment]
@habdelra yes, it sounds like what you have described. can you upgrade your Open Ethereum archive node to 3.2.6 version?
