### ISSUE TITLE
Mainnet: Transferring MATIC tokens from MEW to Matic Mainnet

### ISSUE THREAD

**Issue by Jeun88** [blockscout/blockscout#4143]
*I've sent one matic token from my cold wallet through MEW (myetherwallet) to my matic mainnet. The blocks are still being made, i dont actually know what that means. But the Matic token has not shown up in my matic wallet. * I've checked the etherscan transaction and it said it was sucessful but the block confirmations keep increasing. It has been 1 day and 23 hours and there has been 12878 Block Confirmations. Somebody suggested that maybe the matic tokens were sent through a ethereum network instead. When I sent the Matic token I selected Matic token and not Ethereum. So i am not sure why it would have been sent through the ethereum network instead? 

### Environment
* Elixir Version: 1.11.3
* Erlang Version: 23
* BlockScout Version: v3.7.0-beta

* User Agent: `Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.212 Safari/537.36`

### Steps to reproduce

*Tell us how to reproduce this issue. If possible, push up a branch to your fork with a regression test we can run to reproduce locally.*

### Expected Behaviour

*Tell us what should happen.*

### Actual Behaviour

*Tell us what happens instead.*

**Comment by vbaranov** [comment]
There is no Matic support here. Try to ask at their fork https://github.com/maticnetwork/blockscout.
