### ISSUE TITLE
Mainnet: CHAIN TOKEN STUCK

### ISSUE THREAD

**Issue by mhui-po** [blockscout/blockscout#4154]
https://explorer.matic.network/tx/0x6ce27285e1e78b9e0e553325760525eefdc9c327d984b13424a59f1a1a0c4195

### Environment
* Elixir Version: 1.11.3
* Erlang Version: 23
* BlockScout Version: v3.7.0-beta

* User Agent: `Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.212 Safari/537.36 Edg/90.0.818.66`

### Steps to reproduce

*Tell us how to reproduce this issue. If possible, push up a branch to your fork with a regression test we can run to reproduce locally.*

### Expected Behaviour

*Tell us what should happen.*

### Actual Behaviour

*Tell us what happens instead.*

**Comment by vbaranov** [comment]
There is no Matic support here. Try to ask at their fork https://github.com/maticnetwork/blockscout.
