### ISSUE TITLE
Mainnet: Transactions are successful on metamask but do not show up on the mainnet explorer

### ISSUE THREAD

**Issue by punnymarty** [blockscout/blockscout#4160]
I made a few transactions on polybear.exchange and I cannot find the transactions on the maticvigil mainnet explorer.
I went to chainstacklabs explorer and there I could find the transactions but are not being decoded. Can someone please check and help

### Environment
* Elixir Version: 1.11.3
* Erlang Version: 23
* BlockScout Version: v3.7.0-beta

* User Agent: `Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.212 Safari/537.36`

### Steps to reproduce
1. Add a small lp on quickswap usdc-usdt
2. Deposit lp on polybear
3. Check the transaction on explorer and you will not find it

*Tell us how to reproduce this issue. If possible, push up a branch to your fork with a regression test we can run to reproduce locally.*

### Expected Behaviour

Transactions don't show up on mainnet explorer

### Actual Behaviour

All successful transactions should show up on mainnet explorer.

**Comment by vbaranov** [comment]
There is no Matic support here. Try to ask at their fork https://github.com/maticnetwork/blockscout.
