### ISSUE TITLE
Mainnet: <erroneous withdrawal>

### ISSUE THREAD

**Issue by sweetblossom** [blockscout/blockscout#4169]
*i accidentally copy my Binance address on matic mainnet instead of transferring it to my metamask Ethereum wallet.*

### Environment
* Elixir Version: 1.11.3
* Erlang Version: 23
* BlockScout Version: v3.7.0-beta

* User Agent: `Mozilla/5.0 (Linux; Android 10; RMX2040 Build/QP1A.190711.020; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/90.0.4430.210 Mobile Safari/537.36`

 ## Steps to reproduce

*Tell us how to reproduce this issue. If possible, push up a branch to your fork with a regression test we can run to reproduce locally.*

### Expected Behaviour

*Tell us what should happen.*
I accidentally transfer my matic directly using my matic Binance address instead of transferring it to my metamask Ethereum wallet

**Comment by vbaranov** [comment]
There is no Matic support here. Try to ask at their fork https://github.com/maticnetwork/blockscout.
