### ISSUE TITLE
Pending transactions

### ISSUE THREAD

**Issue by yvan3869** [blockscout/blockscout#4173]
Hi guys,
i'm stuck with pending transactions on matic network (too few gwei i guess), so i can't do nothing anymore. And the more i try to cancel these pending transactions, the more I accumulate new pending ones. how can i cancel all that pending queue?
A big thank you if you have an answer

### Environment

* Elixir & Erlang/OTP versions (`elixir -version`):
* Operating System:
* Blockscout Version/branch: 

### Steps to reproduce

*Tell us how to reproduce this issue.  ❤️ if you can push up a branch to your fork with a regression test we can run to reproduce locally.*

### Expected behaviour

*Tell us what should happen.*

### Actual behaviour

*Tell us what happens instead.*

**Comment by vbaranov** [comment]
There is no Matic/Polygon support here. Try to ask at their fork https://github.com/maticnetwork/blockscout.
