### ISSUE TITLE
Wallet does not show balance

### ISSUE THREAD

**Issue by imontano46** [blockscout/blockscout#4181]
I sent 81 matic to wallet address 0x2eee78750C1CA1D8FC540f26a58DCEd7e641e805. The public ledger shows the balance is in there but the wallet is not showing

### Environment
* Elixir Version: 1.11.3
* Erlang Version: 23
* BlockScout Version: v3.7.0-beta

* User Agent: `Mozilla/5.0 (Linux; Android 11; SM-G991U) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.141 Mobile Safari/537.36`

### Steps to reproduce

*Tell us how to reproduce this issue. If possible, push up a branch to your fork with a regression test we can run to reproduce locally.*

### Expected Behaviour

*Tell us what should happen.*

### Actual Behaviour

*Tell us what happens instead.*

**Comment by vbaranov** [comment]
There is no Matic support here. Try to ask at their fork https://github.com/maticnetwork/blockscout.
