### ISSUE TITLE
Mainnet: <funds sent from matic to eth network success but not reflecting in wallet.>

### ISSUE THREAD

**Issue by prithvik99** [blockscout/blockscout#4183]
*Describe your issue here.*
hi, 
i sent funds from matic network to ETH mainnet and it shows as success on matic scanner but it isnt reflecting in my wallet. 
please help me out. 
Txn hash number: 0x21b941b3215610d55b3031e7f0ae733f3378e07d1984b04f027745f955357ea1
### Environment
* Elixir Version: 1.11.3
* Erlang Version: 23
* BlockScout Version: v3.7.0-beta

* User Agent: `Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.212 Safari/537.36`

### Steps to reproduce

*Tell us how to reproduce this issue. If possible, push up a branch to your fork with a regression test we can run to reproduce locally.*

### Expected Behaviour

*Tell us what should happen.*

### Actual Behaviour

*Tell us what happens instead.*

**Comment by vbaranov** [comment]
There is no Matic support here. Try to ask at their fork https://github.com/maticnetwork/blockscout.
