### ISSUE TITLE
Transaction was successfull but Polygen not crrdited

### ISSUE THREAD

**Issue by Gurwinder1251** [blockscout/blockscout#4185]
I had transaction of 159.99 Polygen from AscendEx (matic network) to Binance (erc20) of Polygen ...but still not get polygen to binance..when will i get back? 

TXN hash is
0xe8ca1b133bf9b7f06baab622d6e10179b49f72f614830107cea24a8fa69fdcad

I also contacted with Binance Deposit  exchange
They told

This transaction cannot be found on the blockchain, please verify and resubmit.

I dont know how to recover it.

**Comment by vbaranov** [comment]
There is no Matic support here. Try to ask at their fork https://github.com/maticnetwork/blockscout.
