### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by znake1st** [blockscout/blockscout#4188]
*Describe your issue here.*

### Environment

* Elixir & Erlang/OTP versions (`elixir -version`):
* Operating System:
* Blockscout Version/branch: 

### Steps to reproduce

*Tell us how to reproduce this issue.  ❤️ if you can push up a branch to your fork with a regression test we can run to reproduce locally.*

### Expected behaviour

*Tell us what should happen.*

### Actual behaviour

*Tell us what happens instead.*
Is still not on mine account im still waiting for the coins or money when do i get my coins or money ? Waitin 3 days still noting
This is the information

1.71202696 ETC
$117.15 USD
0xa5e9ada90abae339e955f1c0c12bfdaa9230f257c6fad543cd690cf3f8998b80
0x69e6cf–57e3e7 → 0x6a67f1–7de3b0
Transaction
Success
2 days ago (May-30-2021 02:39:54 AM +2 UTC)

This is my ref code
BTC Wallet
GU4Q9ZTG

Can you help me out thanks

Greetings
Eldy Van Rooijen
Eldyvanrooijen@hotmail.com
0687862721

**Comment by znake1st** [comment]
Is still not on mine account im still waiting for the coins or money when do i get my coins or money ? Waitin 3 days still noting
This is the information

1.71202696 ETC
$117.15 USD
0xa5e9ada90abae339e955f1c0c12bfdaa9230f257c6fad543cd690cf3f8998b80
0x69e6cf–57e3e7 → 0x6a67f1–7de3b0
Transaction
Success
2 days ago (May-30-2021 02:39:54 AM +2 UTC)

This is my ref code
BTC Wallet
GU4Q9ZTG


Can you help me out thanks

Greetings
Eldy Van Rooijen
Eldyvanrooijen@hotmail.com
0687862721

**Comment by vbaranov** [comment]
Regarding your question try to reach out ETC team, for instance, on their Discord https://discord.com/invite/hQs894U.
