### ISSUE TITLE
Ethereum Classic: <etc not recived>

### ISSUE THREAD

**Issue by znake1st** [blockscout/blockscout#4190]
*Describe your issue here.*

### Environment
* Elixir Version: 1.11.3
* Erlang Version: 23
* BlockScout Version: v3.5.0-beta

* User Agent: `Mozilla/5.0 (Linux; Android 9; ASUS_I001DB) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.105 Mobile Safari/537.36 OPR/63.3.3216.58675`

### Steps to reproduce

*Tell us how to reproduce this issue. If possible, push up a branch to your fork with a regression test we can run to reproduce locally.*

### Expected Behaviour

*Tell us what should happen.*

### Actual Behaviour

*Tell us what happens instead.*

Is not on my wallet
Hier is my adress that i have send money to get etc cion
But stll nothing

Can you help me out

Greetings
Eldy Van Rooijen
Eldyvanrooijen@hotmail.com
0687862721

0xa5e9ada90abae339e955f1c0c12bfdaa9230f257c6fad543cd690cf3f8998b80

**Comment by vbaranov** [comment]
You should ask Coinbase support
