### ISSUE TITLE
Mainnet: <Cancel pending Transaction>

### ISSUE THREAD

**Issue by titanson2** [blockscout/blockscout#4194]
I have a transaction that is pending that I am unable to cancel. I have tried to used the same nonce, same/more gas, PC and mobile and all the possible combinations to get this cancelled. Any help is much appreciated 

https://explorer-mainnet.maticvigil.com/tx/0x706c0a48e4afe37f6f870a31678c3c91f4131f8b6f81d4d5d0fbead43b32415e/internal-transactions

this is my wallet
0xA4E6F96f3f0948d9940E3c3d5C2F3e625605f00b

**Comment by vbaranov** [comment]
There is no Matic support here. Try to ask at their fork https://github.com/maticnetwork/blockscout.
