### ISSUE TITLE
Mainnet: Funds not arrived

### ISSUE THREAD

**Issue by GaryHOST893** [blockscout/blockscout#4196]
I made a bridge transfer from MATIC WETH to Metamask Ethereum and the funds have not arrived yet

### Environment
* Elixir Version: 1.11.3
* Erlang Version: 23
* BlockScout Version: v3.7.0-beta

* User Agent: `Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.77 Safari/537.36`

### Steps to reproduce

*Tell us how to reproduce this issue. If possible, push up a branch to your fork with a regression test we can run to reproduce locally.*

### Expected Behaviour

The Ethereum should have been in my Ethereum Mainnet in Metamask

### Actual Behaviour

The WETH is not in my MATIC Mainnet nor is it in my Ethereum Mainnet in Metamask

**Comment by vbaranov** [comment]
There is no Matic support here. Try to ask at their fork https://github.com/maticnetwork/blockscout.
