### ISSUE TITLE
I mistakenly transfered my $300 to blockscout

### ISSUE THREAD

**Issue by chinonso1234** [blockscout/blockscout#4197]
Please I need help, I mistakenly transfered my $300 to blockscout, please how do I get my money. please help..since 2weeks now.

**Comment by vbaranov** [comment]
Blockscout is a block explorer. It is not a wallet. You cannot send money to it.

**Comment by chinonso1234** [comment]
Please how do I get my $300 back, I want to send the money to my watermine account and I mistakenly send it to ETC blockscout. Please I want the money back. Please help
