### ISSUE TITLE
Carrier prohibited

### ISSUE THREAD

**Issue by mukesh7766063808** [blockscout/blockscout#4199]
![Screenshot_2021-06-02-08-41-49-583_io.metamask.jpg](https://user-images.githubusercontent.com/82068975/120418578-6c960a00-c37e-11eb-9119-0c66f5fb5128.jpg)

I am a new user and I am trying this first time but it has desolate me .

Please try to solve this issue.

My  receipt address is

0xF701CAAa5B6f1A8f808aBDFc92eE41c14D2e5062

Please try to send first faucet withdrawal or show me the way to get your faucet withdrawal please.

Thanks for reading.

**Comment by vbaranov** [comment]
Yes, some carriers are prohibited because they were used by faucet abusers. If bridging assets, you can use bridge auto-faucet https://www.xdaichain.com/about-xdai/news-and-information/project-updates/2021-weekly-updates/xdai-weekly-recap-28-05-2021#omnibridge-autofaucet.
