### ISSUE TITLE
Ethereum Classic: Coinbase etc coin to Binance 

### ISSUE THREAD

**Issue by znake1st** [blockscout/blockscout#4200]
*Describe your issue here.*

### Environment
* Elixir Version: 1.11.3
* Erlang Version: 23
* BlockScout Version: v3.5.0-beta

* User Agent: `Mozilla/5.0 (Linux; Android 9; ASUS_I001DB) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.105 Mobile Safari/537.36 OPR/63.3.3216.58675`

### Steps to reproduce

*Tell us how to reproduce this issue. If possible, push up a branch to your fork with a regression test we can run to reproduce locally.*

### Expected Behaviour

*Tell us what should happen.*

### Actual Behaviour

*Tell us what happens instead.*
Here are my
Transaction Details
0xa5e9ada90abae339e955f1c0c12bfdaa9230f257c6fad543cd690cf3f8998b80
0x69e6cf–57e3e7 → 0x6a67f1–7de3b0
Transaction
Success
3 days ago (May-30-2021 02:39:54 AM +2 UTC)
Block Number
12837915
Block Confirmations
20,281
Nonce
35447
TX Fee
0.00042 ETC ($0.028232 USD)
Transaction Speed
<= 15.253 seconds

And i have not recive anything

Can someone help me out 

I have send from Coinbase a ETC coin to Binance

But still nothing

Pls help me

Greetings
Eldy Van Rooijen
Eldyvanrooijen@hotmail.com
0687862721

**Comment by znake1st** [comment]
Here are my
Transaction Details
0xa5e9ada90abae339e955f1c0c12bfdaa9230f257c6fad543cd690cf3f8998b80
0x69e6cf–57e3e7 → 0x6a67f1–7de3b0
Transaction
Success
3 days ago (May-30-2021 02:39:54 AM +2 UTC)
Block Number
12837915
Block Confirmations
20,281
Nonce
35447
TX Fee
0.00042 ETC ($0.028232 USD)
Transaction Speed
<= 15.253 seconds

And i have not recive anything

Can someone help me out 

I have send from Coinbase a ETC coin to Binance

But still nothing

Pls help me

Greetings
Eldy Van Rooijen
Eldyvanrooijen@hotmail.com
0687862721

**Comment by vbaranov** [comment]
You should ask this question to Coinbase support
