### ISSUE TITLE
Coinbase to binace coin sending dont work

### ISSUE THREAD

**Issue by znake1st** [blockscout/blockscout#4201]
Here are my
Transaction Details
0xa5e9ada90abae339e955f1c0c12bfdaa9230f257c6fad543cd690cf3f8998b80
0x69e6cf–57e3e7 → 0x6a67f1–7de3b0
Transaction
Success
3 days ago (May-30-2021 02:39:54 AM +2 UTC)
Block Number
12837915
Block Confirmations
20,281
Nonce
35447
TX Fee
0.00042 ETC ($0.028232 USD)
Transaction Speed
<= 15.253 seconds

And i have not recive anything

Can someone help me out 

I have send from Coinbase a ETC coin to Binance

But still nothing

Pls help me

Greetings
Eldy Van Rooijen
Eldyvanrooijen@hotmail.com
0687862721

**Comment by vbaranov** [comment]
You should ask Coinbase support
