### ISSUE TITLE
Address page tokens tab: NFTs of the same contract should be collapsed to the one row

### ISSUE THREAD

**Issue by vbaranov** [blockscout/blockscout#4203]
>After accumulating 8 of these Kudos NFTs, blockscout stopped displaying them together and now added a new asset each time I get a new one.   Is there a way this can be fixed?   It's not a huge deal, but it's just annoying.

![](https://cdn.discordapp.com/attachments/502432256011272195/849293725338304512/Screenshot_2021-06-01_102752.png)

Source: https://discord.com/channels/502416149343109121/502432256011272195/849293727775981638

**Comment by vbaranov** [comment]
> Also for a lot of ERC721 contracts, the token holders list seem to be incorrectly populated (duplicated entries) like https://blockscout.com/xdai/mainnet/tokens/0xafb1A0C81c848Ad530766aD4BE2fdddC833e1e96/token-holders

**Comment by manavgarg** [comment]
Have added more info of similar issues here: https://discord.com/channels/502416149343109121/502432256011272195/862032372369981470 and
https://discord.com/channels/502416149343109121/502432256011272195/862032785992187925.

Initial message link: https://discord.com/channels/502416149343109121/502432256011272195/861777916962799656

**Comment by vbaranov** [comment]
@manavgarg thank you. Fixed aggregation of tokens on Tokens tab of address page and partially fixed aggregation of token holders on the token page. Please let me know if it looks better. I am still looking into this issue to fully eliminate it.

**Comment by manavgarg** [comment]
Thanks, this looks much better now. The Token Holders tab for the contract page looks good.
Things still remaining:
1. Total Addresses on a contract page still seems off. It is more than the token supply and perhaps needs to be refreshed.
2. https://blockscout.com/xdai/mainnet/tokens Same thing here. The Holders Count > Total Supply. I believe fixing 1 should. fix too.
2. On the EOA page, all the tokens belonging to the same contract are still not aggregated. They are listed as different rows and sometimes miss data too.

Thank you so much for your help and contribution here and prompt fix :)

**Comment by vbaranov** [comment]
>On the EOA page, all the tokens belonging to the same contract are still not aggregated. They are listed as different rows and sometimes miss data too.

You mean in tokens dropdown, right?

**Comment by manavgarg** [comment]
Correct, in the tokens dropdown.

**Comment by vbaranov** [comment]
New features to the frontend are now considered in the new [frontend app](https://github.com/blockscout/frontend).
