### ISSUE TITLE
SOLAR-WMATIC LP liquidity remotion problem

### ISSUE THREAD

**Issue by Carlo993** [blockscout/blockscout#4209]
*Describe your issue here.*
Hi, I created a LP for blackswap on quickswap platform. A SOLAR-WMATIC LP. I put 26.186 WMATIC and 125.316 SOLAR in order to create 41.863 SOLAR-WMATIC LP (UNI-V2). I can see in the transaction details on mainnet the transactions among my Metamask and the platform. 

After 2-3 minutes I removed this liquidity, splitting the SOLAR-WMATIC LP on quickswap and I just received 94.540 SOLAR. I checked the transaction details on the mainnet and, a part from this 94.54 solar, there are no transaction towards my metamask address.

How can I ask to check these transactions? 

Thank you

### Environment
* Elixir Version: 1.11.3
* Erlang Version: 23
* BlockScout Version: v3.7.0-beta

* User Agent: `Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.212 Safari/537.36`

### Steps to reproduce

*Tell us how to reproduce this issue. If possible, push up a branch to your fork with a regression test we can run to reproduce locally.*

### Expected Behaviour

*Tell us what should happen.*

### Actual Behaviour

*Tell us what happens instead.*

**Comment by vbaranov** [comment]
There is no Matic support here. Try to ask at their fork https://github.com/maticnetwork/blockscout.
