### ISSUE TITLE
Mainnet: Problem with payment 

### ISSUE THREAD

**Issue by madah12345** [blockscout/blockscout#4210]
Hello,
I have a problem with payment from ethermine org.... I made it with Matic (daily payment). I have metamask wallet and nothing came... ETH was sent from pool yesterday but nothing came 🙏
Thank you for fasf reply
Adam Hoferka 

0xf418743f250a9b3e14e27971c3cbebd5f7d5aaff83809723369b0750277220f4

### Environment
* Elixir Version: 1.11.3
* Erlang Version: 23
* BlockScout Version: v3.7.0-beta

* User Agent: `Mozilla/5.0 (Linux; Android 11; SM-G975F) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.210 Mobile Safari/537.36`

### Steps to reproduce

*Tell us how to reproduce this issue. If possible, push up a branch to your fork with a regression test we can run to reproduce locally.*

### Expected Behaviour

*Tell us what should happen.*

### Actual Behaviour

*Tell us what happens instead.*

**Comment by vbaranov** [comment]
There is no Matic support here. Try to ask at their fork https://github.com/maticnetwork/blockscout.
