### ISSUE TITLE
Mainnet: Existent transaction not showing on Maticvigil explorer

### ISSUE THREAD

**Issue by domenicows** [blockscout/blockscout#4213]
I made a tx which I can see on the blockchain but it doesn't exist on Maticvigil.

### Environment
* Elixir Version: 1.11.3
* Erlang Version: 23
* BlockScout Version: v3.7.0-beta

* User Agent: `Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.93 Safari/537.36`

### Steps to reproduce

This transaction is shown as non existent: 0x254c5cfae21f5ce1744315e77e0aba07904ab5277d12f35f5ac5574ca836cca3

### Expected Behaviour

The transaction should exist

### Actual Behaviour

Maticvigil shows a 404 for the transaction

**Comment by domenicows** [comment]
The transaction shows correctly on Tenderly: https://dashboard.tenderly.co/tx/polygon/0x254c5cfae21f5ce1744315e77e0aba07904ab5277d12f35f5ac5574ca836cca3

**Comment by vbaranov** [comment]
There is no Matic/Polygon support here. Try to ask at their fork https://github.com/maticnetwork/blockscout.
