### ISSUE TITLE
Mainnet: my polygon disappeared 

### ISSUE THREAD

**Issue by BuffaloSanto** [blockscout/blockscout#4214]
Please someone help me please!!! 
I sent my polygon (from matic main net wallet) to the Celsius wallet at 2 am this morning. Both addresses are correct. When I go to look at the transaction it tells me no hash can be discovered. Please someone help me 🙏🏽
thank you,
Patrick

### Environment
* Elixir Version: 1.11.3
* Erlang Version: 23
* BlockScout Version: v3.7.0-beta

* User Agent: `Mozilla/5.0 (iPhone; CPU iPhone OS 13_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) CriOS/76.0.3809.123 Mobile/15E148 Safari/605.1`

### Steps to reproduce

*Tell us how to reproduce this issue. If possible, push up a branch to your fork with a regression test we can run to reproduce locally.*

### Expected Behaviour

*Tell us what should happen.*

### Actual Behaviour

*Tell us what happens instead.*

**Comment by BuffaloSanto** [comment]
My email is patrick_santo-donato@hotmail.com and my cell is 7328647311 please help please

**Comment by vbaranov** [comment]
There is no Matic support here. Try to ask at their fork https://github.com/maticnetwork/blockscout.
