### ISSUE TITLE
Data load issues with address_token_balances & address_current_token_balances tables

### ISSUE THREAD

**Issue by zalam003** [blockscout/blockscout#4217]
### Description
We are in the process of upgrading from v3.1.x to v3.7.0.  

We have tested upgrading the schema and migrating the data.  This did not work as expected.  So we are doing a full load of the blockchain data.  During the initial load, we are noticing two columns (`value` and `value_fetched_at`) from `address_token_balances` are not loading.  As such there is no data in `address_token_balances`. 

Here is sample data:
```
   id   |                address_hash                | block_number |        token_contract_address_hash         | value | value_fetched_at |        inserted_at         |         updated_at
--------+--------------------------------------------+--------------+--------------------------------------------+-------+------------------+----------------------------+----------------------------
 100351 | \xb38bd421847a74b8b474f686de9b74756d24a078 |       645063 | \xb2ef65460bf71a05d59fdf5e8f114a32d445d164 |       |                  | 2021-06-02 13:40:35.854658 | 2021-06-02 13:40:35.854658
 100350 | \x2e487219a5e181ffaf3c770b107b7f66d384c37e |       645063 | \xb2ef65460bf71a05d59fdf5e8f114a32d445d164 |       |                  | 2021-06-02 13:40:35.854658 | 2021-06-02 13:40:35.854658
```

Per @vbaranov request, we used the latest code from 02-Jun-2021 without any customization.  It yielded the same results (no data in `value` and `value_fetched_at` columns:
```
id | address_hash | block_number | token_contract_address_hash | value | value_fetched_at | inserted_at | updated_at
------+--------------------------------------------+--------------+--------------------------------------------+-------+------------------+----------------------------+----------------------------
3259 | \x19fe4ef1a970d62c87644f9e9b0d4cb931a6f413 | 641571 | \x0000000000000000000000000000000000000319 | | | 2021-06-02 18:18:24.634554 | 2021-06-02 18:18:24.634554
3258 | \xe1faaa1523d18f7544fb9297dd7f4a6b8c0c4c0d | 641391 | \xefe5de5f5179ff7d1e16423b429571c9549571f1 | | | 2021-06-02 18:18:24.690523 | 2021-06-02 18:18:24.690523
3257 | \x44323dbdc4fb40c11b43da59fb487f94f3ee6aaa | 641391 | \xefe5de5f5179ff7d1e16423b429571c9549571f1 | | | 2021-06-02 18:18:24.690523 | 2021-06-02 18:18:24.690523
3256 | \xe1faaa1523d18f7544fb9297dd7f4a6b8c0c4c0d | 641391 | \xa55f26319462355474a9f2c8790860776a329aa4 | | | 2021-06-02 18:18:24.690523 | 2021-06-02 18:18:24.690523
```

### Environment

* Elixir & Erlang/OTP versions (`elixir --version`):
```
Erlang/OTP 23 [erts-11.2] [source] [64-bit] [smp:4:4] [ds:4:4:10] [async-threads:1] [hipe]

Elixir 1.11.4 (compiled with Erlang/OTP 21)
```
* Operating System: `Ubuntu 18.04 LTS`
* Blockscout Version/branch: `3.7.0-beta (latest from 02-Jun-2021)`

### Steps to reproduce

Drop and recreate database.  Set up and run blockscout

### Expected behaviour

All data should be loaded into the database.

### Actual behaviour

Missing data noted in the description

**Comment by vbaranov** [comment]
@zalam003 most likely you have an issue with customizations. I've run Blockscout from the master branch and see filled `address_current_token_balances` table after several seconds of launch:
```
sokol_test=# select * from address_current_token_balances limit 10;
 id |                address_hash                | block_number |        token_contract_address_hash         |        value        |      value_fetched_at      |        inserted_at        |        updated_at         | old_value
----+--------------------------------------------+--------------+--------------------------------------------+---------------------+----------------------------+---------------------------+---------------------------+-----------
  1 | \x0fa51951f1009c2ac8cf76ec34e0bfc3468a7fdc |     21176263 | \xbe9540796b17f9453613a603307461189ef8c65d | 1014977558952335760 | 2021-06-03 17:05:11.99817  | 2021-06-03 17:05:11.99877 | 2021-06-03 17:05:11.99877 |
  2 | \xe0237d88a660d5c61695be8e050d80ff19a28437 |     21176263 | \xbe9540796b17f9453613a603307461189ef8c65d |       5004441005440 | 2021-06-03 17:05:11.998189 | 2021-06-03 17:05:11.99877 | 2021-06-03 17:05:11.99877 |
(2 rows)
```

**Comment by zalam003** [comment]
@vbaranov Yesterday I ran the master branch code without customization.  It still did not load the 2 columns.  I am investigating to see if there is any difference between our Code Node implementation of the Ethereum code base.

Can you point me to which part of the Blockscout code base fetches data from the blockchain and parses it before committing to the database?  I looked at the SQL code to insert / update the database, it looked fine.  I want to look at the code that calls this SQL script.

**Comment by zalam003** [comment]
@vbaranov I found the code to fetch and load the code.  I am guessing for some reason it is not getting the [value](https://github.com/blockscout/blockscout/blob/800923401331fa8601339eaaafaaae662404a79f/apps/indexer/lib/indexer/token_balances.ex#L63) and executing the [line after it](https://github.com/blockscout/blockscout/blob/800923401331fa8601339eaaafaaae662404a79f/apps/indexer/lib/indexer/token_balances.ex#L67).

I will turn on debugging to get bit more details.

**Comment by zalam003** [comment]
@vbaranov I turned on debug in `apps/ethereum_jsonrpc/config/prod.exs`.  It does not give much detail. Is there another place I should change to details?

**Comment by zalam003** [comment]
@vbaranov I think we have found the issue.  For now, will close this ticket.

**Comment by zalam003** [comment]
Hi @vbaranov ,

I think I have narrowed down why `value` is not being loaded. When we run `debug_traceTransaction`, it is returning:
```
  {
    "type": "call",
    "callType": "call",
    "from": "0x49b1ec9eded235c773b0364d4d00254adcb150f5",
    "to": "0xca9f8e2875a5e1c81c4ba18d74958ef2460b6e0d",
    "input": "0x",
    "output": "0x",
    "traceAddress": [],
    "value": "0x2b5e3af16b18800000",
    "gas": "0x10d88",
    "gasUsed": "0x0"
  }
```

The `value`, `gas` and `gasUsed` are in double quotes.  Do you get the same from Ethereum or xDai?

If I remove the double quotes and run it in Elixir, I get integer amounts returned like below:
```
%{
  callType: "call",
  from: "0x49b1ec9eded235c773b0364d4d00254adcb150f5",
  gas: 69000,
  gasUsed: 0,
  input: "0x",
  output: "0x",
  to: "0xca9f8e2875a5e1c81c4ba18d74958ef2460b6e0d",
  traceAddress: [],
  type: "call",
  value: 800000000000000000000
}
```

Do you know how I can remove the double quotes before passing to Elixir?

**Comment by zalam003** [comment]
Upon further investigate, I see string for `gas`, `gasUsed` and `value` are converted to integer.  Bit puzzled why it is not parsing and committing the data into DB correctly.
