### ISSUE TITLE
Bridged tokens are not shown [Tokens Tab/bridged_tokens table)

### ISSUE THREAD

**Issue by KaamilW** [blockscout/blockscout#4220]
Dear Team,

I am having a hard time to make Bridge tokens list work.

1. Documentation seems to be outdated -> https://docs.blockscout.com/for-developers/information-and-settings/env-variables -> I have found out in the blockscout github repo that newest version doesnt have OMNI_BRIDGE_MEDIATOR nor TOKEN_BRIDGE_CONTRACT but rather BSC_OMNI_BRIDGE_MEDIATOR and ETH_OMNI_BRIDGE_MEDIATOR. Is that correct?
2. I have a hard time to know what exact address should I put to ETH_OMNI_BRIDGE_MEDIATOR/BSC_OMNI_BRIDGE_MEDIATOR -> is it bridge home/foreign? bridge mediator home/foreign?
3. I have a hard time to know what exactly addresses and how should I put addresses to AMB_BRIDGE_MEDIATORS ? Same as above -  bridge home/foreign? bridge mediator home/foreign? 
What should be the structure for that variable value ? 
xxx,xxx,xxx ?
[xxx,xxx,xxx]
'["xxxx","xxxx","xxxx"]'

4. Is FOREIGN_JSON_RPC needed for that to work properly?

Due to all of that what I am seeing is very inconsistant. I have already figured out that tokens tab is just refering to DB table with bridged tokens. However I am not sure how should I configure above options to make it work. 

I managed to somehow "turn on" ETH bridged and BSC bridged tokens support and they were ingested to the table, however only partially and only temporarily. For the sake of test I removed some of them from the table and they were never ingested back again. 

I have tried to "brute force" different configurations however without any luck.

Looking for some guidance and help from your side. Would you please advise?

### Environment

* Blockscout 3.7.0
* https://explorer.energyweb.org/

### Steps to reproduce

Setting up:

AMB_BRIDGE_MEDIATORS=xxx,xxx
BSC_OMNI_BRIDGE_MEDIATOR=xxx
ETH_OMNI_BRIDGE_MEDIATOR=xxx

### Expected behaviour

Tokens tab active with drop down list on blockscout explorer gui and:
-> Tokens option shows "Bridged?" column with ticks next to eth and binance bridged tokens
-> Bridged from ethereum tab shows list of ETH bridged tokens
-> Bridged from BSC tab shows list of BSC bridged tokens

### Actual behaviour

Tokens are not shown/partially shown.

**Comment by vbaranov** [comment]
> Documentation seems to be outdated

Yes, thank you, docs are updated https://docs.blockscout.com/for-developers/information-and-settings/env-variables https://docs.blockscout.com/for-developers/information-and-settings/deprecated-env-variables. `TOKEN_BRIDGE_CONTRACT` is still valid env var though.

> I have a hard time to know what exact address should I put to ETH_OMNI_BRIDGE_MEDIATOR/BSC_OMNI_BRIDGE_MEDIATOR -> is it bridge home/foreign? bridge mediator home/foreign?

These are addresses for home bridge mediators


>I have a hard time to know what exactly addresses and how should I put addresses to AMB_BRIDGE_MEDIATORS ? Same as above - bridge home/foreign? bridge mediator home/foreign?

As per documentation `A comma-separated list`. xxx,xxx,xxx is correct 


>Is FOREIGN_JSON_RPC needed for that to work properly?

No, it is not required. It is used to get custom tokens metadata for specific types of tokens like LP tokens

**Comment by KaamilW** [comment]
@vbaranov any updates?

**Comment by vbaranov** [comment]
>For the AMB_BRIDGE_MEDIATORS - should it be home/foreign or both?

home

>Could there be used both mediators for bsc and eth ?

No, it can be used only for a single chain.

**Comment by KaamilW** [comment]
Hey @vbaranov  - thanks for the answer, thats clear now :)!

What about my second question? I have it set up correctly now but the behaviour is as described in previous posts. Not all of the tokens are being indexed and thus I can see only a few (you can take a look -> https://explorer.energyweb.org/ in "tokens" tabs)

Would you please advise ?

**Comment by KaamilW** [comment]
@vbaranov any idea?

**Comment by vbaranov** [comment]
Bridged tokens removed from the core codebase.
