### ISSUE TITLE
Mainnet: Send USDC from Matic to Binance wallet

### ISSUE THREAD

**Issue by KetoMonster** [blockscout/blockscout#4222]
*Describe your issue here.* I Sent USDC from Metamusk Matic network to Binance ERC20 wallet address. Bainance do not support Matic mainnet and they cannot help me. 

TXID : 0x459f95750f8db9373c641930443c9a35a26f0db54964a47eeb74ca46cfed80a2

It is possible to received this USDC back??

### Environment
* Elixir Version: 1.11.3
* Erlang Version: 23
* BlockScout Version: v3.7.0-beta

* User Agent: `Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.212 Safari/537.36`

### Steps to reproduce

*Tell us how to reproduce this issue. If possible, push up a branch to your fork with a regression test we can run to reproduce locally.* 

### Expected Behaviour

*Tell us what should happen.*

### Actual Behaviour

*Tell us what happens instead.*

**Comment by vbaranov** [comment]
There is no Matic support here. Try to ask at their fork https://github.com/maticnetwork/blockscout.
