### ISSUE TITLE
Add Tags to Transactions

### ISSUE THREAD

**Issue by LucaSilverhand** [blockscout/blockscout#4226]
Add "Levinswap" tag on transactions that are dealing with Levinswap.

Factory: https://blockscout.com/poa/xdai/address/0x965769C9CeA8A7667246058504dcdcDb1E2975A5/transactions
Router: https://blockscout.com/poa/xdai/address/0xb18d4f69627F8320619A696202Ad2C430CeF7C53/transactions

Add "Levinswap Farm" tag on transactions that are dealing with MasterLevin.

Contract: https://blockscout.com/xdai/mainnet/address/0x0f2B0e9DB46C6b538e9276D2cF0C6CE8d515Eca1/transactions

Add "Levinswap Stake" tag on transactions that are dealing with LevinBar.

Contract: https://blockscout.com/xdai/mainnet/address/0xafa57Fb9d8D63Ff8124E17c1495C73bc3a7678D0/transactions

**Comment by vbaranov** [comment]
Tags have been added to xDai Blockscout instance
