### ISSUE TITLE
Mainnet: <Issue Title>lost token 

### ISSUE THREAD

**Issue by drosmjrl** [blockscout/blockscout#4234]
*Describe your issue here.* Tried sending Matic token. From metamask to coinbase. Said "user rejected" when trying to send. Lost my token after the msg. Said it was successful but I am not seeing it in any account.

### Environment
* Elixir Version: 1.11.3
* Erlang Version: 23
* BlockScout Version: v3.7.0-beta

* User Agent: `Mozilla/5.0 (Linux; Android 11; Pixel 4a) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.210 Mobile Safari/537.36`

### Steps to reproduce

*Tell us how to reproduce this issue. If possible, push up a branch to your fork with a regression test we can run to reproduce locally.*
I'm not even sure how to reproduce the transaction as it was just a send and receive transaction.
### Expected Behaviour

*Tell us what should happen.*

### Actual Behaviour

*Tell us what happens instead.*
Was not received in coinbase. Says it was successful but nothing.

**Comment by vbaranov** [comment]
There is no Matic/Polygon support here. Try to ask at their fork https://github.com/maticnetwork/blockscout.
