### ISSUE TITLE
Mainnet: <Issue Title>My matic crypto transfer from ethermine pool to my metamask wallet never finalized

### ISSUE THREAD

**Issue by Hobbes65** [blockscout/blockscout#4238]
Hi There,
these transfers from ethermine pool to my wallet are stuck, never received:
TX hash: 0xf39dac2d09afa42c54b454999ded2240d15eab033f66d2721d16e81738811c75

and 

TX hash: 0xa72bffefeaf088e2b42a76d083a2fa6655a572c8475ca7ad2b38184b89e23813

my wallet address; 0x06F378276a0eEf1Db776Da02DeB0630d456f4954

Thank you in advance

**Comment by vbaranov** [comment]
There is no Matic/Polygon support here. Try to ask at their fork https://github.com/maticnetwork/blockscout.

**Comment by Hobbes65** [comment]
Thanks

> There is no Matic/Polygon support here. Try to ask at their fork https://github.com/maticnetwork/blockscout.
