### ISSUE TITLE
Contributor filters information by address in the Token details page

### ISSUE THREAD

**Issue by gfreh** [blockscout/blockscout#425]
This issue includes a way for the user to filter information by address in the Token details page (as developed by #51).

![screen shot 2018-07-16 at 18 59 10](https://user-images.githubusercontent.com/2921671/42785873-6539ddc2-892a-11e8-9125-6657e6d6b0ea.png)

https://projects.invisionapp.com/share/8EMX9IOR2V9#/screens/308372327

## Acceptance Criteria

<details>
<summary><b>Filtering the Token Transfer List</b></summary>
<br>

- The filter field should be shown above the `Token Transfers` list.
- The user can filter:
    - By `Address` or `Tx Hash` for `ERC-20 Tokens`.
    - By `Address`, `Tx Hash` or `TokenID` for `ERC-721 Tokens`.
- The placeholder in the filter field should be:
    - `Filter transactions by Address/Tx Hash` for `ERC-20 Tokens`.
    - `Filter transactions by Address/Tx Hash/TokenID` for `ERC-721 Tokens`.
- It's only possible to have one filter at a time:
    - `Tx Hash`
        - Possible *for both* `ERC-20` and `ERC-721`.
        - When the user applies the filter, the list should only show the `Token Transfers` that took place in that specific `Transaction`.
    - `Address`
        - Possible *for both* `ERC-20` and `ERC-721`.
        - When the user applies the filter, the list should only show the `Token Transfers` that have a `from` or `to` fields with that `Address`.
    - `TokenID`
        - Possible *only* for `ERC-721`.
        - When the user applies the filter, the list should only show the `Token Transfers` in which the `Token` with that specific `TokenID` was transferred.
- When a filter is applied, the filter field should be replaced by the filtered value, with an `x` next to it so the user can clear the filter.
- When a filter is applied, the `Holders` tab (*not yet developed*) shouldn't be visible.
- When a filter is cleared, the list should be updated and show all transfer entries again.
- It should be possible to load the page with a pre-filled filter (possibly via `query string`.
</details>

<details>
<summary><b>Updating the Top Area</b></summary>
<br>

- It's only possible to have one filter at a time:
    - `Tx Hash`
        - Possible *for both* `ERC-20` and `ERC-721`.
        - When the user applies the filter:
            - It should be possible to see that a `Tx Hash` filter is applied (on Etherscan, there is a label above the top area `Filtered By TxHash`).
            - The `Holders`, `Total Supply` and `Transfers` info is removed 
            - The `Tx Hash` is added.
    - `Address`
        - Possible *for both* `ERC-20` and `ERC-721`.
        - When the user applies the filter:
            - It should be possible to see that an `Address` filter is applied (on Etherscan, there is a label above the top area `Filtered By Token Holder`).
            - The `Holders` and `Total Supply` info is removed.
            - The `Holder Address`, `Balance` and `Percentage of the Total Supply` is added.
            - There is also a `Value` field, which is the `Balance` converted to USD and ETH, but we are not able to develop it yet.
    - `TokenID`
        - Possible *only* for `ERC-721`.
        - When the user applies the filter:
            - It should be possible to see that an `Address` filter is applied (on Etherscan, there is a label above the top area `Filtered By TokenID`).
            - The `Holders` info is removed.
</details>

### Questions
- How should the user filter information in the page? There is no field for that in the mockups.
- When a `Tx Hash` filter is applied, the `Transfers` count is removed from the page. Doesn't it make sense to keep this last one?

### Out of Scope
- The `Inventory Tab` is not yet developed, but it should be filtered too.
- Conversions for USD or any other currency (including POA and ETH).

**Comment by acravenho** [comment]
- When a user types an address into the search bar the list should only show the token transfers that have a `to` or `from` with that address.
- The filtered address should appear to the left of the search box with an `x` for a user to remove the filter.

**Comment by katibest** [comment]
I didn't completely answer your search bar question! Since we're no longer using the filter like etherscan I think we would be ok to keep it in the panel. It just a normal ol' filter which not all sections should need.

**Comment by gfreh** [comment]
@katibest no problem! I believe you folks have already told us about this UX improvement before, but I'm afraid we've misremembered that 😔

**Comment by gfreh** [comment]
I've updated the acceptance criteria to accommodate that changes we've talked about this issue. Since it's not a priority right now, I'll move it to the `To Do` column.
