### ISSUE TITLE
Help Needed with Stuck Transaction 

### ISSUE THREAD

**Issue by danuchida** [blockscout/blockscout#4266]
Recently, I went into a yield farm which rug pulled their participants. When I tried to harvest my rewards, it created a pending transaction which I couldn’t cancel or speed up. I think this might be due to their contracts being edited

Ever since then, I;ve been getting the error message:
Transaction Failed! Error: ethjs-query.

I haven’t been able to use Polygon at all
Any help would be greatly appreciated!

**Comment by vbaranov** [comment]
There is no Matic/Polygon support here. Try to ask at their fork https://github.com/maticnetwork/blockscout.
