### ISSUE TITLE
Mainnet: i sent usdt to kucoin from matic main net 

### ISSUE THREAD

**Issue by billfinitive** [blockscout/blockscout#4270]
it has not shown up yet and just want to know what my options are

txn hash here:     0xbc466d19bcac63f57d752bea92d76f4b15fd37371d88159ac47f19f9932584ad

txn input here:    0xa9059cbb00000000000000000000000069b589514b93819b41a936ee0ce981753330f4d30000000000000000000000000000000000000000000000000000000005c50d00

### Environment

* Elixir Version: 1.11.3
* Erlang Version: 23
* BlockScout Version: v3.7.0-beta

* User Agent: `Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.77 Safari/537.36`

### Steps to reproduce

*Tell us how to reproduce this issue. If possible, push up a branch to your fork with a regression test we can run to reproduce locally.*

### Expected Behaviour

*Tell us what should happen.*

### Actual Behaviour

*Tell us what happens instead.*

**Comment by vbaranov** [comment]
There is no Matic/Polygon support here. Try to ask at their fork https://github.com/maticnetwork/blockscout.
