### ISSUE TITLE
Update Nodejs libraries in block_scout_web/assets

### ISSUE THREAD

**Issue by msbachler** [blockscout/blockscout#4271]
I recenlty upgraded all our Blockscout instances to the latest release 3.7.0. 
But I noticed that the block_scout_web/assets nodejs pacakge had a high number of vunerabilites. 

_found 5721 vulnerabilities (1 low, 160 moderate, 5560 high) in 1723 scanned packages_

I ran npm audit fix but there are still a lot that it could not fix.

_fixed 5112 of 5721 vulnerabilities in 1723 scanned packages
  568 vulnerabilities required manual review and could not be updated
  2 package updates for 41 vulnerabilities involved breaking changes_

Will you be addressing these issues in the next release at all?

**Comment by vbaranov** [comment]
Yes, we already fixed most of them in the master branch. It will be included in the next release.

**Comment by msbachler** [comment]
Brilliant. Great news :-)

**Comment by vbaranov** [comment]
> added 1590 packages, and audited 1593 packages in 32s
>
> 116 packages are looking for funding
  run `npm fund` for details
> 
> 1 low severity vulnerability

Merged to master https://github.com/blockscout/blockscout/pull/4661. I suppose we can close this.
