### ISSUE TITLE
send matic to my wazirix send usdt to my binance but not recived yet

### ISSUE THREAD

**Issue by subha7595** [blockscout/blockscout#4272]
*Describe your issue here.*

### Environment
* Elixir Version: 1.11.3
* Erlang Version: 23
* BlockScout Version: v3.7.0-beta

* User Agent: `Mozilla/5.0 (Linux; Android 9; RMX1801 Build/PKQ1.181121.001; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/78.0.3904.96 Mobile Safari/537.36`

### Steps to reproduce

*Tell us how to reproduce this issue. If possible, push up a branch to your fork with a regression test we can run to reproduce locally.*

### Expected Behaviour

*Tell us what should happen.*

### Actual Behaviour

*Tell us what happens instead.*

**Comment by vbaranov** [comment]
There is no Matic/Polygon support here. Try to ask at their fork https://github.com/maticnetwork/blockscout.
