### ISSUE TITLE
Adjust graph on the main page

### ISSUE THREAD

**Issue by ulyanas** [blockscout/blockscout#4273]
The graph on the main page https://blockscout.com/xdai/mainnet/ is a bit confusing. 
- Not clear which axis represents TLV and which - tx/day 
- xDai graph was not informative as it always equals to 1 USD

Solution:
- Remove TVL axis and graph, leave just Transactions per day 
- Convert TVL to mln with 2 digits after dot and remove "USD", leave "$" only
- Rename Tx/day into "Transactions per day"
- Add title to the scheme "Daily transactions (14 days)" as in the attached example
- xDai block - remove "USD", replace with "$" for consistency

<img width="582" alt="Screenshot at Jun 11 13-05-53" src="https://user-images.githubusercontent.com/6618204/121670140-c94ba000-cab5-11eb-980b-41dea925fc28.png">

<img width="1054" alt="Screen Shot 2021-06-11 at 9 06 51 AM" src="https://user-images.githubusercontent.com/6618204/121669975-a0c3a600-cab5-11eb-8250-2d888ef0d628.png">

**Comment by vbaranov** [comment]
Changes deployed to xDai instance

<img width="595" alt="Screenshot 2021-06-17 at 15 27 29" src="https://user-images.githubusercontent.com/4341812/122396567-c7d01b00-cf80-11eb-8ac0-fded19a956b4.png">
