### ISSUE TITLE
URL redirection on xdai/mainnet instance when accessing internal menus

### ISSUE THREAD

**Issue by andogro** [blockscout/blockscout#4286]
When accessing internal menu items (for example Token Transfers or Internal Transactions for an EOA, or Read Contract for a Smart contract) url forwards to /poa/xdai/ rather than staying on xdai/mainnet url.

### Environment

Public xDai blockscout instance

### Steps to reproduce

Go to an EOA or contract and press an internal menu item

### Expected behaviour

should remain in same domain

### Actual behaviour

domain changes

**Comment by vbaranov** [comment]
@andogro thank you, reproduced and fixed. The issue caused by misconfiguration in reverse proxy.
