### ISSUE TITLE
(MatchError) no match of right hand side value: {:error, :econnrefused}

### ISSUE THREAD

**Issue by sami3232** [blockscout/blockscout#4298]
*Describe your issue here.*

### Environment

* Elixir & Erlang/OTP versions (`elixir -version`):

Erlang/OTP 23 [erts-11.2] [source] [64-bit] [smp:2:2] [ds:2:2:10] [async-threads:1] [hipe]
Elixir 1.11.1 (compiled with Erlang/OTP 23)

* Operating System: Ubuntu 20.04 LTS
* Blockscout Version/branch: https://github.com/poanetwork/blockscout; I'm on branch "master"
* Libtool: 2.4.6-14
* Libgmp3-dev: 2:6.2.0+dfsg-4
* Inotify-tools: 3.14-8
* Rustc: 1.52.1
* Postgres : 11
* Psql : psql (PostgreSQL) 11.12 (Ubuntu 11.12-1.pgdg20.04+1)

### Steps to reproduce

I did all install like this :
```
sudo apt-get update
wget https://packages.erlang-solutions.com/erlang-solutions_2.0_all.deb
sudo dpkg -i erlang-solutions_2.0_all.deb
sudo apt-get update
sudo apt-get install -y esl-erlang=1:23*

sudo apt-get update
sudo apt-get install -y elixir
sudo apt-get update
sudo apt-get install -y elixir

sudo apt update
sudo apt install -y postgresql postgresql-contrib

sudo apt-get install -y npm

sudo apt-get install -y automake

# curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh
curl https://sh.rustup.rs -sSf | sh -s -- -y


cd blockscout

mix do deps.get, local.rebar --force, deps.compile, compile -y;

mix phx.gen.secret

export SECRET_KEY_BASE=<generatedAboveSecret/PasteHere>
export ETHEREUM_JSONRPC_HTTP_URL=http://localhost:8545
export SUBNETWORK=Mainnet
export NETWORK=Ethereum
export DATABASE_URL=postgresql://dbnom:dbmdp@localhost:5432/blockscout

mix do ecto.create, ecto.migrate
cd apps/block_scout_web/assets; npm install && node_modules/webpack/bin/webpack.js --mode production; cd -
cd apps/explorer && npm install; cd -
mix phx.digest
```

To be honest, I'm not sure the last command `mix phx.digest` worked cause I had this message in the console:
```
==> ethereum_jsonrpc
The input path "priv/static" does not exist
==> explorer
The input path "priv/static" does not exist
==> indexer
The input path "priv/static" does not exist
==> block_scout_web
Check your digested files at "priv/static"

```

When I tried to launch the Phoenix Server with `mix phx.server`, the command failed.

### Expected behaviour

Don't even know what it supposed to do but if it could just print less error it would be great.

### Actual behaviour

When I run the command : `mix phx.server`, this error appears:

```
fetcher=block_catchup [error] Task #PID<0.735.0> starte>
** (MatchError) no match of right hand side value: {:error, :econnrefused}
    (indexer 0.1.0) lib/indexer/block/catchup/fetcher.ex:76: Indexer.Block.Catc>
    (elixir 1.11.1) lib/task/supervised.ex:90: Task.Supervised.invoke_mfa/2
    (elixir 1.11.1) lib/task/supervised.ex:35: Task.Supervised.reply/5
    (stdlib 3.14.1) proc_lib.erl:226: :proc_lib.init_p_do_apply/3
Function: &Indexer.Block.Catchup.Fetcher.task/1
    Args: [%Indexer.Block.Catchup.Fetcher{block_fetcher: %Indexer.Block.Fetcher>
2021-06-16T14:49:30.160 application=indexer fetcher=block_catchup [error] Catch>
2021-06-16T14:49:30.172 fetcher=block_catchup [error] Task #PID<0.831.0> starte>
** (MatchError) no match of right hand side value: {:error, :econnrefused}
    (indexer 0.1.0) lib/indexer/block/catchup/fetcher.ex:76: Indexer.Block.Catc>
    (elixir 1.11.1) lib/task/supervised.ex:90: Task.Supervised.invoke_mfa/2
    (elixir 1.11.1) lib/task/supervised.ex:35: Task.Supervised.reply/5
    (stdlib 3.14.1) proc_lib.erl:226: :proc_lib.init_p_do_apply/3
Function: &Indexer.Block.Catchup.Fetcher.task/1
    Args: [%Indexer.Block.Catchup.Fetcher{block_fetcher: %Indexer.Block.Fetcher>
2021-06-16T14:49:30.180 application=indexer fetcher=block_catchup [error] Catch>
```

If you have any idea to fix this error I'll be glad to read it.

**Comment by vbaranov** [comment]
It is required also to set `ETHEREUM_JSONRPC_HTTP_URL`, `ETHEREUM_JSONRPC_VARIANT`

Ethereum Client should be running in archive mode

References:
https://docs.blockscout.com/for-developers/information-and-settings/env-variables
https://docs.blockscout.com/for-developers/information-and-settings/client-settings-parity-geth-ganache

**Comment by sami3232** [comment]
On a ec2 instance, what do you suggest to use in terms of RAM and disk space ?

**Comment by sami3232** [comment]
I launched openethereum in full archive node and fixed the problem I had.

Now I have another issue: 
```
Jun 23 15:21:47 ip-172-31-40-35 bash[269813]: 2021-06-23T15:21:47.812 application=indexer fetcher=block_reward count=10 error_count=10 [error>
Jun 23 15:21:47 ip-172-31-40-35 bash[269813]: @�: (404) Not Found
Jun 23 15:21:47 ip-172-31-40-35 bash[269813]: @�: (404) Not Found
```
I saw that some people got the same issue so I uncommented the line  ```config :indexer, Indexer.Block.Reward.Supervisor, disabled?: true``` in the file ``` apps/indexer/config/config.exs ``` however I still have a 404 error.

Do you have any idea where the problem come from ?

**Comment by vbaranov** [comment]
For block reward fetching `trace_block` should be enabled on the node and tracing of each block in the blockchain should be available. Please re-open if the issue still persists.
