### ISSUE TITLE
block#getblockreward returning incorrect values on ETC mainnet

### ISSUE THREAD

**Issue by psionski** [blockscout/blockscout#4303]
The API seems to always return around 3 ETC block reward, regardless of block height.

### Steps to reproduce

Navigate to https://blockscout.com/etc/mainnet/api?module=block&action=getblockreward&blockno=12968349
Then, navigate to https://blockscout.com/etc/mainnet/api?module=block&action=getblockreward&blockno=1

### Expected behaviour

The new block should have blockReward around 3.2 ETC, while block 1 should have 5 ETC

### Actual behaviour

Both requests return 3 ETC + some small amount TX fees

**Comment by svanegmond** [comment]
getblockreward does not work sensibly for us either.  

example
https://bx.testnet.shyft.network/api?module=block&action=getblockreward&blockno=1024
vs 
http://bx.testnet.shyft.network/blocks/1024/transactions

```

explorer=# select reward,address_hash,address_type from blocks b join block_rewards br on (b.hash=br.block_hash) where b.number=1024 
;
       reward        |                address_hash                |  address_type  
---------------------+--------------------------------------------+----------------
 7458143070000000000 | \x0000000000000000000000000000000000000000 | emission_funds
                   0 | \x0000000000000000000000000000000000000000 | validator
 7458143070000000000 | \x0000000000000000000000000000000000000000 | validator
 7458143070000000000 | \xca64bc42221156d5f0b210d2f2d2f835b6937690 | validator
(4 rows)


```
This is running 'master' as of ~ 2 days ago.

**Comment by vbaranov** [comment]
The issue resolved. The block reward respects block height in API.
