### ISSUE TITLE
Error deploying Docker BlockScout compilation

### ISSUE THREAD

**Issue by hashpaypie** [blockscout/blockscout#4309]
This is an error message

ERROR in ./css/app.scss
Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js):
ModuleBuildError: Module build failed (from ./node_modules/sass-loader/dist/cjs.js):
SassError: Undefined variable: "$font-family".
        on line 6 of css/_typography.scss
        from line 63 of css/app.scss
>>   font-family: $font-family;

   ---------------^

    at processResult (/opt/app/apps/block_scout_web/assets/node_modules/webpack/lib/NormalModule.js:581:19)
    at /opt/app/apps/block_scout_web/assets/node_modules/webpack/lib/NormalModule.js:674:5
    at /opt/app/apps/block_scout_web/assets/node_modules/loader-runner/lib/LoaderRunner.js:397:11
    at /opt/app/apps/block_scout_web/assets/node_modules/loader-runner/lib/LoaderRunner.js:252:18
    at context.callback (/opt/app/apps/block_scout_web/assets/node_modules/loader-runner/lib/LoaderRunner.js:124:13)
    at Object.callback (/opt/app/apps/block_scout_web/assets/node_modules/sass-loader/dist/index.js:54:7)
    at Object.done [as callback] (/opt/app/apps/block_scout_web/assets/node_modules/neo-async/async.js:8069:18)
    at options.error (/opt/app/apps/block_scout_web/assets/node_modules/node-sass/lib/index.js:293:32)
 @ ./js/app.js 4:0-25

ERROR in ./css/stakes.scss
Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js):
ModuleBuildError: Module build failed (from ./node_modules/sass-loader/dist/cjs.js):
SassError: Undefined variable: "$grid-breakpoints".
        on line 71 of node_modules/bootstrap/scss/mixins/_breakpoints.scss, in mixin `media-breakpoint-down`
        from line 21 of css/components/stakes/_stakes.scss
        from line 11 of css/stakes.scss
>> edia-breakpoint-down($name, $breakpoints: $grid-breakpoints) {

   ------------------------------------------^

    at processResult (/opt/app/apps/block_scout_web/assets/node_modules/webpack/lib/NormalModule.js:581:19)
    at /opt/app/apps/block_scout_web/assets/node_modules/webpack/lib/NormalModule.js:674:5
    at /opt/app/apps/block_scout_web/assets/node_modules/loader-runner/lib/LoaderRunner.js:397:11
    at /opt/app/apps/block_scout_web/assets/node_modules/loader-runner/lib/LoaderRunner.js:252:18
    at context.callback (/opt/app/apps/block_scout_web/assets/node_modules/loader-runner/lib/LoaderRunner.js:124:13)
    at Object.callback (/opt/app/apps/block_scout_web/assets/node_modules/sass-loader/dist/index.js:54:7)
    at Object.done [as callback] (/opt/app/apps/block_scout_web/assets/node_modules/neo-async/async.js:8069:18)
    at options.error (/opt/app/apps/block_scout_web/assets/node_modules/node-sass/lib/index.js:293:32)
 @ ./js/pages/stakes.js 12:0-31

2 ERRORS in child compilations
webpack 5.8.0 compiled with 4 errors in 107663 ms

asset awesomplete.min.js 7.64 KiB [emitted] [minimized] (name: awesomplete)
asset awesomplete-util.min.js 6.61 KiB [emitted] [minimized] (name: awesomplete-util)
asset ../css/awesomplete.css 1.84 KiB [emitted] (name: awesomplete)
Entrypoint awesomplete 9.48 KiB = ../css/awesomplete.css 1.84 KiB awesomplete.min.js 7.64 KiB
Entrypoint awesomplete-util 6.61 KiB = awesomplete-util.min.js
runtime modules 657 bytes 3 modules
orphan modules 50 bytes [orphan] 1 module
code generated modules 37.7 KiB (javascript) 1.84 KiB (css/mini-extract) [code generated]
  modules by path ./js/lib/*.js 24.9 KiB
    ./js/lib/awesomplete.js 58 bytes [built] [code generated]
    ./js/lib/awesomplete-util.js 24.9 KiB [built] [code generated]
  modules by path ./node_modules/awesomplete/ 12.8 KiB (javascript) 1.84 KiB (css/mini-extract)
    ./node_modules/awesomplete/awesomplete.js 12.8 KiB [built] [code generated]
    css ./node_modules/css-loader/dist/cjs.js!./node_modules/awesomplete/awesomplete.css 1.84 KiB [code generated]
webpack 5.8.0 compiled successfully in 7359 ms

asset dropzone.min.js 112 KiB [emitted] [minimized] (name: dropzone)
runtime modules 657 bytes 3 modules
cacheable modules 333 KiB
  ./js/lib/dropzone.js 18 bytes [built] [code generated]
  ./node_modules/dropzone/dist/dropzone.js 333 KiB [built] [code generated]
webpack 5.8.0 compiled successfully in 6419 ms
The command '/bin/sh -c cd apps/block_scout_web/assets/ &&     npm install &&     npm run deploy &&     cd -' returned a non-zero code: 1
make: *** [build] error 1

**Comment by hashpaypie** [comment]
After you remove the Docker image and container, you still get the same error

**Comment by vbaranov** [comment]
@hashpaypie could you clarify how to reproduce the issue?

**Comment by hashpaypie** [comment]
Modify a few file configurations and then report an error on startup

/root/blockscout/apps/block_scout_web/priv/gettext/en/LC_MESSAGES/default.po
/root/blockscout/apps/block_scout_web/lib/block_scout_web/templates/layout/_footer.html.eex
/root/blockscout/apps/block_scout_web/assets/css/theme/_variables.scss

cd  blockscout/docker
make start 

My operation steps

> @hashpaypie could you clarify how to reproduce the issue?

**Comment by ksangster** [comment]
I noticed with several of the css related node modules, `node rebuild <module name>` inside the container can fix it.
In my case, I updated this section of the Dockerfile:
```
RUN cd apps/block_scout_web/assets/ && \
    npm install && \
    npm rebuild node-sass && \  #<-- rebuild inside the container 
    npm run build && \
    cd -
```

**Comment by vbaranov** [comment]
NPM packages used by webpack have been updated to the latest versions. Please re-try.
