### ISSUE TITLE
Fetch contracts metadata for partially verified contracts in Sourcify

### ISSUE THREAD

**Issue by vbaranov** [blockscout/blockscout#4317]
> Fetching metadata for partially verified contracts should also work. Example: https://repo.sourcify.dev/contracts/partial_match/100/0x63e62989D9EB2d37dfDB1F93A22f063635b07d51/metadata.json

It should work for verification in the web interface and through existing `/verify_via_sourcify` API endpoint.

Since in this case contract is not fully verified, I suppose we should allow verifying such contracts through web interface / API endpoints even if they already partially verified before.

**Comment by naisteph24** [comment]
Already verified
