### ISSUE TITLE
What mean 'indexed?' field ?

### ISSUE THREAD

**Issue by andrii482** [blockscout/blockscout#4318]
![image](https://user-images.githubusercontent.com/61418776/123407959-303c7f00-d5b5-11eb-9d84-907a9096d16a.png)
Can I get any link to document that should  describe what this field mean, please ?
(or get some answer here, in thread)
Thanks.

**Comment by vbaranov** [comment]
Sure, https://docs.soliditylang.org/en/latest/contracts.html#events

>You can add the attribute indexed to up to three parameters which adds them to a special data structure known as “topics” instead of the data part of the log. A topic can only hold a single word (32 bytes) so if you use a reference type for an indexed argument, the Keccak-256 hash of the value is stored as a topic instead.

>All parameters without the indexed attribute are ABI-encoded into the data part of the log.

>Topics allow you to search for events, for example when filtering a sequence of blocks for certain events. You can also filter events by the address of the contract that emitted the event.

**Comment by andrii482** [comment]
Thank you for quick answer!
