### ISSUE TITLE
Ethereum Classic: <Issue Title>

### ISSUE THREAD

**Issue by Shujasheikh** [blockscout/blockscout#4322]
*Describe your issue here.*

### Environment
* Elixir Version: 1.11.3
* Erlang Version: 23
* BlockScout Version: v3.5.0-beta

* User Agent: `Mozilla/5.0 (Linux; Android 11; SAMSUNG SM-G781B) AppleWebKit/537.36 (KHTML, like Gecko) SamsungBrowser/14.2 Chrome/87.0.4280.141 Mobile Safari/537.36`

### Steps to reproduce

*Tell us how to reproduce this issue. If possible, push up a branch to your fork with a regression test we can run to reproduce locally.*

### Expected Behaviour

*Tell us what should happen.*

### Actual Behaviour

*Tell us what happens instead.*

**Comment by Shujasheikh** [comment]
Hi 
I want stop transaction some hack my bitcoin and ethrum. Please do stop transaction.
Thanks

**Comment by Shujasheikh** [comment]
Hi

In regards of your email, what do mean authorized thread by me.

Thanks
S Sheikh

**Comment by nikitosing** [comment]
@Shujasheikh it was automatically generated email by github

**Comment by Shujasheikh** [comment]
Thanks
Got it,
