### ISSUE TITLE
Watchpack Error (watcher): Error: ENOSPC

### ISSUE THREAD

**Issue by sami3232** [blockscout/blockscout#4328]
### Environment

* Elixir & Erlang/OTP versions (elixir -version):

Erlang/OTP 23 [erts-11.2] [source] [64-bit] [smp:2:2] [ds:2:2:10] [async-threads:1] [hipe]
Elixir 1.11.1 (compiled with Erlang/OTP 23)

*Operating System: Ubuntu 20.04 LTS
*Blockscout Version/branch: https://github.com/poanetwork/blockscout; I'm on branch "master"
*Libtool: 2.4.6-14
*Libgmp3-dev: 2:6.2.0+dfsg-4
*Inotify-tools: 3.14-8
*Rustc: 1.52.1
*Postgres : 11
*Psql : psql (PostgreSQL) 11.12 (Ubuntu 11.12-1.pgdg20.04+1)
*Geth 1.9.25

### Steps to reproduce
Blockscout is installed well.
DB postgres is connected.

I've launched a private chain using geth and created a node by using these commands :

```geth --nousb --rpc --rpcport "8085" --datadir ~/spicy init ~/genesis.json```

Node I launched in full archive mode:

```geth --nousb --rpc --rpcaddr 0.0.0.0 --port 30303 --rpcport 8545  --datadir ~/spicy  --rpcapi debug,net,eth,web3,txpool --wsapi "eth,net,web3,debug,txpool" --ws --wsaddr 0.0.0.0 --wsport 8546 --wsorigins "*" --syncmode=full --gcmode=archive --rpcvhosts=* --networkid 971389 --nodiscover```

genesis.json :
```json
{
    "nonce": "0x0000000000000042",
    "timestamp": "0x0",
    "parentHash": "0x0000000000000000000000000000000000000000000000000000000000000000",
    "extraData": "0x00",
    "gasLimit": "0x000001",
    "difficulty": "0x040",
    "mixhash": "0x0000000000000000000000000000000000000000000000000000000000000000",
    "coinbase": "0x0000000000000000000000000000000000000333",
    "alloc": {},
    "config": {"chainId": 230271 , "homesteadBlock": 0, "eip155Block": 0, "eip158Block": 0, "eip150Block": 0}
}

```
Also I don't really know what env variable to set for a private chain so I put these ones :

```
export ETHEREUM_JSONRPC_HTTP_URL=http://localhost:8545
export ETHEREUM_JSONRPC_WS_URL=ws://localhost:8546
export ETHEREUM_JSONRPC_TRACE_URL=http://localhost:8545
export ETHEREUM_JSONRPC_VARIANT=geth
export COIN=ETH
export PORT=4000
export NETWORK=Ethereum
export SUBNETWORK=Core
export DATABASE_URL=postgresql://123:123@localhost:5432/blockscout

```

### Expected behaviour
I excpect this to have less errors

### Actual behaviour

```
[webpack-cli] watching files for updates...
Watchpack Error (watcher): Error: ENOSPC: System limit for number of file watchers reached, watch '/home/ubuntu/blockscout/apps/block_scout_web/assets'
Watchpack Error (watcher): Error: ENOSPC: System limit for number of file watchers reached, watch '/home/ubuntu/blockscout/apps/block_scout_web/assets/js/lib'
Watchpack Error (watcher): Error: ENOSPC: System limit for number of file watchers reached, watch '/home/ubuntu/blockscout/apps/block_scout_web/assets/js'
Watchpack Error (watcher): Error: ENOSPC: System limit for number of file watchers reached, watch '/home/ubuntu/blockscout/apps/block_scout_web'

```
### PS

_just wanted to ask you if the doc on your website is still up to date ? I saw that you were using a lot of flags completely deprecated for geth. I removed **shh** and **network** from **rpcapi** and **wsapi** since they both no longer exist. Maybe there are some changes to make on doc or maybe I don't have the right version of geth ??_

https://docs.blockscout.com/for-developers/information-and-settings/client-settings-parity-geth-ganache

**Comment by poolarge** [comment]
Watchpack Error (watcher): Error: ENOSPC: System limit for number of file watchers reached, watch '~/blockscout/apps/block_scout_web/assets/node_modules/phoenix'
I came across the similer issue, and my blockscout also reported  "application=explorer [warning] Failed to get known tokens with reason 'econnrefused'."

**Comment by vbaranov** [comment]
@sami3232, @poolarge It looks like a well-known issue. Did you try a solution from https://stackoverflow.com/questions/53930305/nodemon-error-system-limit-for-number-of-file-watchers-reached ?

**Comment by poolarge** [comment]
2021-12-28T17:40:46.897 application=explorer [warning] Failed to get known tokens with reason 'econnrefused'.
 is the main issue for me 
but "Watchpack Error (watcher): Error: ENOSPC: System limit for number of file watchers reached, watch '~/blockscout/apps/block_scout_web/assets/node_modules/phoenix'"

**Comment by vbaranov** [comment]
@poolarge Blockscout tries to fetch the exchange rate for the token from CoinGecko. You can try disabling the known tokens fetcher by setting `DISABLE_KNOWN_TOKENS` environment variable.
