### ISSUE TITLE
Blockscout Docker container crashes in random moments

### ISSUE THREAD

**Issue by przemekpierzga** [blockscout/blockscout#4347]
There is an issue with blockscout container that causes it to crash in random moments (typically after 10-15 hours of work) and sometimes results in container restart loop. The message we receive right before crash is attached in a screenshot. However, the same error seems to appear during work of the container and not resulting in crash - so I don't know if it really is the root cause.

### Environment

* Elixir 1.11.3 (compiled with Erlang/OTP 23)
* Operating System: Docker container (Alpine Linux image) on Ubuntu 20.04.2
* Blockscout Version/branch: v3.7.0-beta

### Steps to reproduce

It's hard to tell how can this issue be reproduced - it happens during regular work, not giving really any specific information why it crashes.

### Expected behaviour

Container works predictably, not crash in unexpected moments or give more info on the issue

### Actual behaviour

Container crashes in random moments and we are unable to find a root cause

![Screenshot_Blockscout-container](https://user-images.githubusercontent.com/66253063/124718722-ad95b700-df06-11eb-9d86-9c7b90dcd622.png)

**Comment by vbaranov** [comment]
@przemekpierzga could you please use the current master branch version? It is not released yet and contains the fix for your issue.

**Comment by przemekpierzga** [comment]
Hello, sorry for late response. I updated the blockscout to version 3.7.1 (as far as I understood the changelog, it had the fix for my issue, too). So far everything seems to be working correctly, but let me go back with the final feedback in few more days if it is acceptable for you.

**Comment by przemekpierzga** [comment]
After updating to Blockscout v3.7.1 the issue seems to have gone - no more smartcontact error, container does not restart itself randomly. Thanks!
