### ISSUE TITLE
403 Error during websocket handshake when deployed behind ELB

### ISSUE THREAD

**Issue by jimmay5469** [blockscout/blockscout#435]
The following error is displayed in the browser console when the application is deployed behind ELB:
`WebSocket connection to 'ws://sokaa-explorer-sokol-elb-1578737512.us-east-1.elb.amazonaws.com/socket/websocket?locale=en&vsn=2.0.0' failed: Error during WebSocket handshake: Unexpected response code: 403`

**Comment by vbaranov** [comment]
not relevant anymore
