### ISSUE TITLE
Incorrect formatting for a complex ABIv2 response

### ISSUE THREAD

**Issue by akolotov** [blockscout/blockscout#4358]
Incorrect formatting while a complex data structure is read by a contract's method call

### Steps to reproduce

* Vist a contract page: https://blockscout.com/poa/sokol/address/0x418FDA4cB55fde2cd2ceD855d16C4fCe6045F2B3/read-contract
* Enter `0xfe6a43fa23a0269092cbf97cb908e1d5a49a18fd6942baf2467fb5b221e39ab2` in the getReceipt method's arguments.

### Expected behaviour

* Proper formatting of data structure

### Actual behaviour

![image](https://user-images.githubusercontent.com/20793260/125088753-68c07a80-e0d6-11eb-842f-7ed4ab431804.png)

**Comment by vbaranov** [comment]
Looks better now

<img width="1287" alt="Screenshot 2021-09-16 at 17 13 28" src="https://user-images.githubusercontent.com/4341812/133628035-ac9dab4b-5303-43ed-a674-c0afd3256612.png">
