### ISSUE TITLE
Search results in 404 error if the search input is empty

### ISSUE THREAD

**Issue by ulyanas** [blockscout/blockscout#4378]
### Steps to reproduce
1. Goto Blockscout homepage
2. Leave Search input field empty
3. Click on the search icon or hit Enter 

### Expected behaviour
1) Nothing happens if the search string is empty. 
or
2) Special page indicating that the empty search string was entered is shown. 
E.g. Google search  uses 1, Etherscan uses 2 https://etherscan.io/search?f=0&q= 

### Actual behaviour
404 page is shown

**Comment by vbaranov** [comment]
Implemented in https://github.com/blockscout/blockscout/pull/4355
