### ISSUE TITLE
Token Holders page not showing complete information

### ISSUE THREAD

**Issue by t12ung** [blockscout/blockscout#4380]
*Token Holders Page showing incorrect information. (issue effective some time between July 4th and July 12th)*
- missing addresses
- not ordered by descending token amount
- listed addresses totalling 100% of liquidity

### Environment

* XDAI mainnet

### Steps to reproduce

* https://blockscout.com/xdai/mainnet/tokens/0x5426a4d0926d6cd2c003241d8fb1c9420e43ed26/token-holders

### Expected behaviour

* 166 addresses, max 50 per page = 4 pages.
* Addresses in descending order of token amount, across all pages, first amount on a consecutive page smaller than last amount on a previous page.
* Total of liquidity % for all listed addresses totalling 100%.

### Actual behaviour

* Showing only 148 of 166 addresses, over 3 pages.
* Addresses in descending ordered only per page, first amount on a consecutive page larger than the last amount on a previous page.
* * Total of liquidity % for all listed addresses totalling 45%.

### Example addresses missing from Token Holders
* https://blockscout.com/xdai/mainnet/address/0xd0B5AB1609E1fa7CF6B714Da42e2C9E45e3Ca28D/tokens (`3,951.922`)
* https://blockscout.com/xdai/mainnet/address/0xbe56543A84a45B1Efe5981A3D43c93dCE7c5f55E/tokens (`3,794.372`)

**Comment by GriffGreen** [comment]
This is the Case for a lot of tokens...

**Comment by vbaranov** [comment]
@t12ung, @GriffGreen thanks for bringing that up. We deployed an update for xDai instance in regards token balances. I would love to get your feedback is the issue still persists from you perspective or not. Thanks in advance.

**Comment by t12ung** [comment]
Can confirm it's fixed now - thanks!
