### ISSUE TITLE
Contract creation code not working

### ISSUE THREAD

**Issue by crypto-facs** [blockscout/blockscout#4386]
### Environment

* Elixir & Erlang/OTP versions (`elixir -version`): Elixir 1.11.3 / Erlang/OTP 23
* Operating System: MacOs Big Sur
* Blockscout Version/branch: Master commit `7dc7604e4f0c8d77b438093be0ee15d7a5b90ce7`

### Steps to reproduce

I am using `geth` but I see the issue on POA production explorer  [here](https://blockscout.com/poa/core/address/0x21128A43e5Af878B9Bdd69EF7423B4690F66f2C1/contracts)
1. Deploy smart contracts
2. Go to contract's address detail dashboard 
3. Click on `code` tab

### Expected behaviour

You should see bytecode and contract creation code

### Actual behaviour

App breaks

**Comment by vbaranov** [comment]
Fixed with https://github.com/blockscout/blockscout/pull/4388
