### ISSUE TITLE
ETC transfer to RONIN WETH 

### ISSUE THREAD

**Issue by czarcasm23** [blockscout/blockscout#4390]
*Describe your issue here.*
Transfrred from Etherium Classic to WETH RONIN and funds are missing
 I accidentally sent etc  to weth ronin address instead of metamask eth 
but it was my weth wallaet will it go thru?

### Steps to reproduce

I want my fund to transfer to metamask instead

blockchain
https://blockscout.com/etc/mainnet/tx/0xe80276a50a6e6a0302ec58b13315a8f6a01a8752d6c6c5a25edcf00b3e8cf0f4/internal-transactions

I need help

Was to transfer to this wallet of mine
ronin:d7a33136f2499c78025f94fdc380ed04a48d31f2 THIS IS RONIN WALLET WETH that I accidentally transfer to

Just transfer it to my  metamask instead 
0xF1B12a5c75B3b4CEe027a57a24fB1cCCefF23dBb

**Comment by vbaranov** [comment]
The issue doesn't relate to Blockscout explorer.
