### ISSUE TITLE
No notification that info copied if two squares are pressed for a method's parameter

### ISSUE THREAD

**Issue by akolotov** [blockscout/blockscout#4392]
Consider the following transaction https://blockscout.com/poa/sokol/tx/0x46da8dae5083bd2867d90f8c6f2908f8172791a4771a924d4a6d6fea10d3f5f9 in BS. In the input section it has a table with the parameters passed to the the method.

![image](https://user-images.githubusercontent.com/20793260/126045015-dd545cda-03f9-4dd9-88a7-d0bf0e84ba16.png)

Two squares near to the transaction hash in the table allow to copy the hash to the buffer and it works without issues. But there is no any notification that the information was copied and it is confusing since it is not clear if the copy functionality works or not.

**Comment by nikitosing** [comment]
This happened because in this and similar cases there are not enough space for rendering tooltip so js does not show tooltip with "Copied!" sign

**Comment by nikitosing** [comment]
[Example](https://github.com/blockscout/blockscout/commit/56133dbad00ce61eeb4b80f6e19210e7b0798068) of code, wich is properly working in this case
