### ISSUE TITLE
Only fetches ropsten genesis block

### ISSUE THREAD

**Issue by enriavil1** [blockscout/blockscout#4394]
*Describe your issue here.*
I try running the Geth varity but it only gets the genesis block and not any other block
### Environment

* Elixir & Erlang/OTP versions (`elixir -version`): 1.11.0
* Operating System: MacOs 
* Blockscout Version/branch: 3.5.0

### Steps to reproduce
run the manual deployment of the blockscout documentation and run it using http = http://localhost:8545 and ws=ws://localhost:8546 then run the Geth blockchain in the terminal with the ropsten blockchain using the following command:
"
geth --ropsten --http --http.addr 0.0.0.0 --http.api debug,net,eth,shh,web3,txpool --ws --ws.addr 0.0.0.0 --ws.api "eth,net,web3,network,debug,txpool" --ws.origins "*" --http.vhosts "*" --gcmode=archive --syncmode snap
"
 

*Tell us how to reproduce this issue.  ❤️ if you can push up a branch to your fork with a regression test we can run to reproduce locally.*

### Expected behaviour
*Tell us what should happen.*
to get all the blocks and show them properly

### Actual behaviour

*Tell us what happens instead.*
it only gets the genesis block of the ropsten testate

**Comment by vbaranov** [comment]
Blockscout should be launched on a synchronized archive node. I suppose you ran it before your Ropsten node synchronized.

**Comment by enriavil1** [comment]
I just checked if it is synchronised with eth.syncing and it returned false, so I believe it is synchronised. I am running it on a second terminal and mix phx.server in another terminal. Now I am getting the following error.

2021-07-19T16:07:13.992 [error] Task #PID<0.1307.0> started from Indexer.Block.Realtime.Fetcher terminating
** (FunctionClauseError) no function clause matching in EthereumJSONRPC.Block.entry_to_elixir/1
    (ethereum_jsonrpc 0.1.0) EthereumJSONRPC.Block.entry_to_elixir({"baseFeePerGas", "0xc"})
    (elixir 1.11.0) lib/enum.ex:1323: anonymous fn/4 in Enum.into/3
    (stdlib 3.14.2.1) maps.erl:233: :maps.fold_1/3
    (elixir 1.11.0) lib/enum.ex:2197: Enum.into/4
    (elixir 1.11.0) lib/enum.ex:1399: Enum."-map/2-lists^map/1-0-"/2
    (ethereum_jsonrpc 0.1.0) lib/ethereum_jsonrpc/blocks.ex:44: EthereumJSONRPC.Blocks.from_responses/2
    (ethereum_jsonrpc 0.1.0) lib/ethereum_jsonrpc.ex:483: EthereumJSONRPC.fetch_blocks_by_params/3
    (indexer 0.1.0) lib/indexer/block/fetcher.ex:131: Indexer.Block.Fetcher.fetch_and_import_range/2
    (indexer 0.1.0) lib/indexer/block/realtime/fetcher.ex:284: Indexer.Block.Realtime.Fetcher.do_fetch_and_import_block/3
    (indexer 0.1.0) lib/indexer/logger.ex:14: Indexer.Logger.metadata/2
    (indexer 0.1.0) lib/indexer/block/realtime/fetcher.ex:267: Indexer.Block.Realtime.Fetcher.fetch_and_import_block/4
    (elixir 1.11.0) lib/task/supervised.ex:90: Task.Supervised.invoke_mfa/2
    (stdlib 3.14.2.1) proc_lib.erl:226: :proc_lib.init_p_do_apply/3
Function: &Indexer.Block.Realtime.Fetcher.fetch_and_import_block/3
    Args: [10668298, %Indexer.Block.Fetcher{broadcast: :realtime, callback_module: Indexer.Block.Realtime.Fetcher, json_rpc_named_arguments: [transport: EthereumJSONRPC.HTTP, transport_options: [http: EthereumJSONRPC.HTTP.HTTPoison, url: "http://localhost:8545", http_options: [recv_timeout: 60000, timeout: 60000, hackney: [pool: :ethereum_jsonrpc]]], variant: EthereumJSONRPC.Geth], receipts_batch_size: 250, receipts_concurrency: 10}, false]
2021-07-19T16:07:14.678 fetcher=pending_transaction [error] Task #PID<0.1300.0> started from Indexer.Fetcher.PendingTransaction terminating
** (FunctionClauseError) no function clause matching in EthereumJSONRPC.Transaction.elixir_to_params/1
    (ethereum_jsonrpc 0.1.0) lib/ethereum_jsonrpc/transaction.ex:149: EthereumJSONRPC.Transaction.elixir_to_params(%{nil => nil, "blockHash" => nil, "blockNumber" => nil, "chainId" => 3, "from" => "0x22dd63c3619818fdbc262c78baee43cb61e9cccf", "gas" => 35000, "hash" => "0x57922df1760d3b799f1222560a554257bff7b6fb6509a0b46579417a7fc42b84", "input" => "0x1a8451e600000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000", "nonce" => 5, "r" => 81298934919429629312381278133741909254614648819989419829674526460850574348327, "s" => 34921141675444461613236846141549202299924393876159089267939850815758685633973, "to" => "0xf2c1e45b6611bc4378c3502789957a57e0390b79", "transactionIndex" => nil, "v" => 1, "value" => 100000000000000})
    (elixir 1.11.0) lib/enum.ex:1399: Enum."-map/2-lists^map/1-0-"/2
    (ethereum_jsonrpc 0.1.0) lib/ethereum_jsonrpc/geth.ex:70: EthereumJSONRPC.Geth.fetch_pending_transactions/1
    (indexer 0.1.0) lib/indexer/fetcher/pending_transaction.ex:120: Indexer.Fetcher.PendingTransaction.task/1
    (elixir 1.11.0) lib/task/supervised.ex:90: Task.Supervised.invoke_mfa/2
    (elixir 1.11.0) lib/task/supervised.ex:35: Task.Supervised.reply/5
    (stdlib 3.14.2.1) proc_lib.erl:226: :proc_lib.init_p_do_apply/3
Function: #Function<2.110683744/0 in Indexer.Fetcher.PendingTransaction.handle_info/2>
    Args: []



> Blockscout should be launched on a synchronized archive node. I suppose you ran it before your Ropsten node synchronized.

**Comment by enriavil1** [comment]
Another error I get later on is 

2021-07-19T16:25:19.249 application=indexer fetcher=block_catchup first_block_number=10612388 last_block_number=10612379 [error] ** (FunctionClauseError) no function clause matching in EthereumJSONRPC.Block.entry_to_elixir/1
    (ethereum_jsonrpc 0.1.0) EthereumJSONRPC.Block.entry_to_elixir({"baseFeePerGas", "0x7"})
    (elixir 1.11.0) lib/enum.ex:1323: anonymous fn/4 in Enum.into/3
    (stdlib 3.14.2.1) maps.erl:233: :maps.fold_1/3
    (elixir 1.11.0) lib/enum.ex:2197: Enum.into/4
    (elixir 1.11.0) lib/enum.ex:1399: Enum."-map/2-lists^map/1-0-"/2
    (ethereum_jsonrpc 0.1.0) lib/ethereum_jsonrpc/blocks.ex:44: EthereumJSONRPC.Blocks.from_responses/2
    (ethereum_jsonrpc 0.1.0) lib/ethereum_jsonrpc.ex:483: EthereumJSONRPC.fetch_blocks_by_params/3
    (indexer 0.1.0) lib/indexer/block/fetcher.ex:131: Indexer.Block.Fetcher.fetch_and_import_range/2
    (indexer 0.1.0) lib/indexer/block/catchup/fetcher.ex:194: Indexer.Block.Catchup.Fetcher.fetch_and_import_range_from_sequence/3
    (elixir 1.11.0) lib/task/supervised.ex:90: Task.Supervised.invoke_mfa/2
    (elixir 1.11.0) lib/task/supervised.ex:35: Task.Supervised.reply/5
    (stdlib 3.14.2.1) proc_lib.erl:226: :proc_lib.init_p_do_apply/3

**Comment by vbaranov** [comment]
>Elixir & Erlang/OTP versions (elixir -version): 1.11.0
Please update to 1.11.4

>Blockscout Version/branch: 3.5.0
Please update to the latest 3.7.1

Which version of Geth do you use?

**Comment by enriavil1** [comment]
I have the version 1.10.4

**Comment by enriavil1** [comment]
> > Elixir & Erlang/OTP versions (elixir -version): 1.11.0
> > Please update to 1.11.4
> 
> > Blockscout Version/branch: 3.5.0
> > Please update to the latest 3.7.1
> 
> Which version of Geth do you use?

Does it matter if I am using --syncmode =snap?

**Comment by vbaranov** [comment]
> Another error I get later on is

The issue resolved by this PR https://github.com/blockscout/blockscout/pull/4486
