### ISSUE TITLE
Ethereum Classic: problem with 0xf885b40fb1619d34af8dcd452cf22f70dcec614455745c01af02166509054e51

### ISSUE THREAD

**Issue by jschaff7711** [blockscout/blockscout#4395]
Transaction submitted two days ago and shown as success has not gone through 0xf885b40fb1619d34af8dcd452cf22f70dcec614455745c01af02166509054e51

Please help with this issue

thank you

### Environment
* Elixir Version: 1.11.3
* Erlang Version: 23
* BlockScout Version: v3.5.0-beta

* User Agent: `Mozilla/5.0 (iPhone; CPU iPhone OS 14_6 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Mobile/15E148 BitMart`

### Steps to reproduce

*Tell us how to reproduce this issue. If possible, push up a branch to your fork with a regression test we can run to reproduce locally.*

### Expected Behaviour

*Tell us what should happen.*

### Actual Behaviour

*Tell us what happens instead.*

**Comment by nikitosing** [comment]
you sent this funds to another account

![image](https://user-images.githubusercontent.com/32202610/126096677-5319fc05-ebb5-4de4-b0b8-4db7521cd797.png)
