### ISSUE TITLE
RSK: Stuck in block 3,496,854

### ISSUE THREAD

**Issue by alepc253** [blockscout/blockscout#4403]
Blockscout is not working for RSK mainnet

### Environment
* Elixir Version: 1.11.4
* Erlang Version: 23
* BlockScout Version: v3.7.0-beta

* User Agent: `Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.114 Safari/537.36`

### Steps to reproduce

Just checking https://blockscout.com/rsk/mainnet you can see the issue

### Expected Behaviour

Explorer showing up-to-date data from RSK blockchain

### Actual Behaviour

Stuck, no new blocks

**Comment by pmprete** [comment]
Same issue as https://github.com/blockscout/blockscout/issues/4405

**Comment by john-light** [comment]
This issue seems to be fixed: https://blockscout.com/rsk/mainnet

**Comment by pmprete** [comment]
It was fixed! thanks!

**Comment by john-light** [comment]
@pmprete @vbaranov actually just noticed that while the explorer is at least back up, it is a few days behind. Maybe the node was offline and it just working to catch up to the chain tip?

![Screenshot 2021-08-18 at 18-03-03 RSK Explorer - BlockScout](https://user-images.githubusercontent.com/9424721/129978226-5b14ac8d-e978-48cc-af87-67260c7fc4a0.png)

**Comment by alepc253** [comment]
hi @john-light, yes, we are working together with Blockscout team to restore the service, should be working normally soon

**Comment by vbaranov** [comment]
RSK instance of Blockscout is processing new blocks. Let me close this issue.
