### ISSUE TITLE
Energy Web Chain: <Issue Title>

### ISSUE THREAD

**Issue by pepito-grillito** [blockscout/blockscout#4404]
*Describe your issue here.*

Recently a new farming platform called g$wap (gswap.app) has launched on the Energy Web Chain, so I think that would be a good idea to include it with Carbonswap and both bridges on the "apps" display that appears on explorer.energyweb.org

### Environment
* Elixir Version: 1.11.4
* Erlang Version: 23
* BlockScout Version: v3.7.1-beta

* User Agent: `Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.164 Safari/537.36`

### Steps to reproduce

*Tell us how to reproduce this issue. If possible, push up a branch to your fork with a regression test we can run to reproduce locally.*

Just to add it

### Expected Behaviour

*Tell us what should happen.*

It should be added to "apps" because it's an app on the Energy Web Chain, like CS and both bridges

### Actual Behaviour

*Tell us what happens instead.*

It's not added yet

![image](https://user-images.githubusercontent.com/87708203/126333442-1172d82b-4720-48b1-a651-6655c7477344.png)

**Comment by vbaranov** [comment]
There is no official support of Energy web chain here. Try to ask in their fork https://github.com/energywebfoundation/blockscout
