### ISSUE TITLE
RSK: <Not working>

### ISSUE THREAD

**Issue by pmprete** [blockscout/blockscout#4405]
*Describe your issue here.*
The blockscout explorer for RSK https://blockscout.com/rsk/mainnet/ never loads the blockchain info and if you try to look for a specific address https://blockscout.com/rsk/mainnet/address/0x9d11937E2179dC5270Aa86A3f8143232D6DA0E69 you get a 504 error

### Environment
* Elixir Version: 1.11.4
* Erlang Version: 23
* BlockScout Version: v3.7.0-beta

* User Agent: `Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.114 Safari/537.36`

### Steps to reproduce

just open https://blockscout.com/rsk/mainnet/

### Expected Behaviour

To load the info from the blockchain

### Actual Behaviour

Pages loads but its not complete and i can't perform any searchs

**Comment by vbaranov** [comment]
RSK instance of Blockscout is back to the operational state
