### ISSUE TITLE
Energy Web Chain: Whenever "code" is selected on the contract page I get "Internal server error"

### ISSUE THREAD

**Issue by Ace-Of-Fades** [blockscout/blockscout#4415]
Lots of the tokens on the https://explorer.energyweb.org block explorer spit out "Internal server error" when trying to view the contract code.

### Environment
* Elixir Version: 1.11.4
* Erlang Version: 23
* BlockScout Version: v3.7.1-beta

* User Agent: `Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:89.0) Gecko/20100101 Firefox/89.0`

### Steps to reproduce

*Tell us how to reproduce this issue. If possible, push up a branch to your fork with a regression test we can run to reproduce locally.*

### Expected Behaviour

*Tell us what should happen.*

### Actual Behaviour

*Tell us what happens instead.*

**Comment by vbaranov** [comment]
There is no official support of Energy Web Chain here. Try to ask in their fork https://github.com/energywebfoundation/blockscout
