### ISSUE TITLE
StakingDapp not working when StakingAuRa is deployed with Native Token

### ISSUE THREAD

**Issue by eabz** [blockscout/blockscout#4438]
I am running my own private network with POSDAO. 

Since it doesn't use a token on the StakingAuRa contract (my network is using the native token), the StakingDapp is not working properly.
I guess it is trying to fetch the token information, but that should only be done when there is a specific token for the StakingAura

Error log:

```
2021-07-26T04:01:35.077 [info] Application explorer exited: Explorer.Application.start(:normal, []) returned an error: shutdown: failed to start child: Explorer.Staking.ContractState
    ** (EXIT) an exception was raised:
        ** (MatchError) no match of right hand side value: %{"2d21d217" => {:error, "(-32015) VM execution error. (Reverted 0x)"}, "dfc8bf4e" => {:ok, ["0x88b35a64690c7b57af11d992d73e90ab8889c919"]}}
            (explorer 0.0.1) lib/explorer/staking/contract_state.ex:106: Explorer.Staking.ContractState.init/1
            (stdlib 3.14.1) gen_server.erl:417: :gen_server.init_it/2
            (stdlib 3.14.1) gen_server.erl:385: :gen_server.init_it/6
            (stdlib 3.14.1) proc_lib.erl:226: :proc_lib.init_p_do_apply/3
** (Mix) Could not start application explorer: Explorer.Application.start(:normal, []) returned an error: shutdown: failed to start child: Explorer.Staking.ContractState
    ** (EXIT) an exception was raised:
        ** (MatchError) no match of right hand side value: %{"2d21d217" => {:error, "(-32015) VM execution error. (Reverted 0x)"}, "dfc8bf4e" => {:ok, ["0x88b35a64690c7b57af11d992d73e90ab8889c919"]}}
            (explorer 0.0.1) lib/explorer/staking/contract_state.ex:106: Explorer.Staking.ContractState.init/1
            (stdlib 3.14.1) gen_server.erl:417: :gen_server.init_it/2
            (stdlib 3.14.1) gen_server.erl:385: :gen_server.init_it/6
            (stdlib 3.14.1) proc_lib.erl:226: :proc_lib.init_p_do_apply/3
```

**Comment by vbaranov** [comment]
In order to make embedded in Blockscout Staking Dapp work, the StakingAura contract should satisfy the ABI StakingAura contract: https://blockscout.com/xdai/mainnet/address/0xAaD2B7d0b9aEF64288bCD541670ecC05aAd1c8dC/contracts and the address of that contract should be provided in `POS_STAKING_CONTRACT` env variable.

**Comment by eabz** [comment]
Yes, I am using the official POSDAO contracts as a Staking Contract (https://github.com/poanetwork/posdao-contracts)

xDai uses `StakingAuRaTokens.sol` as the contract, and seems blockscout is only working with it.
My network uses `StakingAuRaCoins.sol` to stake with the native token.

**Comment by vbaranov** [comment]
The error says that the contract doesn't have `erc677TokenContract` getter.

**Comment by eabz** [comment]
Yes, because the `StakingAuRaCoins` contract on POSDAO consensus doesn't have an `erc677Token` attached to it.

https://github.com/poanetwork/posdao-contracts/blob/master/contracts/base/StakingAuRaCoins.sol

**Comment by vbaranov** [comment]
It would be awesome if you can contribute to add support for native coins. We have no resources currently to allocate for this task since embedded staking dapp is used specifically on xDai instance with non-native token.

**Comment by eabz** [comment]
I finished porting it to native staking but I didn't have time to make both compatible. But might work for future development. 
https://github.com/polischain/blockscout
