### ISSUE TITLE
Firefox: Connection with wss://somewhere.com/phoenix/live_reload/socket/websocket?vsn=2.0.0 has been interrupted.

### ISSUE THREAD

**Issue by sami3232** [blockscout/blockscout#4442]
### Environment

* Elixir & Erlang/OTP versions (elixir -version):

Erlang/OTP 23 [erts-11.2] [source] [64-bit] [smp:2:2] [ds:2:2:10] [async-threads:1] [hipe]
Elixir 1.11.1 (compiled with Erlang/OTP 23)

*Operating System: Ubuntu 20.04 LTS
*Blockscout Version/branch: https://github.com/poanetwork/blockscout; I'm on branch "master"
*Libtool: 2.4.6-14
*Libgmp3-dev: 2:6.2.0+dfsg-4
*Inotify-tools: 3.14-8
*Rustc: 1.52.1
*Postgres : 11
*Psql : psql (PostgreSQL) 11.12 (Ubuntu 11.12-1.pgdg20.04+1)
*Geth 1.9.25

### Steps to reproduce
Blockscout is installed well.
DB postgres is connected.
personal Geth node is running in full archive mode and available

Env variables are set :

```
export ETHEREUM_JSONRPC_HTTP_URL=http://somewhere:8545
export ETHEREUM_JSONRPC_WS_URL=ws://somewhere:8546
export ETHEREUM_JSONRPC_TRACE_URL=http://somewhere:8545
export ETHEREUM_JSONRPC_VARIANT=geth
export COIN=ETH
export PORT=4000
export NETWORK=somewhere network
export SUBNETWORK=Hello
export DATABASE_URL=postgresql://123:123@localhost:5432/blockscout
export LOGO=/images/somewhere.svg

```
### Steps to reproduce
As you saw above, Blockscout is running and I didn't have this "error"/"log" before. What did I change ?
Well since I try to customize Blockscout, I tried to customize the favicon used on the app.

```sudo nano apps/block_scout_web/lib/block_scout_web/templates/layout/app.html.eex```
I replaced all occurrences of `favicon` by another image named `test.png`.

After that I was getting this log on the console of the page :

```
Firefox can't establish connection with the server at address wss://somewhere.com/phoenix/live_reload/socket/websocket?vsn=2.0.0. frame:3:12290

```
I'm not in prod environment.

### Expected behaviour

*What should happened ? This log should not appear. *

### Actual behaviour

```
Firefox can't establish connection with the server at address wss://somewhere.com/phoenix/live_reload/socket/websocket?vsn=2.0.0. frame:3:12290

```

**Comment by vbaranov** [comment]
@sami3232 could you try in Google Chrome instead? Do you see the same behavior?

**Comment by sami3232** [comment]
@vbaranov , I just tried on chrome and I don't have this issue. How can I fix this on firefox ?

**Comment by vbaranov** [comment]
There is no solution yet. You can use Chrome for development purposes. The issue shouldn't reproduce on the prod environment since live reloading is dev-related only.

**Comment by sami3232** [comment]
Well even with the prod environment, I got this issue. I just have to reload the page to see it appears.

Is there anything to add with ` export MIX_ENV=prod` ?

**Comment by vbaranov** [comment]
export MIX_ENV=prod is enough. Take a look to https://blockscout.com/xdai/mainnet/. Looks fine of Firefox from my perspective.

**Comment by sami3232** [comment]
Yeah it looks fine however I still have the same message in the console even with prod environment on firefox. I use a reverse proxy for redirection on the port 443. Maybe it's the nginx reverse proxy. What do you think ?

Here is the code I'm using on the conf file for nginx:

```
server {
	listen    80;
	server_name    something.somewhere.com;
	return 301 https://something.somewhere.com$request_uri;
}

server {
    listen              443 ssl;
    server_name         something.somewhere.com;

    ssl_certificate     ~/alot/SSL.crt;
    ssl_certificate_key ~/alor/SSL.key;
    location / {
        proxy_pass http://localhost:4000;
	root /home/ubuntu/blockscout;
	proxy_http_version 1.1;
        proxy_redirect off;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header Host $host;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
    }
}

```

**Comment by sami3232** [comment]
Well it seems like I'm having the same error on both chrome and firefox. I guess there's something else to modify. Even the prod mod doesn't change a thing

**Comment by vbaranov** [comment]
@sami3232 you should configure `/socket/` path in Nginx like suggested in this comment https://github.com/blockscout/blockscout/issues/4963#issuecomment-1033508838.
