### ISSUE TITLE
Ethereum Classic: <Issue Title>Invalid Transaction

### ISSUE THREAD

**Issue by biuroglobalnet** [blockscout/blockscout#4443]
*Describe your issue here.*
Hi,
I'm completely new here and I don't know English, so forgive me if I write something wrong :)

What is going on?
I want to know because through BINANCE I made a mistake transaction with ETC for ETH wallet. Of course, the funds did not reach me. What can I do about it now?

Thank you for guiding me to the right place :)
### Environment
* Elixir Version: 1.11.3
* Erlang Version: 23
* BlockScout Version: v3.5.0-beta

* User Agent: `Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.107 Safari/537.36`

### Steps to reproduce

*Tell us how to reproduce this issue. If possible, push up a branch to your fork with a regression test we can run to reproduce locally.*

### Expected Behaviour

*Tell us what should happen.*

### Actual Behaviour

*Tell us what happens instead.*

**Comment by vbaranov** [comment]
Please ask binance support

**Comment by biuroglobalnet** [comment]
I contacted Binance,
wrote thus:
"After checking, I found your transaction has already been confirmed on the blockchain, which means Binance has successfully completed the transaction and we are no longer able to control the transaction

If you haven't received your funds after a while, we advise you to contact the receiving wallet / exchange team for assistance. "

**Comment by vbaranov** [comment]
> Contact the receiving wallet / exchange team for assistance

You should do this.

Blockscout is a blockchain explorer and it doesn't store any funds.

**Comment by biuroglobalnet** [comment]
https://blockscout.com/etc/mainnet/tx/0x5f08d79e3349dc7e87ab39b0534af9aec5a2ba3ce51604868275b4e2e0456dbf/internal-transactions
