### ISSUE TITLE
Could not compile dependency ex_keccack on macos

### ISSUE THREAD

**Issue by luffybhaagi** [blockscout/blockscout#4446]
could not compile dependency :ex_keccak, "mix compile" failed. You can recompile this dependency with "mix deps.compile ex_keccak", update it with "mix deps.update ex_keccak" or clean it with "mix deps.clean ex_keccak"
** (ErlangError) Erlang error: :enoent
    (elixir 1.11.4) lib/system.ex:823: System.cmd("cargo", ["rustc", "--release", "--", "-C", "link-arg=-undefined", "-C", "link-arg=dynamic_lookup"], [cd: "/Users/blockscout/deps/ex_keccak/native/exkeccak", stderr_to_stdout: true, env: [{"CARGO_TARGET_DIR", "/Users/blockscout/_build/dev/rustler_crates/exkeccak"}], into: %IO.Stream{device: :standard_io, line_or_bytes: :line, raw: false}])
    (rustler 0.21.1) lib/mix/tasks/compile.rustler.ex:59: Mix.Tasks.Compile.Rustler.compile_crate/1
    (elixir 1.11.4) lib/enum.ex:1411: Enum."-map/2-lists^map/1-0-"/2
    (rustler 0.21.1) lib/mix/tasks/compile.rustler.ex:15: Mix.Tasks.Compile.Rustler.run/1
    (mix 1.11.4) lib/mix/task.ex:394: Mix.Task.run_task/3
    (mix 1.11.4) lib/mix/tasks/compile.all.ex:90: Mix.Tasks.Compile.All.run_compiler/2
    (mix 1.11.4) lib/mix/tasks/compile.all.ex:70: Mix.Tasks.Compile.All.compile/4
    (mix 1.11.4) lib/mix/tasks/compile.all.ex:57: Mix.Tasks.Compile.All.with_logger_app/2
    
 Versions:
elixir 1.11.4
erlang 23.3.4.1
nodejs 14.17.0

Im getting above error when compiling the project:
mix do deps.get, local.rebase --force, deps.compile, compile.

brew list
==> Formulae
ansible		bdw-gc		eslint		gnutls		jansson		libevent	libssh2		m4		nghttp2		p11-kit		python@3.7	unbound
asdf		brotli		gawk		go		jemalloc	libffi		libtasn1	make		nginx		parallel	python@3.9	unixodbc
autoconf	c-ares		gcc		gradle		jpeg		libgcrypt	libtiff		maven		node		pcre		readline	wget
automake	coreutils	gdbm		groovy		jshon		libgpg-error	libtool		minikube	npth		pcre2		rtmpdump	wxmac
babel		curl		gettext		guile		krb5		libidn2		libunistring	mpdecimal	openjdk		pinentry	sqlite		wxwidgets
bash		datamash	git		helm		kubernetes-cli	libksba		libusb		mpfr		openjdk@11	pipx		tcl-tk		xz
bazel@3.7.0	elixir		gmp		icu4c		libassuan	libmpc		libuv		mtr		openldap	pkg-config	terraform	zstd
bc		erlang		gnupg		isl		libev		libpng		libyaml		nettle		openssl@1.1	postgresql	truffle
    
Can you please help to resolve the issue?

**Comment by sidhujag** [comment]
I had this issue, its working in my docker image if you want to take a look at it for hints: https://github.com/syscoin/blockscout/blob/master/Dockerfile

**Comment by luffybhaagi** [comment]
mix do ecto.create
** (File.Error) could not read file "/Users/blockscout/apps/explorer/config/dev/.exs": no such file or directory
    (elixir 1.11.3) lib/file.ex:355: File.read!/1
    (elixir 1.11.3) lib/config.ex:240: Config.__import__!/1
    (mix 1.11.3) lib/mix/config.ex:161: anonymous fn/2 in Mix.Config.__import__!/2
    (elixir 1.11.3) lib/enum.ex:2193: Enum."-reduce/3-lists^foldl/2-0-"/3
    (mix 1.11.3) lib/mix/config.ex:160: Mix.Config.__import__!/2
    (stdlib 3.14) erl_eval.erl:680: :erl_eval.do_apply/6
    
    
   Above error is resolved after install rust. When trying next step Im getting abve error.
   1. Clone the repository
2. `cd blockscout`
3. Install Mix dependencies, compile them and compile the application: `mix do deps.get, local.rebar --force, deps.compile, compile`
4. Generate db secret `mix phx.gen.secret`
5. Update `config.env` (add secret key and network specific details)
6. Export variables `source config.env`
7. Create and migrate database `mix do ecto.create, ecto.migrate`

Config details: 
export NETWORK="DOJIMA"
export PORT=4000
export COIN=DJA
export LOGO="/images/matic-top.png"
export LOGO_FOOTER="/images/matic-footer.svg"
export BLOCKSCOUT_VERSION="v3.3.2-beta"
export RELEASE_LINK="https://github.com/poanetwork/blockscout/releases/tag/v3.3.2-beta"
export LINK_TO_OTHER_EXPLORERS=false
export SECRET_KEY_BASE='JQ6xv7XxHPNjbpwRK8pKaOtBYCnla9fqtYGBMEwfzepfiojoIKaPlpsRT2z+DUoC'
export SUPPORTED_CHAINS='[ { "title": "Mainnet", "url": "https://explorer.matic.network" }, { "title": "Mumbai", "url": "https://mumbai-explorer.matic.today", "test_net?": true}, { "title": "Goerli", "url": "https://goerli.etherscan.io/", "other?": true }, { "title": "Ethereum", "url": "https://etherscan.io/", "other?": true } ]'

Can you please tell whats wrong in this?

**Comment by vbaranov** [comment]
You should set from which archive node you will fetch the date from blockchain into Blockscout database. In order to do that, you need to setup `ETHEREUM_JSONRPC_VARIANT`, `ETHEREUM_JSONRPC_HTTP_URL`, `ETHEREUM_JSONRPC_TRACE_URL` https://docs.blockscout.com/for-developers/information-and-settings/env-variables, for reference. I am closing the issue since the issue with `ex_keccak` is resolved.
