### ISSUE TITLE
Ethereum Classic: Unable to Verify Smart Contracts Deployed w/ Truffle

### ISSUE THREAD

**Issue by Mentors4EDU** [blockscout/blockscout#4447]
*Hi, so currently there is no way to automate verification for mass amounts of contracts that has been deployed via Truffle. This is a problem because when going about compiler version and other questions, these are hard to answer manually. Currently, I wonder if there is somebody who can manually just verify the smart contract addresses for me or if there is a way that I can somehow verify 15 contracts manually through a CLI or outside of the form. Support for Truffle verification or methods outside of the verification form would be helpful because not necessarily did everybody use the default remix or Solidity compiler for ETH Classic*

### Environment
* Elixir Version: 1.11.3
* Erlang Version: 23
* BlockScout Version: v3.5.0-beta

* User Agent: `Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:90.0) Gecko/20100101 Firefox/90.0`

### Steps to reproduce

*I can't configure bytecode or ABIs for massive amounts of contracts compiled w/ Truffle, even if selecting the right compiler version. The flattener tool also doesn't help.*

### Expected Behaviour

*Since there isn't a way to massively verify or automatically verify contracts deployed via Truffle for Ethereum Classic, I think maybe some sort of ABI or bytecode verification method should have been able to work.*

### Actual Behaviour

*Unfortunately, DAPPs and contracts I deploy via Truffle mostly remain unverified if it is for the Ethereum Classic Network.*

**Comment by vbaranov** [comment]
Blockscout ETC instance now supports verification through Standard Input JSON

<img width="449" alt="Screenshot 2021-12-30 at 15 56 10" src="https://user-images.githubusercontent.com/4341812/147753876-3f670ee2-0f14-48b5-996b-814c158bdab4.png">
