### ISSUE TITLE
Ethereum Classic: wrong address

### ISSUE THREAD

**Issue by Badibucci** [blockscout/blockscout#4448]
*Describe your issue here.*
I transferred my Ethereum Classic from my Coinbase wallet to my Atom wallet successfully.  Where I messed up was i tried to send it back to my Coinbase wallet and I did not realize the address was not mine that it came from.  I sent my Ethereum Classic to the wrong address.  I have the transaction details.  I was learning and I won't let that happen again. Is there an easy way to fix my transaction. Cancelling it or refunding it would be extremely appreciated.  Thank you,
Joseph Hornick

0x2859693f15058fccc03a234de42b4783ec0fe2f8359915e197a2f36580e0c59d

### Environment
* Elixir Version: 1.11.3
* Erlang Version: 23
* BlockScout Version: v3.5.0-beta

* User Agent: `Mozilla/5.0 (Android 10; Mobile; rv:90.0) Gecko/90.0 Firefox/90.0`

### Steps to reproduce

*Tell us how to reproduce this issue. If possible, push up a branch to your fork with a regression test we can run to reproduce locally.*

### Expected Behaviour

*Tell us what should happen.*

### Actual Behaviour

*Tell us what happens instead.*

**Comment by vbaranov** [comment]
Please ask Coinbase support
