### ISSUE TITLE
Ethereum Classic: <ETC never completed send through to coinbase)

### ISSUE THREAD

**Issue by jschaff7711** [blockscout/blockscout#4457]
ETC transaction sent over 9 hours ago is still incomplete although shown as a successful transaction. Here are the transaction details:

0xb8ffa236087bde0ac3c7cb8c30980320b0b1e0cbaf81592a099433448fb1bccf

Block Number
13223391
Block Confirmations
2,576
Nonce
0
TX Fee
0.0000231 ETC ($0.001128 USD)
Transaction Speed
<= 13.879 seconds

thank you for your help 

### Environment
* Elixir Version: 1.11.3
* Erlang Version: 23
* BlockScout Version: v3.5.0-beta

* User Agent: `Mozilla/5.0 (iPhone; CPU iPhone OS 14_6 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.1.1 Mobile/15E148 Safari/604.1`

### Steps to reproduce

*Tell us how to reproduce this issue. If possible, push up a branch to your fork with a regression test we can run to reproduce locally.*

### Expected Behaviour

*Tell us what should happen.*

### Actual Behaviour

*Tell us what happens instead.*

**Comment by vbaranov** [comment]
Please ask Coinbase support
