### ISSUE TITLE
POA: missing POA

### ISSUE THREAD

**Issue by ketaminekid423** [blockscout/blockscout#4463]
*Describe your issue here.*

### Environment
* Elixir Version: 1.11.4
* Erlang Version: 23
* BlockScout Version: v3.7.1-beta

* User Agent: `Mozilla/5.0 (Linux; Android 10) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.115 Mobile Safari/537.36`

### Steps to reproduce
Used metamask wallet loaded into trustwallet and dapp poa bridge UI to convert 975 poa to poa 20 and shows transaction success yet I am unable to see balance transferred in any wallet. Pls advise
### Expected Behaviour
Expected to see my pos20 token shown after poa bridge conversion bc trustwallet shows the poa 20 token, however I do not have the 975. Something balance which transferred
*Tell us what should happen.*
Tokens converted and deposited to wallet
### Actual Behaviour
No poa 20 tokens deposited only conversion from poa
*Tell us what happens instead.*
Tokens swapped but not deposited to my wallet addressq
![Screenshot_20210730-021710](https://user-images.githubusercontent.com/58034267/127609825-f27c01cd-75f4-4ae8-baf5-2cedbdd5a22e.jpg)

**Comment by vbaranov** [comment]
This issue doesn't relate to Blockscout. Please ask in https://forum.poa.network/
