### ISSUE TITLE
Mainnet: <Issue Title>

### ISSUE THREAD

**Issue by rosebud33** [blockscout/blockscout#4471]
*https://polygon-explorer-mainnet.chainstacklabs.com/tx/0x146a6f7897246362e47928bdeb1af07e6fee1fced4ad6578fe76e316d388300a/internal-transactions where did this transaction end up?? it was supposed to go to simple swap but apparently went elsewhere?? i need this matic returned to my original metamask wallet now! thank you*

### Environment
* Elixir Version: 1.11.3
* Erlang Version: 23
* BlockScout Version: v3.7.0-beta

* User Agent: `Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.107 Safari/537.36`

### Steps to reproduce

*Tell us how to reproduce this issue. If possible, push up a branch to your fork with a regression test we can run to reproduce locally.*

### Expected Behaviour

*Tell us what should happen.*

### Actual Behaviour

*Tell us what happens instead.*

**Comment by vbaranov** [comment]
There is no Matic/Polygon support here. Try to ask at their fork https://github.com/maticnetwork/blockscout.
