### ISSUE TITLE
Palm: <Issue Title> transfer errors

### ISSUE THREAD

**Issue by ryanleesm** [blockscout/blockscout#4478]
Dear palm team,

I sent Dai coin metamask to Upbit wallet

But upbit can’t check coin comes to upbit wallet.

Matamask mentioned already coin sent to upbit wallet.

but upbit community center answer there's no transfer. 
 

Can you check it for me?

 metamask address: 0xa397C9fA1a7d47Afe7457F6E0072bf790650fA3a

upbit address: 0x3ecd40a2fccc3187c80e81f8e072f21eed723302

https://explorer.palm.io//tx/0x56ddc6e2702fec1b1c1d49bfd70d3cc7de95a15aad1195b857dcadb0cddfc888

this is transfer information

please help me. it's all i have.... 
 

Sincerely,

**Comment by vbaranov** [comment]
Here is not a Palm team. Please ask them.
