### ISSUE TITLE
mix complie error

### ISSUE THREAD

**Issue by coldneverdie** [blockscout/blockscout#4479]
*Describe your issue here.*

### Environment

* Elixir & Erlang/OTP versions (`elixir -version`): 1.10
* Operating System: centos
* Blockscout Version/branch:  1.12 

### Steps to reproduce

when i run the mix command  

sudo  mix do deps.get, local.rebar --force, deps.compile, compile

it erros:

** (Mix) Could not compile dependency :quantile_estimator, "/root/.mix/rebar3 bare compile --paths="/home/centos/pkg/blockscout/_build/dev/lib/*/ebin"" command failed. You can recompile this dependency with "mix deps.compile quantile_estimator", update it with "mix deps.update quantile_estimator" or clean it with "mix deps.clean quantile_estimator"

**Comment by coldneverdie** [comment]
make: *** [lib/elixir/ebin/Elixir.Kernel.beam] 错误 2

**Comment by vbaranov** [comment]
Please check requirements for installation https://docs.blockscout.com/for-developers/information-and-settings/requirements
