### ISSUE TITLE
Sokol: the transcation records is missing when I was using hyperledger besu client 

### ISSUE THREAD

**Issue by eu09** [blockscout/blockscout#4487]
*Describe your issue here.*

### Environment
* Elixir Version: 1.11.0
* Erlang Version: 23
* BlockScout Version: 

* User Agent: `Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/94.0.4595.3 Safari/537.36`

### Steps to reproduce
I am using the docker composer to build up the application

version: '3'
services:
    db:
        image: postgres:latest
        environment:
            - POSTGRES_DB=postgres
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=enviu_dev
        networks: 
            - epirus1
        
    blockscout:
        image: surfingnerd/blockscout:v0.7
        depends_on:
            - "db"
        ports:
            - "4000:4000"
        tty: true

        environment:
            ETHEREUM_JSONRPC_HTTP_URL: http://10.0.0.240:8545
            ETHEREUM_JSONRPC_TRACE_URL: http://10.0.0.240:8545
            ETHEREUM_JSONRPC_WS_URL: ws://10.0.0.240:8546
            ETHEREUM_JSONRPC_VARIANT: besu
            HOST: 172.19.239.3
            DATABASE_URL: postgresql://postgres:enviu_dev@172.19.239.2:5432/explorer?ssl=false
        networks: 
            - epirus1

networks:
   epirus1:
    name: blockscout
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.19.239.0/24
        - 
My issue is when the application cant query the transcations record in the frontend

**Comment by vbaranov** [comment]
@eu09 could you attach an explaining your issue screenshot?
From which commit did you build Blockscout Docker image?

**Comment by vbaranov** [comment]
Closing due to no inactivity
