### ISSUE TITLE
`NETWORK_PATH` doesn't manage all pages paths.

### ISSUE THREAD

**Issue by vbaranov** [blockscout/blockscout#4501]
Configuration of Blockscout on a custom path is available only with a properly configured proxy server.

`NETWORK_PATH` should manage all pages paths, but it doesn't.

The original request from Discord:

> Sorry for the late reply regarding this. Here are my findings regarding the base path issue:
Changing NETWORK_PATH fixes some of the issues. However, whenever I try going to one of the pages, I get an error and it seems the javascript/ html is calling the wrong backend endpoint. 

> I added some log messages for current_path in here https://github.com/blockscout/blockscout/blob/master/apps/block_scout_web/lib/block_scout_web/controllers/block_controller.ex#L107 and the resulting code:
  defp handle_render(full_options, conn, _params) do
    render(conn, "index.html",
      current_path: current_path(conn),
      block_type: Keyword.get(full_options, :block_type, "Block")
    )

    Logger.warn("@@@@@@Path from current_path(conn) is: " <> current_path(conn))
    Logger.warn("@@@@@@Path from block_path(conn, :index) is: " <> block_path(conn, :index))

> I believe that the issue is due to using current_path(conn) . Here are the logs I added:
2021-08-05T01:28:32.670 application=block_scout_web request_id=af6a216c-3834-41e9-827f-c8cebff54813 [warn] @@@@@@Path from current_path(conn) is: //blocks
2021-08-05T01:28:32.670 application=block_scout_web request_id=af6a216c-3834-41e9-827f-c8cebff54813 [warn] @@@@@@Path from block_path(conn, :index) is: /explorer/blocks

> Substituting current_path(conn) with block_path(conn, :index) solves the issue.

> Also, it seems that wherever current_path(conn) is used in the code, the value of NETWORK_PATH is not prepended to the request. 

![SPOILER_unknown](https://user-images.githubusercontent.com/4341812/128842051-4da77ef3-cb70-4abd-8823-e1902ba1f02e.png)

>momo — 08/05/2021
Oh ok. I understand how it is working now. the frontend seems to be calling /blocks but gets redirected by haproxy to /xdai/mainnet/blocks. This is what I understood from the picture below. haproxy configuration is documented in the docs actually here https://docs.blockscout.com/for-developers/information-and-settings/haproxy-settings-for-blockscout.com

![SPOILER_unknown](https://user-images.githubusercontent.com/4341812/128841429-7fdbca58-e124-465e-9f3d-f5851e02f08e.png)

**Comment by mofhusseini** [comment]
@vbaranov Thanks for fixing this. I have tested this with latest master. Here are the issues I found:
1. `search` in
 https://github.com/blockscout/blockscout/blob/master/apps/block_scout_web/assets/js/pages/layout.js#L13
2. `autocomplete` in 
https://github.com/blockscout/blockscout/blob/master/apps/block_scout_web/assets/js/lib/autocomplete.js#L16
and everything under this if-else
https://github.com/blockscout/blockscout/blob/master/apps/block_scout_web/assets/js/lib/autocomplete.js#L125
3. `graphiql` in
https://github.com/blockscout/blockscout/blob/master/apps/block_scout_web/lib/block_scout_web/templates/layout/_topnav.html.eex#L118
4. `static path` in 
https://github.com/blockscout/blockscout/blob/master/apps/block_scout_web/lib/block_scout_web/templates/layout/app.html.eex#L9

Let me know if you need more info.

**Comment by vbaranov** [comment]
I think this has been resolved. @mofhusseini if you aware of else examples, please let us know.
