### ISSUE TITLE
Palm: public REST api explorer base url is localhost

### ISSUE THREAD

**Issue by LittleUmbrella** [blockscout/blockscout#4518]
The [public api explorer](https://explorer.palm.io/api-docs) shows the base url as https://localhost:4000/api:

![image](https://user-images.githubusercontent.com/764596/129599766-8a0ebd09-281f-4b31-a48e-170f01349a48.png)

This is valid for local development, but not for the public block explorer site.  

### Environment
(Not running locally.  Using the public explorer, as described above)

* User Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.131 Safari/537.36

### Steps to reproduce

none of the "Try it out" functionality works, because of the base url.  For example, use [the stats endpoint](https://blockscout.com/poa/core/api-docs#stats), the `coinsupply` action: 

![image](https://user-images.githubusercontent.com/764596/129603655-b4779f16-8a3b-4582-9028-bb35fecaa2a9.png)

### Expected Behaviour

a result following the model: 
```
Result {
result
integer
example: 101959776.3115
description: The total supply from DB minus burnt number in coin dimension.
}
```

### Actual Behaviour

result: `undefined` (see screenshot in "Steps to reproduce")

**Comment by vbaranov** [comment]
@LittleUmbrella in order to resolve host and path at API docs page you should set `BLOCKSCOUT_HOST` and `API_PATH` env variables. Posting here the list of available env variables https://docs.blockscout.com/for-developers/information-and-settings/env-variables.
