### ISSUE TITLE
Wrong token described in balances

### ISSUE THREAD

**Issue by enriavil1** [blockscout/blockscout#4530]
*Describe your issue here.*

### Environment

* Elixir & Erlang/OTP versions (`elixir -version`):
* Operating System:MacOs Monterrey
* Blockscout Version/branch:  latest

### Steps to reproduce

*Tell us how to reproduce this issue.  ❤️ if you can push up a branch to your fork with a regression test we can run to reproduce locally.*
run block scout with a custom net that uses a different token

### Expected behaviour
*Tell us what should happen.*
expected to see the card balances with my private erc20 token
### Actual behaviour

*Tell us what happens instead.*
It shows the balance of a user saying "0 Ethers" instead of my custom token

**Comment by vbaranov** [comment]
Balance card displays a balance of the native to the chain coin, not ERC-20 token. If account owns tokens, their balances are displayed in the dropdown

<img width="485" alt="Screenshot 2021-08-20 at 18 21 50" src="https://user-images.githubusercontent.com/4341812/130255979-4e15b963-6a46-4767-908b-31ddb5f77434.png">

**Comment by enriavil1** [comment]
Yeah I get that now but I am running a docker image and I thought this line should change what kind of coin is being shown.
` if [ "$COIN" != "" ]; then sed -i s/"POA"/"${COIN}"/g apps/block_scout_web/priv/gettext/en/LC_MESSAGES/default.po; fi`
