### ISSUE TITLE
Access calls for keywords expect the key to be an atom, got: "pending"

### ISSUE THREAD

**Issue by Eika4** [blockscout/blockscout#4543]
2021-08-23T14:42:15.020 application=indexer fetcher=pending_transaction [error] pending transaction fetcher task exited due to {%ArgumentError{message: "the Access calls for keywords expect the key to be an atom, got: \"pending\""}, [{Access, :get, 3, [file: 'lib/access.ex', line: 311]}, {EthereumJSONRPC.Geth, :fetch_pending_transactions, 1, [file: 'lib/ethereum_jsonrpc/geth.ex', line: 62]}, {Indexer.Fetcher.PendingTransaction, :task, 1, [file: 'lib/indexer/fetcher/pending_transaction.ex', line: 120]}, {Task.Supervised, :invoke_mfa, 2, [file: 'lib/task/supervised.ex', line: 90]}, {Task.Supervised, :reply, 5, [file: 'lib/task/supervised.ex', line: 35]}, {:proc_lib, :init_p_do_apply, 3, [file: 'proc_lib.erl', line: 226]}]}.  Rescheduling.
2021-08-23T14:42:16.230 fetcher=pending_transaction [error] Task #PID<0.16297.0> started from Indexer.Fetcher.PendingTransaction terminating
** (ArgumentError) the Access calls for keywords expect the key to be an atom, got: "pending"
    (elixir 1.11.2) lib/access.ex:311: Access.get/3
    (ethereum_jsonrpc 0.1.0) lib/ethereum_jsonrpc/geth.ex:62: EthereumJSONRPC.Geth.fetch_pending_transactions/1
    (indexer 0.1.0) lib/indexer/fetcher/pending_transaction.ex:120: Indexer.Fetcher.PendingTransaction.task/1
    (elixir 1.11.2) lib/task/supervised.ex:90: Task.Supervised.invoke_mfa/2
    (elixir 1.11.2) lib/task/supervised.ex:35: Task.Supervised.reply/5
    (stdlib 3.14.2.2) proc_lib.erl:226: :proc_lib.init_p_do_apply/3
Function: #Function<2.110683744/0 in Indexer.Fetcher.PendingTransaction.handle_info/2>
    Args: []

### Environment

* Elixir & Erlang/OTP versions (`elixir -version`):  esl-erlang 23.3.4.5 -- elixir 1.11.2
* Operating System: debian 10 (buster)
* Blockscout Version/branch: master branch, latest version -- 2bf1d0c8d3744349167c02cba7525a38d14f7bd6

### Steps to reproduce

We are using Blockscout on an EVM chain "Petrachor C++ Client" (https://github.com/petrachor/petrachor) using the geth variant on Blockscout. We have made a few modifications for compatibility, however RPC should be the same. 

Our latest version of Petrachor has added Websockets, so we are now connecting to Blockscout using ws://localhost:8546 and everything is working as expected, except for pending transactions. 

Here is an example for calling txpool_content on our Petrachor node:

curl --data '{"method":"txpool_content","params":[],"id":1,"jsonrpc":"2.0"}' -H "Content-Type: application/json" -X POST 127.0.0.1:8545
{"id":1,"jsonrpc":"2.0","result":[{"data":"0x0000000000000000000000000000000000000000000000000000000000000000","from":"0xbffa8d8dcfc91bf34b376d3e3a28fc8a7d7f632d","gas":"0x5208","gasPrice":"0x4a817c800","hash":"0xf9295db7a8d199a768280605b9bd3ed85fce86013a54107d62d72d7d532127a8","nonce":"0xb","senderPublic":"0x90d7e74b1d74d6c101677626b49ae4e7382a6cb1082a43ae127126f35e2603fe18dd4efcd2acfd2b1b8631adc3b4664007ae54ebffe551d0065674db2df51fb55e980bcc76ace7f7e7241839fc64bad35f264b1d083a6980019e01a9dbd8eaa0","sighash":"0xc39092705a793e2902cd719e18488d5d04af26b386da3f4b6e33bbc3aab41087","to":"0xd5c5632dac864ee6c9aed2029ba74d5a04c924f9","value":"0x39636a057665a180"},{"data":"0x0000000000000000000000000000000000000000000000000000000000000000","from":"0xb5ccdb5fccbb650c7c829601e8d7276a270fadbf","gas":"0xcf08","gasPrice":"0x4a817c800","hash":"0xd505696fa1ee0562aa3ae3734b688c1329d3ba5c1cbc4f65acfb938432cdd137","nonce":"0x70","senderPublic":"0xb19d489b8490aba00be4dce3542aa1adefa2ff6b3b068f3918b9cc385aabcf239742c38ea7b8ec66ca3254ab992d579a102a4c522c6f64a53602cbc0eae7bae37a2928b7b49274b70224ebcd0ac269fb866a7659a711ef52bd6be130c09a60a2","sighash":"0xfad2b3655d98a48066d83bd41c5dcb18ad58204b657176901f77e846700fffc4","to":"0xf1b12bb4e000e50ab5d7d07f9ed1d0166a11709d","value":"0x805f85e9ee4b1da40000"}]}

"the Access calls for keywords expect the key to be an atom, got: \"pending\""

**Comment by vbaranov** [comment]
The response of `txpool_content` should contain `pending` property as described in the Geth docs https://geth.ethereum.org/docs/rpc/ns-txpool

```
{
  pending: {
    0x...: {
    ...
    },
    0x...: {
    ...
    }
}
```

**Comment by vbaranov** [comment]
I suppose double quotes in the response are important.

```
curl -H "Content-type: application/json" -X POST --data '{"jsonrpc":"2.0","method":"txpool_content","params":[],"id":1}' ...
```

should return something like this:
```
{"jsonrpc":"2.0","id":1,"result":{"pending":{"0x000000007CbF74626927365e961cC697Ef8FED32":{"47":{"blockHash":null,"blockNumber":null,"from":"0x000...
```

**Comment by vbaranov** [comment]
I am closing this. Please re-open if still have questions.
