### ISSUE TITLE
Blockscout colours won't change with custom theme

### ISSUE THREAD

**Issue by enriavil1** [blockscout/blockscout#4548]
*Describe your issue here.*

### Environment

* Elixir & Erlang/OTP versions (`elixir -version`):
* Operating System: MacOs beta
* Blockscout Version/branch:  Main

### Steps to reproduce

*Tell us how to reproduce this issue.  ❤️ if you can push up a branch to your fork with a regression test we can run to reproduce locally.*

I made a docker image and a docker compose out of that docker image, but whenever I change the preset theme, it always goes for the blockscout default colours. 

### Expected behaviour

*Tell us what should happen.*
It is suppose to change the theme

### Actual behaviour

*Tell us what happens instead.*
Keeps blockscout default colours

**Comment by enriavil1** [comment]
I am wondering if it matter wether or not I am running on the chain I specify

**Comment by vbaranov** [comment]
Follow this guide https://docs.blockscout.com/for-developers/configuration-options/branding-configs

**Comment by enriavil1** [comment]
I am following it but even after changing it exactly to one of the preset themes it won't change colours

**Comment by enriavil1** [comment]
My question is that it says it is reflect on the production-${chain} branch. so if I am using the main branch and try to use xdai theme it won't work?
