### ISSUE TITLE
Mainnet: <Issue Title>

### ISSUE THREAD

**Issue by whefny21** [blockscout/blockscout#4549]
*i transfered matic token from binance to cex.io using unsupported matic network by cex.io*

Txid

0xa13fe40afd1c5efebdea1a1c8fdfbaae6bcd52af53837204057036e3d2d5bf46

### Environment
* Elixir Version: 1.11.3
* Erlang Version: 23
* BlockScout Version: v3.7.0-beta

* User Agent: `Mozilla/5.0 (iPhone; CPU iPhone OS 14_7_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Mobile/15E148`

### Steps to reproduce

*Tell us how to reproduce this issue. If possible, push up a branch to your fork with a regression test we can run to reproduce locally.*

### Expected Behaviour

*Tell us what should happen.*

### Actual Behaviour

*Tell us what happens instead.*

**Comment by vbaranov** [comment]
There is no Matic/Polygon support here. Try to ask at their fork https://github.com/maticnetwork/blockscout.
