### ISSUE TITLE
[Crit] Data is not passed to MetaMask when executing contract method with certain values

### ISSUE THREAD

**Issue by ulyanas** [blockscout/blockscout#4562]
Example contract: https://blockscout.com/xdai/testnet/address/0xdad3840ce8320C4718FaCBdee35aE25595B2E27F/write-proxy
Tab: Write Proxy
Method: depositEth

1. Connect to testnet in MetaMask
2. Goto Contract
3. Input maxSubmissionCost - 1000000 and value - “1000000000000000000”
4. Metamask does not show any data passed 
![image](https://user-images.githubusercontent.com/6618204/130963187-84e9d730-d29d-42b4-9f36-e42c7747b798.png)
<img width="472" alt="Screenshot 2021-08-26 at 15 32 01" src="https://user-images.githubusercontent.com/6618204/130963206-bf09b406-c3d6-4962-a9a0-c87d6fc1f8d3.png">

**Comment by nikitosing** [comment]
This issue is a combination of #4560  and #4561. I think this issue wouldn't be actual when issues #4560 and #4561 will be fixed
