### ISSUE TITLE
"Failed to decode input data" error for a transaction with the use of a verified proxied contract

### ISSUE THREAD

**Issue by ulyanas** [blockscout/blockscout#4570]
Case: 

1. [Transaction](https://blockscout.com/xdai/mainnet/tx/0xc250300206cada09939eec16c89ae2c69081e72305b45dba496fca670aa991e2)  is processed with a call of contract [A](https://blockscout.com/xdai/mainnet/address/0x21AB1Fc6b116dD577409E47b8a7Af87A72b892a2/transactions ) 
2. Contract A is a proxy for contract [B](https://blockscout.com/xdai/mainnet/address/0x524E5181b888E1c2eF9582682381FDD674b4CACc/transactions ) 
3. Transaction is using ABI of contract [C](https://blockscout.com/xdai/mainnet/address/0xa6439Ca0FCbA1d0F80df0bE6A17220feD9c9038a/transactions) 
4. Contract C is verified, however Blockscout is not able to show transaction input: Failed to decode input data. 
5. At the same time we can see the method name in the transaction info
![image](https://user-images.githubusercontent.com/6618204/131022867-b1d2bc01-d43e-499c-892e-f479172f7079.png)
![image](https://user-images.githubusercontent.com/6618204/131022883-15227861-f3c5-4f38-bfc9-344f3e9ae5f5.png)

**Comment by vbaranov** [comment]
How is it possible to get the relation between contracts B and C? `updateWhitelistConsumers` is an external function in the interface of contract B and external functions are not contained in the ABI. cc @akolotov

**Comment by akolotov** [comment]
Do you think it will not confuse if BS makes an assumption about ABI of the method by using entire ABI list of the verified contracts rather than ABI of the particular implementation? From my perspective it will not contradict as BS already does this assumption when displays the method name on the transaction tab.

**Comment by akolotov** [comment]
But BS already recognizes the method:
![image](https://user-images.githubusercontent.com/20793260/133467137-522ecd34-e744-4700-bd4e-e844cf71b32e.png)
May it try to make similar assumption to decode the input?

**Comment by sirpy** [comment]
I think we are having similar issues with some of the methods
