### ISSUE TITLE
Contract name is not shown for a copy of a verified contract

### ISSUE THREAD

**Issue by ulyanas** [blockscout/blockscout#4571]
Contract name is not shown in an internal [transaction](https://blockscout.com/xdai/mainnet/tx/0xc250300206cada09939eec16c89ae2c69081e72305b45dba496fca670aa991e2) for a contract that has a verified clone. Consider showing contract name for such transactions.

**Comment by ulyanas** [comment]
@ulyanas  Need to review with new Contract address pages

**Comment by vbaranov** [comment]
@nikitosing is this already resolved?

**Comment by nikitosing** [comment]
@vbaranov Yes, I suppose it was resolved by #5268

**Comment by nikitosing** [comment]
@vbaranov No, somebody verified these contracts
