### ISSUE TITLE
Contract implementation is not shown for a specific contract 

### ISSUE THREAD

**Issue by ulyanas** [blockscout/blockscout#4572]
1. [Contract](https://blockscout.com/xdai/mainnet/address/0x1d0cb6eb6bF77f1Fba5dC2cF018A6c3bC9CBFA47/contracts) 
2. Implementation address is incorrect and redirects to 404

**Comment by enriavil1** [comment]
What is suppose to be the address?

**Comment by vbaranov** [comment]
We should support retrieval of implementation from `proxy.beacon` slot according to eip-1967 too
>Beacon contract address
Storage slot 0xa3f0ad74e5423aebfd80d3ef4346578335a9a72aeaee59ff6cb3582b35133d50 (obtained as bytes32(uint256(keccak256('eip1967.proxy.beacon')) - 1)).
