### ISSUE TITLE
Arbitum on xDai: Launch Blockscout for Arbitrum Rollup on xDai Chain

### ISSUE THREAD

**Issue by ulyanas** [blockscout/blockscout#4573]
[Arbitrum Optimistic Rollup](https://arbitrum.io/) technology is a L2 solution by [Offchain Labs](https://offchainlabs.com/) which just recently launched. 
Fork of Arbirum was deployed on xDai chain and we should see if Blockscout can be smoothly deployed for the rollup. 
https://arbitrum.xdaichain.com/
wss://arbitrum.xdaichain.com/wss

Any adaptation requests will be created as separate issues within [this project](https://github.com/blockscout/blockscout/projects/12).

**Comment by vbaranov** [comment]
https://blockscout.com/xdai/aox/
