### ISSUE TITLE
Crashing on syncing

### ISSUE THREAD

**Issue by rolik2001** [blockscout/blockscout#4577]
I was trying to start this explorer for BSC, during catching transaction sometimes I receive this message, for new transaction, sometimes is everything good, I tried also to start on my fork of BSc, the same stuff. As a result all transactions stucks in pending.

### Environment

* Elixir & Erlang/OTP versions (`elixir -version`): 23
* Operating System: ubuntu 
* Blockscout Version/branch: master last commit at this moment, tried different release 

### Expected behaviour

Working and syncing blocks

### Actual behaviour

Receiving this red message 

2021-08-29T00:15:38.319 application=explorer fetcher=block_realtime block_number=8361 import_id=68004 transaction_id=53827 [error] Could not insert all of chunk into Elixir.Explorer.Chain.Log using options because of error.

Chunk Size: 2
Chunk:

[%{address_hash: %Explorer.Chain.Hash{byte_count: 20, bytes: <<56, 23, 226, 71, 2, 59, 79, 72, 147, 82, 117, 131, 151, 4, 11, 31, 211, 59, 48, 10>>}, block_hash: %Explorer.Chain.Hash{byte_count: 32, bytes: <<0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0>>}, block_number: 8361, data: %Explorer.Chain.Data{bytes: <<0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 7, 108, 218, 95, 160, 132, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 50>>}, first_topic: "0x040a7993aa0066bc5a359c1703633f73ee4b02e23e5b71159cbcff6c183424ca", index: 0, inserted_at: ~U[2021-08-28 22:15:38.275017Z], transaction_hash: %Explorer.Chain.Hash{byte_count: 32, bytes: <<80, 157, 104, 165, 93, 186, 74, 164, 180, 28, 51, 160, 98, 138, 173, 43, 65, 244, 204, 116, 140, 67, 25, 168, 144, 222, 74, 225, 88, 253, 181, 7>>}, updated_at: ~U[2021-08-28 22:15:38.275017Z]}, %{address_hash: %Explorer.Chain.Hash{byte_count: 20, bytes: <<0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 16, 0>>}, block_hash: %Explorer.Chain.Hash{byte_count: 32, bytes: <<0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0>>}, block_number: 8361, data: %Explorer.Chain.Data{bytes: <<0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 170, 46, 226, 219, 230, 199, 111, 217, 225, 82, 34, 17, 123, 129, 27, 179, 208, 192, 100, 90, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 7, 108, 218, 95, 160, 132, 0>>}, first_topic: "0xe1fffcc4923d04b559f4d29a8bfc6cda04eb5b0d3c460751c2402c5c5cc9109c", index: 1, inserted_at: ~U[2021-08-28 22:15:38.275017Z], transaction_hash: %Explorer.Chain.Hash{byte_count: 32, bytes: <<80, 157, 104, 165, 93, 186, 74, 164, 180, 28, 51, 160, 98, 138, 173, 43, 65, 244, 204, 116, 140, 67, 25, 168, 144, 222, 74, 225, 88, 253, 181, 7>>}, updated_at: ~U[2021-08-28 22:15:38.275017Z]}]

Options:

[conflict_target: [:transaction_hash, :index, :block_hash], on_conflict: #Ecto.Query<from l0 in Explorer.Chain.Log, where: fragment("(EXCLUDED.address_hash, EXCLUDED.data, EXCLUDED.first_topic, EXCLUDED.second_topic, EXCLUDED.third_topic, EXCLUDED.fourth_topic, EXCLUDED.type) IS DISTINCT FROM (?, ?, ?, ?, ?, ?, ?)", l0.address_hash, l0.data, l0.first_topic, l0.second_topic, l0.third_topic, l0.fourth_topic, l0.type), update: [set: [address_hash: fragment("EXCLUDED.address_hash"), data: fragment("EXCLUDED.data"), first_topic: fragment("EXCLUDED.first_topic"), second_topic: fragment("EXCLUDED.second_topic"), third_topic: fragment("EXCLUDED.third_topic"), fourth_topic: fragment("EXCLUDED.fourth_topic"), type: fragment("EXCLUDED.type"), inserted_at: fragment("LEAST(?, EXCLUDED.inserted_at)", l0.inserted_at), updated_at: fragment("GREATEST(?, EXCLUDED.updated_at)", l0.updated_at)]]>, returning: true, timeout: 60000, timestamps: %{inserted_at: ~U[2021-08-28 22:15:38.275017Z], updated_at: ~U[2021-08-28 22:15:38.275017Z]}]

Exception:

** (Postgrex.Error) ERROR 23503 (foreign_key_violation) insert or update on table "logs" violates foreign key constraint "logs_block_hash_fkey"

    table: logs
    constraint: logs_block_hash_fkey

Key (block_hash)=(\x0000000000000000000000000000000000000000000000000000000000000000) is not present in table "blocks".
    (ecto_sql 3.5.3) lib/ecto/adapters/sql.ex:751: Ecto.Adapters.SQL.raise_sql_call_error/1
    (ecto_sql 3.5.3) lib/ecto/adapters/sql.ex:660: Ecto.Adapters.SQL.insert_all/8
    (ecto 3.5.5) lib/ecto/repo/schema.ex:54: Ecto.Repo.Schema.do_insert_all/6
    (explorer 0.0.1) lib/explorer/repo.ex:45: anonymous fn/5 in Explorer.Repo.safe_insert_all/3
    (elixir 1.11.1) lib/enum.ex:2181: Enum."-reduce/3-lists^foldl/2-0-"/3
    (explorer 0.0.1) lib/explorer/chain/import.ex:299: Explorer.Chain.Import.insert_changes_list/3
    (explorer 0.0.1) lib/explorer/chain/import/runner/logs.ex:65: Explorer.Chain.Import.Runner.Logs.insert/3
    (ecto 3.5.5) lib/ecto/multi.ex:646: Ecto.Multi.apply_operation/5
    (elixir 1.11.1) lib/enum.ex:2181: Enum."-reduce/3-lists^foldl/2-0-"/3
    (ecto 3.5.5) lib/ecto/multi.ex:630: anonymous fn/5 in Ecto.Multi.apply_operations/5
    (ecto_sql 3.5.3) lib/ecto/adapters/sql.ex:1027: anonymous fn/3 in Ecto.Adapters.SQL.checkout_or_transaction/4
    (db_connection 2.3.1) lib/db_connection.ex:1444: DBConnection.run_transaction/4
    (ecto 3.5.5) lib/ecto/repo/transaction.ex:20: Ecto.Repo.Transaction.transaction/4
    (stdlib 3.14) timer.erl:197: :timer.tc/3
    (explorer 0.0.1) lib/explorer/repo.ex:21: anonymous fn/2 in Explorer.Repo.logged_transaction/2
    (explorer 0.0.1) lib/explorer/logger.ex:14: Explorer.Logger.metadata/2
    (explorer 0.0.1) lib/explorer/chain/import.ex:330: anonymous fn/3 in Explorer.Chain.Import.import_transactions/2
    (elixir 1.11.1) lib/enum.ex:3764: Enumerable.List.reduce/3
    (elixir 1.11.1) lib/enum.ex:2231: Enum.reduce_while/3
    (explorer 0.0.1) lib/explorer/chain/import.ex:329: Explorer.Chain.Import.import_transactions/2

2021-08-29T00:15:38.321 [error] Task #PID<0.7885.0> started from Indexer.Block.Realtime.Fetcher terminating
** (Postgrex.Error) ERROR 23503 (foreign_key_violation) insert or update on table "logs" violates foreign key constraint "logs_block_hash_fkey"

    table: logs
    constraint: logs_block_hash_fkey

Key (block_hash)=(\x0000000000000000000000000000000000000000000000000000000000000000) is not present in table "blocks".
    (ecto_sql 3.5.3) lib/ecto/adapters/sql.ex:751: Ecto.Adapters.SQL.raise_sql_call_error/1
    (ecto_sql 3.5.3) lib/ecto/adapters/sql.ex:660: Ecto.Adapters.SQL.insert_all/8
    (ecto 3.5.5) lib/ecto/repo/schema.ex:54: Ecto.Repo.Schema.do_insert_all/6
    (explorer 0.0.1) lib/explorer/repo.ex:45: anonymous fn/5 in Explorer.Repo.safe_insert_all/3
    (elixir 1.11.1) lib/enum.ex:2181: Enum."-reduce/3-lists^foldl/2-0-"/3
    (explorer 0.0.1) lib/explorer/chain/import.ex:299: Explorer.Chain.Import.insert_changes_list/3
    (explorer 0.0.1) lib/explorer/chain/import/runner/logs.ex:65: Explorer.Chain.Import.Runner.Logs.insert/3
    (ecto 3.5.5) lib/ecto/multi.ex:646: Ecto.Multi.apply_operation/5
    (elixir 1.11.1) lib/enum.ex:2181: Enum."-reduce/3-lists^foldl/2-0-"/3
    (ecto 3.5.5) lib/ecto/multi.ex:630: anonymous fn/5 in Ecto.Multi.apply_operations/5
    (ecto_sql 3.5.3) lib/ecto/adapters/sql.ex:1027: anonymous fn/3 in Ecto.Adapters.SQL.checkout_or_transaction/4
    (db_connection 2.3.1) lib/db_connection.ex:1444: DBConnection.run_transaction/4
    (ecto 3.5.5) lib/ecto/repo/transaction.ex:20: Ecto.Repo.Transaction.transaction/4
    (stdlib 3.14) timer.erl:197: :timer.tc/3
    (explorer 0.0.1) lib/explorer/repo.ex:21: anonymous fn/2 in Explorer.Repo.logged_transaction/2
    (explorer 0.0.1) lib/explorer/logger.ex:14: Explorer.Logger.metadata/2
    (explorer 0.0.1) lib/explorer/chain/import.ex:330: anonymous fn/3 in Explorer.Chain.Import.import_transactions/2
    (elixir 1.11.1) lib/enum.ex:3764: Enumerable.List.reduce/3
    (elixir 1.11.1) lib/enum.ex:2231: Enum.reduce_while/3
    (explorer 0.0.1) lib/explorer/chain/import.ex:329: Explorer.Chain.Import.import_transactions/2
Function: &Indexer.Block.Realtime.Fetcher.fetch_and_import_block/3
    Args: [8361, %Indexer.Block.Fetcher{broadcast: :realtime, callback_module: Indexer.Block.Realtime.Fetcher, json_rpc_named_arguments: [transport: EthereumJSONRPC.HTTP, transport_options: [http: EthereumJSONRPC.HTTP.HTTPoison, url: "http://localhost:8545", http_options: [recv_timeout: 60000, timeout: 60000, hackney: [pool: :ethereum_jsonrpc]]], variant: EthereumJSONRPC.Geth], receipts_batch_size: 250, receipts_concurrency: 10}, false]

Key (block_hash)=(\x0000000000000000000000000000000000000000000000000000000000000000) is not present in table "blocks".

**Comment by vbaranov** [comment]
@rolik2001 what type of archive node do you use (Ethereum client & version)? Do you observe Genesis block in the `blocks` table:
```
SELECT * FROM blocks
WHERE NUMBER=0;
```

**Comment by rolik2001** [comment]
![](https://user-images.githubusercontent.com/20404966/131406106-8c95e83f-5507-485c-8cfd-ac223307ca4d.jpg)
This error appears only when explorer is connecting to network with a few validator, if one everything is good. What is more error appears for transactions with nonce 7,8 but 9 it shows and it comes for different nonce with different addresses. Also it shows only that transactions that are verified by validator to which explorer is connected, if other sign block it shows error and whole block is empty when transactions stuck in pending. I work with full archive node geth version v.1.0.7

**Comment by vbaranov** [comment]
> geth version v.1.0.7
This version is pretty old. Not sure Blockscout has compatibility with it. What is the reason to work with such an ancient release? Could you try with Geth 1.10.8?

**Comment by rolik2001** [comment]
I tried with a different version,1.0.7 is in BSC version (pretty new) . Moreover, it works with one validator. As, I can see the error is that block_hash is zero bytes  but I don't know why. 
![image](https://user-images.githubusercontent.com/20404966/131735892-0b6bcba5-afb9-44e4-8bd7-dd0e20c1041a.png)

**Comment by rolik2001** [comment]
I changed version to the last and still have this error.

**Comment by rolik2001** [comment]
So I have found the part where it crashes but I still can't find a reason why 
![image](https://user-images.githubusercontent.com/20404966/132142601-8ced6f84-23ca-4523-9f4b-1f1283c6f798.png)
![image](https://user-images.githubusercontent.com/20404966/132142615-40aeb9c8-3e79-4e95-bbd4-4e9e57106d7f.png)
`
failure while trying to log malformed data: [[[] | "\e[31m"], [["2021", 45, [48, "9"], 45, [48, "6"]], "T", [[48, "0"], 58, [48, "1"], 58, "16", 46, "286"], " ", ["application", 61, "explorer", 32, "fetcher", 61, "block_catchup", 32, "first_block_number", 61, "422", 32, "last_block_number", 61, "422", 32, "import_id", 61, "11907", 32, "transaction_id", 61, "28162", 32], "[", "error", "] ", [%{address_hash: %Explorer.Chain.Hash{byte_count: 20, bytes: <<56, 23, 226, 71, 2, 59, 79, 72, 147, 82, 117, 131, 151, 4, 11, 31, 211, 59, 48, 10>>}, block_hash: %Explorer.Chain.Hash{byte_count: 32, bytes: <<0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0>>}, block_number: 422, data: %Explorer.Chain.Data{bytes: <<0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 190, 254, 111, 103, 32, 0, 0, ...>>}, first_topic: "0x040a7993aa0066bc5a359c1703633f73ee4b02e23e5b71159cbcff6c183424ca", index: 0, inserted_at: ~U[2021-09-05 22:01:16.232305Z], transaction_hash: %Explorer.Chain.Hash{byte_count: 32, bytes: <<42, 170, 196, 181, 148, 152, 56, 111, 113, 48, 93, 103, 224, 40, 211, 198, 200, 84, 182, 55, 190, 58, 200, 88, 31, 169, 64, 195, ...>>}, updated_at: ~U[2021-09-05 22:01:16.232305Z]}, %{address_hash: %Explorer.Chain.Hash{byte_count: 20, bytes: <<0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 16, 0>>}, block_hash: %Explorer.Chain.Hash{byte_count: 32, bytes: <<0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0>>}, block_number: 422, data: %Explorer.Chain.Data{bytes: <<0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 170, 46, 226, 219, 230, 199, 111, 217, 225, 82, 34, 17, 123, 129, 27, 179, 208, 192, 100, 90, ...>>}, first_topic: "0xe1fffcc4923d04b559f4d29a8bfc6cda04eb5b0d3c460751c2402c5c5cc9109c", index: 1, inserted_at: ~U[2021-09-05 22:01:16.232305Z], transaction_hash: %Explorer.Chain.Hash{byte_count: 32, bytes: <<42, 170, 196, 181, 148, 152, 56, 111, 113, 48, 93, 103, 224, 40, 211, 198, 200, 84, 182, 55, 190, 58, 200, 88, 31, 169, 64, ...>>}, updated_at: ~U[2021-09-05 22:01:16.232305Z]}], "\n"] | "\e[0m"]

`

**Comment by rolik2001** [comment]
** (ArgumentError) argument error
    (stdlib 3.14) :unicode.characters_to_binary([["2021", 45, [48, "9"], 45, [48, "6"]], "T", [[48, "0"], 58, [48, "1"], 58, "16", 46, "286"], " ", ["application", 61, "explorer", 32, "fetcher", 61, "block_catchup", 32, "first_block_number", 61, "422", 32, "last_block_number", 61, "422", 32, "import_id", 61, "11907", 32, "transaction_id", 61, "28162", 32], "[", "error", "] ", [%{address_hash: %Explorer.Chain.Hash{byte_count: 20, bytes: <<56, 23, 226, 71, 2, 59, 79, 72, 147, 82, 117, 131, 151, 4, 11, 31, 211, 59, 48, 10>>}, block_hash: %Explorer.Chain.Hash{byte_count: 32, bytes: <<0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0>>}, block_number: 422, data: %Explorer.Chain.Data{bytes: <<0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 190, 254, 111, 103, 32, 0, 0, 0, 0, ...>>}, first_topic: "0x040a7993aa0066bc5a359c1703633f73ee4b02e23e5b71159cbcff6c183424ca", index: 0, inserted_at: ~U[2021-09-05 22:01:16.232305Z], transaction_hash: %Explorer.Chain.Hash{byte_count: 32, bytes: <<42, 170, 196, 181, 148, 152, 56, 111, 113, 48, 93, 103, 224, 40, 211, 198, 200, 84, 182, 55, 190, 58, 200, 88, 31, 169, 64, 195, 214, 174, ...>>}, updated_at: ~U[2021-09-05 22:01:16.232305Z]}, %{address_hash: %Explorer.Chain.Hash{byte_count: 20, bytes: <<0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 16, 0>>}, block_hash: %Explorer.Chain.Hash{byte_count: 32, bytes: <<0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0>>}, block_number: 422, data: %Explorer.Chain.Data{bytes: <<0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 170, 46, 226, 219, 230, 199, 111, 217, 225, 82, 34, 17, 123, 129, 27, 179, 208, 192, 100, 90, 0, 0, ...>>}, first_topic: "0xe1fffcc4923d04b559f4d29a8bfc6cda04eb5b0d3c460751c2402c5c5cc9109c", index: 1, inserted_at: ~U[2021-09-05 22:01:16.232305Z], transaction_hash: %Explorer.Chain.Hash{byte_count: 32, bytes: <<42, 170, 196, 181, 148, 152, 56, 111, 113, 48, 93, 103, 224, 40, 211, 198, 200, 84, 182, 55, 190, 58, 200, 88, 31, 169, 64, 195, 214, ...>>}, updated_at: ~U[2021-09-05 22:01:16.232305Z]}], "\n"], :unicode, :unicode)
    (kernel 7.2) file_io_server.erl:437: :file_io_server.put_chars/3
    (kernel 7.2) file_io_server.erl:198: :file_io_server.server_loop/1
2021-09-06T00:01:16.287 [error] Process #PID<0.2278.0> raised an exception

**Comment by rolik2001** [comment]
@vbaranov

**Comment by rolik2001** [comment]
Fixed

**Comment by bretep** [comment]
@rolik2001 what was the fix?

**Comment by lamtanphiho** [comment]
> I was trying to start this explorer for BSC, during catching transaction sometimes I receive this message, for new transaction, sometimes is everything good, I tried also to start on my fork of BSc, the same stuff. As a result all transactions stucks in pending.
> 
> ### Environment
> * Elixir & Erlang/OTP versions (`elixir -version`): 23
> * Operating System: ubuntu
> * Blockscout Version/branch: master last commit at this moment, tried different release
> 
> ### Expected behaviour
> Working and syncing blocks
> 
> ### Actual behaviour
> Receiving this red message
> 
> 2021-08-29T00:15:38.319 application=explorer fetcher=block_realtime block_number=8361 import_id=68004 transaction_id=53827 [error] Could not insert all of chunk into Elixir.Explorer.Chain.Log using options because of error.
> 
> Chunk Size: 2 Chunk:
> 
> [%{address_hash: %Explorer.Chain.Hash{byte_count: 20, bytes: <<56, 23, 226, 71, 2, 59, 79, 72, 147, 82, 117, 131, 151, 4, 11, 31, 211, 59, 48, 10>>}, block_hash: %Explorer.Chain.Hash{byte_count: 32, bytes: <<0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0>>}, block_number: 8361, data: %Explorer.Chain.Data{bytes: <<0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 7, 108, 218, 95, 160, 132, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 50>>}, first_topic: "0x040a7993aa0066bc5a359c1703633f73ee4b02e23e5b71159cbcff6c183424ca", index: 0, inserted_at: ~U[2021-08-28 22:15:38.275017Z], transaction_hash: %Explorer.Chain.Hash{byte_count: 32, bytes: <<80, 157, 104, 165, 93, 186, 74, 164, 180, 28, 51, 160, 98, 138, 173, 43, 65, 244, 204, 116, 140, 67, 25, 168, 144, 222, 74, 225, 88, 253, 181, 7>>}, updated_at: ~U[2021-08-28 22:15:38.275017Z]}, %{address_hash: %Explorer.Chain.Hash{byte_count: 20, bytes: <<0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 16, 0>>}, block_hash: %Explorer.Chain.Hash{byte_count: 32, bytes: <<0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0>>}, block_number: 8361, data: %Explorer.Chain.Data{bytes: <<0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 170, 46, 226, 219, 230, 199, 111, 217, 225, 82, 34, 17, 123, 129, 27, 179, 208, 192, 100, 90, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 7, 108, 218, 95, 160, 132, 0>>}, first_topic: "0xe1fffcc4923d04b559f4d29a8bfc6cda04eb5b0d3c460751c2402c5c5cc9109c", index: 1, inserted_at: ~U[2021-08-28 22:15:38.275017Z], transaction_hash: %Explorer.Chain.Hash{byte_count: 32, bytes: <<80, 157, 104, 165, 93, 186, 74, 164, 180, 28, 51, 160, 98, 138, 173, 43, 65, 244, 204, 116, 140, 67, 25, 168, 144, 222, 74, 225, 88, 253, 181, 7>>}, updated_at: ~U[2021-08-28 22:15:38.275017Z]}]
> 
> Options:
> 
> [conflict_target: [:transaction_hash, :index, :block_hash], on_conflict: #Ecto.Query<from l0 in Explorer.Chain.Log, where: fragment("(EXCLUDED.address_hash, EXCLUDED.data, EXCLUDED.first_topic, EXCLUDED.second_topic, EXCLUDED.third_topic, EXCLUDED.fourth_topic, EXCLUDED.type) IS DISTINCT FROM (?, ?, ?, ?, ?, ?, ?)", l0.address_hash, l0.data, l0.first_topic, l0.second_topic, l0.third_topic, l0.fourth_topic, l0.type), update: [set: [address_hash: fragment("EXCLUDED.address_hash"), data: fragment("EXCLUDED.data"), first_topic: fragment("EXCLUDED.first_topic"), second_topic: fragment("EXCLUDED.second_topic"), third_topic: fragment("EXCLUDED.third_topic"), fourth_topic: fragment("EXCLUDED.fourth_topic"), type: fragment("EXCLUDED.type"), inserted_at: fragment("LEAST(?, EXCLUDED.inserted_at)", l0.inserted_at), updated_at: fragment("GREATEST(?, EXCLUDED.updated_at)", l0.updated_at)]]>, returning: true, timeout: 60000, timestamps: %{inserted_at: ~U[2021-08-28 22:15:38.275017Z], updated_at: ~U[2021-08-28 22:15:38.275017Z]}]
> 
> Exception:
> 
> ** (Postgrex.Error) ERROR 23503 (foreign_key_violation) insert or update on table "logs" violates foreign key constraint "logs_block_hash_fkey"
> 
> ```
> table: logs
> constraint: logs_block_hash_fkey
> ```
> 
> Key (block_hash)=(\x0000000000000000000000000000000000000000000000000000000000000000) is not present in table "blocks". (ecto_sql 3.5.3) lib/ecto/adapters/sql.ex:751: Ecto.Adapters.SQL.raise_sql_call_error/1 (ecto_sql 3.5.3) lib/ecto/adapters/sql.ex:660: Ecto.Adapters.SQL.insert_all/8 (ecto 3.5.5) lib/ecto/repo/schema.ex:54: Ecto.Repo.Schema.do_insert_all/6 (explorer 0.0.1) lib/explorer/repo.ex:45: anonymous fn/5 in Explorer.Repo.safe_insert_all/3 (elixir 1.11.1) lib/enum.ex:2181: Enum."-reduce/3-lists^foldl/2-0-"/3 (explorer 0.0.1) lib/explorer/chain/import.ex:299: Explorer.Chain.Import.insert_changes_list/3 (explorer 0.0.1) lib/explorer/chain/import/runner/logs.ex:65: Explorer.Chain.Import.Runner.Logs.insert/3 (ecto 3.5.5) lib/ecto/multi.ex:646: Ecto.Multi.apply_operation/5 (elixir 1.11.1) lib/enum.ex:2181: Enum."-reduce/3-lists^foldl/2-0-"/3 (ecto 3.5.5) lib/ecto/multi.ex:630: anonymous fn/5 in Ecto.Multi.apply_operations/5 (ecto_sql 3.5.3) lib/ecto/adapters/sql.ex:1027: anonymous fn/3 in Ecto.Adapters.SQL.checkout_or_transaction/4 (db_connection 2.3.1) lib/db_connection.ex:1444: DBConnection.run_transaction/4 (ecto 3.5.5) lib/ecto/repo/transaction.ex:20: Ecto.Repo.Transaction.transaction/4 (stdlib 3.14) timer.erl:197: :timer.tc/3 (explorer 0.0.1) lib/explorer/repo.ex:21: anonymous fn/2 in Explorer.Repo.logged_transaction/2 (explorer 0.0.1) lib/explorer/logger.ex:14: Explorer.Logger.metadata/2 (explorer 0.0.1) lib/explorer/chain/import.ex:330: anonymous fn/3 in Explorer.Chain.Import.import_transactions/2 (elixir 1.11.1) lib/enum.ex:3764: Enumerable.List.reduce/3 (elixir 1.11.1) lib/enum.ex:2231: Enum.reduce_while/3 (explorer 0.0.1) lib/explorer/chain/import.ex:329: Explorer.Chain.Import.import_transactions/2
> 
> 2021-08-29T00:15:38.321 [error] Task #PID<0.7885.0> started from Indexer.Block.Realtime.Fetcher terminating ** (Postgrex.Error) ERROR 23503 (foreign_key_violation) insert or update on table "logs" violates foreign key constraint "logs_block_hash_fkey"
> 
> ```
> table: logs
> constraint: logs_block_hash_fkey
> ```
> 
> Key (block_hash)=(\x0000000000000000000000000000000000000000000000000000000000000000) is not present in table "blocks". (ecto_sql 3.5.3) lib/ecto/adapters/sql.ex:751: Ecto.Adapters.SQL.raise_sql_call_error/1 (ecto_sql 3.5.3) lib/ecto/adapters/sql.ex:660: Ecto.Adapters.SQL.insert_all/8 (ecto 3.5.5) lib/ecto/repo/schema.ex:54: Ecto.Repo.Schema.do_insert_all/6 (explorer 0.0.1) lib/explorer/repo.ex:45: anonymous fn/5 in Explorer.Repo.safe_insert_all/3 (elixir 1.11.1) lib/enum.ex:2181: Enum."-reduce/3-lists^foldl/2-0-"/3 (explorer 0.0.1) lib/explorer/chain/import.ex:299: Explorer.Chain.Import.insert_changes_list/3 (explorer 0.0.1) lib/explorer/chain/import/runner/logs.ex:65: Explorer.Chain.Import.Runner.Logs.insert/3 (ecto 3.5.5) lib/ecto/multi.ex:646: Ecto.Multi.apply_operation/5 (elixir 1.11.1) lib/enum.ex:2181: Enum."-reduce/3-lists^foldl/2-0-"/3 (ecto 3.5.5) lib/ecto/multi.ex:630: anonymous fn/5 in Ecto.Multi.apply_operations/5 (ecto_sql 3.5.3) lib/ecto/adapters/sql.ex:1027: anonymous fn/3 in Ecto.Adapters.SQL.checkout_or_transaction/4 (db_connection 2.3.1) lib/db_connection.ex:1444: DBConnection.run_transaction/4 (ecto 3.5.5) lib/ecto/repo/transaction.ex:20: Ecto.Repo.Transaction.transaction/4 (stdlib 3.14) timer.erl:197: :timer.tc/3 (explorer 0.0.1) lib/explorer/repo.ex:21: anonymous fn/2 in Explorer.Repo.logged_transaction/2 (explorer 0.0.1) lib/explorer/logger.ex:14: Explorer.Logger.metadata/2 (explorer 0.0.1) lib/explorer/chain/import.ex:330: anonymous fn/3 in Explorer.Chain.Import.import_transactions/2 (elixir 1.11.1) lib/enum.ex:3764: Enumerable.List.reduce/3 (elixir 1.11.1) lib/enum.ex:2231: Enum.reduce_while/3 (explorer 0.0.1) lib/explorer/chain/import.ex:329: Explorer.Chain.Import.import_transactions/2 Function: &Indexer.Block.Realtime.Fetcher.fetch_and_import_block/3 Args: [8361, %Indexer.Block.Fetcher{broadcast: :realtime, callback_module: Indexer.Block.Realtime.Fetcher, json_rpc_named_arguments: [transport: EthereumJSONRPC.HTTP, transport_options: [http: EthereumJSONRPC.HTTP.HTTPoison, url: "http://localhost:8545", http_options: [recv_timeout: 60000, timeout: 60000, hackney: [pool: :ethereum_jsonrpc]]], variant: EthereumJSONRPC.Geth], receipts_batch_size: 250, receipts_concurrency: 10}, false]
> 
> Key (block_hash)=(\x0000000000000000000000000000000000000000000000000000000000000000) is not present in table "blocks".

Hi @rolik2001 , I am got same issue with you, can you share me how to fix it ? my mail: lamtanphiho1@gmail.com
Thank you

**Comment by rolik2001** [comment]
In file `apps/ethereum_jsonrpc/lib/ethereum_jsonrpc/receipts.ex` line 227 change function to 

```
defp response_to_receipt(%{id: id, result: receipt}, id_to_transaction_params) do
    %{gas: gas} = Map.fetch!(id_to_transaction_params, id)

    # added code that fills missing logs.blockHash
    logs = Map.get(receipt,"logs");
    temp_logs = Enum.map(logs, fn elem ->
      Map.replace!(elem, "blockHash", Map.get(receipt,"blockHash"))
    end)
    receipt = Map.put(receipt, "logs", temp_logs)

    {:ok, Map.put(receipt, "gas", gas)}
  end
```
Tested and Working on zyx network chains
