### ISSUE TITLE
Addition of other Proxies

### ISSUE THREAD

**Issue by UrsaMaritimus** [blockscout/blockscout#4580]
I'd like to suggest the addition of different types of proxies. 

Transparent proxies that use _IMPLEMENTATION_SLOT ("eip1967.proxy.implementation") show up well. However, when we move to other proxy types, such as Beacon Proxies, which uses _BEACON_SLOT ("eip1967.proxy.beacon") to point to a Beacon which holds the implementation, readable by implementation() in the Beacon, we can no longer read/write from a proxy. The OpenZeppelin Beacon Proxy has such a set up.

Is there a way for the BlockScout explorer to not just read _IMPLEMENTATION_SLOT, but ALL reserved slots, and see if they are contracts, and then see if they have implementation? This is just a naive approach, there may be another way, but it would make the introduction of further Proxies useful.

**Comment by vbaranov** [comment]
@UrsaMaritimus Great suggestion. Do you know where all possible slots for transparent proxies are listed? Anyways, it is in our plans to resolve _BEACON_SLOT as well in addition to _IMPLEMENTATION_SLOT.

**Comment by UrsaMaritimus** [comment]
@vbaranov I am not certain, unfortunately, though I know _BEACON_SLOT and _IMPLEMENTATION_SLOT are two others. AFAIK those are/will be the most common use cases due to them being part of the OpenZeppelin standard but a set up for adding new slots would make it trivial upon discovery of a previously unknown one. Glad to hear that it is in the plans!

**Comment by vbaranov** [comment]
Fetching implementation from _BEACON_SLOT has been added https://github.com/blockscout/blockscout/pull/4621
