### ISSUE TITLE
Arbitum on xDai: Add "L1 Block Number" field to the Block Details 

### ISSUE THREAD

**Issue by ulyanas** [blockscout/blockscout#4584]
- Add "L1 Block Number" field to the Block details 
- Tooltip: "A value close to (but not necessarily exactly) the L1 block number at which the Arbitrum Sequencer received the transaction." 
- Create new label "L1" and place it in front of the value in Block Details table. 
- Block address should be clickablу and open this block in L1 BlockScout in a new browser tab

**Comment by vbaranov** [comment]
<img width="697" alt="Screenshot 2021-09-13 at 15 38 47" src="https://user-images.githubusercontent.com/4341812/133084921-15d5b55e-8016-4234-b341-a3388ec62cf2.png">

It began to work from block number 10078
