### ISSUE TITLE
How many day it takes to sync full geth private node ?

### ISSUE THREAD

**Issue by ajaydoyenhub** [blockscout/blockscout#4585]
*Describe your issue here.*

### Environment

* Elixir & Erlang/OTP versions (`elixir -version`): Erlang/OTP 24 [erts-12.0.3] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [jit]
Elixir 1.11.4 (compiled with Erlang/OTP 24)
* Operating System: Linux 20.04
* Blockscout Version/branch:  github.com/poanetwork/blockscout

**How much time need to full sync ?**

![Screenshot from 2021-08-30 12-32-57](https://user-images.githubusercontent.com/55733195/131342844-f5606577-6a88-42d1-a432-8df44964a5e8.png)
![Screenshot from 2021-08-30 18-29-46](https://user-images.githubusercontent.com/55733195/131342847-59f6719b-9d65-4cab-bc7f-6d06119b958b.png)

**Comment by vbaranov** [comment]
It depends on how many blocks & transactions the blockchain has, how powerful are app/DB/archive node servers. If you could specify those params, I could give you a nestimation. Also take a note, that the requirement, that Ethereum client for Blockscout should be running in the archive mode. Otherwise, Blockscout will not be able to fetch internal transactions.

**Comment by ajaydoyenhub** [comment]
**Please check below param:**

geth --nodiscover --networkid 123 --datadir node1 --syncmode=full --gcmode=archive --rpcvhosts=* --unlock Add --mine --rpc --rpcaddr 0.0.0.0 --port 30303 --rpcport 8545 --rpcapi "admin,debug,eth,miner,net,personal,txpool,web3,clique" --ws --ws.addr 0.0.0.0 --ws.port 8546 --ws.origins "*" --ws.api "admin,db,eth,miner,web3,net,personal,txpool,debug" 

![Screenshot from 2021-08-30 12-32-57](https://user-images.githubusercontent.com/55733195/131439973-baf3b686-7ab6-48be-b6bd-15f3e56ffec3.png)
![Screenshot from 2021-08-30 18-29-46](https://user-images.githubusercontent.com/55733195/131439978-f7b6fedd-2468-4fb3-9523-f2ee3b85bce2.png)
![Screenshot from 2021-08-31 09-26-49](https://user-images.githubusercontent.com/55733195/131439980-3f6b53ce-7029-4f7b-9bab-e8ca71e640b1.png)

**Comment by vbaranov** [comment]
Did you check your websocket endpoint with websocat? Does it work? It lloks unhealthy

**Comment by ajaydoyenhub** [comment]
Yeah, It's working the last is screenshot by mistake.

**Comment by vbaranov** [comment]
Config looks good. Could you post the exact retrying... error from the logs?

**Comment by vbaranov** [comment]
Which version of Geth is installed?

**Comment by ajaydoyenhub** [comment]
1.10.8-stable-26675454

**Comment by ajaydoyenhub** [comment]
![Screenshot from 2021-08-30 18-29-46](https://user-images.githubusercontent.com/55733195/131506236-fcee86cf-d769-4e3c-8782-0833ba0f888f.png)
