### ISSUE TITLE
Ethereum Classic: <Issue Title>

### ISSUE THREAD

**Issue by guiavandelft** [blockscout/blockscout#4588]
*Describe your issue here.*

### Environment
* Elixir Version: 1.11.3
* Erlang Version: 23
* BlockScout Version: v3.5.0-beta

* User Agent: `Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.150 Safari/537.36 Edg/88.0.705.63`

### Steps to reproduce

*Tell us how to reproduce this issue. If possible, push up a branch to your fork with a regression test we can run to reproduce locally.*

### Expected Behaviour

*Tell us what should happen.*

### Actual Behaviour

*Tell us what happens instead.*

**Comment by guiavandelft** [comment]
I transferred this ETC from Binance to Coinbase last Sunday 29 August, transaction is pending until now which is more than 24 hours.  Please help

**Comment by guiavandelft** [comment]
HI, why is this issue closed.  the ETC has not been fully transferred to my coinbase account.  Transaction until now is Pending.)

**Comment by vbaranov** [comment]
You should contact Coinbase.

**Comment by guiavandelft** [comment]
okay thanks
