### ISSUE TITLE
Make blockscout adhere to EIP3091 standard

### ISSUE THREAD

**Issue by sidhujag** [blockscout/blockscout#4595]
Hello,

Can we enable blockscout to work with the [EIP3091](https://eips.ethereum.org/EIPS/eip-3091) standard? You can see that the ethereum-list is enforcing it and its what Etherscan uses anyway:

https://github.com/ethereum-lists/chains/blob/master/src/main/kotlin/org/ethereum/lists/chains/Main.kt#L194

**Comment by vbaranov** [comment]
This is a duplicate of https://github.com/blockscout/blockscout/issues/4455

**Comment by sidhujag** [comment]
thanks! hopefully the PR to fix this can be completed
