### ISSUE TITLE
Not listing all the account addresses in Account Menu

### ISSUE THREAD

**Issue by ajaydoyenhub** [blockscout/blockscout#4597]
I'm running my Ethereum private node:

I can see in **Account Menu** the number of accounts created by the above below command:
**$ geth --datadir datadir account new**

But I can't see other account addresses which are created on **geth console** by using the below command:
**> personal.newAccount()**

Please check and let me know where I'm wrong or what config I need to add.

**Comment by vbaranov** [comment]
Do you mean `/accounts` page by account menu? Only accounts with >0 balance are displayed on that page.

**Comment by ajaydoyenhub** [comment]
Ohh ok. Thank you got it.

One more question, **I don't want to store maintain indexer.log and error.log.** 

how can I stop it?
