### ISSUE TITLE
Chain Data missing?

### ISSUE THREAD

**Issue by aflinfo** [blockscout/blockscout#4605]
Hi There

When i download the chain data via CURL 

curl -s https://s3-us-west-2.amazonaws.com/download.energi.software/releases/chaindata/mainnet/gen3-chaindata.tar.gz | tar xvz

I do not get the latest data it always starts at block 757753, it seems the gen3-chaindata.tar.gz does not contain the most recent data

_Welcome to the Energi Core JavaScript console!
instance: energi3/v3.0.7-stable/linux-amd64/go1.13.8
coinbase: 0x0000000000000000000000457068656d6572616c
at block: 757753 (Thu, 19 Aug 2021 23:33:49 UTC)_

### Environment

* Elixir & Erlang/OTP versions (`elixir -version`): Erlang/OTP 22 [erts-10.6.4] [source] [64-bit] [smp:1:1] [ds:1:1:10] [async-threads:1]
* Elixir 1.9.1 (compiled with Erlang/OTP 22)
* Operating System: Linux (VPS)
* Blockscout Version/branch: ...

### Steps to reproduce

1) Stop the core node: sudo systemctl stop energi3
2) energi3 removedb
3) cd $HOME
4) curl -s https://s3-us-west-2.amazonaws.com/download.energi.software/releases/chaindata/mainnet/gen3-chaindata.tar.gz | tar xvz
5) sudo systemctl start energi3
6) energi3 attach
7) see the at block

Welcome to the Energi Core JavaScript console!

instance: energi3/v3.0.7-stable/linux-amd64/go1.13.8
**coinbase: 0x0000000000000000000000457068656d6572616c
at block: 757753 (Thu, 19 Aug 2021 23:33:49 UTC)**
 datadir: /home/nrgstaker/.energicore3
 modules: admin:1.0 debug:1.0 energi:1.0 eth:1.0 masternode:1.0 miner:1.0 net:1.      0 nrg:1.0 personal:1.0 rpc:1.0 txpool:1.0 web3:1.0

8) check the latest block on explorer (8:06pm ET)
![image](https://user-images.githubusercontent.com/77820748/132110825-a4616d31-7610-4ffd-b5e5-94cba4438bb8.png)

### Expected behaviour

The gen3-chaindata.tar.gz should contain the latest data and be aligned with explorer most recent blocks

### Actual behaviour

gen3-chaindata.tar.gz does not contain the most recent data

*Tell us what happens instead.*

**Comment by vbaranov** [comment]
There is no official support of Energi instance here. You should ask the team directly.
