### ISSUE TITLE
Certain tokens not showing up in "Tokens" tab

### ISSUE THREAD

**Issue by GitCrypt091** [blockscout/blockscout#4614]
Certain tokens not showing up in "Tokens" tab (MoonRiver MVR network)

### Steps to reproduce

1. Go to https://swap.moonfarm.in/#/swap
2. Buy some mSWAP tokens
3. Check block explorer. not showing that you own the bought tokens

**Comment by vbaranov** [comment]
Here is no official support of MoonRiver instance of Blockscout.
