### ISSUE TITLE
Incorrect validator addresses with latest Geth POA chain

### ISSUE THREAD

**Issue by marius3000** [blockscout/blockscout#4616]
I run private POA chain with clique consensus and Blockscout all latest tags (v3.7.x-beta, v3.6.0-beta, v3.5.1-beta) show incorrect validator address for all blocks after Geth (go-ethereum) got upgraded to the latest version (v1.10.8). It's just random address and never repeats twice for any of the blocks.

I do not see any errors in either Blockscout or Geth client. When I query Geth directly via Geth API I get correct sealer address about the block and which of the sealers sealed it so it does not seem like an issue with the chain itself. That's why I'm posting here.

I have upgraded Geth from 1.9.25 to 1.10.8. 

If I run the Geth sealers as upgraded nodes with version 1.10.8 and run one non-sealing Geth node on old version 1.9.25 then the latest Blockscout tags is able to read chain from that non-sealing node very well and shows correct sealer address.

Any suggestions how to resolve this please?

### Environment

* Elixir & Erlang/OTP versions (`elixir -version`): docker image elixir:1.10.4
* Blockscout Version/branch: tried v3.7.3-beta, v3.6.0-beta, v3.5.1-beta (maybe older as well)

**Comment by hjhjdev** [comment]
It happens on latest blockscout V4.1.0 too.

**Comment by vbaranov** [comment]
Rsolved with https://github.com/blockscout/blockscout/pull/5676
