### ISSUE TITLE
ETC indexer not indexing

### ISSUE THREAD

**Issue by nitinmani** [blockscout/blockscout#4627]
The ETC blockscout is not indexing any blocks past #13491650

https://blockscout.com/etc/mainnet

Can we get someone to look into this?

**Comment by vbaranov** [comment]
![scrnli_10_09_2021_11-44-48](https://user-images.githubusercontent.com/4341812/132826718-b48baf51-c4ac-4708-b1fb-44e6787326d4.png)

**Comment by tysovsky** [comment]
@vbaranov its not actually showing any transactions in those blocks. If you looks the last transaction blockscout shows is from 2 days ago.

**Comment by vbaranov** [comment]
Ah, I see now. You should ask ETCCooperative team. Blockscout team is not hosted instance for ETC.

**Comment by diega** [comment]
Hi!
what's the URL of the node you are using for generating the index?

**Comment by bobsummerwill** [comment]
@diega of the Coop is investigating.  Please can we reopen the issue while this is ongoing, @vbaranov?  Thanks!

**Comment by vbaranov** [comment]
@diega @bobsummerwill we recently published 3.7.3 release and I prepared a branch for ETC with its inclusion: https://github.com/blockscout/blockscout/tree/production-classic-stg. It looks like your instance is behind several releases which contain indexer performance improvements: https://github.com/blockscout/blockscout/blob/master/CHANGELOG.md. It is worth updating your instance in my opinion.

**Comment by diega** [comment]
Hi @vbaranov, I'm moving into upgrading the instance. I built the image from the `v3.7.3-beta` tag, do you recommend I rebuild from the branch `production-classic-stg`?
So far, using the `v3.7.3-beta` build I'm getting this kind of errors, I assume there is some migration needed for the database that I may have missed
```
** (Postgrex.Error) ERROR 42703 (undefined_column) column t0.skip_metadata does not exist
```
I ran the `$ mix do ecto.create, ecto.migrate` command, but I don't know if that should have worked

**Comment by vbaranov** [comment]
Hi, yes, I recommend rebuilding from `production-classic-stg`. This is the ETC-specific branch with installed latest published release. It seems, DB migrations didn't run. And `mix do ecto.create, ecto.migrate` should run DB migrations. Just in case, we also added DB migrations step to Docker setup https://github.com/blockscout/blockscout/pull/4516/files. DB migrations should run automatically with Docker container launch if you prepared docker image from `production-classic-stg` branch.

**Comment by diega** [comment]
Excellent. Now I'm running the instance from the `make` script setting the proper env variables.
I can see a lot of output like this
```
2021-09-13T15:44:24.406 application=db_connection [error] Postgrex.Protocol (#PID<0.632.0>) failed to connect: ** (Postgrex.Error) FATAL 53300 (too_many_connections) sorry, too many clients already
2021-09-13T15:44:24.558 fetcher=internal_transaction count=2 [error] Task #PID<0.10755.1> started from Indexer.Fetcher.InternalTransaction terminating
** (FunctionClauseError) no function clause matching in EthereumJSONRPC.Parity.Trace.entry_to_elixir/1
    (ethereum_jsonrpc 0.1.0) EthereumJSONRPC.Parity.Trace.entry_to_elixir({"revertReason", "0x"})
    (elixir 1.11.4) lib/enum.ex:1335: anonymous fn/4 in Enum.into/3
    (stdlib 3.14.1) maps.erl:233: :maps.fold_1/3
    (elixir 1.11.4) lib/enum.ex:2209: Enum.into/4
    (elixir 1.11.4) lib/enum.ex:1411: Enum."-map/2-lists^map/1-0-"/2
    (ethereum_jsonrpc 0.1.0) lib/ethereum_jsonrpc/besu.ex:114: EthereumJSONRPC.Besu.trace_replay_block_transactions_responses_to_internal_transactions_params/2
    (indexer 0.1.0) lib/indexer/fetcher/internal_transaction.ex:109: Indexer.Fetcher.InternalTransaction.run/2
    (elixir 1.11.4) lib/task/supervised.ex:90: Task.Supervised.invoke_mfa/2
Function: &Indexer.BufferedTask.log_run/1                                                                                                                                                                       Args: [%{batch: [13518662, 13518858], callback_module: Indexer.Fetcher.InternalTransaction, callback_module_state: [transport: EthereumJSONRPC.HTTP, transport_options: [http: EthereumJSONRPC.HTTP.HTTPoison, url: "http://3.91.63.126:8545", method_to_url: [eth_getBalance: "http://3.91.63.126:8545", trace_block: "http://3.91.63.126:8545", trace_replayTransaction: "http://3.91.63.126:8545"], http_options:
 [recv_timeout: 600000, timeout: 600000, hackney: [pool: :ethereum_jsonrpc]]], variant: EthereumJSONRPC.Besu], metadata: [fetcher: :internal_transaction]}]
2021-09-13T15:44:24.653 fetcher=internal_transaction count=2 [error] Task #PID<0.10753.1> started from Indexer.Fetcher.InternalTransaction terminating
** (FunctionClauseError) no function clause matching in EthereumJSONRPC.Parity.Trace.entry_to_elixir/1
    (ethereum_jsonrpc 0.1.0) EthereumJSONRPC.Parity.Trace.entry_to_elixir({"revertReason", "0x"})
    (elixir 1.11.4) lib/enum.ex:1335: anonymous fn/4 in Enum.into/3
    (stdlib 3.14.1) maps.erl:233: :maps.fold_1/3
    (elixir 1.11.4) lib/enum.ex:2209: Enum.into/4
    (elixir 1.11.4) lib/enum.ex:1411: Enum."-map/2-lists^map/1-0-"/2
    (elixir 1.11.4) lib/enum.ex:1411: Enum."-map/2-lists^map/1-0-"/2
    (ethereum_jsonrpc 0.1.0) lib/ethereum_jsonrpc/besu.ex:114: EthereumJSONRPC.Besu.trace_replay_block_transactions_responses_to_internal_transactions_params/2
    (indexer 0.1.0) lib/indexer/fetcher/internal_transaction.ex:109: Indexer.Fetcher.InternalTransaction.run/2
Function: &Indexer.BufferedTask.log_run/1                                                                                                                                                                       Args: [%{batch: [13521703, 13521317], callback_module: Indexer.Fetcher.InternalTransaction, callback_module_state: [transport: EthereumJSONRPC.HTTP, transport_options: [http: EthereumJSONRPC.HTTP.HTTPoison, url: "http://3.91.63.126:8545", method_to_url: [eth_getBalance: "http://3.91.63.126:8545", trace_block: "http://3.91.63.126:8545", trace_replayTransaction: "http://3.91.63.126:8545"], http_options:
```

**Comment by vbaranov** [comment]
The set of env variables looks fine. Probably, the version of Besu client was updated on the archive node side and some breaking changes appeared. Let me take a look on this. I will return to you.

**Comment by diega** [comment]
Thanks! just for the record, the Besu version running in the archive node is `v21.7.2`

**Comment by diega** [comment]
https://blockscout.com/etc/mainnet/blocks has been updated to `v3.7.3-beta` and I think we are not skipping blocks anymore. Thanks a lot @vbaranov for your help!

**Comment by vbaranov** [comment]
Awesome to hear! Let me close this issue. Regarding fetching traces error from the logs, we will cover it in the frame of https://github.com/blockscout/blockscout/issues/4311.

**Comment by bobsummerwill** [comment]
Thanks, @vbaranov and @diega!
