### ISSUE TITLE
Older smart contract (Token) transaction data not showing

### ISSUE THREAD

**Issue by ajaydoyenhub** [blockscout/blockscout#4629]
Initially, I was started my geth without **--syncmode=full --gcmode=archive** ,  My geth is running with having some Smart Contract(**Token**) transactions.

Now when I configured Blockscout Explorer with my get It's not showing me token(ERC20) transaction data, But when I do any transaction while Explorer is connected new transaction data showing but not before connecting.

I'm getting below error.
![Screenshot from 2021-09-10 11-52-39](https://user-images.githubusercontent.com/55733195/132809662-cc2a879d-5a88-48a6-b206-1e02912c184b.png)

Also, when I try to run my get with **--syncmode=full --gcmode=archive** param again It's giving the same issue.

Is, there any solution to get my Blockscout Explorer sync with 0 blocks. 
I can't reset my DB because I already transferred some coins. Otherwise, I'll load my data.

**Comment by vbaranov** [comment]
You should re-sync the node with `--syncmode=full --gcmode=archive` from scratch.

**Comment by ajaydoyenhub** [comment]
But, what about of my privious data ?

**Comment by vbaranov** [comment]
Re-sync node from scratch in archive mode. Switch Blockscout to this fully synced node. It will fetch all missing data.

**Comment by ajaydoyenhub** [comment]
Can you please help me with the command that I need to perform?
It's request :)

**Comment by vbaranov** [comment]
Just remove node's data and run it in archive mode. It should be in archive mode from the genesis block to the head of the chain.

**Comment by ajaydoyenhub** [comment]
Then my data will not be lost.

geth --datadir node1/ init genesis.json 

My old data will come again ?

**Comment by vbaranov** [comment]
If you have only one client to keep your private chain running, of course, you will lose the data. You should have a full node launched to keep your chain running. Create a new archive endpoint connected to that chain via boot nodes. Run this archive endpoint in archive mode and use it for Blockscout. You have the issue with Blockscout because you initially launched the node in non-archive mode and then switched to archive mode - this will not work if you want to index the full chain in Blockscout. The main idea - archive node for Blockscout should be launched in archive mode from genesis block.

**Comment by ajaydoyenhub** [comment]
@vbaranov,  I did the exact same. 

I'm getting all the data except token holder info that was previously minted. 

I can see all the Transactions under token but in token holder showing no info. Even holder count also showing 0.

**Comment by vbaranov** [comment]
If you see a message "required historical state unavailable", then your node is not in archive mode for all blocks.

**Comment by ajaydoyenhub** [comment]
Yes, exactly the same message I'm getting after running my node with --syncmode=full --gcmode=archive param

**Comment by ajaydoyenhub** [comment]
@vbaranov, I deployed Blockscout Explorer on the domain by using ELB. but I'm getting an error of **WebSocket connection to failed**.
I have used ProxyPassReverse for redirecting from localhost:4000 to the domain name.

It's running fine on public IP, but after redirecting on the domain it's giving a WebSocket error.

Please do help me.

**Comment by ajaydoyenhub** [comment]
Hello @vbaranov, I'm not able to see the ER721 token list inside the token menu except ERC20.

Is there any config for listing ERC721 ?
