### ISSUE TITLE
Ethereum Classic: <Issue Title>

### ISSUE THREAD

**Issue by Damonxzw** [blockscout/blockscout#4639]
*Describe your issue here.*
I cannot find my transaction of this hash:
0x2a72785f72185700d3357a2bdc5d4a47cd8e18c421934527978a7515d0bf36ac

### Environment
* Elixir Version: 1.11.3
* Erlang Version: 23
* BlockScout Version: v3.5.0-beta

* User Agent: `Mozilla/5.0 (iPhone; CPU iPhone OS 14_7_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.1.2 Mobile/15E148 Safari/604.1`

### Steps to reproduce

*Tell us how to reproduce this issue. If possible, push up a branch to your fork with a regression test we can run to reproduce locally.*

### Expected Behaviour

*Tell us what should happen.*
The page should load and it should show the confirmations and the amount of confirmations received and amount of confirmations required. There should be amount that is sent. I have contacted coinbase for this matter. But i dont know where the problem lies. 

### Actual Behaviour

*Tell us what happens instead.*
There is no confirmations. It just shows could not locate the transaction.

**Comment by vbaranov** [comment]
The issue with indexing has been resolved on ETC instance.

<img width="1045" alt="Screenshot 2021-09-14 at 14 50 27" src="https://user-images.githubusercontent.com/4341812/133252480-3c8a4d63-b39e-405b-8bc1-724f16857cb6.png">
