### ISSUE TITLE
Ethereum Classic: <balance no shows in Wallet>

### ISSUE THREAD

**Issue by darb27** [blockscout/blockscout#4647]
*hello I am using coinbase and I have mine etc but it didn't come in to my wallet but it shows on network 3.75 but in wallet it shows only 3.43 . Please can you see why this happened ?? 

Etc wallet address- 0x107E098c50454D5De0683e1eD335282Fb94b116F

I have attached photo also.
![Screenshot_20210907-030955_Wallet](https://user-images.githubusercontent.com/89255998/133354035-63797d5a-f0d1-45e2-a978-ebebbecb9e18.jpg)
![Screenshot_20210907-030815_Wallet](https://user-images.githubusercontent.com/89255998/133354074-a250e142-2708-46b6-85f7-b4b60d70a9cb.jpg)

### Environment
* Elixir Version: 1.11.3
* Erlang Version: 23
* BlockScout Version: v3.5.0-beta

* User Agent: `Mozilla/5.0 (Linux; Android 11; SM-G988B) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/93.0.4577.62 Mobile Safari/537.36`

### Steps to reproduce

*Tell us how to reproduce this issue. If possible, push up a branch to your fork with a regression test we can run to reproduce locally.*

### Expected Behaviour

*Tell us what should happen.*

### Actual Behaviour

*Tell us what happens instead.*

**Comment by vbaranov** [comment]
You should ask Coinbase
