### ISSUE TITLE
consistency in updating an if NOT to unless statement

### ISSUE THREAD

**Issue by sidhujag** [blockscout/blockscout#4658]
https://github.com/blockscout/blockscout/pull/4649/commits/f81255b711041c4d39c76824810af2b28e66fb09

committed an unless instead of an if !, however searching through the code there are other places if !empty_exchange_rate? is present, I just was wondering why this one spot was changed and not the others?

**Comment by vbaranov** [comment]
That commit is related to a specific PR. Other places will be changed gradually.
