### ISSUE TITLE
Moonriver: Transfer NEVER went through

### ISSUE THREAD

**Issue by louism023** [blockscout/blockscout#4662]
Hello,

I made a few transactions from my MetaMask wallet but one significant one NEVER went through and it has been troubling me.  I need help to resolve.  Below is the link for the transaction where I sent approx 17,000 USDC to KuCoin exchange and it never went through.  Other transactions of MOVR did but this one did not and I need to resolve IMMEDIATELY.  I have contacted KuCoin as well.  PLEASE HELP!!!

https://blockscout.moonriver.moonbeam.network/tx/0x4ecf5e382e93e1d0bb34f8261eac860110c6d4e8820a6c7b4ca93f0d97af1e83/token-transfers

**Comment by vbaranov** [comment]
Moonriver instance is not supported here. Reach out Moonriver team directly.
