### ISSUE TITLE
Transaction list in a block broken across paging

### ISSUE THREAD

**Issue by sidhujag** [blockscout/blockscout#4664]
Transactions are not paging correctly and the total amount of transactions are not showing, lets take this ETC block for example: https://blockscout.com/etc/mainnet/blocks/13558397/transactions
There are 239 transactions in this block. The first txid is: 0x1b03db2fde9e5f6f89946048da98c18f060b5057362e385d14741323dffb8f2e which matches across another explorer: 
https://etcblockexplorer.com/block/0x09198361230aa2cd921b9c6c903e9d6521854e1f7ce08145c14fac76c43fc8b2?page=1

However on page 2 we can see the same txid repeated, there are thus a bunch of missing transactions. A very funny thing happens on the last txid of the first page, it seems like the first tx of page 2 shows up as the last tx of page 1, and on page 2 you have an identical page as on page 1 minus this last tx. 

Another related bug is if I am on page 2, in both the tx list AND block list for example: https://blockscout.com/etc/mainnet/blocks/13558397/transactions?block_number=13558397&index=49&items_count=50 and I move away or refresh (or you click on this link) it will always start back at page 1.

These bugs also exist in the latest code incase etc code is not on master tip.

Also just as a UX hint, I would strongly advise to get rid of the blind paging if possible. Blind paging is especially effective during optimized indexed applications where you need to lazy load data sets and have no idea about total size. However that is not the case here as we know total transactions/total blocks in our data set and thus should be using regular page mechanisms.

<img width="266" alt="Screen Shot 2021-09-18 at 11 56 41 PM" src="https://user-images.githubusercontent.com/6238042/133918581-a0e435e7-7aed-49bf-b929-d2a888d79e75.png">

**Comment by vbaranov** [comment]
@sidhujag thanks for a feedback 
@nikitosing please take into account since you're working on pagination improvements.

**Comment by zalam003** [comment]
@nikitosing @vbaranov We at `Energi` have more than one page worth of internal transactions for every block.  The pagination is not functioning as it should.  It is similar to what is noted in the issue.  In the example below, some of the data in page 2 is the same as page 1:
https://explorer.energi.network/tx/0xb4eb403fdf6d7676c60793042f442159686b9b68fd0c1c3cdfa13b1d98c3b4ea/internal-transactions?block_number=804117&index=50&items_count=50&transaction_index=2
