### ISSUE TITLE
support for openzeppelin uups erc1967 proxy

### ISSUE THREAD

**Issue by sirpy** [blockscout/blockscout#4665]
proxies using this new proxy type are not identified by blockscout as a proxy even after verifying

**Comment by vbaranov** [comment]
@sirpy Could you post a sample contract, please?

**Comment by sirpy** [comment]
@vbaranov 
ropsten: https://ropsten.etherscan.io/address/0x855e98563268A5901245EDAF5D6DC4a84dE52488#code
fuse(blockscout):  https://explorer.fuse.io/address/0x42397cda22eA9678B99aB044e09943dcd9C1C197/contracts

**Comment by vbaranov** [comment]
@sirpy which version of Blockscout application installed in Fuse instance? Looks pretty old.

**Comment by sirpy** [comment]
@vbaranov not sure
are newer versions supposed to support this proxy?

**Comment by vbaranov** [comment]
Support of transparent proxy pattern was added in 3.3.0-beta. Support of Beacon proxy slot is in the current master branch https://github.com/blockscout/blockscout/commit/478af7d8d6ebecfe993880dfb8cbe87b8eb87a56. You should ask Fuse team to upgrade their instance.
