### ISSUE TITLE
Duplicate entry in _transaction.scss

### ISSUE THREAD

**Issue by zalam003** [blockscout/blockscout#4670]
More of a clean-up.  `.transaction-bottom-panel` is listed twice (line 1 and 11)

https://github.com/blockscout/blockscout/blob/478af7d8d6ebecfe993880dfb8cbe87b8eb87a56/apps/block_scout_web/assets/css/components/_transaction.scss#L1

**Comment by zalam003** [comment]
@vbaranov FYI ☝️

**Comment by vbaranov** [comment]
@zalam003 nice catch. Would you prepare a fix for that? Will review it and will merge it with pleasure.

**Comment by zalam003** [comment]
> @zalam003 nice catch. Would you prepare a fix for that? Will review it and will merge it with pleasure.

Happy to do so.
