### ISSUE TITLE
Kotti: Forcefully getting redirected to ETC mainnet

### ISSUE THREAD

**Issue by rupansh** [blockscout/blockscout#4672]
*Describe your issue here.*

### Environment
* Elixir Version: 1.11.4
* Erlang Version: 23
* BlockScout Version: 

* User Agent: `Mozilla/5.0 (X11; Linux x86_64; rv:92.0) Gecko/20100101 Firefox/92.0`

### Steps to reproduce

Select kotti from chainlist
Search for anything
Redirects to mainnet

Click any button in a transaction,
Redirects to mainnet

### Expected Behaviour

Search, buttons etc should be interacting with kotti

### Actual Behaviour

all buttons interact with ETC mainnet

**Comment by vbaranov** [comment]
Related to https://github.com/blockscout/blockscout/issues/4501

**Comment by vbaranov** [comment]
Resolved
