### ISSUE TITLE
Moonriver: transaction ID FAILS

### ISSUE THREAD

**Issue by deechopra** [blockscout/blockscout#4675]
*Describe your issue here.*
Sent USDC from Metamask Moonriver network to Binance account via ERC20 but Metamask shows the transaction FAILED and on checking the transaction on blackscout it says it’s pending. I do not see the funds on my Metamask. 
transaction id is:-

0xb3f6081cff2401abebf78063b0594c74217bb160148847a4edf34282f23f2c9a

### Environment
* Elixir Version: 1.11.4
* Erlang Version: 23
* BlockScout Version: v3.7.0+

* User Agent: `Mozilla/5.0 (iPhone; CPU iPhone OS 14_7_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Mobile/15E148`

### Steps to reproduce

*Tell us how to reproduce this issue. If possible, push up a branch to your fork with a regression test we can run to reproduce locally.*

### Expected Behaviour

*Tell us what should happen.*
Funds should be transferred 
### Actual Behaviour
Funds are stuck. 
*Tell us what happens instead.*

**Comment by deechopra** [comment]
Hi Could someone please help?

**Comment by vbaranov** [comment]
Moonriver instance is unsupported here.

**Comment by deechopra** [comment]
where should I go for help?

**Comment by vbaranov** [comment]
Moonriver team. I am not aware what are the public channels to communicate with them.
