### ISSUE TITLE
how to deploy on production mode + apache2

### ISSUE THREAD

**Issue by ajaydoyenhub** [blockscout/blockscout#4679]
*Describe your issue here.*

I need to deploy my application in production mode. Like access through the domain name.
I did that but using a proxy redirect on the particular domain name.
After redirecting I'm getting **WebSocket endpoint failed** error.

can someone please help me with how to host on the domain instead of redirecting?

### Environment

* Elixir & Erlang/OTP versions (`elixir -version`): Elixir 1.11.4 (compiled with Erlang/OTP 24)
* Operating System: Linux
* Blockscout Version/branch: git clone https://github.com/poanetwork/blockscout

**Comment by baselka** [comment]
> _Describe your issue here._
> 
> I need to deploy my application in production mode. Like access through the domain name. I did that but using a proxy redirect on the particular domain name. After redirecting I'm getting **WebSocket endpoint failed** error.
> 
> can someone please help me with how to host on the domain instead of redirecting?
> ### Environment
> 
>     * Elixir & Erlang/OTP versions (`elixir -version`): Elixir 1.11.4 (compiled with Erlang/OTP 24)
> 
>     * Operating System: Linux
> 
>     * Blockscout Version/branch: git clone https://github.com/poanetwork/blockscout

Were you able to find out how ?

**Comment by ajaydoyenhub** [comment]
I tried but not be able to do that. Still, I'm using ProxyPass to redirect running from IP to the domain name.

I would be very thankful If someone can help me.

**Comment by ajaydoyenhub** [comment]
closed
