### ISSUE TITLE
IDChain: Not receiving Eidi tokens on Metamask after BrightID verification, and app link procedure... no EIDI on blockscout for IDChain explorer...

### ISSUE THREAD

**Issue by satoshi0x** [blockscout/blockscout#4685]
Basically I have tried this many times: https://brightid.gitbook.io/brightid/idchain/claim-your-eidi-supply

And I never get Eidi tokens... I don't even see them on the explorer. Everything else went smoothly. What's up?

### Environment
* Elixir Version: 1.10.2
* Erlang Version: 22
* BlockScout Version: 

* User Agent: `Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/93.0.4577.82 Safari/537.36`

### Steps to reproduce

https://brightid.gitbook.io/brightid/idchain/claim-your-eidi-supply steps 1-5

### Expected Behaviour

After Step 5 i should have Eidi tokens delivered to my MetaMask address verified by BrightID. I also have IDChain linked in the app.

### Actual Behaviour

I get 0 tokens. I don't even have my BrightID ver and IDChain app linked address showing on the explorer for BlockScout's IDChain at https://explorer.idchain.one/

**Comment by vbaranov** [comment]
Here is no support of IDchain. You should ask the team directly.
