### ISSUE TITLE
rhythmic-tegmen: Block Explorer does not work on mobile

### ISSUE THREAD

**Issue by JCaraballo113** [blockscout/blockscout#4687]
*Describe your issue here.*

### Environment
* Elixir Version: 1.11.4
* Erlang Version: 23
* BlockScout Version: latest

* User Agent: `Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/93.0.4577.82 Safari/537.36 Edg/93.0.961.52`

### Steps to reproduce

Open a SKALE block explorer on mobile. It will not work.

### Expected Behaviour

The SKALE block explorer should work on mobile

### Actual Behaviour

The SKALE block explorer does not work.

**Comment by vbaranov** [comment]
Could you provide a link to explorer?

**Comment by JCaraballo113** [comment]
Here you go!

http://rhythmic-tegmen.explorer.mainnet.skalenodes.com/

**Comment by vbaranov** [comment]
I suppose the issue has been resolved

<img width="218" alt="Screenshot 2021-11-01 at 15 00 17" src="https://user-images.githubusercontent.com/4341812/139668237-5c33e9a7-0034-4182-a5e4-c71bc7938b5b.png">
