### ISSUE TITLE
indexer internal_transaction timeout

### ISSUE THREAD

**Issue by lingyun92** [blockscout/blockscout#4691]
application=indexer fetcher=internal_transaction count=10 error_count=10 [error] failed to fetch internal transacti
ons for blocks: [%{data: %{block_number: 0xNumber, transaction_hash: "0xHash", transaction_index
: 0}, message: :timeout}]

### Environment

* Elixir & Erlang/OTP versions (`elixir -version`): Erlang/OTP 24 [erts-12.0.3], Elixir 1.12.2 (compiled with Erlang/OTP 22)
* Operating System: 20.04.1-Ubuntu
* Blockscout Version/branch:  master
* Geth version: 1.10.8

Geth's hardware is enough. Is there a way to increase the timeout?

**Comment by lingyun92** [comment]
geth log show: Served debug_traceTransaction            conn=172.31.2.132:46064 reqid=0 t=5.05557912s  err="execution timeout"

**Comment by vbaranov** [comment]
@lingyun92 you can try to decrease the batch size for internal transactions fetcher. It is managed here:
https://github.com/blockscout/blockscout/blob/ee48f1edac02e68ab18140fa2dadb9022be62e36/apps/indexer/lib/indexer/fetcher/internal_transaction.ex#L23. By default, 10 blocks in the batch.

**Comment by lingyun92** [comment]
change it to 4, still occur sometimes, is there a way to set the timeout param? 
like this `{"tracer":"callTracer","timeout":"60s"}`

**Comment by vbaranov** [comment]
> is there a way to set the timeout param?

Yes, this is for Geth archive node, for instance:

https://github.com/blockscout/blockscout/blob/94286f548a9dce5934e7f8f72e5b03429fe1565a/apps/explorer/config/prod/geth.exs#L9

You can find a similar config for other archive nodes types as well in the current location.

**Comment by lingyun92** [comment]
Thanks, what I mean is not the timeout of HTTP, but the timeout of call of `debug_traceTransaction`. The `debug_tracetransaction` of Geth is 5 seconds as default. Maybe we need a way to override it.

https://geth.ethereum.org/docs/rpc/ns-debug#debug_tracetransaction

**Comment by vbaranov** [comment]
Got it. timeout setting not yet implemented for `debug_traceTransaction` method.

**Comment by lingyun92** [comment]
Yeah, cool, I am willing to help but I don't know Erlang.....

**Comment by jovijovi** [comment]
We also encountered this problem. Blockscout frequent call debug_Tracetransaction leads to abnormally high CPU utilization of archive node.
Any plans to solve this problem?

## Logs

```text
2021-10-11T08:39:44.014 application=indexer fetcher=internal_transaction count=10 error_count=10 [error] failed to fetch internal transactions for blocks: [%{data: %{block_number: 1213409, transaction_hash: "0x02781d7f910abdf4d20e5a7ac77a8b3db3ac02a312cb005ceb0ee2f8efc059b0", transaction_index: 0}, message: :timeout}]
2021-10-11T08:39:45.135 application=indexer fetcher=internal_transaction count=10 error_count=10 [error] failed to fetch internal transactions for blocks: [%{data: %{block_number: 1212728, transaction_hash: "0xc1a8d67f5ad9c6a45447ec02cb4235dbf7e4f27a0d34e4b17f5882731f5063d9", transaction_index: 0}, message: :timeout}]
2021-10-11T08:39:46.325 application=indexer fetcher=internal_transaction count=10 error_count=10 [error] failed to fetch internal transactions for blocks: [%{data: %{block_number: 1212731, transaction_hash: "0xcc72d2907b3ba7ceeed883e6f36fe03e8c67712401ec6c67546030c8b276c105", transaction_index: 0}, message: :timeout}]
```

## Environment
- Operating System: 20.04.3-Ubuntu
- Blockscout Version/branch: 3.7.0-beta
- Geth version: 1.9.23
- Hardware: 16CORE/ 32GB

**Comment by cen1** [comment]
I think this needs more attention. As it is now, blockscout permanently fails to index some of the transactions because of the timeout. But increasing the timeout will only help a bit, in certain cases the call can blow up a node due to memory requirements:

The method is OBS in the documentation:
https://geth.ethereum.org/docs/rpc/ns-debug#debug_traceTransaction

As an immediate optimization, would blockscout work with any of these disabled? `disableStorage`, `disableStack`?

Replacement:
https://geth.ethereum.org/docs/rpc/ns-debug#debug_standardtraceblocktofile -> "It streams output to disk during the execution, to not blow up the memory usage on the node"

**Comment by vbaranov** [comment]
Timeout for `debug_traceTransaction ` is managed by `ETHEREUM_JSONRPC_DEBUG_TRACE_TRANSACTION_TIMEOUT` env variable now:

> Timeout for debug_traceTransaction JSON RPC method request in case of geth archive node. Supported time formats: https://pkg.go.dev/time#ParseDuration. Introduced in [#5505](https://github.com/blockscout/blockscout/pull/5505).

Reference: https://docs.blockscout.com/for-developers/information-and-settings/env-variables#indexer-management
