### ISSUE TITLE
xDai: <Too long transaction>

### ISSUE THREAD

**Issue by G-bon78** [blockscout/blockscout#4720]
I did a 72 USDT transfer from my metamask wallet to Binance account since 3days on xDai chain  but yet it has not arrived. What's the matter and how can it be solved?
 0x8bc7152683c1af63bdcdbd37b3a6c2e31c7d3a1aded5a3f37017da113e919934
That's the transaction hash

### Environment
* Elixir Version: 1.12.2
* Erlang Version: 24
* BlockScout Version: v3.7.3-beta

* User Agent: `Mozilla/5.0 (Linux; Android 8.1.0; Infinix X624B Build/O11019; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/92.0.4515.131 Mobile Safari/537.36`

### Steps to reproduce

*Tell us how to reproduce this issue. If possible, push up a branch to your fork with a regression test we can run to reproduce locally.*

### Expected Behaviour

*Tell us what should happen.*

### Actual Behaviour

*Tell us what happens instead.*

**Comment by vbaranov** [comment]
The transaction was confirmed on xDai chain

<img width="983" alt="Screenshot 2021-10-06 at 13 09 14" src="https://user-images.githubusercontent.com/4341812/136183890-09bd517d-0f48-401b-ae62-82abbb03c6f3.png">

But I think Binance doesn't support USDT from xDai chain. You should ask Binance for support.

**Comment by G-bon78** [comment]
Can i send it to usdt on Trust wallet?
