### ISSUE TITLE
Error:  Certificate Expired while ssl_handshake

### ISSUE THREAD

**Issue by raj-shekhar1** [blockscout/blockscout#4727]
Hi Team, @vbaranov
I have taken the latest Blockscout code, and trying to run it in docker. Earlier code was working good (v3.7.2) but now I am getting below error.

```
 [info] TLS :client: In state :certify at ssl_handshake.erl:1878 generated CLIENT ALERT: Fatal - Certificate Expired
```
I am connecting to custom RPC endpoint and tls certs are fine. can someone please suggest as I am totally new to Elixir.
Thanks in advance.

### Environment 

* Operating System: linux
* Blockscout Version/branch: latest master

**Comment by arvola** [comment]
I'm seeing the same issue, I believe this is being caused by the Let's Encrypt root certificate expiration, referenced in the following links:

https://groups.google.com/g/erlang-programming/c/eo_tlZI59rY
https://blog.voltone.net/post/30

Need to upgrade Erlang to 24.0.6 to avoid this issue.

**Comment by 3commascapital** [comment]
thank you kindly

**Comment by raj-shekhar1** [comment]
@arvola I have not disabled SSL but strangely not got this error in the logs now but the Blockscout UI is not auto-refreshing. Have you also experienced similar issue

**Comment by arvola** [comment]
@raj-shekhar1 With a sufficiently new version of Erlang, the SSL issue only affects the WebSocket connection, so not auto-refreshing is consistent with that. There may be some other reason why you're not seeing the error messages. You could try disabling SSL verification and see if that resolves the issue. Note that it doesn't mean disabling SSL entirely, only the certificate verification.

Ideally of course it would verify the certificate, but I haven't had the time to come up with a proper fix.

**Comment by khanghuynh92** [comment]
@raj-shekhar1 I've got the same issue, Did you resolve it?
