### ISSUE TITLE
Errors after mix phx.server

### ISSUE THREAD

**Issue by thomas59553** [blockscout/blockscout#4728]
*Describe your issue here.*
errors when run blockscout
### Environment

 Erlang/OTP 24 [erts-12.0.3] [source] [64-bit] [smp:16:16] [ds:16:16:10] [async-threads:1] [jit]
Elixir 1.12.0 (compiled with Erlang/OTP 24)

* Operating System: ubuntu 20.04
* Blockscout Version/branch: 3.7.3 beta / Main

### Steps to reproduce

export SECRET_KEY_BASE=IkNPs5cIhJp7b6/x2xrG0m5NjIxcPIyBNFxM7eIZD+PO3JF7wOfBPKrYaZFGsclL
 export COIN=ZYN
 export SUBNETWORK=Mainet
 export NETWORK=Wethio
 export ETHEREUM_JSONRPC_HTTP_URL=http://192.168.1.2:8545
export ETHEREUM_JSONRPC_TRACE_URL=http://192.168.1.2:8545
export ETHEREUM_JSONRPC_WS_URL=ws://192.168.1.2:8546
 export DATABASE_URL=postgresql://dbusername:dbuserpassword@localhost:5432/blockscout
export ETHEREUM_JSONRPC_VARIANT=geth
 
 

node lunch with :
./zyn --datadir "/data" --keystore "/data/keystore/" --port 30306 --identity "annonymous" --syncmode "full" --gcmode "archive" --bootnodes enode://c88384d1eeea7a5db5fe0d317c3141f3d37a91017eae7c72aafe27852a98b76e7edfc4eab20bb2928f27a67e26049af7eb14139ca95dc6c22e1e993ed5b0691f@52.156.105.36:30301,enode://459ffb97de1fb30cebef4b6b43ba50a7d3dc1bf59b1c04804248e1ce2bd279ae9757d9bc4af9d78a85fd87bf4e6b3cbaa129e7cb6fdbc023998ac0a50fdef93e@52.156.152.177:30301,enode://e31050331e42fb3657a7546e64dd37b92aba51a051db2bd1ebcc9174dad2d951f7b553f21f3eeeeffa88390010e07b30ca2ef272dd2d7ab62a73467473f5be67@52.233.89.18:30301 --verbosity 3 --networkid 78    --rpc --rpccorsdomain "*" --rpcaddr 0.0.0.0 --rpcport 8545 --rpcvhosts "*"    --rpcapi "db,eth,net,web3,personal,debug,txpool"   --ws --wsapi "eth,net,web3,network,debug,txpool"   --wsaddr 0.0.0.0 --wsport 8546 --wsorigins "*" 
  

some test 
 **RPC ok:**
exp@explorer:~/blockscout$ curl --data '{"method":"eth_getBlockByNumber","params":["latest", false
> ],"id":1,"jsonrpc":"2.0"}' -H "Content-Type: application/json" -X POST http://192.168.1.2:8545
{"jsonrpc":"2.0","id":1,"result":{"difficulty":"0x50","extraData":"0xd783010503837a796e88676f312e31342e37856c696e757800000000000000005f63654407274c9987359e15bbbe0ca1c7dee32b66deb341b34e6d7fbf8fb5622973721fb04f6f1a2888fdf51e45924002410dabee453656e3b542327919fcee01","gasLimit":"0x501bd00","gasUsed":"0x0","hash":"0x9434fcf75942d0d3c352da40fcf0f042e79dc252857c6d7a81f9c24a9b2c4394","logsBloom":"0x00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000","miner":"0x0000000000000000000000000000000000000000","mixHash":"0x0000000000000000000000000000000000000000000000000000000000000000","nonce":"0x0000000000000000","number":"0x13b001c","parentHash":"0x2e0fbca1f45a0940e4b51362364c299b5f847a9695d76abef68dea337fd050b9","penalties":"0x","receiptsRoot":"0x56e81f171bcc55a6ff8345e692c0f86e5b48e01b996cadc001622fb5e363b421","sha3Uncles":"0x1dcc4de8dec75d7aab85b567b6ccd41ad312451b948a7413f0a142fd40d49347","size":"0x2a8","stateRoot":"0x73d4a0e8bfa922484392dcc5d5106c450894f68352338623635da8be707ca9a2","timestamp":"0x615f2c40","totalDifficulty":"0x4e39fab4","transactions":[],"transactionsRoot":"0x56e81f171bcc55a6ff8345e692c0f86e5b48e01b996cadc001622fb5e363b421","uncles":[],"validator":"0x61150685f056d575f22e246a17f1fe81f3882e78f5b051aba3a411276e8b4dc53f1606fe70d4a71c05e226e02ab7510cdf0f4deca9ab03896ccb6d8e0d4af26000","validators":"0x"}}
 
**verif login to database ok**

### Actual behaviour

exp@explorer:~/blockscout$ mix phx.server
2021-10-07T17:39:19.378 application=que [info] [Que] Booting Que
2021-10-07T17:39:19.378 application=que [info] [Que] Booting Server Supervisor for Workers
2021-10-07T17:39:19.560 application=phoenix [info] Running BlockScoutWeb.Endpoint with cowboy 2.9.0 at 0.0.0.0:4000 (http)
2021-10-07T17:39:19.564 application=phoenix [info] Running BlockScoutWeb.Endpoint with cowboy 2.9.0 at 0.0.0.0:4001 (https)
2021-10-07T17:39:19.564 application=phoenix [info] Access BlockScoutWeb.Endpoint at http://localhost:4001
2021-10-07T17:39:20.093 [error] Task #PID<0.1356.0> started from Indexer.Block.Realtime.Fetcher terminating
** (FunctionClauseError) no function clause matching in EthereumJSONRPC.Block.entry_to_elixir/1
    (ethereum_jsonrpc 0.1.0) EthereumJSONRPC.Block.entry_to_elixir({"penalties", "0x"})
    (elixir 1.12.0) lib/enum.ex:1473: anonymous fn/4 in Enum.into/3
    (stdlib 3.15.2) maps.erl:410: :maps.fold_1/3
    (elixir 1.12.0) lib/enum.ex:2368: Enum.into/4
    (elixir 1.12.0) lib/enum.ex:1553: Enum."-map/2-lists^map/1-0-"/2
    (ethereum_jsonrpc 0.1.0) lib/ethereum_jsonrpc/blocks.ex:44: EthereumJSONRPC.Blocks.from_responses/2
    (ethereum_jsonrpc 0.1.0) lib/ethereum_jsonrpc.ex:483: EthereumJSONRPC.fetch_blocks_by_params/3
    (indexer 0.1.0) lib/indexer/block/fetcher.ex:131: Indexer.Block.Fetcher.fetch_and_import_range/2
    (indexer 0.1.0) lib/indexer/block/realtime/fetcher.ex:284: Indexer.Block.Realtime.Fetcher.do_fetch_and_import_block/3
    (indexer 0.1.0) lib/indexer/logger.ex:14: Indexer.Logger.metadata/2
    (indexer 0.1.0) lib/indexer/block/realtime/fetcher.ex:267: Indexer.Block.Realtime.Fetcher.fetch_and_import_block/4
    (elixir 1.12.0) lib/task/supervised.ex:90: Task.Supervised.invoke_mfa/2
    (stdlib 3.15.2) proc_lib.erl:226: :proc_lib.init_p_do_apply/3
Function: &Indexer.Block.Realtime.Fetcher.fetch_and_import_block/3
    Args: [20644440, %Indexer.Block.Fetcher{broadcast: :realtime, callback_module: Indexer.Block.Realtime.Fetcher, json_rpc_named_arguments: [transport: EthereumJSONRPC.HTTP, transport_options: [http: EthereumJSONRPC.HTTP.HTTPoison, url: "http://192.168.1.2:8545", http_options: [recv_timeout: 60000, timeout: 60000, hackney: [pool: :ethereum_jsonrpc]]], variant: EthereumJSONRPC.Geth], receipts_batch_size: 250, receipts_concurrency: 10}, false]
2021-10-07T17:39:20.472 application=phoenix [info] CONNECTED TO BlockScoutWeb.UserSocket in 78µs
  Transport: :websocket
  Serializer: Phoenix.Socket.V2.JSONSerializer
  Parameters: %{"locale" => "en", "vsn" => "2.0.0"}
2021-10-07T17:39:22.032 [error] Task #PID<0.1368.0> started from Indexer.Block.Realtime.Fetcher terminating
** (FunctionClauseError) no function clause matching in EthereumJSONRPC.Block.entry_to_elixir/1
    (ethereum_jsonrpc 0.1.0) EthereumJSONRPC.Block.entry_to_elixir({"penalties", "0x"})
    (elixir 1.12.0) lib/enum.ex:1473: anonymous fn/4 in Enum.into/3
    (stdlib 3.15.2) maps.erl:410: :maps.fold_1/3
    (elixir 1.12.0) lib/enum.ex:2368: Enum.into/4
    (elixir 1.12.0) lib/enum.ex:1553: Enum."-map/2-lists^map/1-0-"/2
    (ethereum_jsonrpc 0.1.0) lib/ethereum_jsonrpc/blocks.ex:44: EthereumJSONRPC.Blocks.from_responses/2
    (ethereum_jsonrpc 0.1.0) lib/ethereum_jsonrpc.ex:483: EthereumJSONRPC.fetch_blocks_by_params/3
    (indexer 0.1.0) lib/indexer/block/fetcher.ex:131: Indexer.Block.Fetcher.fetch_and_import_range/2
    (indexer 0.1.0) lib/indexer/block/realtime/fetcher.ex:284: Indexer.Block.Realtime.Fetcher.do_fetch_and_import_block/3
    (indexer 0.1.0) lib/indexer/logger.ex:14: Indexer.Logger.metadata/2
    (indexer 0.1.0) lib/indexer/block/realtime/fetcher.ex:267: Indexer.Block.Realtime.Fetcher.fetch_and_import_block/4
    (elixir 1.12.0) lib/task/supervised.ex:90: Task.Supervised.invoke_mfa/2
    (stdlib 3.15.2) proc_lib.erl:226: :proc_lib.init_p_do_apply/3
Function: &Indexer.Block.Realtime.Fetcher.fetch_and_import_block/3
    Args: [20644441, %Indexer.Block.Fetcher{broadcast: :realtime, callback_module: Indexer.Block.Realtime.Fetcher, json_rpc_named_arguments: [transport: EthereumJSONRPC.HTTP, transport_options: [http: EthereumJSONRPC.HTTP.HTTPoison, url: "http://192.168.1.2:8545", http_options: [recv_timeout: 60000, timeout: 60000, hackney: [pool: :ethereum_jsonrpc]]], variant: EthereumJSONRPC.Geth], receipts_batch_size: 250, receipts_concurrency: 10}, false]
2021-10-07T17:39:24.068 [error] Task #PID<0.1375.0> started from Indexer.Block.Realtime.Fetcher terminating
** (FunctionClauseError) no function clause matching in EthereumJSONRPC.Block.entry_to_elixir/1
    (ethereum_jsonrpc 0.1.0) EthereumJSONRPC.Block.entry_to_elixir({"penalties", "0x"})
    (elixir 1.12.0) lib/enum.ex:1473: anonymous fn/4 in Enum.into/3
    (stdlib 3.15.2) maps.erl:410: :maps.fold_1/3
    (elixir 1.12.0) lib/enum.ex:2368: Enum.into/4
    (elixir 1.12.0) lib/enum.ex:1553: Enum."-map/2-lists^map/1-0-"/2
    (ethereum_jsonrpc 0.1.0) lib/ethereum_jsonrpc/blocks.ex:44: EthereumJSONRPC.Blocks.from_responses/2
    (ethereum_jsonrpc 0.1.0) lib/ethereum_jsonrpc.ex:483: EthereumJSONRPC.fetch_blocks_by_params/3
    (indexer 0.1.0) lib/indexer/block/fetcher.ex:131: Indexer.Block.Fetcher.fetch_and_import_range/2
    (indexer 0.1.0) lib/indexer/block/realtime/fetcher.ex:284: Indexer.Block.Realtime.Fetcher.do_fetch_and_import_block/3
    (indexer 0.1.0) lib/indexer/logger.ex:14: Indexer.Logger.metadata/2
    (indexer 0.1.0) lib/indexer/block/realtime/fetcher.ex:267: Indexer.Block.Realtime.Fetcher.fetch_and_import_block/4
    (elixir 1.12.0) lib/task/supervised.ex:90: Task.Supervised.invoke_mfa/2
    (stdlib 3.15.2) proc_lib.erl:226: :proc_lib.init_p_do_apply/3
Function: &Indexer.Block.Realtime.Fetcher.fetch_and_import_block/3
    Args: [20644442, %Indexer.Block.Fetcher{broadcast: :realtime, callback_module: Indexer.Block.Realtime.Fetcher, json_rpc_named_arguments: [transport: EthereumJSONRPC.HTTP, transport_options: [http: EthereumJSONRPC.HTTP.HTTPoison, url: "http://192.168.1.2:8545", http_options: [recv_timeout: 60000, timeout: 60000, hackney: [pool: :ethereum_jsonrpc]]], variant: EthereumJSONRPC.Geth], receipts_batch_size: 250, receipts_concurrency: 10}, false]
2021-10-07T17:39:26.019 [error] Task #PID<0.1382.0> started from Indexer.Block.Realtime.Fetcher terminating
** (FunctionClauseError) no function clause matching in EthereumJSONRPC.Block.entry_to_elixir/1
    (ethereum_jsonrpc 0.1.0) EthereumJSONRPC.Block.entry_to_elixir({"penalties", "0x"})
    (elixir 1.12.0) lib/enum.ex:1473: anonymous fn/4 in Enum.into/3
    (stdlib 3.15.2) maps.erl:410: :maps.fold_1/3
    (elixir 1.12.0) lib/enum.ex:2368: Enum.into/4
    (elixir 1.12.0) lib/enum.ex:1553: Enum."-map/2-lists^map/1-0-"/2
    (ethereum_jsonrpc 0.1.0) lib/ethereum_jsonrpc/blocks.ex:44: EthereumJSONRPC.Blocks.from_responses/2
    (ethereum_jsonrpc 0.1.0) lib/ethereum_jsonrpc.ex:483: EthereumJSONRPC.fetch_blocks_by_params/3
    (indexer 0.1.0) lib/indexer/block/fetcher.ex:131: Indexer.Block.Fetcher.fetch_and_import_range/2
    (indexer 0.1.0) lib/indexer/block/realtime/fetcher.ex:284: Indexer.Block.Realtime.Fetcher.do_fetch_and_import_block/3
    (indexer 0.1.0) lib/indexer/logger.ex:14: Indexer.Logger.metadata/2
    (indexer 0.1.0) lib/indexer/block/realtime/fetcher.ex:267: Indexer.Block.Realtime.Fetcher.fetch_and_import_block/4
    (elixir 1.12.0) lib/task/supervised.ex:90: Task.Supervised.invoke_mfa/2
    (stdlib 3.15.2) proc_lib.erl:226: :proc_lib.init_p_do_apply/3
Function: &Indexer.Block.Realtime.Fetcher.fetch_and_import_block/3
    Args: [20644443, %Indexer.Block.Fetcher{broadcast: :realtime, callback_module: Indexer.Block.Realtime.Fetcher, json_rpc_named_arguments: [transport: EthereumJSONRPC.HTTP, transport_options: [http: EthereumJSONRPC.HTTP.HTTPoison, url: "http://192.168.1.2:8545", http_options: [recv_timeout: 60000, timeout: 60000, hackney: [pool: :ethereum_jsonrpc]]], variant: EthereumJSONRPC.Geth], receipts_batch_size: 250, receipts_concurrency: 10}, false]

.....
unction: &Indexer.Block.Realtime.Fetcher.fetch_and_import_block/3
    Args: [20644547, %Indexer.Block.Fetcher{broadcast: :realtime, callback_module: Indexer.Block.Realtime.Fetcher, json_rpc_named_arguments: [transport: EthereumJSONRPC.HTTP, transport_options: [http: EthereumJSONRPC.HTTP.HTTPoison, url: "http://192.168.1.2:8545", http_options: [recv_timeout: 60000, timeout: 60000, hackney: [pool: :ethereum_jsonrpc]]], variant: EthereumJSONRPC.Geth], receipts_batch_size: 250, receipts_concurrency: 10}, false]
2021-10-07T17:42:56.029 [error] Task #PID<0.1639.0> started from Indexer.Block.Realtime.Fetcher terminating
** (FunctionClauseError) no function clause matching in EthereumJSONRPC.Block.entry_to_elixir/1
    (ethereum_jsonrpc 0.1.0) EthereumJSONRPC.Block.entry_to_elixir({"penalties", "0x"})
    (elixir 1.12.0) lib/enum.ex:1473: anonymous fn/4 in Enum.into/3
    (stdlib 3.15.2) maps.erl:410: :maps.fold_1/3
    (elixir 1.12.0) lib/enum.ex:2368: Enum.into/4
    (elixir 1.12.0) lib/enum.ex:1553: Enum."-map/2-lists^map/1-0-"/2
    (ethereum_jsonrpc 0.1.0) lib/ethereum_jsonrpc/blocks.ex:44: EthereumJSONRPC.Blocks.from_responses/2
    (ethereum_jsonrpc 0.1.0) lib/ethereum_jsonrpc.ex:483: EthereumJSONRPC.fetch_blocks_by_params/3
    (indexer 0.1.0) lib/indexer/block/fetcher.ex:131: Indexer.Block.Fetcher.fetch_and_import_range/2
    (indexer 0.1.0) lib/indexer/block/realtime/fetcher.ex:284: Indexer.Block.Realtime.Fetcher.do_fetch_and_import_block/3
    (indexer 0.1.0) lib/indexer/logger.ex:14: Indexer.Logger.metadata/2
    (indexer 0.1.0) lib/indexer/block/realtime/fetcher.ex:267: Indexer.Block.Realtime.Fetcher.fetch_and_import_block/4
    (elixir 1.12.0) lib/task/supervised.ex:90: Task.Supervised.invoke_mfa/2
    (stdlib 3.15.2) proc_lib.erl:226: :proc_lib.init_p_do_apply/3
Function: &Indexer.Block.Realtime.Fetcher.fetch_and_import_block/3
    Args: [20644548, %Indexer.Block.Fetcher{broadcast: :realtime, callback_module: Indexer.Block.Realtime.Fetcher, json_rpc_named_arguments: [transport: EthereumJSONRPC.HTTP, transport_options: [http: EthereumJSONRPC.HTTP.HTTPoison, url: "http://192.168.1.2:8545", http_options: [recv_timeout: 60000, timeout: 60000, hackney: [pool: :ethereum_jsonrpc]]], variant: EthereumJSONRPC.Geth], receipts_batch_size: 250, receipts_concurrency: 10}, false]
2021-10-07T17:42:58.019 [error] Task #PID<0.1646.0> started from Indexer.Block.Realtime.Fetcher terminating
** (FunctionClauseError) no function clause matching in EthereumJSONRPC.Block.entry_to_elixir/1
    (ethereum_jsonrpc 0.1.0) EthereumJSONRPC.Block.entry_to_elixir({"penalties", "0x"})
    (elixir 1.12.0) lib/enum.ex:1473: anonymous fn/4 in Enum.into/3
    (stdlib 3.15.2) maps.erl:410: :maps.fold_1/3
    (elixir 1.12.0) lib/enum.ex:2368: Enum.into/4
    (elixir 1.12.0) lib/enum.ex:1553: Enum."-map/2-lists^map/1-0-"/2
    (ethereum_jsonrpc 0.1.0) lib/ethereum_jsonrpc/blocks.ex:44: EthereumJSONRPC.Blocks.from_responses/2
    (ethereum_jsonrpc 0.1.0) lib/ethereum_jsonrpc.ex:483: EthereumJSONRPC.fetch_blocks_by_params/3
    (indexer 0.1.0) lib/indexer/block/fetcher.ex:131: Indexer.Block.Fetcher.fetch_and_import_range/2
    (indexer 0.1.0) lib/indexer/block/realtime/fetcher.ex:284: Indexer.Block.Realtime.Fetcher.do_fetch_and_import_block/3
    (indexer 0.1.0) lib/indexer/logger.ex:14: Indexer.Logger.metadata/2
    (indexer 0.1.0) lib/indexer/block/realtime/fetcher.ex:267: Indexer.Block.Realtime.Fetcher.fetch_and_import_block/4
    (elixir 1.12.0) lib/task/supervised.ex:90: Task.Supervised.invoke_mfa/2
    (stdlib 3.15.2) proc_lib.erl:226: :proc_lib.init_p_do_apply/3
Function: &Indexer.Block.Realtime.Fetcher.fetch_and_import_block/3
    Args: [20644549, %Indexer.Block.Fetcher{broadcast: :realtime, callback_module: Indexer.Block.Realtime.Fetcher, json_rpc_named_arguments: [transport: EthereumJSONRPC.HTTP, transport_options: [http: EthereumJSONRPC.HTTP.HTTPoison, url: "http://192.168.1.2:8545", http_options: [recv_timeout: 60000, timeout: 60000, hackney: [pool: :ethereum_jsonrpc]]], variant: EthereumJSONRPC.Geth], receipts_batch_size: 250, receipts_concurrency: 10}, false]

....

Retrying.
2021-10-07T17:43:28.189 application=indexer fetcher=block_catchup first_block_number=20547728 last_block_number=20547719 [error] ** (FunctionClauseError) no function clause matching in EthereumJSONRPC.Block.entry_to_elixir/1
    (ethereum_jsonrpc 0.1.0) EthereumJSONRPC.Block.entry_to_elixir({"penalties", "0x"})
    (elixir 1.12.0) lib/enum.ex:1473: anonymous fn/4 in Enum.into/3
    (stdlib 3.15.2) maps.erl:410: :maps.fold_1/3
    (elixir 1.12.0) lib/enum.ex:2368: Enum.into/4
    (elixir 1.12.0) lib/enum.ex:1553: Enum."-map/2-lists^map/1-0-"/2
    (ethereum_jsonrpc 0.1.0) lib/ethereum_jsonrpc/blocks.ex:44: EthereumJSONRPC.Blocks.from_responses/2
    (ethereum_jsonrpc 0.1.0) lib/ethereum_jsonrpc.ex:483: EthereumJSONRPC.fetch_blocks_by_params/3
    (indexer 0.1.0) lib/indexer/block/fetcher.ex:131: Indexer.Block.Fetcher.fetch_and_import_range/2
    (indexer 0.1.0) lib/indexer/block/catchup/fetcher.ex:192: Indexer.Block.Catchup.Fetcher.fetch_and_import_range_from_sequence/3
    (elixir 1.12.0) lib/task/supervised.ex:90: Task.Supervised.invoke_mfa/2
    (elixir 1.12.0) lib/task/supervised.ex:35: Task.Supervised.reply/5
    (stdlib 3.15.2) proc_lib.erl:226: :proc_lib.init_p_do_apply/3

Retrying.
2021-10-07T17:43:28.189 application=indexer fetcher=block_catchup first_block_number=20547628 last_block_number=20547619 [error] ** (FunctionClauseError) no function clause matching in EthereumJSONRPC.Block.entry_to_elixir/1
    (ethereum_jsonrpc 0.1.0) EthereumJSONRPC.Block.entry_to_elixir({"penalties", "0x"})
    (elixir 1.12.0) lib/enum.ex:1473: anonymous fn/4 in Enum.into/3
    (stdlib 3.15.2) maps.erl:410: :maps.fold_1/3
    (elixir 1.12.0) lib/enum.ex:2368: Enum.into/4
    (elixir 1.12.0) lib/enum.ex:1553: Enum."-map/2-lists^map/1-0-"/2
    (ethereum_jsonrpc 0.1.0) lib/ethereum_jsonrpc/blocks.ex:44: EthereumJSONRPC.Blocks.from_responses/2
    (ethereum_jsonrpc 0.1.0) lib/ethereum_jsonrpc.ex:483: EthereumJSONRPC.fetch_blocks_by_params/3
    (indexer 0.1.0) lib/indexer/block/fetcher.ex:131: Indexer.Block.Fetcher.fetch_and_import_range/2
    (indexer 0.1.0) lib/indexer/block/catchup/fetcher.ex:192: Indexer.Block.Catchup.Fetcher.fetch_and_import_range_from_sequence/3
    (elixir 1.12.0) lib/task/supervised.ex:90: Task.Supervised.invoke_mfa/2
    (elixir 1.12.0) lib/task/supervised.ex:35: Task.Supervised.reply/5
    (stdlib 3.15.2) proc_lib.erl:226: :proc_lib.init_p_do_apply/3

Retrying.
^C
BREAK: (a)bort (A)bort with dump (c)ontinue (p)roc info (i)nfo
       (l)oaded (v)ersion (k)ill (D)b-tables (d)istribution

**Comment by vbaranov** [comment]
Since you're using a custom archive node you should ignore custom block properties by adding them here https://github.com/blockscout/blockscout/blob/5586497db0c194938025df7b76e62fcdc55232cc/apps/ethereum_jsonrpc/lib/ethereum_jsonrpc/block.ex#L590.

**Comment by thomas59553** [comment]
thanks you , this step work now, but i have other issue now
i write new post to explain it
