### ISSUE TITLE
Ethereum Classic: Metamask with ETC blockscout does not work

### ISSUE THREAD

**Issue by resilience-me** [blockscout/blockscout#4731]
*Describe your issue here.*

blockscout.com has an ETC blockexplorer on blockscout.com/etc/mainnet. But when trying to access contracts through it, and using the /write-contract tab, with a Metamask that is connected to Ethereum Classic as well, I get error message and it does not work:

>_ "Unauthorized. You connected to Ethereum Classic chain in the wallet, but the current instance of Blockscout is for Ethereum chain. "_

Is this a known issue? Any plans to fix it?

### Environment
* Elixir Version: 1.11.4
* Erlang Version: 23
* BlockScout Version: v3.7.3-beta

* User Agent: `Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/94.0.4606.61 Safari/537.36`

### Steps to reproduce

*Tell us how to reproduce this issue. If possible, push up a branch to your fork with a regression test we can run to reproduce locally.*

### Expected Behaviour

*Tell us what should happen.*

### Actual Behaviour

*Tell us what happens instead.*

**Comment by vbaranov** [comment]
Thanks for bringing this up. The issue has been resolved.

**Comment by ndnam90** [comment]
Hi @vbaranov, how to resolve this issue, I have same issue in local with ganache

**Comment by rongyi** [comment]
thanks @ndnam90
