### ISSUE TITLE
Optimization runs type ( PostgresSQL binding) is too low, must be UINT32 or more

### ISSUE THREAD

**Issue by fenicks** [blockscout/blockscout#4756]
When  trying to verify a smarcontract in Blockscout with a valid Optimization runs params, an exception arise.

### Environment

Current Avalanche C-chain explorer

### Steps to reproduce

* Compile a smartconract with `Optimization runs` param set to `4294967295`.
* Verify the source with sourcify.dev.
* Use Blockscout verification tool add the link the verified code with the smartcontract.

### Expected behaviour

Expect that the contract code is inserted in PostgreSQL database and Blockscout shows the code.

### Actual behaviour

An exception is raised because the value `4294967295` is greater than an int32. But this value is compliant with the solidity compilation params.

![image](https://user-images.githubusercontent.com/336317/137040682-2e682b85-1b3b-433f-be1f-dd7427517a59.png)

**Comment by vbaranov** [comment]
It sounds like we need to extend DB column type for optimization runs prop to `bigint`
