### ISSUE TITLE
Constructor arguments do not match, please try again.

### ISSUE THREAD

**Issue by vbaranov** [blockscout/blockscout#4758]
> I tried to verify&publish the source code for https://blockscout.com/xdai/mainnet/address/0xe324F36B72EF7cA7ba67492f9D82590941412529/contracts but it fails, even though it's the same contract creation as over on our test setup at https://goerli.etherscan.io/address/0xe324f36b72ef7ca7ba67492f9d82590941412529#code where it succeeded, and I used the same code etc. to do the verification.
<img width="1106" alt="Screenshot 2021-10-13 at 08 30 27" src="https://user-images.githubusercontent.com/4341812/137073011-eb189288-b5b4-486a-9b5f-ac7381dbf96a.png">

We need to check the procedure of constructor arguments verification. Even with automatic detection of constructor arguments, Blockscout hits this error message.

**Comment by KaiRo-at** [comment]
I can confirm that this works now, that a lot!
