### ISSUE TITLE
Brave: Blockscout throws constant "change account" error. refuses to load staking page on xDai

### ISSUE THREAD

**Issue by 0xMrMittens** [blockscout/blockscout#4765]
I go to the Blockscout staking page on xDai > connect to xDai RPC > toggle to the wallet that has deposited STAKE > the page says "loading" for about 10 seconds, then chronically throws up the below error. It started as just an issue on Brave browser, but now it happens on Firefox too. I refresh the page, clear cache, cookies, click around to different pages on Blockscout, etc. and it often refuses to load. I'm talking 50+ attempts at refreshing, reloading, etc.

error image: https://cdn.discordapp.com/attachments/502432256011272195/898055325175906324/unknown.png

Thank you for your review and help.

**Comment by 0xMrMittens** [comment]
MetaMask Version
10.3.0

this is still an issue and has precluded me from claiming rewards. it is refusing to let me access and withdraw rewards or my staked amounts.

**Comment by vbaranov** [comment]
Closing this since Staking dApp is not functional anymore.
