### ISSUE TITLE
Energy Web Chain: <EWT not arrived>

### ISSUE THREAD

**Issue by sunster5** [blockscout/blockscout#4769]
Hi,
I recently bought EWT from Kraken and sent it to my EWT Ellipal address which is under Ethereum.
However, i dont see it in my wallet but the transaction went ok.

TID - 0x3aacd87c22fc27ade7835889fa480e98eb693bbbc28128455a08a99314a28f6d
Ellipal EWT Address - 0xaba112a47f247b0a2179fb67b0e036c2965eaa84

Can you advise why i dont see it in my ellipal account.

Thanks
adnan

### Environment
* Elixir Version: 1.11.4
* Erlang Version: 23
* BlockScout Version: v3.7.3-beta

* User Agent: `Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/94.0.4606.81 Safari/537.36`

### Steps to reproduce

*Tell us how to reproduce this issue. If possible, push up a branch to your fork with a regression test we can run to reproduce locally.*

### Expected Behaviour

*Tell us what should happen.*

### Actual Behaviour

*Tell us what happens instead.*

**Comment by vbaranov** [comment]
You should ask exchange support team.
