### ISSUE TITLE
Internal Server Error

### ISSUE THREAD

**Issue by TriptonPt** [blockscout/blockscout#4787]
*Describe your issue here.*

### Steps to reproduce

https://blockscout.com/eth/mainnet/tx/0xd93da3756b6336573a2165a89a9881a302143fc53ca3b8792c65eef930fa5461/internal-transactions

https://blockscout.com/eth/mainnet/address/0xf617945ba0a2179fb2a68e7fd1e5fd0f12041b50/contracts

### Expected behaviour

Both pages should provide details for each tx and contract respectively .

### Actual behaviour

All of these lead to an Internal Server Error

**Comment by vbaranov** [comment]
Internal server error on the contracts, mentioned in the issue, doesn't happen anymore. Please re-open if you have more examples.
