### ISSUE TITLE
Ethereum Classic: <Issue Title>

### ISSUE THREAD

**Issue by Javed7766** [blockscout/blockscout#4788]
I had transferred $700 AUD from ethereum classic to smart chain but. But transaction shows successful but I it doesnt reflect on my BNB SMART chain balance please help me out.

My email address is javed_pasha
![Screenshot_20211020-032730_Samsung Internet](https://user-images.githubusercontent.com/92811689/137952786-20f1bf53-a6ba-49a6-8877-db1367bddbdf.jpg)
![Screenshot_20211020-032730_Samsung Internet](https://user-images.githubusercontent.com/92811689/137952825-b2a9ef08-a4b7-4c80-8d96-e3bed9a35658.jpg)
81@yahoo.com

**Comment by vbaranov** [comment]
You should contact exchange support
