### ISSUE TITLE
docker build error

### ISSUE THREAD

**Issue by fenQY** [blockscout/blockscout#4808]
when I run it with docker break this error:

==> block_scout
** (Mix) Could not compile dependency :prometheus_process_collector, "/opt/mix/rebar3 bare compile --paths /opt/app/_build/prod/lib/*/ebin" command failed. You can recompile this dependency with "mix deps.compile prometheus_process_collector", update it with "mix deps.update prometheus_process_collector" or clean it with "mix deps.clean prometheus_process_collector"
The command '/bin/sh -c mix do deps.get, local.rebar --force, deps.compile' returned a non-zero code: 1
make: *** [build] error 1

**Comment by pynixwang** [comment]
@ngdlong91 why?

**Comment by vbaranov** [comment]
Please re-open if the issue still exists with the latest version of the application.
