### ISSUE TITLE
NFT: Missing token holders & token transfers

### ISSUE THREAD

**Issue by vbaranov** [blockscout/blockscout#4825]
Copied from Discord:

hello everyone, i am experiencing what seems to be a blockscout bug dealing with xDAI ERC-1155 NFTs
i was directed to ask here about it
when i look at the token ID specific page for any of my NFTs on xDAI BlockScout i only see RECENT history so far as transfers, and an incomplete list of current token holders

for example :

https://blockscout.com/xdai/mainnet/token/0x761dfbcba5a43eaf02dc8b2210d83b2ddf9f2e95/instance/25/token-transfers 2

this page only shows 2 token holders and 2 transactions, but it’s a fact i’ve sold 5 of these to different wallets via Unifty.com = the history is not complete.

pages for my other other NFTs / token IDs = the same, only showing recent history and an incomplete list of token holders

thinking surely displaying complete history = the intended BlockScout functionality ? def needing / desiring complete histories & holder lists 

possibly relevant : once did a mass nft distribution to 1600 wallets, so this wallet may have above average transaction history & holder depth

**Comment by iofthebehodler** [comment]
anyone have time to look into this ? 

Epor.io nft platform is able to display complete histories and holder lists for NFT token ID pages where the blockscout version shows an incomplete / truncated history and holder list. 

still suspecting it may have something to do with an NFT mass distribution to 1600 wallets this contract did around march 23, 2021

**Comment by iofthebehodler** [comment]
here's an example : 

EPOR.IO page for token ID 15
https://epor.io/tokens/0x761dfbcba5a43eaf02dc8b2210d83b2ddf9f2e95/15

- we can see in the history section 6 buy transactions
- this token also has 5 editions in my minting wallet and 1 in my unifty shop contract
- history is complete 
- all holders accounted for

BLOCKSCOUT page for the same token ID 15
https://blockscout.com/xdai/mainnet/token/0x761dFbCBa5A43eAF02dc8B2210D83B2ddf9F2E95/instance/15/token-holders

- shows only 2 transactions
- shows only 3 holders

**Comment by skenaja** [comment]
Similar issue seen on Palm network, with over 800k missing token transfers for a number of ERC-1155 tokens.

example token - 900k transfers made over several months, only 100k recorded in the explorer:
https://explorer.palm.io/token/0x19D4F9A260AF1d7E0E99A32DBe418956af875c25/token-transfers

example of a `transferSingle` event emitted for this ERC-1155 token:
https://explorer.palm.io/tx/0xe241f4f5e29fbe31bf0754cab72aa404ac5725e50e56fedc33d17e5bd96a0121/logs

token ID 78007746218579398377654237264702369096541305845811984373025271426372627852568 minted

404 page for that token ID:
https://explorer.palm.io/token/0x19d4f9a260af1d7e0e99a32dbe418956af875c25/instance/78007746218579398377654237264702369096541305845811984373025271426372627852568/token-transfers

0 rows in `pending_block_operations`.

@vbaranov Is there a way we could reindex older blocks to try to fill these gaps?

**Comment by vbaranov** [comment]
There was a delay in indexing a part of the chain in the explorer. Currently, all missed blocks and their data have been successfully processed and should be available via API. I see, that the number of holders of the token instance from the issue has an equal number of holders compared to gnosisscan. I am closing this issue for now.
