### ISSUE TITLE
BD from RDS

### ISSUE THREAD

**Issue by damianlluch** [blockscout/blockscout#4832]
Hi, we have an instance on AWS and would like to have the DB separately, say on an RDS instance.
The question is, does it improve performance?
I have not found in the issues comments about this.
We want to do this as we have had the EC2 instance suddenly go down, and we think it might improve performance to have the DB separately.
Now we have tried this, but there are questions regarding environment variables.
What can an RDS DB be called?

For the postgres DB that we have in the same instance, we have this variable as indicated in the documentation:

```
export DATABASE_URL=postgresql://user:password@localhost:5432/blockscout
```
But with RDS how would it be?

I tried this in my .bashrc, but it didn't work:
```
PGHOST="urlDatabase"
PGPORT=5432
PGDATABASE=blockscout
PGUSER=user
PGPASSWORD=password
```

thanks!!!!!

**Comment by damianlluch** [comment]
@vbaranov It doesn't work, it says the URL is invalid. That's why I'm asking if anyone has an example. And I would like to know if it increases performance.

**Comment by vbaranov** [comment]
What do you mean by URL is invalid? Can you connect to the RDS instance from the application server with pSQL and connection string from DATABASE_URL? If, no, the connection string is wrong then.

**Comment by damianlluch** [comment]
If the URL of the environment variable is changed to a URL of the RDS, an error occurs...Elixir returns that the URL is i

**Comment by vbaranov** [comment]
Can you connect to the DB from the application server with psql using that connection string?
