### ISSUE TITLE
Internal transaction list is broken(displays same internal transactions on page 1 and page 2) on transaction page - Pagination Issue

### ISSUE THREAD

**Issue by rohitsethii** [blockscout/blockscout#4834]
*Internal Transactions are not paging correctly on the transaction page but working fine on the address page.*

For instance: This transaction on ethereum mainnet shows same internal transactions on page 1 and page 2 https://blockscout.com/eth/mainnet/tx/0xa9a1b8ea288eb9ad315088f17f7c7386b9989c95b4d13c81b69d5ddad7ffe61e/internal-transactions 

And the contract page shows all the internal transactions that happened in the above transaction(0xa9a1b8ea288eb9ad315088f17f7c7386b9989c95b4d13c81b69d5ddad7ffe61e) including an internal transaction with the transfer of 355 ethers(missing on the above-mentioned transaction page).
Contract page: https://blockscout.com/eth/mainnet/address/0x38c40427efbAAe566407e4CdE2A91947dF0bD22B/internal-transactions

**Comment by zalam003** [comment]
@nikitosing @vbaranov We are currently testing a fix in a [test environment]( http://testnet.energi.cloudns.cl:4000/).

All the internal transactions are now reflecting properly under the "_Internal Transaction_" tab of the transaction page.

For ex:

- For [this transaction](http://testnet.energi.cloudns.cl:4000/tx/0x75bfcf8cca184a1c69d26c0e4db1d1e52376ecaf33c7d644771e16110e9af088/internal-transactions), internal tx of 0.006 NRG in now visible on [test enevironment](http://testnet.energi.cloudns.cl:4000) but missing on [testnet](https://explorer.test.energi.network)

- For [another transaction](http://testnet.energi.cloudns.cl:4000/tx/0x601a6c731297ba7d9f47552ba8b86902402509cb474d714710e39653e1fec35c/internal-transactions) with 120 internal txs of 1,2,3,4......120 wei , all the internal txs are now visible on [test enevironment](http://testnet.energi.cloudns.cl:4000) but only 50 internal txs (repeated on page 2) are displayed on [testnet](https://explorer.test.energi.network)
