### ISSUE TITLE
Palm: <unable to move nft from candy and palm to metamask wallet>

### ISSUE THREAD

**Issue by praxis9061** [blockscout/blockscout#4837]
followed instructions to configure metamask to palm (adding network).
used palm safe transfer feature (number 9) to do transfer and it says it doesn't work on scout network.
can't figure out how to move my mlb candy nft off palm to my metamask wallet.
*Describe your issue here.*

### Environment
* Elixir Version: 1.12.2
* Erlang Version: 24
* BlockScout Version: 

* User Agent: `Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:93.0) Gecko/20100101 Firefox/93.0`

### Steps to reproduce

*Tell us how to reproduce this issue. If possible, push up a branch to your fork with a regression test we can run to reproduce locally.*

### Expected Behaviour

*Tell us what should happen.*

### Actual Behaviour

*Tell us what happens instead.*

**Comment by vbaranov** [comment]
Palm instance is not supported here. Please, reach out the team directly.
