### ISSUE TITLE
Blockscout was not able to write media file for NFT instance to a temp path

### ISSUE THREAD

**Issue by lemonsuy** [blockscout/blockscout#4838]
Blockscout was not able to write a media file for the NFT instance to a temp path in order to get its MIME type and throw the internal server error on the web page

### Environment

* Elixir & Erlang/OTP versions: 1.11.4
* Operating System: Docker container (host on: Ubuntu 20.04)
* Blockscout Version/branch:  v3.6.0-beta 

### Steps to reproduce
1. Add metadata to the ERC-721 token (include ipfs URL)
2. Click on the token-id of ERC-721 token on blockscout web page

### Expected behaviour
- The page show the token instance information (e.g. metadata)

### Actual behaviour
- The page is empty and throws the "Internal server error" message

**Comment by lemonsuy** [comment]
Error in the log 
![Screen Shot 2564-10-25 at 14 14 40](https://user-images.githubusercontent.com/24906502/139628299-1e7e3ad3-5da7-4d0b-86cb-80712049acf4.png)

Error when clicking on the token-id
![Screen Shot 2564-11-01 at 13 02 33](https://user-images.githubusercontent.com/24906502/139628422-6aba652b-43f6-4d8a-8499-153d5f21a11a.png)

**Comment by vbaranov** [comment]
@lemonsuy would you copy/paste image URL here. It is hard to retype from the screenshot. Thanks in advance.

**Comment by lemonsuy** [comment]
> @lemonsuy would you copy/paste image URL here. It is hard to retype from the screenshot. Thanks in advance.
URL: https://bkcscan.com/tokens/0xd08ac40b3a0a7fb20b026a3b6cd5d7cfadc3d6f5/instance/49317437834419531530470213658769379617173560208869835463042618518520463360/token-transfers

Image URL: https://ipfs.morningmoonvillage.com/ipfs/QmPbYRQDTkScmk31HZCJEYtzobK9wWKky9wDmzgdVHf8rm

**Comment by lemonsuy** [comment]
@vbaranov  I already found the root cause of this issues.
It's because the Dockerfile of blockscout version 3.6.0-beta (https://github.com/blockscout/blockscout/blob/v3.6.0-beta/docker/Dockerfile) doesn't have module "file" installed but the blockscout is try to use "file" command inside the container to write the image file.

The solution is to add "file" module inside the Dockerfile it's solved the problem!

**Comment by vbaranov** [comment]
@lemonsuy there is no function, which causes an error in your case, in the 3.6.0 release. It was introduced in 3.7.1. Here is the related commit https://github.com/blockscout/blockscout/commit/cce0dd7526f77dbfaf322b1ba92056ffb3379166#diff-f34da55ca08f1a30591d8b0b3e885bcc678537b2a9a4aadea4f190806b374ddc, where the `file` module added to Dockerfile. Probably, you partially took the commit to your customized instance.
