### ISSUE TITLE
Support of timestampNano

### ISSUE THREAD

**Issue by dcnl1980** [blockscout/blockscout#4848]
We created an own private blockchain with timestamp and timestampnano in the getBlock function, see the output:

`difficulty: 0,
  extraData: "0x",
  gasLimit: 281474976710655,
  gasUsed: 1769759,
  hash: "0x00000001000000012f669eac7dff4ec8e49d9294a8cc3096410c8bd33bb7ebe5",
  logsBloom: "0x04001000000000000000000080002000000000000000004000800000000000000000020000010000000202000400000000000000020000001000000000040008000000000000000000000000000000000001000000040008200000000000000000000000020000000000000000000800000000100000040000000000000000400000000040800000000000000000000000000000000000000000001000000000000000000000004000040100000000000000010000800000000000000000400000000004000000000000000000010000000000000400000000002002000060014200000000004000000000100000200004000000008080004100000000000000",
  miner: "0x0000000000000000000000000000000000000000",
  mixHash: "0x0000000000000000000000000000000000000000000000000000000000000000",
  nonce: "0x0000000000000000",
  number: 1,
  parentHash: "0x0000000000000000000000000000000000000000000000000000000000000000",
  receiptsRoot: "0x0000000000000000000000000000000000000000000000000000000000000000",
  sha3Uncles: "0x1dcc4de8dec75d7aab85b567b6ccd41ad312451b948a7413f0a142fd40d49347",
  size: 3588,
  stateRoot: "0x352a6c54a5a770dc6d79d807064b57490f5dd7746753605f365b750dcacc5f71",
  **timestamp: 1608600000,
  timestampNano: 1608600000000000000,**`

While running blockscout we got the following error:

`explorer_1  | 2021-11-02T17:17:08.935 application=indexer fetcher=block_catchup first_block_number=13291 last_block_number=13282 [error] ** (FunctionClauseError) no function clause matching in EthereumJSONRPC.Block.entry_to_elixir/1
explorer_1  |     (ethereum_jsonrpc) lib/ethereum_jsonrpc/block.ex:439: EthereumJSONRPC.Block.entry_to_elixir({"timestampNano", "0x16b335261746a580"})
explorer_1  |     (elixir) lib/map.ex:210: Map.new_transform/3
explorer_1  |     (elixir) lib/enum.ex:1327: Enum."-map/2-lists^map/1-0-"/2
explorer_1  |     (ethereum_jsonrpc) lib/ethereum_jsonrpc/blocks.ex:44: EthereumJSONRPC.Blocks.from_responses/2
explorer_1  |     (ethereum_jsonrpc) lib/ethereum_jsonrpc.ex:452: EthereumJSONRPC.fetch_blocks_by_params/3
explorer_1  |     (indexer) lib/indexer/block/fetcher.ex:127: Indexer.Block.Fetcher.fetch_and_import_range/2
explorer_1  |     (indexer) lib/indexer/block/catchup/fetcher.ex:187: Indexer.Block.Catchup.Fetcher.fetch_and_import_range_from_sequence/3
explorer_1  |     (elixir) lib/task/supervised.ex:90: Task.Supervised.invoke_mfa/2
explorer_1  | 
explorer_1  | 
explorer_1  | Retrying.`

How can we add timestampNano to the elixir entry?

**Comment by vbaranov** [comment]
You should add all custom props in the response of eth_getBlockByNumber request to this line https://github.com/blockscout/blockscout/blob/f94f79aebb295aeb056a0c13f77bc0a37b7674cb/apps/ethereum_jsonrpc/lib/ethereum_jsonrpc/block.ex#L575 in order to eliminate the error
