### ISSUE TITLE
Ethereum Classic: retrive my tokens

### ISSUE THREAD

**Issue by ColgaNRG** [blockscout/blockscout#4864]
*Describe your issue here.*
HELP! SOS HELP!
I have transfered my ETC to BNB Smart chain. My tokens bo! nced to etherscan i want all my tokens back. How do I do this? Can you plz help me to reyrive my tokens back to my trust wallet.

### Environment
* Elixir Version: 1.11.4
* Erlang Version: 23
* BlockScout Version: v3.7.3-beta

* User Agent: `Mozilla/5.0 (Linux; Android 11; SM-G996B) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/94.0.4606.85 Mobile Safari/537.36`

### Steps to reproduce

*Tell us how to reproduce this issue. If possible, push up a branch to your fork with a regression test we can run to reproduce locally.*

### Expected Behaviour

*Tell us what should happen.*

### Actual Behaviour

*Tell us what happens instead.*

**Comment by ColgaNRG** [comment]
Ate you for real? I am asking uou for help, so that I can retrive my tokens stolen from me. I wNt them sent back to my trust wallet. Mot once did i give thdn to etherscn to stedl them

Sent on the go with Vodafone
Get Outlook for Android<https://aka.ms/ghei36>
________________________________

**Comment by vbaranov** [comment]
This tracker is for technical support of Blockscout. There is no ETC support here. You should reach out ETC, for instance, in Discord https://discord.com/invite/hQs894U.
