### ISSUE TITLE
POA: <Issue Title>how to transfer token to exchange 

### ISSUE THREAD

**Issue by wahabbaloch** [blockscout/blockscout#4865]
![WhatsApp Image 2021-11-07 at 10 50 56 AM](https://user-images.githubusercontent.com/93856025/140635516-67b62ee9-cc22-4581-a1c0-01196284250c.jpeg)
*Describe your issue here.*

### Environment
* Elixir Version: 1.12.2
* Erlang Version: 24
* BlockScout Version: v3.7.3-beta

* User Agent: `Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4638.54 Safari/537.36`

### Steps to reproduce

*Tell us how to reproduce this issue. If possible, push up a branch to your fork with a regression test we can run to reproduce locally.*

### Expected Behaviour

*Tell us what should happen.*

### Actual Behaviour

*Tell us what happens instead.*

**Comment by wahabbaloch** [comment]
i need to transfer my POA token to an exchange please guide me

**Comment by wahabbaloch** [comment]
i didnt got any answer

**Comment by nikitosing** [comment]
Questions can be asked in the #poa channel on Discord https://discord.gg/mPJ9zkq
