### ISSUE TITLE
xDai: <Issue Title>

### ISSUE THREAD

**Issue by Lexzy4show** [blockscout/blockscout#4880]
Can u help me cancel this transaction. https://blockscout.com/xdai/mainnet/tx/0xad78c57e84e63ebb774b2c22e527f45617ecbcc3043b30bc5783cabfc30c548e 
I mistakenly choose xdia to eth when bridging, am a newbie and it my first time bridging .. pls I need d money .. PLs help me .. I don't have 700$ worth eth to finish this transaction.. d busd only worth 60$

**Comment by Lexzy4show** [comment]
Help

**Comment by vbaranov** [comment]
Questions can be asked in the #xdai channel on Discord https://discord.gg/mPJ9zkq
