### ISSUE TITLE
Ethereum Classic: <Issue Title>

### ISSUE THREAD

**Issue by DRail925** [blockscout/blockscout#4881]
*Describe your issue here.*
When will my Ethereum funds be transferred to Coinbase?
### Environment
* Elixir Version: 1.11.4
* Erlang Version: 23
* BlockScout Version: v3.7.3-beta

* User Agent: `Mozilla/5.0 (Linux; Android 11) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4638.69 Mobile Safari/537.36`

### Steps to reproduce

*Tell us how to reproduce this issue. If possible, push up a branch to your fork with a regression test we can run to reproduce locally.*

### Expected Behaviour

*Tell us what should happen.*

### Actual Behaviour

*Tell us what happens instead.*

**Comment by vbaranov** [comment]
You should contact Coinbase support
