### ISSUE TITLE
POA: <Issue Title> I send crypto to coinbase wallet but it didn't supported that asset which resulted in loss of crypto how can I recover it

### ISSUE THREAD

**Issue by RAHFIL** [blockscout/blockscout#4882]
*Describe your issue here.*

### Environment
* Elixir Version: 1.12.2
* Erlang Version: 24
* BlockScout Version: v4.0.0-beta

* User Agent: `Mozilla/5.0 (Linux; Android 11; LE2121) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4638.50 Mobile Safari/537.36`

### Steps to reproduce

*Tell us how to reproduce this issue. If possible, push up a branch to your fork with a regression test we can run to reproduce locally.*

### Expected Behaviour

*Tell us what should happen.*

### Actual Behaviour

*Tell us what happens instead.*

**Comment by vbaranov** [comment]
Questions can be asked in the #poa channel on Discord https://discord.gg/mPJ9zkq
