### ISSUE TITLE
POA: <Issue Title>

### ISSUE THREAD

**Issue by goergewatany** [blockscout/blockscout#4886]
*Describe your issue here.*

### Environment
* Elixir Version: 1.12.2
* Erlang Version: 24
* BlockScout Version: v4.0.0-beta

* User Agent: `Mozilla/5.0 (Linux; Android 8.1.0; DUB-LX1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4638.74 Mobile Safari/537.36`

### Steps to reproduce

*Tell us how to reproduce this issue. If possible, push up a branch to your fork with a regression test we can run to reproduce locally.*

### Expected Behaviour

*Tell us what should happen.*

### Actual Behaviour

*Tell us what happens instead.*

**Comment by goergewatany** [comment]
صباح الخير انا عندي مشكلة علي عملة poa  من ساعة ما تم حذفها  منصة باينص حولت 40 دولار من منصة باينص علي محفظة trust wallet وتم استقبالهم بنجاح ولاكن قمت بارسال ال40دولار من المحفظة الي منصة gete علي عنوان الايثريم شبكةp2pولكن لم يصلو الي المنصة من اكثر من خمس ايام ما هي المشكلة

**Comment by goergewatany** [comment]
يوجد 40دولار علي شبكة الايثريم لم يصلو

**Comment by goergewatany** [comment]
هل انتظر حين تشغيل شبكة الايثريم علي عملة poa

ارجو المساعدة

**Comment by vbaranov** [comment]
Questions can be asked in the #poa channel on Discord https://discord.gg/mPJ9zkq

**Comment by goergewatany** [comment]
انا لا اعرف ماذا تقول انا الان ضايع مني 40 دولار علي عملة poa انا سحبتهم من
منصة باينص علي المحفظة ولكن قمت بارسالهم علي الايثيريم علي شبكة p2p بس
موصلوش فهلك ممكن تساعدني


اشكرك

في الأربعاء، ١٠ نوفمبر، ٢٠٢١ ٧:٥٠ م Victor Baranov ***@***.***>
كتب:
