### ISSUE TITLE
POA: <Issue Title> problème transaction poa 

### ISSUE THREAD

**Issue by Peco13** [blockscout/blockscout#4891]
*Describe your issue here.*

envoyé à mon adresse coinbase Wallet et rien reçu .
comment annuler la transaction pour les récupérer sur mon Trust Wallet s'il vous plaît ?

### Environment
* Elixir Version: 1.12.2
* Erlang Version: 24
* BlockScout Version: v4.0.0-beta

* User Agent: `Mozilla/5.0 (Linux; Android 10; M2006C3MNG) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4638.74 Mobile Safari/537.36`

### Steps to reproduce

*Tell us how to reproduce this issue. If possible, push up a branch to your fork with a regression test we can run to reproduce locally.*

### Expected Behaviour

*Tell us what should happen.*

### Actual Behaviour

*Tell us what happens instead.*

**Comment by vbaranov** [comment]
Questions can be asked in the #poa channel on Discord https://discord.gg/mPJ9zkq
