### ISSUE TITLE
POA: <Issue Title>

### ISSUE THREAD

**Issue by Mandipkaswa** [blockscout/blockscout#4892]
*Describe your issue here.*
Hi 
Fee days ago i sent my POA coins to (don’t remember the coin now) another coin. Transfer was successful but i lost my coins and don’t know where it goes.

this is the link where i transfer the coins.

0x9f9cdD2722BB20B07F67c39eAC43517B85990ED7

If you need any other information then please let me know 
Thanks 

### Environment
* Elixir Version: 1.12.2
* Erlang Version: 24
* BlockScout Version: v4.0.0-beta

* User Agent: `Mozilla/5.0 (iPhone; CPU iPhone OS 15_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/15.1 Mobile/15E148 Safari/604.1`

### Steps to reproduce

*Tell us how to reproduce this issue. If possible, push up a branch to your fork with a regression test we can run to reproduce locally.*

### Expected Behaviour

*Tell us what should happen.*

### Actual Behaviour

*Tell us what happens instead.*

**Comment by vbaranov** [comment]
Questions can be asked in the #poa channel on Discord https://discord.gg/mPJ9zkq
