### ISSUE TITLE
ive won an nft and need help transfering it pleasexDai: <Issue Title>

### ISSUE THREAD

**Issue by BillyJames1990** [blockscout/blockscout#4893]
*Describe your issue here.*

### Environment
* Elixir Version: 1.12.2
* Erlang Version: 24
* BlockScout Version: v4.0.0-beta

* User Agent: `Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4638.69 Safari/537.36 Edg/95.0.1020.44`

### Steps to reproduce

*Tell us how to reproduce this issue. If possible, push up a branch to your fork with a regression test we can run to reproduce locally.*

### Expected Behaviour

*Tell us what should happen.*

### Actual Behaviour

*Tell us what happens instead.*

**Comment by BillyJames1990** [comment]
i cannot figure out how to transfer the nft ive earned so far

**Comment by vbaranov** [comment]
Questions can be asked in the #xdai channel on Discord https://discord.gg/mPJ9zkq
