### ISSUE TITLE
POA: <Issue Title>

### ISSUE THREAD

**Issue by Berk9090** [blockscout/blockscout#4896]
*Describe your issue here.*

### Environment
* Elixir Version: 1.12.2
* Erlang Version: 24
* BlockScout Version: v4.0.0-beta

* User Agent: `Mozilla/5.0 (Linux; Android 11; Redmi Note 9 Pro) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4638.74 Mobile Safari/537.36`

### Steps to reproduce

*Tell us how to reproduce this issue. If possible, push up a branch to your fork with a regression test we can run to reproduce locally.*

### Expected Behaviour

*Tell us what should happen.*

### Actual Behaviour

*Tell us what happens instead.*

**Comment by Berk9090** [comment]
0x47407a5efd49ea8b652c2c7c217e668d8d3a47ef
Trust wallet hesabımdan POA NETWORK
0x1fcc852bd8b34ef47216e6347f0dbaeff65c2425
Metamaks hesabıma gönderdim 
Metamaks hesabındaki POA20 GÖRÜNMÜYOR

**Comment by Berk9090** [comment]
Yardım edermisiniz

**Comment by Berk9090** [comment]
Yardım edecek misiniz

**Comment by vbaranov** [comment]
Questions can be asked in the #poa channel on Discord https://discord.gg/mPJ9zkq
