### ISSUE TITLE
xDai: <Issue Title>I could not stake from my Metamask xdai chain wallet to Gate xdai wallet. help me urgently. From my wallet address 0x23a69A5e63CaA6fAF688bB73ABA8176952575426; I wanted to send to the gate stake address 0x348e581B92885Ff2E1cD6D90d5Ec9C78D5619F19. It's been 2 hours and my coins have not arrived.

### ISSUE THREAD

**Issue by senbilemezsin** [blockscout/blockscout#4905]
*Describe your issue here.*

### Environment
* Elixir Version: 1.12.2
* Erlang Version: 24
* BlockScout Version: v4.0.0-beta

* User Agent: `Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36`

### Steps to reproduce

*Tell us how to reproduce this issue. If possible, push up a branch to your fork with a regression test we can run to reproduce locally.*

### Expected Behaviour

*Tell us what should happen.*

### Actual Behaviour

*Tell us what happens instead.*

**Comment by vbaranov** [comment]
Questions can be asked in the #xdai channel on Discord https://discord.gg/mPJ9zkq
