### ISSUE TITLE
Write contract feature doesn't work after EIP-1559 for specific contracts

### ISSUE THREAD

**Issue by vbaranov** [blockscout/blockscout#4909]
https://blockscout.com/xdai/mainnet/address/0x683B799b7ee741f00CCea34AcaDC32ba23E8982a/write-contract

![blockscout](https://user-images.githubusercontent.com/4341812/141758609-3a50a63b-7392-4faf-9f0d-695e9ffdfe27.png)

**Comment by vbaranov** [comment]
Addition from affected user:

> Seems to work on other smart contracts, so I assume maybe it's only with the transferFrom method
https://blockscout.com/xdai/mainnet/address/0x683B799b7ee741f00CCea34AcaDC32ba23E8982a/write-contract
SnafuConverter (0x683B799b7ee741f00CCea34AcaDC32ba23E8982a) - xDai...
View the account balance, transactions, and other data for 0x683B799b7ee741f00CCea34AcaDC32ba23E8982a on the (xDAI)
This is the smart contract
version MetaMask
10.5.1
Also the other methods of this contract don't work (like safeTransferFrom) 
transferFrom method works on other contracts

**Comment by nikitosing** [comment]
Cannot reproduce the issue
