### ISSUE TITLE
POA: poa not recved

### ISSUE THREAD

**Issue by Hrmeer** [blockscout/blockscout#4910]
![Screenshot_20211115-222000_Brave](https://user-images.githubusercontent.com/94391679/141826024-d065bd50-fc71-4b6b-a760-771451da3258.jpg)
i am send some poa trust wallet to hitBTC with poa network but i am not recve any thing......i attached screen shot of my tras detail

### Environment
* Elixir Version: 1.12.2
* Erlang Version: 24
* BlockScout Version: v4.0.0-beta

* User Agent: `Mozilla/5.0 (Linux; Android 10) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4638.69 Mobile Safari/537.36`

### Steps to reproduce

*Tell us how to reproduce this issue. If possible, push up a branch to your fork with a regression test we can run to reproduce locally.*

### Expected Behaviour

*Tell us what should happen.*

### Actual Behaviour

*Tell us what happens instead.*

**Comment by vbaranov** [comment]
Questions can be asked in the #poa channel on Discord https://discord.gg/mPJ9zkq

**Comment by Hrmeer** [comment]
i am send some poa trust wallet to hitBTC with poa network but i am not
recve any thing......i attached screen shot of my tras detail
