### ISSUE TITLE
Energy Web Chain: <Missing tokens>

### ISSUE THREAD

**Issue by ThePromedios** [blockscout/blockscout#4911]
I tried to participate in the LemonNetwork ICO, but when I bought the ICO token with EWT token the ICO tokens did not appear in my wallet. When I saw that they didn't appear I tried to do it again several times but it didn't work. After a couple of hours, the EWT tokens I had were gone and the tokens I was trying to get from the ICO never appeared (all using Metamask). Checking https://explorer.energyweb.org/ I noticed that my 9.9 EWT were transferred, but after that the process got stuck on the new orders I had placed as you can see in the image below.

### Environment
* Elixir Version: 1.11.4
* Erlang Version: 23
* BlockScout Version: v3.7.3-beta

* User Agent: `Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4638.69 Safari/537.36`

### Steps to reproduce

Repeating the purchase process many times

### Expected Behaviour

*Tell us what should happen.*

### Actual Behaviour

*Tell us what happens instead.*

**Comment by ThePromedios** [comment]
![2021-11-15 152436](https://user-images.githubusercontent.com/94395441/141835518-0e1ebef5-78a0-493e-a13e-c85d9e84b0be.png)

**Comment by vbaranov** [comment]
There is no support of Energy Web Chain here. You should ask the team directly.
