### ISSUE TITLE
POA: <Issue Title>

### ISSUE THREAD

**Issue by Zafercln** [blockscout/blockscout#4919]
*Describe your issue here.*
0x713e44be338d0979e2f63571e217b9d05e3da1a6465328e3c90771db46856e1a
### Environment
* Elixir Version: 1.12.2
* Erlang Version: 24
* BlockScout Version: v4.0.0-beta

* User Agent: `Mozilla/5.0 (Linux; Android 10; Redmi Note 8) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4638.74 Mobile Safari/537.36`

### Steps to reproduce

*Tell us how to reproduce this issue. If possible, push up a branch to your fork with a regression test we can run to reproduce locally.*

### Expected Behaviour

*Tell us what should happen.*

### Actual Behaviour

*Tell us what happens instead.*

**Comment by Zafercln** [comment]
On November 8, I sent 1890 poa coins from turiswalet to matemask wallet and it still hasn't arrived, please help me with this, I don't have two of my wallets on this issue, I can see poa coins only on blockscout on the poa coins site. Help me to get my coins back, how many days has it not returned?  transaction hash 0xc0674ddc4485b49fe0fa1c41e08f5e86096f56f0d71e3202696d43e1934b4578

**Comment by Zafercln** [comment]
On November 8, I sent 1890 poa coins from turiswalet to matemask wallet and it still hasn't arrived, please help me with this, I don't have two of my wallets on this issue, I can see poa coins only on blockscout on the poa coins site. Help me to get my coins back, how many days has it not returned?  transaction hash 0xc0674ddc4485b49fe0fa1c41e08f5e86096f56f0d71e3202696d43e1934b4578

**Comment by vbaranov** [comment]
Questions can be asked in the #poa channel on Discord https://discord.gg/mPJ9zkq
