### ISSUE TITLE
POA: <Issue Title>

### ISSUE THREAD

**Issue by Danielquaresmadasilva** [blockscout/blockscout#4920]
*Describe your issue here.*

### Environment
* Elixir Version: 1.12.2
* Erlang Version: 24
* BlockScout Version: v4.0.0-beta

* User Agent: `Mozilla/5.0 (Linux; Android 9; ASUS_X00QD) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4638.74 Mobile Safari/537.36`

### Steps to reproduce

*Tell us how to reproduce this issue. If possible, push up a branch to your fork with a regression test we can run to reproduce locally.*

### Expected Behaviour

*Tell us what should happen.*

### Actual Behaviour

*Tell us what happens instead.*

**Comment by Danielquaresmadasilva** [comment]
Enviei minha moedas POA para carteira e até agora não chegou oque eu devo fazer 0x58fd9AD45FD178AecCAC484c20C7250b2A0B2D42

**Comment by vbaranov** [comment]
Questions can be asked in the #poa channel on Discord https://discord.gg/mPJ9zkq
