### ISSUE TITLE
How to read Contract

### ISSUE THREAD

**Issue by ajaydoyenhub** [blockscout/blockscout#4921]
*Describe your issue here.*

I have created a token on the Ethereum test network and created one ERC721 token and deployed it on the same network by using remix.ethereum.org.

Now, I can't see ERC721 tokens listing in Token menu.
Another is, I can see contract detail from search by contract address but not be able to read the contract like [this](https://blockscout.com/xdai/mainnet/address/0xdBF3Ea6F5beE45c02255B2c26a16F300502F68da/transactions).

What configuration I'm missing, please do let me know.

### Environment

* Elixir & Erlang/OTP versions (`elixir -version`): Erlang/OTP 24 [erts-12.1.5]
* Operating System: linux 20.04
* Blockscout Version/branch: github.com/poanetwork/blockscout

### Expected behaviour

I need to read the contract option inside token transaction like [this ](https://blockscout.com/xdai/mainnet/address/0xdBF3Ea6F5beE45c02255B2c26a16F300502F68da/transactions).

### Actual behaviour

Currently, I can see Token the contract transactions details but can't see below options 
![Screenshot from 2021-11-17 13-11-49](https://user-images.githubusercontent.com/55733195/142157209-e67cdf72-e2f7-4ae0-8e00-c683989dd78c.png)

**Comment by vbaranov** [comment]
@ajaydoyenhub 
> but can't see below options

I don't get it. Which of the tab item don't you see?

Do you have any screenshots for the token which is in question? The current description looks very opaque.

**Comment by ajaydoyenhub** [comment]
This is how my contract page is looking
![Contract 0xBF59D](https://user-images.githubusercontent.com/55733195/142358374-cb639e9f-2568-4048-b7be-c0ca2a5b368e.png)
![Transaction 0x84](https://user-images.githubusercontent.com/55733195/142358385-6d0853ec-225e-48ed-9b57-325447edf767.png)

**Comment by ajaydoyenhub** [comment]
And I need to look like this way **Read Contract, Write Contract options**
![TokenProxy (0xdB](https://user-images.githubusercontent.com/55733195/142358680-dfd1905e-3cf7-4ece-997b-a862692cc66d.png)

**Comment by ajaydoyenhub** [comment]
If you see in the first two pics have no read-write contract option, how can I get those options?

**Comment by nikitosing** [comment]
@ajaydoyenhub you need to verify your smart contract on the **Code** tab

**Comment by ajaydoyenhub** [comment]
@nikitosing thank you so much for your reply.
I'm how can I verify my New Solidity Smart Contract ?

do you have any references?

**Comment by nikitosing** [comment]
@ajaydoyenhub https://docs.blockscout.com/for-users/smart-contract-interaction/verifying-a-smart-contract

**Comment by ajaydoyenhub** [comment]
When I try to verify I'm getting a compiler version error. But the same version I used while creating the smart contract. 
Kindly check the below link.
https://www.awesomescreenshot.com/image/18425294?key=a8dbac630dc6004636c21a92f11c576f
