### ISSUE TITLE
I have a transfer issue 

### ISSUE THREAD

**Issue by kiw6799** [blockscout/blockscout#4925]
*Describe your issue here.*
Here is my transaction hash that I sent yesterday : 0x6985825d6f0f5d07eda5bd7d0bda0ee22902a75f5952572b119f639b527e6d3d
I transferred money from https://blockscout.com/etc/mainnet/address/0xcc659d13d276487cc3d8daf1641945b24e343aa1 to https://blockscout.com/etc/mainnet/address/0x5f4088558f30083922532567992e2f5bf3643b26.  Total value is 
15.61825348 ETC ($802.93 USD). The result was succeed and transaction confirmed as soon as I transferred money. However, the balance shows zero. Is there any way how to transfer money to different account? Please help !! This is really important for me. I will copy my detailed transaction below for your convenience. Please review and let me know how to solve this issue. 
Please email me once you available: Here is my email address => qofndo84@gmail.com

Transaction Details
 Transaction Hash
0x6985825d6f0f5d07eda5bd7d0bda0ee22902a75f5952572b119f639b527e6d3d
 Result
 Success
 Status
Confirmed Confirmed by 7,802
 Block
13940577
 Timestamp
 a day ago | November-16-2021 05:21:19 PM +9 UTC | Confirmed within <= 14.081 seconds
 From
0xcc659d13d276487cc3d8daf1641945b24e343aa1
 To
0x5f4088558f30083922532567992e2f5bf3643b26
 Value
15.61825348 ETC ($802.93 USD)
 Transaction Fee
0.001491 ETC ($0.076652 USD)
 Gas Price
71 Gwei
 Gas Limit
21,000
 Gas Used by Transaction
21,000 | 100%
 NoncePosition
12611

**Comment by vbaranov** [comment]
Regarding your question try to reach out ETC team, for instance, on their Discord https://discord.com/invite/hQs894U.
