### ISSUE TITLE
Space in Disk...

### ISSUE THREAD

**Issue by damianlluch** [blockscout/blockscout#4930]
hello, a question.
We have an AWS instance where Blockscout is running connected to 4 nodes (on other instances) of Besu (IBFT).
The problem we have is that blockscout occupies too much space, in one month it has spent 200 gb, and the blockchain has hardly been used...
We are generating a block every 30 seconds... and blockscout looks like a hard disk eating machine.

Any solution?

thanks

**Comment by damianlluch** [comment]
![image](https://user-images.githubusercontent.com/1463804/142437372-de8edff2-f837-42e7-8661-5ad047dc21b5.png)

**Comment by damianlluch** [comment]
It seems odd that the logs folder takes up so much space. Is it possible to clean this folder from time to time?

**Comment by vbaranov** [comment]
Blockscout supports logs rotation. Please check this answer out https://github.com/blockscout/blockscout/issues/2087#issuecomment-498222801 and below.

**Comment by damianlluch** [comment]
Sorry, I read your reply in the other issue and it was not clear to me. Can I delete that folder yes or no? I don't know what you mean by log rotation.

**Comment by vbaranov** [comment]
> Can I delete that folder yes or no?
Yes, you can, if you don't care what is in that logs. The folder will appear automatically after deletion.
> I don't know what you mean by log rotation.
https://en.wikipedia.org/wiki/Log_rotation
