### ISSUE TITLE
(FunctionClauseError) no function clause matching in EthereumJSONRPC.Parity.Trace.entry_to_elixir/1

### ISSUE THREAD

**Issue by damianlluch** [blockscout/blockscout#4939]
Analysing the error.log file
This error pattern is repeated all the time.
Among the issues, I've seen similar errors, but I can't figure out if this error is something that happens because of the way the nodes are raised, or if it's an error that happens with blockscout and I have to change some variable there.

https://github.com/blockscout/blockscout/issues?q=is%3Aissue+no+function+clause+matching+in+EthereumJSONRPC.Parity

Any suggestions?

thanks

```
Args: [%{batch: [309492, 1160, 307867, 1160, 354978, 1160, 354953, 335706, 354961, 307974], callback_module: Indexer.Fetcher.InternalTransaction, callback_module_state: [transport: EthereumJSONRPC.HTTP, else: EthereumJSONRPC.IPC, transport_options: [http: EthereumJSONRPC.HTTP.HTTPoison, url: "http://ec2-54-93-234-47.eu-central-1.compute.amazonaws.com:8545", method_to_url: [eth_getBalance: "http://ec2-54-93-234-47.eu-central-1.compute.amazonaws.com:8545/", trace_block: "http://ec2-54-93-234-47.eu-central-1.compute.amazonaws.com:8545/", trace_replayBlockTransactions: "http://ec2-54-93-234-47.eu-central-1.compute.amazonaws.com:8545/"], http_options: [recv_timeout: 600000, timeout: 600000, hackney: [pool: :ethereum_jsonrpc]]], variant: EthereumJSONRPC.Besu], metadata: [fetcher: :internal_transaction]}]
2021-11-19T10:13:22.270 fetcher=internal_transaction count=9 [error] Task #PID<0.3499.427> started from Indexer.Fetcher.InternalTransaction terminating
** (FunctionClauseError) no function clause matching in EthereumJSONRPC.Parity.Trace.entry_to_elixir/1
    (ethereum_jsonrpc 0.1.0) lib/ethereum_jsonrpc/parity/trace.ex:454: EthereumJSONRPC.Parity.Trace.entry_to_elixir({"revertReason", "0x08c379a00000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000000000000000000000000000000000002a45524332305061757361626c653a20746f6b656e207472616e73666572207768696c652070617573656400000000000000000000000000000000000000000000"})
```

**Comment by vbaranov** [comment]
Which archive node do you use? Besu?
If yes you can try applying this fix https://github.com/blockscout/blockscout/pull/4895 to your instance.

**Comment by damianlluch** [comment]
I have added that change, and restarted blockscout. I don't know if I need to do anything else.

**Comment by damianlluch** [comment]
@vbaranov thank you, I have added that line manually and so far the error.log file has not regenerated again.
Now, this file occupies 25 GB. 

indexer.log

is it normal?

What does this file store?

**Comment by vbaranov** [comment]
Indexer.log file stores log file of all Blockscout fetchers. And it supports logs rotating - it is enabled by default. Please re-open the issue if you have any other questions.
