### ISSUE TITLE
Energy Web Chain: <Issue Title>

### ISSUE THREAD

**Issue by Einargn** [blockscout/blockscout#4942]
i need to cancel 2 duped transaction but i cant what need to do¿? a did with metamask
They have been running for 2 days but they are neither confirmed nor canceled, what can I do?

0x2cbdf87fbf9618c55b752341768363779bb241eae129baec09500c13f1b704ff
0x4278b7077176fbe3b0597d22211506e7a9dd1b4eaa2f7290114969d6b5df1073

### Environment
* Elixir Version: 1.11.4
* Erlang Version: 23
* BlockScout Version: v3.7.3-beta

* User Agent: `Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.45 Safari/537.36`

### Steps to reproduce

*Tell us how to reproduce this issue. If possible, push up a branch to your fork with a regression test we can run to reproduce locally.*

### Expected Behaviour

*Tell us what should happen.*

### Actual Behaviour

*Tell us what happens instead.*

**Comment by vbaranov** [comment]
Energy Web Chain is not supported here. Please, contact the team directly.
