### ISSUE TITLE
POA: I send my Poa coin to poa20 Server with fault. Can anyone help me. 

### ISSUE THREAD

**Issue by Tarikyildiz16** [blockscout/blockscout#4944]
*Describe your issue here.*
Hi everyone 
I sent my Poa coin to poa20 Server with fault. Xn anyone help me please...
### Environment
* Elixir Version: 1.12.2
* Erlang Version: 24
* BlockScout Version: v4.0.0-beta

* User Agent: `Mozilla/5.0 (Linux; Android 10; CLT-L09 Build/HUAWEICLT-L09; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/96.0.4664.45 Mobile Safari/537.36`

### Steps to reproduce

*Tell us how to reproduce this issue. If possible, push up a branch to your fork with a regression test we can run to reproduce locally.*

### Expected Behaviour

*Tell us what should happen.*

### Actual Behaviour

*Tell us what happens instead.*

**Comment by vbaranov** [comment]
Questions can be asked in the #poa channel on Discord https://discord.gg/mPJ9zkq
