### ISSUE TITLE
could not compile dependency :ex_keccak, "mix compile" failed

### ISSUE THREAD

**Issue by sk-enya** [blockscout/blockscout#4950]
Steps: 
after running `mix do deps.get, local.rebar --force, deps.compile, compile`
I am facing below issue.
```
Compiling failure v0.1.8
   Compiling which v2.0.1
   Compiling rustler v0.21.1
error: failed to run custom build command for `rustler v0.21.1`

Caused by:
  process didn't exit successfully: `/Users/sahil/work/workspace/enya/workspace/blockscout/_build/prod/rustler_crates/exkeccak/release/build/rustler-50a7b7a380525c2a/build-script-build` (exit status: 101)
  --- stderr
  thread 'main' panicked at 'Erlang version 2.16 not handled, please file a a bug report.', /Users/sahil/.cargo/registry/src/github.com-1ecc6299db9ec823/rustler-0.21.1/build.rs:50:10
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
could not compile dependency :ex_keccak, "mix compile" failed. You can recompile this dependency with "mix deps.compile ex_keccak", update it with "mix deps.update ex_keccak" or clean it with "mix deps.clean ex_keccak"
** (RuntimeError) Rust NIF compile error (rustc exit code 101)
    (rustler 0.21.1) lib/mix/tasks/compile.rustler.ex:68: Mix.Tasks.Compile.Rustler.compile_crate/1
    (elixir 1.12.3) lib/enum.ex:1582: Enum."-map/2-lists^map/1-0-"/2
    (rustler 0.21.1) lib/mix/tasks/compile.rustler.ex:15: Mix.Tasks.Compile.Rustler.run/1
    (mix 1.12.3) lib/mix/task.ex:394: anonymous fn/3 in Mix.Task.run_task/3
    (mix 1.12.3) lib/mix/tasks/compile.all.ex:92: Mix.Tasks.Compile.All.run_compiler/2
    (mix 1.12.3) lib/mix/tasks/compile.all.ex:72: Mix.Tasks.Compile.All.compile/4
    (mix 1.12.3) lib/mix/tasks/compile.all.ex:59: Mix.Tasks.Compile.All.with_logger_app/2
    (mix 1.12.3) lib/mix/tasks/compile.all.ex:36: Mix.Tasks.Compile.All.run/1
```

### Environment

* Elixir & Erlang/OTP versions (`elixir -version`):
`Erlang/OTP 24 [erts-12.1.5] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [dtrace]

Elixir 1.12.3 (compiled with Erlang/OTP 24)`
* Operating System:
`MacOS Monterey : Apple M1 pro`
* Blockscout Version/branch: 
`master`
### Steps to reproduce
running the below command from root of project.
```
mix do deps.get, local.rebar --force, deps.compile, compile
```

followed the documentation available here https://docs.blockscout.com/for-developers/information-and-settings/requirements

Can you please help to get the **blockscout** up and running locally?

**Comment by sk-enya** [comment]
Got this issue resolve after downgrading the version with `asdf`.

**Comment by baselka** [comment]
> Got this issue resolve after downgrading the version with `asdf`.

may I know you downgraded to what specific version please ? because I have been getting the same issue with different versions, currently I have the following versions:


```
Erlang/OTP 24 [erts-12.0.3] [source] [64-bit] [smp:4:4] [ds:4:4:10] [async-threads:1] [jit]

Elixir 1.12.2 (compiled with Erlang/OTP 24)
```

Getting the error whenever I run `mix do deps.get, local.rebar --force, deps.compile, compile`


`** (ErlangError) Erlang error: :enoent
    (elixir 1.12.2) lib/system.ex:1041: System.cmd("cargo", ["rustc", "--release", "--", "-C", "link-arg=-undefined", "-C", "link-arg=dynamic_lookup"], [cd: "/Users/basilsatti/Decenternet/acent-chain2/deps/ex_keccak/native/exkeccak", stderr_to_stdout: true, env: [{"CARGO_TARGET_DIR", "/Users/basilsatti/Decenternet/acent-chain2/_build/dev/lib/ex_keccak/native/exkeccak"}], into: %IO.Stream{device: :standard_io, line_or_bytes: :line, raw: false}])
    (rustler 0.22.0) lib/rustler/compiler.ex:27: Rustler.Compiler.compile_crate/2
    lib/ex_keccak.ex:2: (module)
    (stdlib 3.15.1) erl_eval.erl:685: :erl_eval.do_apply/6
could not compile dependency :ex_keccak, "mix compile" failed. You can recompile this dependency with "mix deps.compile ex_keccak", update it with "mix deps.update ex_keccak" or clean it with "mix deps.clean ex_keccak"`

**Comment by Monkey-qiang** [comment]
> > Got this issue resolve after downgrading the version with `asdf`.
> 
> may I know you downgraded to what specific version please ? because I have been getting the same issue with different versions, currently I have the following versions:
> 
> ```
> Erlang/OTP 24 [erts-12.0.3] [source] [64-bit] [smp:4:4] [ds:4:4:10] [async-threads:1] [jit]
> 
> Elixir 1.12.2 (compiled with Erlang/OTP 24)
> ```
> 
> Getting the error whenever I run `mix do deps.get, local.rebar --force, deps.compile, compile`
> 
> `** (ErlangError) Erlang error: :enoent (elixir 1.12.2) lib/system.ex:1041: System.cmd("cargo", ["rustc", "--release", "--", "-C", "link-arg=-undefined", "-C", "link-arg=dynamic_lookup"], [cd: "/Users/basilsatti/Decenternet/acent-chain2/deps/ex_keccak/native/exkeccak", stderr_to_stdout: true, env: [{"CARGO_TARGET_DIR", "/Users/basilsatti/Decenternet/acent-chain2/_build/dev/lib/ex_keccak/native/exkeccak"}], into: %IO.Stream{device: :standard_io, line_or_bytes: :line, raw: false}]) (rustler 0.22.0) lib/rustler/compiler.ex:27: Rustler.Compiler.compile_crate/2 lib/ex_keccak.ex:2: (module) (stdlib 3.15.1) erl_eval.erl:685: :erl_eval.do_apply/6 could not compile dependency :ex_keccak, "mix compile" failed. You can recompile this dependency with "mix deps.compile ex_keccak", update it with "mix deps.update ex_keccak" or clean it with "mix deps.clean ex_keccak"`

Have you run "rustc -V" to check rust has been download? i fixed this problem by run this command and found my environment wasn't prepared.

**Comment by vbaranov** [comment]
`ex_keccak` package updated to the latest version in the master branch https://github.com/blockscout/blockscout/pull/5053.
