### ISSUE TITLE
xDai: <Issue Title>

### ISSUE THREAD

**Issue by UncleNicola** [blockscout/blockscout#4953]
I believe i sent my bao tokens to a wrong address, now I am trying to recover them. It says the transaction was a success, but I never received the tokens.

### Environment
* Elixir Version: 1.12.2
* Erlang Version: 24
* BlockScout Version: v4.0.0-beta

* User Agent: `Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.55 Safari/537.36`

### Steps to reproduce

*Tell us how to reproduce this issue. If possible, push up a branch to your fork with a regression test we can run to reproduce locally.*

### Expected Behaviour

*Tell us what should happen.*

### Actual Behaviour

*Tell us what happens instead.*

**Comment by vbaranov** [comment]
Questions can be asked in the #xdai channel on Discord https://discord.gg/mPJ9zkq
