### ISSUE TITLE
 <Sent ETH from Meta mask Palm network directly to binance without bridge... :>

### ISSUE THREAD

**Issue by Jammycreamer-png** [blockscout/blockscout#4959]
*Is there any way to retrieve my ETH back ? here is the transaction address https://explorer.palm.io/tx/0xe5c9795b6bb7124ace97512e9a6fe6115f50156f0f7712b4ef752d805c09fb66/logs *

### Environment
* Elixir Version: 1.12.2
* Erlang Version: 24
* BlockScout Version: 

* User Agent: `Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.45 Safari/537.36`

### Steps to reproduce

*Tell us how to reproduce this issue. If possible, push up a branch to your fork with a regression test we can run to reproduce locally.*

### Expected Behaviour

*Tell us what should happen.*

### Actual Behaviour

*Tell us what happens instead.*

**Comment by vbaranov** [comment]
There is no support for Palm network. Please ask the team directly.

**Comment by xavier849** [comment]
> *Is there any way to retrieve my ETH back ? here is the transaction address https://explorer.palm.io/tx/0xe5c9795b6bb7124ace97512e9a6fe6115f50156f0f7712b4ef752d805c09fb66/logs *
> 
> ### Environment
> * Elixir Version: 1.12.2
> * Erlang Version: 24
> * BlockScout Version:
> * User Agent: `Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.45 Safari/537.36`
> 
> ### Steps to reproduce
> _Tell us how to reproduce this issue. If possible, push up a branch to your fork with a regression test we can run to reproduce locally._
> 
> ### Expected Behaviour
> _Tell us what should happen._
> 
> ### Actual Behaviour
> _Tell us what happens instead._

Hello, I'm having a similar issue. Did you get it solved?
