### ISSUE TITLE
Palm: <Issue Title>I sent DAI to my METAMASK account.

### ISSUE THREAD

**Issue by DeeMoe2829** [blockscout/blockscout#4960]
I sent DAI from my Nifty's account to my MetaMask account. it appears to be stuck or lost. can this be returned to the original account? I dont know where else to start to recover my DAI. 

10 days ago
### Environment
* Elixir Version: 1.12.2
* Erlang Version: 24
* BlockScout Version: 

* User Agent: `Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/94.0.4606.71 Safari/537.36 Edg/94.0.992.38`

### Steps to reproduce

*Tell us how to reproduce this issue. If possible, push up a branch to your fork with a regression test we can run to reproduce locally.*

### Expected 

*Tell us what should happen.*

### Actual Behaviour

*Tell us what happens instead.*

**Comment by vbaranov** [comment]
Here is no support of Palm Network. Please contact the team directly.

**Comment by xavier849** [comment]
> I sent DAI from my Nifty's account to my MetaMask account. it appears to be stuck or lost. can this be returned to the original account? I dont know where else to start to recover my DAI.
> 
> 10 days ago
> 
> ### Environment
> * Elixir Version: 1.12.2
> * Erlang Version: 24
> * BlockScout Version:
> * User Agent: `Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/94.0.4606.71 Safari/537.36 Edg/94.0.992.38`
> 
> ### Steps to reproduce
> _Tell us how to reproduce this issue. If possible, push up a branch to your fork with a regression test we can run to reproduce locally._
> 
> ### Expected
> _Tell us what should happen._
> 
> ### Actual Behaviour
> _Tell us what happens instead._

Hello, I'm having the same issue. Can somebody help me?
