### ISSUE TITLE
WebSocket connection to 'wss://xxx.com/socket/websocket?locale=en&vsn=2.0.0' failed

### ISSUE THREAD

**Issue by dbarobin** [blockscout/blockscout#4963]
*Describe your issue here.*

```
WebSocket connection to 'wss://xxx.com/socket/websocket?locale=en&vsn=2.0.0' failed
WebSocket connection to 'wss://xxx.com/phoenix/live_reload/socket/websocket?vsn=2.0.0' failed
```

The xxx.com is configured as https.

```
    location / {
        proxy_set_header  X-Real-IP  $remote_addr;
        proxy_set_header  X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header  X_FORWARDED_PROTO $scheme;
        proxy_set_header  Host $http_host;
        proxy_redirect    off;
        client_max_body_size 1M;
        proxy_pass http://127.0.0.1:4000;
    }
```

But the wss require https and proxy_pass is `http://127.0.0.1:4001`, I can't configure the https and wss to the same domain with different proxy_pass.

### Environment

* Elixir & Erlang/OTP versions (`elixir -version`): Elixir 1.12.2
* Operating System: Ubuntu 20.04.3 LTS
* Blockscout Version/branch: master

### Steps to reproduce

* Manual deploy refer https://docs.blockscout.com/for-developers/manual-deployment

### Expected behaviour

Websocket works well.

### Actual behaviour

Websocket connection failed.

**Comment by baselka** [comment]
> _Describe your issue here._
> 
> ```
> WebSocket connection to 'wss://xxx.com/socket/websocket?locale=en&vsn=2.0.0' failed
> WebSocket connection to 'wss://xxx.com/phoenix/live_reload/socket/websocket?vsn=2.0.0' failed
> ```
> 
> The xxx.com is configured as https.
> 
> ```
>     location / {
>         proxy_set_header  X-Real-IP  $remote_addr;
>         proxy_set_header  X-Forwarded-For $proxy_add_x_forwarded_for;
>         proxy_set_header  X_FORWARDED_PROTO $scheme;
>         proxy_set_header  Host $http_host;
>         proxy_redirect    off;
>         client_max_body_size 1M;
>         proxy_pass http://127.0.0.1:4000;
>     }
> ```
> 
> But the wss require https and proxy_pass is `http://127.0.0.1:8546`, I can't configure the https and wss to the same domain with different proxy_pass.
> ### Environment
> 
>     * Elixir & Erlang/OTP versions (`elixir -version`): Elixir 1.12.2
> 
>     * Operating System: Ubuntu 20.04.3 LTS
> 
>     * Blockscout Version/branch: master
> 
> 
> ### Steps to reproduce
> 
>     * Manual deploy refer https://docs.blockscout.com/for-developers/manual-deployment
> 
> 
> ### Expected behaviour
> 
> Websocket works well.
> ### Actual behaviour
> 
> Websocket connection failed.

In my case neither http nor https works .
I have exactly the same environment as yours, I'm able to connect to the socket if I access via xxx.com:4000 or ip:4000 but not from xxx.com.
We're now thinking to have a separate subdomain for the ws and then we could forward to the new ssubdomain/socket url.

But if you have found a solution please share it having it to work in this case xxx.com, though as you mentioned we cannot set .

**Comment by kiraahmad** [comment]
I have the same environment and I'm facing the same Issue, Any solutions ?

**Comment by cedricfung** [comment]
Something like 

```
location ~* /socket/ {
    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "Upgrade";
    proxy_set_header Host $host;
    proxy_pass http://127.0.0.1:4001;
}

location / {
        proxy_set_header  X-Real-IP  $remote_addr;
        proxy_set_header  X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header  X_FORWARDED_PROTO $scheme;
        proxy_set_header  Host $http_host;
        proxy_redirect    off;
        client_max_body_size 10M;
        proxy_pass http://127.0.0.1:4000;
}
```

And it's recommended to use a big `client_max_body_size` to serve a large contract submission.

**Comment by johnsonjie** [comment]
> 

where is the port 4001 defined?And you mean there are 2 ports to listen?one is http and the other is web socket?

**Comment by johnsonjie** [comment]
> _Describe your issue here._
> 
> ```
> WebSocket connection to 'wss://xxx.com/socket/websocket?locale=en&vsn=2.0.0' failed
> WebSocket connection to 'wss://xxx.com/phoenix/live_reload/socket/websocket?vsn=2.0.0' failed
> ```
> 
> The xxx.com is configured as https.
> 
> ```
>     location / {
>         proxy_set_header  X-Real-IP  $remote_addr;
>         proxy_set_header  X-Forwarded-For $proxy_add_x_forwarded_for;
>         proxy_set_header  X_FORWARDED_PROTO $scheme;
>         proxy_set_header  Host $http_host;
>         proxy_redirect    off;
>         client_max_body_size 1M;
>         proxy_pass http://127.0.0.1:4000;
>     }
> ```
> 
> But the wss require https and proxy_pass is `http://127.0.0.1:4001`, I can't configure the https and wss to the same domain with different proxy_pass.
> 
> ### Environment
> * Elixir & Erlang/OTP versions (`elixir -version`): Elixir 1.12.2
> * Operating System: Ubuntu 20.04.3 LTS
> * Blockscout Version/branch: master
> 
> ### Steps to reproduce
> * Manual deploy refer https://docs.blockscout.com/for-developers/manual-deployment
> 
> ### Expected behaviour
> Websocket works well.
> 
> ### Actual behaviour
> Websocket connection failed.

have you solved this issue?

**Comment by uniwswap** [comment]
any update on this?

**Comment by myxtype** [comment]
```
location /socket {
    	proxy_http_version 1.1;
        proxy_pass            http://127.0.0.1:4000;
        proxy_set_header      Host $host;
        proxy_set_header      X-Real-IP $remote_addr;
        proxy_set_header      X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header      X-Forwarded-Proto $scheme;
        proxy_set_header      Upgrade $http_upgrade;
        proxy_set_header      Connection $connection_upgrade;
        client_max_body_size  1m;
}
```

```
proxy_http_version 1.1;
```

This is important

**Comment by semiPlanet** [comment]
this is my working configuration 
location ~* /socket/ {
               proxy_http_version 1.1;
               proxy_set_header Upgrade $http_upgrade;
               proxy_set_header Connection "Upgrade";
               proxy_set_header Host $host;
               proxy_pass https://127.0.0.1:4001;
	}

**Comment by xiaoyuge886** [comment]
> 

完美解决
