### ISSUE TITLE
Palm: <I can't see my cryptos>

### ISSUE THREAD

**Issue by samuspeltra** [blockscout/blockscout#4985]
I sent 73.6 dai from my metamask wallet to my coinbase wallet and despite this transaction is verified I don't see my crypto.
this is the transaction hash: 0x40a0e692ea221b734b0da86ce797f9e86b5781de395ac3f83b8d6031038e907c

**Comment by vbaranov** [comment]
Here is no support of Palm network. Please, contact the team directly.

**Comment by xavier849** [comment]
> 

How we can contact Palm directly? Thanks
