### ISSUE TITLE
POA: <Issue Title>

### ISSUE THREAD

**Issue by aliarslan03** [blockscout/blockscout#4987]
*Describe your issue here.*
hi, i transfered my POA coins from my trustwallet to my coinbase wallet, transfer has been done but it didnt arrived to coinbase wallet yet. it passed more days from 10th november 2021. please help me to find my coins i am very upset. 

here is hash id: 0x91ca98b0f705c85e749149fbc0b374734c8506c06c0bba77dcc85ab068f20a85
### Environment
* Elixir Version: 1.12.2
* Erlang Version: 24
* BlockScout Version: v4.0.0-beta

* User Agent: `Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.45 Safari/537.36`

### Steps to reproduce

*Tell us how to reproduce this issue. If possible, push up a branch to your fork with a regression test we can run to reproduce locally.*

### Expected Behaviour

*Tell us what should happen.*

### Actual Behaviour

*Tell us what happens instead.*

**Comment by vbaranov** [comment]
Questions can be asked in the #poa channel on Discord https://discord.gg/mPJ9zkq
