### ISSUE TITLE
Incorrect info displayed of bridged contract

### ISSUE THREAD

**Issue by olibaron** [blockscout/blockscout#4996]
Incorrect display of a bridged erc20 token 

### Environment

Production

### Steps to reproduce

https://blockscout.com/xdai/mainnet/address/0x988d1Be68F2C5cDE2516a2287c59Bd6302b7D20D/transactions

### Expected behaviour

Should show Contract Address Details

### Actual behaviour

Shows Address details instead. 

We have tested the whole flow with the same contract under a different name. This bridged token does show the correct info.
The original erc20 contract is here:
PUNK ERC20: https://etherscan.io/token/0xd866db204b51ff53b4350fbf415d2e154844698f

**Comment by vbaranov** [comment]
@olibaron perhaps, you know in which transaction https://blockscout.com/xdai/mainnet/address/0x988d1Be68F2C5cDE2516a2287c59Bd6302b7D20D/transactions has been created? Could you give a link, if yes?

**Comment by vbaranov** [comment]
@olibaron this was fixed, the address is recognized as a contract.
