### ISSUE TITLE
Palm: <Funds were never received>

### ISSUE THREAD

**Issue by xavier849** [blockscout/blockscout#4999]
*I made a funds transfer 16 hours ago from my MetaMask wallet on the Palm network to my Crypto.com account. I haven't received the funds yet.
This is the original account: 0x583830789ff6664F7e2976dF51824C34f78B7d1f
This is the crypto.com account: 0xC360EF664739b5B1532bD9e85D4c1704A9Fc6E46

Transaction hash:
0x0442d74f6fe2ce89c45d1af6959a55e0b6b9264f035a37d520f1de37544cd740

I have the following links, one says status confirmed and the other link says error reverted,
https://explorer.palm.io/tx/0x0442d74f6fe2ce89c45d1af6959a55e0b6b9264f035a37d520f1de37544cd740/token-transfers
https://explorer.palm.io/block/3106550/transactions 

*

### Environment
* Elixir Version: 1.12.2
* Erlang Version: 24
* BlockScout Version: 

* User Agent: `Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.93 Safari/537.36`

### Steps to reproduce

*Tell us how to reproduce this issue. If possible, push up a branch to your fork with a regression test we can run to reproduce locally.*

### Expected Behaviour

*Tell us what should happen.*

### Actual Behaviour

*Tell us what happens instead.*

**Comment by vbaranov** [comment]
There is no Palm support here.

**Comment by xavier849** [comment]
> There is no Palm support here.

What's the website or link for Palm Support? all their site says that it in here
