### ISSUE TITLE
Palm: <Account transfer

### ISSUE THREAD

**Issue by CheechNFT** [blockscout/blockscout#5000]
*I can see my public adress for my wallet in the transaction via palm.IO but it’s been over 24 hours and still haven’t received the 92 DAI I transferred. *

### Environment
* Elixir Version: 1.12.2
* Erlang Version: 24
* BlockScout Version: 

* User Agent: `Mozilla/5.0 (iPhone; CPU iPhone OS 13_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) CriOS/76.0.3809.123 Mobile/15E148 Safari/605.1`

### Steps to reproduce

*Tell us how to reproduce this issue. If possible, push up a branch to your fork with a regression test we can run to reproduce locally.*

### Expected Behaviour

*Tell us what should happen.*

### Actual Behaviour

*Tell us what happens instead.*

**Comment by vbaranov** [comment]
There is no Palm support here.
