### ISSUE TITLE
xDai: Wrong Decimal Display

### ISSUE THREAD

**Issue by lucasassislar** [blockscout/blockscout#5007]
Hello, I'm from Liqi and were using Blockscout to show the log of transactions our users' wallets have, but it's displaying the values incorrectly due to a different number of decimals.
Example: https://blockscout.com/xdai/mainnet/address/0x51eaDb3E5Fa505f83bf76cEF62d7FE7050248Adb/transactions
Our contract uses 20 decimals instead of 18.

### Steps to reproduce

Just open the provided link and select any transaction, they all show the wrong value.

### Expected Behaviour

Display the correct value with 20 decimals

### Actual Behaviour

Values are being treated as if they were 18

**Comment by Flllexa** [comment]
Example with wrong value:
https://blockscout.com/xdai/mainnet/token/0x51eaDb3E5Fa505f83bf76cEF62d7FE7050248Adb/token-transfers
