### ISSUE TITLE
CSV export: Error 504 when trying to export transactions

### ISSUE THREAD

**Issue by tristanhcole** [blockscout/blockscout#5009]
*Describe your issue here.*

### Environment
[blockscout.com](https://blockcout.com/)

### Steps to reproduce
Head to this link: https://blockscout.com/xdai/mainnet/transactions-csv?address_id=0xFCF8B0b0a9e2277347E7A42743ab7dEA8410764a&from_period=2020-09-01&to_period=2021-12-17

### Expected behaviour

*Tell us what should happen.*
Ability to export transactions without software timing out.

*Tell us what happens instead.*
Error 504 timeout

**Comment by vbaranov** [comment]
Can you try decreasing the period of export?

**Comment by tristanhcole** [comment]
> Can you try decreasing the period of export?
Not really, I want to export a large amount of transactions...

**Comment by helderjnpinto** [comment]
i'm getting the same problem but with small or not existent transactions for download where is the example https://explorer.tst.publicmint.io/csv-export?address=0xa0D6f62e5f987ba73A6392c78D0541a022e4E332&type=transactions 

in the logs of database we got
![image](https://user-images.githubusercontent.com/12281088/200624413-eabc741f-a206-40ce-97bb-8c368cc41e9d.png)



Query: 
>database_1          | 2022-11-08 15:35:32.617 UTC [27837] LOG:  duration: 59051.252 ms  execute <unnamed>: SELECT max(b0."number") FROM "blocks" AS b0 WHERE (DATE(timestamp) = TO_DATE($1, 'YYYY-MM-DD'))

Sometimes work with small amout of transactions or empty, and sometimes got 504 in any case.

**Comment by helderjnpinto** [comment]
i updated for version 4.18 and it's working fine for now. last test i exported 800 transactions and it's relativelly fast.
