### ISSUE TITLE
Palm: transferring out to crypto.com 

### ISSUE THREAD

**Issue by Homa0602** [blockscout/blockscout#5010]
Transferred 2354 dai out of palm network via MetaMask to crypto.com dai wallet. Cannot view funds?[MetaMask wallet](0x640667435415b2AD210F25658B8de7f949caE521) 

wondering if I lost the funds completely or what I need to do to rectify!?

thanks, 
Matt

### Environment
* Elixir Version: 1.12.2
* Erlang Version: 24
* BlockScout Version: 

* User Agent: `Mozilla/5.0 (iPhone; CPU iPhone OS 15_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Mobile/15E148`

### Steps to reproduce

*Tell us how to reproduce this issue. If possible, push up a branch to your fork with a regression test we can run to reproduce locally.*

### Expected Behaviour

*Tell us what should happen.*

### Actual Behaviour

*Tell us what happens instead.*

**Comment by vbaranov** [comment]
There is no Palm support here
