### ISSUE TITLE
Seemingly incorrect internal call with value for transaction

### ISSUE THREAD

**Issue by area** [blockscout/blockscout#5013]
### Environment

* Xdai Chain, Blockscout.com, v4.0.0-beta

### Steps to reproduce

The issues is around [this](https://blockscout.com/xdai/mainnet/tx/0x2cacb5af9280a01b3ae0c041d2ecf22bd30939e5225dd61fd3c3a068a16a0516) transaction.

### Expected behaviour

If you look at the internal transactions, there are two with value - one with 460xdai near the start, and one with 460xdai near the end. The one at the end, the xdai goes from `0xf3b..`. (the contract being interacted with) to `0xcfd...`

This is surprising, as while the incoming amount is correct, going out from the contract side we expected 135 to be going from `0xf3b...` to `0xd9e4...` (as a refund to the 'from' address for the transaction) and the remainder (around 325) going to `0xcfd...`

If you look at the [coin balance history](https://blockscout.com/xdai/mainnet/address/0xD9e4BD02982406F50d397bAaF1E7fc698b3511Fd/coin-balances) for the 'from' address, it shows the correct overall decrease for that block (-325, block 19619003).

[Tracing the tx](https://dashboard.tenderly.co/tx/xdai/0x2cacb5af9280a01b3ae0c041d2ecf22bd30939e5225dd61fd3c3a068a16a0516/debugger?trace=0.1.10) on Tenderly appears to suggest the correct behaviour. That link should go to line 2323, which is the first transfer (the refund for 135 xDai), and then the next step is 325 xDai going to `0xcfd...`

Finally, querying an archive node agrees with the balance page
![screenshot-2021-12-17_23-51-02](https://user-images.githubusercontent.com/311812/146633360-cd34bf3e-fef0-471a-9138-a6c19cb04fd9.png)

**Comment by vbaranov** [comment]
<img width="1350" alt="Screenshot 2021-12-18 at 13 24 14" src="https://user-images.githubusercontent.com/4341812/146636254-3df89442-5450-4a65-9310-5d011820223c.png">

The issue existed due to the bug of the archive node. It was patched and the block has been re-fetched. Internal transactions look now as you expected.

**Comment by area** [comment]
Thanks for the quick turnaround, really appreciated.
