### ISSUE TITLE
Wrong names for PLS and WPLS

### ISSUE THREAD

**Issue by Sieniak-ms** [blockscout/blockscout#5017]
I did swapPLS to WPLS at https://uniswap.v2.testnet.pulsechain.com/#/swap usiing MEtaMAsk and there are wrong labels ETH instad of PLS or WETH intead WPLS. See attached picture.
![pls_eth](https://user-images.githubusercontent.com/96372847/146670864-ff68fed2-3340-4b05-91e7-779ec0417aab.jpg)

**Comment by vbaranov** [comment]
Here is the wrong place to ask. Nothing related to Blockscout.
