### ISSUE TITLE
Palm: <Issue Title>

### ISSUE THREAD

**Issue by BraveJustice** [blockscout/blockscout#5026]
*Describe your issue here.*

Hello,

I sent my dai to voyager and they’re not showing up

https://explorer.palm.io/address/0x51AAE72f3B200e35FFceeA10E1D705ABe2bB8315/token-transfers

### Environment
* Elixir Version: 1.12.2
* Erlang Version: 24
* BlockScout Version: 

* User Agent: `Mozilla/5.0 (iPhone; CPU iPhone OS 15_2 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) CriOS/96.0.4664.101 Mobile/15E148 Safari/604.1`

### Steps to reproduce

*Tell us how to reproduce this issue. If possible, push up a branch to your fork with a regression test we can run to reproduce locally.*

### Expected Behaviour

*Tell us what should happen.*

### Actual Behaviour

*Tell us what happens instead.*

**Comment by vbaranov** [comment]
No Palm support here
