### ISSUE TITLE
Ethereum Classic: <wrong transaction ETC to ETH>

### ISSUE THREAD

**Issue by Gavinchi236** [blockscout/blockscout#5029]
*Describe your issue here.*

I send the funds (ETC coins) from my phone trust wallet app to my friends, and I direct scan  my friend phone QR code picture (my friend Destination wallet is MEXC APP) and send was success, but a couple hours later his check the phone still didn’t receive the ETC coin and we find we have a mistake, we used ETH instead ETC address.

Now my questions is this transaction was mistake and I didn’t get the ETC back
This is my transaction ID: 0x0e6209b417c709c3fde75cef070568c569169c470210893c1a20d5dcd03668eb

Can you please check for me where is my crypto going, thank you so much for help

### Environment
* Elixir Version: 1.11.4
* Erlang Version: 23
* BlockScout Version: v3.7.3-beta

* User Agent: `Mozilla/5.0 (iPhone; CPU iPhone OS 15_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/15.1 Mobile/15E148 Safari/604.1`

### Steps to reproduce

*Tell us how to reproduce this issue. If possible, push up a branch to your fork with a regression test we can run to reproduce locally.*

### Expected Behaviour

*Tell us what should happen.*

### Actual Behaviour

*Tell us what happens instead.*

**Comment by vbaranov** [comment]
Regarding your question try to reach out ETC team, for instance, on their Discord https://discord.com/invite/hQs894U.
