### ISSUE TITLE
Energy Web Chain: <transaction not working (pending for a months)>

### ISSUE THREAD

**Issue by theyuvalr** [blockscout/blockscout#5037]
*i am trying to transfer the EWT token to my kucoin account but it seems like i cannot do it due to a failed (and still pending) transaction ive made a while ago ( a few month). i cannot cancel the still panding transaction thus i cannot get my ewt out of my wallet. 
it seems like i cannot make a transaction while this one is pending.

whould you kindly help me with that? 

i can add a screenshot if needed, the deal identity is:

0xd1d8472db760eecfe5a570cad9059696dc148b17a9f0690f84d87219471ebea7
.*

### Environment
* Elixir Version: 1.11.4
* Erlang Version: 23
* BlockScout Version: v3.7.3-beta

* User Agent: `Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.110 Safari/537.36`

### Steps to reproduce

*Tell us how to reproduce this issue. If possible, push up a branch to your fork with a regression test we can run to reproduce locally.*

### Expected Behaviour

*Tell us what should happen.*

### Actual Behaviour

*Tell us what happens instead.*

**Comment by vbaranov** [comment]
Energy Web Chain is not supported here. Please contact the team directly.

**Comment by theyuvalr** [comment]
thank you sir, but what team?

**Comment by vbaranov** [comment]
https://www.energyweb.org/
