### ISSUE TITLE
Gnosis Chain: <Issue Title>

### ISSUE THREAD

**Issue by moromoke1603** [blockscout/blockscout#5044]
Transaction issue

### Environment
* Elixir Version: 1.12.2
* Erlang Version: 24
* BlockScout Version: v4.0.0-beta

* User Agent: `Mozilla/5.0 (Linux; Android 11; SM-A125F Build/RP1A.200720.012; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/87.0.4280.141 Mobile Safari/537.36`

### Steps to reproduce

*Tell us how to reproduce this issue. If possible, push up a branch to your fork with a regression test we can run to reproduce locally.*

### Expected Behaviour

*the account I sent usdt was supposed to be credited with 42usd.*

### Actual Behaviour

*the account was not credited *

**Comment by vbaranov** [comment]
Questions can be asked in the #poa channel on Discord https://discord.gg/mPJ9zkq
