### ISSUE TITLE
Gnosis Chain: I can use the link to get free xDai

### ISSUE THREAD

**Issue by SanazR** [blockscout/blockscout#5050]
Hi,

I want to bridge some Dai tokens to my xDai, however, I am not able to use the below link to get free xDai for my gas fee.
It shows a "404, Page not found" error.

https://blockscout.com/xdai/mainnet/faucet

Would you please assist me?

Thanks,
Sanaz

**Comment by vbaranov** [comment]
Faucet #1 - https://xdai-app.herokuapp.com/faucet 

Faucet #2 - https://stakely.io/faucet/xdai-chain
