### ISSUE TITLE
Testnet: My tokens are not showing in Metamask after import contract addresses for USDC/HEX etc

### ISSUE THREAD

**Issue by deanh2k** [blockscout/blockscout#5052]
My tokens are not showing in Metamask after import contract addresses for USDC/HEX etc using testnet

When I check my address 0x9Dbea38cD4557b0D3B51E887Ed73044681608e41

### Environment
* Elixir Version: 1.12.2
* Erlang Version: 24
* BlockScout Version: 

* User Agent: `Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.110 Safari/537.36`

### Steps to reproduce

View on Etherscan and then Pulsechain TestNet 0x9Dbea38cD4557b0D3B51E887Ed73044681608e41

### Expected Behaviour

Should see "some" of my tokens, had in before Sept 2021 snapshot

### Actual Behaviour

no tokens showing

**Comment by vbaranov** [comment]
There is no support of Pulsechain
