### ISSUE TITLE
token images appearing twice

### ISSUE THREAD

**Issue by zalam003** [blockscout/blockscout#5054]
Token images are displayed twice on the `Tokens` page:

![image](https://user-images.githubusercontent.com/48445346/147784623-9391bca6-453f-4d70-afd1-59128e7e136a.png)

### Steps to reproduce

Go to https://blockscout.com/xdai/mainnet/bridged-tokens/eth

### Expected behaviour

Only one token image should be displayed

### Actual behaviour

Token images are repeated

**Comment by vbaranov** [comment]
Thanks, fixed.
