### ISSUE TITLE
Palm: Funds not yet received

### ISSUE THREAD

**Issue by moroseUncertain** [blockscout/blockscout#5056]
Transferred eth from metamask palm network to ZBpro but funds have not received it yet. It’s been a day.

### Environment
* Elixir Version: 1.12.2
* Erlang Version: 24
* BlockScout Version: 

* User Agent: `Mozilla/5.0 (iPhone; CPU iPhone OS 15_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/15.1 Mobile/15E148 Safari/604.1`

### Steps to reproduce

*Tell us how to reproduce this issue. If possible, push up a branch to your fork with a regression test we can run to reproduce locally.*

### Expected Behaviour

*Tell us what should happen.*

### Actual Behaviour

*Tell us what happens instead.*

**Comment by tkyywl1340057** [comment]
I withdrew the cash from MNU chain at 0xbaef8ed3893b61c49caebbe15719ecb56a0f103, but it didn't arrive. It was transferred to 0x1400e0a1626a70cd8cce9081b702e7945385a44c. How can I find it back? Please help me, thank you

**Comment by vbaranov** [comment]
There is no Palm support here.
