### ISSUE TITLE
Ethereum Classic: QUESTION - Are there API rate limits?

### ISSUE THREAD

**Issue by cornopaez** [blockscout/blockscout#5058]
Hello there,

I'm developing an application for personal use that queries your ETH and ETC APIs to gather transactions and balances for addresses. As of today, the ETC endpoints are throwing random 429 HTTP errors. This happens when querying the APIs manually using Postman as well as my NodeJS code.

Are rate limits being enforced? If so, what are those limits?

**Comment by yawhide** [comment]
dec 30th, PR was merged https://github.com/blockscout/blockscout/pull/5030

says 30 req/s on the PR description

**Comment by bernatfp** [comment]
@yawhide are these limits supposed to be per user or global?

**Comment by vbaranov** [comment]
> are these limits supposed to be per user or global?

answered in https://github.com/blockscout/blockscout/pull/5030#issuecomment-1004272705
