### ISSUE TITLE
Ethereum Classic: <Issue Title>

### ISSUE THREAD

**Issue by Sumintrad** [blockscout/blockscout#5061]
I accidentally sent ETC to a wrong ETC address. Can this be reversed?

### Environment
* Elixir Version: 1.12.2
* Erlang Version: 24
* BlockScout Version: v4.1.0-beta

* User Agent: `Mozilla/5.0 (Linux; Android 8.1.0; LM-Q710(FGN)) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.104 Mobile Safari/537.36`

### Steps to reproduce

*Tell us how to reproduce this issue. If possible, push up a branch to your fork with a regression test we can run to reproduce locally.*

### Expected Behaviour

*Tell us what should happen.*

### Actual Behaviour

*Tell us what happens instead.*

**Comment by vbaranov** [comment]
Ethereum Classic Discord is here https://discord.com/invite/bMGuZsA
