### ISSUE TITLE
Read contract throwing error

### ISSUE THREAD

**Issue by zalam003** [blockscout/blockscout#5064]
v4.1.0 is throwing `error` when access read contract:

https://blockscout.com/xdai/mainnet/address/0x8e5bBbb09Ed1ebdE8674Cda39A0c169401db4252/read-contract

![image](https://user-images.githubusercontent.com/48445346/147984986-9aa64fa2-6780-4ec3-b38a-31bad1ff56d8.png)

**Comment by zalam003** [comment]
@nikitosing The error happens for proxy contracts.

**Comment by vbaranov** [comment]
This issue has been resolved - patch installed to Gnosis chain BlockScout instance.
