### ISSUE TITLE
Wrong miner address with latest geth poa(clique), mix test seems to be failed

### ISSUE THREAD

**Issue by hjhjdev** [blockscout/blockscout#5065]
*Describe your issue here.*

### Environment

* Elixir & Erlang/OTP versions (`elixir -version`): elixir 1.12.3-otp-24 erlang 24.2 nodejs 16.13.0
* Operating System: Ubuntu 20.04
* Blockscout Version/branch: V4.1.0 beta

### Steps to reproduce
I've created private poa network with clique engine, enabled configs below.
There were three validators,

    "homesteadBlock": 0,
    "eip150Block": 0,
    "eip150Hash": "0x0000000000000000000000000000000000000000000000000000000000000000",
    "eip155Block": 0,
    "eip158Block": 0,
    "byzantiumBlock": 0,
    "constantinopleBlock": 0,
    "petersburgBlock": 0,
    "istanbulBlock": 0,
    "berlinBlock": 0,
    "londonBlock": 0,
    "clique": {
      "period": 5,
      "epoch": 30000
    }

export NETWORK="testnet"
export COIN="testcoin"
export LOGO="/images/blockscout_logo.svg"
export ETHEREUM_JSONRPC_VARIANT="geth"
export ETHEREUM_JSONRPC_HTTP_URL="http://localhost:58545"
export ETHEREUM_JSONRPC_TRACE_URL="http://localhost:58545"
export ETHEREUM_JSONRPC_WS_URL="ws://localhost:58546"
export SECRET_KEY_BASE="(generated)"
export PORT="3000"
export DATABASE_URL="(url)"
export CHAIN_SPEC_PATH="/root/genesis-main.json"
export SHOW_ADDRESS_MARKETCAP_PERCENTAGE="false"
export SHOW_PRICE_CHART="false"
export SHOW_TXS_CHART="false"
#export APPS_MENU="false"
#export EXTERNAL_APPS=""
export DISABLE_EXCHANGE_RATES="true"
#export DISABLE_KNOWN_TOKENS="false"
export CHAIN_ID="(chainid)"
export DISABLE_BRIDGE_MARKET_CAP_UPDATER="true"
export BLOCK_TRANSFORMER="clique"
export ENABLE_1559_SUPPORT="true"

### Expected behaviour
miner address should be parsed correctly.

### Actual behaviour
Blockscout parses random miner addresses with wallet count same as blockNumber.
So I've run tests and got those errors below: odd-length string.

 56) test Indexer.Block.Fetcher.fetch_and_import_range/1 in range with internal transactions (Indexer.Block.Realtime.FetcherTest)
     test/indexer/block/realtime/fetcher_test.exs:45
     ** (ArgumentError) odd-length string
     code: }} = Indexer.Block.Fetcher.fetch_and_import_range(block_fetcher, 3_946_079..3_946_080)
     stacktrace:
       (elixir 1.12.3) lib/base.ex:349: Base.decode16!/2
       (indexer 0.1.0) lib/indexer/transform/blocks.ex:55: Indexer.Transform.Blocks.signature_hash/1
       (indexer 0.1.0) lib/indexer/transform/blocks.ex:33: Indexer.Transform.Blocks.signer/1
       (indexer 0.1.0) lib/indexer/transform/blocks/clique.ex:14: Indexer.Transform.Blocks.Clique.transform/1
       (elixir 1.12.3) lib/enum.ex:1582: Enum."-map/2-lists^map/1-0-"/2
       (indexer 0.1.0) lib/indexer/block/fetcher.ex:132: Indexer.Block.Fetcher.fetch_and_import_range/2
       test/indexer/block/realtime/fetcher_test.exs:542: (test)

     The following output was logged:
     2022-01-04T06:27:03.634 application=ecto_sql [debug] QUERY OK db=0.1ms
     begin []
     2022-01-04T06:27:03.635 application=ecto_sql [debug] QUERY OK source="address_token_balances" db=0.4ms
     SELECT a0."id", a0."value", a0."block_number", a0."value_fetched_at", a0."token_id", a0."token_type", a0."address_hash", a0."token_contract_address_hash", a0."inserted_at", a0."updated_at" FROM "address_token_balances" AS a0 INNER JOIN "tokens" AS t1 ON a0."token_contract_address_hash" = t1."contract_address_hash" WHERE (((((a0."address_hash" != $1) AND (t1."type" != 'ERC-721')) OR (t1."type" = 'ERC-20')) OR (t1."type" = 'ERC-1155')) AND ((a0."value_fetched_at" IS NULL) OR (a0."value" IS NULL))) [<<0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0>>]
     2022-01-04T06:27:03.636 application=ecto_sql [debug] QUERY OK source="address_token_balances" db=0.1ms
     SELECT a0."id", a0."value", a0."block_number", a0."value_fetched_at", a0."token_id", a0."token_type", a0."address_hash", a0."token_contract_address_hash", a0."inserted_at", a0."updated_at" FROM "address_token_balances" AS a0 INNER JOIN "tokens" AS t1 ON a0."token_contract_address_hash" = t1."contract_address_hash" WHERE (((((a0."address_hash" != $1) AND (t1."type" != 'ERC-721')) OR (t1."type" = 'ERC-20')) OR (t1."type" = 'ERC-1155')) AND ((a0."value_fetched_at" IS NULL) OR (a0."value" IS NULL))) [<<0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0>>]

<img width="2141" alt="Screen Shot 2022-01-04 at 3 36 52 PM" src="https://user-images.githubusercontent.com/17705694/148019169-43faa1dd-7149-4dfd-8e44-4efc9c1baa0b.png">

**Comment by hjhjdev** [comment]
https://github.com/blockscout/blockscout/issues/4616#issue-991256912

**Comment by ayanamidev** [comment]
Fixed by #5669

**Comment by hjhjdev** [comment]
Thanks!
