### ISSUE TITLE
Palm: <Issue Title>

### ISSUE THREAD

**Issue by HenryAP-design** [blockscout/blockscout#5067]
*I placed my minted Nifty Matrix on the second-hand market provided by Nifty. The nft was listed on 12/02/2021 10:40AM. The item was then bought on the 12/27/2021 8:17AM. I am having trouble viewing the DAO token which it was bought with. Please provide me with assistance to resolve this issue. I hope to hear from you as soon as possible thank you. *

### Environment
* Elixir Version: 1.12.2
* Erlang Version: 24
* BlockScout Version: 

* User Agent: `Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.110 Safari/537.36`

### Steps to reproduce

*Tell us how to reproduce this issue. If possible, push up a branch to your fork with a regression test we can run to reproduce locally.*

### Expected Behaviour

*Tell us what should happen.*

### Actual Behaviour

*Tell us what happens instead.*

**Comment by vbaranov** [comment]
Palm instance is not supported here
