### ISSUE TITLE
Gnosis Chain: <add logo>

### ISSUE THREAD

**Issue by yakusag** [blockscout/blockscout#5070]
*Describe your issue here.*

### Environment
* Elixir Version: 1.12.2
* Erlang Version: 24
* BlockScout Version: v4.1.0-beta

* User Agent: `Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.110 Safari/537.36`

### Steps to reproduce

*Tell us how to reproduce this issue. If possible, push up a branch to your fork with a regression test we can run to reproduce locally.*

### Expected Behaviour

*add logo .*

### Actual Behaviour

*add logo.*

**Comment by yakusag** [comment]
Add logo

**Comment by vbaranov** [comment]
We will add a logo for Gnosis Chain once it will be ready.

**Comment by yakusag** [comment]
@vbaranov thank you
