### ISSUE TITLE
Gnosis Chain: <Issue Title>

### ISSUE THREAD

**Issue by emma202201** [blockscout/blockscout#5073]
To whom may concern,

This is Emma from Get Chain PTE. LTD. We are a smart contracts platform in the blockchain industry, under the activity of any proof-of-stake protocol. As we know you have openosurces for us to download, however, we are going to use for business purpose, do we need to get the authorization from you? And how much we need to pay for the authorization?

You may contact me with this email emma.yuchiehtai@gmail.com. I am looking forward to your reply.

Sincerely,
Emma

### Environment
* Elixir Version: 1.12.2
* Erlang Version: 24
* BlockScout Version: v4.1.0-beta

* User Agent: `Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.0.3 Safari/605.1.15`

### Steps to reproduce

*Tell us how to reproduce this issue. If possible, push up a branch to your fork with a regression test we can run to reproduce locally.*

### Expected Behaviour

*Tell us what should happen.*

### Actual Behaviour

*Tell us what happens instead.*

**Comment by vbaranov** [comment]
Blockscout software is under GPL3 license https://github.com/blockscout/blockscout/blob/master/LICENSE

**Comment by emma202201** [comment]
Hello Victor,

Hope this email finds you well.
I am writing to ask about the UI design of your open-source explorer, we
would like to adjust the layout a little bit.
Please let me know if we need to get the official authorization from your
side?
If so, kindly let me know who should I contact. Thank you so much.

Sincerely,
Emma



Victor Baranov ***@***.***> 於 2022年1月10日 週一 下午6:19寫道：
