### ISSUE TITLE
Docker failed to deploy blockScout. Procedure

### ISSUE THREAD

**Issue by avatarvip** [blockscout/blockscout#5079]
*Describe your issue here.*

### Environment

* Elixir & Erlang/OTP versions (`elixir -version`):
* Operating System: CentOS 7.2 
* Blockscout Version/branch: 
This problem occurs with the latest version and with previous versions
### Steps to reproduce

Docker go to block-scout-web Step 18/20: RUN cd apps/block_scout_web/assets/ &&     npm install &&     npm run deploy &&     cd -
---> Running in dff2ee69ee92
An error is reported after this step

Error is as follows

[webpack-cli] Compilation finished
[webpack-cli] Compilation finished
[webpack-cli] Compilation finished
[webpack-cli] Compilation finished
asset address_contract/code_highlighting.js 915 KiB [emitted] [minimized] [big] (name: main) 1 related asset
runtime modules 657 bytes 3 modules
modules by path ./node_modules/highlight.js/lib/languages/*.js 1.19 MiB 190 modules
modules by path ./node_modules/highlight.js/lib/*.js 76.2 KiB
  ./node_modules/highlight.js/lib/index.js 11.8 KiB [built] [code generated]
  ./node_modules/highlight.js/lib/core.js 64.4 KiB [built] [code generated]
./js/view_specific/address_contract/code_highlighting.js 199 bytes [built] [code generated]
./node_modules/jquery/dist/jquery.js 281 KiB [built] [code generated]

WARNING in asset size limit: The following asset(s) exceed the recommended size limit (244 KiB).
This can impact web performance.
Assets: 
  address_contract/code_highlighting.js (915 KiB)

WARNING in entrypoint size limit: The following entrypoint(s) combined asset size exceeds the recommended limit (244 KiB). This can impact web performance.
Entrypoints:
  main (915 KiB)
      address_contract/code_highlighting.js

WARNING in webpack performance recommendations: 
You can limit the size of your bundles by using import() or require.ensure to lazy load some parts of your application.
For more info visit https://webpack.js.org/guides/code-splitting/

webpack 5.8.0 compiled with 3 warnings in 18865 ms

asset raw_trace/code_highlighting.js 915 KiB [emitted] [minimized] [big] (name: main) 1 related asset
runtime modules 657 bytes 3 modules
modules by path ./node_modules/highlight.js/lib/languages/*.js 1.19 MiB 190 modules
modules by path ./node_modules/highlight.js/lib/*.js 76.2 KiB
  ./node_modules/highlight.js/lib/index.js 11.8 KiB [built] [code generated]
  ./node_modules/highlight.js/lib/core.js 64.4 KiB [built] [code generated]
./js/view_specific/raw_trace/code_highlighting.js 199 bytes [built] [code generated]
./node_modules/jquery/dist/jquery.js 281 KiB [built] [code generated]

WARNING in asset size limit: The following asset(s) exceed the recommended size limit (244 KiB).
This can impact web performance.
Assets: 
  raw_trace/code_highlighting.js (915 KiB)

WARNING in entrypoint size limit: The following entrypoint(s) combined asset size exceeds the recommended limit (244 KiB). This can impact web performance.
Entrypoints:
  main (915 KiB)
      raw_trace/code_highlighting.js

WARNING in webpack performance recommendations: 
You can limit the size of your bundles by using import() or require.ensure to lazy load some parts of your application.
For more info visit https://webpack.js.org/guides/code-splitting/

webpack 5.8.0 compiled with 3 warnings in 18839 ms

assets by status 51.1 MiB [cached] 196 assets
runtime modules 41.4 KiB 206 modules
orphan modules 312 KiB [orphan] 79 modules
modules by path ./node_modules/ 4.84 MiB
  javascript modules 4.79 MiB 720 modules
  json modules 52.3 KiB 17 modules
modules by path ./js/ 302 KiB 31 modules
modules by path ./css/*.scss 128 bytes (javascript) 10.6 KiB (css/mini-extract)
  modules with errors 78 bytes [errors] 2 modules
  2 modules
modules by path ../../../deps/ 37.8 KiB
  ../../../deps/phoenix_html/priv/static/phoenix_html.js 2.21 KiB [built] [code generated]
  ../../../deps/phoenix/priv/static/phoenix.js 35.6 KiB [built] [code generated]
buffer (ignored) 15 bytes [optional] [built] [code generated]
crypto (ignored) 15 bytes [optional] [built] [code generated]
util (ignored) 15 bytes [built] [code generated]

ERROR in ./css/app.scss
Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js):
ModuleBuildError: Module build failed (from ./node_modules/sass-loader/dist/cjs.js):
SassError: Undefined variable: "$additional-font".
        on line 881 of css/theme/_dark-theme.scss
        from line 122 of css/app.scss
>> 				color: $additional-font;

   -----------^

    at processResult (/opt/app/apps/block_scout_web/assets/node_modules/webpack/lib/NormalModule.js:581:19)
    at /opt/app/apps/block_scout_web/assets/node_modules/webpack/lib/NormalModule.js:674:5
    at /opt/app/apps/block_scout_web/assets/node_modules/loader-runner/lib/LoaderRunner.js:397:11
    at /opt/app/apps/block_scout_web/assets/node_modules/loader-runner/lib/LoaderRunner.js:252:18
    at context.callback (/opt/app/apps/block_scout_web/assets/node_modules/loader-runner/lib/LoaderRunner.js:124:13)
    at Object.callback (/opt/app/apps/block_scout_web/assets/node_modules/sass-loader/dist/index.js:54:7)
    at Object.done [as callback] (/opt/app/apps/block_scout_web/assets/node_modules/neo-async/async.js:8069:18)
    at options.error (/opt/app/apps/block_scout_web/assets/node_modules/node-sass/lib/index.js:293:32)
 @ ./js/app.js 4:0-25

ERROR in ./css/stakes.scss
Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js):
ModuleBuildError: Module build failed (from ./node_modules/sass-loader/dist/cjs.js):
SassError: Undefined variable: "$dashboard-banner-gradient-start".
        on line 20 of css/_mixins.scss, in mixin `gradient-container`
        from line 8 of css/components/stakes/_stakes.scss
        from line 11 of css/stakes.scss
>>     $dashboard-banner-gradient-start,

   ----^

    at processResult (/opt/app/apps/block_scout_web/assets/node_modules/webpack/lib/NormalModule.js:581:19)
    at /opt/app/apps/block_scout_web/assets/node_modules/webpack/lib/NormalModule.js:674:5
    at /opt/app/apps/block_scout_web/assets/node_modules/loader-runner/lib/LoaderRunner.js:397:11
    at /opt/app/apps/block_scout_web/assets/node_modules/loader-runner/lib/LoaderRunner.js:252:18
    at context.callback (/opt/app/apps/block_scout_web/assets/node_modules/loader-runner/lib/LoaderRunner.js:124:13)
    at Object.callback (/opt/app/apps/block_scout_web/assets/node_modules/sass-loader/dist/index.js:54:7)
    at Object.done [as callback] (/opt/app/apps/block_scout_web/assets/node_modules/neo-async/async.js:8069:18)
    at options.error (/opt/app/apps/block_scout_web/assets/node_modules/node-sass/lib/index.js:293:32)
 @ ./js/pages/stakes.js 12:0-31

2 ERRORS in child compilations
webpack 5.8.0 compiled with 4 errors in 273343 ms

asset awesomplete.min.js 7.64 KiB [emitted] [minimized] (name: awesomplete)
asset awesomplete-util.min.js 6.61 KiB [emitted] [minimized] (name: awesomplete-util)
asset ../css/awesomplete.css 1.84 KiB [emitted] (name: awesomplete)
Entrypoint awesomplete 9.48 KiB = ../css/awesomplete.css 1.84 KiB awesomplete.min.js 7.64 KiB
Entrypoint awesomplete-util 6.61 KiB = awesomplete-util.min.js
runtime modules 657 bytes 3 modules
orphan modules 50 bytes [orphan] 1 module
code generated modules 37.7 KiB (javascript) 1.84 KiB (css/mini-extract) [code generated]
  modules by path ./js/lib/*.js 24.9 KiB
    ./js/lib/awesomplete.js 58 bytes [built] [code generated]
    ./js/lib/awesomplete-util.js 24.9 KiB [built] [code generated]
  modules by path ./node_modules/awesomplete/ 12.8 KiB (javascript) 1.84 KiB (css/mini-extract)
    ./node_modules/awesomplete/awesomplete.js 12.8 KiB [built] [code generated]
    css ./node_modules/css-loader/dist/cjs.js!./node_modules/awesomplete/awesomplete.css 1.84 KiB [code generated]
webpack 5.8.0 compiled successfully in 10686 ms
npm ERR! code 1
npm ERR! path /opt/app/apps/block_scout_web/assets
npm ERR! command failed
npm ERR! command sh -c webpack --mode production

npm ERR! A complete log of this run can be found in:
npm ERR!     /opt/app/.npm/_logs/2022-01-10T06_28_25_245Z-debug.log
The command '/bin/sh -c cd apps/block_scout_web/assets/ &&     npm install &&     npm run deploy &&     cd -' returned a non-zero code: 1
make: *** [build] Error 1

**Comment by vbaranov** [comment]
@avatarvip Could you elaborate on which command originally did you use to bundle and run Docker container? It should be `make start` from `./docker` folder as per https://docs.blockscout.com/for-developers/information-and-settings/docker-integration-local-use-only

**Comment by avatarvip** [comment]
> Could you elaborate on which command originally did you use to bundle and run Docker container? It should be `make start` from `./docker` folder as per https://docs.blockscout.com/for-developers/information-and-settings/docker-integration-local-use-only

make start

**Comment by vbaranov** [comment]
@avatarvip did the folder `./apps/block_scout_web/assets/node_modules` exist before you started to bundle docker container? If yes, please, remove it before executing `make start` command.

**Comment by avatarvip** [comment]
> @avatarvip did the folder `./apps/block_scout_web/assets/node_modules` exist before you started to bundle docker container? If yes, please, remove it before executing `make start` command.

Delete the directory in the./apps/block_scout_web/assets/node_modules path as you said and execute make start again, the result is the same. @vbaranov

**Comment by vbaranov** [comment]
@avatarvip what version of Docker do you use?

**Comment by avatarvip** [comment]
> @avatarvip what version of Docker do you use?

@avatarvip
Client:
 Version:         1.13.1
 API version:     1.26
 Package version: docker-1.13.1-162.git64e9980.el7.centos.x86_64
 Go version:      go1.10.3
 Git commit:      64e9980/1.13.1
 Built:           Wed Jul  1 14:56:42 2020
 OS/Arch:         linux/amd64

Server:
 Version:         1.13.1
 API version:     1.26 (minimum version 1.12)
 Package version: docker-1.13.1-162.git64e9980.el7.centos.x86_64
 Go version:      go1.10.3
 Git commit:      64e9980/1.13.1
 Built:           Wed Jul  1 14:56:42 2020
 OS/Arch:         linux/amd64
 Experimental:    false

**Comment by vbaranov** [comment]
@avatarvip please upgrade Docker to 20.x.x

**Comment by avatarvip** [comment]
> @avatarvip please upgrade Docker to 20.x.x

@vbaranov
I will try

**Comment by vbaranov** [comment]
I am closing this. Please re-open if you have the same issue with Docker 20.x.x

**Comment by avenbreaks** [comment]
> @avatarvip please upgrade Docker to 20.x.x

same issue : 

```
821 │                 color: $additional-font;
    │                        ^^^^^^^^^^^^^^^^
    ╵
  css/theme/_dark-theme.scss 821:12  @import
  css/main-page.scss 76:9            root stylesheet
    at Object.<anonymous> (/app/apps/block_scout_web/assets/node_modules/css-loader/dist/cjs.js!/app/apps/block_scout_web/assets/node_modules/postcss-loader/dist/cjs.js!/app/apps/block_scout_web/assets/node_modules/sass-loader/dist/cjs.js??ruleSet[1].rules[1].use[3]!/app/apps/block_scout_web/assets/css/main-page.scss:1:7)
    at /app/apps/block_scout_web/assets/node_modules/webpack/lib/javascript/JavascriptModulesPlugin.js:441:11
    at Hook.eval [as call] (eval at create (/app/apps/block_scout_web/assets/node_modules/tapable/lib/HookCodeFactory.js:19:10), <anonymous>:7:1)
    at /app/apps/block_scout_web/assets/node_modules/webpack/lib/Compilation.js:5057:39
    at tryRunOrWebpackError (/app/apps/block_scout_web/assets/node_modules/webpack/lib/HookWebpackError.js:83:7)
    at __webpack_require_module__ (/app/apps/block_scout_web/assets/node_modules/webpack/lib/Compilation.js:5055:12)
    at __webpack_require__ (/app/apps/block_scout_web/assets/node_modules/webpack/lib/Compilation.js:5012:18)
    at /app/apps/block_scout_web/assets/node_modules/webpack/lib/Compilation.js:5083:20
    at symbolIterator (/app/apps/block_scout_web/assets/node_modules/neo-async/async.js:3485:9)
    at done (/app/apps/block_scout_web/assets/node_modules/neo-async/async.js:3527:9)

Generated code for /app/apps/block_scout_web/assets/node_modules/css-loader/dist/cjs.js!/app/apps/block_scout_web/assets/node_modules/postcss-loader/dist/cjs.js!/app/apps/block_scout_web/assets/node_modules/sass-loader/dist/cjs.js??ruleSet[1].rules[1].use[3]!/app/apps/block_scout_web/assets/css/main-page.scss
1 | throw new Error("Module build failed (from ./node_modules/sass-loader/dist/cjs.js):\nSassError: Undefined variable.\n    ╷\n821 │                 color: $additional-font;\n    │                        ^^^^^^^^^^^^^^^^\n    ╵\n  css/theme/_dark-theme.scss 821:12  @import\n  css/main-page.scss 76:9            root stylesheet");

3 errors have detailed information that is not shown.
Use 'stats.errorDetails: true' resp. '--stats-error-details' to show it.

webpack 5.74.0 compiled with 6 errors in 444278 ms
The command '/bin/sh -c cd apps/block_scout_web/assets/ &&     npm install &&     npm run deploy &&     cd /app/apps/explorer/ &&     npm install &&     apk update &&     apk del --force-broken-world alpine-sdk gmp-dev automake libtool inotify-tools autoconf python3' returned a non-zero code: 1
make: *** [Makefile:396: build] Error 1
```

OS : Ubuntu Pro 22
Docker : 
```
Client: Docker Engine - Community
 Version:           20.10.19
 API version:       1.41
 Go version:        go1.18.7
 Git commit:        d85ef84
 Built:             Thu Oct 13 16:46:58 2022
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.19
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.18.7
  Git commit:       c964641
  Built:            Thu Oct 13 16:44:47 2022
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.8
  GitCommit:        9cd3357b7fd7218e4aec3eae239db1f68a5a6ec6
 runc:
  Version:          1.1.4
  GitCommit:        v1.1.4-0-g5fd4c4d
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```
