### ISSUE TITLE
Palm: <Issue Title>

### ISSUE THREAD

**Issue by jenmar16** [blockscout/blockscout#5083]
*Describe your issue here.* I purchased matrix nft money was transfered to the seller transaction was completed on 1/5/22. Never received my matrix nft. 

Help! 

### Environment
* Elixir Version: 1.12.2
* Erlang Version: 24
* BlockScout Version: 

* User Agent: `Mozilla/5.0 (iPhone; CPU iPhone OS 15_1_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/15.1 Mobile/15E148 Safari/604.1`

### Steps to reproduce

*Tell us how to reproduce this issue. If possible, push up a branch to your fork with a regression test we can run to reproduce locally.*

### Expected Behaviour

*Tell us what should happen.*

### Actual Behaviour

*Tell us what happens instead.*

**Comment by vbaranov** [comment]
There is no Palm support here
