### ISSUE TITLE
libsecp256k1 compilation fails

### ISSUE THREAD

**Issue by nicexe** [blockscout/blockscout#5084]
libsecp256k1 compilation fails during blockscout setup.

### Environment

* Elixir & Erlang/OTP versions (`elixir -version`): Erlang/OTP 24 [erts-12.1.5] [source] [64-bit] [smp:3:3] [ds:3:3:10] [async-threads:1] [jit], Elixir 1.13.0 (compiled with Erlang/OTP 24)
* Operating System: Ubuntu 20.04
* Blockscout Version/branch: v4.1.0-beta

### Steps to reproduce

I didn't change any code.  
I only set up some env vars and tried to setup blockscout as described here [Manual Deployment - BlockScout](https://docs.blockscout.com/for-developers/manual-deployment).  
It fails during step 7.

### Expected behaviour

Mix dependencies should be installed/compiled.

### Actual behaviour

libsecp256k1 compilation fails.
Here is an asciinema showing this in action: [libsecp256k1 fails - asciinema](https://asciinema.org/a/gVanAqiNrXvROBmJJVf69NsZc)

---

edit: added description on the top

**Comment by vbaranov** [comment]
@nicexe could you try with Elixir 1.12.3? 1.13.0 is not supported yet.
If this doesn't help, please, try with the master branch.

**Comment by nicexe** [comment]
@vbaranov thanks for the reply.
1.12.2 was the closest I could get.
I tried both on master and on v4.1.0-beta but it fails in the same way.

[libsecp256k1 fails - asciinema](https://asciinema.org/a/rNa6qNeBUpLuFjQ1cPZY1rylo)

**Comment by nicexe** [comment]
Thanks. It worked!
Was this dependency introduced recently because I believe I was able to run an older blockscout version without it.

**Comment by vbaranov** [comment]
> Was this dependency introduced recently because I believe I was able to run an older blockscout version without it.

Most likely no, because we didn't update libsecp256k1 package. Blockscout uses the latest version which is from Oct 18, 2018.
