### ISSUE TITLE
Palm: transaction from metamask 

### ISSUE THREAD

**Issue by Pugsyboy** [blockscout/blockscout#5086]
*Describe your issue here.*
Hi I sent palm straight to my coinbase ethereum account thinking it was ethereum based but its went missing. The trade is 0xb82ce48e51918b8d141b0e35e4b85402e6769b1cd02453c5a4ac1cc2a30ee0f2
If I can retrieve it thanks 
### Environment
* Elixir Version: 1.12.2
* Erlang Version: 24
* BlockScout Version: 

* User Agent: `Mozilla/5.0 (Linux; Android 11; SM-G998B Build/RP1A.200720.012; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/97.0.4692.70 Mobile Safari/537.36`

### Steps to reproduce

*Tell us how to reproduce this issue. If possible, push up a branch to your fork with a regression test we can run to reproduce locally.*

### Expected Behaviour

*Tell us what should happen.*

### Actual Behaviour

*Tell us what happens instead.*

**Comment by vbaranov** [comment]
Palm chain is not supported here
