### ISSUE TITLE
Ethereum Classic: <Issue Title>

### ISSUE THREAD

**Issue by OvOJM** [blockscout/blockscout#5087]
*Describe your issue here.*
So I didn’t realize “Meta Mask” only accepts ETH (Ethereum) and i sent $6 worth of ETC ( Ethereum classics) and I can’t resend money back to myself
### Environment
* Elixir Version: 1.12.2
* Erlang Version: 24
* BlockScout Version: v4.1.0-beta

* User Agent: `Mozilla/5.0 (iPhone; CPU iPhone OS 15_1_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/15.1 Mobile/15E148 Safari/604.1`

### Steps to reproduce

*Tell us how to reproduce this issue. If possible, push up a branch to your fork with a regression test we can run to reproduce locally.*

### Expected Behaviour

*Tell us what should happen.*

### Actual Behaviour

*Tell us what happens instead.*

**Comment by vbaranov** [comment]
Ethereum Classic Discord is here https://discord.com/invite/bMGuZsA
