### ISSUE TITLE
Ethereum Classic: <Issue Title>

### ISSUE THREAD

**Issue by OvOJM** [blockscout/blockscout#5089]
*Describe your issue here.*
I didn’t realize Meta Mask only accepted Ethereum and i sent Ethereum Classics instead… but it doesn’t show on the app so i cant even resend myself the ETC back..
### Environment
* Elixir Version: 1.12.2
* Erlang Version: 24
* BlockScout Version: v4.1.0-beta

* User Agent: `Mozilla/5.0 (iPhone; CPU iPhone OS 15_1_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/15.1 Mobile/15E148 Safari/604.1`

### Steps to reproduce

*Tell us how to reproduce this issue. If possible, push up a branch to your fork with a regression test we can run to reproduce locally.*

### Expected Behaviour

*Tell us what should happen.*
Should of went onto the app so i spend it on a NFT but now I just want it back to CoinBase 
### Actual Behaviour

*Tell us what happens instead.*
I pretty much lost my $6 of ETC..

**Comment by vbaranov** [comment]
You should ask in Ethereum Classic Discord https://discord.com/invite/bMGuZsA
