### ISSUE TITLE
what is the blocksсout minimal hardware requirements, and recommend hardware requirements？

### ISSUE THREAD

**Issue by baidang201** [blockscout/blockscout#5093]
*what is the blocksount minimal hardware requirements, and recommend hardware requirements？*

**Comment by vbaranov** [comment]
Minimal HW requirements for the application server:
2 vCPUs
4.0 GiB memory
10 GiB SSD or NVMe

Minimal HW requirements for the DB server:
2 vCPUs
4.0 GiB memory
20 GiB SSD or NVMe

Recommended HW requirements are highly dependant on the capacity of the chain and users activity.
