### ISSUE TITLE
Error compiling ex_keccak.ex

### ISSUE THREAD

**Issue by somoza** [blockscout/blockscout#5100]
I have an error while trying to compile the system.

### Environment

* Erlang/OTP 24 [erts-12.1.5] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [jit]
Elixir 1.13.0 (compiled with Erlang/OTP 24)
* Operating System: Debian
* Blockscout Version/branch: Last

### Steps to reproduce

mix deps.get && mix phx.server

### Expected behaviour

Get this working?

### Actual behaviour

Compiling 1 file (.ex)
    Updating crates.io index

== Compilation error in file lib/ex_keccak.ex ==
** (RuntimeError) calling `cargo metadata` failed.

    (rustler 0.23.0) lib/rustler/compiler/config.ex:86: Rustler.Compiler.Config.external_resources/2
    (rustler 0.23.0) lib/rustler/compiler/config.ex:69: Rustler.Compiler.Config.build/1
    (rustler 0.23.0) lib/rustler/compiler.ex:9: Rustler.Compiler.compile_crate/2
    lib/ex_keccak.ex:6: (module)

**Comment by somoza** [comment]
I went to folder _deps/ex_keccak/native/exkeccak_ and ran ```cargo metadata```

**Received this:**

```
warning: please specify `--format-version` flag explicitly to avoid compatibility problems
    Updating crates.io index
Segmentation fault
```

**Comment by somoza** [comment]
I found out the problem and the solution. The official installer provided by rust fails when you choose option 1) and did not add the bin directory to your $PATH, so you have to add manually on this way:

```
source $HOME/.cargo/env
source ~/.profile
```

You can close this but please don't delete it, could help some people.

**Comment by sg552** [comment]
use 1.55.0  , don't use the latest 1.58.0 

I suggest putting Rust's version into the .tool-versions file
