### ISSUE TITLE
"Contract" entries not generated in database when contract is created from within another contract 

### ISSUE THREAD

**Issue by xrpdevs** [blockscout/blockscout#5107]
"Contract" entries not generated in database when contract is created from within another contract (ie, deploying customized ERC20 from a factory contract, upgradeable proxy etc) 

If I manually try to verify the created contract using the API, then the "Read Proxy / Write Proxy / Read Contract / Write Contract" links appear when I click on "view contract" but clicking on any of those links results in a 404 error.

Using default RPC type, which I presume is "geth"

### Environment

Latest blockscout from github (as of about 2 days ago)

Erlang/OTP 24 [erts-12.1.4] [source] [64-bit] [smp:4:4] [ds:4:4:10] [async-threads:1] [jit]

Elixir 1.14.0-dev (be6cf22) (compiled with Erlang/OTP 24)

### Steps to reproduce

Described above

**Comment by vbaranov** [comment]
@xrpdevs do you have screenshots for a better understanding of the problem, which you experienced? Perhaps, you can provide the link to the contract's page as well?

> Elixir 1.14.0-dev (be6cf22) (compiled with Erlang/OTP 24)

We didn't test with this version yet. The supported one is 1.12.x.

**Comment by xrpdevs** [comment]
I did forget to mention that I had to make a small modification to ethereum_jsonrpc/lib/ethereum_jsonrpc/block.ex in order to get this to work with Flare Networks' geth implementation, could be related.

My (testnet) blockscout instance is open to public, so I can easily provide links and more information, will start again from genesis, and provide you with more detailed information including changes I had to make to source code.

**Comment by vbaranov** [comment]
@xrpdevs do you have the details for issue reproduction?

**Comment by vbaranov** [comment]
@xrpdevs I am closing this since ther is no response. If the issue is still actual, please open a new issue providing the steps for reproducing.
