### ISSUE TITLE
Price history not correct on the graphic

### ISSUE THREAD

**Issue by thomas59553** [blockscout/blockscout#5110]
First run
the price history in the graphic for past days is not correct

### Environment

* Elixir & Erlang/OTP versions (`elixir -12`):
* Operating System: ubuntu
* Blockscout Version/branch: 4.1.1 beta

### Steps to reproduce

first install
 export COINGECKO_COIN_ID=zynecoin
 export COIN_BALANCE_HISTORY_DAYS=10

### Expected behaviour

correct price history (0.30-0.40) $

### Actual behaviour

bad prices (9-10) $

2022-01-18T07:05:12.993 [error] GenServer #PID<0.8887.38> terminating
** (Protocol.UndefinedError) protocol Jason.Encoder not implemented for %Explorer.ExchangeRates.Token{available_supply: #Decimal<0.0>, btc_value:#Decimal<0.000009027619026353740585228338006>, id: "zynecoin", last_updated: ~U[2022-01-18 07:03:04.539Z], market_cap_usd: #Decimal<0.0>, name: "Zynecoin", symbol: "ZYN", total_supply: #Decimal<51009352.0>, usd_value: #Decimal<0.382071>, volume_24h_usd: #Decimal<160669>} of type Explorer.ExchangeRates.Token (a struct), Jason.Encoder protocol must always be explicitly implemented.

If you own the struct, you can derive the implementation specifying which fields should be encoded to JSON:

    @derive {Jason.Encoder, only: [....]}
    defstruct ...

It is also possible to encode all fields, although this should be used carefully to avoid accidentally leaking private information when new fieldsare added:

    @derive Jason.Encoder
    defstruct ...

Finally, if you don't own the struct you want to encode to JSON, you may use Protocol.derive/3 placed outside of any module:

    Protocol.derive(Jason.Encoder, NameOfTheStruct, only: [...])
    Protocol.derive(Jason.Encoder, NameOfTheStruct)
. This protocol is implemented for the following type(s): Any, Atom, BitString, BlockScoutWeb.API.EthRPC.View, Cldr.LanguageTag, Date, DateTime, D                                                                                           ecimal, Ecto.Association.NotLoaded, Ecto.Schema.Metadata, Explorer.Chain.Address, Explorer.Chain.BridgedToken, Explorer.Chain.Data, Explorer.Chain                                                                                           .DecompiledSmartContract, Explorer.Chain.Hash, Explorer.Chain.Token, Explorer.Chain.Transaction, Explorer.Chain.Transaction.History.TransactionSta                                                                                           ts, Float, Integer, Jason.Fragment, Jason.OrderedObject, List, Map, NaiveDateTime, Time
    (jason 1.3.0) lib/jason.ex:213: Jason.encode_to_iodata!/2
    (phoenix 1.5.13) lib/phoenix/socket/serializers/v2_json_serializer.ex:95: Phoenix.Socket.V2.JSONSerializer.encode!/1
    (phoenix 1.5.13) lib/phoenix/channel/server.ex:240: Phoenix.Channel.Server.push/6
    (block_scout_web 0.0.1) lib/block_scout_web/channels/exchange_rate_channel.ex:14: BlockScoutWeb.ExchangeRateChannel.handle_out/3
    (phoenix 1.5.13) lib/phoenix/channel/server.ex:327: Phoenix.Channel.Server.handle_info/2
    (stdlib 3.17) gen_server.erl:695: :gen_server.try_dispatch/4
    (stdlib 3.17) gen_server.erl:771: :gen_server.handle_msg/6
    (stdlib 3.17) proc_lib.erl:236: :proc_lib.wake_up/3
Last message: %Phoenix.Socket.Broadcast{event: "new_rate", payload: %{exchange_rate: %Explorer.ExchangeRates.Token{available_supply: #Decimal<0.0>                                                                                           , btc_value: #Decimal<0.000009027619026353740585228338006>, id: "zynecoin", last_updated: ~U[2022-01-18 07:03:04.539Z], market_cap_usd: #Decimal<0                                                                                           .0>, name: "Zynecoin", symbol: "ZYN", total_supply: #Decimal<51009352.0>, usd_value: #Decimal<0.382071>, volume_24h_usd: #Decimal<160669>}, market                                                                                           _history_data: [%{closing_price: #Decimal<0.382071>, date: ~D[2022-01-18]}, %{closing_price: #Decimal<9.167>, date: ~D[2022-01-17]}, %{closing_pri                                                                                           ce: #Decimal<9.357>, date: ~D[2022-01-16]}, %{closing_price: #Decimal<9.355>, date: ~D[2022-01-15]}, %{closing_price: #Decimal<9.355>, date: ~D[20                                                                                           22-01-14]}, %{closing_price: #Decimal<9.243>, date: ~D[2022-01-13]}, %{closing_price: #Decimal<9.535>, date: ~D[2022-01-12]}, %{closing_price: #De                                                                                           cimal<9.28>, date: ~D[2022-01-11]}, %{closing_price: #Decimal<9.082>, date: ~D[2022-01-10]}, %{closing_price: #Decimal<9.09>, date: ~D[2022-01-09]                                                                                           }, %{closing_price: #Decimal<9.05>, date: ~D[2022-01-08]}, %{closing_price: #Decimal<9.019>, date: ~D[2022-01-07]}, %{closing_price: #Decimal<9.35                                                                                           6>, date: ~D[2022-01-06]}, %{closing_price: #Decimal<9.429>, date: ~D[2022-01-05]}, %{closing_price: #Decimal<9.949>, date: ~D[2022-01-04]}, %{clo                                                                                           sing_price: #Decimal<10.08>, date: ~D[2022-01-03]}, %{closing_price: #Decimal<10.27>, date: ~D[2022-01-02]}, %{closing_price: #Decimal<10.36>, dat                                                                                           e: ~D[2022-01-01]}, %{closing_price: #Decimal<10.03>, date: ~D[2021-12-31]}, %{closing_price: #Decimal<10.23>, date: ~D[2021-12-30]}, %{closing_pr                                                                                           ice: #Decimal<10.09>, date: ~D[2021-12-29]}, %{closing_price: #Decimal<10.32>, date: ~D[2021-12-28]}, %{closing_price: #Decimal<11.01>, date: ~D[2                                                                                           021-12-27]}, %{closing_price: #Decimal<11.03>, date: ~D[2021-12-26]}, %{closing_price: #Decimal<10.95>, date: ~D[2021-12-25]}, %{closing_price: #D                                                                                           ecimal<11.04>, date: ~D[2021-12-24]}, %{closing_price: #Decimal<11.04>, date: ~D[2021-12-23]}, %{closing_price: #Decimal<10.55>, date: ~D[2021-12-                                                                                           22]}, %{closing_price: #Decimal<10.62>, date: ~D[2021-12-21]}, %{closing_price: #Decimal<10.18>, date: ~D[2021-12-20]}]}, topic: "exchange_rate:ne                                                                                           w_rate"}
State: %Phoenix.Socket{assigns: %{locale: "en"}, channel: BlockScoutWeb.ExchangeRateChannel, channel_pid: #PID<0.8887.38>, endpoint: BlockScoutWeb                                                                                           .Endpoint, handler: BlockScoutWeb.UserSocket, id: nil, join_ref: "6", joined: true, private: %{log_handle_in: :debug, log_join: :info}, pubsub_ser                                                                                           ver: BlockScoutWeb.PubSub, ref: nil, serializer: Phoenix.Socket.V2.JSONSerializer, topic: "exchange_rate:new_rate", transport: :websocket, transpo                                                                                           rt_pid: #PID<0.8426.38>}
2022-01-18T07:05:14.337 application=phoenix [info] JOINED exchange_rate:new_rate in 32µs
  Parameters: %{}

![pricepastday](https://user-images.githubusercontent.com/54393167/149888730-58cf61a7-efb4-45bc-b9f6-8f9dcd9dd4c8.jpg)

**Comment by nikolay-nikolaev** [comment]
Most probably I have the similar problem. But the difference exists. Market history is completely empty.
Coin is https://www.coingecko.com/en/coins/ekta

Config on test https://test.ektascan.io is:
    -e 'NETWORK=EKTA Chain' \
    -e 'SUBNETWORK=EktaScan' \
    -e 'CHAIN_ID=1004' \
    -e 'COIN=EKTA' \
    -e 'COINGECKO_COIN_ID=ekta-2' \
    -e 'COIN_BALANCE_HISTORY_DAYS=2' \
    -e 'SHOW_PRICE_CHART=true' \
    -e 'SHOW_TXS_CHART=false' \
    -e 'DISABLE_EXCHANGE_RATES=false' \
Config on live https://ektascan.io is:
    -e 'SUBNETWORK=EktaScan' \
    -e 'CHAIN_ID=1994' \
    -e 'COIN=EKTA' \
    -e 'SHOW_PRICE_CHART=true' \
    -e 'SHOW_TXS_CHART=true' \
    -e 'DISABLE_EXCHANGE_RATES=false' \

On test no errors in blockscout logs. But on live we have next error:
```
2022-02-02T06:12:58.584 [error] GenServer #PID<0.9710.5> terminating
** (Protocol.UndefinedError) protocol Jason.Encoder not implemented for %Explorer.ExchangeRates.Token{available_supply: #Decimal<11218645.94>, btc_value: #Decimal<0.00001134135225398268537966404342>, id: "ekta-2", last_updated: ~U[2022-02-02 06:04:33.814Z], market_cap_usd: #Decimal<4896945>, name: "Ekta", symbol: "EKTA", total_supply: #Decimal<2.205E+8>, usd_value: #Decimal<0.4365>, volume_24h_usd: #Decimal<30620>} of type Explorer.ExchangeRates.Token (a struct), Jason.Encoder protocol must always be explicitly implemented.

If you own the struct, you can derive the implementation specifying which fields should be encoded to JSON:

    @derive {Jason.Encoder, only: [....]}
    defstruct ...

It is also possible to encode all fields, although this should be used carefully to avoid accidentally leaking private information when new fields are added:

    @derive Jason.Encoder
    defstruct ...

Finally, if you don't own the struct you want to encode to JSON, you may use Protocol.derive/3 placed outside of any module:

    Protocol.derive(Jason.Encoder, NameOfTheStruct, only: [...])
    Protocol.derive(Jason.Encoder, NameOfTheStruct)
. This protocol is implemented for the following type(s): BlockScoutWeb.API.EthRPC.View, Explorer.Chain.Hash, Explorer.Chain.DecompiledSmartContract, Explorer.Chain.Transaction.History.TransactionStats, Explorer.Chain.BridgedToken, Explorer.Chain.Transaction, Explorer.Chain.Address, Explorer.Chain.Data, Explorer.Chain.Token, Cldr.LanguageTag, Ecto.Association.NotLoaded, Ecto.Schema.Metadata, Integer, DateTime, List, Decimal, NaiveDateTime, Time, Any, Jason.Fragment, Jason.OrderedObject, Atom, Map, BitString, Date, Float
    (jason 1.3.0) lib/jason.ex:213: Jason.encode_to_iodata!/2
    (phoenix 1.5.13) lib/phoenix/socket/serializers/v2_json_serializer.ex:95: Phoenix.Socket.V2.JSONSerializer.encode!/1
    (phoenix 1.5.13) lib/phoenix/channel/server.ex:240: Phoenix.Channel.Server.push/6
    (block_scout_web 0.0.1) lib/block_scout_web/channels/exchange_rate_channel.ex:14: BlockScoutWeb.ExchangeRateChannel.handle_out/3
    (phoenix 1.5.13) lib/phoenix/channel/server.ex:327: Phoenix.Channel.Server.handle_info/2
    (stdlib 3.15.1) gen_server.erl:695: :gen_server.try_dispatch/4
    (stdlib 3.15.1) gen_server.erl:771: :gen_server.handle_msg/6
    (stdlib 3.15.1) proc_lib.erl:236: :proc_lib.wake_up/3
Last message: %Phoenix.Socket.Broadcast{event: "new_rate", payload: %{exchange_rate: %Explorer.ExchangeRates.Token{available_supply: #Decimal<11218645.94>, btc_value: #Decimal<0.00001134135225398268537966404342>, id: "ekta-2", last_updated: ~U[2022-02-02 06:04:33.814Z], market_cap_usd: #Decimal<4896945>, name: "Ekta", symbol: "EKTA", total_supply: #Decimal<2.205E+8>, usd_value: #Decimal<0.4365>, volume_24h_usd: #Decimal<30620>}, market_history_data: []}, topic: "exchange_rate:new_rate"}
State: %Phoenix.Socket{assigns: %{locale: "en"}, channel: BlockScoutWeb.ExchangeRateChannel, channel_pid: #PID<0.9710.5>, endpoint: BlockScoutWeb.Endpoint, handler: BlockScoutWeb.UserSocket, id: nil, join_ref: "20", joined: true, private: %{log_handle_in: :debug, log_join: :info}, pubsub_server: BlockScoutWeb.PubSub, ref: nil, serializer: Phoenix.Socket.V2.JSONSerializer, topic: "exchange_rate:new_rate", transport: :websocket, transport_pid: #PID<0.9457.5>}
2022-02-02T06:12:59.718 application=phoenix [info] JOINED exchange_rate:new_rate in 20µs
  Parameters: %{}

```

**Comment by vbaranov** [comment]
@thomas59553 this is a bug of cryptocompare API, which is reproducible for ZYN coin.

https://min-api.cryptocompare.com/data/histoday?fsym=ZYN&limit=10&tsym=USD

The response is:
```
{"Response":"Success","Type":100,"Aggregated":false,"TimeTo":1644364800,"TimeFrom":1643500800,"FirstValueInArray":true,"ConversionType":{"type":"multiply","conversionSymbol":"ETH"},"Data":[{"time":1643500800,"high":8.23,"low":8.23,"open":8.29,"volumefrom":0,"volumeto":0,"close":8.23,"conversionType":"multiply","conversionSymbol":"BTC"},{"time":1643587200,"high":8.357,"low":8.357,"open":8.23,"volumefrom":0,"volumeto":0,"close":8.357,"conversionType":"multiply","conversionSymbol":"BTC"},{"time":1643673600,"high":8.406,"low":8.406,"open":8.357,"volumefrom":0,"volumeto":0,"close":8.406,"conversionType":"multiply","conversionSymbol":"BTC"},{"time":1643760000,"high":8.015,"low":8.015,"open":8.406,"volumefrom":0,"volumeto":0,"close":8.015,"conversionType":"multiply","conversionSymbol":"BTC"},{"time":1643846400,"high":8.104,"low":8.104,"open":8.015,"volumefrom":0,"volumeto":0,"close":8.104,"conversionType":"multiply","conversionSymbol":"BTC"},{"time":1643932800,"high":9.029,"low":9.029,"open":8.104,"volumefrom":0,"volumeto":0,"close":9.029,"conversionType":"multiply","conversionSymbol":"BTC"},{"time":1644019200,"high":8.992,"low":8.992,"open":9.029,"volumefrom":0,"volumeto":0,"close":8.992,"conversionType":"multiply","conversionSymbol":"BTC"},{"time":1644105600,"high":9.208,"low":9.208,"open":8.992,"volumefrom":0,"volumeto":0,"close":9.208,"conversionType":"multiply","conversionSymbol":"BTC"},{"time":1644192000,"high":9.522,"low":9.522,"open":9.208,"volumefrom":0,"volumeto":0,"close":9.522,"conversionType":"multiply","conversionSymbol":"BTC"},{"time":1644278400,"high":9.57,"low":9.57,"open":9.522,"volumefrom":0,"volumeto":0,"close":9.57,"conversionType":"multiply","conversionSymbol":"BTC"},{"time":1644364800,"high":0.322,"low":0.3058,"open":0.312,"volumefrom":0,"volumeto":0,"close":0.32,"conversionType":"multiply","conversionSymbol":"ETH"}],"RateLimit":{},"HasWarning":false}
```

If change USD to USDT API endpoint correct prices. In order to fix, you can change on your instance this line (USD => USDT):
https://github.com/blockscout/blockscout/blob/0aa4d2506e6a55a489b06a90055bc64d8d181c3c/apps/explorer/lib/explorer/market/history/source/crypto_compare.ex#L70
