### ISSUE TITLE
Running with indexer disabled doesn't refresh the interface when new blocks come in

### ISSUE THREAD

**Issue by valentinbud** [blockscout/blockscout#5115]
Hello everyone 👋 ,

I wanted to separate the indexer from the webapp and have managed to do so by 
setting the `DISABLED_INDEXER=false` on webapp instances.

But doing so results in the web interface not refreshing when new blocks come in.

There is also and indexer running that is not publicly accessible that indexed to the 
latest block and keeps on indexing properly.

I encounter this with https://github.com/oasisprotocol/emerald-blockscout fork.

### Environment

* Elixir & Erlang/OTP versions (`elixir -version`)
```
valentinbud@boninite:~ $ elixir -v
Erlang/OTP 24 [erts-12.1.5] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [jit] [dtrace]

Elixir 1.12.3 (compiled with Erlang/OTP 24)
``` 
* Operating System
```
valentinbud@boninite:~ $ uname -a
FreeBSD boninite 13.0-RELEASE-p6 FreeBSD 13.0-RELEASE-p6 #0: Mon Jan 10 06:28:50 UTC 2022     root@amd64-builder.daemonology.net:/usr/obj/usr/src/amd64.amd64/sys/GENERIC  amd64
```
* Blockscout Version/branch:  https://github.com/oasisprotocol/emerald-blockscout/tree/oasis-v4.1.1-beta, basically `v4.1.1-beta` with changes specific to Oasis.

### Steps to reproduce

Start the blockscout explorer with `DISABLED_INDEXER=false` and access the instance on its `PORT`

### Expected behaviour

I expect that new coming blocks to refresh the web interface just like it happens when running an instance with `DISABLED_INDEXER=false`

### Actual behaviour

The web interface doesn't get refreshed when new blocks are coming in. If refreshed manually new blocks can be 
seen.

It this expected behaviour? I though of doing this to horizontally scale the incoming websocket/http traffic and also vertically 
scale the indexer instance appropriately. Thank you!

**Comment by vbaranov** [comment]
@valentinbud  would you try with the latest state of the master branch https://github.com/blockscout/blockscout/commit/e9723772956edf851787112cc0174aeb4c7e83a4? We reworked processing of ENV variables, which probably could resolve the issue.

**Comment by valentinbud** [comment]
@vbaranov I have tried with [v4.1.2-beta](https://github.com/blockscout/blockscout/releases/tag/v4.1.2-beta) branch, same behaviour. I see that [e972377](https://github.com/blockscout/blockscout/commit/e9723772956edf851787112cc0174aeb4c7e83a4) made it into the latest release.

**Comment by vbaranov** [comment]
@valentinbud Please, could you try with the latest Blockscout 5.1.0 and let us kno, if this issue resolved on your side.

**Comment by vbaranov** [comment]
@valentinbud please update to [5.1.3](https://github.com/blockscout/blockscout/releases/tag/v5.1.3-beta). I am closing this issue - if it didn't resolve, please let us know in a new issue.
