### ISSUE TITLE
Emerald Mainnet: my balance is reduced but won't showing on tofunft as an offer

### ISSUE THREAD

**Issue by aidillesmana** [blockscout/blockscout#5117]
I've made an offer for 2 OasisPunk NFT, one is 110 bid of ROSE and other is 100 bid of ROSE.
Balance is reduced but won't reflected as offer on tofunft.
1. Id transaction of 110 bid of ROSE: 0xfb02e460000398a819024394339639d34e0afa0100d9f16c05af3aa52ad587bd
2. Id transaction of 100 bid of ROSE : 0xeda82b30b60a310fadeb04768bb9297f4cf7ce3fa407a678a497e719181c52fc

![Screenshot_20220120-060935_Kiwi Browser](https://user-images.githubusercontent.com/73056227/150233094-189b969b-4084-4200-a485-d64763d1d6ef.jpg)

![Screenshot_20220120-060950_Kiwi Browser](https://user-images.githubusercontent.com/73056227/150233103-a3a02981-4d18-4335-a3d3-dc8e19e06fd7.jpg)

### Environment
* Elixir Version: 1.12.3
* Erlang Version: 24
* BlockScout Version: 0.0.1

* User Agent: `Mozilla/5.0 (Linux; Android 11; SM-A505F) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.60 Mobile Safari/537.36`

### Steps to reproduce

*Tell us how to reproduce this issue. If possible, push up a branch to your fork with a regression test we can run to reproduce locally.*

### Expected Behaviour

*Tell us what should happen.*

### Actual Behaviour

*Tell us what happens instead.*

**Comment by vbaranov** [comment]
Emerald Mainnet is not supported here
