### ISSUE TITLE
Consider Regular ABI JSON Verification

### ISSUE THREAD

**Issue by Mentors4EDU** [blockscout/blockscout#5123]
This is a recommended improvement, but consider doing ABI verification for the regular JSON ABI output instead of ABI as a hex encoded format. It makes the verification process way easier as currently for Truffle deployed smart contracts it is extremely difficult to verify, even with the JSON file in it's entirety our flattened Solidity code.

**Comment by vbaranov** [comment]
@Mentors4EDU could you elaborate on what kind of verification do you mean? Blockscout currently provides these options:
- Verification through Standard Input JSON
- Verification through flattened source code
- Verification through metadata JSON
- Basic Vyper contracts verification

Here is the doc with supported options https://docs.blockscout.com/for-users/verifying-a-smart-contract#smart-contract-verification-with-blockscout

**Comment by Mentors4EDU** [comment]
I am having a problem getting hex-encoded format for the ABI. The hyperlink it gives for parsing the JSON and getting an encoded output, doesn't work. It not longer automatically generates the output. I tried uploading the JSON file that Truffle generated and it still had a problem getting the constructor ABIs automatically. This is a problem because the smart contract I wanted to verify is something I tried many different methods for during the past six month for. The flattened source code also didn't work. The same address on Ethereum for the same contract source code have had that code verified, but for some reason for Ethereum Classic's network (on Blockscout not Etherscan), verification is always a mess. Any help would be greatly appreciated.

**Comment by vbaranov** [comment]
@Mentors4EDU For debugging purposes, please provide the contract address, on which chain it has been deployed, verification metadata. If the chain is private, please deploy the contract to Sokol testnet (https://blockscout.com/poa/sokol).

**Comment by vbaranov** [comment]
I am closing this due to no response. Please re-open if the issue is still actual and please provide verification details.
