### ISSUE TITLE
Ethereum Classic: <Issue Title>

### ISSUE THREAD

**Issue by Alaa7619** [blockscout/blockscout#5125]
I have sent ethereum classc to my ethereum address. 
I need help about this issue .
0x7fa84D1dD2C5FfEC1e07d458423fF3Ec1eEA9651
 Balance
0.02317173 ETC ($0.560988 USD)
 Tokens
0 tokens
 Transactions
 Transfers
 Gas Used

**Comment by vbaranov** [comment]
You should ask in Ethereum Classic Discord https://discord.com/invite/bMGuZsA
