### ISSUE TITLE
Emerald Mainnet: <usdt failed in the transition

### ISSUE THREAD

**Issue by Guo888abc** [blockscout/blockscout#5128]
*Dear staff, 
I was using a bridge inside the Emerald wallet and bridged USDT to my Emerald wallet. However, I can't swap using Yuzuswap, because it is not recognized by my usdt coin. So I want to use my USDT coins and sent them to my Binance wallet. The transition showed success but the coins are missing from my Binance wallet. 

Could you kindly help me to check what happened????
Transition ID: 0x1424169d9b9870a6593eefb83eadd5523f4c4de87a8d6e1b1ddd8556486549c4*

### Environment
* Elixir Version: 1.12.3
* Erlang Version: 24
* BlockScout Version: 0.0.1

* User Agent: `Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/97.0.4692.71 Safari/537.36`

### Steps to reproduce

*Tell us how to reproduce this issue. If possible, push up a branch to your fork with a regression test we can run to reproduce locally.*

### Expected Behaviour

*Tell us what should happen.*

### Actual Behaviour

*Tell us what happens instead.*

**Comment by vbaranov** [comment]
There is no support of the Emerald network here
