### ISSUE TITLE
DATABASE_URL environment variable isn't honored when server starts (and a different username is used instead)

### ISSUE THREAD

**Issue by nicexe** [blockscout/blockscout#5130]
I have set a few environment variables like so:
```
NETWORK=xdailike
SUBNETWORK=xdailike testnet
LOGO=/images/some_logo.svg
LOGO_FOOTER=/images/some_logo.svg
ETHEREUM_JSONRPC_VARIANT=parity
ETHEREUM_JSONRPC_HTTP_URL=http://127.0.0.1:8545
ETHEREUM_JSONRPC_WS_URL=ws://127.0.0.1:9545
ETHEREUM_JSONRPC_TRACE_URL=http://127.0.0.1:8545
SECRET_KEY_BASE=secret
PORT=4000
COIN=XDL
DATABASE_URL=postgresql://blockscout:password@127.0.0.1:5432/blockscout
EMISSION_FORMAT=POA
LINK_TO_OTHER_EXPLORERS=FALSE
DISABLE_EXCHANGE_RATES=TRUE
APPS_MENU=TRUE
CHAIN_ID=4680
SOURCIFY_SERVER_URL=https://sourcify.dev/server
SOURCIFY_REPO_URL=https://repo.sourcify.dev/contracts/
VALIDATORS_CONTRACT=0x1000000000000000000000000000000000000001
REWARDS_CONTRACT=0x2000000000000000000000000000000000000001
POS_STAKING_CONTRACT=0x1100000000000000000000000000000000000001
DISABLE_WEBAPP=FALSE
CHAIN_SPEC_PATH=/home/nicexe/xdailike-testnet/spec.json
```
Step 9 in [Manual Deployment - BlockScout](https://docs.blockscout.com/for-developers/manual-deployment) works fine but step 13 gives this error:
![image](https://user-images.githubusercontent.com/867535/150995666-84ee4afb-07db-4c6a-b276-c6895d8725cf.png)

Even though `DATABASE_URL` environment variable is set to `postgresql://blockscout:password@127.0.0.1:5432/blockscout`, `nicexe` is used as a username for authenticating with the database.

### Environment

* Elixir & Erlang/OTP versions (`elixir -version`): Erlang/OTP 24 [erts-12.1.5] [source] [64-bit] [smp:3:3] [ds:3:3:10] [async-threads:1] [jit], Elixir 1.12.2 (compiled with Erlang/OTP 22)
* Operating System: Ubuntu 20.04
* Blockscout Version/branch: v4.1.1-beta

### Steps to reproduce

1. I have set up all requirements for blockscout.
2. I have set the following variables: `NETWORK`, ` SUBNETWORK`, ` LOGO`, ` LOGO_FOOTER`, ` ETHEREUM_JSONRPC_VARIANT`, ` ETHEREUM_JSONRPC_HTTP_URL`, ` ETHEREUM_JSONRPC_WS_URL`, ` ETHEREUM_JSONRPC_TRACE_URL`, ` SECRET_KEY_BASE`, ` PORT`, ` COIN`, ` DATABASE_URL`, ` EMISSION_FORMAT`, ` LINK_TO_OTHER_EXPLORERS`, ` DISABLE_EXCHANGE_RATES`, ` APPS_MENU`, ` CHAIN_ID`, ` SOURCIFY_SERVER_URL`, ` SOURCIFY_REPO_URL`, ` VALIDATORS_CONTRACT`, ` REWARDS_CONTRACT`, ` POS_STAKING_CONTRACT`, ` DISABLE_WEBAPP` and ` CHAIN_SPEC_PATH`
3. Install/compile dependencies and the app using `mix do deps.get, local.rebar --force, deps.compile, compile`
4. Dropping and migrating the database using `mix do ecto.drop, ecto.create, ecto.migrate`
5. Installed node.js dependencies using `cd apps/block_scout_web/assets; npm install && node_modules/webpack/bin/webpack.js --mode production; cd -` and `cd apps/explorer && npm install; cd -`
6. Built static assets using `mix phx.digest`
7. Generated a certificate using `cd apps/block_scout_web; mix phx.gen.cert blockscout blockscout.local; cd -`
8. Started the server using mix `phx.server`

### Expected behaviour

`DATABASE_URL` environment variable should be used to determine the database username.

### Actual behaviour

Database username falls back to the current user's username.

**Comment by sg552** [comment]
I suggest you hard code the `username/password` directly in that module ( Exploror.Chain.Events.Listener) 

I have struggled a couple of days on this manually install, however it seems you have to have the ability to debug yourself. Anything very small would cause this kind of error. 

you have to:
1. have the ability to inspect an variable, such as using `IO.put "==#{inspect some_var}`, or change ```
result = var
   |< func1
   |< func2
```
into 
```
temp1 = func1(var)  
IO.puts "=== temp1 : #{inspect temp1}"    # this kind of code will print more friendly and easier way to debug
temp2 = func2(temp1)  
```
2. have the ability to read the Elixir code.

**Comment by vbaranov** [comment]
@nicexe this has been fixed. One more thing to mention is that boolean env variables values should be in lower case.
