### ISSUE TITLE
Elastos Smart Contract MainNet: CSV Download not working

### ISSUE THREAD

**Issue by PapaRob0** [blockscout/blockscout#5134]
Exporting the transaction history in CSV format on "https://eth.elastos.io/" results in indefinite loading time. The button doesn't react to clicks. Tested on Brave, Chrome Edge, and Mozilla
### Environment
* Elixir Version: 1.12.2
* Erlang Version: 24
* BlockScout Version: 488dae932

* User Agent: `Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/97.0.4692.71 Safari/537.36 Edg/97.0.1072.62`

### Steps to reproduce

Browse to https://eth.elastos.io/ and input your public address. scroll down and under transaction tab press download CSV. On new page press Download. For me the purple button loads indefinately and doesn't return a download

### Expected Behaviour

An export of transaction history in CSV Format should download

### Actual Behaviour

Stuck on loading

**Comment by vbaranov** [comment]
Elastos is not supported here. If you can reproduce the issue on any of the instances from https://blockscout.com family, please, let us know.
