### ISSUE TITLE
Blockscout Error Reading Proxy Contract

### ISSUE THREAD

**Issue by nikolay-nikolaev** [blockscout/blockscout#5143]
We had deployed a proxy contract and linked in to implementation contract and verified both of the contracts. When we use the Proxy Contract Read feature, for a particular query, we are not able to see any visible reply from operation.
Investigation:
When looking at the log we observer the following error thrown immediately after the query call.
Error is thrown in the log when performing a read function of a proxy contract.

2022-01-27T05:24:12.028 [error] #PID<0.30969.0> running BlockScoutWeb.Endpoint (connection #PID<0.15640.0>, stream id 6) terminated
Server: ektascan.io:80 (http)
Request: GET /smart-contracts/.....
** (exit) an exception was raised:
    ** (MatchError) no match of right hand side value: nil
        (explorer 0.0.1) lib/explorer/smart_contract/reader.ex:440: Explorer.SmartContract.Reader.proccess_abi/2
        (explorer 0.0.1) lib/explorer/smart_contract/reader.ex:431: Explorer.SmartContract.Reader.query_function_inner/6
        (explorer 0.0.1) lib/explorer/smart_contract/reader.ex:393: Explorer.SmartContract.Reader.query_function_with_names/5
        (block_scout_web 0.0.1) lib/block_scout_web/controllers/smart_contract_controller.ex:113: BlockScoutWeb.SmartContractController.show/2
        (block_scout_web 0.0.1) lib/block_scout_web/controllers/smart_contract_controller.ex:1: BlockScoutWeb.SmartContractController.action/2
        (block_scout_web 0.0.1) lib/block_scout_web/controllers/smart_contract_controller.ex:1: BlockScoutWeb.SmartContractController.phoenix_controller_pipeline/2
        (phoenix 1.5.13) lib/phoenix/router.ex:352: Phoenix.Router.__call__/2
        (phoenix 1.5.13) lib/phoenix/router/route.ex:41: Phoenix.Router.Route.call/2

Parameters used for blockscout
BLOCKSCOUT_CONTAINER_PARAMS = -e 'MIX_ENV=prod' \
  -e 'DATABASE_URL=$(DB_URL)' \
  --network=host \
  -e 'NETWORK=EKTA Chain' \
  -e 'SUBNETWORK=EktaScan' \
  -e 'CHAIN_ID=1994' \
  -e 'COIN=EKTA' \
  -e 'SHOW_PRICE_CHART=true' \
  -e 'SHOW_TXS_CHART=true' \
  -e 'DISABLE_EXCHANGE_RATES=false' \
  -e 'BLOCKSCOUT_HOST=ektascan.io' \
  -e 'BLOCKSCOUT_PROTOCOL=https' \
  -e 'BLOCK_TRANSFORMER=clique' \
  -e 'LOGO=/images/Ekta-Logo-Inline-Color-01.png' \
  -e 'LOGO_FOOTER=/images/ekta_ligth_text.svg' \
  -e 'ETHEREUM_JSONRPC_VARIANT=besu' \
  -e 'ETHEREUM_JSONRPC_HTTP_URL=http://spark-besu-776712730.ap-northeast-2.elb.amazonaws.com:8545' \
  -e 'ETHEREUM_JSONRPC_WS_URL=ws://spark-besu-776712730.ap-northeast-2.elb.amazonaws.com:8546' \
  -e 'ETHEREUM_JSONRPC_TRACE_URL=http://spark-besu-776712730.ap-northeast-2.elb.amazonaws.com:8545'

### Environment

Project run from docker
Blockscout Version: 4.1.1-beta
Blockchain: Hyperledger Besu

### Steps to reproduce

https://ektascan.io/address/0xEdBa5EF527CF47Ff6E2b8722975D9cf2Ecf5817a/read-proxy
Under 8.hasRole if you enter values & query - it return Error 500 in console

### Expected behaviour

It should return true or false

### Actual behaviour

Error 500

**Comment by vbaranov** [comment]
@nikolay-nikolaev could you deploy the same contract to Sokol testnet https://blockscout.com/poa/sokol? It will help us with debugging. Test coins on Sokol can be received from the faucet https://faucet.poa.network/.

**Comment by nikolay-nikolaev** [comment]
@vbaranov 

We have deployed the contracts to Sokol testnet https://blockscout.com/poa/sokol as you requested. Below contract links.

Proxy
https://blockscout.com/poa/sokol/address/0xa40630348bB492afCD49312AA30ADfF1a34F5AeA/read-proxy
Implementation
https://blockscout.com/poa/sokol/address/0x569e7B559A3aF9B2350b8Db2aFd8977b8bD05172/contracts

**Comment by vbaranov** [comment]
@nikolay-nikolaev thanks, I reproduced and fixed the issue. Could you try to build the application from the branch from this PR https://github.com/blockscout/blockscout/pull/5155? It contains a fix for the issue, you experienced. Could you please confirm, that it resolves the issue?

**Comment by nikolay-nikolaev** [comment]
@vbaranov thank you very much! Tested this version. It works fine.
