### ISSUE TITLE
Emerald Mainnet: <Transaction decoding is not available for chainId 42262>

### ISSUE THREAD

**Issue by ivan5030184** [blockscout/blockscout#5144]
*Describe your issue here.*

### Environment
* Elixir Version: 1.12.3
* Erlang Version: 24
* BlockScout Version: 0.0.1

* User Agent: `Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/97.0.4692.99 Safari/537.36`

### Steps to reproduce

*Tell us how to reproduce this issue. If possible, push up a branch to your fork with a regression test we can run to reproduce locally.*

### Expected Behaviour

*Tell us what should happen.*

### Actual Behaviour

*Tell us what happens instead.*

**Comment by ivan5030184** [comment]
Transaction decoding is not available for chainId 42262

**Comment by ivan5030184** [comment]
0x83317b1c7226bc68398f7f3aefdbbb029a77f051449e9fa5d32489774e7ff9ab

**Comment by vbaranov** [comment]
Here is no support of Emerald network.
