### ISSUE TITLE
Emerald Mainnet: Download CSV not working in Emerald Oasis explorer

### ISSUE THREAD

**Issue by jdurany** [blockscout/blockscout#5145]
When trying to download the CSV from all my transactions in Emerald Oasis explorer (https://explorer.emerald.oasis.dev/csv-export), once I push the button nothing happens and I'm unable to download it, no matter the timeframe selected. 

### Environment
* Elixir Version: 1.12.3
* Erlang Version: 24
* BlockScout Version: 0.0.1

* User Agent: `Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/97.0.4692.99 Safari/537.36`

### Steps to reproduce

1. go to https://explorer.emerald.oasis.dev/ and enter a specific wallet address
2. go to export CVS
3. select any timeframe
4. push "Download"

### Expected Behaviour

I should be able to get a downloaded CVS containing all my transactions for the entered wallet

### Actual Behaviour

Nothing happens, I've been waiting several times and no download is activated.

**Comment by vbaranov** [comment]
Here is no support of Emerald network. Perhaps, CSV export is not properly configured on their end. If you can reproduce the same issue on https://blockscout.com, please re-open the issue.
