### ISSUE TITLE
Emerald Mainnet: <Issue Title>

### ISSUE THREAD

**Issue by Buenia** [blockscout/blockscout#5146]
*Describe your issue here.*

### Environment
* Elixir Version: 1.12.3
* Erlang Version: 24
* BlockScout Version: 0.0.1

* User Agent: `Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/97.0.4692.99 Safari/537.36`

### Steps to reproduce

I did the normal move to extract a profit from Liquidity Mining and it started to take longer than usual, right now I can't enter Liquidity Mining as it says "1 pending" and won't let me navigate.
### Expected Behaviour

extracting the profit from Liquidity Mining

### Actual Behaviour

I get stuck in the "1 pending" and when I want to go to withdraw again it does not let me. The transaction that says pending has an error: Error: (Awaiting internal transactions for reason)
and this is the link to the transaction: 

I am waiting for answers, thank you!

**Comment by Buenia** [comment]
i fixed it pressing clear transactions history, thx

**Comment by baidang201** [comment]
@Buenia 
> i fixed it pressing clear transactions history, thx
how do you  clear transactions history? do you delete the postgre data and resync again?
