### ISSUE TITLE
Ethereum Classic: <Issue Title>

### ISSUE THREAD

**Issue by Xxrath** [blockscout/blockscout#5148]
I sent to wrong account my etc. Please help me and give me back my money.

https://blockscout.com/etc/mainnet/tx/0xc1df42b7f73d15c6de14ad28c28e3397a3412da5fa4f860089089e25c2cbcced/internal-transactions

My e-mail adress is: ercanacikgoz.0001@gmail.com

**Comment by vbaranov** [comment]
Regarding your question try to reach out ETC team, for instance, on their Discord https://discord.com/invite/hQs894U.
