### ISSUE TITLE
Ethereum Classic: <Issue Title>

### ISSUE THREAD

**Issue by vfrangu** [blockscout/blockscout#5164]
i Sent my ETC to wrong address

### Environment
* Elixir Version: 1.12.2
* Erlang Version: 24
* BlockScout Version: v4.1.0-beta

* User Agent: `Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/97.0.4692.99 Safari/537.36`

### Steps to reproduce

*Tell us how to reproduce this issue. If possible, push up a branch to your fork with a regression test we can run to reproduce locally.*

### Expected Behaviour

*Tell us what should happen.*

### Actual Behaviour

*Tell us what happens instead.*

**Comment by vbaranov** [comment]
Regarding your question try to contact ETC team, for instance, on their Discord https://discord.com/invite/hQs894U.
