### ISSUE TITLE
Shiden (EVM): HTTP 504 error trying to shearch for addresses or toknes 

### ISSUE THREAD

**Issue by EMISWAP** [blockscout/blockscout#5181]
HTTP 504 error trying to shearch for addresses or toknes 
Steps:
1. Launch https://blockscout.com/shiden
2. Go to the search string 
![image](https://user-images.githubusercontent.com/68783544/153357676-bfc72c74-f056-4ddc-9b79-5113cb649fd9.png)
3. Try to find tokens by their names or address (any name or address)
4. Get the 504 Gateway Timeout error
### Environment
* Elixir Version: 1.12.3
* Erlang Version: 24
* BlockScout Version: v4.1.0-beta

* User Agent: `Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.110 Safari/537.36 OPR/82.0.4227.58`

**Comment by vbaranov** [comment]
Currently, works

<img width="580" alt="Screenshot 2022-02-10 at 11 04 07" src="https://user-images.githubusercontent.com/4341812/153363661-05cb4713-71fb-4342-925e-d04c2964d33e.png">
