### ISSUE TITLE
Emerald Mainnet: <ZAP: ROSE TO LP CUSD-YUZU LOSE MORE THAN 450 USD>

### ISSUE THREAD

**Issue by Buenia** [blockscout/blockscout#5185]
*Describe your issue here.*

### Environment
* Elixir Version: 1.12.3
* Erlang Version: 24
* BlockScout Version: 0.0.1

* User Agent: `Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.82 Safari/537.36`

### Steps to reproduce

i transferred rose to metamask emerlad mainnet, once i visualize them in yuzuswap i tap the "zap" button, select currency of oirgen rose and TO LP CUSD-YUZU

### Expected Behaviour

 I have a conversion error in the zap of yuzuswap, in the creation of the lp 460 usd were lost approximately, the LP that I chose was: USDC-YUZU, please help me! I converted 1780 ROSE to that LP and it gave me:110.77 yuzu and 42.33 USDC. Here is the link to the transaction:

https://explorer.emerald.oasis.dev/tx/0x8613b99c124ff71442e098bdcde640b1afbfaa8c5f5b8f3d59f3486d381bf703/token-transfers

### Actual Behaviour

i understand that i should have at least 200 usd in the LP created and it gave me only 42.33

*Tell us what happens instead.*

**Comment by vbaranov** [comment]
Here is no support of Emerald network.
