### ISSUE TITLE
Running mix do ecto.migrate reports an error execute "CREATE EXTENSION IF NOT EXISTS btree_gist"

### ISSUE THREAD

**Issue by ranyong321** [blockscout/blockscout#5186]
Running mix do ecto.migrate reports an error execute "CREATE EXTENSION IF NOT EXISTS btree_gist" ** (Postgrex.Error) ERROR 58P01 (undefined_file) could not open extension control file "/Applications/Postgres.app/Contents/Versions/14/share/ postgresql/extension/btree_gist.control": No such file or directory
can you help

**Comment by ranyong321** [comment]
Manual Deployment

**Comment by ranyong321** [comment]
`  == Running 20180522154252 Explorer.Repo.Migrations.CreateBtreeGistExtension.change/0 forward

17:39:18.550 [info]  execute "CREATE EXTENSION IF NOT EXISTS btree_gist"
** (Postgrex.Error) ERROR 58P01 (undefined_file) could not open extension control file "/Applications/Postgres.app/Contents/Versions/14/share/postgresql/extension/btree_gist.control": No such file or directory
    (ecto_sql 3.7.0) lib/ecto/adapters/sql.ex:756: Ecto.Adapters.SQL.raise_sql_call_error/1
    (elixir 1.13.3) lib/enum.ex:1593: Enum."-map/2-lists^map/1-0-"/2
    (ecto_sql 3.7.0) lib/ecto/adapters/sql.ex:844: Ecto.Adapters.SQL.execute_ddl/4
    (ecto_sql 3.7.0) lib/ecto/migration/runner.ex:343: Ecto.Migration.Runner.log_and_execute_ddl/3
    (ecto_sql 3.7.0) lib/ecto/migration/runner.ex:117: anonymous fn/6 in Ecto.Migration.Runner.flush/0
    (elixir 1.13.3) lib/enum.ex:2396: Enum."-reduce/3-lists^foldl/2-0-"/3
    (ecto_sql 3.7.0) lib/ecto/migration/runner.ex:116: Ecto.Migration.Runner.flush/0
    (ecto_sql 3.7.0) lib/ecto/migration/runner.ex:280: Ecto.Migration.Runner.perform_operation/3
    (stdlib 3.17) timer.erl:166: :timer.tc/1
    (ecto_sql 3.7.0) lib/ecto/migration/runner.ex:25: Ecto.Migration.Runner.run/8
    (ecto_sql 3.7.0) lib/ecto/migrator.ex:324: Ecto.Migrator.attempt/8
    (ecto_sql 3.7.0) lib/ecto/migrator.ex:251: anonymous fn/5 in Ecto.Migrator.do_up/5
    (ecto_sql 3.7.0) lib/ecto/migrator.ex:295: anonymous fn/6 in Ecto.Migrator.async_migrate_maybe_in_transaction/7
    (ecto_sql 3.7.0) lib/ecto/adapters/sql.ex:1013: anonymous fn/3 in Ecto.Adapters.SQL.checkout_or_transaction/4
    (db_connection 2.4.1) lib/db_connection.ex:1531: DBConnection.run_transaction/4
    (ecto_sql 3.7.0) lib/ecto/migrator.ex:313: Ecto.Migrator.run_maybe_in_transaction/4
    (elixir 1.13.3) lib/task/supervised.ex:89: Task.Supervised.invoke_mfa/2
    (elixir 1.13.3) lib/task/supervised.ex:34: Task.Supervised.reply/4
    (stdlib 3.17) proc_lib.erl:226: :proc_lib.init_p_do_apply/3`

**Comment by vbaranov** [comment]
@ranyong321 which version of Postgres do you use? https://docs.blockscout.com/for-developers/information-and-settings/requirements

**Comment by ranyong321** [comment]
ok thanks for your answer

**Comment by ranyong321** [comment]
ok thanks for your answer
