### ISSUE TITLE
Transaction Issue not Settling causing a deposit issue

### ISSUE THREAD

**Issue by thedinarian** [blockscout/blockscout#5187]
I am trying to deposit MOVR into my Kucoin account from metamask. The moonscan and my metamask say the tX went through, however Kucoin uses Blockscout to verify funds. TX is here https://blockscout.moonriver.moonbeam.network/tx/0xccd10ed596c335adc678b5471d768122762b4694ebb516b4977e767028b2cf31/internal-transactions 

The Moonscan tx is here:  https://moonriver.moonscan.io/address/0x1d9baffcc887de996949247d409fd8871b632c0a

I submitted a ticket to Kucoin, but they take weeks to reply back. Is there a way to fix this on your end?

**Comment by vbaranov** [comment]
Here is no support of Moonbeam instance. Try to ask in Moonriver Discord https://discord.com/invite/PfpUATX
