### ISSUE TITLE
Emerald Mainnet: <Issue Title>

### ISSUE THREAD

**Issue by perico3000** [blockscout/blockscout#5204]
<puse mal la billetera y lo mande al mismo contrato de ceusd como puedo recuperar mi transaccion
</html>Hash de transacción mi cartera es 0xEC061a3e9934205dF90f0e60063FDEe7554E471F
0xfa25e4bf39340bdf30c493fc899654cee2f2f9df9b8fb6b273ca81f7733f116c
 Resultado
 Éxito
 Estado
Confirmado Confirmado por 2.721
 Cuadra
[484831](https://explorer.emerald.oasis.dev/block/484831)
 marca de tiempo
 | Confirmado dentro de <= 6.263 segundos
 Desde
[0xec061a3e9934205df90f0e60063fdee7554e471f](https://explorer.emerald.oasis.dev/address/0xec061a3e9934205df90f0e60063fdee7554e471f)
 A
[0xdc19a122e268128b5ee20366299fc7b5b199c8e3](https://explorer.emerald.oasis.dev/address/0xdc19a122e268128b5ee20366299fc7b5b199c8e3)
 Fichas transferidas
Desde	[0xEC061a3e9934205dF90f0e60063FDEe7554E471F](https://explorer.emerald.oasis.dev/address/0xec061a3e9934205df90f0e60063fdee7554e471f)	
A	[0x09Ad7Df19ca70386DEbc62C37339D83131a7A9e8](https://explorer.emerald.oasis.dev/address/0x09ad7df19ca70386debc62c37339d83131a7a9e8)	
Para	500 [USDT](https://explorer.emerald.oasis.dev/token/0xdc19a122e268128b5ee20366299fc7b5b199c8e3)
 Valor
0 ROSA
 Tarifa de transacción
0.0081798 ROSA
 Precio de la gasolina
10 gwei
 tipo de transacción
0
 límite de gas
817,980
 Tarifa máxima por gas
10 gwei
 Tarifa Prioritaria Máxima por Gas
10 gwei
 Gas utilizado por transacción
817,980 | 100%
 Posición actual
190 0
 Datos crudos

hexadecimal (predeterminado)

**Comment by vbaranov** [comment]
There is no Emerald official support here. Please find their official channels.
