### ISSUE TITLE
UB: <withdraw no recieved>

### ISSUE THREAD

**Issue by Alpeshasal** [blockscout/blockscout#5207]
![Screenshot_2022-02-17-14-18-34-51_10b18a64ac40f109bc3f858b702404ea](https://user-images.githubusercontent.com/99871127/154440579-f3787df1-5922-4e41-bfb6-287ed23f7c5c.jpg)
*Describe your issue here.*
My withdraw is successful but another wallet not recieved yet

### Environment
* Elixir Version: 1.12.2
* Erlang Version: 24
* BlockScout Version: v4.0.0-beta

* User Agent: `Mozilla/5.0 (Linux; Android 11; RMX2151 Build/RP1A.200720.011; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/98.0.4758.101 Mobile Safari/537.36`

### Steps to reproduce

*Tell us how to reproduce this issue. If possible, push up a branch to your fork with a regression test we can run to reproduce locally.*

### Expected Behaviour

*Tell us what should happen.*

### Actual Behaviour

*Tell us what happens instead.*

**Comment by Alpeshasal** [comment]
Please help

**Comment by vbaranov** [comment]
Unrelated to Blockscout.
