### ISSUE TITLE
Emerald Mainnet: nft issue

### ISSUE THREAD

**Issue by 54yed** [blockscout/blockscout#5209]
I got the ai rose nft from oasis. I can see it on my metamirror nft marketplace when it is linked with my desktop metamask account (public key 
0x363Fd09Bd4c572e4D1135f79DF33a54216aCA1de)  I then filed instrictions to get it on my metamask mobile . Created the receipt network and followed instructions. I then added nft by entering 0x0f4c5A429166608f9225E094F7E66B0bF68a53B9 and then my nft id which is 2. It showed my nft on the mobile metamask. I got a new phone so I reinstalled metamask mobile and transferred account using seed phrase. Only few of the coins came u on ethereal main so I added the others. I then went on to proceed to add the custom rpc network (emerald mainnet) again like I did before.it made the account. Then clicked on add nft and put the contract address in again (0x0f4c5A429166608f9225E094F7E66B0bF68a53B9) and then my nft id number 2. This time it says oops, something happened and then "you are not the owner of this collectible, so you can't add it. However when my metamask i linked with nft marketplace it show  under my items. Can you please sort this out or advise further.
### Environment
* Elixir Version: 1.12.3
* Erlang Version: 24
* BlockScout Version: 0.0.1

* User Agent: `Mozilla/5.0 (Linux; Android 10; SM-G965F Build/QP1A.190711.020; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/98.0.4758.101 Mobile Safari/537.36`

### Steps to reproduce

*Tell us how to reproduce this issue. If possible, push up a branch to your fork with a regression test we can run to reproduce locally.*

### Expected Behaviour

*Tell us what should happen.*

### Actual Behaviour

*Tell us what happens instead.*

**Comment by vbaranov** [comment]
There is no Emerald network support here. Please find their official contacts.
