### ISSUE TITLE
Token ID Link was broken.

### ISSUE THREAD

**Issue by madxcannon** [blockscout/blockscout#5214]
*Describe your issue here.*
Token ID page is broken, showing 404 error. In token page there's only 1 token without ID.

My blockscout link:- 
https://testnet.antscan.net/token/0x8AA23F80d3eaE62f224e74A544c6e4a2441A3e8f/inventory

Token ID Link:-
https://testnet.antscan.net/token/0x8aa23f80d3eae62f224e74a544c6e4a2441a3e8f/instance/6632613466373930373066646435653132663432356535666464663435343139

### Environment

* Elixir & Erlang/OTP versions (`elixir -version`): Elixir 1.12.3 (compiled with Erlang/OTP 22)
* Operating System: CentOS Linux release 7.9.2009 (Core)
* Blockscout Version/branch: v4.1.0-beta

### Steps to reproduce

*Tell us how to reproduce this issue.  ❤️ if you can push up a branch to your fork with a regression test we can run to reproduce locally.*
Manually deployed on Centos 7.9, steps was followed on https://docs.blockscout.com/for-developers/manual-deployment

### Expected behaviour

*Tell us what should happen.*
Token ID link should shows up token info like example:-
https://docs.blockscout.com/for-projects/premium-features/erc-1155-support

### Actual behaviour
When click on token ID link it showing 404 not found. My token page has only 1 token & it was without ID.

*Tell us what happens instead.*

**Comment by vbaranov** [comment]
Please update Blockscout up to version https://github.com/blockscout/blockscout/releases/tag/v5.0.0-beta. It provides optimisation of indexing of token instances. I am closing this for now. Please let me know, if the issue still exists.
