### ISSUE TITLE
Emerald Mainnet: <Issue Title>Wrong deposit

### ISSUE THREAD

**Issue by Biobotu** [blockscout/blockscout#5217]
I made a transfer of USDT from Emerald Mainnet to Binance using an incorrect Network address. The transation was completed on Emerald, but the founds didn´t arrive on Binance. I can see the information about the transation on https://explorer.emerald.oasis.dev/ and I would like to know how can I have the founds back to Emerald Wallet.

**Comment by vbaranov** [comment]
There is no support of the Emerald network. Please find their official contacts.
