### ISSUE TITLE
Enquiry of adjusting the layout of UI design

### ISSUE THREAD

**Issue by getchainnode** [blockscout/blockscout#5221]
To whom may concern,

This is Emma from Get Chain PTE. LTD. We are a smart contracts platform in the blockchain industry, under the activity of any proof-of-stake protocol. 
I am writing to ask about the UI design of your open-source explorer, we would like to adjust the layout a little bit.
Please let me know if we need to get the official authorization from your side? 
If so, kindly let me know who should I contact. Thank you so much.

You may contact me with this email [emma.yuchiehtai@gmail.com](mailto:emma.yuchiehtai@gmail.com). I am looking forward to your reply.

Sincerely,
Emma

**Comment by ulyanas** [comment]
Emma, hi!
Please feel free to customize Blockscout’s UI. As long as you mention Blockscout on the explorer website and in the repo, it’s okay.

Ulyana Skladchikova
Head of product, Blockscout
