### ISSUE TITLE
Ethereum Classic: <Issue Title>

### ISSUE THREAD

**Issue by Hilaryking707** [blockscout/blockscout#5222]
I accidentally sent Etc crypto to my ETH address and I would like it to be refunded and sent to the correct crypto address 
Transaction hash is is 0x548a6dcfaa72a5f40c7e8fa902c4628ff994cfc4c4cc02a15b01573b42cc3807

### Environment
* Elixir Version: 1.12.2
* Erlang Version: 24
* BlockScout Version: v4.1.1-beta

* User Agent: `Mozilla/5.0 (iPhone; CPU iPhone OS 15_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) CriOS/98.0.4758.97 Mobile/15E148 Safari/604.1`

### Steps to reproduce

*Tell us how to reproduce this issue. If possible, push up a branch to your fork with a regression test we can run to reproduce locally.*

### Expected Behaviour

*Tell us what should happen.*

### Actual Behaviour

*Tell us what happens instead.*

**Comment by vbaranov** [comment]
Regarding your question try to contact ETC team, for instance, on their Discord https://discord.com/invite/hQs894U.
