### ISSUE TITLE
Energy Web Chain: EWT sent to EWTB on Trust Wallet

### ISSUE THREAD

**Issue by Kirky51** [blockscout/blockscout#5231]
Hi, I accidentally sent EWT from Kraken to EWTB on Trust wallet. I can see the transaction on the EWT explorer, but it didn't arrive in my trust wallet because it wasn't a bridged version. 
Can you please help me to recover my coins.
Thanks

Anthony

![EWT Trx 22-02-19 155022](https://user-images.githubusercontent.com/100308267/155573620-37ebcc8e-0c1c-4a8f-bc96-935c846603f1.png)
![EWT Trx on EWT explorer 2022-02-23 174015](https://user-images.githubusercontent.com/100308267/155573705-bcf6d1c9-9017-48e7-8b66-5a55a6b81c72.png)
![EWT Trx on EWT explorer2- 2022-02-23 174015](https://user-images.githubusercontent.com/100308267/155573720-838a67b5-f6a2-45fc-8383-d2c522aaed8f.png)

### Environment
* Elixir Version: 1.12.2
* Erlang Version: 24
* BlockScout Version: v4.0.0-beta

* User Agent: `Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.102 Safari/537.36`

### Steps to reproduce

*Tell us how to reproduce this issue. If possible, push up a branch to your fork with a regression test we can run to reproduce locally.*

### Expected Behaviour

*Tell us what should happen.*

### Actual Behaviour

*Tell us what happens instead.*

**Comment by vbaranov** [comment]
Hi, there is no support of EnergyWebChain. Please ask in their fork https://github.com/energywebfoundation/blockscout
