### ISSUE TITLE
Explorer Galaxias .csv file download not working

### ISSUE THREAD

**Issue by wcoombe** [blockscout/blockscout#5235]
*Reported to Telegram Kardiachain Tech Support over a month ago, Galaxias gives a option to download .csv file to export transactions, you can enter date range but the download button does not do anything when you click on it*

### Environment

* Elixir & Erlang/OTP versions (`elixir -version`):
* Operating System: MacOS
* Blockscout Version/branch: 

### Steps to reproduce

*Tell us how to reproduce this issue.  ❤️ if you can push up a branch to your fork with a regression test we can run to reproduce locally.* Go to a holder of one of the tokens, at bottom left of transactions page, click on download .csv, enter date range and click download button.

### Expected behaviour - Click download button, it should download .csv file to your computer.

*Tell us what should happen.* Click download button, it should download .csv file to your computer.

### Actual behaviour - it does not do anything when clicking on download button

*Tell us what happens instead.* nothing happens

**Comment by vbaranov** [comment]
There is no Kardiachain support here. They should configure `RE_CAPTCHA_SECRET_KEY`, `RE_CAPTCHA_CLIENT_KEY` keys (https://docs.blockscout.com/for-developers/information-and-settings/env-variables) in order to make CSV export work.
