### ISSUE TITLE
Emerald Mainnet: ai rose nft is not showing

### ISSUE THREAD

**Issue by stanelopecrypto** [blockscout/blockscout#5238]
*Describe your issue here.*

### Environment
* Elixir Version: 1.12.3
* Erlang Version: 24
* BlockScout Version: 0.0.1

* User Agent: `Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.102 Safari/537.36`

### Steps to reproduce

*Tell us how to reproduce this issue. If possible, push up a branch to your fork with a regression test we can run to reproduce locally.*

### Expected Behaviour

*Tell us what should happen.*

### Actual Behaviour

*Tell us what happens instead.*
i have nft token ai rose but it is not showing it on their website https://auth3.network/metamirror/gallery/airose/
this is my public address : 0x016b5CcD5f996d7769747d97CE026Ec126A3A197

![image](https://user-images.githubusercontent.com/81058496/155838017-45b0882a-8653-40f8-b234-21aaa42fdf71.png)

**Comment by vbaranov** [comment]
There is no official support of Emerald network here.
