### ISSUE TITLE
Testnet: <Issue Title>

### ISSUE THREAD

**Issue by Magicien5** [blockscout/blockscout#5242]
*Describe your issue here.*
Tokens transfered 2 days ago, not yet received.
This is ton hash 👍 
0x79748501744574eaebdd3294e2827e967612f8b2020cb69ea948be7b938d9d68
Said ton succès, but didn't receive tokens
Transfer from metamask to trustwallet of feg token.
Thanks.

**Comment by vbaranov** [comment]
You should ask Trustwallet support.
