### ISSUE TITLE
Kardiachain explorer Galaxias .csv file issues

### ISSUE THREAD

**Issue by wcoombe** [blockscout/blockscout#5246]
*Describe your issue here.* Kardiachain Expolrer Galaxias .csv file download is unusable.

### Environment

* Elixir & Erlang/OTP versions (`elixir -version`):
* Operating System: MacOS
* Blockscout Version/branch: 

### Steps to reproduce

*Tell us how to reproduce this issue.  ❤️ if you can push up a branch to your fork with a regression test we can run to reproduce locally.* In explorer galaxias, pick a address, download .csv file and look at data, all fees and number are in quadrillions, also no token symbols.

### Expected behaviour

*Tell us what should happen.* File has numbers with no decimal points

### Actual behaviour
Need to look at files, they are not usable for tax reporting purposes.
*Tell us what happens instead.*

**Comment by vbaranov** [comment]
Kardiachain explorer is not supported here
