### ISSUE TITLE
Shiden (EVM): the search string doesn't work

### ISSUE THREAD

**Issue by EMISWAP** [blockscout/blockscout#5250]
*Describe your issue here.*

### Environment
* Elixir Version: 1.12.3
* Erlang Version: 24
* BlockScout Version: v4.1.1-beta

* User Agent: `Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.102 Safari/537.36 OPR/84.0.4316.21`

### Steps to reproduce

1) Launch https://blockscout.com/shiden/
2) Enter an address into the search string f.eg 0x831b25EB4073d92E4766411f0DbDd0b549753179
3) Strart searching
4) Get an internal server error 
![image](https://user-images.githubusercontent.com/68783544/156711705-0b3e4dae-f49f-4f82-8ed7-e703de30d1a7.png)

### Expected Behaviour

The contract tx are loaded

### Actual Behaviour

 internal server error

**Comment by vbaranov** [comment]
@EMISWAP it was a temorary issue with the archive node reachability. Currently, address page opens.

<img width="819" alt="Screenshot 2022-03-05 at 10 45 52" src="https://user-images.githubusercontent.com/4341812/156873928-6983b96a-aab0-42c2-9cf0-f1bed7089967.png">
