### ISSUE TITLE
Sample code for API

### ISSUE THREAD

**Issue by dsolstad** [blockscout/blockscout#5251]
Is there any sample code on how to use the API to extract tokens and amounts of a swap from a gettxinfo call?

**Comment by vbaranov** [comment]
Probably, tokentx API endpoint is more suitable for token related stuff. Is not it what you're looking for

<img width="1253" alt="Screenshot 2022-03-04 at 11 44 29" src="https://user-images.githubusercontent.com/4341812/156729655-f7774658-7378-4d60-81e5-7498642b151c.png">
?

**Comment by vbaranov** [comment]
@dsolstad

**Comment by dsolstad** [comment]
Thanks!

**Comment by vbaranov** [comment]
I am closing this for now.
