### ISSUE TITLE
Check transaction ID

### ISSUE THREAD

**Issue by devor10** [blockscout/blockscout#5256]
Hello.

I have a Transaction ID in error and I would like to know what happens. can you help me?

The ID is: [0xce7778db11037c74999cbf2030cb5193d34f43da5ef4e3a21b800cbdaab69026](https://explorer.syscoin.org/tx/0xce7778db11037c74999cbf2030cb5193d34f43da5ef4e3a21b800cbdaab69026/internal-transactions)

Thank you very much!

**Comment by vbaranov** [comment]
There is no support of Syscoin here. Please find their official support contacts.
