### ISSUE TITLE
hl

### ISSUE THREAD

**Issue by tano1986** [blockscout/blockscout#5257]
*Describe your issue here.*

### Environment

* Elixir & Erlang/OTP versions (`elixir -version`):
* Operating System:
* Blockscout Version/branch: 

### Steps to reproduce

*Tell us how to reproduce this issue.  ❤️ if you can push up a branch to your fork with a regression test we can run to reproduce locally.*

### Expected behaviour

*Tell us what should happen.*

### Actual behaviour

*Tell us what happens instead.*

**Comment by tano1986** [comment]
hello, can someone help me? it wont left me dowload the csv from the nergy web explorer. i know i hung up.  thenk you very much.

**Comment by vbaranov** [comment]
Here is no support of Energy web chain explorer.
