### ISSUE TITLE
Ethereum: CSV export function on the frontend is broken

### ISSUE THREAD

**Issue by fyang1024** [blockscout/blockscout#5258]
*Describe your issue here.*

### Environment
* Elixir Version: 1.12.3
* Erlang Version: 24
* BlockScout Version: v4.1.2-beta

* User Agent: `Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/99.0.4844.51 Safari/537.36`

### Steps to reproduce

*Navigate to https://blockscout.com/eth/mainnet/csv-export?address=0x6cc8dCbCA746a6E4Fdefb98E1d0DF903b107fd21&type=transactions and click Download button*

### Expected Behaviour

*The CSV file should be downloaded*

### Actual Behaviour

*A spinner beside the Download text in the button keeps spinning, but no file is downloaded, and the the browser console shows the following error:*
```
recaptcha__en.js:397 Uncaught Error: No reCAPTCHA clients exist.
    at Array.<anonymous> (recaptcha__en.js:397:213)
    at recaptcha__en.js:246:92
    at HTMLButtonElement.<anonymous> (datepicker-e8328e3db40c94a5ce85e79a2a8b0c71.js?vsn=d:2:199849)
    at HTMLButtonElement.dispatch (datepicker-e8328e3db40c94a5ce85e79a2a8b0c71.js?vsn=d:2:66481)
    at HTMLButtonElement.y.handle (datepicker-e8328e3db40c94a5ce85e79a2a8b0c71.js?vsn=d:2:64476)
    at HTMLButtonElement.c (rocket-loader.min.js:1:9405)
(anonymous) @ recaptcha__en.js:397
(anonymous) @ recaptcha__en.js:246
(anonymous) @ datepicker-e8328e3db40c94a5ce85e79a2a8b0c71.js?vsn=d:2
dispatch @ datepicker-e8328e3db40c94a5ce85e79a2a8b0c71.js?vsn=d:2
y.handle @ datepicker-e8328e3db40c94a5ce85e79a2a8b0c71.js?vsn=d:2
c @ VM596 rocket-loader.min.js:1
```

**Comment by vbaranov** [comment]
@fyang1024 thank you for bringing this up. The issue resolved. It is also recommended to shrink the period od export down to a week. Otherwise, it can hit export timeout.
