### ISSUE TITLE
Hardhut plugin = Standard JSON input smart-contract-verification doesn't work for tornado nova

### ISSUE THREAD

**Issue by vbaranov** [blockscout/blockscout#5261]
![photo_2022-03-05 19 13 34](https://user-images.githubusercontent.com/4341812/156891391-962b8158-7e6c-44b3-bd53-47ff155e0865.jpeg)

https://github.com/tornadocash/tornado-nova/tree/l1-fee-from-user

**Comment by nikitosing** [comment]
problem was [fixed](https://blockscout.com/xdai/mainnet/address/0x0CDD3705aF7979fBe80A64288Ebf8A9Fe1151cE1/contracts) by #5198
