### ISSUE TITLE
Explorer.Chain.Events.Listener

### ISSUE THREAD

**Issue by FangYu199** [blockscout/blockscout#5267]
### Here are my environment variables
```
COIN=NAME \
ETHEREUM_JSONRPC_VARIANT=geth \
ETHEREUM_JSONRPC_HTTP_URL=http://xx.xx.xx.xx:8545 \
ETHEREUM_JSONRPC_WS_URL=ws://xx.xx.xx.xx:8546 \
DATABASE_URL=postgresql://postgres:'kamisama123'@xx.xx.xx.xx:5432/blockscout?ssl=false \
MIX_ENV=prod \
LINK_TO_OTHER_EXPLORERS=FALSE \
DISABLE_EXCHANGE_RATES=true \
NETWORK=Ethereum \
BLOCK_TRANSFORMER=clique \
CHAIN_ID=100 \
make start
```

### this is my error message
<img width="1021" alt="image" src="https://user-images.githubusercontent.com/29371052/156925419-44fe75f8-617d-4186-8611-8c228c57485a.png">

### After adding ECTO_USE_SSL POOL_SIZE
```
SECRET_KEY_BASE=Tu3jtoJ/jNvyuoVINdXYsWUJnR5Y6XRYRjbOsXsoqSzdWD2P+F8T8e5jkKh5v2I7 \
ECTO_USE_SSL=false \
POOL_SIZE=2 \
```

### new error

<img width="876" alt="image" src="https://user-images.githubusercontent.com/29371052/156926572-5a903bf0-3a45-4a9a-ad10-e6b72c9569ef.png">

**Comment by vbaranov** [comment]
Could you try https://github.com/blockscout/blockscout/issues/5233#issuecomment-1054113627?

**Comment by FangYu199** [comment]
ok thanks now dealing with this error
I'll take a look at why it doesn't start crawling node data now

**Comment by vbaranov** [comment]
> I'll take a look at why it doesn't start crawling node data now

"Known tokens" fetcher is trying to get exchange rates form CoinGecko. Thus, if your server is closed to the internet, you should disable known tokens fetcher. I am closing this for now. Please le me know if you have furthre requests.
