### ISSUE TITLE
Can blockscout be used on the internal network?

### ISSUE THREAD

**Issue by niceharu** [blockscout/blockscout#5271]
The following error occurs when running on an internal network without internet. 
It works fine on the internet. So I'm thinking the internet is the cause or not.
Is there any way to run it on the internal network?

2022-03-04T08:40:52.042 application=que [info] [Que] Booting Que
2022-03-04T08:40:52.073 application=que [info] [Que] Booting Server Supervisor for Workers
2022-03-04T08:40:52.285 [info] Application explorer exited: Explorer.Application.start(:normal, []) returned an error: shutdown: failed to start child: Explorer.Chain.Events.Listener
    ** (EXIT) an exception was raised:
        ** (MatchError) no match of right hand side value: {:error, {%KeyError{key: :username, message: nil, term: [types: nil, types: Postgrex.DefaultTypes, sync_connect: true, hostname: "postgres", database: "blockscout?ssl=false", migration_timestamps: [type: :utc_datetime_usec], url: "postgresql://postgres:@postgres:5432/blockscout?ssl=false", pool_size: 40, ssl: false, prepare: :unnamed, timeout: 60000]}, [{Keyword, :fetch!, 2, [file: 'lib/keyword.ex', line: 399]}, {Postgrex.Protocol, :startup, 2, [file: 'lib/postgrex/protocol.ex', line: 675]}, {Postgrex.Protocol, :handshake, 2, [file: 'lib/postgrex/protocol.ex', line: 579]}, {Postgrex.Notifications, :connect, 2, [file: 'lib/postgrex/notifications.ex', line: 225]}, {Postgrex.Notifications, :init, 1, [file: 'lib/postgrex/notifications.ex', line: 207]}, {Connection, :init_it, 6, [file: 'lib/connection.ex', line: 424]}, {:proc_lib, :init_p_do_apply, 3, [file: 'proc_lib.erl', line: 249]}]}}
            (explorer 0.0.1) lib/explorer/chain/events/listener.ex:22: Explorer.Chain.Events.Listener.init/1
            (stdlib 3.12.1) gen_server.erl:374: :gen_server.init_it/2
            (stdlib 3.12.1) gen_server.erl:342: :gen_server.init_it/6
            (stdlib 3.12.1) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
** (Mix) Could not start application explorer: Explorer.Application.start(:normal, []) returned an error: shutdown: failed to start child: Explorer.Chain.Events.Listener
    ** (EXIT) an exception was raised:
        ** (MatchError) no match of right hand side value: {:error, {%KeyError{key: :username, message: nil, term: [types: nil, types: Postgrex.DefaultTypes, sync_connect: true, hostname: "postgres", database: "blockscout?ssl=false", migration_timestamps: [type: :utc_datetime_usec], url: "postgresql://postgres:@postgres:5432/blockscout?ssl=false", pool_size: 40, ssl: false, prepare: :unnamed, timeout: 60000]}, [{Keyword, :fetch!, 2, [file: 'lib/keyword.ex', line: 399]}, {Postgrex.Protocol, :startup, 2, [file: 'lib/postgrex/protocol.ex', line: 675]}, {Postgrex.Protocol, :handshake, 2, [file: 'lib/postgrex/protocol.ex', line: 579]}, {Postgrex.Notifications, :connect, 2, [file: 'lib/postgrex/notifications.ex', line: 225]}, {Postgrex.Notifications, :init, 1, [file: 'lib/postgrex/notifications.ex', line: 207]}, {Connection, :init_it, 6, [file: 'lib/connection.ex', line: 424]}, {:proc_lib, :init_p_do_apply, 3, [file: 'proc_lib.erl', line: 249]}]}}
            (explorer 0.0.1) lib/explorer/chain/events/listener.ex:22: Explorer.Chain.Events.Listener.init/1
            (stdlib 3.12.1) gen_server.erl:374: :gen_server.init_it/2
            (stdlib 3.12.1) gen_server.erl:342: :gen_server.init_it/6
            (stdlib 3.12.1) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
Unchecked dependencies for environment prod:
* bcrypt_elixir (Hex package)
  the dependency is not available, run "mix deps.get"
* number (Hex package)
  the dependency is not available, run "mix deps.get"
* prometheus_plugs (Hex package)
  the dependency is not available, run "mix deps.get"
* cldr_utils (Hex package)
  the dependency is not available, run "mix deps.get"
* logger_file_backend (Hex package)
  the dependency is not available, run "mix deps.get"
* websocket_client (Hex package)
  the dependency is not available, run "mix deps.get"
* con_cache (Hex package)
  the dependency is not available, run "mix deps.get"

### Environment

* Elixir & Erlang/OTP versions (elixir -version): Elixir 1.12.3 (compiled with Erlang/OTP 24)
* Operating System: Linux
* Blockscout Version/branch: blockscout/blockscout:latest (docker-compose)
* geth version: 1.10.16-unstable
* consensus: PoA
* geth option in use
--networkid=2731
--port=30303
--maxpeers=10
--allow-insecure-unlock
--nodiscover
--http
--http.addr="0.0.0.0"
--http.port=8545
--http.corsdomain="*"
--http.api="admin, debug, web3, eth, txpool, personal, ethash, miner, net"
--gcmode="archive"
--syncmode="full"

**Comment by vbaranov** [comment]
Yes, it can work without internet connection if the node running is on the same server. But al least internet connection should be opened at the time of compiling the application in order to get packages from the hex and npm repositories or you should copy all Blockscout folders from the server, which is compiled and connected to the internet, and paste them to closed server.

**Comment by niceharu** [comment]
When I run it through the docker image, it works fine. Thanks.
