### ISSUE TITLE
Use cloud db as DATABASE_URL

### ISSUE THREAD

**Issue by icommit** [blockscout/blockscout#5274]
*Describe your issue here.*
I have a Postgresql instance running on Aiven. There's an API endpoint to communicate with this db. I'm having issues assigning the host url for this db instance to DATABASE_URL env variable.

### Environment

* Elixir & Erlang/OTP versions (`elixir -version`): 1.13.3
* Operating System: mac os
* Blockscout Version/branch: master

### Actual behaviour

*Error dump:
`(Mix) Could not start application explorer: Explorer.Application.start(:normal, []) returned an error: shutdown: failed to start child: Explorer.Chain.Events.Listener
    ** (EXIT) an exception was raised:
        ** (MatchError) no match of right hand side value: {:error, %Postgrex.Error{connection_id: nil, message: nil, postgres: %{code: :invalid_authorization_specification, file: "auth.c", line: "496", message: "no pg_hba.conf entry for host \"XX.XX.XX.XX\", user \"admin\", database \"mydb\", SSL off", pg_code: "28000", routine: "ClientAuthentication", severity: "FATAL", unknown: "FATAL"}, query: nil}}
`

**Comment by vbaranov** [comment]
Can you connect to that DB endpoint via Psql?

**Comment by icommit** [comment]
> Can you connect to that DB endpoint via Psql?

There's a service uri in the following format: postgres://<user>:<password>@<host>:<port>/<database>?<options> that client endpoints (go, python) can use to communicate with.
Notice the difference. Locally the format begins like postgresql://

**Comment by vbaranov** [comment]
I suppose this is not the isuue with Blockscout. Most likely the issue is with pg_hba.conf of the DB. Try to connect to the DB not locally. Check this for more info https://elixirforum.com/t/ecto-config-error-with-pg-hba-conf-with-no-local-postgres-running/40264/12
