### ISSUE TITLE
Help trying to get blockscout to work with BESU

### ISSUE THREAD

**Issue by onigiri-x** [blockscout/blockscout#5276]
Having issues connecting to remote private hyperledger Besu chain

blockscout    |     (stdlib 3.15.2) proc_lib.erl:226: :proc_lib.init_p_do_apply/3
blockscout    | Last message: {#Reference<0.2002511538.2675703813.192965>, {:error, :econnrefused}}
blockscout    | State: %Indexer.Block.Catchup.BoundIntervalSupervisor{bound_interval: %Indexer.BoundInterval{current: 2500, maximum: 25000, minimum: 2500}, fetcher: %Indexer.Block.Catchup.Fetcher{block_fetcher: %Indexer.Block.Fetcher{broadcast: :catchup, callback_module: Indexer.Block.Catchup.Fetcher, json_rpc_named_arguments: [transport: EthereumJSONRPC.HTTP, transport_options: [http: EthereumJSONRPC.HTTP.HTTPoison, url: "http://54.139.9.101:8545", http_options: [recv_timeout: 600000, timeout: 600000, hackney: [pool: :ethereum_jsonrpc]]], variant: EthereumJSONRPC.Geth], receipts_batch_size: 250, receipts_concurrency: 10}, blocks_batch_size: 10, blocks_concurrency: 10, memory_monitor: Indexer.Memory.Monitor}, memory_monitor: nil, task: %Task{owner: #PID<0.1803.0>, pid: #PID<0.1815.0>, ref: #Reference<0.2002511538.2675703813.192968>}}

### Environment
Trying to get this working on Windows 10, in Docker desktop / docker-compose 

### Steps to reproduce

Go to blockscout repo and clone it
https://github.com/blockscout/blockscout

In terminal, navigate to docker-compose folder, hopefully that is right
Modify the docker-compose\envs\common-blockscout.env file with

ETHEREUM_JSONRPC_VARIANT=besu
ETHEREUM_JSONRPC_HTTP_URL=http://54.139.9.101:8545/
ETHEREUM_JSONRPC_TRACE_URL=http://54.139.9.101:8545/
SUBNETWORK=My Chain

I have docker desktop installed, open it
call this: docker-compose up --build

### Expected behaviour

That it syncs up some blocks and I can see things on the blockexplorer

### Actual behaviour

localhost:4000 does serve up but I basically see nothing, 0 blocks, etc.

Please let me know if there is another approach, or some other settings I should enable for besu, or if this is a besu issue not a blockscout issue. 

Thanks

**Comment by vbaranov** [comment]
Is archive node at http://54.139.9.101:8545/ reachable from the Blocksout application server?

**Comment by vbaranov** [comment]
Closing due to no answer.
