### ISSUE TITLE
Palm: DAI transfer to MetaMask

### ISSUE THREAD

**Issue by LitLinny** [blockscout/blockscout#5283]
Transaction Hash: 0xe050eea3916e01f36ff4feb14de4cd5e502258cf5fc3993432e63dd031eb16e2

### Environment
* Elixir Version: 1.12.2
* Erlang Version: 24
* BlockScout Version: 

* User Agent: `Mozilla/5.0 (iPhone; CPU iPhone OS 15_3_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/15.3 Mobile/15E148 Safari/604.1`

### Actual Behaviour

Transaction shows as a success, but I have yet to receive the funds in my MetaMask wallet. I look back at the address I transferred from and the
amount transferred has been deducted.

**Comment by vbaranov** [comment]
There is no Palm support here.
