### ISSUE TITLE
make start error

### ISSUE THREAD

**Issue by jianxiangxun** [blockscout/blockscout#5284]
*Describe your issue here.*

make start
==> Checking for blockscout image blockscout/blockscout
==> Image exist. Using blockscout/blockscout
==> Checking PostrgeSQL container
==> Starting PostgreSQL container
Error response from daemon: No such container: db
Error: failed to start containers: db
make: *** [postgres] Error 1

### Environment

* Elixir & Erlang/OTP versions (`elixir -version`):
* Operating System: mac
* Blockscout Version/branch:  master

### Steps to reproduce

*Tell us how to reproduce this issue.  ❤️ if you can push up a branch to your fork with a regression test we can run to reproduce locally.*

### Expected behaviour

*Tell us what should happen.*

### Actual behaviour

*Tell us what happens instead.*

**Comment by vbaranov** [comment]
@jianxiangxun what is the response of `docker ps -a --filter name=db | grep db`?

**Comment by jianxiangxun** [comment]
> @jianxiangxun what is the response of `docker ps -a --filter name=db | grep db`?

saw the readme.md under /docker-compose
run docker-compose up --build
then can be start success

first follow the doc [Docker Integration (Local Use Only)](https://docs.blockscout.com/for-developers/information-and-settings/docker-integration-local-use-only) and run make start directly, encountered error
