### ISSUE TITLE
Proxys validation : Fetch implementation and admin.

### ISSUE THREAD

**Issue by rlajous** [blockscout/blockscout#5292]
We have validated the POAP proxy contract but it says that the implementation is pointing to the `0x00` address.

### Environment

* Elixir & Erlang/OTP versions (`elixir -version`):
* Operating System:
* Blockscout Version/branch: 

### Steps to reproduce

The verified [Proxy Contract](https://www.blockscout.com/xdai/mainnet/address/0x22C1f6050E56d2876009903609a2cC3fEf83B415/transactions).
- Currently we have a custom EIP-1967 with the `ifAdmin` modifier you can’t access directly the contract.
- EVM reverts call of the implementation() method.
- It reverts because the openzepellin `AdminUpgradeabilityProxy` has an `ifAdmin` modifier in `implementation()` and `admin()` functions. 

According to openzepellin clients should read it directly from the storage lot:
In our case that would be `0x7050c9e0f4ca769c69bd3a8ef740bc37934f8e2c036e5a723fd8ee048ed3f8c3` for the implementation and `0x10d6a54a4754c8869d6886b5f5d7fbfa5b4522237ea5c60d11bc4e7a1ff9390b` for the admin

Our current implementation can be found [here](https://github.com/OpenZeppelin/openzeppelin-sdk/tree/release/2.2/packages/lib/contracts/upgradeability), they where compiled with 2.2.3 de zos lib.

### Expected behaviour

- The expected implementation should point to `0xA178b166bea52449d56895231Bb1194f20c2f102`
- The expected admin should be `0xDD3C426fA842F890BCb793DA6ccD749Edb09c44B`

### Actual behaviour

- The implementation is pointing to `0x00`
- The expected admin should be `0x00`

**Comment by vbaranov** [comment]
@rlajous OZ proxy pattern has been deployed to Gnosis Chain Blockscout instance. POAP token implementation is visible again.
