### ISSUE TITLE
UB: <Issue Title>Website error cant access ubchain.site

### ISSUE THREAD

**Issue by Kendzie** [blockscout/blockscout#5309]
Plese your website is down, cant access ubchain.site

And cant open fitur xswap on cola walet because your website is down

Thankyou

### Environment
* Elixir Version: 1.12.2
* Erlang Version: 24
* BlockScout Version: v4.0.0-beta

* User Agent: `Mozilla/5.0 (Linux; Android 9; ASUS_X00TD) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/97.0.4692.98 Mobile Safari/537.36`

### Steps to reproduce

*Tell us how to reproduce this issue. If possible, push up a branch to your fork with a regression test we can run to reproduce locally.*

### Expected Behaviour

*Tell us what should happen.*

### Actual Behaviour

*Tell us what happens instead.*

**Comment by vbaranov** [comment]
Blockscout team doesn't manage this isntance of explorer. Please find official contacts of the team.
