### ISSUE TITLE
Can't Write Contract with Array of Struct Parameter

### ISSUE THREAD

**Issue by fahadh4ilyas** [blockscout/blockscout#5316]
### Environment

* Elixir & Erlang/OTP versions (`elixir -version`): Elixir 1.12.3 (compiled with Erlang/OTP 24)
* Operating System: Alpine Linux v3.14
* Blockscout Version/branch: from master with this e9723772956edf851787112cc0174aeb4c7e83a4 as last commit

### Steps to reproduce

I'm just running inside `docker-compose` directory running `docker-compose up --build`

### Expected behaviour

Writing contract with array of struct is successfully done.

### Actual behaviour

```js
smart-contract-helpers-42daf0db0b108331beed11ccdf2f5ea0.js?vsn=d:2
Uncaught (in promise) TypeError: e.replace is not a function
    at j (smart-contract-helpers-42daf0db0b108331beed11ccdf2f5ea0.js?vsn=d:2:3685035)
    at smart-contract-helpers-42daf0db0b108331beed11ccdf2f5ea0.js?vsn=d:2:3682394
    at Array.map (<anonymous>)
    at b (smart-contract-helpers-42daf0db0b108331beed11ccdf2f5ea0.js?vsn=d:2:3682367)
    at smart-contract-helpers-42daf0db0b108331beed11ccdf2f5ea0.js?vsn=d:2:3682227
    at Array.map (<anonymous>)
    at smart-contract-helpers-42daf0db0b108331beed11ccdf2f5ea0.js?vsn=d:2:3682201
    at Function.map (smart-contract-helpers-42daf0db0b108331beed11ccdf2f5ea0.js?vsn=d:2:1458974)
    at l (smart-contract-helpers-42daf0db0b108331beed11ccdf2f5ea0.js?vsn=d:2:3681990)
    at R (smart-contract-helpers-42daf0db0b108331beed11ccdf2f5ea0.js?vsn=d:2:3686146)
```

Here is methods abi

```json
{"type":"function","stateMutability":"nonpayable","outputs":[],"name":"addCollectorData","inputs":[{"type":"address","name":"receiver","internalType":"address"},{"type":"uint256","name":"createdTime","internalType":"uint256"},{"type":"uint32","name":"weight","internalType":"uint32"},{"type":"uint64","name":"price","internalType":"uint64"},{"type":"tuple[]","name":"farmerData","internalType":"struct DataStruct.FarmerData[]","components":[{"type":"uint32","name":"farmerId","internalType":"uint32"},{"type":"uint256","name":"harvestDate","internalType":"uint256"},{"type":"uint256","name":"pulpDate","internalType":"uint256"},{"type":"string","name":"coffeeVariant","internalType":"string"},{"type":"string","name":"coffeeType","internalType":"string"},{"type":"uint32","name":"weight","internalType":"uint32"},{"type":"uint32","name":"pricePerWeight","internalType":"uint32"}]}]}
```

Here is how I put the `farmerData`

```json
[[1,1647062300,1647062300,"arabika","andungsari",50,20000],[2,1647062300,1647062300,"arabika","andungsari",50,20000]]
```

Here is how the method show in web UI

![addCollectorData](https://user-images.githubusercontent.com/37577369/158112170-3d847eaf-0da4-41cd-a14f-def490be792d.png)

**Comment by vbaranov** [comment]
@fahadh4ilyas could you deploy and verify the same contract to a public testnet https://blockscout.com/poa/sokol for debugging purposes? Test coins faucet is here https://faucet.poa.network/. Or please give us the contract source code in order to reproduce by ourselves.

**Comment by fahadh4ilyas** [comment]
> @fahadh4ilyas could you deploy and verify the same contract to a public testnet https://blockscout.com/poa/sokol for debugging purposes? Test coins faucet is here https://faucet.poa.network/. Or please give us the contract source code in order to reproduce by ourselves.

May I get network ID and rpc url of the network?

**Comment by vbaranov** [comment]
@fahadh4ilyas 

Sure, 

https://sokol.poa.network
network ID: 77

**Comment by fahadh4ilyas** [comment]
> @fahadh4ilyas
> 
> Sure,
> 
> https://sokol.poa.network network ID: 77

I can't deploy the contract using truffle. Here's the error
```
Error: PollingBlockTracker - encountered an error while attempting to update latest block: undefined
```

**Comment by fahadh4ilyas** [comment]
> @fahadh4ilyas
> 
> Sure,
> 
> https://sokol.poa.network network ID: 77

Can I get you account address to grant it role to access the contract?

**Comment by vbaranov** [comment]
@fahadh4ilyas Thank you. The issue is reproducible without granting extended permissions.
