### ISSUE TITLE
GraphQL: avoid hardcoding transaction ordering

### ISSUE THREAD

**Issue by SebastienGllmt** [blockscout/blockscout#5323]
One case for the blockscout API to get all transactions for an address is to occasionally poll for any new transactions for a given address.

### Expected behaviour

Allow users to specify asc order for `address_to_transactions_query` so that you can query for all transactions after some known checkpoint

### Actual behaviour

The ordering is [hard-coded](https://github.com/blockscout/blockscout/blob/bef614825d4f1bb0af433136f3e40102d25270fc/apps/explorer/lib/explorer/graphql.ex#L29) as `desc` instead of being a user parameter. Using the `desc` order would still be fine if you could specify in graphQL to get all transactions after some known point, but this is not possible because of #5321

The Rest API does provide this functionality though, so it should be possible to have this exposed in graphQL as well

**Comment by vbaranov** [comment]
Finalized in https://github.com/blockscout/blockscout/pull/5774
