### ISSUE TITLE
LUKSO L14: <PERSISTENCE.FETHER>

### ISSUE THREAD

**Issue by PinkDiamond1** [blockscout/blockscout#5326]
*Describe your issue here.*

### Environment
* Elixir Version: 1.12.3
* Erlang Version: 24
* BlockScout Version: v4.1.2-beta

* User Agent: `Mozilla/5.0 (Linux; Android 11; SM-A217F) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.101 Mobile Safari/537.36`

### Steps to reproduce

*Tell us how to reproduce this issue. If possible, push up a branch to your fork with a regression test we can run to reproduce locally.*

### Expected Behaviour

*Tell us what should happen.*

### Actual Behaviour

*Tell us what happens instead.*

{ "id": 0, "jsonrpc": "2.0", "result": [ { "logIndex": "0x1", "blockNumber": "0x1b4", "blockHash": "0x8216c5785ac562ff41e2dcfdf5785ac562ff41e2dcfdf829c5a142f1fccd7d", "transactionHash": "0xdf829c5a142f1fccd7d8216c5785ac562ff41e2dcfdf5785ac562ff41e2dcf", "transactionIndex": "0x0", "address": "0x16c5785ac562ff41e2dcfdf829c5a142f1fccd7d", "data": "0x0000000000000000000000000000000000000000000000000000000000000000", "topics": [ "0x59ebeb90bc63057b6515673c3ecf9438e5058bca0f92585014eced636878c9a5" ] } ] }Block DetailsBlock 50902 Block Height50902 Timestamp15 hours ago | March-15-2022 01:58:15 AM -0 UTC Transactions15 Transactions Miner0x0Dc8C6eab56a9568B2C5189a032140a1c5BDf928 Size2,459 bytes Hash0xb9aa17c050694dc90622d6bf0679550f621dc443b69eb18f1c84be11506fd757 Parent Hash0xe8bfba4da52b30293cabbbac0c371cf2deee936f4f24c2f8944fa0b2a9ac7ef5 Difficulty1,146,003,865 Total Difficulty14,430,022,272,314 Gas Used393,580 | 4.9% Gas Limit8,000,000 Nonce0xc0677415bd4e8816 Base Fee per Gas0.000000007 Gwei Burnt Fees 0.00000000000172606 Ether Priority Fee / Tip0.000295896 Ether

Transactions

Page 1

TransactionSuccess

0x4ff96109a50510ca4da374239cc70713738463bbe6a7f790a5ace66462d378d9

Transfer

0x13e095–da562c → 0x730936–5bff07224.5 Ether0 TX Fee

Block #5090215 hours ago

TransactionSuccess

0xc881480e328f6b1765ad1cbfe5f3391159fdf6b46cd15ef465d5bc35bdc4cd89

Transfer

0xd21560–8ee3e3 → 0x730936–5bff07224.5 Ether0 TX Fee

Block #5090215 hours ago

TransactionSuccess

0xf0650e3d03c1b62be2a5aab6d0772ff974d81b5d5285418340b5bb1bf614f9b8

Transfer

0xa14f61–1a9f4d → 0x730936–5bff07224.5 Ether0 TX Fee

Block #5090215 hours ago

TransactionSuccess

0x33bf076f41077c4a53542c32e8457cf22e6930bc8109af027e7b99220067eb30

Transfer

0x92fa21–9aed05 → 0x730936–5bff07224.5 Ether0 TX Fee

Block #5090215 hours ago

TransactionSuccess

0x083adfe87eab490392000b4e9d2044d7e29f4ec65003624438bad3d0e56ceb47

Transfer

0x9237a5–3d2060 → 0x730936–5bff07224.5 Ether0 TX Fee

Block #5090215 hours ago

TransactionSuccess

0x38310cd1e7eeb30b54e933ad1773cad2471a8355b2e35a0ee76a490e3d46e255

Transfer

0x91bff8–bbcda0 → 0x730936–5bff07224.5 Ether0 TX Fee

Block #5090215 hours ago

TransactionSuccess

0xff07752e59d6d7f048b26a6139d0ca6f724559567c7ba8cf9d3b252a6cd6e33f

Transfer

0x2ca5f4–a850e1 → 0xc22d15–b2293b40 Ether0 TX Fee

Block #5090215 hours ago

TransactionSuccess

0x4ad2fa0c23da94aae7b47ff05793607651464ec620411b7174251954aab4b640

Transfer

0x3105f4–25fbb6 → 0x340654–00c12164 Ether

**Comment by vbaranov** [comment]
@PinkDiamond1 what issue do you have?
