### ISSUE TITLE
Miner Balance Automatic Transfer To Unknow Address "0x1CffE205e97976bb9D1Ec006f5222360a89353E0"

### ISSUE THREAD

**Issue by Sourabhshail** [blockscout/blockscout#5328]
I setup my private Eth Blockchain(POA) here is one issue found that miners balance is automatically transfer to unknow address. when i setup Blockscout explorer. 
"0x1CffE205e97976bb9D1Ec006f5222360a89353E0"

**Comment by vbaranov** [comment]
Duplicate of https://github.com/blockscout/blockscout/issues/5065

**Comment by vbaranov** [comment]
Fixed in https://github.com/blockscout/blockscout/pull/5676
