### ISSUE TITLE
how to verify contract

### ISSUE THREAD

**Issue by ajaydoyenhub** [blockscout/blockscout#5338]
*Describe your issue here.*
I'm trying to deploy the smart contract but am not able to do that. Please guide me through some samples or links on how to do that.
### Environment

* Elixir & Erlang/OTP versions (`elixir -version`): 1.12 / 24
* Operating System: linux
* Blockscout Version/branch: latest from repo

I want to verify the contract and can **fetch NFT URI from token ID**
![Screenshot from 2022-03-21 17-04-34](https://user-images.githubusercontent.com/55733195/159254595-e0e19ba7-29b3-4f12-bf59-b86b510a26a7.png)
![Screenshot from 2022-03-21 17-04-57](https://user-images.githubusercontent.com/55733195/159254618-a4234a05-2132-4648-bd81-234c861275ea.png)

Expected behaviors I need it should be like below Image

![Screenshot from 2022-03-21 17-15-27](https://user-images.githubusercontent.com/55733195/159256178-52c5bc1a-57ea-421e-9a2a-6b3557c7cd71.png)
![Arianee Smart-Asset (AriaSA) - POA - BlockScout](https://user-images.githubusercontent.com/55733195/159256289-b4b2da98-87b6-4610-a8a5-e36174289611.jpg)

**Comment by ndnam90** [comment]
I think you need to read this document
https://docs.blockscout.com/for-users/verifying-a-smart-contract

**Comment by ajaydoyenhub** [comment]
solved
