### ISSUE TITLE
Blockscout not properly connecting to the Avalanche test network

### ISSUE THREAD

**Issue by Elektro8** [blockscout/blockscout#5343]
*Describe your issue here.*
Blockscout cannot properly connect to Avalanche test local network. It throws an error and keeps retrying.

### Environment

* Elixir & Erlang/OTP versions (`elixir -version`): elixir 1.12.3-otp-24  erlang 24.2
* Operating System: Ubuntu 20.04
* Blockscout Version/branch: 4d6552aae30facd5ebae24d3a5f3d15936ae2fd2 commit

### Steps to reproduce
Setting env vars.
export DATABASE_URL=postgresql://example:password@localhost:5432/blockscout // this is just an example of var being set
export ETHEREUM_JSONRPC_VARIANT=geth
export ETHEREUM_JSONRPC_HTTP_URL=http://localhost:9650/ext/bc/C/rpc
export COIN=AVAX
export CHAIN_ID=43112
export LOGO=/images/blockscout_logo.svg

compiling everything. Starting 5 node avalanache setup and starting blockscout.

### Expected behaviour

Regular output, it should show blocks and tx's in the explorer.

### Actual behaviour

When navigating to the explorer, there are no blocks nor any tx being shown that were made on the network.
Also this error is being thrown in the blockscout when it tries connecting to the avalanche node.

![blockscout avax error](https://user-images.githubusercontent.com/6122886/159373340-98064181-fb30-4dac-a80f-bb17a3b4889d.PNG)

**Comment by vbaranov** [comment]
@Elektro8 could you try implementing [this fix](https://github.com/blockscout/blockscout/pull/5348) on your instance?

**Comment by Elektro8** [comment]
I cloned your commit git clone -b vb-avalanche-fix https://github.com/blockscout/blockscout.git and compiled everything. And sadly same thing happens again.
![avax blockscout error 3](https://user-images.githubusercontent.com/6122886/159664570-1672d422-93f0-488c-ba85-371118ce6fe1.PNG)

Also when I deploy a contract or just do a transaction this happens as well
![avax blockscout error 2 (2)](https://user-images.githubusercontent.com/6122886/159664824-c5e97407-0ce9-43a3-96f8-3046193b16ba.PNG)

**Comment by vbaranov** [comment]
> And sadly same thing happens again.

@Elektro8 not really, the error is different now. Ok, I will add `extDataHash` key as well.

**Comment by Elektro8** [comment]
Oh yeah you are right, sorry. I watching the part that comes after the actual error message, and that was the same.

**Comment by vbaranov** [comment]
@Elektro8  I updated PR with `extDataHash` key adding. Could you pull the latest update and give feedback?

**Comment by vbaranov** [comment]
@Elektro8 could you give a feedback on updated PR? Did it resolve your issue?

**Comment by Elektro8** [comment]
Sorry for the delay. Yes it does solve it. But I have found something else when testing. I tested with ganache and avalanche local network and it only happened on avalanche. I deploy a certain contract and then i execute function using that said contract. And it  blockscout just start throwing errors. Even when wiping blockscout from scratch, as long as that tx  is on the blockchain it keeps throwing errors. 
Here is how it looks.
![errors internal blockscout](https://user-images.githubusercontent.com/6122886/160522354-8239218a-3ad7-4ad4-b0e9-425ac9b4d0f5.PNG)

Seems to me that if some other chain is similar to avalanache one, it can lead to malicious behaviour making it impossible to run blockscout without constant slew of errors. I can give you said contract and function used in PM because of the reason given.

**Comment by vbaranov** [comment]
@Elektro8 by default, if you didn't indicate another JSON RPC Variant (`ETHEREUM_JSONRPC_VARIANT` environment variable), Blockscout works with OpenEthereum-compatible JSON RPC API interface. And thus, for fetching internal transactions, the `trace_replayBlockTransactions` method is used. I would suggest you to check what your node returns for this method and the transaction hash from the logs. I am closing this issue since the original issue has been resolved.
