### ISSUE TITLE
Testnet: <Issue Title> Inaccurate funds 

### ISSUE THREAD

**Issue by Samborski55** [blockscout/blockscout#5344]
*Describe your issue here.*
inaccurate funds for wallet address 0x2A06f5fCFBeF774c4d546A81f37698A3F9659921 1,500,000-2,000,000PLSX short in test net run. 

### Environment
* Elixir Version: 1.12.2
* Erlang Version: 24
* BlockScout Version: 

* User Agent: `Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/99.0.4844.74 Safari/537.36`

### Steps to reproduce

*Tell us how to reproduce this issue. If possible, push up a branch to your fork with a regression test we can run to reproduce locally.*

### Expected Behaviour

*Tell us what should happen.*

### Actual Behaviour

*Tell us what happens instead.*

**Comment by vbaranov** [comment]
PulseChain is not supported here
