### ISSUE TITLE
Testnet: <Harvest on testnet pools list view error>

### ISSUE THREAD

**Issue by donseelim** [blockscout/blockscout#5351]
Harvesting on pool list view constantly met with transaction fail. 

### Environment
* Elixir Version: 1.12.2
* Erlang Version: 24
* BlockScout Version: 

* User Agent: `Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/99.0.4844.74 Safari/537.36`

### Steps to reproduce

Putting PLSX pool in list view, harvest button will not work. Not sure if its set to "compound" instead of harvest.

### Expected Behaviour

Harvest transaction should work

### Actual Behaviour

Harvest transaction constantly fail.

**Comment by vbaranov** [comment]
PulseChain is unsupported here.
