### ISSUE TITLE
Testnet: Mutiple issues with sacrifice and wallets

### ISSUE THREAD

**Issue by Wainbo49** [blockscout/blockscout#5353]
1) Metamask Wallet PLSX points are less estimated

I sacrificed twice from Metamask Wallet 0x54886F2ffFD54d93A99Aca5D47192bC56A5Ef23C

Mon, 14 Feb 2022 03:46:56 GMT HEX 6500 HEX $1,299 $224 0.00002% x1.0119 $5.7918 = 2,270,026
Txn hash 6500 h e x on 3/14   0x7b5fd4c61ab5970a2be800759e8874250047a68d1cfb558036a7724fc6a9fa18

Sun, 13 Feb 2022 03:21:12 GMT HEX 5000 HEX $1,035 $188 0.00002% x1.0119 $5.5160 = 1,899,407
Txn hash 3/13 5000 h e x on 3/13   0xfc5378f88e9c50d018a882fd860da86d20d2b2d176dc63d78b755784a796b91d
 
I only show 3000691.80982 PLSX balance on the PulseX Blockchain verses 4,169,433 estimated.

2) Staker Wallet 
I sacrificed twice from Staker Wallet 0x5414250E1d979f4961EAe2b25Bbb1B6043aFae85
Staker seems to be Hex only wallet and cannot import its 24 word key into Metamask and have no way to get these points to my testnet or know how to on launch.  Also this balance is off by 25% or so on the PulseX Blockchain. I can see 2.4 million PLSX on the PulseX Blockchain.  I cannot find the hash txns through Staker either. Here is the dates and amounts from PulseLead.com. I cannot see a way to get these to my Metamask Wallet.

Wed, 16 Feb 2022 19:14:58 GMT ETHEREUM 0.21 ETH $657 $103 0.00001% x1.0093 - x1.0093 $6.3855 1,038,647

Sun, 13 Feb 2022 23:38:29 GMT ETHEREUM 0.45 ETH $1,295 $235 0.00002% x1.0093 - x1.0093 $5.5160 2,369,657

3) Coinbase Pro Wallet 
I sacrificed $500 of Ethereum from my Coinbase Wallet 0x0BacC01Ea6991dE274C047D7fAf5a574D0709c47 not knowing that was a no no.  I do not believe I have seen these anywhere. I cannot find this Txn Hash anywhere.

I was completely new to Crypto in January and attended a Crypto Workshop in Dallas at the Westin on January 28th with a more experienced friend through FreedomTV.  They were pushing Staker.  I was obviously late to the sacrifice and was struggling to get funds into any of the Wallets at first. If I could sacrifice more at a good rate, that may be a solution.

I want to invest more and have now done my own research and am staked in Hex over $15k with another 6k liquid. I am a Richard Heart fan and look forward to the launch.  Please let me know what I can do to get these credits into my Metamask Wallet.

My email is wayne@dci123.com and phone is 214-263-7300

Thank you.

**Comment by vbaranov** [comment]
PulseChain is unsupported here.
