### ISSUE TITLE
Energy Web Chain: <Issue Title>

### ISSUE THREAD

**Issue by 472peaks** [blockscout/blockscout#5358]
*Describe your issue here.*

Hi,
I just moved 2120 EWT tokens from the Bitmart exchange to an incorrect EWT address. The tokens were meant for my ethereum wallet that hold EWTB erc-20 tokens. I am hoping since it is an unused EWT address (no prior transactions) that perhaps the address that the tokens were sent to is registered with Energy Web.

Below is the Txid and address funds were moved to. I'd appreciate it if anyone can help me resolve this matter. -Eddy

TXID
[0x265e149ea054910bcb1a642477c0095dcc819caafd4d19098da57f2a0a903591](https://explorer.energyweb.org/tx/0x265e149ea054910bcb1a642477c0095dcc819caafd4d19098da57f2a0a903591)

Withdrawal Address
[0x99790C5608b082E7400131E21126C749E4B8C1Ab](https://explorer.energyweb.org/0x99790C5608b082E7400131E21126C749E4B8C1Ab)

![bandicam 2022-03-23 08-13-38-270](https://user-images.githubusercontent.com/102216457/159735506-b217f108-516b-4271-aae3-10f2bfbc834e.jpg)
![bandicam 2022-03-23 08-13-57-981](https://user-images.githubusercontent.com/102216457/159735512-dccf347d-bfe8-4dad-a478-7a0bd6edc330.jpg)
![bandicam 2022-03-23 08-14-27-418](https://user-images.githubusercontent.com/102216457/159735515-a5cc71cb-a2eb-4fe0-baa9-8c4d260335f4.jpg)

### Environment
* Elixir Version: 1.12.2
* Erlang Version: 24
* BlockScout Version: v4.0.0-beta

* User Agent: `Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:92.0) Gecko/20100101 Firefox/92.0`

### Steps to reproduce

*Tell us how to reproduce this issue. If possible, push up a branch to your fork with a regression test we can run to reproduce locally.*

### Expected Behaviour

*Tell us what should happen.*

### Actual Behaviour

*Tell us what happens instead.*

**Comment by vbaranov** [comment]
Please ask in the Energy Web Foundation Blockscout fork https://github.com/energywebfoundation/blockscout

**Comment by vbaranov** [comment]
Please ask in the Energy Web Foundation Blockscout fork https://github.com/energywebfoundation/blockscout
