### ISSUE TITLE
Missing PulseX Sac

### ISSUE THREAD

**Issue by dammiecum** [blockscout/blockscout#5359]
Hello, please my today sacrifice token was initially 840,815. My total sacrifice is $102 at the rate of $1.2 per 10,000 token. 
I only got 597069 token. Please kindly help me fix this problem. 

### Environment
* Elixir Version: 1.12.2
* Erlang Version: 24
* BlockScout Version: 

* User Agent: `Mozilla/5.0 (Linux; Android 12; SM-N976U) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/99.0.4844.73 Mobile Safari/537.36`

### Steps to reproduce

*Tell us how to reproduce this issue. If possible, push up a branch to your fork with a regression test we can run to reproduce locally.*

### Expected Behaviour

*Tell us what should happen.*

### Actual Behaviour

*Tell us what happens instead.*

**Comment by vbaranov** [comment]
PulseChain instance of Blockscout is unsupportred here.
