### ISSUE TITLE
Testnet: PulseX PRT/PLS farming

### ISSUE THREAD

**Issue by bramsmith** [blockscout/blockscout#5370]
*Describe your issue here.*

### Environment
* Elixir Version: 1.12.2
* Erlang Version: 24
* BlockScout Version: 

* User Agent: `Mozilla/5.0 (Linux; Android 9; SM-G955U) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/99.0.4844.88 Mobile Safari/537.36`

### Steps to reproduce

Attempted to add PRT/PLS LP Token to that farm 

### Expected Behaviour

LP should be able to be farmed in PRT/PLS farm

### Actual Behaviour

Tansaction appeared to go through but received red error message at the top of metamask as well and tokens were not credited to the farm

![Screenshot_20220326-115130_MetaMask](https://user-images.githubusercontent.com/31156043/160249795-97be9aae-35c6-436f-b1f1-3d2cbdd21503.jpg)

**Comment by vbaranov** [comment]
PulseChain is unsupported here.
