### ISSUE TITLE
Testnet: <PulseChain Stake not pending transaction>

### ISSUE THREAD

**Issue by Owlie123** [blockscout/blockscout#5373]
*Describe your issue here.*

1. I staked 5,000,000 tPLS to a validator and it is not pending. It deducted from my wallet and was confirmed but it is not showing the pending on the testnet pulschain.  I submitted 4 different stakes to 4 different validators, only 3 of the stakes are pending. The 4th stake is non-existent.  
2. I am having issues going on to pulse scan to view any of my transactions.
3. I cannot add the USDC token onto my wallet because the pulse scan is freezing to get on to the browser. 

### Environment
* Elixir Version: 1.12.2
* Erlang Version: 24
* BlockScout Version: 

* User Agent: `Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:98.0) Gecko/20100101 Firefox/98.0`

### Steps to reproduce

*Tell us how to reproduce this issue. If possible, push up a branch to your fork with a regression test we can run to reproduce locally.*

### Expected Behaviour

*Tell us what should happen.*
I am not sure if this is a validator issue. 

### Actual Behaviour

*Tell us what happens instead.*

**Comment by Owlie123** [comment]
Pulse stake is now working. 

I still cant access pulsescan to view my transactions.

**Comment by Owlie123** [comment]
I can see my transactions when i copy/paste my address into pulsescan. I do not see it when I click on the tab via metamask. I think it must be a metamask issue and not a pulseschain issue. Not sure tho.

**Comment by Liuminjin** [comment]
You will have to synchronize your wallet and then you debug it with bech13

**Comment by vbaranov** [comment]
PulseChain is unsupported in the main Blockscout repository.
