### ISSUE TITLE
Palm: <Issue Title>

### ISSUE THREAD

**Issue by sanjumaini** [blockscout/blockscout#5379]
*Describe your issue here.*

### Environment
* Elixir Version: 1.12.2
* Erlang Version: 24
* BlockScout Version: 

* User Agent: `Mozilla/5.0 (Linux; Android 11; Redmi Note 8 Pro) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/99.0.4844.66 Mobile Safari/537.36`

### Steps to reproduce

*Tell us how to reproduce this issue. If possible, push up a branch to your fork with a regression test we can run to reproduce locally.*

### Expected Behaviour

*Tell us what should happen.*

### Actual Behaviour

*Tell us what happens instead.*

**Comment by sanjumaini** [comment]
transaction hash
0x0562dbaba5e6d67dfdf275db37b6e52447912beb2c9a1537bc93377858f3130e
 tokens didn't arrived in recipient's address

**Comment by vbaranov** [comment]
Palm instance is unsupported here.
