### ISSUE TITLE
Palm: <Issue Title>

### ISSUE THREAD

**Issue by Jusinofredo** [blockscout/blockscout#5386]
*Had $47 in Dai in my niftys wallet. I sent it to my MetaMask wallet because that’s the only wallet it’s allowing me to send. The palm network said it’s a success that it got confirmed thousand of times. I have yet to receive the $47 Dai in my MetaMask wallet? Addresses are correct. 
### Environment
* Elixir Version: 1.12.2
* Erlang Version: 24
* BlockScout Version: 

* User Agent: `Mozilla/5.0 (iPhone; CPU iPhone OS 14_8_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.1.2 Mobile/15E148 Safari/604.1`

### Steps to reproduce

*Tell us how to reproduce this issue. If possible, push up a branch to your fork with a regression test we can run to reproduce locally.*

### Expected Behaviour

*Tell us what should happen.*

### Actual Behaviour

*Tell us what happens instead.*

**Comment by vbaranov** [comment]
Palm is unsupported here
