### ISSUE TITLE
Testnet: <Pulsex/pulsechain tokens missing>

### ISSUE THREAD

**Issue by petermik3** [blockscout/blockscout#5387]
*hi there is two issues , i sent xdb to pulsex sacrifice transaction hash 0xededa2918ca6d7d8492d4d9595e3b4ae824046d21c357312e06d05172d68f883

also i was meant to sacrifice eth to pulsex sacrifice but entered pulsechain sacrifice address when sending walllet address is 0x281f6109F955165cC37D5E5Dd96f22672B4Bb620

.*

### Environment
* Elixir Version: 1.12.2
* Erlang Version: 24
* BlockScout Version: 

* User Agent: `Mozilla/5.0 (iPhone; CPU iPhone OS 15_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) CriOS/99.0.4844.59 Mobile/15E148 Safari/604.1`

### Steps to reproduce

*Tell us how to reproduce this issue. If possible, push up a branch to your fork with a regression test we can run to reproduce locally.*

### Expected Behaviour

*Tell us what should happen.*

### Actual Behaviour

*Tell us what happens instead.*

**Comment by vbaranov** [comment]
PulseChain is unsupported here.
