### ISSUE TITLE
Request for darkmode on Explorer....my eyes!

### ISSUE THREAD

**Issue by Yellow-Cake** [blockscout/blockscout#5388]
*Describe your issue here.*

### Environment
* Elixir Version: 1.12.2
* Erlang Version: 24
* BlockScout Version: 

* User Agent: `Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/99.0.4844.88 Safari/537.36`

### Steps to reproduce

*Tell us how to reproduce this issue. If possible, push up a branch to your fork with a regression test we can run to reproduce locally.*

### Expected Behaviour

*Tell us what should happen.*

### Actual Behaviour

*Tell us what happens instead.*
Request for darkmode on explorer, my eyes are burning!!!

**Comment by vbaranov** [comment]
Switching to dark mode is available in the top navigation bar at the left of the search bar:

<img width="450" alt="Screenshot 2022-03-30 at 13 23 44" src="https://user-images.githubusercontent.com/4341812/160798337-baa461b9-b47f-49a0-b0e2-52763b83371d.png">

**Comment by Yellow-Cake** [comment]
The option seems to be either missing on Brave browser, or maybe hidden by
the block indexing banner?

**Comment by vbaranov** [comment]
@Yellow-Cake can you show the screesnhot how it looks on your end? And what instance of Blockscout are you talking about?
