### ISSUE TITLE
Astar (EVM): <Issue Title>

### ISSUE THREAD

**Issue by yui6134** [blockscout/blockscout#5390]
*Describe your issue here.*

### Environment
* Elixir Version: 1.12.3
* Erlang Version: 24
* BlockScout Version: v4.1.2-beta

* User Agent: `Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/99.0.4844.84 Safari/537.36`

### Steps to reproduce

*Tell us how to reproduce this issue. If possible, push up a branch to your fork with a regression test we can run to reproduce locally.*

### Expected Behaviour

*Tell us what should happen.*

### Actual Behaviour

*Tell us what happens instead.*

**Comment by yui6134** [comment]
メタマスクからアスターのポータブルサイトのポルがドットに送金したんですが、間違えてしまったみたいでどこのアドレスか分かりません。
コインを取り戻す事はできますか？

0x1dacf3acc9322bf2d0d182af0de9f13df4d2bf54c096a06a6490de3ccfd390ed
トランザクションID

**Comment by vbaranov** [comment]
How can we help you? Please use English.
