### ISSUE TITLE
Incorrect typing of input data from webui

### ISSUE THREAD

**Issue by xrpdevs** [blockscout/blockscout#5395]
I have a function that takes an int (not a uint) as a parameter, if its a negative value, function flips it into a positive.

Works in tests with javascript and the ABI just fine. 

But in blockscout I get errors like below: 

 6. flipSignT → (int128) -> value entered "100"
↳ uint128

[ flipSignT method Response ]

(error) : Data overflow encoding int, data `{` cannot fit in 128 bits

Can't remember version number but is recent from github (about 2 months ago or so, presume problem exists in newer versions too)

**Comment by vbaranov** [comment]
@xrpdevs do you have, maybe, an example of the contract with the function in any of Blockscout instances from https://blockscout.com?

**Comment by nikitosing** [comment]
duplicate of #4674
