### ISSUE TITLE
Gnosis Chain: <Issue Title>Deposit of 27.8695 USDC from my M/Mask Gnosis Network to an Australian Exchange not received. 

### ISSUE THREAD

**Issue by PAM445** [blockscout/blockscout#5405]
*Describe your issue here.*Deposit of 27.8695 USDC from M/mask Gnosis Network into an Australian Exchange---NOT RECEIVED on 2 nd April 2022
Gnosis Explorer details:- CAN ANYONE HELP !!!!!

### Environment
* Elixir Version: 1.12.3
* Erlang Version: 24
* BlockScout Version: v4.1.2-beta

* User Agent: `Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.60 Safari/537.36`

### Steps to reproduce

*Tell us how to reproduce this issue. If possible, push up a branch to your fork with a regression test we can run to reproduce locally.*

### Expected Behaviour

*Tell us what should happen.*

### Actual Behaviour

*Tell us what happens instead.*

**Comment by vbaranov** [comment]
Please ask your question in the #gnosis-chain channel on Discord https://discord.gg/mPJ9zkq

**Comment by PAM445** [comment]
Hi Victor,I think I have this problem sorted, it appears the exchange does not recognise USDC deposits from the Gnosis Platform, seems very strange ????  Sent from Mail for Windows From: Victor BaranovSent: Monday, 4 April 2022 3:36 PMTo: blockscout/blockscoutCc: PAM445; AuthorSubject: Re: [blockscout/blockscout] Gnosis Chain: <Issue Title>Deposit of 27.8695 USDC from my M/Mask Gnosis Network to an Australian Exchange not received. (Issue #5405) Please ask your question in the #gnosis-chain channel on Discord https://discord.gg/mPJ9zkq—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>
