### ISSUE TITLE
Testnet: <Issue Title>

### ISSUE THREAD

**Issue by BRB295** [blockscout/blockscout#5423]
Hi

I dont have any PULSE X in my wallet at all

0xB5406Ff31a98C4E121dc9493591a48Bd26C95aaA

It seems that there is a problem with the transaction, 

Can you assist me ?

Thank you

### Environment
* Elixir Version: 1.12.2
* Erlang Version: 24
* BlockScout Version: 

* User Agent: `Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/99.0.4844.51 Safari/537.36`

### Steps to reproduce

*Tell us how to reproduce this issue. If possible, push up a branch to your fork with a regression test we can run to reproduce locally.*

### Expected Behaviour

*Tell us what should happen.*

### Actual Behaviour

*Tell us what happens instead.*

**Comment by vbaranov** [comment]
PulseChain instance of Blockscout is unsupported here
