### ISSUE TITLE
Testnet: <Issue Title>

### ISSUE THREAD

**Issue by Nocap4200** [blockscout/blockscout#5426]
*Describe your issue 

My pulse chain balance is showing 0.000024 but I have 230k pulsechain points
![Screenshot_20220407-160510_MetaMask](https://user-images.githubusercontent.com/103203543/162232857-3ecc48ab-a623-45ee-be4a-13b07a8c9335.jpg)
![Screenshot_20220407-160512_MetaMask](https://user-images.githubusercontent.com/103203543/162232873-d776dd62-05ba-4f62-b71e-070cce2f811e.jpg)
![Screenshot_20220407-160206_Trust Wallet](https://user-images.githubusercontent.com/103203543/162232893-cde70d4f-ba4e-44b0-bfe9-274a18177ad1.jpg)

**Comment by vbaranov** [comment]
PulseChain is unsupported here.
