### ISSUE TITLE
Unable to verify a flattened contract without metadata hash

### ISSUE THREAD

**Issue by alexdupre** [blockscout/blockscout#5430]
Blockscout is unable to verify flattened solidity smart contracts compiled with `metadata-hash none`.

The metadata hash is ignored by Blockscout when verifying flattened source files, nevertheless if missing it breaks Blockscout metadata parsing.

To be honest (and for an Elixir layman), the metadata parsing code seems a real mess, with matches on opaque sequences of bytes that are not able to cope with all possibilities. The use of a CBOR decoder, like https://github.com/scalpel-software/cbor, would simplify the code a lot and remove the intrinsic fragility.

### Environment

* Blockscout Version/branch: v4.1.2-beta

### Steps to reproduce

1. Deploy a contract built with: `./solc --metadata-hash none ...`
2. Try to verify it with a flattened source file

### Expected behaviour

The bytecode metadata, containing only the solc version, is correctly parsed and the smart contract verified

### Actual behaviour

Metadata parsing fails, returning the error `Compiler version does not match, please try again.`

**Comment by alexdupre** [comment]
Some additional comments:
1) solc code that generates metadata: https://github.com/ethereum/solidity/blob/7f360e61fc4c1e9da0922144bbba9e5f0dbde592/libsolidity/interface/CompilerStack.cpp#L1671-L1692
2) solc test code that finds the metadata: https://github.com/ethereum/solidity/blob/8188ea7d66243e5611e0ae621dd34ec95acae70b/test/Metadata.cpp#L34-L47
3) solc simple CBOR decoder: https://github.com/ethereum/solidity/blob/8188ea7d66243e5611e0ae621dd34ec95acae70b/test/Metadata.cpp#L64-L170

As an example, what's here is identified as "hash common suffix" https://github.com/blockscout/blockscout/blob/ba8e41c0181c91d7774e33d7cfd5a6a796c13d6b/apps/explorer/lib/explorer/smart_contract/solidity/verifier.ex#L21 is actually a 4-bytes len string (0x64) with content "solc" (0x736f6c63), that is the start of the metadata map's entry containing the compiler version (nothing to do with the previous optional entry, that may be the hash).

**Comment by nikitosing** [comment]
@alexdupre could you please share your solidity code and compiling parameters?

**Comment by alexdupre** [comment]
It can be as simple as
```
contract C {
  function test() external pure returns (uint256) {
    return 1;
  }
}
```

and compiled with
```
solc -o out --bin --metadata-hash none C.sol
```
