### ISSUE TITLE
Unable to verify a contract with standard json input, bytecodeHash none and constructor arguments

### ISSUE THREAD

**Issue by alexdupre** [blockscout/blockscout#5431]
Blockscout is unable to verify smart contract with the standard json input method when the following conditions are both true:
- the contract has been compiled with `"bytecodeHash": "none"`
- the contract requires contructor arguments

If just one of the above conditions is true, then the verification succeeds.

### Environment

* Blockscout Version/branch: v4.1.2-beta

### Steps to reproduce
1. Deploy a contract with constructor arguments built with: `./solc --standard-json ...` and a json file with:
```
    "metadata": {
      "useLiteralContent": true,
      "bytecodeHash": "none"
    },
```
2. Try to verify it with the standard json input, passing the abi encoded constructor params

### Expected behaviour

The contract is verified.

### Actual behaviour

It returns the error `There was an error validating your contract, please try again.`

**Comment by nikitosing** [comment]
@alexdupre did you try to verify with `Try to fetch constructor arguments automatically` parameter set `Yes`?
![image](https://user-images.githubusercontent.com/32202610/163254094-268cd0db-ab33-4371-b693-23f99db67647.png)

**Comment by alexdupre** [comment]
I'm quite sure I tried it in one of the several attempts I did, without success. Said so, explicitely passing the arguments should work as well and even better.
