### ISSUE TITLE
Line endings are not correctly displayed for contracts verified with standard json input

### ISSUE THREAD

**Issue by alexdupre** [blockscout/blockscout#5432]
If a contract is verified with standard input json and includes the literal smart contract's source code, the `Code` tab of the explorer shows the entire source code on a single line instead of breaking lines where there was a `\n` in the original source code.
Clicking on `Copy Source Code` does the right thing, because in such case the `\n` are retained, while they aren't in the code area.

### Environment

* Blockscout Version/branch: v4.1.2-beta

### Steps to reproduce

1. Verify a contract with standard input json and literal source code

### Expected behaviour

See the contract's code correctly formatted

### Actual behaviour

The entire code is on a single line.

**Comment by nikitosing** [comment]
@alexdupre could you provide an example of such case? For example [here](https://blockscout.com/xdai/mainnet/address/0x36A644cC38Ae257136EEca5919800f364d73FeFC/contracts) it formatted correclty.

**Comment by alexdupre** [comment]
[Here](https://coston-explorer.flare.network/address/0x825b8DEe38E961e473b038B9992b4c3dbb4E9A9f/contracts) is an example.

**Comment by nikitosing** [comment]
![image](https://user-images.githubusercontent.com/32202610/164624639-d7f95401-74aa-4d42-bb59-f4424ccd505d.png)
problem here. I think problem in the module version

**Comment by nikitosing** [comment]
Yes, we will fix it

**Comment by nikitosing** [comment]
@alexdupre did you set MIX_ENV env variable? If no, you can try set MIX_ENV=prod

**Comment by alexdupre** [comment]
I confirm `MIX_ENV=prod` was set.
