### ISSUE TITLE
"timestampNano" related (FunctionClauseError) no function clause matching in EthereumJSONRPC.Block.entry_to_elixir/1

### ISSUE THREAD

**Issue by bitkin** [blockscout/blockscout#5436]
Hello, I'm trying to run blockscout with geth compatible node but there are lot of repeated errors in the log and blockscout is not showing any data on the web page. I don't know about the problem. The node is geth compatible and working fine.
The error message shows about the "timestampNano" variable which is not successfully parsing. 

```
Retrying.
2022-04-09T05:22:06.181 application=indexer fetcher=block_catchup first_block_number=99326 last_block_number=99317 [error] ** (FunctionClauseError) no function clause matching in EthereumJSONRPC.Block.entry_to_elixir/1
    (ethereum_jsonrpc 0.1.0) lib/ethereum_jsonrpc/block.ex:574: EthereumJSONRPC.Block.entry_to_elixir({"timestampNano", "0x16dba07edc55bae0"})
    (elixir 1.12.2) lib/enum.ex:1586: anonymous fn/3 in Enum.map/2
    (stdlib 3.15.1) maps.erl:410: :maps.fold_1/3
    (elixir 1.12.2) lib/enum.ex:2397: Enum.map/2
    (elixir 1.12.2) lib/enum.ex:1485: Enum.into/3
    (elixir 1.12.2) lib/enum.ex:1582: Enum."-map/2-lists^map/1-0-"/2
    (ethereum_jsonrpc 0.1.0) lib/ethereum_jsonrpc/blocks.ex:44: EthereumJSONRPC.Blocks.from_responses/2
    (ethereum_jsonrpc 0.1.0) lib/ethereum_jsonrpc.ex:487: EthereumJSONRPC.fetch_blocks_by_params/3

```

### Environment

* Elixir & Erlang/OTP versions (`elixir -version`): Elixir 1.12.2 (compiled with Erlang/OTP 24)
* Operating System: Ubuntu 20.04 (Blockscout is running on docker)
* Blockscout Version/branch: 4.0.0

### Steps to reproduce

Start the new blockscout instance in docker with the configuration required

### Expected behaviour

Bloskscout should run and display data

### Actual behaviour

Blockscout is not showing the data on the webpage, instead, it is showing the errors in the logs.

**Comment by vbaranov** [comment]
@bitkin this happens due to customization in Geth. Could you share any public information about this cutomized Geth client? It can be fixed similar to what was implemented for other customized clients. For instance, https://github.com/blockscout/blockscout/pull/5348/files.

**Comment by bitkin** [comment]
@vbaranov the node is of TechPay blockchain. [https://github.com/TechPay-io/go-photon](https://github.com/TechPay-io/go-photon) this is the link to the source code. I also tried with the public available api as [TechPay Public Api](https://api.techpay.io/) 
This api is working with my metamask and expedition explorer. Can you suggest about the fix possible? Thanks :)
