### ISSUE TITLE
Testnet: Issue removing liquidity using Ledger on METAMASK - transaction keeps failing

### ISSUE THREAD

**Issue by Mirmidoneca** [blockscout/blockscout#5438]
*Describe your issue here.

The problem that I encaunter all the time with pulseX is that every time I try to remove liquidity pair the transaction keeps failing. 
I guess this comes from the fact that my MM is linked to a ledger and it is very frustrating. Hope this problem will be resolved till main net, if you have time please investigate.

Transaction Hash - 0xbfefc82d2a7272a43514485d528d09127649e9fa3bf3176b141645c63a660429

### Environment
* Elixir Version: 1.12.2
* Erlang Version: 24
* BlockScout Version: 

* User Agent: `Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.79 Safari/537.36`

### Steps to reproduce

*Tell us how to reproduce this issue. If possible, push up a branch to your fork with a regression test we can run to reproduce locally.*

### Expected Behaviour

*Tell us what should happen.*

### Actual Behaviour

*Tell us what happens instead.*

**Comment by vbaranov** [comment]
PulseChain instance of Blockscout is unsupported here.
