### ISSUE TITLE
Ethereum Classic: 0x50275201660e6e3167b861d9f664ed5639b31801efca365fabb25ebc509797de

### ISSUE THREAD

**Issue by EagleMan2506** [blockscout/blockscout#5441]
Hi
I transferred money from one wallet to an other:

Transaction id:
0x50275201660e6e3167b861d9f664ed5639b31801efca365fabb25ebc509797de

The money did get out from the first but didn’t enter the second
Please tell me y? And how i fix this

### Environment
* Elixir Version: 1.12.2
* Erlang Version: 24
* BlockScout Version: v4.1.1-beta

* User Agent: `Mozilla/5.0 (iPhone; CPU iPhone OS 15_3_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/15.3 Mobile/15E148 Safari/604.1`

### Steps to reproduce

*Tell us how to reproduce this issue. If possible, push up a branch to your fork with a regression test we can run to reproduce locally.*

### Expected Behaviour

*Tell us what should happen.*

### Actual Behaviour

*Tell us what happens instead.*

**Comment by vbaranov** [comment]
Regarding your question try to contact ETC team, for instance, on their Discord https://discord.com/invite/hQs894U.
