### ISSUE TITLE
Issue with the API (RPC) endpoint module. Returns "something went wrong" (LUKSO L14)

### ISSUE THREAD

**Issue by CJ42** [blockscout/blockscout#5448]
*Describe your issue here.*

### Environment

* Blockscout Version/branch: [v4.1.2-beta](https://github.com/blockscout/blockscout/releases/tag/v4.1.2-beta)

### Steps to reproduce

Just enter : https://blockscout.com/lukso/l14/api?module=block&action=getblockreward&blockno=13296975 in your favorite browser.

### Expected behaviour

It should return a json with the block reward.

### Actual behaviour

Currently return the following error message:

```json
{
    "message": "Something went wrong.",
    "result": null,
    "status": "0"
}
```

Also the endpoint URL now shows as `localhost`

![image](https://user-images.githubusercontent.com/31145285/162913045-07d8c733-d05d-4391-82f0-7411ea76bee1.png)

**Comment by vbaranov** [comment]
@CJ42 the issue with blockreward endpoint resolved by updating LUKSO L14 instance. Again, If you have the URL for chain spec path for LUKSO L14, please post it in order to configure on the instance.

**Comment by CJ42** [comment]
@vbaranov here is the chainspecs file https://github.com/lukso-network/l14-chain-spec/blob/l14/spec.json
raw: https://raw.githubusercontent.com/lukso-network/l14-chain-spec/l14/spec.json

**Comment by vbaranov** [comment]
@CJ42 thank you, applied to LUKSO L14 instance.
