### ISSUE TITLE
Emerald Mainnet: <I cannot receive BNB token from BSC chain to Oasis emerald chain via Multichain>

### ISSUE THREAD

**Issue by Nutwuthaste** [blockscout/blockscout#5451]
I cannot receive BNB token from BSC chain to Oasis emerald chain via Multichain

### Environment
* Elixir Version: 1.12.3
* Erlang Version: 24
* BlockScout Version: 0.0.1

* User Agent: `Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.75 Safari/537.36`

### Steps to reproduce

I have bridge token BNB (total 4.89 BNB) from BSC to Emerald oasis network chain via Multichain in 2022/04/11.
And then, I cannot receive BNB token in Oasis emerald chain.
But, my BNB has already transferred from my account.
This is tx hash from BSC chain.
=> 0xbcf2c096d76713e5f81570a0b62183a6fba92a8c1630da7c530863a21c1141dc
This is history from Multichain.
=> https://anyswap.net/explorer/tx?params=0xbcf2c096d76713e5f81570a0b62183a6fba92a8c1630da7c530863a21c1141dc

### Expected Behaviour

I would like to get my BNB. 

### Actual Behaviour

Still pending on history of Multichain status.
I can find tx hash from BSC chain, but cannot find it 
<img width="1195" alt="ภาพถ่ายหน้าจอ 2565-04-12 เวลา 21 03 05" src="https://user-images.githubusercontent.com/103514202/162980191-780d63ff-0608-40aa-9d88-be6082b06f96.png">
from emerald (oasis network).

**Comment by vbaranov** [comment]
This instance of Blockscout is unsupported here.
