### ISSUE TITLE
please help me for windows OS

### ISSUE THREAD

**Issue by soumen29121997** [blockscout/blockscout#5453]
@vbaranov please check

could not compile dependency :libsecp256k1, "mix compile" failed. Errors may have been logged above. You can recompile this dependency with "mix deps.compile libsecp256k1", update it with "mix deps.update libsecp256k1" or clean it with "mix deps.clean libsecp256k1"
** (ErlangError) Erlang error: :enoent
(elixir 1.13.4) lib/system.ex:1044: System.cmd("make", [], [into: %IO.Stream{device: :standard_io, line_or_bytes: :line, raw: false}])
e:/Phoniex/trial 2/blockscout-2.1.0-beta/deps/libsecp256k1/mix.exs:3: Mix.Tasks.Compile.MakeBindings.run/1
(mix 1.13.4) lib/mix/task.ex:397: anonymous fn/3 in Mix.Task.run_task/3
(mix 1.13.4) lib/mix/tasks/compile.all.ex:92: Mix.Tasks.Compile.All.run_compiler/2
(mix 1.13.4) lib/mix/tasks/compile.all.ex:72: Mix.Tasks.Compile.All.compile/4
(mix 1.13.4) lib/mix/tasks/compile.all.ex:59: Mix.Tasks.Compile.All.with_logger_app/2
(mix 1.13.4) lib/mix/tasks/compile.all.ex:36: Mix.Tasks.Compile.All.run/1

**Comment by vbaranov** [comment]
@nikitosing could you please take a look?

**Comment by nikitosing** [comment]
@soumen29121997 Did you install make and  visual studio c++ compiler? https://docs.blockscout.com/for-developers/information-and-settings/requirements

**Comment by soumen29121997** [comment]
@nikitosing i have installed make and visuall studio c++ compiler. But now other error is comming

could not compile dependency :bcrypt_elixir, "mix compile" failed. You can recompile this dependency with "mix deps.compile bcrypt_elixir", update it with "mix deps.update bcrypt_elixir" or clean it with "mix deps.clean bcrypt_elixir"

==> block_scout
** (Mix) "nmake" not found in the path. If you have set the MAKE environment variable,
please make sure it is correct.

**Comment by nikitosing** [comment]
@soumen29121997 you need to include VS c++ to the path variable in system. [info](https://superuser.com/questions/949560/how-do-i-set-system-environment-variables-in-windows-10) about path
My content of path which is related to VS c++:
![image](https://user-images.githubusercontent.com/32202610/163168431-1b0640bf-f43d-443a-aefe-1a6833ce725a.png)

**Comment by soumen29121997** [comment]
@nikitosing can you please help me out in discord please.

**Comment by nikitosing** [comment]
@soumen29121997 Sorry, no, I haven't time for that for now. You can google your errors. Also you could ask for help in our Discord: discord.gg/gnosischain (Channel #blockscout)

**Comment by soumen29121997** [comment]
@nikitosing 

==> bcrypt_elixir

Microsoft (R) Program Maintenance Utility Version 14.28.29336.0
Copyright (C) Microsoft Corporation.  All rights reserved.

        del /Q /F priv
        erl -eval "io:format(\"~s~n\", [lists:concat([\"ERTS_INCLUDE_PATH=\", code:root_dir(), \"/erts-\", erlang:system_info(version), \"/include\"])])" -s init stop -noshell > Makefile.auto.win
        nmake /                   /F Makefile.win priv\bcrypt_nif.dll

Microsoft (R) Program Maintenance Utility Version 14.28.29336.0
Copyright (C) Microsoft Corporation.  All rights reserved.

        if NOT EXIST "priv" mkdir "priv"
        cl /O2 /EHsc /I"c_src" /I"c:/Program Files/erl-24.1.7/erts-12.1.5/include" /LD /MD /Fepriv\bcrypt_nif.dll  c_src\bcrypt_nif.c c_src\blowfish.c
Microsoft (R) C/C++ Optimizing Compiler Version 19.28.29336 for x64
Copyright (C) Microsoft Corporation.  All rights reserved.

bcrypt_nif.c
c_src\bcrypt_nif.c(52): fatal error C1083: Cannot open include file: 'stdio.h': No such file or directory
blowfish.c
e:\Phoniex\blockscout\deps\bcrypt_elixir\c_src\blf.h(37): fatal error C1083: Cannot open include file: 'stdint.h': No such file or directory
Generating Code...
NMAKE : fatal error U1077: '"C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\VC\Tools\MSVC\14.28.29333\bin\Hostx64\x64\cl.EXE"' : return code '0x2'
Stop.
NMAKE : fatal error U1077: '"C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\VC\Tools\MSVC\14.28.29333\bin\Hostx64\x64\nmake.EXE"' : return code '0x2'
Stop.
could not compile dependency :bcrypt_elixir, "mix compile" failed. You can recompile this dependency with "mix deps.compile bcrypt_elixir", update it with "mix deps.update bcrypt_elixir" or clean it with "mix deps.clean bcrypt_elixir"
==> block_scout
** (Mix) Could not compile with "nmake" (exit status: 2).
One option is to install a recent version of
[Visual C++ Build Tools](https://visualstudio.microsoft.com/visual-cpp-build-tools/)
either manually or using [Chocolatey](https://chocolatey.org/) -
`choco install VisualCppBuildTools`.

After installing Visual C++ Build Tools, look in the "Program Files (x86)"
directory and search for "Microsoft Visual Studio". Note down the full path
of the folder with the highest version number. Open the "run" command and
type in the following command (make sure that the path and version number
are correct):

    cmd /K "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" amd64

This should open up a command prompt with the necessary environment variables
set, and from which you will be able to run the "mix compile", "mix deps.compile",
and "mix test" commands.

**Comment by nikitosing** [comment]
@soumen29121997 you need to create .bat file with the following content:
```
cmd /K "C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Auxiliary\Build\vcvarsall.bat" amd64
```
Please check that path is correct for your installation. After that just run this .bat file via cmd. Like: 
```
D:\blocksckout>consoleVS0.bat
```
and run mix compile after initializing the console

**Comment by nikitosing** [comment]
Once you have done this steps, you could just `run mix compile`. Because this step was required only for couple of libraries. I mean  it is one-time procedure. But may be required again in cases of update deps or cleaning of .build directory

**Comment by soumen29121997** [comment]
![ss](https://user-images.githubusercontent.com/94948837/163193292-e6215bb5-241d-4a5b-b4e4-74b59c57c5bf.jpg)

**Comment by soumen29121997** [comment]
@nikitosing  you can see i alreay create the .bat file but still i got this
After installing Visual C++ Build Tools, look in the "Program Files (x86)"
directory and search for "Microsoft Visual Studio". Note down the full path
of the folder with the highest version number. Open the "run" command and
type in the following command (make sure that the path and version number
are correct):

    cmd /K "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" amd64

This should open up a command prompt with the necessary environment variables
set, and from which you will be able to run the "mix compile", "mix deps.compile",
and "mix test" commands.

**Comment by nikitosing** [comment]
No, you shouldnt create `vcvarsall.bat` this .bat provided by Visual Studio. Forget about the step with creating .bat. You just need to run `cmd /K "C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Auxiliary\Build\vcvarsall.bat" amd64` (check that path is right for your installation) and then `mix compile`

**Comment by nikitosing** [comment]
@soumen29121997 you need to install cargo

**Comment by nikitosing** [comment]
@soumen29121997 did you provide DATABASE_URL env var?

**Comment by soumen29121997** [comment]
@nikitosing can you please tell me in which file i should changed the DATABASE_URL env var

**Comment by soumen29121997** [comment]
@nikitosing in many files DATABASE_URL  env var is present can you please tell me in which file should i changed it to localhost

**Comment by soumen29121997** [comment]
@nikitosing i set the DATABASE_URL

E:\Phoniex\trial\blockscout>set DATABASE_URL=postgresql://postgres:postgres@localhost:5432/blockscout

E:\Phoniex\trial\blockscout>mix do ecto.create, ecto.migrate
The database for Explorer.Repo has already been created

**Comment by soumen29121997** [comment]
But i still got this message

2022-04-14T00:08:49.048 [error] Process #PID<0.851.0> raised an exception
** (RuntimeError) An error occurred when loading Bcrypt.
Make sure you have a C compiler and Erlang 20 installed.
If you are not using Erlang 20, either upgrade to Erlang 20 or
use version 0.12 of bcrypt_elixir.
See the Comeonin wiki for more information.

    (bcrypt_elixir 1.1.1) lib/bcrypt/base.ex:17: Bcrypt.Base.init/0
    (kernel 8.1.3) code_server.erl:1317: anonymous fn/1 in :code_server.handle_on_load/5
2022-04-14T00:08:49.051 [warn] The on_load function for module Elixir.Bcrypt.Base returned:
{%RuntimeError{
   message: "An error occurred when loading Bcrypt.\nMake sure you have a C compiler and Erlang 20 installed.\nIf you are not using Erlang 20, either upgrade to Erlang 20 or\nuse version 0.12 of bcrypt_elixir.\nSee the Comeonin wiki for more information.\n"
 },
 [
   {Bcrypt.Base, :init, 0, [file: 'lib/bcrypt/base.ex', line: 17]},
   {:code_server, :"-handle_on_load/5-fun-0-", 1,
    [file: 'code_server.erl', line: 1317]}
 ]}

2022-04-14T00:09:00.571 [warn] The on_load function for module libsecp256k1 returned:
{:error,
 {:load_failed,
  'Failed to load NIF library e:/Phoniex/trial/blockscout/_build/dev/lib/libsecp256k1/priv/libsecp256k1_nif: \'The specified module could not be found.\''}}

2022-04-14T00:09:05.026 [warn] The on_load function for module prometheus_process_collector returned:
{:error,
 {:load_failed,
  'Failed to load NIF library e:/Phoniex/trial/blockscout/_build/dev/lib/prometheus_process_collector/priv/prometheus_process_collector: \'The specified module could not be found.\''}}

2022-04-14T00:09:09.692 [error] Process #PID<0.867.0> raised an exception
** (RuntimeError) An error occurred when loading Bcrypt.
Make sure you have a C compiler and Erlang 20 installed.
If you are not using Erlang 20, either upgrade to Erlang 20 or
use version 0.12 of bcrypt_elixir.
See the Comeonin wiki for more information.

    (bcrypt_elixir 1.1.1) lib/bcrypt/base.ex:17: Bcrypt.Base.init/0
    (kernel 8.1.3) code_server.erl:1317: anonymous fn/1 in :code_server.handle_on_load/5
2022-04-14T00:09:09.697 [warn] The on_load function for module Elixir.Bcrypt.Base returned:
{%RuntimeError{
   message: "An error occurred when loading Bcrypt.\nMake sure you have a C compiler and Erlang 20 installed.\nIf you are not using Erlang 20, either upgrade to Erlang 20 or\nuse version 0.12 of bcrypt_elixir.\nSee the Comeonin wiki for more information.\n"
 },
 [
   {Bcrypt.Base, :init, 0, [file: 'lib/bcrypt/base.ex', line: 17]},
   {:code_server, :"-handle_on_load/5-fun-0-", 1,
    [file: 'code_server.erl', line: 1317]}
 ]}

2022-04-14T00:09:09.724 [warn] The on_load function for module libsecp256k1 returned:
{:error,
 {:load_failed,
  'Failed to load NIF library e:/Phoniex/trial/blockscout/_build/dev/lib/libsecp256k1/priv/libsecp256k1_nif: \'The specified module could not be found.\''}}

2022-04-14T00:09:09.743 [warn] The on_load function for module prometheus_process_collector returned:
{:error,
 {:load_failed,
  'Failed to load NIF library e:/Phoniex/trial/blockscout/_build/dev/lib/prometheus_process_collector/priv/prometheus_process_collector: \'The specified module could not be found.\''}}

2022-04-14T00:09:09.749 application=que [info] [Que] Booting Que
2022-04-14T00:09:09.749 application=que [info] [Que] Booting Server Supervisor for Workers
2022-04-14T00:09:11.591 [error] GenServer Explorer.Counters.AddressesCounter terminating
** (Postgrex.Error) ERROR 42P01 (undefined_table) relation "addresses" does not exist

    query: SELECT COUNT(*) FROM "addresses" AS a0
    (ecto_sql 3.7.1) lib/ecto/adapters/sql.ex:760: Ecto.Adapters.SQL.raise_sql_call_error/1
    (ecto_sql 3.7.1) lib/ecto/adapters/sql.ex:693: Ecto.Adapters.SQL.execute/5
    (ecto 3.7.1) lib/ecto/repo/queryable.ex:219: Ecto.Repo.Queryable.execute/4
    (ecto 3.7.1) lib/ecto/repo/queryable.ex:19: Ecto.Repo.Queryable.all/3
    (ecto 3.7.1) lib/ecto/repo/queryable.ex:146: Ecto.Repo.Queryable.one/3
    (explorer 0.0.1) lib/explorer/counters/addresses_counter.ex:107: Explorer.Counters.AddressesCounter.consolidate/0
    (explorer 0.0.1) lib/explorer/counters/addresses_counter.ex:73: Explorer.Counters.AddressesCounter.handle_continue/2
    (stdlib 3.16.1) gen_server.erl:695: :gen_server.try_dispatch/4
    (stdlib 3.16.1) gen_server.erl:437: :gen_server.loop/7
    (stdlib 3.16.1) proc_lib.erl:226: :proc_lib.init_p_do_apply/3
Last message: {:continue, :ok}
State: %{consolidate?: true}
2022-04-14T00:09:12.701 [info] Application explorer exited: Explorer.Application.start(:normal, []) returned an error: shutdown: failed to start child: Explorer.Counters.AverageBlockTime
    ** (EXIT) an exception was raised:
        ** (Postgrex.Error) ERROR 42P01 (undefined_table) relation "blocks" does not exist

    query: SELECT b0."number", b0."timestamp" FROM "blocks" AS b0 WHERE (b0."consensus" = TRUE) ORDER BY b0."number" DESC LIMIT 100 OFFSET 100
            (ecto_sql 3.7.1) lib/ecto/adapters/sql.ex:760: Ecto.Adapters.SQL.raise_sql_call_error/1
            (ecto_sql 3.7.1) lib/ecto/adapters/sql.ex:693: Ecto.Adapters.SQL.execute/5
            (ecto 3.7.1) lib/ecto/repo/queryable.ex:219: Ecto.Repo.Queryable.execute/4
            (ecto 3.7.1) lib/ecto/repo/queryable.ex:19: Ecto.Repo.Queryable.all/3
            (explorer 0.0.1) lib/explorer/counters/average_block_time.ex:83: Explorer.Counters.AverageBlockTime.refresh_timestamps/0
            (explorer 0.0.1) lib/explorer/counters/average_block_time.ex:45: Explorer.Counters.AverageBlockTime.init/1
            (stdlib 3.16.1) gen_server.erl:423: :gen_server.init_it/2
            (stdlib 3.16.1) gen_server.erl:390: :gen_server.init_it/6
            (stdlib 3.16.1) proc_lib.erl:226: :proc_lib.init_p_do_apply/3
2022-04-14T00:09:12.725 [info] Application con_cache exited: :stopped
2022-04-14T00:09:12.734 [info] Application spandex_ecto exited: :stopped
2022-04-14T00:09:12.739 [info] Application que exited: :stopped
2022-04-14T00:09:12.739 [info] Application ex_utils exited: :stopped
2022-04-14T00:09:12.739 [info] Application memento exited: :stopped
2022-04-14T00:09:12.926 [info] Application mnesia exited: :stopped
2022-04-14T00:09:12.930 [info] Application plug_cowboy exited: :stopped
2022-04-14T00:09:12.930 [info] Application cowboy_telemetry exited: :stopped
2022-04-14T00:09:12.930 [info] Application prometheus_ecto exited: :stopped
2022-04-14T00:09:12.930 [info] Application prometheus_ex exited: :stopped
2022-04-14T00:09:12.934 [info] Application prometheus exited: :stopped
2022-04-14T00:09:12.934 [info] Application quantile_estimator exited: :stopped
2022-04-14T00:09:12.938 [info] Application postgrex exited: :stopped
2022-04-14T00:09:12.938 [info] Application nimble_csv exited: :stopped
2022-04-14T00:09:12.938 [info] Application poison exited: :stopped
2022-04-14T00:09:12.938 [info] Application math exited: :stopped
2022-04-14T00:09:12.941 [info] Application ecto_sql exited: :stopped
2022-04-14T00:09:12.944 [info] Application db_connection exited: :stopped
2022-04-14T00:09:12.944 [info] Application connection exited: :stopped
2022-04-14T00:09:12.948 [info] Application ecto exited: :stopped
2022-04-14T00:09:12.948 [info] Application dataloader exited: :stopped
2022-04-14T00:09:12.948 [info] Application comeonin exited: :stopped
2022-04-14T00:09:12.951 [info] Application briefly exited: :stopped
2022-04-14T00:09:12.951 [info] Application bcrypt_elixir exited: :stopped
2022-04-14T00:09:12.952 [info] Application tesla exited: :stopped
** (Mix) Could not start application explorer: Explorer.Application.start(:normal, []) returned an error: shutdown: failed to start child: Explorer.Counters.AverageBlockTime
    ** (EXIT) an exception was raised:
        ** (Postgrex.Error) ERROR 42P01 (undefined_table) relation "blocks" does not exist

    query: SELECT b0."number", b0."timestamp" FROM "blocks" AS b0 WHERE (b0."consensus" = TRUE) ORDER BY b0."number" DESC LIMIT 100 OFFSET 100
            (ecto_sql 3.7.1) lib/ecto/adapters/sql.ex:760: Ecto.Adapters.SQL.raise_sql_call_error/1
            (ecto_sql 3.7.1) lib/ecto/adapters/sql.ex:693: Ecto.Adapters.SQL.execute/5
            (ecto 3.7.1) lib/ecto/repo/queryable.ex:219: Ecto.Repo.Queryable.execute/4
            (ecto 3.7.1) lib/ecto/repo/queryable.ex:19: Ecto.Repo.Queryable.all/3
            (explorer 0.0.1) lib/explorer/counters/average_block_time.ex:83: Explorer.Counters.AverageBlockTime.refresh_timestamps/0
            (explorer 0.0.1) lib/explorer/counters/average_block_time.ex:45: Explorer.Counters.AverageBlockTime.init/1
            (stdlib 3.16.1) gen_server.erl:423: :gen_server.init_it/2
            (stdlib 3.16.1) gen_server.erl:390: :gen_server.init_it/6
            (stdlib 3.16.1) proc_lib.erl:226: :proc_lib.init_p_do_apply/3
2022-04-14T00:09:12.957 [info] Application runtime_tools exited: :stopped

**Comment by nikitosing** [comment]
@soumen29121997 in windows it is not supported to write mix commands in one line, separated by comma like you wrote:
`mix do ecto.create, ecto.migrate`, you need to run these command one by one:
`mix do ecto.create` 
`mix do ecto.migrate`

**Comment by nikitosing** [comment]
@soumen29121997 you just did not ran migrations

**Comment by soumen29121997** [comment]
@nikitosing all the problem is solved but when i run mix phx.server this thing just looping around


** (FunctionClauseError) no function clause matching in Indexer.Block.Catchup.BoundIntervalSupervisor.handle_info/2
    (indexer 0.1.0) lib/indexer/block/catchup/bound_interval_supervisor.ex:181: Indexer.Block.Catchup.BoundIntervalSupervisor.handle_info({:DOWN, #Reference<0.3245056956.3978035203.102346>, :process, #PID<0.3996.0>, :normal}, %Indexer.Block.Catchup.BoundIntervalSupervisor{bound_interval: %Indexer.BoundInterval{current: 2500, maximum: 25000, minimum: 2500}, fetcher: %Indexer.Block.Catchup.Fetcher{block_fetcher: %Indexer.Block.Fetcher{broadcast: :catchup, callback_module: Indexer.Block.Catchup.Fetcher, json_rpc_named_arguments: [transport: EthereumJSONRPC.HTTP, transport_options: [http: EthereumJSONRPC.HTTP.HTTPoison, url: "http://localhost:7545", http_options: [recv_timeout: 60000, timeout: 60000, hackney: [pool: :ethereum_jsonrpc]]], variant: EthereumJSONRPC.Ganache], receipts_batch_size: 250, receipts_concurrency: 10}, blocks_batch_size: 10, blocks_concurrency: 10, memory_monitor: Indexer.Memory.Monitor}, memory_monitor: nil, task: %Task{owner: #PID<0.3916.0>, pid: #PID<0.4067.0>, ref: #Reference<0.3245056956.3978035204.74314>}})
    (stdlib 3.16.1) gen_server.erl:695: :gen_server.try_dispatch/4
    (stdlib 3.16.1) gen_server.erl:771: :gen_server.handle_msg/6
    (stdlib 3.16.1) proc_lib.erl:226: :proc_lib.init_p_do_apply/3
Last message: {:DOWN, #Reference<0.3245056956.3978035203.102346>, :process, #PID<0.3996.0>, :normal}
State: %Indexer.Block.Catchup.BoundIntervalSupervisor{bound_interval: %Indexer.BoundInterval{current: 2500, maximum: 25000, minimum: 2500}, fetcher: %Indexer.Block.Catchup.Fetcher{block_fetcher: %Indexer.Block.Fetcher{broadcast: :catchup, callback_module: Indexer.Block.Catchup.Fetcher, json_rpc_named_arguments: [transport: EthereumJSONRPC.HTTP, transport_options: [http: EthereumJSONRPC.HTTP.HTTPoison, url: "http://localhost:7545", http_options: [recv_timeout: 60000, timeout: 60000, hackney: [pool: :ethereum_jsonrpc]]], variant: EthereumJSONRPC.Ganache], receipts_batch_size: 250, receipts_concurrency: 10}, blocks_batch_size: 10, blocks_concurrency: 10, memory_monitor: Indexer.Memory.Monitor}, memory_monitor: nil, task: %Task{owner: #PID<0.3916.0>, pid: #PID<0.4067.0>, ref: #Reference<0.3245056956.3978035204.74314>}}
2022-04-14T00:46:04.913 application=indexer fetcher=block_catchup [error] Catchup index stream exited because the archive node endpoint at http://localhost:7545 is unavailable. Restarting
2022-04-14T00:46:04.913 application=indexer fetcher=block_catchup [error] Catchup index stream exited with reason (:normal). Restarting

**Comment by nikitosing** [comment]
@soumen29121997 the problem in your eth node

**Comment by soumen29121997** [comment]
@nikitosing can you please suggest me how should I solved this...??

**Comment by nikitosing** [comment]
@soumen29121997 what do you use? geth/ganache/other? which env variables did you set?

**Comment by soumen29121997** [comment]
@nikitosing 

  if is_nil(System.get_env("ETHEREUM_JSONRPC_VARIANT")) do
    "ganache"
  else
    System.get_env("ETHEREUM_JSONRPC_VARIANT")
    |> String.split(".")
    |> List.last()
    |> String.downcase()
  end

**Comment by nikitosing** [comment]
@soumen29121997 what is it? I asked about your set of environment variables

**Comment by soumen29121997** [comment]
@nikitosing sorry i misunderstood the point here is the environment variables 


Name                           Value
----                           -----
ALLUSERSPROFILE                C:\ProgramData
APPDATA                        C:\Users\user\AppData\Roaming
ChocolateyInstall              C:\ProgramData\chocolatey
ChocolateyLastPathUpdate       132943197174322177
CommonProgramFiles             C:\Program Files\Common Files
CommonProgramFiles(x86)        C:\Program Files (x86)\Common Files
CommonProgramW6432             C:\Program Files\Common Files
COMPUTERNAME                   LAPTOP-I3JO3QJR
ComSpec                        C:\WINDOWS\system32\cmd.exe
DriverData                     C:\Windows\System32\Drivers\DriverData
FPS_BROWSER_APP_PROFILE_STRING Internet Explorer
FPS_BROWSER_USER_PROFILE_ST... Default
HOMEDRIVE                      C:
HOMEPATH                       \Users\user
LOCALAPPDATA                   C:\Users\user\AppData\Local
LOGONSERVER                    \\LAPTOP-I3JO3QJR
NUMBER_OF_PROCESSORS           4
OneDrive                       C:\Users\user\OneDrive
OneDriveConsumer               C:\Users\user\OneDrive
OS                             Windows_NT
Path                           C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPo...
PATHEXT                        .COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC;.CPL
PROCESSOR_ARCHITECTURE         AMD64
PROCESSOR_IDENTIFIER           AMD64 Family 23 Model 24 Stepping 1, AuthenticAMD
PROCESSOR_LEVEL                23
PROCESSOR_REVISION             1801
PROG27B48B2C054                1
ProgramData                    C:\ProgramData
ProgramFiles                   C:\Program Files
ProgramFiles(x86)              C:\Program Files (x86)
ProgramW6432                   C:\Program Files
PSModulePath                   C:\Users\user\Documents\WindowsPowerShell\Modules;C:\Program Files\WindowsPowerShell\...
PUBLIC                         C:\Users\Public
SESSIONNAME                    Console
SystemDrive                    C:
SystemRoot                     C:\WINDOWS
TEMP                           C:\Users\user\AppData\Local\Temp
TMP                            C:\Users\user\AppData\Local\Temp
USERDOMAIN                     LAPTOP-I3JO3QJR
USERDOMAIN_ROAMINGPROFILE      LAPTOP-I3JO3QJR
USERNAME                       Soumen
USERPROFILE                    C:\Users\user
VS120COMNTOOLS                 F:\visual studio 2013\Common7\Tools\
VS160PROCOMNTOOLS              C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\Common7\Tools\
windir                         C:\WINDOWS

**Comment by nikitosing** [comment]
@soumen29121997 you did not provide nor `ETHEREUM_JSONRPC_HTTP_URL` `ETHEREUM_JSONRPC_TRACE_URL`

**Comment by soumen29121997** [comment]
![ss1](https://user-images.githubusercontent.com/94948837/163384791-0073f153-51af-402b-836f-a8c13aef82ca.jpg)
@nikitosing  i set the variable still i got that error

**Comment by soumen29121997** [comment]
@nikitosing all the problem is solved ... thank you so much... 
I just ask you one thing that every time when i open my system why i have to set database url?

**Comment by nikitosing** [comment]
@soumen29121997 because when you use `set ENV_VAR=VALUE` it set env only in current cmd session. You can read more via google

**Comment by soumen29121997** [comment]
thank you for helping me out @nikitosing....
