### ISSUE TITLE
Blockscout fails to get NFT (ERC721) name.

### ISSUE THREAD

**Issue by xrpdevs** [blockscout/blockscout#5467]
If I try to mint an NFT from more than one contract in a single transaction, only one of the NFT's name & symbol is shown in the explorer.

The way the contract works is, user mints a token, and in the minting function, the minting function in a second contract is called using an interface{}

Result: Both tokens *are* visible on blockscout, but blockscout only gets the name / symbol of the second token. The first token is named with random hex digits.

Expected: both tokens have correct information..

**Comment by vbaranov** [comment]
@xrpdevs do you have any public link to those tokens, affected by the issue?
