### ISSUE TITLE
Balance not increasing in account section

### ISSUE THREAD

**Issue by ajaydoyenhub** [blockscout/blockscout#5468]
I have created three PoW ETH chains and they are connected to each other. I'm running the miner on each node. My Blockscout Explorer is connected with 3rd one.
Now the issue is that after Blockscout connection with 3rd node it's not mining new coin. When I disconnect It again starts mining the coin. 

This issue is coming after when we connect multiple nodes for a single node it's working fine.

### Environment

* Elixir & Erlang/OTP versions (`elixir -version`): 1.13 & 24
* Operating System: Linux
* Blockscout Version/branch: latest github branch

### Expected behavior

I want to know why my node stopped minting coins after blockscout connected with the node. Why it's mining for running alone nodes, not multiply connected networks.

### Actual behavior

Right now my network has multiple(3) connections and blockscout explorer is connected with 3rd one but after connecting mining stop for 3rd network.

**Comment by vbaranov** [comment]
@ajaydoyenhub it sound like a node misconfiguration. Blockscout cannot influence on starting/stoppiong of mining on the node.

**Comment by ajaydoyenhub** [comment]
@vbaranov, Actually It's working fine with a single network, but after I connect 3 networks and then connect Blockscout with any of them then it stops mining for that particular network other networks are continuously mining.

I also tried disconnecting explorer from the network and it start mining again.

**Comment by ajaydoyenhub** [comment]
@vbaranov , Please help me out from this

**Comment by vbaranov** [comment]
@ajaydoyenhub you shouldn't run Blockscout on mining node. In addition to mining node, setup also RPC node in archive mode, which Blockscout will utilize. The required parameters for the archive node are described here https://docs.blockscout.com/for-developers/information-and-settings/client-settings-parity-geth-ganache#geth-client
