### ISSUE TITLE
blockscout cannot show ERC721 token on tokens page

### ISSUE THREAD

**Issue by masayil** [blockscout/blockscout#5471]
https://testnetscan.ankr.com/  This is my website. ERC721 Contract Address : 0xBedb5e825989B8ef4B195bfC3A9196eEC35Beae4
blockscout cannot show ERC721 token on tokens page . But I can get results in the search box on the home page
![image](https://user-images.githubusercontent.com/65291464/163711118-1b7328e9-455a-46e1-a899-c78172766dd3.png)

![image](https://user-images.githubusercontent.com/65291464/163711401-ba277489-cbd7-4d59-9741-3df37892d296.png)

![451a9e7a77dfe5c910b2fafc1cd76cb](https://user-images.githubusercontent.com/65291464/163836221-9e0d0e4c-0b38-4e82-92ec-f2f4385a3799.png)

**Comment by vbaranov** [comment]
@masayil Blockscout displays only tokens with positive token_supply on Top tokens page. Here is the related condition in the query to get those tokens https://github.com/blockscout/blockscout/blob/6a918892f65ac482972df2e7551020762270aa4f/apps/explorer/lib/explorer/chain.ex#L2286.
