### ISSUE TITLE
Astar (EVM): <Issue Title>

### ISSUE THREAD

**Issue by diolhomme** [blockscout/blockscout#5472]
Hi Through Metamask, the USDT of Asta Network was accidentally transmitted to Binance BSC Network USDT. I asked Binance, but it is difficult to recover because I couldn't find the transaction ID.
I wonder if there is a way to recover the funds.
Please help me
![20220418_172407_1](https://user-images.githubusercontent.com/103924730/163780625-cc19aa40-b494-4cbe-b8c3-3e70a5599284.png)
.

**Comment by vbaranov** [comment]
Only exchange could help with this.

**Comment by diolhomme** [comment]
> 교환만이 이를 도울 수 있습니다.

What kind of exchange are you talking about?
