### ISSUE TITLE
Input decoded

### ISSUE THREAD

**Issue by Keystarmusic** [blockscout/blockscout#5474]
*Describe your issue here.*
I think I decided input ,it's become on 2 raws but what to do after that

### Environment
* Elixir Version: 1.12.3
* Erlang Version: 24
* BlockScout Version: v4.1.2-beta

* User Agent: `Mozilla/5.0 (Linux; Android 11; SM-A226B) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/93.0.4577.62 Mobile Safari/537.36`

### Steps to reproduce

*Tell us how to reproduce this issue. If possible, push up a branch to your fork with a regression test we can run to reproduce locally.*

### Expected Behaviour

*Tell us what should happen.*

### Actual Behaviour

*Tell us what happens instead.*

**Comment by vbaranov** [comment]
@Keystarmusic  Could you elaborate more on what issue do you have? Any screenshots describing the problem?

**Comment by Keystarmusic** [comment]
This is my problem faild to decode input.
I think I decode it from here but still no effect.


Sent from Yahoo Mail on Android

**Comment by vbaranov** [comment]
@Keystarmusic can you attach screenshot? can you provide link to the smart-contract? Why do you expect that the input should be decoded?

**Comment by Keystarmusic** [comment]
This is hash 0x7bb2a78f60ab2e13254d7e592ff7d12a0d724ca2daf30ac92be792a1fa3ba18d
And this is contract 0x07955be2967b655cf52751fce7ccc8c61ea594e2   .  On etherscan where is see more when tap on it pop up the input and there's option decode that's why I think it's fan be decoded from there.
Sent from Yahoo Mail on Android 
 
  On пн, апр 18, 2022 at 20:34, Victor ***@***.***> wrote:   


@Keystarmusic can you attach screenshot? can you provide link to the smart-contract? Why do you expect that the input should be decoded?

**Comment by Keystarmusic** [comment]
See it on blocscout

Sent from Yahoo Mail on Android 
 
  On пн, апр 18, 2022 at 20:38, David ***@***.***> wrote:   This is hash 0x7bb2a78f60ab2e13254d7e592ff7d12a0d724ca2daf30ac92be792a1fa3ba18d
And this is contract 0x07955be2967b655cf52751fce7ccc8c61ea594e2   .  On etherscan where is see more when tap on it pop up the input and there's option decode that's why I think it's fan be decoded from there.
Sent from Yahoo Mail on Android 
 
  On пн, апр 18, 2022 at 20:34, Victor ***@***.***> wrote:   


@Keystarmusic can you attach screenshot? can you provide link to the smart-contract? Why do you expect that the input should be decoded?

**Comment by vbaranov** [comment]
https://blockscout.com/eth/mainnet/tx/0x7bb2a78f60ab2e13254d7e592ff7d12a0d724ca2daf30ac92be792a1fa3ba18d/token-transfers

proxy and implementation smart-contracts are verified with which interaction happens

<img width="372" alt="Screenshot 2022-04-18 at 21 12 19" src="https://user-images.githubusercontent.com/4341812/163853973-2a7c83ab-1b6a-451b-9ea0-3107b81821cc.png">

cc @nikitosing

**Comment by Keystarmusic** [comment]
You mean my wallet with interacting. That's the address 
0x6CFa7f1d57CDa56C53d341cf196E1B404eC0e2F0
Sent from Yahoo Mail on Android 
 
  On пн, апр 18, 2022 at 21:15, Victor ***@***.***> wrote:   


https://blockscout.com/eth/mainnet/tx/0x7bb2a78f60ab2e13254d7e592ff7d12a0d724ca2daf30ac92be792a1fa3ba18d/token-transfers

proxy and implementation smart-contracts are verified with which interaction happens



cc @nikitosing

**Comment by Keystarmusic** [comment]
You mean verification which I made? It's was first one on list I don't remember.

Sent from Yahoo Mail on Android 
 
  On пн, апр 18, 2022 at 21:19, David ***@***.***> wrote:   You mean my wallet with interacting. That's the address 
0x6CFa7f1d57CDa56C53d341cf196E1B404eC0e2F0
Sent from Yahoo Mail on Android 
 
  On пн, апр 18, 2022 at 21:15, Victor ***@***.***> wrote:   


https://blockscout.com/eth/mainnet/tx/0x7bb2a78f60ab2e13254d7e592ff7d12a0d724ca2daf30ac92be792a1fa3ba18d/token-transfers

proxy and implementation smart-contracts are verified with which interaction happens



cc @nikitosing

**Comment by Keystarmusic** [comment]
I think it was solidity single file

Sent from Yahoo Mail on Android 
 
  On пн, апр 18, 2022 at 21:38, David ***@***.***> wrote:   You mean verification which I made? It's was first one on list I don't remember.

Sent from Yahoo Mail on Android 
 
  On пн, апр 18, 2022 at 21:19, David ***@***.***> wrote:   You mean my wallet with interacting. That's the address 
0x6CFa7f1d57CDa56C53d341cf196E1B404eC0e2F0
Sent from Yahoo Mail on Android 
 
  On пн, апр 18, 2022 at 21:15, Victor ***@***.***> wrote:   


https://blockscout.com/eth/mainnet/tx/0x7bb2a78f60ab2e13254d7e592ff7d12a0d724ca2daf30ac92be792a1fa3ba18d/token-transfers

proxy and implementation smart-contracts are verified with which interaction happens



cc @nikitosing

**Comment by Keystarmusic** [comment]
This is another bridge I made I think with same contract 
0x4aa08d1ea25bc5424a303440c720168b214b3c19594b76436ae269bb9042d9a4
Sent from Yahoo Mail on Android 
 
  On пн, апр 18, 2022 at 22:00, David ***@***.***> wrote:   No I think it was solidity Jason input

Sent from Yahoo Mail on Android 
 
  On пн, апр 18, 2022 at 21:53, David ***@***.***> wrote:   I think it was solidity single file

Sent from Yahoo Mail on Android 
 
  On пн, апр 18, 2022 at 21:38, David ***@***.***> wrote:   You mean verification which I made? It's was first one on list I don't remember.

Sent from Yahoo Mail on Android 
 
  On пн, апр 18, 2022 at 21:19, David ***@***.***> wrote:   You mean my wallet with interacting. That's the address 
0x6CFa7f1d57CDa56C53d341cf196E1B404eC0e2F0
Sent from Yahoo Mail on Android 
 
  On пн, апр 18, 2022 at 21:15, Victor ***@***.***> wrote:   


https://blockscout.com/eth/mainnet/tx/0x7bb2a78f60ab2e13254d7e592ff7d12a0d724ca2daf30ac92be792a1fa3ba18d/token-transfers

proxy and implementation smart-contracts are verified with which interaction happens



cc @nikitosing

**Comment by Keystarmusic** [comment]
Please help me

Sent from Yahoo Mail on Android 
 
  On пн, апр 18, 2022 at 23:16, David ***@***.***> wrote:   This is another bridge I made I think with same contract 
0x4aa08d1ea25bc5424a303440c720168b214b3c19594b76436ae269bb9042d9a4
Sent from Yahoo Mail on Android 
 
  On пн, апр 18, 2022 at 22:00, David ***@***.***> wrote:   No I think it was solidity Jason input

Sent from Yahoo Mail on Android 
 
  On пн, апр 18, 2022 at 21:53, David ***@***.***> wrote:   I think it was solidity single file

Sent from Yahoo Mail on Android 
 
  On пн, апр 18, 2022 at 21:38, David ***@***.***> wrote:   You mean verification which I made? It's was first one on list I don't remember.

Sent from Yahoo Mail on Android 
 
  On пн, апр 18, 2022 at 21:19, David ***@***.***> wrote:   You mean my wallet with interacting. That's the address 
0x6CFa7f1d57CDa56C53d341cf196E1B404eC0e2F0
Sent from Yahoo Mail on Android 
 
  On пн, апр 18, 2022 at 21:15, Victor ***@***.***> wrote:   


https://blockscout.com/eth/mainnet/tx/0x7bb2a78f60ab2e13254d7e592ff7d12a0d724ca2daf30ac92be792a1fa3ba18d/token-transfers

proxy and implementation smart-contracts are verified with which interaction happens



cc @nikitosing

**Comment by Keystarmusic** [comment]
Would you help me

Sent from Yahoo Mail on Android 
 
  On вт, апр 19, 2022 at 0:21, David ***@***.***> wrote:   Please help me

Sent from Yahoo Mail on Android 
 
  On пн, апр 18, 2022 at 23:16, David ***@***.***> wrote:   This is another bridge I made I think with same contract 
0x4aa08d1ea25bc5424a303440c720168b214b3c19594b76436ae269bb9042d9a4
Sent from Yahoo Mail on Android 
 
  On пн, апр 18, 2022 at 22:00, David ***@***.***> wrote:   No I think it was solidity Jason input

Sent from Yahoo Mail on Android 
 
  On пн, апр 18, 2022 at 21:53, David ***@***.***> wrote:   I think it was solidity single file

Sent from Yahoo Mail on Android 
 
  On пн, апр 18, 2022 at 21:38, David ***@***.***> wrote:   You mean verification which I made? It's was first one on list I don't remember.

Sent from Yahoo Mail on Android 
 
  On пн, апр 18, 2022 at 21:19, David ***@***.***> wrote:   You mean my wallet with interacting. That's the address 
0x6CFa7f1d57CDa56C53d341cf196E1B404eC0e2F0
Sent from Yahoo Mail on Android 
 
  On пн, апр 18, 2022 at 21:15, Victor ***@***.***> wrote:   


https://blockscout.com/eth/mainnet/tx/0x7bb2a78f60ab2e13254d7e592ff7d12a0d724ca2daf30ac92be792a1fa3ba18d/token-transfers

proxy and implementation smart-contracts are verified with which interaction happens



cc @nikitosing

**Comment by Keystarmusic** [comment]
It was solidity Jason verification ok

Sent from Yahoo Mail on Android 
 
  On вт, апр 19, 2022 at 17:43, David ***@***.***> wrote:   Would you help me

Sent from Yahoo Mail on Android 
 
  On вт, апр 19, 2022 at 0:21, David ***@***.***> wrote:   Please help me

Sent from Yahoo Mail on Android 
 
  On пн, апр 18, 2022 at 23:16, David ***@***.***> wrote:   This is another bridge I made I think with same contract 
0x4aa08d1ea25bc5424a303440c720168b214b3c19594b76436ae269bb9042d9a4
Sent from Yahoo Mail on Android 
 
  On пн, апр 18, 2022 at 22:00, David ***@***.***> wrote:   No I think it was solidity Jason input

Sent from Yahoo Mail on Android 
 
  On пн, апр 18, 2022 at 21:53, David ***@***.***> wrote:   I think it was solidity single file

Sent from Yahoo Mail on Android 
 
  On пн, апр 18, 2022 at 21:38, David ***@***.***> wrote:   You mean verification which I made? It's was first one on list I don't remember.

Sent from Yahoo Mail on Android 
 
  On пн, апр 18, 2022 at 21:19, David ***@***.***> wrote:   You mean my wallet with interacting. That's the address 
0x6CFa7f1d57CDa56C53d341cf196E1B404eC0e2F0
Sent from Yahoo Mail on Android 
 
  On пн, апр 18, 2022 at 21:15, Victor ***@***.***> wrote:   


https://blockscout.com/eth/mainnet/tx/0x7bb2a78f60ab2e13254d7e592ff7d12a0d724ca2daf30ac92be792a1fa3ba18d/token-transfers

proxy and implementation smart-contracts are verified with which interaction happens



cc @nikitosing

**Comment by nikitosing** [comment]
@vbaranov if we are talking about [this](https://blockscout.com/eth/mainnet/address/0x07955be2967B655Cf52751fCE7ccC8c61EA594e2/read-proxy) contract, I see that implementation is not verified

**Comment by vbaranov** [comment]
@nikitosing thanks, then we can close the issue. @Keystarmusic the event is not decoded because [implementation](https://blockscout.com/eth/mainnet/address/0x5F1E78f12025d8D05920134F4a64DDBDdaa924BE/transactions) of the contract, you interacted to, has not been verified.

**Comment by Keystarmusic** [comment]
I don't understand too much but I verified contract with solidity json

Sent from Yahoo Mail on Android 
 
  On чт, апр 21, 2022 at 11:46, Victor ***@***.***> wrote:   


@nikitosing thanks, then we can close the issue. @Keystarmusic the event is not decoded because implementation of the contract, you interacted to, has not been verified.

**Comment by Keystarmusic** [comment]
What me to do now

Sent from Yahoo Mail on Android 
 
  On пт, апр 22, 2022 at 0:23, David ***@***.***> wrote:   I don't understand too much but I verified contract with solidity json

Sent from Yahoo Mail on Android 
 
  On чт, апр 21, 2022 at 11:46, Victor ***@***.***> wrote:   


@nikitosing thanks, then we can close the issue. @Keystarmusic the event is not decoded because implementation of the contract, you interacted to, has not been verified.

**Comment by vbaranov** [comment]
@Keystarmusic verify implementation contract https://blockscout.com/eth/mainnet/address/0x5F1E78f12025d8D05920134F4a64DDBDdaa924BE/contracts

Verification instruction for the reference https://docs.blockscout.com/for-users/verifying-a-smart-contract

**Comment by Keystarmusic** [comment]
I think is verified what now

Sent from Yahoo Mail on Android 
 
  On пт, апр 22, 2022 at 12:23, Victor ***@***.***> wrote:   


@Keystarmusic verify implementation contract https://blockscout.com/eth/mainnet/address/0x5F1E78f12025d8D05920134F4a64DDBDdaa924BE/contracts

Verification instruction for the reference https://docs.blockscout.com/for-users/verifying-a-smart-contract

**Comment by vbaranov** [comment]
Awesome, I think you issue resolved
<img width="910" alt="Screenshot 2022-04-22 at 15 07 21" src="https://user-images.githubusercontent.com/4341812/164711290-7bef58c7-f0fc-4b04-aad6-e4e2d0d8be79.png">
.

**Comment by Keystarmusic** [comment]
Ok it's really cool but why I didn't receive tokens.

Sent from Yahoo Mail on Android 
 
  On пт, апр 22, 2022 at 15:07, Victor ***@***.***> wrote:   


Awesome, I think you issue resolved

**Comment by Keystarmusic** [comment]
I think I need to withdraw maybe but how

Sent from Yahoo Mail on Android 
 
  On пт, апр 22, 2022 at 18:29, David ***@***.***> wrote:   Ok it's really cool but why I didn't receive tokens.

Sent from Yahoo Mail on Android 
 
  On пт, апр 22, 2022 at 15:07, Victor ***@***.***> wrote:   


Awesome, I think you issue resolved

**Comment by Keystarmusic** [comment]
Maybe I need to make trancfer but how. Now I am on token minting

Sent from Yahoo Mail on Android 
 
  On пт, апр 22, 2022 at 19:06, David ***@***.***> wrote:   I think I need to withdraw maybe but how

Sent from Yahoo Mail on Android 
 
  On пт, апр 22, 2022 at 18:29, David ***@***.***> wrote:   Ok it's really cool but why I didn't receive tokens.

Sent from Yahoo Mail on Android 
 
  On пт, апр 22, 2022 at 15:07, Victor ***@***.***> wrote:   


Awesome, I think you issue resolved

**Comment by vbaranov** [comment]
@Keystarmusic The issue with input decoding resolved. Other issues are our of Blockscout team competence. Please stop spamming on issue or you will be blocked.

**Comment by Keystarmusic** [comment]
Hello the token contract not match to the original contract to ecop so its like a new different coin. I can't use it on exchanges. What to do.

Sent from Yahoo Mail on Android 
 
  On пт, апр 22, 2022 at 20:30, Victor ***@***.***> wrote:   


@Keystarmusic The issue with input decoding resolved. Other issues are our of Blockscout team competence. Please stop spamming on issue or you will be blocked.

**Comment by Keystarmusic** [comment]
I think I didn't finish my bridge yet

Sent from Yahoo Mail on Android 
 
  On сб, апр 23, 2022 at 8:02, David ***@***.***> wrote:   Hello the token contract not match to the original contract to ecop so its like a new different coin. I can't use it on exchanges. What to do.

Sent from Yahoo Mail on Android 
 
  On пт, апр 22, 2022 at 20:30, Victor ***@***.***> wrote:   


@Keystarmusic The issue with input decoding resolved. Other issues are our of Blockscout team competence. Please stop spamming on issue or you will be blocked.
