### ISSUE TITLE
No function clause matching in ABI.TypeEncoder.maybe_encode_unsigned

### ISSUE THREAD

**Issue by vbaranov** [blockscout/blockscout#5478]
https://blockscout.com/xdai/mainnet/address/0x1C232F01118CB8B424793ae03F870aa7D0ac7f77/read-contract

<img width="808" alt="Screenshot 2022-04-18 at 21 47 00" src="https://user-images.githubusercontent.com/4341812/163858697-0877f455-bb32-4e92-9de6-8901111b6713.png">

**Comment by bullsrace** [comment]
when you click on the copy icon, it copies the contract address in complete smallcaps 
![image](https://user-images.githubusercontent.com/42300159/163860917-46f3f5bb-5e3c-4497-81d5-1419efc00511.png)

**Comment by nikitosing** [comment]
@vbaranov the similar issue was opened before #4870
