### ISSUE TITLE
Database_url env variable not updating in windows os

### ISSUE THREAD

**Issue by soumen29121997** [blockscout/blockscout#5481]
@vbaranov please help me out
I set DATABASE_URL env variable in common-blockscout.env file but it's not working as expected. after set that env variable i also need to run set DATABASE_URL = postgres://postgres@database_default:5432/db everytime in m cmd

**Comment by vbaranov** [comment]
@soumen29121997 how do you run Blockscout? And how did you set DATABASE_URL common-blockscout.env?

**Comment by soumen29121997** [comment]
@vbaranov 

I run blockscout by run command mix phx.server in my command prompt

and i set DATABASE_URL like this in the image
![ss1](https://user-images.githubusercontent.com/94948837/164042669-0a40cbb9-516d-4282-997b-53254580ecf7.jpg)

**Comment by vbaranov** [comment]
I you want to use environment variables from common-blockscout.env, you should run with using of docker-compose orchestrator https://github.com/blockscout/blockscout/tree/master/docker-compose. `mix phx.server` doesn't use this file.
