### ISSUE TITLE
C1: CSV Not Downloading

### ISSUE THREAD

**Issue by reactxr** [blockscout/blockscout#5493]
*Describe your issue here.*

### Environment
* Elixir Version: 1.13.1
* Erlang Version: 24
* BlockScout Version: v4.1.2-beta

* User Agent: `Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.127 Safari/537.36`

### Steps to reproduce

Attempt to download CSV of transactions from any contract

### Expected Behaviour

CSV should download
### Actual Behaviour
Spinner keeps going and never excecutes

**Comment by reactxr** [comment]
This is for the Milkomeda explorer

**Comment by reactxr** [comment]
After further inspection, the issue is that the captcha check box is missing on the site.

**Comment by vbaranov** [comment]
Milkomeda instance of the explorer deployed by an external team and it is unsupported here. Probably explorer is not properly configured.
