### ISSUE TITLE
POA: How to get back may my POA coin

### ISSUE THREAD

**Issue by jepoyuser** [blockscout/blockscout#5494]
*POA Coin Recover.*

### Environment
* Elixir Version: 1.13.1
* Erlang Version: 24
* BlockScout Version: v4.1.2-beta

* User Agent: `Mozilla/5.0 (Linux; Android 10; CPH2179) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/94.0.4606.85 Mobile Safari/537.36`

### Steps to reproduce

*Tell us how to reproduce this issue. If possible, push up a branch to your fork with a regression test we can run to reproduce locally.*

### Expected Behaviour

*on 11 November 2021 my POA network coin was stake to WPOA thru Omni bridge via trust wallet i dont where my coin going plss help to recover.*

### Actual Behaviour

*Tell us what happens instead.*

**Comment by vbaranov** [comment]
Questions can be asked in the #poa channel on Discord https://discord.gg/mPJ9zkq
