### ISSUE TITLE
How to avoid indexing internal txs before certain block?

### ISSUE THREAD

**Issue by YakovL** [blockscout/blockscout#5499]
I'm having the "still indexing" issue (like described in #3844) but I know there's couple of specific reasons for it in my case (CLV parachain). One of them is, internal txs (tracing) were started being logged since certain block (referred as `specifiedBlock` below), so requesting `debug_traceTransaction` for some blocks causes an error. What I'm trying to do is to disable indexing of internal txs for those blocks.

The problem is, the only "solution" that I've found seems to be not consistent and may produce new issues, so I'll list my attempts and hope somebody helps with this (at least by clarifying the indexing process).

Basically, I can think of 2 approaches on how to prevent indexing internal txs:

1. don't mark pending ops with `fetch_internal_transactions` for those blocks
2. clear pending ops for those blocks when updating them

My first attempt was based on tracking the `INDEXER_DISABLE_INTERNAL_TRANSACTIONS_FETCHER` env option. In BS code, it affects the `InternalTransactionSupervisor.disabled?` function which is used in apps/indexer/lib/indexer/fetcher/internal_transaction.ex like this:

    @spec async_fetch([Block.block_number()]) :: :ok
    def async_fetch(block_numbers, timeout \\ 5000) when is_list(block_numbers) do
      if InternalTransactionSupervisor.disabled?() do
        :ok
      else
        BufferedTask.buffer(__MODULE__, block_numbers, timeout)
      end
    end

so I though may be disabling this will prevent the problem:

        BufferedTask.buffer(__MODULE__, Enum.filter(block_numbers, fn number -> number >= specifiedBlock end), timeout)

but that actually it didn't prevent pending ops from being created, just from trying to fetch internal txs (which suppressed the error I was getting in BS output), but the number of pending ops even increased: instead of just those for blocks with txs, that time I got pending ops for each block in with numbers `0..specifiedBlock-1`. Similarly, adding after

    def run(block_numbers, json_rpc_named_arguments) do
      unique_numbers = Enum.uniq(block_numbers)

(in internal_transaction.ex) another filter

      |> Enum.filter(fn number -> number >= specifiedBlock end)

didn't prevent extra pending ops from being created.

The procedure to clear the pending ops is rather complicated, so I'll address that later, but I've searched where pending ops are created and found `new_pending_operations` method in apps/explorer/lib/explorer/chain/import/runner/blocks.ex and noticed that all the blocks are getting the `fetch_internal_transactions` flag. I've modified it like this: before:

      sorted_pending_ops =
        nonconsensus_hashes
        |> MapSet.new()
        |> MapSet.union(MapSet.new(hashes))
        |> Enum.sort()
        |> Enum.map(fn hash ->
          %{block_hash: hash, fetch_internal_transactions: true} # let's try to make it true only for blocks after specifiedBlock
        end)

after:

      # ...
        |> Enum.map(fn hash ->
          query = from b in Block,
            where: b.hash == ^hash
          block = Explorer.Repo.one(query) # use get_by instead?
          block_number = block.number
          # presumably degrades performance: we should do this via single request instead of on per block
          %{block_hash: hash, fetch_internal_transactions: block_number >= specifiedBlock}
        end)

This resulted in "still indexing" banner getting removed (which is good), but pending ops for blocks `0..specifiedBlock-1` are still in DB and not cleared (which doesn't seem correct as there's nothing "pending" really and I expected those to be removed after some time). This is the closest attempt that I did so far.

I've also tried the "clear pending ops for those blocks when updating them [pending ops]" approach, but I got stuck in the code structure. As far as I understand, the `run` method in apps/explorer/lib/explorer/chain/import/runner/internal_transactions.ex describe the whole process analysing and updating pending ops due to internal txs updates. The question is, what else pending ops are supposed to mean (what else is "pending" if `fetch_internal_transactions` is `false`)? And what code gets rid of such pending ops?

**Comment by vbaranov** [comment]
@YakovL you can set a minimum block number in `TRACE_FIRST_BLOCK` environment variable. And Blockscout will not request JSON RPC methods for internal transactions and balances less than this block number.

**Comment by YakovL** [comment]
@vbaranov thanks for pointing! However, using `TRACE_FIRST_BLOCK` doesn't seem to provide the expected effect: (after wiping out the DB and restarting BS) we're still getting errors that the node returns when we try to send `debug_traceTransaction` to early blocks and also there are `pending_block_operations` for those blocks. Currently, I'm experiencing some infrastructure problems that prevent me from providing more detailed logs (BS output got polluted with `Watchpack Error (watcher): Error: EMFILE: too many open files, watch '/root/blockscout_reindex/apps/block_scout_web/assets/node_modules/phoenix'` for some reason) but once I fix them, I'll add as much new details as I can.

**Comment by vbaranov** [comment]
@YakovL what did you set in `ETHEREUM_JSONRPC_VARIANT` environment variable?

**Comment by YakovL** [comment]
It's `geth`

**Comment by vbaranov** [comment]
@YakovL thank you. That is why it doesn't work. This environment variable is ignored in case of `geth` Ethereum JSON RPC variant. I prepared a fix https://github.com/blockscout/blockscout/pull/5504. Would you try it and leave feedback?

**Comment by vbaranov** [comment]
@YakovL make sense. Can you take a look at this PR https://github.com/blockscout/blockscout/pull/5508. After implementing it, "Indexing ..." banner should gone, if internal transactions have been fetched for block height `TRACE_FIRST_BLOCK`

**Comment by YakovL** [comment]
@vbaranov right, this removes the banner indeed. What about pending ops? Having those for all first blocks (0..TRACE_FIRST_BLOCK-1) doesn't look like expected behavior.

**Comment by vbaranov** [comment]
@YakovL good catch. I prepared a PR https://github.com/blockscout/blockscout/pull/5513 for resoliving this. Can you try it on your end? This should prevent filling `pending_block_operations` table for block numbers less than `TRACE_FIRST_BLOCK `, if it is set.

**Comment by YakovL** [comment]
Yes, great, no more "unexpected" pending ops after reindexing! Looks like it's time to close the issue.
