### ISSUE TITLE
C1: <Issue Title>

### ISSUE THREAD

**Issue by VeganPoolOrg** [blockscout/blockscout#5500]
I cant swap milkADA for mad USDC. 

https://explorer-mainnet-cardano-evm.c1.milkomeda.com/tx/0x5c221a6daa16caaf850eff4d8cb87c45279eddbd5e1fc3d3a9c7a821a91103f5/internal-transactions

could someone help me please 

### Environment
* Elixir Version: 1.13.1
* Erlang Version: 24
* BlockScout Version: v4.1.2-beta

* User Agent: `Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.127 Safari/537.36`

### Steps to reproduce

*Tell us how to reproduce this issue. If possible, push up a branch to your fork with a regression test we can run to reproduce locally.*

### Expected Behaviour

*Tell us what should happen.*

### Actual Behaviour

*Tell us what happens instead.*

**Comment by vbaranov** [comment]
Milkomeda instance of the explorer deployed by an external team and it is unsupported here.
