### ISSUE TITLE
NFT base on erc721 of token media not show in explorer.

### ISSUE THREAD

**Issue by soobeencn** [blockscout/blockscout#5503]
### Environment

* Operating System: ubuntu20.04
* Blockscout Version/branch: master

### Steps to reproduce

I deployed a contract base on erc721 success, when I call mint method, one of my parameters is tokenURI: http://xxxxx.jpg, and call success.

### Actual behaviour

now blockscout explorer has expired the contract, and when I click tokenID, happend: 
![image](https://user-images.githubusercontent.com/46877223/165470138-8a9f5845-961e-46b3-a218-fc0decd97128.png)

### Question

so I don't know what happen, and reply of my request status is 200.

**Comment by soobeencn** [comment]
I solved it.

**Comment by youngqqcn** [comment]
@soobeencn  How to solve it?
