### ISSUE TITLE
Emerald Mainnet: <Rose tokens sent to wrong address>

### ISSUE THREAD

**Issue by vhchandu** [blockscout/blockscout#5509]
*Describe your issue here.*
I mistakenly sent Rose tokens from my Metamask to Kucoin ETH address. Can you reverse it?

### Environment
* Elixir Version: 1.12.3
* Erlang Version: 24
* BlockScout Version: 0.0.1

* User Agent: `Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.127 Safari/537.36`

### Steps to reproduce

*Tell us how to reproduce this issue. If possible, push up a branch to your fork with a regression test we can run to reproduce locally.*

### Expected Behaviour

*Tell us what should happen.*

### Actual Behaviour

*Tell us what happens instead.*

**Comment by vbaranov** [comment]
Emerald instance is unsupported here.
