### ISSUE TITLE
Docker non-root user: verifying doesn't work 

### ISSUE THREAD

**Issue by mfolnovic** [blockscout/blockscout#5510]
If you run docker image as non-root user, multiple things happen:

1. tzdata errors:
```
2022-04-27T21:07:19.192 [error] GenServer :tzdata_release_updater terminating
** (File.Error) could not write to file "/opt/app/_build/prod/lib/tzdata/priv/latest_remote_poll.txt": permission denied
```

2. while verifying:
```
** (File.Error) could not open "/opt/app/_build/prod/lib/explorer/priv/solc_compilers/v0.8.13+commit.abaa5c0e-tmp.js": permission denied
    (elixir 1.12.3) lib/file.ex:1445: File.open!/2
    (explorer 0.0.1) lib/explorer/smart_contract/solc_downloader.ex:57: Explorer.SmartContract.SolcDownloader.handle_call/3
```

```
2022-04-27T20:48:58.397 [error] Task #PID<0.1601.0> started from #PID<0.1600.0> terminating
** (MatchError) no match of right hand side value: {:no_tmp, ["/tmp", "/opt/app/tmp"]}
    (explorer 0.0.1) lib/explorer/smart_contract/solidity/code_compiler.ex:280: Explorer.SmartContract.Solidity.CodeCompiler.create_source_file/1
```

I've tried to hotfix it by extending image with:

```
RUN chmod -R 777 /opt/app/_build/prod/lib
RUN chmod -R 777 /opt/app/deps/tzdata/priv
RUN chmod -R 777 /opt/app/apps/explorer/priv
RUN chmod -R 777 /tmp
RUN mkdir /opt/app/tmp && chmod -R 777 /opt/app/tmp
```

but last two commands don't help with last error while verifying.

### Environment

* Operating System: Docker, Kubernetes, non-root user
* Blockscout Version/branch:  4.1.2

### Steps to reproduce

Run docker image as non-root user.

### Expected behaviour

While running docker image as non-root user, verifying contract should work.

### Actual behaviour

Verifying contract gives errors.

**Comment by mfolnovic** [comment]
@vbaranov sorry for pinging you, just wanted to check if you'd be interested to receive PR on this issue?

**Comment by vbaranov** [comment]
@mfolnovic yes, sure. Please, go ahead. We would love to review such PR.

**Comment by jessepinkman9900** [comment]
facing the same issue here! has this issue been solved?

**Comment by vbaranov** [comment]
Smart-contract verification is currently extracted into Rust microservice. You can read more about this and how integrate  https://docs.blockscout.com/for-developers/information-and-settings/smart-contract-verification. And aslo we provide comprehensive docker-compose configs, which include all microservices https://github.com/blockscout/blockscout/tree/master/docker-compose#readme. I ma closing this for now. Please, let me know, if the issue still present.
