### ISSUE TITLE
The page does not modify the custom symbol

### ISSUE THREAD

**Issue by zjb0807** [blockscout/blockscout#5512]
### Environment

* Blockscout Version/branch: 
master - 4c634650f0996a3163021ef84e9506fbebee769b

### Steps to reproduce

set env COIN=custom symbol

### Expected behaviour

custom symbol

### Actual behaviour
https://blockscout.moonbeam.network/address/0x6d6F646C43726f77646C6f610000000000000000/tokens
<img width="963" alt="image" src="https://user-images.githubusercontent.com/16496415/165663574-047cc203-034b-4014-bfdf-a28ca1ab3517.png">

**Comment by vbaranov** [comment]
@zjb0807 here is the instruction how to customize coin symbol https://docs.blockscout.com/for-developers/developer-faqs/how-can-i-customize-the-coin-symbol

**Comment by zjb0807** [comment]
@vbaranov Please open the link, you will see the problem.

**Comment by vbaranov** [comment]
@zjb0807 did you follow the instruction, I posted in the previous reply?

**Comment by zjb0807** [comment]
This link:
https://blockscout.moonbeam.network/address/0x6d6F646C43726f77646C6f610000000000000000/tokens

From the moonbeam, it has set the custom symbol

**Comment by vbaranov** [comment]
@zjb0807 Blockscout team does not manage Moonbeam instance. You should contact Moonbeam team directly and suggest them to follow that instruction in order to fix coin symbol.

**Comment by zjb0807** [comment]
master - https://github.com/blockscout/blockscout/commit/4c634650f0996a3163021ef84e9506fbebee769b

I had the same problem with the commit. This should be a bug

**Comment by vbaranov** [comment]
@zjb0807 what value do you you have for `msgid "Ether"` in .pot and .po source files?

**Comment by zjb0807** [comment]
https://github.com/blockscout/blockscout/blob/74658735326cca319d29a1958d11f47a0bc040b3/docker-compose/docker-compose.yml#L19-L23

I set the evn

**Comment by zjb0807** [comment]
Everything is normal, except here

**Comment by vbaranov** [comment]
@zjb0807 indeed, I reproduced the issue and fixed in this PR https://github.com/blockscout/blockscout/pull/5514. Could you try it?
