### ISSUE TITLE
Palm: <Issue Title>

### ISSUE THREAD

**Issue by Jmatthys96** [blockscout/blockscout#5525]
*Describe your issue here.*
I withdrew a 80 DAI awhile back and the transaction says complete but i have still not received any payment
### Environment
* Elixir Version: 1.12.3
* Erlang Version: 24
* BlockScout Version: 

* User Agent: `Mozilla/5.0 (iPhone; CPU iPhone OS 15_4_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/15.4 Mobile/15E148 Safari/604.1`

### Steps to reproduce

*Tell us how to reproduce this issue. If possible, push up a branch to your fork with a regression test we can run to reproduce locally.*

### Expected Behaviour

*Tell us what should happen.*

### Actual Behaviour

*Tell us what happens instead.*

**Comment by nikitosing** [comment]
This issue is out of Blockscout team competence
