### ISSUE TITLE
i Have done a pool RBTC/SYS and it dosen't completed 100%. Only a 35% of my money in the pool and the other part is lost

### ISSUE THREAD

**Issue by moreux** [blockscout/blockscout#5526]
*Describe your issue here.*

### Environment
* Elixir Version: 1.13.1
* Erlang Version: 24
* BlockScout Version: 

* User Agent: `Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.127 Safari/537.36`

### Steps to reproduce

*Tell us how to reproduce this issue. If possible, push up a branch to your fork with a regression test we can run to reproduce locally.*

### Expected Behaviour

*Tell us what should happen.*

### Actual Behaviour

*Tell us what happens instead.*

**Comment by vbaranov** [comment]
This is unrelated to Blockscout. I am closing this.
