### ISSUE TITLE
CUN: I sent my 2 CUN to my ETH Wallet since 4:30 and till now I haven't received incoming yet, please cancel the transaction g 

### ISSUE THREAD

**Issue by OnosChristo** [blockscout/blockscout#5530]
![Screenshot_20220504-230746](https://user-images.githubusercontent.com/103237943/166836412-ef1a6198-0f43-453b-877d-5deca22d6582.png)
![Screenshot_20220504-221113](https://user-images.githubusercontent.com/103237943/166836450-d53c8e5d-b4b7-4ef6-8581-8a2e2a03bcd4.png)
I send my 2 CUN to my ETH Wallet address but till now I haven't received incoming nor have I confirmed the transaction, please help me cancel the transaction please. 

### Environment
* Elixir Version: 1.11.1
* Erlang Version: 23
* BlockScout Version: 

* User Agent: `Mozilla/5.0 (Linux; Android 8.1.0; TECNO KB7 Build/O11019; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/100.0.4896.79 Mobile Safari/537.36`

### Steps to reproduce

*Tell us how to reproduce this issue. If possible, push up a branch to your fork with a regression test we can run to reproduce locally.*

### Expected Behaviour

*Tell us what should happen.* Please cancel the transactions please. 

### Actual Behavior. Unconfirmed to my wallet

*Tell us what happens instead.* The transaction shows Success and out, but I didn't received anything, you can see the screenshot below, so please cancel the transaction for me please I beg you.

**Comment by OnosChristo** [comment]
Please I haven't still received my CUN in my wallet yet, I need your help

**Comment by vbaranov** [comment]
Wrong place to ask

**Comment by OnosChristo** [comment]
Please help me revert my 2 CUN back to my Meta Mask wallet
