### ISSUE TITLE
this error i got when i run code on windows OS. can you please help me out how to fixed this error?

### ISSUE THREAD

**Issue by soumen29121997** [blockscout/blockscout#5537]
@vbaranov 

2022-05-05T23:01:52.635 [error] Task #PID<0.1953.0> started from Indexer.Block.Realtime.Fetcher terminating
** (UndefinedFunctionError) function :libsecp256k1.ecdsa_recover_compact/4 is undefined (module :libsecp256k1 is not available)
    (libsecp256k1 0.1.10) :libsecp256k1.ecdsa_recover_compact(<<132, 0, 45, 140, 126, 200, 209, 49, 212, 63, 224, 203, 97, 7, 226, 195, 238, 207, 180, 168, 145, 18, 218, 75, 184, 87, 243, 65, 181, 158, 219, 196>>, <<205, 203, 121, 158, 200, 227, 204, 131, 106, 142, 124, 47, 72, 58, 236, 195, 24, 160, 32, 44, 9, 43, 58, 60, 110, 246, 141, 86, 196, 131, 4, 208, 65, 8, 157, 64, 61, 193, 63, 188, 116, 139, 114, 255, 21, 61, 214, 161, 230, 176, ...>>, :uncompressed, 0)
    (indexer 0.1.0) lib/indexer/transform/blocks.ex:83: Indexer.Transform.Blocks.recover_pub_key/2
    (indexer 0.1.0) lib/indexer/transform/blocks/clique.ex:14: Indexer.Transform.Blocks.Clique.transform/1
    (elixir 1.12.2) lib/enum.ex:1582: Enum."-map/2-lists^map/1-0-"/2
    (indexer 0.1.0) lib/indexer/block/fetcher.ex:132: Indexer.Block.Fetcher.fetch_and_import_range/2
    (indexer 0.1.0) lib/indexer/block/realtime/fetcher.ex:292: Indexer.Block.Realtime.Fetcher.do_fetch_and_import_block/3
    (indexer 0.1.0) lib/indexer/logger.ex:14: Indexer.Logger.metadata/2
    (indexer 0.1.0) lib/indexer/block/realtime/fetcher.ex:275: Indexer.Block.Realtime.Fetcher.fetch_and_import_block/4
    (elixir 1.12.2) lib/task/supervised.ex:90: Task.Supervised.invoke_mfa/2
    (stdlib 3.16.1) proc_lib.erl:226: :proc_lib.init_p_do_apply/3
Function: &Indexer.Block.Realtime.Fetcher.fetch_and_import_block/3
    Args: [897907, %Indexer.Block.Fetcher{broadcast: :realtime, callback_module: Indexer.Block.Realtime.Fetcher, json_rpc_named_arguments: [transport: EthereumJSONRPC.HTTP, transport_options: [http: EthereumJSONRPC.HTTP.HTTPoison, url: "http://vdg-ledger-alb-1-779038680.us-east-2.elb.amazonaws.com", http_options: [recv_timeout: 60000, timeout: 60000, hackney: [pool: :ethereum_jsonrpc]]], variant: EthereumJSONRPC.Geth], receipts_batch_size: 250, receipts_concurrency: 10}, true]
2022-05-05T23:01:53.922 application=indexer fetcher=empty_blocks_to_refetch [info] Start sanitizing of empty blocks. Batch size is 100
2022-05-05T23:01:53.935 application=indexer fetcher=empty_blocks_to_refetch [info] Batch of empty blocks is sanitized
2022-05-05T23:02:03.498 [warn] The on_load function for module libsecp256k1 returned:
{:error,
 {:load_failed,
  'Failed to load NIF library e:/Phoniex/trial/blockscout/_build/dev/lib/libsecp256k1/priv/libsecp256k1_nif: \'The specified module could not be found.\''}}

**Comment by nikitosing** [comment]
@soumen29121997 you need somehow install `libsecp256k1` library. Try to google how to perform it on windows
