### ISSUE TITLE
There was an error compiling a provided contract: Invalid EVM version requested

### ISSUE THREAD

**Issue by knight2008** [blockscout/blockscout#5541]
*Describe your issue here.*

### Environment

* Elixir & Erlang/OTP versions (`elixir -version`):
* Operating System: Ubuntu 18.04
* Blockscout Version/branch:  4.1.1-beta

### Steps to reproduce
deploy with docker. 
cd blockscout/docker
make start

### Expected behaviour

*Tell us what should happen.*

### Actual behaviour

*Tell us what happens instead.*

after I start, I deployed a token with the code:
https://ropsten.etherscan.io/address/0x363d4a8b7c27103fec77df8f70f74a49c70f60de#code
but when I verified source code (select EVM version default), the backened show the following error.

2022-05-07T14:17:32.836 application=explorer [warn] There was an error compiling a provided contract: {:error, [%{"component" => "general", "formattedMessage" => "Invalid EVM version requested.", "message" => "Invalid EVM version requested.", "severity" => "error", "type" => "JSONError"}]}

should I install solc in my host?

**Comment by nikitosing** [comment]
@knight2008 it's just a warning, BlockScout automatically recompiles source code with different evm versions if user provided params was wrong. So, such warning sometimes appears it's ok. Was contract verified by the end?
