### ISSUE TITLE
Unlimited query causes blockscout to crash unexpectedly on large existing chains

### ISSUE THREAD

**Issue by tomw1808** [blockscout/blockscout#5544]
when trying to sync in large existing chains then blockscout crashes without any error message as this query returns a too large set of rows

https://github.com/blockscout/blockscout/blob/3d92bdee758fb8ec465220f466bd7602a22944b0/apps/explorer/lib/explorer/chain.ex#L3040

suggested fix would be to add a sane limit, for example:
```
   ...
        distinct: missing_range.number,
        limit: 100000
      )
```

**Comment by feld** [comment]
is this why my mainnet node keeps crashing?? I have just been ignoring it as I was too busy with $dayjob

**Comment by tomw1808** [comment]
Could be. I am not sure why nobody else is having this issue...

We have this problem because we run a l2 network at morpher with a 1s block time. There are 58 million blocks and the query would essentially return 58 million rows. It just crashes silently and postgres then errors out with an unexpected connection loss.

I am not 100% sure if that fixes it for your mainnet problem, but it definitely fixed it for us. I upped the limit to 500k blocks at a time, which seems to work fine.

I also upped the parallel workers and the amount of blocks fetched by the catchup process and can sync in about 3500 blocks per second from aws to my local machine where it runs in docker (compose with postgres). I will have our repo, together with some other tweaks, on our orgs' fork of blockscout. If you want, you can check it out. I am not sure if I have enough time to create PR's back to blockscout though, as I have to tweak quite a bit, also with the layout.

**Comment by tomw1808** [comment]
For completeness, this is the query postgres tells me that doesn't work:

```
SELECT DISTINCT ON (f1."number") f1."number" FROM "blocks" AS b0 RIGHT OUTER JOIN   (SELECT distinct b1.number FROM generate_series(($1)::integer, ($2)::integer) AS b1(number) WHERE NOT EXISTS
 (SELECT 1 FROM blocks b2 WHERE b2.number=b1.number AND b2.consensus))
AS f1 ON b0."number" = f1."number" ORDER BY f1."number"
```
