### ISSUE TITLE
Installing Mix dependencies and compiling on V4.1.3-beta doesn't work

### ISSUE THREAD

**Issue by piersandro** [blockscout/blockscout#5551]
We are trying to transfer our Quadrans Blockchain Explorer to a new server so I installed the new v4.1.3-beta (without touching anything) to a new VPS. After installing all the requirements and creating the new database I launched as always the step 4 of the manual deployment documentation but the installation halted.

### Environment

* Elixir & Erlang/OTP versions (`elixir -version`): Elixir 1.9.1 Erlang/OTP 22 [erts-10.6.4]
* Operating System: Ubuntu 20.04.4 LTS
* Blockscout Version/branch: v4.1.3-beta

### Steps to reproduce

Launch: `mix do deps.get, local.rebar --force, deps.compile`

### Expected behaviour

I expect that the script runs.

### Actual behaviour

The script halted after a few seconds with this message:

```
** (CompileError) config/config.exs:65: undefined function config_env/0
 (elixir) src/elixir_bitstring.erl:142: :elixir_bitstring.expand_expr/4
 (elixir) src/elixir_bitstring.erl:27: :elixir_bitstring.expand/8
 (elixir) src/elixir_bitstring.erl:20: :elixir_bitstring.expand/4
 (stdlib) lists.erl:1354: :lists.mapfoldl/3
 (elixir) expanding macro: Config.import_config/1
```

I tried with v4.1.2-beta and it runs perfectly.

We will temporarily move to 4.1.2.

**Comment by vbaranov** [comment]
@piersandro the problem is with the version of Elixir, that you use. `Elixir 1.9.1 Erlang/OTP 22 [erts-10.6.4]` is outdated. You should update to `elixir 1.13.4-otp-24`.

**Comment by piersandro** [comment]
Thank you, I used the official repository and upgraded my packages and now it works.

```
wget https://packages.erlang-solutions.com/erlang-solutions_2.0_all.deb && sudo dpkg -i erlang-solutions_2.0_all.deb
```

Thank you again.

**Comment by MaxTeiger** [comment]
> @piersandro the problem is with the version of Elixir, that you use. `Elixir 1.9.1 Erlang/OTP 22 [erts-10.6.4]` is outdated. You should update to `elixir 1.13.4-otp-24`.

How do you do that ? 
By following official [Elixir Doc](https://elixir-lang.org/install.html#gnulinux) I cannot install this version

Thank you
