### ISSUE TITLE
Ethereum Classic: can't export CSV?

### ISSUE THREAD

**Issue by cryptocore0** [blockscout/blockscout#5554]
Is anyone able to export CSV from a contract in Ethereum Classic network? Have tried disabling adblock, running from other browsers, incognito mode, setting a low date range (1d) but no success. If the website is in dark mode, nothing happens when I click Download. Light mode shows a loading wheel next to it that will keep spinning forever. Have been trying for some months now, I wonder if I'm missing something because the button is there but it doesn't work.

### Environment
* Elixir Version: 1.12.2
* Erlang Version: 24
* BlockScout Version: v4.1.1-beta

* User Agent: `Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/101.0.4951.54 Safari/537.36`

### Steps to reproduce

In Blockscout, search for Contracts Transactions and try downloading CSV by clicking the Download button at the bottom of the page.

### Expected Behaviour

A CSV file download within a couple seconds.

### Actual Behaviour

Nothing happens/keeps loading.

**Comment by vbaranov** [comment]
In order to configure CSV export, instance maintainer should set Google reCAPTCHA `RE_CAPTCHA_SECRET_KEY` and `RE_CAPTCHA_CLIENT_KEY` environment varaibles. cc @diega.
