### ISSUE TITLE
Unable to Verify UUPS proxy using OZ upgradeable plugin.

### ISSUE THREAD

**Issue by akshar** [blockscout/blockscout#5555]
After Deploying to a custom chain using the  OZ `contracts-upgradeable` & `hardhat-upgrades` plugin we were able to verify the implementation contract using standard JSON input. However, we tried verifying the proxy contract using standard json input / Flattened solidity files and we are having no luck. 

Is there verification support for UUPS proxy  ? If so, how would we go about verifying proxy contract using the blockscout UI. 

### Environment

* Elixir & Erlang/OTP versions (`elixir -version`):  1.13.4-otp-24 /  24.3.3
* Operating System: Ubuntu 20
* Blockscout Version/branch:  v4.1.3-beta

### Steps to reproduce
- Attempted to verify standard input json compiled using solidity 0.8.2 (hardhat compile).

### Expected behaviour
- It should verify the proxy

### Actual behaviour
- `There was an error validating your contract, please try again.`

**Comment by nikitosing** [comment]
@akshar How did you compose json file? Did you include all sources in json/flattened source code?

**Comment by akshar** [comment]
we included all the required dependency + actual contract in json file. @nikitosing 

sample json file (from hardhat compiled artifacts)
```
{
  "language": "Solidity",
  "sources": {
    "@openzeppelin/contracts/token/ERC20/IERC20.sol": {
      "content": "// SPDX-License-Identifier: MIT ..."
    },

    ...

    "contracts/tokens/TestToken.sol": {
      "content": "// SPDX-License-Identifier: MIT ..."
    },
  },
  "settings": {
    "optimizer": {
      "enabled": true,
      "runs": 200
    },
    "outputSelection": {
      "*": {
        "*": [
          "abi",
          "evm.bytecode",
          "evm.deployedBytecode",
          "evm.methodIdentifiers",
          "metadata",
          "storageLayout",
          "devdoc",
          "userdoc",
          "evm.gasEstimates"
        ],
        "": [
          "ast"
        ]
      }
    },
    "metadata": {
      "useLiteralContent": true
    }
  }
}
```

**Comment by nikitosing** [comment]
@akshar could you please try to repeat verification after applying [this commit](https://github.com/blockscout/blockscout/commit/cb61231b42bef2d7b95d9d4a29bbc94f8753f8c4). Or just use master branch

**Comment by akshar** [comment]
@nikitosing We tried with the latest changes and are still experiencing the same issue. Do you have steps for verifying UUPSProxy ?  What should be the name of contract with verifying the proxy ?

**Comment by nikitosing** [comment]
@akshar the name should match with deployed contract's name at address.
BlockScout is verifying such proxies without any diffculties. On Gnosis Chain you could find examples by `UUPSProxy` name: https://blockscout.com/xdai/mainnet/address/0x2dFe937cD98Ab92e59cF3139138f18c823a4efE7/contracts

**Comment by nikitosing** [comment]
@akshar Could you send link to contract sources + compiler params? And if it's possible to unverified contract

**Comment by rimrakhimov** [comment]
@akshar If problem occurred on some network running by us, you may try to verify the contract again. We applied new changes from [#97](https://github.com/blockscout/blockscout-rs/pull/97). Not sure that it would help, but who knows...

**Comment by nikitosing** [comment]
@akshar what is the status? Did new update of smart-contract verifier microservice help and we can close the issue or no?

**Comment by akshar** [comment]
hi @nikitosing ,

- we tried verifying the proxy at [0xc8940cCfDdaFd285030Fb2916776123fAc171dC6](https://explorer.toronto.sx.technology/address/0xc8940cCfDdaFd285030Fb2916776123fAc171dC6) and contract at [0x2b2b6bf46947aceaccd26c69da3683686873298e](https://explorer.toronto.sx.technology/address/0x2B2B6Bf46947acEaCCD26c69da3683686873298e) with no luck
- Flattened contract [here](https://pastebin.com/yyYu4RYV)

**Comment by nikitosing** [comment]
@akshar Is it your instance? Please take a look https://github.com/blockscout/blockscout/issues/6264#issuecomment-1280605349

**Comment by akshar** [comment]
@nikitosing thanks! will try running this

**Comment by ericlee42** [comment]
I have tested with smart-contract verifier microservice, it didn't help

**Comment by ericlee42** [comment]
<img width="669" alt="image" src="https://user-images.githubusercontent.com/92196970/210123704-63b6a582-99e4-4f84-bd03-037a907a4737.png">

hardhat-upgrade uses `verifyproxycontract`, blockscout doesn't support it, and etherscan has such api 

https://docs.etherscan.io/api-endpoints/contracts#verify-proxy-contract

**Comment by nikitosing** [comment]
@ericlee42 blockscout automatically links proxy contracts with implementations
