### ISSUE TITLE
Testnet: <Issue Title>

### ISSUE THREAD

**Issue by SoloDboy** [blockscout/blockscout#5556]
*Describe your issue here.*

### Environment
* Elixir Version: 1.12.2
* Erlang Version: 24
* BlockScout Version: 

* User Agent: `Mozilla/5.0 (Linux; Android 12; SM-G998U Build/SP1A.210812.016; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/101.0.4951.41 Mobile Safari/537.36`

### Steps to reproduce

*Tell us how to reproduce this issue. If possible, push up a branch to your fork with a regression test we can run to reproduce locally.*

### Expected Behaviour

*Tell us what should happen.*

### Actual Behaviour

*Tell us what happens instead.*
Hello to whoever reads this, my HEX isn't showing up in my wallet I thought it would fix its self during the indexing phase but to no avail I hope it's not to late, also my pulseX sacrifice balance is correct on the tracker but not in my wallet.

**Comment by vbaranov** [comment]
PulseChain instance is unsupported here
