### ISSUE TITLE
Wrong ipfs URL rewrite

### ISSUE THREAD

**Issue by cen1** [blockscout/blockscout#5557]
I believe the condition here https://github.com/blockscout/blockscout/blob/35d7887b620926122b43904b3517863fcc62aa5c/apps/block_scout_web/lib/block_scout_web/views/tokens/instance/overview_view.ex#L182 and the one below it are wrong.

If url contains "ipfs://ipfs" somewhere in the middle, for example: https://some.gateway.com/ipfs://ipfs...

It will match it but then fail with `** (MatchError) no match of right hand side value`

I think the intended logic for these two condition was to replace the URL with public ipfs gateway if url **starts with** the string.

So conditions should probably be: 

`image_url =~ ~r/^ipfs:\/\/ipfs/ ->`
and
`image_url =~ ~r/^ipfs:\/\// ->`

In any other case we just return the original since it is probably a custom ipfs gateway URL which needs no replacing.

### Steps to reproduce

Token with "ipfs://ipfs" in the middle of image URL.

### Expected behaviour

No exception

### Actual behaviour

Exception

**Comment by nikitosing** [comment]
@cen1 Is that real case?

**Comment by cen1** [comment]
@nikitosing yes, we observed it in the wild. Whether it is legit use case or not I am not sure but an error is not desirable either way.
