### ISSUE TITLE
this issue is coming when i want to run code in ubuntu

### ISSUE THREAD

**Issue by soumen29121997** [blockscout/blockscout#5559]
@vbaranov this issue is coming when i want to run code in ubuntu

could not compile dependency :earmark_parser, "mix compile" failed. You can recompile this dependency with "mix deps.compile earmark_parser", update it with "mix deps.update earmark_parser" or clean it with "mix deps.clean earmark_parser"

**Comment by soumen29121997** [comment]
@nikitosing can you please help me

**Comment by M2l2koPOWER** [comment]
this error is still occurring. Since you closed the issue, do you have any solution? Installing a new version of Elixir didn't help
