### ISSUE TITLE
Value is null of USD and BTC on convert 

### ISSUE THREAD

**Issue by piyushPine** [blockscout/blockscout#5562]
*Describe your issue here.*

### Environment
* Elixir Version: 1.12.2
* Erlang Version: 24
* BlockScout Version: 

* User Agent: `Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/101.0.4951.64 Safari/537.36`

### Steps to reproduce

*Tell us how to reproduce this issue. If possible, push up a branch to your fork with a regression test we can run to reproduce locally.*

### Expected Behaviour

*Tell us what should happen.*

### Actual Behaviour

*Tell us what happens instead.*

**Comment by piyushPine** [comment]
https://scan.v2b.testnet.pulsechain.com/api?module=stats&action=coinprice

Response Body

{
  "message": "OK",
  "result": {
    "coin_btc": null,
    "coin_btc_timestamp": null,
    "coin_usd": null,
    "coin_usd_timestamp": null
  },
  "status": "1"
}

**Comment by vbaranov** [comment]
PulseChain instance is unsupported here.
