### ISSUE TITLE
List of verified contracts page with the ability to search 

### ISSUE THREAD

**Issue by ulyanas** [blockscout/blockscout#5576]
Consider adding a separate page that lists all verified contracts and allows to perform search. 

- List all verified contracts with all available properties
- Allow sorting on each property
- Allow search by address / contract name

**Comment by MaximK3** [comment]
**What problem are you trying to solve?** 
Currently, Blockscout is collecting data about all verified contracts. But there is no separate page that displays a list of verified contracts. 

**Describe the solution you'd like** 
The solution is to add a separate page that lists all verified contracts and allows to perform search.

<img width="1305" alt="Снимок экрана 2022-10-28 в 18 09 19" src="https://user-images.githubusercontent.com/115090716/198634515-67ed086a-4a31-4c1f-b141-4b36e322e59c.png">
