### ISSUE TITLE
Contract: SolToUML diagram

### ISSUE THREAD

**Issue by ulyanas** [blockscout/blockscout#5578]
Develop a page that allows to analyze smart contracts using UML with https://github.com/naddison36/sol2uml

**Comment by vbaranov** [comment]
Original issue https://github.com/blockscout/blockscout/issues/2712

**Comment by vbaranov** [comment]
Resolved in https://github.com/blockscout/blockscout/pull/6401, included into [5.0.0](https://github.com/blockscout/blockscout/releases/tag/v5.0.0-beta).
