### ISSUE TITLE
Token transfer page: display token icons

### ISSUE THREAD

**Issue by ulyanas** [blockscout/blockscout#5581]
Display token icons in the token transfer section on the tx page
<img width="698" alt="image" src="https://user-images.githubusercontent.com/6618204/168883470-e4803cce-2ea5-45b5-b3d4-8c45f96b75ce.png">
<img width="492" alt="image" src="https://user-images.githubusercontent.com/6618204/168883577-eeff887b-d2c9-49a9-8b39-b65b025d7fef.png">

**Comment by vbaranov** [comment]
Implemented in the new UI
