### ISSUE TITLE
Ethereum Classic: <Issue Title>

### ISSUE THREAD

**Issue by davejw824** [blockscout/blockscout#5584]
*Describe your issue here.*
Hi I had an issue transferring some Ethereum classic to another wallet. It was under hash 0x5452a473160ff072ffe52b84cedfa24b253d9e92ecc85e110f77c81b32ff333b
The crypto wallet i transferred this to told me that the coins were in my wallet i just couldnt physically see them until i backed them up using a private key. What is the best wallet to store Ethereum classic mainnet on? Also, is it possible to have the coins sent back to my coinbase account for the inconvenience? 
### Environment
* Elixir Version: 1.12.2
* Erlang Version: 24
* BlockScout Version: v4.1.1-beta

* User Agent: `Mozilla/5.0 (Linux; Android 12; SAMSUNG SM-G996U1) AppleWebKit/537.36 (KHTML, like Gecko) SamsungBrowser/16.2 Chrome/92.0.4515.166 Mobile Safari/537.36`

### Steps to reproduce

*Tell us how to reproduce this issue. If possible, push up a branch to your fork with a regression test we can run to reproduce locally.*

### Expected Behaviour

*Tell us what should happen.*

### Actual Behaviour

*Tell us what happens instead.*

**Comment by vbaranov** [comment]
Regarding your question try to contact ETC team, for instance, on their Discord https://discord.com/invite/hQs894U.
