### ISSUE TITLE
Bridging issue 

### ISSUE THREAD

**Issue by Johnhun88** [blockscout/blockscout#5596]
Transaction 
0xf47f2d14cd1f089a86a6b077ce7ce2d37525ad1b35514c45a8e15eb344d3256a

Was supposed  to bridge 151 DAI to my metamask wallet, the funds never arrived. Could uou please investigate.

Regards

John

**Comment by vbaranov** [comment]
Questions can be asked in the #gnosis-chain channel on Discord https://discord.gg/mPJ9zkq
