### ISSUE TITLE
Testnet: <Issue Title>

### ISSUE THREAD

**Issue by Rhodes84** [blockscout/blockscout#5597]
Week later all most and still not had my hex sent  please send me my hex *

### Environment
* Elixir Version: 1.12.2
* Erlang Version: 24
* BlockScout Version: 

* User Agent: `Mozilla/5.0 (iPhone; CPU iPhone OS 15_4_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Mobile/15E148`

### Steps to reproduce

*Tell us how to reproduce this issue. If possible, push up a branch to your fork with a regression test we can run to reproduce locally.*

### Expected Behaviour

*Tell us what should happen.*

### Actual Behaviour

*Tell us what happens instead.*

**Comment by Rhodes84** [comment]
Please send my my hex it’s been a week with out and I’m getting worried now

**Comment by vbaranov** [comment]
This is the chat about technical issues with BlockScout. Your issue doesn't relate to Blockscout.
