### ISSUE TITLE
Add SECURITY.md

### ISSUE THREAD

**Issue by JamieSlome** [blockscout/blockscout#5604]
Hello 👋

I run a security community that finds and fixes vulnerabilities in OSS. A researcher (@thewhiteevil) has found a potential issue, which I would be eager to share with you.

Could you add a `SECURITY.md` file with an e-mail address for me to send further details to? GitHub [recommends](https://docs.github.com/en/code-security/getting-started/adding-a-security-policy-to-your-repository) a security policy to ensure issues are responsibly disclosed, and it would help direct researchers in the future.

Looking forward to hearing from you 👍

(cc @huntr-helper)

**Comment by igorbarinov** [comment]
Thanks for the suggestion. Will add.

**Comment by JamieSlome** [comment]
@igorbarinov - appreciate it :)

You can also find the report directly here:
https://huntr.dev/bounties/29ed770f-3dd1-4095-8a98-3dd401d498ee/

It is private and only accessible to maintainers with repository write permissions 👍

**Comment by igorbarinov** [comment]
https://github.com/blockscout/.github/blob/main/SECURITY.md

> It is private and only accessible to maintainers with repository write permissions 👍

thanks, will check it out!

**Comment by vbaranov** [comment]
SECURITY.md has been added https://github.com/blockscout/.github/blob/main/SECURITY.md
