### ISSUE TITLE
CSV download UI problem

### ISSUE THREAD

**Issue by cen1** [blockscout/blockscout#5614]
When CSV download takes a long time, the page loading stops and captcha re-appears. But if you have browser dev console open, the request to /transactions-csv is still going in the background and eventually finishes with file download.

![blockscout_csv_ui](https://user-images.githubusercontent.com/1158861/170537946-5c9b35e0-fea5-46ba-b964-666ca086f3ce.png)

This can make user think that something went wrong and nothing happened.

### Environment

* Blockscout Version/branch: 4.1.2-beta

### Expected behaviour

Page should keep loading until file download happens or some other load indicator added to signal that the download process is still ongoing.

**Comment by vbaranov** [comment]
With 5.2.1 the performance of CSV improved. The query shouldn't lasts more than 60 seconds. Please update your instance.
