### ISSUE TITLE
Some CSV download requests end with empty reply (curl 52)

### ISSUE THREAD

**Issue by cen1** [blockscout/blockscout#5615]
Some CSV downloads (especially for older periods like last year and accounts with a lot of transactions) end up with cloudflare error 502 on our instance. Error appears before the cloudflare timeout which is 100 seconds.

To eliminate cloudflare being the problem I tried to replicate the request with curl directly on the server. 

```
curl 'http://127.0.0.1:4000/transactions-csv?address_id=0x0ff...&from_period=2021-10-20&to_period=2021-11-29'
curl: (52) Empty reply from server
```

There is no http code, headers or anything returned. Request terminates after ~**60** seconds all the time which makes me think this is some internal timeout inside blockscout or elixir that is not handled properly. 

If I reduce the period to a few days and repeat the request a few times it sometimes successfuly returns the CSV, probably because something gets into hot cache or indexed.

Trying to get the same transactions through GraphQL API seems very fast so this bug and general slowness of the call seems specific to CSV code.

There is nothing in error log, I only see the incoming request in journal.

### Environment

* Blockscout Version/branch: 4.1.2-beta

### Steps to reproduce

Other than this appearing on older transactions and accounts with lots of them, I don't really have a good reproduction case.

```
curl 'https://songbird-explorer.flare.network/transactions-csv?address_id=0x96b83D3F73E44c9A96388CF1D116595551dAeB5A&from_period=2021-12-01&to_period=2021-12-31'
```

**Comment by Hot-n-Cold** [comment]
Hello is there any update on this problem that still exists or is there a workaround of some sort. Not a developer or technical but am capable. I am just someone in need of downloading a .csv file of my NFTs on Songbird?
Thank you to anyone who can and will help.

**Comment by vbaranov** [comment]
Performance of CSV export improved in Blockscout release 5.2.1. Please try it and let us know, if the issue is still present with it.

**Comment by Hot-n-Cold** [comment]
This is still not downloading.
Error is Verification expired tried on IOS and Windows 10
Same as before
It would be very helpful to have this working

Sent from Proton Mail mobile

-------- Original Message --------

**Comment by vbaranov** [comment]
@Hot-n-Cold please provide the link for reproduction.

**Comment by Hot-n-Cold** [comment]
Hi Victor
I have tried this over 20 different times over the last 3 days or so and only once did it present a .csv to download. It was a period from 01 01 2023 to the current day and produced 5 lines of transactions Flare network and then I tried to download the Token Transfers as well but it did not work.
Have tried both Flare and Songbird networks and different addresses.
I click the Captcha and I can see a message near the task bar saying
Sometimes, Waiting for www.google.com
Once the message said Read songbird-explorer.flare.network
Another time it read
Transferring data from songbird-explorer.flare.network
And
The captcha then stops and briefly shows the message
Verification failed. Check the checkbox again

Two different laptops running windows Home and Windows Pro both up to date, tried Chrome and Firefox.
Tried iPad Pro up to date . It just keeps clearing the Captcha check box tick when I click Download repeatedly?? Nothing else on iPad?

Must have tried 30 times now with one little download?
It would be so good to have this functioning as intended especially the Token Transfers so any help you can provide will be appreciated by a much wider audience than just me.
Thank you
Kind regards
Wayne

Sent with [Proton Mail](https://proton.me/) secure email.

------- Original Message -------

**Comment by cen1** [comment]
@Hot-n-Cold note that CSV improvements mentioned just landed in the latest release and it is unlikely the explorers you mention are already using this version.

**Comment by Hot-n-Cold** [comment]
Oh ok thank you for letting me know.
So who will update the explorers do you know?
Is this Flare or Songbird or Blockscout who will update?

Should I just wait as maybe it should happen shortly?
Regards
Wayne
