### ISSUE TITLE
Palm: Error time out API verify or wrong call

### ISSUE THREAD

**Issue by oriolaguade** [blockscout/blockscout#5616]
*Describe your issue here.*

### Environment
* Elixir Version: 1.12.3
* Erlang Version: 24
* BlockScout Version: 

* User Agent: Chrome/101.0.4951.64  and postman

API palm explorer to verify SC: https://explorer.palm.io/api?module=contract

### Steps to reproduce

I require to verify smart contracts form a Factory contract and I have seen that in the PALM block explorer (https://explorer.palm.io/) there isn't an authomatic code verification for similar smart contracts with the same bytecode.

For our project we require to verify the code of all the Smart contracts created from the Factory contract, so we are trying to call the api to verify the contract with it, but it seems that it isn't working or we are not calling it right.

Thats a SC with the correct (manual) verification:
https://explorer.palm.io/address/0x7E57a5b6b731b6Db04aAE55918c32CBe13E092f8/

and thats another  SC creater later from the same contract factory (same code, evm, compiler), etc.
0x1e8a243Ae85b2D5A0FDc6F38209601c2c19f38e1

When I try to verify via api I get a time out error

could you help me how I should call via GET or POST the api to verify it?

### Expected Behaviour

get it verified with the api

### Actual Behaviour

time out

Thanks in advanced!
Oriol

**Comment by nikitosing** [comment]
@oriolaguade did you try the method described in [api docs](https://explorer.palm.io/api-docs#contract) for `verify` method?
```
curl -d '{"addressHash":"0xc63BB6555C90846afACaC08A0F0Aa5caFCB382a1","compilerVersion":"v0.5.4+commit.9549d8ff", "contractSourceCode":"pragma solidity ^0.5.4; contract Test { }","name":"Test","optimization":false}' -H "Content-Type: application/json" -X POST "https://blockscout.com/poa/sokol/api?module=contract&action=verify"
```
![image](https://user-images.githubusercontent.com/32202610/170576556-881e9635-9d9e-4d0a-9bb5-80bfc7a2fe31.png)

**Comment by oriolaguade** [comment]
Hi, 
Correct, I tried this method but not with curl, instead calling it directly with POST and GET with  Postman.
As I understand if it's for the palm network the endpoint should be https://explorer.palm.io/api?module=contract, is that correct?
because in the documentation the reference is Base URL: https://localhost:4000/api   but that's not possible..

The error that I received is a time out, but I have doubts if I introduced the information correctly, for instance,  for the code param, should I put the code inside { }  or inside ""  or "{}" ? 
If I have the following code (the one verified in this smart contract https://explorer.palm.io/address/0x7E57a5b6b731b6Db04aAE55918c32CBe13E092f8/ )
if ther are line breaks, should I delete them? or they doesn't matter?

If you had an example of calling the api It would be a huge help, 
or at lesat be sure that it's working, because i didn't receive an error, insted I recevied a Time out error. 

Thanks in advanced,
Oriol

**Comment by nikitosing** [comment]
@oriolaguade Hi,
![image](https://user-images.githubusercontent.com/32202610/170784929-bba15a45-c9bc-440a-b74d-a12adeed219c.png)
I turned on Desktop agent, but yes, the response time is quite long. The problem and in Blockscout implementation (We are working on speeding up the compilation proccess) and in Palm's server performance I think. I could suggest to use another API endpoint: `verifysourcecode` (it works in pair with `checkverifystatus`) you can read description in API docs. 
About your question:
1) url is correct: https://explorer.palm.io/api?module=contract
2) \n doesn't matter, Example of valid json (I unable to check if it works because of gateway time out error)
![image](https://user-images.githubusercontent.com/32202610/170785516-2e686fbc-cfea-41aa-bbf0-2f80a93ffbe3.png)

```
{"addressHash":"0x1e8a243Ae85b2D5A0FDc6F38209601c2c19f38e1","compilerVersion":"v0.8.13+commit.abaa5c0e", "contractSourceCode":"//SPDX-License-Identifier: UNLICENSEDpragma solidity ^0.8.13;/// @title Academic Certificate/// @author Blockchain Qualifications/// @notice Academic certificate emitted by an authorized Academic Institution. Once issued its content cannot be modified.contract AcademicCertificate {/* University info */ address public universitySCAddress; address public universityUserCreatorWallet;/* Certificate info */ string public certificateDetailJSON; uint256 public dateCreationBCCertificate; bool public activeCertificate; uint256 public dateDeletion; address public additionalInformationSC;/* BCQ addresses */ uint8 public SCVersion = 2;/* Sign info */ address[] public walletSignerList; mapping (address => uint256) public dateSignatureWallet;/* Modifiers*/ modifier onlyUniversityIssuer { require(msg.sender == universitySCAddress, \"only Academic Institution who created it can operate\"); //only the university who created it can operate _; } modifier onlyActiveCertificate() { require (activeCertificate, \"certificate is inactive\"); _; } event CertificateCreated( address _certificateAddress); event CertificateSigned( address indexed _signer); event CertificateDeleted( uint256 _dateDelete); /// @notice Creation of the Academic certificate by the Academic institution (universitySCAddress) only by authorized personnel(wallets) of the institution. function createCertificate (string memory _certificateInfo ) public returns(bool){ require(bytes(certificateDetailJSON).length == 0, \"Certificate details cannot be modified\"); universitySCAddress = msg.sender; universityUserCreatorWallet = tx.origin; // Set Certificate info certificateDetailJSON= _certificateInfo; dateCreationBCCertificate= block.timestamp; activeCertificate=true; emit CertificateCreated(address(this)); return true; } /// @notice Deletion of the Academic certificate by the Academic institution (universitySCAddress) only by authorized personnel(wallets) of the institution. function deleteCertificate () public onlyUniversityIssuer onlyActiveCertificate returns(bool){ activeCertificate=false; certificateDetailJSON = \"\"; dateDeletion=block.timestamp; emit CertificateDeleted(dateDeletion); return true; } /// @notice Signature of the certificate by the academic institution authorized personnel function signCertificate() public onlyUniversityIssuer onlyActiveCertificate returns (bool) { address signer = tx.origin; require (dateSignatureWallet[signer] == 0, \"already signed by wallet\"); //it can be signed by a signer only once walletSignerList.push(signer); dateSignatureWallet[signer] = block.timestamp; emit CertificateSigned(signer); return true; } /// @notice Function to set the SC where additional academic information of the certiticate is registered */ function setAdditionalInformationSC( address _additionalInformationSC) public onlyUniversityIssuer onlyActiveCertificate returns(bool){ additionalInformationSC = _additionalInformationSC; return true; } //Signer info funcitons function signatures() public view returns (uint256 ) { return walletSignerList.length; } function signatureInfo(uint256 walletSignerIndex) public view returns (address,uint256 ) { if(walletSignerIndex <= walletSignerList.length) { return (walletSignerList[walletSignerIndex], dateSignatureWallet[walletSignerList[walletSignerIndex]]); } return (address(0),0); } function academicInstitutionIdentity() public view returns(address) { return universitySCAddress; }}","name":"AcademicCertificate","optimization":false}
```
