### ISSUE TITLE
Testnet: PLS not received

### ISSUE THREAD

**Issue by sumitd14** [blockscout/blockscout#5619]
Hi,

Hope you are doing well.

I exchanged 1,000,000 PLSX for 298,263.865 PLS, but have not received PLS in my MetaMask wallet.
I see the transaction as Confirmed.

Link to transaction: https://scan.v2b.testnet.pulsechain.com/tx/0x04159241fdc8112f5962b08448ae0e63dd945bf1f24c20e5ca8a5f89123dac50/token-transfers

Could you please look in to this?

Thank you!

Regards,
Sumit Dhall

### Environment
* Elixir Version: 1.12.2
* Erlang Version: 24
* BlockScout Version: 

* User Agent: `Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/102.0.0.0 Safari/537.36`

### Steps to reproduce

1. Goto Exchange: https://app.v2b.testnet.pulsex.com/swap
2. Swap 1,000,000 PLSX to PLS
3. After transaction confirmation, check PLS balance in MetaMask
4. ERROR: PLS not received

### Expected Behaviour

1. After transaction confirmation, PLS should be added to the connected MetaMask account

### Actual Behaviour

1. After waiting for 1+ hours and transaction showing as Confirmed, PLS is not received in the connected MetaMask account

**Comment by vbaranov** [comment]
PulseChain is unsupported here
