### ISSUE TITLE
Palm: <Issue Title>

### ISSUE THREAD

**Issue by darsheehan** [blockscout/blockscout#5622]
*Describe your issue here.*
I sent palm over the palm network via metamask to a kucoin exchange. But the receiver can not see it in his exchange

https://explorer.palm.io/tx/0xab84f4bb47c718211df787b04c02d94f9b3562b141679422864ac11e9314bb64/internal-transactions Attached is the transaction. Help me finding the missing coin

### Environment
* Elixir Version: 1.12.3
* Erlang Version: 24
* BlockScout Version: 

* User Agent: `Mozilla/5.0 (iPhone; CPU iPhone OS 14_4 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.0.3 Mobile/15E148 Safari/604.1`

### Steps to reproduce

*Tell us how to reproduce this issue. If possible, push up a branch to your fork with a regression test we can run to reproduce locally.*

### Expected Behaviour

*Tell us what should happen.*

### Actual Behaviour

*Tell us what happens instead.*

**Comment by vbaranov** [comment]
Palm instance is unsupported here
