### ISSUE TITLE
Ethereum Classic: ETC price frozen at 20.76 USD/ETC

### ISSUE THREAD

**Issue by wpwrak** [blockscout/blockscout#5633]
The ETC exchange rate seems to be "frozen" at 20.76 USD/ETC for a while, according to my records approximately since 2022-05-20. coinmarketcap currently shows it at about 23.1 USD/ETC, and with the usual amount of changes in the last days, not "flatlined".
I saw it at these two places:

https://blockscout.com/etc/mainnet/api?module=stats&action=coinprice
https://blockscout.com/etc/mainnet/address/WALLET/coin-balances

Note that the timestamp returned with the coin price (1652993643) is indeed of 2022-05-19 20:54:03 UTC.

### Environment
Ubuntu 21.04
curl 7.74.0
(I also get the same with Chrome 103.0.5056.0)

### Steps to reproduce
curl -s "https://blockscout.com/etc/mainnet/api?module=stats&action=coinprice"

**Comment by diega** [comment]
Thanks for reporting. I restarted the instance and the price seems to be better drawn in the chart but I think the API isn't responding properly
<img width="381" alt="image" src="https://user-images.githubusercontent.com/79943/171523176-85108a38-d09a-400a-8f9a-2f37dd5fe499.png">

**Comment by vbaranov** [comment]
@diega the issue is related to CoinGecko started to refuse requests from Blockscout. I updated the [branch for ETC Mainnet](https://github.com/blockscout/blockscout/tree/production-classic-stg). This [PR](https://github.com/blockscout/blockscout/pull/5613) is meant to fix this issue by adding support of the CoinGecko API key and optional CoinMarketCap source. Please follow the instructions in that PR, on how to add CoinGecko/CoinMarketCap API key.

Together with updating the instance, please, change `BLOCKSCOUT_VERSION=v4.1.3-beta` since the branch contains this release.

Also, take a note of [4.1.3](https://github.com/blockscout/blockscout/releases/tag/v4.1.3-beta) release's notice:
> Notice: All environment variables, which contained "CACHE" suffix, migrated to get prefix "CACHE_". For instance, BLOCK_COUNT_CACHE_PERIOD -> CACHE_BLOCK_COUNT_PERIOD

**Comment by diega** [comment]
Thanks @vbaranov. Do you know what's the expected API requests count to CoinGecko/CoinMarketCap for a 24/7 blockscout instance? that's for analyzing which plan we need to setup

**Comment by wpwrak** [comment]
Thanks for looking into this !
Right now, the wallet page doesn't show the USD value anymore. Will that be the long-term fix ?

Also, the stats/coinprice API is now broken (it was "frozen" at 20.76 before):
https://blockscout.com/etc/mainnet/api?module=stats&action=coinprice
{"message":"OK","result":{"coin_btc":null,"coin_btc_timestamp":null,"coin_usd":null,"coin_usd_timestamp":null},"status":"1"}

Just FYI, my use case is to track three mining wallets. For this, I load each wallet HTML page every two hours, and extract coin balance and coin price from there. I initially (in January, when I wrote my script) tried to use the RPC APIs, but found them unreliable, due to high load. The Web page worked great so far. Thanks ! :)

**Comment by diega** [comment]
@wpwrak yes, once the external service gets properly setup, that will be a long term fix.

WRT the result that you are obtaining now from the API I assume that's because once I restarted the service some cached value has been lost

**Comment by khanghuynh92** [comment]
> @diega the issue is related to CoinGecko started to refuse requests from Blockscout. I updated the [branch for ETC Mainnet](https://github.com/blockscout/blockscout/tree/production-classic-stg). This [PR](https://github.com/blockscout/blockscout/pull/5613) is meant to fix this issue by adding support of the CoinGecko API key and optional CoinMarketCap source. Please follow the instructions in that PR, on how to add CoinGecko/CoinMarketCap API key.
> 
> Together with updating the instance, please, change `BLOCKSCOUT_VERSION=v4.1.3-beta` since the branch contains this release.
> 
> Also, take a note of [4.1.3](https://github.com/blockscout/blockscout/releases/tag/v4.1.3-beta) release's notice:
> 
> > Notice: All environment variables, which contained "CACHE" suffix, migrated to get prefix "CACHE_". For instance, BLOCK_COUNT_CACHE_PERIOD -> CACHE_BLOCK_COUNT_PERIOD

Hi @vbaranov 
This update means we need to pay a CG subscription right? and if so which plan should I choose to be suitable with blockscout rate exchange API call frequency?


![image](https://user-images.githubusercontent.com/10219168/171853239-2ab27989-bfb5-43e2-9399-785e8e71ef3d.png)

**Comment by igorbarinov** [comment]
> > @diega the issue is related to CoinGecko started to refuse requests from Blockscout. I updated the [branch for ETC Mainnet](https://github.com/blockscout/blockscout/tree/production-classic-stg). This [PR](https://github.com/blockscout/blockscout/pull/5613) is meant to fix this issue by adding support of the CoinGecko API key and optional CoinMarketCap source. Please follow the instructions in that PR, on how to add CoinGecko/CoinMarketCap API key.
> > Together with updating the instance, please, change `BLOCKSCOUT_VERSION=v4.1.3-beta` since the branch contains this release.
> > Also, take a note of [4.1.3](https://github.com/blockscout/blockscout/releases/tag/v4.1.3-beta) release's notice:
> > > Notice: All environment variables, which contained "CACHE" suffix, migrated to get prefix "CACHE_". For instance, BLOCK_COUNT_CACHE_PERIOD -> CACHE_BLOCK_COUNT_PERIOD
> 
> Hi @vbaranov This update means we need to pay a CG subscription right? and if so which plan should I choose to be suitable with blockscout rate exchange API call frequency?
> 
> ![image](https://user-images.githubusercontent.com/10219168/171853239-2ab27989-bfb5-43e2-9399-785e8e71ef3d.png)

we are paying for Analyst and it's enough

**Comment by diega** [comment]
@vbaranov I deployed the new version and I'll keep an eye on the consumption for our key and upgrade the plan if needed. I think you can close this ticket now.
Thanks a lot for your help

**Comment by wpwrak** [comment]
Everything looks fine, both the coinprice API and the wallet page.
Thanks a lot for fixing this !
