### ISSUE TITLE
Venidium Testnet: <Issue Title>

### ISSUE THREAD

**Issue by sergiosurvival** [blockscout/blockscout#5634]
buenos dias cancele XVM stake  y en metamask tenia 154 XVM y al cancelar no me aparecen todos los XVM en Metamask*Describe your issue here.*

### Environment
* Elixir Version: 1.12.2
* Erlang Version: 24
* BlockScout Version: 

* User Agent: `Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/101.0.4951.64 Safari/537.36 Edg/101.0.1210.53`

### Steps to reproduce

*Tell us how to reproduce this issue. If possible, push up a branch to your fork with a regression test we can run to reproduce locally.*

### Expected Behaviour

*Tell us what should happen.*

### Actual Behaviour

*Tell us what happens instead.*

**Comment by sergiosurvival** [comment]
Como se cambian los Venidium para tenerlos en Metamask me banearon en discord Venidium los cambie alli la primera vez pero ahora estoy banned en discord saludos antetodo

**Comment by vbaranov** [comment]
Hello, Venidium instance is unsupported here.
