### ISSUE TITLE
Unnecessary exchange rate query

### ISSUE THREAD

**Issue by diega** [blockscout/blockscout#5646]
Following up #5633, I successfully configured the `EXCHANGE_RATES_SOURCE` to be **coin_market_cap** for the Ethereum Coooperative ETC Blockscout instance (https://blockscout.com/etc/mainnet/). Everything is working fine regarding pricing, but I can see on the CoinMarketCap dashboard certain requests that doesn't seem to be needed for our instance, but either way they are doubling the usage that we are doing of the service.

Every ten minutes I can see these two requests
```
/v2/cryptocurrency/quotes/latest?symbol=ETC&CMC_PRO_API_KEY=<API_KEY>
/v2/cryptocurrency/quotes/latest?symbol=BTC&CMC_PRO_API_KEY=<API_KEY>
```

### Environment
* Run command:
```shell
ETHEREUM_JSONRPC_VARIANT='besu'
ETHEREUM_JSONRPC_WS_URL='ws://127.0.0.1:8546'
ETHEREUM_JSONRPC_HTTP_URL='http://127.0.0.1:8545'
ETHEREUM_JSONRPC_TRACE_URL='http://127.0.0.1:8545'
MIX_ENV='prod'
DATABASE_URL='[...]'
SOCKET_ROOT='/etc/mainnet'
DECOMPILED_SMART_CONTRACT_TOKEN='[...]'
PORT='4000'
SUPPORTED_CHAINS='[ { "title": "POA Core", "url": "https://blockscout.com/poa/core" }, { "title": "POA Sokol", "url": "https://blockscout.com/poa/sokol", "test_net?": true }, { "title": "xDai Chain", "url": "https://blockscout.com/poa/dai" }, { "title": "Kovan Testnet", "url": "https://blockscout.com/eth/kovan", "test_net?": true }, { "title": "Ethereum Classic", "url": "https://blockscout.com/etc/mainnet"}, { "title": "RSK Mainnet", "url": "https://blockscout.com/rsk/mainnet", "other?": true }, { "title": "LUKSO L14 testnet", "url": "https://blockscout.com/lukso/l14", "test_net?": true }, { "title": "Ethereum Mainnet", "url": "https://blockscout.com/eth/mainnet" }, { "title": "ETC Kotti", "url": "https://blockscout.com/etc/kotti", "test_net?": true }, { "title": "ETC Mordor", "url": "https://blockscout.com/etc/mordor", "test_net?": true } ]'
CACHE_TXS_COUNT_PERIOD='7200'
CACHE_BLOCK_COUNT_PERIOD='7200'
ALLOWED_EVM_VERSIONS='homestead,tangerineWhistle,spuriousDragon,byzantium,constantinople,petersburg,default'
BLOCKSCOUT_HOST='blockscout.com'
NETWORK_PATH='/etc/mainnet'
API_PATH='/etc/mainnet'
SUBNETWORK='Ethereum Classic'
LINK_TO_OTHER_EXPLORERS='true'
LOGO='/images/classic_ethereum_logo.svg'
LOGO_FOOTER='/images/classic_ethereum_logo.svg'
SECRET_KEY_BASE='[...]'
NETWORK_ICON='_network_icon.html'
COIN='ETC'
NETWORK='ETC'
CHAIN_ID='61'
POOL_SIZE='100'
POOL_SIZE_API='50'
CHAIN_SPEC_PATH='https://raw.githubusercontent.com/openethereum/openethereum/master/ethcore/res/ethereum/classic.json'
EXCHANGE_RATES_SOURCE='coin_market_cap'
EXCHANGE_RATES_COINMARKETCAP_API_KEY='[...]'
BLOCKSCOUT_VERSION='v4.1.3-beta'
make start
```
* Operating System: Debian 4.19.235-1
* Blockscout Version/branch: v4.1.3-beta/production-classic-stg

### Steps to reproduce

Configure an `EXCHANGE_RATES_SOURCE` for an ETC network and inspect the usage

### Expected behaviour

It should only request ETC related prices

### Actual behaviour

It requests ETC and BTC exchange rates

**Comment by vbaranov** [comment]
@diega currently, you can decrease the period of update of the native coin's exchange rate manually here https://github.com/blockscout/blockscout/blob/4f9e451de58247301d3d68632b03f91453ec2469/apps/explorer/lib/explorer/exchange_rates/exchange_rates.ex#L15. By default, it is 10 minutes. In the future, we will provide an environment variable to manage the periodicity of requests.

**Comment by vbaranov** [comment]
@nikitosing let's make also BTC price request optional and disable it by default.

**Comment by vbaranov** [comment]
Please update BLOCKSCOUT_VERSION=v4.1.5-beta, as well before deploying.

**Comment by diega** [comment]
Thanks a lot @vbaranov. I just deployed the new version and it seems to be working as a charm 🎉
