### ISSUE TITLE
Manual installation yields growing CPU consumption on AWS t3.medium

### ISSUE THREAD

**Issue by chiara-andreini** [blockscout/blockscout#5666]
Manually deployed Blockscout on an AWS t3.medium instance shows a growth in the CPU usage over time, which is not sustainable: clearing the cache by service restart does not help, nor does restarting the machine.

### Environment

* Elixir & Erlang/OTP versions (`elixir -version`): Elixir 1.13.3, Erlang 24.3.2
* Operating System: Ubuntu 22.04 LTS
* Blockscout Version/branch: 4.1.3-beta

### Steps to reproduce

- Install blockscout via manual deployment as per https://docs.blockscout.com/for-developers/manual-deployment,
- Make it a systemctl service,
- Configure env vars to read from a custom POA network. 

### Expected behaviour

CPU consumption is overall stable with usage peaks upon verifications and/or syncs.

### Actual behaviour

CPU consumption grows unsustainably.

<img width="1524" alt="Schermata 2022-06-13 alle 17 28 12" src="https://user-images.githubusercontent.com/20712806/173556934-c627a46c-bfe7-45b7-859e-c5ceed94b492.png">

**Comment by vbaranov** [comment]
@chiara-andreini probably, you can try to run the application inside Docker container https://docs.blockscout.com/for-developers/information-and-settings/docker-integration-local-use-only?

**Comment by Matt8white** [comment]
@vbaranov Hi, I'm @chiara-andreini's colleague, we initially chose the manual installation over the docker one due to the big disclaimer "This integration is not production ready - use locally for now.". Should we ignore that and prefer the docker installation over the manual one anyway?

**Comment by vbaranov** [comment]
@Matt8white Docker installation is widely used on our production instances. I removed that disclaimer.

**Comment by Matt8white** [comment]
Thank you, we will switch to that and update on the results. Should we be aware of possible limitations as the blockchain grows in block depth, aside from SSD usage? I'm asking this because our current block time is 2 seconds, which leads to a steep increment of the block number. Thank you for your time

**Comment by vbaranov** [comment]
You should monitor application and DB servers metrics. With increasing the number of transactions per block most likely you will need to add resources (CPU, memory) aside from storage.

**Comment by vbaranov** [comment]
@Matt8white sorry for the delay in answer. Such growing CPU consumption looks abnormal. Could you please update to the latest release of Blockscout [5.0.0](https://github.com/blockscout/blockscout/releases/tag/v5.0.0-beta) or even better to master branch? Also, what type of JSON RPC node do you use (which client)?

**Comment by Thegaram** [comment]
We're experiencing something similar, constant max CPU use running Blockscout v5.0.0 on AWS inside Docker. It's connected to a geth instance.

```
CONTAINER ID   NAME                  CPU %     MEM USAGE / LIMIT     MEM %     NET I/O   BLOCK I/O    PIDS
a177de2d476d   blockscout            794.51%   2.525GiB / 31.01GiB   8.14%     0B / 0B   0B / 142MB   74
```

**Comment by vbaranov** [comment]
@Thegaram is internal transactions fetching enabled on your instance? Could you disable it for some time (`INDEXER_DISABLE_INTERNAL_TRANSACTIONS_FETCHER=true`) and provide some feedback, if this issue dissappeared or not?

**Comment by ct-toch** [comment]
> We're experiencing something similar, constant max CPU use running Blockscout v5.0.0 on AWS inside Docker. It's connected to a geth instance.
> 
> ```
> CONTAINER ID   NAME                  CPU %     MEM USAGE / LIMIT     MEM %     NET I/O   BLOCK I/O    PIDS
> a177de2d476d   blockscout            794.51%   2.525GiB / 31.01GiB   8.14%     0B / 0B   0B / 142MB   74
> ```

Me too.
Even I have tried this ```INDEXER_DISABLE_INTERNAL_TRANSACTIONS_FETCHER=true```

**Comment by vbaranov** [comment]
@ct-toch how much CPU did you allocate for the Blockscout container? Is the situation the same with 5.1.3?

**Comment by vbaranov** [comment]
Please

**Comment by haidarabdillah** [comment]
i got this problem too, any solve? 
im use blockscout/blockscout:5.2.1

**Comment by yarkinwho** [comment]
Observed as well. Another observation is memory consumption seems keep going up as well. Maybe the growing CPU consumption is wasted on scanning some unnecessary growing list.
