### ISSUE TITLE
Didn't index some ERC20 coins

### ISSUE THREAD

**Issue by RickCastle2018** [blockscout/blockscout#5668]
*Describe your issue here.*

### Environment

* Elixir & Erlang/OTP versions (`elixir -version`):
* Operating System: Ubuntu
* Blockscout Version/branch: Latest, built from source code

### Steps to reproduce

*Tell us how to reproduce this issue.  ❤️ if you can push up a branch to your fork with a regression test we can run to reproduce locally.*

TBH, I don't know. I just set up Blockscout with https://ammer.network, and some coins failed to be loaded (symbol, name, *decimals*)

### Expected behaviour

*Tell us what should happen.*

All ERC20 tokens should've been indexed. All ERC20 tokens had the same source code, but different emission. Coins with big emission weren't recognized, but ones with small were.

### Actual behaviour

*Tell us what happens instead.*

![image](https://user-images.githubusercontent.com/48931166/173676430-78aa39c7-7dd7-4e6c-b9ed-34c9794eea3a.png)

**Comment by vbaranov** [comment]
@RickCastle2018 were those tokens precompiled? Or was a transaction to create a token contract? Can you share the address of the token contract, which is expected to be on the tokens list from your perspective, which is actually missing there?

**Comment by RickCastle2018** [comment]
@vbaranov, what do you mean by precompiled? They were deployed with bytecode. You can see on the screenshot above - some of the tokens have missing symbol, name and have wrong total supply

**Comment by RickCastle2018** [comment]
@vbaranov The question is how can I reindex all the tokens?

**Comment by vbaranov** [comment]
@RickCastle2018 Token's metadata should be updated with every new token transfer or after some time after application restart.

**Comment by RickCastle2018** [comment]
@vbaranov It doesn't seem like transfers update metadata, but I'll try restarting Blockscout and I'll be back. Thank you!
