### ISSUE TITLE
ERC948 support

### ISSUE THREAD

**Issue by owocki** [blockscout/blockscout#567]
This is a placeholder for adding ERC948 support to the OSS POA block explorer ERC948 support

Some things we'd like to see:
* View manage the liveliness of your subscription
* view other subscription transactions associated with a tx.

Anything else?

@aarondr77  @captnseagraves @kosecki123 @lknix @aj07 @androolloyd

**Comment by ulyanas** [comment]
The ERC-948 standard did not receive wide popularity
