### ISSUE TITLE
Testnet: <Sacrifice Balance>

### ISSUE THREAD

**Issue by kincimi** [blockscout/blockscout#5677]
*Hi there, I have Sacrifice some ETH when I check the balance a have o Pulse, where is the Sacrifice point or My ETH? Thank you so much.*

### Environment
* Elixir Version: 1.12.2
* Erlang Version: 24
* BlockScout Version: 

* User Agent: `Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/99.0.4844.83 Safari/537.36`

### Steps to reproduce

*Tell us how to reproduce this issue. If possible, push up a branch to your fork with a regression test we can run to reproduce locally.*

### Expected Behaviour

*Tell us what should happen.*

### Actual Behaviour

*Tell us what happens instead.*

**Comment by vbaranov** [comment]
Pulse chain is unsupported here. Please find their official chains.
