### ISSUE TITLE
Token metadata exceeding 255 characters size

### ISSUE THREAD

**Issue by vbaranov** [blockscout/blockscout#5682]
```
2022-06-17T08:27:43.811 [error] Task #PID<0.14779.12> started from Indexer.Fetcher.Token terminating
** (Postgrex.Error) ERROR 22001 (string_data_right_truncation) value too long for type character varying(255)
    (ecto_sql 3.7.1) lib/ecto/adapters/sql.ex:760: Ecto.Adapters.SQL.raise_sql_call_error/1
    (ecto 3.7.1) lib/ecto/repo/schema.ex:744: Ecto.Repo.Schema.apply/4
    (ecto 3.7.1) lib/ecto/repo/schema.ex:367: anonymous fn/15 in Ecto.Repo.Schema.do_insert/4
    (explorer 0.0.1) lib/explorer/chain.ex:5820: anonymous fn/5 in Explorer.Chain.update_token/2
    (ecto 3.7.1) lib/ecto/multi.ex:716: Ecto.Multi.apply_operation/5
    (elixir 1.13.1) lib/enum.ex:2396: Enum."-reduce/3-lists^foldl/2-0-"/3
    (ecto 3.7.1) lib/ecto/multi.ex:690: anonymous fn/5 in Ecto.Multi.apply_operations/5
    (ecto_sql 3.7.1) lib/ecto/adapters/sql.ex:1021: anonymous fn/3 in Ecto.Adapters.SQL.checkout_or_transaction/4
Function: &Indexer.BufferedTask.log_run/1
    Args: [%{batch: [%Explorer.Chain.Hash{byte_count: 20, bytes: <<210, 13, 106, 245, 121, 229, 112, 70, 178, 82, 22, 216, 255, 79, 206, 48, 76, 59, 236, 88>>}], callback_module: Indexer.Fetcher.Token, callback_module_state: [transport: EthereumJSONRPC.HTTP, transport_options: [http: EthereumJSONRPC.HTTP.HTTPoison, url: "...", method_to_url: [eth_getBalance: "...", trace_block: "...", trace_replayTransaction: "..."], http_options: [recv_timeout: 600000, timeout: 600000, hackney: [pool: :ethereum_jsonrpc]]], variant: EthereumJSONRPC.Parity], metadata: []}]
```

https://github.com/blockscout/blockscout/blob/fb478026959f5e7eedf278771196bab9bedd498d/apps/explorer/lib/explorer/chain.ex#L5820

Token:
https://blockscout.com/eth/mainnet/token/0xd20d6aF579e57046B25216D8FF4fcE304c3bec58/token-transfers

Probably, extending of column data size is required.

**Comment by lqucool** [comment]
get the same err.
`2022-08-12T01:24:39.437 [error] Task #PID<0.1929.0> started from Indexer.Fetcher.Token terminating
** (Postgrex.Error) ERROR 22001 (string_data_right_truncation) value too long for type character varying(255)
    (ecto_sql 3.7.1) lib/ecto/adapters/sql.ex:760: Ecto.Adapters.SQL.raise_sql_call_error/1
    (ecto 3.7.1) lib/ecto/repo/schema.ex:744: Ecto.Repo.Schema.apply/4
    (ecto 3.7.1) lib/ecto/repo/schema.ex:367: anonymous fn/15 in Ecto.Repo.Schema.do_insert/4
    (explorer 0.0.1) lib/explorer/chain.ex:4872: anonymous fn/5 in Explorer.Chain.update_token/2
    (ecto 3.7.1) lib/ecto/multi.ex:716: Ecto.Multi.apply_operation/5
    (elixir 1.13.1) lib/enum.ex:2396: Enum."-reduce/3-lists^foldl/2-0-"/3
    (ecto 3.7.1) lib/ecto/multi.ex:690: anonymous fn/5 in Ecto.Multi.apply_operations/5
    (ecto_sql 3.7.1) lib/ecto/adapters/sql.ex:1021: anonymous fn/3 in Ecto.Adapters.SQL.checkout_or_transaction/4
Function: &Indexer.BufferedTask.log_run/1
    Args: [%{batch: [%Explorer.Chain.Hash{byte_count: 20, bytes: <<140, 56, 101, 169, 161, 151, 67, 202, 20, 38, 135, 193, 82, 63, 63, 106, 163, 204, 11, 227>>}], callback_module: Indexer.Fetcher.Token, callback_module_state: [transport: EthereumJSONRPC.HTTP, transport_options: [http: EthereumJSONRPC.HTTP.HTTPoison, url: "http://172.18.0.1:8545", method_to_url: [eth_getBalance: "http://172.18.0.1:8545", trace_block: "http://172.18.0.1:8545", trace_replayTransaction: "http://172.18.0.1:8545"], http_options: [recv_timeout: 600000, timeout: 600000, hackney: [pool: :ethereum_jsonrpc]]], variant: EthereumJSONRPC.Erigon], metadata: []}]`
Is there any solution? Thanks.
