### ISSUE TITLE
Ethereum Classic: <Issue Title>

### ISSUE THREAD

**Issue by Abundiob** [blockscout/blockscout#5691]
*Describe your issue here.*
Have receive. Transaction 
![C2F44E45-7A50-4C11-A22F-BB21187C540A](https://user-images.githubusercontent.com/107857347/174605052-8c3c43a7-6d57-4cae-bde6-19e4eee0f670.png)
![13F2BA3E-4390-4415-91CE-86EAEB40E85F](https://user-images.githubusercontent.com/107857347/174605061-08cc9033-fd74-4827-8cc8-b8975881ffd9.png)

### Environment
* Elixir Version: 1.13.1
* Erlang Version: 24
* BlockScout Version: v4.1.3-beta

* User Agent: `Mozilla/5.0 (iPhone; CPU iPhone OS 15_5 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/15.5 Mobile/15E148 Safari/604.1`

### Steps to reproduce

*Tell us how to reproduce this issue. If possible, push up a branch to your fork with a regression test we can run to reproduce locally.*

### Expected Behaviour

*Tell us what should happen.*

### Actual Behaviour

*Tell us what happens instead.*

**Comment by vbaranov** [comment]
You should ask in Ethereum Classic Discord https://discord.com/invite/bMGuZsA
