### ISSUE TITLE
Official docker image not update after releases

### ISSUE THREAD

**Issue by wbl** [blockscout/blockscout#5692]
It looks like the image at https://hub.docker.com/r/blockscout/blockscout/tags is still at 4.13 even though 4.14 is released. Is this an official image? When can we expect an update?

**Comment by fullkomnun** [comment]
Seems that the 'Publish Docker image' workflow has failed for both [4.14](https://github.com/blockscout/blockscout/runs/6914306517?check_suite_focus=true) and [4.15 ](https://github.com/blockscout/blockscout/runs/6933039346?check_suite_focus=true) with the following error:  
'could not compile dependency :ex_keccak, "mix compile" failed. Errors may have been logged above. You can recompile this dependency with "mix deps.compile ex_keccak", update it with "mix deps.update ex_keccak" or clean it with "mix deps.clean ex_keccak'

Should I open a dedicated bug?

**Comment by fullkomnun** [comment]
Any update on that failing docker build?

**Comment by vbaranov** [comment]
Docker images updated:

[4.1.4](https://hub.docker.com/layers/blockscout/blockscout/blockscout/4.1.4/images/sha256-4aec2bc45b44e9841f30e523be0fce1c3b1ee29a29e09c5bb65d49181b1492b0?context=explore) && [4.1.5](https://hub.docker.com/layers/blockscout/blockscout/blockscout/4.1.5/images/sha256-536c3013a85a1632801269899bd4c3941a197c1f09722f9d77764a34a7560049?context=explore)
