### ISSUE TITLE
csv not downloading

### ISSUE THREAD

**Issue by stucrompy** [blockscout/blockscout#5708]
*Describe your issue here.*

### Environment
* Elixir Version: 1.13.1
* Erlang Version: 24
* BlockScout Version: v4.1.2-beta

* User Agent: `Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/102.0.0.0 Safari/537.36`

### Steps to reproduce

*Tell us how to reproduce this issue. If possible, push up a branch to your fork with a regression test we can run to reproduce locally.*

### Expected Behaviour

*Tell us what should happen.*

### Actual Behaviour

*Tell us what happens instead.*

**Comment by stucrompy** [comment]
i sent some ada from my eternl wallet to crypto.com which i have done in the past no problems. 
I sent some about a week ago i sent some on the 6th now its MILKada what a joke 
0x0A674D3bD6F1b37FF318D00C96F884D517C6E4ab

**Comment by vbaranov** [comment]
@stucrompy what is your issue with CSV? From which URL you tried to export it?

**Comment by rinor** [comment]
@vbaranov the op is complaining about smth else completely unrelated to Blockscout. It just happens that the involved product uses Blockscout and the csv download functionality is not enabled there. (although the issue title doesn't match op complaint, that is related to some wallet (eternl) issues)

---

@stucrompy if you are referring to [this tx](https://explorer-mainnet-cardano-evm.c1.milkomeda.com/tx/0xee7ab9bd960dc08c9f5c3b2b5b33bd8cd00b94f718fbab5416593c35dc7d2c70/internal-transactions) and haven't already, please contact the [proper team](https://www.milkomeda.com/community) to help you sort it out
