### ISSUE TITLE
mix compile error when installing dependencies

### ISSUE THREAD

**Issue by MaxTeiger** [blockscout/blockscout#5709]
I am trying to install blockscout on a GCP Virtual Machine. I am following the documentation, and when I get to the step 4, where I am supposed to run `mix do deps.get, local.rebar --force, deps.compile`, I get the following error : 

```bash
** (CompileError) config/config.exs:65: undefined function config_env/0
    (stdlib 4.0.1) lists.erl:1462: :lists.mapfoldl_1/3
    (elixir 1.10.3) expanding macro: Kernel.to_string/1
    config/config.exs:65: (file)
    (elixir 1.10.3) expanding macro: Config.import_config/1
    config/config.exs:65: (file)
```

### Environment

* Elixir & Erlang/OTP versions (`elixir -version`):
```bash
Erlang/OTP 25 [erts-13.0.2] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [jit:ns]

Elixir 1.10.3 (compiled with Erlang/OTP 22)
```

* Operating System:
```bash
PRETTY_NAME="Debian GNU/Linux 11 (bullseye)"
NAME="Debian GNU/Linux"
VERSION_ID="11"
VERSION="11 (bullseye)"
VERSION_CODENAME=bullseye
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
```

* Blockscout Version/branch: 
Tried on : 
    * https://github.com/blockscout/blockscout/commit/4b303c49b4ea57e7a0f73643bf5d9e83bdf88013
    * v4.1.5-beta
    * v4.1.4-beta

### Steps to reproduce

Just follow the steps in [Manual Deployment](https://docs.blockscout.com/for-developers/manual-deployment) till step 4. 

### Expected behaviour

`mix` should compile and install dependencies

### Actual behaviour

I get the following error : 
```bash
** (CompileError) config/config.exs:65: undefined function config_env/0
    (stdlib 4.0.1) lists.erl:1462: :lists.mapfoldl_1/3
    (elixir 1.10.3) expanding macro: Kernel.to_string/1
    config/config.exs:65: (file)
    (elixir 1.10.3) expanding macro: Config.import_config/1
    config/config.exs:65: (file)
```

**Comment by MaxTeiger** [comment]
Update : 

I updated my Elixir/Erlang version to : 
```bash
Erlang/OTP 25 [erts-13.0.2] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [jit:ns]
Elixir 1.13.4 (compiled with Erlang/OTP 24)
```

Now, I have a new error
```bash
/usr/lib/erlang/lib/parsetools-2.4/include/leexinc.hrl: no such file or directory
could not compile dependency :floki, "mix compile" failed. Errors may have been logged above. You can recompile this dependency with "mix deps.compile floki", update it with "mix deps.update floki" or clean it with "mix deps.clean floki"
```

I tried cleaning it, updating it and recompiling it but nothing seems to work, do you have any idea about how to solve this issue ? 

Thank you

**Comment by vbaranov** [comment]
@MaxTeiger the working combination would be:
Elixir 1.13.x
Erlang/OTP 24 (you should downgrade from 25 to 24)
Reference https://docs.blockscout.com/for-developers/information-and-settings/requirements

**Comment by MaxTeiger** [comment]
Thank you it worked using `asdf`.
