### ISSUE TITLE
Gnosis Chain: <Issue Title>

### ISSUE THREAD

**Issue by Pankaj0244** [blockscout/blockscout#5712]
*I bridge weth polygon (matic) chain on hop exchange but not received on gnosis chain. The transaction appear on polyscan but not shown on gnosis

Txid- 0x0bef579d42a638029df469af1d0fd62f7f86ff406a0555df29a93e7b83c58b61

Address- 0xc5764322968e0471770429df2e56d21ba36dd182

Contact- pankaj.surkule1710@gmail.com

**Comment by vbaranov** [comment]
@Pankaj0244 you should ask in Polygon Discord or in GC discord #gnosis-chain https://discord.gg/mPJ9zkq
