### ISSUE TITLE
Testnet: <Issue Title>

### ISSUE THREAD

**Issue by shastings8** [blockscout/blockscout#5715]
*Describe your issue here.*

### Environment
* Elixir Version: 1.12.2
* Erlang Version: 24
* BlockScout Version: 

* User Agent: `Mozilla/5.0 (iPhone; CPU iPhone OS 15_5 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Mobile/15E148`

### Steps to reproduce

*Tell us how to reproduce this issue. If possible, push up a branch to your fork with a regression test we can run to reproduce locally.*

### Expected Behaviour

*Tell us what should happen.*

### Actual Behaviour

*Tell us what happens instead.*

**Comment by shastings8** [comment]
Not able to use the burn fiction and rejects each time or several time. I’ve adjust gas fees but nothing is correcting and can only adjust the fees as much as it will allow me. I’m not understanding why it keeps getting rejected. Transaction ID 0xc10f3b6895838dfb20ed73419b4b3557c884bed9c8acde9d3a6180939bb9b217
This is one of the few and can see more from each transaction I placed. Thanks

**Comment by vbaranov** [comment]
Blockscout is not managing transactions. It is a tool for inspecting them.

**Comment by shastings8** [comment]
Sorry bout that but it the page it directed me to

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows
