### ISSUE TITLE
Blockscout UI doesn't display as expected

### ISSUE THREAD

**Issue by MaxTeiger** [blockscout/blockscout#5716]
My Blockscout UI doesn't behave as expected. 
When displaying block information, token name should be **POA** and it is **Ether**, the miner's name should be displayed, and it's not, decimals are round up.  

I played with env variables for a while, but didn't change anything. Do you know if we can change this without modifying the code ? 

Yours: 
* <img width="370" alt="image" src="https://user-images.githubusercontent.com/38110296/176681733-c4819596-0f41-4bc1-a32e-b21a4ae9fc86.png">
Mine : 
* <img width="370" alt="image" src="https://user-images.githubusercontent.com/38110296/176682392-61af8d56-231e-43f4-a96d-f5af78c07f5c.png">

### Environment

* Elixir & Erlang/OTP versions (`elixir -version`): Base docker image [bitwalker/alpine-elixir-phoenix:1.12](https://hub.docker.com/layers/alpine-elixir-phoenix/bitwalker/alpine-elixir-phoenix/1.12/images/sha256-672305ee6608bfc2ddb3f0cfacdda43cbf3ef3b791a6d6a7b6af5fa3e9c0fd8a?context=explore)
* Operating System: docker for debian
* Blockscout Version/branch: master branch commit 35d7887b620926122b43904b3517863fcc62aa5c

### Steps to reproduce

I deployed POA using docker on a Google Compute Engine with the following environment variables : 

Variable | Value |
---------|----------|
| MIX_ENV | prod |
| ETHEREUM_JSONRPC_VARIANT | parity |
| ETHEREUM_JSONRPC_HTTP_URL | http://******/ |
| ETHEREUM_JSONRPC_TRACE_URL | http://******/ |
| DATABASE_URL | postgresql://******ssl=false |
| NETWORK | POA |
| SUBNETWORK | Core |
| LOGO | /images/poa_logo.svg |
| LOGO_FOOTER | /images/poa_logo.svg |
| FAVICON | /images/poa_logo.svg |
| ETHEREUM_JSONRPC_TRANSPORT | http |
| SECRET_KEY_BASE | ****** |
| PORT | 80 |
| COIN | POA |
| COIN_NAME | POA |
| COINGECKO_COIN_ID | POA |
| METADATA_CONTRACT | 0xE3FfFD154931EB80b2aCE096EC32D6df23661203 |
| VALIDATORS_CONTRACT | 0xa105Db0e6671C7B5f4f350ff1Af6460E6C696e71 |
| ECTO_USE_SSL | false |
| CACHE_BLOCK_COUNT_PERIOD | 7200 |
| CACHE_TXS_COUNT_PERIOD | 7200 |
| CACHE_ADDRESS_COUNT_PERIOD | 7200 |
| CACHE_ADDRESS_SUM_PERIOD | 3600 |
| CACHE_TOTAL_GAS_USAGE_PERIOD | 3600 |
| CACHE_ADDRESS_TRANSACTIONS_GAS_USAGE_COUNTER_PERIOD | 1800 |
| CACHE_TOKEN_HOLDERS_COUNTER_PERIOD | 3600 |
| CACHE_TOKEN_TRANSFERS_COUNTER_PERIOD | 3600 |
| CACHE_ADDRESS_WITH_BALANCES_UPDATE_INTERVAL | 1800 |
| CACHE_AVERAGE_BLOCK_PERIOD | 1800 |
| CACHE_MARKET_HISTORY_PERIOD | 21600 |
| CACHE_ADDRESS_TRANSACTIONS_PERIOD | 1800 |
| CACHE_ADDRESS_TOKENS_USD_SUM_PERIOD | 1800 |
| CACHE_ADDRESS_TOKEN_TRANSFERS_COUNTER_PERIOD | 1800 |
| CACHE_BRIDGE_MARKET_CAP_UPDATE_INTERVAL | 1800 |
| CACHE_TOKEN_EXCHANGE_RATE_PERIOD | 1800 |
| TOKEN_METADATA_UPDATE_INTERVAL | 172800 |
| SHOW_PRICE_CHART | true |

### Expected behaviour

**Ether** token name should be replaced by **POA**
Decimals should be displayed
Miner's name should be displayed
 
### Actual behaviour

See issue description

Thank you for your time

**Comment by vbaranov** [comment]
@MaxTeiger in order to change the coin name you should follow this guide https://docs.blockscout.com/for-developers/developer-faqs/how-can-i-customize-the-coin-symbol

**Comment by vbaranov** [comment]
@MaxTeiger 

You should change 
```
METADATA_CONTRACT=0x0bc0EB3a1Ddc4ACC2515b72B7eB8A2F276EDa00F
```

Please take default.po and default.pot from:
https://github.com/blockscout/blockscout/blob/production-core-stg/apps/block_scout_web/priv/gettext/default.pot
https://github.com/blockscout/blockscout/blob/production-core-stg/apps/block_scout_web/priv/gettext/en/LC_MESSAGES/default.po

You should also set:
```
EMISSION_FORMAT=POA
```

I am closing this. Please let me know, how it goes after the changes.

**Comment by MaxTeiger** [comment]
It didn't work, but thank you ! I'll figure it out by myself 😄
