### ISSUE TITLE
Tracer accessed out of bound memory

### ISSUE THREAD

**Issue by salisbury-espinosa** [blockscout/blockscout#5718]
`Tracer accessed out of bound memory: available 576, offset 128, size 452 at callCustomOp (<eval>:218:25(71))    in server-side tracer function 'step'` for https://etherscan.io/tx/0x81478bbea1ada22d26b2b49ccd734c32bb926fdb798499648e5f9fecd19a2a17

**Comment by vbaranov** [comment]
@salisbury-espinosa  Does increasing `INDEXER_MEMORY_LIMIT` for the indexer resolve the issue?

The reference: https://docs.blockscout.com/for-developers/developer-faqs/how-do-i-update-memory-consumption-to-fix-indexer-memory-errors#updating-memory-consumption

**Comment by salisbury-espinosa** [comment]
> @salisbury-espinosa Does increasing INDEXER_MEMORY_LIMIT for the indexer resolve the issue?

these are unrelated things @vbaranov 

it is the script that does not work if it is sent simply to api
https://github.com/blockscout/blockscout/blob/master/apps/ethereum_jsonrpc/priv/js/ethereum_jsonrpc/geth/debug_traceTransaction/tracer.js

```js
const { readFileSync } = require("fs");
const path = require("path");
const axios = require("axios");

const gethTracer = readFileSync(path.join(__dirname, "./tracer.js")).toString(
  "utf8"
);

(async () => {
  const response = await axios.post(
    "http://127.0.0.1:8080",
    {
      method: "debug_traceTransaction",
      params: [
        "0x81478bbea1ada22d26b2b49ccd734c32bb926fdb798499648e5f9fecd19a2a17",
        {
          tracer: gethTracer,
          timeout: "30000ms",
        },
      ],
      id: 1,
    },
    {
      headers: { "content-type": "application/json" },
      timeout: 30000,
    }
  );
  console.log(response.data);
})();

```


result:

```js
{
  jsonrpc: '2.0',
  id: 1,
  error: {
    code: -32000,
    message: "Tracer accessed out of bound memory: available 576, offset 128, size 452 at callCustomOp (<eval>:217:25(71))    in server-side tracer function 'step'"
  }
}
```

Here is a complete javascript example (replace http://127.0.0.1:8080 with you env parametr) 
[test..tar.gz](https://github.com/blockscout/blockscout/files/9048539/test.tar.gz)

1. uncompress 
2. install nodejs
3. cd test
4. npm install
5. node index.js

**Comment by uniwswap** [comment]
any update on it?
