### ISSUE TITLE
Watchpack error

### ISSUE THREAD

**Issue by diucicd** [blockscout/blockscout#5728]
*Describe your issue here.*

### Environment

* Elixir & Erlang/OTP versions (`elixir -version`):
elixir --version
Erlang/OTP 24 [erts-12.3.1] [source] [64-bit] [smp:4:4] [ds:4:4:10] [async-threads:1] [jit]

Elixir 1.13.4 (compiled with Erlang/OTP 22)
* Operating System:
ubuntu 18.04
* Blockscout Version/branch: 
62211b7a3a51de0a54e957d93bba71ecf6dfea59
### Steps to reproduce

*Tell us how to reproduce this issue.  ❤️ if you can push up a branch to your fork with a regression test we can run to reproduce locally.*

### Expected behaviour

*Tell us what should happen.*

### Actual behaviour

*Tell us what happens instead.*
![image](https://user-images.githubusercontent.com/89781678/177506881-167d87c2-3c4c-4126-bd0e-6522aeda98d9.png)

**Comment by vbaranov** [comment]
Closing this issue due to no response
