### ISSUE TITLE
Klin block explorer: 0 transactions counted, yet positive balance

### ISSUE THREAD

**Issue by adv0r** [blockscout/blockscout#5738]
See it for yourself: https://explorer.kiln.themerge.dev/address/0xA3c8eEA403F101cB288C3B31335240017f690505/transactions 

I see 65 ETH balance, yet the explorer says 0 transactions

**Comment by vbaranov** [comment]
@adv0r thanks for noticing. This is a UX bug. That counter is for outgoing transactions. It makes sense to account all: outgoing/inbound transactions.
