### ISSUE TITLE
Verified contracts API (non-GraphQL) has incomplete information

### ISSUE THREAD

**Issue by haltman-at** [blockscout/blockscout#5746]
Hi!  So before I go describing this issue, I thought I'd give some background.  I'm the maintainer of [Truffle](https://github.com/trufflesuite/truffle/)'s debugger.  As you may be aware, we have a feature where when debugging a contract on one of various public blockchains (e.g. Ethereum mainnet), we will try looking up sources for the relevant contracts on Etherscan and Sourcify and downloading them for use in the debugger.  You'll notice I don't list Blockscout there; the reason is that when I looked into adding Blockscout support, I encountered a number of issues.  So, I'm filing this issue, and several others to follow (#5747, #5748, #5749); and hopefully if all this is resolved we can add Blockscout support!

(If you're curious, the actual code where the downloading occurs lives in [our source-fetcher package](https://github.com/trufflesuite/truffle/tree/develop/packages/source-fetcher)).

Anyway, let's start with this issue: The verified contracts API (the non-GraphQL one; I've filed #5747 about the GraphQL API) does not in all cases contain sufficient information to compile the original contract.  If you use unusual `settings`, beyond merely optimization on/off, number of runs, EVM version, and library addresses, these do not show up anywhere in the returned information.

Now, for the single-source Solidity and single-source Vyper case, this doesn't come up, as you don't have detailed control over the `settings` in the first place.

But for the standard JSON case, and for the metadata-and-sources case, this absolutely comes up.  Most of the `settings` are simply discarded and not returned in any form.

### Steps to reproduce

As an example, I've verified contract `0x4E030EF7EF55867a2278A181Ba25cbc04D4CC60C` on Sokol on Blockscout using metadata-and-sources.  If we make a query for its source code, well, you can see the result [here](https://blockscout.com/poa/sokol/api?module=contract&action=getsourcecode&address=0x4E030EF7EF55867a2278A181Ba25cbc04D4CC60C).

However, if you try to download that source and compile it with Solidity 0.6.8, you'll find that it does *not* match the bytecode on chain!  Why not?  Because I compiled it with `{ debug: { revertStrings: "debug" } }` turned on, that's why!  Now obviously that's an impractical example, one wouldn't normally deploy such a contract, but there are any more practical ways this same problem might occur (e.g., using the detailed optimizer settings, or telling Solidity to strip the metadata hash).

As an example for the standard JSON case, I've done the same thing [here](https://blockscout.com/poa/sokol/api?module=contract&action=getsourcecode&address=0x455f719213f4fe527498d5CE436F5D9AE1fafEF5) with address `0x455f719213f4fe527498d5CE436F5D9AE1fafEF5`.

Absolutely nothing in the returned result indicates these unusual settings, causing the problem.

Sourcify doesn't have this problem, because Sourcify gives us the metadata, which includes any unusual `settings`.  Meanwhile, Etherscan doesn't have this problem either, because Etherscan only allows unusual settings if you're using standard input JSON, in which case the response gives you the entire JSON, including the `settings`.  Blockscout, however, will allow to use unusual `settings` in the metadata-and-sources case, but then not actually return the metadata, or any other way of getting at the `settings`.

So, that's issue number one that I encountered.  On to issue number two!

**Comment by vbaranov** [comment]
@nikitosing let's store `settings` returned by Sourcify in Blockscout DB as well in order to cover this edge case? I suppose, it could be stored in a separate column of `smart_contracts` table. Then we could add the value from this column into UI and `getsourcecode` API endpoint response.

**Comment by haltman-at** [comment]
OK, now that I can verify standard JSON, it looks like the problem applies in that case too; I'll update the original issue.
