### ISSUE TITLE
Cannot verify contract with standard input JSON

### ISSUE THREAD

**Issue by haltman-at** [blockscout/blockscout#5748]
I mentioned in #5746 that I couldn't verify to what extent the issue existed for contracts verified with the standard input JSON method, and here's why.  Namely, I wasn't able to verify a contract with the standard input JSON method at all.

### Steps to reproduce

I've deployed a contract to address `0xd6637c81203E2227364D6421476AF6A0C21F37e3` on Sokol.  It was compiled using Solidity 0.6.8.  Assuming I've done everything correctly, it ought to verify with the following standard input JSON:

```json
{
  "language": "Solidity",
  "sources": {
    "ExternalTestJson.sol": {
      "content": "//SPDX-License-Identifier: MIT\r\npragma solidity ^0.6.8;\r\n\r\nimport \"./ExternalTestLibraryJson.sol\";\r\n\r\ncontract ExternalTestJson {\r\n\r\n  address[] stack;\r\n\r\n  function identity(address input) public returns (address) {\r\n    stack.push(input);\r\n    return ExternalTestLibraryJson.pop(stack);\r\n  }\r\n\r\n}"
    },
    "ExternalTestLibraryJson.sol": {
      "content": "//SPDX-License-Identifier: MIT\r\npragma solidity ^0.6.8;\r\n\r\nlibrary ExternalTestLibraryJson {\r\n  function pop(address[] storage list) external returns (address out) {\r\n    out = list[list.length - 1];\r\n    list.pop();\r\n  }\r\n}"
    }
  },
  "settings": {
    "remappings": [],
    "libraries": {
      "ExternalTestJson.sol": {
        "ExternalTestLibraryJson": "0x2375DfcB3a4c0d88260B2A689B5ec8956F3f98FF"
      }
    }
  }
}
```

You'll notice I didn't use any unusual `settings` here at all.

You can attempt to verify the contract [here](https://blockscout.com/poa/sokol/address/0xd6637c81203E2227364D6421476AF6A0C21F37e3/verify-via-standard-json-input/new).  Set name to `ExternalTestJson`, compiler verison to Solidity 0.6.8, and use the JSON above.  For constructor arguments, the problem occurs both ways (note that the contract takes no constructor arguments).

### Expected behaviour

The contract should verify.

### Actual behaviour

I get the error message `There was an error validating your contract, please try again.`

**Comment by rimrakhimov** [comment]
@haltman-at Thank you for your research. I have noticed a small problem with the standard JSON you provided and would be glad to get your opinion on that.

Before version 0.8.6 omitting the 'enabled' key was not equivalent to setting it to false and would actually disable all the optimizations (https://docs.soliditylang.org/en/v0.8.16/using-the-compiler.html#input-description). From the bytecode deployed, the contract you provided has been compiled with `optimzer.enabled=false`. In your standard JSON input example you have omitted `optimzer.enabled` key though, thus, feeding that standard JSON input into the compiler should result in a different bytecode. 

Etherscan though seems to ignore that difference and to automatically add `optimizer.enabled=false` value if it is missing from the standard JSON. That creates a problem if the contract was compiled with `optimizer.enabled` completely omitted. In that case, it seems impossible to verify the contract using Etherscan. As an example, https://ropsten.etherscan.io/address/0x3c5e4a6323091aee0001b373ee2ae726b56034e8#code was compiled with usual remix settings (`optimizer.enabled=false`) and we could verify it given JSON you provided. But https://ropsten.etherscan.io/address/0x529dda5592e7c84c27270d5f4ddd276ca4383eb9#code contains exactly the same contract but compiled with omitted `optimizer.enabled` setting, and I could not find any way to verify it.

We have though about trying to compile contracts with both `optimizer.enabled=false` and `optimizer.enabled` omitted values, in case if it is not present in provided standard JSON input. In case if contract could be verified with `optimizer.enabled=false` value we would append it in that JSON which would be further returned on requests of sources. Would that behavior be correct for your use cases?

**Comment by haltman-at** [comment]
Oh, fascinating!  I wasn't aware of that distinction.  I'll take a look.

**Comment by haltman-at** [comment]
So, I think this is a problem on our end (and Etherscan's too, of course).  It looks to me like Truffle will also by default set `enabled: false` if it's omitted.  Going by what you said, that seems to be a potential problem; I guess we're lucky that Etherscan made the same incorrect decision.  I don't think we can in general change that without breaking things, but we can probably change it in the relevant cases here.

In the meantime, it looks like there probably isn't an issue on your end.  Possibly you might want to do some of the above, I don't know; that may just be for you to figure out...

Of course, I'll need to try actually re-verifying the contract (after adjusting the JSON input) to make sure.  And I may then end up having to update #5746 as a result!  We'll see.  But thanks for alerting me to this problem, I had no idea!

**Comment by haltman-at** [comment]
OK, it verified!  Thanks again!  Now to go test an example with weird settings and see if I need to update #5746 to cover the JSON case. :)

**Comment by fainashalts** [comment]
Hi [rimrakhimov](https://github.com/rimrakhimov)! I'm working on adding Blockscout support to Truffle right now and I've been unable to reproduce the optimizer settings issue Harry brings up here. Apologies if this is the wrong place to ask as the issue is closed, but I was wondering if you all did something on your end to address? Just want to be sure I'm not missing anything as I work on this. Thanks!

**Comment by rimrakhimov** [comment]
@fainashalts Hi! We are glad to see that adding Blockscout support to Truffle is in an active phase again and would be glad to help with any arising questions. Feel free to ask them here or create new issues :)

Regarding this PR, we have not changed anything. I believe the problem still should be there if you try to verify the contract compiled with `enabled: false` optimization with standard json where that parameter is missing.

**Comment by fainashalts** [comment]
Hi @rimrakhimov thank you so much for the response. I see the issue now, as described. :) 

I have a follow-up question, if you don't mind (I can go test this manually but I suspect you know this!). Does Blockscout return the same data in the same format from the `?module=contract` API call regardless of the way in which a user submits their contract for verification (meaning, the various options [here](https://docs.blockscout.com/for-users/verifying-a-smart-contract)? Thanks!
