### ISSUE TITLE
coin_name not changing

### ISSUE THREAD

**Issue by zeus-dev** [blockscout/blockscout#5752]
*Describe your issue her
I changed COIN_NAME= mycoin for my custom blockchain, but still showing ether in currency name in explorer, how can  i change it to custom coin name?

### Environment

* Elixir & Erlang/OTP versions (`elixir -version`): 1.12
* Operating System: ubuntu 20.04
* Blockscout Version/branch: 4.1.5

### Steps to reproduce

*Tell us how to reproduce this issue.  ❤️ if you can push up a branch to your fork with a regression test we can run to reproduce locally.*

### Expected behaviour

*Tell us what should happen.*

### Actual behaviour

*Tell us what happens instead.*

**Comment by vbaranov** [comment]
Here is the guide https://docs.blockscout.com/for-developers/developer-faqs/how-can-i-customize-the-coin-symbol
