### ISSUE TITLE
 Error: (Awaiting internal transactions for reason)

### ISSUE THREAD

**Issue by sadhellkill** [blockscout/blockscout#5753]
Hi we are facing this error ?

https://songbird-explorer.flare.network/tx/0xfb4aac7b0c7b5bdbe717207fd76f972ee040584ddd94e074f72fd86c9ccd5df9/internal-transactions

Its happening to some not all unstake NFTs. Please advise asap its very urgent

*Describe your issue here.*

### Environment

* Elixir & Erlang/OTP versions (`elixir -version`):
* Operating System:
* Blockscout Version/branch: 

### Steps to reproduce

*Tell us how to reproduce this issue.  ❤️ if you can push up a branch to your fork with a regression test we can run to reproduce locally.*

### Expected behaviour

*Tell us what should happen.*

### Actual behaviour

*Tell us what happens instead.*

**Comment by vbaranov** [comment]
Internal transactions have been collected, as far as I see from the link above. Status has been changed.
