### ISSUE TITLE
Top banner has disappeared

### ISSUE THREAD

**Issue by MaxTeiger** [blockscout/blockscout#5756]
At the top of the blockscout page I deployed, there was a banner like this one, stipulating the progress in indexing the blockchain in the DB. (in yellow)  
<img width="1792" alt="image" src="https://user-images.githubusercontent.com/38110296/179470681-40037327-6ad4-4103-9226-c09084d78563.png">

Only, from one day to the next, this banner disappeared, and I can't follow the progress of the blockchain indexing in my DB anymore. 
I don't think the indexing of the blockchain is complete, (I only have 89,000 wallets and 44,711,303 transactions displayed in blockscout interface for POA Core). 

### Environment

* Elixir & Erlang/OTP versions (elixir -version): Base docker image [bitwalker/alpine-elixir-phoenix:1.12](https://hub.docker.com/layers/alpine-elixir-phoenix/bitwalker/alpine-elixir-phoenix/1.12/images/sha256-672305ee6608bfc2ddb3f0cfacdda43cbf3ef3b791a6d6a7b6af5fa3e9c0fd8a?context=explore)
* Operating System: docker for debian
* Blockscout Version/branch: master branch commit https://github.com/blockscout/blockscout/commit/35d7887b620926122b43904b3517863fcc62aa5c

### Steps to reproduce
Deploy blockscout, after few days the banner disappeared by itself.

### Expected behaviour
The banner keeps showing till the indexing of the blockchain is complete

### Actual behaviour
The banner disappeared, and I don't know indexation status of my blockchain anymore.

**Comment by vbaranov** [comment]
@MaxTeiger Banner is disappeared when internal transactions have been fetched for the block with number from `TRACE_FIRST_BLOCK` environment variable or 0 block number. You can also monitor indexing process on the DB level https://docs.blockscout.com/for-developers/indexing#monitoring-indexing-processes. I am closing this issue. Please let me know if you have further questions.
