### ISSUE TITLE
DB Connection Issues with blockscout

### ISSUE THREAD

**Issue by spunkyshooter** [blockscout/blockscout#5758]
Not able to start application since DB connection fails when used with blockscout.

We want to use Blockscout explorer for our Blockchain and wanted to TEST whether it works fine on cloud or not. 

Used AWS RDS 
Engine: PostgreSQL
Size: db.t3.micro
Port: 5432
Publicly Exposed, has VPC, Security groups has inbound rule allowing 5432 port from my source IP

The DB is able to connect when tested out separately using standalone python script.
```
import psycopg2
try:
    db = psycopg2.connect("dbname='explorer' user='postgres' host='database-1.REDACTED.us-east-1.rds.amazonaws.com' password='<REDACTED**>'")
except:
    exit(1)

exit(0)
```

but when DB is tested with blockscout application, got this error
```
** (Mix) The database for Explorer.Repo couldn't be created: connection not available and request was dropped from queue after 2000ms. This means requests are coming in and your connection pool cannot serve them fast enough. You can address this by:

  1. Ensuring your database is available and that you can connect to it
  2. Tracking down slow queries and making sure they are running fast enough
  3. Increasing the pool_size (albeit it increases resource consumption)
  4. Allowing requests to wait longer by increasing :queue_target and :queue_interval

See DBConnection.start_link/2 for more information
```

```
config :explorer, Explorer.Repo,
  url: System.get_env("DATABASE_URL"),
  pool_size: pool_size,
  ssl: String.equivalent?(System.get_env("ECTO_USE_SSL") || "true", "true"),
  prepare: :unnamed,
  timeout: :timer.seconds(300),
  queue_target: 5000,
  queue_interval: 100_000

```

but got error:
```
03:17:07.377 [error] GenServer #PID<0.740.0> terminating
** (DBConnection.ConnectionError) tcp connect (database-1.REDACTED.us-east-1.rds.amazonaws.com:5432): connection timed out - :etimedout
    (db_connection 2.4.0) lib/db_connection/connection.ex:100: DBConnection.Connection.connect/2
    (connection 1.1.0) lib/connection.ex:622: Connection.enter_connect/5
    (stdlib 3.17) proc_lib.erl:226: :proc_lib.init_p_do_apply/3
Last message: nil
State: Postgrex.Protocol

03:19:18.441 [error] GenServer #PID<0.747.0> terminating
** (DBConnection.ConnectionError) tcp connect (database-1.REDACTED.us-east-1.rds.amazonaws.com:5432): connection timed out - :etimedout
    (db_connection 2.4.0) lib/db_connection/connection.ex:100: DBConnection.Connection.connect/2
    (connection 1.1.0) lib/connection.ex:622: Connection.enter_connect/5
    (stdlib 3.17) proc_lib.erl:226: :proc_lib.init_p_do_apply/3
Last message: nil
State: Postgrex.Protocol
** (Mix) The database for Explorer.Repo couldn't be created: killed

```

### Environment

* Elixir & Erlang/OTP versions (`elixir -version`):
* Operating System: linux
* Blockscout Version/branch: master, commit: 4e5ac69d8

### Steps to reproduce

*Tell us how to reproduce this issue.  ❤️ if you can push up a branch to your fork with a regression test we can run to reproduce locally.*

### Expected behaviour

*Tell us what should happen.*
Expected to have DB Alarams. 

### Actual behaviour

*Tell us what happens instead.*
Fails with DB Connection errors

**Comment by vbaranov** [comment]
@spunkyshooter 
Try to connect to the DB with the connection string in `DATABASE_URL` env variable via, for instance, psql from the application server.

**Comment by spunkyshooter** [comment]
Thanks for the direction, issue is fixed now, there was issue with Security Group Rules.
