### ISSUE TITLE
Palm: <Issue Title> Never received DAI tokens

### ISSUE THREAD

**Issue by lmdd1035** [blockscout/blockscout#5766]
*Describe your issue here.*
I sent dai from palm wallet to my metamask wallet it said it was confirmed but i never received pls help!!!!!!!
### Environment
* Elixir Version: 1.13.1
* Erlang Version: 24
* BlockScout Version: 

* User Agent: `Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.0.0 Safari/537.36`

### Steps to reproduce

*Tell us how to reproduce this issue. If possible, push up a branch to your fork with a regression test we can run to reproduce locally.*

### Expected Behaviour

*Tell us what should happen.*

### Actual Behaviour

*Tell us what happens instead.*

**Comment by vbaranov** [comment]
Here is no Palm support
