### ISSUE TITLE
Blockscout fails to sync with Polygon Edge PoA

### ISSUE THREAD

**Issue by gufranco** [blockscout/blockscout#5775]
*Blockscout fails to sync with Polygon Edge PoA*

### Environment

* Elixir & Erlang/OTP versions (`elixir -version`): bitwalker/alpine-elixir-phoenix:1.13
* Operating System: Alpine
* Blockscout Version/branch: v4.1.5-beta

### Steps to reproduce

Start the application and let it start syncing with Polygon Edge PoA

### Expected behaviour

Blockscout should sync properly and continue working without crashing.

### Actual behaviour

Blockscout crashes after syncing for a few minutes and starts giving **Internal Server Error**. There is also the error *(-32601) the method trace_block does not exist/is not available* in the logs.

**Comment by vbaranov** [comment]
@gufranco polygon-edge is unsupported from the box. In regards `trace_block` JSON RPC method - if it is unsupported on polygon-edge, you can disable it by setting `INDEXER_DISABLE_BLOCK_REWARD_FETCHER=true` environment variable.

**Comment by gufranco** [comment]
@vbaranov thank you! It's not crashing anymore, but now I'm getting the error message below.

`the method trace_replayBlockTransactions does not exist/is not available`

**Comment by vbaranov** [comment]
@gufranco you should also set `INDEXER_DISABLE_INTERNAL_TRANSACTIONS_FETCHER=true`, since `trace_replayBlockTransactions` method is unsupported on the polygon-edge side.

**Comment by gufranco** [comment]
Hi, @vbaranov. Thank you! It solved the error message, but now I'm getting another error message. Do you know all the environment vars that I should set?

`mia [info] 2022-07-28T14:45:44.063 application=indexer fetcher=pending_transaction [error] %{code: -32601, message: "the method parity_pendingTransactions does not exist/is not available"}`

**Comment by vbaranov** [comment]
@gufranco no, I don't know the full set of environments since `polygon-edge` is officially unsupported. In order to disable pending transactions fetcher, you should set `INDEXER_DISABLE_PENDING_TRANSACTIONS_FETCHER=true`

**Comment by gufranco** [comment]
Thank you, @vbaranov! I'm testing it again to check if the error messages will stop 🤞🏻 I just asked if you know all the environment vars to avoid pinging you here several times.

**Comment by vbaranov** [comment]
@gufranco how it goes? Do new errors appear?

**Comment by gufranco** [comment]
@vbaranov There aren't new errors related to methods not existing, but now I'm constantly seeing the error below

`0x0000000000000000000000000000000000000000@񠅄: (-32600) failed to get header from block hash or block number`

**Comment by gufranco** [comment]
Hi, @vbaranov. Are you guys offering paid support?

**Comment by vbaranov** [comment]
Sorry for the late response. Yes, we provide hosting opportunity. https://docs.blockscout.com/for-projects/premium-features/your-chain-on-blockscout.com#hosting-your-chain-on-blockscout.com. I am closing this issue for now. If you still have further requests, please let me know.
