### ISSUE TITLE
tokens wont load. just thinks for hoursTestnet: <Issue Title>

### ISSUE THREAD

**Issue by justlearning12** [blockscout/blockscout#5776]
*Describe your issue here.*

### Environment
* Elixir Version: 1.12.2
* Erlang Version: 24
* BlockScout Version: 

* User Agent: `Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.0.0 Safari/537.36`

### Steps to reproduce

*Tell us how to reproduce this issue. If possible, push up a branch to your fork with a regression test we can run to reproduce locally.*

### Expected Behaviour

*Tell us what should happen.*

### Actual Behaviour

*Tell us what happens instead.*

**Comment by vbaranov** [comment]
@justlearning12 
Could you add more context to the issue?
- Which chain (URL to the Blockscout instance)?
- Where token are not loaded (URL, screenshot)?

**Comment by vbaranov** [comment]
Closed due to no feedback
