### ISSUE TITLE
Miner address displaying 0x000... address instead of the actual validator node address

### ISSUE THREAD

**Issue by apquinit** [blockscout/blockscout#5781]
Miner address displaying 0x000... address instead of the actual validator node address

### Environment

* Elixir & Erlang/OTP versions (`elixir -version`): esl-erlang=1:24.* elixir=1.12.*
* Operating System: Ubuntu 20.04
* Blockscout Version/branch: v4.1.5-beta

### Steps to reproduce
1. Create a network and environment on Kaleido (https://www.kaleido.io)
2. Use Geth / PoA
3. Deploy self-hosted blockscout instance.
4. Connect Blockscout using JSON-RPC.
5. Visually check mining, shows 0x000 address instead of the validator node address.

### Expected behaviour
*Tell us what should happen.*
Miner node address should display.

*Tell us what happens instead.*
0x000.. adress displayed instead.

_Screenshot:_
![image](https://user-images.githubusercontent.com/16703483/181835368-8bed8108-92c7-4f70-8976-2531c472ab75.png)

**Comment by vbaranov** [comment]
@apquinit did you set `BLOCK_TRANSFORMER=clique`? If no, please do that. Geth utilises clique consensus for PoA chains.

**Comment by apquinit** [comment]
worked like charm, thanks!
