### ISSUE TITLE
Palm: QR Code is invalid 

### ISSUE THREAD

**Issue by KJM1111** [blockscout/blockscout#5782]
Hello, I noticed that the QR code displayed here(attached)[https://explorer.palm.io/token/0x769f8198a118068a42a7e02a22c0c3be455f84c0/instance/76191892872738138585453167353127130928400460683908039091630326044373782519238/token-transfers](url) returns an error when trying to use.  "This site can't be reached localhost is currently unreachable. ERR_CONNECTION_FAILED"

### Environment
* Elixir Version: 1.13.1
* Erlang Version: 24
* BlockScout Version: 
![image_123986672](https://user-images.githubusercontent.com/100097542/181838751-027964a4-bb49-4db0-9d96-6590f0865956.JPG)

* User Agent: `Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleW
![Batman QR Code v2](https://user-images.githubusercontent.com/100097542/181838492-83b3df2f-a2bb-43fc-885e-ed608f90ad96.png)
ebKit/537.36 (KHTML, like Gecko) Chrome/103.0.0.0 Safari/537.36`

### Steps to reproduce

*Tell us how to reproduce this issue. If possible, push up a branch to your fork with a regression test we can run to reproduce locally.*

### Expected Behaviour

*Tell us what should happen.*

### Actual Behaviour

*Tell us what happens instead.*
![image_123986672](https://user-images.githubusercontent.com/100097542/181838776-d006fcd5-2d4f-4744-ac7d-cc1220787303.JPG)

**Comment by vbaranov** [comment]
@KJM1111  Blockscout team dosn't manage Palm instance of Blockscout. Please advice Palm team to set `BLOCKSCOUT_HOST=https://explorer.palm.io` environment varaible. This should be enough to resolve the issue.

**Comment by skenaja** [comment]
@KJM1111 FYI this has now been fixed on the Palm instance of Blockscout

**Comment by KJM1111** [comment]
Thanks!
