### ISSUE TITLE
Ethereum Classic: <Issue Title>

### ISSUE THREAD

**Issue by pol0000** [blockscout/blockscout#5785]
*Describe your issue here.*
Hi , i sent 1.95 Etc to the exchange coinbase from my coinbase wallet. The transaction has been described as succesful but it is pending. This is the adress of the transaction : 0x7dba9d2eff95b98ddb8925830f3f016d71c8d75b8f6679fa889e7a9b48821ea3
Have a good day, 
Paul 

### Environment
* Elixir Version: 1.13.1
* Erlang Version: 24
* BlockScout Version: v4.1.5-beta

* User Agent: `Mozilla/5.0 (iPhone; CPU iPhone OS 15_5 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/15.5 Mobile/15E148 Safari/604.1`

### Steps to reproduce

*Tell us how to reproduce this issue. If possible, push up a branch to your fork with a regression test we can run to reproduce locally.*

### Expected Behaviour

*Tell us what should happen.*

### Actual Behaviour

*Tell us what happens instead.*

**Comment by vbaranov** [comment]
You should ask in Ethereum Classic Discord https://discord.com/invite/bMGuZsA
