### ISSUE TITLE
Optimism Goerli: Verify code hangs in loading state forever.

### ISSUE THREAD

**Issue by afa7789** [blockscout/blockscout#5792]
I can't verify the code with flattened solidity text

### Environment
* Elixir Version: 1.13.1
* Erlang Version: 24
* BlockScout Version: v4.1.5-beta

* User Agent: `Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.0.0 Safari/537.36`

### Steps to reproduce

I compiled and deployed to the optimism göerli with REMIX IDE in browser.

tx hash: 0xbaffc3f8af38861c7d67419724806e8c73c1216c31fa599940196c8c9acac6de

Tried to add code here:
https://blockscout.com/optimism/goerli/address/0xC8315CC7DCDF57476a8a1D184505845d52711024/verify-via-flattened-code/new

infos that I used to add:

contract address: 0xC8315CC7DCDF57476a8a1D184505845d52711024
contract name: multicall
compiler: v0.8.7
evm: default
optimization: yes
optimizations runs: 200

<details>
<summary>
Code :
</summary>
<code>
pragma solidity >=0.5.0;
pragma experimental ABIEncoderV2;

/// @title Multicall - Aggregate results from multiple read-only function calls
/// @author Michael Elliot <mike@makerdao.com>
/// @author Joshua Levine <joshua@makerdao.com>
/// @author Nick Johnson <arachnid@notdot.net>

contract Multicall {
    struct Call {
        address target;
        bytes callData;
    }

    function aggregate(Call[] memory calls) public returns (uint256 blockNumber, bytes[] memory returnData) {
        blockNumber = block.number;
        returnData = new bytes[](calls.length);
        for (uint256 i = 0; i < calls.length; i++) {
            (bool success, bytes memory ret) = calls[i].target.call(calls[i].callData);
            require(success);
            returnData[i] = ret;
        }
    }

    // Helper functions
    function getEthBalance(address addr) public view returns (uint256 balance) {
        balance = addr.balance;
    }

    function getBlockHash(uint256 blockNumber) public view returns (bytes32 blockHash) {
        blockHash = blockhash(blockNumber);
    }

    function getLastBlockHash() public view returns (bytes32 blockHash) {
        blockHash = blockhash(block.number - 1);
    }

    function getCurrentBlockTimestamp() public view returns (uint256 timestamp) {
        timestamp = block.timestamp;
    }

    function getCurrentBlockDifficulty() public view returns (uint256 difficulty) {
        difficulty = block.difficulty;
    }

    function getCurrentBlockGasLimit() public view returns (uint256 gaslimit) {
        gaslimit = block.gaslimit;
    }

    function getCurrentBlockCoinbase() public view returns (address coinbase) {
        coinbase = block.coinbase;
    }
}
</code>
</details>

### Expected Behaviour

It should verify the code and go next page or open a modal.

### Actual Behaviour

The button stay in a spinloader state forever ( waited more then 1 hour ) 
![image](https://user-images.githubusercontent.com/26887703/182502056-4978d13b-faa6-4d45-99ee-8754ec139f43.png)

**Comment by rimrakhimov** [comment]
@afa7789 I was able to verify the contract by source code you provided. You could check on the explorer page 

The problem was that deployed contract was compiled without optimizations, and it actually could not be verified with parameters you provided. Due to too long processing the connection with the server had being dropped and you did not get the response with failure. We are currently working on the processing time required for verification, so the problem should be fixed in the nearest future

**Comment by slendermaan** [comment]
Why is this question closed, so far I also have this problem. I am using standard json format validation
[Contract](https://blockscout.com/etc/mordor/address/0x4783AEC357bf026A7276314b45CF57D54737ff37)
<img width="1071" alt="image" src="https://user-images.githubusercontent.com/21294029/196020871-b575c53d-c418-4fb0-ad2a-d2d1a6dfb138.png">

```
{
    "language": "Solidity",
    "sources": {
        "test.sol": { "content": "pragma solidity 0.5.17;\nimport \"./LibraryForTest2.sol\";\ncontract test {\n    event Transfer(uint value);\n    function get () public returns(uint) {\n        emit Transfer(LibraryForTest2.get3());\n        return LibraryForTest2.get3();    \n    }\n}"},
        "LibraryForTest2.sol": {"content": "pragma solidity 0.5.17;\nlibrary LibraryForTest2 {\n    function get3() public pure returns(uint) {\n        return 4;\n    }\n}"}
    },
    "settings": {
      "libraries": {
        "test.sol:test": {
          "LibraryForTest2": "0xb4B50a170903c4f62dBBb2EDb02dA35F76ef18cA"
        }
      },
      "metadata": {
        "useLiteralContent": true
      },
      "optimizer": {
        "enabled": false
      },
      "remappings": []
    }
}
```
<img width="329" alt="image" src="https://user-images.githubusercontent.com/21294029/196020878-c8202f0c-7ccb-494d-91f6-47b9c510e74f.png">
