### ISSUE TITLE
0xb635be96898552bbe80043239c57ea864223fdc1

### ISSUE THREAD

**Issue by greg9762** [blockscout/blockscout#5795]

**Comment by greg9762** [comment]
Just pending

**Comment by vbaranov** [comment]
@greg9762 What is the issue with Blockscout?

**Comment by greg9762** [comment]
I guess I just don't know how to use it. I have pending transactions and don't know how to fix them.Thanks

**Comment by vbaranov** [comment]
This is not related to Blockscout. Probably, this would be helpful to you https://metamask.zendesk.com/hc/en-us/articles/360015489251-How-to-Speed-Up-or-Cancel-a-Pending-Transaction.
