### ISSUE TITLE
Animated banner for Blockscout

### ISSUE THREAD

**Issue by tgladilina** [blockscout/blockscout#5802]
**text**

Blockscout - your portal to the multi-chain universe!
Blockscout is a public good for web3.
Help fund Blockscout’s open source development and support explorer diversity today.
[Fund now]

**Comment by tgladilina** [comment]
Banners are ready. We could use both variants or please choose one. 
@ulyanas 


![Image](https://user-images.githubusercontent.com/103045386/183034458-c17da872-b7c3-4ea4-985a-d6d061aa56a3.gif)
![Image](https://user-images.githubusercontent.com/103045386/183034459-afae7686-f182-4c1c-b837-22f3a2ca1316.gif)

**Comment by Paty1283** [comment]
> **text**
> 
> Blockscout - your portal to the multi-chain universe! Blockscout is a public good for web3. Help fund Blockscout’s open source development and support explorer diversity today. [Fund now]

**Comment by tgladilina** [comment]
@Paty1283 
Hi, 
Do you mean to  update 1st banner, right?

**Comment by tgladilina** [comment]
Need retina ready size

**Comment by tgladilina** [comment]
Retina ready banner (3x)
