### ISSUE TITLE
Error in compiling

### ISSUE THREAD

**Issue by jjhesk** [blockscout/blockscout#5805]
*Describe your issue here.*

### Environment

* Elixir & Erlang/OTP versions (`elixir -version`): 
Erlang/OTP 24 [erts-12.1.5] [source] [64-bit] [smp:4:4] [ds:4:4:10] [async-threads:1] [jit]
Elixir 1.14.0-rc.0 (777a11d) (compiled with Erlang/OTP 24)

* Operating System: centos 8 stream
* Blockscout Version/branch: v4.1.7-beta

### Steps to reproduce

I do
`mix do deps.get, local.rebar --force, deps.compile`

Result:
```
warning: the VM is running with native name encoding of latin1 which may cause Elixir to malfunction as it expects utf8. Please ensure your locale is set to UTF-8 (which can be verified by running "locale" in your shell)
==> prometheus_ex
Compiling 19 files (.ex)

== Compilation error in file lib/prometheus/registry.ex ==
** (UndefinedFunctionError) function Kernel.Utils.defdelegate/2 is undefined or private. Did you mean:

      * defdelegate_all/3
      * defdelegate_each/2

    (elixir 1.14.0-rc.0) Kernel.Utils.defdelegate({:exists, [line: 21], [{:name, [line: 21], nil}]}, [])
    lib/prometheus/registry.ex:21: (module)
could not compile dependency :prometheus_ex, "mix compile" failed. Errors may have been logged above. You can recompile this dependency with "mix deps.compile prometheus_ex", update it with "mix deps.update prometheus_ex" or clean it with "mix deps.clean prometheus_ex"
```

**Comment by nikitosing** [comment]
@jjhesk Did you set ENV variables? I think the problem in empty `DATABASE_URL` variable

**Comment by vbaranov** [comment]
@jjhesk could you downgrade Elixir to 1.13.x. 1.14.x is not officially supported yet https://github.com/blockscout/blockscout/issues/5789.

**Comment by vbaranov** [comment]
I am closing this. @jjhesk let us know if you still have the issue.
