### ISSUE TITLE
Issues with Gnosis safe contracts deployment (Astar instance)

### ISSUE THREAD

**Issue by ulyanas** [blockscout/blockscout#5862]
We have Gnosis safe now deployed on Astar (For multisig and other funcs). They can't verify the contract since the contract itself is deployed by proxy.
Here is what they say:

there is an issue in Blockscout - it doesn't recognize smart contracts that were deployed via proxy and not via createContract function. Therefore we cannot verify contract code on the Astar block explorer at this moment.
For example, this is one of the contracts, and Blockscout treat it as an EOA [https://blockscout.com/astar/address/0x3E5c63644E683549055b9Be8653de26E0B4CD36E](https://blockscout.com/astar/address/0x3E5c63644E683549055b9Be8653de26E0B4CD36E)

Would you be able to enable contract verification for contracts using Deterministic Deployment Proxy ([https://github.com/Arachnid/deterministic-deployment-proxy/blob/master/source/deterministic-deployment-proxy.yul](https://github.com/Arachnid/deterministic-deployment-proxy/blob/master/source/deterministic-deployment-proxy.yul)). It is deployed here - [https://blockscout.com/astar/address/0x4e59b44847b379578588920cA78FbF26c0B4956C/contracts#address-tabs](https://blockscout.com/astar/address/0x4e59b44847b379578588920cA78FbF26c0B4956C/contracts#address-tabs),

**Comment by vbaranov** [comment]
Smart-contract is not recognized because tracing is unavailable on Astar node. Once tracing will be enabled, Blockscout will be able to fetch internal transactions and thus recognize the address as smart-contract.

**Comment by vbaranov** [comment]
The issue resolved by implementing [on-demand contract codes fetcher](https://github.com/blockscout/blockscout/pull/9708).
