### ISSUE TITLE
Compiling lib/ex_keccak.ex too long no response

### ISSUE THREAD

**Issue by Ztl36** [blockscout/blockscout#5880]
*Describe your issue here.*

### Environment

* Elixir & Erlang/OTP versions (`elixir -version`):V13.0.3
* Operating System:ubuntu 20.04
* Blockscout Version/branch: [BlockScout v4.1.7-beta](https://github.com/blockscout/blockscout/releases/tag/v4.1.7-beta)

`mix do deps.compile `
Stuck Compiling lib/ex_keccak.ex (it's taking more than 10s)
```
===> Analyzing applications...
===> Compiling mimerl
===> Analyzing applications...
===> Compiling ranch
make: Entering directory '/root/blockscout/deps/prometheus_process_collector/c_src'
make: '/root/blockscout/deps/prometheus_process_collector/c_src/../priv/prometheus_process_collector.so' is up to date.
make: Leaving directory '/root/blockscout/deps/prometheus_process_collector/c_src'
===> Analyzing applications...
===> Compiling prometheus_process_collector
===> Analyzing applications...
===> Compiling certifi
==> ex_keccak
Compiling 1 file (.ex)
    Blocking waiting for file lock on package cache
Compiling lib/ex_keccak.ex (it's taking more than 10s)
```

**Comment by vbaranov** [comment]
> Elixir & Erlang/OTP versions (elixir -version):V13.0.3

@Ztl36 please upgrade to Elixir 1.13.4 and Erlang OTP version should be 24 (not more).

**Comment by Ztl36** [comment]
@vbaranov  Thank you. I solved it after upgrading the version.

**Comment by psipherious** [comment]
> > Elixir & Erlang/OTP versions (elixir -version):V13.0.3
> 
> @Ztl36 please upgrade to Elixir 1.13.4 and Erlang OTP version should be 24 (not more).

Attempting to install 1.13.4 on Debian 10 states that OTP 25 is required.
Only 1.13.0 is able to be installed if one wishes to remain on OTP 24.

root@deb10-builder:~# dpkg -i elixir_1.13.4-1~debian~buster_all.deb
(Reading database ... 57093 files and directories currently installed.)
Preparing to unpack elixir_1.13.4-1~debian~buster_all.deb ...
Unpacking elixir (1.13.4-1) over (1.13.0-1) ...
dpkg: dependency problems prevent configuration of elixir:
 elixir depends on erlang-base (>= 1:25.0.3) | erlang-base-hipe (>= 1:25.0.3) | esl-erlang (>= 1:25.0.3); however:
  Package erlang-base is not installed.
  Package erlang-base-hipe is not installed.
  Version of erlang-base-hipe on system, provided by esl-erlang:amd64, is <none>.
  Version of esl-erlang on system is 1:24.3.3-1.
 elixir depends on erlang-crypto (>= 1:25.0.3) | esl-erlang (>= 1:25.0.3); however:
  Package erlang-crypto is not installed.
  Version of erlang-crypto on system, provided by esl-erlang:amd64, is <none>.
  Version of esl-erlang on system is 1:24.3.3-1.
 elixir depends on erlang-inets (>= 1:25.0.3) | esl-erlang (>= 1:25.0.3); however:
  Package erlang-inets is not installed.
  Version of erlang-inets on system, provided by esl-erlang:amd64, is <none>.
  Version of esl-erlang on system is 1:24.3.3-1.
 elixir depends on erlang-ssl (>= 1:25.0.3) | esl-erlang (>= 1:25.0.3); however:
  Package erlang-ssl is not installed.
  Version of erlang-ssl on system, provided by esl-erlang:amd64, is <none>.
  Version of esl-erlang on system is 1:24.3.3-1.
 elixir depends on erlang-syntax-tools (>= 1:25.0.3) | esl-erlang (>= 1:25.0.3); however:
  Package erlang-syntax-tools is not installed.
  Version of erlang-syntax-tools on system, provided by esl-erlang:amd64, is <none>.
  Version of esl-erlang on system is 1:24.3.3-1.
