### ISSUE TITLE
Mix The task "ecto.create" could not be found

### ISSUE THREAD

**Issue by JohnOldman0202** [blockscout/blockscout#5888]
I tried build `https://github.com/Ankr-network/bas-devnet-setup` to my server
Everything working fine. But docker container `blockscout/blockscout` not working, status alway `Restarting`
I checked docker logs that container 
`
** (Mix) The task "ecto.create" could not be found
Note no mix.exs was found in the current directory`

Image of issue:
![Untitled](https://user-images.githubusercontent.com/111005344/183977646-77083f38-1da4-4470-b71e-d3ee2f8ab2e3.png)

**Comment by vbaranov** [comment]
@JohnOldman0202 yes, you should use another command instead from the latest 4.1.7 release:
https://github.com/blockscout/blockscout/blob/0f1d783d066f73cdbb63680d945cbbaae68deaf1/docker-compose/docker-compose.yml#L37

**Comment by JohnOldman0202** [comment]
I changed command but a new issue:
![Untitled](https://user-images.githubusercontent.com/111005344/184051251-226954df-87d4-4f6e-b112-8cea6b4ab9ca.png)
Should i roll back to old version?
docker-compose.yaml
`version: '3.8'

services:
  db:
    image: postgres:13.6
    restart: always
    environment:
      POSTGRES_PASSWORD: 'postgres'
      POSTGRES_USER: 'postgres'
      POSTGRES_HOST_AUTH_METHOD: 'trust'
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    ports:
      - "7432:5432"

  blockscout:
    depends_on:
      - db
    image: blockscout/blockscout:${DOCKER_TAG:-latest}
    restart: always
    links:
      - db:database
    command: 'bash -c "bin/blockscout eval \"Elixir.Explorer.ReleaseTasks.create_and_migrate()\" && bin/blockscout start"'
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    #env_file:
    #  -  ./envs/common-blockscout.env
    environment:
      ETHEREUM_JSONRPC_VARIANT: "geth"
      BLOCK_TRANSFORMER: "clique"
      ETHEREUM_JSONRPC_HTTP_URL: "http://host.docker.internal:8545/"
      DATABASE_URL: "postgresql://postgres:@host.docker.internal:7432/blockscout?ssl=false"
      ECTO_USE_SSL: "false"
    ports:
      - "4000:4000"

  gateway:
    depends_on:
      - blockscout
    image: ankrnetwork/sidechain-explorer:devel
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    environment:
      DATABASE_POSTGRES_URL: "postgres://postgres:@host.docker.internal:7432/blockscout?sslmode=disable"
      GATEWAY_HTTP_ADDRESS: ":9000"
      REACT_APP_API_ENDPOINT: "/"
      REACT_APP_DEFAULT_NETWORK: "default"
    ports:
      - "9000:9000"`

**Comment by vbaranov** [comment]
@JohnOldman0202 we're working this bug.

**Comment by JohnOldman0202** [comment]
I pulled new commit and build new docker image, but after run it.
New issue:
![Uploading Untitled.png…]()

**Comment by JohnOldman0202** [comment]
I pulled new commit and build new docker image, but after run it.
New issue:
![Untitled](https://user-images.githubusercontent.com/111005344/184297248-8ebd6c1e-f4bd-42ef-9f69-63ef87aca559.png)

**Comment by Qwerty5Uiop** [comment]
@JohnOldman0202 could you show the full logs please? Looks like the postgres container is just not ready yet

**Comment by JohnOldman0202** [comment]
I run command: `docker compose up`
with docker compose config `https://github.com/blockscout/blockscout/blob/master/docker-compose/docker-compose-no-build-geth.yml`
![Untitled](https://user-images.githubusercontent.com/111005344/184370884-fe67c21d-3b00-46e7-b66c-54c910cd2f03.png)

**Comment by Qwerty5Uiop** [comment]
@JohnOldman0202 it works now?)

**Comment by JohnOldman0202** [comment]
@Qwerty5Uiop  new issue https://github.com/blockscout/blockscout/issues/5927 🤣
