### ISSUE TITLE
Error: ace.edit can't find div #code_viewer_main

### ISSUE THREAD

**Issue by vbaranov** [blockscout/blockscout#5899]
https://blockscout.com/poa/sokol/address/0xddFf4A885e46148968e43D562ab931DF8fC99E32/contracts#address-tabs

<img width="1371" alt="Screenshot 2022-08-11 at 15 54 12" src="https://user-images.githubusercontent.com/4341812/184137810-a5891b77-9350-4cb3-b025-9b60310a1ca6.png">

**Comment by nikitosing** [comment]
@vbaranov contract is not verified therefore no source code but ace editor by default loading with code page. This error does not affect any functionality on the page. I think we should change the labels: set `low priority`, and remove `contract verification` label
