### ISSUE TITLE
Gnosis Chain: API returns 'type': 'call' for delegate call 

### ISSUE THREAD

**Issue by 72L** [blockscout/blockscout#5901]
For delegate call internal transactions at endpoint `?module=account&action=txlistinternal&txhash={transactionHash}`, the API returns type: 'call' when I would expect 'delegatecall'

### Environment
* BlockScout Version: v4.1.7-beta

### Steps to reproduce

- try this API call: `https://blockscout.com/xdai/mainnet/api?module=account&action=txlistinternal&txhash=0xa809848cc0bfaf33e58eb8de026f096c7e5184acf7640a326d01aea36c018365`

It produces:
```
{
   "message":"OK",
   "result":[
      {
         "blockNumber":"23498480",
         "contractAddress":"",
         "errCode":"",
         "from":"0x3de8b3e4672a4b5fc63fd2e401881ab1042fc4fd",
         "gas":"14973",
         "gasUsed":"1504",
         "index":"1",
         "input":"0x",
         "isError":"0",
         "timeStamp":"1659496915",
         "to":"0x3e5c63644e683549055b9be8653de26e0b4cd36e",
         "transactionHash":"0xa809848cc0bfaf33e58eb8de026f096c7e5184acf7640a326d01aea36c018365",
         "type":"call",
         "value":"8000000000000000000"
      }
   ],
   "status":"1"
}
```
- However, if you look at the UI, this is a delegate call https://blockscout.com/xdai/mainnet/tx/0xa809848cc0bfaf33e58eb8de026f096c7e5184acf7640a326d01aea36c018365/internal-transactions
<img width="1201" alt="image" src="https://user-images.githubusercontent.com/5567899/184171031-8ac8b7b1-4321-496e-a622-95774588e00d.png">

I'm pretty sure the UI is correct given this is a Gnosis Safe using the Gnosis Safe Proxy contract in a delegate call

### Expected Behaviour

The API should give `"type": "delegatecall"`

### Actual Behaviour

The API gives `"type": "call"`

**Comment by vbaranov** [comment]
@72L the type of this internal transaction is indeed `call`. What could be misleading here that API doesn't return `callType`., which is `delegatecall` for the referenced transaction. We will add `callType` in the reponse of the API endpoint as well.
