### ISSUE TITLE
Ethereum Classic " please help "

### ISSUE THREAD

**Issue by jusinplus7** [blockscout/blockscout#5923]
It is not possible to transfer money from Metamask to Binance Exchange.
please help

Address Details
0x73286992Dc23CF79Bf82AFB2A70dD6317c4410E8
 Balance
11.23208768 ETC ($485.91 USD)
 Tokens
0 tokens
 Transactions
 Transfers
 Gas Used
0
 Last Balance Update
[15732225](https://blockscout.com/etc/mainnet/block/15732225)

**Comment by vbaranov** [comment]
Regarding your question try to contact ETC team, for instance, on their Discord https://discord.com/invite/hQs894U.
