### ISSUE TITLE
Canto: <Issue Title>

### ISSUE THREAD

**Issue by MrWaledhegazy** [blockscout/blockscout#5924]
I had 500 pieces of Canto coin and I transferred 499 pieces and it was sent, but I was surprised that the balance did not reach the other wallet and the hash of the transaction did not appear within the Metamask and also the transaction did not appear within the blockchain This is my address please help please 0x2424ae241ef3d6b7568982Ab5C83d7ca28eec803
![Screenshot_2022-08-14-10-51-23-99_4d38fce200f96aeac5e860e739312e76](https://user-images.githubusercontent.com/72114687/184534616-7e28e76c-1bec-4a18-9cf1-83701d3c4450.jpg)
![Screenshot_2022-08-14-11-10-00-42_4d38fce200f96aeac5e860e739312e76](https://user-images.githubusercontent.com/72114687/184534618-12a93ad7-ac27-4fa0-8c10-d9a0f6e0e3cc.jpg)

**Comment by vbaranov** [comment]
Canto is not officially supported here. If you have issues specific to Blockscout, please let us know. Otherwise, you should reach out Canto team with your question.

**Comment by MrWaledhegazy** [comment]
I do not know who is responsible. I sent to the admin in Telegram all the details and he did not respond to me and I do not know what to do and where to talk to them Do you know where to talk to them please
