### ISSUE TITLE
Canto: <Issue Title>

### ISSUE THREAD

**Issue by MrWaledhegazy** [blockscout/blockscout#5925]
This is the transfer address as well. Nothing reached him via the blockchain and he did not receive any internal transaction. Please solve the problem and send the coins to the address or return them to again. Thank you very much
![Screenshot_2022-08-14-12-03-50-05_4d38fce200f96aeac5e860e739312e76](https://user-images.githubusercontent.com/72114687/184534764-c92b8742-7c34-4fea-ad16-c3745161fc57.jpg)

**Comment by vbaranov** [comment]
Canto is not officially supported here. If you have issues specific to Blockscout, please let us know. Otherwise, you should reach out Canto team with your question.
