### ISSUE TITLE
Docker make start issue

### ISSUE THREAD

**Issue by JohnOldman0202** [blockscout/blockscout#5927]
*Describe your issue here.*

### Environment

* Docker version: 20.10.17
* Operating System:
* Blockscout Version/branch: latest

I run cmd: `COIN=BAS ETHEREUM_JSONRPC_VARIANT=geth ETHEREUM_JSONRPC_HTTP_URL=http://host.docker.internal:8545/ ECTO_USE_SSL=false make start`
But blockscout not running.
Issue:
![Untitled](https://user-images.githubusercontent.com/111005344/184548618-6515f55e-e4eb-4909-ac29-d12c9eacce2a.png)

**Comment by vbaranov** [comment]
@JohnOldman0202  please add `PORT=4000` env variable to the running comand

**Comment by JohnOldman0202** [comment]
@vbaranov i added PORT=4000 and still not running. 
![Untitled](https://user-images.githubusercontent.com/111005344/185212541-6e6c09d9-f86d-409b-9634-b929a64cd7bb.png)

**Comment by vbaranov** [comment]
@JohnOldman0202 did you run archive node on the same host?
How did you launch it?
What ethereum client is used for archive node?

**Comment by JohnOldman0202** [comment]
@vbaranov Sorry man, my mistake set wrong env
