### ISSUE TITLE
Indexing problem with ERC-1155

### ISSUE THREAD

**Issue by adean-consensys** [blockscout/blockscout#5929]
Users are getting 404 errors when they want to view certain NFTs on Blockscout Explorer.

A significant majority of the ERC-1155 tokens don't appear to be indexed at all. The token page shows only 102k transferred, when it's more like 900k+
https://explorer.palm.io/token/0x19D4F9A260AF1d7E0E99A32DBe418956af875c25/token-transfers

Here's an example of a non-indexed Fandome token:
[https://explorer.palm.io/token/0x19d4f9a260af1d7e0e99a32dbe418956af875c25/instance/93[…]32398673704830355479211617995309295072583838/token-transfers](https://explorer.palm.io/token/0x19d4f9a260af1d7e0e99a32dbe418956af875c25/instance/93085636199535520568887282296748232398673704830355479211617995309295072583838/token-transfers)

And one that is indexed:
[https://explorer.palm.io/token/0x19d4f9a260af1d7e0e99a32dbe418956af875c25/instance/58[…]28179761731002901740101948726234922267830219/token-transfers](https://explorer.palm.io/token/0x19d4f9a260af1d7e0e99a32dbe418956af875c25/instance/58445249375204905287384587890673428179761731002901740101948726234922267830219/token-transfers)

### Environment

* Elixir & Erlang/OTP versions (`elixir -version`):
```
Erlang/OTP 24 [erts-12.2] [source] [64-bit] [smp:2:1] [ds:2:1:10] [async-threads:1] [jit:no-native-stack]
Elixir 1.13.1 (compiled with Erlang/OTP 24)
```
* Operating System: Docker (alpine?)
* Blockscout Version/branch: `v4.1.5-0`

### Steps to reproduce

Tokens not indexed

### Expected behaviour

All identified tokens should be indexed, and logs of failed indexes should occur for troubleshooting purposes

### Actual behaviour

Most (800k) tokens were not indexed nor do they ever index, even if we restart the indexer process.

Is it possible for us to manually index these tokens if we have a list of each?  Would it be a simple query/stored procedure we need to call, or is it much more involved?

**Comment by vbaranov** [comment]
@adean-consensys thank you for the issue. We're investigating.

**Comment by adean-consensys** [comment]
Please let me know if more information is needed, or if you have any queries or tests you want me to run.

**Comment by vbaranov** [comment]
@adean-consensys we merged the fix to master branch. You can pull update from master branch or wait until the next release. Please let us know if the issue gone on your end.

**Comment by vbaranov** [comment]
I am closing this. Please let us know if you still experience the issue.

**Comment by adean-consensys** [comment]
Thank you @vbaranov we're in the process of rehosting it in our container registry, we're working through the CVE vulns it's throwing and will be deploying to our environment soon.  :+1:
