### ISSUE TITLE
Palm: My Kucoin account wont accept the PALM network and my DAI is frozen - need refund

### ISSUE THREAD

**Issue by AdamCrypto999** [blockscout/blockscout#5937]
I attempted to transfer my DAI from Metamask via PALM Network and it was successful. Problem is Kucoin doesn't accept PALM network and its just frozen and inaccessible now. I would like PALM to send it back to my Metamask account:

Acct # : 0xdCD9c38D0044FD915f14363ae1E0C763947f58b3
TXID: 0x9b6adfc2bb842abe13d44d2f3923649d6cca9fa28bb65269620da2ef7f629681

https://explorer.palm.io/address/0x94d44F57B7ABA792E77E500dB7261585fC61511e

### Environment
* Elixir Version: 1.13.1
* Erlang Version: 24
* BlockScout Version: 

* User Agent: `Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/104.0.0.0 Safari/537.36`

### Steps to reproduce

*Tell us how to reproduce this issue. If possible, push up a branch to your fork with a regression test we can run to reproduce locally.*

### Expected Behaviour

*Tell us what should happen.*

### Actual Behaviour

*Tell us what happens instead.*

**Comment by vbaranov** [comment]
Here is no Palm instance support
