### ISSUE TITLE
Testnet: <Issue Title>

### ISSUE THREAD

**Issue by tony101-cloud** [blockscout/blockscout#5940]
*Describe your issue here.*

### Environment
* Elixir Version: 1.12.3
* Erlang Version: 24
* BlockScout Version: 4.1.2

* User Agent: `Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/104.0.0.0 Safari/537.36`

### Steps to reproduce

*Tell us how to reproduce this issue. If possible, push up a branch to your fork with a regression test we can run to reproduce locally.*

### Expected Behaviour
I dont know if you could make the exployer load more faster

*Tell us what should happen.*

### Actual Behaviour
Your block explorer kind of loads loads i mean the front end , though when creating my smart contracts and interacting with the chain it more faster. I would really give a 5 star for that

*Tell us what happens instead.*

**Comment by vbaranov** [comment]
@tony101-cloud on which instance of Blockscout did you face with slowness?

**Comment by tony101-cloud** [comment]
Blocks cout #5940

**Comment by vbaranov** [comment]
Do you have the link to the explorer where you met with the problem?

**Comment by vbaranov** [comment]
Closing due to lack of response
