### ISSUE TITLE
Testnet: How to verify contract with source code

### ISSUE THREAD

**Issue by wajahatrashid2** [blockscout/blockscout#5943]
*Describe your issue here.*

I have deployed token on testnet but i do not know how to verify my token contract with source code

### Environment
* Elixir Version: 1.12.3
* Erlang Version: 24
* BlockScout Version: 4.1.2

* User Agent: `Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/104.0.0.0 Safari/537.36`

### Steps to reproduce

*Tell us how to reproduce this issue. If possible, push up a branch to your fork with a regression test we can run to reproduce locally.*

### Expected Behaviour

*Tell us what should happen.*

### Actual Behaviour

*Tell us what happens instead.*

**Comment by vbaranov** [comment]
Please, follow this guide https://docs.blockscout.com/for-users/verifying-a-smart-contract
