### ISSUE TITLE
Gnosis Chain: Bug found

### ISSUE THREAD

**Issue by zhenwarxx** [blockscout/blockscout#5946]
Hi dear team

I found a XSS bug, how I can report it to you?

Best regards

**Comment by vbaranov** [comment]
@zhenwarxx Hi, XSS bug you repoted, should be resolved with update to release [4.1.5](https://github.com/blockscout/blockscout/releases/tag/v4.1.5-beta) or higher. We do not manage Blockscout instance where you found XSS issue. Please, advise instance maintainers to update Blockscout version.
