### ISSUE TITLE
Total transactions in home page is not correct

### ISSUE THREAD

**Issue by youngqqcn** [blockscout/blockscout#5947]
*Describe your issue here.*

### Environment

Elixir & Erlang/OTP versions (elixir -version):
Elixir 1.13.3 (compiled with Erlang/OTP 24)
Operating System: CentOS7.9
Blockscout Version/branch: tag v4.1.7

### Expected behaviour

*Tell us what should happen.*

### Actual behaviour

*Tell us what happens instead.*

![image](https://user-images.githubusercontent.com/30211020/185346501-02f7d148-4597-4583-910e-260ea8c187fc.png)

![image](https://user-images.githubusercontent.com/30211020/185346634-ab4f2e8d-2b22-414d-897e-5d9ac51a8c9d.png)

**Comment by vbaranov** [comment]
@youngqqcn counters on the main page updates on a schedule. And hopefully you can change the schedule. For instance, for transactions counter you can set `CACHE_TXS_COUNT_PERIOD`
> Interval in seconds to restart the task, which calculates the total txs count.

The efault value is 2 hours (7200 sec).

Reference to all supported env variables https://docs.blockscout.com/for-developers/information-and-settings/env-variables

**Comment by youngqqcn** [comment]
@vbaranov Thanks!
