### ISSUE TITLE
Mainnet: <Issue Title>

### ISSUE THREAD

**Issue by Timtamrocks1** [blockscout/blockscout#5958]
I bought 665 million of celestial doge token and it took 1200 doge and gave me all the tokens. Then all of a sudden I lost 90% of the tokens and it says I only had 65 million. I lost 90% of my tokens
### Environment
* Elixir Version: 1.12.3
* Erlang Version: 24
* BlockScout Version: 4.1.2

* User Agent: `Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/104.0.0.0 Safari/537.36`

### Steps to reproduce

*Tell us how to reproduce this issue. If possible, push up a branch to your fork with a regression test we can run to reproduce locally.*

I don't know what happened

*Tell us what should happen.*

I should of kept all 665 million tokens with no issues

Instead I lost 90% of the tokens to thin air and when I sold it took all of them.

![image](https://user-images.githubusercontent.com/106290022/185769809-d9d0ff45-3de2-4f01-913f-ddd82c037a16.png)

![image](https://user-images.githubusercontent.com/106290022/185769810-7b885b2b-0963-41fd-b904-bffefb7d71d0.png)

This is completely unacceptable and I hope for a full refund of the 1200 doge coins I spent to this address: 0xdfEb50F97Bb6A660697849Ac13645E2E26cC4915

**Comment by vbaranov** [comment]
This is the chat for technical issues with Blockscout explorer. Your question doesn't relate to any technical issue.
