### ISSUE TITLE
Gnosis Chain: <POAP token transfer says success but when I check Etherscan, there is no transaction>

### ISSUE THREAD

**Issue by Kozaru-eth** [blockscout/blockscout#5961]
I claimed 2027 POAP from https://poap.delivery/tastybonesog - everything seems to have gone through. My transaction hash says it was successful on blockscout: 0x9d4519fb174ec2864f58fcbc10768889f32991f3cbec4f65845086666f21c5e0

When I check on Etherscan though, there is no token transfer into my wallet.

### Environment
* Elixir Version: 1.13.1
* Erlang Version: 24
* BlockScout Version: v4.1.7-beta

* User Agent: `Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/104.0.5112.81 Safari/537.36`

### Steps to reproduce

*Tell us how to reproduce this issue. If possible, push up a branch to your fork with a regression test we can run to reproduce locally.*

### Expected Behaviour

*Tell us what should happen.*

### Actual Behaviour

*Tell us what happens instead.*

**Comment by vbaranov** [comment]
This transaction is on Gnosis chain. You can check on both explorers:
https://blockscout.com/xdai/mainnet/tx/0x9d4519fb174ec2864f58fcbc10768889f32991f3cbec4f65845086666f21c5e0
https://gnosisscan.io/tx/0x9d4519fb174ec2864f58fcbc10768889f32991f3cbec4f65845086666f21c5e0

**Comment by Kozaru-eth** [comment]
I've added the Gnosis chain to my Metamask wallet, but there are no token
![IMG_1806](https://user-images.githubusercontent.com/110129640/186017102-98fbd9f0-5ea3-4434-a309-c0c2fad9af95.PNG)
s
