### ISSUE TITLE
L16: <explorer not displaying my transaction> after minting  an nft on metamask i cant view my transaction on the explorer is say transaction hash not found 

### ISSUE THREAD

**Issue by noblejos** [blockscout/blockscout#5969]
*Describe your issue here.*

### Environment
* Elixir Version: 1.12.2
* Erlang Version: 24
* BlockScout Version: v4.1.3-beta

* User Agent: `Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/104.0.0.0 Safari/537.36`

### Steps to reproduce

*Tell us how to reproduce this issue. If possible, push up a branch to your fork with a regression test we can run to reproduce locally.*

### Expected Behaviour

*Tell us what should happen.*

### Actual Behaviour

*Tell us what happens instead.*

**Comment by vbaranov** [comment]
Try to ask in LUKSO discord https://discord.com/invite/lukso. Blockscout team doesn't manage this instance.
