### ISSUE TITLE
Hosted Blockscout for Candle

### ISSUE THREAD

**Issue by samisbakedham** [blockscout/blockscout#5972]
Would love to discuss with blockscout on hosting an explorer for candle. Currently we run a blockscout instance for Candle on google cloud, you can view it [here](https://candleexplorer.com). We have it hosted on Google cloud, with 64 vCPU, 32 GB ram, 800 GB SSD. 

thank you!

**Comment by Mojmir-R** [comment]
Hi @samisbakedham, please feel free to contact me through email at mojmir@blockscout.com or Telegram: Mojmir_R. Would love to explore ways how we can collaborate.
