### ISSUE TITLE
Mainnet: <Issue Title>

### ISSUE THREAD

**Issue by Ragul84** [blockscout/blockscout#5979]
*Transaction Hash 0xf57e5551c65cea2dbb64c095a126e7245e988596b05f24c12abda9ea17bad4f9 
Got failed but the EARLY SHIBES airdrop page shows I have Already claimed the airdrop! Do. Somethng soon pls .*

### Environment
* Elixir Version: 1.12.3
* Erlang Version: 24
* BlockScout Version: 4.1.2

* User Agent: `Mozilla/5.0 (Linux; Android 10; CPH2239 Build/QP1A.190711.020; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/87.0.4280.101 Mobile Safari/537.36`

### Steps to reproduce

*Tell us how to reproduce this issue. If possible, push up a branch to your fork with a regression test we can run to reproduce locally.*

### Expected Behaviour

*Tell us what should happen.*

### Actual Behaviour

*Tell us what happens instead.*

**Comment by vbaranov** [comment]
This transaction hash doesn't exist on Ethereum Mainnet. Most likely it was not broadcasted to blockchain or executed on a different blockchain.
