### ISSUE TITLE
Documentation instructs to use node.js 14, but lockfiles are written using version 2 format

### ISSUE THREAD

**Issue by mikonieminen** [blockscout/blockscout#5991]
When installing node.js 14.x, it comes with npm 6.x and this causes warning about lockfile incompatibility:
```
npm WARN read-shrinkwrap This version of npm is compatible with lockfileVersion@1, but package-lock.json was generated for lockfileVersion@2. I'll try to do my best with it!
```
To match exact dependencies, I'm running `npm ci` instead of `npm install`.

### Environment

* Elixir & Erlang/OTP versions (`elixir -version`):
  - Erlang/OTP 24 [erts-12.2.1] [source] [64-bit] [smp:4:4] [ds:4:4:10] [async-threads:1] [jit]
  - Elixir 1.12.2 (compiled with Erlang/OTP 24)
* Operating System:
  - Ubuntu 22.04
* Blockscout Version/branch:
  - v4.1.7-beta

### Steps to reproduce
```sh
git clone -b v4.1.7-beta https://github.com/poanetwork/blockscout blockscout
cd blockscout
mix do local.hex --force, local.rebar --force, deps.get, deps.compile, compile
cd apps/block_scout_web/assets; npm ci && node_modules/webpack/bin/webpack.js --mode production; cd -
# this give the error
cd apps/explorer; npm ci; cd -
# this gives the error
```

### Expected behaviour

When lockfiles are generated with correct version npm (6.x), then this warning not seen.

### Actual behaviour

Because these lockfiles are generated with more recent `npm` version, we get these warnings.

**Comment by vbaranov** [comment]
@mikonieminen could you please point us where to update instructions? Actually, general requirement for the latest release of Blockscout is Node 16.x. Source: https://docs.blockscout.com/for-developers/information-and-settings/requirements

**Comment by mikonieminen** [comment]
I'm a bit puzzled now. I could swear I checked it when I wrote this ticket, but you're right and it's been there quite some time. Maybe I was just too tired and rushing through my checks. Sorry for the trouble. Closing the ticket.
