### ISSUE TITLE
Mainnet: <Issue Title>

### ISSUE THREAD

**Issue by Dinarah1** [blockscout/blockscout#5993]
*Describe your issue here.* I withdraw dc token from mexc to kucoin before 14 hours still not received my tokes how many times i have to wait for

### Environment
* Elixir Version: 1.12.3
* Erlang Version: 24
* BlockScout Version: 4.1.2

* User Agent: `Mozilla/5.0 (Linux; Android 10; Redmi Note 7S) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/104.0.0.0 Mobile Safari/537.36`

### Steps to reproduce

*Tell us how to reproduce this issue. If possible, push up a branch to your fork with a regression test we can run to reproduce locally.*

### Expected Behaviour

*Tell us what should happen.*

### Actual Behaviour

*Tell us what happens instead.*

**Comment by vbaranov** [comment]
This is a technical chat for Blockscout explorer issues. Your question is out of competence of Blockscout team.
