### ISSUE TITLE
Testnet: <usdt didnt went through>

### ISSUE THREAD

**Issue by winningdust** [blockscout/blockscout#5995]
*this is my transcastion id 
0xf1fdc55aba86cb7f7a42c8d163106bf90da9b93a579ec59056e6e68801bd68a7 and its says completed but i havent recevied it on my binance wallet... help.*

### Environment
* Elixir Version: 1.12.2
* Erlang Version: 24
* BlockScout Version: 

* User Agent: `Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/104.0.0.0 Safari/537.36`

### Steps to reproduce

*Tell us how to reproduce this issue. If possible, push up a branch to your fork with a regression test we can run to reproduce locally.*

### Expected Behaviour

*Tell us what should happen.*

### Actual Behaviour

*Tell us what happens instead.*

**Comment by vbaranov** [comment]
This is a technical chat for Blockscout explorer issues. Your question is out of competence of Blockscout team.
