### ISSUE TITLE
Not able to run docker-compose-no-build-ganache on M1 MacBook Pro

### ISSUE THREAD

**Issue by surajsjain** [blockscout/blockscout#5996]
I tried to run a local instance of blockscout to connect to my local ganache by using the docker-compose-no-build-ganache.yml file. The Postgres container seemed to have spawned without issues but the blockscout container did not spawn up and threw some errors.

### Environment

* Elixir & Erlang/OTP versions (`elixir -version`): Not applicable
* Operating System: macOS Monterey (version 12.5.1)
* Blockscout Version/branch: master

### Steps to reproduce
1. Switch the working directory to the `docker-compose` directory 
2. Run the command `sudo docker-compose -f docker-compose-no-build-ganache.yml up`

### Expected behaviour
The console should not log any errors and I should be able to view blockscout on `localhost:4000`

### Actual behaviour
Here are the command line logs from docker-compose:
```
blockscout    | qemu: uncaught target signal 11 (Segmentation fault) - core dumped
blockscout    | /bin/bash: line 1:     9 Segmentation fault      bin/blockscout eval "Elixir.Explorer.ReleaseTasks.create_and_migrate()"
blockscout exited with code 139
```

**Comment by vbaranov** [comment]
@surajsjain the issue is because we do not provide docker images for different architectures on the `latest` tag. However, releases should work fine. So, if you will change `latest` tag to `4.1.7` (the latest release as of now), it should start fine: `DOCKER_TAG=4.1.7 docker-compose -f docker-compose-no-build-ganache.yml up`

**Comment by surajsjain** [comment]
It's working, Thanks!

Maybe the info above can be included in the docs. I see that the docs include [running off the makefile](https://docs.blockscout.com/for-developers/information-and-settings/docker-integration-local-use-only) (which had the same issue/error on M1 Mac), so maybe this point can be included in that page with a note that the same goes with the docker-compose based running.

**Comment by MartianVerse** [comment]
> 

Still the same issu, with m2pro macbook

**Comment by MetaGameNetwork** [comment]
me too

**Comment by 0xhohenheim** [comment]
Same issue for `DOCKER_TAG=4.1.7 docker-compose -f docker-compose-no-build-hardhat-network.yml up -d`
```
2023-05-04 20:36:26 qemu: uncaught target signal 11 (Segmentation fault) - core dumped
2023-05-04 20:36:26 bash: line 1:     8 Segmentation fault      bin/blockscout eval "Elixir.Explorer.ReleaseTasks.create_and_migrate()"
```
