### ISSUE TITLE
Mainnet: <Issue Title>

### ISSUE THREAD

**Issue by Sarbastm** [blockscout/blockscout#6002]
*Describe your issue here.*
Deposit gone wrong 
### Environment
* Elixir Version: 1.12.3
* Erlang Version: 24
* BlockScout Version: 4.1.2

* User Agent: `Mozilla/5.0 (iPhone; CPU iPhone OS 15_6_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/15.6.1 Mobile/15E148 Safari/604.1`

### Steps to reproduce

*Tell us how to reproduce this issue. If possible, push up a branch to your fork with a regression test we can run to reproduce locally.*

### Expected Behaviour

*Tell us what should happen.*

### Actual Behaviour

*Tell us what happens instead.*

**Comment by vbaranov** [comment]
Wrong place asking. This is a technical chat for Blockscout explorer issues.
