### ISSUE TITLE
Mainnet: <Issue Title>

### ISSUE THREAD

**Issue by okrzysziek76** [blockscout/blockscout#6009]
Cześć. 
Wysłałem DC z metamask do Kuckoin. Do dzisiaj transakcja nie przeszła. 
Hash transakcji: 0x2dcae9d1c8cee610226c31568b33668b5543cf841701dbf8cffc06fbc007abb4
Proszę o pomoc
ok76@wp.pl

Hi.
I sent DC with metamask to Kuckoin. Until today, the transaction has not passed.
Transaction hash: 0x2dcae9d1c8cee610226c31568b33668b5543cf841701dbf8cffc06fbc007abb4
Please help
ok76@wp.pl

*Describe your issue here.*

### Environment
* Elixir Version: 1.12.3
* Erlang Version: 24
* BlockScout Version: 4.1.2

* User Agent: `Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/104.0.0.0 Safari/537.36`

### Steps to reproduce

*Tell us how to reproduce this issue. If possible, push up a branch to your fork with a regression test we can run to reproduce locally.*

### Expected Behaviour

*Tell us what should happen.*

### Actual Behaviour

*Tell us what happens instead.*

**Comment by vbaranov** [comment]
This is the chat for technical issues with Blockscout explorer. Your question doesn't relate to Blockscout. You should connect with exchange support in regards to your question.
