### ISSUE TITLE
Mainnet: <Issue Title>

### ISSUE THREAD

**Issue by juiceplanet1629** [blockscout/blockscout#6014]
*To whom this may concern. The Dogechain withdraw feature wouldn’t have converted my dogechain tokens to doge, it just would have taken my doge that I have in my account off the bridge itself to another doge wallet. In order to move my dogechain tokens into another secure wallet, I had to do it through MetaMask. The kucoin wallet address for dogechain is based on the eth mainnet. Dogechain and eth were two different main nets. I remember I tried to find a bridge that could transfer the dc tokens in doge mainnet to the eth network and none of them had dc token available. As a result, I lost my tokens in the transaction. I was wondering if there was any way I could get my tokens back or are they lost forever. Thank you for your time and consideration.*

**Comment by vbaranov** [comment]
This chat is for technical issues with Blockscout explorer. Your question is out of scope of Blockscout support.
