### ISSUE TITLE
Astar (EVM): <I did not receive my BNB>

### ISSUE THREAD

**Issue by coinbear3r** [blockscout/blockscout#6029]
*I was trying to transfer my BNB balance from ASTAR network going into my BNB wallet. At the time, I used an ERC-20 BNB wallet address as I was seeing an Ethereum insignia from the space where to input a wallet address. The transaction hash is: 0x95b120ceb1adb7b215d85b6deaa9b11443f70a5c814749ae28acf29a8dbc712d*

### Environment
* Elixir Version: 1.13.1
* Erlang Version: 24
* BlockScout Version: v4.1.7-beta

* User Agent: `Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.5.4896.80 Safari/537.36`

### Steps to reproduce

*On the Assets page: https://portal.astar.network/#/assets
My BNB balance was reflected under BNB Token and then I clicked on transfer and processed it from there.*

### Expected Behaviour

*It said completed so I was expecting it to reflect in to my BNB wallet*

### Actual Behaviour

*My balance really did not transfer and I dont know how and oddly my transaction shows completed*

**Comment by vbaranov** [comment]
This chat is for technical issues with Blockscout explorer. Your question is out of scope of Blockscout support.
