### ISSUE TITLE
Display all available fields for uncle/reorg blocks

### ISSUE THREAD

**Issue by 0xtzData** [blockscout/blockscout#6039]
*Describe your issue here.*

### Environment

* Deployment type: k8s
* Operating System: ubuntu 16.04
* Blockscout image: [blockscout/blockscout-account:latest ](https://hub.docker.com/layers/blockscout/blockscout-account/latest/images/sha256-f0f1e34355ed63e19f7542ddaa52bfe96ca720ab742137c550d3ea7b5cc42f32?context=repo)

### Steps to reproduce

Deploy an environment with that image, connect to mainnet and check uncle/reorg/common blocks after some time

### Expected behaviour

All the blocks have fields displayed:
`Total Difficulty`
`Gas Used`
`Gas Limit`
`Nonce`

### Actual behaviour

Only common blocks have all the fields displayed

**Comment by vbaranov** [comment]
Fixed in new UI
