### ISSUE TITLE
Can't refresh log filter in address page

### ISSUE THREAD

**Issue by 0xtzData** [blockscout/blockscout#6040]
*Describe your issue here.*

### Environment

* Deployment type: k8s
* Operating System: ubuntu 16.04
* Blockscout image: [blockscout/blockscout-account:latest ](https://hub.docker.com/layers/blockscout/blockscout-account/latest/images/sha256-f0f1e34355ed63e19f7542ddaa52bfe96ca720ab742137c550d3ea7b5cc42f32?context=repo)

### Steps to reproduce

Deploy an environment with that image, connect to mainnet and check uncle/reorg/common blocks after some time

### Expected behaviour

After using the log filter once you can't list all the logs again without refreshing the page
You can't cancel the filter by pressing the cross too

<img width="1413" alt="image" src="https://user-images.githubusercontent.com/108135703/188138658-b5fefdd4-aea8-4a81-9dc9-2936bc38ad21.png">

### Actual behaviour

Filter can be cancelled and refreshed without reloading page

**Comment by vbaranov** [comment]
The issue resolved in https://github.com/blockscout/blockscout/pull/6327
