### ISSUE TITLE
Indexing not working from geth after postgres modification,

### ISSUE THREAD

**Issue by zeus-dev** [blockscout/blockscout#6042]
*Describe your issue here.*

### Environment

* Deployment type (Manual/Docker/Docker-compose): Manual
* Elixir & Erlang/OTP versions (`elixir -version`): 1.134
* Node JS version (`node -v`): 16.14
* Operating System: ubuntu 20.04
* Blockscout Version/branch/commit: 4.15

### Steps to reproduce

*Tell us how to reproduce this issue.  ❤️ if you can push up a branch to your fork with a regression test we can run to reproduce locally.*

### Expected behaviour
i have postgresql connection issue after modify postgres  my explorer not collecting datas from geth archive node,  kindly point me out right direction,

*Tell us what should happen.*

### Actual behaviour

*Tell us what happens instead.*

**Comment by vbaranov** [comment]
@zeus-dev could elaborate more what do you mean by indexing not working?

**Comment by vbaranov** [comment]
How did you modify postgresql?

**Comment by zeus-dev** [comment]
max_connection=200 in postgresql.conf
 and i rebooted postgresql and started blockscout..  no new blocks updates, im syncing ethereum mainnet,

**Comment by zeus-dev** [comment]
you can visit here http://107.22.124.126:4000

**Comment by zeus-dev** [comment]
![image](https://user-images.githubusercontent.com/62093083/188158421-bde975f7-f07f-4ecc-ba12-454dbbbfa687.png)

**Comment by vbaranov** [comment]
>max_connection=200 in postgresql.conf
and i rebooted postgresql and started blockscout..

Hardly this can cause sop indexing

Could you share the set of env variables for the explorer (hiding sensitive info of course)?

**Comment by zeus-dev** [comment]
> 

export DATABASE_URL=postgresql://admin:password@localhost:5432/blockscout

export ETHEREUM_JSONRPC_WS_URL=http://x.x.x.x:8546
export ETHEREUM_JSONRPC_HTTP_URL=http://x.x.x.x.x:8545
export ETHEREUM_JSONRPC_VARIANT=geth
export ETHEREUM_JSONRPC_TRACE_URL=http://x.x.x.x.x:8545
export NETWORK= ethereum

**Comment by zeus-dev** [comment]
![image](https://user-images.githubusercontent.com/62093083/188166853-259c4fa0-12a1-4116-9a1e-6ac87fd12240.png)
 this is my geth node current status

**Comment by zeus-dev** [comment]
r u asking this log? 
![image](https://user-images.githubusercontent.com/62093083/188167410-30c67d20-85af-4e82-abc2-c495fe2e5b65.png)

**Comment by vbaranov** [comment]
It looks like your Geth is still syncing. It is not syncronized with the latest block. What is the response from the node:
```
curl -X POST --data '{"jsonrpc":"2.0","method":"eth_blockNumber","params":[],"id":1}' http://...
```
?
where replace http:// with endpoint of your node

**Comment by zeus-dev** [comment]
yes my node still syncing and responce in console 
![image](https://user-images.githubusercontent.com/62093083/188173411-23ef43b1-0937-4f2a-aa4c-c4d92f26b663.png)

**Comment by zeus-dev** [comment]
see this error please ![image](https://user-images.githubusercontent.com/62093083/188173916-bdbe1b99-0a3a-48aa-b859-1963791ab233.png)

**Comment by zeus-dev** [comment]
getting response from geth node ![image](https://user-images.githubusercontent.com/62093083/188175767-fcb8266e-14a5-4c0e-b088-a6093ec40bf8.png)

**Comment by vbaranov** [comment]
> yes my node still syncing

Blockscout requires fully synchronized node. When it will be in sync with the latest block Blockscout will start to collect blocks. I am closing issue.

**Comment by zeus-dev** [comment]
ok thanks
