### ISSUE TITLE
Ethereum Classic: <Issue Title>

### ISSUE THREAD

**Issue by Tjacklack08** [blockscout/blockscout#6048]
*Describe your issue here.*hi. I'm new to crypto, i'm sorry if this question is stupied, but the my money is gone. What should i do?

Bs danne 

https://blockscout.com/etc/mainnet/tx/0x7b625588a050b0f16c1d7f2b2d6f938fdb2cea38cd68c3106617d1b7460e566e
### Environment
* Elixir Version: 1.13.1
* Erlang Version: 24
* BlockScout Version: v4.1.5-beta

* User Agent: `Mozilla/5.0 (Linux; U; Android 11; sv-se; POCO X3 Pro Build/RKQ1.200826.002) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/89.0.4389.116 Mobile Safari/537.36 XiaoMi/MiuiBrowser/12.13.2-gn`

### Steps to reproduce

*Tell us how to reproduce this issue. If possible, push up a branch to your fork with a regression test we can run to reproduce locally.*

### Expected Behaviour

*Tell us what should happen.*

### Actual Behaviour

*Tell us what happens instead.*

**Comment by vbaranov** [comment]
You should ask in Ethereum Classic Discord https://discord.com/invite/bMGuZsA
