### ISSUE TITLE
Mainnet: Dogechain don't let me sell a token

### ISSUE THREAD

**Issue by TheGingka** [blockscout/blockscout#6050]
Dogechain didn't complete a transaction

### Environment
* Elixir Version: 1.12.3
* Erlang Version: 24
* BlockScout Version: 4.1.2

* User Agent: `Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/104.0.0.0 Safari/537.36`

### Steps to reproduce

I just swap tokens on DogeSwap, OMNOM to WDOGE, and the TX didn't show up and the action is on queue.

### Expected Behaviour

Complete a sell on DogeSwap

### Actual Behaviour

Stuck in the queue.

**Comment by vbaranov** [comment]
This chat is for technical issues with Blockscout explorer. Your question is out of scope of Blockscout support.
