### ISSUE TITLE
Ethereum Classic: METAMASK WONT SEND ETC. PENDING NOT ON BLOCKSCOUT.

### ISSUE THREAD

**Issue by millurdy** [blockscout/blockscout#6051]
Hello for the past several weeks I've been contacting metamask support and their email system which hasn't replied to my message still. The chat support told me an update is coming out next week that will fix this issue? But my MetaMask will not send ETC out of my wallet to any wallet, or even a MetaMask account transfer. I've recently bought a hardware wallet coming soon which hopefully will solve the issue.

It will continuously be pending and will not show up on blockscout as a transaction.

But my MetaMask remains unable to send ETC. It can receive ETC as well as receive and send other cryptos. Does anybody have a fix or has the same issue in MetaMask? I've done all possible fixes reset my account tried mobile and PC nothing is working for ETC to send out of my wallet.
I've used this wallet many times before just fine with ETC. My MetaMask is at current versions.

### Environment
* Elixir Version: 1.13.1
* Erlang Version: 24
* BlockScout Version: v4.1.5-beta

* User Agent: `Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/104.0.0.0 Safari/537.36`

### Steps to reproduce

*Tell us how to reproduce this issue. If possible, push up a branch to your fork with a regression test we can run to reproduce locally.*

### Expected Behaviour

*Tell us what should happen.*

### Actual Behaviour

*Tell us what happens instead.*

**Comment by vbaranov** [comment]
Regarding your question try to contact ETC team, for instance, on their Discord https://discord.com/invite/dwxb6nf.
