### ISSUE TITLE
Mainnet: <Issue Title>

### ISSUE THREAD

**Issue by Dream2727** [blockscout/blockscout#6057]
*Describe your issue here.* I am trying to verify a contract so it can be tradeable on dogechain. It is not letting me verify 

### Environment
* Elixir Version: 1.12.3
* Erlang Version: 24
* BlockScout Version: 4.1.2

* User Agent: `Mozilla/5.0 (iPad; CPU OS 14_7_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Mobile/15E148`

### Steps to reproduce

*Tell us how to reproduce this issue. If possible, push up a branch to your fork with a regression test we can run to reproduce locally.*

### Expected Behaviour

*Tell us what should happen.*

### Actual Behaviour

*Tell us what happens instead.* it’s not letting me

**Comment by Dream2727** [comment]
Hi, I am trying to verify a contract but it is not allowing me too on the dogechain. Please help

**Comment by vbaranov** [comment]
@Dream2727 please provide verification details.

**Comment by vbaranov** [comment]
Closed due to no answer from user.
