### ISSUE TITLE
Palm: Preview and Metadata are not updating on the Palm Explorer

### ISSUE THREAD

**Issue by fabricioblz** [blockscout/blockscout#6058]
*Preview and Metadata are not updating on the Palm Explorer when URI is not available at the moment of `safeMintWithItemData` execution. Even with a valid URI available after the mint process, the Palm Explorer seems to keep the cache of the moment where the token was minted.*

### Environment
* "ethers": "^5.6.9",
* "ethers-aws-kms-signer": "^1.3.2"

### Steps to reproduce

1- Use `safeMintWithItemData` on the contract https://explorer.palm-uat.xyz/address/0x6F8CAE3fc1021E6d345c7F1B62D38114fd4213B8 with a URI without metadata
2- Check palm explorer generated by the minted token. Example: https://explorer.palm-uat.xyz/token/0x61fe263ef5504091586a33750120bb6ff2d3d4ec/instance/296655357153363310031779803359628594062/token-transfers

### Expected Behaviour

This token (the "right" one) was created using the same technology, the only difference is that the URI had the metadata *before* the mint execution:

https://explorer.palm-uat.xyz/token/0x61fe263ef5504091586a33750120bb6ff2d3d4ec/instance/75122169586826164324342054546226394764/token-transfers

1- It should have the preview
2- It should have the metadata tab

<img width="1434" alt="Screen Shot 2022-09-05 at 18 45 35" src="https://user-images.githubusercontent.com/17836184/188518776-3256fe6e-2dbd-4ced-8deb-424580532574.png">

### Actual Behaviour

This token (the "wrong" one) was created using the same technology, the only difference is that the URI had the metadata * after* the mint execution:

https://explorer.palm-uat.xyz/token/0x61fe263ef5504091586a33750120bb6ff2d3d4ec/instance/296655357153363310031779803359628594062/token-transfers

The thing is: 
In the transaction: https://explorer.palm-uat.xyz/tx/0xcd63b5289b608470dc583d5e8e353dd7be4e763cc73bd70d366bed495b87397c

The metadata is available on the URI: https://tokens-staging.candy-digital.net/296655357153363310031779803359628594062

<img width="734" alt="Screen Shot 2022-09-05 at 19 18 43" src="https://user-images.githubusercontent.com/17836184/188519929-f3cf822a-c2e0-424a-8d56-d4b35562d9c0.png">

<img width="734" alt="Screen Shot 2022-09-05 at 19 21 27" src="https://user-images.githubusercontent.com/17836184/188520063-0cc8f377-a478-4982-8ce7-c8e9884afb1a.png">

1- It doesn't have the preview
2- It doesn't have metadata tab

<img width="734" alt="Screen Shot 2022-09-05 at 19 22 29" src="https://user-images.githubusercontent.com/17836184/188520129-dbcc8a0a-ca90-43f5-8082-4e1c032d24d2.png">

**Comment by vbaranov** [comment]
@fabricioblz, token instances fetcher works in background, asynchroniously with the main blocks fetcher, and there might be a delay on token instances fetching. On the 2nd link I see, that metadata finally appeared. I am closing this. Please, let me know, if you still experience the issue with verification of token instances.
