### ISSUE TITLE
docker build defeat

### ISSUE THREAD

**Issue by vb3328998** [blockscout/blockscout#6059]
*Describe your issue here.*
When I build, I will prompt this error
=> ERROR [builder 12/18] RUN mix do deps.get, local.rebar --force, deps.compile                                                                                                                                                                                           1.3s
------
 > [builder 12/18] RUN mix do deps.get, local.rebar --force, deps.compile:
#0 0.178 runc run failed: unable to start container process: exec: "/bin/sh": stat /bin/sh: no such file or directory
------
failed to solve: executor failed running [/bin/sh -c mix do deps.get, local.rebar --force, deps.compile]: exit code: 1

### Environment
Docker-compose
Docker Version 20.10
Docker Compose version v2.10.2
### Steps to reproduce
i dont know how to reproduce,everytime always error
*Tell us how to reproduce this issue.  ❤️ if you can push up a branch to your fork with a regression test we can run to reproduce locally.*

### Expected behaviour

*Tell us what should happen.*

### Actual behaviour

*Tell us what happens instead.*

**Comment by vbaranov** [comment]
@vb3328998 how do you run docker-compose? I mean which docker-compose config did you use - we provide multiple. From which Blockscout release is that docker-compose file?

**Comment by vbaranov** [comment]
Closing the issue because lack of user's feedback.
