### ISSUE TITLE
blockscout is not syncing blocks continously.Gives an error.

### ISSUE THREAD

**Issue by iqbalsingh108** [blockscout/blockscout#6060]
![image](https://user-images.githubusercontent.com/4157381/188623868-fe39bfd3-9053-4329-8c5e-b27af8c6ad21.png)

**Comment by vbaranov** [comment]
@iqbalsingh108 could you share details of deployment? Did you set `MIX_ENV=prod` env variable?

**Comment by vbaranov** [comment]
Closing due to no answer from user
