### ISSUE TITLE
I would like to be a contributor.

### ISSUE THREAD

**Issue by alchemist0803** [blockscout/blockscout#6063]
I used dogechain explorer apis several times and got some errors when trying to get contract source code.
It sometimes says "Something went wrong" with exist contract address.
Not all address throw error just some addressed like "0x99510E7ed4C7b5D8D5E0b735e470e127b4488a7E".
I tried 

> https://explorer.dogechain.dog/api?module=contract&action=getsourcecode&address=0x99510E7ed4C7b5D8D5E0b735e470e127b4488a7E

and it throw error.
Not only this one but many others.

I think I can fix it if you allow me or please fix this problem.
If you let me in, I can add malicious code checker for dogechain in this site like `Token Sniffer`, `Honeypot.is`.

There are many waiting these sites to be completed including me.

Thanks

**Comment by vbaranov** [comment]
dogechain explorer instance uses pretty old version of Blocskcout 4.1.2. The current one is 4.1.8. And there were several updates, which affected mentioned API endpoint, between 4.1.2 and 4.1.8. Most likely the issue will gone with update.

**Comment by vbaranov** [comment]
I am closing this. The endpoint in question doesn't return error anymore.
