### ISSUE TITLE
can't verify contract

### ISSUE THREAD

**Issue by xux1217** [blockscout/blockscout#6066]
*Describe your issue here.*

### Environment

* Deployment type (Manual/Docker/Docker-compose): docker
* Elixir & Erlang/OTP versions (`elixir -version`): use dockerhub image blockscout/blockscout:4.1.8
* Node JS version (`node -v`): use dockerhub image blockscout/blockscout:4.1.8
* Operating System: linux
* Blockscout Version/branch/commit: 4.1.8
* Archive node type && version (Erigon/Geth/Nethermind/Ganache/?): geth 1.10.20

### Steps to reproduce
First, deploy below code. I use remix to deploy, select solc 0.8.9 and optimization 200.

```

  pragma solidity >=0.8.0 <0.9.0;

  contract A {
    function Q()public pure{
        revert("abc");
    }
  }

  contract TEST{

    A a;
    constructor(){
        a = new A();
    }

    event ee(string reason);

    function dd()public{

        try a.Q(){}
        catch Error(string memory revertReason) {
            emit ee(revertReason);
        } 
    }

  }
```

Then, verify these code by flatten method, always report "Bytecode does not match, please try again."

### Expected behaviour

verify success.

### Actual behaviour

can't verify.

**Comment by vbaranov** [comment]
@xux1217 at which Blockscout instance you cannot verify the contract?

**Comment by xux1217** [comment]
> @xux1217 at which Blockscout instance you cannot verify the contract?

Can you verify success?  I used docker image to run an instance, connent our private chain node. We have many contracts, other contracts can be verified, except this one

**Comment by vbaranov** [comment]
Is this private instance of Blockscout?

**Comment by vbaranov** [comment]
@xux1217 you need to run contract verification microservice - it is enhanced sc verifier. We're are working on a common Docker-compose config for both: explorer and sc verifier in frame of this PR https://github.com/blockscout/blockscout/pull/6073

**Comment by xux1217** [comment]
Got it, thanks a lot, I would try it later, and report the result.

**Comment by vbaranov** [comment]
[Docker compose config](https://github.com/blockscout/blockscout/tree/master/docker-compose) updated. Now it includes running of smart-contract verifier service as well. I am closing this issue. If you still experience an issue with smart-contract verification please re-open.

**Comment by LuxesOwen** [comment]
@vbaranov If I deploy blockscout manually,How can I start the verification microservice?

**Comment by vbaranov** [comment]
@LuxesOwen please follow this guide https://docs.blockscout.com/for-developers/information-and-settings/smart-contract-verification

**Comment by LuxesOwen** [comment]
> 
OK. Thranks . I'll try follow it.
