### ISSUE TITLE
about TOKEN_ID column on address_current_token_balances

### ISSUE THREAD

**Issue by donghquinn** [blockscout/blockscout#6068]
*Describe your issue here.*

### Environment

* Deployment type (Manual/Docker/Docker-compose): Docker-Compose
* Elixir & Erlang/OTP versions (`elixir -version`): ELIXIR: 1.13.4-opt-24, ERLANG 24.3.3
* Node JS version (`node -v`): 16.13.0
* Operating System: Ubuntu 20.04-lts
* Blockscout Version/branch/commit: 4.1.7-beta
* Archive node type && version (Erigon/Geth/Nethermind/Ganache/?): Geth

Situation: 
Same Issue #3050 here.

I'm developing API for the NFT for my own service. I want to implement the API shows the token contract address, tokenId, value, metadata, and tokenId for the client. However to query address, token_contract_address, and token_id from address_current_token_balances table, I found out 'token_id' column is null for all rows on 'address_current_token_balances' table. 
I'm confused because I could find token_id from other tables, token_transfers or token_instances.
And it does mean I have to use JOIN from other tables such as token_transfers / token_instances etc... But I want to query all the data I need from one table.

So I want to know the reason why you left the 'token_id' column 'null' on 'address_current_token_balances' and do you have any plan to fix this if you recognize it.

If my understanding is not right or Database is something wrong, please let me know.

Thank you.

P.S. Below is my actual database status. As you can see, All the token_id column show Null for ERC-721 type.

<img width="223" alt="Screen Shot 2022-09-07 at 12 20 57 PM" src="https://user-images.githubusercontent.com/98877622/188781410-229a7bc2-5a7b-4ff3-b997-69362425a3be.png">

------------------------------------------------------------------------------
PLUS
block_number from address_current_token_balances
and block_number from token_transfers
doesn't match. I guess it might cause this issue.

**Comment by phoneix1221** [comment]
Any update on this? @vbaranov  @Qwerty5Uiop
