### ISSUE TITLE
Mainnet: <Issue Title>

### ISSUE THREAD

**Issue by Sep3223** [blockscout/blockscout#6078]
*Describe your issue here.*
Unable to download CSV of transactions for my wallet on dogechain. Can you help? Thanks. 

### Environment
* Elixir Version: 1.12.3
* Erlang Version: 24
* BlockScout Version: 4.1.2

* User Agent: `Mozilla/5.0 (iPhone; CPU iPhone OS 15_2_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/15.2 Mobile/15E148 Safari/604.1`

### Steps to reproduce

*Tell us how to reproduce this issue. If possible, push up a branch to your fork with a regression test we can run to reproduce locally.*

### Expected Behaviour

*Tell us what should happen.*

### Actual Behaviour

*Tell us what happens instead.*

**Comment by vbaranov** [comment]
In order to configure CSV export, instance maintainer should set Google reCAPTCHA RE_CAPTCHA_SECRET_KEY and RE_CAPTCHA_CLIENT_KEY environment varaibles. Blockscout team does not manage mentioned Blockscout instance.

**Comment by Sep3223** [comment]
I don’t understand. Please clarify.
