### ISSUE TITLE
Dogechain Strangeness in Token Swap Process (Block #1944941)

### ISSUE THREAD

**Issue by robotkulubu** [blockscout/blockscout#6087]
I bought 5,923,004,277.76 Doge Eat Bone tokens for 8300 wdoge, but only one in 1000 arrived in my wallet. I traded wdoge to try 5000 pcs. There are currently 5,918,000 Doge Eat Bones in my wallet. Downgraded my 8300 wdoge asset to 8 wdoge. What can I do.  https://explorer.dogechain.dog/tx/0x1569ce16b96fc9cde59fecf48633b66f7e3ba651ce53449b2a69b938ee7bf1c7/token-transfers
### Environment

* Deployment type (Manual/Docker/Docker-compose):
* Elixir & Erlang/OTP versions (`elixir -version`):
* Node JS version (`node -v`):
* Operating System:
* Blockscout Version/branch/commit:
* Archive node type && version (Erigon/Geth/Nethermind/Ganache/?):

### Steps to reproduce

*Tell us how to reproduce this issue.  ❤️ if you can push up a branch to your fork with a regression test we can run to reproduce locally.*

### Expected behaviour

*Tell us what should happen.*

### Actual behaviour

*Tell us what happens instead.*

**Comment by robotkulubu** [comment]
My wallet: 0x6b88FB72D651cDd98449F1CF01827cb0b910bac8

https://explorer.dogechain.dog/address/0xB8b0CDD5Fc2312A7cd445302Ec40D8cB8243CAFD/tokens/0x3FFA83f295FdC28224bc224BeE48AbdF95aD94b6/token-transfers?block_number=1945012&index=1&items_count=850

https://explorer.dogechain.dog/token/0x3FFA83f295FdC28224bc224BeE48AbdF95aD94b6/token-transfers?block_number=1944951&index=2&items_count=1600

**Comment by vbaranov** [comment]
This chat is for technical questions about Blockscout explorer only. Please ask your question with exchange support where your bought tokens.
