### ISSUE TITLE
Create admin panel

### ISSUE THREAD

**Issue by acravenho** [blockscout/blockscout#609]
This admin panel will provide control over several aspects of BlockScout. 

- [ ] block rewards - needs to be customizable due to EIPs and unobtainable chain data.
- [ ] token to USD price - this will match token contracts to CMC data
- [ ] flag an address and provide a warning to the end user in the UI

More features to be added later.

**Comment by alexgaribay** [comment]
Now that I've had some time to research how OpenID works, I don't think this is a viable option for the per-explorer admin panel that we've been discussing. Each explorer would have to register with a auth provider, such as Google, and have their own set of client/secret keys they'd have to manage as part of handling OAuth. This would add more friction for adoption of the application for people who want to self-manage or play with the application. Here is what I propose:

1. Local admin tool uses local authentication by managing users and password
2. UI always forces the user to configure the application before being able to see any data
3. Super-admin tool should become a separate application that can be properly separated out from normal explorers. This would allow the federation of data to take place in the same super-admin application potentially.

@KronicDeth Please correct me if I'm not understanding something correctly here or with add your suggestions.

**Comment by ulyanas** [comment]
Implemented
