### ISSUE TITLE
Ethereum Classic: <transaccion made by mistake>

### ISSUE THREAD

**Issue by vicgrcs** [blockscout/blockscout#6104]
### Steps to reproduce

*this is the transacction https://blockscout.com/etc/mainnet/address/0x645a22AA2916dC937a4dCcBBDD176660875e22Bd*

### Expected Behaviour

*made a wrong transacction to a wallet that doesn't exist by mistake   because that wrong wallet doesn't belong to anyone, please advice...*

### Actual Behaviour

*im wondering if its possible to return this back from the blockchain.*

**Comment by vbaranov** [comment]
ETC Discord https://discord.com/invite/hQs894U. Try to ask there. This chat is for technical questions about Blockscout explorer. Your question is out of scope.
