### ISSUE TITLE
Testnet: exchange from usdt to pls does not work properly

### ISSUE THREAD

**Issue by gerar38** [blockscout/blockscout#6123]
transaction hash 0x8fdee55081e5984fd277c7602f29dafd8ff2db3d41b2c4b16be961680b13cb17 msg: Failed to decode input data.
transaction hash 0x1e2d6ab8052edec0761662705fe2212a521103349e47b501e41f08dca3c1224e msg: Failed to decode input data.

### Environment
* Elixir Version: 1.12.2
* Erlang Version: 24
* BlockScout Version: 

* User Agent: `Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/105.0.0.0 Safari/537.36`

### Steps to reproduce

*Tell us how to reproduce this issue. If possible, push up a branch to your fork with a regression test we can run to reproduce locally.*

### Expected Behaviour

it must exchange usdt to pls

### Actual Behaviour

fail msg
![pls](https://user-images.githubusercontent.com/113627300/190463383-04c25757-1c94-469e-8731-679942f3181c.JPG)

**Comment by vbaranov** [comment]
Pulsechain is unsupported here
