### ISSUE TITLE
BlockScout apis error : Action not found.

### ISSUE THREAD

**Issue by huluBrother** [blockscout/blockscout#6126]
I want get Block  and. transaction.

I  follow the document (https://docs.blockscout.com/for-users/api)

first I use eth rpc
The documentation indicates that the following methods can be used.
```
eth_blockNumber 
eth_call 
eth_getBalance 
eth_getCode 
eth_getBlockByHash 
eth_getBlockByNumber 
eth_getTransactionByHash 
eth_getTransactionByBlockHashAndIndex
eth_getTransactionByBlockNumberAndIndex 
eth_getTransactionReceipt 
eth_getUncleByBlockHashAndIndex 
eth_getLogs
```

when I run  getblock. 
 node is https://blockscout.com/eth/mainnet/api/eth-rpc
   
``` 
{
    "jsonrpc": "2.0",
    "method": "eth_getBlockByNumber",
    "params": [
        "0xed316a",
        true
    ],
    "id": 1
}
``` 

I got error

```
{
    "jsonrpc": "2.0",
    "error": "Action not found.",
    "id": 1
}
```

Then
I begin use blockscout API
https://blockscout.com/eth/mainnet/api-docs.

bug this api is not supply some function.

how do I got block info and translate

**Comment by vbaranov** [comment]
@huluBrother sorry, it was outdated documentation. I updated it. Currently, only 3 JSON RPC methods from the standard set are supported:

- eth_blockNumber 
- eth_getBalance 
- eth_getLogs

However you still can use Etherscan-like API https://blockscout.com/eth/mainnet/api-docs. If you're interested in some specific API endpoint, which we haven't implemented yet, please tell us. We would also hear what is the use case for such API endpoint from your perspective.
