### ISSUE TITLE
Ethereum Classic: <Issue Title>

### ISSUE THREAD

**Issue by rnldyoung0** [blockscout/blockscout#6130]
*Describe your issue here.*
My transaction has been stuck all day  but my coinage dalance shows it available and its not
### Environment
* Elixir Version: 1.13.1
* Erlang Version: 24
* BlockScout Version: v4.1.5-beta

* User Agent: `Mozilla/5.0 (Linux; Android 12; SM-A037U) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/105.0.0.0 Mobile Safari/537.36`

### Steps to reproduce

*Tell us how to reproduce this issue. If possible, push up a branch to your fork with a regression test we can run to reproduce locally.*

### Expected Behaviour

*Tell us what should happen.*

### Actual Behaviour

*Tell us what happens instead.*

**Comment by vbaranov** [comment]
Ethereum Classic Discord is here https://discord.com/invite/bMGuZsA
