### ISSUE TITLE
No transactions in block if no DB connection from the pool

### ISSUE THREAD

**Issue by cen1** [blockscout/blockscout#6135]
If DB connection can't be retrieved from the pool temporarily for whatever reason, explorer ends up in a state with certain blocks having 0 transactions. Block info seems to be saved in the database but no transactions were indexed.

Is there a manual way to force refetch a whole block? Maybe by deleting the block entry from database?

```
Function: &Indexer.Block.Realtime.Fetcher.fetch_and_import_block/3
    Args: [23033826, %Indexer.Block.Fetcher{broadcast: :realtime, callback_module: Indexer.Block.Realtime.Fetcher, json_rpc_named_arguments: [transport: EthereumJSONRPC.HTTP, transport_options: [http: EthereumJSONRPC.HTTP.HTTPoison, url: "http://songbird-api:9650/ext/bc/C/rpc", http_options: [recv_timeout: 600000, timeout: 600000, hackney: [pool: :ethereum_jsonrpc]]], variant: EthereumJSONRPC.Geth], receipts_batch_size: 250, receipts_concurrency: 10}, false]
2022-09-17T12:58:22.236 [error] GenServer #PID<0.31259.129> terminating
** (DBConnection.ConnectionError) connection not available and request was dropped from queue after 2030ms. This means requests are coming in and your connection pool cannot serve them fast enough. You can address this by:...
```
<img width="593" alt="Screenshot 2022-09-19 at 11 10 28" src="https://user-images.githubusercontent.com/1158861/190985492-800d8fc9-887f-4d0f-a765-d43b82d96e3c.png">

### Environment

* Deployment type (Manual/Docker/Docker-compose): manual
* Elixir & Erlang/OTP versions (`elixir -version`): Erlang/OTP 24, elixir 1.13.0
* Node JS version (`node -v`): v16.15.1
* Blockscout Version/branch/commit: 4.1.7-beta
* Archive node type && version (Erigon/Geth/Nethermind/Ganache/?): geth

### Steps to reproduce

Not sure, maybe killing DB connection when realtime fetcher is working? Or setting a very small DB pool on a busy chain.

### Expected behaviour

Blockscout should recover and refetch the block transactions.

### Actual behaviour

Block with no transactions

**Comment by cen1** [comment]
Unfortunately, after deleting the block from the database it was not refetched. We'd need a mechanism to manually trigger this.

**Comment by cen1** [comment]
Small update: temporarily setting FIRST_BLOCK and LAST_BLOCK into the missing range of the deleted block restored the block. Unfortunatelly, the blocks which we did not manually delete from the table still have 0 transactions and were not refetched. TRACE_FIRST_BLOCK/TRACE_LAST_BLOCK also did not resolve the issue.

**Comment by vbaranov** [comment]
@cen1 `Indexer.Fetcher.EmptyBlocksSanitizer` process is responsible to find blocks with 0 transactions and re-fetch them. At the end, it should re-fetch transactions for such blocks automatically. In order to speedup things, you can do it manually: you should set consensus=false for the block with given block numbers in the table `blocks`. Blocks with `consensus=false` will be caught up by indexer automatically and transactions will be re-fetched. In order to even more speedup, you can set FIRST_BLOCK, LAST_BLOCK or BLOCK_RANGES env variable in order to fetch transactions and TRACE_FIRST_BLOCK/TRACE_LAST_BLOCK for refetching of internal transactions.

**Comment by cen1** [comment]
Thanks for the `consensus=false` tip, should come in handy. I will close the issue as I don't have any 0 transaction block examples right now so I can't test it. Will re-open if needed.
