### ISSUE TITLE
Missing block_hash index on logs table, very slow queries

### ISSUE THREAD

**Issue by cen1** [blockscout/blockscout#6136]
logs table is missing an index on `block_hash` column which causes incredibly slow select queries by block and block deletions due to FK  constraint checks.

When trying to delete a block (for https://github.com/blockscout/blockscout/issues/6135) the delete statement never ends. Interrupting the delete prints:

```
CONTEXT:  SQL statement "SELECT 1 FROM ONLY "public"."logs" x WHERE $1 OPERATOR(pg_catalog.=) "block_hash" FOR KEY SHARE OF x"
```

I believe it tries to do a sequential scan of the logs table which is 250M rows (250Gb) in our case.

I believe the same index is missing on internal_transactions which also have an FK constraint on blocks table.

### Environment

* Blockscout Version/branch/commit: 4.1.7-beta

**Comment by cen1** [comment]
Adding this as a simple db migration could cause a significant downtime for production systems on upgrade though: https://www.postgresql.org/docs/current/sql-createindex.html#SQL-CREATEINDEX-CONCURRENTLY

**Comment by vbaranov** [comment]
@cen1 could you please try with the latest release [5.1.3](https://github.com/blockscout/blockscout/releases/tag/v5.1.3-beta)? Is the issue reproducible with it?

**Comment by vbaranov** [comment]
Closing due to no response from the author.
