### ISSUE TITLE
Enhancement of gas price oracle: take into account EIP-1559

### ISSUE THREAD

**Issue by vbaranov** [blockscout/blockscout#6137]
From Discord:

> Ahh thanks. At first sight it DOESN'T take into account EIP1559. I guess what I expected is something like here https://docs.alchemy.com/docs/how-to-build-a-gas-fee-estimator-using-eip-1559. I wonder if it makes a difference?? Since web3 gasPrice is deprecated, and nodes begin to have particular checks for priorityFeePerGas or effectiveFeePerGas. I have experienced some FeeTooLow or FeeTooLowToCompete errors using the xdai gas endpoint recently.

https://discord.com/channels/973915550965174292/973918139664453662/1021445572093292545

**Comment by ulyanas** [comment]
@vbaranov  Please check this PR
