### ISSUE TITLE
coinmarketcap price not update

### ISSUE THREAD

**Issue by qbittex** [blockscout/blockscout#6139]
i add env 
EXCHANGE_RATES_SOURCE=coin_market_cap
EXCHANGE_RATES_COINMARKETCAP_API_KEY=API key

and run again explorer but still price show N/A and marketcap shop $0.00 USD

what i missing please someone help me

**Comment by vbaranov** [comment]
@qbittex you also should set `COIN`, which should be searchable at CoinMarketCap. Did you set?

**Comment by qbittex** [comment]
> @qbittex you also should set `COIN`, which should be searchable at CoinMarketCap. Did you set?

where i set? can you please guide me

**Comment by vbaranov** [comment]
Add `COIN` to the explorer env vars - the same where you set `EXCHANGE_RATES_SOURCE ` and `EXCHANGE_RATES_COINMARKETCAP_API_KEY `. The value is the ticker of the coin, which equal ticker in CoinMarketCap.

**Comment by qbittex** [comment]
> Add `COIN` to the explorer env vars - the same where you set `EXCHANGE_RATES_SOURCE ` and `EXCHANGE_RATES_COINMARKETCAP_API_KEY `. The value is the ticker of the coin, which equal ticker in CoinMarketCap.

already set export COIN=coinname

**Comment by vbaranov** [comment]
What is the value of COIN?

**Comment by qbittex** [comment]
> What is the value of COIN?

$0.0001051

**Comment by vbaranov** [comment]
No, I mean ticker value. What is the coin?

**Comment by qbittex** [comment]
> No, I mean ticker value. What is the coin?

https://coinmarketcap.com/currencies/risu/

RISU

**Comment by vbaranov** [comment]
I see coin price:

![Screenshot 2022-09-26 at 13 56 51](https://user-images.githubusercontent.com/4341812/192259676-22a4c62f-3a0f-4538-b6a3-17d2ed8eddf1.png)
```
COIN=RISU
EXCHANGE_RATES_SOURCE=coin_market_cap
EXCHANGE_RATES_COINMARKETCAP_API_KEY=...
```

Probably, provided CoinMarketCap api key is not valid.

**Comment by qbittex** [comment]
> I see coin price:
> 
> ![Screenshot 2022-09-26 at 13 56 51](https://user-images.githubusercontent.com/4341812/192259676-22a4c62f-3a0f-4538-b6a3-17d2ed8eddf1.png)
> 
> ```
> COIN=RISU
> EXCHANGE_RATES_SOURCE=coin_market_cap
> EXCHANGE_RATES_COINMARKETCAP_API_KEY=...
> ```
> 
> Probably, provided CoinMarketCap api key is not valid.

where you see i have show

![image](https://user-images.githubusercontent.com/87224959/192260397-da96c002-ebbb-4f9e-b36f-f2c7845fbf4f.png)

**Comment by vbaranov** [comment]
I just run Blockscout locally with env variables, I've posted above. How did you run Blockscout?

**Comment by qbittex** [comment]
> I just run Blockscout locally with env variables, I've posted above. How did you run Blockscout?

i run on server 

can you give me api which you use for testing and its show you price

**Comment by vbaranov** [comment]
I provided ENV vars above, which I set for my local deployment. I follow https://docs.blockscout.com/for-developers/manual-deployment. Is your deployment is different?

**Comment by qbittex** [comment]
> I provided ENV vars above, which I set for my local deployment. I follow https://docs.blockscout.com/for-developers/manual-deployment. Is your deployment different?

you use coinmarketcap basic API or pro?

**Comment by qbittex** [comment]
> I just run Blockscout locally with env variables, I've posted above. How did you run Blockscout?

which command you run blockscout locally can you please tell me

**Comment by vbaranov** [comment]
Exectly as in the guide:
> 14) Return to the root directory and start the Phoenix Server. mix phx.server

**Comment by qbittex** [comment]
> Exectly as in the guide:
> 
> > 14. Return to the root directory and start the Phoenix Server. mix phx.server

if i want remove price and chart and put there
Tx/day  so how i set in env

**Comment by vbaranov** [comment]
@qbittex I didn't get from you how did you run Blockscout, but if you're using Docker-compose you need also set `DISABLE_EXCHANGE_RATES=false`. By default price feed is disabled.

**Comment by vbaranov** [comment]
I am closing this. Let us know if you still experience the issue.
