### ISSUE TITLE
> EXCHANGE_RATES_COINGECKO_API_KEY

### ISSUE THREAD

**Issue by benzntech** [blockscout/blockscout#6142]
> EXCHANGE_RATES_COINGECKO_API_KEY

but this key is not available or is blank? quick look through coin gecko api docs show no sign of api_keys

I've also left the following environment variables in place but it didn't fetch from coin gecko api

SOURCE_MODULE=coin_gecko
EXCHANGE_RATES_SOURCE=coin_gecko
EXCHANGE_RATES_COINGECKO_API_KEY=

_Originally posted by @samoclay in https://github.com/blockscout/blockscout/issues/5678#issuecomment-1212068181_

**Comment by vbaranov** [comment]
@benzntech https://docs.blockscout.com/for-developers/information-and-settings/env-variables#exchange-rates-management
Are you at the latest release of Blockscout? you also should set `EXCHANGE_RATES_COINGECKO_COIN_ID`. Please unset `SOURCE_MODULE ` as well - it is deprecated.
