### ISSUE TITLE
ERC721 /instance/{tokenId}/token-transfers  404 not found

### ISSUE THREAD

**Issue by youngqqcn** [blockscout/blockscout#6144]
*Describe your issue here.*

http://172.16.100.70:4000/token/0xe03ad76d6411790208fe5c7bd965a079ed748967/instance/168/token-transfers

- v4.1.8-beta

![image](https://user-images.githubusercontent.com/30211020/191481740-0e501fd1-8d64-4eea-aefe-daf7acd68af5.png)

**Comment by vbaranov** [comment]
@youngqqcn could you pull updates from master branch? It has the fix to this issue.

**Comment by youngqqcn** [comment]
@vbaranov I have merged master branch right now, but this issue still exists.  I found your mainnet explorer also exists this issue.


https://blockscout.com/eth/mainnet/token/0x69a7df5c3a787c4d93b818d219856bec59f29887/instance/258/token-transfers

**Comment by youngqqcn** [comment]
If an ERC721 contract was set with an incorrect `baseURI`, the explorer couldn't fetch metadata of the token, when the user clicks a `tokenId` will cause `404` page.

**Comment by vbaranov** [comment]
@youngqqcn all token instances are indexed on the links provided in the issue. If the issue still persists, please re-open it.
