### ISSUE TITLE
address page fetching transtions and token is too slow

### ISSUE THREAD

**Issue by youngqqcn** [blockscout/blockscout#6145]
v4.1.7-beta

![image](https://user-images.githubusercontent.com/30211020/191483840-6e5ac595-009a-429b-95f0-bf52b4299dad.png)

**Comment by youngqqcn** [comment]
https://explorer-test.rarefy.vip/address/0xC2ED445Ee8DC5791662C574CE21dA57Ba5F2c79f

**Comment by vbaranov** [comment]
It is caching for a first time. Works fine now, as far as I can see.

![Screenshot 2022-09-22 at 14 06 13](https://user-images.githubusercontent.com/4341812/191731005-58f001f6-e5f7-464c-a728-8a70ccdee27e.png)

**Comment by youngqqcn** [comment]
@vbaranov  But my mainnet can not load completely within 10 minutes. How to optimize this loading?

https://explorer.qiyihuo.com/address/0x384F591ed5E76E5dE146A7672674B69051413c7F

My DB server's hardware config with 16cores 32GB

**Comment by vbaranov** [comment]
It looks like it loads it ultimately in 1 sec.

<img width="486" alt="Screenshot 2022-11-13 at 22 31 33" src="https://user-images.githubusercontent.com/4341812/201540550-119c3550-79fc-4269-88a1-32332c3e6e87.png">

I am closing this issue for now.
