### ISSUE TITLE
`token_instances` tables is empty

### ISSUE THREAD

**Issue by youngqqcn** [blockscout/blockscout#6149]
*Describe your issue here.*

### Environment

* Deployment type (Manual/Docker/Docker-compose):
* Elixir & Erlang/OTP versions (`elixir -version`):
* Node JS version (`node -v`):
* Operating System:
* Blockscout Version/branch/commit: v4.1.7
* Archive node type && version (Erigon/Geth/Nethermind/Ganache/?):

### Steps to reproduce

*Tell us how to reproduce this issue.  ❤️ if you can push up a branch to your fork with a regression test we can run to reproduce locally.*

### Expected behaviour

*Tell us what should happen.*

### Actual behaviour

*Tell us what happens instead.*

```
select * from token_instances;
 token_id | token_contract_address_hash | metadata | inserted_at | updated_at | error 
----------+-----------------------------+----------+-------------+------------+-------
(0 rows)
```

**Comment by vbaranov** [comment]
@youngqqcn tell a bit more about setup

**Comment by vbaranov** [comment]
I am closing this due to no feedback from the user.
