### ISSUE TITLE
Change miner field name on ETH mainnet

### ISSUE THREAD

**Issue by sl1depengwyn** [blockscout/blockscout#6156]
Maybe worth changing miner field name on ETH mainnet to something like validator or staker
![IMG_20220924_183002](https://user-images.githubusercontent.com/53992153/192106391-26ee81ef-75e3-4303-ba9d-1571e5bb2bf2.jpg)

**Comment by vbaranov** [comment]
Thank you. Fixed to `Fee Recipient`.
