### ISSUE TITLE
Mined transaction is still shown as pending for long time

### ISSUE THREAD

**Issue by aminlatifi** [blockscout/blockscout#6171]
A gnosis-chain transaction has been mined several minutes ago, but blockscout shows it as a pending transaction

https://blockscout.com/xdai/mainnet/tx/0x6e5bebae7feb0a95e33f2e9edb764767ed648f7a586d39d5c0b70e05dff6fbf1
### Environment
Gnosi-chain

### Expected behaviour

Index the transaction and allow me to work with the created contract

### Actual behaviour

<img width="1374" alt="image" src="https://user-images.githubusercontent.com/5684607/192475606-9648c2ae-37d2-47b8-a137-8f3b61521958.png">

**Comment by vbaranov** [comment]
![Screenshot 2022-09-27 at 13 02 05](https://user-images.githubusercontent.com/4341812/192497112-f3083783-33f2-4788-9070-a4c2b59cf131.png)

transaction state changed to confirmed.
