### ISSUE TITLE
Mainnet: <Issue Title>

### ISSUE THREAD

**Issue by Lungers1021** [blockscout/blockscout#6172]
*sent over 6461 doge from metamask to binance and it says completed but not arrived in binance wallet, ive contacted metamask and they CAN see it, but its a issue on binance end as there the recieving party, ive contacted binance 3 times and they can't see it on the blockchain.
TxID/TxHash : 0x39cd232a5afa691d785ddf96d3bd606a62edeece89f1e450b624b04ea7e3bbc9

From: 0xc185280ddbb84b550d6cb26be2fa61aa3c25da6e

To : 0x0abf8fe2898aa8d27d128f3f37418a0f7a65fce2

I wonder if you could share some light on this confusion.

Kind regards 
Lungers
*

### Environment
* Elixir Version: 1.12.3
* Erlang Version: 24
* BlockScout Version: 4.1.2

* User Agent: `Mozilla/5.0 (Linux; Android 12; SAMSUNG SM-A326B) AppleWebKit/537.36 (KHTML, like Gecko) SamsungBrowser/18.0 Chrome/99.0.4844.88 Mobile Safari/537.36`

### Steps to reproduce

*Tell us how to reproduce this issue. If possible, push up a branch to your fork with a regression test we can run to reproduce locally.*

### Expected Behaviour

*Tell us what should happen.*

### Actual Behaviour

*Tell us what happens instead.*

**Comment by vbaranov** [comment]
Please contact exchange in regards to your issue. This chat is for technical issues with Blockscout explorer.
