### ISSUE TITLE
Hi,I'm getting error on my blockscout explorer

### ISSUE THREAD

**Issue by iqbalsingh108** [blockscout/blockscout#6181]
Due to error my blocks are not syncing properly.But its syncing when i'm running this without domain,i mean on IP:port pattern .Please check the error screenshot are as follows

![image](https://user-images.githubusercontent.com/4157381/192709137-607b68ed-1981-4529-a65d-eb551daac7f2.png)

Please help me on this

Thanks

**Comment by vbaranov** [comment]
You should follow this advise https://github.com/blockscout/blockscout/issues/4963#issuecomment-1033508838 in case onf Nginx reverse proxy configured. If you don;t use Nginx, please provide more details how did you configured explorer accessible via domain name.
