### ISSUE TITLE
Testnet: <Issue Title>

### ISSUE THREAD

**Issue by SOLEREAPER187** [blockscout/blockscout#6201]
I  sacrifice from  Trust wallet I don't really know how to read The way the information of my coins  Is in the wallet block I guess It says 2 coins worth 71,000 plsx a piece and  I don't know how to get them out into my wallet and like I said I don't know how to read it but kinda looks like somebody transferred them out but when I type it in it says it's still there.... 7,000 is alot to me i could  gave got a car but it sounded like and opportunity hope it's still there and able to move it please help!😂😭

### Environment
* Elixir Version: 1.12.2
* Erlang Version: 24
* BlockScout Version: 

* User Agent: `Mozilla/5.0 (Linux; Android 12; SM-A536U) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/105.0.0.0 Mobile Safari/537.36`

### Steps to reproduce

*Tell us how to reproduce this issue. If possible, push up a branch to your fork with a regression test we can run to reproduce locally.*

### Expected Behaviour

*Tell us what should happen.*

### Actual Behaviour

*Tell us what happens instead.*

**Comment by vbaranov** [comment]
This issue doesn't relate to Blocskcout
