### ISSUE TITLE
Blockscout_Container_Params

### ISSUE THREAD

**Issue by avenbreaks** [blockscout/blockscout#6206]
I installed blockscout with docker in azure clouds but I see the ENV file is placed into the Makefile, and I want to change the logo, name, subnetwork, etc. I'm confused by the code can it be replaced from ~>

```
BLOCKSCOUT_CONTAINER_PARAMS += -e 'NETWORK=$(NETWORK)'
BLOCKSCOUT_CONTAINER_PARAMS += -e 'TESTCHAIN=$(NETWORK)'
```
Please forgive me if my inquiry is unclear. This is my first time using elixir and blockscout.

### Environment

* Deployment type (Docker/Docker-compose):
* Elixir & Erlang/OTP versions (`24/otp`):
* Node JS version (`14.17.0`):
* Operating System: (`Ubuntu 22.0`):
* Blockscout Version/branch/commit: 

Makefile : 
```
ifdef NETWORK
	BLOCKSCOUT_CONTAINER_PARAMS += -e 'NETWORK=$(NETWORK)'
endif
ifdef SUBNETWORK
	BLOCKSCOUT_CONTAINER_PARAMS += -e 'SUBNETWORK=$(SUBNETWORK)'
endif
```
![image](https://user-images.githubusercontent.com/93043826/193494470-7ec3e526-cf35-4032-8f09-f6ece44102fd.png)

**Comment by vbaranov** [comment]
@avenbreaks you shouldn't change Makefile. Just put environment variables with the command you running Makefile or set them to the current shell where you running Make file. Please take a look at a full guide for running Blockscout from Makefile https://docs.blockscout.com/for-developers/information-and-settings/docker-integration-local-use-only. Or probably even simpler, you can try run with `docker compose` configurations https://github.com/blockscout/blockscout/tree/master/docker-compose#readme.

**Comment by vbaranov** [comment]
I am closing this. Please let us know if the issue still persists.
