### ISSUE TITLE
Gnosis Chain: blockscout doesn't show my transactions and created contracts

### ISSUE THREAD

**Issue by aminlatifi** [blockscout/blockscout#6222]
I had made a couple of transactions and created contracts by this account 0x5f672d71399d8cDbA64f596394b4f4381247E025
But none of them are visible, while https://gnosisscan.io/address/0x5f672d71399d8cdba64f596394b4f4381247e025 shows them

<img width="1445" alt="image" src="https://user-images.githubusercontent.com/5684607/193813750-16e95069-9801-4b43-9ebb-0586d2c772d6.png">

<img width="1383" alt="image" src="https://user-images.githubusercontent.com/5684607/193813913-cba07ec0-203a-4bbf-8e95-451811538dec.png">

**Comment by vbaranov** [comment]
@aminlatifi they should be visible now. Please let me know if they still aren't visible. It was a temporary issue with the indexing of internal transactions and contract codes from them.
