### ISSUE TITLE
The input path "priv/static" does not exist

### ISSUE THREAD

**Issue by Ranofty** [blockscout/blockscout#6225]
### Environment

* Deployment type (Manual/Localhost):
* Elixir & Erlang/OTP versions (`Elixir 1.13.4 (compiled with Erlang/OTP 24) : erlang 24.3.4.1`):
* Node JS version (`v16.15.1`):
* Operating System: MacOS Monterey
* Blockscout Version/branch/commit: v4.1.8-beta

Hello good day please am getting this error

==> ethereum_jsonrpc
The input path "priv/static" does not exist
==> explorer
The input path "priv/static" does not exist
==> indexer
The input path "priv/static" does not exist
==> block_scout_web
Check your digested files at "priv/static"

when running `sudo mix phx.digest` please any solution for that? what should i do next please?

**Comment by vbaranov** [comment]
@Ranofty these warnings shouldn't break anything. Those warnings mean that `static` folder doesn't exist in `ethereum_jsonrpc`, `explorer`, and `indexer` applications. And this is true. It only exists in `block_scout_web` application.

**Comment by vbaranov** [comment]
You should repeat the same procedure, which you followed in your local setup, on cloud instance.

**Comment by vbaranov** [comment]
Please let us know if you still experience issues with deployment. I am closing this for now.

**Comment by punithbm** [comment]
Hi @Ranofty  can you share the steps you followed for manual deployment of blockscout
