### ISSUE TITLE
Help to run blockcout on aws cloud

### ISSUE THREAD

**Issue by Ranofty** [blockscout/blockscout#6235]
*Describe your issue here.*

### Environment

* Deployment type (aws cloud):
* Elixir & Erlang/OTP versions (`1.13.4`):
* Node JS version (`16`):
* Operating System: Ubuntu 20.04
* Archive node type && version (polygon edge):

Hello please i need help to run blockscout am already done with all the processes but can't open it on browser
below are my logs

sudo systemctl start explorer.service

sudo systemctl status explorer.service

● explorer.service - chainscan Server
Loaded: loaded (/etc/systemd/system/explorer.service; enabled; vendor pres>
Active: activating (auto-restart) (Result: exit-code) since Sun 2022-10-09>
Process: 89264 ExecStart=/usr/local/bin/mix phx.server (code=exited, status>
Main PID: 89264 (code=exited, status=1/FAILURE)

Oct 09 09:09:14 ip-172-31-68-184 systemd[1]: explorer.service: Failed with resu>
lines 1-7/7 (END)

sudo journalctl -u explorer.service -f

45: Config.import!/1
Oct 09 09:11:45 ip-172-31-68-184 mix[92502]: (stdlib 3.17.1) erl_eval.erl:685: :erl_eval.do_apply/6
Oct 09 09:11:45 ip-172-31-68-184 mix[92502]: (stdlib 3.17.1) erl_eval.erl:123: :erl_eval.exprs/5
Oct 09 09:11:45 ip-172-31-68-184 mix[92502]: (elixir 1.13.4) lib/code.ex:404: Code.validated_eval_string/3
Oct 09 09:11:45 ip-172-31-68-184 mix[92502]: (stdlib 3.17.1) erl_eval.erl:685: :erl_eval.do_apply/6
Oct 09 09:11:45 ip-172-31-68-184 systemd[1]: explorer.service: Main process exited, code=exited, status=1/FAILURE
Oct 09 09:11:45 ip-172-31-68-184 systemd[1]: explorer.service: Failed with result 'exit-code'.
Oct 09 09:11:46 ip-172-31-68-184 systemd[1]: explorer.service: Scheduled restart job, restart counter is at 1416.
Oct 09 09:11:46 ip-172-31-68-184 systemd[1]: Stopped chainscan Server.
Oct 09 09:11:46 ip-172-31-68-184 systemd[1]: Started chainscan Server.
Oct 09 09:11:47 ip-172-31-68-184 mix[92540]: ** (File.Error) could not read file "/usr/local/blockscout/apps/block_scout_web/config/prod# run in production mode.exs": no such file or directory
Oct 09 09:11:47 ip-172-31-68-184 mix[92540]: (elixir 1.13.4) lib/file.ex:355: File.read!/1
Oct 09 09:11:47 ip-172-31-68-184 mix[92540]: (elixir 1.13.4) lib/config.ex:245: Config.import!/1
Oct 09 09:11:47 ip-172-31-68-184 mix[92540]: (stdlib 3.17.1) erl_eval.erl:685: :erl_eval.do_apply/6
Oct 09 09:11:47 ip-172-31-68-184 mix[92540]: (stdlib 3.17.1) erl_eval.erl:123: :erl_eval.exprs/5
Oct 09 09:11:47 ip-172-31-68-184 mix[92540]: (elixir 1.13.4) lib/code.ex:404: Code.validated_eval_string/3
Oct 09 09:11:47 ip-172-31-68-184 mix[92540]: (stdlib 3.17.1) erl_eval.erl:685: :erl_eval.do_apply/6
Oct 09 09:11:47 ip-172-31-68-184 systemd[1]: explorer.service: Main process exited, code=exited, status=1/FAILURE
Oct 09 09:11:47 ip-172-31-68-184 systemd[1]: explorer.service: Failed with result 'exit-code'.
Oct 09 09:11:48 ip-172-31-68-184 systemd[1]: explorer.service: Scheduled restart job, restart counter is at 1417.
Oct 09 09:11:48 ip-172-31-68-184 systemd[1]: Stopped chainscan Server.
Oct 09 09:11:48 ip-172-31-68-184 systemd[1]: Started chainscan Server.
Oct 09 09:11:49 ip-172-31-68-184 mix[92578]: ** (File.Error) could not read file "/usr/local/blockscout/apps/block_scout_web/config/prod# run in production mode.exs": no such file or directory
Oct 09 09:11:49 ip-172-31-68-184 mix[92578]: (elixir 1.13.4) lib/file.ex:355: File.read!/1
Oct 09 09:11:49 ip-172-31-68-184 mix[92578]: (elixir 1.13.4) lib/config.ex:245: Config.import!/1
Oct 09 09:11:49 ip-172-31-68-184 mix[92578]: (stdlib 3.17.1) erl_eval.erl:685: :erl_eval.do_apply/6
Oct 09 09:11:49 ip-172-31-68-184 mix[92578]: (stdlib 3.17.1) erl_eval.erl:123: :erl_eval.exprs/5
Oct 09 09:11:49 ip-172-31-68-184 mix[92578]: (elixir 1.13.4) lib/code.ex:404: Code.validated_eval_string/3
Oct 09 09:11:49 ip-172-31-68-184 mix[92578]: (stdlib 3.17.1) erl_eval.erl:685: :erl_eval.do_apply/6
Oct 09 09:11:49 ip-172-31-68-184 systemd[1]: explorer.service: Main process exited, code=exited, status=1/FAILURE
Oct 09 09:11:49 ip-172-31-68-184 systemd[1]: explorer.service: Failed with result 'exit-code'.
Oct 09 09:11:50 ip-172-31-68-184 systemd[1]: explorer.service: Scheduled restart job, restart counter is at 1418.
Oct 09 09:11:50 ip-172-31-68-184 systemd[1]: Stopped chainscan Server.
Oct 09 09:11:50 ip-172-31-68-184 systemd[1]: Started chainscan Server.
Oct 09 09:11:50 ip-172-31-68-184 mix[92616]: ** (File.Error) could not read file "/usr/local/blockscout/apps/block_scout_web/config/prod# run in production mode.exs": no such file or directory
Oct 09 09:11:50 ip-172-31-68-184 mix[92616]: (elixir 1.13.4) lib/file.ex:355: File.read!/1
Oct 09 09:11:50 ip-172-31-68-184 mix[92616]: (elixir 1.13.4) lib/config.ex:245: Config.import!/1
Oct 09 09:11:50 ip-172-31-68-184 mix[92616]: (stdlib 3.17.1) erl_eval.erl:685: :erl_eval.do_apply/6
Oct 09 09:11:50 ip-172-31-68-184 mix[92616]: (stdlib 3.17.1) erl_eval.erl:123: :erl_eval.exprs/5
Oct 09 09:11:50 ip-172-31-68-184 mix[92616]: (elixir 1.13.4) lib/code.ex:404: Code.validated_eval_string/3
Oct 09 09:11:50 ip-172-31-68-184 mix[92616]: (stdlib 3.17.1) erl_eval.erl:685: :erl_eval.do_apply/6
Oct 09 09:11:50 ip-172-31-68-184 systemd[1]: explorer.service: Main process exited, code=exited, status=1/FAILURE
Oct 09 09:11:50 ip-172-31-68-184 systemd[1]: explorer.service: Failed with result 'exit-code'.
Oct 09 09:11:52 ip-172-31-68-184 systemd[1]: explorer.service: Scheduled restart job, restart counter is at 1419.
Oct 09 09:11:52 ip-172-31-68-184 systemd[1]: Stopped chainscan Server.
Oct 09 09:11:52 ip-172-31-68-184 systemd[1]: Started chainscan Server.
Oct 09 09:11:52 ip-172-31-68-184 mix[92654]: ** (File.Error) could not read file "/usr/local/blockscout/apps/block_scout_web/config/prod# run in production mode.exs": no such file or directory
Oct 09 09:11:52 ip-172-31-68-184 mix[92654]: (elixir 1.13.4) lib/file.ex:355: File.read!/1
Oct 09 09:11:52 ip-172-31-68-184 mix[92654]: (elixir 1.13.4) lib/config.ex:245: Config.import!/1
Oct 09 09:11:52 ip-172-31-68-184 mix[92654]: (stdlib 3.17.1) erl_eval

sudo netstat -tulpn

Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address Foreign Address State PID/Program name
tcp 0 0 127.0.0.53:53 0.0.0.0:* LISTEN 2869/systemd-resolv
tcp 0 0 0.0.0.0:22 0.0.0.0:* LISTEN 794/sshd: /usr/sbin
tcp6 0 0 :::22 :::* LISTEN 794/sshd: /usr/sbin
udp 0 0 0.0.0.0:37999 0.0.0.0:* 22146/avahi-daemon:
udp 0 0 0.0.0.0:5353 0.0.0.0:* 22146/avahi-daemon:
udp 0 0 127.0.0.53:53 0.0.0.0:* 2869/systemd-resolv
udp 0 0 172.35.62.187:69 0.0.0.0:* 2863/systemd-networ
udp6 0 0 :::37399 :::* 22146/avahi-daemon:
udp6 0 0 :::5353 :::* 22146/avahi-daemon:

i need your help on this please

**Comment by avenbreaks** [comment]
in your MIX_ENV= "prod" delete this # run in production mode

**Comment by Ranofty** [comment]
Hello i follow all the steps from [Polygon-Edge](https://wiki.polygon.technology/docs/edge/additional-features/blockscout/) then i got thos logs below are where am suspecting my errors from 

1, When running `createuser --interactive` i got this error

createuser --interactive
Enter name of role to add: blockscout
Shall the new role be a superuser? (y/n) y
createuser: error: creation of new role failed: ERROR: must be superuser to create superusers

2, when `sudo touch /etc/systemd/system/explorer.service` and `sudo vi /etc/systemd/system/explorer.service`

i only change description here

[Unit]
Description=chainscan Server
After=network.target
StartLimitIntervalSec=0

[Service]
Type=simple
Restart=always
RestartSec=1
User=root
StandardOutput=syslog
StandardError=syslog
WorkingDirectory=/usr/local/blockscout
ExecStart=/usr/local/bin/mix phx.server
EnvironmentFile=/usr/local/blockscout/env_vars.env

[Install]
WantedBy=multi-user.target

i don't really know exactly what to replace there as am new to Elixir

3, This `cd apps/block_scout_web mix phx.gen.cert blockscout blockscout.local` i always run this command which am cofused on exactly how to use it.


Also how can i locate the `MIX_ENV=prod` file?

**Comment by avenbreaks** [comment]
> 

`sudo vi /usr/local/blockscout/env_vars.env`

you can edit in env file, or you can use AWS RDS or Azure PostgreSQL alternative

**Comment by Ranofty** [comment]
Thanks for your response 
i follow all what you said and is running but still cant open it in browser is this from the script or from my aws security groups? 

please take a look at my logs and security group setup the inbound and outbound are having same set up

Logs

![iScreen Shoter - 20221011101854421](https://user-images.githubusercontent.com/59210788/195052818-2d699fae-85b2-4dae-9cbf-3d343cb31ed4.jpg)

Security Group

![iScreen Shoter - 20221011102255898](https://user-images.githubusercontent.com/59210788/195053050-f969c8ed-13a8-4e55-8142-fc6e97beb1a1.jpg)

**Comment by Ranofty** [comment]
Any respond please am stuck here your assistants will really help 😪 Thanks 🙏

**Comment by avenbreaks** [comment]
> Any respond please am stuck here your assistants will really help sleepy Thanks pray

have you tried the docker version? 
`https://github.com/blockscout/blockscout/tree/master/docker-compose`

**Comment by Ranofty** [comment]
Thanks is now working 🤩🙏

**Comment by avenbreaks** [comment]
> Thanks is now working star_struckpray

you're welcome, because I'm also researching polygon edges :)
