### ISSUE TITLE
Blockscout : Authenticity is not established by certificate path validation

### ISSUE THREAD

**Issue by avenbreaks** [blockscout/blockscout#6241]
in my case blockscout after deploy in VM did not find the port 5432 & 4000, im done active inboud port from panel azure. alternatively I tried to deploy postgresql in Azure SQL Flexibel but I still encounter the same problem. are my postgresql settings wrong?

First Setting:
`export DATABASE_URL=postgresql://blockscoutadm:asdasdasdasd23@52.188.91.5:5432/postgre
`

Second Setting Azure PostgreSQL Flexibel : 
`export DATABASE_URL=postgresql://blockscout:asdasdasdasd23@postgrestlavnos1.postgres.database.azure.com:5432/postgres
`

### Environment

* Deployment type (Manual):
* Elixir & Erlang/OTP versions (`Erlang/OTP 24 & Elixir 1.13.4`):
* Node JS version (`14.17.0`):
* Operating System: `Ubuntu 22.04.1 LTS x86_64`

My ENV File Configuration:

```
ETHEREUM_JSONRPC_HTTP_URL="http://3.93.199.23:10002"
ETHEREUM_JSONRPC_TRACE_URL="http://3.93.199.23:10002"
DATABASE_URL='postgresql://blockscout:asdasdasdasd23@postgrestlavnos1.postgres.database.azure.com:5432/postgres'
SECRET_KEY_BASE="7zeK/XLrhO1FRsojaBe6KGGKhuyLDQT8HKuCfqAAtgrSZ0s+5BA7c+9mMAKMcwl1"
ETHEREUM_JSONRPC_WS_URL="ws://3.93.199.23:10002"
CHAIN_ID=212 # chain id
HEART_COMMAND="systemctl restart explorer"
SUBNETWORK="Blockchain Explorer"
LOGO="/images/logo.svg"
LOGO_FOOTER="/images/logo.svg"
COIN="ASDF" 
COIN_NAME="ASDF Coin"
INDEXER_DISABLE_BLOCK_REWARD_FETCHER="true"
INDEXER_DISABLE_PENDING_TRANSACTIONS_FETCHER="true"
INDEXER_DISABLE_INTERNAL_TRANSACTIONS_FETCHER="true"
MIX_ENV="prod"
BLOCKSCOUT_PROTOCOL="http"
PORT=4000
DISABLE_EXCHANGE_RATES="true"
POOL_SIZE=200
POOL_SIZE_API=300
ECTO_USE_SSL="false"
HEART_BEAT_TIMEOUT=60
INDEXER_MEMORY_LIMIT="10Gb"
FETCH_REWARDS_WAY="manual"
INDEXER_EMPTY_BLOCKS_SANITIZER_BATCH_SIZE=1000
```

### Logs

`Oct 11 06:32:08 Ethereum-Client mix[150730]: Reason: 'Option {verify, verify_peer} and cacertfile/cacerts is missing'`
`Oct 11 06:32:08 Ethereum-Client mix[150730]: 2022-10-11T06:32:08.529 application=db_connection [error] Postgrex.Protocol (#PID<0.1151.0>) failed to connect: ** (Postgrex.Error) FATAL 53300 (too_many_connections) sorry, too many clients already`
`Oct 11 06:32:08 Ethereum-Client mix[150730]: 2022-10-11T06:32:08.538 application=db_connection [error] Postgrex.Protocol (#PID<0.1158.0>) failed to connect: ** (Postgrex.Error) FATAL 53300 (too_many_connections) sorry, too many clients already`
`Oct 11 06:32:08 Ethereum-Client mix[150730]:     ** (EXIT) an exception was raised:
Oct 11 06:32:08 Ethereum-Client mix[150730]:         ** (MatchError) no match of right hand side value: {:error, %Postgrex.Error{connection_id: nil, message: nil, postgres: %{code: :invalid_password, file: "auth.c", line: "422", message: "password authentication failed for user \"blockscout\"", pg_code: "28P01", routine: "auth_failed", severity: "FATAL", unknown: "FATAL"}, query: nil}}`

**Comment by avenbreaks** [comment]
solved

**Comment by AndreMiras** [comment]
> solved

How did you solve it?
By the way you shared your credentials with `DATABASE_URL` above, maybe you should reset the password if you haven't already
