### ISSUE TITLE
How to roll back the latest of several blocks

### ISSUE THREAD

**Issue by free1** [blockscout/blockscout#6242]
If i need to roll back a few blocks, how to do it better?

**Comment by vbaranov** [comment]
If you want to re-fetch some blocks, you can set `consensus=false` for that block numbers in `blocks` table. And catchup indexer should re-fetch them. In order to speed up re-fetching, you can temporarily set `FIRST_BLOCK` and `END_BLOCK` - in this range catchup indexer will reindex.

**Comment by free1** [comment]
This way can be updated blocks information, thanks👍
