### ISSUE TITLE
Manual install fails at the step "mix do deps.get"

### ISSUE THREAD

**Issue by KevinSmall** [blockscout/blockscout#6245]
Manual install fails at the step "mix do deps.get"

### Environment

* Deployment type (Manual/Docker/Docker-compose): Manual
* Elixir & Erlang/OTP versions (`elixir --version`): 
Erlang/OTP 22 [erts-10.6.4] [source] [64-bit] [smp:2:2] [ds:2:2:10] [async-threads:1]
Elixir 1.9.1 (compiled with Erlang/OTP 22)
* Node JS version (`node -v`): v18.10.0
* Operating System: Ubuntu 20.04.5 LTS
* Blockscout Version/branch/commit:  commit 5edd5558d08f0ebd25dac5e56cbad43b2ff46108 (HEAD -> master, origin/master, origin/HEAD)
* Archive node type && version (Erigon/Geth/Nethermind/Ganache/?): Geth

### Steps to reproduce
Follow manual install steps here: https://docs.blockscout.com/for-developers/manual-deployment all ok until this step:
```
4) Install Mix dependencies and compile them `mix do deps.get, local.rebar --force, deps.compile`
```

### Expected behaviour
No errors shown

### Actual behaviour
Step fails to compile:
```
$ mix do deps.get, local.rebar --force, deps.compile
** (CompileError) config/config.exs:67: undefined function config_env/0
    (elixir) src/elixir_bitstring.erl:142: :elixir_bitstring.expand_expr/4
    (elixir) src/elixir_bitstring.erl:27: :elixir_bitstring.expand/8
    (elixir) src/elixir_bitstring.erl:20: :elixir_bitstring.expand/4
    (stdlib) lists.erl:1354: :lists.mapfoldl/3
    (elixir) expanding macro: Config.import_config/1
```

**Comment by vbaranov** [comment]
@KevinSmall 

> Erlang/OTP 22 [erts-10.6.4] [source] [64-bit] [smp:2:2] [ds:2:2:10] [async-threads:1]
> Elixir 1.9.1 (compiled with Erlang/OTP 22)

These are unsupported versions. you should upgrade to Erlang/OTP 25 and Elixir 1.14.1

**Comment by KevinSmall** [comment]
Thanks Victor, I did the upgrades and got further, but get a different error during compilation.

Now the versions are:
```
$ elixir --version
Erlang/OTP 25 [erts-13.0.4] [source] [64-bit] [smp:2:2] [ds:2:2:10] [async-threads:1] [jit:ns]
Elixir 1.14.1 (compiled with Erlang/OTP 25)
```
I also took an update from the repo and so now the commit is:
```
commit 158154272c064ab7c3889f68eb12385b23b2d7dd (HEAD -> master, origin/master, origin/HEAD)
Merge: 9815b799d d8a16e8f2
```

Then:
```
$ mix do deps.get, local.rebar --force, deps.compile
```
does lots of work then gives:
```
===> Analyzing applications...
===> Compiling mimerl
===> Analyzing applications...
===> Compiling ranch
make: Entering directory '/home/qbs/blockscout/deps/prometheus_process_collector/c_src'
make: '/home/qbs/blockscout/deps/prometheus_process_collector/c_src/../priv/prometheus_process_collector.so' is up to date.
make: Leaving directory '/home/qbs/blockscout/deps/prometheus_process_collector/c_src'
===> Analyzing applications...
===> Compiling prometheus_process_collector
===> Analyzing applications...
===> Compiling certifi
==> ex_keccak
Compiling 1 file (.ex)

== Compilation error in file lib/ex_keccak.ex ==
** (ErlangError) Erlang error: :enoent
    (elixir 1.14.1) lib/system.ex:1060: System.cmd("cargo", ["metadata", "--format-version=1"], [cd: "native/exkeccak"])
    (rustler 0.26.0) lib/rustler/compiler/config.ex:82: Rustler.Compiler.Config.metadata!/1
    (rustler 0.26.0) lib/rustler/compiler/config.ex:69: Rustler.Compiler.Config.build/1
    (rustler 0.26.0) lib/rustler/compiler.ex:9: Rustler.Compiler.compile_crate/2
    lib/ex_keccak.ex:6: (module)
could not compile dependency :ex_keccak, "mix compile" failed. Errors may have been logged above. You can recompile this dependency with "mix deps.compile ex_keccak", update it with "mix deps.update ex_keccak" or clean it with "mix deps.clean ex_keccak"
```

**Comment by vbaranov** [comment]
@KevinSmall Cargo is a requirement https://docs.blockscout.com/for-developers/information-and-settings/requirements. Please install it.

**Comment by KevinSmall** [comment]
Thanks Victor, I can now successfully get as far as step 10) on the [manual deployment page](https://docs.blockscout.com/for-developers/manual-deployment), but then hit this error:
```
$ mix do ecto.create, ecto.migrate
** (Protocol.UndefinedError) protocol Enumerable not implemented for nil of type Atom. This protocol is implemented for the following type(s): DBConnection.PrepareStream, DBConnection.Stream, Date.Range, Ecto.Adapters.SQL.Stream, File.Stream, Floki.HTMLTree, Flow, Function, GenEvent.Stream, HashDict, HashSet, IO.Stream, Indexer.BoundQueue, Jason.OrderedObject, List, Map, MapSet, Postgrex.Stream, Range, Stream, Timex.Interval
    (elixir 1.14.1) lib/enum.ex:1: Enumerable.impl_for!/1
    (elixir 1.14.1) lib/enum.ex:166: Enumerable.reduce/3
    (elixir 1.14.1) lib/enum.ex:4307: Enum.reverse/1
    (elixir 1.14.1) lib/keyword.ex:202: Keyword.new/2
    (explorer 4.1.8) lib/explorer/repo/config_helper.ex:47: Explorer.Repo.ConfigHelper.extract_parameters/1
    (explorer 4.1.8) lib/explorer/repo/config_helper.ex:25: Explorer.Repo.ConfigHelper.get_db_config/1
    (explorer 4.1.8) lib/explorer/repo.ex:20: Explorer.Repo.init/2
    (ecto 3.9.1) lib/ecto/repo/supervisor.ex:25: Ecto.Repo.Supervisor.runtime_config/4
```

**Comment by vbaranov** [comment]
@KevinSmall you should set the DATABASE_URL environment variable. It looks like it is not set or contains invalid data.

**Comment by KevinSmall** [comment]
Thanks Victor, I tried the below and `pg_isready` looks ok, but the same error appears:

<img width="947" alt="image" src="https://user-images.githubusercontent.com/5543867/200579721-29dcad4b-6e39-47b6-b9f0-0edec46a7626.png">

What could I try to diagnose further?

**Comment by KevinSmall** [comment]
Hi Victor,

I noticed there is a docker install coming, [mentioned here](https://docs.blockscout.com/about/roadmap#deployment-improvements), I would like to wait for that. If you have any docs on that, I'd be happy to test it out.

This manual install is pretty complex, so I'll wait for the docker option. Fine to close this ticket.

Thanks,
Kevin.

**Comment by vbaranov** [comment]
@KevinSmall we already provide docker-compose configuration https://github.com/blockscout/blockscout/tree/master/docker-compose.

**Comment by KevinSmall** [comment]
ok thanks
