### ISSUE TITLE
Contract Source Code Verification is always Loading

### ISSUE THREAD

**Issue by slendermaan** [blockscout/blockscout#6264]
Contract source code verification is always loading

### Environment
* [Contract](https://blockscout.com/etc/mordor/address/0x4783AEC357bf026A7276314b45CF57D54737ff37/coin-balances)

### Steps to reproduce
Use the following standard json format for [contract](https://blockscout.com/etc/mordor/address/0x4783AEC357bf026A7276314b45CF57D54737ff37/coin-balances) source code validation.
```json
{
    "language": "Solidity",
    "sources": {
        "test.sol": { "content": "pragma solidity 0.5.17;\nimport \"./LibraryForTest2.sol\";\ncontract test {\n    event Transfer(uint value);\n    function get () public returns(uint) {\n        emit Transfer(LibraryForTest2.get3());\n        return LibraryForTest2.get3();    \n    }\n}"},
        "LibraryForTest2.sol": {"content": "pragma solidity 0.5.17;\nlibrary LibraryForTest2 {\n    function get3() public pure returns(uint) {\n        return 4;\n    }\n}"}
    },
    "settings": {
      "libraries": {
        "test.sol:test": {
          "LibraryForTest2": "0xb4B50a170903c4f62dBBb2EDb02dA35F76ef18cA"
        }
      },
      "metadata": {
        "useLiteralContent": true
      },
      "optimizer": {
        "enabled": false
      },
      "remappings": []
    }
}
```

<img width="1033" alt="image" src="https://user-images.githubusercontent.com/21294029/196021194-e37549bc-9ffb-48c0-9295-df302c37550a.png">
<img width="1041" alt="image" src="https://user-images.githubusercontent.com/21294029/196021200-3a441b48-90fb-452e-9f67-cef2846198fa.png">

### Expected behaviour
Successful verification, just like etherscan

### Actual behaviour
Always loading
<img width="317" alt="image" src="https://user-images.githubusercontent.com/21294029/196021153-d7351491-bcb7-418e-93b9-5df081b7626c.png">

**Comment by vbaranov** [comment]
@slendermaan We separated smart-contracts verification to a standalone microservice written in Rust. Your issue should be resolved once the instance will be connected to that microservice. https://docs.blockscout.com/for-developers/information-and-settings/smart-contract-verification.
This is instruction on how 
- to run that microservice https://github.com/blockscout/blockscout-rs/tree/main/smart-contract-verifier-http#readme.
- to activate it in Blockscout https://docs.blockscout.com/for-developers/information-and-settings/smart-contract-verification#activation
But the Blockscout team doesn't host ETC Mordor instance of Blockscout, so I am tagging @diega, who, I suppose can help with that. I suppose this integration should be enabled on all ETC instances.

**Comment by diega** [comment]
@vbaranov, I installed the `smart-contract-verifier-http` service at our Mordor instance but it seems that's something is not working properly.
This is how I'm building and running the rust server
```shell
$ git clone https://github.com/blockscout/blockscout-rs.git
$ cd blockscout-rs
$ git checkout v0.5.0
$ docker build -f ./smart-contract-verifier-http/Dockerfile -t smart-contract-verifier-http:0.5.0 .
[...]
$ docker run --rm -p 8043:8043 smart-contract-verifier-http:0.5.0
2022-10-18T19:32:23.723312Z  INFO smart_contract_verifier_http::run: Smart-contract verifier is starting at 0.0.0.0:8043
2022-10-18T19:32:23.760876Z  INFO smart_contract_verifier::compiler::versions_fetcher: spawn version refresh job
2022-10-18T19:32:23.761127Z  WARN smart_contract_verifier::compiler::compilers: cannot load local compilers from `/tmp/solidity-compilers` dir: No such file or directory (os error 2)
2022-10-18T19:32:23.785108Z  INFO smart_contract_verifier::compiler::versions_fetcher: spawn version refresh job
2022-10-18T19:32:23.785510Z  WARN smart_contract_verifier::compiler::compilers: cannot load local compilers from `/tmp/vyper-compilers` dir: No such file or directory (os error 2)
2022-10-18T19:32:23.801991Z  INFO actix_server::builder: Starting 1 workers
2022-10-18T19:32:23.802276Z  INFO actix_server::server: Tokio runtime found; starting in existing Tokio runtime
```
I added `ENABLE_RUST_VERIFICATION_SERVICE=true` and `RUST_VERIFICATION_SERVICE_URL=http://localhost:8043/` and when I try to verify a contract this is what I could spot in the logs of the blockscout instance
```
2022-10-18T19:27:14.374 application=plug request_id=Fx9Ab2eiYmg-olAAACky [info] POST /verify_smart_contract/contract_verifications
warning: Supervisor.start_child/2 with a list of args is deprecated, please use DynamicSupervisor instead
  (elixir 1.12.2) lib/supervisor.ex:826: Supervisor.start_child/2
  (que 0.10.1) lib/que/server_supervisor.ex:48: Que.ServerSupervisor.add/2
  (block_scout_web 0.0.1) lib/block_scout_web/controllers/address_contract_verification_controller.ex:72: BlockScoutWeb.AddressContractVerificationController.create/2
  (block_scout_web 0.0.1) lib/block_scout_web/controllers/address_contract_verification_controller.ex:1: BlockScoutWeb.AddressContractVerificationController.action/2
  (block_scout_web 0.0.1) lib/block_scout_web/controllers/address_contract_verification_controller.ex:1: BlockScoutWeb.AddressContractVerificationController.phoenix_controller_pipeline/2
  (phoenix 1.5.13) lib/phoenix/router.ex:352: Phoenix.Router.__call__/2

2022-10-18T19:27:14.408 application=que [info] [Que] Spawning Server for worker: Explorer.SmartContract.Solidity.PublisherWorker
2022-10-18T19:27:14.411 application=que [info] [Que] Queued new Job for Explorer.SmartContract.Solidity.PublisherWorker
2022-10-18T19:27:14.412 application=que [info] [Que] Starting Job # 1 with Explorer.SmartContract.Solidity.PublisherWorker
2022-10-18T19:27:14.414 application=plug request_id=Fx9Ab2eiYmg-olAAACky [info] Sent 204 in 39ms

[...]

2022-10-18T19:28:24.862 [error] Task #PID<0.18634.0> started from #PID<0.18632.0> terminating
** (MatchError) no match of right hand side value: %{"enabled" => false}
    (explorer 0.0.1) lib/explorer/smart_contract/solidity/verifier.ex:121: Explorer.SmartContract.Solidity.Verifier.extract_settings_from_json/1
    (explorer 0.0.1) lib/explorer/smart_contract/solidity/verifier.ex:98: anonymous fn/6 in Explorer.SmartContract.Solidity.Verifier.verify/3
    (elixir 1.12.2) lib/enum.ex:4280: Enumerable.List.reduce/3
    (elixir 1.12.2) lib/enum.ex:2431: Enum.reduce_while/3
    (explorer 0.0.1) lib/explorer/smart_contract/solidity/publisher.ex:49: Explorer.SmartContract.Solidity.Publisher.publish_with_standart_json_input/2
    (explorer 0.0.1) lib/explorer/smart_contract/solidity/publisher_worker.ex:39: Explorer.SmartContract.Solidity.PublisherWorker.perform/1
    (elixir 1.12.2) lib/task/supervised.ex:90: Task.Supervised.invoke_mfa/2
    (stdlib 3.15.1) proc_lib.erl:226: :proc_lib.init_p_do_apply/3
Function: #Function<3.131974459/0 in Que.Job.perform/1>
    Args: []
2022-10-18T19:28:24.873 application=que [info] [Que] Failed Job # 1 with Explorer.SmartContract.Solidity.PublisherWorker
```

Any hint on what can I do to make this two components to communicate properly? Just in case, we're on `production-etc-mordor-stg`, does this commit include the _rust server_ feature?

**Comment by vbaranov** [comment]
@diega

> Just in case, we're on production-etc-mordor-stg, does this commit include the rust server feature?

Yes, this is the issue - the branch is pretty old. I am preparing an update for that branch. In order to give you proper instructions on the launch of a new version of the application, please, let me know, how you run the explorer: through Make file, docker, docker-compose or from source?

**Comment by diega** [comment]
Through Makefile. This is our line
```
ETHEREUM_JSONRPC_VARIANT='geth'
ETHEREUM_JSONRPC_WS_URL='ws://127.0.0.1:8546'
ETHEREUM_JSONRPC_HTTP_URL='http://127.0.0.1:8545'
ETHEREUM_JSONRPC_TRACE_URL='http://127.0.0.1:8545'
MIX_ENV='prod'
DATABASE_URL='[redacted]'
SOCKET_ROOT='/etc/mordor'
PORT='4000'
SUPPORTED_CHAINS='[ { "title": "Ethereum Classic", "url": "https://blockscout.com/etc/mainnet"}, { "title": "ETC Kotti", "url": "https://blockscout.com/etc/kotti", "test_net?": true }, { "title": "POA Core", "url": "https://blockscout.com/poa/core" }, { "title": "POA Sokol", "url": "https://blockscout.com/poa/sokol", "test_net?": true }, { "title": "xDai Chain", "url": "https://blockscout.com/poa/dai" }, { "title": "Kovan Testnet", "url": "https://blockscout.com/eth/kovan", "test_net?": true }, { "title": "RSK Mainnet", "url": "https://blockscout.com/rsk/mainnet", "other?": true }, { "title": "LUKSO L14 testnet", "url": "https://blockscout.com/lukso/l14", "test_net?": true }, { "title": "Ethereum Mainnet", "url": "https://blockscout.com/eth/mainnet" }]'
TXS_COUNT_CACHE_PERIOD='7200'
BLOCKSCOUT_HOST='blockscout.com'
NETWORK_PATH='/etc/mordor'
API_PATH='/etc/mordor'
SUBNETWORK='Mordor'
CHAIN_ID='63'
BLOCK_COUNT_CACHE_PERIOD='7200'
LINK_TO_OTHER_EXPLORERS='true'
LOGO='/images/classic_ethereum_logo.svg'
LOGO_FOOTER='/images/classic_ethereum_logo.svg'
NETWORK_ICON='_test_network_icon.html'
COIN='ETC'
NETWORK='ETC'
POOL_SIZE='100'
POOL_SIZE_API='50'
CHAIN_SPEC_PATH='https://raw.githubusercontent.com/etclabscore/core-geth/master/params/parity.json.d/mordor.json'
BLOCKSCOUT_VERSION='v4.1.1-beta'
PORT=80
SECRET_KEY_BASE='[redacted]'
ENABLE_RUST_VERIFICATION_SERVICE=true
RUST_VERIFICATION_SERVICE_URL=http://localhost:8043/
make start
```

**Comment by vbaranov** [comment]
@diega here is the prepared branch https://github.com/blockscout/blockscout/tree/production-etc-mordor-stg

In order to support this version of Blockscout there are changes in environment variables:

- New environment variables, which you should set:
```
COIN_NAME='ETC'
INDEXER_CATCHUP_BLOCKS_BATCH_SIZE='3'
INDEXER_CATCHUP_BLOCKS_CONCURRENCY='3'
JSON_RPC='https://www.ethercluster.com/mordor'
DISABLE_EXCHANGE_RATES='true'  # it doesn't make sense to fetch exchange rates for testnet
FOOTER_CHAT_LINK='https://discord.com/invite/hQs894U' # link to ETC Discord. If you have another link, please replace it.
ENABLE_TXS_STATS='true' # enabling collecting tx stats data on the main page
TXS_STATS_DAYS_TO_COMPILE_AT_INIT='30' # how many days to collect tx stats data for initially
SHOW_TESTNET_LABEL='true' # testnet label right after the logo in the header
RE_CAPTCHA_SECRET_KEY=... # Configure RECAPTCHA in order to give your users the ability to use CSV export functionality
RE_CAPTCHA_CLIENT_KEY=... # the same as above
```

- Change values of some environment variables:
```
SUPPORTED_CHAINS='[ { "title": "Ethereum Classic", "url": "https://blockscout.com/etc/mainnet"}, { "title": "ETC Kotti", "url": "https://blockscout.com/etc/kotti", "test_net?": true }, { "title": "ETC Mordor", "url": "https://blockscout.com/etc/mordor", "test_net?": true }, { "title": "POA", "url": "https://blockscout.com/poa/core" }, { "title": "Sokol", "url": "https://blockscout.com/poa/sokol", "test_net?": true }, { "title": "Gnosis Chain", "url": "https://blockscout.com/xdai/mainnet" }, { "title": "RSK", "url": "https://blockscout.com/rsk/mainnet" }, { "title": "LUKSO L14", "url": "https://blockscout.com/lukso/l14", "other?": true }, {"title": "ARTIS Σ", "url": "https://blockscout.com/artis/sigma1", "other?": true}, {"title": "Ethereum", "url": "https://blockscout.com/eth/mainnet/"}, {"title": "Optimism on Gnosis Chain", "url": "https://blockscout.com/xdai/optimism"} ]'
BLOCKSCOUT_VERSION='v4.1.8-beta'
```

- Change names of some environment variables:
```
TXS_COUNT_CACHE_PERIOD -> CACHE_TXS_COUNT_PERIOD
BLOCK_COUNT_CACHE_PERIOD -> CACHE_BLOCK_COUNT_PERIOD
```

_**Note 1**_: Please be aware, there are DB migrations from 4.1.1 to 4.1.8. Thus, please expect minutes to hours of downtime depending on how much data you have in the chain.

_**Note 2**_: Please be aware, that with the new Rust microservice of smart-contracts verification, only release versions of compilers will be available from the box (no nightly versions). You should fetch nightly versions by yourself or request usage of our smart-contract verifier instance - we provide it as SaaS.


When you be ready for other instances (Kotti and Mainnet), please let me know. I will also update the relevant branches.

**Comment by diega** [comment]
@vbaranov I'm updating Mordor's instance and I'm facing this error on DB migration
```
==> Running migrations
prod
Starting dependencies..
Starting repos..
Create Explorer.Repo database if it doesn't exist
** (KeyError) key :database not found in: [telemetry_prefix: [:explorer, :repo], otp_app: :explorer, migration_timestamps: [type: :utc_datetime_usec], prepare: :unnamed, timeout: 60000, pool_size: 100, ssl: true]
    (elixir 1.13.1) lib/keyword.ex:559: Keyword.fetch!/2
    (ecto_sql 3.9.0) lib/ecto/adapters/postgres.ex:174: Ecto.Adapters.Postgres.storage_up/1
    lib/release_tasks.ex:70: Explorer.ReleaseTasks.create_db_for/1
    (elixir 1.13.1) lib/enum.ex:937: Enum."-each/2-lists^foreach/1-0-"/2
    lib/release_tasks.ex:22: Explorer.ReleaseTasks.create_and_migrate/0
    (stdlib 3.17) erl_eval.erl:685: :erl_eval.do_apply/6
make[1]: *** [Makefile:617: migrate_only] Error 1
```
I just checked and the DB connection is working fine from the instances

**Comment by vbaranov** [comment]
Hi @diega, I updated production-etc-mordor-stg branch. It was a bug inside it. Please, try again and let me know how it goes.

**Comment by diega** [comment]
Awesome. I have it running again now.
I tried testing the verification but I'm not getting a request on the server. I quickly looked at the network interactions from the _verification_ form and it's trying to **POST** to `https://blockscout.com/verify_smart_contract/contract_verifications` ommiting the `/etc/mordor/` path. May this be the issue?

**Comment by vbaranov** [comment]
@diega could you please pull an update from that branch and re-build?

**Comment by vbaranov** [comment]
Glad to hear.

For Kotti please use the same `production-etc-mordor-stg` branch and the same instruction for changing env vars.
For Mainnet, please use `production-classic-stg` and the same instruction for changing env vars except:
- you don't need to set DISABLE_EXCHANGE_RATES='true'
- you don't need to set SHOW_TESTNET_LABEL='true'
- you have to set SHOW_PRICE_CHART='true'

**Comment by diega** [comment]
@vbaranov I just tried to deploy Kotti using `production-etc-mordor-stg` but I think there may be problem, b/c I can see that in the https://blockscout.com/etc/kotti there are calls to `wss://blockscout.com/etc/mordor/socket/websocket`
I'm sorry for hijack the issue with this, let me know if you want me to open a new one

**Comment by vbaranov** [comment]
@diega ok, I will prepare the branch for Kotti.

**Comment by vbaranov** [comment]
@diega production-etc-kotti-stg branch updated

**Comment by diega** [comment]
@vbaranov I've updated every instance and everything is working fine. I think you can close this issue now. Thanks!

**Comment by vbaranov** [comment]
Glad to hear that! Thanks for the feedback.
