### ISSUE TITLE
Ethereum Classic: cannot send ethereum classic

### ISSUE THREAD

**Issue by kambegule** [blockscout/blockscout#6265]
i cannot sent ethereum classic, it dropped and dropped please help 3 hour already

here is transaction hash :
https://blockscout.com/etc/mainnet/tx/0xf3dc8564f772924f1d13ab36668f7d7dfde63e2e22b547fabc5e45045f56d16e

and

https://blockscout.com/etc/mainnet/tx/0x1dc940b273b8164ec0cd9edb834741d9563ef2ed1377184804562ed4ea410715

**Comment by vbaranov** [comment]
You should ask in Ethereum Classic Discord https://discord.com/invite/bMGuZsA
