### ISSUE TITLE
Always 1 block behind

### ISSUE THREAD

**Issue by tonik-ru** [blockscout/blockscout#6266]
after update to commit c965606 explorer is always 1 block behind blockchain

### Environment

* Deployment type (Manual/Docker/Docker-compose): manual
* Elixir & Erlang/OTP versions (`elixir -version`): 1.13.0/24
* Node JS version (`node -v`): 16.16
* Operating System: ubuntu
* Blockscout Version/branch/commit: c965606 
* Archive node type && version (Erigon/Geth/Nethermind/Ganache/?): geth

### Steps to reproduce
send any transaction

### Expected behaviour
show all mined blocks. including latest

### Actual behaviour
missing latest block

**Comment by tonik-ru** [comment]
fetcher.ex
line 392: {:ok, [last_block()..(latest_block_number - 1)]}
why do you do " - 1"?
you do not want to sync latest block? why?
if i remove "-1" sync works as expected. explorer is always synced (but with delays up to 25 seconds).
btw, older releases synced new block as soon as they are minted

**Comment by nikitosing** [comment]
@tonik-ru Hello, please try to change config a little bit:
on this line replace `true` with `false` https://github.com/blockscout/blockscout/blob/master/apps/explorer/config/config.exs#L14
and recompile/restart. Hope it will help

**Comment by bretep** [comment]
Before I make this change, because we, too, are experiencing the behind-by-one block issue, why would turning off the average block time counter fix this issue? (This was line 14 of the code you reference, but has since changed.)

```
config :explorer, Explorer.Chain.Cache.AddressSum,
  enabled: true,
  ttl_check_interval: :timer.seconds(1)
```

**Comment by bretep** [comment]
Are you thinking that this is causing a delay?
https://github.com/blockscout/blockscout/blob/cfc1fa46fed8e02803dd301322dfc7832b75d7e3/apps/block_scout_web/lib/block_scout_web/notifier.ex#L321

**Comment by bretep** [comment]
I have disabled, compiled, and deployed this code. I can confirm that it did not resolve the issue but did cause notifications not to work anymore. I rolled back this change. Now blocks continue to be behind-by-one block.

<img width="473" alt="image" src="https://user-images.githubusercontent.com/787344/215632781-ba4978a6-0ed8-4da0-93a0-76cea8d20fa8.png">

**Comment by bretep** [comment]
Technically, we do not see an exactly behind-by-one block. We have a 10-second block average, and new blocks show up after 8 seconds, not 10 seconds. 

I don't think this is a `latest_block - 1` issue. It may be a performance or timer issue. 

My strong guess is a timer issue.

As for database performance, I'm confident that is not an issue. We're utilizing 0.1% CPU on our Postgres instances, 64Gb ram, 12 core, 10Gig connection, and NVMe disk.

Our instance running the indexer also basically has zero load:
<img width="634" alt="image" src="https://user-images.githubusercontent.com/787344/215686661-10a320bf-fbac-40e3-b90c-9a5f440d3caa.png">

**Comment by tonik-ru** [comment]
> Technically, we do not see an exactly behind-by-one block. We have a 10-second block average, and new blocks show up after 8 seconds, not 10 seconds.

you are not affected behind-by-one block issue, because your chain produces blocks constantly.
but my chain with CLIQUE produces blocks upon request only. so next block may be produced in a few minutes for ex. and all this period explorer will be 1 block behind. so this is definitely an issue.

and what about second issue? even if i remove "-1", blocks appear in explorer with delay (~20 seconds). with previous releases this was instant (within 1 second)

**Comment by bretep** [comment]
My chain also produces blocks when told to by either lighthouse or prysm. ;)

**Comment by nikitosing** [comment]
@bretep The reason why I suggested to disable AverageBlockTime counter is the following. Realtime indexer requests new blocks once at `average_block_time/2`. If this counter is disabled indexer will check new blocks each 2 seconds

**Comment by bretep** [comment]
You can read above, I disabled it, and it broke notifications. If I refreshed the page, I could see that the indexer indexed new blocks. However, the notification of new blocks did not propagate to the user interface.

I rolled back the change, and immediately blocks began coming in again.

There is clearly a problem with this code.

**Comment by nikitosing** [comment]
> Is this it?

Yes

**Comment by bretep** [comment]
Better yet, if specified a websocket address (like I have), why not just react to new blocks?

**Comment by nikitosing** [comment]
websocket should work in a way you described

**Comment by tonik-ru** [comment]
> @tonik-ru Please link to commit: c1efd674 and 43dd377f
looks like this is it. 

https://github.com/blockscout/blockscout/commits/8885075f0a1937f6559bbe2a694f9b73c1efd674
https://github.com/blockscout/blockscout/commits/1b815df72b31b43f258c0df7a848b67943dd377f

**Comment by bretep** [comment]
Thanks for providing those, this will be helpful to me.

For future reports on anything GitHub/git related, if you use the beginning vs. the end of the hash, you can paste it into GitHub, which will bring up the commit. You cannot do that with the end of the hash. ;)

Alright, I think that this is related: https://github.com/blockscout/blockscout/issues/6750#issuecomment-1410907481

On my node that is working (a build from a year ago), WebSockets is being used, and it's not falling back to HTTP RPC.

Using the latest build of blockscout, the HTTP RPC is behaving how it's supposed to. However, after blockscout connects to the WebSockets endpoint, it is not used for subscriptions. It just sends health checks. The current build of blockscout falls back to the HTTP RPC.

@tonik-ru I'm curious if you are also trying to use WebSockets.

**Comment by bretep** [comment]
Taking a quick glance at the diff, there are changes to the RPC. I'll spend some more time going through all the changes.

https://github.com/blockscout/blockscout/compare/1b815df72..888507
