### ISSUE TITLE
Too many attempts to 

### ISSUE THREAD

**Issue by tonik-ru** [blockscout/blockscout#6268]
2022-10-16T19:33:04.195 application=explorer [error] Failed to get owner of token 0xa2cd8ea362b5c2e52d30f2e6be359acd29b50166, token_id 83, reason: (-32000) execution reverted

this token has 100+ different  instances, with thousands in a near future.
and on each restart blockscout is trying to get owner for each instance. and failing, because 1155 doesnt implement getOwner method.
also no need to validate each instance if contract doesnt implement the method. and no need to call this on each restart.

### Environment
Deployment type (Manual/Docker/Docker-compose): manual
Elixir & Erlang/OTP versions (elixir -version): 1.13.0 / 24
Node JS version (node -v): 16.16.0
Operating System: ubuntu
Blockscout Version/branch/commit: https://github.com/blockscout/blockscout/commit/c965606294e9e8b6da995172d626618994bf85e7
Archive node type && version (Erigon/Geth/Nethermind/Ganache/?): geth

**Comment by vbaranov** [comment]
This should be resolved with https://github.com/blockscout/blockscout/pull/6492. This has been merged to master branch.
