### ISSUE TITLE
missing erc1155 instance page

### ISSUE THREAD

**Issue by tonik-ru** [blockscout/blockscout#6269]
erc1155 token instance page is not found
token/0xa2cd8ea362b5c2e52d30f2e6be359acd29b50166/instance/115/token-transfers
gives 404, it was working fine before update

### Environment

* Deployment type (Manual/Docker/Docker-compose): manual
* Elixir & Erlang/OTP versions (`elixir -version`): 1.13.0 / 24
* Node JS version (`node -v`): 16.16.0
* Operating System: ubuntu
* Blockscout Version/branch/commit: c965606
* Archive node type && version (Erigon/Geth/Nethermind/Ganache/?): geth

### Steps to reproduce

open any erc1155 token details page

### Expected behaviour
![image](https://user-images.githubusercontent.com/7190128/196055570-78bdfc7e-2185-4784-975d-741bac5ce94f.png)

### Actual behaviour
![image](https://user-images.githubusercontent.com/7190128/196055615-a834df04-983d-4092-b31b-588e3ea9ec85.png)

**Comment by vbaranov** [comment]
@tonik-ru this should be resolved with [5.0.0](https://github.com/blockscout/blockscout/releases/tag/v5.0.0-beta). Please le tus know, if the issue still persists. I am closing it for now.
