### ISSUE TITLE
custom network's coin name

### ISSUE THREAD

**Issue by donghquinn** [blockscout/blockscout#6271]
*Describe your issue here.*

### Environment

Deployment type (Manual/Docker/Docker-compose): Docker-Compose
Elixir & Erlang/OTP versions (elixir -version): ELIXIR: 1.13.4-opt-24, ERLANG 24.3.3
Node JS version (node -v): 16.13.0
Operating System: Ubuntu 20.04-lts
Blockscout Version/branch/commit: 4.1.7-beta
Archive node type && version (Erigon/Geth/Nethermind/Ganache/?): Geth

I'm running private Ethereum Network and have deployed Blockscout for monitoring.
Then I found something weird situation: The coin name(coin symbol) wasn't changed into my custom coin symbol.
So I checked countlessly whether I mis-typed COIN_NAME on env file or didn't applied it. But Nothing was my situation.

So I checked and tested all the source codes.
Finally I concluded 78 line of "wei_helpers.ex" file on path blockscout/apps/block_scout_web/lib/block_scout_web/views is statically defined "Ether". So I changed and All the Coin Symbol has been changed on the browser.

So Why don't you make it possible with env var? Some User might want to apply the coin_name by just adding their own coin symbol on env file.

Thank you

<img width="774" alt="Screen Shot 2022-10-17 at 4 54 23 PM" src="https://user-images.githubusercontent.com/98877622/196120976-633b7897-3f7f-4626-869e-a4f4c6aeba86.png">

**Comment by vbaranov** [comment]
@donghquinn please use `latest` tag for the Docker image. `COIN_NAME` variable doesn't work as it should in 4.1.7.

**Comment by vbaranov** [comment]
Release [5.0.0](https://github.com/blockscout/blockscout/releases/tag/v5.0.0-beta) has been published. `COIN_NAME` variable is supported there.
