### ISSUE TITLE
Kava: Unable to verify contract

### ISSUE THREAD

**Issue by grGred** [blockscout/blockscout#6275]
Unable to verify contracts in KAVA.

### Environment
* Elixir Version: 1.12.3
* Erlang Version: 24
* BlockScout Version: 

* User Agent: `Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/106.0.0.0 Safari/537.36`

### Steps to reproduce

I'm unable to verify smart-contract in Kava network. Sourcify doesn't support Kava, input json send me that this json is incorrect. While using flattened code it says that the compiler version is incorrect. I have redeployed this contract several times on different Solidity versions but it is still unable to verify. While verifying using this guide https://docs.kava.io/docs/ethereum/contract_verification I receive an error:
NomicLabsHardhatPluginError: The contract verification failed.
Reason: Fail - Unable to verify
Or:
NomicLabsHardhatPluginError: The API responded with an unexpected message.
Contract verification may have succeeded and should be checked manually.
Message: Unknown UID

### Address

https://explorer.kava.io/address/0x0C8f0d522094689E9eFeB2576AB60d54B85209dF/transactions

**Comment by vbaranov** [comment]
@grGred which compiler version did you use during verification?

**Comment by grGred** [comment]
I've already tried with 0.8.16, 0.8.15 and 0.8.14. I can share you flatten source code for that if needed.

**Comment by vbaranov** [comment]
@grGred the contract, you mentioned, compiled with 0.8.10. Please try to verify with this compiler version.

**Comment by rimrakhimov** [comment]
@grGred Could you also share the standard json input and flatten source code which you use for verification

**Comment by grGred** [comment]
My hardhat config is: https://gist.github.com/grGred/2a3e10b0e088135b55964193d3d1304e
I deleted all the cache, artifacts, typechain and ran the deploy script:

```
% npx hardhat run scripts/deploy.ts --network kava

Generating typings for: 23 artifacts in dir: typechain for target: ethers-v5
Successfully generated 39 typings!
Compiled 24 Solidity files successfully
Multichain Proxy deployed to: 0x8F5139c2D73c994358D849280faDde12c1fFdDaB
Nothing to compile
No need to generate any newer typings.
Successfully submitted source code for contract
contracts/MultichainProxy.sol:MultichainProxy at 0x8F5139c2D73c994358D849280faDde12c1fFdDaB
for verification on the block explorer. Waiting for verification result...

We tried verifying your contract MultichainProxy without including any unrelated one, but it failed.
Trying again with the full solc input used to compile and deploy it.
This means that unrelated contracts may be displayed on Etherscan...

Successfully submitted source code for contract
contracts/MultichainProxy.sol:MultichainProxy at 0x8F5139c2D73c994358D849280faDde12c1fFdDaB
for verification on the block explorer. Waiting for verification result...

NomicLabsHardhatPluginError: The contract verification failed.
Reason: Fail - Unable to verify
    at SimpleTaskDefinition.verifySubtask [as action] (/Users/vlad/Desktop/Solidity/14_multichain_impl/node_modules/@nomiclabs/hardhat-etherscan/src/index.ts:350:9)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Environment._runTaskDefinition (/Users/vlad/Desktop/Solidity/14_multichain_impl/node_modules/hardhat/src/internal/core/runtime-environment.ts:308:14)
    at async Environment.run (/Users/vlad/Desktop/Solidity/14_multichain_impl/node_modules/hardhat/src/internal/core/runtime-environment.ts:156:14)
    at async main (/Users/vlad/Desktop/Solidity/14_multichain_impl/scripts/deploy.ts:22:5)
```
Etherscan version: "@nomiclabs/hardhat-etherscan": "^3.1.1".
I think right now no one can verify their contract address, even USDC coin is unverified! 

Flatten contract: https://gist.github.com/grGred/4131734331a2b0204f81b128c5d381bf

I haven't changed anything at all, just fresh test of deployment.

Contract deployed:
https://explorer.kava.io/address/0x8F5139c2D73c994358D849280faDde12c1fFdDaB/transactions

**Comment by grGred** [comment]
Should I give you more info about this? Or what is the current status of this issue?

**Comment by grGred** [comment]
Any updates?

**Comment by grGred** [comment]
@rimrakhimov I don't host Kava instance of Blockscout. You can connect Kava tech support in Kava network discord channel.

**Comment by vbaranov** [comment]
@grGred we do not have official channels with Kava team as far as I know. Please, advise integrating with the Rust smart-contracts microservice the Kava instance team in all known to you channels. The integration guide is here https://docs.blockscout.com/for-developers/information-and-settings/smart-contract-verification.

**Comment by grGred** [comment]
I have contacted developers from Kava network, and sent this issue.
