### ISSUE TITLE
logo and colors

### ISSUE THREAD

**Issue by bi4yi** [blockscout/blockscout#6277]
hello dev,

how can i change main and footer logo , also theme colors for the new network

Cdly

**Comment by vbaranov** [comment]
You can set `LOGO` and `LOGO_FOOTER` environment variables to change the logo. Color customizations are currently can be changed only with new CSS themes. https://docs.blockscout.com/for-developers/configuration-options/css-configuration-and-presets here is the instruction on how to change CSS preset.

**Comment by bi4yi** [comment]
thanks a lot bro ,

SOLVED
