### ISSUE TITLE
Transaction Actions

### ISSUE THREAD

**Issue by ulyanas** [blockscout/blockscout#6289]
Full description: https://www.notion.so/blockscout/Transaction-Action-V1-85cdd9ef57e04b25a4e2c6af9a98dbfe

**Comment by ulyanas** [comment]
@tgladilina  Please add tx actions mockups

**Comment by ulyanas** [comment]
need to add tasks

**Comment by varasev** [comment]
> need to add tasks

Current subtasks (as of 2022-11-22):
- finish displaying tx actions for Uniswap V3 in the new UI (for Mainnet, Optimism, and Polygon)
- make a background process of actions indexing for old transactions (indexed before tx actions module is installed in production)
- implement displaying tx actions of other prioritized protocols/events (opensea, zkbob, wrapping/unwrapping native coins, ERC20 token approval/revoking) for Mainnet, Optimism, Polygon, and Gnosis

**Comment by tgladilina** [comment]
**mockup** 
https://www.figma.com/file/4In0X8UADoZaTfZ34HaZ3K/Blockscout_v1_Chakra?node-id=4876%3A60256&t=3jH0aR6Y8G04Icex-4

<img width="1105" alt="Screenshot 2022-11-23 at 11 46 29" src="https://user-images.githubusercontent.com/103045386/203504191-410b7fd5-8ef7-44c1-896c-ddabe2235489.png">

**etherscan samples** 
<img width="963" alt="Screenshot 2022-11-23 at 11 12 45" src="https://user-images.githubusercontent.com/103045386/203504261-b294a468-1229-4b83-8d82-eda6e78e8555.png">
<img width="268" alt="Screenshot 2022-11-23 at 11 11 28" src="https://user-images.githubusercontent.com/103045386/203504267-050fb324-2f8d-4f75-a4f9-140d02b0b14e.png">
<img width="824" alt="Screenshot 2022-11-23 at 11 11 17" src="https://user-images.githubusercontent.com/103045386/203504270-8e835f05-0f12-4cfa-bc8d-3d9cc38761d1.png">

**Comment by vbaranov** [comment]
Basic functionality of Transaction Actions implemented for some popular DeFi protocols. Others will be added on-demand in separate issues.
