### ISSUE TITLE
Migrate to AlloyDB

### ISSUE THREAD

**Issue by ulyanas** [blockscout/blockscout#6291]
Current situation: 
- job is crashing due to db constraints posed after indexing is done, need to ignore them (AlloyDB will do it)

**Comment by ulyanas** [comment]
-  Add comparison benchmarks (Notion doc)

**Comment by ulyanas** [comment]
https://resisted-spectacles-c10.notion.site/Research-Google-Cloud-AlloyDB-448cb74c44ea43699ab99e87cd3a0360

**Comment by ulyanas** [comment]
https://blockscout.com/eth/alloy/

**Comment by vbaranov** [comment]
Migration to AlloyDB for ETH Mainnet instance has been finished

https://blockscout.com/eth/alloy -> https://blockscout.com/eth/mainnet (now running on AlloyDB)
Final report about queries execution speed comparison between RDS and AlloyDB:
https://resisted-spectacles-c10.notion.site/Research-Google-Cloud-AlloyDB-448cb74c44ea43699ab99e87cd3a0360
