### ISSUE TITLE
Token balances issues

### ISSUE THREAD

**Issue by ulyanas** [blockscout/blockscout#6294]
1. Huge delay in updating balances after a token transfer has occurred.
2. Inconsistent holder information (caused by 1).

**Comment by 0xtzData** [comment]
Does not reproduce itself in test setup, we need to wait for prod data migration and then verify again.

**Comment by 0xtzData** [comment]
Reproduced on local `latest` setup with new UI
- Token holder information update delay is not predictable, some generated tokens haven't updated its description fields of `holdes` and `transfers` for 30mins, data in `holders` and `transfers` is consistent.
- Coin balances for all holders are empty after 30mins
- Transfers field in description of a token holder wasn't updated after 30mins
- In `Address details -> Tokens` quantity of tokens holder owns is 0 after 30 mins, test script verifies that balances are not zero
- In `Token transfers` tab of that particular token transfer value is 0, should it be the token value?

**Comment by 0xtzData** [comment]
After configuring local env properly all fixed, except Address Transfers field delay - needs refresh - known feature.

**Comment by vbaranov** [comment]
The epic for token balances updates and progress of resolving is in https://github.com/blockscout/blockscout/issues/8157
