### ISSUE TITLE
Help install ssl 

### ISSUE THREAD

**Issue by Ranofty** [blockscout/blockscout#6302]
### Environment

* Deployment type (Manual/ aws ubuntu 20.04):
* Elixir & Erlang/OTP versions (`1.13.4`):
* Node JS version (`16`):
* Operating System:
* Blockscout Version/branch/commit: 4.1.8
* Archive node type && version (Nethermind):

Hello please i need help on how to install ssl to my blockscout any guide can help

**Comment by Ranofty** [comment]
Hello any response on this please? 🙏

**Comment by NicoDFS** [comment]
I used nginx and lets encrypt. 

after you install nginx go to  `/etc/nginx/sites-available` and edit the `default` file
remove everything and replace with:

```
server {
  server_name yourdomain.com;

   location / {
    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "upgrade";
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header Host $http_host;
    proxy_set_header X-NginX-Proxy true;
    proxy_pass http://localhost:4000/;
  }
}
```

then install certbot 
`sudo apt install certbot python3-certbot-nginx`
and get the ssl
`sudo certbot --nginx -d example.com -d www.example.com`

When it asks: 
`Please choose whether or not to redirect HTTP traffic to HTTPS, removing HTTP access.`
Select `2`

**Comment by Ranofty** [comment]
Thank alot sir already done that
