### ISSUE TITLE
Palm: withdrawal issues

### ISSUE THREAD

**Issue by ezetulugo** [blockscout/blockscout#6304]
I withdrew 8 dai to my metamask wallet since the past 1 month uptil now i haven,t received it.

### Environment
* Elixir Version: 1.13.1
* Erlang Version: 24
* BlockScout Version: 

* User Agent: `Mozilla/5.0 (Linux; Android 9; SM-J730F) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/105.0.0.0 Mobile Safari/537.36`

### Steps to reproduce

*Tell us how to reproduce this issue. If possible, push up a branch to your fork with a regression test we can run to reproduce locally.*

### Expected Behaviour

*Tell us what should happen.*

### Actual Behaviour

*Tell us what happens instead.*

**Comment by vbaranov** [comment]
The Palm chain is unsupported here.
