### ISSUE TITLE
Issue in running Blockscout

### ISSUE THREAD

**Issue by navdeepgarg1** [blockscout/blockscout#6306]
I setup the blockscout using this documentation on c5.2xlarge and even tried with big instances as well -

https://wiki.polygon.technology/docs/edge/additional-features/blockscout/

It runs proper for around 5-10 mins and then it stated crashes and web didn't get loaded then. Tried many different approaches Setup the web and Rpc on the same instance and on the different instance as well but issue still remains the same. Their is no log to be found and the CPU utilization is also only about 10%.

**Comment by vbaranov** [comment]
@navdeepgarg1 please provide all logs from your Blockscout instance

**Comment by Ranofty** [comment]
> I setup the blockscout using this documentation on c5.2xlarge and even tried with big instances as well -
> 
> https://wiki.polygon.technology/docs/edge/additional-features/blockscout/
> 
> It runs proper for around 5-10 mins and then it stated crashes and web didn't get loaded then. Tried many different approaches Setup the web and Rpc on the same instance and on the different instance as well but issue still remains the same. Their is no log to be found and the CPU utilization is also only about 10%.

I think you should use t3.large it will work that’s what I use also mine is running perfectly only having issue on setting up ssl certificate 😅💔

**Comment by navdeepgarg1** [comment]
Block Scout web url: http://18.188.170.251:4000
RPC URL: http://3.145.82.137:8545

Please find the blockscout logs and resource utilization:

In error.log file:
`Oct 26 07:20:52 ip-10-0-0-95 mix[2211]: 0x0000000000000000000000000000000000000000@򆼱: (-32000) header not found
Oct 26 07:20:52 ip-10-0-0-95 mix[2211]: 0x0000000000000000000000000000000000000000@򃧃: (-32000) hea (truncated)
Oct 26 07:20:52 ip-10-0-0-95 mix[2211]: 2022-10-26T07:20:52.915 [warning] Ranch acceptor reducing accept rate: out of file descriptors
`
`2022-10-26T06:51:03.820 application=indexer fetcher=block_catchup [error] Catchup index stream exited with reason (:normal). Restarting
2022-10-26T06:51:03.820 application=indexer fetcher=block_catchup [error] Catchup index stream exited because the archive node endpoint at http://3.145.82.137:8545/ is unavailable. Restarting
2022-10-26T06:51:03.820 application=indexer fetcher=block_catchup [error] Catchup index stream exited with reason (:normal). Restarting
2022-10-26T06:51:03.820 application=indexer fetcher=block_catchup [error] Catchup index stream exited because the archive node endpoint at http://3.145.82.137:8545/ is unavailable. Restarting`

`2022-10-26T06:51:03.821 application=indexer fetcher=code error_count=7 [error] failed to fetch contract codes: :econnrefused
2022-10-26T06:51:03.821 application=indexer fetcher=code error_count=10 [error] failed to fetch contract codes: :econnrefused
2022-10-26T06:51:03.821 application=indexer fetcher=coin_balance count=500 error_count=500 [error] failed to fetch: :econnrefused
2022-10-26T06:51:03.822 application=indexer fetcher=code error_count=10 [error] failed to fetch contract codes: :econnrefused`

`2022-10-26T07:11:42.556 application=indexer fetcher=coin_balance count=500 error_count=500 [error] failed to fetch: 0x0000000000000000000000000000000000000000@�: (-32000) header not found `

`ethereum_jsonrpc.log

2022-10-26T06:49:28.756 application=ethereum_jsonrpc count=12 [error] 413 Request Entity Too Large returned from single request batch.  Cannot shrink batch further.
2022-10-26T06:49:28.762 application=ethereum_jsonrpc fetcher=token_updater [error] 413 Request Entity Too Large returned from single request batch.  Cannot shrink batch further.`

`netstat -tunalp | grep :5432 | wc -l
201
netstat -tunalp | grep :8545 | wc -l
1065`

Load Average: 2.60, 2.40, 2.06
CPU Average: Max 30%
Memory: Total: 15G used: 875Mi free: 12Gi buff/cache: 1.4Gi available: 14Gi

**Comment by Ranofty** [comment]
Your RPC doesn’t seems to be active 
also can I see the steps you follow to install Blockscout? 
also which chain framework you use to make your chain?

**Comment by navdeepgarg1** [comment]
`
ETHEREUM_JSONRPC_HTTP_URL="http://3.145.82.137:8545"
ETHEREUM_JSONRPC_TRACE_URL="http://3.145.82.137:8545"
DATABASE_URL='xxxxx'
SECRET_KEY_BASE="xxx"
ETHEREUM_JSONRPC_WS_URL="ws://3.145.82.137:8545/ws"
CHAIN_ID=xxx
HEART_COMMAND="systemctl restart explorer"
SUBNETWORK="xxx"
COIN="xxx"
COIN_NAME="xxx"
INDEXER_DISABLE_BLOCK_REWARD_FETCHER="true"
INDEXER_DISABLE_PENDING_TRANSACTIONS_FETCHER="true"
INDEXER_DISABLE_INTERNAL_TRANSACTIONS_FETCHER="true"
MIX_ENV="prod"
BLOCKSCOUT_PROTOCOL="http"
PORT=4000
DISABLE_EXCHANGE_RATES="true"
POOL_SIZE=100
POOL_SIZE_API=100
ECTO_USE_SSL="false"
HEART_BEAT_TIMEOUT=60
INDEXER_MEMORY_LIMIT="10Gb"
FETCH_REWARDS_WAY="manual"
INDEXER_EMPTY_BLOCKS_SANITIZER_BATCH_SIZE=200
`

RPC is active.

documentation followed  - https://wiki.polygon.technology/docs/edge/additional-features/blockscout/

framework - GO

**Comment by Ranofty** [comment]
DM me for Telegram @Ranofty

**Comment by navdeepgarg1** [comment]
connected

**Comment by ridesky** [comment]
Sorry to bother you, but the same issue here.   @vbaranov 

`
application=indexer fetcher=coin_balance count=500 error_count=500 [error] failed to fetch: 0xdd8c1f3091be4df5354f94dee72e26e41bba5bed@: (-32000) missing trie node 4b5a01b0be21d5c2ac1f21284777ffe30c6aab6143a736fd7c84620171998af0 (path ) <nil>
0xdd8c1f3091be4df5354f94dee72e26e41bba5bed@: (-32000) missing trie node bb5e5aabc12fab7d630fa9b809407a846cba217749014cb41a424b919caa7147 (path ) <nil>
0xdd8c1f3091be4df5354f94dee72e26e41bba5bed@: (-32000) missing trie node 8dcd05cabe37ef07e677dddab0d3040276191a9a744ae517217b68b601698f2c (path ) <nil>
0xdd8c1f3091be4df5354f94dee72e26e41bba5bed@: (-32000) missing trie node cadf96b1e543d77872427e9079212961174d7d0eca905a8982896f7dbfa28a07 (path ) <nil>
0xdd8c1f3091be4df5354f94dee72e26e41bba5bed@: (-32000) missing trie node 2d6d131ef861c4e72f1fdb1b944d6928ca52d9faeb6c8bcf86800181a96a192a (path ) <nil
`



> It runs proper for around 5-10 mins and then it stated crashes and web didn't get loaded then. Tried many different approaches Setup the web and Rpc on the same instance and on the different instance as well but issue still remains the same. Their is no log to be found and the CPU utilization is also only about 10%.

I also run it for a few minutes and then the page starts to crash.


### Environment
* Ubuntu 20.04.5 LTS  (focal)
* Erlang/OTP 26 [DEVELOPMENT] [erts-13.1.2]
* Elixir 1.15.0-dev (015f178) (compiled with Erlang/OTP 26)
* Docker version 20.10.21, build baeda1f 
* Docker Compose version v2.12.2
* node v14.17.6
* Blockscout /master/36be1681d89df5894c2d4195202f5c3ad3a39927  (about 2022-11-04)

**Comment by vbaranov** [comment]
In case of Polygon Edge, some additional env variables should be set, because the node doesn't support archive mode:
```
ETHEREUM_JSONRPC_DISABLE_ARCHIVE_BALANCES=true
INDEXER_DISABLE_PENDING_TRANSACTIONS_FETCHER=true
INDEXER_DISABLE_INTERNAL_TRANSACTIONS_FETCHER=true
```
