### ISSUE TITLE
ENV NETWORK_PATH doesn't work.

### ISSUE THREAD

**Issue by w3cool** [blockscout/blockscout#6310]
*Describe your issue here.*

### Environment

* Deployment type  Docker-compose):
* Elixir & Erlang/OTP versions (`Erlang/OTP 24 [erts-12.1.5] Elixir 1.13.0`):
* Node JS version (`v16.16.0`):
* Operating System: centos  stream 9
* Blockscout Version/branch/commit: current（20221020）
* Archive node type && version (Geth):

### Steps to reproduce

*I want to deploy blockscout in a subpath, like http://127.0.0.1:4000/poa , so I set NETWORK_PATH=/poa and restart the docker image using docker-compose down/up, but It doesn't work. Blockscout still running at http://127.0.0.1:4000/.*
*running blockscout by "docker-compose up -d"*

### Expected behaviour

*bs running at http://127.0.0.1:4000/${NETWORK_PATH}*

### Actual behaviour

*bs running at http://127.0.0.1:4000/.*

**Comment by vbaranov** [comment]
This is not implemented on the application level. It should be managed by reverse proxy (nginx, haproxy, ...) in front of blockscout. `NETWORK_PATH` manages at which path to get front-end assets, it doesn't actually allocate that path, but if proxy is configured to a some some custom path, it allows to get front-end assets (js, css, fonts) from that path.

**Comment by w3cool** [comment]
I already use nginx in front of blockscout, config like this:       
```
location /main/browser/ {
                proxy_pass http://127.0.0.1:4000/;
                proxy_http_version 1.1;
                proxy_redirect off;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header Host $host;
                proxy_set_header Upgrade $http_upgrade;
                proxy_set_header Connection "upgrade";
        }
```
The home page HTML code can respond normally. But js CSS(url:/css/main-page-29270d8b034ee2804927ab30cc6ee816.css?vsn=d) asset response 404. I guess NETWORK_PATH should change front-end load assets url to $NETWORK_PATH/css/main-page-29270d8b034ee2804927ab30cc6ee816.css.

**Comment by w3cool** [comment]
I let home page display normally by adding nginx config:
```
                sub_filter '"/' '"/main/browser/';
                sub_filter_once off;
```
but most of function still doesn't work.

**Comment by lucgerrits** [comment]
I have the same issue, even in a local setup NETWORK_PATH doesn't seem to work.
My Config is:
```
NETWORK_PATH=/eth/mainnet
API_PATH=/
SOCKET_ROOT=/
BLOCKSCOUT_HOST=localhost
BLOCKSCOUT_PROTOCOL=http
PORT=4000
```
When going to http://localhost:4000/eth/mainnet I have a 404 not found.

**Comment by lucgerrits** [comment]
@w3cool @vbaranov  Maybe it's required to recompile ? https://github.com/blockscout/blockscout/pull/832#discussion_r221689213
