### ISSUE TITLE
Please Help: The block and All transaction not real-time load. need to be refresh manually.

### ISSUE THREAD

**Issue by mdd0x** [blockscout/blockscout#6317]
*Describe your issue here.*
I run Polygon-Edge POS on the blockscout, once it first run , its running smoothly with realtime load for block and all transaction.
but after 10 mins its like stuck. the block and all transaction stop load. and need to refresh manually to update it. 
Please Help.

This is the processing:
application=indexer fetcher=block_catchup [info] Checking if index needs to catch up in 2500ms.
application=indexer fetcher=empty_blocks_to_refetch [info] Start sanitizing of empty blocks. Batch size is 100

Screenshot:
<img width="1115" alt="Screen Shot 2022-10-21 at 23 24 05" src="https://user-images.githubusercontent.com/22166837/197243417-afd5382b-4920-46ef-9311-654c4b364525.png">

And this is a latest block, 6 mins ago. it should be realtime loading second by second. so it need to be refresh (on browser) manually.  
<img width="394" alt="Screen Shot 2022-10-21 at 23 25 36" src="https://user-images.githubusercontent.com/22166837/197243673-6657754d-79ad-49ff-9f76-37f0ad76ddeb.png">

Once i refresh the browser, its updating. 
<img width="319" alt="Screen Shot 2022-10-21 at 23 27 10" src="https://user-images.githubusercontent.com/22166837/197243964-726d96d6-1604-44fc-aefd-c03f4819e25e.png">

Please Help.

### Environment
* Elixir Version: 1.13.4
* Erlang Version: 25
* BlockScout Version: 

* User Agent: `Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/106.0.0.0 Safari/537.36`

### This is my environment
API_RATE_LIMIT="50"
API_RATE_LIMIT_BY_KEY="50"
API_RATE_LIMIT_BY_IP="50"
API_RATE_LIMIT_WHITELISTED_IPS=
API_RATE_LIMIT_STATIC_API_KEY=
ETHEREUM_JSONRPC_VARIANT="nethermind"
DATABASE_URL="postgresql://...../blockscout"
SECRET_KEY_BASE="2nQXLKno/F0yVr/Sj8RIp2MnPENI/TDPevla8y32k4i/...."
ETHEREUM_JSONRPC_HTTP_URL="http://127.0.0.1:8545"
ETHEREUM_JSONRPC_TRACE_URL="http://127.0.0.1:8545"
ETHEREUM_JSONRPC_WS_URL="ws://127.0.0.1:8545/ws"
DB_HOST="127.0.0.1"
DB_PASSWORD="123456"
DB_PORT="5432"
DB_USERNAME="postgres"
SUBNETWORK="Mainnet"
DISPLAY_TOKEN_ICONS="true"
INDEXER_DISABLE_INTERNAL_TRANSACTIONS_FETCHER="true"
INDEXER_DISABLE_BLOCK_REWARD_FETCHER="true"
INDEXER_DISABLE_ADDRESS_COIN_BALANCE_FETCHER="true"
INDEXER_DISABLE_PENDING_TRANSACTIONS_FETCHER="true"
ENABLE_SOURCIFY_INTEGRATION="false"
SOURCIFY_SERVER_URL="https://sourcify.dev/server"
SOURCIFY_REPO_URL="https://repo.sourcify.dev/contracts"
HEART_COMMAND="systemctl start explorer.service"
OTHER_EXPLORERS="{}"
SUPPORTED_CHAINS="[]"
ETHEREUM_JSONRPC_TRANSPORT="http"
BLOCKSCOUT_PROTOCOL="http"

**Comment by vbaranov** [comment]
@mdd0x it could happen if `ws://127.0.0.1:8545/ws` is not a valid websocket endpoint. Could you try requesting, for instance, the last block from this wesocket endpoint? Also, you can try unsetting `ETHEREUM_JSONRPC_WS_URL` env variable to see if new blocks begin to appear in real time.

**Comment by mdd0x** [comment]
Following polygon-edge doc, that's correct ws URL. and i have test it before to call API. 

but let me try to unsetting **`ETHEREUM_JSONRPC_WS_URL`**.
btw, i install the blockscout on  azure.

**Comment by mdd0x** [comment]
That's still the same error, I make it live, you can check here [http://35.228.193.50:4000]
- the block not running in realtime
- once contract deploy. code tab not showing. but after i restart the service, its shown.

**Comment by vbaranov** [comment]
@mdd0x please try applying this update on your instance https://github.com/blockscout/blockscout/pull/6340 and please let me know how it goes.

**Comment by mdd0x** [comment]
hi @vbaranov After i tried the changes, im getting this
<img width="1435" alt="Screen Shot 2022-10-25 at 23 36 53" src="https://user-images.githubusercontent.com/22166837/197832338-886e6882-fea9-4762-a632-d10bcb46e9dc.png">

**Comment by vbaranov** [comment]
@mdd0x

Is it possible from your side to make websocket avaialble at ws://35.198.54.39:8545 endpoint and try with that branch again setting up `ETHEREUM_JSONRPC_WS_URL =ws://35.198.54.39:8545`.

It looks like websocket_client library of version 1.3.0 doesn't allow a custom path for websocket if it is not 80 or 443 ports.

**Comment by mdd0x** [comment]
can i use a nginx proxy reverse/load balancer? 
ws://35.198.54.39:8545/ws  ->  ws://35.198.54.39:8545

**Comment by vbaranov** [comment]
I suppose, yes

**Comment by mdd0x** [comment]
but i saw dogechain variable env, they keep using ../ws and works. they run on polygon-edge framework too.

**Comment by vbaranov** [comment]
Because they use a higher version of websocket_client 1.5.0. We're trying to debug your issue with 1.3.0 where there are some restrictions on the websocket URL structure.

**Comment by mdd0x** [comment]
I think the URL cant be change, any other solution brother?

**Comment by JResearchLabs** [comment]
@mdd0x Could you please elaborate the solution. I am facing the same issue

**Comment by haidarabdillah** [comment]
any update of this issue? im facing same issue
