### ISSUE TITLE
Api get token holders no result

### ISSUE THREAD

**Issue by thucngv** [blockscout/blockscout#6319]
I want to get list of token holders of ETH, but it returns no results
/eth/mainnet/api?module=token&action=getTokenHolders&contractaddress=0x0000000000000000000000000000000000000000

**Comment by vbaranov** [comment]
If you want to get tokens owned by address, you should call [`tokenlist`](https://docs.blockscout.com/for-users/api/rpc-endpoints/account#get-list-of-tokens-owned-by-address) API endpoint:
```
https://eth.blockscout.com/api?module=account&action=tokenlist&address=0x0000000000000000000000000000000000000000
```

If you want to get ETH (native coin of the chain) holders on the chain, I suppose, you need to call [`listaccounts`](https://docs.blockscout.com/for-users/api/rpc-endpoints/account#get-a-list-of-accounts-and-their-balances) API endpoint (pagination is supported) and post-process it: filter items with balance > 0:

```
https://eth.blockscout.com/api?module=account&action=listaccounts&page=1&offset=50
```
