### ISSUE TITLE
debug_traceTransaction does not exist/is not available

### ISSUE THREAD

**Issue by gaiyaa** [blockscout/blockscout#6322]
application=indexer fetcher=internal_transaction count=10 error_count=10 [error] failed to fetch internal transactions for blocks: [%{code: -32601, data: %{block_number: 217035, transaction_hash: "0x5af9f89381a808f79a141ca180f5b33c17024fb7595f122209c2e2373877be1b", transaction_index: 0}, message: "the method debug_traceTransaction does not exist/is not available"}]

My Geth node has been added the parameter “debug and --gcmode = archive“

**Comment by vbaranov** [comment]
@gaiyaa how is the full set of parameters look like for running Geth? Please take a look recommended parameters https://docs.blockscout.com/for-developers/information-and-settings/client-settings#geth-client

**Comment by dipakitaliya** [comment]
application=indexer fetcher=internal_transaction count=1 error_count=1 [error] failed to fetch internal transactions for blocks: [%{code: -32601, data: %{block_number: 1, transaction_hash: "0xb0663e19bf53fa830f5aa1082bf25cef899ca50b916949921904bda80331b1d4", transaction_index: 0}, message: "the method debug_traceTransaction does not exist/is not available"}]

facing same error with geth node.

**Comment by vbaranov** [comment]
Could you provide RPC endpoint in order to reproduce the issue?

**Comment by vbaranov** [comment]
Closing due to no response. Please open a new issue, if it still persists.
