### ISSUE TITLE
No Contract could be verified with provided Data Error while verify Contract Code

### ISSUE THREAD

**Issue by ravirasadiya** [blockscout/blockscout#6323]
While verifying contract I am getting error of `No Contract could be verified with provided Data`,
there is no any error in console and logs

### Environment

* Deployment type (Manual/Docker/Docker-compose): Manual
* Elixir & Erlang/OTP versions (`elixir -version`): 1.13.4  & Erlang/OTP 24 [erts-12.3.1] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [jit]
* Node JS version (`node -v`): v16.17.1
* Operating System: Ubuntu 
* Blockscout Version/branch/commit:  4.1.8 beta
* Archive node type && version (Erigon/Geth/Nethermind/Ganache/?): Geth

### Steps to reproduce

After providing all details on contract verification page and clicking verify & publish it is giving me this error

![image](https://user-images.githubusercontent.com/13838294/197355665-b635ae32-1417-492a-b6e7-2872695bfd2b.png)

### Expected behaviour

It should be verified

### Actual behaviour

giving error of `No Contract could be verified with provided Data`

**Comment by ravirasadiya** [comment]
@vbaranov

**Comment by vbaranov** [comment]
@ravirasadiya did you run smart-contract verification microservice together with explorer? If not, I suggest doing that https://docs.blockscout.com/for-developers/information-and-settings/smart-contract-verification. You will experience fewer frictions in the smart-contracts verification process with it.

**Comment by uniwswap** [comment]
yes @vbaranov 

it is runnint on port 8043 using  this code https://github.com/blockscout/blockscout-rs/tree/main/smart-contract-verifier-http

**Comment by vbaranov** [comment]
@rimrakhimov could you please comment on that?

**Comment by rimrakhimov** [comment]
@ravirasadiya @uniwswap Could you please provide creation transaction input and deployed bytecode of the contract you are trying to verify, and sources you use for verificaiton?

**Comment by ravirasadiya** [comment]
Yes,

I tried with any other contract but facing same error every time

You can check it here

Deployed Bytecode
https://uniwscan.com/address/0x2a0cf46ECaaEAD92487577e9b737Ec63B0208a33/contracts#address-tabs

Source code
https://github.com/uniwswap/uniw-public-contracts/blob/main/uniw.sol

**Comment by rimrakhimov** [comment]
@ravirasadiya Thank you for sources. Could you also please share parameters you use for the verification, so I can try to debug the problem?

**Comment by ravirasadiya** [comment]
Sure

Contract Name : UniW
Include nightly builds  : No
Compiler : v0.8.17+commit.8df45f5f
EVM Version: default
Optimization: No
Try to fetch constructor arguments automatically: Yes

You can deploy any contract and with every contract verification it is like that

**Comment by rimrakhimov** [comment]
@ravirasadiya Are you sure that those are parameters the code was deployed with? It seems that the compiler version encoded inside bytecode is 0.8.7. Though, if compiled without optimizations compilation result does not still correspond to the bytecode deployed on chain completely. So, I believe some optimizations were also enabled

**Comment by ravirasadiya** [comment]
@rimrakhimov I tried with so many other contracts as well but I am getting same error again
let me share a video link here so you can check everything is correct, I feel it is any  different error.
Because I am facing same error with any smart contract verification.

https://www.loom.com/share/5ec10e3147544b18b6a5923cd92e4aa2

**Comment by uniwswap** [comment]
https://uniwscan.com/address/0x2a0cf46ECaaEAD92487577e9b737Ec63B0208a33/contracts#address-tabs So why this contract that is exactly the same deployed https://uniwscan.com/address/0x5c33D7157e97253e9096925d071D7a70941F8fbB/contracts#address-tabs cannot be verified ?

**Comment by rimrakhimov** [comment]
They are not the same. You can try to compare two bytecodes with text comparing tools (e.g. https://countwordsfree.com/comparetexts) and see, that they are different. In fact, the metadata part of https://uniwscan.com/address/0x2a0cf46ECaaEAD92487577e9b737Ec63B0208a33/contracts#address-tabs implies that it was compiled with version 0.8.7 and not 0.8.17. I've tried to compare with the bytecode compiled with 0.8.7, but unfortunately there are still some small differences. I'm trying to understand what are those differences but have not come up with that yet.

Did you deployed that contract through remix as well, or did you use something else?

**Comment by vbaranov** [comment]
I am closing the issue. Please open a new one, if you still face issuw with contract verification.
