### ISSUE TITLE
Mainnet: <Issue Title>

### ISSUE THREAD

**Issue by ayman656565** [blockscout/blockscout#6328]
*Describe your issue here.*
My problem is I have a dc coin deposit transaction 8 hours ago and it has not been confirmed yet.
txid
0x2d71d3ae3338ba749c6c0e143b7ae97cd0fe80673ffd4addf293cc95743725d1
This is the link that my deposit is in dc currency. Please cancel the transaction and send my money to this deposit link to my dc wallet
0x7adc6b42f7521ec20c1111943586beda1c2fdeab
### Environment
* Elixir Version: 1.13.4
* Erlang Version: 24
* BlockScout Version: 4.1.8

* User Agent: `Mozilla/5.0 (Linux; Android 7.0; FRD-L09) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/106.0.0.0 Mobile Safari/537.36`

### Steps to reproduce

*Tell us how to reproduce this issue. If possible, push up a branch to your fork with a regression test we can run to reproduce locally.*

### Expected Behaviour

*Tell us what should happen.*

### Actual Behaviour

*Tell us what happens instead.*

**Comment by vbaranov** [comment]
Closing this because it is not related to Blockscout explorer.
