### ISSUE TITLE
cookie store expects conn.secret_key_base to be set?

### ISSUE THREAD

**Issue by gaiyaa** [blockscout/blockscout#6353]
2022-10-27T02:58:33.048 application=plug request_id=FyHNtLB-ae7ekrEAADCk [info] Sent 500 in 5ms
2022-10-27T02:58:33.048 [error] #PID<0.19124.0> running BlockScoutWeb.Endpoint (connection #PID<0.18864.0>, stream id 11) terminated
Server: 123.60.65.149:5000 (http)
Request: GET /address/0xaeD46880615684Dc33eE5374F04b67EfDAaDeeE3/contract_verifications/new
** (exit) an exception was raised:
    ** (ArgumentError) cookie store expects conn.secret_key_base to be set
        (block_scout_web 4.1.8) lib/block_scout_web/plug/redis_cookie.ex:127: BlockScoutWeb.Plug.RedisCookie.validate_secret_key_base/1
        (block_scout_web 4.1.8) lib/block_scout_web/plug/redis_cookie.ex:122: BlockScoutWeb.Plug.RedisCookie.derive/3
        (block_scout_web 4.1.8) lib/block_scout_web/plug/redis_cookie.ex:39: BlockScoutWeb.Plug.RedisCookie.put/4
        (plug 1.13.6) lib/plug/session.ex:96: anonymous fn/3 in Plug.Session.before_send/2
        (elixir 1.13.1) lib/enum.ex:2396: Enum."-reduce/3-lists^foldl/2-0-"/3
        (plug 1.13.6) lib/plug/conn.ex:1690: Plug.Conn.run_before_send/2
        (plug 1.13.6) lib/plug/conn.ex:399: Plug.Conn.send_resp/1
        (block_scout_web 4.1.8) lib/block_scout_web/controllers/address_contract_verification_controller.ex:1: BlockScoutWeb.AddressContractVerificationController.action/2
2022-10-27T02:58:33.145 application=phoenix [info] CONNECTED TO BlockScoutWeb.UserSocket in 46µs
  Transport: :websocket
  Serializer: Phoenix.Socket.V2.JSONSerializer
  Parameters: %{"locale" => "en", "vsn" => "2.0.0"}

_Docker Compose version v2.12.2_

**Comment by vbaranov** [comment]
`SECRET_KEY_BASE` env variable should be set:

> Use mix phx.gen.secret to generate a new Secret Key Base string to protect production assets.

https://docs.blockscout.com/for-developers/information-and-settings/env-variables#general
