### ISSUE TITLE
(FunctionClauseError) no function clause matching in EthereumJSONRPC.Block.elixir_to_params/1

### ISSUE THREAD

**Issue by Dev4Crypto** [blockscout/blockscout#6354]
i am getting following error 

2022-10-22T06:21:05.071 application=indexer fetcher=block_catchup first_block_number=7820 last_block_number=7811 [error] ** (FunctionClauseError) no function clause matching in EthereumJSONRPC.Block.elixir_to_params/1
    (ethereum_jsonrpc 0.1.0) lib/ethereum_jsonrpc/block.ex:196: EthereumJSONRPC.Block.elixir_to_params(%{:ignore => :ignore, "difficulty" => 1, "extraData" => "0xd883010704846765746888676f312e31382e31856c696e757800000000000000f5c19335a79f310054f8c2d7de4f91735a65d80032cc2551df10ec6ab3f5968f001045186eae08efcca59272e756e028c6e0560b8d72f64a83e3e93f4035ad9c00", "gasLimit" => 1523224210, "gasUsed" => 0, "hash" => "0x4c6e4578455ca66d650e4da0cdcd5ee8e7bf0660421498099c311bdeeeeb1eb1", "logsBloom" => "0x00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000", "mixHash" => "0x0000000000000000000000000000000000000000000000000000000000000000", "nonce" => "0x0000000000000000", "number" => 7811, "parentHash" => "0xd1094beb9d71333ab6c5722ef395d11a0df0c30084ef4dd6bcf303d467ce2cc0", "receiptsRoot" => "0x56e81f171bcc55a6ff8345e692c0f86e5b48e01b996cadc001622fb5e363b421", "sha3Uncles" => "0x1dcc4de8dec75d7aab85b567b6ccd41ad312451b948a7413f0a142fd40d49347", "size" => 797, "stateRoot" => "0xe8848546835df1d05a4d7f911a5a808358131c55450e4c8dd32fe1cd5df74124", "timestamp" => ~U[2022-10-21 05:38:40Z], "totalDifficulty" => 7812, "transactions" => [], "transactionsRoot" => "0x56e81f171bcc55a6ff8345e692c0f86e5b48e01b996cadc001622fb5e363b421", "uncles" => []})
    (elixir 1.13.0) lib/enum.ex:1593: Enum."-map/2-lists^map/1-0-"/2
    (ethereum_jsonrpc 0.1.0) lib/ethereum_jsonrpc/blocks.ex:51: EthereumJSONRPC.Blocks.from_responses/2
    (ethereum_jsonrpc 0.1.0) lib/ethereum_jsonrpc.ex:484: EthereumJSONRPC.fetch_blocks_by_params/3
    (indexer 0.1.0) lib/indexer/block/fetcher.ex:131: Indexer.Block.Fetcher.fetch_and_import_range/2
    (indexer 0.1.0) lib/indexer/block/catchup/fetcher.ex:205: Indexer.Block.Catchup.Fetcher.fetch_and_import_range_from_sequence/3
    (elixir 1.13.0) lib/task/supervised.ex:89: Task.Supervised.invoke_mfa/2
    (elixir 1.13.0) lib/task/supervised.ex:34: Task.Supervised.reply/4
    (stdlib 3.17.1) proc_lib.erl:226: :proc_lib.init_p_do_apply/3

Retrying.

### Environment

* Deployment type (Manual/Docker/Docker-compose): Manual
* Elixir & Erlang/OTP versions (`elixir -version`): Erlang/OTP version 24
* Node JS version (`node -v`):  v16.16.0
* Operating System:  Ubuntu 20.04.4 LTS Codename:	focal
* Blockscout Version/branch/commit: Blockscout v 4.1.4-beta
* Archive node type && version (Erigon/Geth/Nethermind/Ganache/?):

### Steps to reproduce
when i run mix phx.server it shows ui but without any data and i found this error in error.log

*Tell us how to reproduce this issue.  ❤️ if you can push up a branch to your fork with a regression test we can run to reproduce locally.*
![remmina_ Blockscout--HYPERONCHAIN-Testnet Darthion_143 244 130 224_20221027-45114 286551](https://user-images.githubusercontent.com/92862036/198197177-4150ad50-9c69-4bf7-83c8-fb5ba19b2274.png)

### Expected behaviour
it should not show any error and show data in UI

**Comment by vbaranov** [comment]
@Dev4Crypto which archive node client & version do you use? Alos, it worth updating to the latest release of Blockscout. Currently, the latest on is [4.1.8](https://github.com/blockscout/blockscout/releases/tag/v4.1.8-beta).

**Comment by Dev4Crypto** [comment]
we like to use version 4.1.4

**Comment by MyEtherAuthority** [comment]
Hi,

> @Dev4Crypto which archive node client & version do you use? Also, it is worth updating to the latest release of Blockscout. Currently, the latest on is [4.1.8](https://github.com/blockscout/blockscout/releases/tag/v4.1.8-beta).

Thanks for your response.. We are using geth and version:  1.7.4-stable-7cbe5da6

<img width="541" alt="image" src="https://user-images.githubusercontent.com/43878603/198794687-f226eff4-77a0-458a-b3fe-80629afe94a7.png">

Also, we tried blockscout 4.1.7 but seems latest it is not compatible with the node version we are using.  Blockscout was sending so many requests to node server and node server gets hanged.
<img width="996" alt="image" src="https://user-images.githubusercontent.com/43878603/198798949-43ee321c-b7b9-47fc-9b8e-9d9d55924405.png">

Thanks again for your time.. <3

**Comment by vbaranov** [comment]
@Dev4Crypto @MyEtherAuthority it seems you're using a very old version of Geth. Can you update Geth up to 1.10.x https://github.com/ethereum/go-ethereum/releases?
