### ISSUE TITLE
Qitmeer: <Issue Title>

### ISSUE THREAD

**Issue by honghogi1233** [blockscout/blockscout#6355]
*Describe your issue 

Qitmeer USDT in my meer account
Without swap to BSC USDT
304$ was incorrectly transferred to the address below.

Please transfer to the original account
 #(0x1e5aacc6a19b85a71f6c859fa3ad01a14bd532e5)

txid: 0xc9412e82f4847b45facbd521d8a1d066d9a1877df67ad372b5456d1dc114d206
from :
0x1e5aacc6a19b85a71f6c859fa3ad01a14bd532e5
to:
0xcfaf1bfcd219289a9d3c40313e90492a521bba68

Thank you for checking it out and taking care of it.

### Environment
* Elixir Version: 1.13.0
* Erlang Version: 24
* BlockScout Version: v4.1.8-beta

* User Agent: `Mozilla/5.0 (Linux; Android 12; SM-N981N Build/SP1A.210812.016; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/106.0.5249.126 Mobile Safari/537.36`

### Steps to reproduce

*Tell us how to reproduce this issue. If possible, push up a branch to your fork with a regression test we can run to reproduce locally.*

### Expected Behaviour

*Tell us what should happen.*

### Actual Behaviour

*Tell us what happens instead.*

**Comment by vbaranov** [comment]
@honghogi1233 What is the URL of the explorer?
