### ISSUE TITLE
Testnet: <Bug Confirmation in Metamask>

### ISSUE THREAD

**Issue by Lava8808** [blockscout/blockscout#6358]
*I found issue that I want to confirmation my tx testnet, according my wallet get confirmation without my want.*

### Environment
* Elixir Version: 1.13.1
* Erlang Version: 24
* BlockScout Version: 

* User Agent: `Mozilla/5.0 (Linux; Android 8.1.0; SM-C710F) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/105.0.0.0 Mobile Safari/537.36`

### Steps to reproduce

*Tell us how to reproduce this issue. If possible, push up a branch to your fork with a regression test we can run to reproduce locally.*

### Expected Behaviour

*Tell us what should happen.*

### Actual Behaviour

*Tell us what happens instead.*

**Comment by vbaranov** [comment]
@Lava8808 could you elaborate more on the issue? Are you trying to send transaction from the Write tab of the contract?

**Comment by vbaranov** [comment]
Closed due to no issue author response.
