### ISSUE TITLE
Read contract and write contract tabs hung on loading

### ISSUE THREAD

**Issue by chiara-andreini** [blockscout/blockscout#6365]
### Environment

* Deployment type (Manual/Docker/Docker-compose): Docker-compose
* Elixir & Erlang/OTP versions (`elixir -version`): Elixir 1.13.1 (compiled with Erlang/OTP 24)
* Node JS version (`node -v`): v16.13.1
* Operating System: Ubuntu 22.04.1 LTS
* Blockscout Version/branch/commit: 4.1.8
* Archive node type && version (Erigon/Geth/Nethermind/Ganache/?): Full, Besu

### Steps to reproduce

I installed a Blockscout instance on an AWS Ubuntu machine. Blockscout tracks and indexes a private, permissioned, proof-of-authority Besu 22.7.7 blockchain, with everything perfectly working except for "Read Contract" and "Write Contract" tabs of a verified contract page, which both hang on loading indefinitely, with no error ever popping up, as shown below.

<img width="969" alt="Screenshot 2022-10-29 at 16 35 55" src="https://user-images.githubusercontent.com/20712806/198837427-27bc4d43-1c11-4219-978a-34927334dacb.png">

 I haven't been able to pinpoint the issue, however possibly relevant context information would be the following:

- I would exclude the reason being a lack of computational resources at the machine, both CPU and RAM consumption remains constant, with no spikes nor other sign of anything being saturated.
- I'm not sure if the network being permissioned (on chain permissioning configured at the Besu node) has any role in this, however I reckon it should show the tab interface with all methods before prompting the connection with Metamask, which it won't.
- After clicking on the tab Read Contract, for instance, Blockscout logs show this, after which the page with the tab opened is still on Loading.

`
blockscout                 | 2022-10-29T14:25:51.457 application=plug request_id=FyKQX2QxMfpQCjcAAHjy [info] GET /address/0x12caa44149f29dfa0d31905174bc5118d542fc60/read-contract
blockscout                 | 2022-10-29T14:25:51.461 application=plug request_id=FyKQX2QxMfpQCjcAAHjy [info] Sent 302 in 3ms
blockscout                 | 2022-10-29T14:25:51.531 application=plug request_id=FyKQX2iQCZrX5HgAAHkS [info] GET /address/0x12caa44149F29Dfa0d31905174BC5118D542Fc60/read-contract
blockscout                 | 2022-10-29T14:25:51.657 application=plug request_id=FyKQX2iQCZrX5HgAAHkS [info] Sent 200 in 126ms
blockscout                 | 2022-10-29T14:25:51.731 application=phoenix [info] CONNECTED TO BlockScoutWeb.UserSocket in 41µs
blockscout                 |   Transport: :websocket
blockscout                 |   Serializer: Phoenix.Socket.V2.JSONSerializer
blockscout                 |   Parameters: %{"locale" => "en", "vsn" => "2.0.0"}
`

### Expected behaviour

As with other Blockscout instances (e.g. https://blockscout.com/xdai/mainnet/address/0xD5eAD2d0Fda1d45C1B6132108cCB1c0307d15b7b/read-contract), clicking on Read Contract or Write Contract tab should load a little interaction interface inside.

**Comment by ravirasadiya** [comment]
is there any update on this?

**Comment by nikitosing** [comment]
@chiara-andreini please, take a look: https://discord.com/channels/973915550965174292/973918718105096242/1039440522764357662

**Comment by chiara-andreini** [comment]
@nikitosing Thank you very much, it was exactly that! It works perfectly now.
