### ISSUE TITLE
0xad1f60376b674dd7f0c1db1aac5e62c30bd0fa8f7f68897695fc2680a32827e7 0x984cd61B103F4Bd779392a71FA7E502AE3Fd91e4 → 0x83f2cD185f7680947175f05295243F26cA3587DC 115.726 WWDOGE

### ISSUE THREAD

**Issue by josoahgithinji** [blockscout/blockscout#6367]
I have not seen the WDOGE COINS since yesterday.Please Check and confirm the position?*Describe your issue here.*

### Environment

* Deployment type (Manual/Docker/Docker-compose):
* Elixir & Erlang/OTP versions (`elixir -version`):
* Node JS version (`node -v`):
* Operating System:
* Blockscout Version/branch/commit:
* Archive node type && version (Erigon/Geth/Nethermind/Ganache/?):

### Steps to reproduce

*Tell us how to reproduce this issue.  ❤️ if you can push up a branch to your fork with a regression test we can run to reproduce locally.*

### Expected behaviour

*Tell us what should happen.*

### Actual behaviour

*Tell us what happens instead.*

**Comment by vbaranov** [comment]
This chat is for technical issues with Blockscout explorer. This issue seems is out of scope.
