### ISSUE TITLE
Mainnet: <Issue Title>

### ISSUE THREAD

**Issue by Mascarvin** [blockscout/blockscout#6368]
*Describe your issue here.*  Hello, I deposited 6680.56 dogecoin plus 11113.44 dogecoin to dogechain.dog.  My balance did show that dogechain.dog received the deposit.  It never converted it from doge to dc.  I withdrew 17776.20 dogecoin from dogechain.dog to coinbase but the dogechain.com history says that the status is pending.  The transaction hash is 0xab05c79fc235038d0bda98a8d42cacfa8ca545b0cd66863f1db173e9a27ed6cf .  Please assist.

David S Weissberg
DSW@Mascarvin.com
631-897-0203

### Environment
* Elixir Version: 1.13.4
* Erlang Version: 24
* BlockScout Version: 4.1.8

* User Agent: `Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/106.0.0.0 Safari/537.36`

### Steps to reproduce

*Tell us how to reproduce this issue. If possible, push up a branch to your fork with a regression test we can run to reproduce locally.*

### Expected Behaviour

*Tell us what should happen.*

### Actual Behaviour

*Tell us what happens instead.*

**Comment by vbaranov** [comment]
This chat is for technical issues with Blockscout explorer. This issue seems is out of scope.
