### ISSUE TITLE
Not able to withdraw moneyFUFI Network: <Issue Title>

### ISSUE THREAD

**Issue by kanijiya** [blockscout/blockscout#6369]
Hi
How to withdraw money ?*Describe your issue here.*

### Environment
* Elixir Version: 1.12.3
* Erlang Version: 24
* BlockScout Version: 1.1

* User Agent: `Mozilla/5.0 (Linux; Android 12; SM-M536B Build/SP1A.210812.016; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/106.0.5249.126 Mobile Safari/537.36`

### Steps to reproduce

*Tell us how to reproduce this issue. If possible, push up a branch to your fork with a regression test we can run to reproduce locally.*

### Expected Behaviour

*Tell us what should happen.*

### Actual Behaviour

*Tell us what happens instead.*

**Comment by vbaranov** [comment]
This chat is for Blockscout explorer technical questions.
