### ISSUE TITLE
Adding New Network ENV Files

### ISSUE THREAD

**Issue by avenbreaks** [blockscout/blockscout#6378]
### Environment

* Deployment type (Docker-compose):

Getting error after start compose the file, how to fix? 

ENV Files : DATABASE_URL=postgresql://postgres:@host.docker.internal:7432/postgres?ssl=false

```
db:
    image: postgres:14
    restart: always
    container_name: 'postgres'
    environment:
        POSTGRES_PASSWORD: 'Passwordpostgres'
        POSTGRES_USER: 'postgres'
        POSTGRES_HOST_AUTH_METHOD: 'trust'
    ports:
      - 7432:5432
```

### Steps to reproduce

`docker compose -f docker-compose.yml up --build 
`
```
ERROR! Config provider Config.Reader failed with:
blockscout               | ** (MatchError) no match of right hand side value: :error
blockscout               |     (stdlib 3.17) erl_eval.erl:450: :erl_eval.expr/5
blockscout               |     (elixir 1.13.1) src/elixir.erl:289: :elixir.recur_eval/3
blockscout               |     (elixir 1.13.1) src/elixir.erl:274: :elixir.eval_forms/3
blockscout               |     (elixir 1.13.1) lib/code.ex:404: Code.validated_eval_string/3
blockscout               |     (elixir 1.13.1) lib/config.ex:260: Config.__eval__!/3
blockscout               |     (elixir 1.13.1) lib/config/reader.ex:92: Config.Reader.read!/2
blockscout               |     (elixir 1.13.1) lib/config/reader.ex:58: Config.Reader.load/2
blockscout               |     (elixir 1.13.1) lib/config/provider.ex:373: anonymous fn/2 in Config.Provider.run_providers/2
blockscout               | 
blockscout               | {"init terminating in do_boot",{{badmatch,error},[{erl_eval,expr,5,[{file,"erl_eval.erl"},{line,450}]},{elixir,recur_eval,3,[{file,"src/elixir.erl"},{line,289}]},{elixir,eval_forms,3,[{file,"src/elixir.erl"},{line,274}]},{'Elixir.Code',validated_eval_string,3,[{file,"lib/code.ex"},{line,404}]},{'Elixir.Config','__eval__!',3,[{file,"lib/config.ex"},{line,260}]},{'Elixir.Config.Reader','read!',2,[{file,"lib/config/reader.ex"},{line,92}]},{'Elixir.Config.Reader',load,2,[{file,"lib/config/reader.ex"},{line,58}]},{'Elixir.Config.Provider','-run_providers/2-fun-0-',2,[{file,"lib/config/provider.ex"},{line,373}]}]}}
blockscout               | init terminating in do_boot ({{badmatch,error},[{erl_eval,expr,5,[{_},{_}]},{elixir,recur_eval,3,[{_},{_}]},{elixir,eval_forms,3,[{_},{_}]},{Elixir.Code,validated_eval_string,3,[{_},{_}]},{Elixir.Config,__eval__!,3,[{_},{_}]},{Elixir.Config.Reader,read!,2,[{_},{_}]},{Elixir.Config.Reader,load,2,[{_},{_}]},{Elixir.Config.Provider,-run_providers/2-fun-0-,2,[{_},{_}]}]})
blockscout               | 
blockscout               | Crash dump is being written to: erl_crash.dump...done
blockscout exited with code 1
blockscout               | ERROR! Config provider Config.Reader failed with:
blockscout               | ** (MatchError) no match of right hand side value: :error
blockscout               |     (stdlib 3.17) erl_eval.erl:450: :erl_eval.expr/5
blockscout               |     (elixir 1.13.1) src/elixir.erl:289: :elixir.recur_eval/3
blockscout               |     (elixir 1.13.1) src/elixir.erl:274: :elixir.eval_forms/3
blockscout               |     (elixir 1.13.1) lib/code.ex:404: Code.validated_eval_string/3
blockscout               |     (elixir 1.13.1) lib/config.ex:260: Config.__eval__!/3
blockscout               |     (elixir 1.13.1) lib/config/reader.ex:92: Config.Reader.read!/2
blockscout               |     (elixir 1.13.1) lib/config/reader.ex:58: Config.Reader.load/2
blockscout               |     (elixir 1.13.1) lib/config/provider.ex:373: anonymous fn/2 in Config.Provider.run_providers/2
blockscout               | 
blockscout               | init terminating in do_boot ({{badmatch,error},[{erl_eval,expr,5,[{_},{_}]},{elixir,recur_eval,3,[{_},{_}]},{elixir,eval_forms,3,[{_},{_}]},{Elixir.Code,validated_eval_string,3,[{_},{_}]},{Elixir.Config,__eval__!,3,[{_},{_}]},{Elixir.Config.Reader,read!,2,[{_},{_}]},{Elixir.Config.Reader,load,2,[{_},{_}]},{Elixir.Config.Provider,-run_providers/2-fun-0-,2,[{_},{_}]}]})
```

**Comment by avenbreaks** [comment]
solved, crash because server is low. 

for last question : how to adding new network. 

ENV Files : 

`LINK_TO_OTHER_EXPLORERS=true`

`OTHER_EXPLORERS={"title": "Gitshock Chain", "url": "https://blockscout.com/poa/core" "test_net?": true}, {"title": "Neware Chain", "url": "https://newarescan.gitshock.com", "test_net?": true}, {"title": "Ethereum Mainnet", "url": "https://blockscout.com/eth/mainnet"}, {"title": "Ethereum Classic", "url": "https://blockscout.com/etc/mainnet", "other?": true}, {"title": "Myopsis Chain", "url": "https://scan.myopsis.finance", "other?": true}, {"title": "Cosmos Interchain", "url": "https://hub.mintscan.io/overview",}, {"title": "RSK Mainnet", "url": "https://blockscout.com/rsk/mainnet", "other?": true "hide_in_dropdown?": true}`


`SUPPORTED_CHAINS={"title": "Gitshock Chain", "url": "https://blockscout.com/poa/core" "test_net?": true}, {"title": "Neware Chain", "url": "https://newarescan.gitshock.com", "test_net?": true}, {"title": "Ethereum Mainnet", "url": "https://blockscout.com/eth/mainnet"}, {"title": "Ethereum Classic", "url": "https://blockscout.com/etc/mainnet", "other?": true}, {"title": "Myopsis Chain", "url": "https://scan.myopsis.finance", "other?": true}, {"title": "Cosmos Interchain", "url": "https://hub.mintscan.io/overview",}, {"title": "RSK Mainnet", "url": "https://blockscout.com/rsk/mainnet", "other?": true "hide_in_dropdown?": true}
`
![image](https://user-images.githubusercontent.com/93043826/199368804-339c7021-4098-43c2-9bf6-cbd5dc393603.png)

**Comment by vbaranov** [comment]
> for last question : how to adding new network.

@avenbreaks What do you mean by a new network? What would you like to achieve?

**Comment by avenbreaks** [comment]
sorry I mean how to make a drop down like this I added my network in the dropdown but it doesn't appear after compiling

![image](https://user-images.githubusercontent.com/93043826/199469718-72ab3ad3-4a7c-41f8-acad-25728dc95788.png)

**Comment by vbaranov** [comment]
Yes, it is managed by `SUPPORTED_CHAINS` env variable. But if you are already on that instance, it disappears from the dropdown.

**Comment by avenbreaks** [comment]
how to bring up the dropdown? I've created but the dropdown doesn't appear, I hope my env settings are correct and it can work sir

`SUPPORTED_CHAINS={"title": "Gitshock Chain", "url": "https://blockscout.com/poa/core" "test_net?": true}, {"title": "Neware Chain", "url": "https://newarescan.gitshock.com", "test_net?": true}, {"title": "Ethereum Mainnet", "url": "https://blockscout.com/eth/mainnet"}, {"title": "Ethereum Classic", "url": "https://blockscout.com/etc/mainnet", "other?": true}, {"title": "Myopsis Chain", "url": "https://scan.myopsis.finance", "other?": true}, {"title": "Cosmos Interchain", "url": "https://hub.mintscan.io/overview",}, {"title": "RSK Mainnet", "url": "https://blockscout.com/rsk/mainnet", "other?": true "hide_in_dropdown?": true}`

**Comment by vbaranov** [comment]
@avenbreaks 

It should be in [], like this:
`
SUPPORTED_CHAINS=[ {"title": "Gitshock Chain", "url": "https://blockscout.com/poa/core" "test_net?": true}, {"title": "Neware Chain", "url": "https://newarescan.gitshock.com", "test_net?": true}, {"title": "Ethereum Mainnet", "url": "https://blockscout.com/eth/mainnet"}, {"title": "Ethereum Classic", "url": "https://blockscout.com/etc/mainnet", "other?": true}, {"title": "Myopsis Chain", "url": "https://scan.myopsis.finance", "other?": true}, {"title": "Cosmos Interchain", "url": "https://hub.mintscan.io/overview",}, {"title": "RSK Mainnet", "url": "https://blockscout.com/rsk/mainnet", "other?": true "hide_in_dropdown?": true} ]
`

**Comment by avenbreaks** [comment]
> @avenbreaks
> 
> Seharusnya di [], seperti ini: `SUPPORTED_CHAINS=[ {"title": "Gitshock Chain", "url": "https://blockscout.com/poa/core" "test_net?": true}, {"title": "Neware Chain", "url": "https://newarescan.gitshock.com", "test_net?": true}, {"title": "Ethereum Mainnet", "url": "https://blockscout.com/eth/mainnet"}, {"title": "Ethereum Classic", "url": "https://blockscout.com/etc/mainnet", "other?": true}, {"title": "Myopsis Chain", "url": "https://scan.myopsis.finance", "other?": true}, {"title": "Cosmos Interchain", "url": "https://hub.mintscan.io/overview",}, {"title": "RSK Mainnet", "url": "https://blockscout.com/rsk/mainnet", "other?": true "hide_in_dropdown?": true} ]`

im trying but not working, im using docker compose

**Comment by vbaranov** [comment]
Try this one:
`
SUPPORTED_CHAINS=[ {"title": "Gitshock Chain", "url": "https://blockscout.com/poa/core" "test_net?": true}, {"title": "Neware Chain", "url": "https://newarescan.gitshock.com", "test_net?": true}, {"title": "Ethereum Mainnet", "url": "https://blockscout.com/eth/mainnet"}, {"title": "Ethereum Classic", "url": "https://blockscout.com/etc/mainnet", "other?": true}, {"title": "Myopsis Chain", "url": "https://scan.myopsis.finance", "other?": true}, {"title": "Cosmos Interchain", "url": "https://hub.mintscan.io/overview"}, {"title": "RSK Mainnet", "url": "https://blockscout.com/rsk/mainnet", "other?": true "hide_in_dropdown?": true} ]
`

**Comment by vbaranov** [comment]
@avenbreaks did it work?

**Comment by avenbreaks** [comment]
> @avenbreaks did it work?

not working sir :(

**Comment by vbaranov** [comment]
@avebreaks, you have broken JSON array inititally.

This one is correct:
```
SUPPORTED_CHAINS=[ {"title": "Gitshock Chain", "url": "https://blockscout.com/poa/core", "test_net?": true}, {"title": "Neware Chain", "url": "https://newarescan.gitshock.com", "test_net?": true}, {"title": "Ethereum Mainnet", "url": "https://blockscout.com/eth/mainnet"}, {"title": "Ethereum Classic", "url": "https://blockscout.com/etc/mainnet", "other?": true}, {"title": "Myopsis Chain", "url": "https://scan.myopsis.finance", "other?": true}, {"title": "Cosmos Interchain", "url": "https://hub.mintscan.io/overview"}, {"title": "RSK Mainnet", "url": "https://blockscout.com/rsk/mainnet", "other?": true, "hide_in_dropdown?": true} ]
```

**Comment by avenbreaks** [comment]
Working perfectly, thankyou
