### ISSUE TITLE
Ethereum Classic: <Issue Title>

### ISSUE THREAD

**Issue by Spyder075** [blockscout/blockscout#6389]
*Describe your issue here.*

### Environment
* Elixir Version: 1.13.1
* Erlang Version: 24
* BlockScout Version: v4.1.8-beta

* User Agent: `Mozilla/5.0 (iPhone; CPU iPhone OS 16_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.1 Mobile/15E148 Safari/604.1`

### Steps to reproduce

*Tell us how to reproduce this issue. If possible, push up a branch to your fork with a regression test we can run to reproduce locally.*

### Expected Behaviour

*Tell us what should happen.*

### Actual Behaviour

*Tell us what happens instead.*

None of my transactions are allowing me to send or purchase any crypto. I’ve tried resetting metamask as well as uninstalling and reinstalling the app and still nothing. My contract address is 0x0ca43832c41b50B8aB3Cbc4B8311E5B31B481788

**Comment by vbaranov** [comment]
This question doesn't relate to Blockscout explorer.
