### ISSUE TITLE
C1: Downloading Trasactions

### ISSUE THREAD

**Issue by johnyork1** [blockscout/blockscout#6400]
Hello, I'm trying to download transactions in order to upload them to Koinly. It's not working.

### Environment
* Elixir Version: 1.13.1
* Erlang Version: 24
* BlockScout Version: v4.1.2-beta

* User Agent: `Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/107.0.0.0 Safari/537.36`

### Steps to reproduce

Enter address in the blockchain explorer: 0x79e443c3a85E01FC44277a1f82643414a2a7695c
Click on "Download [CSV]"

### Expected Behaviour

Transactions should download

### Actual Behaviour

Nothing happens. I tried Chrome and Brave.

**Comment by vbaranov** [comment]
@johnyork1 can you give the link to the explorer?
