### ISSUE TITLE
Mainnet: Wrong receiver address 

### ISSUE THREAD

**Issue by Marlonph15** [blockscout/blockscout#6418]
*Describe your issue here.*

### Environment
* Elixir Version: 1.13.4
* Erlang Version: 24
* BlockScout Version: 4.1.8

* User Agent: `Mozilla/5.0 (Linux; Android 9; INE-LX2; HMSCore 6.7.0.321; GMSCore 22.15.14) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.105 HuaweiBrowser/12.1.2.312 Mobile Safari/537.36`

### Steps to reproduce

*Tell us how to reproduce this issue. If possible, push up a branch to your fork with a regression test we can run to reproduce locally.*

### Expected Behaviour

*Tell us what should happen.*

### Actual Behaviour

*Tell us what happens instead.*

**Comment by vbaranov** [comment]
@Marlonph15 could you elaborate on the issue?

**Comment by Marlonph15** [comment]
Dogecoin.i make a withdrawa in MEXC platform. but input  a wrong network
address. so the fund is gone

**Comment by vbaranov** [comment]
You should contact that platform. This issue doesn't relate to Blockscout.
