### ISSUE TITLE
Mainnet: <Issue Title>

### ISSUE THREAD

**Issue by alalsa65** [blockscout/blockscout#6426]
*Describe your issue here.*

I lost 101,00 DOGE after executing a deposit  from my account in Binance to Metamask. I can see the 101DOGE in the bridge of Dogechain, but they do not pass to Metamask. I've copy here all transsaction details, and you can see at the end, an "input data error of decoding". May be the cause could be this... Could you please give me some solution in order to recover my money, and make it go to Metamask? Thanks a lot.

Transaction Details :
 Transaction Hash
0x5562318665c7e51040aa8455fdf4b11515b60e7dfd10e9003b1cfe59f69a5193
 Result
 Success
 Status
Confirmed Confirmed by 26,511
 Block
[4340840](https://explorer.dogechain.dog/block/4340840)
 Timestamp
 20 hours ago | November-09-2022 01:39:53 PM +1 UTC | Confirmed within <= 2.717 seconds
 From
[0x3e0d4EB566b3d03CaDb8d9e42eE48D90AA40482b](https://explorer.dogechain.dog/address/0x3e0d4EB566b3d03CaDb8d9e42eE48D90AA40482b)
 To
[0x0000000000000000000000000000000000001002](https://explorer.dogechain.dog/address/0x0000000000000000000000000000000000001002)
 Value
0 Doge
 Transaction Fee
0.024755775 Doge
 Gas Price
275 Gwei
 Gas Limit
2,000,000
 Gas Used by Transaction
90,021 | 4.5%
 NoncePosition
6436221
 Raw Input
Hex (Default)
0x19e5c03400000000000000000000000012d3b45bc9d02513be964d6cd122321e0a07733200000000000000000000000000000000000000000000000579a814e10a740000000000000000000000000000000000000000000000000000000000000000008000000000000000000000000000000000000000000000000000000000000001000000000000000000000000000000000000000000000000000000000000000049373036633139396136393666383438316634666534643639396261306635663265363265343639303037623061643136303733383430656664363733323034612d30303030303030340000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000002244465139634754334d4145757644586575453761474459587266383763527a63375a000000000000000000000000000000000000000000000000000000000000
Input
Failed to decode input data.

### Environment
* Elixir Version: 1.13.4
* Erlang Version: 24
* BlockScout Version: 4.1.8

* User Agent: `Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/107.0.0.0 Safari/537.36 Edg/107.0.1418.35`

### Steps to reproduce

*Tell us how to reproduce this issue. If possible, push up a branch to your fork with a regression test we can run to reproduce locally.*

### Expected Behaviour

*Tell us what should happen.*

### Actual Behaviour

*Tell us what happens instead.*

**Comment by vbaranov** [comment]
The issue doesn't relate to Blockscout. Please contact exchange support.

**Comment by alalsa65** [comment]
OK. I'm sorry. I'll do it. Tank you.

________________________________
De: Victor Baranov ***@***.***>
Enviado: jueves, 10 de noviembre de 2022 9:37
Para: blockscout/blockscout ***@***.***>
Cc: alalsa65 ***@***.***>; Author ***@***.***>
Asunto: Re: [blockscout/blockscout] Mainnet: <Issue Title> (Issue #6426)


The issue doesn't relate to Blockscout. Please contact exchange support.
