### ISSUE TITLE
Mainnet: <Didn't Receive DC in my trust wallet>

### ISSUE THREAD

**Issue by Azizkhan75** [blockscout/blockscout#6438]
Hi team

I transferred DC token to my trust wallet but didn't receive it after passing 23 hrs. The receiving address is correct and the transaction id confirms the transfer but the tokens are not reflecting in the trust wallet although I added DC as ERC20 custom token.

transaction-id : 0x63c79cb2f7c406f86884081551b2363ff180643c6aa9e9524ea27904049a1e62
Pls help;

**Comment by vbaranov** [comment]
The question doesn't relate to Blockscout explorer.
