### ISSUE TITLE
Energy Web Chain: sent EWT tokens to wrong address

### ISSUE THREAD

**Issue by ImtiazZafar** [blockscout/blockscout#6441]
*Describe your issue here.*

I have sent EWT tokens (EWT) to an EWTB address (ERC-20). Could you please send it back to:

0xf60569df71d6b82fc744270d5dafa2ce03da758b

TxHash:
0x8e36f35ad12c56ac387b4fb91907f4fe35c3e42a81248371949c18093618451b

### Environment
* Elixir Version: 1.13.1
* Erlang Version: 24
* BlockScout Version: v4.1.5-beta

* User Agent: `Mozilla/5.0 (iPhone; CPU iPhone OS 15_5 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/15.5 Mobile/15E148 Safari/604.1`

### Steps to reproduce

*Tell us how to reproduce this issue. If possible, push up a branch to your fork with a regression test we can run to reproduce locally.*

### Expected Behaviour

*Tell us what should happen.*

### Actual Behaviour

*Tell us what happens instead.*

**Comment by vbaranov** [comment]
This chat is for technical questions about Blockscout. Your question is out of scope.
