### ISSUE TITLE
System requirements suggestions

### ISSUE THREAD

**Issue by zeus-dev** [blockscout/blockscout#6448]
Can I run postgresql server without rds server? I need get data from Ethereum archive node.

**Comment by AndreMiras** [comment]
Maybe that could help https://docs.blockscout.com/for-projects/resource-requirements
Otherwise maybe try on Discord https://discord.gg/blockscout

**Comment by vbaranov** [comment]
Having RDS instance is not a requirement. You can host Postgres DB anywhere.
