### ISSUE TITLE
Issue connecting contract verifier service to Blockscout

### ISSUE THREAD

**Issue by blockinator** [blockscout/blockscout#6453]
I have both Blockscout and the smart-contract-verifier running on a server and I am unable to verify smart contracts. I have both of these variables enabled for the explorer like so:
```
ENABLE_RUST_VERIFICATION_SERVICE=true
RUST_VERIFICATION_SERVICE_URL=http://127.0.01:8043
```

When I run this command:
```
/api/v1/solidity/versions
```
I get this error:
```
{"message":"Params 'module' and 'action' are required parameters","result":null,"status":"0"}
```

The blockchain is based on Polygon Edge. And the Blockscout version is v4.1.8.

**Comment by vbaranov** [comment]
@blockinator 

> When I run this command:
> /api/v1/solidity/versions

This API endpoint is exposed at the smart-contract verification service - this endpoint http://127.0.01:8043/api/v1/solidity/versions should return compiler versions.

**Comment by vbaranov** [comment]
I am closing this because the same issue has been opened at https://github.com/blockscout/blockscout-rs/issues/196. Let's move the discussion there.
