### ISSUE TITLE
Contract verification on Sourcify doesn't show the code in the web interface

### ISSUE THREAD

**Issue by vrde** [blockscout/blockscout#6457]
Contract verification on Sourcify  doesn't show the code in the web interface on evm.evmos.org
Note: we use proxies.

### Environment

* Deployment type (Manual/Docker/Docker-compose):
* Elixir & Erlang/OTP versions (`elixir -version`):
* Node JS version (`node -v`):
* Operating System:
* Blockscout Version/branch/commit:
* Archive node type && version (Erigon/Geth/Nethermind/Ganache/?):

### Steps to reproduce

We have an upgradable contract called `ResolutionManager`.

- Proxy: https://evm.evmos.org/address/0xA65d12De252c60EBD251b3aE45d6029e9eBCA5E7
- Implementation: https://evm.evmos.org/address/0xA0497e979A05E2C3238A50854409Ad3E1487eda3
- Contract lookup on sourcify: https://sourcify.dev/#/lookup/0xA0497e979A05E2C3238A50854409Ad3E1487eda3
- The code doesn't show up https://evm.evmos.org/address/0xA0497e979A05E2C3238A50854409Ad3E1487eda3/contracts

### Expected behaviour

I expect to see the code and being able to read/write at this address: https://evm.evmos.org/address/0xA0497e979A05E2C3238A50854409Ad3E1487eda3/contracts

### Actual behaviour

The code is not verified and I cannot interact with the smart contract through the web interface.

**Comment by vbaranov** [comment]
@vrde we advised evmos team to adjust environment variables for Blockscout instance in order to resolve your issue.

**Comment by vrde** [comment]
@vbaranov did you get any reply? Unfortunately the issue is not solved yet (and I understand it's not your responsibility).

**Comment by vbaranov** [comment]
@vrde sorry for the late reply. Unfortunately evmos shutted down their instance. If you will have similar issue with any other existing instance of Blocskcout, please let me know.
