### ISSUE TITLE
Ethereum Classic: csv-export is not working

### ISSUE THREAD

**Issue by xsoft** [blockscout/blockscout#6458]
Hi,
CSV export of ETC address will always end in 504 timeout.

### Environment
* Elixir Version: 1.13.1
* Erlang Version: 24
* BlockScout Version: v4.1.8-beta

* User Agent: `Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/107.0.0.0 Safari/537.36`

### Steps to reproduce

Try to do CSV export of one ETC adress for one year (even for one month or day).
https://blockscout.com/etc/mainnet/csv-export?address=xxxx&type=transactions

It will result in 504 error and timeout.
```
Gateway time-out Error code 504
Visit [cloudflare.com](https://www.cloudflare.com/5xx-error-landing?utm_source=errorcode_504&utm_campaign=blockscout.com) for more information.
2022-11-16 10:47:35 UTC
You
Browser
Working
Prague
[Cloudflare](https://www.cloudflare.com/5xx-error-landing?utm_source=errorcode_504&utm_campaign=blockscout.com)
Working
blockscout.com
Host
Error
What happened?
The web server reported a gateway time-out error.
```

Im trying this for 24h, different hours (to avoid load).
But result is always the same.

### Expected Behaviour

Success CSV export.

### Actual Behaviour

504 timeout, error, and no export.

**Comment by vbaranov** [comment]
The issue has been resolved. Please re-open, if you still experience it.
