### ISSUE TITLE
Blockscout stops File.Error

### ISSUE THREAD

**Issue by infinite404** [blockscout/blockscout#6465]
I get the following error message:
** (File.Error) could not read file "/usr/local/blockscout/apps/block_scout_web/config/prod# run in production mode.exs": no such file or directory

### Environment

* Deployment type (Manual/Docker/Docker-compose): Manual
* Elixir & Erlang/OTP versions (`elixir -version`): OTP 24 erts-12.1 & Elixir 1.13.4
* Node JS version (`node -v`): 19.1.0
* Operating System: Ubuntu 22.04.1 LTS
* Blockscout Version/branch/commit: https://github.com/Trapesys/blockscout
* Archive node type && version (Erigon/Geth/Nethermind/Ganache/?): Polygon-Edge v0.6.1

### Steps to reproduce

Following the steps here causing the error. I have tried several Erlang installs with openssl1.1.1s, https://wiki.polygon.technology/docs/edge/additional-features/blockscout/#add-erlang-repos 

### Expected behaviour

explorer service should start ( sudo systemctl start explorer.service )

### Actual behaviour

explorer service stops

![blockscout_error](https://user-images.githubusercontent.com/41642833/202328039-e8d51279-01c2-4ac3-9b4e-5be88220c57f.png)

**Comment by vbaranov** [comment]
@infinite404 please check your env variables. Probably, `prod#` is set instead of `prod` somewhere.

**Comment by infinite404** [comment]
Thank you, I found the solution already and it's weird! Basically you have to remove the comments from the .env file. It was reading the comments as well as the vars.
