### ISSUE TITLE
How to verify a contract?

### ISSUE THREAD

**Issue by alexisdavidson** [blockscout/blockscout#6466]
*Describe your issue here.*

Hi, I'm used to verifying smart contracts on ETH pretty easily with hardhat.
Now for ETC I researched a lot and tried many different things. I might not be familiar with the concepts of flattening code, or standard input JSON.

Anyone could share with me a clear way to go through this? My smart contract imports OpenZeppelin contracts so there are dependencies as well

**Comment by vbaranov** [comment]
@alexisdavidson probably, this instruction would be useful https://docs.blockscout.com/for-users/verifying-a-smart-contract/openzeppelin-contract-verification#manual-standard-input-json-with-remix
