### ISSUE TITLE
Block_scout_web return 404 error

### ISSUE THREAD

**Issue by rrhlrmrr** [blockscout/blockscout#6480]
Access to Blockscout web some file return to 404
please help me

### Environment
* Deployment type (Manual/Docker/Docker-compose):
 - Manual
* Elixir & Erlang/OTP versions (`elixir -version`):
 - Elixir 1.12.2 (compiled with Erlang/OTP 24)
* Node JS version (`node -v`):
 - v12.22.9
* Operating System: 
 - Liunx(Ubuntu)
* Blockscout Version/branch/commit:
 - Main Branch
* Archive node type && version (Erigon/Geth/Nethermind/Ganache/?):
 - Geth

### Steps to reproduce
Start the geth -> Start the Blockscout -> access the webpage 

*Tell us how to reproduce this issue.  ❤️ if you can push up a branch to your fork with a regression test we can run to reproduce locally.*
Access to the web

### Expected behaviour
show the page normally

*Tell us what should happen.*

```
./geth --datadir /home/ubuntu/store/ --networkid 3773 --http --http.addr 0.0.0.0 --http.port 8545 --http.api eth,net,web3,txpool --http.corsdomain * --ws.addr 0.0.0.0 --ws.port 8645 --ws.origins * --rpc.allow-unprotected-txs --allow-insecure-unlock --mine --miner.threads 1


cd /home/ubuntu/scan/blockscout
export DATABASE_URL=postgresql://postgres:111111@localhost:5432/blockscout
export SECRET_KEY_BASE=dRJthDUoHCg0Xkdvd23Goq5gz32DCcyGpu+ZoqZKrTIs5deWoI0u+zTQMM2g6QoU 
export ETHEREUM_JSONRPC_VARIANT=geth
export ETHEREUM_JSONRPC_HTTP_URL=http://127.0.0.1:8545
export ETHEREUM_JSONRPC_WS_URL=ws://127.0.0.1:8645
export NETWORK=Test Chain
export SUBNETWORK=
export COIN=TEST
export ECTO_USE_SSL=false
export DISABLE_KNOWN_TOKENS=true
export COINGECKO_COIN_ID=Test
export LOGO=/home/ubuntu/Logo-Test.png
export BLOCK_TRANSFORMER=clique
export DISABLE_KNOWN_TOKENS="true"
mix phx.server

OpenWeb -> http://IP:4000

```

### Actual behaviour
![1](https://user-images.githubusercontent.com/39875249/202845964-03852e61-1d37-446e-944e-62664e21f77a.PNG)

**Comment by vbaranov** [comment]
In order to generate front-end assets you need to run:
>cd apps/block_scout_web/assets; npm install && node_modules/webpack/bin/webpack.js --mode production; cd -
cd apps/explorer && npm install; cd -
>13) Build static assets for deployment mix phx.digest

From the manual deployment guide https://docs.blockscout.com/for-developers/manual-deployment

I am closing this issue for now. Please let us know if you have further requests.
