### ISSUE TITLE
Costume Theme Cannot Change

### ISSUE THREAD

**Issue by avenbreaks** [blockscout/blockscout#6490]
im trying to change UI theme in blockscout neutral_var to ether_var but UI cannot change

### Environment
* Deployment type (Docker-compose): latest
* Operating System: Ubuntu
* Blockscout Version/branch/commit: v4.1.3

### Expected behaviour

![image](https://user-images.githubusercontent.com/93043826/203237909-257f8de7-d76f-4992-9254-d972c8c3c701.png)

**Comment by avenbreaks** [comment]
Im running using docker sir, position blockscout running and i try to command : docker-compose up -d

**Comment by vbaranov** [comment]
Then you need to rebuild the image: `docker-compose up --build`

**Comment by vbaranov** [comment]
I am closing this. Please re-open, if the issue is still present.
