### ISSUE TITLE
Mainnet: <Issue Title>

### ISSUE THREAD

**Issue by borantovas** [blockscout/blockscout#6499]
Hi, I sent DC from the MEXC exchange to my Metamask wallet, this amount is reflected in the explorer, it is not in the wallet. What to do?

*Describe your issue here.*

### Environment
* Elixir Version: 1.13.4
* Erlang Version: 24
* BlockScout Version: 4.1.8

* User Agent: `Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/107.0.0.0 Safari/537.36`

### Steps to reproduce

*Tell us how to reproduce this issue. If possible, push up a branch to your fork with a regression test we can run to reproduce locally.*

### Expected Behaviour

*Tell us what should happen.*

### Actual Behaviour

*Tell us what happens instead.*

**Comment by vbaranov** [comment]
You should ask in exchange support. This chat is for technical questions with Blockscout explorer.

**Comment by borantovas** [comment]
> Hi, I sent DC from the MEXC exchange to my Netmask wallet, this amount is reflected in the explorer, it is not in the wallet. What to do?
> 
> _Describe your issue here._
> 
> ### Environment
> * Elixir Version: 1.13.4
> * Erlang Version: 24
> * BlockScout Version: 4.1.8
> * User Agent: `Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/107.0.0.0 Safari/537.36`
> 
> ### Steps to reproduce
> _Tell us how to reproduce this issue. If possible, push up a branch to your fork with a regression test we can run to reproduce locally._
> 
> ### Expected Behaviour
> _Tell us what should happen._
> 
> ### Actual Behaviour
> _Tell us what happens instead._

**Comment by borantovas** [comment]
In the explorer, this transaction is executed, but in fact there are no coins. https://explorer.dogechain.dog/tx/0x827b720a154d22946c9119185683c62acc17b4be82f5a8badf3313e803b18ad2
