### ISSUE TITLE
[L2 MAIN] Scroll: <Issue Title>

### ISSUE THREAD

**Issue by mru8040** [blockscout/blockscout#6503]
![Screenshot_2022-11-24-23-25-29-866_com kiwibrowser browser](https://user-images.githubusercontent.com/95074164/203844305-d01b91d6-10d2-420e-b7b5-b8e65ee1e066.jpg)
![Screenshot_2022-11-24-23-25-33-591_com kiwibrowser browser](https://user-images.githubusercontent.com/95074164/203844309-23fada07-9142-4c77-b514-056048f6989f.jpg)
![Screenshot_2022-11-24-23-25-29-866_com kiwibrowser browser](https://user-images.githubusercontent.com/95074164/203844336-3ced98ed-3616-44ad-8113-cda201a3dd47.jpg)
Swaping get failed *Describe your issue here.*

### Environment
* Elixir Version: 1.13.1
* Erlang Version: 24
* BlockScout Version: 0.2

* User Agent: `Mozilla/5.0 (Linux; Android 12; M2101K7BI) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/107.0.0.0 Mobile Safari/537.36`

### Steps to reproduce

*Tell us how to reproduce this issue. If possible, push up a branch to your fork with a regression test we can run to reproduce locally.*

### Expected Behaviour

*Tell us what should happen.*

### Actual Behaviour

*Tell us what happens instead.*

**Comment by mru8040** [comment]
Each process work very fast

**Comment by vbaranov** [comment]
This chat is for technical questions about the explorer. Your question is out of scope.
