### ISSUE TITLE
Explorer smart verifier is not working on my end

### ISSUE THREAD

**Issue by iqbalsingh108** [blockscout/blockscout#6508]
Giving below giving errors why this is happening,Please help if there is something wrong on my end.
Smart verifier is not working
![image](https://user-images.githubusercontent.com/4157381/204261121-4492837d-ec00-4bca-b89a-192085541968.png)

**Comment by vbaranov** [comment]
Blockscout's default port is 4000. Did you change it to 80? If not try opening the application at 4000 port.

**Comment by iqbalsingh108** [comment]
> Blockscout's default port is 4000. Did you change it to 80? If not try opening the application at 4000 port.

![image](https://user-images.githubusercontent.com/4157381/204197459-a6c5a564-85ad-456b-9eaf-9a9e19dbdf80.png)
This is the another error when i restart the app with latest codebase with manual deployment.

**Comment by iqbalsingh108** [comment]
@vbaranov And also i've deployed smart contract verifier but there is not verify and publish button here.

![image](https://user-images.githubusercontent.com/4157381/204197815-73da96d8-4242-40d3-ab20-4c46fb9a1cf0.png)

**Comment by iqbalsingh108** [comment]
Any help form @vbaranov from your side.If you can please look into it.Branch is main for smart-verifier

**Comment by eightbox** [comment]
Have you installed smart-contract-verifier?

**Comment by vbaranov** [comment]
You can run smart-verifier from `docker-compose` in one click https://github.com/blockscout/blockscout/tree/master/docker-compose. Please, let me know, if you still facing this issue.
