### ISSUE TITLE
Mainnet: <DOGE Coin sent via Dogechain not received >

### ISSUE THREAD

**Issue by Takaya6388** [blockscout/blockscout#6509]
*DOGE Coin sent via Dogechain not received *

### Environment
* Elixir Version: 1.13.4
* Erlang Version: 24
* BlockScout Version: 4.1.8

* User Agent: `Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:107.0) Gecko/20100101 Firefox/107.0`

### Steps to reproduce

*I sent my DOGE in Dogechain 6 days ago and it shows it is successful but the destination wallet didnt receive it*

### Expected Behaviour

*Destination address should receive the sent doge.*

### Actual Behaviour

*Nothing was received*

**Comment by vbaranov** [comment]
This chat is for technical questions about the explorer. Your question is out of scope.
