### ISSUE TITLE
Testnet: <Issue Title>

### ISSUE THREAD

**Issue by MUSS239** [blockscout/blockscout#6516]
*No technical issue, but the dark mode of the explorer is not readable due to the color selection*

### Environment
* Elixir Version: 1.13.1
* Erlang Version: 24
* BlockScout Version: 

* User Agent: `Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/107.0.0.0 Safari/537.36 Edg/107.0.1418.56`

### Steps to reproduce

*Tell us how to reproduce this issue. If possible, push up a branch to your fork with a regression test we can run to reproduce locally.*

### Expected Behaviour

*Tell us what should happen.*

### Actual Behaviour

*Tell us what happens instead.*

**Comment by vbaranov** [comment]
@MUSS239 which instance of Blockscout are you talking about?

**Comment by vbaranov** [comment]
Closed due to no user feedback.
