### ISSUE TITLE
Ethereum Classic: <Wrong balance>

### ISSUE THREAD

**Issue by SinghSantosh-19** [blockscout/blockscout#6522]
*Blockscout rest api return incorrect balance for below addresses at block number 16436522*
0x063a62060e6720b4da2e0911fb120e238444ebf9
0x06bbac0db47c17fcb89599b76584763a880f13c9
0x1220a50706b347fc69da0458897f28acab50a700

### Environment
* Elixir Version: 1.13.1
* Erlang Version: 24
* BlockScout Version: v4.1.8-beta

* User Agent: `Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/107.0.0.0 Safari/537.36 Edg/107.0.1418.56`

### Steps to reproduce

*Please make api request to blockscout with this URL https://blockscout.com/etc/mainnet/api?module=account&action=eth_get_balance&address=0x06bbac0db47c17fcb89599b76584763a880f13c9&block=16436522.*

### Expected Behaviour

*It should return correct balance*

### Actual Behaviour

*It returns incorrect balance (Please verify it with some other etc explorer or with the ETC node rest api query*

**Comment by vbaranov** [comment]
Balances on all three addresses at block number 16436522 from Blockscout API totally match with balances returned from JSON RPC node. I am closing this issue.
