### ISSUE TITLE
Mainnet: <Issue Title>

### ISSUE THREAD

**Issue by dlugo39** [blockscout/blockscout#6529]
*Describe your issue here.*
I tried to send my dogechain into my coinbase as ETH but the transaction failed. I’d like to either get the coins back into my Metamask or for the transaction to be sent to my coinbase please.
### Environment
* Elixir Version: 1.13.4
* Erlang Version: 24
* BlockScout Version: 4.1.8

* User Agent: `Mozilla/5.0 (iPhone; CPU iPhone OS 15_7_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Mobile/15E148`

### Steps to reproduce

*Tell us how to reproduce this issue. If possible, push up a branch to your fork with a regression test we can run to reproduce locally.*

### Expected Behaviour

*Tell us what should happen.*

### Actual Behaviour

*Tell us what happens instead.*

**Comment by vbaranov** [comment]
You should ask Coinbase support. This question is out of the scope of Blockscout support.
