### ISSUE TITLE
Gnosis tx issues

### ISSUE THREAD

**Issue by vbaranov** [blockscout/blockscout#6537]
1. When fetcher tries to get internal transactions for transaction, but transaction doesn't exist in the Blockscout DB, this error appears:
```
Key (transaction_hash)=(\x03cdaf95b4caf7ea1373dd7da40fb7b133c1c74b9b08c56c1fce6c80ceb403d5) is not present in table "transactions".
```
While we don't know the reason of appearance blocks without some transactions (probably, the bug of archive node), we need to re-fetch that block once this error occurs. Re-fetching implemented in https://github.com/blockscout/blockscout/pull/6510.

2. Pending block operations are growing in GC Blockscout:

![Image](https://user-images.githubusercontent.com/4341812/205070976-750d606d-dd05-440d-ae4e-6e5e1b3b2e6f.png)

**Comment by vbaranov** [comment]
1. resolved by https://github.com/blockscout/blockscout/pull/6510
2. resolved by limiting timeout for the query https://github.com/blockscout/blockscout/commit/3dc901d7cb3252b1c9ce53a3093a9e9f28ce8fa5. But we should also find the reason that some ranges of blocks cause the hanging of the query.

**Comment by 0xtzData** [comment]
Still blocked by Gnosis deployment to verify

**Comment by 0xtzData** [comment]
Fixed in `latest` image, closing.
