### ISSUE TITLE
Slow query pattern to get contracts with unindexed code

### ISSUE THREAD

**Issue by vbaranov** [blockscout/blockscout#6560]
```
 24883 | 01:22:26.540766 | SELECT t0."block_number", t0."created_contract_address_hash", t0."hash" FROM "transactions" AS t0 WHERE ((NOT (t0."block_hash" IS NULL) AND NOT (t0."created_contract_address_hash" IS NULL)) AND (t0."created_contract_code_indexed_at" IS NULL))
```

This partial index potentially improves the execution plan of this query:
```
CREATE INDEX contracts_without_code ON transactions(created_contract_address_hash) WHERE ((block_hash IS NOT NULL) AND (created_contract_code_indexed_at IS NULL));
```

**Comment by nikitosing** [comment]
--- 

Current execution plan

"Index Scan using transactions_created_contract_address_hash_with_pending_index on transactions t0  (cost=0.43..2398.62 rows=625 width=58) (actual time=1.510..1.510 rows=0 loops=1)"
"  Index Cond: (created_contract_address_hash IS NOT NULL)"
"  Filter: ((block_hash IS NOT NULL) AND (created_contract_code_indexed_at IS NULL))"
"  Rows Removed by Filter: 979"
"Planning Time: 0.168 ms"
"Execution Time: 1.531 ms"

----

@vbaranov suggestion 

"Index Scan using contracts_without_code on transactions t0  (cost=0.12..2239.43 rows=625 width=58) (actual time=0.005..0.005 rows=0 loops=1)"
"Planning Time: 0.751 ms"
"Execution Time: 0.029 ms"

-----

**This is the gold middle** 

CREATE INDEX contracts_without_code ON transactions(block_number) WHERE ((block_hash IS NOT NULL) AND (created_contract_code_indexed_at IS NULL) AND (created_contract_address_hash IS NOT NULL));

"Index Scan using contracts_without_code on transactions t0  (cost=0.12..319.38 rows=625 width=58) (actual time=0.001..0.001 rows=0 loops=1)"
"Planning Time: 0.139 ms"
"Execution Time: 0.007 ms"

----

**The best result I achieved but drawback is that index has 3 fields and it will probably leads to a huge index size**

CREATE INDEX contracts_without_code ON transactions(block_number, created_contract_address_hash, hash) WHERE ((block_hash IS NOT NULL) AND (created_contract_code_indexed_at IS NULL) AND (created_contract_address_hash IS NOT NULL));

"Index Only Scan using contracts_without_code on transactions t0  (cost=0.12..293.78 rows=625 width=58) (actual time=0.001..0.001 rows=0 loops=1)"
"  Heap Fetches: 0"
"Planning Time: 0.173 ms"
"Execution Time: 0.006 ms"

----

**Comment by vbaranov** [comment]
I am closing this since the performance of the query improved by the other factors https://github.com/blockscout/blockscout/pull/6570#issuecomment-1857790111.
