### ISSUE TITLE
Add default icon for tokens

### ISSUE THREAD

**Issue by ulyanas** [blockscout/blockscout#6563]

**Comment by tgladilina** [comment]
PNG and SVG  formats

![Token_placeholder](https://user-images.githubusercontent.com/103045386/206242127-7ee932d0-ac3f-483d-bd6c-1cd9a74815ea.svg)
<img width="24" alt="Token_placeholder@2x" src="https://user-images.githubusercontent.com/103045386/206242130-47ef87d8-3469-4263-8de2-560900bb7555.png">

<img width="797" alt="Screenshot 2022-12-07 at 19 55 52" src="https://user-images.githubusercontent.com/103045386/206242233-0d20d9e7-8a5c-43f2-bdc3-42759497cd55.png">

**Comment by 0xtzData** [comment]
иконки теперь есть в:
главная ( список транзакций )
список транзакций
детали транзакции
детали адреса
список транзакций в деталях адреса
токен трансферы
токены (тип токена)
внутренние транзакции
вотч лист
приватные тэги для адреса
публичные тэги для адреса
