### ISSUE TITLE
Verified contract sender incorrect in "read contract" tab.

### ISSUE THREAD

**Issue by LuxesOwen** [blockscout/blockscout#6571]
Verified contract sender incorrect in "read contract" tab.

### Environment

* Deployment type (Manual/Docker/Docker-compose):Manual
* Elixir & Erlang/OTP versions (`elixir -version`):Elixir 1.13.4 (compiled with Erlang/OTP 22)
* Node JS version (`node -v`):v16.15.0
* Operating System: Ubuntu
* Blockscout Version/branch/commit:v4.1.8 master
* Archive node type && version (Erigon/Geth/Nethermind/Ganache/?):Geth

### Steps to reproduce

<img width="1486" alt="image" src="https://user-images.githubusercontent.com/66360114/206985318-2da93f51-7f8d-40df-9700-fb7303e0ede5.png">
I deployed a contract,as above.Then I had Verified it. But when I open the "read contract" tab,all the read functions been invoke automatic,then I write a function to see which sender it use,It print "
0x0000000000000000000000000000000000000000".
How can I call read functions use my current connected wallet address?

### Expected behaviour

“read contract” should be call use my connected wallet address,Or let me call it manual,not automatic.

### Actual behaviour

“read contract” been call automatic,have not use my wallet address.

**Comment by nikitosing** [comment]
@LuxesOwen Hello, could you please share the smart contract code?

**Comment by LuxesOwen** [comment]
> @LuxesOwen Hello, could you please share the smart contract code?
Sure,here are these contracts.
[tokenVestingContracts.zip](https://github.com/blockscout/blockscout/files/10217626/tokenVestingContracts.zip)
