### ISSUE TITLE
Watchpack Error (watcher): Error: ENOSPC

### ISSUE THREAD

**Issue by GVenkata98** [blockscout/blockscout#6575]
*Describe your issue here.*
Error: node_modules/date-fns/typings.d.ts:21146:9 - error TS2649: Cannot augment module 'zhCN' with value exports because it resolves to a non-module entity.
[ng] 
[ng] 21146   const zhCN: Locale
[ng]               ~~~~
[ng] Error: node_modules/date-fns/typings.d.ts:21149:9 - error TS2649: Cannot augment module 'zhHK' with value exports because it resolves to a non-module entity.
[ng] 
[ng] 21149   const zhHK: Locale
[ng]               ~~~~
 node_modules/date-fns/typings.d.ts:21152:9 - error TS2649: Cannot augment module 'zhTW' with value exports because it resolves to a non-module entity.
### Environment

* Deployment type (Manual/Docker/Docker-compose):
* Elixir & Erlang/OTP versions (`elixir -version`):
* Node JS version (`node -v`):
* Operating System:
* Blockscout Version/branch/commit:
* Archive node type && version (Erigon/Geth/Nethermind/Ganache/?):

Plz Reslove this issuse ASAP

**Comment by ekawibisono** [comment]
Hello, please visit this link with problem watcher
https://stackoverflow.com/a/55543310/19909766

**Comment by vbaranov** [comment]
@GVenkata98 which version of NodeJS is used? It should be v16.17.x

**Comment by vbaranov** [comment]
Closing issue because there is no user's feedback.
