### ISSUE TITLE
Missing /js/contract-read-write.js file - Read and Write tabs are not working

### ISSUE THREAD

**Issue by infinite404** [blockscout/blockscout#6604]
Nothing happens when I click on Read or Write tab. Console writes "GET {my-domain}/js/contract-read-write.js net::ERR_ABORTED 404"

### Environment

* Deployment type (Manual/Docker/Docker-compose): manual
* Elixir & Erlang/OTP versions (`elixir -version`): Elixir 1.13.4 & Erlang/OTP 24 [erts-12.3.1]
* Node JS version (`node -v`): v16.18.1
* Operating System: Ubuntu 20.04.5 LTS
* Blockscout Version/branch/commit: it's a fork from https://github.com/Trapesys/blockscout
* Archive node type && version (Erigon/Geth/Nethermind/Ganache/?): polygon-edge v0.6.1 (PoA) ( https://github.com/0xPolygon/polygon-edge/releases/tag/v0.6.1 )

### Steps to reproduce

I have installed polygon-edge following these steps: https://wiki.polygon.technology/docs/edge/get-started/set-up-ibft-on-the-cloud
It's a non-validator node.
I followed the steps here: https://wiki.polygon.technology/docs/edge/additional-features/blockscout
I made a workaround for the problem of indexing is stuck at 99% (def finished_indexing ...)
There was errors because the first few blocks were not imported properly from the chain but I found out there is no real solution on this (maybe because polygon-edge) and I set the value in last_fetched_counters to the last properly indexed block (to 50) and the explorer is working right now without creating error logs

### Expected behaviour

contract's read/write tabs should work and also the Connect Wallet button

### Actual behaviour

read and write tabs are not working, connect wallet button is not working

![read_contract](https://user-images.githubusercontent.com/41642833/208002540-c63b6b73-0ff2-4589-9928-2db708c259b5.png)

![write_contract](https://user-images.githubusercontent.com/41642833/208002572-ea67fc0f-8aa4-421c-bb8a-671ece4c86cd.png)

![missing_file](https://user-images.githubusercontent.com/41642833/208002588-d7b733fe-9722-42f1-9313-bd7aa1838c03.png)

**Comment by infinite404** [comment]
I also reinstalled the solc module because contract verification was not working:
cd /usr/local/blockscout/apps/explorer
npm uninstall solc
npm install --save solc
sudo systemctl restart explorer.service

**Comment by vbaranov** [comment]
@infinite404 The fork of Blockscout is indicated in that instruction. If you need the help of the fork, you should the author of it at in https://github.com/blockscout/blockscout or try cloning code from https://github.com/blockscout/blockscout.

**Comment by infinite404** [comment]
Thanks, I have a question. Is this module https://github.com/blockscout/blockscout-rs/tree/main/smart-contract-verifier the responsible one for the Read / Write tabs?

**Comment by vbaranov** [comment]
@infinite404 https://github.com/blockscout/blockscout-rs/tree/main/smart-contract-verifier is responsible for verification of the contracts (https://docs.blockscout.com/for-developers/information-and-settings/smart-contract-verification). Once the contract is verified, Read/write tabs appear. However, this microservice is not used during contract interaction from those tabs.

**Comment by infinite404** [comment]
Thank you for the info!  I have working Read/Write tabs in the BlockScout v4.1.8-beta version.
