### ISSUE TITLE
 failed to fetch internal transactions for blocks: :closed

### ISSUE THREAD

**Issue by islishude** [blockscout/blockscout#6605]
*Describe your issue here.*

### Environment

* Deployment type (Manual/Docker/Docker-compose): docker-compose
* Elixir & Erlang/OTP versions (`elixir -version`): latest
* Node JS version (`node -v`): latest
* Operating System: Ubuntu 20.04
* Blockscout Version/branch/commit: master
* Archive node type && version (Erigon/Geth/Nethermind/Ganache/?): Geth

### Steps to reproduce

ENV 

```
      ETHEREUM_JSONRPC_DEBUG_TRACE_TRANSACTION_TIMEOUT: '10m'
      INDEXER_DISABLE_PENDING_TRANSACTIONS_FETCHER: 'true'
      INDEXER_DISABLE_BLOCK_REWARD_FETCHER: 'true'
      INDEXER_DISABLE_EMPTY_BLOCK_SANITIZER: 'true'
      ETHEREUM_JSONRPC_DISABLE_ARCHIVE_BALANCES: 'true'
      INDEXER_INTERNAL_TRANSACTIONS_CONCURRENCY: '1'
```

Log

```
2022-12-16T03:40:36.066 application=indexer fetcher=block_catchup first_block_number=4189779 last_block_number=430100 missing_block_count=0 shrunk=false [info] Index already caught up.
2022-12-16T03:40:36.066 application=indexer fetcher=block_catchup [info] Checking if index needs to catch up in 5000ms.
2022-12-16T03:40:36.174 application=indexer fetcher=internal_transaction count=10 error_count=10 [error] failed to fetch internal transactions for blocks: :closed
```

### Expected behaviour

*Tell us what should happen.*

### Actual behaviour

*Tell us what happens instead.*

**Comment by vbaranov** [comment]
@islishude you can also try decreasing `INDEXER_INTERNAL_TRANSACTIONS_BATCH_SIZE`. By default, it is 10.

**Comment by islishude** [comment]
Ok, let me try out with it

**Comment by islishude** [comment]
Not works. I have changed it to 1

**Comment by islishude** [comment]
I don't know what the closed error means, It's weird

**Comment by vbaranov** [comment]
Is `debug` module enabled on Geth node? Can you request Geth node with `debug_traceTransaction` method directly for any transaction?

**Comment by islishude** [comment]
yes, it's enabled

**Comment by islishude** [comment]
I'm sure it's enabled.

<img width="635" alt="image" src="https://user-images.githubusercontent.com/24730006/208066624-bfa93c8e-8e96-4ceb-ae10-5adc7e85431d.png">

some txes have raw trace, some txes don't

**Comment by vbaranov** [comment]
Then probably, the node lack resources under the loading. Try to increase resources for it.

**Comment by islishude** [comment]
I run the blockscout on an aws c5.4xlarge instance, load is not high now

1.87, 1.86, 1.86

**Comment by islishude** [comment]
and I have a question.

If this rpc request for a tx trace fails, will the fetcher try something else?


```
2022-12-16T09:27:33.259 application=indexer fetcher=internal_transaction count=1 error_count=1 [error] failed to fetch internal transactions for blocks: [%{code: -32000, data: %{block_number: 1448102, transaction_hash: "0x987e1ee7f8a6c66a3570a74e464f73b04f7b7d565a76b2d9c4c97dadc2914976", transaction_index: 0}, message: "TypeError: cannot read property 'calls' of undefined    in server-side tracer function 'result'"}]
```

**Comment by islishude** [comment]
I have a layer 2 node.

It has a special logic for a tx, miner will take data gas fee first, It means if a tx doesn't have enough gas, it will not be called in EVM and will be failed on chain.

blockscout couldn't get raw tracer for those txs, because `this.ctxToResult(ctx, db)` returns `undefined`

<img width="792" alt="image" src="https://user-images.githubusercontent.com/24730006/208071504-193483c4-b072-4bac-8b90-c3a0289df625.png">

and rpc always returns `TypeError: cannot read property 'calls' of undefined    in server-side tracer function 'result'`

**Comment by islishude** [comment]
I can change the tracer code and let rpc returns an empty array to blockscout.

seems that blockscout can't handle an empty array.

<img width="550" alt="image" src="https://user-images.githubusercontent.com/24730006/208073890-89efae9f-7d69-444a-aa4c-2734a9a7408d.png">

I'm not good at elixir, do you have any suggestions for the case?

**Comment by islishude** [comment]
blockscout indexer recv_timeout is 30 mins 

```
    transport_options: [
      http: EthereumJSONRPC.HTTP.HTTPoison,
      url: System.get_env("ETHEREUM_JSONRPC_HTTP_URL"),
      http_options: [recv_timeout: :timer.minutes(30), timeout: :timer.minutes(1), hackney: hackney_opts]
    ],
```

tracer timeout is also 30 mins

```
ETHEREUM_JSONRPC_DEBUG_TRACE_TRANSACTION_TIMEOUT: '30m'
```

geth's rpc server writeTimeout is 30 mins

I still get this error, and I don't get any timeout error from geth

```
2023-01-04T00:36:22.728 application=indexer fetcher=internal_transaction count=1 error_count=1 [error] failed to fetch internal transactions for blocks: :closed
```

I don't think it's related to timeout setting.

maybe it's a bug from httpoison?

https://github.com/edgurgel/httpoison/issues/326

**Comment by hundredark** [comment]
> blockscout indexer recv_timeout is 30 mins
> 
> ```
>     transport_options: [
>       http: EthereumJSONRPC.HTTP.HTTPoison,
>       url: System.get_env("ETHEREUM_JSONRPC_HTTP_URL"),
>       http_options: [recv_timeout: :timer.minutes(30), timeout: :timer.minutes(1), hackney: hackney_opts]
>     ],
> ```
> 
> tracer timeout is also 30 mins
> 
> ```
> ETHEREUM_JSONRPC_DEBUG_TRACE_TRANSACTION_TIMEOUT: '30m'
> ```
> 
> geth's rpc server writeTimeout is 30 mins
> 
> I still get this error, and I don't get any timeout error from geth
> 
> ```
> 2023-01-04T00:36:22.728 application=indexer fetcher=internal_transaction count=1 error_count=1 [error] failed to fetch internal transactions for blocks: :closed
> ```
> 
> I don't think it's related to timeout setting.
> 
> maybe it's a bug from httpoison?
> 
> [edgurgel/httpoison#326](https://github.com/edgurgel/httpoison/issues/326)

Hi, have you solve this problem?

**Comment by ammaraskar** [comment]
I'm running into the same problem. I enabled verbose logging on geth and it shows it's successfully the `debug_traceTransaction` requests within milliseconds:
```

infra-geth-miner-1  | DEBUG[01-25|22:21:11.927] Served debug_traceTransaction            conn=172.19.0.8:36464 reqid=6   duration=38.143336ms
infra-geth-miner-1  | DEBUG[01-25|22:21:11.930] Served debug_traceTransaction            conn=172.19.0.8:37358 reqid=132 duration=32.642147ms
infra-geth-miner-1  | DEBUG[01-25|22:21:11.941] Served debug_traceTransaction            conn=172.19.0.8:50020 reqid=835 duration=33.124925ms
...
```

however I see the same `:closed` failures.

Bizzarely enough, when I attached to the application's console and did:
```elixir
iex(blockscout@9bee743b1647)6> import Indexer.Fetcher.InternalTransaction
Indexer.Fetcher.InternalTransaction
iex(blockscout@9bee743b1647)7> json_rpc_named_arguments = Application.get_env(:explorer, :json_rpc_named_arguments)
[
  transport: EthereumJSONRPC.HTTP,
  ...
]
iex(blockscout@9bee743b1647)8> Indexer.Fetcher.InternalTransaction.run([159017], json_rpc_named_arguments)

00:36:39.116 [debug] fetching internal transactions for blocks
...
```

The fetching of the transactions was successful. I'll try to debug further.

**Comment by phpmac** [comment]
Is it solved?
