### ISSUE TITLE
Frontend Broken

### ISSUE THREAD

**Issue by avenbreaks** [blockscout/blockscout#6615]
*Describe your issue here.*

### Environment

* Deployment type (Docker-compose):

After Deploy using Docker, UI broken. 

![image](https://user-images.githubusercontent.com/93043826/208234404-cdc555ae-0dc1-4deb-a165-a744c1e0a74b.png)

**Comment by avenbreaks** [comment]
![image](https://user-images.githubusercontent.com/93043826/208242642-6e7fce78-5ae6-4bc0-954c-328b8cc05103.png)


Logs : 

DevTools failed to load source map: Could not load content for chrome-extension://dmkamcknogkgcdfhhbddcghachkejeap/browser-polyfill.js.map: System error: net::ERR_BLOCKED_BY_CLIENT
139.178.94.227/:10          GET http://139.178.94.227:4000/cartenz/js/chart-loader-b6bde9ee0ca3dcc0ece3e8b5d14fc37f.js?vsn=d net::ERR_ABORTED 404 (Not Found)
139.178.94.227/:1 Refused to apply style from 'http://139.178.94.227:4000/cartenz/css/main-page-200b4c176b26d4aa1eba6fa9b990c0b7.css?vsn=d' because its MIME type ('text/html') is not a supported stylesheet MIME type, and strict MIME checking is enabled.
139.178.94.227/:9          GET http://139.178.94.227:4000/cartenz/js/chain-d01cee1fd307634a795c1a7c042fc59d.js?vsn=d net::ERR_ABORTED 404 (Not Found)
139.178.94.227/:1 Refused to apply style from 'http://139.178.94.227:4000/cartenz/css/non-critical-6de483a6b84348eaf68d9a9e443900b6.css?vsn=d' because its MIME type ('text/html') is not a supported stylesheet MIME type, and strict MIME checking is enabled.
139.178.94.227/:13          GET http://139.178.94.227:4000/cartenz/js/autocomplete-dfb6105e55de214f6a5636ed52df5c17.js?vsn=d net::ERR_ABORTED 404 (Not Found)
139.178.94.227/:11          GET http://139.178.94.227:4000/cartenz/js/token-transfers-toggle-dffbeff4e22a1427602392ce0437273e.js?vsn=d net::ERR_ABORTED 404 (Not Found)
5Refused to execute script from '<URL>' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.
139.178.94.227/:14          GET http://139.178.94.227:4000/cartenz/images/icons/fontawesome/github-085f3d7cc061791dbc3091dd891324d0.svg?vsn=d 404 (Not Found)
139.178.94.227/:15          GET http://139.178.94.227:4000/cartenz/images/icons/fontawesome/twitter-77c54a1c1b6059dd7d457930bc8d1671.svg?vsn=d 404 (Not Found)
139.178.94.227/:16          GET http://139.178.94.227:4000/cartenz/images/icons/fontawesome/telegram-b3bc7d8aac69fc737afcd163f23c5dd3.svg?vsn=d 404 (Not Found)
139.178.94.227/:17          GET http://139.178.94.227:4000/cartenz/images/icons/fontawesome/bar-chart-695c0e001e45371bc2aa623682ee28b4.svg?vsn=d 404 (Not Found)
139.178.94.227/:18          GET http://139.178.94.227:4000/cartenz/images/icons/fontawesome/info-circle-cc526228a68f0cd74fa6c80b8924d54f.svg?vsn=d 404 (Not Found)
139.178.94.227/:19          GET http://139.178.94.227:4000/cartenz/images/icons/fontawesome/tag-287add6175476b8324518840bd775fc4.svg?vsn=d 404 (Not Found)
139.178.94.227/:120          GET http://139.178.94.227:4000/cartenz/images/blockscout_logo-449ba7bde61596740c04a20e99bf6ae7.svg?vsn=d 404 (Not Found)
139.178.94.227/:603          GET http://139.178.94.227:4000/cartenz/js/banner-ef7570b97a11af976bbd60cb9bcd9de5.js?vsn=d net::ERR_ABORTED 404 (Not Found)
DevTools failed to load source map: Could not load content for chrome-extension://gagidkjllbdgggpboolfmmdpeagghjlm/content-script.js.map: System error: net::ERR_BLOCKED_BY_CLIENT
favicon-32x32-4f7aaad43917b84fe242b33e4732942a.png:1          GET http://139.178.94.227:4000/cartenz/images/favicon-32x32-4f7aaad43917b84fe242b33e4732942a.png?vsn=d 404 (Not Found)
Image (async)
(anonymous) @ inpage.js:1
u @ inpage.js:1
a @ inpage.js:1
(anonymous) @ inpage.js:1
r.sendSiteMetadata @ inpage.js:1
e @ inpage.js:1
favicon-16x16-b6c6b5a1c3c74cd45ab16e9c826a85d6.png:1          GET http://139.178.94.227:4000/cartenz/images/favicon-16x16-b6c6b5a1c3c74cd45ab16e9c826a85d6.png?vsn=d 404 (Not Found)
Image (async)
(anonymous) @ inpage.js:1
u @ inpage.js:1
a @ inpage.js:1
await in a (async)
(anonymous) @ inpage.js:1
r.sendSiteMetadata @ inpage.js:1
e @ inpage.js:1
favicon-b71bc796df24f327cddd64b98e93f4ad.ico:1          GET http://139.178.94.227:4000/cartenz/images/favicon-b71bc796df24f327cddd64b98e93f4ad.ico?vsn=d 404 (Not Found)
Image (async)
(anonymous) @ inpage.js:1
u @ inpage.js:1
a @ inpage.js:1
await in a (async)
(anonymous) @ inpage.js:1
r.sendSiteMetadata @ inpage.js:1
e @ inpage.js:1
6The resource <URL> was preloaded using link preload but not used within a few seconds from the window's load event. Please make sure it has an appropriate `as` value and it is preloaded intentionally.
app.use(express.static(path.join(__dirname, "js")));
VM659:1 Uncaught ReferenceError: app is not defined
    at <anonymous>:1:1
(anonymous) @ VM659:1

**Comment by avenbreaks** [comment]
@vbaranov

**Comment by vbaranov** [comment]
@avenbreaks which docker-compose did you use exactly? How did you run the docker container and what docker image tag of the application has been used?

**Comment by avenbreaks** [comment]
Im using latest version
