### ISSUE TITLE
Ethereum Classic: <Issue Title>

### ISSUE THREAD

**Issue by ACybernet** [blockscout/blockscout#6634]
Last night I sent from Ledger 20 ETC to my ETC coinbase account and it is not reflected in the balance, I already checked the address and confirm that it is the same I would like to know if you can help me with this matter

### Environment
* Elixir Version: 1.13.1
* Erlang Version: 24
* BlockScout Version: v4.1.8-beta

* User Agent: `Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36`

### Steps to reproduce

*Tell us how to reproduce this issue. If possible, push up a branch to your fork with a regression test we can run to reproduce locally.*

### Expected Behaviour

*Tell us what should happen.*

### Actual Behaviour

*Tell us what happens instead.*

**Comment by ACybernet** [comment]
Transaction Hash
0x6dc0e3f1a0123a82168cd103a0280d1811379c7bbcd4270a3cb0274c243fe16e

It say complete but is not transfer 

Thanks in advance

**Comment by vbaranov** [comment]
ETC Discord is here https://discord.com/invite/hQs894U
