### ISSUE TITLE
Slow sync in ETH Mainnet error dbconnection disconnected  error :timed out 60000ms

### ISSUE THREAD

**Issue by phoneix1221** [blockscout/blockscout#6644]
*Describe your issue here.*

### Environment

* Deployment type (Manual/Docker/Docker-compose): Docker-compose
* Elixir & Erlang/OTP versions (`elixir -version`): OTP 24 Elixir 1.13.1
* Node JS version (`node -v`): v16.13.1
* Operating System: Ubuntu
* Blockscout Version/branch/commit: 4.1.8
* Archive node type && version (Erigon/Geth/Nethermind/Ganache/?): Erigon

### Steps to reproduce
run blockscout through docker-compose no build no db config

*Tell us how to reproduce this issue.  ❤️ if you can push up a branch to your fork with a regression test we can run to reproduce locally.*

### Expected behaviour
syncs fast and normally without error

*Tell us what should happen.*

### Actual behaviour
syncs very slowly its been 4 days still stuck at 1% indexing and giving an error 

application=indexer fetcher=pending_transaction step=import [error] Failed to validate: [#Ecto.Changeset<action: nil, changes: %{earliest_processing_start: ~U[2022-12-24 06:23:46.657331Z], from_address_hash: %Explorer.Chain.Hash{byte_count: 20, bytes: <<27, 75, 164, 227, 168, 196, 189, 218, 246, 174, 165, 62, 227, 173, 123, 154, 215, 192, 203, 245>>}, gas: #Decimal<139164>, hash: %Explorer.Chain.Hash{byte_count: 32, bytes: <<245, 221, 229, 0, 122, 113, 57, 234, 123, 94, 142, 88, 117, 232, 142, 34, 71, 247, 160, 197, 143, 160, 248, 164, 55, 18, 162, 19, 154, 201, 50, 91>>}, input: %Explorer.Chain.Data{bytes: <<42, 186, 222, 202>>}, max_fee_per_gas: #Explorer.Chain.Wei<11843230974>, max_priority_fee_per_gas: #Explorer.Chain.Wei<179617544>, nonce: 503, r: #Decimal<29562082300876810867528977720638035879938871950751264617946558999436813402803>, s: #Decimal<29866279563794703621138130981116720104921527148344875431598536709454289624311>, to_address_hash: %Explorer.Chain.Hash{byte_count: 20, bytes: <<151, 137, 53, 51, 80, 172, 194, 88, 60, 47, 23, 134, 149, 94, 229, 5, 125, 186, 208, 28>>}, type: 2, v: #Decimal<0>, value: #Explorer.Chain.Wei<0>}, errors: [gas_price: {"can't be blank", [validation: :required]}], data: #Explorer.Chain.Transaction<>, valid?: false>
hosted server configs are 

16c32t cpu
128gb ram
10gbps network 

Config

ETHEREUM_JSONRPC_VARIANT: 'erigon'
ETHEREUM_JSONRPC_HTTP_URL:"url"
ETHEREUM_JSONRPC_TRACE_URL: :"url"
ETHEREUM_JSONRPC_WS_URL:"url"
DATABASE_URL: "db url"
ECTO_USE_SSL: 'false'
SECRET_KEY_BASE: 'keybase'
INDEXER_MEMORY_LIMIT: 96
POOL_SIZE: 500
COIN: ETH
SUBNETWORK: Mainnet
NETWORK: Ethereum

**Comment by kajowy** [comment]
I am experiencing the same errors for the eth mainnet and erigon archive nodes. Log file attached
[a.log](https://github.com/blockscout/blockscout/files/10318621/a.log)

**Comment by phoneix1221** [comment]
@vbaranov

**Comment by phoneix1221** [comment]
> I am experiencing the same errors for the eth mainnet and erigon archive nodes. Log file attached [a.log](https://github.com/blockscout/blockscout/files/10318621/a.log)

Are you still suffering from this issue or you have fixed this?
