### ISSUE TITLE
Cannot Get Block And Transaction On Blockscout

### ISSUE THREAD

**Issue by avenbreaks** [blockscout/blockscout#6660]
I can't get the last block or the block that has been validated in blockscout and the transaction doesn't show at all, is there any suggestion for this problem?

- Polygon SDK

### Environment

* Deployment type (Docker-compose):

![210208724-72ba9b24-a0fd-441d-86fb-4f0429ba7d03](https://user-images.githubusercontent.com/93043826/210222451-ff1572a9-36e8-431f-bea7-8b88ba6566d3.png)

![photo_6165715794869203999_x](https://user-images.githubusercontent.com/93043826/210222369-5694e4f4-5ecd-436a-8a9e-d1c057a6b288.jpg)

![photo_6165715794869204000_y](https://user-images.githubusercontent.com/93043826/210222391-e85b39aa-1e07-45a7-b478-f1a0fdb0cb10.jpg)

![photo_6165715794869204001_y](https://user-images.githubusercontent.com/93043826/210222402-1e3d7497-d08b-4baa-97f2-8a097eacb28b.jpg)

**Comment by vbaranov** [comment]
@avenbreaks is this reprodusible from the latest master branch? Please pull an update.
