### ISSUE TITLE
ConsenSys zkEVM testnet: <The ConsenSys zkEVM network is not being added to the metamask, the fitch chain id is showing. >

### ISSUE THREAD

**Issue by faheemraj** [blockscout/blockscout#6681]
*Describe your issue here.*

### Environment
* Elixir Version: 1.13.1
* Erlang Version: 24
* BlockScout Version: 

* User Agent: `Mozilla/5.0 (Linux; Android 11; RMX2195) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/107.0.0.0 Mobile Safari/537.36`

### Steps to reproduce

*Tell us how to reproduce this issue. If possible, push up a branch to your fork with a regression test we can run to reproduce locally.*

### Expected Behaviour

*Tell us what should happen.*

### Actual Behaviour

*Tell us what happens instead.*

**Comment by faheemraj** [comment]
![Screenshot_2023-01-07-18-33-01-42](https://user-images.githubusercontent.com/61710423/211152039-52f9af81-76a6-4703-92fc-8b489247b08b.jpg)
### 
Please make one click to add network link

**Comment by vbaranov** [comment]
@faheemraj are you sure that RPC URL is correct one? What is the response of this request from the URL `curl -X POST -H "Content-Type: application/json" --data '{"jsonrpc":"2.0","method":"net_version","params":[],"id":1}'` ?

**Comment by faheemraj** [comment]
Thanks for response
Problem solved

Thanks 🙏
