### ISSUE TITLE
ConsenSys zkEVM testnet: Balance Loading Error

### ISSUE THREAD

**Issue by Adolphus000** [blockscout/blockscout#6692]
*Describe your issue here.*

### Environment
* Elixir Version: 1.13.1
* Erlang Version: 24
* BlockScout Version: 

* User Agent: `Mozilla/5.0 (Linux; Android 12; SM-A127F) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/107.0.0.0 Mobile Safari/537.36`

### Steps to reproduce

*Tell us how to reproduce this issue. If possible, push up a branch to your fork with a regression test we can run to reproduce locally.*

Switching to the network, fails to show available balance for coins/tokens.

*Tell us what should happen.*

Balance should be shown after Switching to the Network. 

*Tell us what happens instead.*
![Screenshot_20230109-195151_Kiwi Browser](https://user-images.githubusercontent.com/121563780/211385972-903cbcc7-d43a-4ba2-8c18-05abea9e165b.jpg)

**Comment by vbaranov** [comment]
This chat is for Blockscout related issues.
