### ISSUE TITLE
Does docker deployment support aarch64?

### ISSUE THREAD

**Issue by harveyff** [blockscout/blockscout#6700]
*Describe your issue here.*

Hi, thank you for your great work.

I am currently trying to deploy BSC and ETH with docker, but I found that it does not seem to support aarch64, is there a way to support this? Or do I need to deploy from source?

**Comment by vbaranov** [comment]
[Releases](https://github.com/blockscout/blockscout/releases) support aarch64. The latest on is `blockscout/blockscout:4.1.8`.

**Comment by harveyff** [comment]
> [Releases](https://github.com/blockscout/blockscout/releases) support aarch64. The latest on is `blockscout/blockscout:4.1.8`.

```
 ⠏ smart-contract-verifier The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested                          0.0s
 ⠏ visualizer The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested                                       0.0s
 ⠿ Container blockscout                                                                                                                                                   Started                  1.9s
 ⠇ blockscout The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested 
```

When I use docker deployment on arm64, it reports this error. How can I solve it?

**Comment by vbaranov** [comment]
@harveyff could you add `docker-compose.override.yml` with the following context:
```
cat docker-compose.override.yml
services:

  blockscout:
    platform: linux/arm64
  smart-contract-verifier:
    platform: linux/arm64
  visualizer:
    platform: linux/arm64
```
along with `docker-compose.yml`

**Comment by vbaranov** [comment]
Please use updated `docker-compose.yml` from master branch.

**Comment by 13310241314** [comment]
> _Describe your issue here._
> 
> Hi, thank you for your great work.
> 
> I am currently trying to deploy BSC and ETH with docker, but I found that it does not seem to support aarch64, is there a way to support this? Or do I need to deploy from source?

hi
Have you successfully run blockscout in the arm architecture?

I tried install with source code and Docker image, but they didn't work all.
