### ISSUE TITLE
application=indexer, failed to fetch internal transactions for blocks

### ISSUE THREAD

**Issue by avenbreaks** [blockscout/blockscout#6707]
im using geth and lodestar for consensus create public blockchain with costumized files, But Getting Error `failed to fetch internal transactions for blocks`  After Blockscout Up 

### Environment
* Deployment type (Docker-compose):
* Operating System: Ubuntu Pro 350GB RAM 4TB SSD | Baremetal 
* Blockscout Version/branch/commit: Latest v5
* Archive node type && version (Geth):

### Steps to reproduce
1. setting up env 
2. `docker compose up --build -d `
3. `docker logs -f <container-id>`

Logs: 
```
238fdaa9d086176b4f26e6c7bfb0e130d163ff0f1fe32b4742763f", transaction_index: 0}, message: "the method debug_traceTransaction does not exist/is not available"}]
2023-01-12T03:12:01.955 application=indexer fetcher=pending_transaction [error] %{code: -32601, message: "the method txpool_content does not exist/is not available"}
```

`2023-01-12T03:12:13.335 application=indexer fetcher=internal_transaction count=4 error_count=4 [error] failed to fetch internal transactions for blocks: [%{code: -32601, data: %{block_number: 33, transaction_hash: "0x2f7edae431238fdaa9d086176b4f26e6c7bfb0e130d163ff0f1fe32b4742763f", transaction_index: 0}, message: "the method debug_traceTransaction does not exist/is not available"}]`

**Comment by avenbreaks** [comment]
@vbaranov

**Comment by avenbreaks** [comment]
```
2023-01-12T14:43:43.982 application=indexer fetcher=block_catchup first_block_number=133 last_block_number=124 [error] ** (MatchError) no match of right hand side value: ""
blockscout               |     (indexer 5.0.0) lib/indexer/transform/blocks.ex:90: Indexer.Transform.Blocks.recover_pub_key/2
blockscout               |     (indexer 5.0.0) lib/indexer/transform/blocks/clique.ex:14: Indexer.Transform.Blocks.Clique.transform/1
blockscout               |     (elixir 1.13.1) lib/enum.ex:1593: Enum."-map/2-lists^map/1-0-"/2
blockscout               |     (indexer 5.0.0) lib/indexer/block/fetcher.ex:135: Indexer.Block.Fetcher.fetch_and_import_range/2
blockscout               |     (stdlib 3.17) timer.erl:166: :timer.tc/1
blockscout               |     (indexer 5.0.0) lib/indexer/block/catchup/fetcher.ex:177: Indexer.Block.Catchup.Fetcher.fetch_and_import_range_from_sequence/3
blockscout               |     (elixir 1.13.1) lib/task/supervised.ex:89: Task.Supervised.invoke_mfa/2
blockscout               |     (elixir 1.13.1) lib/task/supervised.ex:34: Task.Supervised.reply/4
```

**Comment by vbaranov** [comment]
@avenbreaks what type of chain are you running? Is it PoA chain? Did you enable `debug` and `txpool` modules on Geth? Please take a look to requirements for Geth https://docs.blockscout.com/for-developers/information-and-settings/client-settings#geth-client.
