### ISSUE TITLE
Smart Contracts Deployed in Genesis Block are Not Recognized as Smart Contracts

### ISSUE THREAD

**Issue by jsanders5** [blockscout/blockscout#6708]
We have a private GoQuorum (geth) chain that deploys several smart contracts in the genesis block. When navigating blockscout to the address of the smart contract, they are not seen as smart contracts, and the code tab is not present

### Environment

* Deployment type (Manual/Docker/Docker-compose): Docker-compose
* Elixir & Erlang/OTP versions (`elixir -version`): bitwalker/alpine-elixir-phoenix:1.13
* Node JS version (`node -v`): bitwalker/alpine-elixir-phoenix:1.13
* Operating System: Manjaro
* Blockscout Version/branch/commit: commit 6935dc68cdee9d853924e2f35471138fb8431374 (origin/master, origin/HEAD, master)
* Archive node type && version (Erigon/Geth/Nethermind/Ganache/?): Full Archive Node && geth

### Steps to reproduce

1. Configure docker-compose to connect to an RPC node of a network that has deployed smart contracts in the genesis block.
2. Run docker-compose
3. Wait for the indexer to finish indexing the chain 
4. Navigate to: http://localhost:4000/address/_<Smart Contract Address>_
5. Notice, it does not say "Contract Address Details", there is no "creator" field, and there is node "Code" tab.

### Expected behaviour

Navigating to the contract address should look like this:

![image](https://user-images.githubusercontent.com/1510222/211975258-08b9062e-3d3e-418d-a294-dde1310c7d94.png)

### Actual behaviour

The address information looks like a normal wallet, and not like that of a smart contract. 

_i.e. it does not say "Contract Address Details", there is no "creator" field, and there is no "Code" tab._

**Comment by vbaranov** [comment]
@jsanders5 in order to get bytecodes of precompiled smart-contracts, Blockscout needs to geth the path to genesis. You can provide it through `CHAIN_SPEC_PATH` environment variable (restart of the application is required after setting it).

From [the docs](https://docs.blockscout.com/for-developers/information-and-settings/env-variables):
> Chain specification path (absolute file system path or URL) to import block emission reward ranges and genesis account balances from. Geth- and OpenEthereum-style specs are supported.

**Comment by vbaranov** [comment]
I am closing this issue. PLease let me know, if you still experience issues regarding this.
