### ISSUE TITLE
Incorrect contract code to address binding

### ISSUE THREAD

**Issue by Qwerty5Uiop** [blockscout/blockscout#6711]
Internal transactions fetcher sometimes misses the internal transactions that creates contract so the indexer doesn't update the corresponding address

**Comment by vbaranov** [comment]
New examples:
https://eth.blockscout.com/address/0xf5f5B97624542D72A9E06f04804Bf81baA15e2B4
https://eth.blockscout.com/address/0x7F86Bf177Dd4F3494b841a37e810A34dD56c829B
