### ISSUE TITLE
API: Last block timestamp or difference between last block timestamp and UTC time.

### ISSUE THREAD

**Issue by GrzegorzDrozda** [blockscout/blockscout#6726]
Hi.
I would like to ask for API endpoint for last block timestamp or even difference between UTC time and last block timestamp:
Something like this on database level:
`
select (EXTRACT(EPOCH FROM (now() at time zone 'utc'))::int) - (EXTRACT(EPOCH FROM max(timestamp))::int) as last_timestamp from blocks;
`
This would be really useful when comes to monitoring blockscout.
Thank you very much for your efforts.

**Comment by vbaranov** [comment]
Blockscout provides `health` endpoint at `/api/v1/health`. For instance, you can check at https://blockscout.com/eth/mainnet/api/v1/health. And here is the response sample:
```
{"data":{"cache_latest_block_inserted_at":"2023-01-24 16:10:11.000000Z","cache_latest_block_number":"16477772","decompiled_contracts_count":"-1.0","latest_block_inserted_at":"2023-01-24 16:10:11.000000Z","latest_block_number":"16477772"},"healthy":true}
```

@GrzegorzDrozda does it fit your needs?
