### ISSUE TITLE
Timestamp is empty on some transaction data in an address

### ISSUE THREAD

**Issue by AFwcxx** [blockscout/blockscout#6729]
On this API

[https://blockscout.com/eth/mainnet/api?module=account&action=txlist&address=0x08723392Ed15743cc38513C4925f5e6be5c17243](https://blockscout.com/eth/mainnet/api?module=account&action=txlist&address=0x08723392Ed15743cc38513C4925f5e6be5c17243)

The `timeStamp` is empty on hash `0xa0427076e8a3ae2aca5e94928c71a54bbc02bd7c56930f4b126336a21baebc2d`.

But on the explorer page the timestamp is shown:
[https://blockscout.com/eth/mainnet/tx/0xa0427076e8a3ae2aca5e94928c71a54bbc02bd7c56930f4b126336a21baebc2d](https://blockscout.com/eth/mainnet/tx/0xa0427076e8a3ae2aca5e94928c71a54bbc02bd7c56930f4b126336a21baebc2d)

**Comment by vbaranov** [comment]
Resolved by updating to 6.0.0
