### ISSUE TITLE
Taiko Alpha-1 L1

### ISSUE THREAD

**Issue by SMojtabaHosseini** [blockscout/blockscout#6733]
### Environment
* Elixir Version: 1.13.1
* Erlang Version: 24
* BlockScout Version: 4.1.8

Google Chrome
### Steps to reproduce
I uploaded a contract on Taiko chain that do some internal transactions

### Expected Behaviour
show internal transactions

### Actual Behaviour
does not show internal transactions

**Comment by vbaranov** [comment]
Blockscout team doesn't manage this instance of Blocskcout. You should contract the Taiko chain team in regards this question.
