### ISSUE TITLE
Code Tab is not showing after deploying contract

### ISSUE THREAD

**Issue by SYSADMGARG** [blockscout/blockscout#6735]
*Describe your issue here.*
I have a blockscout explorer for my polygon-edge based private chain.I'm deploying  contract on my chain after that when i'm trying to verify there is no code tab here
### Environment

* Deployment type (Manual/Docker/Docker-compose):Manual
* Elixir & Erlang/OTP versions (`elixir -version`):1.13.4 & 24
* Node JS version (`node -v`):16.19.0
* Operating System:Ubuntu 20.04 LTS
* Blockscout Version/branch/commit:https://github.com/Trapesys/blockscout(I'm using this as described in official doc of Polygon-Edge)
* Archive node type && version (Erigon/Geth/Nethermind/Ganache/?):Nethermind

### Steps to reproduce

*I have a blockscout explorer for my polygon-edge based private chain.I'm deploying  contract on my chain after that when i'm trying to verify there is no code tab here*

### Expected behaviour

*After deploying contract there should be code tab so that i can move further for verifying contract*

### Actual behaviour

*There is no code tab ,then how can i further proceed for Smart contract verification*

**Comment by SYSADMGARG** [comment]
I tried with the version 5.0.0 beta just now but problem is still there.

**Comment by vbaranov** [comment]
@SYSADMGARG if this contract created from internal transactions, than Blockscout should be able to fetch internal transactions from the node in order to track its creation. Is this contract created from internal transaction or from parent transaction? If it was created from parent transaction, could you check, that archive node, which you're using for Blocskcout do supports one of these methods https://docs.blockscout.com/for-developers/information-and-settings/node-tracing-json-rpc-requirements#enable-tracing-to-fetch-internal-transactions.

**Comment by SYSADMGARG** [comment]
@vbaranov This Contract was created as a dummy contract on chain for testing the verification protocol.I think Polygon-edge based support the methods you sent to me because contract verification and code tab is working before.This is creating issues by tommorrow.

**Comment by SYSADMGARG** [comment]
@vbaranov One thing is weird that on older transactions code tab is showing up.If i restart the explorer service then code tab will active on latest one also
![image](https://user-images.githubusercontent.com/90236304/213421555-20b1642b-fc20-4616-955f-b28b82ba2b81.png)

**Comment by vbaranov** [comment]
> One thing i wanted to know that blockscout release 5.0.0-beta is stable one or not?If not then what is the stable release

5.0.0-beta is stable release.

> One thing is weird that on older transactions code tab is showing up.If i restart the explorer service then code tab will active on latest one also

Fetching of contract bytecode is asynchronous process. So if you wouldn't restart, indexer would fetch it anyways, but after some time.

**Comment by SYSADMGARG** [comment]
> > One thing i wanted to know that blockscout release 5.0.0-beta is stable one or not?If not then what is the stable release
> 
> 5.0.0-beta is stable release.
> 
> > One thing is weird that on older transactions code tab is showing up.If i restart the explorer service then code tab will active on latest one also
> 
> Fetching of contract bytecode is asynchronous process. So if you wouldn't restart, indexer would fetch it anyways, but after some time.

**Comment by SYSADMGARG** [comment]
> > > One thing i wanted to know that blockscout release 5.0.0-beta is stable one or not?If not then what is the stable release
> > 
> > 
> > 5.0.0-beta is stable release.
> > > One thing is weird that on older transactions code tab is showing up.If i restart the explorer service then code tab will active on latest one also
> > 
> > 
> > Fetching of contract bytecode is asynchronous process. So if you wouldn't restart, indexer would fetch it anyways, but after some time.

So what i have to do in my case
Wait or i can do better for this??

**Comment by vbaranov** [comment]
Yes, you should wait or if this a dev instance you can restart the application in order speedup fetching of codes for recent contracts.

**Comment by SYSADMGARG** [comment]
> Yes, you should wait or if this a dev instance you can restart the application in order speedup fetching of codes for recent contracts.

I can restart but i don't want this.I want it will update own the own.

**Comment by SYSADMGARG** [comment]
In how much time this will become normal,i meant to say that in how much time contract transaction update in real time with code.

**Comment by dorijan** [comment]
Hi @SYSADMGARG I have similar situation, do you run polygon-edge in PoS mode? I cannot get Code Tab working either :(

Can you maybe share your env_vars.env to see how you set it up?
Thank you
Dorijan

**Comment by dorijan** [comment]
@SYSADMGARG it seems that I had to set to true 
`INDEXER_DISABLE_INTERNAL_TRANSACTIONS_FETCHER`
on polygon-edge, and this is needed to get this working. How did you pass around that, since you get code tab?

**Comment by SYSADMGARG** [comment]
> @SYSADMGARG it seems that I had to set to true `INDEXER_DISABLE_INTERNAL_TRANSACTIONS_FETCHER` on polygon-edge, and this is needed to get this working. How did you pass around that, since you get code tab?

Hi @dorijan 
Hope ypu're doing good.
Have you solved the above asked issue?

**Comment by SYSADMGARG** [comment]
> Hi @SYSADMGARG I have similar situation, do you run polygon-edge in PoS mode? I cannot get Code Tab working either :(
> 
> Can you maybe share your env_vars.env to see how you set it up? Thank you Dorijan

ETHEREUM_JSONRPC_VARIANT=nethermind
ETHEREUM_JSONRPC_HTTP_URL=localhost:8545
ETHEREUM_JSONRPC_TRACE_URL=localhost:8545
DATABASE_URL=postgresql://blockscout:Passw0Rd@db.instance.local:5432/blockscout
SECRET_KEY_BASE=
ETHEREUM_JSONRPC_WS_URL=
CHAIN_ID=
HEART_COMMAND=systemctl restart explorer
COIN=
COIN_NAME=
MIX_ENV=prod
BLOCKSCOUT_PROTOCOL=http
PORT=4000
HEART_BEAT_TIMEOUT=60
INDEXER_CATCHUP_BLOCKS_BATCH_SIZE=1
INDEXER_DISABLE_BLOCK_REWARD_FETCHER=true
INDEXER_DISABLE_PENDING_TRANSACTIONS_FETCHER=true
INDEXER_DISABLE_INTERNAL_TRANSACTIONS_FETCHER=true
ECTO_USE_SSL=false
INDEXER_MEMORY_LIMIT=10Gb
LOGO=/images/logo.svg
POOL_SIZE=200
POOL_SIZE_API=300
NETWORK=name
SUBNETWORK=name
DB_HOST=Host 
DB_PASSWORD=password
DB_PORT=5432
DB_USERNAME=user
#FOOTER_CHAT_LINK=/images/TG.svg
#FOOTER_FORUM_LINK=/images/TW.svg

**Comment by SYSADMGARG** [comment]
> Hi @SYSADMGARG I have similar situation, do you run polygon-edge in PoS mode? I cannot get Code Tab working either :(
> 
> Can you maybe share your env_vars.env to see how you set it up? Thank you Dorijan

Yes i'm running in POS @dorijan

**Comment by SYSADMGARG** [comment]
Let you know when i'm sure with the solution @dorijan

**Comment by dorijan** [comment]
@SYSADMGARG I think I managed to get it working, hope this will help you
from your env, I took

```
ETHEREUM_JSONRPC_VARIANT=nethermind
INDEXER_CATCHUP_BLOCKS_BATCH_SIZE=1
```

but one thing i also did, took the newest polygon-edge and use it as a rpc client

`docker pull 0xpolygon/polygon-edge:latest`

and used this one, hope this helps.

Dorijan

**Comment by SYSADMGARG** [comment]
> @SYSADMGARG I think I managed to get it working, hope this will help you from your env, I took
> 
> ```
> ETHEREUM_JSONRPC_VARIANT=nethermind
> INDEXER_CATCHUP_BLOCKS_BATCH_SIZE=1
> ```
> 
> but one thing i also did, took the newest polygon-edge and use it as a rpc client
> 
> `docker pull 0xpolygon/polygon-edge:latest`
> 
> and used this one, hope this helps.
> 
> Dorijan

Thanks @dorijan for you suggestions.My side is also working
Closing this
Thanks @vbaranov
