### ISSUE TITLE
reCAPTCHA expire before terminate background process to download CSV  v.4.1.8

### ISSUE THREAD

**Issue by helderjnpinto** [blockscout/blockscout#6738]
*Describe your issue here.*

This issue occurs after aprox 1 min. locally tested with increase connection time and resetDownload in .js file but without success.

![image](https://user-images.githubusercontent.com/12281088/213504991-c303bf07-4851-4653-9e8d-819ba0dd7f79.png)

Some times is possible export only 1 month sometimes not. This is relative to backend processing and frontend connections only wait 1 min after that return a CSV with network error...

![image](https://user-images.githubusercontent.com/12281088/213505045-facb5e7a-00d6-47ad-84ef-686711de0362.png)

 
### Steps to reproduce

Export account transactions with large amount of transactions. This video is from one explorer that are hosted in AWS with 
c5.large

### Expected behaviour

Export CSV even reCAPTCHA time expire.

### Actual behaviour

https://streamable.com/cy6jyr

**Comment by helderjnpinto** [comment]
Maybe related with this issue #5009

**Comment by vbaranov** [comment]
The issue should be resolved with the release 5.2.1, where CSV export performance has been addressed.
