### ISSUE TITLE
Astar (EVM): <Issue Title>

### ISSUE THREAD

**Issue by MissyMining** [blockscout/blockscout#6741]
I cannot find the ASTR I bought on the DEX.  

address # is https://blockscout.com/astar/address/0x315753d9a92e3d5A98809f8A30c7f40134cA5C1C. 

I thought this would be in my Coinbase wallet extension as I did create a network for ASTR.  But I did not find it when I switched networks...any help would be greatly appreciated.  

### Environment
* Elixir Version: 1.13.1
* Erlang Version: 24
* BlockScout Version: v5.0.0-beta

* User Agent: `Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36`

### Steps to reproduce

*Tell us how to reproduce this issue. If possible, push up a branch to your fork with a regression test we can run to reproduce locally.*

### Expected Behaviour

*Tell us what should happen.*

### Actual Behaviour

*Tell us what happens instead.*

**Comment by vbaranov** [comment]
You should contact exchange. This question is out of scope of Blockscout explorer team.
