### ISSUE TITLE
Token id null in address_token_balances for ERC-721 Tokens

### ISSUE THREAD

**Issue by phoneix1221** [blockscout/blockscout#6742]
Describe your issue here.

Environment
Deployment type (Manual/Docker/Docker-compose): Docker-Compose
Elixir & Erlang/OTP versions (elixir -version): OTP 24 Elixir 1.13.1-opt-24
Node JS version (node -v): v16.13.1
Operating System: Ubuntu 22.04.1 LTS
Blockscout Version/branch/commit: 5.0.0-beta
Archive node type && version (Erigon/Geth/Nethermind/Ganache/?): Erigon
Situation:
Same Issue https://github.com/blockscout/blockscout/issues/6068 here.

### Expected behaviour 
For all ERC-721 tokens token_id column should not be null and must contain integer values  in address_token_balances Table 

### Actual behaviour
For all ERC-721 tokens token_id column is null in address_token_balances Table

**Comment by vbaranov** [comment]
`address_current_token_balances` keeps the current balance for the address. For ERC-721 tokens Blockscout stores how many tokens one or the other address owns. This is how we measure balance of ERC-721 tokens for an address. @phoneix1221 could you please clarify, what is the purpose keeping id for ERC-721 tokens which are non-fungible by design in this case?

**Comment by phoneix1221** [comment]
@vbaranov  sorry for misunderstanding in address_current_token_balances as ERC-1155 have token ids and ERC-721 dosen't in that table .I meant to say only for address_token_balances .

**Comment by phoneix1221** [comment]
![image](https://user-images.githubusercontent.com/44673414/214351632-dcd5d56c-ba08-4eb5-a7a5-b15562132827.png)
Here is the image for reference from address_token_balances  Table

**Comment by vbaranov** [comment]
The same as I described above is applied for `address_token_balances` table since this is "the history of token balances": for ERC-721 tokens, Blockscout stores the number of token instances owned by account in `value` column.
