### ISSUE TITLE
why does it show transations when I haven't done any in the past year Palm: <Issue Title>

### ISSUE THREAD

**Issue by electricpumpkin** [blockscout/blockscout#6745]
*Describe your issue here.*

### Environment
* Elixir Version: 1.13.1
* Erlang Version: 24
* BlockScout Version: 

* User Agent: `Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36`

### Steps to reproduce

*Tell us how to reproduce this issue. If possible, push up a branch to your fork with a regression test we can run to reproduce locally.*

### Expected Behaviour

*Tell us what should happen.*

### Actual Behaviour

*Tell us what happens instead.*

**Comment by electricpumpkin** [comment]
why does it show transactions when I haven't done ANY -- ahhhhhhh

**Comment by vbaranov** [comment]
Palm instance of Blocskcout is not managed by Blockscout team. Please, address your question to Palm team.
