### ISSUE TITLE
Error Docker Build And Verification Contract

### ISSUE THREAD

**Issue by ekawibisono** [blockscout/blockscout#6749]
I'm having problems with the latest version of Blockscout V.5.0.0, which is postgres.
I Using Postgres Version 10

### Environment

* Deployment type (Manual/Docker/Docker-compose): Manual And Docker
* Elixir & Erlang/OTP versions (`elixir -version`): elixir 1.14.2-otp-25 | erlang 25.1.1
* Node JS version (`node -v`): nodejs 16.16.0
* Operating System: Ubuntu 20.04
* Blockscout Version/branch/commit: V5.0.0
* Archive node type && version (Erigon/Geth/Nethermind/Ganache/?): Geth

### Steps to reproduce

#!/bin/bash

#restartdatabase
sudo systemctl restart postgresql

#mainblockscout
export SECRET_KEY_BASE=secret
export ETHEREUM_JSONRPC_VARIANT=geth
export ETHEREUM_JSONRPC_HTTP_URL=http://ip:9095/
export ETHEREUM_JSONRPC_WS_URL=ws://ip:9055/
export ETHEREUM_JSONRPC_PENDING_TRANSACTIONS_TYPE=geth
export DATABASE_URL=postgresql://username:password@localhost:5432/blockscout
export COIN=Testnet
export COIN_NAME=Testnet Network
export DISPLAY_TOKEN_ICONS=true
export NETWORK=Testnet
export SUBNETWORK=testnet
export BLOCK_TRANSFORMER=clique
export CHAIN_ID=1104
export JSON_RPC=https://rpc.url.com/
export SHOW_ADDRESS_MARKETCAP_PERCENTAGE=true
export SHOW_PRICE_CHART=true
export SHOW_TXS_CHART=true
export POOL_SIZE=200
export LOGO=/images/logo.png
export LOGO_FOOTER=/images/logo_foot.png
export GAS_PRICE=1
export DISABLE_KNOWN_TOKENS=true
export ECTO_USE_SSL=false 
export BLOCKSCOUT_VERSION=v1.0.0
export LINK_TO_OTHER_EXPLORERS=false
export DISABLE_EXCHANGE_RATES=true
export DISABLE_INDEXER=false
export INDEXER_MEMORY_LIMIT=7
export ENABLE_SOURCIFY_INTEGRATION=true
export ENABLE_RUST_VERIFICATION_SERVICE=true
export RUST_VERIFICATION_SERVICE_URL=http://0.0.0.0:8043/
export APPS_MENU=true
export EXTERNAL_APPS='[ { "title": "Website", "url": "https://url.com/" }, { "title": "Faucet", "url": "https://faucet.url.com/" } ]'

mix compile

#playblockscout
mix phx.server

### Expected behaviour
I Found Error in Postgresql.

![image](https://user-images.githubusercontent.com/22586872/213945963-e0c8223c-03b4-4500-b36e-66224b68aa01.png)

### Actual behaviour

I haven't found the problem yet

**Comment by ekawibisono** [comment]
Update :
When I Run With Manual Success No Problem, But In Docker I Found New Problem.
![image](https://user-images.githubusercontent.com/22586872/213953887-637fb83d-bb52-4fae-b225-217e02c75d4f.png)

**Comment by vbaranov** [comment]
@ekawibisono in order to resolve "too many connections" error you could try decreasing:
```
export POOL_SIZE=200
```

**Comment by ekawibisono** [comment]
hello @vbaranov ,
The manual build process is running smoothly, however, during the docker build process, an error occurs. here is my docker envs

```
# DOCKER_TAG=
ETHEREUM_JSONRPC_VARIANT=geth
ETHEREUM_JSONRPC_HTTP_URL=http://url:9095/
DATABASE_URL=postgresql://postgres:admin001@host.docker.internal:7432/blockscout?ssl=false
ETHEREUM_JSONRPC_TRACE_URL=http://url:9095/
NETWORK=
SUBNETWORK=Testnet Network
LOGO=/images/a.png
LOGO_FOOTER=/images/a.png
ETHEREUM_JSONRPC_WS_URL=ws://url:9055/
ETHEREUM_JSONRPC_TRANSPORT=http
ETHEREUM_JSONRPC_DISABLE_ARCHIVE_BALANCES=false
IPC_PATH=
NETWORK_PATH=/
API_PATH=/
SOCKET_ROOT=/
BLOCKSCOUT_HOST=
BLOCKSCOUT_PROTOCOL=
# SECRET_KEY_BASE=
# CHECK_ORIGIN=
PORT=4000
COIN_NAME=Testnet
# METADATA_CONTRACT=
# VALIDATORS_CONTRACT=
# KEYS_MANAGER_CONTRACT=
# REWARDS_CONTRACT=
# TOKEN_BRIDGE_CONTRACT=
EMISSION_FORMAT=DEFAULT
# CHAIN_SPEC_PATH=
# SUPPLY_MODULE=
COIN=Testnet
EXCHANGE_RATES_COIN=
# EXCHANGE_RATES_SOURCE=
# EXCHANGE_RATES_COINGECKO_COIN_ID=
# EXCHANGE_RATES_COINGECKO_API_KEY=
# EXCHANGE_RATES_COINMARKETCAP_API_KEY=
POOL_SIZE=200
POOL_SIZE_API=10
ECTO_USE_SSL=false
# DATADOG_HOST=
# DATADOG_PORT=
# SPANDEX_BATCH_SIZE=
# SPANDEX_SYNC_THRESHOLD=
HEART_BEAT_TIMEOUT=30
# HEART_COMMAND=
BLOCKSCOUT_VERSION=V1.0.0
RELEASE_LINK=
BLOCK_TRANSFORMER=clique
# GRAPHIQL_TRANSACTION=
# BLOCK_RANGES=
# FIRST_BLOCK=
# LAST_BLOCK=
# TRACE_FIRST_BLOCK=
# TRACE_LAST_BLOCK=
LINK_TO_OTHER_EXPLORERS=true
OTHER_EXPLORERS=[{ "title": "Testnet", "url": "https://explorer.url.com/" },{ "title": "Mainnet", "url": "#" }]
SUPPORTED_CHAINS={}
CACHE_BLOCK_COUNT_PERIOD=7200
CACHE_TXS_COUNT_PERIOD=7200
CACHE_ADDRESS_COUNT_PERIOD=7200
CACHE_ADDRESS_SUM_PERIOD=3600
CACHE_TOTAL_GAS_USAGE_PERIOD=3600
CACHE_ADDRESS_TRANSACTIONS_GAS_USAGE_COUNTER_PERIOD=1800
CACHE_TOKEN_HOLDERS_COUNTER_PERIOD=3600
CACHE_TOKEN_TRANSFERS_COUNTER_PERIOD=3600
CACHE_ADDRESS_WITH_BALANCES_UPDATE_INTERVAL=1800
CACHE_AVERAGE_BLOCK_PERIOD=1800
CACHE_MARKET_HISTORY_PERIOD=21600
CACHE_ADDRESS_TRANSACTIONS_COUNTER_PERIOD=1800
CACHE_ADDRESS_TOKENS_USD_SUM_PERIOD=1800
CACHE_ADDRESS_TOKEN_TRANSFERS_COUNTER_PERIOD=1800
CACHE_BRIDGE_MARKET_CAP_UPDATE_INTERVAL=1800
CACHE_TOKEN_EXCHANGE_RATE_PERIOD=1800
TOKEN_METADATA_UPDATE_INTERVAL=172800
ALLOWED_EVM_VERSIONS=homestead,tangerineWhistle,spuriousDragon,byzantium,constantinople,petersburg,istanbul,berlin,london,default
UNCLES_IN_AVERAGE_BLOCK_TIME=false
DISABLE_WEBAPP=false
DISABLE_READ_API=false
DISABLE_WRITE_API=false
DISABLE_INDEXER=false
DISABLE_REALTIME_INDEXER=false
DISABLE_TOKEN_INSTANCE_FETCHER=true
INDEXER_DISABLE_PENDING_TRANSACTIONS_FETCHER=true
INDEXER_DISABLE_INTERNAL_TRANSACTIONS_FETCHER=true
# INDEXER_CATCHUP_BLOCKS_BATCH_SIZE=
# INDEXER_CATCHUP_BLOCKS_CONCURRENCY=
# INDEXER_INTERNAL_TRANSACTIONS_BATCH_SIZE=
# INDEXER_INTERNAL_TRANSACTIONS_CONCURRENCY=
# INDEXER_COIN_BALANCES_BATCH_SIZE=
# INDEXER_COIN_BALANCES_CONCURRENCY=
# INDEXER_RECEIPTS_BATCH_SIZE=
# INDEXER_RECEIPTS_CONCURRENCY=
# TOKEN_ID_MIGRATION_FIRST_BLOCK=
# TOKEN_ID_MIGRATION_CONCURRENCY=
# TOKEN_ID_MIGRATION_BATCH_SIZE=
# WEBAPP_URL=
# API_URL=
WOBSERVER_ENABLED=false
SHOW_ADDRESS_MARKETCAP_PERCENTAGE=true
CHECKSUM_ADDRESS_HASHES=true
CHECKSUM_FUNCTION=eth
DISABLE_EXCHANGE_RATES=true
DISABLE_KNOWN_TOKENS=false
ENABLE_TXS_STATS=true
SHOW_PRICE_CHART=false
SHOW_TXS_CHART=true
SHOW_TESTNET_LABEL=true
TESTNET_LABEL_TEXT=TESTNET
HISTORY_FETCH_INTERVAL=30
TXS_HISTORIAN_INIT_LAG=0
TXS_STATS_DAYS_TO_COMPILE_AT_INIT=10
COIN_BALANCE_HISTORY_DAYS=90
APPS_MENU=true
EXTERNAL_APPS=[ { "title": "Home", "url": "https://url.com/" },{ "title": "Faucet", "url": "https://faucet.url.com/" },{ "title": "Staking", "url": "https://url.live/" } ]
# GAS_PRICE=
# RESTRICTED_LIST=
# RESTRICTED_LIST_KEY=
SHOW_MAINTENANCE_ALERT=false
MAINTENANCE_ALERT_MESSAGE=
CUSTOM_CONTRACT_ADDRESSES_TEST_TOKEN=
ENABLE_SOURCIFY_INTEGRATION=false
SOURCIFY_SERVER_URL=
SOURCIFY_REPO_URL=
CHAIN_ID=1114
MAX_SIZE_UNLESS_HIDE_ARRAY=50
HIDE_BLOCK_MINER=false
DISPLAY_TOKEN_ICONS=false
SHOW_TENDERLY_LINK=false
TENDERLY_CHAIN_PATH=
MAX_STRING_LENGTH_WITHOUT_TRIMMING=2040
RE_CAPTCHA_SECRET_KEY=
RE_CAPTCHA_CLIENT_KEY=
JSON_RPC=https://rpc.url.com/
API_RATE_LIMIT=50
API_RATE_LIMIT_BY_KEY=50
API_RATE_LIMIT_BY_IP=50
API_RATE_LIMIT_WHITELISTED_IPS=
API_RATE_LIMIT_STATIC_API_KEY=
FETCH_REWARDS_WAY=trace_block
ENABLE_RUST_VERIFICATION_SERVICE=true
RUST_VERIFICATION_SERVICE_URL=http://host.docker.internal:8043/
VISUALIZE_SOL2UML_ENABLED=true
VISUALIZE_SOL2UML_SERVICE_URL=http://host.docker.internal:8050/
# DATABASE_READ_ONLY_API_URL=
# ACCOUNT_DATABASE_URL=
# ACCOUNT_POOL_SIZE=
# ACCOUNT_AUTH0_DOMAIN=
# ACCOUNT_AUTH0_CLIENT_ID=
# ACCOUNT_AUTH0_CLIENT_SECRET=
# ACCOUNT_AUTH0_LOGOUT_URL=
# ACCOUNT_AUTH0_LOGOUT_RETURN_URL=
# ACCOUNT_PUBLIC_TAGS_AIRTABLE_URL=
# ACCOUNT_PUBLIC_TAGS_AIRTABLE_API_KEY=
# ACCOUNT_SENDGRID_API_KEY=
# ACCOUNT_SENDGRID_SENDER=
# ACCOUNT_SENDGRID_TEMPLATE=
ACCOUNT_CLOAK_KEY=
ACCOUNT_ENABLED=false
ACCOUNT_REDIS_URL=redis://redis_db:6379
# MIXPANEL_TOKEN=
# MIXPANEL_URL=
# AMPLITUDE_API_KEY=
# AMPLITUDE_URL=
```

**Comment by ekawibisono** [comment]
And now, I have problems when running the blockcout application via docker, the error is as drawn, please help @vbaranov 

![image](https://user-images.githubusercontent.com/22586872/215198592-18b2d4e8-a0e5-4a56-ad76-d4edeece068d.png)

**Comment by ekawibisono** [comment]
then I get an error on contract verification. please help @vbaranov 
![image](https://user-images.githubusercontent.com/22586872/215219071-6e004819-2ef9-4804-957d-476adfc56b4f.png)
