### ISSUE TITLE
Mainnet: <Issue Title>

### ISSUE THREAD

**Issue by rair81** [blockscout/blockscout#6751]
Hello, I made a Dogechain withdrawal from the MEXC brokerage on 01-22-2023, but it did not fall into my Trust wallet, but it was completed. I ask for help to solve this problem.
transaction hash 0xf25ddc6d39d1f4452b137a58a7407279a713a032fcdb7202735a14cbbb32271f please help.

**Comment by vbaranov** [comment]
You should address this question to the exchange, you interacted with.
