### ISSUE TITLE
Issue with TransparentUpgradeableProxy's implementation address

### ISSUE THREAD

**Issue by adaki2004** [blockscout/blockscout#6760]
We have a polygon-edge based 4-node based private blockchain set up with blockscout:master. 
Our deployment system works with hardhat-deploy modules.

When we deploy smart contracts to the system, we are doing so with the TransparentUpgradeableProxy pattern. It deploys the proxy, the proxy admin and the implementation.

So far so good.
What we observed is, that the proxy contract itself shows, implementation address is 0x0 and I'm not able to query that smart contract via Blockscout at all. (See below)

Impl. address:
![kép](https://user-images.githubusercontent.com/51912515/214552443-3b28fd35-5b50-43bd-87f8-355f5fea5e3e.png)

Not able to query:
![kép](https://user-images.githubusercontent.com/51912515/214552615-5bc856e4-4584-49c1-9268-44ca578749d2.png)

While if I go to the ProxyAdmin contract and query which implementation belongs to this contract address it gives me back the correct setup.
![kép](https://user-images.githubusercontent.com/51912515/214552893-c04958dd-ca4a-4144-9ae3-b3461ceeb1fe.png)

Could you please let us know what we are might missing ? Maybe it is just an environmental variable we haven't set correctly ?

Thank you in advance!

**Comment by nikitosing** [comment]
> But since in the code, this section of code is guarded with a modifier (ifAdmin) blockscout does not support the visualization anymore and shows it as 0x000.... to viewers.

It's possible behaviour. Btw could you check if this repdoducable with current blockscout version

**Comment by nikitosing** [comment]
Close due to no author's response
