### ISSUE TITLE
Astar (EVM): <DATA export CSV - 0x0cF3E16948418649498b59c336ba38678842E2d4>

### ISSUE THREAD

**Issue by Matt3Web** [blockscout/blockscout#6776]
I just want to export transactions for address [0x0cF3E16948418649498b59c336ba38678842E2d4](https://blockscout.com/astar/address/0x0cF3E16948418649498b59c336ba38678842E2d4) to CSV file.

### Environment
* Elixir Version: 1.13.1
* Erlang Version: 24
* BlockScout Version: v5.0.0-beta

* User Agent: `Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36`

### Steps to reproduce

Export transactions for address [0x0cF3E16948418649498b59c336ba38678842E2d4](https://blockscout.com/astar/address/0x0cF3E16948418649498b59c336ba38678842E2d4) to CSV file.

### Expected Behaviour

Start downloading th CSV file.

### Actual Behaviour

After while, it's just stop loading and turn back to orginal state of page without checkmark in CAPTCHA.

**Comment by vbaranov** [comment]
Performance issue with CSV resolved in https://github.com/blockscout/blockscout/pull/7771 and applied to Astar Blockscout instance.
