### ISSUE TITLE
Transmission Sending takes over 24 hours

### ISSUE THREAD

**Issue by DerCaptain69** [blockscout/blockscout#6783]
Hello, everyone,

I wanted ETC from the platform about 24 hours ago
Transfer www.bitfinex.com to www.blockchain.com.

Bitfinex.com showed me that the transfer was filled out correctly. I confirmed everything and the transfer was carried out directly.

The ETC have not arrived in my blockchain (www.blockchain.com) after more than 24 hours.

My ETC have been hanging here since that time (24 hours).
 https://www.blockscout.com.

Is it normal that the transmission or sending of ETC takes so long?

Did I maybe make a mistake when entering it?

Maybe you can help me.

thanks

Transaction Hash: 0x61ac9a4e322af443cea45f81979e146995385bb1fabf656246123cc37a2d413b

Status: Confirmed Confirmed by 7,862
Result: Success
From: 0x77134cbc06cb00b66f4c7e623d5fdbf6777635ec
To: 0x746f3b1e81ebf2b089fe3b860b69557cedf7638b

**Comment by vbaranov** [comment]
You should contact exchange, which you interacted with.
