### ISSUE TITLE
make: *** [priv/libsecp256k1_nif.so] Error 77

### ISSUE THREAD

**Issue by sertoriuss** [blockscout/blockscout#6791]
### Environment

* Deployment type (Manual/Docker/Docker-compose): Manual
* Elixir & Erlang/OTP versions (`elixir -version`): elixir 1.14.3 (compiled with Erlang/OTP 25)
* Node JS version (`node -v`): 18.13.0
* Operating System: macOS 13.2
* Blockscout Version/branch/commit: master

### Steps to reproduce

```
mix do deps.get, local.rebar --force, deps.compile

checking whether the C compiler works... no
configure: error: in `/blockscout/deps/libsecp256k1/c_src/secp256k1':
configure: error: C compiler cannot create executables
See `config.log' for more details
make: *** [priv/libsecp256k1_nif.so] Error 77
==> libsecp256k1
warning: Mix compiler :make_bindings was supposed to return {:ok | :noop | :error, [diagnostic]} but it returned :error
Compiling 1 file (.erl)
src/libsecp256k1.erl:146:1: Warning: function not_loaded/1 is unused
%  146| not_loaded(Line) ->
%     | ^

Generated libsecp256k1 app
==> con_cache
```

### Expected behaviour

Dependencies are successfully installed

### Actual behaviour

Dependencies installation error

**Comment by vbaranov** [comment]
@sertoriuss what Erlang/OTP version is used?
You can check with:
```
erl -eval '{ok, Version} = file:read_file(filename:join([code:root_dir(), "releases", erlang:system_info(otp_release), "OTP_VERSION"])), io:fwrite(Version), halt().' -noshell
```

If it is less than `25.2.1`, could you please try to upgrade?

**Comment by sertoriuss** [comment]
`25.2.1`

**Comment by sertoriuss** [comment]
Found that blockscout uses:
```
{:libsecp256k1, "~> 0.1.10"}
```
https://github.com/blockscout/blockscout/blob/85963ef02f6608bcbd0c43468b64e65995e0c558/apps/indexer/mix.exs#L49

I'm not the only one who has this problem:
https://github.com/exthereum/libsecp256k1/issues/25

last commit for `libsecp256k1`, was in `Jan 30, 2020`
https://github.com/exthereum/libsecp256k1/commit/304a8c513ad505b14c02e269494f31f108775190

perhaps there are more relevant alternatives or can this package become a replacement:
https://hex.pm/packages/libsecp256k1_diode_fork
https://github.com/diodechain/libsecp256k1

with `libsecp256k1_diode_fork`, I moved on, but came across this error:
```


~/blockscout]$ mix phx.server
2023-01-31T20:20:01.392 [warning] The on_load function for module Elixir.ExKeccak returned:
{:error,
 {:load_failed,
  'Failed to load NIF library: \'dlopen(/blockscout/_build/dev/lib/ex_keccak/priv/native/libexkeccak.so, 0x0002): tried: \'/blockscout/_build/dev/lib/ex_keccak/priv/native/libexkeccak.so\' (mach-o file, but is an incompatible architecture (have \'x86_64\', need \'arm64\')), \'/System/Volumes/Preboot/Cryptexes/OS/blockscout/_build/dev/lib/ex_keccak/priv/native/libexkeccak.so\' (no such file), \'/blockscout/_build/dev/lib/ex_keccak/priv/native/libexkeccak.so\' (mach-o file, but is an incompatible architecture (have \'x86_64\', need \'arm64\')), \'/blockscout/deps/ex_keccak/priv/native/libexkeccak.so\' (mach-o file, but is an incompatible architecture (have \'x86_64\', need \'arm64\')), \'/System/Volumes/Preboot/Cryptexes/OS/blockscout/deps/ex_keccak/priv/native/libexkeccak.so\' (no such file), \'/blockscout/deps/ex_keccak/priv/native/libexkeccak.so\' (mach-o file, but is an incompatible architecture (have \'x86_64\', need \'arm64\'))\''}}
```

**Comment by ekawibisono** [comment]
Hello @sertoriuss 
Please View Thread this https://github.com/blockscout/blockscout/issues/3593

Thanks

**Comment by sertoriuss** [comment]
Hi @ekawibisono 

this solution:
https://github.com/blockscout/blockscout/issues/3593#issuecomment-835562028

didn't help me, I got such error:
```
checking if gcc supports -std=c89 -pedantic -Wall -Wextra -Wcast-align -Wnested-externs -Wshadow -Wstrict-prototypes -Wno-unused-function -Wno-long-long -Wno-overlength-strings... yes
checking if gcc supports -fvisibility=hidden... yes
checking for __int128... yes
checking for __builtin_expect... yes
checking native compiler: gcc... ok
checking for x86_64 assembly availability... no
checking for gmp.h... yes
checking for __gmpz_init in -lgmp... yes
checking for libcrypto... yes
checking for main in -lcrypto... yes
checking for EC functions in libcrypto... no
checking jni headers... configure: WARNING: jni headers/dependencies not found. jni support disabled
none
checking whether byte ordering is bigendian... no
configure: Using static precomputation: yes
configure: Using assembly optimizations: no
configure: Using field implementation: 64bit
configure: Using bignum implementation: gmp
configure: Using scalar implementation: 64bit
configure: Using endomorphism optimizations: no
configure: Building benchmarks: yes
configure: Building for coverage analysis: no
configure: Building ECDH module: no
configure: Building ECDSA pubkey recovery module: yes
configure: Using jni: no
checking that generated files are newer than configure... done
configure: creating ./config.status
config.status: creating Makefile
config.status: creating libsecp256k1.pc
config.status: creating src/libsecp256k1-config.h
config.status: src/libsecp256k1-config.h is unchanged
config.status: executing depfiles commands
config.status: executing libtool commands
cc -I/Users/p/.asdf/installs/erlang/25.2.2/erts-13.1.4/include -I c_src/secp256k1 -I c_src/secp256k1/src -I c_src/secp256k1/include -I../libsecp256k1/src -fPIC -shared -o priv/libsecp256k1_nif.so c_src/libsecp256k1_nif.c -dynamiclib -undefined dynamic_lookup c_src/secp256k1/.libs/libsecp256k1.a -lgmp
In file included from c_src/libsecp256k1_nif.c:9:
In file included from c_src/secp256k1/src/secp256k1.c:10:
In file included from c_src/secp256k1/src/num_impl.h:14:
In file included from c_src/secp256k1/src/num.h:17:
c_src/secp256k1/src/num_gmp.h:10:10: fatal error: 'gmp.h' file not found
#include <gmp.h>
         ^~~~~~~
1 error generated.
make: *** [priv/libsecp256k1_nif.so] Error 1
==> libsecp256k1
warning: Mix compiler :make_bindings was supposed to return {:ok | :noop | :error, [diagnostic]} but it returned :error
Compiling 1 file (.erl)
src/libsecp256k1.erl:146:1: Warning: function not_loaded/1 is unused
%  146| not_loaded(Line) ->
%     | ^

Generated libsecp256k1 app
==> con_cache
Compiling 8 files (.ex)
warning: use Bitwise is deprecated. import Bitwise instead
  lib/con_cache/owner.ex:5: ConCache.Owner
```

although I have installed `gmp`
```
$ brew info gmp
==> gmp: stable 6.2.1 (bottled), HEAD
GNU multiple precision arithmetic library
https://gmplib.org/
/opt/homebrew/Cellar/gmp/6.2.1_1 (21 files, 3.2MB) *
  Poured from bottle on 2023-01-30 at 16:54:44
```
 
If have changed:
```
{:libsecp256k1, "~> 0.1.10"},
```

to
```
{:libsecp256k1, "~> 0.1.12", hex: :libsecp256k1_diode_fork}
```

and that error is gone

**Comment by ekawibisono** [comment]
Hi @sertoriuss 
Have you installed sudo apt-get install libgmp3-dev ?
I installed blockscout manually safely and had no problems.
The following are my steps when installing the manual version of Blockscout on a new VPS Server Ubuntu : 
**Step 1 :** 
Update Server OS
- sudo apt-get update
Install ASDF
before Run ASDF Please Install This For OS Ubuntu 20.04
- sudo apt-get -y install build-essential autoconf m4 libncurses5-dev libwxgtk3.0-gtk3-dev libwxgtk-webview3.0-gtk3-dev libgl1-mesa-dev libglu1-mesa-dev libpng-dev libssh-dev unixodbc-dev xsltproc fop libxml2-utils libncurses-dev openjdk-11-jdk
After Install This Install Curl And Git
- sudo apt-get install curl git -y
Now Clone ASDF in github
- git clone https://github.com/asdf-vm/asdf.git ~/.asdf
After Clone ASDF Add Source asdf in profile
- nano .profile
- add in shell ( . $HOME/.asdf/asdf.sh )
After Add Source ASDF in profile Refresh profile
- . ~/.profile
before clone install this in server
- sudo apt-get install libudev-dev zip unzip build-essential cmake -y
- sudo apt-get install git \
                       automake \
                       libtool inotify-tools \
                       libgmp-dev \
                       libgmp10 \
                       build-essential \
                       cmake -y
- sudo apt-get install inotify-tools
- sudo apt install make
- sudo apt install g++
- sudo apt-get install cargo
- curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh
- and install your postgres version. Me install blockscout manual using postgres version 10.
- Docs : https://docs.komodoplatform.com/qa/blockscout-deployment-guide.html#postgresql-setup ( I only took the postgresql installation step )

If you don't understand, you can contact me via telegram https://t.me/lialia05, I will help you as much as I can

**Comment by sertoriuss** [comment]
Hi @ekawibisono 

The problem is I'm trying to run blockscout locally and I have macOS which runs on ARM CPU. Maybe blockscout works well on Ubuntu 20.04 x86_64, but in my case it doesn't work so well. My version of why it is because of this dependency `libsecp256k1`

**Comment by ekawibisono** [comment]
> Hi @ekawibisono
> 
> The problem is I'm trying to run blockscout locally and I have macOS which runs on ARM CPU. Maybe blockscout works well on Ubuntu 20.04 x86_64, but in my case it doesn't work so well. My version of why it is because of this dependency `libsecp256k1`

Maybe you try looking for the problem on the macOS forums

**Comment by vbaranov** [comment]
We migrated from `libsecp256k1` to `ex_secp256k1`. This issue shouldn't be reproducible with `blockscout/blockscout:master` docker image. I am closing the issue. Please, let me know, if this is still taking place.
