### ISSUE TITLE
Realtime Indexer WebSocket not subscribing to newHeads

### ISSUE THREAD

**Issue by bretep** [blockscout/blockscout#6800]
Blockscout Indexer connects to the WebSocket endpoint but never subscribes to `newHeads`

### Environment

* Deployment type (Manual/Docker/Docker-compose): `Docker`
* Elixir & Erlang/OTP versions (`elixir -version`): `Elixir 1.13.1 (compiled with Erlang/OTP 24)`
* Node JS version (`node -v`): `v16.13.1`
* Operating System: Host: `Ubuntu 20.04.5 LTS` Container: `Alpine Linux v3.15`
* Blockscout Version/branch/commit: `85963ef0`
* Archive node type && version (Erigon/Geth/Nethermind/Ganache/?): `geth`
* Environment Variables:
 ``` BLOCK_TRANSFORMER=base
DATABASE_URL=postgres://${local.db_user}:${local.db_pw}@${aws_db_instance.postgres.endpoint}/blockscout
DISABLE_INDEXER=false
DISABLE_REALTIME_INDEXER=false
DISABLE_WEBAPP=true
ECTO_USE_SSL=false
ENABLE_1559_SUPPORT=true
ETHEREUM_JSONRPC_HTTP_INSECURE=true
ETHEREUM_JSONRPC_HTTP_URL=http://execution-explorer-archive.service.${var.region}.consul:80/
ETHEREUM_JSONRPC_TRACE_URL=http://execution-explorer-archive.service.${var.region}.consul:80/
ETHEREUM_JSONRPC_VARIANT=geth
ETHEREUM_JSONRPC_WS_URL=ws://execution-explorer-archive.service.${var.region}.consul:8546/
FIRST_BLOCK=15669697
INDEXER_MEMORY_LIMIT=59Gb
PORT=4000
```

### Steps to reproduce

Using the latest head (commit above) do the following:

1. install tshark and wscat
2. cd docker
3. make build
4. run
 ```
sudo tshark -i ${interface} -Y websocket.payload -E occurrence=l -T fields -e text port ${websocket_port}
```
5. in a new terminal start the container with the above environment variables
6. in another new terminal run the following:
 ```
wscat -c ws://execution-explorer-archive.service.us-east-1.consul:8546/
```
7. paste in the following in the `wscat` terminal
 ```
{"id": 1, "method": "eth-subscribe", "params": ["newHeads"]}
```

### Expected behaviour
On step 5, you should see a subscription happen within a minute or so in the `tshark` (step 4) terminal. This never happens.

### Actual behaviour

Step 5 shows that the subscription never happens. However a `tcpdump` (not documented above) does show a connection and heartbeat. In addition if the connection fails the process will core dump and stop.

### Above actions with screenshots:

I verified that subscriptions work using `wscat` from the indexer node.
I also verified that `tshark` could decode the `wscat` websocket connection.

When running `sudo tshark -i ens5 -Y websocket.payload -E occurrence=l -T fields -e text port 8546` and restarting the blockscout process, I do not see any subscription. (The below `tcpdump` shows that blockscout does create the connection.

#### wscat + tshark
<img width="1327" alt="image" src="https://user-images.githubusercontent.com/787344/215950494-e7252511-262c-40fd-ac22-fdf3b50f74d0.png">

#### blockscout + tshark
<img width="1347" alt="image" src="https://user-images.githubusercontent.com/787344/215951823-374b2c01-f87b-4874-b16b-a396eaf64f1b.png">

#### tcpdump of both HTTP and WebSocket
[Archive.zip](https://github.com/blockscout/blockscout/files/10549845/Archive.zip)

**Comment by bretep** [comment]
This issue may be causing:
- https://github.com/blockscout/blockscout/issues/6266
- https://github.com/blockscout/blockscout/issues/6750

Please see the comments:
- https://github.com/blockscout/blockscout/issues/6750#issuecomment-1410907481
- https://github.com/blockscout/blockscout/issues/6266#issuecomment-1411365892

**Comment by ekawibisono** [comment]
If you are using docker, after changing the config please do docker-compose up --build

**Comment by bretep** [comment]
> Can you do an ENV test with this ETHEREUM_JSONRPC_HTTP_URL=http://your-ip-address:9545/ << Please Change IP And Your Port Geth Ethereum ETHEREUM_JSONRPC_TRACE_URL=http://your-ip-address:9545/ << Please Change IP And Your Port Geth Ethereum ETHEREUM_JSONRPC_WS_URL=ws://your-ip-address:9455/ << Please Change IP And Your Port Geth Ethereum
> 
> I just did an install using docker-compose safe and able to run indexer blocks

How is this different then what I'm currently running?

**Comment by ekawibisono** [comment]
it's no different, maybe you can just change the Ethereum url address using the IP. i am running via secure docker no problem realtime indexer running

**Comment by bretep** [comment]
I found the breaking change and am working on a fix. If someone want's to jump in and help, that would be great!

Bisecting results.
| WS RPC | Release |
| :------: | :-------: |
|   ❌   | v5.0.0-beta e7557c4 |
|   ❌   | 2022-11-29 c46e6b7 |
|   ❌   | 2022-11-01 d932786 |
|   ❌   | 2022-10-10 faf695d |
|   ❌   | 2022-09-29 1a29b38 |
|   ⚠️   | [2022-09-21 453c8f](https://github.com/blockscout/blockscout/commit/453c8fcf6a502ab8af2241333226739a07251366) |
|   ✅   | 2022-09-19 4ca9e24 |
|   ✅   | 2022-09-15 c3e6ab7 |
|   ✅   | v4.1.8-beta 771631e |
|   ✅   | v4.1.2-beta ce94949 |

#### Breaking change
[websocket_client 1.3.0 (ae43396027) -> websocket_client 1.5.0 (8babbf30d)](https://github.com/sanmiguel/websocket_client/compare/ae43396027..8babbf30d)

**Comment by bretep** [comment]
> it's no different, maybe you can just change the Ethereum url address using the IP. i am running via secure docker no problem realtime indexer running

Yeah, if you are running the latest, it's for sure falling back to HTTP RPC. Your WS is not functioning. 100% not.

**Comment by vbaranov** [comment]
Thank you @bretep for comprehensive debug. We will rollback to websocket_client 1.3.0.

**Comment by bretep** [comment]
This isn't the ideal solution, but I'm assuming rollback to the previous client is due to the time and effort to fix the bug.

Just to be clear, what is going to happen is someone will upgrade the client again, and because of the silent fallback to HTTP RPC, it will go unnoticed for another 6-10 months.

I think rather than close out the bug as resolved, it needs to be put on a backlog for someone to pick up and resolve.

**Comment by vbaranov** [comment]
@bretep welcome to test the solution https://github.com/blockscout/blockscout/pull/6922. We would appreciate your feedback.

**Comment by bretep** [comment]
@vbaranov looks good. Nice work @Qwerty4Uiop
