### ISSUE TITLE
Canto: Successfully Verified Contract Code Not showing in the Explorer

### ISSUE THREAD

**Issue by eddietree** [blockscout/blockscout#6811]
I deployed a contract on CANTO and verified it successfully on Sourcify, however it is **not showing the code** within the EVM Explorer.

This is the contract (CANTO):
https://evm.explorer.canto.io/address/0xBaCC4d9B8776371f70e7bf2E72115D896422F9Ff/contracts#address-tabs

This is the sourcify verification with perfect match (verified):
https://sourcify.dev/#/lookup/0xBaCC4d9B8776371f70e7bf2E72115D896422F9Ff

Another odd behavior is if try to press "Verify & Publish" in the contract, then select "Via Souricfy", if you press next the website glitches back into the contract, rather than the expected screen which asks user to drop files:
https://evm.explorer.canto.io/address/0xBaCC4d9B8776371f70e7bf2E72115D896422F9Ff/contract_verifications/new
(This behavior only happens AFTER I verified the code successfully via sourcify)

### Environment
* Elixir Version: 1.13.4
* Erlang Version: 24
* BlockScout Version: 

* User Agent: `Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36`

### Steps to reproduce

Deploy my contracts, then successfully verify code, see that verified code is not shown in explorer.

### Expected Behaviour

I expect to be able to see the verified code within the explorer along with the ability to Read/Write from the contract

### Actual Behaviour

No verified code is being shown and unable to see Read/Write tabs within the contract.
![brave_QdGCY0pN3U](https://user-images.githubusercontent.com/71531/216558542-5e20a62b-6fc4-40f8-b5ce-16b94fc39ac2.png)

**Comment by vbaranov** [comment]
It looks like the Canto team didn't enable integration with Sourcify. Please ask this in Canto team support channels. Blockscout team doesn't manage this instance of explorer.
