### ISSUE TITLE
403 scout can't conn to ethreum

### ISSUE THREAD

**Issue by LonYui** [blockscout/blockscout#6812]
*Describe your issue here.*
i can do transaciton on metamask with my geth local private node. but scout receive an 403.
### Environment

* Deployment type Docker-compose
* Operating System:MacOs 12.6
* Blockscout blockscout/blockscout:${DOCKER_TAG:-latest} date:2/3
* Archive node type && version : Geth 1.8

### Steps to reproduce
```
docker-compose up --build
```
### Expected behaviour
web start
### Actual behaviour
can't not connect to ethreum with below err code
```
2023-02-03T09:16:31.010 application=ethereum_jsonrpc [error] Failed to decode Ethereum JSONRPC response:
blockscout               | 
blockscout               |   request:
blockscout               | 
blockscout               |     url: http://host.docker.internal:8545/
blockscout               | 
blockscout               |     body: [{"id":0,"jsonrpc":"2.0","method":"eth_call","params":[{"data":"0xb7ab4db5","to":null},"latest"]}]
blockscout               | 
blockscout               |   response:
blockscout               | 
blockscout               |     status code: 403
blockscout               | 
blockscout               |     body: invalid host specified
blockscout               | 

```

**Comment by vbaranov** [comment]
@LonYui which version of Docker-compose and docker do you use?

**Comment by LonYui** [comment]
I tried 2 latest  and  last ver
Versions
^5.0.0  With 5^doxker image
^4.0.0 with 4^ docker image (I change the version in composer file)

Victor Baranov ***@***.***>於 2023年2月8日 週三，上午2:41寫道：

**Comment by vbaranov** [comment]
@LonYui please send the result from terminal
```
docker --version
```

and

```
docker-compose --version
```

**Comment by LonYui** [comment]
```

Kde-MacBook-Pro:~ k$ docker --version

Docker version 20.10.22, build 3a2c30b

Kde-MacBook-Pro:~ k$ docker-compose --version

Docker Compose version v2.15.1

Kde-MacBook-Pro:~ k$
```

Victor Baranov ***@***.***> 於 2023年2月8日 週三 下午5:41寫道：

**Comment by vbaranov** [comment]
@LonYui what comand did you use to start Geth? It is running on the same machine, right?

**Comment by vbaranov** [comment]
Closing due to no author's response
