### ISSUE TITLE
Canto: <u need to improve your web>

### ISSUE THREAD

**Issue by risshuuchouhan** [blockscout/blockscout#6818]
Website is working slowly

### Environment
* Elixir Version: 1.13.4
* Erlang Version: 24
* BlockScout Version: 

* User Agent: `Mozilla/5.0 (Linux; Android 12; RMX2151) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/107.0.0.0 Mobile Safari/537.36`

### Steps to reproduce

*Tell us how to reproduce this issue. If possible, push up a branch to your fork with a regression test we can run to reproduce locally.*

### Expected Behaviour

*Tell us what should happen.*

### Actual Behaviour

*Tell us what happens instead.*

**Comment by vbaranov** [comment]
Blockscout team doesn't manage Canto instance of Blockscout explorer. Please, address this issue to Canto team directly.
