### ISSUE TITLE
Ethereum Classic: <Issue Title>

### ISSUE THREAD

**Issue by ClassicRewards** [blockscout/blockscout#6821]
Unable to interact with Ethereum Classic smart contracts. Even though I am properly connected to ETC in metamask, a message pops up saying that this instance of blockscout is for ethereum. 

### Environment
* Elixir Version: 1.13.1
* Erlang Version: 24
* BlockScout Version: v4.1.8-beta

* User Agent: `Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36`

### Steps to reproduce

*Tell us how to reproduce this issue. If possible, push up a branch to your fork with a regression test we can run to reproduce locally.*

### Expected Behaviour

*Tell us what should happen.*

### Actual Behaviour

*Tell us what happens instead.*

**Comment by vbaranov** [comment]
This issue has been resolved
