### ISSUE TITLE
Canto: Cannot Download Transaction History

### ISSUE THREAD

**Issue by popa1986** [blockscout/blockscout#6830]
I want to download my Canto Transaction history for 2022 from the evm explorer but it keeps timing out or something. Please help me retrieve my history! Thanks-

### Environment
* Elixir Version: 1.13.4
* Erlang Version: 24
* BlockScout Version: 

* User Agent: `Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/109.0`

### Steps to reproduce

Search for wallet on evm explorer, click on 'Transactions', scroll all the way down and click on 'CSV' icon, new window pops up for date range, enter date range for Calendar Year 2022, and then click on 'Download'.

### Expected Behaviour

I should get a csv file with all my transaction records.

### Actual Behaviour

A processing wheel shows up next to the 'Download' text in the button, and then nothing happens.  I re-tried several times and still did not receive a CSV file. Screenshot attached, please let me know if you need my wallet address and I'll submit it as well (*EDIT: address is in screenshot!).
![Canto_Transaction_Download_Issue](https://user-images.githubusercontent.com/124653309/217151849-f8462d93-e15a-4dcd-8055-c4a07e3b4d8e.jpg)

**Comment by vbaranov** [comment]
Please contact Canto support. This instance is not supported here. Most likely, it is misconfigured.
