### ISSUE TITLE
Canto: <Issue Title>

### ISSUE THREAD

**Issue by variousred** [blockscout/blockscout#6837]
*Describe your issue here.*

### Environment
* Elixir Version: 1.13.4
* Erlang Version: 24
* BlockScout Version: 

* User Agent: `Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36`

### Steps to reproduce

*Tell us how to reproduce this issue. If possible, push up a branch to your fork with a regression test we can run to reproduce locally.*
navigate to explorer.
### Expected Behaviour

*Tell us what should happen.*
functional website
### Actual Behaviour

*Tell us what happens instead.*
no styles no js broken website.

**Comment by vbaranov** [comment]
@variousred are you running your own explorer? Which way did you setup it?

**Comment by martianacademy** [comment]
simple download the git repository, cd to docker-compose and run docker-compose up --build

**Comment by vbaranov** [comment]
Closing due to no feedback from the author.
