### ISSUE TITLE
Blockscout can't see contract bytecode deployed from openzeppelin clone

### ISSUE THREAD

**Issue by mortum5** [blockscout/blockscout#6852]
I have local ganache instance with deployed factory contract. And factory can produce new contract via **openzeppelin Clone proxy contracts**.  But blockscount doesn`t see bytecode on clone created 

### Environment

* Deployment type (Manual/Docker/Docker-compose): Docker-compose
* Elixir & Erlang/OTP versions (`elixir -version`): Elixir 1.13.1 (compiled with Erlang/OTP 24)
* Node JS version (`node -v`): v16.13.1
* Operating System: Ubuntu 
* Blockscout Version/branch/commit: 5.0.0
* Archive node type && version (Erigon/Geth/Nethermind/Ganache/?): Ganache:latest

### Steps to reproduce

```js

import "@openzeppelin/contracts/proxy/Clones.sol";
...

contract = Clones.clone(impl);
     
```

### Expected behaviour

I've expected to see code tab on explorer for new deployed proxy

### Actual behaviour

I can't see this tab and also can't verify contract with error `exception.message=bytecode is empty `

**Comment by vbaranov** [comment]
@mortum5 probably, it will not work with Ganache, since contract creation is from internal transaction, and Ganache doesn't provide methods to retrieve them. Is this reproducible with public testnets? For instance, https://blockscout.com/gnosis/chiado/
