### ISSUE TITLE
Blockscout API - getlogs from address always shows "No logs found"

### ISSUE THREAD

**Issue by Kankalius** [blockscout/blockscout#6861]
Hi, 
We are using the current BlockScout Version on our own Server. When we try to get the log entries wirh this api call, 
it always answers with "No Logs found": 

https://blockscout.pooscan.co/api?module=logs&action=getLogs&fromBlock=1677205&toBlock=latest&address=0x80bE50Fe21F0e848E40bf78EC825d6fed08c37F3&topic0=0xd78ad95fa46c994b6551d0da85fc275fe613ce37657fb8d5e3d130840159d822

removing the address from that query and only search for the topic0 works: 

https://blockscout.pooscan.co/api?module=logs&action=getLogs&fromBlock=1677205&toBlock=latest&topic0=0xd78ad95fa46c994b6551d0da85fc275fe613ce37657fb8d5e3d130840159d822

Testing the opposite to query logs only by address without the topic also shows "No logs found" 
https://blockscout.pooscan.co/api?module=logs&action=getLogs&fromBlock=1677205&toBlock=latest&address=0x80bE50Fe21F0e848E40bf78EC825d6fed08c37F3

### Environment

* Deployment type (Manual/Docker/Docker-compose): manual
* Elixir & Erlang/OTP versions (`elixir -version`):  Elixir 1.13.4 - Erlang/OTP 24 [erts-12.3.1]
* Node JS version (`node -v`): v16.19.0
* Operating System: Ubuntu Server 20.04 LTS 64bit
* Blockscout Version/branch/commit: master, current BlockScout v5.0.0-beta
* Archive node type && version (Erigon/Geth/Nethermind/Ganache/?): polygon-edge nethermind

### Steps to reproduce

Please compare these three links i posted above. 

### Expected behaviour

The query should show us the TRansaction log

### Actual behaviour

API answers with "No logs found"

**Comment by Kankalius** [comment]
Hi everybody, 
any tips or help is highly appreciated. We'd like to use this api call on our own Telegram bot. 

Thank youvery much.

**Comment by ttblack** [comment]
我们也遇到同样问题？请问可以修复吗？

**Comment by vbaranov** [comment]
@Kankalius I cannot reproduce this issue with the latest release. Are you able to update the instance to [6.0.0](https://github.com/blockscout/blockscout/releases/tag/v6.0.0-beta) or at least to [5.4.0](https://github.com/blockscout/blockscout/releases/tag/v5.4.0-beta)?
