### ISSUE TITLE
Failed to load /root/blockscout/envs/common-smart-contract-verifier.env: open /root/blockscout/envs/common-smart-contract-verifier.env: no such file or directory

### ISSUE THREAD

**Issue by martianacademy** [blockscout/blockscout#6862]
*Describe your issue here.*

root@blockchain:~/blockscout/docker-compose# docker compose up --build
Failed to load /root/blockscout/envs/common-smart-contract-verifier.env: open /root/blockscout/envs/common-smart-contract-verifier.env: no such file or directory
root@blockchain:~/blockscout/docker-compose# 

getting this error any help?

### Environment

* Deployment type (Manual/Docker/Docker-compose):
* Elixir & Erlang/OTP versions (`elixir -version`):
* Node JS version (`node -v`):
* Operating System:
* Blockscout Version/branch/commit:
* Archive node type && version (Erigon/Geth/Nethermind/Ganache/?):

### Steps to reproduce

*Tell us how to reproduce this issue.  ❤️ if you can push up a branch to your fork with a regression test we can run to reproduce locally.*

### Expected behaviour

*Tell us what should happen.*

### Actual behaviour

*Tell us what happens instead.*

**Comment by vbaranov** [comment]
@martianacademy how did you run docker? Please post full command.

**Comment by martianacademy** [comment]
docker compose up --build

**Comment by martianacademy** [comment]
Why is this happening any idea?

**Comment by vbaranov** [comment]
@martianacademy what is the full path of folder from which you launch `docker compose up --build`?

**Comment by martianacademy** [comment]
Folder full path is /root/blockscout/docker-compose I am using ubuntu 20
lts on DigitalOcean.

**Comment by vbaranov** [comment]
What version of docker do you use?
```
docker -v
```

**Comment by martianacademy** [comment]
distroying the container and lets c if problem persists

**Comment by martianacademy** [comment]
Problem sort out. docker-compose -v was 1.25 now using docker-compose version 1.29.2, build 5becea4c.

**Comment by martianacademy** [comment]
Thanks everyone.
