### ISSUE TITLE
Unable to figure a transaction 

### ISSUE THREAD

**Issue by Rkolomiychenko** [blockscout/blockscout#6865]
I am trying to figure out what happened with a particular transaction. The tokens left my address, and I have no idea where they went. Can you assist?
![Screenshot_20230210_223321_MetaMask](https://user-images.githubusercontent.com/125083010/218172193-244295b8-a6df-4ece-85bc-18da37c709f8.jpg)

**Comment by vbaranov** [comment]
Metis instance is not supported here. Please find proper support channel.
