### ISSUE TITLE
Fatal Kernel

### ISSUE THREAD

**Issue by SerkanCAKMAK** [blockscout/blockscout#6868]
blockscout                 | {"Kernel pid terminated",application_controller,"{application_start_failure,explorer,{{shutdown,{failed_to_start_child,'Elixir.Explorer.Chain.Events.Listener',{{badmatch,{error,#{'__exception__' => true,'__struct__' => 'Elixir.Postgrex.Error',connection_id => nil,message => nil,postgres => #{code => too_many_connections,file => <<\"proc.c\">>,line => <<\"359\">>,message => <<\"sorry, too many clients already\">>,pg_code => <<\"53300\">>,routine => <<\"InitProcess\">>,severity => <<\"FATAL\">>,unknown => <<\"FATAL\">>},query => nil}}},[{'Elixir.Explorer.Chain.Events.Listener',init,1,[{file,\"lib/explorer/chain/events/listener.ex\"},{line,17}]},{gen_server,init_it,2,[{file,\"gen_server.erl\"},{line,423}]},{gen_server,init_it,6,[{file,\"gen_server.erl\"},{line,390}]},{proc_lib,init_p_do_apply,3,[{file,\"proc_lib.erl\"},{line,226}]}]}}},{'Elixir.Explorer.Application',start,[normal,[]]}}}"}
blockscout                 | Kernel pid terminated (application_controller) ({application_start_failure,explorer,{{shutdown,{failed_to_start_child,'Elixir.Explorer.Chain.Events.Listener',{{badmatch,{error,#{'__exception__' => true,'__struct__' => 'Elixir.Postgrex.Error',connection_id => nil,message => nil,postgres => #{code => too_many_connections,file => <<"proc.c">>,line => <<"359">>,message => <<"sorry, too many clients already">>,pg_code => <<"53300">>,routine => <<"InitProcess">>,severity => <<"FATAL">>,unknown => <<"FATAL">>},query => nil}}},[{'Elixir.Explorer.Chain.Events.Listener',init,1,[{file,"lib/explorer/chain/events/listener.ex"},{line,17}]},{gen_server,init_it,2,[{file,"gen_server.erl"},{line,423}]},{gen_server,init_it,6,[{file,"gen_server.erl"},{line,390}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,226}]}]}}},{'Elixir.Explorer.Application',start,[normal,[]]}}})
blockscout                 |
blockscout                 | Crash dump is being written to: erl_crash.dump...done

**Comment by vbaranov** [comment]
@SerkanCAKMAK please elaborate on how did you run Blockscout application?

**Comment by SerkanCAKMAK** [comment]
there are a lot of important points geth settings are very important
Demo www.istanbulchain.com

20 Nis 2023 Per, saat 10:28 tarihinde Victor Baranov <
***@***.***> şunu yazdı:

**Comment by vbaranov** [comment]
I need comand and parameters which you used for running Blockscout in order to be able to help.

**Comment by SerkanCAKMAK** [comment]
I solved all my problems now it works perfectly

Thank you

20 Nis 2023 Per, saat 14:22 tarihinde Victor Baranov <
***@***.***> şunu yazdı:
