### ISSUE TITLE
Energy Web Chain: <Issue Title>

### ISSUE THREAD

**Issue by Ether1516** [blockscout/blockscout#6870]
*Describe your issue here.*

I sent my EWT from KuCoin to my Ellipal hardware wallet via erc20. When tracking the transfer it appears completed in the main net in explorer energy web chain. The balance does not appear anywhere else. I am just hoping to figure out how I can either get the coins back to KuCoin or some how have them bridged to transfer to my cold storage.

### Environment
* Elixir Version: 1.13.1
* Erlang Version: 24
* BlockScout Version: v4.1.5-beta

* User Agent: `Mozilla/5.0 (iPhone; CPU iPhone OS 16_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.1 Mobile/15E148 Safari/604.1`

### Steps to reproduce

*Tell us how to reproduce this issue. If possible, push up a branch to your fork with a regression test we can run to reproduce locally.*

### Expected Behaviour

*Tell us what should happen.*

### Actual Behaviour

*Tell us what happens instead.*

**Comment by vbaranov** [comment]
Eneregy web chain is unsupported here.
