### ISSUE TITLE
postgress error. Need to worry?

### ISSUE THREAD

**Issue by martianacademy** [blockscout/blockscout#6873]
blockscout                 | 2023-02-13T08:23:11.286 application=db_connection [error] Postgrex.Protocol (#PID<0.4108.0>) failed to connect: ** (Postgrex.Error) FATAL 53300 (too_many_connections) sorry, too many clients already

*Describe your issue here.*

### Environment
* Elixir Version: 1.13.1
* Erlang Version: 24
* BlockScout Version:  v5.0.0-beta

* User Agent: `Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/110.0.0.0 Safari/537.36`

### Steps to reproduce

*Tell us how to reproduce this issue. If possible, push up a branch to your fork with a regression test we can run to reproduce locally.*

### Expected Behaviour

*Tell us what should happen.*

### Actual Behaviour

*Tell us what happens instead.*

**Comment by VestedNehal** [comment]
Same issue Occur on Windows 10, I also try to increase max_connection to 300 and pool size to 100
and then run docker compose-up --build again, but not working.

**Comment by vbaranov** [comment]
> Same issue Occur on Windows 10, I also try to increase max_connection to 300 and pool size to 100 and then run docker compose-up --build again, but not working.

Please update to [v5.3.1](https://github.com/blockscout/blockscout/releases/tag/v5.3.1-beta)
