### ISSUE TITLE
Docker-compose setup doesn't work - error on start

### ISSUE THREAD

**Issue by ondratra** [blockscout/blockscout#6875]
Blockscout doesn't start when started via docker-compose. It is possible that the problem is not exclusive to docker-compose and HardHat that I'm trying to setup, but it is my first use of Blockscout, so I don't know.

### Environment

* Deployment type (Manual/Docker/Docker-compose): Docker-compose (`docker-compose-no-build-hardhat-network.yml`)

### Steps to reproduce
Start HardHat node from your repository (`yarn hardhat node`).
You can generate project via HardHat's built-in tools - see https://github.com/NomicFoundation/hardhat.
```
git clone git@github.com:blockscout/blockscout.git
cd blockscout/docker-compose

docker-compose -f docker-compose-no-build-hardhat-network.yml up -d
```

### Expected behaviour

Blockscout should startup.

### Actual behaviour

Blockscout doesn't start. In the docker logs I can see the following error, but it is not clear if it is the cause or effect of the problem:
```
2023-02-13T10:48:16.500 [notice] Application explorer exited: Explorer.Application.start(:normal, []) returned an error: shutdown: failed to start child: Explorer.Chain.Events.Listener
    ** (EXIT) an exception was raised:
        ** (MatchError) no match of right hand side value: {:error, %Postgrex.Error{connection_id: nil, message: nil, postgres: %{code: :too_many_connections, file: "proc.c", line: "359", message: "sorry, too many clients already", pg_code: "53300", routine: "InitProcess", severity: "FATAL", unknown: "FATAL"}, query: nil}}
            (explorer 5.0.0) lib/explorer/chain/events/listener.ex:17: Explorer.Chain.Events.Listener.init/1
            (stdlib 3.17) gen_server.erl:423: :gen_server.init_it/2
            (stdlib 3.17) gen_server.erl:390: :gen_server.init_it/6
            (stdlib 3.17) proc_lib.erl:226: :proc_lib.init_p_do_apply/3
```

Here you can see the full error log created by Blockscout https://gist.github.com/ondratra/614ef0d5fb5fbd75607b1b3ba8c1bd68 and log from Blockscout's docker https://gist.github.com/ondratra/9d09466276fa21744f9ea7fb72d1f8cd.

**Comment by ondratra** [comment]
Thank you, @vbaranov, for a quick fix. Your PR did indeed fix `sorry, too many clients already` error. 

Unfortunately, docker-compose still doesn't work and crashes on different error. This is the error I see in the logs:

```
2023-02-13T13:20:14.242 [notice] Application indexer exited: Indexer.Application.start(:normal, []) returned an error: shutdown: failed to start child: Indexer.Supervisor
    ** (EXIT) shutdown: failed to start child: Indexer.Block.Catchup.Supervisor
        ** (EXIT) shutdown: failed to start child: Indexer.Block.Catchup.MissingRangesCollector
            ** (EXIT) an exception was raised:
                ** (MatchError) no match of right hand side value: {:error, :econnrefused}
                    (indexer 5.0.0) lib/indexer/block/catchup/missing_ranges_collector.ex:196: Indexer.Block.Catchup.MissingRangesCollector.fetch_max_block_number/0
                    (indexer 5.0.0) lib/indexer/block/catchup/missing_ranges_collector.ex:113: Indexer.Block.Catchup.MissingRangesCollector.get_initial_min_max/0
                    (indexer 5.0.0) lib/indexer/block/catchup/missing_ranges_collector.ex:42: Indexer.Block.Catchup.MissingRangesCollector.default_init/0
                    (indexer 5.0.0) lib/indexer/block/catchup/missing_ranges_collector.ex:24: Indexer.Block.Catchup.MissingRangesCollector.init/1
                    (stdlib 3.17) gen_server.erl:423: :gen_server.init_it/2
                    (stdlib 3.17) gen_server.erl:390: :gen_server.init_it/6
                    (stdlib 3.17) proc_lib.erl:226: :proc_lib.init_p_do_apply/3
```

Once again, here is Blockscout error log https://gist.github.com/ondratra/dc9b3497198a768df6697bdd978d07d5 and docker log https://gist.github.com/ondratra/a22a362b7f6ac6c8b890d1be570130ae.

Please, reopen the issue.

**Comment by vbaranov** [comment]
@ondratra most likely Blockscout cannot connect to the HardHat network endpoint for some reason. I will try to reproduce. Meanwhile, at what OS are you running Docker and what is the docker-compose version is used?

**Comment by ondratra** [comment]
@vbaranov I'm using Debian (sid)
```
$ uname -a
Linux mymachinename 6.0.0-6-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.0.12-1 (2022-12-09) x86_64 GNU/Linux
$ docker -v
Docker version 20.10.23+dfsg1, build 7155243
$ docker-compose -v
docker-compose version 1.29.2, build unknown
```

To start HardHat you can generate new project using the Hardhat repo or feel free to use my boilerplate:
```
git clone git@github.com:ondratra/boilerplates.git
cd boilerplates/eth_hardhat_ts
yarn 
yarn build
yarn hardhat node
```

**Comment by vbaranov** [comment]
Thank you for the details.

At the same time, hardly this resolve the issue, but we recommend using docker-compose v2:
> Docker-compose 2.x.x+

**Comment by ondratra** [comment]
> Also, there is [the note for Linux users](https://docs.blockscout.com/for-developers/information-and-settings/docker-integration-local-use-only)
>
> > Note for Linux users: Linux users who run Blockscout in docker with a local node need to run the node on http://0.0.0.0/ rather than http://127.0.0.1/

That was the issue!

While I have been aware of this in a general sense, I didn't realize there is a difference between running a HardHat node in Docker and natively. There is a message in HardHat code https://github.com/NomicFoundation/hardhat/blob/b768fcbbb01707cf45b6dee378dab7756024e40b/packages/hardhat-core/src/builtin-tasks/node.ts#L254.
```
The host to which to bind to for new connections (Defaults to 127.0.0.1 running locally, and 0.0.0.0 in Docker)
```

So, if you run the node inside of Docker, it **works** with Blockscout's docker-compose:
```
# let's assume a valid `Dockerfile` containing HardHat exists
docker build -t my-hardhat-node .
docker run my-hardhat-node


Output:
...
Started HTTP and WebSocket JSON-RPC server at http://0.0.0.0:8545/
```

On the other hand, this will **not work** with Blockscout's docker-compose:
```
yarn hardhat node


Output:
...
Started HTTP and WebSocket JSON-RPC server at http://127.0.0.1:8545/
```
---
We can close this issue now.
