### ISSUE TITLE
Why this issue?

### ISSUE THREAD

**Issue by martianacademy** [blockscout/blockscout#6876]
blockscout                 | 2023-02-13T11:01:21.095 [notice] Application explorer exited: Explorer.Application.start(:normal, []) returned an error: shutdown: failed to start child: Explorer.Chain.Events.Listener
blockscout                 |     ** (EXIT) an exception was raised:
blockscout                 |         ** (MatchError) no match of right hand side value: {:error, %Postgrex.Error{connection_id: nil, message: nil, postgres: %{code: :too_many_connections, file: "proc.c", line: "359", message: "sorry, too many clients already", pg_code: "53300", routine: "InitProcess", severity: "FATAL", unknown: "FATAL"}, query: nil}}
blockscout                 |             (explorer 5.0.0) lib/explorer/chain/events/listener.ex:17: Explorer.Chain.Events.Listener.init/1
blockscout                 |             (stdlib 3.17) gen_server.erl:423: :gen_server.init_it/2
blockscout                 |             (stdlib 3.17) gen_server.erl:390: :gen_server.init_it/6
blockscout                 |             (stdlib 3.17) proc_lib.erl:226: :proc_lib.init_p_do_apply/3
blockscout                 | 2023-02-13T11:01:21.099 application=db_connection [info] Postgrex.Protocol (#PID<0.4076.0>) disconnected: ** (DBConnection.ConnectionError) client #PID<0.4300.0> exited
postgres                   | 2023-02-13 11:01:21.142 UTC [1200] LOG:  unexpected EOF on client connection with an open transaction
postgres                   | 2023-02-13 11:01:21.154 UTC [1285] LOG:  PID 1200 in cancel request did not match any process
blockscout                 | {"Kernel pid terminated",application_controller,"{application_start_failure,explorer,{{shutdown,{failed_to_start_child,'Elixir.Explorer.Chain.Events.Listener',{{badmatch,{error,#{'__exception__' => true,'__struct__' => 'Elixir.Postgrex.Error',connection_id => nil,message => nil,postgres => #{code => too_many_connections,file => <<\"proc.c\">>,line => <<\"359\">>,message => <<\"sorry, too many clients already\">>,pg_code => <<\"53300\">>,routine => <<\"InitProcess\">>,severity => <<\"FATAL\">>,unknown => <<\"FATAL\">>},query => nil}}},[{'Elixir.Explorer.Chain.Events.Listener',init,1,[{file,\"lib/explorer/chain/events/listener.ex\"},{line,17}]},{gen_server,init_it,2,[{file,\"gen_server.erl\"},{line,423}]},{gen_server,init_it,6,[{file,\"gen_server.erl\"},{line,390}]},{proc_lib,init_p_do_apply,3,[{file,\"proc_lib.erl\"},{line,226}]}]}}},{'Elixir.Explorer.Application',start,[normal,[]]}}}"}
blockscout                 | Kernel pid terminated (application_controller) ({application_start_failure,explorer,{{shutdown,{failed_to_start_child,'Elixir.Explorer.Chain.Events.Listener',{{badmatch,{error,#{'__exception__' => true,'__struct__' => 'Elixir.Postgrex.Error',connection_id => nil,message => nil,postgres => #{code => too_many_connections,file => <<"proc.c">>,line => <<"359">>,message => <<"sorry, too many clients already">>,pg_code => <<"53300">>,routine => <<"InitProcess">>,severity => <<"FATAL">>,unknown => <<"FATAL">>},query => nil}}},[{'Elixir.Explorer.Chain.Events.Listener',init,1,[{file,"lib/explorer/chain/events/listener.ex"},{line,17}]},{gen_server,init_it,2,[{file,"gen_server.erl"},{line,423}]},{gen_server,init_it,6,[{file,"gen_server.erl"},{line,390}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,226}]}]}}},{'Elixir.Explorer.Application',start,[normal,[]]}}})

**Comment by ekawibisono** [comment]
any fix ?

**Comment by Gmlogy** [comment]
same error, any fix ?
