### ISSUE TITLE
function :http_uri.parse/2 is undefined or private, :http_uri.parse('ws://127.0.0.1:8545', [scheme_defaults: [ws: 80, wss: 443]])

### ISSUE THREAD

**Issue by phoneix1221** [blockscout/blockscout#6886]
Unable  to  start blockscout  with error on v5.1.0
function :http_uri.parse/2 is undefined or private, :http_uri.parse('ws://127.0.0.1:8545', [scheme_defaults: [ws: 80, wss: 443]])

### Environment

* Deployment type (Manual/Docker/Docker-compose):Manual
* Elixir & Erlang/OTP versions (`elixir -version`): elixir 1.14.3-otp-25 erlang 25.2.1
* Node JS version (`node -v`): 18.13.0
* Operating System: ubuntu 20.04
* Blockscout Version/branch/commit: v5.1.0 beta
* Archive node type && version (Erigon/Geth/Nethermind/Ganache/?): erigon 

### Steps to reproduce

Start blockscout 

### Expected behaviour

Should start normally 

### Actual behaviour

Blockscout starts with an error 

function :http_uri.parse/2 is undefined or private, :http_uri.parse('ws://127.0.0.1:8545', [scheme_defaults: [ws: 80, wss: 443]])

**Comment by vbaranov** [comment]
This is a bug. As a workaround you can unset `ETHEREUM_JSONRPC_WS_URL` environment variable for now.

**Comment by vbaranov** [comment]
> Websocket will not be used until this is fixed right?
> 
> > This is a bug. As a workaround you can unset `ETHEREUM_JSONRPC_WS_URL` environment variable for now.

Correct
