### ISSUE TITLE
verified-contracts page returns 404 Page not found

### ISSUE THREAD

**Issue by pmualaba** [blockscout/blockscout#6888]
*Describe your issue here.*

The **/verified-contracts** page always returns a 404 Page not found. All other pages are working fine!

<img width="483" alt="image" src="https://user-images.githubusercontent.com/1754718/218684016-fdc83de6-7947-4410-9252-aaa42076d293.png">

https://user-images.githubusercontent.com/1754718/218684123-4d03c47a-ce50-4a74-a78d-903791f2a20d.mov

### Environment

* Deployment type (Manual/Docker/Docker-compose): Docker/Kubernetes
* Elixir & Erlang/OTP versions (`elixir -version`): 1.13.1/OTP 24
<img width="543" alt="image" src="https://user-images.githubusercontent.com/1754718/218684604-1b7bdcbe-5401-421b-bba2-bb21f5e96b75.png">

* Node JS version (`node -v`):v16.13.1

* Operating System: Linux ( FROM bitwalker/alpine-elixir-phoenix:1.13 )
* Blockscout Version/branch/commit: master/commit/32ccdc5babdd46579f055a6c99ae95ef174de0c3
* Archive node type && version (Erigon/Geth/Nethermind/Ganache/?): Besu 

### Steps to reproduce

*Tell us how to reproduce this issue.  ❤️ if you can push up a branch to your fork with a regression test we can run to reproduce locally.*

Build and deploy the blockscout docker image.
Open the **Blockchain** dropdown menu at the top and select **Verified contracts** or navigate to **/verified-contracts**

### Expected behaviour

*Tell us what should happen.*

It should display the **Verified contracts**

### Actual behaviour

*Tell us what happens instead.*

It displays a **Page not found** message

**Comment by vbaranov** [comment]
This is a known issue. This page should restore by itself after some time: several minutes when the first run of DB query results will be cached. Could you please re-open that page a bit later to confirm?

**Comment by pmualaba** [comment]
> This is a known issue. This page should restore by itself after some time: several minutes when the first run of DB query results will be cached. Could you please re-open that page a bit later to confirm?

Hmmm, even after 48h still Page not found...

**Comment by vbaranov** [comment]
Still page not found? If yes, do you have any insights on the number of addresses/contracts in your DB?

**Comment by vbaranov** [comment]
I am closing this issue, because no response. Please let me know, if the issue still present.
