### ISSUE TITLE
Unable to launch Blockscout

### ISSUE THREAD

**Issue by Bharathcoorg** [blockscout/blockscout#6914]
I am repeatedly getting this error after using git pull. Tried re-install OS, Different RPCs even local-node. I tried different VPS too. But its the same.
There is no process running, even in new VPS its showing unable to start child

mix phx.server or iex -S mix phx.server gives same error
Error

** (Mix) Could not start application indexer: Indexer.Application.start(:normal, []) returned an error: shutdown: failed to start child: Indexer.Supervisor
    ** (EXIT) shutdown: failed to start child: Indexer.Block.Realtime.Supervisor
        ** (EXIT) shutdown: failed to start child: EthereumJSONRPC.WebSocket.WebSocketClient
            ** (EXIT) an exception was raised:
                ** (UndefinedFunctionError) function :http_uri.parse/2 is undefined or private
                    (inets 8.2.1) :http_uri.parse('ws://localhost:9944', [scheme_defaults: [ws: 80, wss: 443]])
                    (websocket_client 1.3.0) /root/blockscout/deps/websocket_client/src/websocket_client.erl:139: :websocket_client.start_link/5
                    (stdlib 4.2) supervisor.erl:414: :supervisor.do_start_child_i/3
                    (stdlib 4.2) supervisor.erl:400: :supervisor.do_start_child/2
                    (stdlib 4.2) supervisor.erl:384: anonymous fn/3 in :supervisor.start_children/2
                    (stdlib 4.2) supervisor.erl:1250: :supervisor.children_map/4
                    (stdlib 4.2) supervisor.erl:350: :supervisor.init_children/2
                    (stdlib 4.2) gen_server.erl:851: :gen_server.init_it/2

**Comment by vbaranov** [comment]
@Bharathcoorg this is known bug. Please unset `ETHEREUM_JSONRPC_WS_URL`.

**Comment by Bharathcoorg** [comment]
Solved thank you....
