### ISSUE TITLE
Skin 1.0 Nubank

### ISSUE THREAD

**Issue by vbaranov** [blockscout/blockscout#6915]
Based on the Optimism background colors.

https://nubank.com.br/en/
https://dribbble.com/tags/nubank

Light theme:

**Header**
#9436E1 - menu icon & line hover
#F6ECFE - hover point background
#333 - text

![Image](https://user-images.githubusercontent.com/103045386/219381723-9fcad345-6015-4916-a648-816fca8e5bb1.png)

**Stats**
#D2A5FF - info icons + chart legend label + text

![Image](https://user-images.githubusercontent.com/103045386/219383866-b7ff9aac-abca-44d7-b55e-2be8da8c32ef.png)

Please change graph line  /* gradient */
background: linear-gradient(0.52deg, #D2A5FF -35.19%, #9436E1 139.35%);

![Image](https://user-images.githubusercontent.com/103045386/219383274-9ccc4df8-61d2-401f-b3bc-e5f5e75d0497.png)

![Image](https://user-images.githubusercontent.com/103045386/219384016-4e456d1d-91e7-4171-898e-e3d7a640a8f8.png)

**Blocks**
#9436E1 - border-left, buttons (+ hover effect)

![Image](https://user-images.githubusercontent.com/103045386/219385820-74c72867-0af1-450e-8f08-6f608df82894.png)

**Transactions**
#9436E1 - button (+ hover effect)

![Image](https://user-images.githubusercontent.com/103045386/219386114-8916f02a-9439-4ad1-8a54-810a54667b6c.png)

**Bottom**
#D2A5FF - bullets + social icons
#fff - logo+ links 

![Image](https://user-images.githubusercontent.com/103045386/219390785-639d743a-2fed-4e78-984d-7da494d067de.png)

![Image](https://user-images.githubusercontent.com/103045386/219391868-df156d84-0630-4b2e-bc23-25449d68d4fc.png)

Dark theme:

**Header**
White logo
#9436E1 - menu icon & line hover + hover point background
#fff - text

![Image](https://user-images.githubusercontent.com/103045386/219394634-684726b2-c19f-462a-aacc-f0bfdaa569e9.png)

**Stats**
Like on the light theme

![Image](https://user-images.githubusercontent.com/103045386/219399698-21eba5ef-f211-46bd-aded-1c37c1a4217b.png)

**Blocks**
#9436E1 - border-left, buttons (+ hover effect)
#fff - button text

**Transactions**
#9436E1 - button (+ hover effect)
#fff - button text

![Image](https://user-images.githubusercontent.com/103045386/219399030-c148b0d1-231b-4e2b-bfb2-1aaba386d129.png)

**Bottom**
Like on the light theme

![Image](https://user-images.githubusercontent.com/103045386/219399273-77c874bf-ea39-4b0c-87ae-d3e009585998.png)

**Comment by tgladilina** [comment]
Logo 

![Image](https://user-images.githubusercontent.com/103045386/220394678-9cd60b2f-c410-4ea6-a2c1-12e76ef92cca.png)

![Image](https://user-images.githubusercontent.com/103045386/220394838-df9c9e55-913c-44f7-9e3f-deea4ce0d022.png)

**Comment by vbaranov** [comment]
Applied at https://supernets-testnet.blockscout.com/
