### ISSUE TITLE
Address Coin balances history issue

### ISSUE THREAD

**Issue by 0xtzData** [blockscout/blockscout#6916]
In `UI 2.0` Coin balances doesn't update even when Ether transfers are present.
SPOA balance is empty too.

![Image](https://user-images.githubusercontent.com/108135703/219422744-a0e484eb-608d-4aa1-896d-3e1f53dc8bc0.png)

![Image](https://user-images.githubusercontent.com/108135703/219421967-27c53988-9c7e-4ed1-a1c5-3e966a8e6182.png)

![Image](https://user-images.githubusercontent.com/108135703/219422048-5d20393d-e9b9-45a7-944b-5a9ce41d6a39.png)

**Comment by vbaranov** [comment]
Coin balance history table fixed by `ETHEREUM_JSONRPC_DISABLE_ARCHIVE_BALANCES=true`. Should be unset or set to `false`.
