### ISSUE TITLE
Compiler version not visible

### ISSUE THREAD

**Issue by Bharathcoorg** [blockscout/blockscout#6918]
![blockscou](https://user-images.githubusercontent.com/40591495/219470908-41f7f8bd-d82e-4172-834f-7e704948339c.PNG)

I got very strange issue compiler version not visible in Smart contract verification form

**Comment by vbaranov** [comment]
How did you run Blockscout? Did you start smart-contract verifier microservice as well and connect it to Blockscout?

**Comment by Bharathcoorg** [comment]
Yes smart-contract verifier microservice is running

**Comment by vbaranov** [comment]
At which port? Is the same port used in `RUST_VERIFICATION_SERVICE_URL` env variable? You can test your verifier endpoint by curling this path `/api/v2/verifier/solidity/versions` - it should return compiler versions.

**Comment by Bharathcoorg** [comment]
Something wrong with VPS. Blockscout is only visible via url, direct ip:port access not working

**Comment by Bharathcoorg** [comment]
I tried everything its not working

**Comment by Bharathcoorg** [comment]
http://174.138.178.227:4000/api/v2/verifier/solidity/versions

See the output

**Comment by vbaranov** [comment]
http://174.138.178.227:4000 is explorer URL. This path `/api/v2/verifier/solidity/versions` is from smart-contract verifier service. Did you run smart-contract verifier service?

**Comment by Bharathcoorg** [comment]
yes

**Comment by Bharathcoorg** [comment]
http://174.138.178.227:8043/api/v2/verifier/solidity/versions

this?

**Comment by vbaranov** [comment]
Does this URL return response?

**Comment by Bharathcoorg** [comment]
No 404 error

**Comment by vbaranov** [comment]
How did you run smart-contract verifier service? Please send env variables and command to run.

**Comment by vbaranov** [comment]
In different Blocksout versions exposed port of the service is different.

**Comment by Bharathcoorg** [comment]
![smart contract](https://user-images.githubusercontent.com/40591495/219851994-86d9109b-56b9-4849-902a-cb68a4a64a86.PNG)
COIN=5IRE
NETWORK=Thunder
SUBNETWORK=Testnet
ETHEREUM_JSONRPC_VARIANT=parity
SECRET_KEY_BASE=JfBYTmt3uqmZsX/mia8hmoOoQdVM0KnLWA+qtnvfK8uUpFOCXrX9CEepjT1YuABe
DATABASE_URL=postgresql://blockscout1:P4ssw0rd@localhost:5432/blockscout1?ssl=false
PORT=4000
ETHEREUM_JSONRPC_HTTP_URL=https://rpc-testnet.5ire.network
ETHEREUM_JSONRPC_TRACE_URL=https://rpc-testnet.5ire.network
MAIN_DENOM=5IRE
CHAIN_ID=997
FIRST_BLOCK=1
TRACE_FIRST_BLOCK=1
HISTORY_FETCH_INTERVAL=2
TXS_STATS_DAYS_TO_COMPILE_AT_INIT=365
COIN_NAME=5IRE
EXCHANGE_RATES_SOURCE=coin_gecko
EXCHANGE_RATES_COINGECKO_COIN_ID=5ire
SHOW_ADDRESS_MARKETCAP_PERCENTAGE=true
GAS_PRICE=true
JSON_RPC=https://rpc-testnet.5ire.network
INDEXER_MEMORY_LIMIT=6Gb
SHOW_TESTNET_LABEL=true
TESTNET_LABEL_TEXT=Testnet
SHOW_PRICE_CHART=false
ENABLE_TXS_STATS=true
export ENABLE_RUST_VERIFICATION_SERVICE=true
export RUST_VERIFICATION_SERVICE_URL=http://0.0.0.0:8043/

**Comment by Bharathcoorg** [comment]
i used cargo method

**Comment by vbaranov** [comment]
Are you running the latest version of Blockscout and smart-contract verifier service? Could you check? The interface of smart-contract verifier has been recently changed.

**Comment by Bharathcoorg** [comment]
Yes i used latest code from yesterday

**Comment by Bharathcoorg** [comment]
Can I send server credentials via Email?

**Comment by vbaranov** [comment]
Then this is the problem with service host/port visibility. This URL http://host:8043/api/v2/verifier/solidity/versions MUST return data with the latest smart-contract verifier service. Try use 127.0.0.1 instead 0.0.0.0.

**Comment by Bharathcoorg** [comment]
Tried localhost and 127.0.0.1  both not working

**Comment by Bharathcoorg** [comment]
I emailed server login details please help me

**Comment by Bharathcoorg** [comment]
There was some error in ENV i think this issue solved now

**Comment by Bharathcoorg** [comment]
Its still not working even after solving ENV issues

**Comment by Bharathcoorg** [comment]
It's running and showing listening in Aapanel. I have one more Explorer setup in that also 
http://host:8043/api/v2/verifier/solidity/versions not visible but it's showing Compiler version in Frontend

**Comment by Bharathcoorg** [comment]
![netstat](https://user-images.githubusercontent.com/40591495/219879754-8e6bd6ee-d632-489c-9af9-79afd80bfcd6.PNG)

**Comment by Bharathcoorg** [comment]
Its running correctly right?

**Comment by Bharathcoorg** [comment]
Still i cant solve this issue. i don't know if its host issue.

**Comment by Bharathcoorg** [comment]
I think this is a script issue. I used my old explorer script that's not updated from last 6 months. Its working in that.
