### ISSUE TITLE
check why sometime token max total supply is zero

### ISSUE THREAD

**Issue by tom2drum** [blockscout/blockscout#6920]
[Blockscout](https://eth-goerli.blockscout.com/token/0xA79F16C012909E91C87Ae36B2b6B56D7AE567043) 
[Etherscan](https://goerli.etherscan.io/token/0xA79F16C012909E91C87Ae36B2b6B56D7AE567043)

**Comment by nikitosing** [comment]
should be fixed via https://github.com/blockscout/blockscout/pull/6933

**Comment by tom2drum** [comment]
for the token in the description it is still `0`. is it really fixed? @nikitosing
