### ISSUE TITLE
Node version is outdated.

### ISSUE THREAD

**Issue by martianacademy** [blockscout/blockscout#6924]
getting this warning while building docker image:

npm WARN EBADENGINE   required: { node: '18.x', npm: '8.x' },                                                                                      
 => => # npm WARN EBADENGINE   current: { node: 'v16.13.1', npm: '8.3.0' }   

Is there anything, need to worry about?

*Describe your issue here.*

### Environment

* Deployment type (Manual/Docker/Docker-compose):
* Elixir & Erlang/OTP versions (`elixir -version`):
* Node JS version (`node -v`):
* Operating System:
* Blockscout Version/branch/commit:
* Archive node type && version (Erigon/Geth/Nethermind/Ganache/?):

### Steps to reproduce

*Tell us how to reproduce this issue.  ❤️ if you can push up a branch to your fork with a regression test we can run to reproduce locally.*

### Expected behaviour

*Tell us what should happen.*

### Actual behaviour

*Tell us what happens instead.*

**Comment by vbaranov** [comment]
> Is there anything, need to worry about?

No worries. You can ignore this warning.
