### ISSUE TITLE
too many blocks missed

### ISSUE THREAD

**Issue by Jaycelv** [blockscout/blockscout#6935]
![image](https://user-images.githubusercontent.com/99306545/219994727-b47a65ca-5a03-469d-af4c-fb6fe7a81fcd.png)

I deployed blockscout on a layer2, and the block time is very short,  there are lots of missed block, and some of them will never be saved in database, how to resolve it ?

**Comment by vbaranov** [comment]
They should be ultimately fetched by catchup fetcher.

**Comment by vbaranov** [comment]
@Jaycelv did explorer processed the queue?

**Comment by vbaranov** [comment]
I am closing this. Please re-open, if the issue still persists.
