### ISSUE TITLE
Internal transactions cannot be indexed sometime

### ISSUE THREAD

**Issue by ericlee42** [blockscout/blockscout#6938]
*Describe your issue here.*

### Environment

* Deployment type (Manual/Docker/Docker-compose): docker
* Elixir & Erlang/OTP versions (`elixir -version`): latest
* Node JS version (`node -v`): latest
* Operating System: Ubuntu
* Blockscout Version/branch/commit: 5.1.0
* Archive node type && version (Erigon/Geth/Nethermind/Ganache/?): Geth

### Steps to reproduce

```console
$ select * from missing_block_ranges;
 id | from_number | to_number
----+-------------+-----------
(0 rows)


$ select * from pending_block_operations;
 block_hash | inserted_at | updated_at | block_number
------------+-------------+------------+--------------
(0 rows)

$ select count(*) from blocks as bk join internal_transactions as it on bk.hash=it.block_hash where bk.number=4855859;
 count
-------
     0
(1 row)

$ select count(*) from blocks as bk join internal_transactions as it on bk.hash=it.block_hash where bk.number=4855860;
 count
-------
    12
(1 row)


$ insert into missing_block_ranges (from_number, to_number) values (4855859,4855859);
INSERT 0 1

$  select count(*) from blocks as bk join internal_transactions as it on bk.hash=it.block_hash where bk.number=4855859;
-[ RECORD 1 ]
count | 8
```

If I add a row to the `missing_block_ranges table`, then the data is re-indexed again. it is very strange.

### Expected behaviour

*Tell us what should happen.*

### Actual behaviour

*Tell us what happens instead.*

**Comment by Qwerty5Uiop** [comment]
Hi @ericlee42, could you show what env variables you have set?

**Comment by ericlee42** [comment]
I guess it's similar to #6933

**Comment by vbaranov** [comment]
@ericlee42 what are your expectations?

**Comment by ericlee42** [comment]
many transactions don't have internal transactions data on my instance, even if no rows in pending_block_operations and missing_block_ranges tables.

I think I have already expressed myself clearly

**Comment by vbaranov** [comment]
> I think I have already expressed myself clearly

@ericlee42 Not really, some details are missing in your description in order to be able to help with your issue.

First of all, not all transactions should have internal transactions (Blockscout doesn't store 1st trace, if there were no internal calls). Can you provide evidence, that transaction should have internal transactions? Any public URL to transaction and RPC?

Do you see any errors in the logs related to internal transactions?
Which version of Geth are you using?
What exact version of Blocskcout is used right now?

If you invalidate block with $block_number (`UPDATE blocks SET consensus=false WHERE number=$block_number;`), do the internal transactions appear on transactions in the block with that number?

**Comment by vbaranov** [comment]
> I don't think you've taken a closer look at my issue.

I did - I saw these queries before. And I don't see anything strange with them. This is whhy I am asking what are your expectations here. 
What I see from these queires:
- there were no internal transactions for block 4855859
- You added that block (with number 4855859) to missing ranges
- Internal transactions appeared for the that block with number 4855859

**Comment by vbaranov** [comment]
@ericlee42 Seems, I got what is your problem. Please try update from master branch. Missing ranges collector currently works constantly: when the queue has been processed, it returns to the beginning. So, https://github.com/blockscout/blockscout/pull/7305 should fix your issue - it is available in master branch.

**Comment by ericlee42** [comment]
Noted, I will try it out later

**Comment by vbaranov** [comment]
What is the result of `select * from internal_transactions where transaction_hash='\xab052720e65f5e44a694827024dc768297fd0ff7e415f0e9fa12dea0123d7a52`';

And result of request from archive node, which Blockscout is connected to

```
curl -sL \
  -H "Content-Type:application/json;charset=utf-8" \
  -d "{
      \"jsonrpc\": \"2.0\",
      \"id\": 1,
      \"method\": \"debug_traceTransaction\",
      \"params\": [
          \"0xab052720e65f5e44a694827024dc768297fd0ff7e415f0e9fa12dea0123d7a52\",
          { \"tracer\": \"callTracer\"}
      ]
  }" \
```
?

**Comment by ericlee42** [comment]
<img width="889" alt="image" src="https://user-images.githubusercontent.com/92196970/235014562-12dfb75c-36a0-4c2c-8fc8-2fc59c682de1.png">


<img width="894" alt="image" src="https://user-images.githubusercontent.com/92196970/235014707-c1dd894e-524e-4d8f-82d5-6a03a56dc93f.png">

**Comment by ericlee42** [comment]
it seems to be because I set INDEXER_ DISABLE_ EMPTY_ BLOCK_ SANITIZER to true.

**Comment by vbaranov** [comment]
Empty blocks sanitizer does help when the block with no transactions in Blockscout DB - it checks, if block has transactions on the node, and if yes it marks block to re-fetch together with internal transactions. It worth to keep it enabled. But, in your case transaction already existed in the DB - not sure how it helps in this case.

If it was a bug in the previous versions of Blockscout and you have a range of blocks where you expect internal transactions to be present, the manual way to fix that is to invalidate that range of blocks. So, if you have block numbers, you can do something like this:
```
UPDATE blocks SET consensus=false WHERE number in (...);
```

Those blocks will dissappear in UI, but will return once missing block ranges collector will process them.
