### ISSUE TITLE
Update ETC instances

### ISSUE THREAD

**Issue by diega** [blockscout/blockscout#6992]
The ETC instances have been updated almost 5 months ago and we detected that some glitches could be avoided by using newer versions.

These are the branches that we have deployed using **Docker**
* **Mainnet**: [blockscout/production-classic-stg](https://github.com/blockscout/blockscout/tree/production-classic-stg)
* **Mordor**: [blockscout/production-etc-mordor-stg](https://github.com/blockscout/blockscout/tree/production-etc-mordor-stg)
* **Kotti**: [blockscout/production-etc-kotti-stg](https://github.com/blockscout/blockscout/tree/production-etc-kotti-stg)

Would be possible to rebase our branches on top of the latest release? Also, is there any special treatment or step needed for switching from version 4.x to 5.x?

Bellow you can find our running instances:
* https://blockscout.com/etc/mainnet/
* https://blockscout.com/etc/mordor/
* https://blockscout.com/etc/kotti/

Thanks a lot

**Comment by vbaranov** [comment]
ETC Mainnet and Mordor instances have been updated with the new UI
