### ISSUE TITLE
Pending transactions fetcher using eth_newPendingTransactionFilter ?

### ISSUE THREAD

**Issue by lucgerrits** [blockscout/blockscout#6995]
Is it possible to setup blockscout to get pending transactions where the RPC endpoint has only these methods:
```
eth_accounts
eth_blockNumber
eth_call
eth_chainId
eth_coinbase
eth_estimateGas
eth_feeHistory
eth_gasPrice
eth_getBalance
eth_getBlockByHash
eth_getBlockByNumber
eth_getBlockTransactionCountByHash
eth_getBlockTransactionCountByNumber
eth_getCode
eth_getFilterChanges
eth_getFilterLogs
eth_getLogs
eth_getStorageAt
eth_getTransactionByBlockHashAndIndex
eth_getTransactionByBlockNumberAndIndex
eth_getTransactionByHash
eth_getTransactionCount
eth_getTransactionReceipt
eth_getUncleByBlockHashAndIndex
eth_getUncleByBlockNumberAndIndex
eth_getUncleCountByBlockHash
eth_getUncleCountByBlockNumber
eth_getWork
eth_hashrate
eth_maxPriorityFeePerGas
eth_mining
eth_newBlockFilter
eth_newFilter
eth_newPendingTransactionFilter
eth_protocolVersion
eth_sendRawTransaction
eth_sendTransaction
eth_submitHashrate
eth_submitWork
eth_subscribe
eth_syncing
eth_uninstallFilter
eth_unsubscribe
```

**Comment by vbaranov** [comment]
Currently, only`parity_pendingTransactions` or `txpool_content` are supported.

For the reference, https://docs.blockscout.com/for-developers/information-and-settings/node-tracing-json-rpc-requirements#fetching-pending-transactions

Curious, what type of client is used, which supports only this set of endpoints?

**Comment by lucgerrits** [comment]
Ok.
It's the default set of endpoints is when using Frontier (Ethereum compatibility layer for Substrate blockchains) https://github.com/paritytech/frontier

**Comment by lucgerrits** [comment]
@vbaranov When I've the time I'll try to add `parity_pendingTransactions` following the suggestion here: https://github.com/paritytech/frontier/issues/1035
