### ISSUE TITLE
blockscout indexer always stop at sometime

### ISSUE THREAD

**Issue by LuxesOwen** [blockscout/blockscout#7006]
I upgrade our blockscout to lastest version from master branch recently.Then I found the indexer always stop at sometime,I must restart blockscout to make it return to normal.

I deduced from the logs that it was an issue with the indexer,I found my indexer.log had stopped logging from that time.The behavior in webpage is blocks sync stopped.

The following is last logs once indexer stopped,When I found out, it had stop logging for 3 hours.
```
2023-03-01T08:27:13.884 application=indexer fetcher=block_catchup missing_block_count=0 shrunk=false [info] Index already caught up.
2023-03-01T08:27:13.884 application=indexer fetcher=block_catchup [info] Checking if index needs to catch up in 25000ms.
2023-03-01T08:27:21.508 application=indexer fetcher=empty_blocks_to_refetch [info] Start sanitizing of empty blocks. Batch size is 100
2023-03-01T08:27:21.529 application=indexer fetcher=empty_blocks_to_refetch [info] Batch of empty blocks is sanitized
2023-03-01T08:27:23.090 application=indexer fetcher=block_catchup missing_block_count=0 shrunk=false [info] Index already caught up.
2023-03-01T08:27:23.090 application=indexer fetcher=block_catchup [info] Checking if index needs to catch up in 5000ms.
2023-03-01T08:27:23.148 application=indexer fetcher=block_catchup missing_block_count=0 shrunk=false [info] Index already caught up.
2023-03-01T08:27:23.148 application=indexer fetcher=block_catchup [info] Checking if index needs to catch up in 5000ms.
2023-03-01T08:27:23.208 application=indexer fetcher=block_catchup missing_block_count=0 shrunk=false [info] Index already caught up.
2023-03-01T08:27:23.208 application=indexer fetcher=block_catchup [info] Checking if index needs to catch up in 5000ms.
```
In addition, I think it may have some connection with transactions occurred on the chain, such as token transfer.

And following are my env-variables about indexer,Many variables are the default settings used, which variables might be useful for this issue? please tell me to have a try.
```
export INDEXER_DISABLE_PENDING_TRANSACTIONS_FETCHER="true"
export INDEXER_DISABLE_BLOCK_REWARD_FETCHER="true"
export INDEXER_DISABLE_INTERNAL_TRANSACTIONS_FETCHER="false"
export DISABLE_EXCHANGE_RATES="true"
export FETCH_REWARDS_WAY="manual"
export INDEXER_DISABLE_ADDRESS_COIN_BALANCE_FETCHER="true"
export INDEXER_INTERNAL_TRANSACTIONS_TRACER_TYPE="js"
```

**Comment by LuxesOwen** [comment]
hi @vbaranov ,I updated to this commit yesterday:58d0e56eca56c179bcf0913ffb6619c0d4940f63.
I think this issue have existed for a long time.I encounter this issue many times before v5.0. 
After I update program I restart my blockscout.I open my blockscout webpage now then found the indexer had stopped again.you can see the last log time matches the last block sync time.
<img width="542" alt="image" src="https://user-images.githubusercontent.com/66360114/222625272-b99964c0-6066-47d5-aba2-5b41fd141eb4.png">
<img width="1366" alt="image" src="https://user-images.githubusercontent.com/66360114/222625497-3d618a0c-f1b2-4eeb-b1c9-d9b7a18e3163.png">

I restart my blockscout now,then it return to normal again.

**Comment by vbaranov** [comment]
Logs, which you attached initially, don't reveal the issue. And we are unable to reproduce this in our environment. Can you attach full logs? are any errors in the error.log? Can you check what does RPC node return in the request to `eth_blockNumber`, when Blockscout "stops" indexing? I mean is JSON RPC endpoint, which Blockscout connected to, does return new block numbers and Blockscout doesn't show them? Or maybe RPC endpoint doesnt return new blocks?

**Comment by LuxesOwen** [comment]
When this issue happened there was no errors in error.log,everytime the indexer.log was stopped logging like that,and I havn't found errors in any log files.
The RPC node that connection with blockscout is running on the same server as blockscout.I think this RPC node always running well,so that I could resumed blockscout via only restart blockscout service.
I'm sure that the local RPC node had got newest blocks everytime,How to check whether it has returns to blockscout exactly？

**Comment by LuxesOwen** [comment]
Hi @vbaranov ,I found some errors in error.log lastnight.Could this be the cause of this issue? 
I didn't pay attention to them before, because they were not the occured at the time of the indexer stop.

```
2023-03-03T16:50:46.459 [error] Task #PID<0.24708.6> started from Indexer.Block.Realtime.Fetcher terminating
** (DBConnection.ConnectionError) connection not available and request was dropped from queue after 122ms. This means requests are coming in and your connection pool cannot serve them fast enough. You can address this by:

  1. Ensuring your database is available and that you can connect to it
  2. Tracking down slow queries and making sure they are running fast enough
  3. Increasing the pool_size (although this increases resource consumption)
  4. Allowing requests to wait longer by increasing :queue_target and :queue_interval

See DBConnection.start_link/2 for more information

    (db_connection 2.4.3) lib/db_connection.ex:953: DBConnection.transaction/3
    (ecto 3.9.4) lib/ecto/repo/transaction.ex:18: Ecto.Repo.Transaction.transaction/4
    (stdlib 3.17.1) timer.erl:197: :timer.tc/3
    (explorer 5.1.1) lib/explorer/repo.ex:37: anonymous fn/2 in Explorer.Repo.logged_transaction/2
    (explorer 5.1.1) lib/explorer/logger.ex:14: Explorer.Logger.metadata/2
    (explorer 5.1.1) lib/explorer/chain/import.ex:334: anonymous fn/3 in Explorer.Chain.Import.import_transactions/2
    (elixir 1.13.4) lib/enum.ex:4475: Enumerable.List.reduce/3
    (elixir 1.13.4) lib/enum.ex:2442: Enum.reduce_while/3
Function: &:erlang.apply/2
    Args: [#Function<13.124376668/1 in Indexer.Block.Realtime.Fetcher.start_fetch_and_import/4>, [6604626]]
```

**Comment by LuxesOwen** [comment]
I decided to change the POOL_SIZE variable value to 200.I have not set it before.I will follow up on the effect.

**Comment by LuxesOwen** [comment]
Hi @vbaranov ,After I modified POOL_SIZE variable value to 200,The indexer seems could keep alive longer.But another case arises,The blocks of page moving slow down,the last block displayed 2~3 minutes ago,Normally it should be displayed as a few seconds ago,but it's keep moving.Should this be a performance issue?

**Comment by vbaranov** [comment]
Most probably, then the issue with the lack of computing resources on the DB. Could you check memory and CPU consumption on it?

**Comment by NicoDFS** [comment]
I am facing the exact same issue, running 5.1.1 upgraded from 4.1.8 on a dedicated server with 32gb RAM and Intel i5. 

Memory and CPU usage dont seem to be he issue. 

RAM:
` free -g
              total        used        free      shared  buff/cache   available
Mem:             31           2          12           0          15          27
Swap:             7           0           7
`
CPU: 
`1739349 dev       20   0 2783484 263072 120140 S  10.3   0.8   1:54.38 beam.smp
1466462 dev       20   0   10.8g   1.2g  40756 S   1.3   3.8 483:30.30 java
1740130 postgres  20   0  287580  12436   9700 S   0.7   0.0   0:00.02 postgres
1740236 dev       20   0   12392   4492   3196 R   0.7   0.0   0:00.25 top
`

**Comment by LuxesOwen** [comment]
Hi @vbaranov ,I found some sql execute slow. There is the top sql from our aws rds monitor panel.
<img width="1800" alt="image" src="https://user-images.githubusercontent.com/66360114/225545354-49b1a20e-e7de-4c63-a86c-3d447cff2529.png">

It looks like cause of something about "fetched coin balance". Should I modify some env variables about "fetched coin balance"? How to do it?
Besides,our test env running based on the same env variables,it rarely happens.

**Comment by LuxesOwen** [comment]
I modified two env variables(INDEXER_COIN_BALANCES_BATCH_SIZE=200,INDEXER_COIN_BALANCES_CONCURRENCY=2),then got following error
```
2023-03-17T08:32:45.104 fetcher=coin_balance count=200 [error] Task #PID<0.3589.0> started from Indexer.Fetcher.CoinBalance terminating
** (FunctionClauseError) no function clause matching in EthereumJSONRPC.HTTP.standardize_response/1
    (ethereum_jsonrpc 5.1.1) lib/ethereum_jsonrpc/http.ex:145: EthereumJSONRPC.HTTP.standardize_response(%{"error" => %{"code" => -32600, "message" => "Batch request length too long"}, "jsonrpc" => "2.0"})
    (elixir 1.13.4) lib/enum.ex:1593: Enum."-map/2-lists^map/1-0-"/2
    (ethereum_jsonrpc 5.1.1) lib/ethereum_jsonrpc/http.ex:44: EthereumJSONRPC.HTTP.chunked_json_rpc/3
    (ethereum_jsonrpc 5.1.1) lib/ethereum_jsonrpc/request_coordinator.ex:86: anonymous fn/3 in EthereumJSONRPC.RequestCoordinator.perform/4
    (ethereum_jsonrpc 5.1.1) lib/ethereum_jsonrpc/request_coordinator.ex:106: EthereumJSONRPC.RequestCoordinator.trace_request/2
    (ethereum_jsonrpc 5.1.1) lib/ethereum_jsonrpc.ex:203: EthereumJSONRPC.fetch_balances/2
    (indexer 5.1.1) lib/indexer/fetcher/coin_balance.ex:92: Indexer.Fetcher.CoinBalance.run/2
    (elixir 1.13.4) lib/task/supervised.ex:89: Task.Supervised.invoke_mfa/2
Function: &Indexer.BufferedTask.log_run/1
    Args: [%{batch: [{<<0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0>>, 2463466}, {<<0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0>>, 2463467}, {<<0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0>>, 2463468}, {<<0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0>>, 2463469}, {<<0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0>>, 2463470}, {<<0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0>>, 2463471}, {<<0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0>>, 2463472}, {<<0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0>>, 2463473}, {<<0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0>>, 2463474}, {<<0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0>>, 2463475}, {<<0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0>>, 2463286}, {<<0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0>>, 2463287}, {<<0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0>>, 2463288}, {<<0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0>>, 2463289}, {<<0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0>>, 2463290}, {<<0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0>>, 2463291}, {<<0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0>>, 2463292}, {<<0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0>>, 2463293}, {<<0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0>>, 2463294}, {<<0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0>>, 2463295}, {<<0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0>>, 2461366}, {<<0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0>>, 2461367}, {<<0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0>>, 2461368}, {<<0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0>>, 2461369}, {<<0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0>>, 2461370}, {<<0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0>>, 2461371}, {<<0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0>>, 2461372}, {<<0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...>>, 2461373}, {<<0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...>>, 2461374}, {<<0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...>>, 2461375}, {<<0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...>>, 2461076}, {<<0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...>>, 2461077}, {<<0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...>>, 2461078}, {<<0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...>>, 2461079}, {<<0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...>>, 2461080}, {<<0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...>>, 2461081}, {<<0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...>>, 2461082}, {<<0, 0, 0, 0, 0, 0, 0, 0, 0, ...>>, 2461083}, {<<0, 0, 0, 0, 0, 0, 0, 0, ...>>, 2461084}, {<<0, 0, 0, 0, 0, 0, 0, ...>>, 2461085}, {<<0, 0, 0, 0, 0, 0, ...>>, 2460706}, {<<0, 0, 0, 0, 0, ...>>, 2460707}, {<<0, 0, 0, 0, ...>>, 2460708}, {<<0, 0, 0, ...>>, 2460709}, {<<0, 0, ...>>, 2460710}, {<<0, ...>>, 2460711}, {<<...>>, ...}, {...}, ...], callback_module: Indexer.Fetcher.CoinBalance, callback_module_state: [transport: EthereumJSONRPC.HTTP, transport_options: [http: EthereumJSONRPC.HTTP.HTTPoison, url: "http://127.0.0.1:8545", http_options: [recv_timeout: 600000, timeout: 600000, hackney: [pool: :ethereum_jsonrpc]]], variant: EthereumJSONRPC.Geth], metadata: [fetcher: :coin_balance]}]
```

**Comment by LuxesOwen** [comment]
Hi @vbaranov ,I think I had found some cue about this issue. From our rds load(AAS)  panel I can see it's more than 80% Lock:tuple all the time.
<img width="1662" alt="image" src="https://user-images.githubusercontent.com/66360114/225930184-74622522-d09a-4f60-9ee6-a368a08453af.png">
The following sql are the most slow sql ,most time been call they had to wait for locks from other calls.
```
INSERT INTO "addresses" AS a0 ("decompiled","fetched_coin_balance","fetched_coin_balance_block_number","hash","inserted_at","updated_at","verified") VALUES ($1,$2,$3,$4,$5,$6,$7) ON CONFLICT ("hash") DO UPDATE SET "contract_code" = COALESCE(EXCLUDED.contract_code, a0."contract_code"), "fetched_coin_balance" = CASE WHEN EXCLUDED.fetched_coin_balance_block_number IS NOT NULL
      AND EXCLUDED.fetched_coin_balance IS NOT NULL AND
          (a0."fetched_coin_balance" IS NULL OR a0."fetched_coin_bal
```
```
INSERT INTO "addresses" AS a0 INSERT INTO "address_coin_balances_daily" AS a0 ("address_hash","day","inserted_at","updated_at","value") VALUES ($1,$2,$3,$4,$5) ON CONFLICT ("address_hash","day") DO UPDATE SET "value" = CASE WHEN EXCLUDED.value IS NOT NULL AND (a0."value" IS NULL OR EXCLUDED.value > a0."value") THEN
       EXCLUDED.value
     ELSE
       a0."value"
END
, "inserted_at" = LEAST(EXCLUDED.inserted_at, a0."inserted_at"), "updated_at" = GREATEST(EXCLUDED.updated_at, a0."updated_at") WHERE (EXCLUDED.value IS NOT NUL
```
And the second sql had been call more than 100 times/second.

This may be caused by these operations：
A high number of concurrent sessions are trying to acquire a conflicting lock for the same tuple by running UPDATE or DELETE statements.
Highly concurrent sessions are running a SELECT statement using the FOR UPDATE.

Will you continue to optimize this issue?

**Comment by vbaranov** [comment]
Hi @LuxesOwen I suppose this PR https://github.com/blockscout/blockscout/pull/6778 could resolve or mitigate the issue. However, it is still in progress. You can use it, but with caution (only in dev environment).

**Comment by LuxesOwen** [comment]
OK,thank you. I will refer to it and look forward to your updates

**Comment by shufps** [comment]
probably related to: https://github.com/blockscout/blockscout/issues/7300#issuecomment-1520104247

**Comment by cauta** [comment]
Version:
Backend: [v5.2.2-beta.+commit.0b44c42e](https://github.com/blockscout/blockscout/commit/0b44c42e)
Frontend: v1.10.0-aplha+2df78df4
Geth variant.  

i faced this issue with docker compose no build frontend.  
There is no error, but the indexer stop after catch up newest block.  
whenever i restart, indexer sync up again and then stop.   

<img width="1397" alt="image" src="https://github.com/blockscout/blockscout/assets/15400058/d5ed38f8-ac9c-4e07-b42c-8afcc4946a0d">

<img width="1465" alt="image" src="https://github.com/blockscout/blockscout/assets/15400058/95bcfd86-16b1-4a1f-a9f5-5a3691b1d255">

**Comment by cauta** [comment]
after several hours, it's indexed again and then stop

**Comment by daramir** [comment]
> after several hours, it's indexed again and then stop i noticed it is 2hours and indexer run again

I have this issue as well. Which version are you running? I'm running v6 via docker compose. There are a few indexer related errors that I haven't been able to pin down yet.
