### ISSUE TITLE
TPC: <Issue Title>

### ISSUE THREAD

**Issue by marcosalberini** [blockscout/blockscout#7013]
how to add tchpay in metamask or trust wallet?

*Describe your issue here.*

### Environment
* Elixir Version: 1.13.4
* Erlang Version: 25
* BlockScout Version: 4.1.6

* User Agent: `Mozilla/5.0 (Linux; Android 11; SM-A307GT Build/RP1A.200720.012; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/87.0.4280.141 Mobile Safari/537.36 EdgW/1.0`

### Steps to reproduce

*Tell us how to reproduce this issue. If possible, push up a branch to your fork with a regression test we can run to reproduce locally.*

### Expected Behaviour

*Tell us what should happen.*

### Actual Behaviour

*Tell us what happens instead.*

**Comment by vbaranov** [comment]
Please address your question to tchpay support. This chat is for Blockscout explorer issues.
