### ISSUE TITLE
Blockscout website verified contracts view for mainnet is broken

### ISSUE THREAD

**Issue by fainashalts** [blockscout/blockscout#7044]
*Describe your issue here.*

### Environment

Using the blockscout website for mainnet to peruse verified contracts.

### Steps to reproduce

Go to https://blockscout.com/eth/mainnet/verified-contracts

### Expected behaviour

A list of verified contracts is available for view.

### Actual behaviour

"Something went wrong. Click to reload" message is shown, and reloading does not do anything.

**Comment by vbaranov** [comment]
The verified contracts view is currently working.
