### ISSUE TITLE
Configure Sign in With Auth0 

### ISSUE THREAD

**Issue by avenbreaks** [blockscout/blockscout#7045]
*Describe your issue here.*
how do i add auth0 to blockscout, after i try to signin i get an error

```
Callback URL mismatch.
The provided redirect_uri is not in the list of allowed callback URLs.
```

### ENV Config :
ACCOUNT_CLOAK_KEY="`xxxxxxxxxxxxxxxxxxxxxx`" >> _`generate from iex`_
ACCOUNT_ENABLED=`true`
ADMIN_PANEL_ENABLED=`true`

ACCOUNT_AUTH0_DOMAIN=`login-gitshock.jp.auth0.com`
ACCOUNT_AUTH0_CLIENT_ID=`from auth0`
ACCOUNT_AUTH0_CLIENT_SECRET=`from auth0`

ACCOUNT_AUTH0_LOGOUT_URL=https://scan.cartenz.works/logout
ACCOUNT_AUTH0_LOGOUT_RETURN_URL=https://scan.cartenz.works/return

### Auth0 Configuration
Application URIs Login: `https://scan.cartenz.works/auth/auth0`
Allowed Callback URls: `https://scan.cartenz.works/auth/auth0/callback`
Allowed Logout URls: `https://scan.cartenz.works/logout`
Allowed Web Origin: `I didn't fill in because I don't know`
Cross-Origin Authentication `ON`

### Environment
* Deployment type (Docker-compose)
* Operating System: Ubuntu 20 / AWS
* Blockscout Version/branch/commit: Latest
* Archive node type && version (Geth)

### Expected behaviour
Running smoothly like [Gnosis Scan](https://login.blockscout.com/u/login?state=hKFo2SBhRV9NV3BxR1lHRGdFOU9RTzUyMHhJSXRxNG1kMWJoNaFur3VuaXZlcnNhbC1sb2dpbqN0aWTZIE1aSXZXYkFGLWtJa0pOaWhWNU1UaEViNmkySC03eTQ5o2NpZNkgbWtXSDd5ZURHUnNsSXZrSTJwZVV3Q3l6cVBncDBqc3g) hosted blockscout

## Screenshots

![image](https://user-images.githubusercontent.com/93043826/223630264-7a166f7e-551b-45c4-adfc-6cf918a2460b.png)

**Comment by avenbreaks** [comment]
@vbaranov @nikitosing

**Comment by vbaranov** [comment]
@avenbreaks you should set:
```
ACCOUNT_AUTH0_CALLBACK_URL=https://scan.cartenz.works/auth/auth0/callback
```

**Comment by Todmeem8** [comment]
Solved adding callback ENV on blockscout ENV, thanks

**Comment by avenbreaks** [comment]
> @avenbreaks you should set:
> ```
> ACCOUNT_AUTH0_CALLBACK_URL=https://scan.cartenz.works/auth/auth0/callback
> ```

On me, ITS not solved, callback missmatch sir

**Comment by vbaranov** [comment]
@avenbreaks 

Please unset this env variable
```
ADMIN_PANEL_ENABLED=true
```
It is not required for Account functionality.

And please set next env variables the proper values:
```
ACCOUNT_AUTH0_LOGOUT_URL=https://login-gitshock.jp.auth0.com/v2/logout
ACCOUNT_AUTH0_LOGOUT_RETURN_URL=https://scan.cartenz.works/auth/logout
```

Please let me know how it goes after the changes.

**Comment by vbaranov** [comment]
@avenbreaks if you pull updates form master branch, ACCOUNT_AUTH0_LOGOUT_URL and ACCOUNT_AUTH0_LOGOUT_RETURN_URL env variables are not required anymore. I am closing this issue for now. Please, let me know, if you have futher requests.
