### ISSUE TITLE
Testnet: sent wrongly to binance address

### ISSUE THREAD

**Issue by Jiten69** [blockscout/blockscout#7060]
I sent my pulsechain coins wrongly to my binance chain address from pulsechain testnet to eth wallet in binance app... Not received in binance. 

*Describe your issue here.*

### Environment
* Elixir Version: 1.12.2
* Erlang Version: 24
* BlockScout Version: 

* User Agent: `Mozilla/5.0 (Linux; Android 13; SM-S908E Build/TP1A.220624.014; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/111.0.5563.58 Mobile Safari/537.36`

### Steps to reproduce

*Tell us how to reproduce this issue. If possible, push up a branch to your fork with a regression test we can run to reproduce locally.*

### Expected Behaviour

*Tell us what should happen.*

### Actual Behaviour

*Tell us what happens instead.*

**Comment by vbaranov** [comment]
You should contact exchange support.
