### ISSUE TITLE
Blockscout won't show compilers when verifying smart contracts

### ISSUE THREAD

**Issue by iulianivg** [blockscout/blockscout#7069]
*Blockscout won't show smart contract verification Solidity compiler versions, not even default one*
<img width="1131" alt="image" src="https://user-images.githubusercontent.com/43420841/224555986-e0c3aaa1-6906-4c0c-8b48-4eee7cfa8207.png">

### Environment

* Deployment type (Manual/Docker/Docker-compose): Manual
* Elixir & Erlang/OTP versions (`elixir -version`):
```
Erlang/OTP 22 [erts-10.6.4] [source] [64-bit] [smp:4:4] [ds:4:4:10] [async-threads:1]

Elixir 1.13.4 (compiled with Erlang/OTP 22)
```
* Node JS version (`node -v`): v16.19.1
* Operating System: Ubuntu 20.04 (LTS) x64 on Digital Ocean
* Blockscout Version/branch/commit: 
```
root@btc-evm-blockexplorer:~/blockscout/.git/refs/heads# cat master 
711d1483bfa5b8e9cf120f2f3772a108d74e0e90
```

* Archive node type && version (Erigon/Geth/Nethermind/Ganache/?): Geth (POA)

### Steps to reproduce

Deploy the code manually & deploy a smart contract. 

### Expected behaviour

It should show solidity versions or at least "default"

### Actual behaviour

It doesn't show. 

**More info**

- smart-contract-verifier-http is running 
- the ENV variables ENABLE_RUST_VERIFICATION_SERVICE and RUST_VERIFICATION_SERVICE_URL are set
- when running `smart-contract-verifier-http` it turns a warning 
```
2023-03-12T15:06:16.525160Z  WARN smart_contract_verifier::compiler::compilers: cannot load local compilers from `/tmp/solidity-compilers` dir: No such file or directory (os error 2)
2023-03-12T15:06:16.549512Z  INFO smart_contract_verifier::compiler::versions_fetcher: spawn version refresh job
2023-03-12T15:06:16.549586Z  WARN smart_contract_verifier::compiler::compilers: cannot load local compilers from `/tmp/vyper-compilers` dir: No such file or directory (os error 2)
```

Can see the code changed a lot in the past versions and now inside "api" folder we have inside apiv2 this `verification_controller.ex` 

I don't know if that's what's currently affecting since I never had an issue in past versions.

**Comment by nikitosing** [comment]
Which version of `smart-contract-verifier-http` you are using? It should be at least [1.0.0](https://github.com/blockscout/blockscout-rs/releases/tag/smart-contract-verifier%2Fv1.0.0)

**Comment by bluekornchips** [comment]
I can confirm this is happening for me as well.

**Comment by nikitosing** [comment]
@bluekornchips Hello, what version of `smart-contract-verifier-http` do you use?

**Comment by NicoDFS** [comment]
@nikitosing I built from the link you posted and still have this issue. Using 5.1.1-beta version of blockscout

**Comment by thempp66** [comment]
@nikitosing I have the same issue. smart-contract-verifier-http version is 1.0.0

**Comment by rimrakhimov** [comment]
@thempp66 @NicoDFS You have to use [smart-contract-verifier-server](https://github.com/blockscout/blockscout-rs/tree/main/smart-contract-verifier/smart-contract-verifier-server) with newest Blockscout. Could you try to use that instead of http?

**Comment by NicoDFS** [comment]
> 

thanks @rimrakhimov will give it a try when i get a chance
