### ISSUE TITLE
Canto: <Issue Title>

### ISSUE THREAD

**Issue by Blackleets** [blockscout/blockscout#7071]
*Describe your issue here.*

### Environment
* Elixir Version: 1.13.4
* Erlang Version: 24
* BlockScout Version: 

* User Agent: `Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/110.0.0.0 Safari/537.36`

### Steps to reproduce

*Tell us how to reproduce this issue. If possible, push up a branch to your fork with a regression test we can run to reproduce locally.*

### Expected Behaviour

*Tell us what should happen.*

### Actual Behaviour

*Tell us what happens instead.*

**Comment by Blackleets** [comment]
Hi, nice to greet you. I'm having problems with my smart contract on the blockchain, it won't let me open the contract in the browser, it always has a problem code 505, my internet is stable and I want to write some new lines and modify something. Can you please help me!

**Comment by vbaranov** [comment]
Canto instance is unsupported here. Please address your question to Canto team.
