### ISSUE TITLE
Blocksout .env issue

### ISSUE THREAD

**Issue by Neoblock8** [blockscout/blockscout#7085]
Hi,
 Having **common-visualizer.env** under envs folder. But it failed to load that file.
 
Failed to load /root/Explorer/blockscout/envs/common-visualizer.env: open /root/Explorer/blockscout/envs/common-visualizer.env: no such file or directory

**Comment by vbaranov** [comment]
@Neoblock8 
How did you run docker compose? And which version of `docker-compose` do you use?

**Comment by vbaranov** [comment]
@Neoblock8 friendly ping

**Comment by Mustafa-Agha** [comment]
@vbaranov I'm facing similar issue when running this command

docker compose up

Docker version 23.0.1, build a5ee5b1

I fixed it by changing the env path in docker-compose-visualizer.yml and docker-compose-smart-contract-verifier.yml in services folder

**Comment by vbaranov** [comment]
@Mustafa-Agha what is the result of `docker compose version` in your case?

**Comment by vbaranov** [comment]
I cannot reproduce the issue with 
```
Docker version 23.0.4, build f480fb1
Docker Compose version v2.17.2
```

Please update Docker to the latest release.
