### ISSUE TITLE
Ethereum Classic: <Transaction Issue - Request to Revert Back>

### ISSUE THREAD

**Issue by TLukasz72** [blockscout/blockscout#7105]
*Describe your issue here.*
Request to revert ETC transaction: Block 16976040

From (My Trust Wallet)

0x8af380ccc1de78a35690436d62286e3b4a12d014

To
0x03abd1387bfebef7223923bd8f7b5c060c720afb

Amount: 64.9939748

**Please support in reverting transaction back to: From Account (My Trust Wallet)**

My intention was to send funds back to original address in past transaction Block 16350808

### Environment
* Elixir Version: 1.13.1
* Erlang Version: 24
* BlockScout Version: v4.1.8-beta

* User Agent: `Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/111.0`

### Steps to reproduce

*Tell us how to reproduce this issue. If possible, push up a branch to your fork with a regression test we can run to reproduce locally.*

### Expected Behaviour

*Tell us what should happen.*

### Actual Behaviour

*Tell us what happens instead.*

**Comment by vbaranov** [comment]
You should ask in Ethereum Classic Discord https://discord.com/invite/bMGuZsA
