### ISSUE TITLE
Energy Web Chain: <Issue Title>

### ISSUE THREAD

**Issue by Mel164201** [blockscout/blockscout#7108]
*Describe your issue here.*
I swapped bitcoin for EWT sent to my metamask wallet....unfortunately I didn't swap for EWTB. Is there anything else I should do?
### Environment
* Elixir Version: 1.13.1
* Erlang Version: 24
* BlockScout Version: v4.1.5-beta

* User Agent: `Mozilla/5.0 (Linux; Android 13; SM-S908U) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/111.0.0.0 Mobile Safari/537.36`

### Steps to reproduce

*Tell us how to reproduce this issue. If possible, push up a branch to your fork with a regression test we can run to reproduce locally.*

### Expected Behaviour

*Tell us what should happen.*

### Actual Behaviour

*Tell us what happens instead.*

**Comment by vbaranov** [comment]
Energy Web Chain is unsupported here.
