### ISSUE TITLE
export to csv button is not working

### ISSUE THREAD

**Issue by martianacademy** [blockscout/blockscout#7109]
*Describe your issue here.*

### Environment

* Deployment type (Manual/Docker/Docker-compose):
* Elixir & Erlang/OTP versions (`elixir -version`):
* Node JS version (`node -v`):
* Operating System:
* Blockscout Version/branch/commit:
* Archive node type && version (Erigon/Geth/Nethermind/Ganache/?):

### Steps to reproduce

*Tell us how to reproduce this issue.  ❤️ if you can push up a branch to your fork with a regression test we can run to reproduce locally.*

### Expected behaviour

*Tell us what should happen.*

### Actual behaviour

*Tell us what happens instead.*

**Comment by vbaranov** [comment]
@martianacademy please, elaborate the issue

Did you configure reCAPTCHA https://docs.blockscout.com/for-developers/information-and-settings/env-variables#csv-export

**Comment by martianacademy** [comment]
no

**Comment by martianacademy** [comment]
Is it mandatory to configure reCAPTCHA to export data in CSV file?

**Comment by vbaranov** [comment]
Yes
