### ISSUE TITLE
Question: Changing BLOCK_TRANSFORMER on an existing instance

### ISSUE THREAD

**Issue by Thegaram** [blockscout/blockscout#7111]
Is it safe to change `BLOCK_TRANSFORMER` from `base` to `clique` on an existing instance? Or does it require reindexing? I don't mind if old blocks show incorrectly, but want to switch to `clique` for new blocks.

**Comment by vbaranov** [comment]
It is safe, if you don't mind about previous blocks. The value in `BLOCK_TRANSFORMER` affects only the value in `miner_hash` property of block.
