### ISSUE TITLE
Getting wrong tokenbalance from eth mainnet API

### ISSUE THREAD

**Issue by harveyff** [blockscout/blockscout#7124]
Hi team,
Thank you for your great work.

I try to get some data via https://blockscout.com/eth/mainnet/api-docs, but I get some error results do not match.

For example, the following example:
```
https://blockscout.com/eth/mainnet/api?module=account&action=tokenbalance&address=0x3eede967f32936a7aab4536475bbfd3f2ef8e542&contractaddress=0x03be5c903c727ee2c8c4e9bc0acc860cca4715e2
```

Got wrong balance:
```
{"message":"OK","result":"372264341658603125867","status":"1"}
```

but through
```
https://blockscout.com/eth/mainnet/api?module=account&action=tokentx&address=0x3eede967f32936a7aab4536475bbfd3f2ef8e542&contractaddress=0x03be5c903c727ee2c8c4e9bc0acc860cca4715e2
```

Seeing that there are only 2 receipts, the balance should be 1653083404066866767550. You can also see the result from 
```
https://etherscan.io/token/0x03be5c903c727ee2c8c4e9bc0acc860cca4715e2?a=0x3eede967f32936a7aab4536475bbfd3f2ef8e542
```

**Comment by vbaranov** [comment]
@harveyff specified current balance should be fixed now. please let me know, if you face with any other discrepancies.
