### ISSUE TITLE
Blockscout do not support reCAPTCHA v3 and reCAPTCHA enterprise

### ISSUE THREAD

**Issue by anhnh131** [blockscout/blockscout#7130]
@vbaranov When I add the key from reCAPTCHA v3 or reCAPTCHA enterprise, I see it does not work on Blockscout.
Can you check it?

![Screen Shot 2023-03-24 at 13 38 05](https://user-images.githubusercontent.com/43759289/227445135-e7a6e435-6cbf-42c6-99ab-34619e9f5cf8.png)

**Comment by vbaranov** [comment]
Yes, currently Blockscout supports only reCAPTCHA v2. I've updated in the docs.
