### ISSUE TITLE
RPC API `Tokentx` returning different results

### ISSUE THREAD

**Issue by VmMad** [blockscout/blockscout#7137]
So we are currently making tests fetching data from testnets. 
We've tried with [Scroll Alpha](https://blockscout.scroll.io/) and  [Goerli](https://eth-goerli.blockscout.com/).
The issue comes when we try fetching data (usually from large smart contracts) using the query 
`?module=account&action=tokentx&address={addressHash}&start_block={startBlock}&end_block={endBlock}&offset=10000&page=1` . 
The problem we're encountering is that the response we get changes from one moment to the next, even within a span of 10 minutes.
Also, when we fetch from the same smart contract using `offset=1000` or another small number, the first 5 pages come empty and then the 6th has some transfers, which makes it difficult for us to know the total number of transfers.
We don't know if this is something we are doing wrong, so any help or advice would be greatly appreciated!

### Steps to reproduce

Using Goerli testnet:

1. Go to [this link](https://eth-goerli.blockscout.com/api?module=account&action=tokentx&address=0xc92470D7Ffa21473611ab6c6e2FcFB8637c8f330&start_block=8573412&end_block=8705096&offset=10000&page=1).
2. Open dev tools and switch to the network tab. Open the document response (you might need to reload the page) and look at the last index of the `result` array. At the moment of writing the last index is `4247`

With this smart contract you can also try changing the offset query to 1000 and you will notice that pages 1 to 5 are empty but the [page 6 currently has `210` results](https://eth-goerli.blockscout.com/api?module=account&action=tokentx&address=0xc92470D7Ffa21473611ab6c6e2FcFB8637c8f330&start_block=8573412&end_block=8705096&offset=1000&page=6)

Using Scroll Alpha testnet

1. Go to [this link](https://blockscout.scroll.io/api?module=account&action=tokentx&address=0xaC07EE38FA79d3Cc8d27E3e765f059b3b5D0dD8a&start_block=30224&offset=10000&page=0&end_block=526224) and follow the same steps from above. Right now the last index is `642` 

### Expected behaviour

Shouldn't offset give you the first X number of results from that query? If so what is happening with the first 6000 transfers from the link above?
Also, we expect the number of transfers to remain static. Not change unexpectedly.

### Actual behaviour

Responses vary from time to time and some pages come empty when they shouldn't

**Comment by MiLk** [comment]
This might be related to https://github.com/blockscout/blockscout/pull/8868
