### ISSUE TITLE
Testnet: SWAP Error PLSX-PLS

### ISSUE THREAD

**Issue by emirgoud** [blockscout/blockscout#7139]
*When trying to swap out PLSX tokens for PLS, I get the following error:

"Error:  Failed to execute 'requestDevice' on 'HID': Must be handling a user gesture to show a permission request." *

### Environment
* This was done on Mac OS Ventura  13.2.1 (22D68)
* Erlang Version: 24
* BlockScout Version: 

* User Agent: Chrome Version 111.0.5563.110 (Official Build) (x86_64)

### Steps to reproduce

*Try to swap out PLSX for PLS, click the "enable" button and then try to put in the max in the alloted amount in MetaMask.  Once you're done, you click to finish the transaction and the error above appears.*

### Expected Behaviour

*Should swap out PLSX - PLS

### Actual Behaviour

*Error*

Doug Rime
dougrime@gmaill.com

**Comment by vbaranov** [comment]
This question does not relate to Blockscout explorer.

**Comment by emirgoud** [comment]
Where can I submit questions about the bridge (not working for me), swapping out tokens, etc.?  Someone suggested this avenue.

**Comment by vbaranov** [comment]
Try https://t.me/PulseChainCom
