### ISSUE TITLE
Taiko Alpha-2 L2: <Issue Title>

### ISSUE THREAD

**Issue by Bibin-10** [blockscout/blockscout#7142]
*Describe your issue here.*

### Environment
* Elixir Version: 1.13.1
* Erlang Version: 24
* BlockScout Version: 5.0.0

* User Agent: `Mozilla/5.0 (Linux; Android 13; SM-A326B) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/107.0.0.0 Mobile Safari/537.36`

### Steps to reproduce

*Tell us how to reproduce this issue. If possible, push up a branch to your fork with a regression test we can run to reproduce locally.*

### Expected Behaviour

*Tell us what should happen.*

### Actual Behaviour

*Tell us what happens instead.*

Isuue for trasactions very slow & always pending

**Comment by vbaranov** [comment]
Taiko Alpha-2 L2 instance is unsupported here.
