### ISSUE TITLE
ConsenSys zkEVM testnet: <No search icon on the explorer>

### ISSUE THREAD

**Issue by Samakus1** [blockscout/blockscout#7145]
*Describe your issue here.*

### Environment
* Elixir Version: 1.13.1
* Erlang Version: 24
* BlockScout Version: 

* User Agent: `Mozilla/5.0 (Linux; arm_64; Android 13; SM-A127F) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 YaBrowser/23.1.4.33.00 (alpha) SA/3 Mobile Safari/537.36`

### Steps to reproduce

*Tell us how to reproduce this issue. If possible, push up a branch to your fork with a regression test we can run to reproduce locally.*

### Expected Behaviour

*Tell us what should happen.*
There should be search icon the explorer to enable seamless search of ones wallet and the transactions done on the wallet

### Actual Behaviour

*Tell us what happens instead.*
No search icon found, making it difficult to see transactions done in a particular wallet

**Comment by vbaranov** [comment]
Search field is in the right-top corner
![Screenshot 2023-03-27 at 13 41 39](https://user-images.githubusercontent.com/4341812/227919248-8ba07ffb-86a1-4442-a675-d2becd64aac7.png)
Or do you mean anything else?
