### ISSUE TITLE
Blockscout not indexing contracts created through create2

### ISSUE THREAD

**Issue by pajicf** [blockscout/blockscout#7150]
Smart Contracts created through other Factory contracts using the `create2` opcode don't seem to be indexed.
Specifically, this is happening on Scroll's Blockscout instance for the Scroll Alpha Testnet. 

### Environment
- Blockscout: blockscout/blockscout:5.0.0 Docker image used through docker-compose
- Node: https://github.com/scroll-tech/go-ethereum

### Steps to reproduce

1. Solidity version
**Repo of contracts:** https://gist.github.com/pajicf/44b897f80b601135db68a0980772cffb used for reproducing the issue.
**Factory deployment:** https://blockscout.scroll.io/address/0xd61b1f2E5035050a2e4243EE417765869b814E38/transactions#address-tabs
**Tx to create a new contract through the factory:** https://blockscout.scroll.io/tx/0x59e0d06552b2d5841878afe0c8ddb48b3de8f579b2591ddf5a3160984c2cb33a
**Newly deployed contract:** https://blockscout.scroll.io/address/0x54CF89300C05B0dFe1Ee4d5b177F59dCE5735d5B
2. Yul version
Repo of contracts: https://github.com/safe-global/safe-singleton-factory/blob/main/source/deterministic-deployment-proxy.yul
Factory deployment: https://blockscout.scroll.io/address/0x914d7Fec6aaC8cd542e72Bca78B30650d45643d7
Tx to create a new contract through the factory: https://blockscout.scroll.io/tx/0xe6d1bc2c88cdb21b53d83db93f5cc63864fa9ea69baa29c1e5dcdbe8fb2474a5
Newly deployed contract: https://blockscout.scroll.io/address/0x69f4D1788e39c87893C980c06EdF4b7f686e2938

### Expected behaviour

Newly created contracts should be indexed and recognised as contracts in the block explorer

### Actual behaviour

Newly created contract are not indexed and shown as regular EOA addresses in the block explorer

**Comment by vbaranov** [comment]
The issue seems was related to unavailability to fetch internal trasnactions from the node. As far as I can see now internal transactions have been fetched, code is displayed at the contract page and thereby it is recognized as a contract. I am closing this issue. Let me know, if you have further requests.
