### ISSUE TITLE
Linea Testnet: <Issue Title>

### ISSUE THREAD

**Issue by captnem00** [blockscout/blockscout#7160]
*i cant add network manually it says "Could not fetch chain ID. Is your RPC URL correct?".*

### Environment
* Elixir Version: 1.13.1
* Erlang Version: 24
* BlockScout Version: 

* User Agent: `Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/111.0.0.0 Safari/537.36 Edg/111.0.1661.54`

you should change chain id Consensys that use in the past testnet

**Comment by vbaranov** [comment]
Linea Testnet is not supported by Blockscout team. Please address your question to an appropriate support channel.
