### ISSUE TITLE
Linea Testnet: Blockscout Testnet Goerli explorer API ReCaptcha not defined

### ISSUE THREAD

**Issue by vbuck-project** [blockscout/blockscout#7163]
Problem on explorer.goerli.linea.build

CSV download will not work since reCAPTCHA is not configured. Please advise server maintainer to configure RE_CAPTCHA_CLIENT_KEY and RE_CAPTCHA_SECRET_KEY environment variables.

### Environment
![warning-api-key-recaptcha](https://user-images.githubusercontent.com/32679536/228606315-572ac26c-990a-40fb-9101-55ab55b4b20f.PNG)

* Elixir Version: 1.13.1
* Erlang Version: 24
* BlockScout Version: 

* User Agent: `Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/111.0.0.0 Safari/537.36`

### Steps to reproduce

Example:
Clic on "Download CSV button" and check the error message.
https://explorer.goerli.linea.build/csv-export?address=0xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx&type=transactions

### Expected Behaviour

When we use the Download CSV button on an address or contract page.### Actual Behaviour

**Comment by vbaranov** [comment]
Linea Testnet is unsupported in this channel. Please address your question to Linea Testnet support team.
