### ISSUE TITLE
EVM Devnet Sidechain: <locating XRP wallet address after importing from unsupported wallet>

### ISSUE THREAD

**Issue by pworts** [blockscout/blockscout#7169]
I was holding XRP in Coinbase Wallet. They were preventing my transfer out before the unsupport deadline because of my VPN. Now I have tried importing  my wallet to MetaMask in order to view and manage my XRP. When I import the wallet, no coins show up on the side chain and I am prompted to import coins. When asked, I need to provide my XRP wallet address but Coinbase can’t provide it to me because it’s no longer supported and I don’t know where else to look.

thank you in advance.

### Environment
* Elixir Version: 1.13.1
* Erlang Version: 24
* BlockScout Version: 

* User Agent: `Mozilla/5.0 (iPhone; CPU iPhone OS 16_3_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Mobile/15E148`

### Steps to reproduce

*Tell us how to reproduce this issue. If possible, push up a branch to your fork with a regression test we can run to reproduce locally.*

### Expected Behaviour

*Tell us what should happen.*

### Actual Behaviour

*Tell us what happens instead.*

**Comment by vbaranov** [comment]
XRP EVM Devnet Sidechain is unsupported by Blockscout team. Please address your question to the support of the chain.
