### ISSUE TITLE
Token metadata not showing up

### ISSUE THREAD

**Issue by atiprashant** [blockscout/blockscout#7171]
I just deployed a new instance of blockscout on my local machine. It is not fetching metadata of the tokens which are deployed. Is there any way of resync the tokens metadata ?

https://scan.playota.app/tokens
I am sharing the link to tokens page

**Comment by vbaranov** [comment]
I see only ERC-20 tokens on the list. Which token metadata do you expect to see?

**Comment by vbaranov** [comment]
@atiprashant I am closing the issue because didn't get response from you. Please open a new one, if the issue still persists.
