### ISSUE TITLE
Linea Testnet: Can not add RPC to MM

### ISSUE THREAD

**Issue by wishxy** [blockscout/blockscout#7172]
I just try to add Linea test RPC {explorer.goerli.linea.build/} to Metamask, but I'm getting message wrong RPC.
Also, link: 'Add Linea Testnet' on BlockScout doesn't work. Any help?

**Comment by vbaranov** [comment]
Linea Testnet is not supported by Blockscout team.

**Comment by wishxy** [comment]
How do you mean Linea testnet is not supported by Blockscout team? 
What is this? 
https://prnt.sc/bMm2NajJNTyN
