### ISSUE TITLE
A lot of data in address_token_balances is not fetched

### ISSUE THREAD

**Issue by harveyff** [blockscout/blockscout#7175]
*Describe your issue here.*

### Environment

* Deployment type (Manual/Docker/Docker-compose):
Manual
* Elixir & Erlang/OTP versions (`elixir -version`):
Erlang/OTP 25 [erts-13.0.2] [source] [64-bit] [smp:32:32] [ds:32:32:10] [async-threads:1] [jit]

Elixir 1.14.3 (compiled with Erlang/OTP 24)

* Node JS version (`node -v`):
v18.14.2

* Operating System:
Ubuntu 20.04.5 LTS (GNU/Linux 5.15.0-1033-aws aarch64)
* Blockscout Version/branch/commit:
v5.1.1-beta
* Archive node type && version (Erigon/Geth/Nethermind/Ganache/?):
Erigon
### Steps to reproduce

*Tell us how to reproduce this issue.  ❤️ if you can push up a branch to your fork with a regression test we can run to reproduce locally.*

Hi, I try to sync node data of ethereum network, I try to sync 10000 blocks, it generated about 2112642 address_token_balances records in total, but after I synced for 10 minutes, it finished, I checked the data and found that there are 32000 The value of address_token_balances is null, that is, it has not been updated, so the user's token list cannot be obtained correctly.

May I ask what is the reason for this, because the token list data is very important to me, how can I ensure that it is all synchronized in a timely manner?

Thanks again for your great work.

best wishes.

![p1](https://user-images.githubusercontent.com/21994933/228750220-7acd83d8-c544-4b76-93ee-1c2519cbef99.png)

The running program of my 32-core 128G EC2 host, the database is also a 32-core 128G AWS RDS, and the IO is very large, so theoretically these are not bottlenecks.

```
DB_PASSWORD=12345678
COIN=ETH
INDEXER_DISABLE_BLOCK_REWARD_FETCHER=true
DATABASE_URL=postgresql://postgres:12345678@******.us-east-1.rds.amazonaws.com:5432/eth
INDEXER_DISABLE_ADDRESS_COIN_BALANCE_FETCHER=true
ETHEREUM_JSONRPC_HTTP_URL=http://127.0.0.1:9527
DISABLE_EXCHANGE_RATES=true
PORT=5000
LAST_BLOCK=16935000
FIRST_BLOCK=16925000
CHAIN_ID=1
DB_PORT=5432
INDEXER_EMPTY_BLOCKS_SANITIZER_BATCH_SIZE=200
ETHEREUM_JSONRPC_TRACE_URL=http://127.0.0.1:9527
NETWORK=Mainnet
INDEXER_CATCHUP_BLOCKS_CONCURRENCY=80
INDEXER_MEMORY_LIMIT=40
DB_USERNAME=postgres
POOL_SIZE=1000
POOL_SIZE_API=200
INDEXER_CATCHUP_BLOCKS_BATCH_SIZE=10
ETHEREUM_JSONRPC_VARIANT=erigon
SECRET_KEY_BASE=******
COIN_NAME=ETH
ETHEREUM_JSONRPC_HTTP_INSECURE=true
INDEXER_DISABLE_PENDING_TRANSACTIONS_FETCHER=true
SUBNETWORK=Mainnet
```

**Comment by vbaranov** [comment]
@harveyff the set of environment variables looks healthy. I cannot reproduce the issue with the latest 5.1.3 release or current master branch. Could you please pull updates, if not yet, and re-try?

**Comment by bretep** [comment]
I am also having this issue after upgrading to 5.1.3
https://scan.v4.testnet.pulsechain.com/tokens

**Comment by vbaranov** [comment]
Closing due to no response from the author.
