### ISSUE TITLE
docker image missing file

### ISSUE THREAD

**Issue by masayil** [blockscout/blockscout#7176]
![image](https://user-images.githubusercontent.com/65291464/228756152-27ff69dc-9b1a-40fd-af34-5981cf7dd2e2.png)
Docker image: blockscout/blockscout:5.1.2
Looks like "/app/releases/5.1.2/config_helper.exs" is missing.

**Comment by vbaranov** [comment]
Thank you for such quick feedback. I revoked that docker image. Could you please re-test again with the same docker image tag (you need to remove that tag from your local machine first)?

**Comment by masayil** [comment]
fixed.

**Comment by vbaranov** [comment]
@norbubb could you please clarify how did you run docker compose?
