### ISSUE TITLE
Linea Testnet: <Issue Title>

### ISSUE THREAD

**Issue by tgoshare** [blockscout/blockscout#7180]
*Describe your issue here.*

### Environment
* Elixir Version: 1.13.1
* Erlang Version: 24
* BlockScout Version: 

* User Agent: `Mozilla/5.0 (Linux; Android 11; GIONEE M15) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/107.0.0.0 Mobile Safari/537.36`

### Steps to reproduce

*Tell us how to reproduce this issue. If possible, push up a branch to your fork with a regression test we can run to reproduce locally.*

### Expected Behaviour

*Tell us what should happen.*

### Actual Behaviour

*Tell us what happens instead.*

**Comment by tgoshare** [comment]
Unable to view on explore chain.
0x092fd6f391698c7c977adee41ef3ccde258764cf

**Comment by vbaranov** [comment]
Blockscout team cannot help with this question because we do not manage Linea Testnet instance. Try to ask in https://support.linea.build/hc/en-us/requests/new.
