### ISSUE TITLE
Linea Testnet: Metamask "Add Linea Testnet" link doesn't work

### ISSUE THREAD

**Issue by darklion84** [blockscout/blockscout#7182]
"Add Linea Testnet " link in the footer on https://explorer.goerli.linea.build/ doesn't work.

### Environment
* Elixir Version: 1.13.1
* Erlang Version: 24
* BlockScout Version: 

* User Agent: `Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:87.0) Gecko/20100101 Firefox/87.0`

### Steps to reproduce

No Chrome neither Firefox. Just doesn't work.

### Expected Behaviour

Open Metamask and add custom Linea network.

### Actual Behaviour

No visible reaction for the link click. There is an error in browser console: 
Object { code: -32602, message: "Expected an array with at least one valid string HTTPS url 'rpcUrls', Received:\n", stack: "Error@moz-extension://520e5e41-a296-4087-92a5-dc411b96fc18/runtime-lavamoat.js:7523:17\ni@moz-extension://520e5e41-a296-4087-92a5-dc411b96fc18/common-1.js:12:10871\na@moz-extension://520e5e41-a296-4087-92a5-dc411b96fc18/common-1.js:12:13811\ninvalidParams@moz-extension://520e5e41-a296-4087-92a5-dc411b96fc18/common-1.js:12:14319\nimplementation@moz-extension://520e5e41-a296-4087-92a5-dc411b96fc18/background-3.js:1:367325\nr.createMethodMiddleware/<@moz-extension://520e5e41-a296-4087-92a5-dc411b96fc18/background-3.js:1:364908\n_runMiddleware/<@moz-extension://520e5e41-a296-4087-92a5-dc411b96fc18/background-3.js:1:9485\n_runMiddleware@moz-extension://520e5e41-a296-4087-92a5-dc411b96fc18/background-3.js:1:9141\n_runAllMiddleware@moz-extension://520e5e41-a296-4087-92a5-dc411b96fc18/background-3.js:1:9047\n" }

**Comment by wishxy** [comment]
I've already reported the issue, and this is the answer I've got. 
https://github.com/blockscout/blockscout/issues/7172

**Comment by vbaranov** [comment]
Blockscout team cannot help with this question because we do not manage Linea Testnet instance. Try to ask in https://support.linea.build/hc/en-us/requests/new.
