### ISSUE TITLE
Blockscout Indexer stops always working after ~ 147 - 150 transactions, reproducable

### ISSUE THREAD

**Issue by itinance** [blockscout/blockscout#7191]
*Describe your issue here.*

Blockscout Indexer stops indexing after around 147-150 transactions or 147-150 blocks existing in the blockchain. 
Stopping blockscout, resetting the database and restarting Blockscout again will catch up to the most recent transactions, but will still not index newer ones. 

Setting up a new empty blockchain will lead to the same result: it indexes automatically until 147-151 transactions exist (the final number varies a bit within this range). Then indexing stops automatically, although the indexer internally still is doing something according to the logfiles (more details below). 

However, no new records will be written into the database then any more via the running indexer. Also, the statistics of counting transactions and blocks in the header of homepage are suddenly rendered with wrong values once this moment has reached (they show the half of the actual number)

I have reproducible examples, and I will give further information below. Our EVM-Testnet can be used for debugging. I am happy to provide details and tokens.

Maybe important to know:

I hunter this issue for a week now with my DevOps. We setup several blockchain nodes and blockscout nodes, populated tons of transactions, reset everything again, tested a lot with database clearing and so got a clue what is seemingly happening. Everything that I explain here can be reproduced at any time. We even tested latest blockscout and older versions like 4.1.8. 

### Environment

* Deployment type (Manual/Docker/Docker-compose):  docker-compose and kubernetes (happening on both)
* Elixir & Erlang/OTP versions (`elixir -version`): 
     - Erlang/OTP 24 [erts-12.2] [source] [64-bit] [smp:3:3] [ds:3:3:10] [async-threads:1] [jit:no-native-stack]
     - Elixir 1.13.1 (compiled with Erlang/OTP 24)
* Node JS version (`node -v`): v16.13.1
* Operating System: Ubuntu 22
* Blockscout Version/branch/commit: 
   - happens with all versions I tried, especially: blockscout/blockscout:4.1.8, blockscout/blockscout:5.1.2
* Archive node type && version (Erigon/Geth/Nethermind/Ganache/?): Geth, Avalanche Fuji EVM-SubNet

* Blockchain: Avalanche EVM-SubNet, based on FUJI-testnet, we run our own validators with basic setup of Avalanche

### Steps to reproduce

see below
### Expected behaviour

see below

### Actual behaviour

see below:

Here we go:

Important to know: in my case, and probably since I am the only user, per transaction a new block will be produced on my Avalanche SubNet.

1. Setup Blockscout with empty database
2. Connect with en Empty Blockchain
3. Blockscout Indexer is working for a while, even days and weeks, indexing all incoming transactions
4. After ~ 147-151 transactions (or 150 blocks, in my case 1 tx = 1block) it stops indexing
4. new transactions will not written any more into the database, although they are happing correctly on the blockchain
5. `select count(*) from transactions` -> 150
5. STOP blockscout service
6. DROP DATABASE blockscout
7. CREATE DATABASE blockscout
8. Restart blockscout service
9. -> Indexer works and indexes ALL including the new, most recent transactions
10.   `select count(*) from transactions;` -> 164
11. Submit new transactions to the blockchain, blockscout will not write them to the database, although logs are populated heavily with new entries
12.  wait 60 sec,  `select count(*) from transactions;` -> still 164
13. Submit new transaction
14.  wait 60 sec, `select count(*) from transactions;` -> 164
15. STOP blockscout service
16. DROP DATABASE 
17. CREATE DATABASE 
18. Indexer works and indexes all including most recent transactions, including all new transactions that were happening in the meanwhile
19.   `select count(*) from transactions;` -> 168
20. Indexing stops working 
21. GOTO 5

To summarize:

1. indexer works until a certain threshold of transactions or blocks has been reached
2. indexer stops writing entries to the database then
3. rebuilding the database from scratch will index ALL transactions
4. but will NOT write new transactions any more

Maybe WORTH to Know:

When I accidentally tried to drop the database, although the Blockscout Service was still running, I saw the following error message:

```
ERROR:  database "blockscout" is being accessed by other users
DETAIL:  There are 151 other sessions using the database.
```

This can be random, but 151 opened sessions is a little similar to the same number when Blockscout stops indexing. Maybe there is some relation.

In the logfiles I see tons of messages, but not a single log entry is related to database issues.

I will attach logs, but I'm afraid they are not helpful. But they show that there is something like a loop happening. After around 150 rows in the logfiles they will repeat. So always the same ~ 147-150 first transactions of the blockchain will be logged again and again in a loop and not the latest one.

I don't know why, but 150 is the magic number here :). 

It seems that only the first 150 transactions will be fetched then all the time.

To narrow it down, I need further information:
I'd like to track and log all RPC-calls including all parameters that will be made to the node including all database queries and statements. Can we achieve this via a Setting to enable further logging? 

My theory:
1. either only the first 150 transactions will be received from the nodes in a loop (although at startup it will index ALL transactions, even 250 and more)
2. or the service that writes into the database is stopping after 150 records (150 is meant as a value between the range 147 and 151, as we have seen all values in this range in our attempts)

Attached are logfiles and all config-files.

If someone wants to debug this issue on our EVM-chain (testnet, details in config files available), I'm happy to send tokens.

[logs.txt](https://github.com/blockscout/blockscout/files/11129174/logs.txt)
[log2.txt](https://github.com/blockscout/blockscout/files/11129175/log2.txt)
[visualizer.txt](https://github.com/blockscout/blockscout/files/11129209/visualizer.txt)
[sc-verifier.txt](https://github.com/blockscout/blockscout/files/11129210/sc-verifier.txt)
[blockscout.txt](https://github.com/blockscout/blockscout/files/11129211/blockscout.txt)

**Comment by vbaranov** [comment]
@itinance thanks for thorough description. Looking to the logs of the explorer, it seems, archive state is not available on your Avalanchego node. I would suggest make the modifications to the set of environment variables - it should reduce the number of error logs, and probably, it will help to facilitate with debugging the issue, you have with indexing. The suggested change is:
```
ETHEREUM_JSONRPC_DISABLE_ARCHIVE_BALANCES=true
```

Could you please apply to the instance?

**Comment by itinance** [comment]
Thank you very much for this. Some guys from AvaLabs also mentioned already, that it seems to have something to do with "non archival node" availability, so I was setting up a node without pruning. However, it takes a while and is still bootstrapping since 10 days or so :) 


We tested the mentioned setting `ETHEREUM_JSONRPC_DISABLE_ARCHIVE_BALANCES=true` and it works properly on ONE of our setups (means one block-explorer instance on one specific subnet).
On 2 other instances it didn't helped like as the setting was not passed correctly, although we use the same config files across all nodes.

DevOps are on it and try to identify the root cause. I will keep you posted next days here.

Conclusion at the moment: the setting seems to be the right candidate for non-archival nodes and is even **necessary**. 
Nevertheless, we still have to figure out, why this setting doesn't work everywhere.

**Comment by itinance** [comment]
I can confirm now, that the setting 

`ETHEREUM_JSONRPC_DISABLE_ARCHIVE_BALANCES=true` 

is absolutely necessary here for non-archival nodes and makes the issue not happen. Going to close now.
