### ISSUE TITLE
Linea Testnet: Wrong number of transactions

### ISSUE THREAD

**Issue by jujielbrus** [blockscout/blockscout#7193]
![zxzxz](https://user-images.githubusercontent.com/128135321/229347578-c5186f74-f69a-47e2-9907-96c88876df12.png)

Blockchain explorer shows 0 transactions despite i have atleast 4 of them

Wallet is 0x765E070365723EEA3735C5Ee1ce22a5746EA05A7

### Environment
* Elixir Version: 1.13.1
* Erlang Version: 24
* BlockScout Version: 

* User Agent: `Mozilla/5.0 (X11; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/111.0`

### Steps to reproduce

Code changing maybe?

### Expected Behaviour

Correct number of transactions

### Actual Behaviour

Wrong number of transactions

**Comment by vbaranov** [comment]
There is a latency in the cache update of number of transactions. It should be displayed correctly after a while.
