### ISSUE TITLE
Mainnet: can someone help me with a transaction

### ISSUE THREAD

**Issue by Taylort6464** [blockscout/blockscout#7195]
I sent my DC to my ERC20 address by mistake through the Dog20 network from Kucoin.

0x0a4ce4dd86a58cf64c2f0ebf53023090548c81b4eba386c960125cb369d4d9fa

Is there any way to reverse the transaction, or connect the dog20 network to my CB wallet, or something else? I fear I have compromised my assets.

**Comment by vbaranov** [comment]
You should contact exchange support, which you were using, with this question.
