### ISSUE TITLE
Canto: Cannot Export Transaction Data

### ISSUE THREAD

**Issue by samuel-poon** [blockscout/blockscout#7213]
I am trying to export my transaction data into a CSV on https://evm.explorer.canto.io/. When I click on Download CSV, I am redirected to https://evm.explorer.canto.io/csv-export?address={address}&type=transactions, but nothing happens after clicking the Download button.

**Comment by superskirv** [comment]
I am also having issues with download. If I do not change the dates it will download the csv file, but I wanted a full year and it just does nothing, sometimes it tells me the blockscout can not connect to the captcha servers.

**Comment by vbaranov** [comment]
Blockscout team doesn't manage this instance of explorer. Canto explorer maintainer didn't configure reCAPTCHA for this page.
