### ISSUE TITLE
Linea Testnet: <Issue Title>

### ISSUE THREAD

**Issue by Alexmachine1** [blockscout/blockscout#7216]
*Describe your issue here.*

### Environment
* Elixir Version: 1.13.1
* Erlang Version: 24
* BlockScout Version: 

* User Agent: `Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/111.0.0.0 Safari/537.36`

### Steps to reproduce

*Tell us how to reproduce this issue. If possible, push up a branch to your fork with a regression test we can run to reproduce locally.*

### Expected Behaviour

*Tell us what should happen.*

### Actual Behaviour

*Tell us what happens instead.* I am finding it hard to add this contract address 0xea54c22E1E6bBfEb33efd0cD1b5033B522e2C520

**Comment by Alexmachine1** [comment]
I am finding it hard to add this contract address 0xea54c22E1E6bBfEb33efd0cD1b5033B522e2C520

**Comment by vbaranov** [comment]
Not sure how Blockscout team can help you with this. If you still have issue with Blockscout explorer, please create a new one following  issue template.
