### ISSUE TITLE
App crashed when API endpoint is unavailable

### ISSUE THREAD

**Issue by MayankMittal1** [blockscout/blockscout#7217]
*App crashed when API endpoint is unavailable*

### Environment

* Deployment type (Docker):
* Operating System: Amazon ECS
* Blockscout 5.1.2:
* Archive node type && version (Nethermind:

### Steps to reproduce

Run the app and make rpc endpoint unavailable

### Expected behaviour

App should not crash, just stop indexing

### Actual behaviour

App crashes when API endpoint is unavailable

**Comment by vbaranov** [comment]
Related to https://github.com/blockscout/blockscout/issues/6975
