### ISSUE TITLE
Testnet: <Issue Title>wont confirm 

### ISSUE THREAD

**Issue by shellyhasha** [blockscout/blockscout#7221]
When I try to add liquidity to staking an error keeps coming up. Do math sub underfloor. I have changed my settings and the has trying to fix it. I do not know what I am doing wrong.

You can email me at shellymhasha@gmail.com 

Thank you, shellyhasha

### Environment
* Elixir Version: 1.12.2
* Erlang Version: 24
* BlockScout Version: 

* User Agent: `Mozilla/5.0 (Linux; Android 12; SM-S134DL) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/111.0.0.0 Mobile Safari/537.36`

### Steps to reproduce
Try staking liquidity on the farm for pls/pulsex.

*Tell us how to reproduce this issue. If possible, push up a branch to your fork with a regression test we can run to reproduce locally.*

### Expected Behaviour
Error will show when trying to confirm

*Tell us what should happen.*
It should confirm staking the lp.

### Actual Behaviour
Error listed above comes up

*Tell us what happens instead.*

**Comment by vbaranov** [comment]
Thi chat is for Blockscout explorer related questions. Your question is out of scope.
