### ISSUE TITLE
Error: (Awaiting internal transactions for reason)

### ISSUE THREAD

**Issue by bretep** [blockscout/blockscout#7225]
We are seeing a large number of:

```
Error: (Awaiting internal transactions for reason)
```

We are able to run the following with success:
```
curl -H 'Content-Type: application/json' --data '{"jsonrpc":"2.0", "id": 1, "method": "debug_traceTransaction", "params": [ "0xc1b496d0af70b14025c4dd8f760e3eb2fad1af4f354dd7cc6a4d73d6b8d72b9e" ] }' http://localhost
```

### Environment

* Deployment type (Manual/Docker/Docker-compose): Docker
* Elixir & Erlang/OTP versions (`elixir -version`):
* Node JS version (`node -v`):
* Operating System: Linux (Ubuntu 20.04.5 LTS (Focal Fossa))
* Blockscout Version/branch/commit: `c1b0e1ba5c1e84a5d5f51a998c610c4ee6e666bf` 5.1.2
* Archive node type && version (Erigon/Geth/Nethermind/Ganache/?): geth

### Steps to reproduce

Note: We generally run with `INDEXER_INTERNAL_TRANSACTIONS_BATCH_SIZE=5` I increased it to 500 to see if this was causing an issue.

```
sudo docker run -d --net=host --restart always --log-opt max-size=50m
 -e FIRST_BLOCK=16492700
 -e BLOCK_TRANSFORMER=base
 -e BLOCKSCOUT_HOST=localhost
 -e BLOCKSCOUT_PROTOCOL=http
 -e CHAIN_ID=942
 -e COIN=tPLS
 -e DATABASE_URL=postgres://.../blockscout
 -e DISABLE_INDEXER=false
 -e DISABLE_REALTIME_INDEXER=false
 -e INDEXER_CATCHUP_BLOCKS_BATCH_SIZE=2
 -e INDEXER_CATCHUP_BLOCKS_CONCURRENCY=2
 -e INDEXER_INTERNAL_TRANSACTIONS_BATCH_SIZE=500
 -e INDEXER_DISABLE_EMPTY_BLOCK_SANITIZER=true
 -e INDEXER_RECEIPTS_BATCH_SIZE=50
 -e INDEXER_COIN_BALANCES_BATCH_SIZE=50
 -e INDEXER_TX_ACTIONS_ENABLE=true
 -e DISABLE_EXCHANGE_RATES=true
 -e ENABLE_SOURCIFY_INTEGRATION=true
 -e DISABLE_WEBAPP=true
 -e ECTO_USE_SSL=false
 -e ENABLE_1559_SUPPORT=true
 -e ETHEREUM_JSONRPC_HTTP_INSECURE=true
 -e ETHEREUM_JSONRPC_HTTP_URL=http://localhost:80/
 -e ETHEREUM_JSONRPC_TRACE_URL=http://localhost:80/
 -e ETHEREUM_JSONRPC_WS_URL=ws://localhost:8546/
 -e ETHEREUM_JSONRPC_VARIANT=geth
 -e ETHEREUM_JSONRPC_TRANSPORT=http
 -e ETHEREUM_JSONRPC_DEBUG_TRACE_TRANSACTION_TIMEOUT=20s
 -e ETHEREUM_JSONRPC_HTTP_TIMEOUT=60
 -e FETCH_REWARDS_WAY=manual
 -e INDEXER_MEMORY_LIMIT=300g
 -e PORT=4000 -p 4000:4000 --restart on-failure:5 --entrypoint /bin/sh rdocker pull blockscout/blockscout:5.1.2.commit.c1b0e1ba -c 'bash -c "bin/blockscout eval \"Elixir.Explorer.ReleaseTasks.create_and_migrate()\" && bin/blockscout start"'
 ```

### Expected behaviour
```
curl -H 'Content-Type: application/json' --data '{"jsonrpc":"2.0", "id": 1, "method": "debug_traceTransaction", "params": [ "0xc1b496d0af70b14025c4dd8f760e3eb2fad1af4f354dd7cc6a4d73d6b8d72b9e" ] }' http://localhost
```
Returns:
```
"returnValue": "08c379a00000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000000000000000000000000000000000001a536166654d6174683a206469766973696f6e206279207a65726f000000000000",
```

If we decode this it is:

```
0x08c379a0                                                          // Function selector for Error(string)
0x0000000000000000000000000000000000000000000000000000000000000020  // Data offset
0x000000000000000000000000000000000000000000000000000000000000001a  // String length
0x536166654d6174683a206469766973696f6e206279207a65726f000000000000  // String data
```

When decoding the `String data` it displays the reason.
![telegram-cloud-photo-size-1-5003756759948569412-y](https://user-images.githubusercontent.com/787344/230201850-dbeeb1cd-8e06-44a7-9301-8ffe694ddc54.jpg)

This reason should be indexed and displayed vs. the actual behavior.

### Actual behaviour

![telegram-cloud-photo-size-1-5003756759948569411-y](https://user-images.githubusercontent.com/787344/230202409-fb35b981-da2d-4a80-9f86-a59a6262d7d8.jpg)

**Comment by bretep** [comment]
Bump, incase it missed. :)

**Comment by bretep** [comment]
Still seeing this issue.

**Comment by vbaranov** [comment]
@bretep is the number of internal transactions increasing overtime at all?
```
SELECT COUNT(*) FROM internal_transactions;
```

> Note: We generally run with INDEXER_INTERNAL_TRANSACTIONS_BATCH_SIZE=5 I increased it to 500 to see if this was causing an issue.

Then you need to increase ETHEREUM_JSONRPC_DEBUG_TRACE_TRANSACTION_TIMEOUT too: the higher batch size, the slower response from debug_traceTransaction. And 500 is very high number for this endpoint - I doubt Geth can respond in decent time with such huge batch size. Usually, batch size should be ~10.

Also, Blockscout uses callTracer, as a tracer with timeout option, which sent in batches. So the actual request from Blockscout would be like this:
```
curl -H 'Content-Type: application/json' --data '[{"jsonrpc":"2.0", "id": 1, "method": "debug_traceTransaction", "params": [ "0xc1b496d0af70b14025c4dd8f760e3eb2fad1af4f354dd7cc6a4d73d6b8d72b9e", { "tracer": "callTracer", "timeout": "20s"}, {"jsonrpc":"2.0", "id": 2, "method": "debug_traceTransaction", "params": [ "0x...", { "tracer": "callTracer", "timeout": "20s"}] }]'

```

**Comment by bretep** [comment]
ETHEREUM_JSONRPC_DEBUG_TRACE_TRANSACTION_TIMEOUT=20s
INDEXER_INTERNAL_TRANSACTIONS_BATCH_SIZE=500

We are using erigon as our backend now, still the same issue.

**Comment by bretep** [comment]
128 core server. No virtulaization.
992G RAM

Erigon is running on 8 SSDs in a lvgroup tested reading and writing over 2 GB/s

```
sudo vgdisplay
  --- Volume group ---
  VG Name               ephemeral
  System ID
  Format                lvm2
  Metadata Areas        8
  Metadata Sequence No  2
  VG Access             read/write
  VG Status             resizable
  MAX LV                0
  Cur LV                1
  Open LV               1
  Max PV                0
  Cur PV                8
  Act PV                8
  VG Size               27.28 TiB
  PE Size               4.00 MiB
  Total PE              7152552
  Alloc PE / Size       7152552 / 27.28 TiB
  Free  PE / Size       0 / 0
  VG UUID               V3wcVw-340g-1tY0-xFoR-SNEK-Ze3M-vsaQZX
  ```
/dev/mapper/ephemeral-data   28T  2.7T   25T  10% /blockchain


<img width="1431" alt="image" src="https://user-images.githubusercontent.com/787344/233644768-076b825f-b9aa-48ad-9b1f-874542aa1410.png">


```
sudo docker run -d --net=host --restart always --label=periodic.restart=1 --log-opt max-size=50m
 -e BLOCKSCOUT_HOST=localhost
 -e BLOCKSCOUT_PROTOCOL=http
 -e BLOCK_TRANSFORMER=base
 -e CHAIN_ID=943
 -e COIN=tPLS
 -e DATABASE_URL=postgres://.../blockscout
 -e DISABLE_EXCHANGE_RATES=true
 -e DISABLE_INDEXER=false
 -e DISABLE_REALTIME_INDEXER=false
 -e DISABLE_WEBAPP=true
 -e ECTO_USE_SSL=false
 -e ENABLE_1559_SUPPORT=true
 -e ETHEREUM_JSONRPC_DEBUG_TRACE_TRANSACTION_TIMEOUT=20s
 -e ETHEREUM_JSONRPC_HTTP_INSECURE=true
 -e ETHEREUM_JSONRPC_HTTP_TIMEOUT=60
 -e ETHEREUM_JSONRPC_HTTP_URL=http://localhost:80/
 -e ETHEREUM_JSONRPC_TRACE_URL=http://localhost:80/
 -e ETHEREUM_JSONRPC_TRANSPORT=http
 -e ETHEREUM_JSONRPC_VARIANT=erigon
 -e ETHEREUM_JSONRPC_WS_URL=ws://localhost:80/
 -e FETCH_REWARDS_WAY=manual
 -e FIRST_BLOCK=16492700
 -e INDEXER_CATCHUP_BLOCKS_BATCH_SIZE=2
 -e INDEXER_CATCHUP_BLOCKS_CONCURRENCY=2
 -e INDEXER_COIN_BALANCES_BATCH_SIZE=50
 -e INDEXER_DISABLE_EMPTY_BLOCK_SANITIZER=true
 -e INDEXER_INTERNAL_TRANSACTIONS_BATCH_SIZE=500
 -e INDEXER_MEMORY_LIMIT=300g
 -e INDEXER_RECEIPTS_BATCH_SIZE=50
 -e INDEXER_TX_ACTIONS_ENABLE=true
 -e SOURCIFY_INTEGRATION_ENABLED=true
 -e PORT=4000 -p 4000:4000 --restart on-failure:5 --entrypoint /bin/sh ... -c 'bash -c "bin/blockscout eval \"Elixir.Explorer.ReleaseTasks.create_and_migrate()\" && bin/blockscout start"'
 ```

Running:

```
 curl -w "@curl-format.txt" -H 'Content-Type: application/json' --data '{"jsonrpc":"2.0", "id": 1, "method": "debug_traceTransaction", "params": [ "0x3bc9f81494822b8f139f1c1f1e9767b11251d246fd8f17eaa4391d9f9bb1ac65" ] }' http://localhost
```

Output:
[curl_output.txt](https://github.com/blockscout/blockscout/files/11296057/curl_output.txt)

```
...cbe494b7000000000000000000000000000000000000000000000000000000","0000000055ffff0538782d122d3112f75dc7121f61562261c0f7943d7c5c0aaa","95a7d73df8b67b3ce8dd58c8f486ccdf37b876180ecb17a5657659fffffddd75","6cba9095128e53f3291a6ba38b21e3df744936e7289326555d6208c379a00000","0000000000000000000000000000000000000000000000000000000000200000","0000000000000000000000000000000000000000000000000000000000285075","6c736558526f757465723a20494e53554646494349454e545f4f55545055545f","414d4f554e540000000000000000000000000000000000000000000000000000"]}],"gas":39155,"failed":true,"returnValue":"08c379a00000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000000000000000000000000000000000002850756c736558526f757465723a20494e53554646494349454e545f4f55545055545f414d4f554e54000000000000000000000000000000000000000000000000"}}
time_namelookup:  0.000442s
        time_connect:  0.000511s
     time_appconnect:  0.000000s
    time_pretransfer:  0.000536s
       time_redirect:  0.000000s
  time_starttransfer:  0.002027s
                     ----------
          time_total:  0.958280s
```

https://scan.v4.testnet.pulsechain.com/tx/0x3bc9f81494822b8f139f1c1f1e9767b11251d246fd8f17eaa4391d9f9bb1ac65

<img width="1104" alt="image" src="https://user-images.githubusercontent.com/787344/233646548-acb11620-bf57-47da-9dfb-1e63a283d3a4.png">

**Comment by bretep** [comment]
The previous post contains all the information.

- Hardware is sufficient (probably way overkill)
- Total time of the request 0.958280s
- We're not even close to `ETHEREUM_JSONRPC_DEBUG_TRACE_TRANSACTION_TIMEOUT`
- Changing `INDEXER_INTERNAL_TRANSACTIONS_BATCH_SIZE` to a lower number does not change anything.
- https://github.com/blockscout/blockscout/issues/7225#issue-1656245257 still not being decoded.

**Comment by bretep** [comment]
So it seems, for every "Awaiting internal transactions for reason" I'm looking up, they are all `Revert reason (0x08c379a)`. I think blockscout is not decoding reverts correctly. I do not think this is a timeout issue.

**Comment by vbaranov** [comment]
@bretep could you please answer to this question?

> @bretep is the number of internal transactions increasing overtime at all?

> SELECT COUNT(*) FROM internal_transactions;


> Changing INDEXER_INTERNAL_TRANSACTIONS_BATCH_SIZE to a lower number does not change anything.

Which values did you try? Did you try to decrease it down to ~10 ?

**Comment by bretep** [comment]
> @bretep could you please answer to this question?
> 
> > @bretep is the number of internal transactions increasing overtime at all?
> 
> > SELECT COUNT(*) FROM internal_transactions;

After decreasing from 500 to 2 the `internal_transactions` is increasing.

I'll keep an eye out to see if this allows the decoding of the errors.

Is there a way to re-index the transactions that still say "Awaiting internal transactions for reason"?

**Comment by bretep** [comment]
`internal_transactions` are still increasing, currently: `63,220,166`, however, this has not resolved the `Awaiting internal transactions for reason` messages.

Seems like the realtime indexer should be able to decode these messages.

**Comment by vbaranov** [comment]
This should be resolved once more and more internal transactions will be fetched. Health of internal transactions fetcher could be monitored via `SELECT COUNT(*) FROM pending_block_operations;` query. The value should be tend to zero. Is it true in your case?

**Comment by vbaranov** [comment]
Left column doesn't look right - the value should decrease over time.
You say, you're now using Erigon, did you changed ETHEREUM_JSONRPC_VARIANT=geth to ETHEREUM_JSONRPC_VARIANT=erigon?

And try to double INDEXER_INTERNAL_TRANSACTIONS_BATCH_SIZE (from 2 to 4)

**Comment by bretep** [comment]
Yes, you can see the environment variables I am running with above. :) 
I changed `INDEXER_INTERNAL_TRANSACTIONS_BATCH_SIZE=4`

The behavior stayed the same.

However, we turned off our historical indexer, which seems to have resolved the issue.

Side note: Many issues were resolved by turning off a second indexer.

I had two indexers:
1. Real-time indexer
2. Historical indexer (we are indexing ethereum mainnet, and this takes a long time)

I tried to ensure that the appropriate indexers were turned on/off on each. I finally gave up and moved to a single indexer. All the deadlock issues, the performance, and everything improved. 

The downsides:
1. Indexing is going to take much, much longer. Seems like a few years.
2. I would love to have three real-time indexers running for redundancy.
3. I would love to have multiple archive indexers responsible for specific ranges. I initially tried spinning up 20 or so indexers that were responsible for a range of blocks. The deadlocks were killer.

**Comment by JABirchall** [comment]
I would like to add, I have started to experiance this on my explorer.
Seems its just stopped indexing internal transcations, it even knows this and is displaying that it is indexing internal transcations, but it isnt doing anything. 

![](https://i.imgur.com/3s9R1yf.png)

This address is for the uniswap permit2 contact, it has been created using a create2 contract. 

The explorer hasnt seen the internal transcation creating the contract and thinks the address is just a normal wallet address. 
It has seen the execute revert transcation, but can fetch the reason why.

**Comment by vbaranov** [comment]
> Yes, you can see the environment variables I am running with above. :) I changed `INDEXER_INTERNAL_TRANSACTIONS_BATCH_SIZE=4`
> 
> The behavior stayed the same.
> 
> However, we turned off our historical indexer, which seems to have resolved the issue.
> 
> Side note: Many issues were resolved by turning off a second indexer.
> 
> I had two indexers:
> 
> 1. Real-time indexer
> 2. Historical indexer (we are indexing ethereum mainnet, and this takes a long time)
> 
> I tried to ensure that the appropriate indexers were turned on/off on each. I finally gave up and moved to a single indexer. All the deadlock issues, the performance, and everything improved.
> 
> The downsides:
> 
> 1. Indexing is going to take much, much longer. Seems like a few years.
> 2. I would love to have three real-time indexers running for redundancy.
> 3. I would love to have multiple archive indexers responsible for specific ranges. I initially tried spinning up 20 or so indexers that were responsible for a range of blocks. The deadlocks were killer.

@bretep the speed of internal transactions indexing can be increased, if you're using Erigon node by switching to `debug_traceBlockByNumber` method request. You need to set `ETHEREUM_JSONRPC_GETH_TRACE_BY_BLOCK=true` on the backend for that. Iam closing this for now. Please let us know your experience with the new setup.
