### ISSUE TITLE
Linea Testnet: <Issue Title> crusdc read contract on uniswap.

### ISSUE THREAD

**Issue by pachinko99** [blockscout/blockscout#7226]
try to copy contract crusdc on uniswap can't read or visible token on AMM.

All parthner explore collabs with Linea network only work on USDC not crUSDC (mesprotocol etc).

please solved or give response this issue for test network.

### Environment
* Elixir Version: 1.13.1
* Erlang Version: 24
* BlockScout Version: 

* User Agent: `Mozilla/5.0 (Linux; Android 11; Redmi Note 8) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/105.0.0.0 Mobile Safari/537.36`

### Steps to reproduce

*Tell us how to reproduce this issue. If possible, push up a branch to your fork with a regression test we can run to reproduce locally.*

### Expected Behaviour

*Tell us what should happen.*

### Actual Behaviour

*Tell us what happens instead.*

**Comment by vbaranov** [comment]
Please reach out Linea testnet support. There is nothing related to Blockscout explorer in your question.

**Comment by pachinko99** [comment]
oh okay 👌

Pada tanggal Sen, 10 Apr 2023 15.55, Victor Baranov <
***@***.***> menulis:
