### ISSUE TITLE
missing field `deployed_bytecode` & contract verifier failed

### ISSUE THREAD

**Issue by Jaycelv** [blockscout/blockscout#7228]
*Describe your issue here.*

### Environment

* Deployment type (Manual/Docker/Docker-compose):
* Elixir & Erlang/OTP versions (`elixir -version`):
* Node JS version (`node -v`):
* Operating System:
* Blockscout Version/branch/commit: v5.1.2-beta
* Archive node type && version (Erigon/Geth/Nethermind/Ganache/?):

### Steps to reproduce

1. deploy a smart contract.
2. verifier the contract
3. then the error display: missing field `deployed_bytecode` 

![image](https://user-images.githubusercontent.com/99306545/230306781-bf66a1d1-83f7-40be-8eea-1ddb3f0a52e1.png)

Blockscout-rs: https://github.com/blockscout/blockscout-rs/commits/stats/v1.0.0 use this version

**Comment by vbaranov** [comment]
@Jaycelv is the issue resolved?
