### ISSUE TITLE
How can I run blockscout on the aarch64 CPU architecture？

### ISSUE THREAD

**Issue by 13310241314** [blockscout/blockscout#7230]
excuse me!
When I attempted to install blockscout 4.1.8 in the aarch64 CPU architecture, an error was reported during the process of building the Docker image, How can we solve this error?
![3bdd9eba96df7c51d33640533dd1f8f](https://user-images.githubusercontent.com/125418632/230522322-cc5f72cd-6d06-4af0-9f5a-5e4d634137e0.png)

**Comment by harveyff** [comment]
I compile and run from source code, no such problem

**Comment by 13310241314** [comment]
> I compile and run from source code, no such problem

I ran it using Docker Compose

**Comment by vbaranov** [comment]
@13310241314 could you please try https://github.com/blockscout/blockscout/issues/6700#issuecomment-1396669876?

**Comment by vbaranov** [comment]
Please use `blockscout/blockscout:master` Docker image. The issue should resolved there and will be released soon.
