### ISSUE TITLE
RPC API getLogs not working on ETH-Goerli testnet env

### ISSUE THREAD

**Issue by 0xtzData** [blockscout/blockscout#7232]
Example request:
https://eth-goerli.blockscout.com/api?module=logs&action=getLogs&fromBlock=8783459&toBlock=8783457&address=0xf74a5ca65E4552CfF0f13b116113cCb493c580C5
returns 503

**Comment by 0xtzData** [comment]
Need to be reproduced again.

**Comment by vbaranov** [comment]
Opens for me almost immediately after migration to 6.0.0. I am closing this.
