### ISSUE TITLE
How to Run BlockScout in Docker Environment on aarch64 CPU Architecture？

### ISSUE THREAD

**Issue by 13310241314** [blockscout/blockscout#7241]
excuse me!
When I attempted to use docker-compose to install blockscout 4.1.8 in the aarch64 CPU architecture, an error was reported during the process of building the Docker image, How can we solve this error?
cd docker-compose && docker-compose up --build
![b3c7d247df42ce7b9881c0b36ae2283](https://user-images.githubusercontent.com/125418632/230868172-e9b963fc-72b3-4bfe-a0f8-e29f82260cf5.png)

**Comment by vbaranov** [comment]
@13310241314 do you have the same issue with the currently latest erlease 5.1.2?

**Comment by 13310241314** [comment]
> @13310241314 do you have the same issue with the currently latest erlease 5.1.2?

yes, I tried the latest version, but still reported the same error.

**Comment by vbaranov** [comment]
@13310241314 could you please try [this suggestion](https://github.com/blockscout/blockscout/issues/6700#issuecomment-1396669876)?

**Comment by 13310241314** [comment]
> @13310241314 could you please try [this suggestion](https://github.com/blockscout/blockscout/issues/6700#issuecomment-1396669876)?

Thank you for your answer!
But I tried according to your prompts and still made the same error.

**Comment by vbaranov** [comment]
@13310241314 please try the latest docker image with `master` tag. It should resolve the issue. Please let us know if the issue persists.
