### ISSUE TITLE
Wrong decimals in tx_state tab

### ISSUE THREAD

**Issue by 0xtzData** [blockscout/blockscout#7262]
Wrong decimals on main dev stand in `tx_state` tab.
Example tx from Etherscan: https://goerli.etherscan.io/tx/0xede7884da9ee68d77ff632a0f1acd680bb8713fc4381a68ad27b407f0dd89a1d

**Comment by sl1depengwyn** [comment]
Closed in favor of https://github.com/blockscout/frontend/issues/924
