### ISSUE TITLE
how to show more network?

### ISSUE THREAD

**Issue by aoeng** [blockscout/blockscout#7266]
```
NETWORK=mainnet
SUBNETWORK=mainnet
LINK_TO_OTHER_EXPLORERS=false
OTHER_EXPLORERS={}
SUPPORTED_CHAINS=[{title:"mainnet",url:"https://pilotscan.org"},{title:"testnet",url:"https://testnet.pilotscan.org",test_net?:true}]
```
![image](https://user-images.githubusercontent.com/23565714/231638705-7b200d28-f716-4736-86e4-b463049d9c7c.png)
now,Only one can be displayed, there is no way to switch!
I want to show two(mainnet adnd testnet) to toggle,how do i configure?

**Comment by sl1depengwyn** [comment]
Try putting `title` `url` and `test_net?` words in quotation marks like this
`SUPPORTED_CHAINS=[{"title":"mainnet","url":"https://pilotscan.org"},{"title":"testnet","url":"https://testnet.pilotscan.org","test_net?":true}]
`

**Comment by aoeng** [comment]
@sl1depengwyn  thank you
