### ISSUE TITLE
Linea Testnet: RPC error formatting

### ISSUE THREAD

**Issue by pathomphongCh** [blockscout/blockscout#7267]
*Describe your issue here.*

### Environment
* Metamask Version: 10.28.2

* User Agent: `Google chrome Version 112.0.5615.49 (Official Build) (x86_64)`

### Steps to reproduce

1. I transfered ETH from my account to another account. The transaction was pending. 
2. After 24 hr, I `Clear activity and nonce data` in metamask.
3. I try to interact with Linea network by using:
- Hop: https://goerli.hop.exchange/#/send?token=ETH&sourceNetwork=linea&destNetwork=ethereum
- Uni: https://swap.goerli.linea.build/?fbclid=IwAR2Zz6HpXZgVD1a2K2ZPdVAZaxDBQulUio--DKD_TwOPyPiTITEtg-mOcp8#/swap

### Expected Behaviour

Both dapp should be display like the successful or fail tx.

### Actual Behaviour

Both dapp display the error
- Hop error: `An RPC error occurred. Please check your wallet network settings are correct and refresh page to try again.`
- Uni error: `Transaction 26 faied! [ethjs-query] wile formatting outputs from RPC`

**Comment by pathomphongCh** [comment]
Artifacts:
- Hop
![image](https://user-images.githubusercontent.com/53785906/231648777-45a5ef92-098a-4ad2-97f3-51838961b210.png)

- Uni: 
![image](https://user-images.githubusercontent.com/53785906/231649442-79ca960b-bb8f-4603-8bc5-108fc683fd25.png)

- Error from MM
![image](https://user-images.githubusercontent.com/53785906/231649061-ebc60161-4d82-4b14-a0b6-fbcb6fb67393.png)

**Comment by pathomphongCh** [comment]
My network RPC:
![image](https://user-images.githubusercontent.com/53785906/231649842-0fab06d8-04ed-4752-858c-d9dceb4c1d0b.png)

**Comment by pathomphongCh** [comment]
All Transaction: https://explorer.goerli.linea.build/address/0x3C43AA8E525d0CA2fab672CD55F79dE777295e99
![image](https://user-images.githubusercontent.com/53785906/231650119-38c948a4-ad99-4858-b61d-304b9c3ce6dc.png)

**Comment by vbaranov** [comment]
You should contact Linea testnet about this issue. Blockscout team doesn't manage this instance of expolorer.
