### ISSUE TITLE
about install with source code in the Linux system of ARM architecture

### ISSUE THREAD

**Issue by 13310241314** [blockscout/blockscout#7271]
excuse me!
When I tried to install the latest release and 4.1.8 with source code in the Linux of ARM architecture, an error was reported as follows:
![image](https://user-images.githubusercontent.com/125418632/231787898-f7bb6b3c-07a6-4ea8-bfe5-842432b67f2a.png)

 How can we solve this error?

**Comment by vbaranov** [comment]
@13310241314 did you try suggested in red message steps?

**Comment by vbaranov** [comment]
Closing due to no response from the author.
