### ISSUE TITLE
ENV and Database issues 

### ISSUE THREAD

**Issue by Ranofty** [blockscout/blockscout#7272]
*Describe your issue here.*

### Environment

* Deployment type (Manual/Docker/Docker-compose):
* Elixir & Erlang/OTP versions (`v1.13`):
* Node JS version (`node -v`):
* Operating System:
* Blockscout Version/branch/commit: Any version 
* Archive node type && version (Erigon/Geth/Nethermind/Ganache/?):

### Steps to reproduce

I am facing a database error whenever I try to run Blockscout. I have followed the instructions in the Blockscout and Polygon-Edge documentation, but I still encounter the same issue. I use docker-compose, but the problem persists. Sometimes it works, but with database errors in the background. Other times it will work for a few days and then stop working again, and it stops printing blocks and transactions. Can you please help me with this issue?
![IMG_1243](https://user-images.githubusercontent.com/59210788/231788788-452752f0-b08a-4635-b33d-54506f052a25.png)

I face this error also: 
“ ** (Mix) Could not start application explorer: Explorer.Application.start(:normal, []) returned an error: shutdown: failed to start child: Explorer.Chain.Events.Listener
    ** (EXIT) an exception was raised:
        ** (MatchError) no match of right hand side value: {:error, %DBConnection.ConnectionError{message: "tcp connect (localhost:5432): connection refused - :econnrefused", reason: :error, severity: :error}}
            (explorer 4.1.8) lib/explorer/chain/events/listener.ex:17: Explorer.Chain.Events.Listener.init/1
            (stdlib 3.17.1) gen_server.erl:423: :gen_server.init_it/2
            (stdlib 3.17.1) gen_server.erl:390: :gen_server.init_it/6
            (stdlib 3.17.1) proc_lib.erl:226: :proc_lib.init_p_do_apply/3”

I also face this error: 
“ Retrying.
2023-04-08T00:02:10.144 application=indexer fetcher=block_catchup first_block_number=239 last_block_number=235 [error] ** (FunctionClauseError) no function clause matching in EthereumJSONRPC.HTTP.standardize_response/1
    (ethereum_jsonrpc 4.1.8) lib/ethereum_jsonrpc/http.ex:135: EthereumJSONRPC.HTTP.standardize_response(%{"error" => %{"code" => -32600, "message" => "Batch request length too long"}, "jsonrpc" => "2.0"})
    (elixir 1.13.0) lib/enum.ex:1593: Enum."-map/2-lists^map/1-0-"/2
    (ethereum_jsonrpc 4.1.8) lib/ethereum_jsonrpc/http.ex:44: EthereumJSONRPC.HTTP.chunked_json_rpc/3
    (ethereum_jsonrpc 4.1.8) lib/ethereum_jsonrpc/request_coordinator.ex:86: anonymous fn/3 in EthereumJSONRPC.RequestCoordinator.perform/4
    (ethereum_jsonrpc 4.1.8) lib/ethereum_jsonrpc/request_coordinator.ex:106: EthereumJSONRPC.RequestCoordinator.trace_request/2
    (ethereum_jsonrpc 4.1.8) lib/ethereum_jsonrpc.ex:494: EthereumJSONRPC.fetch_blocks_by_params/3
    (indexer 4.1.8) lib/indexer/block/fetcher.ex:131: Indexer.Block.Fetcher.fetch_and_import_range/2
    (indexer 4.1.8) lib/indexer/block/catchup/fetcher.ex:209: Indexer.Block.Catchup.Fetcher.fetch_and_import_range_from_sequence/3
    (elixir 1.13.0) lib/task/supervised.ex:89: Task.Supervised.invoke_mfa/2
    (elixir 1.13.0) lib/task/supervised.ex:34: Task.Supervised.reply/4
    (stdlib 3.17.1) proc_lib.erl:226: :proc_lib.init_p_do_apply/3”

I think this errors should be from My ENV settings and DB settings please someone should help me with the correct thing to do please 🙏 

### Expected behaviour
Working normal 
### Actual behaviour
Not Refreshing transactions also DB errors
*Tell us what happens instead.*

**Comment by vbaranov** [comment]
@Ranofty which command did you use exactly to run Blockscout? Did you set `DATABASE_URL` environment variable? Did you run Postgres DB via docker-compose as well?

**Comment by Ranofty** [comment]
> DATABASE_URL

Yeah I use `DATABASE_URL` and all what I do in docker is after setting up everything in env file I run this command `docker-compose up --build` I think that run run everything including the postgres DB. Also I always use AWS Postgres DB I don’t know if that can cause an issue also. And in Manual deployment I use both Blockcout, Polygon Edge and Dogechain docs but still same issues

**Comment by vbaranov** [comment]
If you're using external DB URL, it worth to remove db container from docker-compose:
https://github.com/blockscout/blockscout/blob/master/docker-compose/docker-compose.yml#L9-L12
https://github.com/blockscout/blockscout/blob/master/docker-compose/docker-compose.yml#L17
https://github.com/blockscout/blockscout/blob/master/docker-compose/docker-compose.yml#L36-L37

and you should set correct DATABASE_URL to external DB on AWS.

**Comment by Ranofty** [comment]
How about for the manual deployment? What should I do?

**Comment by Ranofty** [comment]
> If you're using external DB URL, it worth to remove db container from docker-compose: https://github.com/blockscout/blockscout/blob/master/docker-compose/docker-compose.yml#L9-L12 https://github.com/blockscout/blockscout/blob/master/docker-compose/docker-compose.yml#L17 https://github.com/blockscout/blockscout/blob/master/docker-compose/docker-compose.yml#L36-L37
> 
> and you should set correct DATABASE_URL to external DB on AWS.

How about for the manual deployment? What should I do?

**Comment by Ranofty** [comment]
> You told, that you use `docker-compose up --build` for running explorer, right? Thus, before running it, it worth to remove that lines from docker-compose.yml, which I mentioned above, in order to remove runnning DB container since you're using external DB.

I think using internal DB will be much better how do I create internal DB please 🙏 or by running `docker-compose up --build` it create DB and integrate it and all?

**Comment by vbaranov** [comment]
Yes, `docker-compose up --build` deploys Postgres container with an empty DB, deploys DB schema there and Blockscout is connected to it until you provide another DATABASE_URL.

**Comment by Ranofty** [comment]
> Yes, `docker-compose up --build` deploys Postgres container with an empty DB, deploys DB schema there and Blockscout is connected to it until you provide another DATABASE_URL.

So meaning if I didn’t provide this `DATABASE_URL` it will do everything it self right?

**Comment by Ranofty** [comment]
> Just leave it as is. You just need to provide `ETHEREUM_JSONRPC_HTTP_URL` to the node.

hello after doing what you said i end up getting this error 

`blockscout    |
blockscout    | Retrying.
blockscout    | 2023-04-15T00:52:23.200 application=indexer fetcher=block_catchup first_block_number=112629 last_block_number=112625 [error] ** (FunctionClauseError) no function clause matching in EthereumJSONRPC.HTTP.standardize_response/1
blockscout    |     (ethereum_jsonrpc 4.1.8) lib/ethereum_jsonrpc/http.ex:135: EthereumJSONRPC.HTTP.standardize_response(%{"error" => %{"code" => -32600, "message" => "Batch request length too long"}, "jsonrpc" => "2.0"})
blockscout    |     (elixir 1.13.1) lib/enum.ex:1593: Enum."-map/2-lists^map/1-0-"/2
blockscout    |     (ethereum_jsonrpc 4.1.8) lib/ethereum_jsonrpc/http.ex:44: EthereumJSONRPC.HTTP.chunked_json_rpc/3
blockscout    |     (ethereum_jsonrpc 4.1.8) lib/ethereum_jsonrpc/request_coordinator.ex:86: anonymous fn/3 in EthereumJSONRPC.RequestCoordinator.perform/4
blockscout    |     (ethereum_jsonrpc 4.1.8) lib/ethereum_jsonrpc/request_coordinator.ex:106: EthereumJSONRPC.RequestCoordinator.trace_request/2
blockscout    |     (ethereum_jsonrpc 4.1.8) lib/ethereum_jsonrpc.ex:494: EthereumJSONRPC.fetch_blocks_by_params/3
blockscout    |     (indexer 4.1.8) lib/indexer/block/fetcher.ex:131: Indexer.Block.Fetcher.fetch_and_import_range/2
blockscout    |     (indexer 4.1.8) lib/indexer/block/catchup/fetcher.ex:209: Indexer.Block.Catchup.Fetcher.fetch_and_import_range_from_sequence/3
blockscout    |
blockscout    |
blockscout    | Retrying.
blockscout    | 2023-04-15T00:52:23.200 application=indexer fetcher=block_catchup first_block_number=112609 last_block_number=112605 [error] ** (FunctionClauseError) no function clause matching in EthereumJSONRPC.HTTP.standardize_response/1
blockscout    |     (ethereum_jsonrpc 4.1.8) lib/ethereum_jsonrpc/http.ex:135: EthereumJSONRPC.HTTP.standardize_response(%{"error" => %{"code" => -32600, "message" => "Batch request length too long"}, "jsonrpc" => "2.0"})
blockscout    |     (elixir 1.13.1) lib/enum.ex:1593: Enum."-map/2-lists^map/1-0-"/2
blockscout    |     (ethereum_jsonrpc 4.1.8) lib/ethereum_jsonrpc/http.ex:44: EthereumJSONRPC.HTTP.chunked_json_rpc/3
blockscout    |     (ethereum_jsonrpc 4.1.8) lib/ethereum_jsonrpc/request_coordinator.ex:86: anonymous fn/3 in EthereumJSONRPC.RequestCoordinator.perform/4
blockscout    |     (ethereum_jsonrpc 4.1.8) lib/ethereum_jsonrpc/request_coordinator.ex:106: EthereumJSONRPC.RequestCoordinator.trace_request/2
blockscout    |     (ethereum_jsonrpc 4.1.8) lib/ethereum_jsonrpc.ex:494: EthereumJSONRPC.fetch_blocks_by_params/3
blockscout    |     (indexer 4.1.8) lib/indexer/block/fetcher.ex:131: Indexer.Block.Fetcher.fetch_and_import_range/2
blockscout    |     (indexer 4.1.8) lib/indexer/block/catchup/fetcher.ex:209: Indexer.Block.Catchup.Fetcher.fetch_and_import_range_from_sequence/3
blockscout    |
blockscout    |
blockscout    | Retrying.
blockscout    | 2023-04-15T00:52:23.201 application=indexer fetcher=block_catchup first_block_number=112614 last_block_number=112610 [error] ** (FunctionClauseError) no function clause matching in EthereumJSONRPC.HTTP.standardize_response/1
blockscout    |     (ethereum_jsonrpc 4.1.8) lib/ethereum_jsonrpc/http.ex:135: EthereumJSONRPC.HTTP.standardize_response(%{"error" => %{"code" => -32600, "message" => "Batch request length too long"}, "jsonrpc" => "2.0"})
blockscout    |     (elixir 1.13.1) lib/enum.ex:1593: Enum."-map/2-lists^map/1-0-"/2
blockscout    |     (ethereum_jsonrpc 4.1.8) lib/ethereum_jsonrpc/http.ex:44: EthereumJSONRPC.HTTP.chunked_json_rpc/3
blockscout    |     (ethereum_jsonrpc 4.1.8) lib/ethereum_jsonrpc/request_coordinator.ex:86: anonymous fn/3 in EthereumJSONRPC.RequestCoordinator.perform/4
blockscout    |     (ethereum_jsonrpc 4.1.8) lib/ethereum_jsonrpc/request_coordinator.ex:106: EthereumJSONRPC.RequestCoordinator.trace_request/2
blockscout    |     (ethereum_jsonrpc 4.1.8) lib/ethereum_jsonrpc.ex:494: EthereumJSONRPC.fetch_blocks_by_params/3
blockscout    |     (indexer 4.1.8) lib/indexer/block/fetcher.ex:131: Indexer.Block.Fetcher.fetch_and_import_range/2
blockscout    |     (indexer 4.1.8) lib/indexer/block/catchup/fetcher.ex:209: Indexer.Block.Catchup.Fetcher.fetch_and_import_range_from_sequence/3
blockscout    |
blockscout    |
blockscout    | Retrying.
blockscout    | 2023-04-15T00:52:23.201 application=indexer fetcher=block_catchup first_block_number=112649 last_block_number=112645 [error] ** (FunctionClauseError) no function clause matching in EthereumJSONRPC.HTTP.standardize_response/1
blockscout    |     (ethereum_jsonrpc 4.1.8) lib/ethereum_jsonrpc/http.ex:135: EthereumJSONRPC.HTTP.standardize_response(%{"error" => %{"code" => -32600, "message" => "Batch request length too long"}, "jsonrpc" => "2.0"})
blockscout    |     (elixir 1.13.1) lib/enum.ex:1593: Enum."-map/2-lists^map/1-0-"/2
blockscout    |     (ethereum_jsonrpc 4.1.8) lib/ethereum_jsonrpc/http.ex:44: EthereumJSONRPC.HTTP.chunked_json_rpc/3
blockscout    |     (ethereum_jsonrpc 4.1.8) lib/ethereum_jsonrpc/request_coordinator.ex:86: ano^Z`

**Comment by Ranofty** [comment]
> Just leave it as is. You just need to provide `ETHEREUM_JSONRPC_HTTP_URL` to the node.

Hello after doing this here is the result that i am getting [http://3.236.21.177:4000/](url) is just saying this _"0% Blocks Indexed - We're indexing this chain right now. Some of the counts may be inaccurate."_ nothing more and it keep on giving me indexing error and this previous error 

`blockscout    | Retrying. blockscout    | 2023-04-15T00:52:23.200 application=indexer fetcher=block_catchup first_block_number=112609 last_block_number=112605 [error] ** (FunctionClauseError) no function clause matching in EthereumJSONRPC.HTTP.standardize_response/1 blockscout    |     (ethereum_jsonrpc 4.1.8) lib/ethereum_jsonrpc/http.ex:135: EthereumJSONRPC.HTTP.standardize_response(%{"error" => %{"code" => -32600, "message" => "Batch request length too long"}, "jsonrpc" => "2.0"}) blockscout    |     (elixir 1.13.1) lib/enum.ex:1593: Enum."-map/2-lists^map/1-0-"/2 blockscout    |     (ethereum_jsonrpc 4.1.8) lib/ethereum_jsonrpc/http.ex:44: EthereumJSONRPC.HTTP.chunked_json_rpc/3 blockscout    |     (ethereum_jsonrpc 4.1.8) lib/ethereum_jsonrpc/request_coordinator.ex:86: anonymous fn/3 in EthereumJSONRPC.RequestCoordinator.perform/4 blockscout    |     (ethereum_jsonrpc 4.1.8) lib/ethereum_jsonrpc/request_coordinator.ex:106: EthereumJSONRPC.RequestCoordinator.trace_request/2 blockscout    |     (ethereum_jsonrpc 4.1.8) lib/ethereum_jsonrpc.ex:494: EthereumJSONRPC.fetch_blocks_by_params/3 blockscout    |     (indexer 4.1.8) lib/indexer/block/fetcher.ex:131: Indexer.Block.Fetcher.fetch_and_import_range/2 blockscout    |     (indexer 4.1.8) lib/indexer/block/catchup/fetcher.ex:209: Indexer.Block.Catchup.Fetcher.fetch_and_import_range_from_sequence/3 blockscout    | blockscout    | blockscout    `

![iScreen Shoter - Google Chrome - 230417085150](https://user-images.githubusercontent.com/59210788/232420477-b65cf1b3-67ee-4bcb-b6df-7457a3ce849c.png)

**Comment by vbaranov** [comment]
@Ranofty which client do you use for RPC endpoint under the hood?

**Comment by Ranofty** [comment]
> @Ranofty which client do you use for RPC endpoint under the hood?

I fork Dogechain which i think the are using Geth

**Comment by vbaranov** [comment]
@Ranofty please also set:
```
INDEXER_COIN_BALANCES_BATCH_SIZE=10
```

Blockscout should be compatible with latest Ploygon Edge. You're talking about this node, right? You can decrease batch sized on Blockscout side, as I describide above. Or you can increase default one, which is relatevely small, on the node side.

**Comment by Ranofty** [comment]
> @Ranofty please also set:
> 
> ```
> INDEXER_COIN_BALANCES_BATCH_SIZE=10
> ```
> 
> Blockscout should be compatible with latest Ploygon Edge. You're talking about this node, right? You can decrease batch sized on Blockscout side, as I describide above. Or you can increase default one, which is relatevely small, on the node side.

I already increase it like that

**Comment by vbaranov** [comment]
Try to decrease it until error is gone. Or check Polygon Edge manual in order to increase available batch size.

**Comment by WSbaikaishui** [comment]
i try to deploy a optimism stack ,and everything is ok,except blockscout,I did meet this mistake too. I can't see any blocks in my explorer, is there are some solutions ?

**Comment by vbaranov** [comment]
@Ranofty I am closing this. Please, let me know if you still face the issue.

**Comment by haidarabdillah** [comment]
seem i have some problem like this, any solving?

**Comment by Ranofty** [comment]
> seem i have some problem like this, any solving? 

Use Docker

**Comment by haidarabdillah** [comment]
> > seem i have some problem like this, any solving?
> 
> Use Docker

can you share your common-blockscout.env
i already run on eth and ganache base, but got a bunch error on polygon_edge (like dogechain)

![image](https://github.com/blockscout/blockscout/assets/113880800/a2df0a47-60be-4af3-a28d-ea2db93feb7a)

**Comment by Ranofty** [comment]
> > > seem i have some problem like this, any solving?
> 
> > 
> 
> > Use Docker
> 
> 
> 
> can you share your common-blockscout.env
> 
> i already run on eth and ganache base, but got a bunch error on polygon_edge (like dogechain)
> 
> 
> 
> ![image](https://github.com/blockscout/blockscout/assets/113880800/a2df0a47-60be-4af3-a28d-ea2db93feb7a)
> 
> 
> 
> 

Use Geth Ethereum Go Layer2

**Comment by haidarabdillah** [comment]
> Use Geth Ethereum Go Layer2

im use 
Explorer: https://explorer-devnet.dogechain.dog/
ChainID: 668
RPC Endpoints:
https://rpc-devnet.dogechain.dog/


can you help me the .env setting to running this chains?  it's use polygon_edge, i just try chain 

CHAIN_TYPE=polygon_edge
BLOCK_TRANSFORMER= clique

but th result is same

**Comment by Ranofty** [comment]
> 
> 
> > Use Geth Ethereum Go Layer2
> 
> 
> 
> im use 
> 
> Explorer: https://explorer-devnet.dogechain.dog/
> 
> ChainID: 668
> 
> RPC Endpoints:
> 
> https://rpc-devnet.dogechain.dog/
> 
> 
> 
> 
> 
> can you help me the .env setting to running this chains?  it's use polygon_edge, i just try chain 
> 
> 
> 
> CHAIN_TYPE=polygon_edge
> 
> BLOCK_TRANSFORMER= clique
> 
> 
> 
> but th result is same
> 
> 

DM on TG bro @Ranofty

**Comment by haidarabdillah** [comment]
> DM on TG bro @Ranofty

twitter or telegram?  do you have telegram ?

**Comment by Ranofty** [comment]
> > DM on TG bro @Ranofty
> 
> 
> 
> twitter or telegram?  do you have telegram ?

Telegram

**Comment by haidarabdillah** [comment]
> > > DM on TG bro @Ranofty
> > 
> > 
> > twitter or telegram?  do you have telegram ?
> 
> Telegram

ceck your telegram bro
