### ISSUE TITLE
Testnet: IDE Not Claiming

### ISSUE THREAD

**Issue by NASIMUDDIN12** [blockscout/blockscout#7275]
*Describe your issue here.*

### Environment
* Elixir Version: 1.12.2
* Erlang Version: 24
* BlockScout Version: 

* User Agent: `Mozilla/5.0 (Linux; Android 11; RMX3286) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/105.0.0.0 Mobile Safari/537.36`

### Steps to reproduce

*Tell us how to reproduce this issue. If possible, push up a branch to your fork with a regression test we can run to reproduce locally.*

### Expected Behaviour

*Tell us what should happen.*

### 2 times i request for faucet but got only WETH

*Tell us what happens instead.*

**Comment by vbaranov** [comment]
Closing, because doesn't relate to Blockscout explorer.
