### ISSUE TITLE
Canto: <Blocks are not indexed on time, 1 day behind>

### ISSUE THREAD

**Issue by jhaigcg** [blockscout/blockscout#7289]
*Describe your issue here.*
Blocks on https://evm.explorer.canto.io/ are 1 day behind https://tuber.build/.

### Environment
* Elixir Version: 1.13.4
* Erlang Version: 24
* BlockScout Version: 

* User Agent: `Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/112.0.0.0 Safari/537.36`

### Steps to reproduce

*Tell us how to reproduce this issue. If possible, push up a branch to your fork with a regression test we can run to reproduce locally.*

### Expected Behaviour

*Tell us what should happen.*

### Actual Behaviour

*Tell us what happens instead.*

**Comment by vbaranov** [comment]
Indexer caught up the head of the chain.
