### ISSUE TITLE
mix do deps.get mix.exs:37: Mix.Release.__struct__/0 is undefined,

### ISSUE THREAD

**Issue by ZebroTech** [blockscout/blockscout#7299]
After export DATABASE_URL=postgresql://user:password@localhost:5432/blockscout when try compile 'mix do deps.get" it throws following error.

** (CompileError) mix.exs:37: Mix.Release.__struct__/0 is undefined, cannot expand struct Mix.Release
    (stdlib) lists.erl:1354: :lists.mapfoldl/3

don't know if it is duplicated issue, thanks in advance.

**Comment by vbaranov** [comment]
Which version of Elixir, Erlang/OTP are you on?

**Comment by ZebroTech** [comment]
Erlang/OTP 20 [erts-9.2]

**Comment by ZebroTech** [comment]
> Which version of Elixir, Erlang/OTP are you on?

Erlang/OTP 20 [erts-9.2]

**Comment by vbaranov** [comment]
Please, take a look to requirements https://docs.blockscout.com/for-developers/information-and-settings/requirements

**Comment by ZebroTech** [comment]
> Please, take a look to requirements https://docs.blockscout.com/for-developers/information-and-settings/requirements

should install OTP24.
it's on Ubuntu 18.04

**Comment by vbaranov** [comment]
You can also use [docker-compose](https://github.com/blockscout/blockscout/tree/master/docker-compose).

**Comment by ZebroTech** [comment]
> You can also use [docker-compose](https://github.com/blockscout/blockscout/tree/master/docker-compose).

Running characterised ethereum private chain starts with cmd  'gozebro' instead of 'geth'.
Do I need to export/edit anything such as cmd 'gozebro', DATABASE_URL, ETHEREUM_JSONRPC_VARIANT, JSONRPC_HTTP_URL, COIN, MIX_ENV etc. to run blockscout in docker-container?

**Comment by ZebroTech** [comment]
> You can also use [docker-compose](https://github.com/blockscout/blockscout/tree/master/docker-compose).

root@vmi292469:~/blockscout/docker-compose# docker-compose up --build
ERROR: Version in "./docker-compose.yml" is unsupported. You might be seeing this error because you're using the wrong Compose file version. Either specify a supported version (e.g "2.2" or "3.3") and place your service definitions under the `services` key, or omit the `version` key and place your service definitions at the root of the file to use version 1.

**Comment by vbaranov** [comment]
You have most likely outdated version of docker-compose. Try to update to v2

**Comment by ZebroTech** [comment]
> You have most likely outdated version of docker-compose. Try to update to v2

using https://github.com/docker/compose#docker-compose-v2

now error is 
ERROR: Invalid interpolation format for "blockscout" option in service "services": "blockscout/blockscout:${DOCKER_TAG:-latest}"

**Comment by vbaranov** [comment]
How did you run docker-compose and full error please?

**Comment by ZebroTech** [comment]
> How did you run docker-compose and full error please?

downloaded docker-compose v2 and moved to /usr/lib/docker/cli-plugins.

cd blockscout/docker-copose

docker-compose up --build

ERROR: Version in "./docker-compose.yml" is unsupported. You might be seeing this error because you're using the wrong Compose file version. Either specify a supported version (e.g "2.2" or "3.3") and place your service definitions under the `services` key, or omit the `version` key and place your service definitions at the root of the file to use version 1.
For more on the Compose file format versions, see https://docs.docker.com/compose/compose-file/

cd blockscout
docker-compose up --build

ERROR:
        Can't find a suitable configuration file in this directory or any
        parent. Are you in the right directory?

        Supported filenames: docker-compose.yml, docker-compose.yaml

**Comment by ZebroTech** [comment]
> You should run from `blockscout/docker-copose`. Please send the result of `docker-compose --version`

root@vmi292469:~/blockscout/docker-compose# docker-compose --version
docker-compose version 1.17.1, build unknown

**Comment by vbaranov** [comment]
You didn't update docker-compose to v2. Please do that.

**Comment by ZebroTech** [comment]
> You didn't update docker-compose to v2. Please do that.

Ah, okay. thanks

BTW for manual deployment I upgraded erlang otp 25 
I have finished steps until export SECRET_KEY_BASE, 
And now want to set environment variables.
I am running node on local machine go-ethereum forked using cmd 'gozebro' instead of 'geth' .
So do I have to 'export ETHEREUM_JSONRPC_VARIANT=gozebro'?
Also do I have to export everything as in example file Gnosis-Chain-Variables.txt?

**Comment by ZebroTech** [comment]
> > So do I have to export ETHEREUM_JSONRPC_VARIANT='gozebro' or 'geth' (since blockscout only supports 'geth' and other 4 variants?
> 
> You should still use even if it is a fork of Geth.
> 
> > Also do I have to export everything as in example file Gnosis-Chain-Variables.txt?
> 
> No. The minimal set of env variables consists of env vars marked as "Required" in https://docs.blockscout.com/for-developers/information-and-settings/env-variables. There are only 4.

Will it do if I export following variables including required ones. (got other variables from nethermind template)

 Variable Required
 ------------------
 DATABASE_URL=postgresql://user:password@localhost::5432/db_name
 ETHEREUM_JSONRPC_VARIANT=gozebro
 ETHEREUM_JSONRPC_HTTP_URL=http://localhost:8587

 Other variables from nethermind template 
 -------------------------------------------
LOGO=/images/gc_logo_rebrand.svg

FOOTER_LOGO=/images/gc_logo_rebrand.svg

NETWORK=(ZSC)

SUBNETWORK=ZSC Chain

LINK_TO_OTHER_EXPLORERS=false

COIN=ZEBRO

COIN_NAME=Zebrocoin

BLOCKSCOUT_VERSION=v4.1.3-beta

CACHE_TXS_COUNT_PERIOD=7200

CACHE_BLOCK_COUNT_PERIOD=7200

PORT=4000

ALLOWED_EVM_VERSIONS=homestead, eip150Block, eip155Block, eip158Block, byzantium, constantinople, petersburg, istanbul, berlin, default

POOL_SIZE=120

POOL_SIZE_API=400

BLOCKSCOUT_HOST=explorer.zebrocoin.info

SUPPORTED_CHAINS=[ { "title": "ZSC Mainnet", "url": "https://explorer.zebrocoin.info" }, { "title": "ZSC Mainnet", "url": "https://zebroscan.zebrocoin.info" }, { "title": "ZSC Testnet", "url": "https://testplorer.zebrocoin.info", "test_net?": true }, { "title": "ZSC Testnet", "url": "https://testnet-zebroscan.zebrocoin.info", "test_net?": true } ]

GRAPHIQL_TRANSACTION=0x

SHOW_PRICE_CHART=true

SHOW_TXS_CHART=true

TXS_STATS_ENABLED=true

HISTORY_FETCH_INTERVAL=240

TXS_HISTORIAN_INIT_LAG=0

TXS_STATS_DAYS_TO_COMPILE_AT_INIT=10

COIN_BALANCE_HISTORY_DAYS=90

APPS_MENU=true

TOKEN_METADATA_UPDATE_INTERVAL=1800

GAS_PRICE=1

CACHE_TOKEN_EXCHANGE_RATE_PERIOD=3600000

CACHE_TOTAL_GAS_USAGE_PERIOD=7200

CACHE_ADDRESS_TRANSACTIONS_GAS_USAGE_COUNTER_PERIOD=14400

SOURCIFY_INTEGRATION_ENABLED=true

CHAIN_ID=786786

APPS=[{"title": "ZEBRO STAKE", "url": "https://zebrocoin.info/stake"}]

BRIDGES=[{"title": "ZEBRO BRIDGE 1", "url": "https://zebrocoin.info/bridge"}]

DEFI_MENU_LIST=[{"title": "ZEBRO SWAP", "url": "https://zebrocoin.info/swap"}]

NFT_MENU_LIST=[{"title": "ZEBRO NFT", "url": "https://zebrocoin.info/nft"}]

TOKEN_BALANCE_ON_DEMAND_FETCHER_THRESHOLD_MINUTES=60

GAS_PRICE_ORACLE_NUM_OF_BLOCKS=200

GAS_PRICE_ORACLE_SAFELOW_PERCENTILE=35

GAS_PRICE_ORACLE_AVERAGE_PERCENTILE=60

GAS_PRICE_ORACLE_FAST_PERCENTILE=90

GAS_PRICE_ORACLE_CACHE_PERIOD=300

DISPLAY_TOKEN_ICONS=true

API_RATE_LIMIT=100

API_RATE_LIMIT_BY_KEY=30

API_RATE_LIMIT_BY_IP=30

INDEXER_MEMORY_LIMIT=7

Thanks a lot.

**Comment by ZebroTech** [comment]
HI any help will be appreciated, 

getting following error  while building 'smart contract verification' from source.

error: failed to run custom build command for `smart-contract-verifier-proto v0.1.0 (/root/.cargo/git/checkouts/blockscout-rs-1329d74b8bb8dea8/745db1d/smart-contract-verifier/smart-contract-verifier-proto)`

Caused by:
  process didn't exit successfully: `/tmp/cargo-install0o5gOI/release/build/smart-contract-verifier-proto-23e2d19bf207ae04/build-script-build` (exit status: 1)
  --- stdout
  cargo:rerun-if-changed=proto/

  --- stderr
  Error: Custom { kind: Other, error: "protoc failed: Unknown flag: --openapiv2_opt\n" }
warning: build failed, waiting for other jobs to finish...
error: failed to compile `smart-contract-verifier-server v0.1.0 (https://github.com/blockscout/blockscout-rs#745db1d0)`, intermediate artifacts can be found at `/tmp/cargo-install0o5gOI`

thanks in advance.

**Comment by vbaranov** [comment]
I am closing this issue since original problem resolved. Please don't mix different questions in a single issue. If you still have any issue, please let us know by creating a new one.
