### ISSUE TITLE
Indexing gets slower and slower

### ISSUE THREAD

**Issue by shufps** [blockscout/blockscout#7300]
We have a lot of problems with Blockscout. First indexing runns smoothly but it gradually gets slower and slower up to a point where a lot of queries get canceled and it seems to never finish.

Also random 500 server errors get more and more frequent.

We sync a chain that has about 500k blocks in total and we tried to get Blockscout synced. But after it surpassed the 100k timeouts are so frequent that it seems to be impossible to ever get it synced completly.

We also had lots of deadlocks but with the PR https://github.com/blockscout/blockscout/pull/6778 they are gone. But the timeout problem persists.

Also reducing every `_CONCURRENCY` to 1 only relaxes the problem for a bit but then it starts again.

Naively I would think that indexes in the database are missing ... (or perhaps too many?) :man_shrugging: 

### Environment

Docker 5.1.1 to 5.1.3-beta and PR-6778
Archiv node but own eth-compatible chain with total of 500k blocks
Server Ryzen 5 3600 + 64GB RAM + 1TB NVME

### Expected behaviour

It shouldn't get slower and slower causing more and more timeouts and 500 server errors

### Actual behaviour

The oppositve from "Expected behaviour".

**Comment by shufps** [comment]
Here a bit what I saw:

One query that was often aborted is the following:

```
2023-04-18 08:13:40.917 UTC [415] LOG:  duration: 20857.541 ms  execute <unnamed>: INSERT INTO "addresses" AS a0 ("contract_code","decompiled","fetched_coin_balance","fetched_coin_balance_block_number","hash","inserted_at","updated_at","verified") VALUES ($1,$2,$3,$4,$5,$6,$7,$8) ON CONFLICT ("hash") DO UPDATE SET "contract_code" = COALESCE(EXCLUDED.contract_code, a0."contract_code"), "fetched_coin_balance" = CASE WHEN EXCLUDED.fetched_coin_balance_block_number IS NOT NULL
              AND EXCLUDED.fetched_coin_balance IS NOT NULL AND
                  (a0."fetched_coin_balance" IS NULL OR a0."fetched_coin_balance_block_number" IS NULL OR
                   EXCLUDED.fetched_coin_balance_block_number >= a0."fetched_coin_balance_block_number") THEN
                    EXCLUDED.fetched_coin_balance
             ELSE a0."fetched_coin_balance"
        END
        , "fetched_coin_balance_block_number" = GREATEST(EXCLUDED.fetched_coin_balance_block_number, a0."fetched_coin_balance_block_number"), "nonce" = GREATEST(EXCLUDED.nonce, a0."nonce"), "updated_at" = GREATEST(a0."updated_at", EXCLUDED.updated_at) WHERE ((COALESCE(a0."contract_code", EXCLUDED.contract_code) IS DISTINCT FROM a0."contract_code" OR EXCLUDED.fetched_coin_balance_block_number IS NOT NULL AND (a0."fetched_coin_balance_block_number" IS NULL OR EXCLUDED.fetched_coin_balance_block_number >= a0."fetched_coin_balance_block_number")) OR GREATEST(a0."nonce", EXCLUDED.nonce) IS DISTINCT FROM  a0."nonce") RETURNING "updated_at","inserted_at","gas_used","token_transfers_count","transactions_count","verified","decompiled","nonce","contract_code","fetched_coin_balance_block_number","fetched_coin_balance","hash"
```

with
```
2023-04-18 08:13:40.917 UTC [415] DETAIL:  parameters: $1 = '\x', $2 = 'f', $3 = '0', $4 = '411598', $5 = '\x0000000000000000000000000000000000000000', $6 = '2023-04-18 08:13:20.059227', $7 = '2023-04-18 08:13:20.059227', $8 = 'f'
```

`explain` says:

```
blockscout=# explain (analyze, buffers) INSERT INTO "addresses" AS a0 ("contract_code","decompiled","fetched_coin_balance","fetched_coin_balance_block_number","hash","inserted_at","updated_at","verified") VALUES ('\x','f','0','411598','\x0000000000000000000000000000000000000000','2023-04-18 08:13:20.059227','2023-04-18 08:13:20.059227','f') ON CONFLICT ("hash") DO UPDATE SET "contract_code" = COALESCE(EXCLUDED.contract_code, a0."contract_code"), "fetched_coin_balance" = CASE WHEN EXCLUDED.fetched_coin_balance_block_number IS NOT NULL AND EXCLUDED.fetched_coin_balance IS NOT NULL AND (a0."fetched_coin_balance" IS NULL OR a0."fetched_coin_balance_block_number" IS NULL OR EXCLUDED.fetched_coin_balance_block_number >= a0."fetched_coin_balance_block_number") THEN EXCLUDED.fetched_coin_balance ELSE a0."fetched_coin_balance" END, "fetched_coin_balance_block_number" = GREATEST(EXCLUDED.fetched_coin_balance_block_number, a0."fetched_coin_balance_block_number"), "nonce" = GREATEST(EXCLUDED.nonce, a0."nonce"), "updated_at" = GREATEST(a0."updated_at", EXCLUDED.updated_at) WHERE ((COALESCE(a0."contract_code", EXCLUDED.contract_code) IS DISTINCT FROM a0."contract_code" OR EXCLUDED.fetched_coin_balance_block_number IS NOT NULL AND (a0."fetched_coin_balance_block_number" IS NULL OR EXCLUDED.fetched_coin_balance_block_number >= a0."fetched_coin_balance_block_number")) OR GREATEST(a0."nonce", EXCLUDED.nonce) IS DISTINCT FROM  a0."nonce") RETURNING "updated_at","inserted_at","gas_used","token_transfers_count","transactions_count","verified","decompiled","nonce","contract_code","fetched_coin_balance_block_number","fetched_coin_balance","hash"
;
                                                                                                                                                                                        QUERY PLAN                                                                             
                                                                                                           
-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
-----------------------------------------------------------------------------------------------------------
 Insert on addresses a0  (cost=0.00..0.01 rows=1 width=156) (actual time=1267.469..1267.469 rows=0 loops=1)
   Conflict Resolution: UPDATE
   Conflict Arbiter Indexes: addresses_pkey
   Conflict Filter: ((COALESCE(a0.contract_code, excluded.contract_code) IS DISTINCT FROM a0.contract_code) OR ((excluded.fetched_coin_balance_block_number IS NOT NULL) AND ((a0.fetched_coin_balance_block_number IS NULL) OR (excluded.fetched_coin_balance_block_number >= 
a0.fetched_coin_balance_block_number))) OR (GREATEST(a0.nonce, excluded.nonce) IS DISTINCT FROM a0.nonce))
   Rows Removed by Conflict Filter: 1
   Tuples Inserted: 0
   Conflicting Tuples: 1
   Buffers: shared hit=18 dirtied=1
   ->  Result  (cost=0.00..0.01 rows=1 width=156) (actual time=0.002..0.003 rows=1 loops=1)
 Planning:
   Buffers: shared hit=82
 Planning Time: 0.362 ms
 Execution Time: 1267.883 ms
(13 rows)
```

**Comment by Qwerty5Uiop** [comment]
Hi @shufps! I'm investigating the timeouts problem right now. Could you provide a little bit more info please:

- does the speed return to normal if you restart the instance?
- do you have any examples of error logs of these random server errors?

**Comment by shufps** [comment]
`does the speed return to normal if you restart the instance?`

No, restarting doesn't solve the problem, unfortunately :disappointed: 

`do you have any examples of error logs of these random server errors?`

Yes, it's the default error-message that suggests to increase the pool size or tweak two parameters `":queue_target` and `:queue_interval`. Probably you have seen it a lot :sweat_smile: 

It seems, I could reduce the 500 server errors a bit by increasing the default `API_POOL_SIZE` from the default value `10` to `50` but I'm not sure if it will fix it completly.

The main problems we have is during syncing. Timeouts on `insert`s perhaps indicate that the database is rebuilding the indexes after each insert and this could take longer and longer time. 

As mentioned earlier, it seems to be impossible to completly sync the chain with a total of 500k blocks (we got it to 72% and there it's stuck for days and restarting doesn't help) because it cannot make progress because `inserts` cause timeouts.

I suspect that 500 errors on the web UI also would be gone if we could finish syncing :thinking: :man_shrugging: 


--
This are the custom-settings we are using:

```
(I removed URLs to our chain)
DATABASE_URL: "postgresql://blockscout:blockscout@postgres:5432/blockscout?ssl=false"
INDEXER_DISABLE_INTERNAL_TRANSACTIONS_FETCHER: 'false'
INDEXER_MEMORY_LIMIT: 8G
TRACE_FIRST_BLOCK: 1
FIRST_BLOCK: 1
INDEXER_CATCHUP_BLOCKS_CONCURRENCY: 3
INDEXER_INTERNAL_TRANSACTIONS_CONCURRENCY: 3
POOL_SIZE: 100
POOL_SIZE_API: 50 
```

and Postgres-Settings:
```
- postgres
- -cmax_connections=250
- -cshared_buffers=8GB
- -cwal_buffers=64MB
- -csynchronous_commit=off
- -cwork_mem=128MB
- -cmax_wal_size=4GB
- -ceffective_cache_size=32GB
- -cmaintenance_work_mem=1GB
- -cenable_partitionwise_aggregate=on
- -cenable_partitionwise_join=on
- -clog_min_duration_statement=1000
#        - -clog_statement=all
- -clogging_collector=on
- -clog_directory=/logs
- -clog_filename=postgresql-%Y-%m-%d.log
```

**Comment by shufps** [comment]
Perhaps I found something that could be leading to problems:

![image](https://user-images.githubusercontent.com/3079832/233128123-2465874d-720e-4c1f-89ac-561cf6261943.png)

Our chain uses constant `0x0...` as miner address.

Do you think this could be a problem? 500k times the same `0x0...` address :thinking:

**Comment by bretep** [comment]
We've had this problem with BS for almost two years. We restart the realtime indexer every 9 minutes to ensure it doesn't slow down. This is very much not ideal, but it's the workaround we've come up with.

**Comment by shufps** [comment]
@bretep Oh interesting, could you please explain a little more how you did this? Can the indexer be restarted separately without restarting the whole Blockchain setup? :thinking: 

@Qwerty5Uiop Thx a lot, I have just deployed it on our setup. Hopefully it will improve it :pray:

**Comment by shufps** [comment]
I think this is where it's updated:

https://github.com/blockscout/blockscout/blob/master/apps/explorer/lib/explorer/chain/import/runner/addresses.ex#L198

Hmm, it looks like as it is only used for updating a timestamp :thinking:

**Comment by benjamindamm** [comment]
I am pretty sure my problem is not exactly the same. But I made the experience that the first 300K of blocks are indexed pretty fast in about 24h. And after that it gets slower and slower. 

Since I am trying to sync the whole Ethereum chain it's not possible to just be patient. 

I really don't understand how the speed can drop from 300.000 to about 2000. I did every update. I am running the absolute standard config. 

My technical setup is using NVMEs for the node and blockscout and 64GB Ram with 12 CPU cores. I understand it's not high end. But it should get the job done I think.

Any suggestions?

**Comment by rollue** [comment]
> I am pretty sure my problem is not exactly the same. But I made the experience that the first 300K of blocks are indexed pretty fast in about 24h. And after that it gets slower and slower.
> 
> Since I am trying to sync the whole Ethereum chain it's not possible to just be patient.
> 
> I really don't understand how the speed can drop from 300.000 to about 2000. I did every update. I am running the absolute standard config.
> 
> My technical setup is using NVMEs for the node and blockscout and 64GB Ram with 12 CPU cores. I understand it's not high end. But it should get the job done I think.
> 
> Any suggestions?

Curious if you've found a fix for this?

**Comment by benjamindamm** [comment]
Tbh no

But right now I am trying a different approach using multiple archive nodes. I tend to believe that the bottleneck is the RPC node itself. Looking into the console logs it runs really really fast. But I guess not fast enough. 

Atm I can not give any updates since I am still setting up everything. I am trying to use 3 archive nodes behind a node balancer to push blockscout indexer to the limit. What I can tell for sure so far is, it doesn't depend on which disk I run blockscout. Switching from SSD to NVMe brought absolutely no difference. Thats how I came to my mentioned conclusion.

But still I don't understand why the first 300K got indexed so fast in comparison. This can be the case due to a smaller index in DB. But such a huge drop? I'll keep u updated.
