### ISSUE TITLE
Sign in , but does not get personal information

### ISSUE THREAD

**Issue by Jaycelv** [blockscout/blockscout#7301]
*Describe your issue here.*

### Environment

* Deployment type (Manual/Docker/Docker-compose):
* Elixir & Erlang/OTP versions (`elixir -version`):
* Node JS version (`node -v`):
* Operating System:
* Blockscout Version/branch/commit: v5.0.0-beta
* Archive node type && version (Erigon/Geth/Nethermind/Ganache/?):

### Steps to reproduce

export ACCOUNT_AUTH0_DOMAIN="dev-quu8v1pqs4oq7.us.auth0.com"
export ACCOUNT_AUTH0_CLIENT_ID="YGsykmGsfj0qALk8NraBnjb"
export ACCOUNT_AUTH0_CLIENT_SECRET="7fygpnimCdxhun9Ng7wOabfyCCyz6se3NYBGoXGutbVOw6hFnGOQ" 
export ACCOUNT_AUTH0_LOGOUT_URL="https://dev-quu8v1pqs4oq7.us.auth0.com/v2/logout"
export ACCOUNT_AUTH0_LOGOUT_RETURN_URL="https://compony.com/auth/logout"
export ACCOUNT_CLOAK_KEY="lvutbtvZAeuy3SFAftwky+IW4ESy6syE="
here is my env config, When I log in, I can be redirected to the authorization login page and successfully authorize. I print logs in the code and the parameters passed to put_session have values, but the method get_session(conn, :current_user) cannot retrieve the value.  
The following is the user log that I printed out."
%{avatar: "https://lh3.googleusercontent.com/a/AGNmyxYRdPlRmw7aj-Ekprx5cCpIfoqgyg_BKPb0svLN=s96-c", email: "aaa@gmail.com", id: 10, name: "Rumble", nickname: "Rumble.L", uid: "google-oauth2|114928592633458978", watchlist_id: 10}

### Expected behaviour
I have successfully logged in and should have access to my personal information

### Actual behaviour
the get_session(conn, :current_user) function returns  "nil"

**Comment by vbaranov** [comment]
Did you set `ACCOUNT_AUTH0_CALLBACK_URL` environment variable? It should be like:
```
ACCOUNT_AUTH0_CALLBACK_URL=http://your_explorer_url.com/auth/auth0/callback
```

**Comment by Jaycelv** [comment]
> Did you set `ACCOUNT_AUTH0_CALLBACK_URL` environment variable? It should be like:
> 
> ```
> ACCOUNT_AUTH0_CALLBACK_URL=http://your_explorer_url.com/auth/auth0/callback
> ```

![image](https://user-images.githubusercontent.com/99306545/233221097-8f5bec65-b28a-4505-8e78-f633ac42ea32.png)
Are you referring to configuring it in the dashboard? This is the callback URL that I configured. Or should I add this environment variable when the project starts? I couldn't find this environment variable in the project and it's not listed in this documentation: https://docs.blockscout.com/for-developers/information-and-settings/env-variables#account-related-env-variables. I tried adding this environment variable before starting the project, but I still couldn't retrieve the data.

**Comment by vbaranov** [comment]
@Jaycelv you should also 
- setup Redis and provide URL of it in `ACCOUNT_REDIS_URL`
- provide DB URL for Account in `ACCOUNT_DATABASE_URL`.

Did you do both?

**Comment by Jaycelv** [comment]
> * ACCOUNT_REDIS_URL

Thx, I had lost the environment variable 'ACCOUNT_REDIS_URL', it's working fine now.

**Comment by vbaranov** [comment]
@Jaycelv could you check Redis DB? It looks like it doesn't work.

**Comment by Jaycelv** [comment]
> @Jaycelv could you check Redis DB? It looks like it doesn't work.

![image](https://github.com/blockscout/blockscout/assets/99306545/ebb2c9f8-dd85-42c8-aa6f-2d3743532009)

Redis DB works normaly
