### ISSUE TITLE
Get 500 error page on verified contract code tab

### ISSUE THREAD

**Issue by aminlatifi** [blockscout/blockscout#7308]
I have verified my contract via sourcify. After that, I see 500 error on the code tab of the contract
https://blockscout.com/xdai/mainnet/address/0x318F5CDF53F2d2Da3331a98e986758F32126cda5/contracts
<img width="801" alt="image" src="https://user-images.githubusercontent.com/5684607/233498198-0ad372d2-a1dc-46ec-a6ce-66dc287a92a8.png">

The contract is now verified on gnosisscan

**Comment by vbaranov** [comment]
I don't see 500 error currently. The contract is verified 
![Screenshot 2023-04-21 at 09 05 14](https://user-images.githubusercontent.com/4341812/233553236-4941039c-e2a6-42f5-a122-230cd6640c22.png)
