### ISSUE TITLE
docker-compose application=ecto_sql [error] Could not create schema migrations table.

### ISSUE THREAD

**Issue by ZebroTech** [blockscout/blockscout#7341]
![image](https://user-images.githubusercontent.com/32578764/234330228-61f4329d-94bd-45b0-8335-c52e5dbc7f8c.png)

error.log

The full error report is shown below.

2023-04-25T15:37:30.141 application=ecto_sql [error] Could not create schema migrations table. This error usually happens due to the following:

  * The database does not exist
  * The "schema_migrations" table, which Ecto uses for managing
    migrations, was defined by another library
  * There is a deadlock while migrating (such as using concurrent
    indexes with a migration_lock)

To fix the first issue, run "mix ecto.create" for the desired MIX_ENV.

To address the second, you can run "mix ecto.drop" followed by
"mix ecto.create", both for the desired MIX_ENV. Alternatively you may
configure Ecto to use another table and/or repository for managing
migrations:

    config :explorer, Explorer.Repo,
      migration_source: "some_other_table_for_schema_migrations",
      migration_repo: AnotherRepoForSchemaMigrations

**Comment by vbaranov** [comment]
@ZebroTech how did you run docker compose exactly?

**Comment by ZebroTech** [comment]
> @ZebroTech how did you run docker compose exactly?

Solved, 
I opened postgres port and it worked.
