### ISSUE TITLE
custom header footer logo and apps info

### ISSUE THREAD

**Issue by ZebroTech** [blockscout/blockscout#7342]
How to show custom logos and app info etc. if running blockscout from container via docker-compose?
Is it possible to add custom logo etc. to local blockscout/apps/block_scout_web/assets/static/images and define in common-blockscout.env and docker-compose up build?

**Comment by ZebroTech** [comment]
solved

**Comment by ranjith-edx** [comment]
> How to show custom logos and app info etc. if running blockscout from container via docker-compose?
> Is it possible to add custom logo etc. to local blockscout/apps/block_scout_web/assets/static/images and define in common-blockscout.env and docker-compose up build?

i'm facing same issue not able to add custom image or svg

**Comment by Hyferion** [comment]
1. Add your images to the folders
2. Change environment variables
3. Run docker-compose build
4. Rund docker-compose up

Hope it helps

**Comment by ranjith-edx** [comment]
you mean i need to create a new folder inside the images folder and then add it ..?

**Comment by Hyferion** [comment]
Doesn't matter you just need to put your images in the images folder and then reference them with the environment file
