### ISSUE TITLE
everytime I put docker down and up again blocks indexing 0%

### ISSUE THREAD

**Issue by ZebroTech** [blockscout/blockscout#7362]
every time I run docker-compose down and docker-compose up again it starts indexing from 0% again.
also always connection lost alert.

![image](https://user-images.githubusercontent.com/32578764/235218891-7f1b7b03-7159-43f7-9c59-23fa871cb0da.png)

**Comment by kuetabby** [comment]
hey @ZebroTech this is out of topic, but how did u change the header logo? ive tried to replace the LOGO but it just showing empty image

**Comment by ZebroTech** [comment]
> hey @ZebroTech this is out of topic, but how did u change the header logo? ive tried to replace the LOGO but it just showing empty image

add line to docker-compose/envs/common-blockscout.env
'LOGO=/images/your_logo.svg'

place svg logo file into /apps/block_scout_web/assets/static/images/

**Comment by kuetabby** [comment]
> > hey @ZebroTech this is out of topic, but how did u change the header logo? ive tried to replace the LOGO but it just showing empty image
> 
> add line to docker-compose/envs/common-blockscout.env 'LOGO=/images/your_logo.svg'
> 
> place svg logo file into /apps/block_scout_web/assets/static/images/
> 
> @kuetabby

i do exactly like the documentation & like u mention above, but it still giving me empty image
is there something i missing? cause i just restart the container

**Comment by ZebroTech** [comment]
> > > hey @ZebroTech this is out of topic, but how did u change the header logo? ive tried to replace the LOGO but it just showing empty image
> > 
> > 
> > add line to docker-compose/envs/common-blockscout.env 'LOGO=/images/your_logo.svg'
> > place svg logo file into /apps/block_scout_web/assets/static/images/
> > @kuetabby
> 
> i do exactly like the documentation & like u mention above, but it still giving me empty image is there something i missing? cause i just restart the container
> 
> @ZebroTech

documentation doesn't mention re-build to change effect, but I think it requires rebuild.
@kuetabby

**Comment by kuetabby** [comment]
> > > > hey @ZebroTech this is out of topic, but how did u change the header logo? ive tried to replace the LOGO but it just showing empty image
> > > 
> > > 
> > > add line to docker-compose/envs/common-blockscout.env 'LOGO=/images/your_logo.svg'
> > > place svg logo file into /apps/block_scout_web/assets/static/images/
> > > @kuetabby
> > 
> > 
> > i do exactly like the documentation & like u mention above, but it still giving me empty image is there something i missing? cause i just restart the container
> > @ZebroTech
> 
> documentation doesn't mention re-build to change effect, but I think it requires rebuild. @kuetabby

what strange is even i try to edit the page it doesn't get change, what version do u use ?

@ZebroTech

**Comment by ZebroTech** [comment]
> 

![image](https://user-images.githubusercontent.com/32578764/235291963-37c84bce-19a5-4602-8166-840c6a6b8700.png)

**Comment by kuetabby** [comment]
> > 
> 
> @kuetabby ![image](https://user-images.githubusercontent.com/32578764/235291963-37c84bce-19a5-4602-8166-840c6a6b8700.png)

did u run this command "cd apps/block_scout_web/assets; npm install && node_modules/webpack/bin/webpack.js --mode production; cd -" after u update the footer ? 

@ZebroTech

**Comment by ZebroTech** [comment]
> > > 
> > 
> > 
> > @kuetabby ![image](https://user-images.githubusercontent.com/32578764/235291963-37c84bce-19a5-4602-8166-840c6a6b8700.png)
> 
> did u run this command "cd apps/block_scout_web/assets; npm install && node_modules/webpack/bin/webpack.js --mode production; cd -" after u update the footer ?
> 
> @ZebroTech

running from container using docker-compose up --build from /blockscout/docker-conpose

@kuetabby

**Comment by ZebroTech** [comment]
looks like original question is not answered and it's gone out of topic.

Closing this issue and opening new topic with original issue.
