### ISSUE TITLE
Andromeda: not able to download CSV

### ISSUE THREAD

**Issue by foegra** [blockscout/blockscout#7372]
*Describe your issue here.*

### Environment
* Elixir Version: 1.14.0
* Erlang Version: 25
* BlockScout Version: v5.1.4-beta

* User Agent: `Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/112.0.0.0 Safari/537.36`

### Steps to reproduce

*Tell us how to reproduce this issue. If possible, push up a branch to your fork with a regression test we can run to reproduce locally.*

### Expected Behaviour

Tried to download transactions as CSV

### Actual Behaviour

After pressing "Download" nothing happens

**Comment by vbaranov** [comment]
@foegra Andromeda instance is not managed by Blockscout team. Most likely instance maintainer didn't configure reCAPTCHA for CSV export page.
