### ISSUE TITLE
Kava 10: <Issue Title>im using plexus.app fo bridge from kava-usdc to bsc-usdc.

### ISSUE THREAD

**Issue by ryushuki87** [blockscout/blockscout#7375]
*Describe your issue here.*
helo si, i need help for my case.. i make bridge using plexus.app for bridge kava-usdc to bsc-usdc.
in plexus.app already success. but the tx id i open,, the page is not found.. and i check my metamask no transaction to.
everyday im bridge using plexus.app from kava to bsc and from bsc back to kava.. this is my first time i get case like this..
please help me for my case sir.. thank you so much.
this is my tx id : 0x2462a886ac35540cad49cf1636ebcfcabe6926edf2d809e48e14033202e17569
and this is my wallet 0x1735DD04B021A97B931225C69D0248c94d0a8DB9
![not found](https://user-images.githubusercontent.com/128893322/235412052-eecf5ba6-fcd5-4acd-b4cc-5461a13726a5.png)
![no transaction](https://user-images.githubusercontent.com/128893322/235412078-b84e5de9-948e-4e02-a11a-0f779ff3a5b8.png)

### Environment
* Elixir Version: 1.12.3
* Erlang Version: 24
* BlockScout Version: 

* User Agent: `Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/112.0.0.0 Safari/537.36`

### Steps to reproduce

*Tell us how to reproduce this issue. If possible, push up a branch to your fork with a regression test we can run to reproduce locally.*

### Expected Behaviour

*Tell us what should happen.*

### Actual Behaviour

*Tell us what happens instead.*

**Comment by vbaranov** [comment]
Hello, Kava 10 Blockscout instance is not managed by Blockscout team. Please address your question to Kava team.
