### ISSUE TITLE
account balance not showing, connection lost alert, contract_verifications page error

### ISSUE THREAD

**Issue by ZebroTech** [blockscout/blockscout#7376]
Running blockscout from container using docker version 20.10.+, docker-compose 2.17.+.

All working fine except few issues.

1. account main/token balances not showing.

2. /blocks page always show alert 'Connection Lost, click to load newer blocks'.

3. /contract_verifications/new page throws error 500 'Internal server error. An unexpected error has occurred. Try reloading the page, or come back soon and try again'.

**Comment by vbaranov** [comment]
> account main/token balances not showing.

Could you elaborate on this? On which page? Could you provide any screenshots to better understand what happened on your end?

> /blocks page always show alert 'Connection Lost, click to load newer blocks'.

Try to set `MIX_ENV=prod`

> /contract_verifications/new page throws error 500

Most likely because `SECRET_KEY_BASE` is not configured. It should be alphanumeric string with 64 bytes min length.

**Comment by ZebroTech** [comment]
> > account main/token balances not showing.
> 
> Could you elaborate on this? On which page? Could you provide any screenshots to better understand what happened on your end?
> 
> > /blocks page always show alert 'Connection Lost, click to load newer blocks'.
> 
> Try to set `MIX_ENV=prod`
> 
> > /contract_verifications/new page throws error 500
> 
> Most likely because `SECRET_KEY_BASE` is not configured. It should be alphanumeric string with 64 bytes min length.

![zex_issue1](https://user-images.githubusercontent.com/32578764/235599403-ba09c749-9386-4899-ad30-a03404f0d485.jpg)

![zex_issue2](https://user-images.githubusercontent.com/32578764/235599437-b5d446a9-2134-46cf-8bca-f7ddb753cb90.jpg)

**Comment by wzglgo** [comment]
> > > account main/token balances not showing.
> > 
> > 
> > Could you elaborate on this? On which page? Could you provide any screenshots to better understand what happened on your end?
> > > /blocks page always show alert 'Connection Lost, click to load newer blocks'.
> > 
> > 
> > Try to set `MIX_ENV=prod`
> > > /contract_verifications/new page throws error 500
> > 
> > 
> > Most likely because `SECRET_KEY_BASE` is not configured. It should be alphanumeric string with 64 bytes min length.
> 
> ![zex_issue1](https://user-images.githubusercontent.com/32578764/235599403-ba09c749-9386-4899-ad30-a03404f0d485.jpg)
> 
> ![zex_issue2](https://user-images.githubusercontent.com/32578764/235599437-b5d446a9-2134-46cf-8bca-f7ddb753cb90.jpg)

If the balance is not displayed, it may be that the number is too large. Try to transfer all the balance and only keep a small part, and it may be displayed.

**Comment by ZebroTech** [comment]
@wzglgo 

an account with small balances also don't display 

![image](https://user-images.githubusercontent.com/32578764/235600612-acab8662-7457-4402-95f1-c85de9245ad4.png)

**Comment by ZebroTech** [comment]
> > account main/token balances not showing.
> 
> Could you elaborate on this? On which page? Could you provide any screenshots to better understand what happened on your end?
> 
> > /blocks page always show alert 'Connection Lost, click to load newer blocks'.
> 
> Try to set `MIX_ENV=prod`
> 
> > /contract_verifications/new page throws error 500
> 
> Most likely because `SECRET_KEY_BASE` is not configured. It should be alphanumeric string with 64 bytes min length.

I think MIX_ENV=prod mode by default if you build blockscout using docker-compose, no?
How to configure  `SECRET_KEY_BASE` for running blockscout from docker?

**Comment by ZebroTech** [comment]
> > > account main/token balances not showing.
> > 
> > 
> > Could you elaborate on this? On which page? Could you provide any screenshots to better understand what happened on your end?
> > > /blocks page always show alert 'Connection Lost, click to load newer blocks'.
> > 
> > 
> > Try to set `MIX_ENV=prod`
> > > /contract_verifications/new page throws error 500
> > 
> > 
> > Most likely because `SECRET_KEY_BASE` is not configured. It should be alphanumeric string with 64 bytes min length.
> 
> I think MIX_ENV=prod mode by default if you build blockscout using docker-compose, no? 
Should I add MIX_ENV=prod to common-blockscout.env and run?
How to configure `SECRET_KEY_BASE` for running blockscout from docker?

**Comment by vbaranov** [comment]
> How to configure SECRET_KEY_BASE for running blockscout from docker?

Add SECRET_KEY_BASE env variable to docker-compose. The value should be alphanumeric string with 64 bytes min length.

> Should I add MIX_ENV=prod to common-blockscout.env and run?

Yes. Please, try.

**Comment by vbaranov** [comment]
@ZebroTech didn't get feedback from you. Is all good now?

**Comment by ZebroTech** [comment]
> @ZebroTech didn't get feedback from you. Is all good now?
![image](https://github.com/blockscout/blockscout/assets/32578764/80a9f3bd-cf40-44a0-9691-eec091a009a0)

another explorer running with same configuration also from docker-compose shows account/address balance perfectly.
both still having issue of smart-contract-verification page error 500.

**Comment by ZebroTech** [comment]
> @ZebroTech didn't get feedback from you. Is all good now?

account balance not showing issue has been solved now by cleaning up old files in docker-compose and  rebuilding docker-compose. yet smart-contract-verification error 500tobe solved.

**Comment by vbaranov** [comment]
@ZebroTech did you set SECRET_KEY_BASE, which I already mentioned before?

**Comment by vbaranov** [comment]
@ZebroTech please consider migration to a new UI https://docs.blockscout.com/for-developers/frontend-migration
