### ISSUE TITLE
internal transactions can not display

### ISSUE THREAD

**Issue by Jaycelv** [blockscout/blockscout#7383]
*Describe your issue here.*

### Environment

* Blockscout Version/branch/commit: v5.0.0-beta
* Archive node type && version (Erigon/Geth/Nethermind/Ganache/?): Geth

### Steps to reproduce

export DATABASE_URL=postgresql://postgres:@localhost:5432/blockscout
export COIN_NAME=BTC
export SUBNETWORK="xxxx
export ETHEREUM_JSONRPC_HTTP_URL=https://xxxxx
export ETHEREUM_JSONRPC_TRACE_URL=https://xxxxx
export CHAIN_ID=1434
export BLOCKSCOUT_HOST=xxxx
export PORT=4001
export ECTO_USE_SSL="false"
export DISABLE_EXCHANGE_RATES="true"
export INDEXER_DISABLE_INTERNAL_TRANSACTIONS_FETCHER="false"
export INDEXER_DISABLE_BLOCK_REWARD_FETCHER="true"
export INDEXER_DISABLE_PENDING_TRANSACTIONS_FETCHER="false"
export INDEXER_DISABLE_ADDRESS_COIN_BALANCE_FETCHER="false"
export DISABLE_EXCHANGE_RATES="true"
export ETHEREUM_JSONRPC_DISABLE_ARCHIVE_BALANCES="false"
export ENABLE_RUST_VERIFICATION_SERVICE="true"
export RUST_VERIFICATION_SERVICE_URL="xxxxxx"

here is my env, and geth node enabled debug module, but still received no internal transactions, why?
![image](https://user-images.githubusercontent.com/99306545/235563336-11f8d36c-f055-4c98-8282-6c85520d85c9.png)

### Expected behaviour

Internal txns can display normaly

### Actual behaviour

Internal transactions list is empty

**Comment by vbaranov** [comment]
Probably, given transaction doesn't have internal transactions at all? Is `internal_transactions` table ever populated with the new rows?

**Comment by Jaycelv** [comment]
> Probably, given transaction doesn't have internal transactions at all? Is `internal_transactions` table ever populated with the new rows?

![image](https://user-images.githubusercontent.com/99306545/235623119-d16099ed-9f42-4097-a57d-bca929851a73.png)
![image](https://user-images.githubusercontent.com/99306545/235623165-6a147e13-1da3-4ac2-83ee-4676eb557124.png)
There are a lot of different types of transactions on the chain, and there must be internal transactions

**Comment by vbaranov** [comment]
@Jaycelv are you using Geth client? Is debug module enabled on it? Blockscout requests internal transactions via `debug_traceTransactions` method https://docs.blockscout.com/for-developers/information-and-settings/node-tracing-json-rpc-requirements#enable-tracing-to-fetch-internal-transactions
