### ISSUE TITLE
Can i close balance history?

### ISSUE THREAD

**Issue by wzglgo** [blockscout/blockscout#7384]
Because my node often reports an error when calling eth_getBalance that includes the block height, I hope to stop this service that records historical balances. How can I modify it?

**Comment by vbaranov** [comment]
You can set `ETHEREUM_JSONRPC_DISABLE_ARCHIVE_BALANCES=true`. Then all requests to eth_getBalance method will be skipped except with tag `latest`.

**Comment by wzglgo** [comment]
> You can set `ETHEREUM_JSONRPC_DISABLE_ARCHIVE_BALANCES=true`. Then all requests to eth_getBalance method will be skipped except with tag `latest`.

now,i got  [required historical state unavailable], what should i do?
thx

**Comment by wzglgo** [comment]
Why blockscout is doing debug_traceTransaction, can I turn it off?

**Comment by vbaranov** [comment]
It tries to fetch internal transactions from the node. If the debug module is switched off on the node, you should disable the corresponding fetcher in Blockscout: `INDEXER_DISABLE_INTERNAL_TRANSACTIONS_FETCHER=true`.

**Comment by wzglgo** [comment]
What data will I lose if I turn on INDEXER_DISABLE_INTERNAL_TRANSACTIONS_FETCHER?

**Comment by vbaranov** [comment]
Blockscout won't try to fetch internal transactions from `debug_traceTransaction` method, which anyways doesn't return data from your node.

**Comment by vbaranov** [comment]
I am closing this. @wzglgo please let me know if you have further requests.
