### ISSUE TITLE
Linea Testnet: <Issue Title> my transaction not transaction hash 

### ISSUE THREAD

**Issue by robinsiondu** [blockscout/blockscout#7386]
Hello,

Why  my transaction not transaction hash,It is take a long time like this.
Please see attached the pictures.
![000](https://user-images.githubusercontent.com/130286204/235612488-f4062308-9023-46f7-8179-a88cf75e1d38.jpg)
![33](https://user-images.githubusercontent.com/130286204/235612516-06920884-e543-4143-b093-bf84a2cfb082.jpg)
![44](https://user-images.githubusercontent.com/130286204/235612538-3e156f39-549e-4b51-ba3d-6a2bde266b31.jpg)

**Comment by robinsiondu** [comment]
here is my public address 0xB80975C0415C8f5dFDeE8F3ADA5f224CC57e0FEb

**Comment by vbaranov** [comment]
Linea testnet explorer is not managed by the Blockscout team. Please address your question to Linea testnet support.
