### ISSUE TITLE
C1: Cannot download CSV transactions

### ISSUE THREAD

**Issue by RailayBC** [blockscout/blockscout#7396]
The bottom-page button is not giving any download file with list....

### Environment
* Elixir Version: 1.13.1
* Erlang Version: 24
* BlockScout Version: v4.1.2-beta

* User Agent: `Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:109.0) Gecko/20100101 Firefox/112.0`

### Steps to reproduce

*Tell us how to reproduce this issue. If possible, push up a branch to your fork with a regression test we can run to reproduce locally.*

### Expected Behaviour

*Tell us what should happen.*

### Actual Behaviour

*Tell us what happens instead.*

**Comment by vbaranov** [comment]
This instance is not managed by Blockscout team. They didn't configure reCAPTCHA for CSV export page.

**Comment by RailayBC** [comment]
Hi there, this is all well but how to progress, whom to contact?

**Comment by vbaranov** [comment]
I guess you can find contacts on the official site https://milkomeda.com/
