### ISSUE TITLE
Astar (EVM): <Issue Title>

### ISSUE THREAD

**Issue by ahmetzturk** [blockscout/blockscout#7414]
Error "New Smart Contract Verification"

I am uploading .json file but getting an error saying "There was an error validating your contract, please try again."

**Comment by vbaranov** [comment]
@ahmetzturk could you provide details for reproducing the issue?

**Comment by ahmetzturk** [comment]
I have solved the problem, thanks.

Victor Baranov ***@***.***>, 10 May 2023 Çar, 15:59 tarihinde
şunu yazdı:
