### ISSUE TITLE
Andromeda: <Issue Title>

### ISSUE THREAD

**Issue by TheBullFerdinand** [blockscout/blockscout#7423]
*Describe your issue here.*
Funds did not arrive. I send over WETH from Andromeda Network on my Metamask to my Trust Wallet WETH address on the Eth network and funds never arrived after being confirmed. 

Hash on Andromeda: 0xbe13af81a20992ed53adcdf010352711b8a64eb736d57172b4f0ff84dcdf6f97
<img width="929" alt="Screen Shot 2023-05-07 at 12 51 51 PM" src="https://user-images.githubusercontent.com/90650111/236699748-accf17f6-052b-4687-81a4-31184e4e075c.png">

### Environment
* Elixir Version: 1.14.0
* Erlang Version: 25
* BlockScout Version: v5.1.4-beta

* User Agent: `Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/111.0.0.0 Safari/537.36`

### Steps to reproduce

*Tell us how to reproduce this issue. If possible, push up a branch to your fork with a regression test we can run to reproduce locally.*

### Expected Behaviour

*Tell us what should happen.*

### Actual Behaviour

*Tell us what happens instead.*

**Comment by vbaranov** [comment]
You should contact Andromeda network support. The question doesn't relate to the Blockscout explorer.
