### ISSUE TITLE
signin page issue in blockscout

### ISSUE THREAD

**Issue by Neoblock8** [blockscout/blockscout#7424]
How to integrate signin page in blockscout?

**Comment by vbaranov** [comment]
This is not a comprehensive guide, but you can use to configure My account section https://docs.blockscout.com/for-developers/configuration-options/my-account-settings

**Comment by Neoblock8** [comment]
> This is not a comprehensive guide, but you can use to configure My account section https://docs.blockscout.com/for-developers/configuration-options/my-account-settings

**Comment by Neoblock8** [comment]
> This is not a comprehensive guide, but you can use to configure My account section https://docs.blockscout.com/for-developers/configuration-options/my-account-settings

How to integrate the Account page with existing blockscout?

**Comment by vbaranov** [comment]
Complete the list of env variables from the guide above and use the version of Blockscout >= 5.0.0.

**Comment by vbaranov** [comment]
@Neoblock8 I am closing this. Please, let me know if you have further requests.
