### ISSUE TITLE
Compilation issue 

### ISSUE THREAD

**Issue by Neoblock8** [blockscout/blockscout#7425]
Hi,
  Compile using this command: mix deps.clean --all && mix deps.get && mix deps.compile
  How to solve this error?
  **Having below error:**
  
![image](https://user-images.githubusercontent.com/81068101/236754318-cab3b734-3a31-4b14-baab-901e66a13738.png)

**Erlang and Elixir versions using:**
   Erlang/OTP 24 [erts-12.3.2.1] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [jit]
   Elixir 1.12.2 (compiled with Erlang/OTP 22)

**Comment by vbaranov** [comment]
@Neoblock8 elixir 1.12.2 is unsupported. Please follow the requirements https://docs.blockscout.com/for-developers/information-and-settings/requirements. Elixir 1.13.x is a minimum supported version. It is even better to update to 1.14.x and the latest Erlang/OTP.

**Comment by Neoblock8** [comment]
> @Neoblock8 elixir 1.12.2 is unsupported. Please follow the requirements https://docs.blockscout.com/for-developers/information-and-settings/requirements. Elixir 1.13.x is a minimum supported version. It is even better to update to 1.14.x and the latest Erlang/OTP.

I will check and let you know

**Comment by Neoblock8** [comment]
> @Neoblock8 elixir 1.12.2 is unsupported. Please follow the requirements https://docs.blockscout.com/for-developers/information-and-settings/requirements. Elixir 1.13.x is a minimum supported version. It is even better to update to 1.14.x and the latest Erlang/OTP.

Hi @vbaranov,
 Still having same issue
 
 
![image](https://user-images.githubusercontent.com/81068101/236793491-45fee2b7-73db-4a68-89fa-2ba9b82e3eb5.png)


**Version upgraded:**
Erlang/OTP 24 [erts-12.3.2.1] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [jit]

Elixir 1.13.3 (compiled with Erlang/OTP 22)

**Comment by vbaranov** [comment]
@Neoblock8 Blockscout core doesn't have file staking_pool.ex. It looks like customization on your side.
