### ISSUE TITLE
Protocol Enumerable not implemented for nil of type Atom

### ISSUE THREAD

**Issue by khaitqNapaglobal** [blockscout/blockscout#7427]
Is the document you wrote the deployment manual correct? Does it update anymore? If yes, can you update the document with more details about config env run locally? I followed your deployment manual and am getting this error:
![Screenshot from 2023-05-08 17-02-23](https://user-images.githubusercontent.com/108641766/236796103-bae9978b-30aa-4963-8370-c624558cde4c.png)

**Comment by sl1depengwyn** [comment]
What is your `DATABASE_URL`? It seems that something is wrong with this env

**Comment by andreujuanc** [comment]
Having the same issue @sl1depengwyn : this is my url: `postgresql://postgres:postgres@postgres_db:5432/blockscout?ssl=false`

**Comment by andreujuanc** [comment]
LOL so it's because it has an underscore? SERIOUSLY?

**Comment by nikitosing** [comment]
@andreujuanc Could you show your error log?

**Comment by khaitqNapaglobal** [comment]
Sorry for the inconvenience. Thank you very much. I have solved my issue

**Comment by andreujuanc** [comment]
The issue @nikitosing  is that the hostname of the db contained an orderscore. There must be some dependency that fails because of that.

And the error (title of this issue) offers no clues.
Maybe there should be a check for it and a clear info/error?

**Comment by sl1depengwyn** [comment]
> LOL so it's because it has an underscore? SERIOUSLY?

Underscore is not a valid url host character, it's not allowed to use `_` in domain name.
[RFC-952](http://www.ietf.org/rfc/rfc952.txt), [RFC-1123](http://www.ietf.org/rfc/rfc1123.txt)

**Comment by andreujuanc** [comment]
> > LOL so it's because it has an underscore? SERIOUSLY?
> 
> Underscore is not a valid url host character, it's not allowed to use `_` in domain name. [RFC-952](http://www.ietf.org/rfc/rfc952.txt), [RFC-1123](http://www.ietf.org/rfc/rfc1123.txt)

That's right, but how it's not validated at all and just showing this is no bueno.
![image](https://github.com/blockscout/blockscout/assets/360052/8843ff4f-dc1b-41e8-8a0f-9476032bbbfd)
 Specially if it's a small mistake from the user side, very common when defining services in dockercompose.

**Comment by yohanelly95** [comment]
I am getting this error with db url as:
`DATABASE_URL=postgresql://blockscout:'password'@db:5432/blockscout`. DB is running on the same vm, I am able to `psql` into the this db using the same url.
