### ISSUE TITLE
Blockscout 5.13 shows a wrong ERC-20 token balance.

### ISSUE THREAD

**Issue by GiladLeef** [blockscout/blockscout#7429]
*Blockscout 5.13 shows a wrong ERC-20 token balance.*

### Environment
Deployed contract (On blockscout) - http://62.221.254.77:4000/token/0xb44DFD33a02DD87a5A16544F39391deC8DC235a0/token-transfers
Deployed contract (On etherscan-based explorer) - https://testnet.cronoscan.com/token/0x9622b9ddce346d209246cacb935c6c1ccad783e5
* Docker-compose
* Ubuntu 20.04 server
* Polygon edge
### Steps to reproduce
Copy the contract source code from https://testnet.cronoscan.com/token/0x9622b9ddce346d209246cacb935c6c1ccad783e5#code
Deploy it into a local test network (See polygon's edge docs for the exact setup instructions, we used a PoS blockchain with the config being almost identical to the defaults)
Just use the default 5.13 release, jump into docker-compose directory and run `docker-compose up --build`

*What should happen VS The actual case*
It should have been showing `100,000,000,000` tokens balance instead of `100,000,000,000,000,000,000`

**Comment by vbaranov** [comment]
@GiladLeef this has been fixed in [5.1.5](https://github.com/blockscout/blockscout/releases/tag/v5.1.5-beta). Even better to update to the latest release [5.2.0](https://github.com/blockscout/blockscout/releases/tag/v5.2.0-beta).
