### ISSUE TITLE
Error while sending request to verification microservice url

### ISSUE THREAD

**Issue by 0xhohenheim** [blockscout/blockscout#7441]
I've been trying to verify Smart Contracts via the `smart-contract-verifier` but the Blockscout server is unable to reach the microservice.

### Environment

* Deployment type (Manual/Docker/Docker-compose): Manual
* Elixir & Erlang/OTP versions (`elixir -version`): Erlang (v25.0) + Elixir (v1.14.0-otp-25)
* Node JS version (`node -v`): 14.20.1
* Operating System: Ubuntu 22.04
* Blockscout Version/branch/commit: v5.1.4-beta
* Archive node type && version (Erigon/Geth/Nethermind/Ganache/?): Ganache

### Steps to reproduce

- Run microservice: `docker run -p 8043:8043 ghcr.io/blockscout/smart-contract-verifier:latest`
- Set env variables: 
```
export MICROSERVICE_SC_VERIFIER_ENABLED=true
export MICROSERVICE_SC_VERIFIER_URL=http://0.0.0.0:8043/
```
- Run blockscout `v5.1.4-beta`
- Deploy contract
- Try verifying contract

### Expected behaviour

Should provide options for various compiler versions

### Actual behaviour

API call to the microservice fails with the following error:
```sh
2023-05-09T21:31:46.912 application=explorer request_id=F12FCGcQZItQYC4AAAEF [error] Error while sending request to verification microservice url: http://0.0.0.0:8043/api/v2/verifier/solidity/versions: %HTTPoison.Error{reason: :closed, id: nil}
```
No compiler versions show up

**Comment by rimrakhimov** [comment]
@0xhohenheim The latest verifier sercice runs by default on port number 8050. You can find all available configuration variables with their default values in [envs](https://github.com/blockscout/blockscout-rs/blob/main/smart-contract-verifier/smart-contract-verifier-server/config/base.env). The readme for the latest verifier service server could be found in [Readme](https://github.com/blockscout/blockscout-rs/tree/main/smart-contract-verifier/smart-contract-verifier-server#readme)

**Comment by 0xhohenheim** [comment]
@rimrakhimov That was it, thanks a lot! Someone should probably update the docker command in the [Manual Deployment](https://docs.blockscout.com/for-developers/manual-deployment) documentation though.
