### ISSUE TITLE
The function of the drop-down box is disabled

### ISSUE THREAD

**Issue by Jaycelv** [blockscout/blockscout#7444]
*Describe your issue here.*

### Environment

* Deployment type (Manual/Docker/Docker-compose):
* Elixir & Erlang/OTP versions (`elixir -version`):
* Node JS version (`node -v`):
* Operating System:
* Blockscout Version/branch/commit: v5.0.0-beta
* Archive node type && version (Erigon/Geth/Nethermind/Ganache/?): Geth

### Steps to reproduce

https://blockscout.com/optimism/goerli/address/0x896CA9931238169186001228ab2D3e060cA21179/contract_verifications/new
![image](https://github.com/blockscout/blockscout/assets/99306545/9617bd53-df2d-4379-8083-6e5175b013db)
The function of the drop-down box is disabled

**Comment by vbaranov** [comment]
@Jaycelv this is resolved in the linked PR. Will be deployed to the instance soon.
