### ISSUE TITLE
Get 500 Error page on contract code tab

### ISSUE THREAD

**Issue by TTBOBO** [blockscout/blockscout#7447]
https://scan.gdc.plus/address/0xED926d25521DA2639b9FfFf88985bbE29cbc4CaB/contracts

Request: GET /address/0xED926d25521DA2639b9FfFf88985bbE29cbc4CaB/contracts
blockscout               | ** (exit) an exception was raised:
blockscout               |     ** (CaseClauseError) no case clause matching: []
blockscout               |         (hackney 1.18.1) /app/deps/hackney/src/hackney_url.erl:248: :hackney_url.parse_netloc/2
blockscout               |         (hackney 1.18.1) /app/deps/hackney/src/hackney.erl:351: :hackney.request/5
blockscout               |         (httpoison 1.8.2) lib/httpoison/base.ex:846: HTTPoison.Base.request/6
blockscout               |         (explorer 5.1.2) lib/explorer/third_party_integrations/sourcify.ex:155: Explorer.ThirdPartyIntegrations.Sourcify.http_get_request/2
blockscout               |         (explorer 5.1.2) lib/explorer/smart_contract/solidity/publish_helper.ex:181: Explorer.SmartContract.Solidity.PublishHelper.check_by_address_in_sourcify_else/1
blockscout               |         (block_scout_web 5.1.2) lib/block_scout_web/controllers/address_contract_controller.ex:27: BlockScoutWeb.AddressContractController.index/2
blockscout               |         (block_scout_web 5.1.2) lib/block_scout_web/controllers/address_contract_controller.ex:2: BlockScoutWeb.AddressContractController.action/2
blockscout               |         (block_scout_web 5.1.2) lib/block_scout_web/controllers/address_contract_controller.ex:2: BlockScoutWeb.AddressContractController.phoenix_controller_pipeline/2

**Comment by nikitosing** [comment]
@TTBOBO Please unset `SOURCIFY_SERVER_URL` looks like that you assigned this variable an empty value. Also make sure that your `CHAIN_ID` is supported by sourcify. If not then it's better to set `SOURCIFY_INTEGRATION_ENABLED` to `false`

**Comment by vbaranov** [comment]
Closing due to no response from the author.
