### ISSUE TITLE
Customization of pages

### ISSUE THREAD

**Issue by Neoblock8** [blockscout/blockscout#7453]
*Describe your issue here.*
Hi,
 Running blockscout in local environment. Need to change the color(purple) of pages.
  In which file will we customize the color of header and footer?

**Comment by vbaranov** [comment]
Footer HTML:
https://github.com/blockscout/blockscout/blob/master/apps/block_scout_web/lib/block_scout_web/templates/layout/_footer.html.eex

Footer styles:
https://github.com/blockscout/blockscout/blob/master/apps/block_scout_web/assets/css/components/_footer.scss

Header HTML:
https://github.com/blockscout/blockscout/blob/master/apps/block_scout_web/lib/block_scout_web/templates/layout/_topnav.html.eex

Header styles:
https://github.com/blockscout/blockscout/blob/master/apps/block_scout_web/assets/css/components/_navbar.scss
