### ISSUE TITLE
indexer fetcher coin balance error

### ISSUE THREAD

**Issue by Noctis0227** [blockscout/blockscout#7462]
*Describe your issue here.*
indexer fetcher coin balance error,address appears garbled code.

### Environment

* Deployment type (Manual/Docker/Docker-compose): Manual
* Elixir & Erlang/OTP versions (`elixir -version`): Erlang/OTP 25, Elixir 1.14.4
* Node JS version (`node -v`): v16.18.1
* Operating System:
* Blockscout Version/branch/commit: 5.1.4
* Archive node type && version (Erigon/Geth/Nethermind/Ganache/?):

### Steps to reproduce

*Tell us how to reproduce this issue.  ❤️ if you can push up a branch to your fork with a regression test we can run to reproduce locally.*

### Expected behaviour

*Tell us what should happen.*

### Actual behaviour

*Tell us what happens instead.*

![image](https://github.com/blockscout/blockscout/assets/10266848/16250b65-1c6d-4c1f-9478-61e6c81eaa8f)

**Comment by vbaranov** [comment]
This means, that the node doesn't contain an archive state. You should run the node in archive mode or switch off fetching of archive balances in Blockscout via setting runtime environment variable:
```
ETHEREUM_JSONRPC_DISABLE_ARCHIVE_BALANCES=true
```

**Comment by Noctis0227** [comment]
--gcmode=archive

**Comment by Noctis0227** [comment]
![image](https://github.com/blockscout/blockscout/assets/10266848/2bbc3718-92cd-486f-8c46-f89de91b261e)

The node has been using archive mode.

**Comment by Noctis0227** [comment]
ok, thanks.
