### ISSUE TITLE
Export csv doesn't work

### ISSUE THREAD

**Issue by pustovalov** [blockscout/blockscout#7470]
### Environment

* Deployment type (Manual/Docker/Docker-compose): Manual
* Elixir & Erlang/OTP versions (`elixir -version`): Elixir 1.14.4 (compiled with Erlang/OTP 25)
* Node JS version (`node -v`): v18.16.0
* Blockscout Version/branch/commit: https://github.com/blockscout/blockscout/commit/eebaa390bc2121848c6eb55c26fa1094a81968dd

### Steps to reproduce

Go to some address and try to export csv, with reCAPTCHA v2

http://localhost:4000/csv-export?address=0xf91AaE6F1742bb554645729D8164B5d8Da425fF3&type=token-transfers

![image](https://github.com/blockscout/blockscout/assets/1568885/2e676acc-77d2-419e-be27-eae77f729dfd)

Before that commit:
```
token-transfers-csv?address_id=0xf91AaE6F1742bb554645729D8164B5d8Da425fF3&from_period=2023-04-12&to_period=2023-05-12&recaptcha_response=03AL8dmw-hdAX1ezeFv031BeWmKsjzzb6brlY1cA-l4Q4NsgOututSsXnwrtGYXm8tQmrO9rEGND-RqXhb_1IEnJiGJD6HnRztm7OxTuFi2jNW8obS8HCTvj6e6ODBPLMGI9QRWpIqMLpz5ZkgHKCCBMvY-3EabwTU0xzKRvz0jcs2zb9tYUz7
```

After that commit
```
token-transfers-csv?address_id=0xf91AaE6F1742bb554645729D8164B5d8Da425fF3&from_period=2023-04-12&to_period=2023-05-12
```

### Expected behaviour

CSV export works

### Actual behaviour

CSV export doesn't work, because `recaptcha_response` not added to query

Maybe this PR changed behaviour: https://github.com/blockscout/blockscout/pull/7416

**Comment by pustovalov** [comment]
Works well on this commit:
https://github.com/blockscout/blockscout/commit/9615e2fa0b67c7ca66759bdd6cce5976878fe781

![image](https://github.com/blockscout/blockscout/assets/1568885/d49b680e-5493-4ee2-906a-f7d46864d593)

**Comment by vbaranov** [comment]
@pustovalov https://github.com/blockscout/blockscout/pull/7472 should resolve the issue.
