### ISSUE TITLE
Indexer locking

### ISSUE THREAD

**Issue by bretep** [blockscout/blockscout#7475]
We only have one indexer. I restarted it and the performance has degraded quite a bit.

<img width="1577" alt="image" src="https://github.com/blockscout/blockscout/assets/787344/e24e12b4-bc45-4a7b-88b2-62321c4c34ec">

### Environment

Deployment type (Manual/Docker/Docker-compose): Docker
Elixir & Erlang/OTP versions (elixir -version):
Node JS version (node -v):
Operating System: Linux (Ubuntu 20.04.5 LTS (Focal Fossa))
Blockscout Version/branch/commit: v5.1.4-beta https://github.com/blockscout/blockscout/commit/9615e2fa0b67c7ca66759bdd6cce5976878fe781
Archive node type && version (Erigon/Geth/Nethermind/Ganache/?): erigon

### Steps to reproduce

ENV:
```
BLOCK_TRANSFORMER=base
BLOCKSCOUT_HOST=localhost
BLOCKSCOUT_PROTOCOL=http
CHAIN_ID=369
COIN=PLS
DATABASE_URL=postgres://.../blockscout
DISABLE_EXCHANGE_RATES=true
DISABLE_INDEXER=false
DISABLE_REALTIME_INDEXER=false
DISABLE_WEBAPP=true
ECTO_USE_SSL=false
ENABLE_1559_SUPPORT=true
ETHEREUM_JSONRPC_DEBUG_TRACE_TRANSACTION_TIMEOUT=500s
ETHEREUM_JSONRPC_HTTP_INSECURE=true
ETHEREUM_JSONRPC_HTTP_TIMEOUT=60
ETHEREUM_JSONRPC_HTTP_URL=http://localhost:80/
ETHEREUM_JSONRPC_TRACE_URL=http://localhost:80/
ETHEREUM_JSONRPC_TRANSPORT=http
ETHEREUM_JSONRPC_VARIANT=erigon
ETHEREUM_JSONRPC_WS_URL=ws://localhost:80/
FETCH_REWARDS_WAY=manual
FIRST_BLOCK=17233000
INDEXER_CATCHUP_BLOCKS_BATCH_SIZE=10
INDEXER_CATCHUP_BLOCKS_CONCURRENCY=10
INDEXER_COIN_BALANCES_BATCH_SIZE=50
INDEXER_DISABLE_WITHDRAWALS_FETCHER=false
INDEXER_MEMORY_LIMIT=300g
INDEXER_RECEIPTS_BATCH_SIZE=50
INDEXER_TX_ACTIONS_ENABLE=true
SOURCIFY_INTEGRATION_ENABLED=true
WITHDRAWALS_FIRST_BLOCK=17233000
```
Launch a new chain, index it, restart the indexer because it seems lagging, and watch as the database is locking up all over the place.

### Expected behaviour

Restarting the indexer should not cause locking contention

### Actual behaviour

It's locking the database, pages having issues loading, and the indexer is way behind.

**Comment by vbaranov** [comment]
Please update your indexer/api pods to the latest release [6.7.2](https://github.com/blockscout/blockscout/releases/tag/v6.7.2-beta).
