### ISSUE TITLE
Optimism-Goerli Txn Batches has invalid data

### ISSUE THREAD

**Issue by 0xtzData** [blockscout/blockscout#7477]
Optimism-Goerli explorer:
https://goerli-optimism.etherscan.io/batches?p=1

Blockscout Optimism-Goerli:
https://blockscout-optimism-goerli.test.aws-k8s.blockscout.com/l2-txn-batches

1. L2 Block number link leads nowhere
2. Wrong txn count for a block
3. Age is wrong, compared to original explorer

**Comment by varasev** [comment]
Hi,

1. That is test instance, so not all blocks are indexed (and we see 404 error).

2. The same reason (unindexed blocks).

3. The module https://blockscout-optimism-goerli.test.aws-k8s.blockscout.com/l2-txn-batches doesn't work correctly as it has some bugs, so it stopped to index batches. The current release is in https://base-goerli.blockscout.com/l2-txn-batches (indexing right now). Please note, that https://goerli-optimism.etherscan.io/batches?p=1 displays an old (Pre-BedRock) page.

**Comment by vbaranov** [comment]
I would close this since the links to the instance is outdated. @0xtzData if some of the issues are still present, could you please open a new issue?
