### ISSUE TITLE
Optimism-Goerli L1->L2 Transactions wrong gas limit

### ISSUE THREAD

**Issue by 0xtzData** [blockscout/blockscout#7478]
Compared to https://goerli-optimism.etherscan.io/txsEnqueued we have different Gas Limit for blocks - https://blockscout-optimism-goerli.test.aws-k8s.blockscout.com/l2-deposits

**Comment by vbaranov** [comment]
The 2nd instance is not live anymore. Please re-open if the issue is still reproducible.
