### ISSUE TITLE
Build in docker-compose

### ISSUE THREAD

**Issue by Neoblock8** [blockscout/blockscout#7491]
Hi @vbaranov,
  If i modified any one file in blockscout. Should I build all docker images?
  
  Because it takes too long to progress.

**Comment by vbaranov** [comment]
If you modified files in main blockscout repo, you should rebuild blockscout docker image only.

**Comment by Neoblock8** [comment]
> If you modified files in main blockscout repo, you should rebuild blockscout docker image only.

Does it will take long time?

**Comment by vbaranov** [comment]
Rebuilding of Docker image could take tens of minutes.

**Comment by Neoblock8** [comment]
> Rebuilding of Docker image could take tens of minutes.

Connecting blockscout with local network.
For instance: If i modified **_dashboard-banner.scss** under assets folder. Then i rebuild with docker-compose "**docker-compose build**" . It will merely takes one hour.

**Comment by vbaranov** [comment]
It depends on the resources of the machine, where you build. I am closing this. Let me know, if you have further requests.
