### ISSUE TITLE
Linea Testnet: <Issue Title>execution reverted

### ISSUE THREAD

**Issue by Divyanshukulshrestha** [blockscout/blockscout#7498]
![Screenshot (158)](https://github.com/blockscout/blockscout/assets/121822488/b89ac690-66a1-44fc-8bb9-f6722435af8c)
*Describe your issue here.*

### Environment
* Elixir Version: 1.14.0
* Erlang Version: 25
* BlockScout Version: v5.1.3-beta

* User Agent: `Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/113.0.0.0 Safari/537.36`

### Steps to reproduce

*Tell us how to reproduce this issue. If possible, push up a branch to your fork with a regression test we can run to reproduce locally.*

### Expected Behaviour

*Tell us what should happen.*

### Actual Behaviour

*Tell us what happens instead.*

**Comment by vbaranov** [comment]
You should address your question to Linea testnet support.
