### ISSUE TITLE
need suggestion regarding fetching market history data

### ISSUE THREAD

**Issue by webdeveloper20213** [blockscout/blockscout#7503]
The [api_endpoint](https://min-api.cryptocompare.com/data/histoday?fsym=source_cryptocurrency&limit=number&tsym=destination_currency)  which you guys have used to fetch the market history data, doesn't give us the data for the specific cryptocurrency that we are using..!

So can you give us some other ways we can use to get this done...?, any other API suggestions...?

**Comment by vbaranov** [comment]
In addition to CryptoCompare, CoinGecko, CoinMarketCap are the currently available options.
