### ISSUE TITLE
Running BlockScout with a 'recent' archive node

### ISSUE THREAD

**Issue by dreadedhamish** [blockscout/blockscout#7512]
If I had a 'recent' archive node, either by converting GETH to an archive at some point, or using Erigon to prune everything before a specific block, would Blockscout happily index everything that is present, or would it throw errors expecting there to be more records?

**Comment by vbaranov** [comment]
Yes, Blockscout will throw errors in this case. In order to mitigate the issue, you should set `FIRST_BLOCK` environment variable with the block number, when you switched to archive mode. Thus, Blockscout will not request internal transactions below this block number.

**Comment by dreadedhamish** [comment]
> 

thankyou! that is so helpful.
