### ISSUE TITLE
Rank the records being shown in the TokenHolders page

### ISSUE THREAD

**Issue by igorffs** [blockscout/blockscout#752]
Each TokenHolders in the TokenHolders tab should have a rank number.

### Observation

- This requirement first appeared in #516 and was unprioritized at the time so we could have a first version of the feature due to the considerations in https://github.com/poanetwork/blockscout/pull/668#issuecomment-418188618. 
- This issue may require a different pagination approach so we can make the ranking.

**Comment by Lucasnar** [comment]
Just to complement this description: we ended up agreeing to use `limit` + `offset` in order to easily allow both pagination and ranking. We limited the number of pages to 20, with 50 records per page.

Is that right, @acravenho?
