### ISSUE TITLE
Mix Compilation Error: (CompileError) lib/block_scout_web/templates/layout/_default_title.html.eex:2

### ISSUE THREAD

**Issue by Mentors4EDU** [blockscout/blockscout#7522]
I keep getting an error trying to compile with Mix.
```
Generating BlockScoutWeb.Cldr for 2 locales named [:en, :und] with a default locale named :en
Compiling lib/block_scout_web/cldr.ex (it's taking more than 10s)
warning: undefined function subnetwork_title/0 (expected BlockScoutWeb.LayoutView to define such a function or for it to be imported, but none are available)
  lib/block_scout_web/views/layout_view.ex:157

warning: undefined function subnetwork_title/0 (expected BlockScoutWeb.LayoutView to define such a function or for it to be imported, but none are available)
  lib/block_scout_web/views/layout_view.ex:62

warning: undefined function subnetwork_title/0 (expected BlockScoutWeb.LayoutView to define such a function or for it to be imported, but none are available)
  lib/block_scout_web/templates/layout/_topnav.html.eex:161

warning: undefined function subnetwork_title/0 (expected BlockScoutWeb.LayoutView to define such a function or for it to be imported, but none are available)
  lib/block_scout_web/templates/layout/_topnav.html.eex:9

warning: undefined function subnetwork_title/0 (expected BlockScoutWeb.LayoutView to define such a function or for it to be imported, but none are available)
  lib/block_scout_web/templates/layout/_footer.html.eex:8


== Compilation error in file lib/block_scout_web/views/layout_view.ex ==
** (CompileError) lib/block_scout_web/templates/layout/_default_title.html.eex:2: undefined function subnetwork_title/0 (expected BlockScoutWeb.LayoutView to define such a function or for it to be imported, but none are available)
```
### Environment

* Deployment type (Manual/Docker/Docker-compose): Manual
* Elixir & Erlang/OTP versions (`elixir -version`): Elixir 1.13.4 (compiled with Erlang/OTP 25)
* Node JS version (`node -v`): v18.16.0
* Operating System: Ubuntu 20.04 (LTS) x64
* Blockscout Version/branch/commit: [BlockScout v5.1.4-beta](https://github.com/blockscout/blockscout/releases/tag/v5.1.4-beta)
* Archive node type && version (Erigon/Geth/Nethermind/Ganache/?): Self-hosted EVM Network ~ https://evm.cloutcontracts.net

### Steps to reproduce

*Tell us how to reproduce this issue.  ❤️ if you can push up a branch to your fork with a regression test we can run to reproduce locally.*

Ran `mix do deps.get, local.rebar --force, deps.compile` in base directory

### Expected behaviour

*Tell us what should happen.*
Compile without error
### Actual behaviour

*Tell us what happens instead.*
Has these lines:
```Compiling 274 files (.ex)
Generating BlockScoutWeb.Cldr for 2 locales named [:en, :und] with a default locale named :en
Compiling lib/block_scout_web/cldr.ex (it's taking more than 10s)
```
Then prints out a fail

**Comment by alokeutpal** [comment]
Total disgusting system

**Comment by vbaranov** [comment]
@Mentors4EDU did you make customizations to the code of the release? It looks impossible to have errors, you mentioned, with that release: `subnetwork_title` function is defined in the release actually https://github.com/blockscout/blockscout/blob/v5.1.4-beta/apps/block_scout_web/lib/block_scout_web/views/layout_view.ex#L50-L52

**Comment by vbaranov** [comment]
Closing due to no response from the author.
