### ISSUE TITLE
docker-compose   M1 error

### ISSUE THREAD

**Issue by Osub** [blockscout/blockscout#7525]
docker-compose -f docker-compose-no-build-hardhat-network.yml up
[+] Running 3/4
 ✘ smart-contract-verifier Error                                                                                                                                                2.9s 
 ✘ sig-provider Error                                                                                                                                                           2.9s 
 ⠇ visualizer Pulling                                                                                                                                                           2.9s 
 ✘ blockscout Error                                                                                                                                                             2.9s 
no matching manifest for linux/arm64/v8 in the manifest list entries

**Comment by alexroan** [comment]
Same here on M2 chip

**Comment by sl1depengwyn** [comment]
Duplicate of https://github.com/blockscout/blockscout/issues/6787
