### ISSUE TITLE
Inconsistent blockscout user experience while indexing (503)

### ISSUE THREAD

**Issue by 0xtzData** [blockscout/blockscout#7528]
Opening 
https://eth.blockscout.com/txs
https://eth.blockscout.com/blocks
have a chance to return 503 on all APIs while Blockscout is still indexing a lot of old blocks

![Image](https://user-images.githubusercontent.com/108135703/239830344-163b913a-c652-40a5-ac18-dd1dbab19e40.png)

**Comment by vbaranov** [comment]
I cannot reproduce the issue. If the issue is still reproducible, could you please provide steps in order to repro? I am closing this for now.
