### ISSUE TITLE
Need help to separate the transaction view just like block view using socket

### ISSUE THREAD

**Issue by webdeveloper20213** [blockscout/blockscout#7530]
**[image-1]**
![Screenshot from 2023-05-22 17-37-27](https://github.com/blockscout/blockscout/assets/133633860/167c9ed8-8bab-45ba-8ed5-44fcd698b095)

You can see in the above screenshot there is **Transactions** data being displayed..

**[image-2]**
![Screenshot from 2023-05-22 17-37-40](https://github.com/blockscout/blockscout/assets/133633860/b374634b-6773-4921-a999-477671a3d3e4)

When we click on the **View All Transactions** which is there in the [image-1], it will redirect us to the [image-2] which contains the same data which is there in the [image-1], the only things changes in [image-2] is design.
after initial loading the latest transactions data will be pushed to the respective UI pages using socket in your implementation . 

Now our query is :
-we are working on Transactions sections,and we want the same behaviour as describe above for our Transactions sections, there also after initial loading we are getting the latest data using socket, and we are successfully able to separate the UI pages as show in image-1,2 for the initial data.!
-but only things that we are unable to do is after initial loading, when latest data comes using socket we unable to push that data to the two different file for UI pages of transaction section.
-can you describe in what files we should make change so that we would be able to push the latest data which comes using socket to the two different UI pages of transaction section.

**Comment by Mojmir-R** [comment]
Hey, @webdeveloper20213, Mojmir from the Blockscout BD team here. Do you mind pinging me on Telegram at Mojmir_R? I would love to chat more about your use case and how we can best collaborate. Thank you!

**Comment by vbaranov** [comment]
We do not consider new features for the old UI. Please create the issue in https://github.com/blockscout/frontend (new Blockscout UI), if it is still relevant.
