### ISSUE TITLE
Indexer fetch 1 millisecond one time

### ISSUE THREAD

**Issue by khaitqNapaglobal** [blockscout/blockscout#7536]
How to config indexer fetch data slowly, present I saw the indexer fetch 1 millisecond one time. Because I scare speed fetch data very fast will die server

**Comment by vbaranov** [comment]
@khaitqNapaglobal how do you track that 1ms? Which types of requests from Blockscout do you see with such frequency?

**Comment by khaitqNapaglobal** [comment]
in general, I find the scan speed very fast, is there any way to slow it down?

**Comment by vbaranov** [comment]
In general, in order to decrease the speed of indexing = send fewer requests to the node, you should decrease the concurrency of the catchup fetchers. For instance, set it to 1:
```
INDEXER_CATCHUP_BLOCKS_CONCURRENCY=1
INDEXER_INTERNAL_TRANSACTIONS_CONCURRENCY=1
INDEXER_BLOCK_REWARD_CONCURRENCY=1
INDEXER_RECEIPTS_CONCURRENCY=1
INDEXER_COIN_BALANCES_CONCURRENCY=1
INDEXER_TOKEN_INSTANCE_RETRY_CONCURRENCY=1
INDEXER_TOKEN_INSTANCE_REALTIME_CONCURRENCY=1
INDEXER_TOKEN_INSTANCE_SANITIZE_CONCURRENCY=1
```

Please, keep in mind, as a drawback, it will slow down indexing progress.

**Comment by khaitqNapaglobal** [comment]
thank you so much
