### ISSUE TITLE
Compilation Issue of mix phx.server

### ISSUE THREAD

**Issue by Neoblock8** [blockscout/blockscout#7540]
Hi @vbaranov,

1.Clone blockscout from github.

2.Running postgresql by using below command: 
pg_ctl -D /usr/local/var/postgres status
pg_ctl -D /usr/local/var/postgres start

*Postgres server is running.

3.Compilation process completed
   mix do deps.get, local.rebar --force, deps.compile
   
 4. mix compile
 5. Created and migrate database:
     mix do ecto.create, ecto.migrate 
6. Installed all Node.js dependencies

7. **If we running this phx server [mix phx.server], it will show error**

![WhatsApp Image 2023-05-23 at 5 38 53 PM](https://github.com/blockscout/blockscout/assets/81068101/de460196-ac3c-4a09-baa7-f947f601ec02)

Can you give a suggestion?

**Comment by vbaranov** [comment]
@Neoblock8 did you setup `DATABASE_URL` with the proper DB URL?

**Comment by Neoblock8** [comment]
> @Neoblock8 did you setup `DATABASE_URL` with the proper DB URL?

Yes,

**Comment by Neoblock8** [comment]
> > @Neoblock8 did you setup `DATABASE_URL` with the proper DB URL?
> 
> Yes,

Shall we create a user and DB manually in postgres?

Or

It will create automatically while running **mix create** command

**Comment by vbaranov** [comment]
You should create DB and user manually.

**Comment by Neoblock8** [comment]
> You should create DB and user manually.

Signup tab is not coming while compile using mix phx.server.
Can we give any export command?


While running in docker-compose it will show

**Comment by vbaranov** [comment]
Please take a look at https://docs.blockscout.com/for-developers/configuration-options/my-account-settings

**Comment by Neoblock8** [comment]
> Please take a look at https://docs.blockscout.com/for-developers/configuration-options/my-account-settings

ENV variable:
export SECRET_KEY_BASE=<Ur_secret_key>
export ETHEREUM_JSONRPC_VARIANT=geth
export MICROSERVICE_SC_VERIFIER_ENABLED=true
export MICROSERVICE_SC_VERIFIER_URL=http://0.0.0.0:8050/
export ETHEREUM_JSONRPC_HTTP_URL=http://127.0.0.1:8545/
export ETHEREUM_JSONRPC_WS_URL="ws://127.0.0.1:8546"                                                                                                                                                           export ETHEREUM_JSONRPC_TRACE_URL="ws://127.0.0.1:8545"    
export HOSTNAME="localhost"     
export DATABASE_URL='postgresql://postgres:postgres@localhost:5432/explorer_dev              
export COIN=ETH                                                                                                                                                                                                                                                                                                               export LANG=en_US.UTF-8                                                                                                                                                                                         export LANGUAGE=en_US                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          export BLOCKSCOUT_PROTOCOL=http                                                                                                                                                                                export PORT=4000                                                                                                                                                                                               export MIX_ENV=prod  
export ECTO_USE_SSL=false 
export CURRENCY=ETH
export LOGO="/images/header_logo.svg"    
export LOGO_FOOTER="/images/logo_footer.svg"   
export LOGO_HEADER="/images/header_logo.svg"  
export NETWORK=""
export DISABLE_EXCHANGE_RATES=false   
export SUBNETWORK="ETH"
export LINK_TO_OTHER_EXPLORERS="false"     
export BLOCK_TRANSFORMER=clique            
export INDEXER_DISABLE_BLOCK_REWARD_FETCHER = false      
export POS_STAKING_CONTRACT=true   
export  FOOTER_TELEGRAM_LINK_ENABLED = true
export FOOTER_TELEGRAM_LINK = “<your_link>”
export FOOTER_FORUM_LINK_ENABLED = true
export FOOTER_FORUM_LINK = “<your_link>”
export FOOTER_LINK_TO_OTHER_EXPLORERS = false
export CONTRACT_DISABLE_INTERACTION = true
export ACCOUNT_ENABLED = true
export SUPPORTED_CHAINS={}
export APPS_MENU = true


**We need this sign tab.**

Can we add any other command?
![image](https://github.com/blockscout/blockscout/assets/81068101/5520fd5a-d3c9-46f6-9fcb-089203907c57)
