### ISSUE TITLE
Indexing notification is hanging even after 100% indexing

### ISSUE THREAD

**Issue by 0xtzData** [blockscout/blockscout#7550]
On `https://blockscout-optimism-goerli.k8s-dev.blockscout.com/`
`https://blockscout-optimism-goerli.k8s-dev.blockscout.com/api/v2/main-page/indexing-status`
```
{"finished_indexing":false,"finished_indexing_blocks":true,"indexed_blocks_ratio":"1.00","indexed_internal_transactions_ratio":"1.00"}
```
Indexing notification is present even when all txns/internal are collected, is it working correctly?

![Image](https://user-images.githubusercontent.com/108135703/240862302-5ef4a7ac-23da-4ecd-b179-22b9d9d6cf83.png)

**Comment by vbaranov** [comment]
Resolved by https://github.com/blockscout/blockscout/pull/7590
