### ISSUE TITLE
Andromeda: Data export fail

### ISSUE THREAD

**Issue by merlinseph** [blockscout/blockscout#7551]
*Describe your issue here.*

Data fails to download

* User Agent:  Chrome/113.0.0.0

### Steps to reproduce

Set date range to download Andromeda blockchain transactions for tax reporting purposes.
Made many repeated attempts over different days and times, even shortening the date range to 10 days.

### Expected Behaviour

Completed CSV file downloaded.

### Actual Behaviour

Warning notice that the download failed

**Comment by vbaranov** [comment]
The issue should be resolved. Please let us know, if the issue still persists and provide live link in order to reproduce it.
