### ISSUE TITLE
Transaction stuck

### ISSUE THREAD

**Issue by mshihata** [blockscout/blockscout#7571]
*Describe your issue here.*

I tried transferring an amount from milkomeda to an exchange but the exchange can’t seem to access it. And when I check it may be still stuck somewhere in between

0x59c512c0a2c2f368f6c87ee78b0ef7e8317c55bc0f731b7000ad4c2866f5eadd

### Environment
* Elixir Version: 1.13.1
* Erlang Version: 24
* BlockScout Version: v4.1.7-beta

* User Agent: `Mozilla/5.0 (iPhone; CPU iPhone OS 16_5 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Mobile/15E148`

### Steps to reproduce

*Tell us how to reproduce this issue. If possible, push up a branch to your fork with a regression test we can run to reproduce locally.*

### Expected Behaviour

*Tell us what should happen.*

### Actual Behaviour

*Tell us what happens instead.*

**Comment by vbaranov** [comment]
Please contact to Milkomeda chain support. This is chat is for Blockscout-related questsions.
