### ISSUE TITLE
Failed to fetch internal transactions for blocks

### ISSUE THREAD

**Issue by khaitqNapaglobal** [blockscout/blockscout#7586]
Sorry for the inconvenience,
You can support me with this issue?

<img width="1499" alt="Screenshot 2023-05-30 at 16 43 30" src="https://github.com/blockscout/blockscout/assets/108641766/f28e30fb-f811-4374-91c4-1c9f07716252">

<img width="1505" alt="Screenshot 2023-05-30 at 17 09 04" src="https://github.com/blockscout/blockscout/assets/108641766/c6880082-aa49-46be-b810-90edbcea4e48">

RPC: https://ethereum.publicnode.com
Erlang/OTP 24
Elixir 1.14.4

**Comment by sl1depengwyn** [comment]
Your node does not support debug methods, you can either change the node or disable internal transactions fetching via `INDEXER_DISABLE_INTERNAL_TRANSACTIONS_FETCHER=true`
