### ISSUE TITLE
Linea Testnet: <Stuck transactions>

### ISSUE THREAD

**Issue by Lvmnvnt** [blockscout/blockscout#7604]
im not able to process any tx by any method or forcing the nonce
https://explorer.goerli.linea.build/address/0xbCfc71db90338A867Df0dA6A2A3b661c780215ff

wallet restored, cancel manual transctions and nothing. Pls help

### Environment
* Elixir Version: 1.14.0
* Erlang Version: 25
* BlockScout Version: v5.1.3-beta

* User Agent: `Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/113.0.0.0 Safari/537.36`

### Steps to reproduce

*Tell us how to reproduce this issue. If possible, push up a branch to your fork with a regression test we can run to reproduce locally.*

### Expected Behaviour

*Tell us what should happen.*

### Actual Behaviour

*Tell us what happens instead.*

**Comment by vbaranov** [comment]
Please ask this question in Linea Discord, which can be found here https://goerli.linea.build.
