### ISSUE TITLE
Andromeda: <Issue Title>

### ISSUE THREAD

**Issue by Troskiev83** [blockscout/blockscout#7606]
*Describe your issue here.*

### Environment
* Elixir Version: 1.14.0
* Erlang Version: 25
* BlockScout Version: v5.1.5-beta

* User Agent: `Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36`

### Steps to reproduce

Want to download all transactions for account: 0x18D1EB6F4a74aB1d4704ec1688d87047efDb83D5

### Expected Behaviour

Download CSV with all transactions 

### Actual Behaviour

Fails. 
<img width="1162" alt="image" src="https://github.com/blockscout/blockscout/assets/57766291/678d941d-acc5-4653-a967-691d80f71ea2">

**Comment by vbaranov** [comment]
Please try decreasing period of export.

**Comment by Troskiev83** [comment]
I've also tried and failed again

**Comment by vbaranov** [comment]
The issue should be resolved. Please let us know, if the issue still persists and provide live link in order to reproduce it.
