### ISSUE TITLE
Documentation / build procedure on building each service docker images are missing

### ISSUE THREAD

**Issue by wighawag** [blockscout/blockscout#7607]
Documentation / build procedure on building each service docker images are missing

### Expected behaviour

I expect to be able to build each blockscout's service docker image from the source code provided in this repo

### Actual behaviour

Currently apart from the main blockscout image [docker/Dockerfile](https://github.com/blockscout/blockscout/blob/master/docker/Dockerfile) there seems to be no documented procedure to generate the other docker images

- ghcr.io/blockscout/frontend
- ghcr.io/blockscout/sig-provider
- ghcr.io/blockscout/smart-contract-verifier
- ghcr.io/blockscout/visualizer

Solving this would allow me to solve https://github.com/blockscout/blockscout/issues/7596

**Comment by vbaranov** [comment]
> ghcr.io/blockscout/frontend

A new frontend is currently private. There is a discussion about early access requests https://github.com/orgs/blockscout/discussions/7121. Would you like to get access too?

As for Rust microservices, @rimrakhimov is a better person who can advise on proper Docker files for them. @rimrakhimov, could you please advise?

**Comment by rimrakhimov** [comment]
Hi, @wighawag

Rust microservices are located in a separate repository (https://github.com/blockscout/blockscout-rs). Corresponding dockerfiles could also be found there: [sig-provider](https://github.com/blockscout/blockscout-rs/blob/main/sig-provider/Dockerfile), [smart-contract-verifier](https://github.com/blockscout/blockscout-rs/blob/main/smart-contract-verifier/smart-contract-verifier-server/Dockerfile), [visualizer](https://github.com/blockscout/blockscout-rs/blob/main/visualizer/Dockerfile), [stats](https://github.com/blockscout/blockscout-rs/blob/main/stats/Dockerfile)
