### ISSUE TITLE
custom svg logo 

### ISSUE THREAD

**Issue by ranjith-edx** [blockscout/blockscout#7612]
_Originally posted by @ZebroTech in https://github.com/blockscout/blockscout/issues/7342#issuecomment-1522857378_
            
this i'm having same prob i have added the custom svg logo in the apps/block_scout_web/assets/static/images and added in the env as well but after build it gives not found error 404 but the custom svg is in the path as same as blockscout_logo.svg

**Comment by ranjith-edx** [comment]
i'm using docker compose @vbaranov

**Comment by vbaranov** [comment]
You need to rebuild the docker image after the changes.

**Comment by ranjith-edx** [comment]
yes i rebuilt it but still gives me 404 not found can you test once please 

just add an svg sample logo new one in images folder and try to build and run it

**Comment by ranjith-edx** [comment]
Got fixed the issue with https://github.com/blockscout/blockscout/issues/7549#issuecomment-1589676536
