### ISSUE TITLE
Data fetching issue

### ISSUE THREAD

**Issue by Neoblock8** [blockscout/blockscout#7615]
Hi @vbaranov,
Running blockscout in local and connect with geth node. But our database is running successfully and tables are created.

But Data of block and transactions are not showing.
Below image is the issue, while running 'mix phx.server'

![image](https://github.com/blockscout/blockscout/assets/81068101/7799a6bc-0fdb-4e3e-9b1b-394add081817)

**Comment by vbaranov** [comment]
@Neoblock8 how powerful is DB? Can you increase resources on it? And increase `POOL_SIZE` env variable value on the application side?

**Comment by vbaranov** [comment]
Closing due to no answer from the author.
