### ISSUE TITLE
Ethereum Classic: <Issue Title>

### ISSUE THREAD

**Issue by 69ellie** [blockscout/blockscout#7616]
*Describe your issue here.*

### Environment
* Elixir Version: 1.13.1
* Erlang Version: 24
* BlockScout Version: v4.1.8-beta

* User Agent: `Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/113.0.0.0 Safari/537.36 Edg/113.0.1774.50`

### Steps to reproduce

*Tell us how to reproduce this issue. If possible, push up a branch to your fork with a regression test we can run to reproduce locally.*

### Expected Behaviour

*Tell us what should happen.*

### Actual Behaviour

*Tell us what happens instead.*

**Comment by 69ellie** [comment]
I don't understand how Pull Request works. How do I use it to recover my ETC? I have been trying to do this for months now. Coinbase stopped supporting ETC and sent my assets to Blockscout. Every time I request help for this issue, I get an email which states Close# and completed when it has not been. If I don't respond right away, it's because I had to step away from my computer. Can you explain how Pull Request works or give me more information? Thank you. Ellie #7616    On Friday, June 2, 2023 at 02:07:37 PM CDT, nikitosing ***@***.***> wrote:  
 
 


Closed #7616 as completed.

**Comment by nikitosing** [comment]
@69ellie you need to contact coinbase support I guess. You submitted ticket to the BlockScout repo. BlocksScout is an open source block explorer. We cannot help with that problem on ETC.
