### ISSUE TITLE
I want to include my new project in Blockscout.

### ISSUE THREAD

**Issue by gethub2022** [blockscout/blockscout#7620]
*Describe your issue here.*

### Environment

* Deployment type (Manual/Docker/Docker-compose):
* Elixir & Erlang/OTP versions (`elixir -version`):
* Node JS version (`node -v`):
* Operating System:
* Blockscout Version/branch/commit:
* Archive node type && version (Erigon/Geth/Nethermind/Ganache/?):

### Steps to reproduce

*Tell us how to reproduce this issue.  ❤️ if you can push up a branch to your fork with a regression test we can run to reproduce locally.*

### Expected behaviour

*Tell us what should happen.*

### Actual behaviour

*Tell us what happens instead.*

**Comment by vbaranov** [comment]
What is your project about? Do you have a public link to the explorer?

**Comment by gethub2022** [comment]
Hello, The name of our project is SocialVerse. ''Next generation social
blockchain community!''. https://socialverse.app is the name of our site.
We are considering using https://explorer.socialverse.app as explorer. We
are planning to build a big community. May I know the price information?

5 Haz 2023 Pzt, saat 10:54 tarihinde Victor Baranov <
***@***.***> şunu yazdı:

**Comment by vbaranov** [comment]
Please find contact info here https://docs.blockscout.com/for-projects/premium-features/your-chain-on-blockscout.com#hosting-your-chain-on-blockscout.com
