### ISSUE TITLE
Frontend UI Docker

### ISSUE THREAD

**Issue by avenbreaks** [blockscout/blockscout#7621]
Error compiling frontend docker-compose.

curl -I https://ghcr.io/v2/blockscout/frontend/manifests/latest
HTTP/2 401 
content-type: application/json
www-authenticate: Bearer realm="https://ghcr.io/token",service="ghcr.io",scope="repository:blockscout/frontend:pull"
date: Sat, 03 Jun 2023 16:41:50 GMT
content-length: 73
x-github-request-id: A640:5EB3:A27077:EE9006:647B6D4E

**Comment by avenbreaks** [comment]
@vbaranov hi sir, frontend files is private or subscription user? i cannot compile the docker image

**Comment by vbaranov** [comment]
@avenbreaks new frontend docker image is currently private. Please join this discussion https://github.com/orgs/blockscout/discussions/7121 in order to request early access.
