### ISSUE TITLE
Codornix: <Issue Title>

### ISSUE THREAD

**Issue by Naz1980SHRK** [blockscout/blockscout#7625]
*Describe your issue here.*good evening,
I did a transfer of my ether funds, but have not received them in the given wallet address.
Could you please check.

Kind regards 

### Environment
* Elixir Version: 1.14.0
* Erlang Version: 25
* BlockScout Version: v5.1.4-beta

* User Agent: `Mozilla/5.0 (Linux; Android 13; SM-G991B Build/TP1A.220624.014; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/113.0.5672.163 Mobile Safari/537.36`

### Steps to reproduce

*Tell us how to reproduce this issue. If possible, push up a branch to your fork with a regression test we can run to reproduce locally.*

### Expected Behaviour

*Tell us what should happen.*

### Actual Behaviour

*Tell us what happens instead.*

**Comment by vbaranov** [comment]
This chat is for technical issues with Blockscout explorer. Your question is out of the scope of Blockscout explorer support.
