### ISSUE TITLE
ecto.create is not reading DATABASE_URL from the env file

### ISSUE THREAD

**Issue by yaziciahmet** [blockscout/blockscout#7627]
`mix do ecto.create` command is not working properly. It seems to not read the DATABASE_URL from env file. The database is a remote database url. I tested the url I am using and it is alive and connectable. But for some reason it tries to connect localhost for database.

### Environment

* Deployment type (Manual/Docker/Docker-compose): Manual
* Elixir & Erlang/OTP versions (`elixir -version`): elixir: 1.13.4 Erlang/OTP 25 [erts-13.0.4]
* Node JS version (`node -v`): v16.20.*
* Operating System: ubuntu 20.04
* Blockscout Version/branch/commit: 62c71dac67a4f1a139bd6d41b303926d17f0d231
* Archive node type && version (Erigon/Geth/Nethermind/Ganache/?): geth

### Steps to reproduce

- Clone blockscout repo
- Create env_vars.env file inside blockscout project with following variables:
```
        ETHEREUM_JSONRPC_HTTP_URL="{{ETHEREUM_JSONRPC_HTTP_URL}}"
        ETHEREUM_JSONRPC_TRACE_URL="{{ETHEREUM_JSONRPC_TRACE_URL}}"
        ETHEREUM_JSONRPC_WS_URL="{{ETHEREUM_JSONRPC_WS_URL}}"
        ETHEREUM_JSONRPC_VARIANT=geth
        DATABASE_URL='{{DATABASE_URL}}'
        SECRET_KEY_BASE={{SECRET_KEY_BASE}}
        CHAIN_ID={{CHAIN_ID}}
        HEART_COMMAND=/usr/bin/systemctl restart blockscout.service
        SUBNETWORK="{{SUBNETWORK}}"
        MIX_ENV=prod
```
- `mix local.hex --force`
- `mix do deps.get, local.rebar --force, deps.compile, compile`
- `mix do ecto.create, ecto.migrate`

### Expected behaviour

Database is populated using the `mix do ecto.create` command.

### Actual behaviour

It throws this error:
```
10:43:32.026 [error] Postgrex.Protocol (#PID<0.797.0>) failed to connect: ** (DBConnection.ConnectionError) tcp connect (localhost:5432): connection refused - :econnrefused

10:43:32.041 [error] Postgrex.Protocol (#PID<0.803.0>) failed to connect: ** (DBConnection.ConnectionError) tcp connect (localhost:5432): connection refused - :econnrefused
** (Mix) The database for Explorer.Repo couldn't be created: killed
```

**Comment by GouthamJM** [comment]
I am getting the same error - 
I have updated env in common-blockscout.env


```
# DOCKER_TAG=
ETHEREUM_JSONRPC_VARIANT=geth
ETHEREUM_JSONRPC_HTTP_URL=https://eth.llamarpc.com
# ETHEREUM_JSONRPC_FALLBACK_HTTP_URL=
DATABASE_URL=postgres://postgres:password@localhost:5432/blockscout
ETHEREUM_JSONRPC_TRACE_URL=http://host.docker.internal:8545/

```

<img width="585" alt="Screenshot 2023-08-02 at 11 01 32 AM" src="https://github.com/blockscout/blockscout/assets/67677902/4ed66637-b3a6-4000-b9a9-b7c26307bb44">

**Comment by sl1depengwyn** [comment]
> I am getting the same error @vbaranov vbaranov - I have updated env in common-blockscout.env
> 
> ```
> # DOCKER_TAG=
> ETHEREUM_JSONRPC_VARIANT=geth
> ETHEREUM_JSONRPC_HTTP_URL=https://eth.llamarpc.com
> # ETHEREUM_JSONRPC_FALLBACK_HTTP_URL=
> DATABASE_URL=postgres://postgres:password@localhost:5432/blockscout
> ETHEREUM_JSONRPC_TRACE_URL=http://host.docker.internal:8545/
> ```
> 
> <img alt="Screenshot 2023-08-02 at 11 01 32 AM" width="585" src="https://user-images.githubusercontent.com/67677902/257710993-4ed66637-b3a6-4000-b9a9-b7c26307bb44.png">

`common-blockscout.env` is for docker, you need to do `export DATABASE_URL=postgres://postgres:password@localhost:5432/blockscout` 
you can check if any env is really available like so `echo $DATABASE_URL`
