### ISSUE TITLE
Linea goerli focet not claimed 0x0B518f99683ddBB7b31D7AaaeEca598b370b1adF

### ISSUE THREAD

**Issue by St578865** [blockscout/blockscout#7640]
*Describe your issue here.*

### Environment
* Elixir Version: 1.14.0
* Erlang Version: 25
* BlockScout Version: v5.1.3-beta

* User Agent: `Mozilla/5.0 (Linux; Android 11; SM-M017F Build/RP1A.200720.012; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/113.0.5672.131 Mobile Safari/537.36`
My linea goerly fouset not claimed 0x0B518f99683ddBB7b31D7AaaeEca598b370b1adF
### Steps to reproduce

*Tell us how to reproduce this issue. If possible, push up a branch to your fork with a regression test we can run to reproduce locally.*

### Expected Behaviour

*Tell us what should happen.*

### Actual Behaviour

*Tell us what happens instead.*

**Comment by St578865** [comment]
I claimed linea goerli but it not showing  in my account  0x0B518f99683ddBB7b31D7AaaeEca598b370b1adF

**Comment by vbaranov** [comment]
Please ask this question in Linea Discord, which can be found here https://goerli.linea.build.
