### ISSUE TITLE
Can not add Extra headers with RPC URL

### ISSUE THREAD

**Issue by isurutmv** [blockscout/blockscout#7645]
I want to pass extra headers with my Json RPC Url like api key, I didn't find any method in the code to pass the header is there any method that I can pass custom headers with RPC URL

**Comment by vbaranov** [comment]
I think it is currently not supported yet. In case auth on the node Blockscout currently supports Basic auth via `ETHEREUM_JSONRPC_USER` and `ETHEREUM_JSONRPC_PASSWORD`
