### ISSUE TITLE
Optimism Mainnet: <Issue Title>

### ISSUE THREAD

**Issue by vladisvobo** [blockscout/blockscout#7651]
*Describe your issue here.*

### Environment
* Elixir Version: 1.14.0
* Erlang Version: 25
* BlockScout Version: v5.1.5-beta.+commit.a4670db4

* User Agent: `Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/113.0.0.0 Mobile Safari/537.36`

### Steps to reproduce

*Tell us how to reproduce this issue. If possible, push up a branch to your fork with a regression test we can run to reproduce locally.*

### Expected Behaviour

*Tell us what should happen.*

### Actual Behaviour

*Tell us what happens instead.*

**Comment by vbaranov** [comment]
@vladisvobo what is your issue?

**Comment by vbaranov** [comment]
Closing due to no response from the author.
