### ISSUE TITLE
Fail to run blockscout locally with docker-compose instructions

### ISSUE THREAD

**Issue by vch9** [blockscout/blockscout#7656]
Hi all, I'm trying to deploy the explorer with a custom JSON-RPC client I'm working on, by following the [documentation](https://docs.blockscout.com/for-developers/information-and-settings/docker-integration-local-use-only). However it always fails to start the blockscout container , see below for the error

It's the very first time I'm using the software so I don't have a clue what's going on. For what it's worth, I tried to deploy manually blockscout and it went better. Would this ring a bell? Am I doing something incredibly stupid?

### Environment

* Deployment type (Manual/Docker/Docker-compose): docker-compose
* Elixir & Erlang/OTP versions (`elixir -version`): N/A
* Node JS version (`node -v`): N/A
* Operating System: Ubuntu
* Blockscout Version/branch/commit: `7b0703f633ff98cd5c20b6a90930b495618ea6ba`
* Archive node type && version (Erigon/Geth/Nethermind/Ganache/?): `geth`

### Steps to reproduce

```
$ cd docker-compose
$ docker-compose up
```

### Expected behaviour

Blockscout at http://localhost:4000. 

### Actual behaviour

The container blockscout fails, here are the logs:

```
2023-06-07T15:08:55.906 application=ecto_sql [error] Could not create schema migrations table. This error usually happens due to the following:

  * The database does not exist
  * The "schema_migrations" table, which Ecto uses for managing
    migrations, was defined by another library
  * There is a deadlock while migrating (such as using concurrent
    indexes with a migration_lock)

To fix the first issue, run "mix ecto.create" for the desired MIX_ENV.

To address the second, you can run "mix ecto.drop" followed by
"mix ecto.create", both for the desired MIX_ENV. Alternatively you may
configure Ecto to use another table and/or repository for managing
migrations:

    config :explorer, Explorer.Repo,
      migration_source: "some_other_table_for_schema_migrations",
      migration_repo: AnotherRepoForSchemaMigrations

The full error report is shown below.
```

**Comment by sashaaldrick** [comment]
I have exactly the same issue on Ubuntu 22.04 as well

**Comment by sashaaldrick** [comment]
I fixed it by opening the custom port for the postgres container:

`sudo ufw allow 7432/tcp`

and that stopped the deadlock looping

**Comment by cauta** [comment]
I face the same error and this solution work. but i think we should fix it by internal network connection.
The problem might be from bind ip address


> I fixed it by opening the custom port for the postgres container:
> 
> `sudo ufw allow 7432/tcp`
> 
> and that stopped the deadlock looping

**Comment by cauta** [comment]
Change connection to postres in docker-compose:
```
DATABASE_URL: postgresql://postgres:@postgres:5432/blockscout?ssl=false
```

We don't need to connect to postgres though host.docker.internal
firewall gonna deny that request

**Comment by yzh-d** [comment]
Have you solved this problem? I tried the method: sudo ufw allow 7432/tcp, and also tried the method: DATABASE_URL: postgresql://postgres:@postgres:5432/blockscout?ssl=false, but neither solved the problem.

**Comment by vbaranov** [comment]
Please pull updates from the master branch. This issue shouldn't be reproducible anymore since connection Blockscout to the DB happens via its internal name and port now.
