### ISSUE TITLE
Fetcher block_catchup error

### ISSUE THREAD

**Issue by khaitqNapaglobal** [blockscout/blockscout#7662]
I don't know the reason error when starting the indexer, the fetch block catchup failed. help me, please

![Screenshot from 2023-06-08 13-56-51](https://github.com/blockscout/blockscout/assets/108641766/b4865b5d-7ae7-4a58-b293-aec96a252d9f)

**Comment by vbaranov** [comment]
@khaitqNapaglobal This error means, that Blockscout cannot get transaction receipt with `eth_getTransactionReceipt` method for the transaction hashes, which are listed in the error message, from the node.
