### ISSUE TITLE
How do I modify the rpc interface for obtaining internal transactions

### ISSUE THREAD

**Issue by Jaycelv** [blockscout/blockscout#7663]
Because the number of internal transactions is too large, it has a great impact on geth nodes, so I think that the node that obtains internal transactions should be run separately

I want to call a separate geth node for the http request for internal transaction, but I can't find the code where to change it, can you give me a hint

**Comment by sl1depengwyn** [comment]
Try to set `ETHEREUM_JSONRPC_TRACE_URL` env

**Comment by sl1depengwyn** [comment]
> > 
> 
> My chain does not support the trace_replayTransaction method, I use the debug_traceTransaction method, can I also modify this variable

Yes, you can

**Comment by Jaycelv** [comment]
> ETHEREUM_JSONRPC_TRACE_URL

it doesn't work

**Comment by Jaycelv** [comment]
> > > 
> > 
> > 
> > My chain does not support the trace_replayTransaction method, I use the debug_traceTransaction method, can I also modify this variable
> 
> Yes, you can

Do you have any other solutions

**Comment by sl1depengwyn** [comment]
> > ETHEREUM_JSONRPC_TRACE_URL
> 
> it doesn't work

Please, share your configuration, I've tested it locally and it works

**Comment by Jaycelv** [comment]
> > > ETHEREUM_JSONRPC_TRACE_URL
> > 
> > 
> > it doesn't work
> 
> Please, share your configuration, I've tested it locally and it works

here is my env

**Comment by Jaycelv** [comment]
debug_traceTransaction            conn=10.45.24.177:34122 reqid=0       t=13.754µs     err="the method debug_traceTransaction does not exist/is not available"
WARN [06-09|00:45:10.182] Served debug_traceTransaction            conn=10.45.24.177:34122 reqid=0       t=11.243µs     err="the method debug_traceTransaction does not exist/is not available"
WARN [06-09|00:45:10.188] Served debug_traceTransaction            conn=10.45.24.177:34122 reqid=0       t=9.716µs      err="the method debug_traceTransaction does not exist/is not available"
INFO [06-09|00:45:10.197] SyncService sync                         nextIndex=20707 latestIndex=20706
WARN [06-09|00:45:10.200] Served debug_traceTransaction            conn=10.45.24.177:34122 reqid=0       t=7.604µs      err="the method debug_traceTransaction does not exist/is not available"
WARN [06-09|00:45:10.205] Served debug_traceTransaction            conn=10.45.24.177:34122 reqid=0       t=9.109µs      err="the method debug_traceTransaction does not exist/is not available"
WARN [06-09|00:45:10.210] Served debug_traceTransaction            conn=10.45.24.177:34122 reqid=0       t=8.934µs      err="the method debug_traceTransaction does not exist/is not available"

Here is my verifiler log ， I didn't call the rpc corresponding to the ETHEREUM_JSONRPC_HTTP_URL variable, and I sent the related transaction, but it didn't synchronize to the data




> > > > > ETHEREUM_JSONRPC_TRACE_URL
> > > > 
> > > > 
> > > > it doesn't work
> > > 
> > > 
> > > Please, share your configuration, I've tested it locally and it works
> > 
> > 
> > here is my env
> 
> So, how did you conclude that it doesn't work?

**Comment by vbaranov** [comment]
@Jaycelv which version of the explorer do you use?

**Comment by vbaranov** [comment]
@Jaycelv we were unable to reproduce this behavior with the latest version of Blockscout - if ETHEREUM_JSONRPC_TRACE_URL is set, the tracing requests are routed there. Please update your instance. Let me know, if you still experience the issue.
