### ISSUE TITLE
Added AMPLITUDE_API_KEY  but amplitude analytics is not working

### ISSUE THREAD

**Issue by zzq0826** [blockscout/blockscout#7683]
Added `AMPLITUDE_API_KEY`  but amplitude analytics is not working.

After checking and testing, I found that it is because `AMPLITUDE_API_KEY` has been determined in the `docker build`, which is different from other environment variables (in the `docker compose` phase)
### Environment
* Deployment type (Manual/Docker/Docker-compose): Docker-compose
* Blockscout Version/branch/commit: v5.1.4

### Steps to reproduce
Add `AMPLITUDE_API_KEY` to environment variables, run Docker-compose

### Expected behaviour

Upload event information to amplitude analytics.

### Actual behaviour

Not uploaded

**Comment by sl1depengwyn** [comment]
You need to rebuild the container after change of this variable

**Comment by vbaranov** [comment]
No, rebuild is still a requirement for Amplitude configuration.
