### ISSUE TITLE
Frontend Problem only when MIX_ENV=prod

### ISSUE THREAD

**Issue by izakxyz** [blockscout/blockscout#7695]
Hello, I'm trying to Deploy Blockscout Manually, It's all good when MIX_ENV=dev it runs just fine,
But when I set MIX_ENV to prod I get some problems on frontend.
it's like I couldn't load css style files, js and even images.

### Environment

* Deployment type (Manual/Docker/Docker-compose): Manual
* Elixir & Erlang/OTP versions (`elixir -version`): Elixir 1.13.4 & Erlang/OTP 24.2.1
* Node JS version (`node -v`): v16
* Operating System: ubuntu 22.04
* Blockscout Version/branch/commit: v5.1.5
* Archive node type && version (Erigon/Geth/Nethermind/Ganache/?): geth

some of the chrome console logs:

GET http://mysite.com:4000/js/token-transfers-toggle.js net::ERR_ABORTED 404
Refused to apply style from 'http://mysite.com:4000/css/main-page.css' because its MIME type ('text/html') is not a supported stylesheet MIME type, and strict MIME checking is enabled.
GET http://mysite.com:4000/manifest.webmanifest 404
,...

some of the terminal logs:

2023-06-13T03:31:47.020 application=block_scout_web request_id=F2gaau57sCxlbpMAAL_h [info] GET /images/icons/fontawesome/tag.svg
2023-06-13T03:31:47.021 application=block_scout_web request_id=F2gaau5vLErwagEAAKAC [info] Sent 404 in 1ms
2023-06-13T03:31:47.021 application=block_scout_web request_id=F2gaau57sCxlbpMAAL_h [info] Sent 404 in 1ms
2023-06-13T03:31:47.386 application=block_scout_web request_id=F2gaawRN_2x2JEwAAG9D [info] GET /images/favicon-32x32.png
2023-06-13T03:31:47.387 application=block_scout_web request_id=F2gaawRN_2x2JEwAAG9D [info] Sent 404 in 1ms
,...

ENV:
export ETHEREUM_JSONRPC_TRANSPORT=http
export INDEXER_CATCHUP_BLOCKS_BATCH_SIZE=20
export INDEXER_CATCHUP_BLOCKS_CONCURRENCY=20
export ETHEREUM_JSONRPC_HTTP_INSECURE=true
export BLOCKSCOUT_VERSION=5.1.5
export ACCOUNT_ENABLED=false
export DISABLE_EXCHANGE_RATES=false
export SHOW_PRICE_CHART=false
export LOGO=/images/my_logo.png
export FOOTER_LOGO=/images/my_logo.png
export DISPLAY_TOKEN_ICONS=false
export ADMIN_PANEL_ENABLED=false
export DISABLE_ADD_TO_MM_BUTTON=true
export SHOW_TESTNET_LABEL=true
export ETHEREUM_JSONRPC_VARIANT=geth
export TOKEN_EXCHANGE_RATE_INTERVAL=30s
export ETHEREUM_JSONRPC_HTTP_URL=https://fullyworkingprivaterpc.com
export CHAIN_ID=2368
export COIN_NAME=Mychain
export MICROSERVICE_SC_VERIFIER_ENABLED=true
export MICROSERVICE_SC_VERIFIER_URL=http://0.0.0.0:8050/
export COIN=chain
export NETWORK=(CHAIN)
export SUBNETWORK=Mychain
export PORT=4000
export BLOCKSCOUT_HOST=mysite.com
export ECTO_USE_SSL=true
export BLOCKSCOUT_PROTOCOL=https
export LINK_TO_OTHER_EXPLORERS=false
export MIX_ENV=prod

I also had a question, is using ssl mandatory in prod mode? how do i do this? (where do i put my cert files?)
thanks.

**Comment by vbaranov** [comment]
@izakxyz could you please re-compile the application after setting MIX_ENV=prod?
