### ISSUE TITLE
Verify smart contract not fetcher data.

### ISSUE THREAD

**Issue by khaitqNapaglobal** [blockscout/blockscout#7696]
I did verify the smart contract on my chain, but the indexer did not fetch data to table smart_contracts, I don't know. Is there anything wrong with the setup config in the environment? help me.

**Comment by vbaranov** [comment]
Please elaborate on this:
- How did you run Blockscout (docker, manual)? Hos does setup look like? Did you run Rust sc verification service as well? 
- How did you verify contract: through UI or API?
- How did you know, that verification was successful?
- Do you have public link to the contact and verification data?

**Comment by vbaranov** [comment]
Closing due to no response from the author.
