### ISSUE TITLE
Coingecko problem

### ISSUE THREAD

**Issue by polygomic** [blockscout/blockscout#7698]
Only try to fetch maincoin from coingecko with def format_data(supported_coins) when is_list(supported_coins) do
and not try to check tokens on coingeko
i changed my platform  (EXCHANGE_RATES_COINGECKO_PLATFORM_ID) to binance-smart-chain and all of my token contracts are valid contracts on coinhecko
the logos and the prices not fetch from coingecko only try to fetch main coin
what is the problem

### Environment

* Deployment type (Manual/Docker/Docker-compose):
* Elixir & Erlang/OTP versions (`elixir -version`):
* Node JS version (`node -v`):
* Operating System:
* Blockscout Version/branch/commit:
* Archive node type && version (Erigon/Geth/Nethermind/Ganache/?):

### Steps to reproduce

*Tell us how to reproduce this issue.  ❤️ if you can push up a branch to your fork with a regression test we can run to reproduce locally.*

### Expected behaviour

*Tell us what should happen.*

### Actual behaviour

*Tell us what happens instead.*

**Comment by vbaranov** [comment]
@polygomic are you on the latest version of Blockscout, right?

**Comment by polygomic** [comment]
yes I am on 5.1.5

**Comment by vbaranov** [comment]
Could you please give at least one contract address, for which Blockscout cannot get the price in your setup?

**Comment by polygomic** [comment]
0x55d398326f99059ff775485246999027b3197955
I put the logger in coin_gecko.ex the token fetcher not run and token fetcher method only one method run and is def format_data(supported_coins) when is_list(supported_coins) do should I set any extra env variables or other files in source checks the contracts

**Comment by vbaranov** [comment]
Until `DISABLE_EXCHANGE_RATES` env variable set to 'true', exchange rates for tokens should work from the box ( https://docs.blockscout.com/for-developers/information-and-settings/env-variables#exchange-rates-management). @polygomic if you're exactly on v5.1.5, could you please try pulling updates from master branch. There is [the fix](https://github.com/blockscout/blockscout/pull/7654) to get prices only for whitelisted contracts.

**Comment by sl1depengwyn** [comment]
Did you set `DISABLE_TOKEN_EXCHANGE_RATE` to false? It is disabled by default in order to force users to change `EXCHANGE_RATES_COINGECKO_PLATFORM_ID` and prevent getting false prices on chains that different from mainnet

**Comment by polygomic** [comment]
where the whitelisted token has been fetch from?
from database or coingecko?
is it predefined?

**Comment by sl1depengwyn** [comment]
> where the whitelisted token has been fetch from? from database or coingecko? is it predefined?

From coingecko `/coins/list` api endpoint

**Comment by polygomic** [comment]
I should set DISABLE_EXCHANGE_RATES to true or false to fetch tokens from coingecko let me know if I should set other env vars

**Comment by vbaranov** [comment]
DISABLE_EXCHANGE_RATES=false or it shouldn't be set at all.

**Comment by vbaranov** [comment]
> Until DISABLE_EXCHANGE_RATES env variable set to 'true', exchange rates for tokens should work from the box

@polygomic this is the wrong statement. You should set `DISABLE_EXCHANGE_RATES=false` in order to enable exchange rates.

**Comment by polygomic** [comment]
I do not know why never run method
@spec fetch_exchange_rates_for_token_address(String.t()) :: {:ok, [Token.t()]} | {:error, any}
  def fetch_exchange_rates_for_token_address(address_hash) do
    source_url = CoinGecko.source_url(address_hash)
    headers = CoinGecko.headers()
    fetch_exchange_rates_request(CoinGecko, source_url, headers)
  end

**Comment by sl1depengwyn** [comment]
> I do not know why never run method @SPEC fetch_exchange_rates_for_token_address(String.t()) :: {:ok, [Token.t()]} | {:error, any} def fetch_exchange_rates_for_token_address(address_hash) do source_url = CoinGecko.source_url(address_hash) headers = CoinGecko.headers() fetch_exchange_rates_request(CoinGecko, source_url, headers) end

This function should not be used for this, this should instead 

https://github.com/blockscout/blockscout/blob/81c7fed16a9102ed2f9f5b2747e66baeb8d4a92e/apps/explorer/lib/explorer/exchange_rates/source.ex#L37

**Comment by vbaranov** [comment]
@polygomic is the issue resolved?

**Comment by vbaranov** [comment]
there is no response from the author - closing the issue. Please notify us, if the issue still present.
