### ISSUE TITLE
I sent EWT to my trustwallet Energy Web Chain: <Issue Title>

### ISSUE THREAD

**Issue by joolsfeet** [blockscout/blockscout#7700]
*Describe your issue here.*

### Environment
* Elixir Version: 1.13.1
* Erlang Version: 24
* BlockScout Version: v4.1.5-beta

* User Agent: `Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36`

### Steps to reproduce

*Tell us how to reproduce this issue. If possible, push up a branch to your fork with a regression test we can run to reproduce locally.*

### Expected Behaviour

*Tell us what should happen.*

### Actual Behaviour

*Tell us what happens instead.*

**Comment by vbaranov** [comment]
Energy web chain instance is unsupported here.

**Comment by joolsfeet** [comment]
Thanks for the reply,

I sent EWT to Trustwallet, is it possible to recover?
Here is the hash: 0x170016cdb42dd806bbb32db8a779d50fa2440cf762ca25b07cded46070381291

From: Victor Baranov ***@***.***>
Date: Tuesday, June 13, 2023 at 12:23 PM
To: blockscout/blockscout ***@***.***>
Cc: julius preite ***@***.***>, Author ***@***.***>
Subject: Re: [blockscout/blockscout] I sent EWT to my trustwallet Energy Web Chain: <Issue Title> (Issue #7700)

Energy web chain instance is unsupported here.
