### ISSUE TITLE
Palm: api?module=account&action=txlist ignores startblock and endblock parameters.

### ISSUE THREAD

**Issue by opariltay** [blockscout/blockscout#7703]
There's an issue with module=account&action=txlist method which started today. 

This API method ignores startblock and endblock parameters and always returns all transactions starting from the very first block. Thus it returns thousands of transactions.

Please see example below: 
https://explorer.palm.io/api?module=account&action=txlist&address=0xf180cC516C307653A3623b91083f6548DC048A1a&startblock=11983850&endblock=11983944&sort=asc

### Expected Behaviour

It must return only the transactions between start block and end block.

**Comment by opariltay** [comment]
Update: I guess Palm Explorer API is updated with some major changes and input parameters changed without an announcement. "startblock" is now "start_block" and "endblock" is now "end_block". API runs very slowly at the moment.

**Comment by skenaja** [comment]
@opariltay Palm network instance of Blockscout was recently upgraded to a newer version which included this PR - https://github.com/blockscout/blockscout/pull/6187/files

The Blockscout team doesn't support Palm Explorer, so if you have any issues around performance, please raise a ticket via https://support.palm.io/hc/en-us/requests/new

Blockscout API is meant to be compatible with Etherscan API params (`This API is provided for developers transitioning their applications from Etherscan to BlockScout.`), so if it has stopped supporting `startblock` parameter as per [Etherscan docs](https://docs.etherscan.io/api-endpoints/accounts), it feels like there was a regression bug introduced by #6187 - @vbaranov can you confirm?

**Comment by opariltay** [comment]
> @opariltay Palm network instance of Blockscout was recently upgraded to a newer version which was pre-announced via a banner on the Explorer. The Blockscout team doesn't support Palm Explorer, so if you have any issues around performance, please raise a ticket via https://support.palm.io/hc/en-us/requests/new
> 
> Blockscout API is meant to be compatible with Etherscan API params (`This API is provided for developers transitioning their applications from Etherscan to BlockScout.`), so if it has stopped supporting `startblock` parameter as per [Etherscan docs](https://docs.etherscan.io/api-endpoints/accounts), it feels like there was a regression bug introduced by #6187 which removed startblock as an optional param - @vbaranov can you confirm?
> 
> As far as I can tell, there's no versioning of the API endpoints, so there's always a risk of an upgrade affecting parameters.

Thanks for very detailed explanation @skenaja . I've migrated my projects as per new parameter changes.

Now API works with a better performance. Closing this issue for now. Have a great day.
