### ISSUE TITLE
Lineaster - cant login

### ISSUE THREAD

**Issue by tommek009** [blockscout/blockscout#7715]
while login attempt such message appears "Unable to create your handle
You already have a Lineaster handle" and the signup window does not let me to continue

there is an error , can this be reseted?

Transaction Hash
    0x0b79a6167a70fe89b0829f562316efb2853cd58c66b4a205e2ea25e5d585e771 

Result
    Error: execution reverted 

Status
    Confirmed
    Confirmed by 8,274 

Revert reason

    Raw:	0x08c379a000000000000000000000000000000000000000000000000000000000000000200000000000000000000000000000000000000000000000000000000000000019416c7265616479206861732061204c656e732068616e646c6500000000000000
    UTF-8:	�y� Already has a Lens handle

Block
    [915805](https://explorer.goerli.linea.build/block/915805) 

Timestamp
    a day ago | June-14-2023 06:34:14 PM +2 UTC | Confirmed within <= 12.0 seconds 

From
   [ 0x0230eF48E9C199b71f2F1867bdc377278f74d36C ](https://explorer.goerli.linea.build/address/0x0230eF48E9C199b71f2F1867bdc377278f74d36C)

Interacted With (To)
    MockProfileCreationProxy (0x407972–c6dbdf)

**Comment by vbaranov** [comment]
Please ask this question in Linea Discord, which can be found here https://goerli.linea.build.
