### ISSUE TITLE
Linea Testnet 

### ISSUE THREAD

**Issue by sektrade** [blockscout/blockscout#7720]
Llinea test ağında gerçekleştirdiğim işlemlerden 16 tanesi askıda olarak görünüyor. İşlemi iptal yada hızlandır seçeneklerini denememe rağmen askıdaki işlemler temizlenmiyor. Bu sorunu yaşayanlar nasıl çözüm buldular?

**Comment by sektrade** [comment]
Llinea test ağında gerçekleştirdiğim işlemlerden 16 tanesi askıda olarak görünüyor. İşlemi iptal yada hızlandır seçeneklerini denememe rağmen askıdaki işlemler temizlenmiyor. Bu sorunu yaşayanlar nasıl çözüm buldular?

**Comment by vbaranov** [comment]
Please ask this question in Linea Discord, which can be found here https://goerli.linea.build.
