### ISSUE TITLE
Linea Testnet: the transaction still pending lasting 24 hours

### ISSUE THREAD

**Issue by Louis0124** [blockscout/blockscout#7721]
*Describe your issue here.*

### Environment
* Elixir Version: 1.14.0
* Erlang Version: 25
* BlockScout Version: v5.1.3-beta

* User Agent: `Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36`

### Steps to reproduce
i sign a meaasge in metamask and give the highest gas fee, it last a long time. then i speed up it. it doesn't work. so i try to cancel it. in the last , i try serveral times. it still keep pending.  how to fix it? i can not execute a new transaction using this address?
![微信图片_20230616160629](https://github.com/blockscout/blockscout/assets/120041482/5fd5c076-ba86-4e1a-85c3-54be344289a4)

*Tell us how to reproduce this issue. If possible, push up a branch to your fork with a regression test we can run to reproduce locally.*

### Expected Behaviour

*Tell us what should happen.*

### Actual Behaviour

*Tell us what happens instead.*

**Comment by vbaranov** [comment]
Please ask this question in Linea Discord, which can be found here https://goerli.linea.build.

**Comment by Louis0124** [comment]
Ok, thx for your reply. i will send message in the Linea's Discord.
