### ISSUE TITLE
transaction conformation is pendig

### ISSUE THREAD

**Issue by manudot89** [blockscout/blockscout#7723]
*Describe your issue here.*
     blockscout says (Sorry, we are unable to locate this transaction hash) my transaction is pending for linea quest & pending conformation.  please help
### Environment

* Deployment type (Manual/Docker/Docker-compose):
* Elixir & Erlang/OTP versions (`elixir -version`):
* Node JS version (`node -v`):
* Operating System:
* Blockscout Version/branch/commit:
* Archive node type && version (Erigon/Geth/Nethermind/Ganache/?):

### Steps to reproduce

*Tell us how to reproduce this issue.  ❤️ if you can push up a branch to your fork with a regression test we can run to reproduce locally.*

### Expected behaviour

*Tell us what should happen.*

### Actual behaviour

*Tell us what happens instead.*

**Comment by vbaranov** [comment]
Please ask this question in Linea Discord, which can be found here https://goerli.linea.build.
