### ISSUE TITLE
Loading site after docker-compose build

### ISSUE THREAD

**Issue by Neoblock8** [blockscout/blockscout#7725]
Hi @vbaranov ,
 Built project using docker-compose, after that when running '<ip:4000>' in site it takes too much time to load the project (merely 30 mins).
 Why it is so?

**Comment by ekawibisono** [comment]
Where do you run the blockscout file from? local PC or Server (VPS,DS or etc)

**Comment by Neoblock8** [comment]
Hi @ekawibisono 
 Running in server

**Comment by ekawibisono** [comment]
Server Specifications? I build with Docker Safe and it opens smoothly in less than 30 minutes @Neoblock8
