### ISSUE TITLE
Issue in signin

### ISSUE THREAD

**Issue by Neoblock8** [blockscout/blockscout#7733]
Hi @vbaranov,
 Setting callback function in AUTH0 and in env files. After clicking sign in tab, it won't return any error.
 But signin profile doesnot appear, why?

**Comment by vbaranov** [comment]
Most likely because Redis is not configured. Double-check your env set for Account with this one https://docs.blockscout.com/for-developers/configuration-options/my-account-settings.

**Comment by vbaranov** [comment]
@Neoblock8 Make sure you have properly configured Auth0 in their dashboard (callback url, logut url).
You also should remove `ACCOUNT_AUTH0_LOGOUT_RETURN_URL` and `ACCOUNT_AUTH0_LOGOUT_URL` env vars - they are depreciated and are defined in Auth0.
Make sure, that Redis is working by selecting something from there.

**Comment by vbaranov** [comment]
Please let us know, if the issue still persist.
