### ISSUE TITLE
Andromeda: <Issue Title>

### ISSUE THREAD

**Issue by aljazirrr** [blockscout/blockscout#7755]
*Describe your issue here.*

### Environment
* Elixir Version: 1.14.0
* Erlang Version: 25
* BlockScout Version: v5.1.5-beta

* User Agent: `Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36`

### Steps to reproduce

*Tell us how to reproduce this issue. If possible, push up a branch to your fork with a regression test we can run to reproduce locally.*

### Expected Behaviour

*Tell us what should happen.*

### Actual Behaviour

*Tell us what happens instead.*
last year i buy some tokens on polaris app via public sale with the address 0x22164b6Db6beB2F34C6DAB0798AFB49a609eE02f . I was able to see the tokens on polaris app for a wile but now there are no more tokens.Is there a chance to recover the polaris tokens?

**Comment by vbaranov** [comment]
Andromeda instance is not managed by the Blockscout team. Please ask in Andromeda chain support channel.
