### ISSUE TITLE
can't upgrade to 5.2.0

### ISSUE THREAD

**Issue by ericlee42** [blockscout/blockscout#7757]
*Describe your issue here.*

### Environment

* Deployment type (Manual/Docker/Docker-compose): Docker
* Elixir & Erlang/OTP versions (`elixir -version`): 
* Node JS version (`node -v`):
* Operating System:
* Blockscout Version/branch/commit: 5.2.0
* Archive node type && version (Erigon/Geth/Nethermind/Ganache/?): geth

### Steps to reproduce

the migration error, but it works with 5.1.5

```
** (KeyError) key :database not found in: [telemetry_prefix: [:explorer, :repo], otp_app: :explorer, migration_timestamps: [type: :utc_datetime_usec], prepare: :unnamed, timeout: 60000, migration_lock: nil, pool_size: 40, ssl: true]
    (elixir 1.14.0) lib/keyword.ex:595: Keyword.fetch!/2
    (ecto_sql 3.10.1) lib/ecto/adapters/postgres.ex:179: Ecto.Adapters.Postgres.storage_up/1
    lib/release_tasks.ex:70: Explorer.ReleaseTasks.create_db_for/1
    (elixir 1.14.0) lib/enum.ex:975: Enum."-each/2-lists^foreach/1-0-"/2
    lib/release_tasks.ex:22: Explorer.ReleaseTasks.create_and_migrate/0
    nofile:1: (file)
    (stdlib 4.0.1) erl_eval.erl:748: :erl_eval.do_apply/7
```

### Expected behaviour

*Tell us what should happen.*

### Actual behaviour

*Tell us what happens instead.*

**Comment by vbaranov** [comment]
Which envs did you set related to DB?

**Comment by ericlee42** [comment]
I have `DATABASE_URL`, and it worked with 5.1.5
