### ISSUE TITLE
v5.2.0 Postgrex.Protocol (#PID<0.4101.0>) disconnected: ** (DBConnection.ConnectionError) client #PID<0.6313.0> exited

### ISSUE THREAD

**Issue by pmualaba** [blockscout/blockscout#7767]
*Describe your issue here.*

### Environment

* Deployment type (Manual/Docker/Docker-compose): kubernetes/docker
* Elixir & Erlang/OTP versions (`elixir -version`):
* Node JS version (`node -v`):
* Operating System: ubuntu
* Blockscout Version/branch/commit: 
* Archive node type && version (Erigon/Geth/Nethermind/Ganache/?): Polygon Edge (blocktime 5sec) ETHEREUM_JSONRPC_VARIANT : geth

### Steps to reproduce

*Tell us how to reproduce this issue.  ❤️ if you can push up a branch to your fork with a regression test we can run to reproduce locally.*

### Expected behaviour
Blockscout (as of v5.1.5 up to v5.2.0) docker container should not crash after boot.

*Tell us what should happen.*

### Actual behaviour

*Tell us what happens instead.*

After upgrading from 5.1.0 to 5.2.0 the blockscout Pod is exiting with exit code 1. after Postgrex.Protocol disonnecting the DBConnection. The Postgress DB is still up and running though, but it logs invalid length of startup packet. This does not happen when using previous blockscout docker image 5.1.0

![image](https://github.com/blockscout/blockscout/assets/1754718/e37afa3a-9f79-4e42-84eb-d1919e3a9c4e)

![image](https://github.com/blockscout/blockscout/assets/1754718/aaeea11a-0725-4e79-baea-01ce5156d0f1)

**Comment by vbaranov** [comment]
Closing due to lack of response from the author.
