### ISSUE TITLE
Can not receive the email if I add a address to watchlist

### ISSUE THREAD

**Issue by Jaycelv** [blockscout/blockscout#7774]
![image](https://github.com/blockscout/blockscout/assets/99306545/e427537e-724e-4328-9cf5-4abb406c754e)

![image](https://github.com/blockscout/blockscout/assets/99306545/ce91951f-c1e3-4029-b5ca-b85c9387bb88)

I add my address to watchlist, then I send some tokens to another address, the debug log shows that send email successfully, but I didn't receive the email

**Comment by sl1depengwyn** [comment]
You still got no email? Blockscout received _accepted_ from sendgrid, so we have nothing to do here, maybe it's something with your sendgrid config?

**Comment by Nixinh12** [comment]
> Bạn vẫn không có email? Blockscout đã _được chấp nhận_ từ sendgrid, vì vậy chúng tôi không có gì để làm ở đây, có thể đó là điều gì đó với cấu hình sendgrid của bạn?

nguyenduyentini1993@gmail.com

**Comment by vbaranov** [comment]
Closing due to no answer from the author.
