### ISSUE TITLE
No fully-reliable way to determine language of a given contract's source code (in API)

### ISSUE THREAD

**Issue by haltman-at** [blockscout/blockscout#7775]
Hi, it's me again, with more issues that pose problems for the Blockscout/Truffle integration I've been trying to write!

Now, this one isn't a show-stopper like #7648 or #7768 that I just filed.  But it's an annoyance, and it's *possible* that it's worse than I think, so @gnidan thought I ought to file an issue about it.

The problem is this: There's no way to fully reliably determine the language of a given contract's source code.  (Barring, of course, attempting to parse or compile said code, which is not exactly practical!  Although I suppose that raises the specter of polyglots... anyway, nobody's going to take that approach, I'm certainly not, so it's not relevant.)

(Note: I'm talking specifically about the API here, not the web interface.)

Currently, the logic that I've figured out for this is as follows.  If the ABI is reported as `"null"`, it's Yul -- that part is simple, and, as as far as I'm aware, reliable (although see below).  But to distinguish Solidity from Vyper, as best I can tell, the only thing we have to go on is the contract name; Vyper contracts will have a contract name of `"Vyper_contract"`.  This is obviously not fully reliable since there is nothing stopping someone from writing a Solidity contract by that name!  (Obviously file extensions are in no way reliable either.)

Now I think it's reasonable to guess that if a contract is named `"Vyper_contract"`, it's probably not Solidity... but it would be nice to have something that is actually fully reliable.  Like a simple `Language` field or something, that could be `"Solidity"` or `"Yul"` or `"Vyper"`.

We might contrast with how Etherscan handles the same problem.  In Etherscan, Solidity may be reliably distinguished from Vyper by the `CompilerVersion` field; Vyper contracts will have `"vyper:"` prepended to the compiler version.  In Blockscout, no such distinction is made; like I said, the best we have to go on is the contract name.

One thing I've skipped over here is that Blockscout actually offers mixed-Solidity-and-Yul verifications, which *would* pose problems for determining a single language, since in that case one might need a different language for each source; but in fact as best I can tell this is not a real problem.  Solidity and Yul can't actually be compiled together (I still don't understand what the point of mixed verifications is supposed to be), and if you verify a contract this way, as best I can tell the source code that Blockscout reports will be whichever one was relevant, i.e., it will all have a single language.  So we may ignore this potential stumbling block.

(If that weren't the case, what a nightmare this would be -- how would we assign languages to individual sources, when the only way to distinguish Solidity from Yul is looking at whether `Abi` is null or not, something which applies only to the primary source?  We can't go by file extensions!  After all, maybe the verification was actually done using the standard JSON format, in which case filenames could be absolutely arbitrary.)

By the way -- above I asserted that we can at least reliably distinguish Solidity from Yul by the `Abi` field.  @gnidan has suggested one way in which this might not be true, although I have not fully tested this.  He suggested attempting to trip up Blockscout by using standard JSON input, with an `outputSelection` that excludes the ABI -- could we thus get a Solidity contract with a reported ABI of `"null"`, appearing to be Yul?  Well, using the web interface, no we can't; it will ignore our attempt to sabotage the `outputSelection` and use its own instead.  But could this be done using the API directly...?  I haven't tried this due to how inconvenient it is, but something you might want to think about!

(Another thing you might want to be sure if is that it's not possible to verify standard JSON that uses the `"SolidityAST"` language instead of Solidity or Yul, since that would obviously cause all number of issues, including, of course, throwing a wrench in reporting what language was used (although that's obviously the least of your worries there).  As best I can tell this isn't possible with the web interface, or, at least, I wasn't able to make it work.  But could I have made it work with the API directly?  I hope not...)

Anyway, yeah.  I *expect* that checking `Abi` and `ContractName` will give us the right answer in almost all cases, so this isn't a show-stopper like #7648 or #7768; but it would be nice to be 100% certain.

Thank you!

**Comment by sl1depengwyn** [comment]
I guess I didn't understand you, but isn't this the way to do it?
![image](https://github.com/blockscout/blockscout/assets/53992153/867db41f-1f12-4cad-a636-cd3d13539170)

**Comment by haltman-at** [comment]
Ah, sorry, that's the web interface.  I'll update the issue to be more explicit that I'm talking specifically about the API.  I'm not intending to write a web scraper here!

**Comment by sl1depengwyn** [comment]
> Ah, sorry, that's the web interface. I'll update the issue to be more explicit that I'm talking specifically about the API. I'm not intending to write a web scraper here!

Ah, got it! What do you use to get smart contract via API?

**Comment by haltman-at** [comment]
I use the method documented [here](https://docs.blockscout.com/for-users/api/rpc-endpoints/contract#get-contract-source-code-for-a-verified-contract).  I don't use the GraphQL API because it's lacking a lot of information (see #5747).  As you can see, I've filed a number of issues about both of these interfaces. :)  (Well, a lot of issues about this one, and one issue about the GraphQL one...)

Thanks!

**Comment by sl1depengwyn** [comment]
You can try `api/v2/smart-contracts/<address_hash>` there you should see `language` field. APIv2 is still in development so there are no up to date documentation, but you can try your luck [here](https://github.com/blockscout/blockscout-api-v2-swagger)

**Comment by haltman-at** [comment]
Oh, interesting.  I'll check it out later, thanks!  Not really the solution I was hoping for, as going based on that would mean having to deal with *two* APIs for Blockscout (not every instance will support the new API, surely), but it may be workable regardless.  Would still be nice to modify the existing API to handle this if possible.

Yes I haven't really relied on documentation for figuring out any of this, whether with Blockscout, Etherscan, or Sourcify. :)  Nobody bothers to document these things well, it seems, which really isn't too surprising.  Just have to rely on experiment and make sure you hit those exotic cases! :)

**Comment by rimrakhimov** [comment]
> By the way -- above I asserted that we can at least reliably distinguish Solidity from Yul by the Abi field. @gnidan has suggested one way in which this might not be true, although I have not fully tested this. He suggested attempting to trip up Blockscout by using standard JSON input, with an outputSelection that excludes the ABI -- could we thus get a Solidity contract with a reported ABI of "null", appearing to be Yul? Well, using the web interface, no we can't; it will ignore our attempt to sabotage the outputSelection and use its own instead. But could this be done using the API directly...? I haven't tried this due to how inconvenient it is, but something you might want to think about!

That would not work, as the verification service rewrites `outputSelection` field to contain only what is required for it to verify the contract. So, we do not use the user-provided `outputSelection` in our verification process

**Comment by haltman-at** [comment]
Oh, that's a relief!

**Comment by rimrakhimov** [comment]
Regarding the SolidityAST, I believe I need some time to research that more, because I've never heard about such an option before👀

**Comment by haltman-at** [comment]
Well, it's quite new, it was only introduced in Solidity 0.8.20!  But it's documented along with [all the other input options](https://docs.soliditylang.org/en/v0.8.20/using-the-compiler.html#input-description).  I think you can see that allowing it wouldn't really make sense...

Interestingly I managed to verify [a contract](https://goerli.etherscan.io/address/0x94469B10e465B18C262Cdb43cC82B59D651652d0) this way on Etherscan... I assume that's an oversight on their part!  (Like, they don't seem to allow Yul standard JSON, best I can tell.)  I sent them an email, hopefully they close that hole soon.  (Maybe they already have, not like I've rechecked, but if so they haven't deleted the verification on that contract. :P )  Sourcify's standard-JSON-input rejects it; their code checks that you specified the language as "Solidity" and doesn't allow anything else.

**Comment by haltman-at** [comment]
OK, this v2 API seems pretty nice!  At least on a first check; I'll have to do more testing to make sure it doesn't have any holes of its own.  But (where it's enabled) it will handle the language problem, at least!  Thanks!

**Comment by haltman-at** [comment]
Hm, so this problem is actually worse now what with the fix to #7768, because now Vyper contracts no longer even necessarily have that particular name!  (Likely also the case with JSON Vyper, but I still haven't tested out that case.)

**Comment by sl1depengwyn** [comment]
@haltman-at So, are you able to determine contract language now?

**Comment by haltman-at** [comment]
Oh, apologies, Truffle is no longer being worked on so I naturally stopped work on the integration.  I haven't checked on the matter recently.  Certainly it's possible with the v2 API; whether that's good enough, whether I would have been satisfied with that if I were still working on this, is a question I can't really answer anymore!

**Comment by sl1depengwyn** [comment]
Thank you for the feedback, then I'm closing this for now, feel free to reopen if you will find an answer for this question :)
