### ISSUE TITLE
Errro in Polygon-edge

### ISSUE THREAD

**Issue by plgchainteam** [blockscout/blockscout#7777]
I got this errors:
blockscout               | 2023-06-23T12:56:17.668 application=ethereum_jsonrpc fetcher=internal_transaction count=10 [error] 413 Request Entity Too Large returned from single request batch.  Cannot shrink batch further.
blockscout               | 2023-06-23T12:56:17.668 application=indexer fetcher=internal_transaction count=10 error_count=10 [error] failed to fetch internal transactions for blocks: ** (ErlangError) Erlang error: :timeout

rpc url works fine and randomly fetch block and most of times I got this error
and I use docker version

### Environment

* Deployment type (Manual/Docker/Docker-compose):
* Elixir & Erlang/OTP versions (`elixir -version`):
* Node JS version (`node -v`):
* Operating System:
* Blockscout Version/branch/commit:
* Archive node type && version (Erigon/Geth/Nethermind/Ganache/?):

### Steps to reproduce

*Tell us how to reproduce this issue.  ❤️ if you can push up a branch to your fork with a regression test we can run to reproduce locally.*

### Expected behaviour

*Tell us what should happen.*

### Actual behaviour

*Tell us what happens instead.*

**Comment by sl1depengwyn** [comment]
You can try to increase `ETHEREUM_JSONRPC_DEBUG_TRACE_TRANSACTION_TIMEOUT` env or you can disable internal transactions fetching if you do not need it via `INDEXER_DISABLE_INTERNAL_TRANSACTIONS_FETCHER`
