### ISSUE TITLE
Probleme pour transferer des POA du Meta Mask

### ISSUE THREAD

**Issue by adribrd** [blockscout/blockscout#7779]
*Describe your issue here.*

### Environment
* Elixir Version: 1.14.0
* Erlang Version: 25
* BlockScout Version: v5.2.0-beta.+commit.548fd774

* User Agent: `Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36`

### Steps to reproduce

*Tell us how to reproduce this issue. If possible, push up a branch to your fork with a regression test we can run to reproduce locally.*

### Expected Behaviour

*Tell us what should happen.*

### Actual Behaviour

*Tell us what happens instead.*

**Comment by adribrd** [comment]
![Capture d'écran 2023-06-23 163935](https://github.com/blockscout/blockscout/assets/130541915/b77f93db-84c5-4cdd-8bd4-a339f4d241be)

**Comment by sl1depengwyn** [comment]
This node is not supported anymore, POA Network merged with the Gnosis Chain. More information [here](https://www.poa.network/).
