### ISSUE TITLE
Connection lost alert

### ISSUE THREAD

**Issue by ZebroTech** [blockscout/blockscout#7786]
![image](https://github.com/blockscout/blockscout/assets/32578764/4fb1f13a-431b-4cda-baa1-5f62b4a956ea)
Connection lost alert is always there even though explorer is connected to node, blocks are up to date and latest block printed.

**Comment by vbaranov** [comment]
Please migrate to the new Blockscout UI in order to resolve this issue https://docs.blockscout.com/for-developers/deployment/frontend-migration.
