### ISSUE TITLE
Linea Testnet: <Issue Title>transaction pending

### ISSUE THREAD

**Issue by Mahim6295** [blockscout/blockscout#7787]
*Describe your issue here.*

### Environment
* Elixir Version: 1.14.0
* Erlang Version: 25
* BlockScout Version: v5.1.3-beta

* User Agent: `Mozilla/5.0 (Linux; Android 13; RMX3031) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/112.0.0.0 Mobile Safari/537.36`

### Steps to reproduce

*Tell us how to reproduce this issue. If possible, push up a branch to your fork with a regression test we can run to reproduce locally.*

### Expected Behaviour

*Tell us what should happen.*

### Actual Behaviour
0x832a91769455e89e98567abe3083500c759faf6aacb86efc98494f38da1050ff
*Tell us what happens instead.*

**Comment by sl1depengwyn** [comment]
Please ask this question in Linea Discord, which can be found here https://goerli.linea.build/.
