### ISSUE TITLE
Linea Testnet: <Issue Title> My Usdt transaction on pool didn't get approved but I was debited. 0x2650fB7a319e578574a032644Cc6912269E01A71

### ISSUE THREAD

**Issue by Dikatimothy** [blockscout/blockscout#7788]
*Describe your issue here.*

### Environment
* Elixir Version: 1.14.0
* Erlang Version: 25
* BlockScout Version: v5.1.3-beta

* User Agent: `Mozilla/5.0 (Linux; Android 10; Infinix X657C) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Mobile Safari/537.36`

### Steps to reproduce

*Tell us how to reproduce this issue. If possible, push up a branch to your fork with a regression test we can run to reproduce locally.*

### Expected Behaviour

*Tell us what should happen.*

### Actual Behaviour

*Tell us what happens instead.*

**Comment by sl1depengwyn** [comment]
Please ask this question in Linea Discord, which can be found here https://goerli.linea.build/.
