### ISSUE TITLE
Beacon Testnet: I did tx for staking on beacon layer but my tx are not showing 

### ISSUE THREAD

**Issue by Legendone91** [blockscout/blockscout#7790]
*hello
I did fewer tx for tx on beacon layer staking. tx Ids are as fol

0x44b24893e9b287ab627704836c9dcfb49f610bf225f50d52f510988be5ca9935
0xba6ea0bf6740613563b85dc008632aaff3ca75fdda711a7fd4bd77ddc8269cfe
0x04636ee5bdfe4df3137a1afa1d71dd49aeb65485a7e0273a2f791c8e4b30d910
0xc053c71a916f5eca4dca46aaf46389a68a7df82dca40030cdd9149ba98ecf643
and my token staked successfully and showing in wallet but these tx are not traceable in block explorer and no tx is showing against my wallet 0xDA2fdC816AFf4D8B9CE7A28b403809FB53B32F0e.
due to this reason my Galxe tasks are incomplete for Beacon and Rollup staking whereas both dashboards showing staked amount. 
Can you help me in solving the issue pl
Thanks and Regards
Imran Yasin
legendone91@gmail.com

**Comment by vbaranov** [comment]
This chat is for Blockscout related questions. Your question is out of scope, where Blockscout tem can help.
