### ISSUE TITLE
Research feature toggles for backend

### ISSUE THREAD

**Issue by ulyanas** [blockscout/blockscout#7798]
- Introduce feature toggles for backend to ensure that back and front are compatible

**Comment by nikitosing** [comment]
I think we can use headers as feature toggle like we did here: https://github.com/blockscout/blockscout/pull/9044/files#diff-f57bb39a73db7afcbb9da3d1c819eb96ffcd802ce9a6d7f1fbba2f7f9f783b26R159-R171
