### ISSUE TITLE
haw can i get csv reCptcha its dont work: <Issue Title>

### ISSUE THREAD

**Issue by Yananautonomo** [blockscout/blockscout#7809]
*Describe your issue here.*

### Environment
* Elixir Version: 1.13.1
* Erlang Version: 24
* BlockScout Version: 

* User Agent: `Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) aves-wallet/1.0.10 Chrome/98.0.4758.102 Electron/17.1.0 Safari/537.36`

### Steps to reproduce

*Tell us how to reproduce this issue. If possible, push up a branch to your fork with a regression test we can run to reproduce locally.*

### Expected Behaviour

*Tell us what should happen.*

### Actual Behaviour

*Tell us what happens instead.*

**Comment by vbaranov** [comment]
ENV variables for CSV export configuration: https://docs.blockscout.com/for-developers/information-and-settings/env-variables#csv-export
