### ISSUE TITLE
Fuse: Unable to Verify with foundry

### ISSUE THREAD

**Issue by rupansh** [blockscout/blockscout#7810]
*Describe your issue here.*

### Environment
* Elixir Version: 1.14.0
* Erlang Version: 25
* BlockScout Version: 5.1.5

* User Agent: `Mozilla/5.0 (X11; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/114.0`

### Steps to reproduce

I've deployed a simple counter to address `0x447373A0bC0EbeAAAF25D3ea742F95680C181f60`
https://paste.gg/p/anonymous/52f1bddf57a1448fbe701c799f1f08da

Run verification using [foundry](https://github.com/foundry-rs/foundry):
`forge verify-contract 0x447373A0bC0EbeAAAF25D3ea742F95680C181f60 src/Counter.sol:Counter --verifier blockscout --verifier-url https://explorer.fusespark.io/api --api-key <my api key> --compiler-version 0.8.19`

Changing the `--verifier` to `etherscan` doesn't help either

### Expected Behaviour

Contract verification should be succesful

### Actual Behaviour

`- Received error response: status=0,message=Something went wrong., result=None`

**Comment by sl1depengwyn** [comment]
How did you deployed this contract? It seems that compiler runtime bytecode is different from onchain bytecode and that's probably the reason of the error

**Comment by rupansh** [comment]
ah seems like i used a different solc version to deploy it

**Comment by MarcusWentz** [comment]
What happens if you don't put the Solidity compiler version?
I am getting this same error with
```shell
forge create --rpc-url https://rpc.test.taiko.xyz --verify --verifier blockscout --verifier-url https://explorer.test.taiko.xyz/api --private-key $devTestnetPrivateKey "src/Contract.sol:SimpleStorage"
```

**Comment by MarcusWentz** [comment]
I added the compiler version flag 
```
forge create --rpc-url https://rpc.test.taiko.xyz --verify --verifier blockscout --verifier-url https://explorer.test.taiko.xyz/api --private-key $devTestnetPrivateKey "src/Contract.sol:SimpleStorage" --compiler-version 0.8.7
error: unexpected argument '--compiler-version' found
```
but the flag is not recognized 
```
error: unexpected argument '--compiler-version' found
```
