### ISSUE TITLE
Linea Testnet: <Issue Title>

### ISSUE THREAD

**Issue by feretoreto** [blockscout/blockscout#7813]
Hi. i have a transaction locking my metamask account

Please could yours help me and cell it?

https://explorer.goerli.linea.build/tx/0x9ba47c5bf503955d7c8176ae95a17f1fee8f750adf068d8f0f75ad796a6b9fcf

kind regards

**Comment by vbaranov** [comment]
Please ask this question in Linea Discord, which can be found here https://goerli.linea.build.
