### ISSUE TITLE
Kava 10: Cannot Verify Simple Token Contract

### ISSUE THREAD

**Issue by PinjamLabs** [blockscout/blockscout#7814]
*Describe your issue here.*

I have been trying to verify my token contract for the past couple of weeks, but it keeps reporting invalid compiler version.

The compiler version is hardcoded as 0.7.6 so there should be no mistake there

Contract Address:
https://explorer.kava.io/address/0xE5274E38E91b615D8822e8512a29A16FF1B9C4Af/contracts

### Environment
* Elixir Version: 1.12.3
* Erlang Version: 24
* BlockScout Version: 

* User Agent: `Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36 Edg/114.0.1823.58`

### Steps to reproduce
Upload flatten source code to verify page.

The contract was flattened using npx hardhat flatter command
*Tell us how to reproduce this issue. If possible, push up a branch to your fork with a regression test we can run to reproduce locally.*

### Expected Behaviour
*Tell us what should happen.*

The contract should get verified

### Actual Behaviour
*Tell us what happens instead.*

Reports invalid compiler version.

**Comment by sl1depengwyn** [comment]
Could you please share contract source code?

**Comment by PinjamLabs** [comment]
hey @sl1depengwyn, thanks for the response.

You can find it here: https://github.com/PinjamLabs/pinjam-core/blob/main/contracts/PinkavToken.sol

**Comment by sl1depengwyn** [comment]
> hey @sl1depengwyn, thanks for the response.
> 
> You can find it here: https://github.com/PinjamLabs/pinjam-core/blob/main/contracts/PinkavToken.sol

How many optimizations did you specify while compiling your contract?

**Comment by PinjamLabs** [comment]
optimized 200 runs

**Comment by sl1depengwyn** [comment]
> optimized 200 runs

I was able to verify your contract on the testnet https://explorer.testnet.kava.io/address/0x87645aC7E038Fe54480542354BD55c8Eb36c3E55/contracts and as you can see bytecodes are different from address that you sent https://explorer.kava.io/address/0xE5274E38E91b615D8822e8512a29A16FF1B9C4Af/contracts
Recheck what you have deployed there

**Comment by sl1depengwyn** [comment]
Which blockscout version is used by https://explorer.kava.io/? Also, is Smart-contract Verifier microservice used on any of these instances?

**Comment by PinjamLabs** [comment]
Not something we know, we're not the ones hosting it. Simply trying to verify our contracts.

**Comment by sl1depengwyn** [comment]
It seems to me that versions are not the same, we're also not the ones hosting it, so I would recommend you to contact kava team directly https://www.kava.io/community
