### ISSUE TITLE
Linea Testnet: <Issue Title>

### ISSUE THREAD

**Issue by samsam48w** [blockscout/blockscout#7817]
hello guys i have transaction still pending since 3 days and i cant remove it or cancel or do any new transaction 

https://explorer.goerli.linea.build/tx/0x22f9c8689976c06508dd5d88605cc1abdcb03de7f4f0fdcc797da74f5e4f5bad
https://explorer.goerli.linea.build/tx/0xcf8e04c10bd726d9e50d416a5266d6a7117a7789b8d84f57e6d6fc2fafa0963d

can you help me guys 
best regards .

### Environment
* Elixir Version: 1.14.0
* Erlang Version: 25
* BlockScout Version: v5.1.3-beta

* User Agent: `Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36`

### Steps to reproduce

*Tell us how to reproduce this issue. If possible, push up a branch to your fork with a regression test we can run to reproduce locally.*

### Expected Behaviour

*Tell us what should happen.*

### Actual Behaviour

*Tell us what happens instead.*

**Comment by sl1depengwyn** [comment]
Please ask this question in Linea Discord, which can be found here https://goerli.linea.build/.

**Comment by samsam48w** [comment]
it is issue 
not a question

**Comment by sl1depengwyn** [comment]
> it is issue not a question

It's unrelated to Blockscout as chain explorer, pending transactions and inability to remove them is a chain issue
