### ISSUE TITLE
Zero transactions counters for `/addresses`

### ISSUE THREAD

**Issue by nikitosing** [blockscout/blockscout#7822]
https://eth-goerli.blockscout.com/accounts

![Image](https://user-images.githubusercontent.com/32202610/250056011-33b321fe-882f-4c71-a47c-bc00e3a0c9a6.png)

**Comment by vbaranov** [comment]
![Screenshot 2024-01-17 at 00 41 58](https://github.com/blockscout/blockscout/assets/4341812/786ced1b-0fc2-4159-b71b-6c3a69057d50)

I would close this

**Comment by nikitosing** [comment]
@vbaranov actually it still shows 0s for some addresses which have transactions
![image](https://github.com/blockscout/blockscout/assets/32202610/4883bb0f-17c3-41db-920d-c9a2d76080bb)

**Comment by vbaranov** [comment]
Yes, but this means no one opened those addresses.

**Comment by nikitosing** [comment]
if it is ok behavior. Then let's close
