### ISSUE TITLE
Lightlink Pegasus Testnet: <Issue Title>

### ISSUE THREAD

**Issue by rafcrypto8** [blockscout/blockscout#7830]
*Describe your issue here.*
404 error from Pegasus testnet to Goerli. Ok if from Goerli to Pegasus.
![Iightlink404_7 1 23](https://github.com/blockscout/blockscout/assets/138296972/24779183-ec97-4978-8480-05513f7e32bd)

https://pegasus.lightlink.io/tx/0x70081357d24bb0179480dce201db14a9fda5e2054b79839ba079fb7aca6996b6
### Environment

* Backend Version/branch/commit: v5.2.0-beta
* Frontend Version+commit: 45ed806d
* User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36

### Steps to reproduce

*Tell us how to reproduce this issue.  ❤️ if you can push up a branch to your fork with a regression test we can run to reproduce locally.*

### Expected behaviour

*Tell us what should happen.*

### Actual behaviour

*Tell us what happens instead.*

**Comment by vbaranov** [comment]
tx details are currently displayed
