### ISSUE TITLE
Gettext not working in api router

### ISSUE THREAD

**Issue by dennisloh95** [blockscout/blockscout#7834]
I wrote a custom plugin to support Gettext language switching by cookie:

--- **code start** ---
```elixir
defmodule BlockScoutWeb.Plug.SetLocale do
  import Plug.Conn # 1

  @supported_locales Gettext.known_locales(BlockScoutWeb.Gettext) # 2

  def init(_options), do: nil # 3

  @spec call(atom | %{:params => nil | maybe_improper_list | map, optional(any) => any}, any) ::
          atom | %{:params => nil | maybe_improper_list | map, optional(any) => any}
  def call(%Plug.Conn{params: %{"locale" => locale}} = conn, _options) when locale in @supported_locales do
    BlockScoutWeb.Gettext |> Gettext.put_locale(locale)
    conn |> put_resp_cookie "locale", locale, max_age: 365*24*60*60, http_only: false
  end

  def call(conn, _options) do
    case fetch_locale_from(conn) do
      nil -> conn
      locale ->
        BlockScoutWeb.Gettext |> Gettext.put_locale(locale)
        conn |> put_resp_cookie "locale", locale, max_age: 365*24*60*60, http_only: false
    end
  end

  defp fetch_locale_from(conn) do
    (conn.params["locale"] || conn.cookies["locale"]) |>
    check_locale
  end

  defp check_locale(locale) when locale in @supported_locales, do: locale

  defp check_locale(_), do: nil

end
```
--- **code end** ---

I include this plugin into admin_router, router, web_router:

```elixir
  pipeline :browser do
    plug(:accepts, ["html"])
    plug(:fetch_session)
    plug(:fetch_flash)
    plug(:protect_from_forgery)
    plug(BlockScoutWeb.CSPHeader)
    plug(BlockScoutWeb.ChecksumAddress)
    plug(BlockScoutWeb.Plug.SetLocale)
  end
```

i18n is working on certain view, but when I use gettext on etherscan.ex, for api docs, is not working, how to make it work on api docs?

**Comment by sl1depengwyn** [comment]
Sorry I didn't understand you the first time, have you done `mix gettext.extract --merge` in `blockscout/apps/block_scout_web/` folder after adding gettext call?

**Comment by dennisloh95** [comment]
> 

Yes I did, in my zh/default.po,
#: lib/block_scout_web/etherscan.ex:1226
#, elixir-autogen
msgid "Mimics Ethereum JSON RPC's eth_getBalance. Returns the balance as of the provided block (defaults to latest)"
msgstr "模仿以太坊 JSON RPC 的 eth_getBalance。返回提供的区块的余额（默认为最新）"

I wondering is etherscan.ex never compile my gettext content? It only work on the default_locale that I define at 
https://github.com/blockscout/blockscout/blob/master/apps/block_scout_web/config/config.exs

for example if i change the default_locale: "zh", it will give me "zh" content on etherscan.ex, but it didn't not handle by the custom plug I wrote.

**Comment by sl1depengwyn** [comment]
> 



> > 
> 
> Yes I did, in my zh/default.po, #: lib/block_scout_web/etherscan.ex:1226 #, elixir-autogen msgid "Mimics Ethereum JSON RPC's eth_getBalance. Returns the balance as of the provided block (defaults to latest)" msgstr "模仿以太坊 JSON RPC 的 eth_getBalance。返回提供的区块的余额（默认为最新）"
> 
> I wondering is etherscan.ex never compile my gettext content? It only work on the default_locale that I define at https://github.com/blockscout/blockscout/blob/master/apps/block_scout_web/config/config.exs
> 
> for example if i change the default_locale: "zh", it will give me "zh" content on etherscan.ex, but it didn't not handle by the custom plug I wrote.

The reason is that `Mimics Ethereum JSON RPC's eth_getBalance. Returns the balance as of the provided block (defaults to latest)` is actually inside module attribute, it means that gettext called in compile time once, you need to transform module attributes to functions and function calls. Let me know if this worked

**Comment by dennisloh95** [comment]
> > 
> 
> > > 
> > 
> > 
> > Yes I did, in my zh/default.po, #: lib/block_scout_web/etherscan.ex:1226 #, elixir-autogen msgid "Mimics Ethereum JSON RPC's eth_getBalance. Returns the balance as of the provided block (defaults to latest)" msgstr "模仿以太坊 JSON RPC 的 eth_getBalance。返回提供的区块的余额（默认为最新）"
> > I wondering is etherscan.ex never compile my gettext content? It only work on the default_locale that I define at https://github.com/blockscout/blockscout/blob/master/apps/block_scout_web/config/config.exs
> > for example if i change the default_locale: "zh", it will give me "zh" content on etherscan.ex, but it didn't not handle by the custom plug I wrote.
> 
> The reason is that `Mimics Ethereum JSON RPC's eth_getBalance. Returns the balance as of the provided block (defaults to latest)` is actually inside module attribute, it means that gettext called in compile time once, you need to transform module attributes to functions and function calls. Let me know if this worked

Thanks @sl1depengwyn, it work after change to function call. One more issue I facing is on channel view.
For example in https://github.com/blockscout/blockscout/blob/master/apps/block_scout_web/lib/block_scout_web/templates/block/_tile.html.eex

gettext work on initial load, however when there is new block pushing in, it is default language, could it be any configuration needed on the socket?

**Comment by sl1depengwyn** [comment]
> channel

Try to change this file https://github.com/blockscout/blockscout/blob/master/apps/block_scout_web/assets/js/locale.js in the following way:
```js
import moment from 'moment'
import numeral from 'numeral'
import 'numeral/locales'
import { Path } from 'path-parser'
import Cookies from 'js-cookie'

export const { locale } = Path.createPath('?locale').partialTest(window.location.search) || { locale: Cookies.get('locale') } || { locale: 'en' }

moment.locale(locale)
numeral.locale(locale)

```

**Comment by dennisloh95** [comment]
> https://github.com/blockscout/blockscout/blob/master/apps/block_scout_web/lib/block_scout_web/templates/block/_tile.html.eex

Tried but not working, don't think it's related to js? cause is on gettext string, for example line 41  <%= gettext "Miner" %>
and line 73 <%= gettext "Gas Used" %>
https://github.com/blockscout/blockscout/blob/master/apps/block_scout_web/lib/block_scout_web/templates/block/_tile.html.eex

Is working for initial load block, but once there is new block coming in, it become default lang

![Screenshot 2023-07-07 at 10 56 10 AM](https://github.com/blockscout/blockscout/assets/34902315/3e4125a8-d6d0-4fc8-a9d7-99a6b80ba125)

**Comment by sl1depengwyn** [comment]
> > https://github.com/blockscout/blockscout/blob/master/apps/block_scout_web/lib/block_scout_web/templates/block/_tile.html.eex
> 
> Tried but not working, don't think it's related to js? cause is on gettext string, for example line 41 <%= gettext "Miner" %> and line 73 <%= gettext "Gas Used" %> https://github.com/blockscout/blockscout/blob/master/apps/block_scout_web/lib/block_scout_web/templates/block/_tile.html.eex
> 
> Is working for initial load block, but once there is new block coming in, it become default lang
> 
> ![Screenshot 2023-07-07 at 10 56 10 AM](https://user-images.githubusercontent.com/34902315/251623779-3e4125a8-d6d0-4fc8-a9d7-99a6b80ba125.png)

Didn't you forget to run `mix phx.digest`?
