### ISSUE TITLE
Sahara Mainnet: <Issue Title>

### ISSUE THREAD

**Issue by koollich** [blockscout/blockscout#7835]
*Describe your issue here.*

### Environment
* Elixir Version: 1.13.4
* Erlang Version: 24
* BlockScout Version: 1.0

* User Agent: `Mozilla/5.0 (Linux; Android 11; M2006C3LG Build/RP1A.200720.011; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/114.0.5735.131 Mobile Safari/537.36`

### Steps to reproduce

*Tell us how to reproduce this issue. If possible, push up a branch to your fork with a regression test we can run to reproduce locally.*

### Expected Behaviour

*Tell us what should happen.*

### Actual Behaviour

*Tell us what happens instead.*

**Comment by sl1depengwyn** [comment]
Try to ask your question here https://t.me/fasttoken_eng
