### ISSUE TITLE
[error] failed to fetch internal transactions for blocks : ErlangError : "URL is nil"

### ISSUE THREAD

**Issue by J-Chan96** [blockscout/blockscout#7858]
*Describe your issue here.*

When I run mix phx.server, the following phrase error pops up a lot. How should I solve it?

2023-07-06T16:56:48.472 application=indexer fetcher=internal_transaction count=10 error_count=10 [error] failed to fetch internal transactions for blocks: ** (ErlangError) Erlang error: "URL is nil"

### Environment

* Deployment type (Manual/Docker/Docker-compose):
* Elixir & Erlang/OTP versions (`elixir -version`):  
Erlang/OTP 25 [erts-13.2.2.1] [source] [64-bit] [smp:10:10] [ds:10:10:10] [async-threads:1] [jit] [dtrace]
Elixir 1.14.5 (compiled with Erlang/OTP 25)

* Node JS version (`node -v`): v16.20.0
* Archive node type && version (Erigon/Geth/Nethermind/Ganache/?): Geth

The environment variables in /etc/profile:

```
export ETHEREUM_JSONRPC_VARIANT=geth
export ETHEREUM_JSONRPC_HTTP_URL=https://rpc.lvscan.io
export DATABASE_URL=postgresql://libervance:@localhost:5432/blockscout
export COIN=ETH
export MIX_ENV=prod
export PORT=4001
```

**Comment by vbaranov** [comment]
@J-Chan96 it is required to set `ETHEREUM_JSONRPC_TRACE_URL` in order to fetch internal transactions.

**Comment by J-Chan96** [comment]
@vbaranov  
Thanks! I solved it!

**Comment by Edison4mobile** [comment]
> @J-Chan96 it is required to set `ETHEREUM_JSONRPC_TRACE_URL` in order to fetch internal transactions.

Perfect !!!!!!!!!!!!!!!!
