### ISSUE TITLE
Inconsistent tokens for address in new chiado env

### ISSUE THREAD

**Issue by 0xtzData** [blockscout/blockscout#7864]
https://gnosis-chiado.blockscout.com/address/0x19C653Da7c37c66208fbfbE8908A5051B57b4C70 - new API/env
https://blockscout.chiadochain.net/address/0x19C653Da7c37c66208fbfbE8908A5051B57b4C70 - old API/env

There is one token showing up in the old API, in the new env API returns no tokens for ERC-20/721/1155 for the same addrerss.
If we check it through contract API we can see this contract have 3 GNO tokens.

![Image](https://github.com/blockscout/blockscout/assets/108135703/8cccb792-317c-4ac8-953d-b43a44730388)

**Comment by vbaranov** [comment]
@0xtzData the 2nd Chiado explorer instance is now redirecting to the main Blockscout. The issue cannot be reproduced.
