### ISSUE TITLE
The block height and transaction hash in Coin balance history do not match the change in balance

### ISSUE THREAD

**Issue by Jaycelv** [blockscout/blockscout#7892]
Version: v5.0.0-beta

Block height 11269850 This transaction in this block is a swap transaction, but the corresponding balance change in coin balance history is a Mint operation of mine, why is there a mismatch?

![yVuQh5MTiy](https://github.com/blockscout/blockscout/assets/99306545/8123da41-436c-47aa-b3a5-add45b5270da)
![image](https://github.com/blockscout/blockscout/assets/99306545/47b4c837-b56b-4429-aec2-316bfebfc4ce)

**Comment by vbaranov** [comment]
It is possible, if internal transactions are not fetched on the instance for some reason. I hope this has been resolved on the Mantle instance of Blocskcout. Please let us know, if the issue is still present.
