### ISSUE TITLE
Ethereum Classic: <Issue Title>

### ISSUE THREAD

**Issue by Tasha1994** [blockscout/blockscout#7897]
*Describe your issue here.*
when minting a NFT im getting code 404 when i try to view on ETC blockscout 
I also can not import my new NFT to metamask 

### Environment
* Elixir Version: 1.13.1
* Erlang Version: 24
* BlockScout Version: v4.1.8-beta

* User Agent: `Mozilla/5.0 (X11; CrOS x86_64 14541.0.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36`

### Steps to reproduce

*Tell us how to reproduce this issue. If possible, push up a branch to your fork with a regression test we can run to reproduce locally.*
you could try mint a NFT and import to a metamask account.

### Expected Behaviour

*Tell us what should happen.*
i should mint a NFT and see the address and token ID on blockscout to be able to either view the images or import the token
### Actual Behaviour

*Tell us what happens instead.*
This isnt happening im getting code 404 instead no images available to view.

**Comment by vbaranov** [comment]
Ethereum Classic Discord is https://discord.com/invite/bMGuZsA - please ask there.
