### ISSUE TITLE
NFT token transfers: "token_id" is "null" for an item

### ISSUE THREAD

**Issue by tom2drum** [blockscout/blockscout#7908]
### Example

https://eth-goerli.blockscout.com/token/0xA0E1b46e99459e45B2AC1122Bc0594A585c481e2

for one of the item in the response of token transfers `token_id` field is set to `null` that should not be for `ERC-1155` tokens

```json
{
  "block_hash": "0x61b720e40f8c521edd77a52cabce556c18b18b198f78e361f310003386ff1f02",
  "from": {
    "hash": "0x598AF04C88122FA4D1e08C5da3244C39F10D4F14",
    "implementation_name": null,
    "is_contract": false,
    "is_verified": null,
    "name": null,
    "private_tags": [],
    "public_tags": [],
    "watchlist_names": []
  },
  "log_index": "6",
  "method": "0x759631c6",
  "timestamp": "2023-05-26T03:28:36.000000Z",
  "to": {
    "hash": "0x0000000000000000000000000000000000000000",
    "implementation_name": null,
    "is_contract": false,
    "is_verified": null,
    "name": null,
    "private_tags": [],
    "public_tags": [],
    "watchlist_names": []
  },
  "token": {
    "address": "0xA0E1b46e99459e45B2AC1122Bc0594A585c481e2",
    "circulating_market_cap": null,
    "decimals": null,
    "exchange_rate": null,
    "holders": "5519",
    "icon_url": null,
    "name": "Isekai Battle Weapons",
    "symbol": "WPN",
    "total_supply": null,
    "type": "ERC-1155"
  },
  "total": {
    "decimals": null,
    "token_id": null,
    "value": null
  },
  "tx_hash": "0xa6ad6588edb4abd8ca45f30d2f026ba20b68a3002a5870dbd30cc3752568483b",
  "type": "token_burning"
}

```

**Comment by atapin** [comment]
@tom2drum this is not reproduced in API anymore, but the link gives 500 error

**Comment by tom2drum** [comment]
@atapin for [the tx in the example](https://eth-goerli.blockscout.com/tx/0xa6ad6588edb4abd8ca45f30d2f026ba20b68a3002a5870dbd30cc3752568483b) I still see that some of the token transfers doesn't have `token_id`. Getting this response over and over again.

**Comment by atapin** [comment]
@tom2drum works as expected ATM, but I was curious of the reasons of this bug and dug the codebase a little. I think, we have redundant decimals processing for ERC1155 here: https://github.com/blockscout/blockscout/blob/a019b6f9fe933cf2c5134b7b405c675473c5fea0/apps/block_scout_web/lib/block_scout_web/views/api/v2/transaction_view.ex#L228-L245

**Comment by tom2drum** [comment]
I don't know but I still see 500 error on the page because of that

<details><summary>Screenshot</summary>
<p>
<img width="1710" alt="image" src="https://github.com/blockscout/blockscout/assets/22130104/78a58f76-746f-4db8-9fd0-4be292f90c3a">

</p>
</details>

**Comment by atapin** [comment]
@tom2drum @nikitosing do you guys mind if I submit a PR for this issue? I have found the root cause

**Comment by nikitosing** [comment]
@atapin Hello, please submit your PR, we will really grateful
