### ISSUE TITLE
Andromeda: <Issue Title>

### ISSUE THREAD

**Issue by Vanya13917** [blockscout/blockscout#7914]
I made a wrong transaction, can I reverse it?

### Environment
* Elixir Version: 1.14.0
* Erlang Version: 25
* BlockScout Version: v5.2.0-beta

* User Agent: `Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36`

### Steps to reproduce

I transferred my m.USDT tokens to Binance wallet (BEP20), the system did not block the transfer and the tokens disappeared(

### Expected Behaviour

please cancel the transfer

### Actual Behaviour

I will lose money

**Comment by vbaranov** [comment]
This chat is for Blockscout explorer related questions. Your question is out of scope.
