### ISSUE TITLE
Could not start application indexer: Indexer.Application.start(:normal, []) returned an error: shutdown: failed to start child: Indexer.Memory.Monitor

### ISSUE THREAD

**Issue by rkdevstack** [blockscout/blockscout#7919]
my common-block scout.env file 
itor
    ** (EXIT) an exception was raised:
        ** (KeyError) key :limit not found in: %Indexer.Memory.Monitor{shrinkable_set: #MapSet<[]>, timer_interval: 60000, timer_reference: nil}
            (stdlib 3.17) :maps.update(:limit, 1073741824, %Indexer.Memory.Monitor{shrinkable_set: #MapSet<[]>, timer_interval: 60000, timer_reference: nil})
            (indexer 5.2.0) lib/indexer/memory/monitor.ex:17: anonymous fn/2 in Indexer.Memory.Monitor.__struct__/1
            (stdlib 3.17) maps.erl:410: :maps.fold_1/3
            (elixir 1.12.2) lib/kernel.ex:2285: Kernel.struct!/2
            (indexer 5.2.0) lib/indexer/memory/monitor.ex:45: Indexer.Memory.Monitor.init/1
            (stdlib 3.17) gen_server.erl:423: :gen_server.init_it/2
            (stdlib 3.17) gen_server.erl:390: :gen_server.init_it/6
            (stdlib 3.17) proc_lib.erl:226: :proc_lib.init_p_do_apply/3
2023-07-12T19:43:49.997 [info] Application libsecp256k1 exited: :stopped
2023-07-12T19:43:49.998 [info] Application ex_rlp exited: :stopped
2023-07-12T19:43:49.999 application=explorer [info] tx/per day chart: timestamp cannot be converted to min/max blocks, trying to find min/max blocks through a fallback option}
** (Mix) Could not start application indexer: Indexer.Application.start(:normal, []) returned an error: shutdown: failed to start child: Indexer.Memory.Monitor
    ** (EXIT) an exception was raised:
        ** (KeyError) key :limit not found in: %Indexer.Memory.Monitor{shrinkable_set: #MapSet<[]>, timer_interval: 60000, timer_reference: nil}
            (stdlib 3.17) :maps.update(:limit, 1073741824, %Indexer.Memory.Monitor{shrinkable_set: #MapSet<[]>, timer_interval: 60000, timer_reference: nil})
            (indexer 5.2.0) lib/indexer/memory/monitor.ex:17: anonymous fn/2 in Indexer.Memory.Monitor.__struct__/1
            (stdlib 3.17) maps.erl:410: :maps.fold_1/3
            (elixir 1.12.2) lib/kernel.ex:2285: Kernel.struct!/2
            (indexer 5.2.0) lib/indexer/memory/monitor.ex:45: Indexer.Memory.Monitor.init/1
            (stdlib 3.17) gen_server.erl:423: :gen_server.init_it/2
            (stdlib 3.17) gen_server.erl:390: :gen_server.init_it/6
            (stdlib 3.17) proc_lib.erl:226: :proc_lib.init_p_do_apply/3

**Comment by vbaranov** [comment]
@rkdevstack please pull updates ftom master branch - this has been fixed in https://github.com/blockscout/blockscout/pull/7918

**Comment by rkdevstack** [comment]
thanks , this is resolved and my node is running now
