### ISSUE TITLE
configure database master-slave

### ISSUE THREAD

**Issue by guoshijiang** [blockscout/blockscout#7942]
I want to configure the database master-slave. I use the DATABASE_URL configuration item for the master database, DATABASE_READ_ONLY_API_URL for the slave database, and ACCOUNT_DATABASE_URL configuration for the Account database. After I restart the service after configuration, the data corresponding to DATABASE_READ_ONLY_API_URL and ACCOUNT_DATABASE_URL has not been queried SQL, am I doing this incorrectly and what should I do?

**Comment by guoshijiang** [comment]
Who knows how to configure the master-slave database of blockscout, can you give me an answer?  Thank you!

**Comment by sl1depengwyn** [comment]
What have you done after service restart to see any queries? `DATABASE_READ_ONLY_API_URL` is used only in API calls

**Comment by guoshijiang** [comment]
> What have you done after service restart to see any queries? `DATABASE_READ_ONLY_API_URL` is used only in API calls

From the application level, blockscout how to implement the database master-slave configuration, one master and multiple slaves, can help provide a solution

**Comment by sl1depengwyn** [comment]
> > What have you done after service restart to see any queries? `DATABASE_READ_ONLY_API_URL` is used only in API calls
> 
> From the application level, blockscout how to implement the database master-slave configuration, one master and multiple slaves, can help provide a solution

You have done everything alright, with this configuration all API calls will go to the slave instance of database

**Comment by guoshijiang** [comment]
> You have done everything alright, with this configuration all API calls will go to the slave instance of database

Config as above describe, Which UI goes to the slave database, Or just the API？

**Comment by sl1depengwyn** [comment]
> > You have done everything alright, with this configuration all API calls will go to the slave instance of database
> 
> Config as above describe, Which UI goes to the slave database, Or just the API？

Only API goes to the slave db, if you are talking about new UI, it uses API, so all requests from there goes to slave database
