### ISSUE TITLE
Keeps retrying the same block 6356348. Heavy CPU load and syslog running into huge amounts of GB in size

### ISSUE THREAD

**Issue by Nexsuperne101** [blockscout/blockscout#7944]
*Describe your issue here.*

### Environment
* Elixir Version: 1.13.0
* Erlang Version: 24
* BlockScout Version:  5.2.0

* User Agent: `Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36`

### Steps to reproduce

*Tell us how to reproduce this issue. If possible, push up a branch to your fork with a regression test we can run to reproduce locally.*

### Expected Behaviour -  Stops retrying after a few attempts

*Tell us what should happen.*

### Actual Behaviour - Keeps retrying. This is the typical output.
Jul 17 06:00:53 ubuntu mix[811]: 2023-07-17T06:00:53.851 application=indexer fetcher=block_catchup first_block_number=6356321 last_block_number=6356321 step=import [error] failed to validate: [#Ecto.Changeset<action: nil, changes: %{}, errors: [hash: {"is invalid", [type: Explorer.Chain.Hash.Address, validation: :cast]}], data: #Explorer.Chain.Address<>, valid?: false>, #Ecto.Changeset<action: nil, changes: %{block_number: 6356321}, errors: [address_hash: {"is invalid", [type: Explorer.Chain.Hash.Address, validation: :cast]}], data: #Explorer.Chain.Address.CoinBalance<>, valid?: false>, #Ecto.Changeset<action: nil, changes: %{consensus: true, difficulty: Decimal.new("6356321"), gas_limit: Decimal.new("1000000000"), gas_used: Decimal.new("0"), hash: %Explorer.Chain.Hash{byte_count: 32, bytes: <<90, 170, 240, 138, 167, 10, 220, 50, 44, 44, 129, 2, 144, 79, 179, 163, 221, 78, 95, 98, 14, 120, 47, 82, 44, 141, 75, 114, 240, 8, 17, 109>>}, nonce: %Explorer.Chain.Hash{byte_count: 8, bytes: <<255, 255, 255, 255, 255, 255, 255, 255>>}, number: 6356321, parent_hash: %Explorer.Chain.Hash{byte_count: 32, bytes: <<181, 71, 236, 243, 93, 175, 143, 175, 221, 254, 13, 72, 184, 224, 14, 28, 190, 236, 178, 136, 121, 217, 6, 162, 83, 47, 211, 212, 236, 142, 2, 96>>}, size: 3695, timestamp: ~U[2023-07-13 08:49:32.000000Z], total_difficulty: Decimal.new("6356321")}, errors: [miner_hash: {"is invalid", [type: Explorer.Chain.Hash.Address, validation: :cast]}], data: #Explorer.Chain.Block<>, valid?: false>, #Ecto.Changeset<action: nil, changes: %{day: ~D[2023-07-13]}, errors: [address_hash: {"is invalid", [type: Explorer.Chain.Hash.Address, validation: :cast]}], data: #Explorer.Chain.Address.CoinBalanceDaily<>, valid?: false>, #Ecto.Changeset<action: nil, changes: %{address_type: :validator, block_hash: %Explorer.Chain.Hash{byte_count: 32, bytes: <<90, 170, 240, 138, 167, 10, 220, 50, 44, 44, 129, 2, 144, 79, 179, 163, 221, 78, 95, 98, 14, 120, 47, 82, 44, 141, 75, 114, 240, 8, 17, 109>>}, reward: #Explorer.Chain.Wei<0>}, errors: [address_hash: {"is invalid", [type: Explorer.Chain.Hash.Address, validation: :cast]}], data: #Explorer.Chain.Block.Reward<>, valid?: false>]. Retrying.

*Tell us what happens instead.* Creates a huge syslog file, which needs to be manually deleted every few hours.

**Comment by vbaranov** [comment]
@Nexsuperne101 which chain are you trying to index? What RPC client do you use?

**Comment by Nexsuperne101** [comment]
Poochain (20202021). Rpc is https://mainnet.poochain.co/rpc
