### ISSUE TITLE
C1: <Crosschain not successfull>

### ISSUE THREAD

**Issue by millatmisu3** [blockscout/blockscout#7956]
Crosschain not successfull
https://app.multichain.org/
### from usdc milikomed(cardano)  to ethereum udsc

trx id https://explorer-mainnet-cardano-evm.c1.milkomeda.com/tx/0x9c04eb9ed0829d6e3591326ce931a825421bb86428dfb766962cee11a98ebc34

wallet address.. 0x3DC32d4811b229797129A9B0931dA2e8437B272F
my coin not back ...
plz solve my problem

### Steps to reproduce

*Tell us how to reproduce this issue. If possible, push up a branch to your fork with a regression test we can run to reproduce locally.*

### Expected Behaviour

*Tell us what should happen.*

### Actual Behaviour

*Tell us what happens instead.*

**Comment by vbaranov** [comment]
You should contact milkomeda chain support. This issue tracker is only for Blockscout explorer.
