### ISSUE TITLE
Email notifications - SendGrid link tracking leads to SSL error

### ISSUE THREAD

**Issue by atapin** [blockscout/blockscout#7957]
In the Watchlist email notification, all links (except for "See more details") are tracked SendGrid links.

<details>
<summary>Screenshot</summary>

<img width="619" alt="image" src="https://github.com/blockscout/blockscout/assets/1181403/87d1f046-f638-4a13-bed6-2db9417369df">

</details>

For example, "From" field has link to `http://url1021.blockscout.com/ls/click?upn=hILKh6wwlmud8xpmlIqKmoHfZP87pbiUoYXIrqIZh-2Bk0eX0zvCRA5qADSPOajK9cdBEf6gIED6q7r03hg6yvaLjzNRBsbAi4zsixgvX0zg7Hz-2FeT11MaGO8NdKwHHh6MAJMI_1qOR9RrskwxWxaFr-2F1BL7PtWKBcyfsDMf7T5gZ1BnAmwg-2BUyevHycj3F-2FP1qM-2BF-2BRie6f-2FRr-2FeejZ4-2BF4qG8aWoL-2BOjSUmF5-2FXTrh1zJ4hpRcnqnU5AB01CvZGgeSsNzH53ChOOo8Z0t9WLHHC7SFZ33hieL3ZIxS8o5Km3JGgcVQMbIHHAC0t6SAtpehp1o6wW-2Bzwe5nbOArcLeywtVSOC0rF30wkAW2F4AlqkEMdAAmmdS4aKsKpb0JkaX6GNghOkPGwA5ob5pjuB95N6ivPnIWVLklY4KJmEO2ONcZsC7mGqOAzL3BjcsnFmJ8SH2OFv-2F4LMo5XL9pgUSvz-2Bv8A-3D-3D`

This link results in a SSL error page.

Possible solutions:
1. [Set up SSL for link tracking](https://docs.sendgrid.com/ui/analytics-and-reporting/click-tracking-ssl)
2. [Turn-off link tracking](https://docs.sendgrid.com/for-developers/sending-email/smtp-errors-and-troubleshooting#turning-off-click-tracking)

**Comment by atapin** [comment]
@0xtzData FYI

**Comment by nikitosing** [comment]
@atapin Hello, could you check please if the issue reproducible now?

**Comment by vbaranov** [comment]
This should be resolved.
