### ISSUE TITLE
MAINNET: <Issue Title>

### ISSUE THREAD

**Issue by Obedino164** [blockscout/blockscout#7966]
I want to withdraw my Bitcoin from the bomb crypto app to my Binance, but it's not going through

### Environment
* Elixir Version: 1.13.4
* Erlang Version: 24
* BlockScout Version: v4.1.3

* User Agent: `Mozilla/5.0 (Linux; Android 10; Infinix X657B) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.99 Mobile Safari/537.36`

### Steps to reproduce

*Tell us how to reproduce this issue. If possible, push up a branch to your fork with a regression test we can run to reproduce locally.*

### Expected Behaviour

*Tell us what should happen.*

### Actual Behaviour

*Tell us what happens instead.*

**Comment by sl1depengwyn** [comment]
Contact the bomb crypto app, it is unrelated to Blockscout
