### ISSUE TITLE
Linea: Bridge Not successful

### ISSUE THREAD

**Issue by Satu60** [blockscout/blockscout#7967]
I have done Bridge in Official Site of Linea

But ETH is gone 
Still I not got Linea too

I done before 2 hours
In explorer too Showing 0 transaction

**Comment by sl1depengwyn** [comment]
Please contact Linea team directly, contacts can be found [here](https://bridge.linea.build/) or [here](https://goerli.linea.build/), this issue is unrelated to blockscout.
