### ISSUE TITLE
Linea: <Issue Title>

### ISSUE THREAD

**Issue by brohems** [blockscout/blockscout#7968]
*Describe your issue here.*

sir i have bridge 0.340510257854032631 ETH from ethereum to linea https://etherscan.io/tx/0xb221eb721c4c70a844cfe9aa557272debda0d676cb040325bf003116f20df01d but still i didnt get in linea will you solve the problem

**Comment by sl1depengwyn** [comment]
Please contact Linea team directly, contacts can be found [here](https://bridge.linea.build/) or [here](https://goerli.linea.build/), this issue is unrelated to blockscout.
