### ISSUE TITLE
how to use the lastest ui

### ISSUE THREAD

**Issue by yiaimoli** [blockscout/blockscout#7969]
*Describe your issue here.*

### Environment

* Backend Version/branch/commit: v5.2.0-beta
* Frontend Version+commit: v1.6.0+cc644b71
* User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36

### Steps to reproduce

*Tell us how to reproduce this issue.  ❤️ if you can push up a branch to your fork with a regression test we can run to reproduce locally.*

### Expected behaviour

*Tell us what should happen.*

### Actual behaviour

*Tell us what happens instead.*

**Comment by sl1depengwyn** [comment]
https://github.com/orgs/blockscout/discussions/7121
