### ISSUE TITLE
Ethereum Classic: <Issue Title>

### ISSUE THREAD

**Issue by Carve22** [blockscout/blockscout#7979]
*Describe your issue here.*

### Environment
* Elixir Version: 1.13.1
* Erlang Version: 24
* BlockScout Version: v4.1.8-beta

* User Agent: `Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/113.0.0.0 Mobile Safari/537.36`

### Steps to reproduce

*Tell us how to reproduce this issue. If possible, push up a branch to your fork with a regression test we can run to reproduce locally.*

### Expected Behaviour

*Tell us what should happen.*

### Actual Behaviour

*Tell us what happens instead.*

hice un retiro ayer de yesterday I made a withdrawal of  ethereu I made a withdrawal yesterday from ethereum it says it was paid successfully but it has not reached my wallet

**Comment by vbaranov** [comment]
Regarding your question try to contact ETC team, for instance, on their Discord https://discord.com/invite/hQs894U.
