### ISSUE TITLE
Linea: pending tx how to fix it

### ISSUE THREAD

**Issue by Barelsyahmanhar** [blockscout/blockscout#7988]
*Describe your issue here.*

### Environment
* Elixir Version: 1.14.0
* Erlang Version: 25
* BlockScout Version: v5.2.0-beta

* User Agent: `Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/112.0.0.0 Safari/537.36`

### Steps to reproduce

*Tell us how to reproduce this issue. If possible, push up a branch to your fork with a regression test we can run to reproduce locally.*

### Expected Behaviour

*Tell us what should happen.*

### Actual Behaviour

*Tell us what happens instead.*
![Screenshot_20230721-051806_Mises](https://github.com/blockscout/blockscout/assets/140121405/21122740-a380-4dec-aa88-9b35bbbcd1e4)

How to fix pending tx in linea build? Via explorer because in my tx in my wallet has been delete and just shown on the explore the issue still pending around 24hours 

This my two tx id on block   
1.  0xf737fca538f229cd68bcf54a0c01b30c98cc28f6c0f73a60aff2b477b2f17036 
2. 0x3d689ee2bcb810c7699b6c5749f11512749d4616cd5bdea180b0bfaf3b30c488      on linea network

**Comment by sl1depengwyn** [comment]
Please contact Linea team directly, contacts can be found [here](https://bridge.linea.build/) or [here](https://goerli.linea.build/), this issue is unrelated to blockscout.
