### ISSUE TITLE
Base Göerli: <Issue Title>0x6202db90e38f5846c735ffaebbf9c6b7ed44c950

### ISSUE THREAD

**Issue by Ronniegrey71** [blockscout/blockscout#7989]
*Describe your issue here.*this is my account 

### Environment

* Backend Version/branch/commit: v5.2.1-beta
* Frontend Version+commit: v1.6.1+9faebc10
* User Agent: Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Mobile Safari/537.36

### Steps to reproduce

*Tell us how to reproduce this issue.  ❤️ if you can push up a branch to your fork with a regression test we can run to reproduce locally.*

### Expected behaviour

*Tell us what should happen.*

### Actual behaviour

*Tell us what happens instead.*

**Comment by Ronniegrey71** [comment]
My account  looks to be moved to another  how do I get my account back. This is my account. 0x6202db90e38f5846c735ffaebbf9c6b7ed44c950

**Comment by Ronniegrey71** [comment]
It was moved to this one.0x309d99804a18f40a4c55d328b3da9cadf496ea15

**Comment by sl1depengwyn** [comment]
This issue is unrelated to Blockscout as a chain explorer
