### ISSUE TITLE
Linea: < my transactions is stuck and pending 

### ISSUE THREAD

**Issue by Mariamarianel** [blockscout/blockscout#7993]
*Describe your issue here.*
My transactions is stuck and pending 
### Environment
* Elixir Version: 1.14.0
* Erlang Version: 25
* BlockScout Version: v5.2.0-beta

* User Agent: `Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/112.0.0.0 Safari/537.36`

### Steps to reproduce

*Tell us how to reproduce this issue. If possible, push up a branch to your fork with a regression test we can run to reproduce locally.*

### Expected Behaviour

*Tell us what should happen.*

### Actual Behaviour

*Tell us what happens instead.*

**Comment by sl1depengwyn** [comment]
Please contact Linea team directly, contacts can be found [here](https://bridge.linea.build/) or [here](https://goerli.linea.build/), this issue is unrelated to blockscout.
