### ISSUE TITLE
Some ERC-20 tokens don't appear in the balances dataset 

### ISSUE THREAD

**Issue by llunaCreixent** [blockscout/blockscout#7994]
I want to get the balance of all the Circles tokens (which are ERC-20 tokens, and also called `CRC`) held by some account. Have two data sources where to get this information:
- `gnosis.blockscout.com` api: `https://gnosis.blockscout.com/api/v2/addresses/${safeAddress}/tokens?type=ERC-20`
- the circles subgraph (hosted for example here `https://thegraph.com/hosted-service/subgraph/circlesubi/circles-ubi`)

Unfortunately, there is a discrepancy when asking both sources for the number of different Circles tokens (which are ERC-20 tokens) held by some accounts. Specifically, There's no error in the balances of the tokens, but in the number of different tokens retrieved: Some Circles tokens are missing from the blosckscout dataset.

### Environment

* Node JS version (`node -v`): 16
* Operating System: Debian
* Blockscout Version/branch/commit:
  * Backend: [v5.2.0-beta](https://github.com/blockscout/blockscout/tree/v5.2.0-beta)
  * Frontend: v1.6.0+cc644b71

### Steps to reproduce

Running the following script will retrieve the Circles tokens from both apis, and compare the results.
```
git clone https://github.com/CirclesUBI/circles-toolbelt.git
cd circles-toolbelt/helper-tools
npm i
node check-balances.js
```

### Expected behaviour

I expect retrieving same number of Circles tokens from both datasets.

### Actual behaviour

The actual output of the script:
```
CHECK BALANCES OF CRC TOKENS FOR SAFE: 0x42cEDde51198D1773590311E2A340DC06B24cB37.

 --------------- 
Get the Blockscout data
With a total value of 10261869825635210942529 CRC

 ---------------
Get the Subgraph data
With a total value of 10261870325735209813968 CRC

 --------------- 
Length of the subgraph data: 49
Length of the blockscout data: 40

 --------------- 
Intersection of the datasets:
Number of tokens from the subgraph dataset that are also in the blockscout dataset: 40
Number of tokens from the blockscout dataset that are also in the subgraph dataset: 40

 --------------- 
Difference of the datasets::
Number of tokens from the subgraph dataset that are NOT in the blockscout dataset: 9
Number of tokens from the blockscout dataset that are NOT in the subgraph dataset: 0

 --------------- 
Tokens that are not in the Blockscout dataset:
* Token 0x088679034Ea9953fCaa27B0BA2c3AAfFC1B939cE, which has a balance of 100000000000000
* Token 0x0e49DF98B28Ec3CdE4E10325D68D6318454735f0, which has a balance of 100000000000001
* Token 0x4894b4E797E2b126440597EE052b36254863C02A, which has a balance of 1
* Token 0x505784D2A844780cAd4FbfA96c15e59aA643C19B, which has a balance of 100000000000000
* Token 0x517EEA0325989D69c4ea851e58d55b07489E5d17, which has a balance of 199999998871435
* Token 0x80C0479662d45fb26B95b701422DB6B2Df3b145c, which has a balance of 1
* Token 0xa086840065f90f586780b20713acF1eB4AFcd8E3, which has a balance of 1
* Token 0xb2Eb4956610C3aF22Dd4ab064C2a8B2A0a7ce081, which has a balance of 1
* Token 0xbfeefeBe98bABe981FB813C641376000DF37F86c, which has a balance of 99999999999
```

**Comment by vbaranov** [comment]
Thank you for reporting this issue. There was an issue with some blocks fetching on Gnosis chain explorer, which leads to the discrepancy. That issue resolved - all historical blocks were fetched. Please let me kno, if you still observe discrepancy in the number of tokens.
