### ISSUE TITLE
: <Issue Title>

### ISSUE THREAD

**Issue by rkyatham21** [blockscout/blockscout#7998]
*Describe your issue here.*

### Environment
* Elixir Version: 1.14.0
* Erlang Version: 25
* BlockScout Version: 

* User Agent: `Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36`

### Steps to reproduce

*Tell us how to reproduce this issue. If possible, push up a branch to your fork with a regression test we can run to reproduce locally.*

### Expected Behaviour

*Tell us what should happen.*

### Actual Behaviour

*Tell us what happens instead.*

**Comment by rkyatham21** [comment]
While i deposit transaction keep getting failed i have tried like 3-4 times all the time im getting failed transactions failed

**Comment by vbaranov** [comment]
This chat is for Blockscout related questions. Your question is out of scope, where Blockscout team can help.
