### ISSUE TITLE
24h bridge from linea to eth

### ISSUE THREAD

**Issue by runduck113** [blockscout/blockscout#8002]
*Describe your issue here.*
pls check my tx. its been 24 hours but my eth from linea to eth still pending sir. thats too long.. https://explorer.linea.build/tx/0x98dc3476418459b590fd012cef88a4bbccce770f155d5f20c8ddb6fa9b03270b

**Comment by sl1depengwyn** [comment]
Please contact Linea team directly, contacts can be found [here](https://bridge.linea.build/) or [here](https://goerli.linea.build/), this issue is unrelated to blockscout.
