### ISSUE TITLE
Linea: <Issue Title> transaction not credited 

### ISSUE THREAD

**Issue by Ombalaji** [blockscout/blockscout#8003]
*Describe Hi sir.. This is Balaji from our community member.I bridged our official site 2 times L1 to L2 mainnet.Bridgiging error acquired but Fund credited to my Linea account and transaction details not showing in our site.We need to clear the bugs and i claim manually my Linea Eth L2 to ETH L1network 3 days before but still now not credited to my L1 Etherium network.Pls check and update. I'm unable to join our discord because invite link showing expired error so only i sent message here.

Transaction hash:
0xad96c6680ae15b1ed3f44a2909d0131f517994843184d7018fcac8aa891cb8be
 issue here*

### Environment
* Elixir Version: 1.14.0
* Erlang Version: 25
* BlockScout Version: v5.2.0-beta

* User Agent: `Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/112.0.0.0 Safari/537.36`

### Steps to reproduce

*Tell us how to reproduce this issue. If possible, push up a branch to your fork with a regression test we can run to reproduce locally.*

### Expected Behaviour

*Tell us what should happen.*

### Actual Behaviour

*Tell us what happens instead.*

**Comment by vbaranov** [comment]
Please ask this question in Linea Discord, which can be found here https://goerli.linea.build.
