### ISSUE TITLE
Alpha-3 L2: <Issue Title>

### ISSUE THREAD

**Issue by Nftlover17** [blockscout/blockscout#8004]
*Describe your issue here.*

### Environment
* Elixir Version: 1.14.0
* Erlang Version: 25
* BlockScout Version: 5.1.5

* User Agent: `Mozilla/5.0 (X11; CrOS x86_64 14541.0.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36`

### Steps to reproduce

*Tell us how to reproduce this issue. If possible, push up a branch to your fork with a regression test we can run to reproduce locally.*

### Expected Behaviour

*Tell us what should happen.*

### Actual Behaviour

*Tell us what happens instead.*

**Comment by Nftlover17** [comment]
i am try to bridge eth from Grimsvotn L2 to Eldfell L3.But every time txs fail from metamask.
What can i do?
![Screenshot 2023-07-22 6 33 03 PM](https://github.com/blockscout/blockscout/assets/119653737/c0848ece-6d78-4d03-b415-a4b57c40c10a)

**Comment by vbaranov** [comment]
Please ask your question in Taiko discord https://discord.gg/taikoxyz
