### ISSUE TITLE
Alpha-3 L2: **Unable to Bridge ETH from Taiko Alpha-3 L2 to Eldwell L3 Testnets - Urgent Resolution Needed**

### ISSUE THREAD

**Issue by UNIsan33** [blockscout/blockscout#8005]
**Unable to Bridge ETH from Taiko Alpha-3 L2 to Eldwell L3 Testnets - Urgent Resolution Needed**

Dear [Developer/Support Team],

I hope this message finds you well. I am writing to report a critical issue that I have encountered while attempting to bridge ETH from Taiko Alpha-3 Layer 2 (L2) to Eldwell Layer 3 (L3) testnet. As of this complaint, the transaction has been pending for over a day, and I am unable to locate the transaction hash associated with this failed bridge attempt.

**Issue Summary:**
1. Unable to bridge ETH from Taiko Alpha-3 L2 to Eldwell L3 testnet.
2. Transaction has been pending for an extended period.
3. Transaction hash is untraceable, making it difficult to investigate.

**Details of the Issue:**
On [21/07/23 at 23:58], I initiated a transaction to bridge ETH from my account with the Ethereum address: 0x7f7B2c48E68242E4918625FD6f1231407D00A311. The objective was to transfer ETH from Taiko Alpha-3 L2 to Eldwell L3 testnet to participate in the ecosystem seamlessly. However, the transaction has been pending for almost 24 hours, preventing the successful bridging of my funds.

Additionally, despite numerous attempts to locate the transaction hash on both Taiko Alpha-3 L2 and Eldwell L3 block explorers, I have been unable to find any trace of the transaction. This has compounded my concerns as the lack of a transaction hash further hinders any potential troubleshooting.

**Impact and Urgency:**
As an active participant in both the Taiko and Eldwell ecosystems, the inability to bridge ETH between these chains has significantly disrupted my operations and undermined my confidence in the networks' interoperability. I urgently require a resolution on this matter to resume normal activities.

**Requested Action:**
I kindly request the development team's immediate attention to investigate and rectify this issue. Please prioritize this case as high urgency and assign appropriate resources to identify the cause of the failed bridge transaction and initiate a fix.

**Additional Information:**
To aid in the investigation process, I am providing relevant transaction details below:
- Ethereum Address: 0x7f7B2c48E68242E4918625FD6f1231407D00A311
- Bridge Source: Taiko Alpha-3 L2
- Bridge Destination: Eldwell L3 Testnets

**Conclusion:**
I genuinely appreciate your prompt attention to this matter, as it significantly impacts my operations within both ecosystems. Please keep me informed of the progress made toward resolving this issue. Should you require any further information or assistance, do not hesitate to reach out to me at [Your Email Address/Preferred Contact Method].

Thank you for your understanding and dedication to ensuring the seamless functioning of the Taiko and Eldwell networks.

Sincerely,

San

**Comment by vbaranov** [comment]
Please ask your question in Taiko discord https://discord.gg/taikoxyz
