### ISSUE TITLE
Alpha-3 L2: <MetaMask Transaction stack>

### ISSUE THREAD

**Issue by CloudR4108** [blockscout/blockscout#8006]
*Describe your issue here.*

My transaction is super stack. I tried to bridge from Taiko to sepholia and sth went wrong.

transaction id 
0x683d33bf9da6fe26b62716441cd2311f50ae5a2e7144cf37132ab2cbdda2d59e

### Environment
* Elixir Version: 1.14.0
* Erlang Version: 25
* BlockScout Version: 5.1.5

* User Agent: `Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36`

### Steps to reproduce

*Tell us how to reproduce this issue. If possible, push up a branch to your fork with a regression test we can run to reproduce locally.*

### Expected Behaviour

*Tell us what should happen.*

### Actual Behaviour

*Tell us what happens instead.*
![Screenshot_2](https://github.com/blockscout/blockscout/assets/140271425/0da30175-b11d-4373-aeb1-450eb90506f3)
![Screenshot_1](https://github.com/blockscout/blockscout/assets/140271425/d7475c09-43b0-4f37-a0cf-84e19589d5e3)

**Comment by vbaranov** [comment]
Please ask your question in Taiko discord https://discord.gg/taikoxyz
