### ISSUE TITLE
Andromeda: <Issue Title>Layerzero transaction pending from your side

### ISSUE THREAD

**Issue by rektoshii** [blockscout/blockscout#8007]
*Describe your issue here.*
The USDC i bridged to metic from BNB have been pending for a long time now, please do something about it ASAP
hash: 0xd8f8325268d92afdffe65d0a6e7782b162a67108920162412107f50281ccfdef
link to transaction: https://layerzeroscan.com/102/address/0x6694340fc020c5e6b96567843da2df01b2ce1eb6/message/151/address/0x45f1a95a4d3f3836523f5c83673c797f4d4d263b/nonce/214269

### Environment
* Elixir Version: 1.14.0
* Erlang Version: 25
* BlockScout Version: v5.2.1-beta

* User Agent: `Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36`

### Steps to reproduce

*Tell us how to reproduce this issue. If possible, push up a branch to your fork with a regression test we can run to reproduce locally.*

### Expected Behaviour

*Tell us what should happen.*

### Actual Behaviour

*Tell us what happens instead.*

**Comment by vbaranov** [comment]
Andromeda Blockscout instance is not managed by the Blockscout team. Please ask your question in Andromeda chain support channel.
