### ISSUE TITLE
Kroma Sepolia: <Issue Title>

### ISSUE THREAD

**Issue by peekabu123** [blockscout/blockscout#8016]
*Describe your issue here.*

### Environment

* Backend Version/branch/commit: v4.1.7-beta
* Frontend Version+commit: 
* User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36

### Steps to reproduce

*Tell us how to reproduce this issue.  ❤️ if you can push up a branch to your fork with a regression test we can run to reproduce locally.*

### Expected behaviour

*Tell us what should happen.*

### Actual behaviour

*Tell us what happens instead.*

**Comment by peekabu123** [comment]
VictorI have a swap transaction on Kroma that has been pending for three days now and my metamask wallet cannot up date the Kroma balances or transact on the bridge or swap anymore Is there a fix guideline for that?  Randy ChanOn Jul 25, 2023, at 3:36 AM, Victor Baranov ***@***.***> wrote:﻿
Closed #8016 as completed.

**Comment by NikitaSavik** [comment]
> VictorI have a swap transaction on Kroma that has been pending for three days now and my metamask wallet cannot up date the Kroma balances or transact on the bridge or swap anymore Is there a fix guideline for that?  Randy ChanOn Jul 25, 2023, at 3:36 AM, Victor Baranov ***@***.***> wrote:﻿ Closed #8016 as completed. —Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>

Please contact Kroma team directly, https://discord.com/invite/kroma
