### ISSUE TITLE
Issue worker fetcher internal transaction

### ISSUE THREAD

**Issue by khaitqNapaglobal** [blockscout/blockscout#8017]
<img width="1504" alt="Screenshot 2023-07-24 at 11 52 51" src="https://github.com/blockscout/blockscout/assets/108641766/432f5997-75d6-47d7-bb4e-1ef8591c8bc0">

my node config 

<img width="641" alt="Screenshot 2023-07-24 at 11 55 07" src="https://github.com/blockscout/blockscout/assets/108641766/f8b28e32-f4df-40d2-8a1f-2d8e3c0028fd">

**Comment by vbaranov** [comment]
@khaitqNapaglobal did you run the node in archive mode from the 0 block or switched to the mode after sometime of running the node?

**Comment by khaitqNapaglobal** [comment]
I switched to the mode after some time of running the node.

**Comment by vbaranov** [comment]
Unfortunately, this will not make the node to the archiveal for the blocks, which were already indexed by the node. In order to convert the node to the full archival mode, you should start it with `--gcmode=archive` from scratch.

**Comment by khaitqNapaglobal** [comment]
thank you so much, ok i'm try
