### ISSUE TITLE
Linea: <Issue Title>

### ISSUE THREAD

**Issue by sahidmolla55** [blockscout/blockscout#8018]
*Describe your issue here.*

### Environment
* Elixir Version: 1.14.0
* Erlang Version: 25
* BlockScout Version: v5.2.0-beta

* User Agent: `Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/116.0.0.0 Mobile Safari/537.36`

### Steps to reproduce

*Tell us how to reproduce this issue. If possible, push up a branch to your fork with a regression test we can run to reproduce locally.*

### Expected Behaviour

*Tell us what should happen.*

### Actual Behaviour

*Tell us what happens instead.*

**Comment by sahidmolla55** [comment]
My bridge is pending 3 days
Transaction hash :- 0x3c0c4c3a16a0680e0c713197501682cf1134be3fe156b27dd5e810628b46b9bf
Success but not received

**Comment by sl1depengwyn** [comment]
Please contact Linea team directly, contacts can be found [here](https://bridge.linea.build/) or [here](https://goerli.linea.build/), this issue is unrelated to blockscout.
