### ISSUE TITLE
Linea: <Issue Title>

### ISSUE THREAD

**Issue by Farhanghaz** [blockscout/blockscout#8021]
*DeHello, I used Linea Bridge to transfer currencies from Linea to Eth, but unfortunately, the transaction has not been completed until today, and I do not know what to do in order to retrieve the Linea currency
![Screenshot 2023-07-24 042703](https://github.com/blockscout/blockscout/assets/136129505/0618ed65-d365-4042-8361-3c7868873971)
scribe your issue here.*

### Environment
* Elixir Version: 1.14.0
* Erlang Version: 25
* BlockScout Version: v5.2.0-beta

* User Agent: `Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36`

### Steps to reproduce

*Tell us how to reproduce this issue. If possible, push up a branch to your fork with a regression test we can run to reproduce locally.*

### Expected Behaviour

*Tell us what should happen.*

### Actual Behaviour

*Tell us what happens instead.*

**Comment by sl1depengwyn** [comment]
Please contact Linea team directly, contacts can be found [here](https://bridge.linea.build/) or [here](https://goerli.linea.build/), this issue is unrelated to blockscout.
