### ISSUE TITLE
Polygon-edge deposit problem

### ISSUE THREAD

**Issue by polygomic** [blockscout/blockscout#8032]
when in bridge we deposit from root chain to side chain blockscout shows 0xf213159c not deposit
what is the problem and how can we map the codes to deposit.

* Deployment type (Manual/Docker/Docker-compose):
* Elixir & Erlang/OTP versions (`elixir -version`):
* Node JS version (`node -v`):
* Operating System:
* Blockscout Version/branch/commit:
* Archive node type && version (Erigon/Geth/Nethermind/Ganache/?):

### Steps to reproduce

*Tell us how to reproduce this issue.  ❤️ if you can push up a branch to your fork with a regression test we can run to reproduce locally.*

### Expected behaviour

*Tell us what should happen.*

### Actual behaviour

*Tell us what happens instead.*

**Comment by polygomic** [comment]
how should etherscan shows methods names in unverified bridge contracts?

**Comment by vbaranov** [comment]
Could you provide link as example?

**Comment by Shednandezstore** [comment]
Tőkén contact allowed

**Comment by Shednandezstore** [comment]
Verify my bc1qhqcw83dck6m644448w9mvs6vssm57mlvtfn68n address

**Comment by vbaranov** [comment]
Closing due to no response from the author.
