### ISSUE TITLE
How to solve application=indexer fetcher=block_reward count=10 error_count=10 [error] failed to fetch

### ISSUE THREAD

**Issue by bayupratama15** [blockscout/blockscout#8033]
how do i fix this ? 
![image](https://github.com/blockscout/blockscout/assets/42171088/0f97f34a-b1c1-4a62-bc85-0be426953a9e)

### Environment

* Deployment type (Docker-compose): Docker Compose
* Node JS version (`node -v`): 16.14
* Operating System: Ubuntu
* Blockscout Version/branch/commit: latest
* Archive node type && version (Erigon/Geth/Nethermind/Ganache/?): Parity (Open Ethereum)

**Comment by vbaranov** [comment]
@bayupratama15 you should enable `trace` module.

**Comment by bayupratama15** [comment]
> @bayupratama15 you should enable `trace` module.

how to enable trace module?

**Comment by vbaranov** [comment]
Please take a look to OpenEthereum docs about Trace module https://openethereum.github.io/JSONRPC-trace-module

**Comment by bayupratama15** [comment]
oke thans
