### ISSUE TITLE
: <Issue Title>

### ISSUE THREAD

**Issue by ASMSKANNER** [blockscout/blockscout#8034]
*Describe your issue here.*

### Environment
* Elixir Version: 1.14.0
* Erlang Version: 25
* BlockScout Version: 

* User Agent: `Chrome/115.0.5790.102

### Steps to reproduce

Withdrowing any amount of ETH

### Expected Behaviour

Waiting for withdroeal message should dissapear after the TX is done.

### Actual Behaviour

The message is running forever.

![image](https://github.com/blockscout/blockscout/assets/7419561/32f3e2f8-50e0-480e-b63c-4090c1e5babd)

**Comment by vbaranov** [comment]
This chat is for Blockscout related questions. Your question is out of scope, where Blockscout team can help.
