### ISSUE TITLE
import_test.exs:167 failing, (test "with valid data") 

### ISSUE THREAD

**Issue by voyenavion** [blockscout/blockscout#8037]
*Describe your issue here.*
running the "test valid data" fails for an odd reason. the match assertion fails on many byte arrays but the values in the array look exactly the same. why is this? also, should i expect all the unit tests in blockscout to pass generally? 
 
### Environment

* Deployment type (Manual/Docker/Docker-compose): manual
* Elixir & Erlang/OTP versions (`elixir -version`): elixir 1.14.5-otp-25 and erlang 25.3.2.3
* Node JS version (`node -v`):  
* Operating System: mac ventura 
* Blockscout Version/branch/commit: 5.2.1-beta
* Archive node type && version (Erigon/Geth/Nethermind/Ganache/?):

### Steps to reproduce

*Tell us how to reproduce this issue.  ❤️ if you can push up a branch to your fork with a regression test we can run to reproduce locally.*

### Expected behaviour

*Tell us what should happen.* 
import_test.exs/test "with valid data" on line 167 should pass

### Actual behaviour

*Tell us what happens instead.*
It does not, see screenshots 
![Screenshot 2023-07-25 at 9 37 57 AM](https://github.com/blockscout/blockscout/assets/14279989/c945f8c0-d14b-4a2a-a3fa-0a6a8a812d77)
![Screenshot 2023-07-25 at 9 37 31 AM](https://github.com/blockscout/blockscout/assets/14279989/9b3dcac1-4d7d-4b84-bbc9-041cf437dc8d)

**Comment by vbaranov** [comment]
@voyenavion I cannot reproduce the issue by running:
```
mix test test/explorer/chain/import_test.exs
```
from `apps/explorer` folder from master branch. How do you run the test?

**Comment by voyenavion** [comment]
cd apps/explorer
mix test test/explorer/chain/import_test.exs:167

**Comment by voyenavion** [comment]
MIX_ENV=test
POSTGRES_DB=explorer_test
POSTGRES_PASSWORD=postgres
POSTGRES_USER=postgres
CHAIN_ID=77
ETHEREUM_JSONRPC_CASE=EthereumJSONRPC.Case.Geth.Mox
ETHEREUM_JSONRPC_WEB_SOCKET_CASE=EthereumJSONRPC.WebSocket.Case.Mox
ETHEREUM_JSONRPC_VARIANT=geth
env vars set

**Comment by vbaranov** [comment]
You should not set `ETHEREUM_JSONRPC_VARIANT=geth` when running the test.

**Comment by voyenavion** [comment]
Right you are. Thanks for your help @vbaranov . On a more personal note, blockscout is by far the most complicated thing I have ever worked on. It's a really impressive piece of software. My hat is off to you, sir. Thanks for all you do.
