### ISSUE TITLE
Linea: Bridging

### ISSUE THREAD

**Issue by Hardeybola** [blockscout/blockscout#8043]
My bridged linea hasn’t reached ethereum after several days
0x21aE2ccc8D9988640232bFC690ef82A9B3f9F642
### Environment
* Elixir Version: 1.14.0
* Erlang Version: 25
* BlockScout Version: v5.2.0-beta

* User Agent: `Mozilla/5.0 (iPhone; CPU iPhone OS 16_4 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Mobile/15E148 WebView MetaMaskMobile`

### Steps to reproduce

*Tell us how to reproduce this issue. If possible, push up a branch to your fork with a regression test we can run to reproduce locally.*

### Expected Behaviour

*Tell us what should happen.*

### Actual Behaviour

*Tell us what happens instead.*

**Comment by vbaranov** [comment]
Please ask this question in Linea Discord, which can be found here https://goerli.linea.build.
