### ISSUE TITLE
How to configure APIS URL?

### ISSUE THREAD

**Issue by binny1024** [blockscout/blockscout#8057]
*Describe your issue here.*

### Environment

* Deployment type (Docker-compose):
* Elixir & Erlang/OTP versions (`elixir -version`):
* Node JS version (`node -v`):
* Operating System: MacOS  m1
* Blockscout Version/branch/commit:
* Archive node type && version (Erigon/Geth/Nethermind/Ganache/?):

### Steps to reproduce

*Tell us how to reproduce this issue.  ❤️ if you can push up a branch to your fork with a regression test we can run to reproduce locally.*

The containers are up, but some configurations are not found where to configure。
Can anyone tell me which environment variable the URL of APIS corresponds to?
Thank you very much.
Thank you very much.
Thank you very much.

### Expected behaviour

*Tell us what should happen.*

### Actual behaviour

*Tell us what happens instead.*
![image](https://github.com/blockscout/blockscout/assets/20657767/09faabf1-cb12-4ed0-a375-6f87b8ae7caf)

![image](https://github.com/blockscout/blockscout/assets/20657767/505a4034-6e95-4dca-bb61-60cf0322eaee)

**Comment by sl1depengwyn** [comment]
Via `BLOCKSCOUT_HOST` env variable

**Comment by binny1024** [comment]
Thank you very much.
