### ISSUE TITLE
Ethereum Classic: <Issue Title>

### ISSUE THREAD

**Issue by Pendingissue** [blockscout/blockscout#8058]
*Describe your issue here.*

### Environment
* Elixir Version: 1.13.1
* Erlang Version: 24
* BlockScout Version: v4.1.8-beta

* User Agent: `Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/115.0.0.0 Safari/537.36`

### Steps to reproduce

*Tell us how to reproduce this issue. If possible, push up a branch to your fork with a regression test we can run to reproduce locally.*

### Expected Behaviour

*Tell us what should happen.*

### Actual Behaviour

*Tell us what happens instead.*

**Comment by Pendingissue** [comment]
Block Details
 Block Height
18009638
 Timestamp
18 minutes ago | July-28-2023 06:17:39 PM +9 UTC
 Transactions
 Miner
[0x6364C971f636b14fC7FDB5E3Ccd0d8c396870328](https://blockscout.com/etc/mainnet/address/0x6364C971f636b14fC7FDB5E3Ccd0d8c396870328)
 Size
659 bytes
 Hash
0x8fc45fd2acb9d57210ed095a3974ad3d3478f75eda07d5e30e889af727a04b55
 Parent Hash
[0x15de7db92003349ca0c54cbfd145b8906a4da367894dd4eac27c6ebcaecefe23](https://blockscout.com/etc/mainnet/block/18009637)
 Difficulty
1,861,938,910,139,990
 Total Difficulty
5,834,438,115,167,446,505,730
 Gas Used
21,000 | 0.3%
 Gas Limit
8,000,000
 Nonce
0x0efde1fa253bb9b7
 Miner Reward
2.560126 ETC

How can i solve this problem...

**Comment by sl1depengwyn** [comment]
Please ask your question in Ethereum Classic Discord https://discord.com/invite/dwxb6nf

**Comment by vbaranov** [comment]
Please ask your question in Ethereum Classic Discord https://discord.com/invite/dwxb6nf
