### ISSUE TITLE
My contract address issues

### ISSUE THREAD

**Issue by Shednandezstore** [blockscout/blockscout#8061]
Contract api not correct 
Please remove from contract list as well as account details for this reason 

1. [x] @coinmarket

### Environment

* Deployment type (Manual/Docker/Docker-compose):
* Elixir & Erlang/OTP versions (`elixir -version`):
* Node JS version (`node -v`):
* Operating System:
* Blockscout Version/branch/commit:
* Archive node type && version (Erigon/Geth/Nethermind/Ganache/?):

### Steps to reproduce
Use this public address as my virility token [0xf752EC3A9091Aa800561f5e232e7b0b326402215****]()
*Tell us how to reproduce this issue.  ❤️ if you can push up a branch to your fork with a regression test we can run to reproduce locally.*

### Expected behaviour

*Tell us what should happen.*

### Actual behaviour

*Tell us what happens instead.*
Contract address reversed and incorrect

**Comment by vbaranov** [comment]
@Shednandezstore could you elaborate on what issue do you have? I didn't get it from the description.

**Comment by Shednandezstore** [comment]
Account address changed by default Sent by me On Jul 28, 2023, at 2:08 PM, Victor Baranov ***@***.***> wrote:﻿
@Shednandezstore could you elaborate on what issue do you have? I didn't get it from the description.
