### ISSUE TITLE
verify and publish code error

### ISSUE THREAD

**Issue by oki-cyber** [blockscout/blockscout#8074]
*Describe your issue here.*
after deploying contract using remix i was unable to verify and publish the transactions on the block explorer
### Environment

* Deployment type (Manual/Docker/Docker-compose):
* Elixir & Erlang/OTP versions (`elixir -version`):
* Node JS version (`node -v`):
* Operating System:
* Blockscout Version/branch/commit:
* Archive node type && version (Erigon/Geth/Nethermind/Ganache/?):

### Steps to reproduce

*Tell us how to reproduce this issue.  ❤️ if you can push up a branch to your fork with a regression test we can run to reproduce locally.*

### Expected behaviour

*Tell us what should happen.*

### Actual behaviour

*Tell us what happens instead.*

**Comment by oki-cyber** [comment]
i hope the issue is resolved soon

**Comment by Osub** [comment]
Solve it？
