### ISSUE TITLE
Unable to distinguish between erc721 and erc20 transactions

### ISSUE THREAD

**Issue by xuxinlai2002** [blockscout/blockscout#8079]
Unable to distinguish between erc721 and erc20 transactions.

### Environment
* Deployment type (Manual/Docker/Docker-compose):
Manual
* Elixir & Erlang/OTP versions (`elixir -version`):

* Node JS version (`node -v`):
nodejs v16.0.0
* Operating System:
Ubuntu
* Blockscout Version/branch/commit:
main
* Archive node type && version (Erigon/Geth/Nethermind/Ganache/?):
elixir 1.12.3-otp-24
erlang 24.2
nodejs 16.13.0

**Comment by vbaranov** [comment]
@xuxinlai2002 what do you mean by "Unable to distinguish between erc721 and erc20 transactions."? How is it shown?

**Comment by vbaranov** [comment]
Closing due to no response from the author.
