### ISSUE TITLE
Unable to display contract's internal transaction information

### ISSUE THREAD

**Issue by xuxinlai2002** [blockscout/blockscout#8080]
Unable to display contract's internal transaction information

Environment
Deployment type (Manual/Docker/Docker-compose):
Manual

Elixir & Erlang/OTP versions (elixir -version):

Node JS version (node -v):
nodejs v16.0.0

Operating System:
Ubuntu

Blockscout Version/branch/commit:
main

Archive node type && version (Erigon/Geth/Nethermind/Ganache/?):
elixir 1.12.3-otp-24
erlang 24.2
nodejs 16.13.0

**Comment by vbaranov** [comment]
@xuxinlai2002 could elaborate on the issue? What type of the node are you using? Does it support required methods for internal transactions fetching https://docs.blockscout.com/for-developers/information-and-settings/node-tracing-json-rpc-requirements#enable-tracing-to-fetch-internal-transactions? Is supported method enabled on the node?

**Comment by vbaranov** [comment]
Closing due to no response from the author.
