### ISSUE TITLE
Contract verification using API is always pending

### ISSUE THREAD

**Issue by shellteo** [blockscout/blockscout#8085]
We forked blockscout v5.0.0, but when the user uses [mantle explorer](https://explorer.testnet.mantle.xyz/), the contract verification using forge has been stuck in pending

### Environment

* Deployment type: Manual
* Elixir & Erlang/OTP versions (`elixir -version`): Erlang/OTP 25 [erts-13.1.1] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [jit] Elixir 1.14.2 (compiled with Erlang/OTP 25)
* Node JS version (`node -v`): v16.16.0
* Operating System: macOS Montery 12.6.5
* Blockscout Version/branch/commit: v5.0.0-beta(https://github.com/mantlenetworkio/blockscout)
* Archive node type && version (Erigon/Geth/Nethermind/Ganache/?): Mantle-Geth

### Steps to reproduce
Execute the following command
```shell
forge verify-contract --verifier blockscout --watch \
--verifier-url https://explorer.testnet.mantle.xyz/api\?module\=contract\&action\=verify \
--compiler-version "v0.8.9+commit.e5eed63a" \
--num-of-optimizations 200 \
--chain 5001 \
--constructor-args $(cast abi-encode "constructor(address,address,string,string,uint8)" 0x4200000000000000000000000000000000000010 0x9DDc8558df18dD6b6961D42eE312cb770979F6BB "Albert Token" "AT" 18) \
0xc8058960a9d7e7d81143bdba38d19e6824165932 src/L2StandardERC20.sol:L2StandardERC20
```

### Expected behaviour
verify success

### Actual behaviour
<img width="1060" alt="image" src="https://github.com/blockscout/blockscout/assets/16064604/e13300e0-15f5-4048-94bf-b5666040cba8">

**Comment by vbaranov** [comment]
The root cause of the issue is the same, as in https://github.com/blockscout/blockscout/issues/8084 - missing internal transactions in the DB.
