### ISSUE TITLE
RSK/Rootstock: implement additional block data

### ISSUE THREAD

**Issue by ulyanas** [blockscout/blockscout#8086]
Custom fields for indexing, to be shown on block page:

- minimumGasPrice
- bitcoinMergedMiningHeader
- bitcoinMergedMiningCoinbaseTransaction
- bitcoinMergedMiningMerkleProof
- hashForMergedMining

Source: **eth_getBlockByHash** or **eth_getBlockByNumber** methods

**Comment by vbaranov** [comment]
Resolved in #8076
