### ISSUE TITLE
Missing index on transactions to_address_hash and from_address_hash

### ISSUE THREAD

**Issue by cen1** [blockscout/blockscout#8089]
After updating one of our instances from v4.1.8-beta to v5.1.2-beta our database got hit with 100% CPU usage due to slow queries.

Analytics showed this query type as the culprit:

`SELECT count(t0."hash") FROM "transactions" AS t0 WHERE ((t0."to_address_hash" = '0x...') OR (t0."from_address_hash" = '0x...'))`

After adding this index, everything seems OK:
`CREATE INDEX idx_transactions_from_to ON transactions (to_address_hash, from_address_hash);`

I do not know what parts of the code call this query, observation was strictly through slow query log.

My initial thought was that v5 dropped some index but after comparing v4 and v5 transactions table there were only minor differences, so the only explanation I have is that v5 introduced this query in some part of the code and it did not exist in v4.

### Environment

* Deployment type (Manual/Docker/Docker-compose): manual
* Blockscout Version/branch/commit: v5.1.2-beta

**Comment by cen1** [comment]
Another offending query appeared, still researching what index is missing on this one:

`SELECT t0."block_hash", t0."block_number", t0."created_contract_address_hash", t0."cumulative_gas_used", t0."from_address_hash", t0."gas", t0."gas_price", t0."gas_used", t0."hash", t0."index", t0."input", t0."nonce", t0."status", t0."to_address_hash", t0."value", t0."revert_reason", b1."timestamp", $1 - t0."block_number" FROM "transactions" AS t0 INNER JOIN "blocks" AS b1 ON b1."hash" = t0."block_hash" WHERE ((t0."to_address_hash" = '...')) OR (t0."from_address_hash" = '...') OR (t0."created_contract_address_hash" = '...') ORDER BY t0."block_number" DESC LIMIT $2 OFFSET $3;`

**Comment by cen1** [comment]
It could be that my newly added index affected the planner to perform worse since the index is part of the plan:

```
Limit  (cost=15028.68..15447.87 rows=50 width=844) (actual time=19.852..21.634 rows=0 loops=1)
   ->  Nested Loop  (cost=15028.68..44581.11 rows=3525 width=844) (actual time=19.850..21.631 rows=0 loops=1)
         ->  Gather Merge  (cost=15028.25..15438.79 rows=3525 width=828) (actual time=19.848..21.628 rows=0 loops=1)
               Workers Planned: 2
               Workers Launched: 0
               ->  Sort  (cost=14028.23..14031.90 rows=1469 width=828) (actual time=6.605..6.608 rows=0 loops=1)
                     Sort Key: t0.block_number DESC
                     Sort Method: quicksort  Memory: 25kB
                     ->  Parallel Bitmap Heap Scan on transactions t0  (cost=154.78..13950.95 rows=1469 width=828) (actual time=3.769..3.772 rows=0 loops=1)
                           Recheck Cond: ((to_address_hash = '\x307839653535613439443235313332344231363233646332413831383934443141664266423862626443'::bytea) OR (from_address_hash = '\x307839653535613439443235313332344231363233646332413831383934443141664266423862626443'::bytea) OR (created_contract_address_hash = '\x307839653535613439443235313332344231363233646332413831383934443141664266423862626443'::bytea))
                           ->  BitmapOr  (cost=154.78..154.78 rows=3525 width=0) (actual time=3.253..3.256 rows=0 loops=1)
                                 ->  Bitmap Index Scan on flare_transactions_from_to  (cost=0.00..19.00 rows=1392 width=0) (actual time=0.808..0.808 rows=0 loops=1)
                                       Index Cond: (to_address_hash = '\x307839653535613439443235313332344231363233646332413831383934443141664266423862626443'::bytea)
                                 ->  Bitmap Index Scan on transactions_from_address_hash_with_pending_index  (cost=0.00..128.56 rows=2132 width=0) (actual time=1.383..1.383 rows=0 loops=1)
                                       Index Cond: (from_address_hash = '\x307839653535613439443235313332344231363233646332413831383934443141664266423862626443'::bytea)
                                 ->  Bitmap Index Scan on transactions_created_contract_address_hash_with_pending_index  (cost=0.00..4.57 rows=1 width=0) (actual time=1.059..1.059 rows=0 loops=1)
                                       Index Cond: (created_contract_address_hash = '\x307839653535613439443235313332344231363233646332413831383934443141664266423862626443'::bytea)
         ->  Index Scan using blocks_number_index on blocks b1  (cost=0.43..8.26 rows=1 width=16) (never executed)
               Index Cond: (number = t0.block_number)
```

**Comment by atapin** [comment]
> Another offending query appeared, still researching what index is missing on this one:
> 
> `SELECT t0."block_hash", t0."block_number", t0."created_contract_address_hash", t0."cumulative_gas_used", t0."from_address_hash", t0."gas", t0."gas_price", t0."gas_used", t0."hash", t0."index", t0."input", t0."nonce", t0."status", t0."to_address_hash", t0."value", t0."revert_reason", b1."timestamp", $1 - t0."block_number" FROM "transactions" AS t0 INNER JOIN "blocks" AS b1 ON b1."hash" = t0."block_hash" WHERE ((t0."to_address_hash" = '...')) OR (t0."from_address_hash" = '...') OR (t0."created_contract_address_hash" = '...') ORDER BY t0."block_number" DESC LIMIT $2 OFFSET $3;`

this query has the join just for the sake of getting the block's timestamp. 
@vbaranov can this be optimised by saving the block's timestamp right into the `transactions` table?

**Comment by cen1** [comment]
Closing due to performance improvements in later releases, will reopen as needed.
