### ISSUE TITLE
Wrong link in email notifications in mainnet

### ISSUE THREAD

**Issue by 0xtzData** [blockscout/blockscout#8094]
must be https://eth.blockscout.com/

Backend: [v5.2.1-beta.+commit.bbcebae8](https://github.com/blockscout/blockscout/commit/bbcebae8)

![Image](https://user-images.githubusercontent.com/108135703/257664804-6ff64075-c071-4e94-bd84-1e70af147743.png)

**Comment by atapin** [comment]
it should have been fixed in [494b89f](https://github.com/blockscout/blockscout/commit/494b89fdeca629891a1d6dfe92daa938ff0e81f7), but it's on master branch

cc @vbaranov

**Comment by vbaranov** [comment]
This was a DevOps issue because of wrong value in `BLOCKSCOUT_HOST` env variable. Fixed.
