### ISSUE TITLE
Need help to recovery my ETH coins

### ISSUE THREAD

**Issue by SCShawDesigns** [blockscout/blockscout#8095]
I need help retrieving my ETH coins. The transaction is not successful as the coins has not arrived in my Gemini Wallet.

[Transaction 0x47b868e7349146e6bcd38988300afbfc9267cd5cb01f0ae0d6c5224843fb3843 - Quorum Explorer.pdf](https://github.com/blockscout/blockscout/files/12235615/Transaction.0x47b868e7349146e6bcd38988300afbfc9267cd5cb01f0ae0d6c5224843fb3843.-.Quorum.Explorer.pdf)

**Comment by SCShawDesigns** [comment]
Please may I have a feedback on my query

**Comment by sl1depengwyn** [comment]
> Please may I have a feedback on my query

It's not related to blockscout as open source blockchain explorer, we do not relate to Quorum
