### ISSUE TITLE
ADMIN_PANEL_ENABLED=true      but      /admin        404

### ISSUE THREAD

**Issue by Osub** [blockscout/blockscout#8096]
ADMIN_PANEL_ENABLED=true      but      /admin        404
![image](https://github.com/blockscout/blockscout/assets/7599190/fd70e56d-abfe-4c68-9506-24098023363f)

**Comment by vbaranov** [comment]
@Osub it is compile-time env variable. You should recompile/rebuild application after setting it. However, this embedded admin functionality is almost empty inside. We develop a separate service, but it is closed-source at the monent.

**Comment by Osub** [comment]
Is there an open source plan?

**Comment by vbaranov** [comment]
I would suggest to contact with this inquiry through https://www.blockscout.com/#contact-us. I am closing this for now.

**Comment by iw4p** [comment]
> @Osub it is compile-time env variable. You should recompile/rebuild application after setting it. However, this embedded admin functionality is almost empty inside. We develop a separate service, but it is closed-source at the monent.

I set it and recompiled it using `--build` via `docker compose` and still unable to use /admin route. Is there something wrong that I am doing?
