### ISSUE TITLE
Linea: API Request Timeout

### ISSUE THREAD

**Issue by KuanYuLai** [blockscout/blockscout#8098]
*Describe your issue here.*

### Environment
* Elixir Version: 1.14.0
* Erlang Version: 25
* BlockScout Version: v5.2.0-beta

* User Agent: `Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/115.0.0.0 Safari/537.36`

### Steps to reproduce

Request any api with base url `http://explorer.linea.build/api`. For example `http://explorer.linea.build/api?module=block&action=eth_block_number`.

### Expected Behaviour

Should return json rpc result

### Actual Behaviour

API never response, will timeout eventaully.

**Comment by vbaranov** [comment]
Please ask this question in Linea Discord, which can be found here https://goerli.linea.build.
