### ISSUE TITLE
There are many blocks missing

### ISSUE THREAD

**Issue by shellteo** [blockscout/blockscout#8107]
This is our testnet explorer, https://explorer.testnet.mantle.xyz/. Recently we found out that there are some cases of missing blocks. It has been a day so far, and these blocks have not been synchronized to.

### Environment

* Deployment type: Manual
* Elixir & Erlang/OTP versions (`elixir -version`): Erlang/OTP 25 [erts-13.1.1] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [jit] Elixir 1.14.2 (compiled with Erlang/OTP 25)
* Node JS version (`node -v`): v16.16.0
* Operating System: macOS Montery 12.6.5
* Blockscout Version/branch/commit: v5.0.0-beta(https://github.com/mantlenetworkio/blockscout)
* Archive node type && version (Erigon/Geth/Nethermind/Ganache/?): Mantle-Geth

### Expected behaviour
Blocks are synchronized normally and remain continuous

### Actual behaviour
You can take a look at the details through the link below
https://explorer.testnet.mantle.xyz/blocks?block_number=16462020&block_type=Block&items_count=50

<img width="1227" alt="image" src="https://github.com/blockscout/blockscout/assets/16064604/9b8262d4-5f51-44c1-bdc6-98bd81b114bf">
<img width="1285" alt="image" src="https://github.com/blockscout/blockscout/assets/16064604/82e65106-2a00-4614-8d82-ed14684f4af8">

use cast to get missed block: 
```shell
cast bl 16462008 --rpc-url https://rpc.testnet.mantle.xyz/
```
The following is the data obtained: 
```js
baseFeePerGas
difficulty           2
extraData            0xd98301090a846765746889676f312e31352e3133856c696e7578000000000000b5a5af8beb2240c6c02131b5094231bec35f467906138adcb0e0cb6cbd35a5ee112dfac50e86f17fe5bfdd13d94ec46dab35bc84d44aee99b310e1320b6f73d601
gasLimit             30000000
gasUsed              46158
hash                 0x97d0fd1a5e838cf30b991564433c13a620bef26fb0b26b1d504f127db12a4574
logsBloom            0x00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000200001000008000000000000000000000000000000000000000000000000000100000000000000000000008000000000400000000000000000040000000000000000000000000000420000000000000000000000000000000000000000000000000000020100000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000010000000000000000000000000000000000000000000000000000000000000
miner                0x0000000000000000000000000000000000000000
mixHash              0x0000000000000000000000000000000000000000000000000000000000000000
nonce                0x0000000000000000
number               16462008
parentHash           0xe2a9d4b82112a9ca82a053c29d81b0dcbcee374220d4959e74a6c8316df8c957
receiptsRoot         0x26508be0c2f53c4eeb7b4eed0fd3403f5e757afdb13a569ce8d17bda0fd68ff3
sealFields           []
sha3Uncles           0x1dcc4de8dec75d7aab85b567b6ccd41ad312451b948a7413f0a142fd40d49347
size                 781
stateRoot            0x33b8524a57bb29a572f465accc6dd08b2acdb72dce377407dc8507565ce3c8a0
timestamp            1690946526
withdrawalsRoot
totalDifficulty      32924017
transactions:        [
	0x91d55dfcdcda8ff06ace37fc260ed2d3dc1effb7316d88a6bfc1fd47723ad891
]
```

**Comment by iw4p** [comment]
Hi, I checked your chain and [#16462017](https://explorer.testnet.mantle.xyz/block/16462017) is indexed right now. I have a same problem. Did you change anything to fix it?

**Comment by vbaranov** [comment]
Closing since seems the original issue with Mantle explorer indexing has been resolved with updating to the latest backend version.
