### ISSUE TITLE
Kava 10: <Issue Title>

### ISSUE THREAD

**Issue by oirobles** [blockscout/blockscout#8109]
*Describe your issue here.*

bridged Kava WBTC to Polygon WBTC, via satelite bridge. 

Transaction Hash:   0x9531d99932a540583b581c18907e50e9ab8a861c92b815cb21a30b9f5c43fc2f

I have not received fund. Can you Please help me.

### Environment
* Elixir Version: 1.14.5
* Erlang Version: 25
* BlockScout Version: v5.1.5-kava

* User Agent: `Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/115.0.0.0 Safari/537.36`

### Steps to reproduce

*Tell us how to reproduce this issue. If possible, push up a branch to your fork with a regression test we can run to reproduce locally.*

### Expected Behaviour

*Tell us what should happen.*

### Actual Behaviour

*Tell us what happens instead.*

**Comment by vbaranov** [comment]
Kava Blockscout instance is not managed by the Blockscout team. Please ask your question in Kava chain support channel.
