### ISSUE TITLE
Slow response from /txs endpoint

### ISSUE THREAD

**Issue by pustovalov** [blockscout/blockscout#8113]
Hi,

We have recently updated from [5.2.0-beta](https://github.com/blockscout/blockscout/commit/1e2b7eba598653b5276262d50f00cd6d2b037db5) to [5.2.1-beta](https://github.com/blockscout/blockscout/commit/1e2b7eba598653b5276262d50f00cd6d2b037db5)

and noticed performance degradation for pages with transactions

`5.2.1-beta`
https://explorer.aurora.dev/txs?block_number=97989588&index=0&page_number=1&page_size=50&pages_limit=200
![Mainnet Explorer - BlockScout 2023-08-03 17-30-12](https://github.com/blockscout/blockscout/assets/1568885/8289a212-f819-4da4-9ec4-82ffac800d2d)

`5.2.0-beta`
https://explorer.testnet.aurora.dev/txs?block_number=133886161&index=0&page_number=1&page_size=50&pages_limit=200
![Testnet Explorer - BlockScout 2023-08-03 17-31-19](https://github.com/blockscout/blockscout/assets/1568885/26cbf8c1-24af-4d25-8e0e-e38f7729a6f8)

### Environment
* Deployment type (Manual/Docker/Docker-compose): Manual
* Elixir & Erlang/OTP versions (`elixir -version`): 1.14.5-otp-25
* Node JS version (`node -v`): 18.16.1
* Operating System: Alpine Linux
* Blockscout Version/branch/commit: [1e2b7eba](https://github.com/blockscout/blockscout/commit/1e2b7eba598653b5276262d50f00cd6d2b037db5)

### Steps to reproduce

Open page with transactions:
https://explorer.aurora.dev/txs?block_number=97989433&index=5&page_number=1&page_size=50&pages_limit=200

Our fork: https://github.com/aurora-is-near/blockscout

### Expected behaviour

Page with transactions loads as before within two seconds

### Actual behaviour

Page load time reaches 40 seconds

**Comment by vbaranov** [comment]
@pustovalov thank you for the report. Just to clarify the difference between 2 explorer versions is exactly diff between releases, and no other customizations, right? Is it possible to see, are there any differences in `transactions` table schemas between 2 explorers?

**Comment by pustovalov** [comment]
there is some customization, two additional fields for `transactions` table:
```
near_receipt_hash
near_transaction_hash
```

there are no differences between releases in the schema of this table:
https://gist.github.com/pustovalov/f0263e73a27bf574e6f811a72c701aa5

**Comment by pustovalov** [comment]
We recreated the blockscout instance and now everything works well, thx.
