### ISSUE TITLE
Do not automatically refresh the page when there are new blocks

### ISSUE THREAD

**Issue by BigOceanGG** [blockscout/blockscout#8123]
Is there a problem with my settings? When there is a new block, the page will not be automatically refreshed, and the new block can only be seen after a forced refresh，thanks

**Comment by vbaranov** [comment]
@BigOceanGG are there any errros in the Chrome dev console? I suspect there might be errors about websocket in that case.

**Comment by BigOceanGG** [comment]
@vbaranov It seems like it's a browser issue. Chrome can handle it, but it doesn't work on Safari. Maybe it's because I'm using ws, not wss

**Comment by vbaranov** [comment]
It could be the reason, but I am not sure. Do you have a public link to the instance to reproduce the issue?

**Comment by vbaranov** [comment]
Closing due to no response from the author.
