### ISSUE TITLE
Linea: <Issue Title>claim button not showing up

### ISSUE THREAD

**Issue by raivinitkr** [blockscout/blockscout#8127]
*Describe your issue here.*
0xc2427473e874a6e7ff5ded0aa62a246eeb41f60c955842ffb3e5b7e99d4dc3e3
above is my txn hash, I bridged 0.01 linea ETH to ethereum but not showing claim button to claim my eth on ethereum network. please have a look into this.
![Screenshot 2023-08-05 181825](https://github.com/blockscout/blockscout/assets/132645073/23e659ab-19d2-4dc6-a31b-68df9c927579)

### Environment
* Elixir Version: 1.14.0
* Erlang Version: 25
* BlockScout Version: v5.2.0-beta

* User Agent: `Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/115.0.0.0 Safari/537.36`

### Steps to reproduce

*Tell us how to reproduce this issue. If possible, push up a branch to your fork with a regression test we can run to reproduce locally.*

### Expected Behaviour

*Tell us what should happen.*

### Actual Behaviour

*Tell us what happens instead.*

**Comment by vbaranov** [comment]
Please ask this question in Linea Discord, which can be found here https://goerli.linea.build.
