### ISSUE TITLE
BlockScout v5.2.1-beta :: Amount Issue

### ISSUE THREAD

**Issue by SlmnVaival** [blockscout/blockscout#8133]
### Discussed in https://github.com/orgs/blockscout/discussions/8132

<div type='discussions-op-text'>

<sup>Originally posted by **SlmnVaival** August  7, 2023</sup>
Hi, 

The Total Supply of Token is showing too many decimals.
Version what I am using [BlockScout v5.2.1-beta](https://github.com/blockscout/blockscout/releases/tag/v5.2.1-beta)

The new version where codes are deployed 
http://3.74.229.169:4000/token/0xa801b1A7846156d4C81bD188F96bfcb621517611/token-transfers

</div>

**Comment by islishude** [comment]
+1

```
2023-08-07T10:42:55.222 [notice] Application indexer exited: Indexer.Application.start(:normal, []) returned an error: shutdown: failed to start child: Indexer.Supervisor
    ** (EXIT) shutdown: failed to start child: Indexer.Fetcher.TokenTotalSupplyUpdater
        ** (EXIT) an exception was raised:
            ** (ArgumentError) errors were found at the given arguments:

  * 1st argument: out of range

                :erlang.send_after(-12, #PID<0.4934.0>, :update)
                (indexer 5.2.1) lib/indexer/fetcher/token_total_supply_updater.ex:49: Indexer.Fetcher.TokenTotalSupplyUpdater.schedule_next_update/0
                (indexer 5.2.1) lib/indexer/fetcher/token_total_supply_updater.ex:21: Indexer.Fetcher.TokenTotalSupplyUpdater.init/1
                (stdlib 4.0.1) gen_server.erl:848: :gen_server.init_it/2
                (stdlib 4.0.1) gen_server.erl:811: :gen_server.init_it/6
                (stdlib 4.0.1) proc_lib.erl:240: :proc_lib.init_p_do_apply/3
```

**Comment by vbaranov** [comment]
@SlmnVaival  I see 5.2.0 in the footer. Are you really on 5.2.1?

**Comment by vbaranov** [comment]
Closing due to no response from the author.

**Comment by SlmnVaival** [comment]
Hi @vbaranov, It's just a string that's showing in the footer, I'm using the updated version `v5.2.2-beta`
