### ISSUE TITLE
Kava 10: <Issue Title>

### ISSUE THREAD

**Issue by Falkx** [blockscout/blockscout#8144]
*Describe your issue here.*

### Environment
* Elixir Version: 1.14.5
* Erlang Version: 25
* BlockScout Version: v5.1.5-kava

* User Agent: `Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/115.0.0.0 Safari/537.36`

### Steps to reproduce

*Tell us how to reproduce this issue. If possible, push up a branch to your fork with a regression test we can run to reproduce locally.*

### Expected Behaviour

*Tell us what should happen.*

### Actual Behaviour

*Tell us what happens instead.*

**Comment by Falkx** [comment]
Hallo, ich soll Ihnen mitteilen dass diese Transaktion bis jetzt nicht vollständig durch geführt wurde.

Beste Grüße

**Comment by vbaranov** [comment]
Kava Blockscout instance is not managed by the Blockscout team. Please ask your question in Kava chain support channel.
