### ISSUE TITLE
Application Indexer  exited: shutdown

### ISSUE THREAD

**Issue by oswaldindex** [blockscout/blockscout#8154]
When I started  a standard geth(Geth/v1.12.0-stable-e501b3b0), and running a standard blockscout(v5.2.1 beta). I found that it always occur such an log: `Application Indexer  exited: shutdown`. And The blockscout will not follow the new blocks, just stuck.

I complied my blockscout in my own env. And get postgres installed locally.

My config:
export ETHEREUM_JSONRPC_VARIANT=geth
export BLOCK_TRANSFORMER=clique
export ETHEREUM_JSONRPC_HTTP_URL=http://localhost:8545
export ETHEREUM_JSONRPC_WS_URL=ws://localhost:8551
export DATABASE_URL=postgresql://postgres:123456@127.0.0.1:5432/blockscout
export DATABASE_READ_ONLY_API_URL=postgresql://postgres:123456@127.0.0.1:5432/blockscout
export ETHEREUM_JSONRPC_WS_URL=ws://localhost:8551
export ECTO_USE_SSL=false
export CHAIN_ID=1337
export PORT=4000
export ETHEREUM_JSONRPC_TRACE_URL=http://localhost:8545
export DB_HOST=127.0.0.1
export DB_PASSWORD=123456
export DB_PORT=5432
export MIX_ENV=prod
export SECRET_KEY_BASE=ImBxONcBEkcf5n+OR1pJgA1szmAq3N2tramqetfuYiQqS3wpiN1cas/BU/3Kcnh5
export DB_USERNAME=postgres

My env:
Erlang/OTP 25
elixir 1.14.5-otp-25
Ubuntu 11.3.0-1ubuntu1~22.04.1

**Comment by oswaldindex** [comment]
<img width="1503" alt="image" src="https://github.com/blockscout/blockscout/assets/137664710/a5f332d4-e047-47c4-9406-bdf9c1cc7327">
these are the only things i got, and in /logs/pord/indexer.log ,we have:
<img width="943" alt="image" src="https://github.com/blockscout/blockscout/assets/137664710/5f5faa33-b9ce-4cb6-8048-f4d686919d9a">;
But in fact, the local standard geth has lots of blocks that blockscout didn't fetched.

**Comment by oswaldindex** [comment]
And i switch the log level into debug like this:
<img width="716" alt="image" src="https://github.com/blockscout/blockscout/assets/137664710/2772b7b9-a86e-4ff6-a99c-821bb87f7248">
I'm a newbie in elixir and blockscout, i'm not sure if the setting is valid, but there are no further logs printed when the app shutdown.

**Comment by vbaranov** [comment]
Is anything in `logs/prod/error.log`?

**Comment by oswaldindex** [comment]
Actually, there are no error.log being created in /logs/prod .

**Comment by vbaranov** [comment]
@oswaldindex which version of Blockscout are you running?

**Comment by oswaldindex** [comment]
https://github.com/blockscout/blockscout/releases/tag/v5.2.1-beta
this one

**Comment by vbaranov** [comment]
@oswaldindex 

You provided twice:
```
export ETHEREUM_JSONRPC_WS_URL=ws://localhost:8551
```
and the port is unusual for websocket. Ususally, it is 8545/8546. Are you sure you have websocket enabled on this port? Try to unset this env var in order to check, if explorer will launch, because this var is optional, but wrong value can cause the issues.

**Comment by vbaranov** [comment]
Closing due to no response from the author.
