### ISSUE TITLE
Manual Deployment Error: application=indexer fetcher=pending_transaction [error] connection_refused

### ISSUE THREAD

**Issue by aacostarua** [blockscout/blockscout#8161]
*Describe your issue here.*

### Environment

Deployment type (Manual/Docker/Docker-compose): Manual
Elixir & Erlang/OTP versions (elixir -version): 1.14.5-otp-25 (OTP 25.0)
Node JS version (node -v): 20.5.0
Operating System: Ubuntu 20.04.6 LTS (64 bit)
Blockscout Version/branch/commit: latest
Archive node type && version (Erigon/Geth/Nethermind/Ganache/?): parity

### Steps to reproduce

*Tell us how to reproduce this issue.  ❤️ if you can push up a branch to your fork with a regression test we can run to reproduce locally.*

### Expected behaviour

should run the explorer.

### Actual behaviour

2023-08-09T16:35:00.935 application=indexer fetcher=empty_blocks_to_refetch [info] Start sanitizing of empty blocks. Batch size is 100
2023-08-09T16:35:00.938 application=indexer fetcher=empty_blocks_to_refetch [info] Batch of empty blocks is sanitized
2023-08-09T16:35:01.003 application=indexer fetcher=pending_transaction [error] connection_refused
2023-08-09T16:35:02.004 application=indexer fetcher=pending_transaction [error] connection_refused
2023-08-09T16:35:03.007 application=indexer fetcher=pending_transaction [error] connection_refused
2023-08-09T16:35:04.009 application=indexer fetcher=pending_transaction [error] connection_refused

---
Also made sure I'm running OpenEthereum with the recommended flags.

ENV file.:
ETHEREUM_JSONRPC_VARIANT=parity
ETHEREUM_JSONRPC_HTTP_URL=https://bc1.mycryptobox.com/node
DATABASE_URL=postgres://postgres:xxx@127.0.0.1:5432/blockscout
COIN=BIO
MIX_ENV=prod
SECRET_KEY_BASE=xxxxxxxxxxxxxxx

**Comment by vbaranov** [comment]
@aacostarua is `parity_pendingTransactions` method is enabled on the node? Can you try making request to the node with it
```
curl --data '{"method":"parity_pendingTransactions","params":[],"id":1,"jsonrpc":"2.0"}' -H "Content-Type: application/json" -X POST
```
?

**Comment by aacostarua** [comment]
curl --data '{"method":"parity_pendingTransactions","params":[],"id":1,"jsonrpc":"2.0"}' -H "Content-Type: application/json" -X POST http://localhost:8545
{"jsonrpc":"2.0","result":[],"id":1}

curl --data '{"method":"parity_pendingTransactions","params":[],"id":1,"jsonrpc":"2.0"}' -H "Content-Type: application/json" -X POST https://bc1.mycryptobox.com/node
{"jsonrpc":"2.0","result":[],"id":1}

**Comment by aacostarua** [comment]
Here's my node.toml config file:
[parity]
chain = "genesis.json"
base_path = "/home/user1/openethereum"

[network]
port = 30301
#reserved_only = true
#reserved_peers = "reserved.ansi"


[rpc]
port = 8545
apis = ["web3", "eth", "net", "personal", "parity", "traces", "pubsub"]
cors = ["null","localhost:3000","localhost:3001","http://remix.ethereum.org","chrome-search://ae62fc16-c916-4c24-9a36-97f5a850f25c","chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn","moz-extension://01de6db3-7c8c-45f4-99d6-b2a17c734c1a","moz-extension://58a74539-7855-44fc-8f22-95edfb62319d","localhost:4000","https://www.myetherwallet.com/","chrome://extensions/?id=nkbihfbeogaeaoehlefnkodbefgpgknn"]
interface = "all" #external access to rpc
hosts = ["all"]

[websockets]
port = 8546
interface = "all"
apis = ["all"]
hosts = ["all"]
origins = ["all"]

[ipc]
disable = false

[account]
unlock = ["0x8659370f9c3fa10f13b3ed5a148a021e21b90706"]
password = ["node.pwds"]
[mining]
engine_signer = "0x8659370f9c3fa10f13b3ed5a148a021e21b90706"
reseal_max_period = 86400000

**Comment by aacostarua** [comment]
Are the flags --fat-db=on --pruning=archive needed?  Getting Loading config file from node.toml
FatDB resync required
Error: 1
when I run with those flags.

**Comment by aacostarua** [comment]
I'm running with FATDB and pruning archive still getiing no result when I run:

 curl --data '{"method":"parity_pendingTransactions","params":[],"id":1,"jsonrpc":"2.0"}' -H "Content-Type: application/json" -X POST localhost:8545

**Comment by aacostarua** [comment]
When I run attach to the ipc. and run eth:
defaultAccount: undefined,
  defaultBlock: "latest",
  gasPrice: 0,
  hashrate: 0,
  maxPriorityFeePerGas: undefined,
  mining: true,
  pendingTransactions: undefined,
  protocolVersion: "65",
  syncing: false,
  call: function(),
  chainId: function(),
  contract: function(abi),
  createAccessList: function(),
  estimateGas: function(),
  feeHistory: function(),
  fillTransaction: function(),
  filter: function(options, callback, filterCreationErrorCallback),
  getAccounts: function(callback),
  getBalance: function(),
  getBlock: function(),
  getBlockByHash: function(),
  getBlockByNumber: function(),
  getBlockNumber: function(callback),
  getBlockTransactionCount: function(),
  getBlockUncleCount: function(),
  getCode: function(),
  getCoinbase: function(callback),
  getCompilers: function(),
  getGasPrice: function(callback),
  getHashrate: function(callback),
  getHeaderByHash: function(),
  getHeaderByNumber: function(),
  getLogs: function(),
  getMaxPriorityFeePerGas: function(callback),
  getMining: function(callback),
  getPendingTransactions: function(callback),
  getProof: function(),
  getProtocolVersion: function(callback),
  getRawTransaction: function(),
  getRawTransactionFromBlock: function(),
  getStorageAt: function(),
  getSyncing: function(callback),
  getTransaction: function(),
  getTransactionCount: function(),
  getTransactionFromBlock: function(),
  getTransactionReceipt: function(),
  getUncle: function(),
  getWork: function(),
  iban: function(iban),
  icapNamereg: function(),
  isSyncing: function(callback),
  namereg: function(),
  resend: function(),
  sendIBANTransaction: function bound transfer(),
  sendRawTransaction: function(),
  sendTransaction: function(),
  sign: function(),
  signTransaction: function(),
  submitTransaction: function(),
  submitWork: function()

**Comment by aacostarua** [comment]
Fixed by hooking up through IPC path...

**Comment by yasmuru** [comment]
Hi @aacostarua, Can you elaborate on how did you resolve this issue?

**Comment by FournyP** [comment]
Same issue here with Polygon Edge, can you give some details @aacostarua ?

**Comment by haidarabdillah** [comment]
Fixed by hooking up through IPC path...

how to doit?

**Comment by Nexsuperne101** [comment]
I too have this issue. I'm learning Blockscout from notes given to me by a friend that got it working successfully. Unfortunately he is no longer available. An indication on how this was fixed will be much appreciated! 
TIA
