### ISSUE TITLE
MXC zkEVM: coin transfer issue

### ISSUE THREAD

**Issue by camelbaba** [blockscout/blockscout#8175]
Hello,

i have transferred 56000 MXC FROM MXC Mainet to my datadash portfolio but I never received the funds.

could I have these 56000 MXCs transferred back to my MXC Mainet portfolio?

many thanks.
Camel Bait

### Environment

* Backend Version/branch/commit: v1.0.0-beta
* Frontend Version+commit: 
* User Agent: Mozilla/5.0 (iPhone; CPU iPhone OS 16_6 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Mobile/15E148

### Steps to reproduce

*Tell us how to reproduce this issue.  ❤️ if you can push up a branch to your fork with a regression test we can run to reproduce locally.*

### Expected behaviour

*Tell us what should happen.*

### Actual behaviour

*Tell us what happens instead.*

**Comment by vbaranov** [comment]
This chat is for Blockscout related questions. Your question is out of scope, where Blockscout team can help.
