### ISSUE TITLE
verfication of two smart contract with the same bytecode error

### ISSUE THREAD

**Issue by aagbotemi** [blockscout/blockscout#8176]
I deployed a smart contract and verified successfully. When I deployed the same smart contract again but for another purpose, It is giving smart contract verified already because they have the same bytecode. But on getting to the explorer, the new smart contract is not deployed.

**Comment by vbaranov** [comment]
@aagbotemi what do you mean by 
> But on getting to the explorer, the new smart contract is not deployed.
?

Maybe, you can provide screenshots, or the links for beteer understanding the problem?

**Comment by aagbotemi** [comment]
![bbs](https://github.com/blockscout/blockscout/assets/63763418/a3bd1fb5-b0eb-4caa-97cf-ca58cacec66a)
![bbss](https://github.com/blockscout/blockscout/assets/63763418/8643dfea-4fd3-4663-a37b-73f62303be9b)

There is actually a service that rely on the event emitted after deployment, that needs the contract to be verifed, to pick the data. Coming to the web will make the service loose time, as there will be multiple activities carried out by the service

**Comment by aagbotemi** [comment]
@vbaranov please, I am waiting for your feedback

**Comment by aagbotemi** [comment]
@vbaranov this is a top priority for me. I will appreciate any help you can provide to fix this issue.

**Comment by nikitosing** [comment]
@aagbotemi hello, could you please rephrase what is the issue?

**Comment by aagbotemi** [comment]
after deploying a smart contract and I verify it, it will be verified and I can see it on the explorer. When I come to deploy the smart contract again for another use case and now verify it, it will say contract has already been verified, meanwhile checking the explorer, I realise that it's not verified. I believe because the two smart contracts are pointing to the same bytecode.

It is important for me to verify this smart contract at the point of deployment because there is a service that is relying on the event that I emit at the point of deploying this contract.

**Comment by vbaranov** [comment]
@aagbotemi you still can verify and publish the 2nd contract: click the link "Verify & Publish" and verify it.

**Comment by aagbotemi** [comment]
@vbaranov 
the "Verify & Publish" link is on the browser, which will take a longer time for the service using it to get the event, as the service rely on events from verified smart contract.

Also, trying to "Verify & Publish" on the browser, I am getting error "No contract could be verified with provided data", even while putting the flattened code in the input field.
![bva](https://github.com/blockscout/blockscout/assets/63763418/1cdfcc0e-ef9b-428c-93b7-6827743a296b)

**Comment by nikitosing** [comment]
how did you verify the first contract?

**Comment by aagbotemi** [comment]
i verified it in my script
```ts
await run("verify:verify", {
    address: sensorProfile.address,
    constructorArguments: [
      ApplicationAddress,
      PROFILE_URI,
      TIER
    ]
  })
  ```
  
  I tried to verify the second one same way like that, the response was what i shared in the first screenshot

**Comment by aagbotemi** [comment]
I used hardhat-etherscan npm package

**Comment by nikitosing** [comment]
@aagbotemi in cli you tried to verify contract (0xD33..269) which is different from contract (0xD21...dDa) you tried to verify on blockscout

**Comment by aagbotemi** [comment]
@nikitosing @vbaranov 
The cli you saw was the one I deployed last week, below is a screenshot of (0xD33..269) 

![nns](https://github.com/blockscout/blockscout/assets/63763418/99448b37-4590-47ee-8397-4465f61c21be)

**Comment by nikitosing** [comment]
@aagbotemi can you share the link to the smart contract?

**Comment by aagbotemi** [comment]
@nikitosing do you mean my codebase or the deployed link on the explorer?

**Comment by nikitosing** [comment]
@aagbotemi both of them

**Comment by aagbotemi** [comment]
@nikitosing 
This is the codebase: https://github.com/MXCzkEVM/core-contracts/blob/main/contracts/token/MEP803.sol
This is the explorer: https://wannsee-explorer.mxc.com/address/0xD3370101e4E39698FA85ab5d4230fbc4A879a269?tab=contract

**Comment by aagbotemi** [comment]
@nikitosing @vbaranov, please I am waiting for your feedback.

**Comment by rimrakhimov** [comment]
@aagbotemi The reason you cannot manually verify the contract is because the data from codebase is different from the one actually deployed. You can see the difference for the `MEP803.sol` file where the right version is copied from the https://wannsee-explorer.mxc.com/address/0x4B8E85Fad30ba08e11360F66666ed5979078070D?tab=contract

![image](https://github.com/blockscout/blockscout/assets/25086020/9db42925-fa47-423b-b883-26fff5c321eb)

**Comment by rimrakhimov** [comment]
https://wannsee-explorer.mxc.com/address/0xD3370101e4E39698FA85ab5d4230fbc4A879a269?tab=contract - was successfully verified with the code taken from https://wannsee-explorer.mxc.com/address/0x4B8E85Fad30ba08e11360F66666ed5979078070D?tab=contract

**Comment by aagbotemi** [comment]
Thank you for the fix @rimrakhimov, I am trying to replicate the deployment on my end and I am getting "No contract could be verified with provided data" error. My flattened code is attached below. Could you give me the steps you used to verify the contract for me. Thank you

![carbon](https://github.com/blockscout/blockscout/assets/63763418/1ab99d52-fcf1-40a5-a322-3ecd611f161a)

**Comment by rimrakhimov** [comment]
Could you please share the address of the code, you are trying to verify?

**Comment by aagbotemi** [comment]
This is it @rimrakhimov 0x389A8Ba516c716488dc7B5833c266Fd6bA57d99B

**Comment by aagbotemi** [comment]
Hi @rimrakhimov, I want to ask if you found any solution for me.

**Comment by rimrakhimov** [comment]
I've used the standard-json verification with the following file:
```json
{
    "language": "Solidity",
    "sources": {
      "contracts/token/IMEP803.sol": {
        "content": "\/\/ SPDX-License-Identifier: UNLICENSED\r\npragma solidity ^0.8.18;\r\n\r\ninterface IMEP803 {\r\n    \/\/\/ @dev This event gets emitted when the Sensor Profile contract is deployed.\r\n    \/\/\/  The parameters is the address of the application contract and address of the contract deployed\r\n    event SensorProfileDeployed(\r\n        address indexed _sensorProfileContractAddress,\r\n        address indexed _appContractAddress,\r\n        string indexed _sensorProfileURI\r\n    );\r\n\r\n    \/\/\/ @dev this function returns the tier for the profile\r\n    function getTier() external view returns (string memory);\r\n}\r\n"
      },
      "contracts/token/MEP803.sol": {
        "content": "\/\/ SPDX-License-Identifier: UNLICENSED\r\npragma solidity ^0.8.18;\r\n\r\nimport \".\/IMEP803.sol\";\r\n\r\n\/**\r\n * @title SensorProfile\r\n * @author Abiodun Awoyemi\r\n * @notice This contract manages the device profiles of a sensor network.\r\n *\/\r\ncontract SensorProfile is IMEP803 {\r\n    \/\/ State variables\r\n    address public owner;\r\n    address public appContractAddress;\r\n    bytes32 public profileURIHash;\r\n    string public tier;\r\n\r\n    \/**\r\n     * @notice Constructor function to initialize a new `SensorProfile` instance.\r\n     * @param _appContractAddress The address of the lpwan contract.\r\n     * @param _sensorProfileURI The metadata link of the sensor profile.\r\n     * @param _tier The tier of the sensor profile.\r\n     *\/\r\n    constructor(address _appContractAddress, string memory _sensorProfileURI, string memory _tier) {\r\n        appContractAddress = _appContractAddress;\r\n        owner = msg.sender;\r\n\r\n        bytes32 _profileURIHash = hashString(_sensorProfileURI);\r\n\r\n        profileURIHash = _profileURIHash;\r\n        tier = _tier;\r\n\r\n        emit SensorProfileDeployed(address(this), _appContractAddress, _sensorProfileURI);\r\n    }\r\n\r\n    function getTier() external view returns (string memory) {\r\n        return tier;\r\n    }\r\n\r\n    \/**\r\n     * @dev Returns the keccak256 hash of the input metadata link string\r\n     * @param _profileURI The metadata link string to be hashed\r\n     *\/\r\n    function hashString(string memory _profileURI) internal pure returns (bytes32 profileURIHash_) {\r\n        profileURIHash_ = keccak256(abi.encodePacked(_profileURI));\r\n    }\r\n}\r\n"
      }
    },
    "settings": {
      "optimizer": {
        "enabled": true,
        "runs": 10000
      }
    }
  }
  
```

**Comment by aagbotemi** [comment]
Thank you so much @rimrakhimov. It worked. Can you kindly share with me the command that you used to generate this json file. I used this command 'solc --combined-json ast,metadata contracts/token/MEP803.sol > contracts/token/MEP803.json' and I got an empty json file.

**Comment by aagbotemi** [comment]
I have been able verify using the "standard-json verification". Thank you @rimrakhimov @vbaranov @nikitosing
