### ISSUE TITLE
HAQQ Testedge2: <Issue Title>

### ISSUE THREAD

**Issue by aprendiz96** [blockscout/blockscout#8190]
*Describe your issue here.*

### Environment

* Backend Version/branch/commit: v5.2.0-beta
* Frontend Version+commit: 
* User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/113.0.0.0 Safari/537.36 OPR/99.0.0.0

### Steps to reproduce

*Tell us how to reproduce this issue.  ❤️ if you can push up a branch to your fork with a regression test we can run to reproduce locally.*

### Expected behaviour

*Tell us what should happen.*

### Actual behaviour

*Tell us what happens instead.*  there are many problems in the explore og blocks i did many tx but they don´t appear

**Comment by sl1depengwyn** [comment]
HAQQ Testedge2 Blockscout instance is not managed by the Blockscout team. Please ask your question in HAQQ Testedge2 support channel.
