### ISSUE TITLE
: <Issue Title>

### ISSUE THREAD

**Issue by Dray-art** [blockscout/blockscout#8191]
*Describe your issue here.*
I can't add the chain to my metamask wallet

### Environment
* Elixir Version: 1.14.0
* Erlang Version: 25
* BlockScout Version: 

* User Agent: `Mozilla/5.0 (Linux; Android 11; Infinix X689C) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/107.0.0.0 Mobile Safari/537.36`

### Steps to reproduce

*Tell us how to reproduce this issue. If possible, push up a branch to your fork with a regression test we can run to reproduce locally.*

### Expected Behaviour

*Tell us what should happen.*

### Actual Behaviour

*Tell us what happens instead.*

**Comment by sl1depengwyn** [comment]
Have you set up `CHAIN_ID` env?

**Comment by Dray-art** [comment]
Yes I think I did

**Comment by vbaranov** [comment]
@Dray-art what error do you see in Chrome dev console when trying to add che chain to MetaMask?

**Comment by vbaranov** [comment]
Closing due to no response from the author.
