### ISSUE TITLE
HAQQ Testedge2: <$ISLM not receiving in Haqq wallet>

### ISSUE THREAD

**Issue by mohammadyasirumrani26** [blockscout/blockscout#8193]
*Describe your issue here.*

### Environment

* Backend Version/branch/commit: v5.2.0-beta
* Frontend Version+commit: 
* User Agent: Mozilla/5.0 (Linux; Android 11; TECNO KF6k Build/RP1A.200720.011; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/115.0.5790.166 Mobile Safari/537.36

### Steps to reproduce

*Tell us how to reproduce this issue.  ❤️ if you can push up a branch to your fork with a regression test we can run to reproduce locally.*

### Expected behaviour

*Tell us what should happen.*

### Actual behaviour

*Tell us what happens instead.*

**Comment by vbaranov** [comment]
This chat is for Blockscout related questions. Your question is out of scope, where Blockscout team can help.
