### ISSUE TITLE
Base Mainnet: <Base to Binance wallet transaction not received>

### ISSUE THREAD

**Issue by abhi177321** [blockscout/blockscout#8194]
I have transfer base network to binance wallet and not able seen the transaction in binance. How can i retrive this base network fund to my meta wallet again ?

![Screenshot 2023-08-13 122210](https://github.com/blockscout/blockscout/assets/142141123/acdcc280-3726-4093-ba50-ae96a95ea9cf)

**Comment by vbaranov** [comment]
This chat is for Blockscout related questions. Your question is out of scope, where Blockscout team can help. Please exchange support.

**Comment by abhi177321** [comment]
Hi how can I retrieve my fund back to base wallet
