### ISSUE TITLE
Setup Admin panel for development - Want to contribute

### ISSUE THREAD

**Issue by JABirchall** [blockscout/blockscout#8195]
Having trouble getting admin panel working in dev, I had an idea to moved the ENV variables for labeling addresses to the database manageable by the admin panel. 

The `CUSTOM_CONTRACT_ADDRESSES_{tag}`

But I cant find any documentation on running the admin panel to start working on this feature.

### Environment

* Deployment type (Manual/Docker/Docker-compose): Docker compose up -d --build
* Elixir & Erlang/OTP versions (`elixir -version`): Included in docker
* Node JS version (`node -v`): Included in docker
* Operating System: Windows
* Blockscout Version/branch/commit: 5.2.1
* Archive node type && version (Erigon/Geth/Nethermind/Ganache/?): geth private testnet

### Steps to reproduce

I have set set ADMIN_PANEL_ENABLED=true in envs but its unclear and undocumented how to access the admin panel

### Expected behaviour

I would have thought setting the admin ENV would make the admin routes accessable

### Actual behaviour

Some documention on this so that developers can contribute to admin panel features?

**Comment by JABirchall** [comment]
Update: 

i managed to get the admin setup to load, turns out only env variables from the files in the envs directory get loaded into the docker container?

But now its requesting the recovery code from apps/explorer/priv/.recovery

This file doesnt exist?

**Comment by lewtran** [comment]
> 

Same here, I posted a question before but it's closed with no support

**Comment by JABirchall** [comment]
Update:
I found where this is created in docker.

The file is created in `/lib/explorer-5.2.1/priv/.recovery`
not `/apps/explorer/priv/.recovery` which is where the docs say it is.
