### ISSUE TITLE
Wrong transaction URL on Goerli in notification email

### ISSUE THREAD

**Issue by 0xtzData** [blockscout/blockscout#8196]
https://eth-goerli.blockscout.com/
Backend: [v5.2.1-beta.+commit.baff2721](https://github.com/blockscout/blockscout/commit/baff2721)

![Image](https://user-images.githubusercontent.com/108135703/260322976-60ed4205-3de3-4ffd-be23-718030d8dff2.png)

Details URL is valid, transaction URL leads there

https://url1021.blockscout.com/ls/click?upn=hILKh6wwlmud8xpmlIqKmjeDZqWAmn5Fq9xBPHMWdlb7GVlJFpygWU7SS241hGWzFPtZRDT7-2B1UBdBlequjzZf8uVNa9u8bzBpjDgOKhrkfYTFZk5u6Yqyqxh3bUEFStcF8z3gq5I4uTVAukJ-2F5yHttmVQ5f7MXYew1poy-2BZSIg-3Dl1FQ_iizkmtLLVyn5vyZHcUHxVX9N3ZuWy-2B7LqUPCE-2BIhhfahW0fxBbsfVwRRj1704Q2e6SaVsB-2Fkl8gDT8f0ul5POnnq4td8TupSe2p3V8sCg-2Ff-2BgaaSB4H5SSZlpsi4xzbQ07m-2Fnvi1CRctTAyr-2F5WNU-2F9ex79eTP20q6YK60nUwUjq-2FTUdjGSuKtucpY4MNhw-2FW3OWePkonA5g8ZCE7Bc5wQ4yQYPe0D2ffOXgqQWuq0F-2BY7SeB-2Bli231scHrNbuhLDDAPCt8tTyXZkicltX6dwJHcuIinUNjIc3quLh9Ew4LnzqdHFklRVqEutKuWS-2BuTuMajMnjKxTFp7aBOz6cnmw-3D-3D

Chrome tells me that cert is invalid.

**Comment by vbaranov** [comment]
#7957

**Comment by nikitosing** [comment]
@0xtzData Hello, could you check please if the issue reproducible now?
