### ISSUE TITLE
HAQQ Testedge2: <Issue Title>

### ISSUE THREAD

**Issue by Ajeet786786** [blockscout/blockscout#8200]
I want claim of ISLM coins but not received*Describe your issue here.*

### Environment

* Backend Version/branch/commit: v5.2.0-beta
* Frontend Version+commit: 
* User Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/115.0.0.0 Safari/537.36

### Steps to reproduce

*Tell us how to reproduce this issue.  ❤️ if you can push up a branch to your fork with a regression test we can run to reproduce locally.*

### Expected behaviour

*Tell us what should happen.*

### Actual behaviour

*Tell us what happens instead.*

**Comment by vbaranov** [comment]
This chat is for Blockscout related questions. Your question is out of scope, where Blockscout team can help.
