### ISSUE TITLE
GraphQL Specific Query and /API Not Working (Nginx 503 Bad Gateway)

### ISSUE THREAD

**Issue by aacostarua** [blockscout/blockscout#8205]
### Steps to reproduce

*Tell us how to reproduce this issue.  ❤️ if you can push up a branch to your fork with a regression test we can run to reproduce locally.*

GraphQL Query:
{
  address(hash: "0x5756DF88D31FD6c0A74C3194Db6ca5E8AB02Aa3F") {
    tokenTransfers(first:5, tokenContractAddressHash: "0xEBfb85Dc08Ac893137Ef22658d5C493F498B53b2") {
      edges {
        node {
          blockNumber
          createdContractAddressHash
          fromAddressHash
          toAddressHash
          gas
          hash
        }
      }
    }
  }
}

Also:

I cant access the API on my Blockscout. I get 502 bad gateway when I try to go to the /api. I know ETH JSON-RPC works from CURL. All other pages work for me on Blockscout.

### Expected behaviour

Trying to create a function query the users wallet address, return token transfers from a given tokenContractAddress associated with that wallet address.  

### Actual behaviour

Schema doesn't work with address.  I'd use GraphQL if the schema allowed for selecting an address within the tokenTransfers this would also solve my problem, so I could get just the TXs with the toAddressHash or fromAddressHash equals the users wallet address.  Nor does /API work.

**Comment by aacostarua** [comment]
I cant access the API on my Blockscout. I get 502 bad gateway when I try to go to the /api.  I know ETH JSON-RPC works from CURL.

**Comment by vbaranov** [comment]
@aacostarua how did you run Blockscout?

**Comment by aacostarua** [comment]
@vbaranov Manual Deployment using https. Followed your intructions.  https://bc4.mycryptobox.com .  .ENV im using to run:
ETHEREUM_JSONRPC_VARIANT=parity
ETHEREUM_JSONRPC_JSON_RPC_TRANSPORT=ipc
export IPC_PATH=/home/user1/openethereum/jsonrpc.ipc
DATABASE_URL=postgres://postgres:xxx@127.0.0.1:5432/blockscout
COIN=ECO
MIX_ENV=prod
SECRET_KEY_BASE=xxx
INDEXER_DISABLE_BLOCK_REWARD_FETCHER=true
ECTO_USE_SSL=true
ETHEREUM_JSONRPC_HTTP_URL=https://bc4.mycryptobox.com/xxx

I had to run export DATABASE_URL=postgres://postgres:xxx@127.0.0.1:5432/blockscout and export INDEXER_DISABLE_BLOCK_REWARD_FETCHER=true for it to run, maybe its not reading all the ENV vars from the .ENV file?

**Comment by vbaranov** [comment]
Ah, I see. Actually, you cannot get token transfers from the address via GraphQL. It is known current limitation and will be fixed in the frame of https://github.com/blockscout/blockscout/issues/7976.

**Comment by aacostarua** [comment]
@vbaranov Great!  I'm assuming the API not working on my Blockscout is a seperate issue.  Is there anything I can do to debug that?

**Comment by aacostarua** [comment]
I prefer to use GraphQL queries anyway, but I guess good to know why API isn't working.

**Comment by vbaranov** [comment]
@aacostarua what version of Blockscout do you use? I am asking because `ETHEREUM_JSONRPC_JSON_RPC_TRANSPORT ` is quite outdated. I recommend using the latest version of the application and changing the name of this env var to `ETHEREUM_JSONRPC_TRANSPORT`, if you want to use IPC transport. You can find [here](https://docs.blockscout.com/for-developers/information-and-settings/env-variables) the actual list of env vars compatible with the latest version of the application.

**Comment by aacostarua** [comment]
@vbaranov Using latest verison.  Great replacing the variable name now! Thanks for the catch.

**Comment by aacostarua** [comment]
Still getting the 503 gateway error when trying to connect to the /API after switching the name to ETHEREUM_JSONRPC_TRANSPORT .

**Comment by vbaranov** [comment]
If
```
API_V1_READ_METHODS_DISABLED=true
API_V1_WRITE_METHODS_DISABLED=true
```

are not set, `/api` and `/api-docs` pages are enabled by default. Maybe, you have some additional routing on nginx, which prevents exposing those paths?

**Comment by aacostarua** [comment]
@vbaranov Yup its now responding!  I had a conflicting redirect for /api.  Thanks again man!!  API now working.
