### ISSUE TITLE
No prices UI

### ISSUE THREAD

**Issue by Toni-d-e-v** [blockscout/blockscout#8221]
*Describe your issue here.*

### Environment

* Deployment type (Manual/Docker/Docker-compose):Docker-compose
* Elixir & Erlang/OTP versions (`elixir -version`):Docker-compose
* Node JS version (`node -v`):Docker-compose
* Operating System:ubuntu-22
* Blockscout Version/branch/commit:does not say so
* Archive node type && version (Erigon/Geth/Nethermind/Ganache/?):Geth
![image](https://github.com/blockscout/blockscout/assets/62844491/2f954564-bf20-4b81-9f6f-fa2aa62ddf9b)
But I need to have prices, I have added in the env folder:
COIN=AVES
EXCHANGE_RATES_COIN=aves
EXCHANGE_RATES_COINMARKETCAP_COIN_ID= 24329
EXCHANGE_RATES_SOURCE= coin_market_cap
EXCHANGE_RATES_COINMARKETCAP_API_KEY= ...
DISABLE_TOKEN_EXCHANGE_RATE=false
TOKEN_EXCHANGE_RATE_INTERVAL=60s

**Comment by vbaranov** [comment]
@Toni-d-e-v currently, Blockscout fetches native coin prices from cryptocompare API, and it seems, there is no token AVES there:
```
curl "https://min-api.cryptocompare.com/data/histoday?fsym=AVES&limit=1&tsym=USD"
{"Response":"Error","Message":"There is no data for the symbol AVES .","HasWarning":false,"Type":2,"RateLimit":{},"Data":{},"ParamWithError":"fsym"}%
```
