### ISSUE TITLE
Getting error message:429 Too Many Requests on API call

### ISSUE THREAD

**Issue by kmcrae2023** [blockscout/blockscout#8226]
This API call:
https://blockscout.com/etc/mainnet/api?module=account&action=balance&address=0x1517FecDc6281306F1567636291D5Cf1C0d59578

starting giving this error a couple days ago:
{"message":"429 Too Many Requests","result":null,"status":"0"}

I'm also getting this error:
Connection Lost, click to load newer transactions

in the web block explorer. here's a sample link:
https://blockscout.com/etc/mainnet/address/0x1517FecDc6281306F1567636291D5Cf1C0d59578

### Environment
* BlockScout Version: v4.1.8-beta

* User Agent: `Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/115.0.0.0 Safari/537.36`

### Steps to reproduce

check these 2 links and you'll see the errors I describe above.

https://blockscout.com/etc/mainnet/api?module=account&action=balance&address=0x1517FecDc6281306F1567636291D5Cf1C0d59578

https://blockscout.com/etc/mainnet/address/0x1517FecDc6281306F1567636291D5Cf1C0d59578

### Expected Behaviour

I should be able to see the balance of this wallet but getting errors last couple days. This has been working quite well up until a coulpe days ago.

### Actual Behaviour

I see the errors I mention above.

thanks!

**Comment by uglydrummer** [comment]
Same issue here, but with:
https://blockscout.com/etc/mainnet/api?module=account&action=balance&address=0x21Dd5c13925407e5bCec3f27aB11a355a9Dafbe3

After several tries finally returns "OK", but immediately reverts back to "429" again.

**Comment by iraykhel** [comment]
Same issue, please fix.
