### ISSUE TITLE
Ethereum Classic: tranjection pending

### ISSUE THREAD

**Issue by krishnasinghsuyal** [blockscout/blockscout#8227]
withdrawal my etc mining token date 6 aug 2023 until now not received?

### Environment
* Elixir Version: 1.13.1
* Erlang Version: 24
* BlockScout Version: v4.1.8-beta

* User Agent: `Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/115.0.0.0 Mobile Safari/537.36`

### Steps to reproduce

*Tell us how to reproduce this issue. If possible, push up a branch to your fork with a regression test we can run to reproduce locally.*

### Expected Behaviour

*Tell us what should happen.*

### Actual Behaviour

*Tell us what happens instead.*

**Comment by krishnasinghsuyal** [comment]
![Screenshot_2023-08-17-11-04-00-881_com android chrome](https://github.com/blockscout/blockscout/assets/133041063/33132123-88ae-47ed-954b-d5c51bce5b46)

**Comment by vbaranov** [comment]
Please ask your question in Ethereum Classic Discord https://discord.com/invite/dwxb6nf
