### ISSUE TITLE
when I deploy a contract using the factory i am not able to  view code tabs and not able to verify the contract which deploy using factory contract

### ISSUE THREAD

**Issue by nisarg2023** [blockscout/blockscout#8230]
not display code tabs in the factory contract but it displays in parent contract
not able to verify the factory contract 

![Screenshot from 2023-08-17 14-54-26](https://github.com/blockscout/blockscout/assets/125979189/efe7c50e-2e65-4778-a2cc-c62462f4fdaf)

**Comment by vbaranov** [comment]
@nisarg2023 does the node, you connected Blockscout with, support tracing module? And does Blockscout fetches internal transactions from the node? More info is [here](https://docs.blockscout.com/for-developers/information-and-settings/node-tracing-json-rpc-requirements#enable-tracing-to-fetch-internal-transactions).

**Comment by nisarg2023** [comment]
@vbaranov it does not fetch internal transactions from the node

**Comment by nisarg2023** [comment]
@igorbarinov can I use Ganache for the deployment of the factory contract and get an internal transaction 
if yes, can you tell me the steps to use Ganache?

**Comment by vbaranov** [comment]
@nisarg2023 it is not currently possible with Ganache. You should run any of these: Erigon, Reth, Geth, Nethermind, OpenEthereum with enabled tracing module.

**Comment by nisarg2023** [comment]
now in a change in my node rpc and I successfully get an internal transaction
but no I get to face a new problem verifying the contract

Contracts that self destruct in their constructors have no contract code published and cannot be verified.
Displaying the init data provided of the creating transaction.
![Screenshot from 2023-08-22 18-05-14](https://github.com/blockscout/blockscout/assets/125979189/ab954ee6-1939-46f2-a5c9-d59e08463a11)
![Uploading Screenshot from 2023-08-22 18-06-47.png…]()
