### ISSUE TITLE
ERC20 Token Transaction Value issue

### ISSUE THREAD

**Issue by farazahmadvaival** [blockscout/blockscout#8232]
i have build and run the blockscout on EC2. mostly data looks ok except one issue. ERC20 token transaction is showing value without dividing by decimals.

http://3.74.229.169:4000/tx/0x6e33b42e606c09603aeb57f61e701371ae0197c8978d0da7d1b0c605bdd2527f

### Environment

* Deployment type (Manual/Docker/Docker-compose): Manual
* Elixir & Erlang/OTP versions (`elixir -version`): 1.24
* Node JS version (`node -v`): 16
* Operating System: Ubuntu
* Blockscout Version/branch/commit: maaster
* Archive node type && version (Erigon/Geth/Nethermind/Ganache/?): parity

### Steps to reproduce

*Tell us how to reproduce this issue.  ❤️ if you can push up a branch to your fork with a regression test we can run to reproduce locally.*

https://github.com/farazahmadvaival/blockscout

### Expected behaviour

It should display the Token Transfer value as divided by contract decimals.

### Actual behaviour

It is displaying the token transfer value as full amount.

**Comment by vbaranov** [comment]
@farazahmadvaival the link to tx is broken. Is Blockscout instance still working? Are you on the latest commit of master branch? Or what version do you use?

**Comment by farazahmadvaival** [comment]
unfortunately, I have cleaned the data from the database. and now started the blockscout again to reindex the data. i will update here once all data will be synced.

**Comment by vbaranov** [comment]
@farazahmadvaival how is it going now?

**Comment by farazahmadvaival** [comment]
after I wiped out all data and restarted the indexer, every thing start working fine.
