### ISSUE TITLE
Zora: <Issue Title>I can't witdraw my ethereum

### ISSUE THREAD

**Issue by Kreator2502** [blockscout/blockscout#8245]
*Describe your issue here.*

### Environment

* Backend Version/branch/commit: 
* Frontend Version+commit: 
* User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/116.0.0.0 Safari/537.36

### Steps to reproduce

*Tell us how to reproduce this issue.  ❤️ if you can push up a branch to your fork with a regression test we can run to reproduce locally.*

### Expected behaviour

*Tell us what should happen.*

### Actual behaviour

*Tell us what happens instead.*

**Comment by Kreator2502** [comment]
I CAN'T WITHDRAWALS MY ETH

**Comment by sl1depengwyn** [comment]
This chat is for Blockscout related questions. Your question is out of scope, where Blockscout team can help.
