### ISSUE TITLE
Carbon Devnet: <Issue Title> devnet network not connecting

### ISSUE THREAD

**Issue by thecryptoseries** [blockscout/blockscout#8246]
*Describe your issue here.*

### Environment
* Elixir Version: 1.13.4
* Erlang Version: 25
* BlockScout Version: 

* User Agent: `Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/116.0.0.0 Safari/537.36`

### Steps to reproduce

*Tell us how to reproduce this issue. If possible, push up a branch to your fork with a regression test we can run to reproduce locally.*

### Expected Behaviour

*Tell us what should happen.*

### Actual Behaviour

*Tell us what happens instead.*

**Comment by thecryptoseries** [comment]
Chain id 9791 shows " Could not fetch chain ID. Is your RPC URL correct?

**Comment by vbaranov** [comment]
This Blockscout instance is not managed by Blockscout team. Please ask in Carbon Devnet chain support.
