### ISSUE TITLE
Faucet Issue

### ISSUE THREAD

**Issue by hassangujjarofficial** [blockscout/blockscout#8266]
*faucet via this link is not being claimed     https://testedge2.haqq.network/   .*

### Environment

* Deployment type (Manual/Docker/Docker-compose):
* Elixir & Erlang/OTP versions (`elixir -version`):
* Node JS version (`node -v`):
* Operating System:
* Blockscout Version/branch/commit:
* Archive node type && version (Erigon/Geth/Nethermind/Ganache/?):

### Steps to reproduce

*You should visit site or link*

### Expected behaviour

*It should work properly and fast*

### Actual behaviour

*faucet via this link is not being claimed.*

**Comment by vbaranov** [comment]
HAQQ Blockscout instance is not managed by the Blockscout team. Please ask your question in HAQQ chain support channel.
