### ISSUE TITLE
ZetaChain: rpc is down

### ISSUE THREAD

**Issue by piweidong** [blockscout/blockscout#8267]
*Describe your issue here.*

### Environment

* Backend Version/branch/commit: v5.2.2-beta.+commit.e9b09b4f
* Frontend Version+commit: v1.9.0+5c12230c
* User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/115.0.0.0 Safari/537.36

### Steps to reproduce

*Tell us how to reproduce this issue.  ❤️ if you can push up a branch to your fork with a regression test we can run to reproduce locally.*

### Expected behaviour

*Tell us what should happen.*

### Actual behaviour

*Tell us what happens instead.*

**Comment by vbaranov** [comment]
@piweidong which RPC do you mean exactly? Is it still down?
