### ISSUE TITLE
Support Safe proxy contracts

### ISSUE THREAD

**Issue by nikitosing** [blockscout/blockscout#8271]
Need to add support for safe proxy contracts. Example: https://gnosis.blockscout.com/address/0x73DcE9348a03975415C6Fa5296e71C1ABaE61407?tab=contract

**Comment by vbaranov** [comment]
@nikitosing what do you mean by support? I see proxy and implementation - so the contract recognized as proxy contract.

**Comment by nikitosing** [comment]
@vbaranov Actually, I do not remember, what was the point. Then let's close
