### ISSUE TITLE
Gnosis chain: <Sent funds to wrong address need help >

### ISSUE THREAD

**Issue by cgelinas17** [blockscout/blockscout#8273]
*Describe your issue here.*

### Environment

* Backend Version/branch/commit: v5.2.2-beta.+commit.0f5a1b56
* Frontend Version+commit: v1.9.0+5c12230c
* User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/107.0.0.0 Safari/537.36

### Steps to reproduce

*Tell us how to reproduce this issue.  ❤️ if you can push up a branch to your fork with a regression test we can run to reproduce locally.*

### Expected behaviour

*Tell us what should happen.*

### Actual behaviour

*Tell us what happens instead.*

**Comment by vbaranov** [comment]
This chat is for Blockscout related questions. Your question is out of scope, where Blockscout team can help.
