### ISSUE TITLE
No metadata for NFT on Base

### ISSUE THREAD

**Issue by 0xtzData** [blockscout/blockscout#8278]
Environment: https://base.blockscout.com/

Backend: [v5.2.2-beta.+commit.7348280f](https://github.com/blockscout/blockscout/commit/7348280f)

Frontend: v1.9.0+5c12230c

Steps to reproduce:
1.  Mint any NFT using https://mint.fun/feed/trending on Base
2. Check token metadata

![Image](https://user-images.githubusercontent.com/108135703/262498485-3c7c0591-1fb4-4237-bd8a-967c16f0e50f.png)

**Comment by vbaranov** [comment]
This has been resolved. @0xtzData please check.

**Comment by 0xtzData** [comment]
We've figured out that it's not working reliably and only fetch data sometimes.
We've discussed to try to estimate the possibility of having a dedicated IPFS node for that case or improved timeouts, reopening.
