### ISSUE TITLE
HAQQ Testedge2: <Issue Title>

### ISSUE THREAD

**Issue by Anititheboss** [blockscout/blockscout#8279]
*Describe your issue here.*

### Environment

* Backend Version/branch/commit: v5.2.0-beta
* Frontend Version+commit: 
* User Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/115.0.0.0 Safari/537.36

### Steps to reproduce

*Tell us how to reproduce this issue.  ❤️ if you can push up a branch to your fork with a regression test we can run to reproduce locally.*

### Expected behaviour

*Tell us what should happen.*

### Actual behaviour

*Tell us what happens instead.*
    I didn't receive toke to my haqq wallet

**Comment by vbaranov** [comment]
HAQQ Blockscout instance is not managed by the Blockscout team. Please ask your question in HAQQ chain support channel.
