### ISSUE TITLE
Puppynet Testnet: <Issue Title>

### ISSUE THREAD

**Issue by akashi199701** [blockscout/blockscout#8286]
*Describe your issue here.*

### Environment

* Backend Version/branch/commit: v5.2.2-beta.+commit.e9b09b4f
* Frontend Version+commit: v1.9.0+5c12230c
* User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/116.0.0.0 Safari/537.36

### Steps to reproduce

*Tell us how to reproduce this issue.  ❤️ if you can push up a branch to your fork with a regression test we can run to reproduce locally.*

### Expected behaviour

*Tell us what should happen.*

### Actual behaviour

*Tell us what happens instead.*

https://www.shibariumscan.io/ is not working right now. is this something that you guys can fix? thank you. i just tried to look at the website and it seems to be down whenever i search the website

![image](https://github.com/blockscout/blockscout/assets/143063908/ef43c046-6a21-4356-b327-a9d09b75d08e)

**Comment by vbaranov** [comment]
Blockscout team does not manage this instance of Blockscout yet. As far as I can see, it is up now.
