### ISSUE TITLE
values reset when refreshing the page of shibariumscan.io

### ISSUE THREAD

**Issue by steachie** [blockscout/blockscout#8289]
values reset when refreshing the page of shibariumscan.io

### Environment
* Elixir Version: 1.14.0
* Erlang Version: 25
* BlockScout Version: 

* User Agent: `Mozilla/5.0 (iPhone; CPU iPhone OS 16_3_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.3 Mobile/15E148 Safari/604.1`

### Steps to reproduce

- Go to shibariumscan.io
- Check the values of Total transactions and total block for example, and till it increases
- Refresh the page

### Expected Behaviour
The values of Total transactions and total block should increase and multiply after page refresh 

### Actual Behaviour
The values of Total transactions and total block are decreasing and resetting to “t.transactions:9681” “t.blocks:266240” after every refresh of the page

![538CD18C-23BF-44FE-AC7B-16E95D53A21D](https://github.com/blockscout/blockscout/assets/39695682/5c04ccad-b3ec-4420-b6ff-45c7934778e1)

**Comment by vbaranov** [comment]
This is not reproducible with the new Blockscout UI, which was recently installed to Shibarium instance. I am closing this.
