### ISSUE TITLE
HAQQ Testedge2: <Issue Title>

### ISSUE THREAD

**Issue by deadleaves95** [blockscout/blockscout#8299]
*I did not recieve the amount i was supposed to get*

### Environment

* Backend Version/branch/commit: v5.2.0-beta
* Frontend Version+commit: 
* User Agent: Mozilla/5.0 (iPhone; CPU iPhone OS 16_2 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.2 Mobile/15E148 Safari/604.1

### Steps to reproduce

*need to tell the owner that the sum isn't transferred *

### Expected behaviour

*i should be able to recieve the sum in another server*

### Actual behaviour

*owner attempted to send but it did not appear in my server.*

**Comment by vbaranov** [comment]
HAQQ Blockscout instance is not managed by the Blockscout team. Please ask your question in HAQQ chain support channel.
