### ISSUE TITLE
Error after create database, and run blockscout

### ISSUE THREAD

**Issue by ekawibisono** [blockscout/blockscout#8303]
### Environment

* Deployment type (Manual/Docker/Docker-compose): Docker Compose
* Elixir & Erlang/OTP versions (`elixir -version`):
* Node JS version (`node -v`):
* Operating System: Ubuntu 20.04
* Blockscout Version/branch/commit: latest
* Archive node type && version (Erigon/Geth/Nethermind/Ganache/?): Geth

### Steps to reproduce

Hello, I'm having trouble running the command docker compose -f docker-compose-no-build-frontend.yml up on a blockscout section. so when the database creation process, and blockscout is running, suddenly postgress sends an error message as shown. please help to fix it

![image](https://github.com/blockscout/blockscout/assets/22586872/90149e38-622c-4492-bb5b-4604d66c7772)

**Comment by ekawibisono** [comment]
The above problems have been solved, but when moving to the frontend, geth etherum is out of sync on the frontend. is there any error in my .env ?

![image](https://github.com/blockscout/blockscout/assets/22586872/6e632b3d-e8de-4af6-b2f3-eac80560d0d8)

```
# Set of ENVs for local network explorer

# app configuration
NEXT_PUBLIC_APP_PROTOCOL=http
NEXT_PUBLIC_APP_HOST=0.0.0.0
NEXT_PUBLIC_APP_PORT=3000
NEXT_PUBLIC_STATS_API_HOST=http://0.0.0.0:8050/
NEXT_PUBLIC_VISUALIZE_API_HOST=http://0.0.0.0:8050/

# blockchain parameters
NEXT_PUBLIC_NETWORK_NAME=TestPoA
NEXT_PUBLIC_NETWORK_SHORT_NAME=TTS
NEXT_PUBLIC_NETWORK_ID=12120
NEXT_PUBLIC_NETWORK_CURRENCY_NAME=TestPoA
NEXT_PUBLIC_NETWORK_CURRENCY_SYMBOL=TTS
NEXT_PUBLIC_NETWORK_CURRENCY_DECIMALS=18
NEXT_PUBLIC_NETWORK_VERIFICATION_TYPE=mining
NEXT_PUBLIC_NETWORK_RPC_URL=http://geth-node1:9545/

# api configuration
NEXT_PUBLIC_API_BASE_PATH=/
NEXT_PUBLIC_API_HOST=0.0.0.0
NEXT_PUBLIC_API_PROTOCOL=http
NEXT_PUBLIC_API_PORT=3001

# ui config
## homepage
NEXT_PUBLIC_HOMEPAGE_CHARTS=['daily_txs']
## sidebar
NEXT_PUBLIC_FEATURED_NETWORKS=https://raw.githubusercontent.com/blockscout/frontend-configs/dev/configs/featured-networks/eth-goerli.json
## footer
## misc
NEXT_PUBLIC_NETWORK_EXPLORERS=[{'title':'Anyblock','baseUrl':'https://explorer.anyblock.tools','paths':{'tx':'/ethereum/poa/core/transaction','address':'/ethereum/poa/core/address'}}]

# app features
NEXT_PUBLIC_APP_INSTANCE=local
NEXT_PUBLIC_APP_ENV=development
NEXT_PUBLIC_SENTRY_DSN=xxxxxx
#NEXT_PUBLIC_API_SPEC_URL=https://raw.githubusercontent.com/blockscout/blockscout-api-v2-swagger/main/swagger.yaml
#NEXT_PUBLIC_IS_ACCOUNT_SUPPORTED=true
#NEXT_PUBLIC_AUTH_URL=http://localhost:3000
#NEXT_PUBLIC_LOGOUT_URL=https://blockscoutcom.us.auth0.com/v2/logout
```

**Comment by ekawibisono** [comment]
Now i Found the problem in this.
![image](https://github.com/blockscout/blockscout/assets/22586872/9e037bfd-9ac5-470f-a77e-6ef6a4712696)

when i run using vps, url using ip address vps,

any help ? or solution ?

**Comment by ekawibisono** [comment]
in docker logs -f proxy, respone for screenshot this.

![image](https://github.com/blockscout/blockscout/assets/22586872/ebd9cc72-f3bb-402d-a0fa-87c8a76ae4aa)

it's Normal ? or Failed ?

**Comment by vbaranov** [comment]
Let's keep conversation in one place. Answered here https://github.com/blockscout/frontend/discussions/1118.
