### ISSUE TITLE
Quorum: <Issue Title>I made a transfer to a wallet which has up till now have not been seen in the wall. Bellow is the transaction HASH.  0x22bbbbb49a56970480c48f46c33799d630c4a57bf9b1e9897fdacdc385e6aa0d

### ISSUE THREAD

**Issue by mannyO1** [blockscout/blockscout#8306]
*Describe your issue here.*

### Environment
* Elixir Version: 1.13.1
* Erlang Version: 24
* BlockScout Version: 

* User Agent: `Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/116.0.0.0 Safari/537.36`

### Steps to reproduce

*Tell us how to reproduce this issue. If possible, push up a branch to your fork with a regression test we can run to reproduce locally.*

### Expected Behaviour

*Tell us what should happen.*

### Actual Behaviour

*Tell us what happens instead.*

**Comment by mannyO1** [comment]
I made a transfer to a wallet which has up till now have not been seen in the wall. Bellow is the transaction HASH.

0x22bbbbb49a56970480c48f46c33799d630c4a57bf9b1e9897fdacdc385e6aa0d

**Comment by triplexitsme** [comment]
Me too https://puppyscan.shib.io//tx/0xc643d3090e6f3a7caaeae4c09b0395d0180380cfbe39d415e878986899460bd4

**Comment by vbaranov** [comment]
This chat is for Blockscout related questions. Your question is out of scope, where Blockscout team can help.
