### ISSUE TITLE
Kava 10: <Issue Title>. Funds sent to a wallet that does not support kava network

### ISSUE THREAD

**Issue by craigjf1** [blockscout/blockscout#8308]
*Describe your issue here.*
I sent 199.638509 [USDt from a kucoin wallet to a coinbase wallet via kava network.  Coinbase wallet does not support kava network, so I need to either route those funds to another wallet, or they need to be sent back to the kucoin wallet they came from. 

(https://kavascan.com/tx/0x860e06cec176831a83fc50b87c5f5dd9d33f65a8158b5ba00bc9185ce9b66019/state)

Transaction Hash
0x860e06cec176831a83fc50b87c5f5dd9d33f65a8158b5ba00bc9185ce9b66019thank you,

Craig
craigjf1@protonmail.com

### Environment
* Elixir Version: 1.14.5
* Erlang Version: 25
* BlockScout Version: v5.1.5-kava

* User Agent: `Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/116.0.0.0 Safari/537.36`

### Steps to reproduce

*Tell us how to reproduce this issue. If possible, push up a branch to your fork with a regression test we can run to reproduce locally.*

### Expected Behaviour

*Tell us what should happen.*

### Actual Behaviour

*Tell us what happens instead.*

**Comment by vbaranov** [comment]
Kava Blockscout instance is not managed by the Blockscout team. Please ask your question in Kava chain support channel.

**Comment by craigjf1** [comment]
could you give me a link of who to contact for this issue?
