### ISSUE TITLE
Sent coin to wallet that doesn't support kava chain network 

### ISSUE THREAD

**Issue by oaboaba** [blockscout/blockscout#8309]
*Describe your issue here.*
I mistakenly sent  123 usdt erc20 from my kucoin wallet to my trust wallet through kava network not knowing that trust wallet doesn't support kava network can you please send back to kucoin wallet. Thanks for your co-operation 
Ola 
Ifeaboaba@yahoo.com 
Transaction hash
0x9f7d44aa0eb43a03948e3ed9177bae8a8fc9f44c0c3f61f07ae78b68eb555c1a
* Deployment type (Manual/Docker/Docker-compose):
* Elixir & Erlang/OTP versions (`elixir -version`):
* Node JS version (`node -v`):
* Operating System:
* Blockscout Version/branch/commit:
* Archive node type && version (Erigon/Geth/Nethermind/Ganache/?):

### Steps to reproduce

*Tell us how to reproduce this issue.  ❤️ if you can push up a branch to your fork with a regression test we can run to reproduce locally.*

### Expected behaviour

*Tell us what should happen.*

### Actual behaviour

*Tell us what happens instead.*

**Comment by vbaranov** [comment]
Kava Blockscout instance is not managed by the Blockscout team. Please ask your question in Kava chain support channel.
