### ISSUE TITLE
@nisarg2023 did you configure smart-contract verification service https://docs.blockscout.com/for-developers/information-and-settings/smart-contract-verification and connect it to your Blockscout instance?

### ISSUE THREAD

**Issue by nisarg2023** [blockscout/blockscout#8315]
@nisarg2023 did you configure smart-contract verification service https://docs.blockscout.com/for-developers/information-and-settings/smart-contract-verification and connect it to your Blockscout instance?

_Originally posted by @vbaranov in https://github.com/blockscout/blockscout/issues/8272#issuecomment-1689731124_

**Comment by vbaranov** [comment]
See https://github.com/blockscout/blockscout/issues/8316#issuecomment-1695425844
