### ISSUE TITLE
@vbaranov

### ISSUE THREAD

**Issue by nisarg2023** [blockscout/blockscout#8317]
@vbaranov 
But when i comment  This below line works properly
 || Chain.get_address_verified_twin_contract(address_hash).verified_contract  

![image](https://github.com/blockscout/blockscout/assets/125979189/fae77eb1-7191-4866-9d64-e607144eea77)

so it can affect another functionality?

_Originally posted by @nisarg2023 in https://github.com/blockscout/blockscout/issues/8272#issuecomment-1692875985_

**Comment by vbaranov** [comment]
@nisarg2023 please do not open multiple issues on a single topic. Join [Discord](https://discord.com/invite/blockscout) for questions, you have.
