### ISSUE TITLE
Need info as to who to contact for this issue, like a link or something..  Thank you

### ISSUE THREAD

**Issue by craigjf1** [blockscout/blockscout#8333]
*Describe your issue here.*
I sent 199.638509 [USDt from a kucoin wallet to a coinbase wallet via kava network. Coinbase wallet does not support kava network, so I need to either route those funds to another wallet, or they need to be sent back to the kucoin wallet they came from.

(https://kavascan.com/tx/0x860e06cec176831a83fc50b87c5f5dd9d33f65a8158b5ba00bc9185ce9b66019/state)

Transaction Hash
0x860e06cec176831a83fc50b87c5f5dd9d33f65a8158b5ba00bc9185ce9b66019thank you,

**If this is the wrong group to ask please forward me to the appropriate group.**

Craig
[craigjf1@protonmail.com](mailto:craigjf1@protonmail.com)
### Environment

* Deployment type (Manual/Docker/Docker-compose):
* Elixir & Erlang/OTP versions (`elixir -version`):
* Node JS version (`node -v`):
* Operating System:
* Blockscout Version/branch/commit:
* Archive node type && version (Erigon/Geth/Nethermind/Ganache/?):

### Steps to reproduce

*Tell us how to reproduce this issue.  ❤️ if you can push up a branch to your fork with a regression test we can run to reproduce locally.*

### Expected behaviour

*Tell us what should happen.*

### Actual behaviour

*Tell us what happens instead.*

**Comment by vbaranov** [comment]
https://github.com/blockscout/blockscout/issues/8310#issuecomment-1696934429
