### ISSUE TITLE
Sitemap for Google Search

### ISSUE THREAD

**Issue by nikitosing** [blockscout/blockscout#8334]
**Problem:** 
most of the important pages are not indexed by Google (e.g. USDC/BNB token pages)

While we are not going towards server-side rendering, there is an intermediary solution for this: sitemaps (https://developers.google.com/search/docs/crawling-indexing/sitemaps/build-sitemap)

- Sitemap should be available via externally-accessible link
- Sitemap should be updated daily

Sitemap should include:

- all entry-level pages (Transactions, L1>L2, Deposits, Withdrawals, Tokens, Apps, Stats etc)
- all token pages with token data present (e.g.  from coingecko or admin requests)
- top accounts (limit 200)
- all addresses with public tag

**Comment by NikitaSavik** [comment]
https://docs.google.com/spreadsheets/d/1R4r2olC-LqqxUpt-_BEz5D4oopUYqyBOlrCACRpSLEc/edit?usp=sharing - list of all URL templates
