### ISSUE TITLE
Gnosis chain: <HONEYPOT AIRDROP>

### ISSUE THREAD

**Issue by EnceeFinancials** [blockscout/blockscout#8348]
*The following token is among many that are being airdropped to users,*

### Environment

* Backend Version/branch/commit: v5.2.2-beta.+commit.0f5a1b56
* Frontend Version+commit: v1.10.0+ea5c9d58
* User Agent: Mozilla/5.0 (iPhone; CPU iPhone OS 16_6 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko)

### Steps to reproduce

*Tell us how to reproduce this issue.  ❤️ if you can push up a branch to your fork with a regression test we can run to reproduce locally.

honestly speaking I’m not a coder I just wanted to warn everyone of this and begin flagging them as I see this trend increasing heavily, so I’m not sure how to go about it I just wanted to label it as a phishing / honeypot attempt when checked via explorer*

### Expected Behavior 

* ideally, one would be able to trust the information and go claim their air drop or award or swap, the NFT/token promising such*

### Actual behavior 

* If user attempts to claim their reward of the promised cryptocurrency on certain website, it will then ask user to connect their wallet, giving the bad actor authorization to their funds.*

**Comment by vbaranov** [comment]
I suppose it is better to warn Gnosis chain users via [Discord](https://discord.com/invite/gnosischain). This chat is for technical issues about Blockscout explorer.
