### ISSUE TITLE
Stuck in perpetual debug_traceTranscation loop

### ISSUE THREAD

**Issue by JABirchall** [blockscout/blockscout#8356]
A fresh installation of blockscout has become completely hung on on a block and spamming trace calls for blocks.

### Environment

* Deployment type (Manual/Docker/Docker-compose): Docker compose
* Elixir & Erlang/OTP versions (`elixir -version`): Included in docker
* Node JS version (`node -v`): Included in docker
* Operating System: Debian 11
* Blockscout Version/branch/commit: 5.2.1
* Archive node type && version (Erigon/Geth/Nethermind/Ganache/?): Geth

### Steps to reproduce
Unknown

### Expected behaviour

Too not become stuck?

### Actual behaviour
Blockscout has become completely stuck doing a trace on a block and just spamming trace requests for that block and not processing any other blocks or transcations

![](https://i.imgur.com/RA3wsiK.png)

Error log: [error.zip](https://github.com/blockscout/blockscout/files/12478854/error.zip)

**Comment by ekawibisono** [comment]
Can you reset all blockscout and get ethereum?

And delete the data folder in docker-compose which I marked in red in the image below
![image](https://github.com/blockscout/blockscout/assets/22586872/2c52a8bd-71c1-4828-b6b1-50a1c389322e)

**Comment by vbaranov** [comment]
@JABirchall it looks like your Geth node is misconfigured. Those errors are from node's logs. Please follow these suggestions https://stackoverflow.com/questions/51536484/insufficient-funds-for-gas-price-value-using-geth-dev. I am closing this since it is unrelated to Blockscout.

**Comment by ekawibisono** [comment]
@JABirchall Please change this
ETHEREUM_JSONRPC_HTTP_URL=http://host.docker.internal:8545/ To ETHEREUM_JSONRPC_HTTP_URL=http://ipaddressserver:8545/ or url rpc
And this same
ETHEREUM_JSONRPC_TRACE_URL=http://host.docker.internal:8545/ To 
ETHEREUM_JSONRPC_HTTP_URL=http://ipaddressserver:8545/ or url rpc

**Comment by JABirchall** [comment]
But http://host.docker.internal:8545/  is correct no? This is what allows the internal docker apps to access the external Geth?

**Comment by ekawibisono** [comment]
> But http://host.docker.internal:8545/ is correct no? This is what allows the internal docker apps to access the external Geth?

If my configuration uses the VPS Server IP, and even then there is no problem, don't use 0.0.0.0, then it won't work
