### ISSUE TITLE
The CACHE_ADDRESS_WITH_BALANCES_UPDATE_INTERVAL configuration does not work

### ISSUE THREAD

**Issue by jacquelynroberts38** [blockscout/blockscout#8357]
I started the service using docker-cmpose and configured CACHE_ADDRESS_WITH_BALANCES_UPDATE_INTERVAL as "30s", but the total number of addresses queried through /api/v2/stats is still updated every half an hour. The version I use is v5.2.1-beta.

**Comment by jacquelynroberts38** [comment]
Am I using the wrong configuration, so which configuration can I edit to update the total address number of the /api/v2/stats api?

**Comment by vbaranov** [comment]
@jacquelynroberts38 `CACHE_ADDRESS_WITH_BALANCES_UPDATE_INTERVAL` is compile-time env variable. Setting it in runtime will not take effect. Thus, in order to apply new value, you need to add it in build args and re-build docker image.

**Comment by jacquelynroberts38** [comment]
> @jacquelynroberts38 `CACHE_ADDRESS_WITH_BALANCES_UPDATE_INTERVAL` is compile-time env variable. Setting it in runtime will not take effect. Thus, in order to apply new value, you need to add it in build args and re-build docker image.

The problem has been solved, thank you
