### ISSUE TITLE
Kava 10: <Issue Title>

### ISSUE THREAD

**Issue by brady384** [blockscout/blockscout#8366]
I did a transaction almost 24 hours ago and it has not been sent, the receiver has asked to check the transaction hash as the one provided to me is in correct. hash provided: 0x610afe469c9a9d926eb37465e0ee5ff75b8b5a621bf8bbbfe4e4d1c1afa3e444

### Environment
* Elixir Version: 1.14.5
* Erlang Version: 25
* BlockScout Version: v5.1.5-kava

* User Agent: `Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.5.2 Safari/605.1.15`

### Steps to reproduce

*Tell us how to reproduce this issue. If possible, push up a branch to your fork with a regression test we can run to reproduce locally.*

### Expected Behaviour

*Tell us what should happen.*

### Actual Behaviour

*Tell us what happens instead.*

**Comment by vbaranov** [comment]
Kava Blockscout instance is not managed by the Blockscout team. Please ask your question in Kava chain support channel.
