### ISSUE TITLE
Blockscout API - Get token holders list

### ISSUE THREAD

**Issue by Bharathcoorg** [blockscout/blockscout#8369]
How to get list of holders for a token using blockscout API?

**Comment by vbaranov** [comment]
https://docs.blockscout.com/for-users/api/rpc-endpoints/token#get-token-holders-by-contract-address

**Comment by Bharathcoorg** [comment]
With erc721 standard each token have own id. I need this ids.

**Comment by vbaranov** [comment]
This is work in progress in frame of this task https://github.com/blockscout/blockscout/issues/8231. Please subscribe to it.
