### ISSUE TITLE
Gnosis chain: <Issue Title>

### ISSUE THREAD

**Issue by Parfaitmugisha** [blockscout/blockscout#8381]
*Describe your issue here.*

Hello, I sent the USDC from the Gnosis chain, to another Ethereum account of an individual hosted on Binance and the latter did not receive the funds in cryptocurrency, what went wrong?

here are the details of my transactions:
 HASH: 0xafd35a819366b508a1e5711cb10c4aca659e746f1a16153c8ca81d15fc65fff0
 
FROM: 0x1de498918d04B8Bf162210103CDd547f73387B2E
TO: 0x77C5446EA01369B0c01963f63648eD661A9A8700

AMOUNT: 92 xdai

ANOTHER TRANSACTION IS: 
HASH: 0xe0f5b82c0dbd8707a8b06bc718f41d976a818cfc75aadd53466b7862a02b30db

FROM: 0x1de498918d04B8Bf162210103CDd547f73387B2E
TO: 0x77C5446EA01369B0c01963f63648eD661A9A8700
AMOUNT : 312 usdc

**Comment by vbaranov** [comment]
This chat is for Blockscout related questions. Your question is out of scope, where Blockscout team can help.

**Comment by Parfaitmugisha** [comment]
who can  respond to my quetions?
