### ISSUE TITLE
Verification failed

### ISSUE THREAD

**Issue by dazhlord** [blockscout/blockscout#8394]
*Describe your issue here.*

### Environment

* Deployment type (Manual/Docker/Docker-compose):
* Elixir & Erlang/OTP versions (`elixir -version`):
* Node JS version (`node -v`):
* Operating System:
* Blockscout Version/branch/commit:
* Archive node type && version (Erigon/Geth/Nethermind/Ganache/?):

### Steps to reproduce
Tried to deploy&verify contracts in hardhat on kava testnet.
deployed successfully but verification doesn't.
Verify contracts without constructor arguments works successfully, but with arguments doens't.
contracts with constructor arguments can be verified via block explorer.

always get below error.
**NomicLabsHardhatPluginError: The contract verification failed.
Reason: Fail - Unable to verify**

**Comment by ekawibisono** [comment]
CC : @vbaranov @nikitosing

**Comment by vbaranov** [comment]
This issue belongs to the fact, that Kava chain instance doesn't collect internal transactions. Their team is aware about that and working on resolvation.
