### ISSUE TITLE
Optimism: optimize configuration envs

### ISSUE THREAD

**Issue by vbaranov** [blockscout/blockscout#8402]
Currently, there are 10 env vars for configuring Optimism instance. But it looks like the number could be significantly reduced, because most of the data are derived from [SystemConfig](https://specs.optimism.io/protocol/system_config.html) contract:
- it has `startBlock` property, which we can use in order to define required params, which are currently retrieved from `INDEXER_OPTIMISM_L1_BATCH_START_BLOCK `, `INDEXER_OPTIMISM_L1_OUTPUT_ROOTS_START_BLOCK `, `INDEXER_OPTIMISM_L1_DEPOSITS_START_BLOCK `, `INDEXER_OPTIMISM_L1_WITHDRAWALS_START_BLOCK `
- it has `batchInbox` property, which defines `INDEXER_OPTIMISM_L1_BATCH_INBOX` address
- it has `batcherHash` property, which defines `INDEXER_OPTIMISM_L1_BATCH_SUBMITTER` address
- it has `optimismPortal` property, which defines `INDEXER_OPTIMISM_L1_PORTAL_CONTRACT`
- it has `l2OutputOracle` property, which defines `INDEXER_OPTIMISM_L1_OUTPUT_ORACLE_CONTRACT`

Can use https://docs.optimism.io/builders/node-operators/json-rpc#optimism_rollupconfig

**Comment by 0xtrou** [comment]
what is the optimismPortal? is it the contract bridge proxy?

**Comment by InoMurko** [comment]
> what is the optimismPortal? is it the contract bridge proxy?
For example
https://sepolia.etherscan.io/address/0x60377e3cE15dF4CCA24c4beF076b60314240b032
