### ISSUE TITLE
My Account logout issues ?

### ISSUE THREAD

**Issue by Gopal-Gurram** [blockscout/blockscout#8408]
After signing in with my account not able to log out the my account.

getting below errors?

![image](https://github.com/blockscout/blockscout/assets/59303056/9be67799-6bd7-4bcf-82b1-c3fc9c7ed6fb)

I am sharing my account env variables and auth0 callback URL and logout URL.

ACCOUNT_DATABASE_URL=postgresql://postgres:@host.docker.internal:7432/blockscout?ssl=false
ACCOUNT_POOL_SIZE=50
ACCOUNT_AUTH0_DOMAIN=................
ACCOUNT_AUTH0_CLIENT_ID=...................
ACCOUNT_AUTH0_CLIENT_SECRET=............
ACCOUNT_PUBLIC_TAGS_AIRTABLE_URL=
ACCOUNT_PUBLIC_TAGS_AIRTABLE_API_KEY=
ACCOUNT_SENDGRID_API_KEY=
ACCOUNT_SENDGRID_SENDER=
ACCOUNT_SENDGRID_TEMPLATE=
ACCOUNT_CLOAK_KEY=
ACCOUNT_ENABLED=true
ACCOUNT_REDIS_URL=redis://redis_db:6379

and 

![image](https://github.com/blockscout/blockscout/assets/59303056/f2f123ad-b91f-4069-82df-e5012ac5cb5d)

**Comment by vbaranov** [comment]
@Gopal-Gurram it should be:
```
http://127.0.0.1:4000/auth/logout
```
in the allowed logout URLs

**Comment by Gopal-Gurram** [comment]
still the same error and it was redirecting the below URL ,

https://dev-3c5uvx24zuwoigrb.us.auth0.com/v2/logout

**Comment by vbaranov** [comment]
Login works fine at the same time, right? Are you on the latest Blockscout version?

**Comment by vbaranov** [comment]
Apart from [this change](https://github.com/blockscout/blockscout/issues/8408#issuecomment-1709591703) everything looks fine. Did you try to ask in Auth0 support?

**Comment by Gopal-Gurram** [comment]
didn't ask them and I have other issues after my email was verified still getting the popup that resends the email verification link on the header and it will only disappear after I start the blockout again.

**Comment by Gopal-Gurram** [comment]
yes I asked in auth0 community and they said pass the URL like this **returnTo=http://127.0.0.1:4000/auth/logout.** but its not taking in allowed logout URLs.

**Comment by Gopal-Gurram** [comment]
In the below URL:
https://dev-3c5uvx24zuwoigrb.us.auth0.com/v2/logout?client_id=G5Z25TkDUIfqVGuX0oyCTRfVs9ergzcN&returnTo=%3A%2F%2F%2Fauth%2Flogout

after I replace the returnTo=%3A%2F%2F%2Fauth%2Flogout to returnTo=http://127.0.0.1:4000/auth/logout
Logout is working @vbaranov 
But the thing is how to stop encoding the logout URL?

**Comment by vbaranov** [comment]
@Gopal-Gurram try replacing 127.0.0.1 with localhost in the Auth0 dashboard.

**Comment by Gopal-Gurram** [comment]
I am trying with domain also not working @vbaranov

**Comment by vbaranov** [comment]
@Gopal-Gurram could you set `BLOCKSCOUT_HOST=localhost_or_domain`? Will this change what is in `returnTo`?

**Comment by Gopal-Gurram** [comment]
I didn't use anything on that env variable.

**Comment by SurenFTN** [comment]
Hello @Gopal-Gurram  how you solved the issue with access tokens ?

**Comment by Gopal-Gurram** [comment]
We have to use the machine to machine application in Auth0?
