### ISSUE TITLE
HAQQ Testedge2: <Issue Title> I can't receive raffle tickets by clicking facing issue it's showing received but not yet 

### ISSUE THREAD

**Issue by yasirnaseerkhan** [blockscout/blockscout#8412]
![Screenshot_20230908_090533_Haqq](https://github.com/blockscout/blockscout/assets/143736359/873e4a17-12bf-4655-9f29-682ff52d86b0)
![Screenshot_20230908_085716_Haqq](https://github.com/blockscout/blockscout/assets/143736359/bf7d9f68-60fb-415c-8d33-97b22c2f0841)
![Screenshot_20230908_085736_Haqq](https://github.com/blockscout/blockscout/assets/143736359/3c58964d-b79e-42c6-b6fb-a2c3e5d5ca70)
*Describe your issue here.*

### Environment

* Backend Version/branch/commit: v5.2.2-beta
* Frontend Version+commit: 
* User Agent: Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/116.0.0.0 Mobile Safari/537.36

### Steps to reproduce

*Tell us how to reproduce this issue.  ❤️ if you can push up a branch to your fork with a regression test we can run to reproduce locally.*

### Expected behaviour

*Tell us what should happen.*

### Actual behaviour

*Tell us what happens instead.*

**Comment by yasirnaseerkhan** [comment]
Dear admin please solve this issue I can't receive raffle tickets by clicking
Best regards

**Comment by sl1depengwyn** [comment]
HAQQ Blockscout instance is not managed by the Blockscout team. Please ask your question in HAQQ chain support channel.
