### ISSUE TITLE
MXC zkEVM: <Issue Title>

### ISSUE THREAD

**Issue by rchamseddine** [blockscout/blockscout#8420]
*Describe your issue here.*
I have two transactions that seem cannot pass the committing
transaction hash! 0x560d438fbe8cab06013870ac4c6515ba1325c419f61ad67a10f5b661a954f06a
and 0xc049a1e7dcfa6d41f5793ccf11efd73cf44ce9fc4c1c50939dce6ed7df85f138

### Environment

* Backend Version/branch/commit: 
* Frontend Version+commit: 
* User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/116.0.0.0 Safari/537.36 Edg/116.0.1938.69

### Steps to reproduce

*Tell us how to reproduce this issue.  ❤️ if you can push up a branch to your fork with a regression test we can run to reproduce locally.*

### Expected behaviour

*Tell us what should happen.*

### Actual behaviour

*Tell us what happens instead.*

**Comment by sl1depengwyn** [comment]
MXC zkEVM Blockscout instance is not managed by the Blockscout team. Please ask your question in MXC zkEVM chain support channel.
