### ISSUE TITLE
Public Goods Network: <Issue Title>

### ISSUE THREAD

**Issue by atama345** [blockscout/blockscout#8425]
*0.0549 ETH value Amount of Ethereum in my account (0x0aAdaA54b39CB6762184Ea2C57b3cF03CEba6d64) is not received *

**Description of issue-**
I am transferred 0.0549 Eth from PGN network to Ethereum network on August-21-2023 23:12:21 PM +05:30 UTC but till now it is not received.
Transaction hash for the same is https://explorer.publicgoods.network/tx/0xeff78b408a449f0dbd08f6b07c6ccfcc084a28936752f89ebed17791a3100317
screenshot for the same is Tx is uploaded below:-
![Screenshot (164)](https://github.com/blockscout/blockscout/assets/111719718/424b6e10-f3bd-4fcd-b83a-22cf4d254e93)

**Comment by vbaranov** [comment]
This chat is for Blockscout-related questions. Your question is out of scope, where the Blockscout team can help. Try to ask in Public Goods Network support channel.
