### ISSUE TITLE
INDEXER_MEMORY_LIMIT=50Gb bring ignored

### ISSUE THREAD

**Issue by dreadedhamish** [blockscout/blockscout#8434]
I'm a few hours into indexing for the first time - so sorry if this is expected behaviour or a noob mistake.

I've added the INDEXER_MEMORY_LIMIT= variable to my .env file. Even though the docs indicate that either of these are valid I've tried both:
INDEXER_MEMORY_LIMIT=50Gb
INDEXER_MEMORY_LIMIT=50

Regardless of what it's set to my RAM usage sits between 2.5 and 3.2GB.

It is happily using 25-40 cores, but wont grab any more RAM (80GB spare)

### Environment

* Deployment type : docker-compose
* Operating System: manjaro
* Blockscout Version/branch/commit: latest - 5.2.1
* Archive node type && version : Erigon

### Steps to reproduce

Fresh docker-compose install (uses Latest - 5.2.1)
Add variable to env file

### Expected behaviour

Uses more than 3GB - I'm led to beleive this because the recommendation for Ethereum is 30GB.

### Actual behaviour

RAM usage sites between 2.5 and 3.2 GB

**Comment by sl1depengwyn** [comment]
Probably the app do not need more, you can try to tune `_BATCH_SIZE` and `_CONCURRENCY` variables from https://docs.blockscout.com/for-developers/information-and-settings/env-variables#indexer-management, then the app may use more memory and index faster

**Comment by dreadedhamish** [comment]
> Probably the app do not need more, you can try to tune `_BATCH_SIZE` and `_CONCURRENCY` variables from https://docs.blockscout.com/for-developers/information-and-settings/env-variables#indexer-management, then the app may use more memory and index faster

Thanks. Yeah I think it's functioning correctly - recently it hit 5GB. I think I was just confused because of the recommendation of 30GB for ethereum.
