### ISSUE TITLE
Why are there so many queries

### ISSUE THREAD

**Issue by 0xcary** [blockscout/blockscout#8453]
According to AWS monitoring, Blockscout sends too many requests to the database. For more details, see the image below. I would greatly appreciate it if you could clarify and help me identify the problem.
<img width="1781" alt="image" src="https://github.com/blockscout/blockscout/assets/96516143/a8f4d22a-8907-469e-a122-bc6cf7e7b81a">

query：
`SELECT b0."number", b0."hash" FROM "blocks" AS b0 WHERE ((b0."consensus" = ?) AND b0."number" = ANY($1))`

So I have two questions: First, why are there so many requests, and secondly, what can be done to optimize to reduce the amount of requests?

### Environment

* Deployment type (Manual/Docker/Docker-compose):
* Elixir & Erlang/OTP versions (`elixir -version`): Elixir 1.13.0 (compiled with Erlang/OTP 24)
* Node JS version (`node -v`): v17.9.1
* Operating System: Amazon Linux 2
* Blockscout Version/branch/commit: v5.2.1-beta
* Archive node type && version (Erigon/Geth/Nethermind/Ganache/?):Geth

**Comment by vbaranov** [comment]
@0xcary this query is used in API endpoint `getblockreward`. Looks like someone is heavily using exposed API endpoint. You have an option to disable the API endpoints via `API_V1_READ_METHODS_DISABLED=true`. It is compile-time env variable. This should be done before the compilation from source or building docker image (this depends on the way, you deploy explorer).

**Comment by 0xcary** [comment]
Resolved, thanks!
