### ISSUE TITLE
Bahamut: <Issue Title>

### ISSUE THREAD

**Issue by YULIIA8919** [blockscout/blockscout#8460]
*Опишите свой вопрос здесь.*

### Окружающая среда
* Версия Elixir: 1.13.4
* Версия Эрланг: 24
* Версия BlockScout: 1.0

* Пользовательский агент: `Mozilla / 5.0 ( Linux; Android 13; SM-A137F ) AppleWebKit / 537.36 ( KHTML, как Gecko ) Chrome / 114.0.5735.196 Мобильный Safari /537.37

### Шаги для воспроизведения

*Расскажите нам, как воспроизвести этот вопрос. Если возможно, подтолкните ветку к вилке с помощью регрессионного теста, который мы можем запустить для локального воспроизведения.*

### Ожидаемое поведение

*Расскажите нам, что должно произойти.*

### Фактическое поведение

*Расскажите нам, что происходит вместо этого.*

**Comment by YULIIA8919** [comment]
Не пришли FTN которые отправляла с казино как мне их вернуть?

**Comment by sl1depengwyn** [comment]
This chat is for Blockscout related questions. Your question is out of scope, where Blockscout team can help.
