### ISSUE TITLE
ERC-4337 token must be detected as a contract

### ISSUE THREAD

**Issue by 0xtzData** [blockscout/blockscout#8490]
Backend: [v5.2.2-beta.+commit.b4c0ab85](https://github.com/blockscout/blockscout/commit/b4c0ab85)

Frontend: [v1.11.1](https://github.com/blockscout/frontend/tree/v1.11.1)

Token: https://eth.blockscout.com/address/0x5FF137D4b0FDCD49DcA30c7CF57E578a026d2789

Etherscan token: https://etherscan.io/address/0x5FF137D4b0FDCD49DcA30c7CF57E578a026d2789

![Image](https://github.com/blockscout/blockscout/assets/108135703/5eb60699-16f9-4f34-b5e4-724457128bd2)

Actual result: It's EOA
Expected result: ERC-4337 must be recognized as a contract

**Comment by vbaranov** [comment]
We have no issues with detecting ERC-4337 as contracts.
