### ISSUE TITLE
Indexer validation fail for a new EVM compatible blockchain

### ISSUE THREAD

**Issue by tonylkc** [blockscout/blockscout#8498]
We have a new launching chain that is compatible with EVM and their Json RPC. But we are not able to point out what is the issue when we try to use Blockscout. We got this error when we first start the server:

`2023-09-20T13:59:19.127 application=indexer fetcher=block_catchup first_block_number=351831 last_block_number=351822 step=import [error] failed to validate: [#Ecto.Changeset<action: nil, changes: %{consensus: true, difficulty: Decimal.new("0"), gas_limit: Decimal.new("1000000000"), gas_used: Decimal.new("0"), hash: %Explorer.Chain.Hash{byte_count: 32, bytes: <<249, 3, 41, 250, 5, 94, 87, 247, 162, 31, 139, 217, 209, 188, 161, 47, 138, 169, 84, 100, 161, 207, 61, 159, 227, 97, 113, 46, 232, 122, 41, 132>>}, miner_hash: %Explorer.Chain.Hash{byte_count: 20, bytes: <<219, 115, 123, 168, 113, 214, 228, 35, 159, 235, 85, 146, 213, 159, 48, 189, 118, 211, 33, 137>>}, number: 351831, parent_hash: %Explorer.Chain.Hash{byte_count: 32, bytes: <<249, 3, 41, 250, 5, 94, 86, 247, 18, 90, 26, 145, 34, 18, 71, 98, 79, 221, 103, 175, 242, 152, 192, 191, 125, 138, 76, 196, 133, 156, 142, 76>>}, size: 358, timestamp: ~U[2023-09-20 09:50:20.000000Z], total_difficulty: Decimal.new("0")}, errors: [nonce: {"is invalid", [type: Explorer.Chain.Hash.Nonce, validation: :cast]}], data: #Explorer.Chain.Block<>, valid?: false>, #Ecto.Changeset<action: nil, changes: %{consensus: true, difficulty: Decimal.new("0"), gas_limit: Decimal.new("1000000000"), gas_used: Decimal.new("0"), hash: %Explorer.Chain.Hash{byte_count: 32, bytes: <<249, 3, 41, 250, 5, 94, 86, 247, 18, 90, 26, 145, 34, 18, 71, 98, 79, 221, 103, 175, 242, 152, 192, 191, 125, 138, 76, 196, 133, 156, 142, 76>>}, miner_hash: %Explorer.Chain.Hash{byte_count: 20, bytes: <<219, 115, 123, 168, 113, 214, 228, 35, 159, 235, 85, 146, 213, 159, 48, 189, 118, 211, 33, 137>>}, number: 351830, parent_hash: %Explorer.Chain.Hash{byte_count: 32, bytes: <<249, 3, 41, 250, 5, 94, 85, 247, 10, 109, 77, 231, 46, 27, 240, 51, 92, 192, 197, 202, 34, 243, 149, 6, 84, 111, 160, 220, 149, 210, 186, 7>>}, size: 358, timestamp: ~U[2023-09-20 09:50:10.000000Z], total_difficulty: Decimal.new("0")}, errors: [nonce: {"is invalid", [type: Explorer.Chain.Hash.Nonce, validation: :cast]}], data: #Explorer.Chain.Block<>, valid?: false>, #Ecto.Changeset<action: nil, changes: %{consensus: true, difficulty: Decimal.new("0"), gas_limit: Decimal.new("1000000000"), gas_used: Decimal.new("0"), hash: %Explorer.Chain.Hash{byte_count: 32, bytes: <<249, 3, 41, 250, 5, 94, 85, 247, 10, 109, 77, 231, 46, 27, 240, 51, 92, 192, 197, 202, 34, 243, 149, 6, 84, 111, 160, 220, 149, 210, 186, 7>>}, miner_hash: %Explorer.Chain.Hash{byte_count: 20, bytes: <<219, 115, 123, 168, 113, 214, 228, 35, 159, 235, 85, 146, 213, 159, 48, 189, 118, 211, 33, 137>>}, number: 351829, parent_hash: %Explorer.Chain.Hash{byte_count: 32, bytes: <<249, 3, 41, 250, 5, 94, 84, 247, 119, 2, 218, 124, 88, 48, 158, 75, 164, 53, 71, 180, 221, 3, 68, 22, 176, 60, 241, 220, 33, 233, 24, 124>>}, size: 358, timestamp: ~U[2023-09-20 09:50:00.000000Z], total_difficulty: Decimal.new("0")}, errors: [nonce: {"is invalid", [type: Explorer.Chain.Hash.Nonce, validation: :cast]}], data: #Explorer.Chain.Block<>, valid?: false>, #Ecto.Changeset<action: nil, changes: %{consensus: true, difficulty: Decimal.new("0"), gas_limit: Decimal.new("1000000000"), gas_used: Decimal.new("0"), hash: %Explorer.Chain.Hash{byte_count: 32, bytes: <<249, 3, 41, 250, 5, 94, 84, 247, 119, 2, 218, 124, 88, 48, 158, 75, 164, 53, 71, 180, 221, 3, 68, 22, 176, 60, 241, 220, 33, 233, 24, 124>>}, miner_hash: %Explorer.Chain.Hash{byte_count: 20, bytes: <<219, 115, 123, 168, 113, 214, 228, 35, 159, 235, 85, 146, 213, 159, 48, 189, 118, 211, 33, 137>>}, number: 351828, parent_hash: %Explorer.Chain.Hash{byte_count: 32, bytes: <<249, 3, 41, 250, 5, 94, 83, 247, 3, 161, 251, 152, 181, 72, 19, 112, 92, 230, 132, 191, 193, 114, 6, 201, 225, 129, 35, 33, 62, 79, 28, 4>>}, size: 358, timestamp: ~U[2023-09-20 09:49:50.000000Z], total_difficulty: Decimal.new("0")}, errors: [nonce: {"is invalid", [type: Explorer.Chain.Hash.Nonce, validation: :cast]}], data: #Explorer.Chain.Block<>, valid?: false>, #Ecto.Changeset<action: nil, changes: %{consensus: true, difficulty: Decimal.new("0"), gas_limit: Decimal.new("1000000000"), gas_used: Decimal.new("0"), hash: %Explorer.Chain.Hash{byte_count: 32, bytes: <<249, 3, 41, 250, 5, 94, 83, 247, 3, 161, 251, 152, 181, 72, 19, 112, 92, 230, 132, 191, 193, 114, 6, 201, 225, 129, 35, 33, 62, 79, 28, 4>>}, miner_hash: %Explorer.Chain.Hash{byte_count: 20, bytes: <<219, 115, 123, 168, 113, 214, 228, 35, 159, 235, 85, 146, 213, 159, 48, 189, 118, 211, 33, 137>>}, number: 351827, parent_hash: %Explorer.Chain.Hash{byte_count: 32, bytes: <<249, 3, 41, 250, 5, 94, 82, 247, 157, 154, 178, 209, 102, 218, 21, 9, 57, 97, 56, 101, 85, 207, 52, 105, 118, 50, 121, 20, 78, 107, 161, 133>>}, size: 358, timestamp: ~U[2023-09-20 09:49:40.000000Z], total_difficulty: Decimal.new("0")}, errors: [nonce: {"is invalid", [type: Explorer.Chain.Hash.Nonce, validation: :cast]}], data: #Explorer.Chain.Block<>, valid?: false>, #Ecto.Changeset<action: nil, changes: %{consensus: true, difficulty: Decimal.new("0"), gas_limit: Decimal.new("1000000000"), gas_used: Decimal.new("0"), hash: %Explorer.Chain.Hash{byte_count: 32, bytes: <<249, 3, 41, 250, 5, 94, 82, 247, 157, 154, 178, 209, 102, 218, 21, 9, 57, 97, 56, 101, 85, 207, 52, 105, 118, 50, 121, 20, 78, 107, 161, 133>>}, miner_hash: %Explorer.Chain.Hash{byte_count: 20, bytes: <<219, 115, 123, 168, 113, 214, 228, 35, 159, 235, 85, 146, 213, 159, 48, 189, 118, 211, 33, 137>>}, number: 351826, parent_hash: %Explorer.Chain.Hash{byte_count: 32, bytes: <<249, 3, 41, 250, 5, 94, 81, 247, 166, 60, 77, 11, 240, 48, 66, 35, 225, 205, 111, 51, 228, 223, 6, 67, 130, 19, 191, 221, 197, 255, 26, 84>>}, size: 358, timestamp: ~U[2023-09-20 09:49:30.000000Z], total_difficulty: Decimal.new("0")}, errors: [nonce: {"is invalid", [type: Explorer.Chain.Hash.Nonce, validation: :cast]}], data: #Explorer.Chain.Block<>, valid?: false>, #Ecto.Changeset<action: nil, changes: %{consensus: true, difficulty: Decimal.new("0"), gas_limit: Decimal.new("1000000000"), gas_used: Decimal.new("0"), hash: %Explorer.Chain.Hash{byte_count: 32, bytes: <<249, 3, 41, 250, 5, 94, 81, 247, 166, 60, 77, 11, 240, 48, 66, 35, 225, 205, 111, 51, 228, 223, 6, 67, 130, 19, 191, 221, 197, 255, 26, 84>>}, miner_hash: %Explorer.Chain.Hash{byte_count: 20, bytes: <<219, 115, 123, 168, 113, 214, 228, 35, 159, 235, 85, 146, 213, 159, 48, 189, 118, 211, 33, 137>>}, number: 351825, parent_hash: %Explorer.Chain.Hash{byte_count: 32, bytes: <<249, 3, 41, 250, 5, 94, 80, 247, 76, 218, 249, 190, 59, 216, 196, 48, 22, 91, 135, 20, 196, 38, 52, 104, 34, 156, 202, 194, 194, 211, 44, ...>>}, size: 358, timestamp: ~U[2023-09-20 09:49:20.000000Z], total_difficulty: Decimal.new("0")}, errors: [nonce: {"is invalid", [type: Explorer.Chain.Hash.Nonce, validation: :cast]}], data: #Explorer.Chain.Block<>, valid?: false>, #Ecto.Changeset<action: nil, changes: %{consensus: true, difficulty: Decimal.new("0"), gas_limit: Decimal.new("1000000000"), gas_used: Decimal.new("0"), hash: %Explorer.Chain.Hash{byte_count: 32, bytes: <<249, 3, 41, 250, 5, 94, 80, 247, 76, 218, 249, 190, 59, 216, 196, 48, 22, 91, 135, 20, 196, 38, 52, 104, 34, 156, 202, 194, 194, 211, 44, 58>>}, miner_hash: %Explorer.Chain.Hash{byte_count: 20, bytes: <<219, 115, 123, 168, 113, 214, 228, 35, 159, 235, 85, 146, 213, 159, 48, 189, 118, 211, 33, 137>>}, number: 351824, parent_hash: %Explorer.Chain.Hash{byte_count: 32, bytes: <<249, 3, 41, 250, 5, 94, 79, 247, 164, 91, 232, 97, 242, 59, 114, 182, 19, 195, 196, 163, 11, 147, 115, 117, 7, 146, 43, 218, 245, 2, ...>>}, size: 358, timestamp: ~U[2023-09-20 09:49:10.000000Z], total_difficulty: Decimal.new("0")}, errors: [nonce: {"is invalid", [type: Explorer.Chain.Hash.Nonce, validation: :cast]}], data: #Explorer.Chain.Block<>, valid?: false>, #Ecto.Changeset<action: nil, changes: %{consensus: true, difficulty: Decimal.new("0"), gas_limit: Decimal.new("1000000000"), gas_used: Decimal.new("0"), hash: %Explorer.Chain.Hash{byte_count: 32, bytes: <<249, 3, 41, 250, 5, 94, 79, 247, 164, 91, 232, 97, 242, 59, 114, 182, 19, 195, 196, 163, 11, 147, 115, 117, 7, 146, 43, 218, 245, 2, 137, 249>>}, miner_hash: %Explorer.Chain.Hash{byte_count: 20, bytes: <<219, 115, 123, 168, 113, 214, 228, 35, 159, 235, 85, 146, (truncated)
2023-09-20T13:59:19.127 fetcher=block_catchup first_block_number=351831 last_block_number=351822 [error] Task #PID<0.5313.0> started from #PID<0.5048.0> terminating
** (stop) exited in: GenServer.call(#PID<0.5095.0>, {:push_back, 351831..351822//-1}, 5000)
    ** (EXIT) no process: the process is not alive or there's no process currently associated with the given name, possibly because its application isn't started
    (elixir 1.14.0) lib/gen_server.ex:1038: GenServer.call/3
    (indexer 5.2.3) lib/indexer/block/catchup/fetcher.ex:274: Indexer.Block.Catchup.Fetcher.push_back/2
    (indexer 5.2.3) lib/indexer/block/catchup/fetcher.ex:211: Indexer.Block.Catchup.Fetcher.fetch_and_import_range_from_sequence/3
    (elixir 1.14.0) lib/task/supervised.ex:89: Task.Supervised.invoke_mfa/2
    (elixir 1.14.0) lib/task/supervised.ex:34: Task.Supervised.reply/4
    (stdlib 4.0.1) proc_lib.erl:240: :proc_lib.init_p_do_apply/3
Function: &:erlang.apply/2
    Args: [#Function<16.70495197/1 in Indexer.Block.Catchup.Fetcher.stream_fetch_and_import/2>, [351831..351822//-1]]`

Since it is not a clone from any existing Ethereum code, we would like Blockscout support in the future. Please kindly help to spot out the cause of the indexer issues. Thank you!

### Environment

* Deployment type (Manual/Docker/Docker-compose): Docker-compose
* Elixir & Erlang/OTP versions (`elixir -version`):
* Node JS version (`node -v`):
* Operating System: Ubuntu 22
* Blockscout Version/branch/commit: master
* Archive node type && version (Erigon/Geth/Nethermind/Ganache/?): Geth

**Comment by sl1depengwyn** [comment]
It seems that there are no `nonce` field in your block structure, however blockscout expects it according to eth json rpc docs https://github.com/orgs/blockscout/projects/8/views/1?filterQuery=roots&pane=issue&itemId=38253523

**Comment by tonylkc** [comment]
> It seems that there are no `nonce` field in your block structure, however blockscout expects it according to eth json rpc docs https://github.com/orgs/blockscout/projects/8/views/1?filterQuery=roots&pane=issue&itemId=38253523

Thanks, but the link is not able to open.

**Comment by sl1depengwyn** [comment]
> > It seems that there are no `nonce` field in your block structure, however blockscout expects it according to eth json rpc docs https://github.com/orgs/blockscout/projects/8/views/1?filterQuery=roots&pane=issue&itemId=38253523
> 
> Thanks, but the link is not able to open.

My bad, comment is updated

**Comment by tonylkc** [comment]
Thank you! problem solved!
