### ISSUE TITLE
token name is not showed in blockscout

### ISSUE THREAD

**Issue by Selva1712098** [blockscout/blockscout#8503]
*Describe your issue here.*

### Environment
* Elixir Version: 1.13.1
* Erlang Version: 24
* BlockScout Version: 

* User Agent: `Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/117.0.0.0 Safari/537.36`

### Steps to reproduce

*Tell us how to reproduce this issue. If possible, push up a branch to your fork with a regression test we can run to reproduce locally.*

### Expected Behaviour

*Tell us what should happen.*

### Actual Behaviour

*Tell us what happens instead.*

**Comment by vbaranov** [comment]
@Selva1712098 were any token transfers of this token ever made? Doy ou have a public link to the token?

**Comment by vbaranov** [comment]
Closing due to no response from the author.
