### ISSUE TITLE
Kava 10: Blockchain network not supported by coinbase 

### ISSUE THREAD

**Issue by Pia01pt** [blockscout/blockscout#8507]
I sent usdt from kucoin to coinbase but it's not supported on your network. Please can you help me reclaim the monies 

### Environment
* Elixir Version: 1.14.5
* Erlang Version: 25
* BlockScout Version: v5.1.5-kava

* User Agent: `Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/117.0.0.0 Mobile Safari/537.36`

### Steps to reproduce

*Tell us how to reproduce this issue. If possible, push up a branch to your fork with a regression test we can run to reproduce locally.*

### Expected Behaviour

*Tell us what should happen.*

### Actual Behaviour

*Tell us what happens instead.*

**Comment by vbaranov** [comment]
Kava Blockscout instance is not managed by the Blockscout team. Please ask your question in Kava chain support channel.
