### ISSUE TITLE
Application indexer exited: shutdown,backend exited with code 1

### ISSUE THREAD

**Issue by sameplacewei** [blockscout/blockscout#8516]
*I clone the latest blockscout V5.2.3-beta(bf0c8dc8e11965899a22b0f409de249d52337cbb),deploy the application using the Docker-compose,the following error occurs:

![1695383194683](https://github.com/blockscout/blockscout/assets/33245656/151da6ce-4114-473b-9301-d1db61043fa8)

environment:
        

> ETHEREUM_JSONRPC_HTTP_URL: http://192.168.230.134:7545/
>         ETHEREUM_JSONRPC_TRACE_URL: http://192.168.230.134:7545/
>         ETHEREUM_JSONRPC_WS_URL: ws://192.168.230.134:7545/
>         DATABASE_URL: postgresql://postgres:@192.168.230.135:7432/blockscout
>         CHAIN_ID: '118'
>         API_V2_ENABLED: 'true'
>         MIX_ENV: 'prod'
>         ECTO_USE_SSL: 'false'
>         SECRET_KEY_BASE: '56NtB48ear7+wMSf0IQuWDAAazhpb31qyc7GiyspBP2vh7t5zlCsF5QDv76chXeN'

backend container aways rebooting,can you help me analyze why? Thanks !

**Comment by ekawibisono** [comment]
Hello @sameplacewei , can i see your config envs `common-blockscout.env` ?

i think you can edit `common-blockscout.env`

**Comment by sameplacewei** [comment]
this is my common-blockscout.env
[common-blockscout.env.txt](https://github.com/blockscout/blockscout/files/12705208/common-blockscout.env.txt)

**Comment by ekawibisono** [comment]
Change this ENV
```
ETHEREUM_JSONRPC_HTTP_URL=http://host.docker.internal:8545/
ETHEREUM_JSONRPC_TRACE_URL=http://host.docker.internal:8545/
```
To
```
ETHEREUM_JSONRPC_HTTP_URL=your ip address with http:// or domain rpc you
ETHEREUM_JSONRPC_TRACE_URL=your ip address with http:// or domain rpc you
```

**Comment by sameplacewei** [comment]
I've already configured these two variables in docker-compose.yml
![1695449076614](https://github.com/blockscout/blockscout/assets/33245656/08a18dfa-6c81-4513-a3cb-16b50a231398)

**Comment by ekawibisono** [comment]
> I've already configured these two variables in docker-compose.yml
> 
> ![1695449076614](https://github.com/blockscout/blockscout/assets/33245656/08a18dfa-6c81-4513-a3cb-16b50a231398)
> 
> 

Yes bro, but common-blockscout.env must also be settings

**Comment by sameplacewei** [comment]
I try again,but this problem still exists. 
--------------------------------------------------------------------------
backend         | warning: redefining module ConfigHelper (current version defined in memory)
backend         |   config/config_helper.exs:1
backend         | 
backend         | warning: redefining module ConfigHelper (current version defined in memory)
backend         |   config/config_helper.exs:1
backend         | 
backend         | Starting dependencies..
backend         | Starting repos..
backend         | Create Explorer.Repo database if it doesn't exist
backend         | Create Explorer.Repo.Account database if it doesn't exist
backend         | Running migrations for explorer
backend         | 2023-09-23T10:38:10.893 application=ecto_sql [info] Migrations already up
backend         | Running migrations for explorer
backend         | Success!
backend         | 2023-09-23T10:38:10.905 application=ecto_sql [info] Migrations already up
backend         | warning: redefining module ConfigHelper (current version defined in memory)
backend         |   config/config_helper.exs:1
backend         | 
backend         | warning: redefining module ConfigHelper (current version defined in memory)
backend         |   config/config_helper.exs:1
backend         | 
backend         | 2023-09-23T10:38:14.151 application=que [info] [Que] Booting Que
backend         | 2023-09-23T10:38:14.151 application=que [info] [Que] Booting Server Supervisor for Workers
backend         | 2023-09-23T10:38:14.248 application=explorer [info] tx/per day chart: collect records for txs per day stats
backend         | 2023-09-23T10:38:14.249 application=explorer [info] tx/per day chart: earliest date 2023-09-14 00:00:00Z
backend         | 2023-09-23T10:38:14.249 application=explorer [info] tx/per day chart: latest date 2023-09-14 23:59:59Z
backend         | 2023-09-23T10:38:14.260 application=explorer [info] tx/per day chart: timestamp cannot be converted to min/max blocks, trying to find min/max blocks through a fallback option}
backend         | 2023-09-23T10:38:14.267 application=explorer [warning] tx/per day chart: failed to get min/max blocks through a fallback option}
backend         | 2023-09-23T10:38:14.267 application=explorer [info] tx/per day chart: collect records for txs per day stats
backend         | 2023-09-23T10:38:14.267 application=explorer [info] tx/per day chart: earliest date 2023-09-15 00:00:00Z
backend         | 2023-09-23T10:38:14.267 application=explorer [info] tx/per day chart: latest date 2023-09-15 23:59:59Z
backend         | 2023-09-23T10:38:14.281 application=explorer [info] tx/per day chart: timestamp cannot be converted to min/max blocks, trying to find min/max blocks through a fallback option}
backend         | 2023-09-23T10:38:14.288 application=explorer [warning] tx/per day chart: failed to get min/max blocks through a fallback option}
backend         | 2023-09-23T10:38:14.288 application=explorer [info] tx/per day chart: collect records for txs per day stats
backend         | 2023-09-23T10:38:14.288 application=explorer [info] tx/per day chart: earliest date 2023-09-16 00:00:00Z
backend         | 2023-09-23T10:38:14.288 application=explorer [info] tx/per day chart: latest date 2023-09-16 23:59:59Z
backend         | 2023-09-23T10:38:14.295 application=explorer [info] tx/per day chart: timestamp cannot be converted to min/max blocks, trying to find min/max blocks through a fallback option}
backend         | 2023-09-23T10:38:14.300 application=explorer [warning] tx/per day chart: failed to get min/max blocks through a fallback option}
backend         | 2023-09-23T10:38:14.300 application=explorer [info] tx/per day chart: collect records for txs per day stats
backend         | 2023-09-23T10:38:14.300 application=explorer [info] tx/per day chart: earliest date 2023-09-17 00:00:00Z
backend         | 2023-09-23T10:38:14.300 application=explorer [info] tx/per day chart: latest date 2023-09-17 23:59:59Z
backend         | 2023-09-23T10:38:14.307 application=explorer [info] tx/per day chart: timestamp cannot be converted to min/max blocks, trying to find min/max blocks through a fallback option}
backend         | 2023-09-23T10:38:14.313 application=explorer [warning] tx/per day chart: failed to get min/max blocks through a fallback option}
backend         | 2023-09-23T10:38:14.313 application=explorer [info] tx/per day chart: collect records for txs per day stats
backend         | 2023-09-23T10:38:14.313 application=explorer [info] tx/per day chart: earliest date 2023-09-18 00:00:00Z
backend         | 2023-09-23T10:38:14.313 application=explorer [info] tx/per day chart: latest date 2023-09-18 23:59:59Z
backend         | 2023-09-23T10:38:14.325 application=explorer [info] tx/per day chart: timestamp cannot be converted to min/max blocks, trying to find min/max blocks through a fallback option}
backend         | 2023-09-23T10:38:14.329 application=explorer [warning] tx/per day chart: failed to get min/max blocks through a fallback option}
backend         | 2023-09-23T10:38:14.329 application=explorer [info] tx/per day chart: collect records for txs per day stats
backend         | 2023-09-23T10:38:14.329 application=explorer [info] tx/per day chart: earliest date 2023-09-19 00:00:00Z
backend         | 2023-09-23T10:38:14.330 application=explorer [info] tx/per day chart: latest date 2023-09-19 23:59:59Z
backend         | 2023-09-23T10:38:14.339 application=explorer [info] tx/per day chart: timestamp cannot be converted to min/max blocks, trying to find min/max blocks through a fallback option}
backend         | 2023-09-23T10:38:14.343 application=explorer [warning] tx/per day chart: failed to get min/max blocks through a fallback option}
backend         | 2023-09-23T10:38:14.343 application=explorer [info] tx/per day chart: collect records for txs per day stats
backend         | 2023-09-23T10:38:14.343 application=explorer [info] tx/per day chart: earliest date 2023-09-20 00:00:00Z
backend         | 2023-09-23T10:38:14.343 application=explorer [info] tx/per day chart: latest date 2023-09-20 23:59:59Z
backend         | 2023-09-23T10:38:14.354 application=explorer [info] tx/per day chart: timestamp cannot be converted to min/max blocks, trying to find min/max blocks through a fallback option}
backend         | 2023-09-23T10:38:14.359 application=explorer [warning] tx/per day chart: failed to get min/max blocks through a fallback option}
backend         | 2023-09-23T10:38:14.359 application=explorer [info] tx/per day chart: collect records for txs per day stats
backend         | 2023-09-23T10:38:14.359 application=explorer [info] tx/per day chart: earliest date 2023-09-21 00:00:00Z
backend         | 2023-09-23T10:38:14.360 application=explorer [info] tx/per day chart: latest date 2023-09-21 23:59:59Z
backend         | 2023-09-23T10:38:14.367 application=explorer [info] tx/per day chart: timestamp cannot be converted to min/max blocks, trying to find min/max blocks through a fallback option}
backend         | 2023-09-23T10:38:14.368 application=phoenix [info] Running BlockScoutWeb.Endpoint with cowboy 2.10.0 at 0.0.0.0:4000 (http)
backend         | 2023-09-23T10:38:14.370 application=explorer [warning] tx/per day chart: failed to get min/max blocks through a fallback option}
backend         | 2023-09-23T10:38:14.370 application=explorer [info] tx/per day chart: collect records for txs per day stats
backend         | 2023-09-23T10:38:14.370 application=explorer [info] tx/per day chart: earliest date 2023-09-22 00:00:00Z
backend         | 2023-09-23T10:38:14.371 application=explorer [info] tx/per day chart: latest date 2023-09-22 23:59:59Z
backend         | 2023-09-23T10:38:14.376 application=explorer [info] tx/per day chart: timestamp cannot be converted to min/max blocks, trying to find min/max blocks through a fallback option}
backend         | 2023-09-23T10:38:14.377 application=phoenix [info] Access BlockScoutWeb.Endpoint at ://:4000
backend         | 2023-09-23T10:38:14.379 application=explorer [warning] tx/per day chart: failed to get min/max blocks through a fallback option}
backend         | 2023-09-23T10:38:14.379 application=explorer [info] tx/per day chart: collect records for txs per day stats
backend         | 2023-09-23T10:38:14.379 application=explorer [info] tx/per day chart: records collected [%{date: ~D[2023-09-22], gas_used: 0, number_of_transactions: 0, total_fee: 0}, %{date: ~D[2023-09-21], gas_used: 0, number_of_transactions: 0, total_fee: 0}, %{date: ~D[2023-09-20], gas_used: 0, number_of_transactions: 0, total_fee: 0}, %{date: ~D[2023-09-19], gas_used: 0, number_of_transactions: 0, total_fee: 0}, %{date: ~D[2023-09-18], gas_used: 0, number_of_transactions: 0, total_fee: 0}, %{date: ~D[2023-09-17], gas_used: 0, number_of_transactions: 0, total_fee: 0}, %{date: ~D[2023-09-16], gas_used: 0, number_of_transactions: 0, total_fee: 0}, %{date: ~D[2023-09-15], gas_used: 0, number_of_transactions: 0, total_fee: 0}, %{date: ~D[2023-09-14], gas_used: 0, number_of_transactions: 0, total_fee: 0}]
backend         | 2023-09-23T10:38:14.379 application=explorer [info] tx/per day chart: save records
backend         | 2023-09-23T10:38:14.383 application=explorer [info] tx/per day chart: number of inserted 10
backend         | 2023-09-23T10:38:16.252 [notice] Application indexer exited: shutdown
backend         | Kernel pid terminated (application_controller) ({application_terminated,indexer,shutdown}{"Kernel pid terminated",application_controller,"{application_terminated,indexer,shutdown}"}
backend         | )
backend         | 
backend         | Crash dump is being written to: erl_crash.dump...done
backend exited with code 1
-----------------------------------------------------
My new configuration file 
[common-blockscout.env.txt](https://github.com/blockscout/blockscout/files/12706221/common-blockscout.env.txt)

**Comment by ekawibisono** [comment]
> ## I try again,but this problem still exists.
> ## backend | warning: redefining module ConfigHelper (current version defined in memory)
> backend | config/config_helper.exs:1
> backend |
> backend | warning: redefining module ConfigHelper (current version defined in memory)
> backend | config/config_helper.exs:1
> backend |
> backend | Starting dependencies..
> backend | Starting repos..
> backend | Create Explorer.Repo database if it doesn't exist
> backend | Create Explorer.Repo.Account database if it doesn't exist
> backend | Running migrations for explorer
> backend | 2023-09-23T10:48:48.199 application=ecto_sql [info] Migrations already up
> backend | Running migrations for explorer
> backend | Success!
> backend | 2023-09-23T10:48:48.209 application=ecto_sql [info] Migrations already up
> backend | warning: redefining module ConfigHelper (current version defined in memory)
> backend | config/config_helper.exs:1
> backend |
> backend | warning: redefining module ConfigHelper (current version defined in memory)
> backend | config/config_helper.exs:1
> backend |
> backend | 2023-09-23T10:48:51.260 application=que [info] [Que] Booting Que
> backend | 2023-09-23T10:48:51.260 application=que [info] [Que] Booting Server Supervisor for Workers
> backend | 2023-09-23T10:48:51.354 application=explorer [info] tx/per day chart: collect records for txs per day stats
> backend | 2023-09-23T10:48:51.354 application=explorer [info] tx/per day chart: earliest date 2023-09-14 00:00:00Z
> backend | 2023-09-23T10:48:51.354 application=explorer [info] tx/per day chart: latest date 2023-09-14 23:59:59Z
> backend | 2023-09-23T10:48:51.377 application=explorer [info] tx/per day chart: timestamp cannot be converted to min/max blocks, trying to find min/max blocks through a fallback option}
> backend | 2023-09-23T10:48:51.384 application=explorer [warning] tx/per day chart: failed to get min/max blocks through a fallback option}
> backend | 2023-09-23T10:48:51.384 application=explorer [info] tx/per day chart: collect records for txs per day stats
> backend | 2023-09-23T10:48:51.384 application=explorer [info] tx/per day chart: earliest date 2023-09-15 00:00:00Z
> backend | 2023-09-23T10:48:51.384 application=explorer [info] tx/per day chart: latest date 2023-09-15 23:59:59Z
> backend | 2023-09-23T10:48:51.399 application=explorer [info] tx/per day chart: timestamp cannot be converted to min/max blocks, trying to find min/max blocks through a fallback option}
> backend | 2023-09-23T10:48:51.419 application=explorer [warning] tx/per day chart: failed to get min/max blocks through a fallback option}
> backend | 2023-09-23T10:48:51.419 application=explorer [info] tx/per day chart: collect records for txs per day stats
> backend | 2023-09-23T10:48:51.419 application=explorer [info] tx/per day chart: earliest date 2023-09-16 00:00:00Z
> backend | 2023-09-23T10:48:51.419 application=explorer [info] tx/per day chart: latest date 2023-09-16 23:59:59Z
> backend | 2023-09-23T10:48:51.430 application=explorer [info] tx/per day chart: timestamp cannot be converted to min/max blocks, trying to find min/max blocks through a fallback option}
> backend | 2023-09-23T10:48:51.475 application=explorer [warning] tx/per day chart: failed to get min/max blocks through a fallback option}
> backend | 2023-09-23T10:48:51.475 application=explorer [info] tx/per day chart: collect records for txs per day stats
> backend | 2023-09-23T10:48:51.475 application=explorer [info] tx/per day chart: earliest date 2023-09-17 00:00:00Z
> backend | 2023-09-23T10:48:51.475 application=explorer [info] tx/per day chart: latest date 2023-09-17 23:59:59Z
> backend | 2023-09-23T10:48:51.483 application=explorer [info] tx/per day chart: timestamp cannot be converted to min/max blocks, trying to find min/max blocks through a fallback option}
> backend | 2023-09-23T10:48:51.486 application=phoenix [info] Running BlockScoutWeb.Endpoint with cowboy 2.10.0 at 0.0.0.0:4000 (http)
> backend | 2023-09-23T10:48:51.491 application=phoenix [info] Access BlockScoutWeb.Endpoint at ://:4000
> backend | 2023-09-23T10:48:51.525 application=explorer [warning] tx/per day chart: failed to get min/max blocks through a fallback option}
> backend | 2023-09-23T10:48:51.525 application=explorer [info] tx/per day chart: collect records for txs per day stats
> backend | 2023-09-23T10:48:51.525 application=explorer [info] tx/per day chart: earliest date 2023-09-18 00:00:00Z
> backend | 2023-09-23T10:48:51.525 application=explorer [info] tx/per day chart: latest date 2023-09-18 23:59:59Z
> backend | 2023-09-23T10:48:51.548 application=explorer [info] tx/per day chart: timestamp cannot be converted to min/max blocks, trying to find min/max blocks through a fallback option}
> backend | 2023-09-23T10:48:51.560 application=explorer [warning] tx/per day chart: failed to get min/max blocks through a fallback option}
> backend | 2023-09-23T10:48:51.560 application=explorer [info] tx/per day chart: collect records for txs per day stats
> backend | 2023-09-23T10:48:51.560 application=explorer [info] tx/per day chart: earliest date 2023-09-19 00:00:00Z
> backend | 2023-09-23T10:48:51.560 application=explorer [info] tx/per day chart: latest date 2023-09-19 23:59:59Z
> backend | 2023-09-23T10:48:51.567 application=indexer fetcher=block_catchup missing_block_count=0 shrunk=false [info] Index already caught up.
> backend | 2023-09-23T10:48:51.567 application=indexer fetcher=block_catchup [info] Checking if index needs to catch up in 5000ms.
> backend | 2023-09-23T10:48:51.598 application=explorer [info] tx/per day chart: timestamp cannot be converted to min/max blocks, trying to find min/max blocks through a fallback option}
> backend | 2023-09-23T10:48:51.626 application=explorer [warning] tx/per day chart: failed to get min/max blocks through a fallback option}
> backend | 2023-09-23T10:48:51.626 application=explorer [info] tx/per day chart: collect records for txs per day stats
> backend | 2023-09-23T10:48:51.626 application=explorer [info] tx/per day chart: earliest date 2023-09-20 00:00:00Z
> backend | 2023-09-23T10:48:51.626 application=explorer [info] tx/per day chart: latest date 2023-09-20 23:59:59Z
> backend | 2023-09-23T10:48:51.642 application=explorer [info] tx/per day chart: timestamp cannot be converted to min/max blocks, trying to find min/max blocks through a fallback option}
> backend | 2023-09-23T10:48:51.655 application=explorer [warning] tx/per day chart: failed to get min/max blocks through a fallback option}
> backend | 2023-09-23T10:48:51.655 application=explorer [info] tx/per day chart: collect records for txs per day stats
> backend | 2023-09-23T10:48:51.655 application=explorer [info] tx/per day chart: earliest date 2023-09-21 00:00:00Z
> backend | 2023-09-23T10:48:51.655 application=explorer [info] tx/per day chart: latest date 2023-09-21 23:59:59Z
> backend | 2023-09-23T10:48:51.675 application=explorer [info] tx/per day chart: timestamp cannot be converted to min/max blocks, trying to find min/max blocks through a fallback option}
> backend | 2023-09-23T10:48:51.685 application=explorer [warning] tx/per day chart: failed to get min/max blocks through a fallback option}
> backend | 2023-09-23T10:48:51.685 application=explorer [info] tx/per day chart: collect records for txs per day stats
> backend | 2023-09-23T10:48:51.685 application=explorer [info] tx/per day chart: earliest date 2023-09-22 00:00:00Z
> backend | 2023-09-23T10:48:51.685 application=explorer [info] tx/per day chart: latest date 2023-09-22 23:59:59Z
> backend | 2023-09-23T10:48:51.693 application=explorer [info] tx/per day chart: timestamp cannot be converted to min/max blocks, trying to find min/max blocks through a fallback option}
> backend | 2023-09-23T10:48:51.705 application=explorer [warning] tx/per day chart: failed to get min/max blocks through a fallback option}
> backend | 2023-09-23T10:48:51.705 application=explorer [info] tx/per day chart: collect records for txs per day stats
> backend | 2023-09-23T10:48:51.705 application=explorer [info] tx/per day chart: records collected [%{date: ~D[2023-09-22], gas_used: 0, number_of_transactions: 0, total_fee: 0}, %{date: ~D[2023-09-21], gas_used: 0, number_of_transactions: 0, total_fee: 0}, %{date: ~D[2023-09-20], gas_used: 0, number_of_transactions: 0, total_fee: 0}, %{date: ~D[2023-09-19], gas_used: 0, number_of_transactions: 0, total_fee: 0}, %{date: ~D[2023-09-18], gas_used: 0, number_of_transactions: 0, total_fee: 0}, %{date: ~D[2023-09-17], gas_used: 0, number_of_transactions: 0, total_fee: 0}, %{date: ~D[2023-09-16], gas_used: 0, number_of_transactions: 0, total_fee: 0}, %{date: ~D[2023-09-15], gas_used: 0, number_of_transactions: 0, total_fee: 0}, %{date: ~D[2023-09-14], gas_used: 0, number_of_transactions: 0, total_fee: 0}]
> backend | 2023-09-23T10:48:51.705 application=explorer [info] tx/per day chart: save records
> backend | 2023-09-23T10:48:51.719 application=explorer [info] tx/per day chart: number of inserted 10
> backend | 2023-09-23T10:48:51.744 application=db_connection [info] Postgrex.Protocol (#PID<0.4119.0>) disconnected: ** (DBConnection.ConnectionError) client #PID<0.4794.0> exited
> backend | 2023-09-23T10:48:51.744 application=db_connection [info] Postgrex.Protocol (#PID<0.4122.0>) disconnected: ** (DBConnection.ConnectionError) client #PID<0.4652.0> exited
> backend | 2023-09-23T10:48:51.775 application=indexer fetcher=block_catchup missing_block_count=0 shrunk=false [info] Index already caught up.
> backend | 2023-09-23T10:48:51.775 application=indexer fetcher=block_catchup [info] Checking if index needs to catch up in 5000ms.
> backend | 2023-09-23T10:48:51.894 application=db_connection [info] Postgrex.Protocol (#PID<0.4134.0>) disconnected: ** (DBConnection.ConnectionError) client #PID<0.4967.0> exited
> backend | 2023-09-23T10:48:51.894 application=db_connection [info] Postgrex.Protocol (#PID<0.4129.0>) disconnected: ** (DBConnection.ConnectionError) client #PID<0.4805.0> exited
> backend | 2023-09-23T10:48:51.894 application=db_connection [info] Postgrex.Protocol (#PID<0.4124.0>) disconnected: ** (DBConnection.ConnectionError) client #PID<0.4963.0> exited
> backend | 2023-09-23T10:48:51.894 application=db_connection [info] Postgrex.Protocol (#PID<0.4095.0>) disconnected: ** (DBConnection.ConnectionError) client #PID<0.4968.0> exited
> backend | 2023-09-23T10:48:51.895 application=db_connection [info] Postgrex.Protocol (#PID<0.4117.0>) disconnected: ** (DBConnection.ConnectionError) client #PID<0.4964.0> exited
> backend | 2023-09-23T10:48:51.939 application=indexer fetcher=block_catchup missing_block_count=0 shrunk=false [info] Index already caught up.
> backend | 2023-09-23T10:48:51.939 application=indexer fetcher=block_catchup [info] Checking if index needs to catch up in 5000ms.
> backend | 2023-09-23T10:48:52.067 application=db_connection [info] Postgrex.Protocol (#PID<0.4123.0>) disconnected: ** (DBConnection.ConnectionError) client #PID<0.4977.0> exited
> backend | 2023-09-23T10:48:52.098 application=indexer fetcher=block_catchup missing_block_count=0 shrunk=false [info] Index already caught up.
> backend | 2023-09-23T10:48:52.099 application=indexer fetcher=block_catchup [info] Checking if index needs to catch up in 5000ms.
> backend | 2023-09-23T10:48:52.226 application=db_connection [info] Postgrex.Protocol (#PID<0.4127.0>) disconnected: ** (DBConnection.ConnectionError) client #PID<0.5161.0> exited
> backend | 2023-09-23T10:48:52.226 application=db_connection [info] Postgrex.Protocol (#PID<0.4133.0>) disconnected: ** (DBConnection.ConnectionError) client #PID<0.5348.0> exited
> backend | 2023-09-23T10:48:52.226 application=db_connection [info] Postgrex.Protocol (#PID<0.4130.0>) disconnected: ** (DBConnection.ConnectionError) client #PID<0.5350.0> exited
> backend | 2023-09-23T10:48:52.230 [notice] Application indexer exited: shutdown
> backend | {"Kernel pid terminated",application_controller,"{application_terminated,indexer,shutdown}"}
> backend | Kernel pid terminated (application_controller) ({application_terminated,indexer,shutdown})
> backend |
> backend | Crash dump is being written to: erl_crash.dump...done
> backend exited with code 1
> My new configuration file [common-blockscout.env.txt](https://github.com/blockscout/blockscout/files/12706221/common-blockscout.env.txt)

Is your server using UFW or is there an active firewall? @sameplacewei

**Comment by sameplacewei** [comment]
The system I used was ubuntu20.04. No firewall。Also, the database I have accessed from other machines using client tools is in good condition

**Comment by ekawibisono** [comment]
> The system I used was ubuntu20.04. No firewall。Also, the database I have accessed from other machines using client tools is in good condition

if you have problem you can join on group Discord [Blockscout](https://discord.gg/fytMgXJG)

**Comment by vbaranov** [comment]
@sameplacewei most likely websocket endpoint, which set in `ETHEREUM_JSONRPC_WS_URL` doesn't work. You should unset this env var in that case. Please let me know, if this doesn't resolve the issue. I am closing this for now.
