### ISSUE TITLE
Unreachable URL for vyper.list.json when SMART_CONTRACT_VERIFIER__VYPER__ENABLED is true

### ISSUE THREAD

**Issue by ayushguptacse14** [blockscout/blockscout#8517]
**Describe your issue here.**

The application relies on the `SMART_CONTRACT_VERIFIER__VYPER__ENABLED` environment variable in the `blockscout/docker-compose/envs/common-smart-contract-verifier.env` configuration file. When set to `true`, the application attempts to fetch the JSON file from `https://raw.githubusercontent.com/blockscout/solc-bin/main/vyper.list.json`. However, this URL is currently unreachable.

### Environment

* Deployment type (Manual/Docker/Docker-compose): Docker-compose
* Blockscout Version/branch/commit: [1be25fc](https://github.com/blockscout/blockscout/commit/1be25fcf1b54be481eedcb2349a360fef91fc214)

### Steps to reproduce

1. Set `SMART_CONTRACT_VERIFIER__VYPER__ENABLED` to `true` in `blockscout/docker-compose/envs/common-smart-contract-verifier.env`.
2. Run the application via docker.
3. The application attempts to fetch `https://raw.githubusercontent.com/blockscout/solc-bin/main/vyper.list.json` and fails since the URL is unreachable.

*Note: A sample setup that replicates the issue would be beneficial.*

### Expected behaviour

The application should be able to fetch the `vyper.list.json` file from the given URL without any issues.

### Actual behaviour

The URL `https://raw.githubusercontent.com/blockscout/solc-bin/main/vyper.list.json` is not reachable, causing failures in the application when `SMART_CONTRACT_VERIFIER__VYPER__ENABLED` is set to `true`.

**Comment by sevenzing** [comment]
it's strange that you cannot access `https://raw.githubusercontent.com/blockscout/solc-bin/main/vyper.list.json`.

for me it returns 200:

```
$ curl -I https://raw.githubusercontent.com/blockscout/solc-bin/main/vyper.list.json
HTTP/2 200
...
```

could you please check your internet connection and maybe try to get some other files via `githubusercontent`

**Comment by vbaranov** [comment]
@ayushguptacse14 were you able to resolve the issue?

**Comment by ayushguptacse14** [comment]
It's an issue from my ISP which is Jio, they have blocked [https://raw.githubusercontent.com](https://raw.githubusercontent.com)for some reason. It's working with VPN.
