### ISSUE TITLE
Bahamut: <Issue Title>

### ISSUE THREAD

**Issue by vizapeace** [blockscout/blockscout#8518]
*Describe your issue here.*
how to claim back FTN token that send to wrong network?
### Environment
* Elixir Version: 1.13.4
* Erlang Version: 24
* BlockScout Version: 1.0

* User Agent: `Mozilla/5.0 (iPhone; CPU iPhone OS 15_7_6 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Mobile/15E148`

### Steps to reproduce

*Tell us how to reproduce this issue. If possible, push up a branch to your fork with a regression test we can run to reproduce locally.*

### Expected Behaviour

*Tell us what should happen.*

### Actual Behaviour

*Tell us what happens instead.*

**Comment by vbaranov** [comment]
This chat is for Blockscout-related questions. Your question is out of scope, where the Blockscout team can help.
