### ISSUE TITLE
Token burning was duplicated

### ISSUE THREAD

**Issue by danielbui12** [blockscout/blockscout#8525]
### Environment

* Deployment type: Docker-compose
* Elixir & Erlang/OTP versions: elixir 1.14.5-otp-25, erlang 25.3.2.3
* Node JS version: 18.16.1
* Operating System: linux
* Blockscout Version/branch/commit: v5

### Steps to reproduce

Taking a look at these transactions on Oasys Hub Explorer
- https://explorer.oasys.games/tx/0xdb7825158e195833eac82ee6e2ed2970f53503919b4b86096d812216550a3b29/token-transfers
- https://explorer.oasys.games/tx/0xa38049d09a08d78005f0add54b93249727826ea634e7d83f4ac7df6e02624fc3/token-transfers

### Expected behaviour

The Withdrawal log shouldn't have been considered as the token burning.

### Actual behaviour

The token burning was duplicated when the Logs contains 1 pair of Transfer - Withdrawal events.

**Comment by danielbui12** [comment]
This is because of the smart contract emit 2 event Transfer and Withdrawal.
Normally, it should emit only 1 of them.

**Comment by danielbui12** [comment]
New question: Why Withdrawal event is considered as token burning?

**Comment by sl1depengwyn** [comment]
The reason for this is that logic for WETH like contracts that emits withdrowal and deposit events was taken from contracts like [this](https://explorer.fuse.io/address/0x0BE9e53fd7EDaC9F859882AfdDa116645287C629) and implemented [here](https://github.com/blockscout/blockscout/pull/7653), and this contract do not emit transfer event while withdrawing (check [this](https://explorer.fuse.io/tx/0x4da8addc49956aa317a6e62ba0d242d0b9ba69b73fba3baf45a3547af6054e00) tx)

I think it makes sense actually

> New question: Why Withdrawal event is considered as token burning?
