### ISSUE TITLE
Token_transfers and address_token_balances / address_current_token_balances does not tally

### ISSUE THREAD

**Issue by fazzywuzzy** [blockscout/blockscout#8526]
*Describe your issue here.*
For transactions involving the specific `token_address` = `sample token address`, the sum calculated for a respective address `address_hash` does not tally with the balance obtained from either `address_token_balances` or `address_current_token_balances` table. 

```
SELECT
    SUM(
        CASE
            WHEN token_transfers.to_address_hash = 'sample address hash' THEN amount
            WHEN token_transfers.from_address_hash = 'sample address hash' THEN -amount
            ELSE 0
        END
    ) AS total_amount
FROM
    token_transfers
WHERE
    token_transfers.token_contract_address_hash = 'sample token address'
    AND (token_transfers.to_address_hash = 'sample address hash'
        OR token_transfers.from_address_hash = 'sample address hash;
```

### Environment

* Deployment type (Manual/Docker/Docker-compose): kubernetes
* Elixir & Erlang/OTP versions (`elixir -version`):
Erlang/OTP 24 [erts-12.0.3] [source] [64-bit] [smp:2:1] [ds:2:1:10] [async-threads:1] [jit:no-native-stack], Elixir 1.12.2 (compiled with Erlang/OTP 24)
* Node JS version (`node -v`): v14.17.1
* Operating System: linux
* Blockscout Version/branch/commit: v3.7.3-beta
* Archive node type && version (Erigon/Geth/Nethermind/Ganache/?): geth 

### Steps to reproduce

*Tell us how to reproduce this issue.  ❤️ if you can push up a branch to your fork with a regression test we can run to reproduce locally.*

### Expected behaviour

*Tell us what should happen.*
Amount from token_transfer should tally with address_token_balances table.

### Actual behaviour
Amount from token_transfer does not tally

*Tell us what happens instead.*

**Comment by vbaranov** [comment]
@fazzywuzzy you're using quite old version of the explorer. Could you update to [v5.2.3](https://github.com/blockscout/blockscout/releases/tag/v5.2.3-beta)?

**Comment by vbaranov** [comment]
Closing due to no response from the author.
