### ISSUE TITLE
Create CSS variables using Bootstrap 4

### ISSUE THREAD

**Issue by acravenho** [blockscout/blockscout#853]
Not having compiled assets would help us in creating a GUI for users to define their theme templates within a BlockScout admin panel.

**Comment by arthurra** [comment]
The advantage to using CSS custom properties (variables) is that they can be updated during runtime with javascript. This is not the case with preprocessor variables, which need to be compiled into static values before they can be downloaded to the HTML document. This means that user could select the colors for their theme through the admin UI and see the app update in real-time. Fortunately for us, Bootstrap 4 provides us the CSS custom properties that match the values that are set in the base variables SCSS file 👍. These custom properties are set on the `:root` selector which matches the root element of the document – the `<html>` element – but with higher specificity than the `<html>`selector. 


We can use javascript to set custom property values on the fly by targeting the `documentElement`. This will replace any property already set in the `:root` selector.
```javascript
document.documentElement.style.setProperty('--primary-color', #XXXXXX);
```


The CSS `var()` function by which custom proerties are used also accepts a fallback option that we can use to set the color values back to the default theme in the event that javascript is not available or we need to rely on prepocessor values.
```css
:root {
    --primary-color: #5b389f;
}

.navbar-primary {
    // using a SASS variable as the fallback to the CSS custom property
    background-color: var(--primary-color, #{$primary});
}
```

To make use of CSS custom properties in BlockScout we will need to replace all instances of the theme color SASS vaiables with a `var()` function that includes the apporpriate custom property. Once the CSS is set up, our javascript will need to be aware of what context the app is in – which chain is being observed – and set the custom property values based on what the user has selected in the admin UI.

**Comment by vbaranov** [comment]
Irrelevant due to migration to new UI
