### ISSUE TITLE
My POA chain stops adding new blocks and new blocks are counted as 'pending'.

### ISSUE THREAD

**Issue by aacostarua** [blockscout/blockscout#8559]
### Description

Blockscout is running fine when a new database is setup. After sometime the blockscout gets out of sync and no new blocks from the chain get added to blockscout (they are added as pending which is not true as they have gone through).  It requires me to wipe the database and start over from a fresh one each time. This is now happening daily, not sure what is the work around or fix?

### Type of the installation

Manual from the source code

### Type of the JSON RPC archive node

OpenEthereum

### Type of the chain

L1

### Link to the page

https://bc4.mycryptobox.com/

### Steps to reproduce

Just running the OpenEthereum POA private network with blockscout it gets out of sync and stops working daily now.

### Backend version

latest

### Elixir & Erlang/OTP versions

Elixir 1.14.5 OTP 25

### Operating system

Linux

### Additional information

Console logs appear to be working fine, no errors.  When I go to https://bc4.mycryptobox.com/address/0xEBfb85Dc08Ac893137Ef22658d5C493F498B53b2

I see the recent transactions that have went through but for some reason blockscout shows them as pending?  Not sure why this happening.  Please let me know as I'm relying on blockscout to work for the transactions, and explorer.  Cheers!

**Comment by vbaranov** [comment]
@aacostarua are you sure JSON RPC of the node is still producing logs? Are you connected to websocket endpoint of the node via ETHEREUM_JSONRPC_WS_URL?

**Comment by aacostarua** [comment]
Fixed it was because I was running without fat db on OpenEthereum and changed JSON RPC endpoint to localhost:8545. Thanks!
