### ISSUE TITLE
My account bug "unknown cipher or invalid key size" 

### ISSUE THREAD

**Issue by Dien-DOS** [blockscout/blockscout#8601]
### Description

My account bug "unknown cipher or invalid key size" 
<img width="1335" alt="Screenshot 2023-10-09 at 18 14 35" src="https://github.com/blockscout/blockscout/assets/16808591/77a3a6d4-5b6a-427b-b4ed-bdecdc6a9efb">

### Type of the installation

Docker-compose

### Type of the JSON RPC archive node

Geth

### Type of the chain

L1

### Link to the page

https://doscan.io

### Steps to reproduce

My account bug "unknown cipher or invalid key size" 

### Backend version

v5.2.3

### Frontend version

v1.11.1

### Elixir & Erlang/OTP versions

1.14.5

### Operating system

linux

### Additional information

My account bug "unknown cipher or invalid key size"

**Comment by sl1depengwyn** [comment]
Could you please share the stacktrace that you see below the error?

**Comment by vbaranov** [comment]
@Dien-DOS did you configure ACCOUNT_CLOAK_KEY env variable on backend? Here is the instruction how you can generate it https://hexdocs.pm/cloak_ecto/generate_keys.html#content.

**Comment by vbaranov** [comment]
@Dien-DOS I am closing this issue. Please let me knoe, if the issue is still present.
