### ISSUE TITLE
Live reload on the address token page

### ISSUE THREAD

**Issue by acravenho** [blockscout/blockscout#861]
The user expects to see the token page for an address live reload since most of the app already does this.

**Comment by enea1982** [comment]
sorry there is my transaction on this site blockscout who I can contact?

**Comment by acravenho** [comment]
@enea1982 I don't understand the question, can you please provide more context?

**Comment by enea1982** [comment]
Tokens have been deposited in the mining that you have sent

who can I contact to pick them up?
they have been deposited here

TxHash:
0x690e2d496cd83c1a0c9b3d04f79f39077cdd08f16440a98aa10d7a9b28fa7e55
TxReceipt Status:
Success
Block Height:
6572787 <https://etherscan.io/block/6572787> (138596 Block Confirmations)
TimeStamp:
22 days 16 hrs ago (Oct-24-2018 04:50:17 AM +UTC)
From:
0x003e36550908907c2a2da960fd19a419b9a774b7
<https://etherscan.io/address/0x003e36550908907c2a2da960fd19a419b9a774b7>
To:
0x6b7f09b04961f2cf705c8734057e509c1fe1e423
<https://etherscan.io/address/0x6b7f09b04961f2cf705c8734057e509c1fe1e423>
Value:
1*.*814674640480022309 Ether
Gas Limit:
21000
Gas Used By Transaction:
21000 (100%)
Gas Price:
0*.*000000008 Ether (8 Gwei)
Actual Tx Cost/Fee:
0*.*000168 Ether ($0.03)
Nonce & {Position}:
76685 | {24}

Il giorno gio 15 nov 2018 alle ore 21:59 Andrew Cravenho <
notifications@github.com> ha scritto:
