### ISSUE TITLE
Zora testnet Blockscout does not show WETH among my ERC-20 tokens

### ISSUE THREAD

**Issue by deni64k** [blockscout/blockscout#8612]
### Description

The list of ERC-20 tokens is empty for my account.

https://testnet.explorer.zora.energy/address/0x43464Fe06c18848a2E2e913194D64c1970f4326a?tab=tokens

It should show I have 0.2 WETH.

At the same time it does show WETH balance for other wallets: https://testnet.explorer.zora.energy/address/0x42D2ae193484470FeB0674E6c9f4949b796f5c37?tab=tokens

### Type of the installation

Docker-compose

### Type of the JSON RPC archive node

unknown

### Type of the chain

L2

### Link to the page

https://testnet.explorer.zora.energy/address/0x43464Fe06c18848a2E2e913194D64c1970f4326a?tab=tokens

### Backend version

unknown

### Elixir & Erlang/OTP versions

unknown

**Comment by vbaranov** [comment]
@deni64k I would advise contacting the Zora team directly in order to update backend to the latest 5.2.3 release as their Blockscout instance is managed by them/Conduit and not by the core Blockscout team.
