### ISSUE TITLE
When the transfer is 0, the transaction hash is not displayed in coin-balance-history

### ISSUE THREAD

**Issue by yzh-d** [blockscout/blockscout#8621]
### Description

When the transfer is 0, check the coin-balance-history in the address and the transaction hash will not be displayed.

### Type of the installation

Docker-compose

### Type of the JSON RPC archive node

ganache

### Type of the chain

L1

### Link to the page

https://scan.aries.axiomesh.io/address/0x70997970C51812dc3A010C7d01b50e0d17dc79C8

### Backend version

master

### Frontend version

Self-developed front-end

### Elixir & Erlang/OTP versions

Elixir 1.14.0 (compiled with Erlang/OTP 25)

### Operating system

Linux

### Additional information

<img width="1280" alt="image" src="https://github.com/blockscout/blockscout/assets/30540477/7643bb5f-210a-4085-88ff-c499943c5eb2">

**Comment by yzh-d** [comment]
@nikitosing How to solve this problem or how to explain this phenomenon? Looking forward to your reply

**Comment by nikitosing** [comment]
Hello, this is a bug, thanks for reporting it! It will be fixed soon
