### ISSUE TITLE
The data for gas_prices is wrong

### ISSUE THREAD

**Issue by yzh-d** [blockscout/blockscout#8622]
### Description

 Question one
API: api/v2/stats. The average of the gas_prices field is 1.0e3, but fast is 2002.5 and slow is 1.0e3. I understand that the actual average value should be greater than 1.0e3.
![image](https://github.com/blockscout/blockscout/assets/30540477/70afd2d7-9991-43ba-bbe1-5c9420520582)

 Question two
The result of gas_prices is different from what I expected. In my design, gas_prices will only increase when the number of transactions in a block reaches 200 transactions. However, in the actual test, the number of transactions in each block did not exceed 200. In theory, gas_prices It should be gradually reduced to the minimum of 1000, and it will not rise again. However, it is actually observed that the value of gas_prices will continue to rise. I think this may be related to the calculation logic of gas_prices. What is the reason?

### Type of the installation

Docker-compose

### Type of the JSON RPC archive node

ganache

### Type of the chain

L1

### Backend version

master

### Frontend version

Self-developed front-end

### Elixir & Erlang/OTP versions

Elixir 1.14.0 (compiled with Erlang/OTP 25)

### Operating system

Linux

**Comment by sl1depengwyn** [comment]
1) Here average is more like a median value, so it can be equal to slow
2) Calculation logic of gas prices is the same as in the https://docs.alchemy.com/reference/eth-feehistory you can configure it via https://docs.blockscout.com/for-developers/information-and-settings/env-variables#gas-price-oracle-management

**Comment by yzh-d** [comment]
> 1. 这里的average更像是一个中值，所以可以等于slow
> 2. [Gas价格的计算逻辑与https://docs.alchemy.com/reference/eth-feehistory](https://docs.alchemy.com/reference/eth-feehistory)中的相同，您可以通过[https://docs.blockscout.com/for-developers/information-and-settings](https://docs.blockscout.com/for-developers/information-and-settings/env-variables#gas-price-oracle-management)进行配置[/env-variables#gas-price-oracle-management](https://docs.blockscout.com/for-developers/information-and-settings/env-variables#gas-price-oracle-management)

What does the value of GAS_PRICE_ORACLE_SAFELOW_PERCENTILE mean? What does it mean if it is lower than the set value?

**Comment by yzh-d** [comment]
> 1. Here average is more like a median value, so it can be equal to slow
> 2. Calculation logic of gas prices is the same as in the https://docs.alchemy.com/reference/eth-feehistory you can configure it via https://docs.blockscout.com/for-developers/information-and-settings/env-variables#gas-price-oracle-management

I read this link: https://docs.alchemy.com/reference/eth-feehistory for an introduction to eth-feehistory, but I did not implement the eth-feehistory interface. In this case, how is the value of gas_prices calculated?

**Comment by sl1depengwyn** [comment]
> What does the value of GAS_PRICE_ORACLE_SAFELOW_PERCENTILE mean? What does it mean if it is lower than the set value?

It's percentile of `"slow"` gas price, you can think of it as you are making `eth_feeHistory` request like this:
```json
{
  "id": 1,
  "jsonrpc": "2.0",
  "method": "eth_feeHistory",
  "params": [
    <GAS_PRICE_ORACLE_NUM_OF_BLOCKS>,
    "latest",
    [
      <GAS_PRICE_ORACLE_SAFELOW_PERCENTILE>,
      <GAS_PRICE_ORACLE_AVERAGE_PERCENTILE>,
      <GAS_PRICE_ORACLE_FAST_PERCENTILE>
    ]
  ]
}
``` 

> I read this link: https://docs.alchemy.com/reference/eth-feehistory for an introduction to eth-feehistory, but I did not implement the eth-feehistory interface. In this case, how is the value of gas_prices calculated?

Blockscout does not use `eth_feeHistory` directly, only the logic of the fee calculation is the same.
