### ISSUE TITLE
There is no data

### ISSUE THREAD

**Issue by zeus-dev** [blockscout/blockscout#8624]
### Description

im runnning  etherum private network with poa and im running docker-compose I added rpc in env and these are my geth commands
geth version 1.13.2 stable

geth --datadir data/ --bootnodes enode://5a8192c1b39141ef56953ae0edc3a974ba5d58b6836c5ebf91da0a4b4b02e833767e488ada387dd3aa9b8ef5150936d418353d48b7ad412135ad737b9442e9de@127.0.0.1:0?discport=30305 --networkid 12345  --http.corsdomain "*" --allow-insecure-unlock --unlock 0x6bfFC7f5e5d5111BFB49a8623e07156e1E1b8bdc --password data/password.txt --mine --port 30306 --miner.etherbase 0x6bfFC7f5e5d5111BFB49a8623e07156e1E1b8bdc --http --http.addr 0.0.0.0 --http.port 8545 --http.api admin,clique,debug,eth,net,txpool,web3  --http.corsdomain "*" --gcmode archive --ws --ws.port 8546 --ws.addr 0.0.0.0 --ws.api admin,clique,debug,eth,net,txpool,web3 --syncmode full

<img width="1904" alt="Screenshot 2023-10-12 at 8 43 52 PM" src="https://github.com/blockscout/blockscout/assets/62093083/2faddfe9-ee64-42ef-ae8b-e92e03af8308">
<img width="1605" alt="Screenshot 2023-10-12 at 8 23 29 PM" src="https://github.com/blockscout/blockscout/assets/62093083/3215bd6e-dee5-4abc-9093-ec15827b0278">
<img width="1605" alt="Screenshot 2023-10-12 at 8 22 26 PM" src="https://github.com/blockscout/blockscout/assets/62093083/34de813e-684a-4d30-974d-22ad476262d4">

### Type of the installation

Docker-compose

### Type of the JSON RPC archive node

Geth

### Type of the chain

L1

### Link to the page
http://65.0.27.52
_No response_

### Steps to reproduce

this is my genesis.json file

{
    "config": {
        "chainId": 12345,
        "homesteadBlock": 0,
        "eip150Block": 0,
        "eip155Block": 0,
        "eip158Block": 0,
        "byzantiumBlock": 0,
        "constantinopleBlock": 0,
        "petersburgBlock": 0,
        "istanbulBlock": 0,
        "berlinBlock": 0,
        "clique": {
            "period": 15,
            "epoch": 30000
        }
    },
    "difficulty": "1",
    "gasLimit": "8000000",
    "extradata": "0x00000000000000000000000000000000000000000000000000000000000000006bfFC7f5e5d5111BFB49a8623e07156e1E1b8bdc0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000",
    "alloc": {
        "6bfFC7f5e5d5111BFB49a8623e07156e1E1b8bdc": { "balance": "300000000000000000000000" },
        "2462a08cc0E80d1ac597687e69a7Bca17000CD03": { "balance": "400000000000000000000000" }
    }
}

### Backend version

docker  file version

### Frontend version

1.14.0

### Elixir & Erlang/OTP versions

docker file version

### Operating system

Linux

### Additional information

<img width="1292" alt="Screenshot 2023-10-13 at 11 58 43 AM" src="https://github.com/blockscout/blockscout/assets/62093083/21aa5435-fc4c-412e-9d5a-580b8e56a196">

**Comment by zeus-dev** [comment]
<img width="1792" alt="Screenshot 2023-10-13 at 12 19 42 PM" src="https://github.com/blockscout/blockscout/assets/62093083/2beca241-d8e4-4558-83ec-b0464d4c300e">
this is the log

**Comment by vbaranov** [comment]
Please set NEXT_PUBLIC_API_HOST=65.0.27.52. Currently, it is pointed to localhost.

**Comment by zeus-dev** [comment]
yes done still no datas showing

**Comment by vbaranov** [comment]
> yes done still no datas showing

Where did you set it? I still see the frontend is requesting localhost.

**Comment by zeus-dev** [comment]
yes i changed in common-fronted.env and now working, thanks chart and stats only not loading
anyway thanks
