### ISSUE TITLE
Still no ETH received after transferring from Zora to Ethereum Mainet

### ISSUE THREAD

**Issue by Gunter3PO** [blockscout/blockscout#8655]
### Description

HI,
I transferred 0.04 Eth from Zora to Ethereum Mainnet using Zora Bridge on 02.10.23. I have not received any ETH yet.

Transaction hash 0xcf0e6b2031b29808c6c7d8a8a1715b064a50de6e27235bb1400d90a9c09c0b04

many greetings
Gunter

### Type of the installation

Helm charts

### Type of the JSON RPC archive node

Ethereum Mainnet

### Type of the chain

Zora 

### Backend version

01

### Elixir & Erlang/OTP versions

Google Chrome

### Operating system

MS

**Comment by vbaranov** [comment]
You should contact Zora team. This chat is for Blockscout-related questions. Your question is out of scope, where the Blockscout team can help.
