### ISSUE TITLE
Rootstock data is not loading

### ISSUE THREAD

**Issue by john-light** [blockscout/blockscout#8665]
### Description

When I open https://rootstock.blockscout.com/ the data does not load, even after several minutes waiting.

<img width="905" alt="Screenshot 2023-10-20 200609" src="https://github.com/blockscout/blockscout/assets/9424721/7c533a5a-0f67-4821-91ac-e91f33f80cc8">

### Type of the installation

hosted

### Type of the JSON RPC archive node

rskj

### Link to the page

https://rootstock.blockscout.com/

### Backend version

unsure

### Frontend version

v1.15.0+1db67c5b

### Elixir & Erlang/OTP versions

unsure

### Additional information

Issue occurs in latest Brave browser
Version 1.59.120 Chromium: 118.0.5993.88 (Official Build) (64-bit)
No other extensions interfering

Issue does not occur in latest Firefox browser

**Comment by ekawibisono** [comment]
hi @john-light The website is currently under repair, please wait until the blockscout team replies to your issue.

Thanks

**Comment by vbaranov** [comment]
This issue has been resolved. Rootstock instance is in operational state.
