### ISSUE TITLE
Contract code cannot be fetched on Base Sepolia instance

### ISSUE THREAD

**Issue by vbaranov** [blockscout/blockscout#8667]
### Description

This contract looks like EOA in the explorer https://base-sepolia.blockscout.com/address/0x13b0D85CcB8bf860b6b79AF3029fCA081AE9beF2.

However, this is a contract created in this tx https://base-sepolia.blockscout.com/tx/0x07066db690bda35716ec326bd2a544e775c501184baf105f223a0d1319bcfd8a.

### Type of the installation

Helm charts

### Type of the JSON RPC archive node

Geth

### Link to the page

https://base-sepolia.blockscout.com/address/0x13b0D85CcB8bf860b6b79AF3029fCA081AE9beF2

### Backend version

v5.3.0

### Elixir & Erlang/OTP versions

Elixir 1.14.5

### Additional information

```
base_sepolia=> select created_contract_address_hash from transactions where created_contract_address_hash is not null and block_hash is not null and created_contract_code_indexed_at is null;
       created_contract_address_hash
--------------------------------------------
 \x13b0d85ccb8bf860b6b79af3029fca081ae9bef2
(1 row)
```

This env is set on the instance:
ETHEREUM_JSONRPC_DISABLE_ARCHIVE_BALANCES=true

**Comment by yzh-d** [comment]
I am searching for related issues to try to answer my question. 😩 I would like to know how to deploy the contract you provided and which method to verify. We have connected to blocksout, but we don’t know how to deploy and verify this kind of folder level. contract
