### ISSUE TITLE
Search the block number on the homepage, and the result is empty

### ISSUE THREAD

**Issue by yzh-d** [blockscout/blockscout#8699]
### Description

- first question
At present, the number of blocks produced in the blockchain has reached 999967, but when searching for 590172 on the homepage, the block number should be displayed, but the actual result is empty.
An operation I did before was to clear the blockscout data, which should resynchronize the historical data. However, it has been at least 5 days since I cleared the data, and I still can’t find the top block number.

<img width="1343" alt="image" src="https://github.com/blockscout/blockscout/assets/30540477/4a426992-eb5d-45c1-9980-1f7535815aa9">

<img width="766" alt="image" src="https://github.com/blockscout/blockscout/assets/30540477/f82b34d3-ffb0-4508-9d50-cc86c5cfe59d">

- second question
Under the premise of question 1 (the data has been cleared before), I restart blockscout. Occasionally, the Latest blocks on the homepage will display not the latest block number, but the block number from a long time ago. However, when I send a transaction, it appears again. Newly generated blocks will be synchronized.

<img width="730" alt="image" src="https://github.com/blockscout/blockscout/assets/30540477/d8e7583b-a3c2-4415-b8dd-257797a1d7e7">

### Type of the installation

Docker-compose

### Type of the JSON RPC archive node

ganache

### Type of the chain

L1

### Backend version

v5.2.3-beta

### Frontend version

Self-developed front-end

### Elixir & Erlang/OTP versions

Elixir 1.14.0 (compiled with Erlang/OTP 25)

### Operating system

Linux

**Comment by vbaranov** [comment]
This probably means, that this block number is not fetched yet from the node.

**Comment by yzh-d** [comment]
> 这可能意味着，尚未从节点获取该块号。

So can we only wait for block synchronization data? Is there any relevant env configuration to speed up the synchronization?

**Comment by vbaranov** [comment]
You can adjust INDEXER_CATCHUP_BLOCKS_BATCH_SIZE, INDEXER_CATCHUP_BLOCKS_CONCURRENCY in order to manage speed. Please, take a look https://docs.blockscout.com/for-developers/information-and-settings/env-variables#indexer-management.

Also, you can monitor indexing progress
- via API endpoint /api/v2/main-page/indexing-status
- via db query: https://docs.blockscout.com/for-developers/indexing#monitoring-indexing-processes queries.
