### ISSUE TITLE
Error reported when performing contract verification through Sourcify: Smart-contract verification error: Chain 1356 not supported for verification!

### ISSUE THREAD

**Issue by yzh-d** [blockscout/blockscout#8700]
### Description

Our blockchain is deployed in the intranet environment. The blockchain ID is 1356. The same contract code can be deployed successfully at  [https://eth-sepolia.blockscout.com/address/0xd96C5Aa080435821795B2a69b2dE9bFaa284De3c?tab=contract](https://eth-sepolia.blockscout.com/address/0xd96C5Aa080435821795B2a69b2dE9bFaa284De3c?tab=contract), but The blockscout I deployed reported an error

The following ENV variables are set：
- SOURCIFY_INTEGRATION_ENABLED=true
- CHAIN_ID=1356

<img width="818" alt="image" src="https://github.com/blockscout/blockscout/assets/30540477/6e0e7ce4-47a3-4020-9fc6-8ddaf1d1277d">

I looked at [sourcify](https://sourcify.dev/) and suspected that it was because my blockchain was deployed in the intranet environment, so I deployed local sourcify by referring to links [Running Sourcify Locally](https://docs.sourcify.dev/docs/run-locally/) and [Verification on Local Test Chain](https://docs.sourcify.dev/docs/local-test-chain/), but still got the same error.

### Type of the installation

Docker-compose

### Type of the JSON RPC archive node

ganache

### Type of the chain

L1

### Backend version

v5.2.3-beta

### Frontend version

Self-developed front-end

### Elixir & Erlang/OTP versions

Elixir 1.14.0 (compiled with Erlang/OTP 25)

### Operating system

Linux

**Comment by vbaranov** [comment]
If you deployed Sourcify locally, you should also provide your SOURCIFY_SERVER_URL and SOURCIFY_REPO_URL https://docs.blockscout.com/for-developers/information-and-settings/env-variables#sourcify
