### ISSUE TITLE
Read contract method shows error as response

### ISSUE THREAD

**Issue by Anilkumar18** [blockscout/blockscout#8711]
### Description

After completing the contract verification when we click on the read contract tab it gives me an error message. When I tried to inspect the issue on the network tab I found that an endpoint named "/smart-contracts" provided the 500 internal server error. I have attached the reference images below.

URL: https://bs-explorer.ncogchain.earth/smart-contracts?hash=0x5e42a6495e47739c3cc587ae8faecfe9b4698c97&type=regular&action=read&is_custom_abi=false&from=0x62d8c001cfac4cb3deb64071bcc83c9029ca9c06

![image](https://github.com/blockscout/blockscout/assets/32846534/28d56aa4-2d39-4666-89e1-7064f1f14ada)

![image](https://github.com/blockscout/blockscout/assets/32846534/197b65d5-c84c-4608-bac9-7bf0b2c7177b)

![image](https://github.com/blockscout/blockscout/assets/32846534/43928f6f-c84d-48ef-8f19-97863c0b4873)

### Type of the installation

Manual from the source code

### Type of the JSON RPC archive node

Geth

### Link to the page

https://bs-explorer.ncogchain.earth/

### Backend version

v5.2.0

### Elixir & Erlang/OTP versions

Elixir 1.13.3(compiled with Erlang/OTP 24)

### Operating system

Linux

**Comment by sl1depengwyn** [comment]
Could you please provide logs from blockscout when you open read contract tab on this address?

**Comment by Anilkumar18** [comment]
@sl1depengwyn , here is the log. Please have a look. Thanks!

2023-10-24T08:29:34.760 [error] #PID<0.16543.53> running BlockScoutWeb.Endpoint (connection #PID<0.16545.53>, stream id 1) terminated
Server: bs-explorer.ncogchain.earth:80 (http)
Request: GET /smart-contracts?hash=0x026409d0766fcc854d961f5707777a83af1c8695&type=regular&action=read&is_custom_abi=false&from=
** (exit) an exception was raised:
    ** (ArgumentError) errors were found at the given arguments:

  * 2nd argument: not a valid pattern

        (stdlib 3.17) :binary.matches("URL is nil", nil)
        (elixir 1.13.3) lib/string.ex:1521: String.replace_guarded/4
        (block_scout_web 5.2.0) lib/block_scout_web/views/smart_contract_view.ex:305: BlockScoutWeb.SmartContractView.cut_rpc_url/1
        (block_scout_web 5.2.0) lib/block_scout_web/templates/smart_contract/_functions.html.eex:155: anonymous fn/3 in BlockScoutWeb.SmartContractView."_functions.html"/1
        (elixir 1.13.3) lib/enum.ex:2396: Enum."-reduce/3-lists^foldl/2-0-"/3
        (block_scout_web 5.2.0) lib/block_scout_web/templates/smart_contract/_functions.html.eex:38: BlockScoutWeb.SmartContractView."_functions.html"/1
        (phoenix 1.5.13) lib/phoenix/view.ex:472: Phoenix.View.render_to_iodata/3
        (phoenix 1.5.13) lib/phoenix/controller.ex:777: Phoenix.Controller.render_and_send/4

**Comment by sl1depengwyn** [comment]
Please, share your env vars

**Comment by ekawibisono** [comment]
> Sure @sl1depengwyn , please suggest if I'm missing something or need to modify it. That would be very helpful.
> 
> PORT=4000 SECRET_KEY_BASE= DATABASE_URL= NETWORK=NCOGEarthChain SUBNETWORK=NEC CHAIN_ID= COIN= COIN_NAME= LOGO= LOGO_FOOTER= BLOCKSCOUT_VERSION=5.2.0 SUPPORTED_CHAINS= ETHEREUM_JSONRPC_VARIANT=geth ETHEREUM_JSONRPC_TRANSPORT=ipc IPC_PATH= JSON_RPC= SHOW_TXS_CHART=true ENABLE_TXS_STATS=true MIX_ENV=prod TRACE_FIRST_BLOCK=false TRACE_LAST_BLOCK=false INDEXER_DISABLE_INTERNAL_TRANSACTIONS_FETCHER=true MICROSERVICE_SC_VERIFIER_ENABLED=true HEART_COMMAND= BLOCKSCOUT_HOST= MICROSERVICE_SC_VERIFIER_URL=http://0.0.0.0:8050/ SOURCIFY_INTEGRATION_ENABLED=true

What method did you build blockscout using? manual or docker compose?

try using env this

```
MICROSERVICE_SC_VERIFIER_ENABLED=true
MICROSERVICE_SC_VERIFIER_URL=https://eth-bytecode-db.services.blockscout.com/
MICROSERVICE_SC_VERIFIER_TYPE=eth_bytecode_db
MICROSERVICE_ETH_BYTECODE_DB_INTERVAL_BETWEEN_LOOKUPS=10m
MICROSERVICE_ETH_BYTECODE_DB_MAX_LOOKUPS_CONCURRENCY=10
```

**Comment by ekawibisono** [comment]
your console log error this
![image](https://github.com/blockscout/blockscout/assets/22586872/de4c0069-faca-43fc-b787-ec99b3599d37)

**Comment by Anilkumar18** [comment]
@ekawibisono Yes, that is the error I'm error. Can you please provide more info to fix this issue? Thanks!

**Comment by ekawibisono** [comment]
> @ekawibisono Yes, that is the error I'm facing. Can you please provide more info to fix this issue? Thanks!

Please check your blockscout configuration and web server configuration again

**Comment by Anilkumar18** [comment]
adding ETHEREUM_JSONRPC_HTTP_URL fixed this. Closing the issue. Thanks!
