### ISSUE TITLE
Add smart-contracts metadata to the eth-bytecode-db request

### ISSUE THREAD

**Issue by nikitosing** [blockscout/blockscout#8720]
https://app.swaggerhub.com/apis/rimrakhimov/EthereumBytecodeDatabase/v2#/

**Comment by rimrakhimov** [comment]
Eventually, we want to run a script which would go through all unverified deployed contracts and tries to look up the sources via eth-bytecode-db. The basic idea was to get all contracts from the blockscout database, and then request a corresponding page for each contracts to trigger the search mechanism.

For that we need a separate api endpoint which uses `search-sources` eth-bytecode-db endpoint. That should allow us not to make requests to Sourcify, as the volume of data may be too much for them. 

Besides, we want that endpoint to search the contract without any timeouts we have (10 minutes as for now) for the usual lookup.

Considering that endpoint allows to ignore the timeouts it would be better to make that endpoint private and requiring an api-key
