### ISSUE TITLE
ws://localhost/socket/v2/websocket?vsn=2.0.0' failed

### ISSUE THREAD

**Issue by CodeWithJD** [blockscout/blockscout#8732]
### Description

_app-559dd2f562b9bf97.js:18 WebSocket connection to 'ws://localhost/socket/v2/websocket?vsn=2.0.0' failed: 
connect @ _app-559dd2f562b9bf97.js:18
(anonymous) @ _app-559dd2f562b9bf97.js:18
(anonymous) @ _app-559dd2f562b9bf97.js:18
waitForSocketClosed @ _app-559dd2f562b9bf97.js:18
(anonymous) @ _app-559dd2f562b9bf97.js:18
waitForBufferDone @ _app-559dd2f562b9bf97.js:18
teardown @ _app-559dd2f562b9bf97.js:18
(anonymous) @ _app-559dd2f562b9bf97.js:18
(anonymous) @ _app-559dd2f562b9bf97.js:18

nothing touch anything yet backend auto connected with node beacuse node already running ing docker but front give this error and front end page load but data not come on it i thini i need to configure it 

### Type of the installation

Docker-compose

### Type of the JSON RPC archive node

geth

### Link to the page

http://178.128.29.162/

### Backend version

no idea

### Frontend version

v1.16.0+502bcffe

### Elixir & Erlang/OTP versions

already in docker image

### Operating system

Linux

### Additional information

**User Agent:** Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/118.0.0.0 Safari/537.36

**Comment by ekawibisono** [comment]
Can you send more details about your problem via screenshots?

**Comment by vbaranov** [comment]
@CodeWithJD you should replace localhost with ip of the server in Nginx config and in frontend env variables.

**Comment by CodeWithJD** [comment]
> @CodeWithJD you should replace localhost with ip of the server in Nginx config and in frontend env variables.

wow..! after replace server ip it's fix and working normal Thanks..!
