### ISSUE TITLE
Problem L2 Chain Based Optimism

### ISSUE THREAD

**Issue by avenbreaks** [blockscout/blockscout#8734]
### Description

Cannot running Blockscout used L2 Based Optimism, but unset the L2 Environment is perfectly running, 
[Documentation](https://stack.optimism.io/docs/build/explorer/#archive-mode) Optimism Running Blockscout need `--gcmode=archive` is already setting to start node. Now Blockscout running without Env Var L2 

RPC Expose on Public : 
```
<IPAddress:8545> op-geth
<IPAddress:8547> op-node
<IPAddress:8560> op-proposer
<IPAddress:8548> op-batcher
```

ENV Frontend : 
```
# Optimistic rollup (L2) chain
NEXT_PUBLIC_IS_OPTIMISTIC_L2_NETWORK=true
NEXT_PUBLIC_OPTIMISTIC_L2_WITHDRAWAL_URL=https://app.optimism.io/bridge/withdraw
NEXT_PUBLIC_L1_BASE_URL=https://sepolia.etherscan.io
```

Logs Frontend : 
```
🌀 Checking environment variables and their placeholders congruity...
🚸 For the following environment variables placeholders were not generated at build-time:

 NEXT_PUBLIC_OPTIMISTIC_L2_WITHDRAWAL_URL
 NEXT_PUBLIC_IS_OPTIMISTIC_L2_NETWORK

 They are either deprecated or running the app with them may lead to unexpected behavior. 
 Please check the documentation for more details - https://github.com/blockscout/frontend/blob/main/docs/ENVS.md
      
🚨 Congruity check failed.
```

### Type of the installation

Docker-compose

### Type of the JSON RPC archive node

Geth

### Type of the chain

L2

### Link to the page

https://cybascan.io

### Backend version

latest

### Frontend version

latest

### Elixir & Erlang/OTP versions

none

### Operating system

Ubuntu 22.04 LTS (Digital Ocean)

**Comment by 0xtrou** [comment]
use this branch instead https://github.com/blockscout/blockscout/tree/production-optimism-stg

**Comment by avenbreaks** [comment]
> use this branch instead https://github.com/blockscout/blockscout/tree/production-optimism-stg

thankyou, any documentation about environment on L2 OP ?

**Comment by avenbreaks** [comment]
> use this branch instead https://github.com/blockscout/blockscout/tree/production-optimism-stg

```
🌀 Checking environment variables and their placeholders congruity...
🚸 For the following environment variables placeholders were not generated at build-time:
     NEXT_PUBLIC_OPTIMISTIC_L2_WITHDRAWAL_URL
     NEXT_PUBLIC_IS_OPTIMISTIC_L2_NETWORK
   They are either deprecated or running the app with them may lead to unexpected behavior. 
   Please check the documentation for more details - https://github.com/blockscout/frontend/blob/main/docs/ENVS.md
      
🚨 Congruity check failed.
```


same error

**Comment by vbaranov** [comment]
@avenbreaks for L2 Optimism stack chain, you should configure all required env vars from this section:

https://github.com/blockscout/frontend/blob/main/docs/ENVS.md#optimistic-rollup-l2-chain
