### ISSUE TITLE
Didn’t receive ETC

### ISSUE THREAD

**Issue by gurtejgrewal3000** [blockscout/blockscout#8738]
### Description

As binance is closing 
I tried to move it to different platform but it’s not working as I lost it I didn’t receive it and it’s not on binance even 
If possible can u please reverse it 
Thanks

### Type of the installation

Manual from the source code

### Type of the JSON RPC archive node

0xd60452e12a6715829a7c2c19c65a1c237656cb4a0a34277ede3850491e3c6626

### Type of the chain

L2

### Link to the page

https://etc.blockscout.com/tx/0xd60452e12a6715829a7c2c19c65a1c237656cb4a0a34277ede3850491e3c6626?sceneValue=1301

### Steps to reproduce

0xd60452e12a6715829a7c2c19c65a1c237656cb4a0a34277ede3850491e3c6626

### Backend version

v5.3.1-beta

### Frontend version

v1.16.0+502bcffe

### Elixir & Erlang/OTP versions

Email

### Operating system

Ios

### Additional information

**User Agent:** Mozilla/5.0 (iPhone; CPU iPhone OS 17_0_3 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.0.1 Mobile/15E148 Safari/604.1

**Comment by vbaranov** [comment]
This chat is for Blockscout-related questions. Your question is out of scope, where the Blockscout team can help. You should contact exchange.
