### ISSUE TITLE
For contracts with import local relative path sol, such as the erc20 contract in the openzeppelin example, I don’t know how to complete the verification after the deployment is completed.

### ISSUE THREAD

**Issue by yzh-d** [blockscout/blockscout#8763]
### Description

Contract address deployed on the sepolia test network: https://eth-sepolia.blockscout.com/address/0x837Ea540A7e2356bFDa5525fDc53d57F421C6bd0

I also have a message here: https://github.com/blockscout/blockscout/issues/8667

### Type of the installation

Docker-compose

### Type of the JSON RPC archive node

ganache

### Type of the chain

L1

### Link to the page

https://eth-sepolia.blockscout.com/address/0x837Ea540A7e2356bFDa5525fDc53d57F421C6bd0

### Backend version

v5.2.3-beta

### Frontend version

Self-developed front-end

### Elixir & Erlang/OTP versions

Elixir 1.14.0 (compiled with Erlang/OTP 25)

### Operating system

Linux

**Comment by vbaranov** [comment]
Please read this guide https://docs.blockscout.com/for-users/verifying-a-smart-contract/openzeppelin-contract-verification

**Comment by yzh-d** [comment]
> 请阅读本指南https://docs.blockscout.com/for-users/verifying-a-smart-contract/openzeppelin-contract-verification

It seems that the result I want needs to be verified through the Hardhat Etherscan plugin supports contract, I will try it
