### ISSUE TITLE
A contract that has been verified can still be verified using a different contract code, and the name and code of the contract will be modified.

### ISSUE THREAD

**Issue by yzh-d** [blockscout/blockscout#8766]
### Description

The two contract codes above can verify each other
- Deployed contract link：[https://eth-sepolia.blockscout.com/address/0xd96C5Aa080435821795B2a69b2dE9bFaa284De3c?tab=contract](url)
- contract code

// SPDX-License-Identifier: GPL-3.0
pragma solidity 0.8.18;
contract Demo {
    uint256 number;
    function CustomSet(uint256 num) public {
        number = num;
    }
    function CustomGet() public view returns (uint256){
        return number;
    }
}

- Another contract code
// SPDX-License-Identifier: GPL-3.0
pragma solidity 0.8.18;
contract Demo_1020_1 {
    uint256 age;
    function CustomSet(uint256 num) public {
        age = num;
    }
    function CustomGet() public view returns (uint256){
        return age;
    }
}

### Type of the installation

Docker-compose

### Type of the JSON RPC archive node

ganache

### Type of the chain

L1

### Link to the page

https://eth-sepolia.blockscout.com/address/0xd96C5Aa080435821795B2a69b2dE9bFaa284De3c?tab=contract

### Backend version

v5.2.3-beta

### Frontend version

Self-developed front-end

### Elixir & Erlang/OTP versions

Elixir 1.14.0 (compiled with Erlang/OTP 25)

### Operating system

Linux

**Comment by sl1depengwyn** [comment]
These smart contracts do the same thing, hence they have the same bytecode, it's okay that both these sources can verify the same address

**Comment by sl1depengwyn** [comment]
I'm closing this, feel free to re-open if you have any questions
