### ISSUE TITLE
Enable Auth0 New UI

### ISSUE THREAD

**Issue by avenbreaks** [blockscout/blockscout#8773]
### Description

hey guys, i got error enable auth0 

`https://scan.engram.tech/auth/auth0?path=%2F
`

Callback URL mismatch.
The provided redirect_uri is not in the list of allowed callback URLs.
Please go to the [Application Settings page](https://manage.auth0.com/#/applications/mc9GJzPM8QWbIB2gIctfoS4tz2GcG1VY/settings) and make sure you are sending a valid callback url from your application.

`https://engramnet.us.auth0.com/authorize?client_id=mc9GJzPM8QWbIB2gIctfoS4tz2GcG1VY&redirect_uri=http%3A%2F%2Fscan.engram.tech%2Fauth%2Fauth0%2Fcallback%3Fpath%3D%252F&response_type=code&scope=openid+profile+email&state=n2DWnvRjxKFbGd5GQ-lFNYkN`

**Auth0 Settings** 
```
Application Login URI : https://scan.engram.tech/auth/auth0
Allowed Callback URLs : https://scan.engram.tech/auth/auth0/callback
Allowed Logout URLs   : https://scan.engram.tech/auth/logout
Allowed Web Origins   : https://scan.engram.tech
Allowed Cross Origin  : https://scan.engram.tech
```

**Backend ENV** 
```
ACCOUNT_CLOAK_KEY=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
ACCOUNT_ENABLED=true
ACCOUNT_REDIS_URL=redis://redis_db:6379
ACCOUNT_DATABASE_URL=postgresql://xxxxxxxx:xxxxxxxxxxxxxxx@db:5432/xxxxxxxxxxxx
ACCOUNT_POOL_SIZE=50
ACCOUNT_AUTH0_DOMAIN=engramnet.us.auth0.com
ACCOUNT_AUTH0_CLIENT_ID=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
ACCOUNT_AUTH0_CLIENT_SECRET=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
ACCOUNT_PUBLIC_TAGS_AIRTABLE_URL=https://api.airtable.com/v0/xxxxxxx
ACCOUNT_PUBLIC_TAGS_AIRTABLE_API_KEY=xxxxxxxxxxxxxxxxxxxxx
ACCOUNT_SENDGRID_API_KEY=xxxxxxxxxxxxxxxxxxxx
ACCOUNT_SENDGRID_SENDER=xxxxxxxxxxxxxxxxxxxxxx
ACCOUNT_SENDGRID_TEMPLATE=xxxxxxxxxxxxxxxxxxxx
ACCOUNT_PRIVATE_TAGS_LIMIT=2000
ACCOUNT_WATCHLIST_ADDRESSES_LIMIT=15
```

**Frontend ENV** 
```
NEXT_PUBLIC_IS_ACCOUNT_SUPPORTED=true
NEXT_PUBLIC_AUTH0_CLIENT_ID=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
NEXT_PUBLIC_AUTH_URL=https://scan.engram.tech
NEXT_PUBLIC_LOGOUT_URL=https://engramnet.us.auth0.com/v2/logout
NEXT_PUBLIC_CONTRACT_INFO_API_HOST=https://contracts-info.services.blockscout.com
NEXT_PUBLIC_ADMIN_SERVICE_API_HOST=https://admin-rs.services.blockscout.com
NEXT_PUBLIC_CONTRACT_INFO_API_HOST=https://contracts-info.services.blockscout.com
```

### Type of the installation

Docker-compose

### Type of the JSON RPC archive node

Geth

### Type of the chain

L1

### Link to the page

https://scan.engram.tech

### Backend version

latest

### Frontend version

latest

### Elixir & Erlang/OTP versions

none

### Operating system

Linux

**Comment by vbaranov** [comment]
@avenbreaks could you upgrade the backend to 5.3.1?

<img width="157" alt="Screenshot 2023-11-02 at 11 42 35" src="https://github.com/blockscout/blockscout/assets/4341812/4a023eaf-1e06-454c-aad8-4d78e639e649">

Try to empty Allowed Web Origins and Allowed Cross Origin.
