### ISSUE TITLE
docker integration local step up error

### ISSUE THREAD

**Issue by sakthikutti21** [blockscout/blockscout#8778]
### Description

![WhatsApp Image 2023-11-02 at 5 59 14 PM](https://github.com/blockscout/blockscout/assets/125294637/586a989d-6b0c-4a84-b08b-ede158d29739)

i used code in above image (cd ./docker-compose
docker-compose up --build) to step up docker composer, i used this code in terminal running more than 6 hours after that installation stopped. 

![Screenshot_291](https://github.com/blockscout/blockscout/assets/125294637/94249882-e09c-4a61-bda9-773c2db82315)

Is there anyother way to step blockscout. 
Explain me in step by step, because i am new for this language.

### Type of the installation

Docker-compose

### Type of the JSON RPC archive node

Geth

### Link to the page

localhost

### Backend version

v5.1.3

### Frontend version

v1.16.0

### Elixir & Erlang/OTP versions

no

### Operating system

windows

**Comment by ekawibisono** [comment]
What specifications do you use to install Blockscout?

**Comment by sakthikutti21** [comment]
i am  new, i just download blockscout from github i dont know how to stepup, explain step by step in easy way

**Comment by ekawibisono** [comment]
> i am  new, i just download blockscout from github i dont know how to stepup, explain step by step in easy way
> 
> 
> 
> system specification:
> 
> -> os windows 10
> 
> -> proccessor intel i5 7th gen
> 
> -> 4gb ram and 250 gb rom
> 
> 
> 
> Docker version 24.0.6, build ed223bc
> 
> Docker Compose version v2.23.0-desktop.1
> 
> docker.io/hexpm/elixir:1.14.5-erlang-24.2.2-alpine-3.18.2  
> 
> 
> 
> using docker to fetch data

Please check the Blockscout installation specifications

https://docs.blockscout.com/for-developers/information-and-settings

**Comment by ekawibisono** [comment]
If there is no answer you can ask on the official blockscout discord. please close this issue because there are no replies and duplication of posts
