### ISSUE TITLE
Bridge not receive from bitcoincode.technolog

### ISSUE THREAD

**Issue by indiateam10** [blockscout/blockscout#8782]
### Description

I have withdraw $19 from bridge USDT TRC20 but still I don't receive still 20  hours why please help me to get my USDT TRC 20 address TXknARJ5f2m14qz9hDttgwPBW6qxmnGGdv  Transection ](https://scan.bitcoincode.technology/tx/0xbb605ee23eb04a2173741a14a7d477c13c46b305d83f5e60699ef2511361b31d)

### Type of the installation

Manual from the source code

### Type of the JSON RPC archive node

https://scan.bitcoincode.technology/

### Type of the chain

BTC20 Smart chain

### Link to the page

https://scan.bitcoincode.technology/tx/0xbb605ee23eb04a2173741a14a7d477c13c46b305d83f5e60699ef2511361b31d

### Steps to reproduce

I have withdraw $19 from bridge USDT TRC20 but still I don't receive still 20  hours why please help me to get my USDT TRC 20 address TXknARJ5f2m14qz9hDttgwPBW6qxmnGGdv  Transection ](https://scan.bitcoincode.technology/tx/0xbb605ee23eb04a2173741a14a7d477c13c46b305d83f5e60699ef2511361b31d)

### Backend version

metamask

### Frontend version

tron

### Elixir & Erlang/OTP versions

otp

### Operating system

crome

### Additional information

I have withdraw $19 from bridge USDT TRC20 but still I don't receive still 20  hours why please help me to get my USDT TRC 20 address TXknARJ5f2m14qz9hDttgwPBW6qxmnGGdv  Transection ](https://scan.bitcoincode.technology/tx/0xbb605ee23eb04a2173741a14a7d477c13c46b305d83f5e60699ef2511361b31d)
![397992534_10168264746115261_3854769765938622256_n](https://github.com/blockscout/blockscout/assets/149860840/ac5f52e4-b681-4d9f-9f2f-314e1b8d1f37)
![Untitled](https://github.com/blockscout/blockscout/assets/149860840/4c3cdba4-5617-4eef-958d-7dff88e8e4c5)

**Comment by sl1depengwyn** [comment]
Blockscout is explorer, and this issue is unrelated to explorer functionality, so I cant help here, please contact bitcoincode directly
