### ISSUE TITLE
There are no internal transactions for transaction

### ISSUE THREAD

**Issue by ganzr** [blockscout/blockscout#8785]
### Description

I have 2 contract, say, caller and callee, and i send a tx calling method A in caller, where method A will call mothod B in callee.
The tx is mined successfully, and i can get output when calling debug_traceTransaction like this:
{"jsonrpc":"2.0","id":1,"result":{"type":"CALL","from":"0x74e00c288c5c997f97a1fd4331f2dfc567aa1571","to":"0x19b949f743e2ab7b0d1bd98c8cc90d9b679a7db2","value":"0x0","gas":"0x47a8","gasUsed":"0x25c3","input":"0xcb5870390000000000000000000000003101db9cfcd23fa8a56474e36f5a3b8d83ce38910000000000000000000000000000000000000000000001695d556204b1e80000","output":"0x","calls":[{"type":"CALL","from":"0x19b949f743e2ab7b0d1bd98c8cc90d9b679a7db2","to":"0x3101db9cfcd23fa8a56474e36f5a3b8d83ce3891","value":"0x0","gas":"0x38bd","gasUsed":"0x166a","input":"0x4018d9aa0000000000000000000000000000000000000000000001695d556204b1e80000","output":"0x0000000000000000000000000000000000000000000001695d556204b1e80000"}]}}

But there is no internal transaction in blocksout:
<img width="1314" alt="image" src="https://github.com/blockscout/blockscout/assets/20966436/df923899-d080-403b-9249-4784c0114669">
there is error produced by indexer.How could this happen? 

### Type of the installation

Manual from the source code

### Type of the JSON RPC archive node

Geth

### Backend version

v5.3.1

### Elixir & Erlang/OTP versions

Elixir 1.14.1 (compiled with Erlang/OTP 25)

**Comment by ganzr** [comment]
There is no error about fetching internal transaction in log

**Comment by sl1depengwyn** [comment]
Could you please share your environment variables?

**Comment by ganzr** [comment]
export ETHEREUM_JSONRPC_VARIANT=geth
export ETHEREUM_JSONRPC_HTTP_URL=localhost:4000
export ETHEREUM_JSONRPC_TRACE_URL=http://localhost:4000
export MIX_ENV=dev
export MICROSERVICE_SC_VERIFIER_ENABLED=true
export MICROSERVICE_SC_VERIFIER_URL=http://0.0.0.0:8050/
export POOL_SIZE=200

**Comment by sl1depengwyn** [comment]
> export ETHEREUM_JSONRPC_VARIANT=geth export ETHEREUM_JSONRPC_HTTP_URL=localhost:4000 export ETHEREUM_JSONRPC_TRACE_URL=http://localhost:4000 export MIX_ENV=dev export MICROSERVICE_SC_VERIFIER_ENABLED=true export MICROSERVICE_SC_VERIFIER_URL=http://0.0.0.0:8050/ export POOL_SIZE=200

By default blockscout app is running on port 4000, are you sure that `localhost:4000` is node json rpc endpoint?

**Comment by ganzr** [comment]
yes, i've set the PORT=5000 and it's running for i can get the result of curl request

**Comment by vbaranov** [comment]
@ganzr ot of curiosity, the default port for Geth RPC endpoint is 8545. Why did you place it to 4000 instead?

**Comment by ganzr** [comment]
This issue is related to the EIP1559 and not related to blockscout, so i'm going to close this issue.
