### ISSUE TITLE
Recover of my USDT

### ISSUE THREAD

**Issue by Aspuct** [blockscout/blockscout#8799]
### Description

My USDT went to the wrong adress and I want it to go back to the the first place 

https://explorer.kava.io/tx/0x79181e9feb87b0466d72a7ee21b8f1211388f89657b94c79fc82855194b7f00e

### Type of the installation

Docker-compose

### Type of the JSON RPC archive node

geth

### Type of the chain

KAVA 

### Link to the page

https://explorer.kava.io/tx/0x79181e9feb87b0466d72a7ee21b8f1211388f89657b94c79fc82855194b7f00e

### Steps to reproduce

It went to some random adress please email me to contact me

### Backend version

v5.3.1-kava

### Elixir & Erlang/OTP versions

Elixir 1.14.5 Erlang/OTP 25

### Operating system

unix linux

### Additional information

The issue happened at Kava 10 Blockscout instance

**Comment by vbaranov** [comment]
This chat is for Blockscout-related questions. Your question is out of scope, where the Blockscout team can help.
