### ISSUE TITLE
Enabling "My account' functionality failed 

### ISSUE THREAD

**Issue by SurenFTN** [blockscout/blockscout#8801]
### Description

Hey there. I am facing an issue while trying to enable My account functionality.After setting dependency in mix.exs the guide https://docs.blockscout.com/for-developers/configuration-options/my-account-settings is incomplete . Can you please share more described info for enabling functionality.

### Type of the installation

Manual from the source code

### Type of the JSON RPC archive node

Geth

### Type of the chain

L1

### Link to the page

https://www.ftnscan.com/

### Backend version

V5.0.0-beta

### Elixir & Erlang/OTP versions

elixir 1.13.4-otp-24/erlang 24.0

### Operating system

Linux

**Comment by sl1depengwyn** [comment]
Please, specify what issue exactly do you face?

**Comment by SurenFTN** [comment]
The changes for ueberauth in elixir. Also regarding the ACCOUNT_DATABASE_URL  env  it should be seperate db for account right ?

**Comment by sl1depengwyn** [comment]
I do not understand you, maybe this will help you https://discord.com/channels/973915550965174292/973918718105096242/1050721320750546946, if not please specify exactly what error do you face. About the database, no, the same database should be okay

**Comment by SurenFTN** [comment]
Ok what are the steps for enablig my account functinality. Just setting the ENVS adding Aritable and set up the Sendgrid?

**Comment by sl1depengwyn** [comment]
Basically yes

> Ok what are the steps for enablig my account functinality. Just setting the ENVS adding Aritable and set up the Sendgrid?

**Comment by SurenFTN** [comment]
What should i set the ACCOUNT_AUTH0_CLIENT_ID .

**Comment by sl1depengwyn** [comment]
> What should i set the ACCOUNT_AUTH0_CLIENT_ID .

Client ID of your Auth0 application/project

**Comment by SurenFTN** [comment]
I belive the problem is from the AUTH0 configuration side as as you mentioned from the server side I need to put just correct ENVs. Is there any guide in order to understand how should be the blockscout instance configured on the AUTH0's side.

**Comment by sl1depengwyn** [comment]
Please, specify your issue, have you set all the envs and nothing has changed?
Are you using the new frontend?

**Comment by SurenFTN** [comment]
After setting envs for 
`
#My Account

export ACCOUNT_ENABLED=true
export ACCOUNT_AUTH0_DOMAIN=https://login.oasis.ftnscan.com (is it correct it should listen the host on which the server is run right ?)
export ACCOUNT_AUTH0_CLIENT_ID=dI..................D9KhCECXPBiI1adMxVAJrw
export ACCOUNT_AUTH0_CLIENT_SECRET=DnstK8GjHu......................o30OLfTrCGoaPszrRZOrv
export ACCOUNT_SENDGRID_API_KEY=SG.u_N5BtoBRYGWevJc63pJRA...............h4v7fhLIKBoH1NvZw
export ACCOUNT_SENDGRID_SENDER=noreply@fasttoken.com
# export ACCOUNT_SENDGRID_TEMPLATE=d-...
export ACCOUNT_PUBLIC_TAGS_AIRTABLE_URL=https://airtable.com/appO.............KtggFNm/..........lSH03rPojBX
export ACCOUNT_PUBLIC_TAGS_AIRTABLE_API_KEY=appOQNY....Nm
# export ACCOUNT_CLOAK_KEY=...
export ACCOUNT_REDIS_URL=redis://127.0.0.1:6379
export ACCOUNT_DATABASE_URL=postgresql://.....................@localhost:5432/v2

`


It is built by manual deployment  without docker version 5.3.1

In the log I can see this message two messages 

`
2023-11-16T17:25:37.628 application=block_scout_web request_id=F5gdW2BO8mhyCnUAAAoG [info] GET /auth/auth0
2023-11-16T17:25:37.629 application=block_scout_web request_id=F5gdW2BO8mhyCnUAAAoG [info] Sent 302 in 983µs
`

the second one some times is giving that AUTH0 is not configured

**Comment by SurenFTN** [comment]
Hey there  after signing in  I am being redirected to main page with status code 500 here is the account releted part of my env I am using the old frontend https://oasis.ftnscan.com/ 

export ACCOUNT_ENABLED=true 
export ACCOUNT_DATABASE_URL=postgresql******************
export ACCOUNT_REDIS_URL=redis://localhost:6379,
export ACCOUNT_POOL_SIZE=50 
export ACCOUNT_AUTH0_DOMAIN=dev-***********************us.auth0.com
export ACCOUNT_AUTH0_CLIENT_ID=dIJ***********************w
export ACCOUNT_AUTH0_CLIENT_SECRET=D***********************v
export ACCOUNT_PUBLIC_TAGS_AIRTABLE_URL=https://api.airtable.com/v0/***********************/test***********************
export ACCOUNT_PUBLIC_TAGS_AIRTABLE_API_KEY=p***********************u
@vbaranov  Maybe you can help somehow

**Comment by GimluCom** [comment]
Have you set the `ACCOUNT_CLOAK_KEY` ENV?

**Comment by SurenFTN** [comment]
I believe its missing how can I generate it ?

**Comment by GimluCom** [comment]
Manual:
```sh
iex
32 |> :crypto.strong_rand_bytes() |> Base.encode64()
# Exit by pressing <ctrl-c> twice
```
Docker:
```sh
docker run --rm blockscout/blockscout elixir -e 'IO.puts(32 |> :crypto.strong_rand_bytes() |> Base.encode64())'
```
