### ISSUE TITLE
Recover funds

### ISSUE THREAD

**Issue by Migue6328** [blockscout/blockscout#8806]
### Description

Yesterday I sent USDT from my account in kucoin to my account in Coinbase, I didn’t receive because I use kava network. Now they say that my funds are in limbo. I really appreciate your help. 
![IMG_3825](https://github.com/blockscout/blockscout/assets/150305209/20a0c0bc-81a5-4bca-86c0-97245671af44)

### Type of the installation

Docker-compose

### Type of the JSON RPC archive node

geth

### Backend version

v5.3.1-kava

### Elixir & Erlang/OTP versions

Elixir 1.14.5 Erlang/OTP 25

### Operating system

unix linux

### Additional information

The issue happened at Kava 10 Blockscout instance

**Comment by vbaranov** [comment]
This chat is for Blockscout-related questions. Your question is out of scope, where the Blockscout team can help.
