### ISSUE TITLE
No deposit 

### ISSUE THREAD

**Issue by alirezaee7** [blockscout/blockscout#8810]
### Description

0xe5cd0387a9c945202aecf1ab87fbed19817757bd3ce4af37175aee73ecaf8fa0

### Type of the installation

Docker

### Type of the JSON RPC archive node

Zetachin

### Link to the page

https://zetachain-athens-3.blockscout.com/tx/0xe5cd0387a9c945202aecf1ab87fbed19817757bd3ce4af37175aee73ecaf8fa0?tab=token_transfers

### Steps to reproduce

0xe5cd0387a9c945202aecf1ab87fbed19817757bd3ce4af37175aee73ecaf8fa0

### Backend version

v5.3.1-beta 

### Frontend version

v1.16.0+502bcffe

### Elixir & Erlang/OTP versions

Harvard

### Operating system

Android 

### Additional information

**User Agent:** Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Mobile Safari/537.36

**Comment by vbaranov** [comment]
@alirezaee7 could you elaborate on what is the issue?

**Comment by alirezaee7** [comment]
Harvard ball and no deposit

**Comment by alirezaee7** [comment]
Farm ball exchange Zeta ball LP 0xf00b974d25c6fe627ee03ad2230d5708d9a7f53a
 harvest no deposit

**Comment by vbaranov** [comment]
This chat is for Blockscout-related questions. Your question is out of scope, where the Blockscout team can help.
