### ISSUE TITLE
Issues running Docker Hub images on Kubernetes

### ISSUE THREAD

**Issue by carlossrp** [blockscout/blockscout#8829]
### Description

Hello Blockscout team,

We're running a Blockscout deployment on Kubernetes and we're facing some errors using some images.

We used Kompose to convert docker-compose files to a working kubernetes deployment and had done some few adjustments.
This deployment works fine with Blockscout 5.1.5 and 5.2.3.

When we tried to update to Blockscout 5.3.0 and 5.3.1, the container promptly exits with the following message:
failed to create containerd task: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: exec: &qout;bash&quot;: executable file no found in $PATH: unknown

We faced similar issues with the nightly commit images.

We believe it could be related to the base image changing from bitwalker/alpine-elixir-phoenix:1.14 to hexpm/elixir:1.14.5-erlang-24.2.2-alpine-3.18.2.

We also noticed that the image size dropped from 208mb to 118mb on image [5.2.3.commit.c46aa15d](https://hub.docker.com/layers/blockscout/blockscout/5.2.3.commit.c46aa15d/images/sha256-5756f9d7d4dc4cde658b6218a9d589dae6c703e997867af878f13d271efcd39b?context=explore). We're able to launch the previous image [5.2.3.commit.3326d67e](https://hub.docker.com/layers/blockscout/blockscout/5.2.3.commit.3326d67e/images/sha256-0bb3670ab847ba2f69f82e50db5473a0ad49a10e8c0c04d89ddd76a810d1dcee?context=explore).

Our environment is AWS EKS running kubernetes:1.24.13.

Can you help us with this issue?

Thanks in advance, best regards

### Type of the installation

Docker-compose

### Type of the JSON RPC archive node

Besu

### Backend version

v5.3.1

### Elixir & Erlang/OTP versions

docker hub v5.3.1 image

### Operating system

aws eks

**Comment by vbaranov** [comment]
@carlossrp what command do you use to run docker image? You should replace bin/bash with bin/sh there.

**Comment by carlossrp** [comment]
Hi @vbaranov!

I’ve checked your suggestion and it worked.
Our Kompose converted container command was something like this:
```
command:
  - bash
args:
  - -c
  - bin/blockscout eval "Elixir.Explorer.ReleaseTasks.create_and_migrate()" && bin/blockscout start
```
Changed to
```
command:
  - /bin/sh
args:
  - -c
  - bin/blockscout eval "Elixir.Explorer.ReleaseTasks.create_and_migrate()" && bin/blockscout start
```
And worked fine, even with older releases, like 5.1.5 and 5.2.3.
Thanks for your help, we can close this
