### ISSUE TITLE
Gas Tracker API for v1

### ISSUE THREAD

**Issue by MaximK3** [blockscout/blockscout#8833]
Methods to be implemented for V1:
1) Sec in tx 
The time in which the transaction occurs in seconds (v1)

2) USD in tx
Price in USD per transaction (v1)

3) Update frequency in sec (v1)
Gas Tracker update frequency in seconds

**Comment by vbaranov** [comment]
Add all missing data to `/api/v2/stats` endpoint into `gas_prices` property.

**Comment by tom2drum** [comment]
+ can you add into `/api/v2/stats` response info about native coin delta for the last 24h to display it in the UI?

![Image](https://github.com/blockscout/blockscout/assets/22130104/9b670aac-dd56-4280-9c42-b667a557536e)
