### ISSUE TITLE
Help with a transaction 

### ISSUE THREAD

**Issue by Rdo556** [blockscout/blockscout#8852]
### Description

Hello! I transferred usdt from KuCoin 15 days ago via the network kava evm co-chain, but they still haven’t reached my coinbase wallet. What should I do? On KuCoin said, that I should write to your platform directly.  please help!

my email is rdo556@yahoo.com

Thank you for your assistance in advance!

Ryan

### Type of the installation

Docker-compose

### Type of the JSON RPC archive node

geth

### Backend version

v5.3.1-kava

### Elixir & Erlang/OTP versions

Elixir 1.14.5 Erlang/OTP 25

### Operating system

Windows 10

### Additional information

The issue happened at Kava 10 Blockscout instance

**Comment by vbaranov** [comment]
You should contact KuCoin for solving this. This chat is for Blockscout-related questions. Your question is out of scope, where the Blockscout team can help.
