### ISSUE TITLE
Cant download transactions

### ISSUE THREAD

**Issue by aibrahi3** [blockscout/blockscout#8856]
### Description

Transaction history cannot be downloaded. Issue with recaptia module precvents downloading of txn on the front end

### Type of the installation

Docker-compose

### Type of the JSON RPC archive node

GETH

### Type of the chain

L2

### Link to the page

https://zksync2-mainnet.zkscan.io/address/0xFC961534a0A55b925dB2c5ee546c8A019c0D78d5

### Steps to reproduce

try to download transaction history csv

### Backend version

v5.3.1-beta.+commit.644bc4b3

### Frontend version

v1.17.0+11524381

### Elixir & Erlang/OTP versions

?

### Additional information

**User Agent:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36

**Comment by ekawibisono** [comment]
There was an error in capcha verification, Please contact ZkSync ERA [ZkSync ERA](https://zksync.io/)
![image](https://github.com/blockscout/blockscout/assets/22586872/82bfdaa5-02c9-4325-8c7f-35cb27a72a20)

**Comment by vbaranov** [comment]
@aibrahi3 The issue has been resolved.

**Comment by aibrahi3** [comment]
Thank you Sent from my iPhoneOn Nov 21, 2023, at 1:15 AM, Victor Baranov ***@***.***> wrote:﻿
Closed #8856 as completed.
