### ISSUE TITLE
Fraud $950 ETC taking away from my Coinbase account! 

### ISSUE THREAD

**Issue by yhgong1961** [blockscout/blockscout#8857]
### Description

Fraud $950 ETC taking away from my Coinbase account! Received by 0x5253b33c1313a4449Bc5304A9C55b4CC2Bdf2872
Please help reverse and recover my big loss! Send back to my address:
0x69e6CfFCA250493510E10c939546d353a557e3E7
Thanks!

### Type of the installation

Docker-compose

### Type of the JSON RPC archive node

ETC

### Type of the chain

L1/L2

### Link to the page

https://etc.blockscout.com/block/18719101

### Steps to reproduce

Fraud $950 ETC taking away from my Coinbase account! Received by 0x5253b33c1313a4449Bc5304A9C55b4CC2Bdf2872
Please help reverse and recover my big loss! Send back to my address:
0x69e6CfFCA250493510E10c939546d353a557e3E7
Thanks!

### Backend version

v5.3.1-beta

### Frontend version

v1.17.0+11524381

### Elixir & Erlang/OTP versions

Elivir

### Operating system

Windows

### Additional information

Fraud $950 ETC taking away from my Coinbase account! Received by 0x5253b33c1313a4449Bc5304A9C55b4CC2Bdf2872
Please help reverse and recover my big loss! Send back to my address:
0x69e6CfFCA250493510E10c939546d353a557e3E7
Thanks!

**Comment by vbaranov** [comment]
This chat is for Blockscout-related questions. Your question is out of scope, where the Blockscout team can help.

**Comment by yhgong1961** [comment]
Condemn your irresponsible closing of the fraud case! Combined lawsuit is
going on and posting on X Twitter!
