### ISSUE TITLE
I request help to recover 250USDT

### ISSUE THREAD

**Issue by Xema33** [blockscout/blockscout#8871]
### Description

The first thing to indicate is that I do not speak English and I use Google translator.

Yesterday I sent 250 USDT to the indicated address through the KAVA EVM Network that has not arrived. It is possible that the wallet it was sent to does not accept the KAVA Network, in any case, they are not responding to my request via email. Can you help me recover the 250USDT? Or at least to see what steps I can take to recover them, taking into account that the wallet (Trust Wallet) is not responding and I have no way of contacting them.
I anticipate my gratitude for your attention.
Greetings
Xema

### Type of the installation

Manual from the source code

### Type of the JSON RPC archive node

geth

### Backend version

v5.3.1-kava

### Elixir & Erlang/OTP versions

Elixir 1.14.5 Erlang/OTP 25

### Operating system

unix linux

### Additional information

The issue happened at Kava 10 Blockscout instance

**Comment by sl1depengwyn** [comment]
You should contact Kava for solving this. This chat is for Blockscout-related questions. Your question is out of scope, where the Blockscout team can help.

**Comment by Xema33** [comment]
Good morning:
Thank you for your response, I am going to all the doors you indicate.
I don't know how to contact Kava, I can't find any email or contact form. COULD YOU TELL ME HOW TO CONTACT KAVA?
I thank you in advance for her willingness.
greetings
Xema

Sent from Proton Mail for iOS

El jue, 23 nov, 2023 a las 09:33, Maxim Filonov ***@***.***(mailto:El jue, 23 nov, 2023 a las 09:33, Maxim Filonov <<a href=)> ha escrito:
