### ISSUE TITLE
Clarification and Improvement of Docker Documentation in BlockScout Repository

### ISSUE THREAD

**Issue by blucrates** [blockscout/blockscout#8880]
### Description

The documentation for local docker deployment mention to use docker-compose, using docker-compose causes an error.

Please clarify which docker compose version to use docker-compose or docker compose

Best Regards

### Type of the installation

Docker-compose

### Type of the JSON RPC archive node

geth

### Type of the chain

L1

### Link to the page

https://

### Steps to reproduce

docker-compose -f docker-compose-no-build-geth-clique-consensus.yml up -d

### Backend version

v5.3.2

### Frontend version

/

### Elixir & Erlang/OTP versions

/

### Operating system

Ubuntu 23.10

**Comment by vbaranov** [comment]
@blucrates which error do you see? There is a prerequisite https://github.com/blockscout/blockscout/blob/master/docker-compose/README.md#prerequisites. Are you using docker-compose v2?

**Comment by blucrates** [comment]
Certainly, here's the response in normal text without code boxes:

Hi @vbaranov,

Thank you for your quick response. I've identified that the error I'm encountering is specific to the Docker Compose version provided on Ubuntu, which seems to be v1. When using the provided command:

`docker-compose -f docker-compose-no-build-geth-clique-consensus.yml up -d`

I'm getting the following error:


`ERROR: Cannot extend service 'db' in /home/blucrates/blockscout-5.3.1-beta/docker-compose/services/docker-compose-db.yml: services with 'depends_on' cannot be extended`

Interestingly, the deployment proceeds smoothly with Docker Compose v2, and for that version, I've been using the command:


`docker compose -f docker-compose-no-build-geth-clique-consensus.yml up -d`

Given this, I would like to suggest adding a note in the [docker](https://docs.blockscout.com/for-developers/information-and-settings/docker-integration-local-use-only) regarding the potential discrepancy in Docker Compose versions on Ubuntu. As there are two different Docker binaries on Ubuntu, providing clarity on which version is recommended for this deployment would greatly help users avoid such issues.

Your guidance on this matter would be highly appreciated.

Best Regards,

**Comment by vbaranov** [comment]
![Screenshot 2023-11-27 at 13 09 29](https://github.com/blockscout/blockscout/assets/4341812/8c1b37d6-97cf-4e76-a704-ac4d6afd369f)

Note added. Thanks for suggestion.
