### ISSUE TITLE
 Issue with Blockscout Chain Indexing on VPS Deployment

### ISSUE THREAD

**Issue by blucrates** [blockscout/blockscout#8883]
### Description

I am encountering an issue when attempting to deploy Blockscout on a VPS (Virtual Private Server) instance. The blockchain network is a private Geth Clique network with the RPC endpoint: https://rpc.blucrates.pro. I have followed the Docker-based deployment documentation, configured the necessary environment variables, and launched the services using the docker-compose -f docker-compose-no-build-geth-clique-consensus.yml up -d command.

**Problem:**

Local deployment of Blockscout works without any problems, but when deploying on a VPS instance (in this case, on a Digital Ocean server running Ubuntu 23.10), Blockscout does not seem to index the blockchain. The backend logs display the following information:

`{"time":"2023-11-24T18:34:56.406Z","severity":"info","message":"Batch of empty blocks is sanitized","metadata":{"fetcher":"empty_blocks_to_refetch"}}
{"time":"2023-11-24T18:35:02.392Z","severity":"info","message":"Index already caught up.","metadata":{"fetcher":"block_catchup","first_block_number":null,"last_block_number":null,"missing_block_count":0,"shrunk":false}}
{"time":"2023-11-24T18:35:02.392Z","severity":"info","message":"Checking if index needs to catch up in 25000ms.","metadata":{"fetcher":"block_catchup"}}
{"time":"2023-11-24T18:35:06.407Z","severity":"info","message":"Start sanitizing of empty blocks. Batch size is 100","metadata":{"fetcher":"empty_blocks_to_refetch"}}
{"time":"2023-11-24T18:35:06.563Z","severity":"info","message":"Batch of empty blocks is sanitized","metadata":{"fetcher":"empty_blocks_to_refetch"}}
{"time":"2023-11-24T18:35:16.564Z","severity":"info","message":"Start sanitizing of empty blocks. Batch size is 100","metadata":{"fetcher":"empty_blocks_to_refetch"}}
{"time":"2023-11-24T18:35:16.716Z","severity":"info","message":"Batch of empty blocks is sanitized","metadata":{"fetcher":"empty_blocks_to_refetch"}}
`

**Environment Variables (Backend):**

`ETHEREUM_JSONRPC_DISABLE_ARCHIVE_BALANCES=false
ETHEREUM_JSONRPC_HTTP_URL=https://rpc.bluchain.pro/
ETHEREUM_JSONRPC_TRACE_URL=https://rpc.bluchain.pro/
// ETHEREUM_JSONRPC_WS_URL=
`

**Question:**

What could be the reason for this behavior, and why is Blockscout not indexing the blockchain when running on a VPS?

### Type of the installation

Docker-compose

### Type of the JSON RPC archive node

geth

### Type of the chain

L1

### Link to the page

http://34.125.157.93/

### Steps to reproduce

Deploy Blockscout on a VPS instance using the provided Docker-based deployment steps.
Configure environment variables for the Ethereum JSON-RPC endpoint.
Monitor the backend logs for any issues related to blockchain indexing.

### Backend version

v5.3.2-beta

### Frontend version

v1.18.0

### Elixir & Erlang/OTP versions

/

### Operating system

Linux Ubuntu

### Additional information

Local deployment works as expected.
VPS instance is running Ubuntu 23.10.
Geth Clique network with the RPC endpoint https://rpc.blucrates.pro.
Thank you for your assistance in resolving this issue.

**Expected Behavior:**

Blockscout should successfully index the blockchain on the VPS instance, similar to the local deployment.

**Actual Behavior:**

Blockscout does not seem to index the blockchain, as indicated by the logs.

**Comment by vbaranov** [comment]
@blucrates please check with curl, if `https://rpc.bluchain.pro/` is available from VPS. And try to unset ETHEREUM_JSONRPC_WS_URL.

**Comment by blucrates** [comment]
Indeed, curl is accessible and functioning correctly when connecting to the https://rpc.bluchain.pro/ endpoint from the VPS that hosts BlockScout. As for ETHEREUM_JSONRPC_WS_URL, it has retained its original value, which is currently commented out: # ETHEREUM_JSONRPC_WS_URL=.

`# `DOCKER_TAG=
ETHEREUM_JSONRPC_VARIANT=geth
ETHEREUM_JSONRPC_HTTP_URL=https://data.bluchain.pro
`#` ETHEREUM_JSONRPC_FALLBACK_HTTP_URL=
DATABASE_URL=postgresql://blockscout:ceWb1MeLBEeOIfk65gU8EjF8@db:5432/blockscout
ETHEREUM_JSONRPC_TRACE_URL=http://data.bluchain.pro
`# `ETHEREUM_JSONRPC_FALLBACK_TRACE_URL=
`# `ETHEREUM_JSONRPC_HTTP_TIMEOUT=
`# `CHAIN_TYPE=

p.s. i've changed the url on purpose, the json rpc endpoint works

**Comment by blucrates** [comment]
i have a new error now : 

`{"time":"2023-11-27T22:03:27.193Z","severity":"error","message":"Task #PID<0.14845.0> started from Indexer.Block.Catchup.BoundIntervalSupervisor terminating\n** (MatchError) no match of right hand side value: nil\n    (indexer 5.3.2) lib/indexer/block/catchup/fetcher.ex:61: Indexer.Block.Catchup.Fetcher.task/1\n    (elixir 1.14.5) lib/task/supervised.ex:89: Task.Supervised.invoke_mfa/2\n    (elixir 1.14.5) lib/task/supervised.ex:34: Task.Supervised.reply/4\n    (stdlib 3.17) proc_lib.erl:226: :proc_lib.init_p_do_apply/3\nFunction: &Indexer.Block.Catchup.Fetcher.task/1\n    Args: [%Indexer.Block.Catchup.Fetcher{block_fetcher: %Indexer.Block.Fetcher{broadcast: :catchup, callback_module: Indexer.Block.Catchup.Fetcher, json_rpc_named_arguments: [transport: EthereumJSONRPC.HTTP, transport_options: [http: EthereumJSONRPC.HTTP.HTTPoison, url: \"https://data.bluchain.pro\", fallback_url: nil, fallback_trace_url: nil, method_to_url: [debug_traceTransaction: \"https://data.bluchain.pro\"], http_options: [recv_timeout: 600000, timeout: 600000, hackney: [pool: :ethereum_jsonrpc]]], variant: EthereumJSONRPC.Geth], receipts_batch_size: 250, receipts_concurrency: 10}, memory_monitor: Indexer.Memory.Monitor}]","metadata":{"error":{"initial_call":null,"reason":"** (MatchError) no match of right hand side value: nil\n    (indexer 5.3.2) lib/indexer/block/catchup/fetcher.ex:61: Indexer.Block.Catchup.Fetcher.task/1\n    (elixir 1.14.5) lib/task/supervised.ex:89: Task.Supervised.invoke_mfa/2\n    (elixir 1.14.5) lib/task/supervised.ex:34: Task.Supervised.reply/4\n    (stdlib 3.17) proc_lib.erl:226: :proc_lib.init_p_do_apply/3\n"},"fetcher":"block_catchup"}}
{"time":"2023-11-27T22:03:27.199Z","severity":"error","message":"Catchup index stream exited with reason ({{:badmatch, nil}, [{Indexer.Block.Catchup.Fetcher, :task, 1, [file: 'lib/indexer/block/catchup/fetcher.ex', line: 61]}, {Task.Supervised, :invoke_mfa, 2, [file: 'lib/task/supervised.ex', line: 89]}, {Task.Supervised, :reply, 4, [file: 'lib/task/supervised.ex', line: 34]}, {:proc_lib, :init_p_do_apply, 3, [file: 'proc_lib.erl', line: 226]}]}). Restarting","metadata":{"fetcher":"block_catchup"}}
`

**Comment by sashaaldrick** [comment]
What changed @blucrates to get the new error? I am also struggling to get connection to an RPC via a VPS deployment, whereas it works perfectly locally, so I think its something to do with the networking rules but not 100% sure yet. Did you change anything to get some connection?

**Comment by blucrates** [comment]
I'am now running  geth client via command line on the blockscout vps, it is clear that there is communication happening between the backend and the rpcnode, at this point if i'm doing something wrong or its a bug

`DEBUG[11-28|13:32:19.670] Served eth_getBlockByNumber              conn=172.29.0.6:40156 reqid=52 duration="131.535µs"
DEBUG[11-28|13:32:19.671] Served eth_getBlockByNumber              conn=172.29.0.6:40156 reqid=53 duration="94.004µs"
DEBUG[11-28|13:32:19.673] Served eth_getBlockByNumber              conn=172.29.0.6:40156 reqid=54 duration="85.901µs"
DEBUG[11-28|13:32:19.674] Served eth_getBlockByNumber              conn=172.29.0.6:40156 reqid=55 duration="65.652µs"
DEBUG[11-28|13:32:19.675] Served eth_getBlockByNumber              conn=172.29.0.6:40156 reqid=56 duration="61.916µs"
DEBUG[11-28|13:32:19.676] Served eth_getBlockByNumber              conn=172.29.0.6:40156 reqid=57 duration="57.827µs"
`

`            "4538413765fb0b3f17b146bdf0a7a0129b41eb92716e57d80c820d36f9116a01": {
                "Name": "backend",
                "EndpointID": "3851db196df33fa260217a8da6ff9616fa7d4e7c09b2477bc57c5f997a96425c",
                "MacAddress": "02:42:ac:1d:00:06",
                "IPv4Address": "172.29.0.6/16",
                "IPv6Address": ""
`

**Comment by sashaaldrick** [comment]
@blucrates I'm on Ubuntu 20, don't think that's the issue. Just added a firewall rule to my VPS to allow for connection to the RPC node. I'm not sure I've done it correctly as I'm still getting the same issues. I think it has something to do with this, might be worth checking your outbound traffic rules on your VPS

**Comment by blucrates** [comment]
> @blucrates I'm on Ubuntu 20, don't think that's the issue. Just added a firewall rule to my VPS to allow for connection to the RPC node. I'm not sure I've done it correctly as I'm still getting the same issues. I think it has something to do with this, might be worth checking your outbound traffic rules on your VPS

I've ran several vps instances with no firewall rules, I am running a geth instance on the vps hosting blockscout at the moment and i can see that they are indeed communicating just have to wait for the node to sync fully to establish whats happening

**Comment by blucrates** [comment]
my issue has been resolved, my nginx proxy was not configured properly

**Comment by 0xharryriddle** [comment]
@blucrates Hi sir, I have met the same issue. Could you please share your correct nginx proxy config, sir?
