### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by mctamney** [blockscout/blockscout#8884]
### Description

I sent eth classsic to my eth nano cold storage wallet by mistake. I sent a etc to a eth addreas

### Type of the installation

Docker-compose

### Type of the JSON RPC archive node

Na

### Type of the chain

Na

### Link to the page

https://etc.blockscout.com/tx/0x0cb7f85f9119875bcd981436aa5a975f748af9f0ae9ca44184564be2d0e55cda

### Steps to reproduce

![image](https://github.com/blockscout/blockscout/assets/151992909/f2540fc3-a720-4ad0-a331-3a59f34371b5)

### Backend version

v5.3.1-beta

### Frontend version

v1.17.0+11524381

### Elixir & Erlang/OTP versions

Na 

### Operating system

Windows

### Additional information

**User Agent:** Mozilla/5.0 (iPhone; CPU iPhone OS 17_1_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.1.1 Mobile/15E148 Safari/604.1

**Comment by vbaranov** [comment]
This chat is for Blockscout-related questions. Your question is out of scope, where the Blockscout team can help.
