### ISSUE TITLE
I can't verify smart contract on hardhat

### ISSUE THREAD

**Issue by BlueSpadeV2** [blockscout/blockscout#8889]
### Description

I can't verify smart contract on hardhat project.
Can you provide me any instruction?
Thank you

### Type of the installation

Docker-compose

### Type of the JSON RPC archive node

https://pulsechain.publicnode.com

### Type of the chain

L2

### Link to the page

http://127.0.0.1:3694/#/

### Backend version

v5.3.1-pulsechain

### Elixir & Erlang/OTP versions

don't know

### Operating system

Windows

### Additional information

**User Agent:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36

**Comment by vbaranov** [comment]
https://docs.blockscout.com/for-users/verifying-a-smart-contract/hardhat-verification-plugin
