### ISSUE TITLE
Lost transaction

### ISSUE THREAD

**Issue by captccs** [blockscout/blockscout#8893]
### Description

https://kavascan.com/tx/0x1daea98f8451c9edb677420e9c643f7dc7eac052ca590e2d8ba163605ed29575

Was not received in my coinbase account. It is apparently not supported. The transaction was successfully withdrawn from Kucoin. 

Need assistance getting transfer completed.

### Type of the installation

Docker-compose

### Type of the JSON RPC archive node

geth

### Backend version

v5.3.1-kava

### Elixir & Erlang/OTP versions

Elixir 1.14.5 Erlang/OTP 25

### Operating system

unix linux

### Additional information

The issue happened at Kava 10 Blockscout instance

**Comment by vbaranov** [comment]
This chat is for Blockscout-related questions. Your question is out of scope, where the Blockscout team can help. You should contact Kucoin.
