### ISSUE TITLE
New Interface v2 | Price and coinmarketcap not realtime move/change showing from coinmarketcap or coingecko fetch.

### ISSUE THREAD

**Issue by mdd0x** [blockscout/blockscout#8894]
### Description

Hi, got the small issue in my instance. the coinmarketcap and price not showing realtime change from coingecko or cryptocompare . the text its stuck and not change.

### Type of the installation

Docker-compose

### Type of the JSON RPC archive node

Besy

### Backend version

v5.3.2

### Frontend version

v.1.18

### Elixir & Erlang/OTP versions

v1.14

**Comment by vbaranov** [comment]
@mdd0x how did you configure exchange rates for the instnance? Here is the list of supported env vars https://docs.blockscout.com/for-developers/information-and-settings/env-variables#exchange-rates-management.

**Comment by mdd0x** [comment]
Hi @vbaranov , thanks for answer. 
<img width="278" alt="Screenshot 2023-11-28 at 17 02 17" src="https://github.com/blockscout/blockscout/assets/22166837/92cee532-90e7-44e3-b338-f44b073c0053">

My problem is the price and marketcap not move base on coingecko realtime price and mc movement.
this is for my .env for fetching price and marketcap 
EXCHANGE_RATES_MARKET_CAP_SOURCE=coin_gecko
EXCHANGE_RATES_PRICE_SOURCE=coin_gecko
EXCHANGE_RATES_COINGECKO_COIN_ID={coingecko coin id}


Thank you :)

**Comment by vbaranov** [comment]
@mdd0x are the prices and market cap correct at the start/re-start of the application for selecte native coin?

**Comment by mdd0x** [comment]
Yes its corrent, on my old explorer, its change realtime from coingecko. but on v2 the text price and coinmarketcap are stuck and no changes.

**Comment by mdd0x** [comment]
<img width="630" alt="Screenshot 2023-11-28 at 18 55 43" src="https://github.com/blockscout/blockscout/assets/22166837/b91dc450-9369-4fac-a0b7-589911b36400">
<img width="503" alt="Screenshot 2023-11-28 at 18 56 16" src="https://github.com/blockscout/blockscout/assets/22166837/39deedda-ad9e-4657-bb83-383693bc785f">

The second image is explorer v1, its the true one, price and marketcap is realtime fetched from coingecko. and on the first image that price and marketcap is stuck.

**Comment by mdd0x** [comment]
i think i found the problem.
<img width="455" alt="Screenshot 2023-11-28 at 19 03 15" src="https://github.com/blockscout/blockscout/assets/22166837/84ad0f5d-0941-4c36-b483-af700b2c5a4f">

in the chart. its true. but its not update to red circle.

**Comment by vbaranov** [comment]
> @vbaranov i think i found the problem. <img alt="Screenshot 2023-11-28 at 19 03 15" width="455" src="https://private-user-images.githubusercontent.com/22166837/286243434-84ad0f5d-0941-4c36-b483-af700b2c5a4f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU0MzQwNDAsIm5iZiI6MTcwNTQzMzc0MCwicGF0aCI6Ii8yMjE2NjgzNy8yODYyNDM0MzQtODRhZDBmNWQtMDk0MS00YzM2LWI0ODMtYWY3MDBiMmM1YTRmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE2VDE5MzU0MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE3MDFlYWQzNzJhNGNiNWQ1M2ZjOTk3ZmEzNzVkY2MwNWIxYzkxZmIwMTQ4NTgwZGU5YzljMTQ1NmZhMzI5OWEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.gpvZGHHTar8_jK4rPExQed2B36_u_c5ccMLmraMOHtM">
> 
> in the chart. its true. but its not update to red circle.

This has been resolved in this PR https://github.com/blockscout/blockscout/pull/9109, which merged to master branch.
