### ISSUE TITLE
 sent a USDT coin to a kava network. My meta mask says the coin was only sent 97% of the time. Can you help me?

### ISSUE THREAD

**Issue by Praaaner** [blockscout/blockscout#8895]
### Description

 sent a USDT coin to a kava network. My meta mask says the coin was only sent 97% of the time. Can you help me?

### Type of the installation

Docker-compose

### Type of the JSON RPC archive node

geth

### Backend version

v5.3.1-kava

### Elixir & Erlang/OTP versions

Elixir 1.14.5 Erlang/OTP 25

### Operating system

unix linux

### Additional information

The issue happened at Kava 10 Blockscout instance

**Comment by vbaranov** [comment]
This chat is for Blockscout-related questions. Your question is out of scope, where the Blockscout team can help.
