### ISSUE TITLE
Polygon-POS - application=indexer fetcher=pending_transaction [error] timeout

### ISSUE THREAD

**Issue by MudDev** [blockscout/blockscout#8909]
### Description

I'm using the default [docker-compose](https://github.com/blockscout/blockscout/tree/master/docker-compose) values, and getting this error:

```
{
  "time": "2023-11-30T04:09:45.991Z",
  "severity": "error",
  "message": "timeout",
  "metadata": {
    "fetcher": "pending_transaction"
  }
}
```

### Type of the installation

Docker-compose

### Type of the JSON RPC archive node

PolygonPOS

### Type of the chain

L2

### Backend version

v5.3.2-beta

### Elixir & Erlang/OTP versions

latest

### Operating system

Ubuntu

### Additional information

I'm pointing to a Polygon-POS RPC. I have confirmed that the RPC node is started with all of these flags:

`--http.api 'personal,eth,net,web3,txpool,miner,admin,bor,debug'`

_The symptoms of my issue feel very similar to the blockscout polygon explorer_: https://polygon.blockscout.com/

![Screenshot from 2023-11-29 21-38-27](https://github.com/blockscout/blockscout/assets/44410798/88d18226-1450-4fca-b726-cf61e13b8318)

**Comment by ekawibisono** [comment]
Currently the polygon network in Blockscout is under maintenance. please wait for information from the core team. thank you

**Comment by vbaranov** [comment]
@MudDev you can disable pending transactions fetcher for Polygon: `INDEXER_DISABLE_PENDING_TRANSACTIONS_FETCHER=true`.

Also, if your node is not in archive state, you should also disable internal trasnsactions fetcher:
`INDEXER_DISABLE_INTERNAL_TRANSACTIONS_FETCHER=true`

**Comment by BradleyN0** [comment]
Is this normal to disable pending transactions? I would like that are enabled.

My polygon node is in archive state.

**Comment by vbaranov** [comment]
> Is this normal to disable pending transactions? I would like that are enabled.
> 
> My polygon node is in archive state.

Do you see any issues with pending transactions? If `txpool_content` method returns data less than in 1 minute, pending transactions fetcher should work fine.

**Comment by vbaranov** [comment]
Please let us know, if you still face the issue with pending transactions. I am closing this for now.
