### ISSUE TITLE
Using the docker-compose command to deploy the v5.3.2-beta version always reports an error

### ISSUE THREAD

**Issue by yzh-d** [blockscout/blockscout#8944]
### Description

I have noticed this issue: [Fail to run blockscout locally with docker-compose instructions](https://github.com/blockscout/blockscout/issues/7656.) It has the same error as me, but according to the method mentioned in it, it is not solved.

The error message is as follows
 2023-12-05T08:22:16.541 application=db_connection [error] Postgrex.Protocol (#PID<0.200.0>) failed to connect: ** (DBConnection.ConnectionError) tcp connect (db:5432): connection refused - :econnrefused
2023-12-05T08:22:16.759 application=db_connection [error] Postgrex.Protocol (#PID<0.204.0>) failed to connect: ** (DBConnection.ConnectionError) tcp connect (db:5432): connection refused - :econnrefused
2023-12-05T08:22:17.520 application=ecto_sql [error] Could not create schema migrations table. This error usually happens due to the following:

  * The database does not exist
  * The "schema_migrations" table, which Ecto uses for managing
    migrations, was defined by another library
  * There is a deadlock while migrating (such as using concurrent
    indexes with a migration_lock)

To fix the first issue, run "mix ecto.create" for the desired MIX_ENV.

To address the second, you can run "mix ecto.drop" followed by
"mix ecto.create", both for the desired MIX_ENV. Alternatively you may
configure Ecto to use another table and/or repository for managing
migrations:

    config :explorer, Explorer.Repo,
      migration_source: "some_other_table_for_schema_migrations",
      migration_repo: AnotherRepoForSchemaMigrations

The full error report is shown below. 

The methods I tried are as follows, but none of them solved it：
- opening the custom port for the postgres container: `sudo ufw allow 7432/tcp`
- Change connection to postres in docker-compose: `DATABASE_URL: postgresql://postgres:@postgres:5432/blockscout?ssl=false`
- Comment out the `ETHEREUM_JSONRPC_WS_URL` configuration

My configuration is consistent with v5.2.3-beta, except for some necessary changes, but v5.3.2-beta version has this problem. How should I solve it? Is there any reference document?

### Type of the installation

Docker-compose

### Type of the JSON RPC archive node

ganache

### Type of the chain

L1

### Backend version

v5.3.2-beta

### Frontend version

Self-developed front-end

### Elixir & Erlang/OTP versions

Elixir 1.14.0 (compiled with Erlang/OTP 25)

### Operating system

Linux

**Comment by ekawibisono** [comment]
what your OS linux bro ? and version OS Linux ? @yzh-d
