### ISSUE TITLE
My bone transactions have been done for 1 day, but the eth still hasn't arrived in my wallet.

### ISSUE THREAD

**Issue by omen3547** [blockscout/blockscout#8945]
### Description

My bone transactions have been done for 1 day, but the eth still hasn't arrived in my wallet.   transaction mix these 2 transactions

0x27f60ab6c6c6b1372635f50bc042d1c5ee7f06e2564fc79fdf06ccfdd8a4b427

0x7be58549e33d6c1aab04c94140877aa7dfce0273e9afce8ee5d2de021495c92a

### Type of the installation

Docker-compose

### Type of the JSON RPC archive node

0

### Link to the page

https://www.shibariumscan.io/

### Steps to reproduce

My bone transactions have been done for 1 day, but the eth still hasn't arrived in my wallet.   transaction mix these 2 transactions

0x27f60ab6c6c6b1372635f50bc042d1c5ee7f06e2564fc79fdf06ccfdd8a4b427

0x7be58549e33d6c1aab04c94140877aa7dfce0273e9afce8ee5d2de021495c92a

### Backend version

v5.3.2-beta.+commit.19c9e7c6

### Frontend version

v1.18.0+32896734

### Elixir & Erlang/OTP versions

İksir ve Erlang/OTP versiyonları.

### Operating system

windovs

### Additional information

**User Agent:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36

**Comment by sl1depengwyn** [comment]
This question is not related to Blockscout as a blockchain explorer, contact Shibarium team directly
