### ISSUE TITLE
Sent USDT from Kucoin to Coinbase using Kava EVM cochain

### ISSUE THREAD

**Issue by valenciag9** [blockscout/blockscout#8970]
### Description

Hello, I'm wondering if you can help me recover my life savings. I made the mistake of sending USDT from Kucoin to Coinbase using Kava EVM cochain. Three days have passed and I don't see the funds in Coinbase!!!!

https://kavascan.com/tx/0x699e533fba29709000b8ac9e8e7889b800b053cde1f44ccf53adfd4bc8bca3ea

### Type of the installation

Docker-compose

### Type of the JSON RPC archive node

geth

### Backend version

v5.3.1-kava

### Elixir & Erlang/OTP versions

Elixir 1.14.5 Erlang/OTP 25

### Operating system

unix linux

### Additional information

The issue happened at Kava 10 Blockscout instance

**Comment by sl1depengwyn** [comment]
This question is not related to Blockscout as a blockchain explorer, contact Kava team directly
