### ISSUE TITLE
500 Internal Server Error

### ISSUE THREAD

**Issue by andreamauro17** [blockscout/blockscout#8977]
### Description

"When I make a call on Postman to fetch the transactions, I receive `next_page_params`, but when I use these values in the request, it doesn't work. Until Wednesday, everything was fine (and there were only 3 values: `block_number`, `items_count`, and `index`), but now there are 6. The error is a 500 Internal Server Error."

### Type of the installation

Manual from the source code

### Type of the JSON RPC archive node

Nothing

### Link to the page

https://etc.blockscout.com/api-docs

### Backend version

v5.3.3-beta.+commit.b7dac2a2

### Frontend version

v1.19.0+452c77fd

### Elixir & Erlang/OTP versions

.

### Operating system

Linux

### Additional information

**User Agent:** Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:120.0) Gecko/20100101 Firefox/120.0

**Comment by andreamauro17** [comment]
> ### Description
> 
"When I make a call on Postman to fetch the transactions, I receive `next_page_params`, but when I use these values in the request, it doesn't work. Until Wednesday, everything was fine (and there were only 3 values: `block_number`, `items_count`, and `index`), but now there are 6. The error is a 500 Internal Server Error."
> ### Type of the installation
> 
> Manual from the source code
> ### Type of the JSON RPC archive node
> 
> Nothing
> ### Type of the chain
> 
> _No response_
> ### Link to the page
> 
> https://etc.blockscout.com/api-docs
> ### Steps to reproduce
> 
> _No response_
> ### Backend version
> 
> v5.3.3-beta.+commit.b7dac2a2
> ### Frontend version
> 
> v1.19.0+452c77fd
> ### Elixir & Erlang/OTP versions
> 
> .
> ### Operating system
> 
> Linux
> ### Additional information
> 
> **User Agent:** Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:120.0) Gecko/20100101 Firefox/120.0

**Comment by sl1depengwyn** [comment]
Could you please tell what was the reason of the issue and how you were able to resolve it?

**Comment by andreamauro17** [comment]
Hi,i wanted to perform a Postman test that, given an address hash, would return transactions. Until the other day, I had no issues, but today the next_page_params object contained new attributes, and it didn't work in Postman (500 error). However, without doing anything, I resolved it because after a few hours on Postman, I got what I wanted, and the error was gone.
