### ISSUE TITLE
Why use the latest tag in the docker-compose configuration file?

### ISSUE THREAD

**Issue by dogethdev** [blockscout/blockscout#8990]
### Description

In the Docker Compose configuration file, the image field is not specified with a version name but uses -latest. This results in older releases pulling the latest version when configuring Docker. As a consequence, the older releases, by default, cannot function properly. You need to manually match the Docker image version.

### Type of the installation

Docker-compose

### Type of the JSON RPC archive node

123456

### Backend version

all version

### Frontend version

all version

### Elixir & Erlang/OTP versions

123456

**Comment by vbaranov** [comment]
We keep the latest tags of all Blockscout components in sync on order to safely use them. However, if you prefer to stick to some version, you can specify it via environment variable. There is a corresponding env variable for every component:
```
DOCKER_TAG
FRONTEND_DOCKER_TAG
SIG_PROVIDER_DOCKER_TAG
SMART_CONTRACT_VERIFIER_DOCKER_TAG
STATS_DOCKER_TAG
VISUALIZER_DOCKER_TAG
```
