### ISSUE TITLE
CPU keeps going up with NO traffic served at all

### ISSUE THREAD

**Issue by yarkinwho** [blockscout/blockscout#8992]
### Description

Running a docker deployment of backend (indexer turned off). Database is on other machines.

CPU keeps going up while no traffic is served at all (vm not put into the upstream of load balancer yet).

Tried 5.1.2 and 5.3.1. both have same pattern.

Please let me know if any information needed.

Thanks

### Type of the installation

Docker-compose

### Type of the JSON RPC archive node

Erigon

### Type of the chain

L1

### Link to the page

NA

### Backend version

v5.3.1

### Elixir & Erlang/OTP versions

Default for docker

### Operating system

Ubuntu

### Additional information

<img width="416" alt="image" src="https://github.com/blockscout/blockscout/assets/99302011/abd3f956-0e5b-446c-bc34-dfd227a9bc57">

**Comment by ekawibisono** [comment]
Can you tell us the specifications of the computer you use for blockscout?

**Comment by yarkinwho** [comment]
> hi @yarkinwho Can you tell us the specifications of the computer you use for blockscout?

@ekawibisono 

it's an aws c6a.2xlarge

8 core 16G

**Comment by ekawibisono** [comment]
hi @yarkinwho 
Is that one AWS machine running Blockscout and Erigon?

**Comment by yarkinwho** [comment]
> running

@ekawibisono Blockscout is targeting a customized client based on Erigon API deployed on another machine. 

The VM with this CPU consumption pattern only has blockscout on it. And it is not running with the new separate frontend. 

Also, given I turned off indexer (both docker build time and runtime), the webapp should be able to run even without the ethereum API.

**Comment by yarkinwho** [comment]
Any update?

It seems memory consumption is also keep growing. Any suggestion on how to debug?

**Comment by zillnet-l2** [comment]
Upgrade to v6.5.0-beta quickly, this version finally resolves the issue of high CPU usage.

**Comment by vbaranov** [comment]
@yarkinwho please update to 6.5.0 and let us know, if the issue still persists with that version.

**Comment by yarkinwho** [comment]
> @yarkinwho please update to 6.5.0 and let us know, if the issue still persists with that version.

Will do it later and go back to let you know the result. Thanks for the remind.
