### ISSUE TITLE
Sent 16000 to valora wallet address but not supported

### ISSUE THREAD

**Issue by Offia** [blockscout/blockscout#9003]
### Description

I sent 16000 good dollars to valora wallet but not supported by the wallet please I need a refund
![Screenshot_20231214-155059](https://github.com/blockscout/blockscout/assets/99348380/567082f7-7227-4966-8b76-9524f57d9181)

### Type of the installation

Docker-compose

### Type of the JSON RPC archive node

No response

### Type of the chain

No response

### Link to the page

https://explorer.fuse.io/tx/0x9fa50fecd5419c13bf7129a70d9ab868472e845312e790e4d7dcabbefb7d0ea4

### Steps to reproduce

No response

### Backend version

v5.3.3-beta.+commit.18408e30

### Frontend version

v1.19.0+452c77fd

### Elixir & Erlang/OTP versions

No response

### Operating system

No response

### Additional information

**User Agent:** Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/113.0.0.0 Mobile Safari/537.36

**Comment by vbaranov** [comment]
This chat is for Blockscout-related questions. Your question is out of scope, where the Blockscout team can help.

**Comment by Offia** [comment]
Please I need 16000 good dollar fuse to be reversed back to my good dollar
wallet since valora wallet does not support good dollar fuse
