### ISSUE TITLE
Token balance update takes too long on Sepolia

### ISSUE THREAD

**Issue by yvaskov** [blockscout/blockscout#9017]
## Description

Client reported ~2 min delay for balance update on Sepolia.
Thread: https://blockscout.slack.com/archives/C0504M3Q09J/p1702874349877749

https://eth-sepolia.blockscout.com/api/v2/addresses/0x1E8dC77BEd0da06621e819fa0AFb59D50F76CfDf/tokens?type=ERC-20
![Image](https://github.com/blockscout/blockscout/assets/72267126/91845eae-5020-406e-9e7e-54a86a6786e2)

## Version

[v5.3.3-beta.+commit.f738c402](https://github.com/blockscout/blockscout/commit/f738c402)

**Comment by vbaranov** [comment]
Resolved: `TOKEN_BALANCE_ON_DEMAND_FETCHER_THRESHOLD=1s`
