### ISSUE TITLE
GHCR permission issue

### ISSUE THREAD

**Issue by victor-nerdunited** [blockscout/blockscout#9022]
### Description

I'm getting an error running it with docker compose

```
$ docker-compose up --build
[+] Running 4/4
 ✘ stats Error                                                                                                                                                                        3.3s 
 ✘ sig-provider Error                                                                                                                                                                 3.3s 
 ✘ visualizer Error                                                                                                                                                                   3.3s 
 ✘ frontend Error                                                                                                                                                                     3.3s 
Error response from daemon: Head "https://ghcr.io/v2/blockscout/visualizer/manifests/latest": denied: denied
```

### Type of the installation

Docker-compose

### Type of the JSON RPC archive node

geth, default

### Type of the chain

L1

### Steps to reproduce

Just ran `docker-compose up --build`

### Backend version

3.9

### Frontend version

3.9

### Elixir & Erlang/OTP versions

NA

### Operating system

Windows

**Comment by vbaranov** [comment]
@victor-nerdunited you should auntenticate to github container registry. Please take a look https://docs.github.com/en/packages/working-with-a-github-packages-registry/working-with-the-container-registry#authenticating-with-a-personal-access-token-classic.
