### ISSUE TITLE
Ethereum classic not found in Wallet.

### ISSUE THREAD

**Issue by Boogie46** [blockscout/blockscout#9028]
### Description

I have double checked my address to a storage were my etherium classic should be. Every looks right with my transfer yet my tokens are there.

Please assist if possible. God bless

### Type of the installation

Docker-compose

### Type of the JSON RPC archive node

???

### Link to the page

https://etc.blockscout.com/tx/0x0e421b07baab7df9ae01c7cc6dde754f4ca1e2b5ac681d692ab06252e621d138

### Steps to reproduce

Not sure, I was moving crypto to my storage. It says completed yet the token aren't there.

### Backend version

v5.3.3-beta.+commit.b7dac2a2

### Frontend version

v1.20.0+e0c4f572

### Elixir & Erlang/OTP versions

???

### Additional information

**User Agent:** Mozilla/5.0 (iPhone; CPU iPhone OS 17_1_2 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.1.2 Mobile/15E148 Safari/604.1

**Comment by vbaranov** [comment]
This chat is for Blockscout-related questions. Your question is out of scope, where the Blockscout team can help.

**Comment by Boogie46** [comment]
Morning,

    Thanks for the response. This interaction would be a little more
helpful if you could steer me in the right direction for assistance.

Thanks


happy holidays!



Jays Lawn Care & Landscape LLC P.o Box 252 Griffith, In 46419 Phone
219-306-7961 Fax 219-397-7909 E-mail ***@***.*** Website
http://www.jayslawncarelandscape.com/
