### ISSUE TITLE
Is there a max transaction in a block that indexer can handle?

### ISSUE THREAD

**Issue by dennisloh95** [blockscout/blockscout#9050]
### Description

There are some block consist more than 3k transactions, when the indexer fetching internal_transaction it always return Erlang error: :closed. is there some env config I can update to fix this?

application=indexer fetcher=internal_transaction count=1 error_count=1 [error] failed to fetch internal transactions for blocks: ** (ErlangError) Erlang error: :closed

Below is my indexer config:
export INDEXER_MEMORY_LIMIT=6
export ETHEREUM_JSONRPC_HTTP_TIMEOUT=60
export ETHEREUM_JSONRPC_WAIT_PER_TIMEOUT=20s
export ETHEREUM_JSONRPC_DEBUG_TRACE_TRANSACTION_TIMEOUT=30s
export INDEXER_INTERNAL_TRANSACTIONS_BATCH_SIZE=1
export INDEXER_INTERNAL_TRANSACTIONS_CONCURRENCY=4
export INDEXER_RECEIPTS_BATCH_SIZE=200
export INDEXER_RECEIPTS_CONCURRENCY=10
export INDEXER_CATCHUP_BLOCKS_BATCH_SIZE=10
export INDEXER_CATCHUP_BLOCKS_CONCURRENCY=10

### Type of the installation

Docker-compose

### Type of the JSON RPC archive node

Geth

### Backend version

v5.3.3

### Elixir & Erlang/OTP versions

1.14.5-otp-25

### Additional information

<img width="1326" alt="Screenshot 2023-12-25 at 12 31 08 PM" src="https://github.com/blockscout/blockscout/assets/34902315/59b600a8-5da5-417f-bf0e-0c4c860241b7">

**Comment by vbaranov** [comment]
For Geth variant internal transactions are currently fetched per transaction. So the error is hardly connected to the fact, that chain contains block with 3k trasnactions. Most likely, `debug_traceTransaction` request to the node is failed. You can try to increase timeout for the request via `ETHEREUM_JSONRPC_DEBUG_TRACE_TRANSACTION_TIMEOUT`, which is 5s default. Or configure higher timeout for debug requests on the node.
