### ISSUE TITLE
during bridging the fund  burnt to null address

### ISSUE THREAD

**Issue by rambharose2867** [blockscout/blockscout#9051]
### Description

dear Sir.
my fund 826 USDc while bridging on Rhino.fi and was sent to null address instead of Deposit address

Txn Hash 

0x28aa9956ac4704f9e1e8091a5033944cf69912016ff116c0f5870c37a85e7b32

### Type of the installation

Docker-compose

### Type of the JSON RPC archive node

manta

### Type of the chain

L2

### Link to the page

https://pacific-bridge.manta.network/

### Steps to reproduce

rhino. fi
transfer funds manta to zksync era
usdc

### Backend version

NANA

### Elixir & Erlang/OTP versions

not aware

### Operating system

windows

### Additional information

please help

**Comment by vbaranov** [comment]
This chat is for Blockscout-related questions. Your question is out of scope, where the Blockscout team can help.
