### ISSUE TITLE
Can't verify my contract

### ISSUE THREAD

**Issue by FEEDZED** [blockscout/blockscout#9064]
### Description

I deployed my custom smart contract on metis using the thirdweb soidity SDK but now when I try to verify it manually (metis verification not supportd by thirdweb at the moment) it says the following "No contract could be verified with provided data"

### Type of the installation

Manual from the source code

### Type of the JSON RPC archive node

geth

### Type of the chain

l2

### Link to the page

https://andromeda-explorer.metis.io/address/0xc3D3B71710Cb726902D065A6efB9aac32AFB8AF5/verify-via-flattened-code/new

### Steps to reproduce

just try to verify the smart contract

### Backend version

v5.3.2-beta

### Elixir & Erlang/OTP versions

Elixir 1.14.5 Erlang/OTP 24

### Operating system

windows

### Additional information

The issue happened at Andromeda Blockscout instance

**Comment by ekawibisono** [comment]
Hi @FEEDZED , your Contract has been Verify. Please Check again
