### ISSUE TITLE
ETH Transaction Not Completed, Reciever Wallet incompatible with Base Network?

### ISSUE THREAD

**Issue by JWags85** [blockscout/blockscout#9070]
### Description

I sent 2 different ETH transactions on the Coinbase via the Base network.  However they never reached the receiver wallet and the transactions show up nowhere outside of Basescan.  The wallet appears empty to the receiver but Coinbase cannot do anything cause to them the transaction is "completed".  Any assistance in reversing or salvaging the ETH lost would be appreciated.

Thank you

### Type of the installation

Docker-compose

### Type of the JSON RPC archive node

OpenEthereum

### Link to the page

https://base.blockscout.com/address/0x9B6d07284bE1a112875660c92185c59050B4E797

### Backend version

v5.4.0-beta.+commit.63747320

### Frontend version

v1.20.0+e0c4f572

### Elixir & Erlang/OTP versions

Elixir 1.14.5

### Operating system

MacOS

### Additional information

**User Agent:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36

**Comment by vbaranov** [comment]
This chat is for Blockscout-related questions. Your question is out of scope, where the Blockscout team can help.
