### ISSUE TITLE
Address network not supported 

### ISSUE THREAD

**Issue by Bogdanel0184** [blockscout/blockscout#9074]
### Description

Hi, 
I have transferred yesterday morning from my trading platform to another platform $505 ( tether )but the money never arrived to the platform supposed to arrive as they don't support KAVA EVM CO-CHAIN network. It's any way I can recover my assets? 
Thank you for your help!

### Type of the installation

Docker-compose

### Type of the JSON RPC archive node

geth

### Backend version

v5.3.3-kava

### Elixir & Erlang/OTP versions

Elixir 1.14.5 Erlang/OTP 25

### Operating system

unix linux

### Additional information

The issue happened at Kava 10 Blockscout instance

**Comment by vbaranov** [comment]
This chat is for Blockscout-related questions. Your question is out of scope, where the Blockscout team can help.
