### ISSUE TITLE
My transfer is still didn’t show up in the Trust wallet

### ISSUE THREAD

**Issue by Xyden2019** [blockscout/blockscout#9077]
### Description

I transferred USD from KuCoin to my Trust wallet, and it still not in my account
![IMG_9714](https://github.com/blockscout/blockscout/assets/155246714/d22d3dfe-bc68-4652-808a-224ab743d701)

### Type of the installation

Docker-compose

### Type of the JSON RPC archive node

geth

### Backend version

v5.3.3-kava

### Elixir & Erlang/OTP versions

Elixir 1.14.5 Erlang/OTP 25

### Operating system

unix linux

### Additional information

The issue happened at Kava 10 Blockscout instance

**Comment by ekawibisono** [comment]
this blockscout issue, please you can contact kava evm, thank you
