### ISSUE TITLE
Deploying v5.3.3-beta version in docker-compose mode, startup failed

### ISSUE THREAD

**Issue by yzh-d** [blockscout/blockscout#9089]
### Description

The v5.2.3-beta version was successfully deployed before. Now I want to follow blockscout to upgrade the version to v5.3.3-beta. After all configurations are modified, use the command: docker-compose up, but the startup fails.

Error content：dependency failed to start: container docker-compose-db-init-1 exited (0)
Startup log：
[+] Running 6/6
 ✔ sig-provider Pulled                                                                                                            1.8s
 ✔ stats Pulled                                                                                                                   1.8s
 ✔ frontend Pulled                                                                                                                1.7s
 ✔ smart-contract-verifier Pulled                                                                                                 2.0s
 ✔ visualizer Pulled                                                                                                              2.1s
 ✔ backend Pulled                                                                                                                 2.2s
[+] Running 13/13
 ✔ Network docker-compose_default            Created                                                                              0.1s
 ✔ Container redis_db                        Created                                                                              0.1s
 ✔ Container sig-provider                    Created                                                                              0.1s
 ✔ Container docker-compose-db-init-1        Created                                                                              0.1s
 ✔ Container smart-contract-verifier         Created                                                                              0.1s
 ✔ Container visualizer                      Created                                                                              0.1s
 ✔ Container docker-compose-stats-db-init-1  Created                                                                              0.1s
 ✔ Container db                              Created                                                                              0.0s
 ✔ Container blockscout-5.3.3                Created                                                                              0.0s
 ✔ Container stats-postgres                  Created                                                                              0.0s
 ✔ Container frontend                        Created                                                                              0.0s
 ✔ Container stats                           Created                                                                              0.0s
 ✔ Container proxy                           Created                                                                              0.0s
Attaching to blockscout-5.3.3, db, docker-compose-db-init-1, docker-compose-stats-db-init-1, frontend, proxy, redis_db, sig-provider, smart-contract-verifier, stats, stats-postgres, visualizer
visualizer                      | 2024-01-02T03:34:44.481661Z  INFO visualizer_server::run: starting http server on addr 0.0.0.0:8050
visualizer                      | 2024-01-02T03:34:44.482540Z  INFO actix_server::builder: Starting 16 workers
visualizer                      | 2024-01-02T03:34:44.482622Z  INFO actix_server::server: Tokio runtime found; starting in existing Tokio runtime
visualizer                      | 2024-01-02T03:34:44.483038Z  INFO visualizer_server::run: starting grpc server on addr 0.0.0.0:8051
sig-provider                    | 2024-01-02T03:34:44.721029Z  INFO blockscout_service_launcher::launch: starting http server on addr 0.0.0.0:8050
sig-provider                    | 2024-01-02T03:34:44.722047Z  INFO actix_server::builder: Starting 16 workers
sig-provider                    | 2024-01-02T03:34:44.722093Z  INFO blockscout_service_launcher::launch: starting grpc server on addr 0.0.0.0:8051
sig-provider                    | 2024-01-02T03:34:44.722179Z  INFO actix_server::server: Tokio runtime found; starting in existing Tokio runtime
redis_db                        | 1:C 02 Jan 2024 03:34:44.794 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
redis_db                        | 1:C 02 Jan 2024 03:34:44.795 # Redis version=7.0.12, bits=64, commit=00000000, modified=0, pid=1, just started
redis_db                        | 1:C 02 Jan 2024 03:34:44.795 # Warning: no config file specified, using the default config. In order to specify a config file use redis-server /path/to/redis.conf
redis_db                        | 1:M 02 Jan 2024 03:34:44.795 * monotonic clock: POSIX clock_gettime
redis_db                        | 1:M 02 Jan 2024 03:34:44.796 * Running mode=standalone, port=6379.
redis_db                        | 1:M 02 Jan 2024 03:34:44.796 # WARNING: The TCP backlog setting of 511 cannot be enforced because /proc/sys/net/core/somaxconn is set to the lower value of 128.
redis_db                        | 1:M 02 Jan 2024 03:34:44.796 # Server initialized
redis_db                        | 1:M 02 Jan 2024 03:34:44.796 # WARNING Memory overcommit must be enabled! Without it, a background save or replication may fail under low memory condition. Being disabled, it can can also cause failures without low memory condition, see https://github.com/jemalloc/jemalloc/issues/1328. To fix this issue add 'vm.overcommit_memory = 1' to /etc/sysctl.conf and then reboot or run the command 'sysctl vm.overcommit_memory=1' for this to take effect.
redis_db                        | 1:M 02 Jan 2024 03:34:44.796 * Loading RDB produced by version 7.0.12
redis_db                        | 1:M 02 Jan 2024 03:34:44.796 * RDB age 252 seconds
redis_db                        | 1:M 02 Jan 2024 03:34:44.796 * RDB memory usage when created 0.82 Mb
redis_db                        | 1:M 02 Jan 2024 03:34:44.796 * Done loading RDB, keys loaded: 0, keys expired: 0.
redis_db                        | 1:M 02 Jan 2024 03:34:44.797 * DB loaded from disk: 0.000 seconds
redis_db                        | 1:M 02 Jan 2024 03:34:44.797 * Ready to accept connections
docker-compose-stats-db-init-1 exited with code 0
docker-compose-db-init-1 exited with code 0
dependency failed to start: container docker-compose-db-init-1 exited (0)

### Type of the installation

Docker-compose

### Type of the JSON RPC archive node

ganache

### Type of the chain

L1

### Backend version

v5.3.3-beta

### Elixir & Erlang/OTP versions

Elixir 1.13.0 (compiled with Erlang/OTP 24)

### Operating system

Linux

**Comment by ekawibisono** [comment]
hello, if you have a problem using linux centos, please direct dm me on [Telegram](https://t.me/eka_wibisono1)

**Comment by yzh-d** [comment]
> Telegram

Already contacted you on Telegram

**Comment by ekawibisono** [comment]
> > Telegram
> 
> Already contacted you on Telegram

on reply your message
