### ISSUE TITLE
I sent through wrong network 

### ISSUE THREAD

**Issue by Tonytregenza** [blockscout/blockscout#9091]
### Description

I sent through wrong network,  recipient doesn't use base platform.  

### Type of the installation

Docker-compose

### Type of the JSON RPC archive node

Idk

### Type of the chain

Idk

### Link to the page

https://base.blockscout.com/tx/0x2a36a0075e1a8169b0b6a74b0c0b2b041dcd9a292b9b784e26e94b64939260d5

### Backend version

v5.4.0-beta.+commit.63747320

### Frontend version

v1.20.0+e0c4f572

### Elixir & Erlang/OTP versions

Idk

### Operating system

Windows 

### Additional information

**User Agent:** Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Mobile Safari/537.36

**Comment by sl1depengwyn** [comment]
This repo is for Blockscout-related questions. Blockscout is an open source blockchain explorer, so we do not host this chain ourself, only explorer. Thus, your question is out of scope, where the Blockscout team can help, you better contact the chain support directly.

**Comment by Tonytregenza** [comment]
Ok, yeah im not very crypto savvy, what chain support and how do I
contact them? Any help or input would be much appreciated.  Thank you
