### ISSUE TITLE
Sent etherum using wrong network

### ISSUE THREAD

**Issue by anvesh434** [blockscout/blockscout#9092]
### Description

I have used base network to complete a transaction which i would like to get reversed so that i can use right network to make this transaction.
Details of transaction:
Used coinbase to perform below transaction.
address: 0xe9ba8EfC88EFa7CABa9F057c763ecb124ef4e301
Network: base
Transaction hash: 0x4d1f18b75e82e0058f86056bade1fcd81af767b0d62ec9a0406f63e93ecbb97c
Date: 9:58pm- Jan 2,2024
Link- https://base.blockscout.com/tx/0x4d1f18b75e82e0058f86056bade1fcd81af767b0d62ec9a0406f63e93ecbb97c

### Type of the installation

Docker-compose

### Type of the JSON RPC archive node

N/A

### Backend version

V5.0

### Elixir & Erlang/OTP versions

1.14.5

**Comment by sl1depengwyn** [comment]
This repo is for Blockscout-related questions. Blockscout is an open source blockchain explorer, so we do not host this chain ourself, only explorer. Thus, your question is out of scope, where the Blockscout team can help, you better contact the chain support directly.
