### ISSUE TITLE
Lost USDT transferring to CoinBase from KuCoin

### ISSUE THREAD

**Issue by Jwear24** [blockscout/blockscout#9096]
### Description

Attempted to transfer USDT from KuCoin to CoinBase, but CoinBase only supports ERC-20. I have information about the transaction I can supply once someone is assigned to this ticket

### Type of the installation

Docker-compose

### Type of the JSON RPC archive node

geth

### Backend version

v5.3.3-kava

### Elixir & Erlang/OTP versions

Elixir 1.14.5 Erlang/OTP 25

### Operating system

unix linux

### Additional information

The issue happened at Kava 10 Blockscout instance

**Comment by sl1depengwyn** [comment]
This repo is for Blockscout-related questions. Blockscout is an open source blockchain explorer, so we do not host this chain ourselves. Thus, your question is out of scope, where the Blockscout team can help, you better contact the chain support directly.

**Comment by Jwear24** [comment]
I used Kavascan to send crypto. Do you have a contact for their support? I’m having trouble finding it.

On Jan 3, 2024, at 12:31 PM, Maxim Filonov ***@***.***> wrote:

﻿

CAUTION: This email originated from outside your organization. Exercise caution when opening attachments or clicking links, especially from unknown senders.

Closed #9096<https://github.com/blockscout/blockscout/issues/9096> as completed.
