### ISSUE TITLE
Network utilization >100% on Filecoin

### ISSUE THREAD

**Issue by yvaskov** [blockscout/blockscout#9128]
## Description

https://filecoin.blockscout.com/api/v2/stats returns
```
"network_utilization_percentage": 113.4415791586
```
![Image](https://github.com/blockscout/blockscout/assets/72267126/5d70de58-e89b-413b-b95e-48f2dac15036)

## Version

[v5.4.0-beta.+commit.26ebc041](https://github.com/blockscout/blockscout/commit/26ebc041)

**Comment by vbaranov** [comment]
The node can return gas used > gas limit
```
curl -s -H "Content-Type: application/json" -X POST --data '{"jsonrpc":"2.0","method":"eth_getBlockByNumber","params":["0x367D1C", false],"id":1}' https://api.node.glif.io/  | jq -r .result.gasLimit

0x2540be400

curl -s -H "Content-Type: application/json" -X POST --data '{"jsonrpc":"2.0","method":"eth_getBlockByNumber","params":["0x367D1C", false],"id":1}' https://api.node.glif.io/  | jq -r .result.gasUsed
0x28a13aaf7
```

**Comment by vbaranov** [comment]
This has been resolved on Lotus FEVM side https://github.com/filecoin-project/lotus/issues/11721.
