### ISSUE TITLE
No FIL price on Filecoin

### ISSUE THREAD

**Issue by yvaskov** [blockscout/blockscout#9129]
## Description

Filecoin has no price for FIL: 
https://filecoin.blockscout.com/api/v2/stats
```
"coin_price": null
```
https://filecoin.blockscout.com/api/v2/addresses/0x7B90337f65fAA2B2B8ed583ba1Ba6EB0C9D7eA44
```
"exchange_rate": null
```

## Version

[v5.4.0-beta.+commit.26ebc041](https://github.com/blockscout/blockscout/commit/26ebc041)

**Comment by vbaranov** [comment]
Resolved
