### ISSUE TITLE
'Error fetching schema' in GraphQL docs

### ISSUE THREAD

**Issue by yvaskov** [blockscout/blockscout#9135]
## Description

For example https://eth-goerli.blockscout.com/graphiql
![Image](https://github.com/blockscout/blockscout/assets/72267126/d8fc0a3a-8abb-4a91-9851-e0b64a179a20)

## Version

**v5.4.0+**

**Comment by philliprossii7** [comment]
Was able to fetch on Go

**Comment by philliprossii7** [comment]
> ## Response to Bug
> 

> Was able to fetch on Go.
> For example https://eth-goerli.blockscout.com/graphiql
> ![Image](https://github.com/blockscout/blockscout/assets/72267126/d8fc0a3a-8abb-4a91-9851-e0b64a179a20)
> 
> ## Version
> 
> **v5.4.0+**
>

**Comment by philliprossii7** [comment]
> > ## Response Image

![image](https://github.com/blockscout/blockscout/assets/71346231/52f92989-78d1-4311-b95b-a934c853a933)
