### ISSUE TITLE
Ican`t claim eth(Ethreum mainnet)

### ISSUE THREAD

**Issue by pocchi555** [blockscout/blockscout#9156]
### Description

I bridged from ETH(ZORA) to ETH(Ethreum mainnet).
I wanna claim,but it is not reaction the claim button.

transaction ID
0xc5cf0ceb29422c26513e04df175b02452986007890c5292e25b5224d484956ed

### Type of the installation

Docker-compose

### Type of the JSON RPC archive node

ZORA, ETH mainnet

### Type of the chain

L1

### Link to the page

https://bridge.zora.energy/transactions?tab=withdrawals

### Backend version

v5.4.0-beta.+commit.63747320

### Elixir & Erlang/OTP versions

Elixir

### Additional information

**User Agent:** Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36

**Comment by sl1depengwyn** [comment]
This repo is for Blockscout-related questions. Blockscout is an open source blockchain explorer, so we do not host this chain ourselves. Thus, your question is out of scope, where the Blockscout team can help, you better contact the chain support directly.
