### ISSUE TITLE
Various errors while trying to run the project for the first time

### ISSUE THREAD

**Issue by megalepozy** [blockscout/blockscout#9170]
### Description

Hi,

A fresh install without a frontend resulted in a log with various errors at the start and repeating messages from that point forward.

I'll just add that Erigon seems to work correctly and is accessible as I successfully work against it with ethereum-etl on the same network, url and port.

If any other information is needed (added the logs in the additional information) please let me know.

Thanks a lot for this amazing project!

### Type of the installation

Docker-compose

### Type of the JSON RPC archive node

Erigon

### Type of the chain

Ethereum mainnet

### Steps to reproduce

1. Start Erigon - docker run -it --rm --name erigon -p 9090:9090 -p 42069:42069/tcp -p 42069:42069/udp -p 8545:8545 -p 8546:8546 -p 8551:8551 -p 30303:30303/tcp -p 30303:30303/udp -p 30304:30304/tcp -p 30304:30304/udp -p 9091:9091 -p 9092:9092 -p 9093:9093 -p 9094:9094 -p 4000:4000/udp -p 4001:4001/tcp -p 5555:5555 -p 6060:6060 --mount type=bind,source=/media/erigonSpace,target=/media/erigonSpace --network 2moira-net thorax/erigon --snapshots --datadir=/media/erigonSpace --private.api.addr=localhost:9090 --snap.keepblocks=true --chain=mainnet --http=true --http.addr=0.0.0.0 --http.port=8545 --nodiscover=true --maxpeers=0 --no-downloader=true --rpc.batch.limit=300
2. Update external-frontend.yml backend to:
`  
  backend:
    depends_on:
      - db
      - redis_db
    extends:
      file: ./services/backend.yml
      service: backend
    build:
      context: ..
      dockerfile: ./docker/Dockerfile
      args:
        DISABLE_WEBAPP: "true"
        API_V1_READ_METHODS_DISABLED: "false"
        API_V1_WRITE_METHODS_DISABLED: "false"
        RELEASE_VERSION: 6.0.0
    links:
      - db:database
    environment:
        ETHEREUM_JSONRPC_VARIANT: "erigon"
        ETHEREUM_JSONRPC_TRACE_URL: "http://172.19.0.2:8545/"
        ETHEREUM_JSONRPC_HTTP_URL: "http://172.19.0.2:8545/"
        INDEXER_MEMORY_LIMIT: "50Gb"
`
3. Add network to external-frontend.yml so it would be on the same network as Erigon:
`
networks:
  network1:
    name: 2moira-net
    external: true
`
4. I also updated the relevant services yml files to use a specific folder on the host (checked and data is saved correctly)
5. Run with the following command (removed -d to c the logs)
> docker-compose -f external-frontend.yml up

### Backend version

v6.0.0

### Elixir & Erlang/OTP versions

no clue, whatever is retrieved with docker-compose

### Operating system

Ubuntu 23.10

### Additional information

The following are specific messages from the logs which show the amount of issues I seem to get (they r ordered chronologically):

db                              | chmod: changing permissions of '/var/run/postgresql': Operation not permitted
db                              | The files belonging to this database system will be owned by user "postgres".

stats-postgres                  | chmod: changing permissions of '/var/run/postgresql': Operation not permitted
stats-postgres                  | The files belonging to this database system will be owned by user "postgres".

db                              | 2024-01-15 17:05:20.000 UTC [66] ERROR:  database "blockscout" already exists
db                              | 2024-01-15 17:05:20.000 UTC [66] STATEMENT:  CREATE DATABASE "blockscout" ENCODING 'UTF8'

stats-postgres                  | 2024-01-15 17:05:21.481 UTC [61] ERROR:  database "stats" already exists
stats-postgres                  | 2024-01-15 17:05:21.481 UTC [61] STATEMENT:  CREATE DATABASE "stats"

db                              | 2024-01-15 17:05:21.563 UTC [72] ERROR:  relation "transactions" does not exist at character 266
db                              | 2024-01-15 17:05:21.563 UTC [72] STATEMENT:  
db                              | 	                SELECT 
db                              | 	                    first_tx.date as date,
db                              | 	                    count(*) as value
db                              | 	                FROM (
db                              | 	                    SELECT DISTINCT ON (t.from_address_hash)
db                              | 	                        b.timestamp::date as date
db                              | 	                    FROM transactions  t
db                              | 	                    JOIN blocks        b ON t.block_hash = b.hash
db                              | 	                    WHERE 
db                              | 	                        b.timestamp != to_timestamp(0) AND 
stats                           | 2024-01-15T17:05:21.563945Z ERROR stats_server::update_service: error during updating chart: blockscout database error: Query Error: error returned from database: relation "transactions" does not exist chart="accountsGrowth"
db                              | 	                        b.consensus = true
stats                           | 2024-01-15T17:05:21.563964Z  INFO stats_server::update_service: updating chart chart="averageBlockSize"
db                              | 	                    ORDER BY t.from_address_hash, b.timestamp
db                              | 	                ) first_tx
db                              | 	                GROUP BY first_tx.date;
db                              | 	                
db                              | 	                
stats                           | 2024-01-15T17:05:21.564045Z  INFO stats_server::update_service: scheduled next run of chart update in 42878.435966984s chart="accountsGrowth"
db                              | 2024-01-15 17:05:21.564 UTC [72] ERROR:  relation "blocks" does not exist at character 42
db                              | 2024-01-15 17:05:21.564 UTC [72] STATEMENT:  SELECT MIN("number") AS "min_block" FROM "blocks" WHERE "blocks"."consensus" = $1 LIMIT $2
stats                           | 2024-01-15T17:05:21.564307Z ERROR stats_server::update_service: error during updating chart: blockscout database error: Query Error: error returned from database: relation "blocks" does not exist chart="averageBlockSize"

The above issue of non-existing "blocks"/"transactions" relation keep occurring with various statements.

backend                         | {"time":"2024-01-15T17:05:22.873Z","severity":"info","message":"== Running 20180117221922 Explorer.Repo.Migrations.CreateBlocks.change/0 forward","metadata":{}}
backend                         | {"time":"2024-01-15T17:05:22.873Z","severity":"info","message":"create table blocks","metadata":{}}
backend                         | {"time":"2024-01-15T17:05:22.879Z","severity":"info","message":"create index blocks_timestamp_index","metadata":{}}
backend                         | {"time":"2024-01-15T17:05:22.882Z","severity":"info","message":"create index one_consensus_child_per_parent","metadata":{}}
backend                         | {"time":"2024-01-15T17:05:22.884Z","severity":"info","message":"create index one_consensus_block_at_height","metadata":{}}
backend                         | {"time":"2024-01-15T17:05:22.886Z","severity":"info","message":"== Migrated 20180117221922 in 0.0s","metadata":{}}
backend                         | {"time":"2024-01-15T17:05:22.889Z","severity":"info","message":"== Running 20180117221923 Explorer.Repo.Migrations.CreateTransactions.change/0 forward","metadata":{}}
backend                         | {"time":"2024-01-15T17:05:22.889Z","severity":"info","message":"create table transactions","metadata":{}}

backend                         | Success!
backend                         | warning: redefining module ConfigHelper (current version defined in memory)
backend                         |   config/config_helper.exs:1
backend                         | 
backend                         | 
backend                         | warning: redefining module ConfigHelper (current version defined in memory)
backend                         |   config/config_helper.exs:1
backend                         | 
backend                         | 
backend                         | {"time":"2024-01-15T17:05:26.865Z","severity":"info","message":"[Que] Booting Que","metadata":{}}
backend                         | {"time":"2024-01-15T17:05:26.865Z","severity":"info","message":"[Que] Booting Server Supervisor for Workers","metadata":{}}
backend                         | {"time":"2024-01-15T17:05:26.926Z","severity":"info","message":"tx/per day chart: collect records for txs per day stats","metadata":{}}
backend                         | {"time":"2024-01-15T17:05:26.926Z","severity":"info","message":"tx/per day chart: earliest date 2024-01-06 00:00:00Z","metadata":{}}
backend                         | {"time":"2024-01-15T17:05:26.926Z","severity":"info","message":"tx/per day chart: latest date 2024-01-06 23:59:59Z","metadata":{}}
backend                         | {"time":"2024-01-15T17:05:26.964Z","severity":"info","message":"tx/per day chart: timestamp cannot be converted to min/max blocks, trying to find min/max blocks through a fallback option}","metadata":{}}
backend                         | {"time":"2024-01-15T17:05:26.965Z","severity":"warn","message":"tx/per day chart: failed to get min/max blocks through a fallback option}","metadata":{}}
backend                         | {"time":"2024-01-15T17:05:26.965Z","severity":"info","message":"tx/per day chart: collect records for txs per day stats","metadata":{}}
backend                         | {"time":"2024-01-15T17:05:26.965Z","severity":"info","message":"tx/per day chart: earliest date 2024-01-07 00:00:00Z","metadata":{}}
backend                         | {"time":"2024-01-15T17:05:26.965Z","severity":"info","message":"tx/per day chart: latest date 2024-01-07 23:59:59Z","metadata":{}}
backend                         | {"time":"2024-01-15T17:05:26.967Z","severity":"info","message":"tx/per day chart: timestamp cannot be converted to min/max blocks, trying to find min/max blocks through a fallback option}","metadata":{}}
backend                         | {"time":"2024-01-15T17:05:26.968Z","severity":"warn","message":"tx/per day chart: failed to get min/max blocks through a fallback option}","metadata":{}}
backend                         | {"time":"2024-01-15T17:05:26.968Z","severity":"info","message":"tx/per day chart: collect records for txs per day stats","metadata":{}}
backend                         | {"time":"2024-01-15T17:05:26.968Z","severity":"info","message":"tx/per day chart: earliest date 2024-01-08 00:00:00Z","metadata":{}}
backend                         | {"time":"2024-01-15T17:05:26.968Z","severity":"info","message":"tx/per day chart: latest date 2024-01-08 23:59:59Z","metadata":{}}
backend                         | {"time":"2024-01-15T17:05:26.970Z","severity":"info","message":"tx/per day chart: timestamp cannot be converted to min/max blocks, trying to find min/max blocks through a fallback option}","metadata":{}}
backend                         | {"time":"2024-01-15T17:05:26.972Z","severity":"warn","message":"tx/per day chart: failed to get min/max blocks through a fallback option}","metadata":{}}
backend                         | {"time":"2024-01-15T17:05:26.972Z","severity":"info","message":"tx/per day chart: collect records for txs per day stats","metadata":{}}
backend                         | {"time":"2024-01-15T17:05:26.972Z","severity":"info","message":"tx/per day chart: earliest date 2024-01-09 00:00:00Z","metadata":{}}
backend                         | {"time":"2024-01-15T17:05:26.972Z","severity":"info","message":"tx/per day chart: latest date 2024-01-09 23:59:59Z","metadata":{}}
backend                         | {"time":"2024-01-15T17:05:26.974Z","severity":"info","message":"tx/per day chart: timestamp cannot be converted to min/max blocks, trying to find min/max blocks through a fallback option}","metadata":{}}
backend                         | {"time":"2024-01-15T17:05:26.975Z","severity":"warn","message":"tx/per day chart: failed to get min/max blocks through a fallback option}","metadata":{}}
backend                         | {"time":"2024-01-15T17:05:26.975Z","severity":"info","message":"tx/per day chart: collect records for txs per day stats","metadata":{}}
backend                         | {"time":"2024-01-15T17:05:26.975Z","severity":"info","message":"tx/per day chart: earliest date 2024-01-10 00:00:00Z","metadata":{}}
backend                         | {"time":"2024-01-15T17:05:26.975Z","severity":"info","message":"tx/per day chart: latest date 2024-01-10 23:59:59Z","metadata":{}}
backend                         | {"time":"2024-01-15T17:05:26.977Z","severity":"info","message":"tx/per day chart: timestamp cannot be converted to min/max blocks, trying to find min/max blocks through a fallback option}","metadata":{}}
backend                         | {"time":"2024-01-15T17:05:26.978Z","severity":"warn","message":"tx/per day chart: failed to get min/max blocks through a fallback option}","metadata":{}}
backend                         | {"time":"2024-01-15T17:05:26.978Z","severity":"info","message":"tx/per day chart: collect records for txs per day stats","metadata":{}}
backend                         | {"time":"2024-01-15T17:05:26.978Z","severity":"info","message":"tx/per day chart: earliest date 2024-01-11 00:00:00Z","metadata":{}}
backend                         | {"time":"2024-01-15T17:05:26.978Z","severity":"info","message":"tx/per day chart: latest date 2024-01-11 23:59:59Z","metadata":{}}
backend                         | {"time":"2024-01-15T17:05:26.981Z","severity":"info","message":"tx/per day chart: timestamp cannot be converted to min/max blocks, trying to find min/max blocks through a fallback option}","metadata":{}}
backend                         | {"time":"2024-01-15T17:05:26.982Z","severity":"warn","message":"tx/per day chart: failed to get min/max blocks through a fallback option}","metadata":{}}
backend                         | {"time":"2024-01-15T17:05:26.982Z","severity":"info","message":"tx/per day chart: collect records for txs per day stats","metadata":{}}
backend                         | {"time":"2024-01-15T17:05:26.982Z","severity":"info","message":"tx/per day chart: earliest date 2024-01-12 00:00:00Z","metadata":{}}
backend                         | {"time":"2024-01-15T17:05:26.982Z","severity":"info","message":"tx/per day chart: latest date 2024-01-12 23:59:59Z","metadata":{}}
backend                         | {"time":"2024-01-15T17:05:26.983Z","severity":"info","message":"Running BlockScoutWeb.Endpoint with cowboy 2.10.0 at 0.0.0.0:4000 (http)","metadata":{}}
backend                         | {"time":"2024-01-15T17:05:26.984Z","severity":"info","message":"tx/per day chart: timestamp cannot be converted to min/max blocks, trying to find min/max blocks through a fallback option}","metadata":{}}
backend                         | {"time":"2024-01-15T17:05:26.985Z","severity":"info","message":"Access BlockScoutWeb.Endpoint at ://:4000","metadata":{}}
backend                         | {"time":"2024-01-15T17:05:26.985Z","severity":"warn","message":"tx/per day chart: failed to get min/max blocks through a fallback option}","metadata":{}}
backend                         | {"time":"2024-01-15T17:05:26.985Z","severity":"info","message":"tx/per day chart: collect records for txs per day stats","metadata":{}}
backend                         | {"time":"2024-01-15T17:05:26.985Z","severity":"info","message":"tx/per day chart: earliest date 2024-01-13 00:00:00Z","metadata":{}}
backend                         | {"time":"2024-01-15T17:05:26.985Z","severity":"info","message":"tx/per day chart: latest date 2024-01-13 23:59:59Z","metadata":{}}
backend                         | {"time":"2024-01-15T17:05:26.987Z","severity":"info","message":"tx/per day chart: timestamp cannot be converted to min/max blocks, trying to find min/max blocks through a fallback option}","metadata":{}}
backend                         | {"time":"2024-01-15T17:05:26.989Z","severity":"warn","message":"tx/per day chart: failed to get min/max blocks through a fallback option}","metadata":{}}
backend                         | {"time":"2024-01-15T17:05:26.989Z","severity":"info","message":"tx/per day chart: collect records for txs per day stats","metadata":{}}
backend                         | {"time":"2024-01-15T17:05:26.989Z","severity":"info","message":"tx/per day chart: earliest date 2024-01-14 00:00:00Z","metadata":{}}
backend                         | {"time":"2024-01-15T17:05:26.989Z","severity":"info","message":"tx/per day chart: latest date 2024-01-14 23:59:59Z","metadata":{}}
backend                         | {"time":"2024-01-15T17:05:26.991Z","severity":"info","message":"tx/per day chart: timestamp cannot be converted to min/max blocks, trying to find min/max blocks through a fallback option}","metadata":{}}
backend                         | {"time":"2024-01-15T17:05:26.992Z","severity":"info","message":"Index already caught up.","metadata":{"fetcher":"block_catchup","first_block_number":null,"last_block_number":null,"missing_block_count":0,"shrunk":false}}
backend                         | {"time":"2024-01-15T17:05:26.992Z","severity":"info","message":"Checking if index needs to catch up in 5000ms.","metadata":{"fetcher":"block_catchup"}}
backend                         | {"time":"2024-01-15T17:05:26.993Z","severity":"warn","message":"tx/per day chart: failed to get min/max blocks through a fallback option}","metadata":{}}
backend                         | {"time":"2024-01-15T17:05:26.993Z","severity":"info","message":"tx/per day chart: collect records for txs per day stats","metadata":{}}
backend                         | {"time":"2024-01-15T17:05:26.993Z","severity":"info","message":"tx/per day chart: records collected [%{date: ~D[2024-01-14], gas_used: 0, number_of_transactions: 0, total_fee: 0}, %{date: ~D[2024-01-13], gas_used: 0, number_of_transactions: 0, total_fee: 0}, %{date: ~D[2024-01-12], gas_used: 0, number_of_transactions: 0, total_fee: 0}, %{date: ~D[2024-01-11], gas_used: 0, number_of_transactions: 0, total_fee: 0}, %{date: ~D[2024-01-10], gas_used: 0, number_of_transactions: 0, total_fee: 0}, %{date: ~D[2024-01-09], gas_used: 0, number_of_transactions: 0, total_fee: 0}, %{date: ~D[2024-01-08], gas_used: 0, number_of_transactions: 0, total_fee: 0}, %{date: ~D[2024-01-07], gas_used: 0, number_of_transactions: 0, total_fee: 0}, %{date: ~D[2024-01-06], gas_used: 0, number_of_transactions: 0, total_fee: 0}]","metadata":{}}
backend                         | {"time":"2024-01-15T17:05:26.993Z","severity":"info","message":"tx/per day chart: save records","metadata":{}}
backend                         | {"time":"2024-01-15T17:05:26.995Z","severity":"info","message":"tx/per day chart: number of inserted 10","metadata":{}}
backend                         | {"time":"2024-01-15T17:05:30.344Z","severity":"info","message":"tzdata release in place is from a file last modified Fri, 22 Oct 2021 02:20:47 GMT. Release file on server was last modified Fri, 22 Dec 2023 09:25:37 GMT.","metadata":{}}
backend                         | {"time":"2024-01-15T17:05:31.353Z","severity":"info","message":"Tzdata has updated the release from 2021e to 2023d","metadata":{}}

And it keeps repeating:

backend                         | {"time":"2024-01-15T17:25:47.358Z","severity":"info","message":"Start sanitizing of empty blocks. Batch size is 100","metadata":{"fetcher":"empty_blocks_to_refetch"}}
backend                         | {"time":"2024-01-15T17:25:47.361Z","severity":"info","message":"Batch of empty blocks is sanitized","metadata":{"fetcher":"empty_blocks_to_refetch"}}
backend                         | {"time":"2024-01-15T17:25:57.361Z","severity":"info","message":"Start sanitizing of empty blocks. Batch size is 100","metadata":{"fetcher":"empty_blocks_to_refetch"}}
backend                         | {"time":"2024-01-15T17:25:57.364Z","severity":"info","message":"Batch of empty blocks is sanitized","metadata":{"fetcher":"empty_blocks_to_refetch"}}
backend                         | {"time":"2024-01-15T17:26:02.060Z","severity":"info","message":"Index already caught up.","metadata":{"fetcher":"block_catchup","first_block_number":null,"last_block_number":null,"missing_block_count":0,"shrunk":false}}
backend                         | {"time":"2024-01-15T17:26:02.060Z","severity":"info","message":"Checking if index needs to catch up in 25000ms.","metadata":{"fetcher":"block_catchup"}}
backend                         | {"time":"2024-01-15T17:26:07.364Z","severity":"info","message":"Start sanitizing of empty blocks. Batch size is 100","metadata":{"fetcher":"empty_blocks_to_refetch"}}
backend                         | {"time":"2024-01-15T17:26:07.367Z","severity":"info","message":"Batch of empty blocks is sanitized","metadata":{"fetcher":"empty_blocks_to_refetch"}}
backend                         | {"time":"2024-01-15T17:26:17.367Z","severity":"info","message":"Start sanitizing of empty blocks. Batch size is 100","metadata":{"fetcher":"empty_blocks_to_refetch"}}
backend                         | {"time":"2024-01-15T17:26:17.369Z","severity":"info","message":"Batch of empty blocks is sanitized","metadata":{"fetcher":"empty_blocks_to_refetch"}}
backend                         | {"time":"2024-01-15T17:26:27.061Z","severity":"info","message":"Index already caught up.","metadata":{"fetcher":"block_catchup","first_block_number":null,"last_block_number":null,"missing_block_count":0,"shrunk":false}}
backend                         | {"time":"2024-01-15T17:26:27.061Z","severity":"info","message":"Checking if index needs to catch up in 25000ms.","metadata":{"fetcher":"block_catchup"}}
backend                         | {"time":"2024-01-15T17:26:27.370Z","severity":"info","message":"Start sanitizing of empty blocks. Batch size is 100","metadata":{"fetcher":"empty_blocks_to_refetch"}}
backend                         | {"time":"2024-01-15T17:26:27.372Z","severity":"info","message":"Batch of empty blocks is sanitized","metadata":{"fetcher":"empty_blocks_to_refetch"}}
backend                         | {"time":"2024-01-15T17:26:37.372Z","severity":"info","message":"Start sanitizing of empty blocks. Batch size is 100","metadata":{"fetcher":"empty_blocks_to_refetch"}}
backend                         | {"time":"2024-01-15T17:26:37.374Z","severity":"info","message":"Batch of empty blocks is sanitized","metadata":{"fetcher":"empty_blocks_to_refetch"}}
backend                         | {"time":"2024-01-15T17:26:47.374Z","severity":"info","message":"Start sanitizing of empty blocks. Batch size is 100","metadata":{"fetcher":"empty_blocks_to_refetch"}}
backend                         | {"time":"2024-01-15T17:26:47.376Z","severity":"info","message":"Batch of empty blocks is sanitized","metadata":{"fetcher":"empty_blocks_to_refetch"}}
backend                         | {"time":"2024-01-15T17:26:52.062Z","severity":"info","message":"Index already caught up.","metadata":{"fetcher":"block_catchup","first_block_number":null,"last_block_number":null,"missing_block_count":0,"shrunk":false}}
backend                         | {"time":"2024-01-15T17:26:52.062Z","severity":"info","message":"Checking if index needs to catch up in 25000ms.","metadata":{"fetcher":"block_catchup"}}
backend                         | {"time":"2024-01-15T17:26:57.376Z","severity":"info","message":"Start sanitizing of empty blocks. Batch size is 100","metadata":{"fetcher":"empty_blocks_to_refetch"}}
backend                         | {"time":"2024-01-15T17:26:57.379Z","severity":"info","message":"Batch of empty blocks is sanitized","metadata":{"fetcher":"empty_blocks_to_refetch"}}
backend                         | {"time":"2024-01-15T17:27:07.379Z","severity":"info","message":"Start sanitizing of empty blocks. Batch size is 100","metadata":{"fetcher":"empty_blocks_to_refetch"}}
backend                         | {"time":"2024-01-15T17:27:07.381Z","severity":"info","message":"Batch of empty blocks is sanitized","metadata":{"fetcher":"empty_blocks_to_refetch"}}
backend                         | {"time":"2024-01-15T17:27:17.063Z","severity":"info","message":"Index already caught up.","metadata":{"fetcher":"block_catchup","first_block_number":null,"last_block_number":null,"missing_block_count":0,"shrunk":false}}
backend                         | {"time":"2024-01-15T17:27:17.063Z","severity":"info","message":"Checking if index needs to catch up in 25000ms.","metadata":{"fetcher":"block_catchup"}}
backend                         | {"time":"2024-01-15T17:27:17.381Z","severity":"info","message":"Start sanitizing of empty blocks. Batch size is 100","metadata":{"fetcher":"empty_blocks_to_refetch"}}
backend                         | {"time":"2024-01-15T17:27:17.383Z","severity":"info","message":"Batch of empty blocks is sanitized","metadata":{"fetcher":"empty_blocks_to_refetch"}}
backend                         | {"time":"2024-01-15T17:27:27.383Z","severity":"info","message":"Start sanitizing of empty blocks. Batch size is 100","metadata":{"fetcher":"empty_blocks_to_refetch"}}
backend                         | {"time":"2024-01-15T17:27:27.386Z","severity":"info","message":"Batch of empty blocks is sanitized","metadata":{"fetcher":"empty_blocks_to_refetch"}}
backend                         | {"time":"2024-01-15T17:27:37.386Z","severity":"info","message":"Start sanitizing of empty blocks. Batch size is 100","metadata":{"fetcher":"empty_blocks_to_refetch"}}
backend                         | {"time":"2024-01-15T17:27:37.389Z","severity":"info","message":"Batch of empty blocks is sanitized","metadata":{"fetcher":"empty_blocks_to_refetch"}}
backend                         | {"time":"2024-01-15T17:27:42.064Z","severity":"info","message":"Index already caught up.","metadata":{"fetcher":"block_catchup","first_block_number":null,"last_block_number":null,"missing_block_count":0,"shrunk":false}}
backend                         | {"time":"2024-01-15T17:27:42.064Z","severity":"info","message":"Checking if index needs to catch up in 25000ms.","metadata":{"fetcher":"block_catchup"}}
backend                         | {"time":"2024-01-15T17:27:47.389Z","severity":"info","message":"Start sanitizing of empty blocks. Batch size is 100","metadata":{"fetcher":"empty_blocks_to_refetch"}}
backend                         | {"time":"2024-01-15T17:27:47.392Z","severity":"info","message":"Batch of empty blocks is sanitized","metadata":{"fetcher":"empty_blocks_to_refetch"}}
backend                         | {"time":"2024-01-15T17:27:57.392Z","severity":"info","message":"Start sanitizing of empty blocks. Batch size is 100","metadata":{"fetcher":"empty_blocks_to_refetch"}}
backend                         | {"time":"2024-01-15T17:27:57.395Z","severity":"info","message":"Batch of empty blocks is sanitized","metadata":{"fetcher":"empty_blocks_to_refetch"}}
backend                         | {"time":"2024-01-15T17:27:58.229Z","severity":"error","message":"timeout","metadata":{"fetcher":"pending_transaction"}}

**Comment by vbaranov** [comment]
@megalepozy do those errors in the logs prevent explorer to work properly?

**Comment by megalepozy** [comment]
Well I actually found out that I had an issue with the connection to Erigon, since fixing that the last block of messages I wrote above have disappeared and instead I get a ton of other logs of various severities... also Erigon started to rapidly throw WARN level logs where most of them are method=eth_call and err="execution reverted" while the rest got the same method and the err is some sort or another type of err="execution reverted" + some other data like err="execution reverted: Diamond: Function does not exist"

In regards to the explorer, I didn't run the frontend so I don't know. 
I did psql the DB and found that the missing relations (transactions, blocks) got created and getting populated but I'm not sure if everything is being done correctly because of all of the warning & error logs.

**Comment by vbaranov** [comment]
I inspected your logs and nothing is criminal in those erros/warnings there so far. In regards execution reverted errors - most likely it is Blockscout trying to fetch token instance metadata and specific token smart-contract has no proper interface to accomplish that.

**Comment by megalepozy** [comment]
btw the last log message from backend from the first blockscout logs image is severity="error", can that really be ignored?

**Comment by vbaranov** [comment]
Yes, you can ignore those messages.

> btw the last log message from backend from the first blockscout logs image is severity="error", can that really be ignored?

Yes, explorer indexer faced with unknown transfer format. Probably, make sense to lower severity level for this message.

**Comment by megalepozy** [comment]
Perfect, thanks a lot!
