### ISSUE TITLE
Duplicated read methods in API

### ISSUE THREAD

**Issue by vbaranov** [blockscout/blockscout#9175]
https://eth.blockscout.com/token/0x57f1887a8BF19b14fC0dF6Fd9B2acc9Af147eA85?tab=read_contract
https://eth.blockscout.com/api/v2/smart-contracts/0x57f1887a8BF19b14fC0dF6Fd9B2acc9Af147eA85/methods-read?is_custom_abi=false

![Image](https://github.com/blockscout/blockscout/assets/4341812/3df5fec3-48f9-4bc4-af36-9d6c2ede5849)

**Comment by Tura187** [comment]
Read and write

**Comment by Tura187** [comment]
I verified the correct way I didn't use any wallet connect what ever this email said
