### ISSUE TITLE
Docker Compose support?

### ISSUE THREAD

**Issue by zulhfreelancer** [blockscout/blockscout#918]
Hi,

I just found this awesome project. But I couldn't find way to make it up using Docker Compose. Does it possible to have _docker-compose.yml_ for this? That will be super helpful to spin up this explorer easier and faster in many environments.

Thank you. ❤️

**Comment by zulhfreelancer** [comment]
@acravenho you are welcome. Just curious, what does _Kuala Lumpur_ tag means here?

**Comment by acravenho** [comment]
Kuala Lumpur is our internal name for our `v2` release.

**Comment by zulhfreelancer** [comment]
Cool. I live in KL. 🙂

**Comment by zulhfreelancer** [comment]
Noted @konstantinzolotarev, thanks for sharing.

**Comment by tmm360** [comment]
Any update on this, please?

**Comment by Dbhardwaj99** [comment]
Hey, I can create a docker-compose.yml for this... Would love to contribute

**Comment by vbaranov** [comment]
Blockscout provides docker-compose configs https://github.com/blockscout/blockscout/tree/master/docker-compose
