### ISSUE TITLE
HTTPs SSL Record Too Long

### ISSUE THREAD

**Issue by aacostarua** [blockscout/blockscout#9183]
### Description

Trying to run blockscout through 4000 on HTTPS. I have lets encrypt SSL certs I use for my other apps, but don't know if there is a way to point them to use with blockscout.  I used the SSL certs generated in mix from your guys tutorial.  I've retried Nginx redirecting with no luck.  Please let me know how to get this working.

SSL_ERROR_RX_RECORD_TOO_LONG

### Type of the installation

Manual from the source code

### Type of the JSON RPC archive node

OpenEthereum

### Type of the chain

L1

### Link to the page

http://bc4.mycryptobox.com:4000/

### Steps to reproduce

Running with instructions results in not being able to connect over HTTPS to port 4000.

### Backend version

v5.4

### Elixir & Erlang/OTP versions

Elixir 1.14.5 OTP 25

### Operating system

Linux

### Additional information

It was working fine with /etc/hosts originally with no port, but I decided it needed to be only working through port 4000 and removed the config for /etc/hosts.

**Comment by ekawibisono** [comment]
Hello @aacostarua , do you want to connect this https to your domain?

**Comment by aacostarua** [comment]
Allowing blockscout on 4000 to accept HTTPs correct.

**Comment by ekawibisono** [comment]
> Allowing blockscout on 4000 to accept HTTPs correct.

using domain or using ip address ?

**Comment by aacostarua** [comment]
I am using a domain. Look at the link to page.

**Comment by ekawibisono** [comment]
> I am using a domain. Look at the link to page.

Hello @aacostarua you build using manual development right ?

**Comment by aacostarua** [comment]
Yes
