### ISSUE TITLE
Adding the BTCC network on chrome mac os

### ISSUE THREAD

**Issue by mufarrah** [blockscout/blockscout#9191]
### Description

I have an issue while trying to add BTCC network on my mac laptop on chrome on my metamask 

<img width="1241" alt="Screenshot 2024-01-18 at 10 26 34 PM" src="https://github.com/blockscout/blockscout/assets/67714308/3829805a-b3c4-4efc-83ac-9a314681d301">

### Type of the installation

Docker-compose

### Type of the JSON RPC archive node

-

### Backend version

v!

### Elixir & Erlang/OTP versions

-

**Comment by vbaranov** [comment]
Blockscout team doesn't manage this instance of explorer. You should contact directly the network support.
