### ISSUE TITLE
Transfered to different address

### ISSUE THREAD

**Issue by npsrb** [blockscout/blockscout#9199]
### Description

hi, i was having this issue, after claiming the airdrop manta. in the same time it sent to new address : 0xfc59952FF30F605a68E0F40b7b8a39f046420725, what is happening ?

### Type of the installation

Docker-compose

### Type of the JSON RPC archive node

Open ETH

### Link to the page

https://pacific-explorer.manta.network/address/0xfc59952FF30F605a68E0F40b7b8a39f046420725?tab=token_transfers

### Backend version

v.6

### Elixir & Erlang/OTP versions

Elixir

### Additional information

**User Agent:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36

**Comment by sl1depengwyn** [comment]
This repo is for Blockscout-related questions. Blockscout is an open source blockchain explorer, so we do not host this chain ourselves. Thus, your question is out of scope, where the Blockscout team can help, you better contact the chain support directly.
