### ISSUE TITLE
Swap any amount of assets on kroma using iziswap

### ISSUE THREAD

**Issue by ericmanoptr** [blockscout/blockscout#9205]
### Description

I did the task and I don't receive approval from it.

0x02F55D53DcE23B4AA962CC68b0f685f26143Bdb2

### Type of the installation

Docker-compose

### Type of the JSON RPC archive node

0x02F55D53DcE23B4AA962CC68b0f685f26143Bdb2

### Backend version

s

### Elixir & Erlang/OTP versions

s

**Comment by ekawibisono** [comment]
This is blockscout github, you can chat on discord [kroma](https://discord.gg/kroma)
thanks
