### ISSUE TITLE
My fund lost and wallet hack 

### ISSUE THREAD

**Issue by mdashfaqh14** [blockscout/blockscout#9209]
### Description

0x956f8ac5d17ea926ad7fcc4a4a67e4cf99665f26
This address is transferred all my asset,so please help me to recover my asset.

### Type of the installation

Manual from the source code

### Type of the JSON RPC archive node

Manta

### Type of the chain

Manta

### Link to the page

https://pacific-explorer.manta.network/address/0x956f8Ac5d17ea926AD7FCc4a4a67E4cf99665f26?tab=tokens

### Backend version

V6.0.0

### Frontend version

V1.11

### Elixir & Erlang/OTP versions

1.4

### Operating system

Android 

### Additional information

**User Agent:** Mozilla/5.0 (Linux; Android 14; SM-S908E Build/UP1A.231005.007; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/121.0.6167.71 Mobile Safari/537.36 AgentWeb/3.1.0 Mobile Safari/537.36

**Comment by ekawibisono** [comment]
Hello, This is Blockscout Github, You Wrong Issue, Please you can visit discord [manta](https://discord.com/invite/mantanetwork)
thanks
