### ISSUE TITLE
V1 API Unavailability Issue

### ISSUE THREAD

**Issue by Nowalski** [blockscout/blockscout#9228]
### Description

The V1 API for token transactions and general transactions has been inaccessible for several days. Users relying on this API are experiencing disruptions in their applications and services that depend on the data provided by these endpoints.

Affected Endpoints
Token Transactions:

API Endpoint: https://etc.blockscout.com/api/v1/?module=account&action=tokentx&contractaddress=${Tokken_ADDRESS}&address=${walletAddress}&page=1&offset=${numTransactions}
Issue: Unreachable or returning errors.
General Transactions:

API Endpoint: https://etc.blockscout.com/api/v1/?module=account&action=txlist&address=${walletAddress}&page=1&offset=${numTransactions}
Issue: Unreachable or returning errors.
Expected Behavior
Users expect the V1 API to be functional and provide accurate data as per the specified endpoints.

Current Behavior
The API endpoints mentioned above are either returning errors or are completely unreachable.

Steps to Reproduce
Attempt to access the token transactions API endpoint.

Example: https://etc.blockscout.com/api/v1/?module=account&action=tokentx&contractaddress=${Tokken_ADDRESS}&address=${walletAddress}&page=1&offset=${numTransactions}
Attempt to access the general transactions API endpoint.

Example: https://etc.blockscout.com/api/v1/?module=account&action=txlist&address=${walletAddress}&page=1&offset=${numTransactions}
Additional Information
The issue has been persistent for several days.
Users are facing disruptions in their applications and services relying on the V1 API.
It's crucial to resolve this issue promptly to ensure the continuity of services relying on the affected endpoints.
Environment:

API Endpoint: V1
Blockchain: Ethereum Classic
Block Explorer: BlockScout

### Type of the installation

Docker-compose

### Type of the JSON RPC archive node

Geth

### Link to the page

https://etc.blockscout.com/

### Backend version

v6.0.0-beta

### Frontend version

v1.21.2+bdd0a9f4

### Elixir & Erlang/OTP versions

-

### Additional information

**User Agent:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36

**Comment by vbaranov** [comment]
We didn't detect unavailability of indicated API endpoints for such a long period. Indeed, there was a downtime during migration to 6.0.0 release, but about several minutes . Currently, all mentioned API endpoints work fine and should work a bit faster than it was before 6.0.0.

**Comment by Nowalski** [comment]
Well after some Testing,  https://etc.blockscout.com/api/v1/?module=account&action=txlist&address=0x64A03f51c201C05E7FF4F02AfddA2BB14540e34D&page=1&offset=5  Does not work, but that used to work
now 
https://etc.blockscout.com/api?module=account&action=txlist&address=0x64A03f51c201C05E7FF4F02AfddA2BB14540e34D&page=0&&offset=5&sort=asc Works but if i remove the Optional Sorting it does not work, if i Sort by desc it does not work, but the Documentation cleary states it's an Optional Argument and the Desc should work,  so cleary something has changed / or broke things, as i mention again the First URL used to work just fine like 3 weeks ago,

**Comment by Nowalski** [comment]
So, https://etc.blockscout.com/api?module=account&action=txlist&address=0x64A03f51c201C05E7FF4F02AfddA2BB14540e34D&page=0&offset=2&filter_by=from&sort=desc Works, but filter_by=to does not work at all,

https://[etc.blockscout.com/api?module=account&action=txlist&address=0x64A03f51c201C05E7FF4F02AfddA2BB14540e34D&page=0&offset=2&filter_by=to&sort=desc](https://etc.blockscout.com/api?module=account&action=txlist&address=0x64A03f51c201C05E7FF4F02AfddA2BB14540e34D&page=0&offset=2&filter_by=to&sort=desc)
{
    "message": "Something went wrong.",
    "result": null,
    "status": "0"
}

i keep Testing but a lot of Optional Combination does not work but the Documentation does say it works
