### ISSUE TITLE
funds didn't arrive 

### ISSUE THREAD

**Issue by Eliasinc69** [blockscout/blockscout#9238]
### Description

I bridged MANTA from Pacific to Atlantic network (using https://app.manta.network/manta/bridge) but it only took my MANTA from Pacific and never allocated it to Atlantic. And I was never directed to Moonbeam to finalize the transfer.

The transaction ID: 0x282013db8bbf0259230e9f1675a9e6c5e9be66ff2fb96d061ea84d5c161df27e

Please advice and Thank You

### Type of the installation

Docker-compose

### Type of the JSON RPC archive node

n/a

### Link to the page

https://manta-pacific.calderaexplorer.xyz/tx/0x282013db8bbf0259230e9f1675a9e6c5e9be66ff2fb96d061ea84d5c161df27e?tab=index

### Backend version

n/a

### Elixir & Erlang/OTP versions

n/a

**Comment by vbaranov** [comment]
This chat is for Blockscout-related questions. Your question is out of scope, where the Blockscout team can help.
