### ISSUE TITLE
Sent tether over Wrong network. 

### ISSUE THREAD

**Issue by RealAaron42** [blockscout/blockscout#9248]
### Description

I sent a transfer to coinbase from kucoin over your network and coinbase doesn't support you. I goofed and am wondering if I can possibly recover my funds.
![Uploading Screenshot_20240124-082630_Chrome.jpg…]()

Let me know if there is a support process I am to follow

### Type of the installation

Docker-compose

### Type of the JSON RPC archive node

geth

### Backend version

v5.3.3-kava

### Elixir & Erlang/OTP versions

Elixir 1.14.5 Erlang/OTP 25

### Operating system

unix linux

**Comment by vbaranov** [comment]
This chat is for Blockscout-related questions. Your question is out of scope, where the Blockscout team can help.
