### ISSUE TITLE
Ethereum Loss

### ISSUE THREAD

**Issue by davidlee2295** [blockscout/blockscout#9250]
### Description

My ethereum has been lost in transit from Coinbase to Robinhood via base network. I would like to recover these funds. It was transacted on January 20.
Transaction Hash: 0xb42c3a6cdf21d68f94a7190e9e4c23f267fd347e899c24865d3ffca03e5f7015

From:0x6dcbce46a8b494c885d0e7b6817d2b519df64467
To: 0x7889a35858bb4c666df18f7961d35eeac4423b92

### Type of the installation

Docker-compose

### Type of the JSON RPC archive node

?

### Link to the page

https://base.blockscout.com/tx/0xb42c3a6cdf21d68f94a7190e9e4c23f267fd347e899c24865d3ffca03e5f7015?tab=index

### Backend version

v6.0.0-beta.+commit.219f014f

### Frontend version

v1.22.0+d67d6621

### Elixir & Erlang/OTP versions

?

### Additional information

**User Agent:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36

**Comment by vbaranov** [comment]
This chat is for Blockscout-related questions. Your question is out of scope, where the Blockscout team can help.

**Comment by davidlee2295** [comment]
Can you refer me to the team? Email, phone number?
Sunyong Lee

 

    On Wednesday, January 24, 2024 at 11:52:33 PM CST, Victor Baranov ***@***.***> wrote:  
 
 


This chat is for Blockscout-related questions. Your question is out of scope, where the Blockscout team can help.
