### ISSUE TITLE
 Advertising

### ISSUE THREAD

**Issue by bobchandra** [blockscout/blockscout#9255]
### Description

we would like to advertise on the ZK fair chain explorer. How do we do that?  https://scan.zkfair.io/

### Type of the installation

Docker-compose

### Type of the JSON RPC archive node

Na

### Link to the page

https://scan.zkfair.io/tx/0x1221c9e24cb0da957fb4d955ab44fc8fef74833e6d948a56d04a41d1aba8a5c8

### Backend version

v6.0.0-beta

### Frontend version

v1.22.0-alpha+d67d6621

### Elixir & Erlang/OTP versions

Na

### Additional information

**User Agent:** Mozilla/5.0 (iPhone; CPU iPhone OS 16_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) CriOS/120.0.6099.119 Mobile/15E148 Safari/604.1

**Comment by vbaranov** [comment]
Answered in Discord
