### ISSUE TITLE
Can’t Find Transferred Métis Token in Binance web3 wallet 

### ISSUE THREAD

**Issue by DeboBillz** [blockscout/blockscout#9263]
### Description

I cannot find the Métis token 0.28 I transferred from my MetaMask wallet to my Binance Web3 wallet. Nothing has been deposited but the transfer said “success” on Sepolia server. Hash node: 0x449DE62641aCff927b413dd2670d1A4E4082EA62
Please help to rectify this. Thanks.

### Type of the installation

Docker-compose

### Type of the JSON RPC archive node

geth

### Backend version

v5.3.2-beta

### Elixir & Erlang/OTP versions

Elixir 1.14.5 Erlang/OTP 24

### Operating system

unix linux

### Additional information

The issue happened at Metis Sepolia Blockscout instance

**Comment by DeboBillz** [comment]
![IMG_8110](https://github.com/blockscout/blockscout/assets/157706749/26f2e2f0-cc24-43ef-b054-0edf7d159b61)
![IMG_8109](https://github.com/blockscout/blockscout/assets/157706749/f46a1524-42c6-48a1-9fcd-985a4616a316)

**Comment by DeboBillz** [comment]
Please see these screen shots for the narration of the transfer.

**Comment by sl1depengwyn** [comment]
This repo is for Blockscout-related questions. Blockscout is an open source blockchain explorer, so we do not host this chain ourselves. Thus, your question is out of scope, where the Blockscout team can help, you better contact the chain support directly.
