### ISSUE TITLE
More than 7 days have passed but the withdrawal has not arrived.

### ISSUE THREAD

**Issue by Kirill777777777** [blockscout/blockscout#9265]
### Description

I have not received the withdrawal of funds that I made on January 9, although more than a week has passed.

### Type of the installation

Docker

### Type of the JSON RPC archive node

I dont understand

### Link to the page

https://explorer.zora.energy/tx/0x4abbcc047057ad74753229c894196f5547327d9c6de9f27070521b210e7031e0?tab=index

### Backend version

v5.4.0-beta.+commit.63747320

### Elixir & Erlang/OTP versions

Elixir 1.14.5 (compiled with Erlang/OTP 25)

### Operating system

Windows

### Additional information

**User Agent:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/111.0.0.0 Safari/537.36

**Comment by sl1depengwyn** [comment]
This repo is for Blockscout-related questions. Blockscout is an open source blockchain explorer, so we do not host this chain ourselves. Thus, your question is out of scope, where the Blockscout team can help, you better contact the chain support directly.
