### ISSUE TITLE
Extend ETH JSON RPC Proxy API methods

### ISSUE THREAD

**Issue by vbaranov** [blockscout/blockscout#9267]
Currently Blockscout supports

- [x] eth_blockNumber
- [x] eth_getBalance
- [x] eth_getLogs (with paging)

Extend JSON RPC API methods with these:

- [x] eth_gasPrice
- [x] eth_getTransactionCount
- [x] eth_getCode
- [x] eth_getStorageAt
- [x] eth_getBlockByNumber
- [x] eth_getTransactionByHash
- [x] eth_getTransactionReceipt
- [x] eth_estimateGas

**Comment by NikitaSavik** [comment]
To be added:

- eth_chainId
- eth_maxPriorityFeePerGas
- eth_sendRawTransaction
- eth_getBlockByHash
- eth_call (should we limit that one?)
