### ISSUE TITLE
Solady minimal proxy support

### ISSUE THREAD

**Issue by agsola** [blockscout/blockscout#9271]
### Description

Automatic [EIP-1167](https://github.com/blockscout/blockscout/blob/master/apps/explorer/lib/explorer/chain/smart_contract/proxy/eip_1167.ex) (https://eips.ethereum.org/EIPS/eip-1167) is supported. However, another popular proxy by @Vectorized on Solady is not supported.

You can see the implementation here:
https://github.com/vectorized/solady/blob/main/src/utils/LibClone.sol

For EIP 1167 the implementation bytecode is this, as described in the EIP:
363d3d373d3d3d363d73bebebebebebebebebebebebebebebebebebebebe5af43d82803e903d91602b57fd5bf3

For Solady's, the pattern is slightly different, but more efficient:
3d3d3d3d363d3d37363d73bebebebebebebebebebebebebebebebebebebebe5af43d3d93803e602a57fd5bf3

And the creation code:
0x602c3d8160093d39f33d3d3d3d363d3d37363d73bebebebebebebebebebebebebebebebebebebebe5af43d3d93803e602a57fd5bf3

If you need a deployed example, I can provide it.

**Comment by GimluCom** [comment]
Should be relatively easy to modify the EIP1167 pattern to work with the [0age version](https://medium.com/coinmonks/the-more-minimal-proxy-5756ae08ee48).
Looks like Etherscan does not support this proxy yet (example contract [Blockscout](https://eth.blockscout.com/address/0xBB01A7A2Bf67e6B2f43815E520d7ce3A5231Fc83?tab=contract) / [Etherscan](https://etherscan.io/address/0xBB01A7A2Bf67e6B2f43815E520d7ce3A5231Fc83#code)), but there are [\~28000](https://dune.com/pcaversaccio/minimal-proxies) of them.

**Comment by GimluCom** [comment]
Thank you for clarifying, I mistakenly assumed it would detect the proxy pattern either way.
