### ISSUE TITLE
ETH deposit not shown in Wallet

### ISSUE THREAD

**Issue by basselooo5** [blockscout/blockscout#9273]
### Description

On 2024-01-21 09:18AM EST, I have withdrawn 0.41029509 ETH from my Binance account and deposited them into my Ledger wallet throught the MANTA network in the following address: 0xB53bfF08D011A6E1BD3C7fc8436E69584ADbe1dd

The withdrawal has been completed from my Binance account, but I do not see the amount in my Ledger wallet yet. The transaction ID from Binance is the following: 0x989a25dd6fb464ead470bfa49ca02f9566aa4984dddb138b026afb75a9c77980. I have also attached the printscreen of the Manta transaction.

Please help me find my ETH deposit. Thank you.
<img width="879" alt="Capture d’écran 2024-01-27 115237" src="https://github.com/blockscout/blockscout/assets/157907550/8de6437a-4e7b-4aef-be8c-990e7357bc69">

### Type of the installation

Docker-compose

### Type of the JSON RPC archive node

OpenEthereum

### Type of the chain

L1

### Link to the page

https://pacific-explorer.manta.network/tx/0x989a25dd6fb464ead470bfa49ca02f9566aa4984dddb138b026afb75a9c77980?tab=index

### Backend version

v6,1,0

### Elixir & Erlang/OTP versions

Elixir 1.14.5

### Operating system

Windows

### Additional information

**User Agent:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36

**Comment by sl1depengwyn** [comment]
This repo is for Blockscout-related questions. Blockscout is an open source blockchain explorer, so we do not host this chain ourselves. Thus, your question is out of scope, where the Blockscout team can help, you better contact the chain support directly.
