### ISSUE TITLE
METIS TOKEN EATEN BY ADDING POOL on NETSWAP

### ISSUE THREAD

**Issue by AXEATHEM** [blockscout/blockscout#9277]
### Description

When Im trying yo provide liquidity for the pool.
My Metis token is eaten by Netswap.

### Type of the installation

Docker-compose

### Type of the JSON RPC archive node

geth

### Backend version

v5.3.2-beta

### Elixir & Erlang/OTP versions

Elixir 1.14.5 Erlang/OTP 24

### Operating system

unix linux

### Additional information

The issue happened at Metis Sepolia Blockscout instance

**Comment by sl1depengwyn** [comment]
This repo is for Blockscout-related questions. Blockscout is an open source blockchain explorer. Thus, your question is out of scope, where the Blockscout team can help, you better contact the chain support directly.
