### ISSUE TITLE
request tokens but get no token

### ISSUE THREAD

**Issue by ttkhai1990** [blockscout/blockscout#9279]
### Description

i add the chain and request tokens into my address 0x04aE3d6A8147bC9935A2C98a8dF58E4E19a03abf

but i do have token
hope you help me
![Screenshot_2024-01-29-20-14-55-565_io metamask](https://github.com/blockscout/blockscout/assets/53230253/c1f7c26a-7398-4bb0-8517-2dc366cc8bfb)
![Screenshot_2024-01-29-20-14-34-807_io metamask](https://github.com/blockscout/blockscout/assets/53230253/fe3697dd-7fc0-48f9-8186-d78bbc6689e6)

### Type of the installation

Manual from the source code

### Type of the JSON RPC archive node

none

### Type of the chain

none

### Link to the page

https://milan-gibraltar.explorer.caldera.xyz/address/0x04aE3d6A8147bC9935A2C98a8dF58E4E19a03abf

### Backend version

5.2.2

### Frontend version

none

### Elixir & Erlang/OTP versions

none

### Operating system

android mobile

### Additional information

**User Agent:** Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Mobile Safari/537.36

**Comment by sl1depengwyn** [comment]
This repo is for Blockscout-related questions. Blockscout is an open source blockchain explorer. Thus, your question is out of scope, where the Blockscout team can help, you better contact the chain support directly.
