### ISSUE TITLE
The close of the short does not worked

### ISSUE THREAD

**Issue by SUBIFU** [blockscout/blockscout#9295]
### Description

I swapped tokens and wanted to trade. I opened a short i Saw it and when i want to Close it i can't.. i refresh the page and the order disapeared (i Saw the History there IS a trade in it..)

### Type of the installation

Docker-compose

### Type of the JSON RPC archive node

geth

### Backend version

v5.3.2-beta

### Elixir & Erlang/OTP versions

Elixir 1.14.5 Erlang/OTP 24

### Operating system

unix linux

### Additional information

The issue happened at Metis Sepolia Blockscout instance

**Comment by sl1depengwyn** [comment]
This repo is for Blockscout-related questions. Blockscout is an open source blockchain explorer. Thus, your question is out of scope, where the Blockscout team can help, you better contact the chain support directly.
