### ISSUE TITLE
Contract Address Genesis Changed EOA

### ISSUE THREAD

**Issue by avenbreaks** [blockscout/blockscout#9296]
### Description

I built an op stack from genesis and the standard output address that the op stack has is not detected by blockscout. it is actually a contract address but changed to EOA. how do I change it? 

Example : 
https://onlyscan.info/address/0x4200000000000000000000000000000000000015 ( L1BlockAttributes ) 
https://onlyscan.info/address/0x4200000000000000000000000000000000000010 ( L2StandardBridge ) 

![image](https://github.com/blockscout/blockscout/assets/93043826/eaa4ee64-1d88-4c50-bd5d-663956fdbb8c)

### Type of the installation

Docker-compose

### Type of the JSON RPC archive node

Geth

### Type of the chain

L2

### Link to the page

https://onlyscan.info

### Steps to reproduce

DOCKER_REPO=blockscout-optimism docker compose -f docker-compose.yml up --build -d 

### Backend version

v6.0.0

### Frontend version

latest

### Elixir & Erlang/OTP versions

none

### Operating system

Linux

**Comment by GimluCom** [comment]
You would need have the accounts listed in a chain spec file and then set `CHAIN_SPEC_PATH=path/to/chain.json` 
> Chain specification path (absolute file system path or URL) to import block emission reward ranges and genesis account balances from. Geth- and OpenEthereum-style specs are supported.

**Comment by avenbreaks** [comment]
> You would need have the accounts listed in a chain spec file and then set `CHAIN_SPEC_PATH=path/to/chain.json` 
> > Chain specification path (absolute file system path or URL) to import block emission reward ranges and genesis account balances from. Geth- and OpenEthereum-style specs are supported.

This is genesis.json right? Already listed on path but same

**Comment by vbaranov** [comment]
@avenbreaks is it possible to see to the genesis file? Probably, it wan't parse succesfully. Then, you should probably see something like `Failed to fetch genesis data`.

Recently, I added a fix for genesis issue [here](https://github.com/blockscout/blockscout/pull/9346). Probably, this is the case for you as well. Could you please try it on your instance?

**Comment by avenbreaks** [comment]
> @avenbreaks is it possible to see to the genesis file? Probably, it wan't parsed succesfully. Then, you should probably see something like `Failed to fetch genesis data`.
> 
> Recently, I added a fix for genesis issue [here](https://github.com/blockscout/blockscout/pull/9346). Probably, this is the case for you as well. Could you please try it on your instance?

https://sos-onlylayer.fra1.cdn.digitaloceanspaces.com/genesis-l2.json

**Comment by zlhwdsz** [comment]
@avenbreaks Hi, I am facing the same problem now. 
I see your browser now correclty shows the addresses as contracts.
Can you share your solutions?

**Comment by avenbreaks** [comment]
> @avenbreaks Hi, I am facing the same problem now. I see your browser now correclty shows the addresses as contracts. Can you share your solutions?

solved, hosting your `genesis.json` on github or other S3 Storage compatible and point into `CHAIN_SPEC_URL`

**Comment by avenbreaks** [comment]
Closed
