### ISSUE TITLE
PG database connection problem, causing server memory and load to be too high

### ISSUE THREAD

**Issue by yzh-d** [blockscout/blockscout#9297]
### Description

The load, CPU and memory of the server where blockscout is deployed are relatively high. After troubleshooting, we found that it was most likely caused by a problem with the PG database connection. I also found some evidence of pg problems on the Internet:
- [https://www.postgresql.org/message-id/flat/20160708012833.1419.89062%40wrigleys.postgresql.org#20160708012833.1419.89062@wrigleys.postgresql.org](url)
- [https://github.com/digoal/blog/blob/master/201607/20160709_01.md?spm=a2c6h.13066369.question.7.38567627IRt389&file=20160709_01.md](url)
- [https://github.com/digoal/blog/blob/master/202104/20210415_04.md](url)

Additional information
- Using SSD, Node mode POS
- our test networks: https://scan.taurus.axiomesh.io/home. The deployed blockscout version is still v5.2.3-beta. At the same time, I tested it myself on the intranet, using v5.4.4. The server configuration is the same and the problems mentioned above will occur.

![image](https://github.com/blockscout/blockscout/assets/30540477/47747ed6-7679-471f-9cea-6a8018881b55)

![image](https://github.com/blockscout/blockscout/assets/30540477/e95358c9-1de3-4fe9-97de-ffcfc77053f0)

What I want to ask is whether there is a recommended pg configuration under the 4C8G server configuration. Or for blockscout, the 4C8G server will have problems and we need to upgrade the server configuration.

### Type of the installation

Docker-compose

### Type of the JSON RPC archive node

geth

### Type of the chain

L1

### Link to the page

https://scan.taurus.axiomesh.io/home

### Backend version

v5.2.3-beta&v5.4.0-beta

### Frontend version

Self-developed front-end

### Elixir & Erlang/OTP versions

Elixir 1.14.0 (compiled with Erlang/OTP 25)

### Operating system

Linux

**Comment by zillnet-l2** [comment]
4C8G is not enough; 8C8G is decent, 12C12G is good.

**Comment by vbaranov** [comment]
@yzh-d please migrate your instance to [v6](https://github.com/blockscout/blockscout/releases/tag/v6.5.0-beta).
