### ISSUE TITLE
Missing MANTA TOKENS

### ISSUE THREAD

**Issue by Souldidi** [blockscout/blockscout#9299]
### Description

I made a transfer to the Manta Atlantic Bridge in order to participate in the staking. but my token went missing. 55I MANTA TOKENS. 

### Type of the installation

Manual from the source code

### Type of the JSON RPC archive node

eth

### Link to the page

https://pacific-explorer.manta.network/tx/0x3581102e034908aa3e4dc5d29b1acf2159244aebaa211a93af247e83fc44a018?tab=token_transfers

### Steps to reproduce

missing manta tokens on the Manta Atlantic Bridge

### Backend version

v6.11.0

### Elixir & Erlang/OTP versions

metamask

### Operating system

windows

### Additional information

**User Agent:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36

**Comment by sl1depengwyn** [comment]
This repo is for Blockscout-related questions. Blockscout is an open source blockchain explorer. Thus, your question is out of scope, where the Blockscout team can help, you better contact the chain support directly.
