### ISSUE TITLE
Metis transfer 

### ISSUE THREAD

**Issue by apb23** [blockscout/blockscout#9301]
### Description

Processed a transfer of Metis tokens to mainnet over 10 days ago and still says pending . The withdrawal request was supposed to be by the 28/01/2024 

### Type of the installation

Docker-compose

### Type of the JSON RPC archive node

geth

### Backend version

v5.3.2-beta

### Elixir & Erlang/OTP versions

Elixir 1.14.5 Erlang/OTP 24

### Operating system

unix linux

### Additional information

The issue happened at Andromeda Blockscout instance

**Comment by GimluCom** [comment]
> This repo is for Blockscout-related questions. Blockscout is an open source blockchain explorer. Thus, your question is out of scope, where the Blockscout team can help, you better contact the chain support directly.

**Comment by apb23** [comment]
No worries thank you
