### ISSUE TITLE
Unable to index pending transactions

### ISSUE THREAD

**Issue by yzh-d** [blockscout/blockscout#9302]
### Description

In the blockscout log, I encountered an error that pending transactions could not be indexed. After checking some issues, it was said that changing the configuration INDEXER_DISABLE_PENDING_TRANSACTIONS_FETCHER to true is enough. After the change, there is indeed no error, but if we want to use this configuration, we should use Which rpc interface of Ethereum is there?

### Type of the installation

Docker-compose

### Type of the JSON RPC archive node

geth

### Type of the chain

L1

### Backend version

v5.2.3-beta&v5.4.0-beta

### Frontend version

Self-developed front-end

### Elixir & Erlang/OTP versions

Elixir 1.14.0 (compiled with Erlang/OTP 25)

### Operating system

Linux

**Comment by GimluCom** [comment]
Please make sure `txpool` method is enabled on your Geth node. Example: `--http.api eth,net,web3,debug,txpool`

**Comment by yzh-d** [comment]
> Please make sure `txpool` method is enabled on your Geth node. Example: `--http.api eth,net,web3,debug,txpool`

According to your tips, I found several related interfaces: txpool_content, txpool_inspect, txpool_contentFrom and txpool_status. Do these interfaces need to be implemented? If not, can you tell me what interfaces must be implemented?

[https://github.com/ethereum/go-ethereum/blob/master/internal/ethapi/api.go](url)

**Comment by GimluCom** [comment]
When you append `txpool` to the `--http.api` option then all those interfaces will be enabled.

**Comment by GimluCom** [comment]
I believe Blockscout uses Geth's `txpool_content` interface.
