### ISSUE TITLE
unable to use the test network

### ISSUE THREAD

**Issue by SolarPluto** [blockscout/blockscout#9308]
### Description

 I was trying to use the test network however, it says insufficient balance. 

### Type of the installation

Docker-compose

### Type of the JSON RPC archive node

geth

### Link to the page

https://testnet.tethys.finance/trade

### Backend version

v5.3.2-beta

### Elixir & Erlang/OTP versions

Elixir 1.14.5 Erlang/OTP 24

### Operating system

unix linux

### Additional information

The issue happened at Metis Sepolia Blockscout instance

**Comment by ekawibisono** [comment]
Hello @SolarPluto This Blockscout Github not tethysswap, please contact Team Tethysswap. Thanks https://t.me/tethysswap
