### ISSUE TITLE
Transaction

### ISSUE THREAD

**Issue by MusikDmytro** [blockscout/blockscout#9319]
### Description

I want to transfer BNB to ZETA coins using Eddy.Finance. I sent $3, more than an hour passed and the transaction was not completed. I go to the BSC Skan website. And there it says that it is impossible to view this transaction. What is the problem?
![BNB Smart Chain Transaction Hash (Txhash) Details _ BscScan - Google Chrome 03 02 2024 21_16_00](https://github.com/blockscout/blockscout/assets/158774018/b93c09e4-cd0e-4455-b192-49915ee5e7b6)

### Type of the installation

Docker-compose

### Type of the JSON RPC archive node

Bnb

### Type of the chain

L2

### Link to the page

https://app.eddy.finance/transaction

### Backend version

v6.0.0-beta

### Frontend version

v1.22.0+d67d6621

### Elixir & Erlang/OTP versions

1.14.5 

### Additional information

**User Agent:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36

**Comment by ekawibisono** [comment]
Hello @MusikDmytro This blockscout github, not ZETA, please you can contract Zeta Team. Thanks
