### ISSUE TITLE
Can’t find these Métis Sepolia tokens

### ISSUE THREAD

**Issue by DeboBillz** [blockscout/blockscout#9326]
### Description

Please look into this transaction Hash: 0x7364545c63bf82cc826fa09e579f934a8ad7d52d7ed4c2cd22df3292ec875abf
The tokens cannot be found at the address.
![IMG_8146](https://github.com/blockscout/blockscout/assets/157706749/d5f1db88-539a-4f80-ad22-50c72629c79a)
![IMG_8145](https://github.com/blockscout/blockscout/assets/157706749/75cade23-d49a-4004-96f7-366c0251b2e0)

### Type of the installation

Docker-compose

### Type of the JSON RPC archive node

geth

### Type of the chain

L2

### Link to the page

https://metamask.com

### Backend version

v5.3.2-beta

### Elixir & Erlang/OTP versions

Elixir 1.14.5 Erlang/OTP 24

### Operating system

unix linux

### Additional information

The issue happened at Metis Sepolia Blockscout instance

**Comment by DeboBillz** [comment]
Please help out. I am not a Tech person.

**Comment by vbaranov** [comment]
This chat is for Blockscout-related questions. Your question is out of scope, where the Blockscout team can help.
