### ISSUE TITLE
Contract Read return no function clause matching in Integer.parse/2

### ISSUE THREAD

**Issue by dennisloh95** [blockscout/blockscout#9341]
### Description

There is a read function from my contract, "getProjectConfig", it can query read at etherscan but blockscout return no function clause matching in Integer.parse/2.

https://eth-goerli.blockscout.com/address/0xfbfE30818BA312A14c5532A311DdA2578B80Ca10?tab=read_contract
![Screenshot 2024-02-06 at 10 15 18 AM](https://github.com/blockscout/blockscout/assets/34902315/3e96f642-b5c5-4233-b11d-fee987cd11cb)

https://goerli.etherscan.io/address/0xfbfe30818ba312a14c5532a311dda2578b80ca10#readContract
![Screenshot 2024-02-06 at 10 14 24 AM](https://github.com/blockscout/blockscout/assets/34902315/d8dee044-d693-43c8-8af6-d45eb5845fa2)

### Type of the installation

Docker-compose

### Type of the JSON RPC archive node

Geth

### Type of the chain

L1 Goerli

### Link to the page

https://eth-goerli.blockscout.com/address/0xfbfE30818BA312A14c5532A311DdA2578B80Ca10?tab=read_contract

### Backend version

v6.0.0

### Elixir & Erlang/OTP versions

1.14.5-otp-25

**Comment by dennisloh95** [comment]
Hi can confirm the #9300 can solve my issue? cause when I try to copy the code from https://github.com/blockscout/blockscout/pull/9300/files encoder.ex, it still return no function clause matching in Integer.parse/2.

any plan to deploy the update to goerli blockscout so I can test again from 
https://eth-goerli.blockscout.com/address/0xfbfE30818BA312A14c5532A311DdA2578B80Ca10?tab=read_contract

**Comment by vbaranov** [comment]
ETH Goerli will be updated soon with this fix.

**Comment by vbaranov** [comment]
@dennisloh95 ETH Goerli instance patched.

**Comment by dennisloh95** [comment]
> @dennisloh95 ETH Goerli instance patched.

after try again on https://eth-goerli.blockscout.com/address/0xfbfE30818BA312A14c5532A311DdA2578B80Ca10?tab=read_contract seems like it still return the same error "no function clause matching in Integer.parse/2."

**Comment by vbaranov** [comment]
> > @dennisloh95 ETH Goerli instance patched.
> 
> after try again on https://eth-goerli.blockscout.com/address/0xfbfE30818BA312A14c5532A311DdA2578B80Ca10?tab=read_contract seems like it still return the same error "no function clause matching in Integer.parse/2."

Could you copy/paste the input parameters in order to repro?

**Comment by dennisloh95** [comment]
> > > @dennisloh95 ETH Goerli instance patched.
> > 
> > 
> > after try again on https://eth-goerli.blockscout.com/address/0xfbfE30818BA312A14c5532A311DdA2578B80Ca10?tab=read_contract seems like it still return the same error "no function clause matching in Integer.parse/2."
> 
> Could you copy/paste the input parameters in order to repro?

curl --location 'https://eth-goerli.blockscout.com/api/v2/smart-contracts/0xfbfE30818BA312A14c5532A311DdA2578B80Ca10/query-read-method?is_custom_abi=false' \
--header 'Content-Type: application/json' \
--data '{"args":["0xc3aC498cdFb6E1dCfA17cBC55e514560f26A1922",["1"]],
"method_id":"817a14b8",
"contract_type":"regular",
"from":"0xc3aC498cdFb6E1dCfA17cBC55e514560f26A1922"}'

**Comment by vbaranov** [comment]
I reproduced the issue, we'll continue to debug it.
