### ISSUE TITLE
Wrong coin balance (ETH) when there's a reorg

### ISSUE THREAD

**Issue by rollue** [blockscout/blockscout#9342]
### Description

We think we're seeing incorrect data in address_coin_balance and fetched_coin_balance in addresses tables

Mostly the problems seems to be related to reorgs - e.g. if there's a reorg the historical coin balance history seems to be incorrect (the reorged data is saved not deleted or replaced with valid block data) & also the fetched_coin_balance field in the addresses table.

Data regarding token_balances (reorged rows are deleted), transactions (you can use block.consensus field to distinguish), and token transfers are handled. But doesn't seem to be the case with coin_balance & coin related fields in addresses table - rogue data in inserted & not updated. 

For example, there should be a logic to handle reogs by deleting all reorged rows from address_coin_balance table and reinserting included block address data, but there isn't such logic within the code. (there's an issue with deleting token related reorg data but not coin(native ETH) https://github.com/blockscout/blockscout/pull/7927)

### Type of the installation

Docker-compose

### Type of the JSON RPC archive node

Erigon

### Steps to reproduce

https://eth.blockscout.com/address/0x95222290DD7278Aa3Ddd389Cc1E1d165CC4BAfe5?tab=coin_balance_history&page=24&next_page_params=%7B%22block_number%22%3A19163649%2C%22items_count%22%3A1150%7D

As an example, the incorrect data is at block 19163628 - the balance ETH is 17.57699143 in blockscout. But if you use RPC to check the balance ETH at that block using

```
curl {YOUR_RPC_URL} -H "Content-type:application/json" --data '{"jsonrpc": "2.0", "method": "eth_getBalance", "params": ["0x95222290dd7278aa3ddd389cc1e1d165cc4bafe5", "0x12469EC"], "id": 0}'
```

the result is 
```
 {"jsonrpc":"2.0","id":0,"result":"0xf3e8c0ee7ed1ef59"}
```

converting the hexadecimal to decimal you get 17575509676375797593 which is more like 17.5755097... - not the 17.57699143 as shown in blockscout

### Backend version

v5.4.0-beta

### Elixir & Erlang/OTP versions

elixir-1.14.5, erlang-24.2.2 (docker)

**Comment by Kb00711** [comment]
I have created over 70 NFTs and have been first to mint but haven't received first minter Rewards or any Rewards at all since the 3rd NFT creation
