### ISSUE TITLE
errors in Microservices when install backend services via Manual Deployment Guide

### ISSUE THREAD

**Issue by LuxesOwen** [blockscout/blockscout#9343]
### Description

  Microservices stats-postgres and stats can't start up normally.  And I have not start the backend service yet.

### Type of the installation

Manual from the source code

### Type of the JSON RPC archive node

GETH

### Type of the chain

L1

### Link to the page

https://scan.test.algen.network/

### Steps to reproduce

After step [2. Run Microservices] of document https://docs.blockscout.com/for-developers/deployment/manual-deployment-guide
1. cd ./blockscout-backend/docker-compose
2. docker-compose -f microservices.yml up -d

then list the services and check logs of stats-postgres,stats:
![WX20240206-165218@2x](https://github.com/blockscout/blockscout/assets/66360114/29d5a8bb-e753-4756-84d6-f2d4479d4bc6)

docker logs stats-postgres -f 
[stats-postgres.log](https://github.com/blockscout/blockscout/files/14177126/stats-postgres.log)

docker logs stats -f
[stats.log](https://github.com/blockscout/blockscout/files/14177142/stats.log)

these two service always produce errors after start.

### Backend version

current default branch

### Frontend version

current default branch

### Elixir & Erlang/OTP versions

Erlang/OTP 25 [erts-13.2.2.5] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [jit:ns]  Elixir 1.14.5 (compiled with Erlang/OTP 25)

### Operating system

Ubuntu 22.04.3 LTS (GNU/Linux 6.2.0-1017-aws x86_64)

### Additional information

Errors with these services hindered my subsequent installations,  I had deleted the repository and try again,It's same.

**Comment by GimluCom** [comment]
Try this before starting
```sh
export STATS__BLOCKSCOUT_DB_URL="postgresql://<pg_user>:<pg_password>@host.docker.internal:5432/blockscout"
```

**Comment by LuxesOwen** [comment]
> Try this before starting
> 
> ```shell
> export STATS__BLOCKSCOUT_DB_URL="postgresql://<pg_user>:<pg_password>@host.docker.internal:5432/blockscout"
> ```

Hi, thans for your help!  But  the problem has not been solved.
I had try to export this this variable on command line , and set it to /docker-compose/envs/common-stats.env
`
STATS__SERVER__HTTP__ENABLED=true
STATS__SERVER__HTTP__ADDR=0.0.0.0:8050
STATS__SERVER__HTTP__MAX_BODY_SIZE=2097152

STATS__SERVER__GRPC__ENABLED=false
STATS__SERVER__GRPC__ADDR=0.0.0.0:8051

STATS__DB_URL=
STATS__BLOCKSCOUT_DB_URL="postgresql://bs:abcd1234@host.docker.internal:5432/blockscout"
STATS__CREATE_DATABASE=false
STATS__RUN_MIGRATIONS=false
STATS__DEFAULT_SCHEDULE=0 0 1 * * * *
STATS__FORCE_UPDATE_ON_START=false

STATS__METRICS__ENABLED=false
STATS__METRICS__ADDR=0.0.0.0:6060
STATS__METRICS__ROUTE=/metrics

STATS__JAEGER__ENABLED=false
STATS__JAEGER__AGENT_ENDPOINT=localhost:6831

STATS__TRACING__ENABLED=true
STATS__TRACING__FORMAT=default
`

After start all Microservices, those errors happend again. error logs almost the same as the previous. error logs generated non-stop.
**service stats:**
2024-02-07T04:03:07.928881Z ERROR stats_server: service failed with error: Connection Error: pool timed out while waiting for an open connection    
Error: Connection Error: pool timed out while waiting for an open connection
or
2024-02-07T04:09:19.933160Z ERROR stats_server: service failed with error: Connection Error: error communicating with database: failed to lookup address information: Temporary failure in name resolution    
Error: Connection Error: error communicating with database: failed to lookup address information: Temporary failure in name resolution

**service stats-postgres:**
2024-02-07 04:02:06.920 UTC [1] LOG:  starting PostgreSQL 15.5 (Debian 15.5-1.pgdg120+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 12.2.0-14) 12.2.0, 64-bit
2024-02-07 04:02:06.920 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
2024-02-07 04:02:06.920 UTC [1] LOG:  listening on IPv6 address "::", port 5432
2024-02-07 04:02:06.923 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
2024-02-07 04:02:06.929 UTC [55] LOG:  database system was shut down at 2024-02-07 04:02:06 UTC
2024-02-07 04:02:06.934 UTC [1] LOG:  database system is ready to accept connections
2024-02-07 04:02:07.352 UTC [59] ERROR:  database "stats" already exists
2024-02-07 04:02:07.352 UTC [59] STATEMENT:  CREATE DATABASE "stats"


[stats-postgres.log](https://github.com/blockscout/blockscout/files/14188976/stats-postgres.log)
[stats.log](https://github.com/blockscout/blockscout/files/14188978/stats.log)

There is no doubt that stats service failed to start.
Should I set STATS__DB_URL in /docker-compose/envs/common-stats.env? I noticed that it's empty.

**Comment by GimluCom** [comment]
Yes, try `STATS__DB_URL=postgresql://stats:n0uejXPl61ci6ldCuE2gQU5Y@stats-db:5432/stats`

**Comment by LuxesOwen** [comment]
> Yes, try `STATS__DB_URL=postgresql://stats:n0uejXPl61ci6ldCuE2gQU5Y@stats-db:5432/stats`

After add this variable, the error logs same as the previous. 
And can't request to stats successful.

curl http://localhost:8080/health/
```
<html>
<head><title>502 Bad Gateway</title></head>
<body>
<center><h1>502 Bad Gateway</h1></center>
<hr><center>nginx/1.25.3</center>
</body>
</html>
```

**Comment by D3athGr1p** [comment]
I'm facing same issue, @LuxesOwen if you got any solution about this please share it.

**Comment by vbaranov** [comment]
@LuxesOwen could you please pull updates from master branch? The issue should be fixed there.

**Comment by yucheng-Li** [comment]
> I didn't directly resolve the issue, but I made some adjustments to the `stats.yml` files: change:
> 
> ```js
> STATS__DB_URL=postgres://stats:n0uejXPl61ci6ldCuE2gQU5Y@stats-db:5432/stats 
> ```
> 
> to
> 
> ```js
> STATS__DB_URL=postgres://stats:n0uejXPl61ci6ldCuE2gQU5Y@stats-postgres:5432/stats
> ```
> 
> and change:
> 
> ```js
> STATS__BLOCKSCOUT_DB_URL=${STATS__BLOCKSCOUT_DB_URL-postgresql://blockscout:ceWb1MeLBEeOIfk65gU8EjF8@db:5432/blockscout}
> ```
> 
> to
> 
> ```js
> STATS__BLOCKSCOUT_DB_URL=postgresql://blockscout:ceWb1MeLBEeOIfk65gU8EjF8@db:5432/blockscout
> ```
> 
> Now, before executing `docker-compose -f microservices.yml up -d` run this `docker-compose -f services/db.yml up -d`, and it should work fine.
> 
> or you could just edit `microservices.yml` file and add this at start: ![Screenshot from 2024-02-08 17-31-07](https://private-user-images.githubusercontent.com/86771928/303319430-4c5a8110-95eb-40f2-8edc-abefb5e8dfb9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkyMDAzMDIsIm5iZiI6MTcwOTIwMDAwMiwicGF0aCI6Ii84Njc3MTkyOC8zMDMzMTk0MzAtNGM1YTgxMTAtOTVlYi00MGYyLThlZGMtYWJlZmI1ZThkZmI5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjI5VDA5NDY0MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJjMDA3NDdmNjQxZGM0MGVmYTRhMGY4MTE1Y2Q4NzFjYjRmYjI4OWExZjBhMDIzYWU2NzhkZDg4MTRjZGRlMGImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.coWwAroHU3SjAp7iNYJtmzQQYsCLZxQr4E_y9JUXNV0)
> 
> and also
> 
> ![Screenshot from 2024-02-08 17-31-52](https://private-user-images.githubusercontent.com/86771928/303319629-5442de73-7696-46a6-a51b-614d47447636.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkyMDAzMDIsIm5iZiI6MTcwOTIwMDAwMiwicGF0aCI6Ii84Njc3MTkyOC8zMDMzMTk2MjktNTQ0MmRlNzMtNzY5Ni00NmE2LWE1MWItNjE0ZDQ3NDQ3NjM2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjI5VDA5NDY0MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTcyYzY4YWZhMmZiMmJhMzg2ODk4NDgzMGFiNTBhNzQ5NWIwMjRhZDFjM2RiYzI3NGUyYmVhM2QzMGFlMGM5MTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.XP7xD48itu60C13hI00dnbCb1t3FaSmjLDuvlOl1VSc)

I have the some problem and solve it by the second way, i add a db config in microservices.yml and run again it work fine

**Comment by yucheng-Li** [comment]
已收到
