### ISSUE TITLE
Tidak menerima pengiriman metis koin

### ISSUE THREAD

**Issue by Golan06** [blockscout/blockscout#9353]
### Description

Koin tidak masuk, tolong di bantu
![Screenshot_20240207_205159](https://github.com/blockscout/blockscout/assets/158133930/3e5eaedc-ccdd-4ded-a32f-626dfca1cf3f)

### Type of the installation

Docker-compose

### Type of the JSON RPC archive node

geth

### Backend version

v5.3.2-beta

### Elixir & Erlang/OTP versions

Elixir 1.14.5 Erlang/OTP 24

### Operating system

unix linux

### Additional information

The issue happened at Metis Sepolia Blockscout instance

**Comment by Golan06** [comment]
Tolong di bantu

**Comment by vbaranov** [comment]
Please formulate your issue in English.
