### ISSUE TITLE
The problem with the website

### ISSUE THREAD

**Issue by Zeram10** [blockscout/blockscout#9362]
### Description

There is a problem with the website when logging in from the MetaMask browser and clicking on the icons at the bottom of the page for Twitter and Discord does not work

### Type of the installation

Docker-compose

### Type of the JSON RPC archive node

All

### Type of the chain

L3

### Link to the page

https://bridge.swanchain.io/deposit

### Backend version

v6.0.0-beta.+commit.ce735c12

### Frontend version

v1.22.0+d67d6621

### Elixir & Erlang/OTP versions

Elixir

### Operating system

Android 

### Additional information

**User Agent:** Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Mobile Safari/537.36

**Comment by vbaranov** [comment]
This chat is for Blockscout-related questions. Your question is out of scope, where the Blockscout team can help.
