### ISSUE TITLE
Skip internal transactions fetch for transactions with type=0x58 on ZetaChain

### ISSUE THREAD

**Issue by vbaranov** [blockscout/blockscout#9368]
> Yeah type 0x58 txs do not work on trace transactions. They are special txs customized by us. (edited) 

> for all other tx types the traceTransaction RPC should work.

I'd suggest moving this logic based on `CHAIN_TYPE=zetachain`.

**Comment by Paukageo10** [comment]
CHAIN_TYPE=zetachain123

**Comment by Paukageo10** [comment]
CHAIN_TYPE=zetachain
