### ISSUE TITLE
Sending a token

### ISSUE THREAD

**Issue by hudojar** [blockscout/blockscout#9370]
### Description

Good afternoon! Today, I made a transaction to transfer the MATIS token from one wallet to another. Confirmation of the transaction 0x28e07cd8f980b9cf4500e11f56b513ee63a1f9accbe39d8828cd8a9ff080ae4d

### Type of the installation

Docker-compose

### Type of the JSON RPC archive node

geth

### Steps to reproduce

The funds have not been received to the specified address yet 0xECb6a1E18d13BeC7c39170DEBf2FD7177eDE7c67 What could be the reason for the delay?

### Backend version

v5.3.2-beta

### Elixir & Erlang/OTP versions

Elixir 1.14.5 Erlang/OTP 24

### Operating system

unix linux

### Additional information

The issue happened at Metis Sepolia Blockscout instance

**Comment by hudojar** [comment]
Although the browser indicates that the transaction has been confirmed
![Screenshot_1](https://github.com/blockscout/blockscout/assets/159371322/235a67ff-935d-492d-bf30-9e52c1808d97)

**Comment by vbaranov** [comment]
This chat is for Blockscout-related questions. Your question is out of scope, where the Blockscout team can help.
