### ISSUE TITLE
Doc for contract verification api (api/v2)

### ISSUE THREAD

**Issue by wighawag** [blockscout/blockscout#9372]
### Description

I am doing the following

```typescript
const formData = new FormData();
formData.append('address_hash', address);
formData.append('compiler_version',compiler.version);
const metadataBlob = new Blob([metadata], {
	type: 'application/json',
});
formData.append('files', metadataBlob, 'metadata.json');
const submissionResponse = await fetch(
	`${url}api/v2/smart-contracts/${address}/verification/via/standard-input`,
	{body: formData, method: 'POST'}
);
const json = await submissionResponse.json();
```

But I get the following error

```
{ message: 'JSON files not found' }
```

### Type of the installation

Docker-compose

### Type of the JSON RPC archive node

ethereum

### Backend version

latest

### Elixir & Erlang/OTP versions

latest

**Comment by wighawag** [comment]
Never mind, I had to put `files[0]`

so

`formData.append('files[0]', metadataBlob, 'metadata.json');`

**Comment by dreadedhamish** [comment]
> Never mind, I had to put `files[0]`
> 
> so
> 
> `formData.append('files[0]', metadataBlob, 'metadata.json');`

So for multi-file it's going to have a files[0], files[1] etc...?
