### ISSUE TITLE
Transaction problem

### ISSUE THREAD

**Issue by Alekjo8** [blockscout/blockscout#9375]
### Description

Hi dear 
I was transfer  metis to exchange account. transaction successfully but not add to destination address. Please help 
TxID: 0x0af827f12f4d0f72d697dac264d7bb2d5ab10e22a067e9c456bd856d71a17625

### Type of the installation

Docker-compose

### Type of the JSON RPC archive node

geth

### Backend version

v5.3.2-beta

### Elixir & Erlang/OTP versions

Elixir 1.14.5 Erlang/OTP 24

### Operating system

unix linux

### Additional information

The issue happened at Metis Sepolia Blockscout instance

**Comment by vbaranov** [comment]
This chat is for Blockscout-related questions. Your question is out of scope, where the Blockscout team can help.
