### ISSUE TITLE
Quai testnet faucet

### ISSUE THREAD

**Issue by wgunther85** [blockscout/blockscout#9382]
### Description

When trying to collect coins in the testnet faucet they never show up even days after into my Koala Wallet. When I click on the transaction hash right after it says it was a successful transaction there is an error 500 that says internal server error.

### Type of the installation

Docker-compose

### Type of the JSON RPC archive node

Im not sure

### Type of the chain

Quai testnet faucet

### Link to the page

https://faucet.quai.network/

### Steps to reproduce

enter koala quai address into the wallet address bar and click the button below.

### Backend version

v.6.1 not sure

### Elixir & Erlang/OTP versions

not sure

### Operating system

windows 11

**Comment by vbaranov** [comment]
This chat is for Blockscout-related questions. Your question is out of scope, where the Blockscout team can help.
