### ISSUE TITLE
Manta transfer

### ISSUE THREAD

**Issue by KiaToth** [blockscout/blockscout#9392]
### Description

Tried to transfer Manta token from manta pacific (metamask wallet) to manta atlantic (Manta wallet) on they website (app.manta.network) but didn't arrived. Pacific-explorer shows the transfer stopped somewhere between the two addresses.

### Type of the installation

Docker-compose

### Type of the JSON RPC archive node

ethereum

### Type of the chain

L2

### Link to the page

https://pacific-explorer.manta.network/address/0x95CeF13441Be50d20cA4558CC0a27B601aC544E5?tab=tokens

### Backend version

v6.1.0.

### Elixir & Erlang/OTP versions

otp

### Operating system

windows

### Additional information

**User Agent:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36 Edg/121.0.0.0

**Comment by vbaranov** [comment]
This chat is for Blockscout-related questions. Your question is out of scope, where the Blockscout team can help.
