### ISSUE TITLE
Wrong transaction 

### ISSUE THREAD

**Issue by Daweirdone1** [blockscout/blockscout#9399]
### Description

I mistakenly sent my Metis coin to the wrong network. What do I do to recover it?

### Type of the installation

Docker-compose

### Type of the JSON RPC archive node

geth

### Backend version

v5.3.3-beta

### Elixir & Erlang/OTP versions

Elixir 1.14.5 Erlang/OTP 24

### Operating system

unix linux

### Additional information

The issue happened at Metis Sepolia Blockscout instance

**Comment by vbaranov** [comment]
This chat is for Blockscout-related questions. Your question is out of scope, where the Blockscout team can help.
