### ISSUE TITLE
Cannot start microservices

### ISSUE THREAD

**Issue by blocks404protocol** [blockscout/blockscout#9411]
### Description

When I run docker-compose
docker-compose -f microservices.yml up -d

it returns
service "stats" can't be used with `extends` as it declare `depends_on`

I started installing entire blockscout in a Docker container with ubuntu

### Type of the installation

Docker

### Type of the JSON RPC archive node

geth

### Steps to reproduce

I followed the guide and I am stuck on the part with starting the microservices

### Backend version

v6.1.0

### Elixir & Erlang/OTP versions

Elixir 1.14.5 (compiled with Erlang/OTP 24)

### Operating system

Linux

**Comment by blocks404protocol** [comment]
I downgraded docker-compose and it worked. I think there's some breaking changes with the most recent version(s) of docker-compose

**Comment by vbaranov** [comment]
@blocks404protocol which docker-compose version did you downgrade from and to?

**Comment by yucheng-Li** [comment]
> @blocks404protocol which docker-compose version did you downgrade from and to?
https://github.com/docker/compose/issues/11544
2.24.5 is work well, but in mac i can not change my docker-compose to 2.24.5, so i can't solve it.

Have any way to solve it?

**Comment by vbaranov** [comment]
@blocks404protocol the issue should be resolved in #9512. Could you please pull it in your env?

**Comment by yucheng-Li** [comment]
已收到
