### ISSUE TITLE
Bridge amount not credited 

### ISSUE THREAD

**Issue by Tanmoy6295** [blockscout/blockscout#9412]
### Description

Transaction hash 0xc24df57e88783c96fb4f9940435d8a393d990655e22e215632c1e938d9dc0b0c

I bridged mood eth to eth Mainnet but 1 week done still not recived help me 

My addres - 0xF568535c10d5B5479f18241e429bd9dd600C8bE8

### Type of the installation

Docker-compose

### Type of the JSON RPC archive node

0xF568535c10d5B5479f18241e429bd9dd600C8bE8

### Link to the page

https://explorer.mode.network/tx/0xc24df57e88783c96fb4f9940435d8a393d990655e22e215632c1e938d9dc0b0c

### Steps to reproduce

I bridged mood eth to my eth but not received 

### Backend version

v5.4.0-beta.+commit.63747320

### Elixir & Erlang/OTP versions

Nothing 

### Additional information

**User Agent:** Mozilla/5.0 (Linux; Android 13; I2202) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/105.0.0.0 Mobile Safari/537.36

**Comment by vbaranov** [comment]
This chat is for Blockscout-related questions. Your question is out of scope, where the Blockscout team can help.
