### ISSUE TITLE
Send metis but still not received

### ISSUE THREAD

**Issue by junaid20055** [blockscout/blockscout#9416]
### Description

Dear sir i send 2 metis on kycoin but still not received yet what the issue 

### Type of the installation

Docker-compose

### Type of the JSON RPC archive node

geth

### Backend version

v5.3.3-beta

### Elixir & Erlang/OTP versions

Elixir 1.14.5 Erlang/OTP 24

### Operating system

unix linux

### Additional information

The issue happened at Metis Sepolia Blockscout instance

**Comment by vbaranov** [comment]
This chat is for Blockscout-related questions. Your question is out of scope, where the Blockscout team can help.
