### ISSUE TITLE
Transaction count won't update

### ISSUE THREAD

**Issue by DwikiBayu123** [blockscout/blockscout#9438]
### Description

The number of total transaction won't update even there's a new transactions. I have waiting for more than 8 hours but it's won't update

### Type of the installation

Docker-compose

### Type of the JSON RPC archive node

https://saturn-rpc.swanchain.io/

### Type of the chain

L2

### Link to the page

https://saturn-explorer.swanchain.io/

### Backend version

v6.0.0-beta.+commit.ce735c12

### Frontend version

v1.22.0+d67d6621

### Elixir & Erlang/OTP versions

Elixir 1.14.5 /otp version 15

### Operating system

Android 10

### Additional information

**User Agent:** Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Mobile Safari/537.36

**Comment by ekawibisono** [comment]
Hello @DwikiBayu123 Please Contact Team Swan. https://linktr.ee/swan_chain

Thanks
