### ISSUE TITLE
money withdrawal problem

### ISSUE THREAD

**Issue by ccagataycelik** [blockscout/blockscout#9445]
### Description

On Wednesday last week, I sent my Ethereum balance from the Mode Network network back to the Ethereum network from the bridge section for withdrawal. The transaction was confirmed in my metamask wallet, but it still hasn't arrived on the ethereum network for 7 days.

### Type of the installation

Manual from the source code

### Type of the JSON RPC archive node

.

### Link to the page

https://explorer.mode.network/

### Backend version

v5.4.0-beta.+commit.63747320

### Elixir & Erlang/OTP versions

.

### Additional information

**User Agent:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36

**Comment by sl1depengwyn** [comment]
This repo is for Blockscout-related questions. Blockscout is an open source blockchain explorer. Thus, your question is out of scope, where the Blockscout team can help, you better contact the chain support directly.
