### ISSUE TITLE
Missing ERC20 token balances on ZkSync Era

### ISSUE THREAD

**Issue by yvaskov** [blockscout/blockscout#9453]
## Description

A user reported most of his token balances missing for the address on ZkSync:
https://zksync.blockscout.com/address/0x52432473144056FE91Aeae9240aD21e6B8213440

API returns only 2 from the long list of the tokens, as provided by the user.

![Image](https://github.com/blockscout/blockscout/assets/72267126/a4564929-c288-45d9-880c-bc91b8071859)

![Image](https://github.com/blockscout/blockscout/assets/72267126/9bdcaba1-2f51-4744-8d46-1f4f3eda7c53)

All the tokens themselves can be found on Blockscout, e.g. https://zksync.blockscout.com/token/0x8E86e46278518EFc1C5CEd245cBA2C7e3ef11557

## Version

[v6.1.0-beta.+commit.dd31aea4](https://github.com/blockscout/blockscout/commit/dd31aea4)

**Comment by vbaranov** [comment]
```

  | {"time":"2024-02-27T15:18:42.527Z","severity":"error","message":"Failed to decode Ethereum JSONRPC response:\n\n  request:\n\n    url: https://mainnet.era.zksync.io\n\n    body: [{\"id\":0,\"jsonrpc\":\"2.0\",\"method\":\"eth_call\",\"params\":[{\"data\":\"0x70a08231000000000000000000000000dfaab828f5f515e104baaba4d8d554da9096f0e4\",\"to\":\"0x3355df6d4c9c3035724fd0e3914de96a5a83aaf4\"},\"0x8E7CA9\"]},{\"id\":1,\"jsonrpc\":\"2.0\",\"method\":\"eth_call\",\"params\":[{\"data\":\"0x70a08231000000000000000000000000dfaab828f5f515e104baaba4d8d554da9096f0e4\",\"to\":\"0x3355df6d4c9c3035724fd0e3914de96a5a83aaf4\"},\"0x8E7CB6\"]},{\"id\":2,\"jsonrpc\":\"2.0\",\"method\":\"eth_call\",\"params\":[{\"data\":\"0x70a08231000000000000000000000000bb84d99708a32cc3e358062ad5c9996d9d579990\",\"to\":\"0x3355df6d4c9c3035724fd0e3914de96a5a83aaf4\"},\"0x8E7CA9\"]},{\"id\":3,\"jsonrpc\":\"2.0\",\"method\":\"eth_call\",\"params\":[{\"data\":\"0x70a0823100000000000000000\n\n  response:\n\n    status code: 429\n\n    body: <!doctype html><meta charset=\"utf-8\"><meta name=viewport content=\"width=device-width, initial-scale=1\"><title>429</title>429 Too Many Requests\n","metadata":{"count":100}} |  
-- | -- | --


<br class="Apple-interchange-newline">
```

The public RPC node, which Blockscout uses throttles requests including `eth_call` `balanceOf` requests.
