### ISSUE TITLE
Internal transactions do not trigger balance update

### ISSUE THREAD

**Issue by ardier16** [blockscout/blockscout#9455]
### Description

When the contract transfers some native tokens to EOA (e.g. Account A) inside internal transaction, this transfer has no effect on the Account A balance and is not reflected on `Coin Balance History` page and on the address balance view.

### Type of the installation

Docker-compose

### Type of the JSON RPC archive node

Geth

### Link to the page

https://eth-sepolia.blockscout.com/tx/0xf9c2b98c5f24249303f605a818e9b738cff836f88bfee20d3283f3d781f7f277?tab=internal

### 1. Deploy a contract that tranfers some native tokens to EOA
<details><summary>Contract example source code (Solidity)</summary>
<p>

```solidity
// SPDX-License-Identifier: LGPL-3.0-or-later
pragma solidity 0.8.24;

contract AllocatorTest {
    constructor() {}
    receive() external payable {}

    function allocate() external payable {
        address[] memory members = [// list of addresses];

        uint256 amount = 100000000000000; // 0.0001 ETH
        address payable _to;

        for (uint64 i = 0; i < members.length; ++i) {
            _to = payable(members[i]);
            (bool sent,) = _to.call{value: amount}("");
            require(sent, "Failed to send Ether");
        }
    }
}
``` 

</p>
</details>

Deployed contract on Sepolia:
https://eth-sepolia.blockscout.com/address/0x2aD29aca9455fba6E8DA77b52Ed8111438C2c90B

### 2. Call the contract method to allocate the funds
Example of allocate transaction:
https://eth-sepolia.blockscout.com/tx/0xf9c2b98c5f24249303f605a818e9b738cff836f88bfee20d3283f3d781f7f277

<details><summary>Screenshot of internal transactions</summary>
<p>

<img width="1176" alt="image" src="https://github.com/blockscout/blockscout/assets/17788043/8ba18de6-9708-405c-8354-e3c4af587b29">

</p>
</details> 

### 3. Verify the balance of allocation members

Members:
- Balance is 0:
https://eth-sepolia.blockscout.com/address/0x9BA6878e2E5B75aAeaba35Ce62cF13ED6dCaa02B?tab=coin_balance_history
- Balance is OK, but no history:
https://eth-sepolia.blockscout.com/address/0x19df6692a4E590122A49A1ef3390e01A36C48908?tab=coin_balance_history

<details><summary>Screenshots</summary>
<p>

<img width="1197" alt="Screenshot 2024-02-22 at 16 56 14" src="https://github.com/blockscout/blockscout/assets/17788043/3a06ab09-0ba8-4b8a-a086-bb2d21fb46b4">
<img width="1223" alt="Screenshot 2024-02-22 at 16 56 38" src="https://github.com/blockscout/blockscout/assets/17788043/b746132c-234f-46b8-b939-3cce669e14a3">

</p>
</details> 

## Expected behavior
- All member balances are updated according to the allocation
- The coin balance history is updated accordingly

## Actual behavior
- Coin balance history is empty
- Balance is not updated for some members

### Backend version

v6.1.0-beta.+commit.61df0a9b

### Elixir & Erlang/OTP versions

Deployed on eth-sepolia.blockscout.com

### Additional information

On Sepolia Etherscan the balance update is handled correctly:

**Transaction:**
https://sepolia.etherscan.io/tx/0xf9c2b98c5f24249303f605a818e9b738cff836f88bfee20d3283f3d781f7f277#internal

**Members:**
  - https://sepolia.etherscan.io/address/0x9ba6878e2e5b75aaeaba35ce62cf13ed6dcaa02b
  - https://sepolia.etherscan.io/address/0x19df6692a4e590122a49a1ef3390e01a36c48908

<details><summary><b>Screenshots</b></summary>
<p>

<img width="1440" alt="image" src="https://github.com/blockscout/blockscout/assets/17788043/475f218c-9748-47f8-9c34-03234e958a96">
<img width="1440" alt="Screenshot 2024-02-22 at 17 02 17" src="https://github.com/blockscout/blockscout/assets/17788043/f636adea-2cfc-4681-97c7-6388ade1ebda">
<img width="1440" alt="Screenshot 2024-02-22 at 17 02 27" src="https://github.com/blockscout/blockscout/assets/17788043/c89befc4-5bb5-43ce-a6da-d06039be00ce">

</p>
</details>

**Comment by TbLtzk** [comment]
Any update on this?

**Comment by Kb00711** [comment]
I have created over 70 NFTs and have been first to mint but haven't received first minter Rewards or any Rewards at all since the 3rd NFT creation
