### ISSUE TITLE
OP Stack L2 Based - Deposit Not Sync On Explorer

### ISSUE THREAD

**Issue by avenbreaks** [blockscout/blockscout#9464]
### Optimism Stack Based (Sepolia) 

We built OP Stack based but in blockscout after 3 weeks running, deposit or withdrawal is no longer readable in explorer. although I tried again but it was completely invisible tx, but transactions from L1 > L2 in EOA address were accepted. 

Example: 
L1 > L2 Bridge Transaction (Sepolia) Readable
`https://onlyscan.info/tx/0x2bb7ab5a425eb5ce5d7b745132ab2e0d7ebdccff2729fa7036860e0a4586fa4d`

But in the Deposit menu there is no Tx visible last Bridge Tx update 3 Weeks ago: `https://onlyscan.info/l2-deposits`

### Type of the installation

Docker-compose

### Type of the JSON RPC archive node

geth

### Type of the chain

L2

### Link to the page

https://onlyscan.info

### Steps to reproduce

`DOCKER_REPO=blockscout-optimism docker compose -f docker-compose.yml up --build -d
`

### Backend version

latest

### Frontend version

latest

### Elixir & Erlang/OTP versions

Docker Images

### Operating system

Linux

### Additional information

The block explorer should still be able to synchronize transaction data from L1 > L2 and vice versa but after 3 weeks of running the explorer cannot retrieve transaction data again.

**Comment by avenbreaks** [comment]
@vbaranov @GimluCom

**Comment by sl1depengwyn** [comment]
I see fresh deposits on your url now, and particular deposit that you mention as well
From logs that you provided I can suggest that there was some problem with rpc
Is the issue resolved now?

**Comment by avenbreaks** [comment]
solved, need to restart explorer
