### ISSUE TITLE
I cannot get blockscout (production-filecoin) work!

### ISSUE THREAD

**Issue by EAG-es** [blockscout/blockscout#9465]
### Description

I follow the instructions:

`- Follow: `[https://docs.blockscout.com/for-developers/deployment/manual-deployment-guide/ubuntu-setup](https://docs.blockscout.com/for-developers/deployment/manual-deployment-guide/ubuntu-setup) 
[https://docs.blockscout.com/for-developers/deployment/manual-deployment-guide](https://docs.blockscout.com/for-developers/deployment/manual-deployment-guide)
```
sudo apt-get update
sudo apt-get install inotify-tools && sudo apt install make && sudo apt install g++
sudo apt-get install libudev-dev zip unzip build-essential cmake -y
sudo apt-get install git \ automake \ libtool inotify-tools \ libgmp-dev \ libgmp10 \ build-essential \ cmake -y

- Clone Asdf

git clone https://github.com/asdf-vm/asdf.git ~/.asdf
Edit your ubuntu profile
nano .profile

- Add this line in end break

. $HOME/.asdf/asdf.sh 

- Refresh your profile after the update

source ~/.profile

- Test active asdf after refresh

asdf version

- Add asdf plugin for erlang, elixir, and nodejs

asdf plugin add erlang
asdf plugin add elixir
asdf plugin add nodejs

- Install additional prerequisites

sudo apt-get -y install build-essential autoconf m4 libncurses5-dev libwxgtk3.0-gtk3-dev libwxgtk-webview3.0-gtk3-dev libgl1-mesa-dev libglu1-mesa-dev libpng-dev libssh-dev unixodbc-dev xsltproc fop libxml2-utils libncurses-dev openjdk-11-jdk

- Install PostgreSQL

adduser <username>
su - postgres
createuser --interactive <username>
createdb blockscout
psql
	ALTER USER <username> WITH PASSWORD '<username_password>';
	GRANT ALL PRIVILEGES ON DATABASE blockscout TO <username>;
	\q
exit
sudo systemctl restart postgresql
su - <username>
psql -d blockscout
	\q
exit
git clone -b production-filecoin https://github.com/blockscout/blockscout
cd blockscout-backend
asdf install
export DATABASE_URL=postgresql://<username>:<username_password>@localhost:5432/blockscout
mix do deps.get, local.rebar --force, deps.compile

```
`#FF0000` `** (Mix) Could not compile dependency :quantile_estimator, "/home/emilio/.asdf/installs/elixir/1.14.5-otp-25/.mix/elixir/1-14/rebar3 bare compile --paths /home/emilio/proyectos/blockscout-backend/_build/dev/lib/*/ebin" command failed. Errors may have been logged above. You can recompile this dependency with "mix deps.compile quantile_estimator", update it with "mix deps.update quantile_estimator" or clean it with "mix deps.clean quantile_estimator"`
```
mix deps.compile quantile_estimator
mix deps.update quantile_estimator
mix do deps.get, local.rebar --force, deps.compile
mix phx.gen.secret

```
`#FF0000` `** (Mix) Could not compile dependency :accept, "/home/emilio/.asdf/installs/elixir/1.14.5-otp-25/.mix/elixir/1-14/rebar3 bare compile --paths /home/emilio/proyectos/blockscout-backend/_build/dev/lib/*/ebin" command failed. Errors may have been logged above. You can recompile this dependency with "mix deps.compile accept", update it with "mix deps.update accept" or clean it with "mix deps.clean accept"`
```
mix deps.compile accept
mix deps.update accept
mix phx.gen.secret
```
### Type of the installation

Manual from the source code

### Type of the JSON RPC archive node

Geth (cronos in local computer)

### Type of the chain

L2 (Cronos in local computer)

### Backend version

production-filecoin

### Frontend version

production-filecoin: http://localhost:8080

### Elixir & Erlang/OTP versions

elixir 1.14.5-otp-25

### Operating system

Linux Mint 21 (Ubuntu 22.04)

**Comment by ekawibisono** [comment]
hello @EAG-es Can you Resume your problem on [discord blockscout](https://discord.gg/cVP4EsWb) ?

Thanks
