### ISSUE TITLE
Pulsechain blocksout api not work

### ISSUE THREAD

**Issue by DangLin012** [blockscout/blockscout#9480]
### Description

When test with url https://api.scan.pulsechain.com/api/v2/addresses/0x6109f0BB0d1485CE1BA27D1C99A90De6864c7fa0/transactions, the below error was reported:
"Internal server error"

### Type of the installation

Docker-compose

### Type of the JSON RPC archive node

Pulsechain

### Link to the page

https://pulsescan.live/#/api-docs

### Backend version

v5.3.3-pulsechain

### Elixir & Erlang/OTP versions

unknown

### Additional information

**User Agent:** Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36

**Comment by ekawibisono** [comment]
Hello @DangLin012 This problem on Pulsechain, Please Contact [PulseChain](https://t.me/PulseChainCom). This is blockscout github.

Thanks
