### ISSUE TITLE
Can't docker-compose up

### ISSUE THREAD

**Issue by Toni-d-e-v** [blockscout/blockscout#9496]
### Description

![image](https://github.com/blockscout/blockscout/assets/62844491/5c070a88-3da9-4098-8fd2-47cec4809988)

### Type of the installation

Docker-compose

### Type of the JSON RPC archive node

Besu

### Backend version

lastest

### Elixir & Erlang/OTP versions

lastest

**Comment by vbaranov** [comment]
@Toni-d-e-v which version of Docker do you use?

**Comment by Toni-d-e-v** [comment]
@vbaranov lastest

**Comment by Toni-d-e-v** [comment]
Docker version 25.0.3, build 4debf41
docker-compose version 1.29.2, build 5becea4c

**Comment by ekawibisono** [comment]
> Docker version 25.0.3, build 4debf41 docker-compose version 1.29.2, build 5becea4c

please use 
`docker compose up -d --build`

**Comment by ekawibisono** [comment]
![WhatsApp Image 2024-02-28 at 20 55 40_8a997261](https://github.com/blockscout/blockscout/assets/22586872/384880a8-ed30-41be-a6dd-79adf48b1754)

**Comment by vbaranov** [comment]
> Docker version 25.0.3, build 4debf41 docker-compose version 1.29.2, build 5becea4c

Could you update docker-compose up to v2?

**Comment by Toni-d-e-v** [comment]
![image](https://github.com/blockscout/blockscout/assets/62844491/ad2c08fc-e8a7-4eba-968f-f0594d1e1dee)
V2 still does not work?

**Comment by Toni-d-e-v** [comment]
![image](https://github.com/blockscout/blockscout/assets/62844491/6428c3f8-c4c3-4cf1-ab50-1b0e7560aa2b)

**Comment by vbaranov** [comment]
@Toni-d-e-v do you have [these changes](https://github.com/blockscout/blockscout/pull/9196/files) in your env?

**Comment by Toni-d-e-v** [comment]
@vbaranov  its lastest git cloned few times today

**Comment by GimluCom** [comment]
Looks like there is a breaking change introduced in Docker Compose version `v2.24.6`

At the moment you may work around the issue by using a previous release of Docker Compose, such as `v2.24.5`

**Comment by GimluCom** [comment]
Here is how you may install a specific Docker Compose version on Ubuntu.
First run this command:
```console
$ apt show -a docker-compose-plugin | grep "Version" | grep -v "2.24.6"
Version: 2.24.5-1~ubuntu.22.04~jammy
Version: 2.24.2-1~ubuntu.22.04~jammy
Version: 2.24.1-1~ubuntu.22.04~jammy
```
Then install the first version listed above, for example:
```console
$ apt install docker-compose-plugin=2.24.5-1~ubuntu.22.04~jammy
```

Alternatively it can be installed manually using this method: https://docs.docker.com/compose/install/linux/#install-the-plugin-manually

**Comment by vbaranov** [comment]
@Toni-d-e-v compatibility with docker-compose 2.24.6 is added in #9512. Could you please try?

**Comment by Toni-d-e-v** [comment]
@GimluCom 
![image](https://github.com/blockscout/blockscout/assets/62844491/0b5302f8-7d6b-4e6b-b544-b1a5316e7a29)

**Comment by Toni-d-e-v** [comment]
@vbaranov  Works now, thanks man
