### ISSUE TITLE
Zetachain mainnet explorer user area issue

### ISSUE THREAD

**Issue by ronaldoguedess** [blockscout/blockscout#9497]
### Description

I cant sign in in the zetachain mainnet explorer to insert custom abi.
please, fix that asap.

![Screenshot_357](https://github.com/blockscout/blockscout/assets/18597639/07732b4e-7602-4fc1-946b-bf414048f099)

### Link to the page

https://zetachain.blockscout.com/auth/auth0/callback?path=%2F&code=SCUp7MzmLge4yimw-phxuDNnoQqRgoQ2vncTTui0Nihgj

### Steps to reproduce

1 - Go to explorer on Zetachain Main net
2 - Click to log-in

**Comment by vbaranov** [comment]
The issue with login on Zetachain Mainnet instance resolved.
