### ISSUE TITLE
Wrong address

### ISSUE THREAD

**Issue by Asiia0706** [blockscout/blockscout#9499]
### Description

Hello! February 27 I sent  crypto USDT by ERC20. How can I cancel this transaction because I didn't receive it on my ShakePay Wallet.
![IMG_20240228_000746_298](https://github.com/blockscout/blockscout/assets/161649333/5717829f-b836-4fef-a0b4-950483437d39)

### Type of the installation

Docker-compose

### Type of the JSON RPC archive node

geth

### Link to the page

0xc9d2c0bb76d9fc9e4ed2df3a2cdb0de79bc7bfe5e4fafe1fe71c7d41e570bd20

### Backend version

v5.3.3-kava

### Elixir & Erlang/OTP versions

Elixir 1.14.5 Erlang/OTP 25

### Operating system

unix linux

### Additional information

The issue happened at Kava 10 Blockscout instance

**Comment by vbaranov** [comment]
This chat is for Blockscout-related questions. Your question is out of scope, where the Blockscout team can help.
