### ISSUE TITLE
hello, my NFT got on the block during claiming

### ISSUE THREAD

**Issue by Abdykadyr97** [blockscout/blockscout#9500]
### Description

hello, my NFT got on the block during claiming. Block #13946079. what do I need to do to pick up my NFT

### Type of the installation

Docker-compose

### Type of the JSON RPC archive node

geth

### Link to the page

https://andromeda-explorer.metis.io/token/0xf29ea76d01ccfa2f8772519a3813078d267b080d/instance/63260/token-transfers

### Backend version

v5.3.3-beta

### Elixir & Erlang/OTP versions

Elixir 1.14.5 Erlang/OTP 24

### Operating system

unix linux

### Additional information

The issue happened at Andromeda Blockscout instance

**Comment by sl1depengwyn** [comment]
This repo is for Blockscout-related questions. Blockscout is an open source blockchain explorer. Thus, your question is out of scope, where the Blockscout team can help, you better contact the chain support directly.
