### ISSUE TITLE
Used Kava to Coinbase

### ISSUE THREAD

**Issue by davidkartiganer** [blockscout/blockscout#9501]
### Description

I sent about $700 worth of tether to coinbase using kava not realizing that coinbase doesnt accept kava. Is there any way to recover the tether i sent to this wallet?

### Type of the installation

Docker-compose

### Type of the JSON RPC archive node

geth

### Type of the chain

Kava

### Link to the page

https://kavascan.com/tx/0xec4c829f3f834d320a821168d6a5af7f2c94fe9e8a9f0ccb0a93d6890e6fb64b

### Backend version

v5.3.3-kava

### Elixir & Erlang/OTP versions

Elixir 1.14.5 Erlang/OTP 25

### Operating system

unix linux

### Additional information

The issue happened at Kava 10 Blockscout instance

**Comment by vbaranov** [comment]
This chat is for Blockscout-related questions. Your question is out of scope, where the Blockscout team can help.
