### ISSUE TITLE
过了7天还不到账

### ISSUE THREAD

**Issue by houyao2025** [blockscout/blockscout#9507]
### Description

跨链交易成功七天之后还不到账
<img width="715" alt="屏幕截图 2024-03-01 142440" src="https://github.com/blockscout/blockscout/assets/158189269/f8047c74-63d4-45a6-b600-276304e09f73">

### Type of the installation

Docker-compose

### Type of the JSON RPC archive node

OpenEth

### Type of the chain

L2

### Link to the page

https://explorer.mode.network/tx/0xaba187cfc4344fc3e6b7c1685751106950812ce680a5cf7d7fb6d1a29bd5b8be

### Backend version

v5.4.0-beta.+commit.63747320

### Frontend version

v1.11.1

### Elixir & Erlang/OTP versions

elixir

### Operating system

Windows

### Additional information

**User Agent:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36

**Comment by vbaranov** [comment]
This chat is for Blockscout-related questions. Your question is out of scope, where the Blockscout team can help.
