### ISSUE TITLE
Unable to receive my withdrawn ETH into my wallet

### ISSUE THREAD

**Issue by 13hanu** [blockscout/blockscout#9508]
### Description

Hi Team, 

I didn't receive my ETH into my wallet yet. As part of MANTA New Paradigm, first i linked my Binance wallet to manta mainnet and deposited ETH, later i tried to withdraw the ETH in manta mainnet but i didn't received into my binance web3 wallet yet. In binance history it is displaying a smart contract. 

Below is my transaction hash
0xd44dea748d8afa72a8b13399920dea5126fc278a8042626d2043fb438a8889ef
  
Could you please help me to receive my ETH into my wallet?

Thanks,
Bhanu

### Type of the installation

Docker-compose

### Type of the JSON RPC archive node

No idea

### Type of the chain

L1

### Link to the page

https://pacific-explorer.manta.network/tx/0xd44dea748d8afa72a8b13399920dea5126fc278a8042626d2043fb438a8889ef

### Backend version

No idea

### Frontend version

No idea

### Elixir & Erlang/OTP versions

No idea

### Operating system

Windows 

### Additional information

**User Agent:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36

**Comment by vbaranov** [comment]
This chat is for Blockscout-related questions. Your question is out of scope, where the Blockscout team can help.
