### ISSUE TITLE
Metis not credited to coinex ac

### ISSUE THREAD

**Issue by Rk616831** [blockscout/blockscout#9513]
### Description

I am transferring metis matamaxe to coinex but it is not transferred 

### Type of the installation

Docker-compose

### Type of the JSON RPC archive node

geth

### Type of the chain

L1

### Backend version

v5.3.3-beta

### Elixir & Erlang/OTP versions

Elixir 1.14.5 Erlang/OTP 24

### Operating system

unix linux

### Additional information

The issue happened at Metis Sepolia Blockscout instance

**Comment by ulyanas** [comment]
@Rk616831  


Please contact Metis and Coinex for support.

Looks like the issue occurred with the Metis Sepolia. It's important to note that if you are using the Metis testnet, it is primarily intended for testing purposes and may not be compatible with exchanges.
