### ISSUE TITLE
Backend crash on start, docker-compose newest patch

### ISSUE THREAD

**Issue by Toni-d-e-v** [blockscout/blockscout#9517]
### Description

![image](https://github.com/blockscout/blockscout/assets/62844491/cc8871d4-6a35-4fa3-8ef2-0a7b0e6021fa)
![image](https://github.com/blockscout/blockscout/assets/62844491/b57403c2-26ca-4c3c-8ebf-eb5b398fe90d)

### Type of the installation

Docker-compose

### Type of the JSON RPC archive node

,

### Backend version

.

### Elixir & Erlang/OTP versions

.

**Comment by ekawibisono** [comment]
Hello, If In Github no respon, you can submit issue on discord blockscout. This link invite
https://discord.gg/92aZF93c

Thanks

**Comment by Toni-d-e-v** [comment]
It just loops
![image](https://github.com/blockscout/blockscout/assets/62844491/b029cbbf-3ad7-4ef7-b43d-d91cdd18d0fc)

**Comment by Toni-d-e-v** [comment]
Can't find solution and I need it quick!
@vbaranov

**Comment by Toni-d-e-v** [comment]
https://github.com/blockscout/blockscout/assets/62844491/7e28992f-a7e3-4a7b-a0c6-48b241bdc228

**Comment by avenbreaks** [comment]
> 
> https://github.com/blockscout/blockscout/assets/62844491/7e28992f-a7e3-4a7b-a0c6-48b241bdc228
> 
> 

If you use 6.2.2-beta try to downgrade 6.1.x version, i got same issue on 6.2.2-beta but now im change version

**Comment by vbaranov** [comment]
@Toni-d-e-v how do you run docker compose and what kid of archive node JSON RPC endpoint do you use?
