### ISSUE TITLE
Coingecko new api integration request 

### ISSUE THREAD

**Issue by ohari5336** [blockscout/blockscout#9521]
### Description

I have coingecko free beta api plan. Can any one implement free api base url and option in blockscout.

curl --request GET \
     --url https://api.coingecko.com/api/v3/coins/larissa-blockchain \
     --header 'x-cg-demo-api-key: CG-XYZ'

### Type of the installation

Docker-compose

### Type of the JSON RPC archive node

Geth

### Type of the chain

L1

### Backend version

Backend: kf-arm-build-test2

### Elixir & Erlang/OTP versions

Not know

**Comment by Mamu364014** [comment]
Can anyone give me a hand with understanding and doing this correctly plz. I don't understand this at all. Thank you.

**Comment by vbaranov** [comment]
@ohari5336 CoinGecko API is supported by Blockscout. See https://docs.blockscout.com/for-developers/information-and-settings/env-variables#exchange-rates-management

**Comment by ohari5336** [comment]
Currently blockscout support only paid plan api which base url: https://pro-api.coingecko.com/api/v3

But I want to add support coingecko new free plan api which base url: https://api.coingecko.com/api/v3

![Screenshot_20240310231427](https://github.com/blockscout/blockscout/assets/22674877/b1538a99-b550-45c7-8768-89e5068d686c)

**Comment by ohari5336** [comment]
Please Reopen this issue

**Comment by GimluCom** [comment]
Currently if the ENV `EXCHANGE_RATES_COINGECKO_API_KEY` is empty, the https://api.coingecko.com/api/v3 endpoint is used automatically.
I assume your issue that you would like to use a Demo Account API key?

**Comment by ohari5336** [comment]
Yes I want to use demo api key, because when EXCHANGE_RATES_COINGECKO_API_KEY env is empty not getting price
