### ISSUE TITLE
Not a bug. I made a mistake.

### ISSUE THREAD

**Issue by ChizKid** [blockscout/blockscout#9522]
### Description

Hello, i made a transfer using kava when I shouldve used ERC20. Is my money able to get recovered? 

### Type of the installation

Docker-compose

### Type of the JSON RPC archive node

geth

### Backend version

v5.3.3-kava

### Elixir & Erlang/OTP versions

Elixir 1.14.5 Erlang/OTP 25

### Operating system

unix linux

### Additional information

The issue happened at Kava 10 Blockscout instance

**Comment by ekawibisono** [comment]
Hello @ChizKid , This is github blockscout, please contact Kava Team.

Thanks
