### ISSUE TITLE
0x0E803aD182d5F2682fAc70ae0A464816F3968c48

### ISSUE THREAD

**Issue by Marianos15** [blockscout/blockscout#9523]
### Description

0x0E803aD182d5F2682fAc70ae0A464816F3968c48

### Type of the installation

Docker-compose

### Type of the JSON RPC archive node

Eth

### Type of the chain

L1

### Link to the page

https://explorer.karak.network/address/0x0E803aD182d5F2682fAc70ae0A464816F3968c48

### Steps to reproduce

0x0E803aD182d5F2682fAc70ae0A464816F3968c48

### Backend version

v6.1.0-beta.+commit.d42d34e5

### Frontend version

v1.25.0-alpha.2+c6133dc4

### Elixir & Erlang/OTP versions

0x0E803aD182d5F2682fAc70ae0A464816F3968c48

### Operating system

0x0E803aD182d5F2682fAc70ae0A464816F3968c48

### Additional information

**User Agent:** Mozilla/5.0 (Linux; U; Android 8.1.0; pl-pl; Redmi 5 Plus Build/OPM1.171019.019) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/100.0.4896.127 Mobile Safari/537.36 XiaoMi/MiuiBrowser/13.14.2-go

**Comment by Marianos15** [comment]
Good

**Comment by ekawibisono** [comment]
Hello @Marianos15 This is blockscout github, please contact Karak Network. 

Thanks
