### ISSUE TITLE
I can't find my helmet nft 

### ISSUE THREAD

**Issue by Javed3788** [blockscout/blockscout#9526]
### Description

I already mint bassed nft but if isee my nft I can see

### Type of the installation

Docker-compose

### Type of the JSON RPC archive node

geth

### Type of the chain

L1

### Link to the page

https://decentralize.metis.io/

### Backend version

v5.3.3-beta

### Elixir & Erlang/OTP versions

Elixir 1.14.5 Erlang/OTP 24

### Operating system

unix linux

### Additional information

The issue happened at Andromeda Blockscout instance

**Comment by ekawibisono** [comment]
Hello @Javed3788 , This is blockscout github, please contact Andromeda Team, Thanks
