### ISSUE TITLE
My id is block i think  beacuse i dont have nft but i participate in testnet and i have 34k xp token plese solve my problem and give nft token 

### ISSUE THREAD

**Issue by chandan14300** [blockscout/blockscout#9527]
### Description

Hii My id is block i think  beacuse i dont have nft but i participate in testnet and i have 34k xp token plese solve my problem and give nft token 

### Type of the installation

Docker-compose

### Type of the JSON RPC archive node

geth

### Steps to reproduce

Yes  My id is block i think  beacuse i dont have nft but i participate in testnet and i have 34k xp token plese solve my problem and give nft token 

### Backend version

v5.3.3-beta

### Elixir & Erlang/OTP versions

Elixir 1.14.5 Erlang/OTP 24

### Operating system

unix linux

### Additional information

The issue happened at Andromeda Blockscout instance 
My id is block i think  beacuse i dont have nft but i participate in testnet and i have 34k xp token plese solve my problem and give nft token

**Comment by ekawibisono** [comment]
Hello @chandan14300 This is github blockscout, please contact [Andromeda Team](https://t.me/MetisDAO). Andromeda is Deploy Self, not using blockscout instance.
![image](https://github.com/blockscout/blockscout/assets/22586872/266a4dea-5bf7-4cf2-bc85-ed9d99743a98)
https://docs.blockscout.com/about/projects
