### ISSUE TITLE
Return numbers as string in contract methods result

### ISSUE THREAD

**Issue by yvaskov** [blockscout/blockscout#9536]
## Description

Frontend converts big numbers in contract method result to exponential notation ([MAX_SAFE_INTEGER](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number/MAX_SAFE_INTEGER)). Example:

https://unreal.blockscout.com/address/0x66d6B9c8E4A44B1B36bdA16e1Ba930CA6881Fa69?tab=read_contract
Method: `getQuoteAtCurrentTick`
Args:
```
0x9801EEB848987c0A8d6443912827bD36C288F8FB
0x83feDBc0B85c6e29B589aA6BdefB1Cc581935ECD
3000
```

![Image](https://github.com/blockscout/frontend/assets/72267126/7e8ecf96-0503-4160-bf94-f89ef21b0364)

## Solution

To avoid this backend needs to return numbers as string.

## Version

[v6.1.0-beta](https://github.com/blockscout/blockscout/tree/v6.1.0-beta)
[v1.24.1](https://github.com/blockscout/frontend/tree/v1.24.1)

**Comment by fedor-ivn** [comment]
Seems like this was already fixed in this PR: https://github.com/blockscout/blockscout/pull/9529
