### ISSUE TITLE
I din't receive my 220 bone from the shibarium network in the ethereum networ in the metamask wallet

### ISSUE THREAD

**Issue by Daci23** [blockscout/blockscout#9559]
### Description

Hello. Yesterday i made a transaction from the Shibarium network in the Etereum network on the metamask wallet. The transaction was successful but i didn't recive the 220 bone that i transfered.
This is my transaction.
https://www.shibariumscan.io/tx/0x7e31cd500c026e86fbc8f4836815e5918ac30daac49b8971f4e251dbd851b280

Thank you

### Type of the installation

Docker-compose

### Type of the JSON RPC archive node

Shibarium

### Type of the chain

Shibarium 

### Link to the page

https://www.shibariumscan.io/tx/0x7e31cd500c026e86fbc8f4836815e5918ac30daac49b8971f4e251dbd851b280

### Steps to reproduce

Hello. Yesterday i made a transaction from the Shibarium network in the Etereum network on the metamask wallet. The transaction was successful but i didn't recive the 220 bone that i transfered.
This is my transaction.
https://www.shibariumscan.io/tx/0x7e31cd500c026e86fbc8f4836815e5918ac30daac49b8971f4e251dbd851b280

Thank you

### Backend version

V6.1.0

### Elixir & Erlang/OTP versions

1

### Operating system

Android

**Comment by vbaranov** [comment]
This chat is for Blockscout-related questions. Your question is out of scope, where the Blockscout team can help.
