### ISSUE TITLE
Block Catchup - Hyperledger Besu

### ISSUE THREAD

**Issue by avenbreaks** [blockscout/blockscout#9569]
### Description

Run Besu From Genesis (Private Network) but getting error on fetcher block 

```
{"time":"2024-03-06T17:59:06.417Z","severity":"info","message":"Checking if index needs to catch up in 2500ms.","metadata":{"fetcher":"block_catchup"}}
{"time":"2024-03-06T17:59:09.058Z","severity":"info","message":"Index had to catch up.","metadata":{"fetcher":"block_catchup","first_block_number":3068916,"last_block_number":2689169,"missing_block_count":10,"shrunk":false}}
{"time":"2024-03-06T17:59:09.058Z","severity":"info","message":"Checking if index needs to catch up in 2500ms.","metadata":{"fetcher":"block_catchup"}}
{"time":"2024-03-06T17:59:11.979Z","severity":"info","message":"Index had to catch up.","metadata":{"fetcher":"block_catchup","first_block_number":3068916,"last_block_number":2302184,"missing_block_count":10,"shrunk":false}}
{"time":"2024-03-06T17:59:11.979Z","severity":"info","message":"Checking if index needs to catch up in 2500ms.","metadata":{"fetcher":"block_catchup"}}
{"time":"2024-03-06T17:59:14.258Z","severity":"info","message":"Start sanitizing of empty blocks. Batch size is 100","metadata":{"fetcher":"empty_blocks_to_refetch"}}
{"time":"2024-03-06T17:59:14.262Z","severity":"info","message":"Batch of empty blocks is sanitized","metadata":{"fetcher":"empty_blocks_to_refetch"}}
{"time":"2024-03-06T17:59:14.709Z","severity":"info","message":"Index had to catch up.","metadata":{"fetcher":"block_catchup","first_block_number":3068916,"last_block_number":2689169,"missing_block_count":10,"shrunk":false}}
{"time":"2024-03-06T17:59:14.709Z","severity":"info","message":"Checking if index needs to catch up in 2500ms.","metadata":{"fetcher":"block_catchup"}}
{"time":"2024-03-06T17:59:17.630Z","severity":"info","message":"Index had to catch up.","metadata":{"fetcher":"block_catchup","first_block_number":3068916,"last_block_number":2689169,"missing_block_count":10,"shrunk":false}}
{"time":"2024-03-06T17:59:17.630Z","severity":"info","message":"Checking if index needs to catch up in 2500ms.","metadata":{"fetcher":"block_catchup"}}
```

### Type of the installation

Docker-compose

### Type of the JSON RPC archive node

Besu

### Type of the chain

L1

### Backend version

v6.1.0-beta

### Frontend version

latest

### Elixir & Erlang/OTP versions

-

### Operating system

Linux

**Comment by Toni-d-e-v** [comment]
same

**Comment by Toni-d-e-v** [comment]
@vbaranov

**Comment by vbaranov** [comment]
I don't see errors in the provided logs. This is normal behaviour.

**Comment by avenbreaks** [comment]
> I don't see errors in the provided logs. This is normal behaviour.

thanks, solved sir. 

now on my client explorer L2 Based Optimism got error like this : 

```
{"time":"2024-03-09T06:09:06.575Z","severity":"error","message":"Failed to decode Ethereum JSONRPC response:\n\n  request:\n\n    url: https://onlylayer.org\n\n    body: [{\"id\":16,\"jsonrpc\":\"2.0\",\"method\":\"eth_getBalance\",\"params\":[\"0x4200000000000000000000000000000000000011\",\"0x1AC847\"]},{\"id\":79,\"jsonrpc\":\"2.0\",\"method\":\"eth_getBalance\",\"params\":[\"0x4200000000000000000000000000000000000015\",\"0x1AC80E\"]},{\"id\":18,\"jsonrpc\":\"2.0\",\"method\":\"eth_getBalance\",\"params\":[\"0xdeaddeaddeaddeaddeaddeaddeaddeaddead0001\",\"0x1AC847\"]},{\"id\":54,\"jsonrpc\":\"2.0\",\"method\":\"eth_getBalance\",\"params\":[\"0x4200000000000000000000000000000000000011\",\"0x1AC7CB\"]},{\"id\":5,\"jsonrpc\":\"2.0\",\"method\":\"eth_getBalance\",\"params\":[\"0x4200000000000000000000000000000000000015\",\"0x1AC842\"]},{\"id\":65,\"jsonrpc\":\"2.0\",\"method\":\"eth_getBalance\",\"params\":[\"0xdeaddeaddeaddeaddeaddeaddeaddeaddead0001\"\n\n  response:\n\n    status code: 500\n\n    body: <html>\r\n<head><title>500 Internal Server Error</title></head>\r\n<body>\r\n<center><h1>500 Internal Server Error</h1></center>\r\n<hr><center>nginx/1.18.0 (Ubuntu)</center>\r\n</body>\r\n</html>\r\n\n","metadata":{"count":100,"fetcher":"coin_balance_realtime"}}
{"time":"2024-03-09T06:09:06.575Z","severity":"error","message":"failed to fetch: {:bad_response, \"https://onlylayer.org\"}","metadata":{"count":100,"error_count":100,"fetcher":"coin_balance_realtime"}}
{"time":"2024-03-09T06:09:14.433Z","severity":"info","message":"Start sanitizing of empty blocks. Batch size is 100","metadata":{"fetcher":"empty_blocks_to_refetch"}}
{"time":"2024-03-09T06:09:14.841Z","severity":"info","message":"Batch of empty blocks is sanitized","metadata":{"fetcher":"empty_blocks_to_refetch"}}
{"time":"2024-03-09T06:09:16.225Z","severity":"info","message":"Start handling L1 block #5447214.","metadata":{"fetcher":"optimism_output_roots"}}
{"time":"2024-03-09T06:09:16.265Z","severity":"info","message":"Finish handling L1 block #5447214. Found 1 OutputProposed event(s).","metadata":{"fetcher":"optimism_output_roots"}}
{"time":"2024-03-09T06:09:17.381Z","severity":"error","message":"Failed to decode Ethereum JSONRPC response:\n\n  request:\n\n    url: https://onlylayer.org\n\n    body: [{\"id\":16,\"jsonrpc\":\"2.0\",\"method\":\"eth_getBalance\",\"params\":[\"0x4200000000000000000000000000000000000015\",\"0x1AC4A0\"]},{\"id\":79,\"jsonrpc\":\"2.0\",\"method\":\"eth_getBalance\",\"params\":[\"0x4200000000000000000000000000000000000015\",\"0x1AC2FC\"]},{\"id\":18,\"jsonrpc\":\"2.0\",\"method\":\"eth_getBalance\",\"params\":[\"0x4200000000000000000000000000000000000015\",\"0x1AC4A2\"]},{\"id\":54,\"jsonrpc\":\"2.0\",\"method\":\"eth_getBalance\",\"params\":[\"0xdeaddeaddeaddeaddeaddeaddeaddeaddead0001\",\"0x1AC4A8\"]},{\"id\":5,\"jsonrpc\":\"2.0\",\"method\":\"eth_getBalance\",\"params\":[\"0xdeaddeaddeaddeaddeaddeaddeaddeaddead0001\",\"0x1AC5FE\"]},{\"id\":65,\"jsonrpc\":\"2.0\",\"method\":\"eth_getBalance\",\"params\":[\"0x4200000000000000000000000000000000000011\"\n\n  response:\n\n    status code: 500\n\n    body: <html>\r\n<head><title>500 Internal Server Error</title></head>\r\n<body>\r\n<center><h1>500 Internal Server Error</h1></center>\r\n<hr><center>nginx/1.18.0 (Ubuntu)</center>\r\n</body>\r\n</html>\r\n\n","metadata":{"count":100,"fetcher":"coin_balance_catchup"}}
{"time":"2024-03-09T06:09:17.381Z","severity":"error","message":"failed to fetch: {:bad_response, \"https://onlylayer.org\"}","metadata":{"count":100,"error_count":100,"fetcher":"coin_balance_catchup"}}
{"time":"2024-03-09T06:09:17.524Z","severity":"info","message":"Start handling L1 block #5447214.","metadata":{"fetcher":"optimism_withdrawal_events"}}
{"time":"2024-03-09T06:09:17.542Z","severity":"info","message":"Finish handling L1 block #5447214. Found 0 WithdrawalProven/WithdrawalFinalized event(s).","metadata":{"fetcher":"optimism_withdrawal_events"}}
{"time":"2024-03-09T06:09:21.366Z","severity":"error","message":"Failed to decode Ethereum JSONRPC response:\n\n  request:\n\n    url: https://onlylayer.org\n\n    body: [{\"id\":16,\"jsonrpc\":\"2.0\",\"method\":\"eth_getBalance\",\"params\":[\"0x4200000000000000000000000000000000000015\",\"0x1AC45F\"]}
```

**Comment by vbaranov** [comment]
> > I don't see errors in the provided logs. This is normal behaviour.
> 
> thanks, solved sir.
> 
> now on my client explorer L2 Based Optimism got error like this :
> 
> ```
> {"time":"2024-03-09T06:09:06.575Z","severity":"error","message":"Failed to decode Ethereum JSONRPC response:\n\n  request:\n\n    url: https://onlylayer.org\n\n    body: [{\"id\":16,\"jsonrpc\":\"2.0\",\"method\":\"eth_getBalance\",\"params\":[\"0x4200000000000000000000000000000000000011\",\"0x1AC847\"]},{\"id\":79,\"jsonrpc\":\"2.0\",\"method\":\"eth_getBalance\",\"params\":[\"0x4200000000000000000000000000000000000015\",\"0x1AC80E\"]},{\"id\":18,\"jsonrpc\":\"2.0\",\"method\":\"eth_getBalance\",\"params\":[\"0xdeaddeaddeaddeaddeaddeaddeaddeaddead0001\",\"0x1AC847\"]},{\"id\":54,\"jsonrpc\":\"2.0\",\"method\":\"eth_getBalance\",\"params\":[\"0x4200000000000000000000000000000000000011\",\"0x1AC7CB\"]},{\"id\":5,\"jsonrpc\":\"2.0\",\"method\":\"eth_getBalance\",\"params\":[\"0x4200000000000000000000000000000000000015\",\"0x1AC842\"]},{\"id\":65,\"jsonrpc\":\"2.0\",\"method\":\"eth_getBalance\",\"params\":[\"0xdeaddeaddeaddeaddeaddeaddeaddeaddead0001\"\n\n  response:\n\n    status code: 500\n\n    body: <html>\r\n<head><title>500 Internal Server Error</title></head>\r\n<body>\r\n<center><h1>500 Internal Server Error</h1></center>\r\n<hr><center>nginx/1.18.0 (Ubuntu)</center>\r\n</body>\r\n</html>\r\n\n","metadata":{"count":100,"fetcher":"coin_balance_realtime"}}
> {"time":"2024-03-09T06:09:06.575Z","severity":"error","message":"failed to fetch: {:bad_response, \"https://onlylayer.org\"}","metadata":{"count":100,"error_count":100,"fetcher":"coin_balance_realtime"}}
> {"time":"2024-03-09T06:09:14.433Z","severity":"info","message":"Start sanitizing of empty blocks. Batch size is 100","metadata":{"fetcher":"empty_blocks_to_refetch"}}
> {"time":"2024-03-09T06:09:14.841Z","severity":"info","message":"Batch of empty blocks is sanitized","metadata":{"fetcher":"empty_blocks_to_refetch"}}
> {"time":"2024-03-09T06:09:16.225Z","severity":"info","message":"Start handling L1 block #5447214.","metadata":{"fetcher":"optimism_output_roots"}}
> {"time":"2024-03-09T06:09:16.265Z","severity":"info","message":"Finish handling L1 block #5447214. Found 1 OutputProposed event(s).","metadata":{"fetcher":"optimism_output_roots"}}
> {"time":"2024-03-09T06:09:17.381Z","severity":"error","message":"Failed to decode Ethereum JSONRPC response:\n\n  request:\n\n    url: https://onlylayer.org\n\n    body: [{\"id\":16,\"jsonrpc\":\"2.0\",\"method\":\"eth_getBalance\",\"params\":[\"0x4200000000000000000000000000000000000015\",\"0x1AC4A0\"]},{\"id\":79,\"jsonrpc\":\"2.0\",\"method\":\"eth_getBalance\",\"params\":[\"0x4200000000000000000000000000000000000015\",\"0x1AC2FC\"]},{\"id\":18,\"jsonrpc\":\"2.0\",\"method\":\"eth_getBalance\",\"params\":[\"0x4200000000000000000000000000000000000015\",\"0x1AC4A2\"]},{\"id\":54,\"jsonrpc\":\"2.0\",\"method\":\"eth_getBalance\",\"params\":[\"0xdeaddeaddeaddeaddeaddeaddeaddeaddead0001\",\"0x1AC4A8\"]},{\"id\":5,\"jsonrpc\":\"2.0\",\"method\":\"eth_getBalance\",\"params\":[\"0xdeaddeaddeaddeaddeaddeaddeaddeaddead0001\",\"0x1AC5FE\"]},{\"id\":65,\"jsonrpc\":\"2.0\",\"method\":\"eth_getBalance\",\"params\":[\"0x4200000000000000000000000000000000000011\"\n\n  response:\n\n    status code: 500\n\n    body: <html>\r\n<head><title>500 Internal Server Error</title></head>\r\n<body>\r\n<center><h1>500 Internal Server Error</h1></center>\r\n<hr><center>nginx/1.18.0 (Ubuntu)</center>\r\n</body>\r\n</html>\r\n\n","metadata":{"count":100,"fetcher":"coin_balance_catchup"}}
> {"time":"2024-03-09T06:09:17.381Z","severity":"error","message":"failed to fetch: {:bad_response, \"https://onlylayer.org\"}","metadata":{"count":100,"error_count":100,"fetcher":"coin_balance_catchup"}}
> {"time":"2024-03-09T06:09:17.524Z","severity":"info","message":"Start handling L1 block #5447214.","metadata":{"fetcher":"optimism_withdrawal_events"}}
> {"time":"2024-03-09T06:09:17.542Z","severity":"info","message":"Finish handling L1 block #5447214. Found 0 WithdrawalProven/WithdrawalFinalized event(s).","metadata":{"fetcher":"optimism_withdrawal_events"}}
> {"time":"2024-03-09T06:09:21.366Z","severity":"error","message":"Failed to decode Ethereum JSONRPC response:\n\n  request:\n\n    url: https://onlylayer.org\n\n    body: [{\"id\":16,\"jsonrpc\":\"2.0\",\"method\":\"eth_getBalance\",\"params\":[\"0x4200000000000000000000000000000000000015\",\"0x1AC45F\"]}
> ```

`https://onlylayer.org` which, I assume, you use for `ETHEREUM_JSONRPC_HTTP_URL`, return errors on batched request of `eth_getBalance` method.

**Comment by vbaranov** [comment]
> > > > I don't see errors in the provided logs. This is normal behaviour.
> > > 
> > > 
> > > thanks, solved sir.
> > > now on my client explorer L2 Based Optimism got error like this :
> > > ```
> > > {"time":"2024-03-09T06:09:06.575Z","severity":"error","message":"Failed to decode Ethereum JSONRPC response:\n\n  request:\n\n    url: https://onlylayer.org\n\n    body: [{\"id\":16,\"jsonrpc\":\"2.0\",\"method\":\"eth_getBalance\",\"params\":[\"0x4200000000000000000000000000000000000011\",\"0x1AC847\"]},{\"id\":79,\"jsonrpc\":\"2.0\",\"method\":\"eth_getBalance\",\"params\":[\"0x4200000000000000000000000000000000000015\",\"0x1AC80E\"]},{\"id\":18,\"jsonrpc\":\"2.0\",\"method\":\"eth_getBalance\",\"params\":[\"0xdeaddeaddeaddeaddeaddeaddeaddeaddead0001\",\"0x1AC847\"]},{\"id\":54,\"jsonrpc\":\"2.0\",\"method\":\"eth_getBalance\",\"params\":[\"0x4200000000000000000000000000000000000011\",\"0x1AC7CB\"]},{\"id\":5,\"jsonrpc\":\"2.0\",\"method\":\"eth_getBalance\",\"params\":[\"0x4200000000000000000000000000000000000015\",\"0x1AC842\"]},{\"id\":65,\"jsonrpc\":\"2.0\",\"method\":\"eth_getBalance\",\"params\":[\"0xdeaddeaddeaddeaddeaddeaddeaddeaddead0001\"\n\n  response:\n\n    status code: 500\n\n    body: <html>\r\n<head><title>500 Internal Server Error</title></head>\r\n<body>\r\n<center><h1>500 Internal Server Error</h1></center>\r\n<hr><center>nginx/1.18.0 (Ubuntu)</center>\r\n</body>\r\n</html>\r\n\n","metadata":{"count":100,"fetcher":"coin_balance_realtime"}}
> > > {"time":"2024-03-09T06:09:06.575Z","severity":"error","message":"failed to fetch: {:bad_response, \"https://onlylayer.org\"}","metadata":{"count":100,"error_count":100,"fetcher":"coin_balance_realtime"}}
> > > {"time":"2024-03-09T06:09:14.433Z","severity":"info","message":"Start sanitizing of empty blocks. Batch size is 100","metadata":{"fetcher":"empty_blocks_to_refetch"}}
> > > {"time":"2024-03-09T06:09:14.841Z","severity":"info","message":"Batch of empty blocks is sanitized","metadata":{"fetcher":"empty_blocks_to_refetch"}}
> > > {"time":"2024-03-09T06:09:16.225Z","severity":"info","message":"Start handling L1 block #5447214.","metadata":{"fetcher":"optimism_output_roots"}}
> > > {"time":"2024-03-09T06:09:16.265Z","severity":"info","message":"Finish handling L1 block #5447214. Found 1 OutputProposed event(s).","metadata":{"fetcher":"optimism_output_roots"}}
> > > {"time":"2024-03-09T06:09:17.381Z","severity":"error","message":"Failed to decode Ethereum JSONRPC response:\n\n  request:\n\n    url: https://onlylayer.org\n\n    body: [{\"id\":16,\"jsonrpc\":\"2.0\",\"method\":\"eth_getBalance\",\"params\":[\"0x4200000000000000000000000000000000000015\",\"0x1AC4A0\"]},{\"id\":79,\"jsonrpc\":\"2.0\",\"method\":\"eth_getBalance\",\"params\":[\"0x4200000000000000000000000000000000000015\",\"0x1AC2FC\"]},{\"id\":18,\"jsonrpc\":\"2.0\",\"method\":\"eth_getBalance\",\"params\":[\"0x4200000000000000000000000000000000000015\",\"0x1AC4A2\"]},{\"id\":54,\"jsonrpc\":\"2.0\",\"method\":\"eth_getBalance\",\"params\":[\"0xdeaddeaddeaddeaddeaddeaddeaddeaddead0001\",\"0x1AC4A8\"]},{\"id\":5,\"jsonrpc\":\"2.0\",\"method\":\"eth_getBalance\",\"params\":[\"0xdeaddeaddeaddeaddeaddeaddeaddeaddead0001\",\"0x1AC5FE\"]},{\"id\":65,\"jsonrpc\":\"2.0\",\"method\":\"eth_getBalance\",\"params\":[\"0x4200000000000000000000000000000000000011\"\n\n  response:\n\n    status code: 500\n\n    body: <html>\r\n<head><title>500 Internal Server Error</title></head>\r\n<body>\r\n<center><h1>500 Internal Server Error</h1></center>\r\n<hr><center>nginx/1.18.0 (Ubuntu)</center>\r\n</body>\r\n</html>\r\n\n","metadata":{"count":100,"fetcher":"coin_balance_catchup"}}
> > > {"time":"2024-03-09T06:09:17.381Z","severity":"error","message":"failed to fetch: {:bad_response, \"https://onlylayer.org\"}","metadata":{"count":100,"error_count":100,"fetcher":"coin_balance_catchup"}}
> > > {"time":"2024-03-09T06:09:17.524Z","severity":"info","message":"Start handling L1 block #5447214.","metadata":{"fetcher":"optimism_withdrawal_events"}}
> > > {"time":"2024-03-09T06:09:17.542Z","severity":"info","message":"Finish handling L1 block #5447214. Found 0 WithdrawalProven/WithdrawalFinalized event(s).","metadata":{"fetcher":"optimism_withdrawal_events"}}
> > > {"time":"2024-03-09T06:09:21.366Z","severity":"error","message":"Failed to decode Ethereum JSONRPC response:\n\n  request:\n\n    url: https://onlylayer.org\n\n    body: [{\"id\":16,\"jsonrpc\":\"2.0\",\"method\":\"eth_getBalance\",\"params\":[\"0x4200000000000000000000000000000000000015\",\"0x1AC45F\"]}
> > > ```
> > 
> > 
> > `https://onlylayer.org` which, I assume, you use for `ETHEREUM_JSONRPC_HTTP_URL`, returns error on batched request of `eth_getBalance` method.
> 
> yes i use this. so i just disable ?

It is a bug of the RPC, which you use. On the Blockscout side you can disable `eth_getBalance` requests to the archive via `
ETHEREUM_JSONRPC_DISABLE_ARCHIVE_BALANCES=true`;

**Comment by avenbreaks** [comment]
solved thanks
