### ISSUE TITLE
Failed to decode Ethereum JSONRPC response

### ISSUE THREAD

**Issue by khaitqNapaglobal** [blockscout/blockscout#9570]
### Description

<img width="1498" alt="Screenshot 2024-03-07 at 11 05 17" src="https://github.com/blockscout/blockscout/assets/108641766/2081659d-fe75-4805-8110-4f76f4fea3b1">

I'm using blockscount beta version v5.2.2, but I'm getting an error fetcher internal transaction from RPC. Can I ask if this version has a retry feature to fetch internal transactions? If so, how do I turn off retry fetch internal transaction?

### Type of the installation

Docker-compose

### Type of the JSON RPC archive node

Geth

### Backend version

v5.2.2

### Elixir & Erlang/OTP versions

1.14.4

**Comment by vbaranov** [comment]
You can disable internal transactions fetcher via setting `INDEXER_DISABLE_INTERNAL_TRANSACTIONS_FETCHER=true`

**Comment by vbaranov** [comment]
Try setting `INDEXER_INTERNAL_TRANSACTIONS_TRACER_TYPE =callTracer`. In the lastest release it is default option.

**Comment by khaitqNapaglobal** [comment]
So I need to upgrade blockscout to the latest version?

**Comment by vbaranov** [comment]
> So I need to upgrade blockscout to the latest version?

It is better to update, yes.

**Comment by vbaranov** [comment]
@khaitqNapaglobal please update to v6.5.0 and let us know, if the issue is still present there or provide more details on the JSON RPC node client version and what type of chain you'r trying to index.
