### ISSUE TITLE
Не получил шлем

### ISSUE THREAD

**Issue by ArtemAma077** [blockscout/blockscout#9574]
### Description

7 дней идет отправка шлема. В чем может быть проблема?

### Type of the installation

Docker-compose

### Type of the JSON RPC archive node

geth

### Backend version

v5.3.3-beta

### Elixir & Erlang/OTP versions

Elixir 1.14.5 Erlang/OTP 24

### Operating system

unix linux

### Additional information

The issue happened at Andromeda Blockscout instance

**Comment by vbaranov** [comment]
Andromeda Blockscout instance is not managed by the Blockscout team. Please ask your question in Andromeda chain support channel.

**Comment by ArtemAma077** [comment]
Где я могу его увидеть? Он не пришел на MetaMask в тестовою сеть Métis.

Пт, 8 марта 2024 г. в 18:09, Victor Baranov ***@***.***>:
