### ISSUE TITLE
metis測試網交易錯誤

### ISSUE THREAD

**Issue by Jz88112** [blockscout/blockscout#9593]
### Description

我的地址:0xFfe409F926a3231E4a682B14B75bdB376e9B6925
交易地址:0x25aD88Ee5F1c45A84D33322911aC698ecF4d073E
交易ID:0x57b34d14fd67eae440be87ed7478e98930aa8e4088ff4ae7a8002979b9bc112c

交易建立，數量 0 METIS @ 00:41 on 1/28/2024。
交易送出，手續費 0.000557 METIS @ 00:42 on 1/28/2024。
交易重新送出，手續費提高至 0.000557 METIS @ 00:42 on 1/28/2024
再麻煩您們了 

### Type of the installation

Docker-compose

### Type of the JSON RPC archive node

geth

### Backend version

v5.3.3-beta

### Elixir & Erlang/OTP versions

Elixir 1.14.5 Erlang/OTP 24

### Operating system

unix linux

### Additional information

The issue happened at Metis Sepolia Blockscout instance

**Comment by vbaranov** [comment]
Blockscout team doesn't manage this instance of Blockscout. You should ask the question to the team, which supports this chain.

**Comment by Jz88112** [comment]
不好意思 他們說Blockscout只是對區塊鏈交易的探索，而Blockscout沒有交易所網站。
但我這邊卡住 無法做其他任何交易 是否可以幫我取消或者我有甚麼其他解決的方法呢
