### ISSUE TITLE
txlist on acala doesnt work for me

### ISSUE THREAD

**Issue by sfeyal** [blockscout/blockscout#9610]
### Description

sending a request for module "account" with action "txlist" always return "something went wrong"

### Type of the installation

Docker-compose

### Type of the JSON RPC archive node

geth

### Link to the page

https://blockscout.acala.network/

### Steps to reproduce

curl -X POST https://blockscout.acala.network/api -H 'Content-Type: application/json' -d '{
    "module": "account",
    "action": "txlist",
    "address": "0x07df96d1341a7d16ba1ad431e2c847d978bc2bce",
    "sort": "asc"
 }'

### Backend version

v5.3.0-beta

### Elixir & Erlang/OTP versions

Elixir 1.14.5 Erlang/OTP 24

### Operating system

unix linux

### Additional information

The issue happened at Acala Chain Blockscout instance

**Comment by sl1depengwyn** [comment]
Here is an example of right request:
```
curl -X GET 'https://blockscout.acala.network/api?module=account&action=txlist&address=0x07df96d1341a7d16ba1ad431e2c847d978bc2bce&startblock=555555&endblock=666666&page=1&offset=5&sort=asc'
```

docs: https://docs.blockscout.com/for-users/api/rpc-endpoints/account

**Comment by sfeyal** [comment]
thanks!
it means that the other params are required and not optional as written in the docs?
taking your request and deleting the params after the address will result in the same error I got before.

from the docs:

startblock | optional integer block number to start transaction search
endblock | optionalinteger block number to stop transaction search.
page | optional integer representing the page number used for pagination. offset must also be provided.
offset | optional integer representing number of transactions returned per page. page must also be provided.

**Comment by sfeyal** [comment]
trying to work with your request (different value in offset) I've ended up with the same error:
```
curl -X GET 'https://blockscout.acala.network/api?module=account&action=txlist&address=0x07df96d1341a7d16ba1ad431e2c847d978bc2bce&startblock=555555&endblock=666666&page=1&offset=300&sort=asc'
```

in the docs i dont see any limit for the offset.

**Comment by zjb0807** [comment]
> trying to work with your request (different value in offset) I've ended up with the same error:
> 
> ```
> curl -X GET 'https://blockscout.acala.network/api?module=account&action=txlist&address=0x07df96d1341a7d16ba1ad431e2c847d978bc2bce&startblock=555555&endblock=666666&page=1&offset=300&sort=asc'
> ```
> 
> in the docs i dont see any limit for the offset.

I added shared memory to support the queries, but excessive `offset` will still be limited.

**Comment by sfeyal** [comment]
thanks!
what is the limit?

**Comment by zjb0807** [comment]
There is no specific number, it depends on the database's shared memory size
