### ISSUE TITLE
Unable to verify contract on Base Sepolia Blockscout instance

### ISSUE THREAD

**Issue by mp-freatic** [blockscout/blockscout#9614]
### Description

Hi there,
We had no issue verifying previous versions of our contract, but the last upgrade is creating trouble.
https://base-sepolia.blockscout.com/address/0xC27e89Fdda1E3bbaEc5ADa877000472eFc9bBCd9

I managed to verify the same contract on basescan using the standard JSON input: https://sepolia.basescan.org/address/0xc27e89fdda1e3bbaec5ada877000472efc9bbcd9#code

But for some reason, it's not working on Blockscout.

One especially weird behaviours I noticed: 
The UI directly says "Failed to verify" although the request returns a 200 : `{"message":"Smart-contract verification started"}` 

![image](https://github.com/blockscout/blockscout/assets/163126871/4d793826-d9f1-4b7a-bda4-1bfdc9c00660)

![image](https://github.com/blockscout/blockscout/assets/163126871/0030aa99-1be8-4c3c-b81f-68f49e238f9c)
 
Same using the flattened code verification process:
![image](https://github.com/blockscout/blockscout/assets/163126871/9ae8f1de-becc-4e71-99ca-ce48906d782a)

### Type of the installation

Docker-compose

### Type of the JSON RPC archive node

No idea

### Type of the chain

L2 (Base sepolia)

### Link to the page

https://base-sepolia.blockscout.com/address/0xC27e89Fdda1E3bbaEc5ADa877000472eFc9bBCd9?tab=txs

### Steps to reproduce

Go to https://base-sepolia.blockscout.com/address/0xC27e89Fdda1E3bbaEc5ADa877000472eFc9bBCd9/contract-verification 

Attempt to verify the contract.

Standard input JSON file: 
[input-basescan-working.json](https://github.com/blockscout/blockscout/files/14571129/input-basescan-working.json)

It fails.

### Backend version

v6.2.2-beta.+commit.612dc2c0

### Frontend version

v1.25.0+8df5ab3f

### Elixir & Erlang/OTP versions

No idea

### Operating system

macOS

### Additional information

**User Agent:** Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36 

=> Using Chrome

**Comment by vbaranov** [comment]
Thank you for heads-up. The issue resolved and smart-contract has been verified.
