### ISSUE TITLE
not validating deposit test token  in collateral 

### ISSUE THREAD

**Issue by santosh3642** [blockscout/blockscout#9618]
### Description

before one day i have deposited 0.0005 btc testnet transction hash 0xfd9dc6b504c437314303d9cc9e5e17c26eb7ccda7e815a92b56f23c9fbb8bfd4
from wallet adress:  0x56A4F837374D890F630B6748CB275aA309e5E7b3

### Type of the installation

Docker-compose

### Type of the JSON RPC archive node

BEVM canary TestNet

### Link to the page

https://scan-canary-testnet.bevm.io/tx/0xfd9dc6b504c437314303d9cc9e5e17c26eb7ccda7e815a92b56f23c9fbb8bfd4

### Steps to reproduce

please avilable for borrow sat
![Screenshot (1130)](https://github.com/blockscout/blockscout/assets/130894291/a527363e-f7cf-4b8f-896f-c34a9ef41bd9)

### Backend version

v6.2.2-beta

### Elixir & Erlang/OTP versions

BEVM canary TestNet

### Additional information

**User Agent:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36 Edg/122.0
![Screenshot (1130)](https://github.com/blockscout/blockscout/assets/130894291/29cb2e9c-3c84-45fe-88f8-a5765cc4c483)

**Comment by sl1depengwyn** [comment]
This repo is for Blockscout-related questions. Blockscout is an open source blockchain explorer. Thus, your question is out of scope, where the Blockscout team can help, you better contact the chain support directly.
