### ISSUE TITLE
frontend application show no data but there is data in the backend database

### ISSUE THREAD

**Issue by BlockgenStudio** [blockscout/blockscout#9624]
### Description

i followed the manual deployment guidance and the backend is deployed successfully. i can see there is data in the tables.
how ever when i run the front end by yarn dev, the front end shows no data. Appreciate any idea how to fix this!!

![Screenshot 2024-03-12 at 6 31 05 PM](https://github.com/blockscout/blockscout/assets/135279728/29f27fce-8895-48ea-9f2f-14d94fd24bfa)

```

blockscout=# SELECT count(*) FROM transactions;
 count 
-------
 45734
(1 row)

blockscout=# SELECT count(*) FROM blocks;
  count  
---------
 1257422
(1 row)
image
```

here is my front end .env, NEXT_PUBLIC_API_PORT is 4000 since it's the default: https://docs.blockscout.com/for-developers/information-and-settings/env-variables
```

NEXT_PUBLIC_API_HOST=localhost
NEXT_PUBLIC_API_PORT=4000
NEXT_PUBLIC_API_PROTOCOL=http
NEXT_PUBLIC_STATS_API_HOST=http://localhost:8080
NEXT_PUBLIC_VISUALIZE_API_HOST=http://localhost:8081
NEXT_PUBLIC_APP_HOST=localhost
NEXT_PUBLIC_APP_PORT=3000
NEXT_PUBLIC_APP_INSTANCE=localhost
NEXT_PUBLIC_APP_ENV=development
NEXT_PUBLIC_API_WEBSOCKET_PROTOCOL='ws'
```
i also tried to execute a backend API call, here is the output

```
curl http://localhost:4000/api/
{"message":"Params 'module' and 'action' are required parameters","result":null,"status":"0"}
how to fix this? Appreciate any input

```
Link to the page
http://35.94.88.222:3000/

### Type of the installation

Manual from the source code

### Type of the JSON RPC archive node

geth

### Type of the chain

L2

### Backend version

V6.1

### Frontend version

v1.26.0-alpha

### Elixir & Erlang/OTP versions

1.14.5

### Operating system

linux

**Comment by sl1depengwyn** [comment]
Check the browser console when you open the frontend and see what backend responses

**Comment by BlockgenStudio** [comment]
Thanks! I will give it a try. is there any way to enable the logs of backend API. if it's logged, which file I can check? @sl1depengwyn

**Comment by sl1depengwyn** [comment]
Besides the logs in the terminal there should appear a folder named logs

**Comment by BlockgenStudio** [comment]
thanks! i fixed the issue by replace 'localhost' across the .env in frontend to my aws ec2 load balancer dns
