### ISSUE TITLE
Lost token

### ISSUE THREAD

**Issue by BlkLuffy64** [blockscout/blockscout#9649]
### Description

I sent 21 Metis tokens to crypto.com from my meta mask,  March-16-2024 01:14:55 PMthe status was confirmed and results successful, but I have not received my tokens on the exchange. Can you help me recover my assets please.

### Type of the installation

Docker-compose

### Type of the JSON RPC archive node

geth

### Type of the chain

L2

### Backend version

v5.3.3-beta

### Elixir & Erlang/OTP versions

Elixir 1.14.5 Erlang/OTP 24

### Operating system

unix linux

### Additional information

The issue happened at Andromeda Blockscout instance

**Comment by fedor-ivn** [comment]
Hello! This repository is specifically dedicated to Blockscout, an open-source blockchain explorer.

Unfortunately, your question appears to be outside the scope of Blockscout. We recommend reaching out directly to the support team of the specific blockchain you're inquiring about for more accurate assistance.
