### ISSUE TITLE
The data does not appear to be indexed for a specific hash

### ISSUE THREAD

**Issue by DanielAdamFR** [blockscout/blockscout#9657]
### Description

Hello, (im not a contributor but an api consumer) for this request 

[blockscout api call with specific account](https://blockscout.com/xdai/mainnet/api?action=tokentx&module=account&address=0x0d67A5798D70b6B8Ecd7f58d7bA813D0bA0eeC9D&startblock=0&endblock=99999999&page=1&offset=1000&sort=asc )

associated with this account `0x0d67A5798D70b6B8Ecd7f58d7bA813D0bA0eeC9D`

I am supposed to find this hash 

[blockscout api call with specific hash](https://gnosis.blockscout.com/tx/0x42bacfbf3e0bf35870f0443b8dbf6696d76af7500dfeb1844f3772600af0048c)
which is available in your system but is not provided in your API.

I'm supposed to get this:
(data from gnosisscan)
`... Dai","tokenSymbol":"USDC","tokenDecimal":"6","transactionIndex":"2","gas":"16150000","gasPrice":"4003938527","gasUsed":"11942015","cumulativeGasUsed":"12382089","input":"deprecated","confirmations":"2021355"},{"blockNumber":"31013366","timeStamp":"1700321865","hash":"0x42bacfbf3e0bf35870f0443b8dbf6696d76af7500dfeb1844f3772600af0048c","nonce":"30400","blockHash":"0x5e759c1868812999f13a2c700d05d0bec3d9df2dedf6b6ebbeb4c19d8c181bb4","from":"0xef8db3f5e1817e907f13778c4d5f933279546d5a","to":"0x0d67a5798d70b6b8ecd7f58d7ba813d0ba0eec9d","contractAddress":"0x5a722eda908e3db61c9a14cce757ce673f5e3a17","value":"2000000000000000000","tokenName":"RealToken S 7913 Faith Ln Montgomery AL","tokenSymbol":"REALTOKEN-S-7913-FAITH-LN-MONTGOMERY- ...`
Can you please help me?

### Type of the installation

Manual from the source code

### Type of the JSON RPC archive node

I'm a consumer

### Type of the chain

Gnosis 

### Link to the page

https://gnosis.blockscout.com/

### Steps to reproduce

Hello, for this request (im not a contributor but an api consumer) 

[blockscout api call with specific account](https://blockscout.com/xdai/mainnet/api?action=tokentx&module=account&address=0x0d67A5798D70b6B8Ecd7f58d7bA813D0bA0eeC9D&startblock=0&endblock=99999999&page=1&offset=1000&sort=asc )

associated with this account `0x0d67A5798D70b6B8Ecd7f58d7bA813D0bA0eeC9D`

I am supposed to find this hash 

[blockscout api call with specific hash](https://gnosis.blockscout.com/tx/0x42bacfbf3e0bf35870f0443b8dbf6696d76af7500dfeb1844f3772600af0048c)
which is available in your system but is not provided in your API.

I'm supposed to get this:
(data from gnosisscan)
`... Dai","tokenSymbol":"USDC","tokenDecimal":"6","transactionIndex":"2","gas":"16150000","gasPrice":"4003938527","gasUsed":"11942015","cumulativeGasUsed":"12382089","input":"deprecated","confirmations":"2021355"},{"blockNumber":"31013366","timeStamp":"1700321865","hash":"0x42bacfbf3e0bf35870f0443b8dbf6696d76af7500dfeb1844f3772600af0048c","nonce":"30400","blockHash":"0x5e759c1868812999f13a2c700d05d0bec3d9df2dedf6b6ebbeb4c19d8c181bb4","from":"0xef8db3f5e1817e907f13778c4d5f933279546d5a","to":"0x0d67a5798d70b6b8ecd7f58d7ba813d0ba0eec9d","contractAddress":"0x5a722eda908e3db61c9a14cce757ce673f5e3a17","value":"2000000000000000000","tokenName":"RealToken S 7913 Faith Ln Montgomery AL","tokenSymbol":"REALTOKEN-S-7913-FAITH-LN-MONTGOMERY- ...`
Can you please help me?

### Backend version

v6.2.2-beta.+commit.b9d92b39

### Frontend version

v1.26.2+12f0781e

### Elixir & Erlang/OTP versions

I'm a consumer

### Additional information

**User Agent:** Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36

**Comment by GimluCom** [comment]
Reduced the block range of the API request for easier demonstration.

https://gnosis.blockscout.com/api?module=account&action=tokentx&address=0x0d67A5798D70b6B8Ecd7f58d7bA813D0bA0eeC9D&startblock=31013365&endblock=31013367
returns: `{"message":"No token transfers found","result":[],"status":"0"}`
but should return the transaction [0x42bacfbf3e0bf35870f0443b8dbf6696d76af7500dfeb1844f3772600af0048c](https://gnosis.blockscout.com/tx/0x42bacfbf3e0bf35870f0443b8dbf6696d76af7500dfeb1844f3772600af0048c).

**Comment by vbaranov** [comment]
@DanielAdamFR there was a delay in indexing a part of the chain in the explorer. Currently, all missed blocks and their data have been successfully processed and should be available via API. If you have any issues with that please let me know. I am closing the issue for now.
