### ISSUE TITLE
USDT - Issue

### ISSUE THREAD

**Issue by xJASONKINGx** [blockscout/blockscout#9688]
### Description

Hey having an issue with usdt I sent $5000 USD T to the shaberium network.It's showing up as $5000 in my wallet.But when I go to swap it, it's only valuing it at $1500 U.S I don't Know what happened? Maybe at the time of valued the usdt at $0.35 instead of $1
![Screenshot_20240320_114123_Chrome](https://github.com/blockscout/blockscout/assets/164225437/c2e3ad18-34c7-4cbf-885f-b52d352bdf15)
 Also When I went to use Wolf swap It was also Valuing it at roughly $1500.I tried marswap aswell same issue 
![Screenshot_20240319_233439_MetaMask](https://github.com/blockscout/blockscout/assets/164225437/f4ea1e45-8fbc-4c24-88c4-c928c4c3728a)

Can someone please help 😢 

### Type of the installation

Docker-compose

### Type of the JSON RPC archive node

Shiberium 

### Type of the chain

Shiberium

### Link to the page

https://www.shibariumscan.io/token/0xaB082b8ad96c7f47ED70ED971Ce2116469954cFB?tab=holders

### Steps to reproduce

Please help 

### Backend version

v6.2.2-beta

### Frontend version

v1.26.2+12f0781e

### Elixir & Erlang/OTP versions

Evn

### Operating system

Android 

### Additional information

**User Agent:** Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Mobile Safari/537.36

**Comment by xJASONKINGx** [comment]
It's showing in my up shiberium wallet as $5000usdt 
![Screenshot_20240319_234330_Chrome](https://github.com/blockscout/blockscout/assets/164225437/d0bac8eb-f955-4699-a7a0-5a056719ee90)

**Comment by xJASONKINGx** [comment]
Please check the video when I try to  withdraw the $5000 usdt the value is less then half 

https://github.com/blockscout/blockscout/assets/164225437/0555f989-e895-4791-89b1-af5d7aa69056

**Comment by sl1depengwyn** [comment]
This repo is for Blockscout-related questions. Blockscout is an open source blockchain explorer. Thus, your question is out of scope, where the Blockscout team can help, you better contact the chain support directly.

> Please check the video when I try to withdraw the $5000 usdt the value is less then half
> 
>  Screen_Recording_20240320_135042_MetaMask.mp4

It shows fee, not amount of the transfer
