### ISSUE TITLE
NFT Minting for more than 20 days

### ISSUE THREAD

**Issue by moncmonc2000** [blockscout/blockscout#9689]
### Description

Hi, My Helmet NFT is minting for more than 20 days. It would be great if you could take a look at this.

Token ID: 222392
[Block #13921543](https://andromeda-explorer.metis.io/block/13921543)
Transaction Hash - 0xaca00f2fc600953324df46191aa0162a1176a27f942e222fec9fcca1a7843118

### Type of the installation

Docker-compose

### Type of the JSON RPC archive node

geth

### Backend version

v5.3.3-beta

### Elixir & Erlang/OTP versions

Elixir 1.14.5 Erlang/OTP 24

### Operating system

unix linux

### Additional information

The issue happened at Andromeda Blockscout instance

**Comment by sl1depengwyn** [comment]
This repo is for Blockscout-related questions. Blockscout is an open source blockchain explorer. Thus, your question is out of scope, where the Blockscout team can help, you better contact the chain support directly.
