### ISSUE TITLE
Money never arrived

### ISSUE THREAD

**Issue by offirmad** [blockscout/blockscout#9691]
### Description

Hi I sent 3.05893 ETC worth from Binance to an Exodus wallet about a month ago and it still never arrived. Is it possible to get a refund back?
This is the transaction https://etc.blockscout.com/tx/0xe568cda75f1eef499e0cf763b93182d5cc67a7915105b71c95e0dd2c372c3155

### Type of the installation

Docker-compose

### Type of the JSON RPC archive node

.

### Link to the page

https://etc.blockscout.com/address/0xEA240a9DC0E0ad50A942D2358a8855ce1b5EC8fA

### Backend version

v6.2.2-beta

### Frontend version

v1.26.2+12f0781e

### Elixir & Erlang/OTP versions

.

### Additional information

**User Agent:** Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.1 Safari/605.1.15

**Comment by sl1depengwyn** [comment]
This repo is for Blockscout-related questions. Blockscout is an open source blockchain explorer. Thus, your question is out of scope, where the Blockscout team can help, you better contact the chain support directly.
