### ISSUE TITLE
Money not arriving

### ISSUE THREAD

**Issue by offirmad** [blockscout/blockscout#9692]
### Description

Hi I sent 3.05893 ETC worth from Binance to an Exodus wallet about a month ago and it still never arrived. Is it possible to get a refund back?
This is the transaction https://etc.blockscout.com/tx/0xe568cda75f1eef499e0cf763b93182d5cc67a7915105b71c95e0dd2c372c3155

### Type of the installation

Docker-compose

### Type of the JSON RPC archive node

Erigon

### Link to the page

https://etc.blockscout.com/address/0xEA240a9DC0E0ad50A942D2358a8855ce1b5EC8fA

### Backend version

v6.2.2-beta

### Frontend version

v1.26.2+12f0781e

### Elixir & Erlang/OTP versions

Elixir 1.14.5

### Additional information

**User Agent:** Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.1 Safari/605.1.15

**Comment by DappsTechTeam** [comment]
> ### Description
> Hi I sent 3.05893 ETC worth from Binance to an Exodus wallet about a month ago and it still never arrived. Is it possible to get a refund back? This is the transaction https://etc.blockscout.com/tx/0xe568cda75f1eef499e0cf763b93182d5cc67a7915105b71c95e0dd2c372c3155
> 
> ### Type of the installation
> Docker-compose
> 
> ### Type of the JSON RPC archive node
> Erigon
> 
> ### Type of the chain
> _No response_
> 
> ### Link to the page
> https://etc.blockscout.com/address/0xEA240a9DC0E0ad50A942D2358a8855ce1b5EC8fA
> 
> ### Steps to reproduce
> _No response_
> 
> ### Backend version
> v6.2.2-beta
> 
> ### Frontend version
> v1.26.2+12f0781e
> 
> ### Elixir & Erlang/OTP versions
> Elixir 1.14.5
> 
> ### Operating system
> _No response_
> 
> ### Additional information
> **User Agent:** Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.1 Safari/605.1.15


Hey there @offirmad  ! 

Thank you for reaching out! Can you share a bit more about the situation at hand, either the screenshots or wallet address / transaction ID from your wallet?
If you prefer, you can also contact live support via EXODUS DApps WalletNode Github Support directly with the ticket ID9463 if you don’t want to share those on this thread!

Note; Click on the live chat icon at the bottom corner of the page to initiate chat with a live support agent for a faster response.

**Comment by GimluCom** [comment]
@offirmad The user above is trying to scam you.

You would need to contact Binance about your issue. Blockscout is not a chain or a wallet, we can't assist with transaction issues.

**Comment by offirmad** [comment]
> @offirmad The user above is trying to scam you.
> 
> You would need to contact Binance about your issue. Blockscout is not a chain or a wallet, we can't assist with transaction issues.

Well but the money was sent it shows here its in the wallet it just doesn't show up.
