### ISSUE TITLE
Getting issue at MacOS

### ISSUE THREAD

**Issue by DedicatedDev** [blockscout/blockscout#9702]
### Description

 | {"time":"2024-03-21T22:49:46.846Z","severity":"error","message":"failed to fetch: :econnrefused.  Block will be retried by catchup indexer.","metadata":{"block_number":1866,"

At MacOS, I'm getting this issue, blockscout doesn't update status. block number is correct. 
At Ubuntu, everything is okay. 

### Type of the installation

Docker-compose

### Type of the JSON RPC archive node

Ethermint

### Type of the chain

Ethermint

### Backend version

latest

### Frontend version

v1.11.1

### Elixir & Erlang/OTP versions

1.14.5

### Operating system

MacOS

### Additional information

backend          | {"time":"2024-03-21T22:49:46.301Z","severity":"error","message":"failed to fetch: :econnrefused. Retrying.","metadata":{"fetcher":"block_catchup","first_block_number":0,"last_block_number":0,"step":"blocks"}}
backend          | {"time":"2024-03-21T22:49:46.302Z","severity":"info","message":"Index had to catch up.","metadata":{"fetcher":"block_catchup","first_block_number":0,"last_block_number":0,"missing_block_count":1,"shrunk":false}}
backend          | {"time":"2024-03-21T22:49:46.302Z","severity":"info","message":"Checking if index needs to catch up in 2500ms.","metadata":{"fetcher":"block_catchup"}}
backend          | {"time":"2024-03-21T22:49:46.846Z","severity":"error","message":"failed to fetch: :econnrefused.  Block will be retried by catchup indexer.","metadata":{"block_number":1866,"fetcher":"block_realtime","step":"blocks"}}
backend          | {"time":"2024-03-21T22:49:47.914Z","severity":"error","message":"failed to fetch: :econnrefused.  Block will be retried by catchup indexer.","metadata":{"block_number":1867,"fetcher":"block_realtime","step":"blocks"}}
backend          | {"time":"2024-03-21T22:49:48.638Z","severity":"info","message":"Start sanitizing of empty blocks. Batch size is 100","metadata":{"fetcher":"empty_blocks_to_refetch"}}
backend          | {"time":"2024-03-21T22:49:48.671Z","severity":"info","message":"Batch of empty blocks is sanitized","metadata":{"fetcher":"empty_blocks_to_refetch"}}
backend          | {"time":"2024-03-21T22:49:48.807Z","severity":"error","message":"failed to fetch: :econnrefused. Retrying.","metadata":{"fetcher":"block_catchup","first_block_number":0,"last_block_number":0,"step":"blocks"}}

**Comment by fedor-ivn** [comment]
Hello! 

Did you use the same environment settings on Ubuntu and MacOS?

**Comment by DedicatedDev** [comment]
could you elaborate? 
what kind of things do I have to change?
I've reinstalled docker at Ubuntu because of the crash issue. 
after that,  happening similar issue. 

Could you let me know the datailed setting?
I'm running node on my computer. 
RPC endpoint is just 0.0.0.0:8545 (http, ws)
Looking json-rpc lib fetch block number correctly but failed fetch information. 
I'm not sure this is database problem or permission problem between docker container and host computer.

**Comment by fedor-ivn** [comment]
> could you elaborate?

Could you share your `.env` for further troubleshooting?

1. How do you run your node? Is it also running in docker container? 
2. What type of node you are using? (geth, ganache, etc)
3. Did you change the docker-compose configuration?

**Comment by DedicatedDev** [comment]
Hello. Thanks for late response. 
1. I'm runing with docker composer
 docker compose docker compose -f notary-network.yml up
docker compose -f hardhat-network.yml up
2. I'm using custom build ethermint evm node (cosmos) and hardhat. 
3. ```version: "3.9"

services:
  redis-db:
    extends:
      file: ./services/redis.yml
      service: redis-db

  db-init:
    extends:
      file: ./services/db.yml
      service: db-init

  db:
    depends_on:
      db-init:
        condition: service_completed_successfully
    extends:
      file: ./services/db.yml
      service: db

  backend:
    depends_on:
      - db
      - redis-db
    extends:
      file: ./services/backend.yml
      service: backend
    links:
      - db:database
    environment:
      ETHEREUM_JSONRPC_VARIANT: "geth"
      ETHEREUM_JSONRPC_WS_URL: ws://host.docker.internal:8546/
      INDEXER_DISABLE_PENDING_TRANSACTIONS_FETCHER: "true"
      CHAIN_ID: "1337"

  visualizer:
    extends:
      file: ./services/visualizer.yml
      service: visualizer

  sig-provider:
    extends:
      file: ./services/sig-provider.yml
      service: sig-provider

  frontend:
    depends_on:
      - backend
    extends:
      file: ./services/frontend.yml
      service: frontend
    environment:
      NEXT_PUBLIC_NETWORK_ID: "1317"
      NEXT_PUBLIC_NETWORK_RPC_URL: http://host.docker.internal:8545/

  stats-db-init:
    extends:
      file: ./services/stats.yml
      service: stats-db-init

  stats-db:
    depends_on:
      stats-db-init:
        condition: service_completed_successfully
    extends:
      file: ./services/stats.yml
      service: stats-db

  stats:
    depends_on:
      - stats-db
      - backend
    extends:
      file: ./services/stats.yml
      service: stats

  proxy:
    depends_on:
      - backend
      - frontend
      - stats
    extends:
      file: ./services/nginx.yml
      service: proxy
```

**Comment by vbaranov** [comment]
@DedicatedDev would you please check with the latest release of the backend 6.7.2 (currently the latest)?

**Comment by vbaranov** [comment]
Closing due to no response from the author.
