### ISSUE TITLE
COULDN'T RECEIVE MY OEX LONG TESTNET

### ISSUE THREAD

**Issue by Gcolombus** [blockscout/blockscout#9703]
### Description

I completed my Faucet Task oh OEX HUB TESTNET but couldn't receive my USDT Long to complete the mission on OEX TESTNET
WALLET ADDRESS: 0x7Da429be886bF30af431864C3731271D62423080

### Type of the installation

Docker-compose

### Type of the JSON RPC archive node

Agiex.org

### Type of the chain

0x7Da429be886bF30af431864C3731271D62423080

### Link to the page

https://scan.long.openex.network/address/0x7Da429be886bF30af431864C3731271D62423080

### Steps to reproduce

I completed my Faucet Task oh OEX HUB TESTNET but couldn't receive my USDT Long to complete the mission on OEX TESTNET
WALLET ADDRESS: 0x7Da429be886bF30af431864C3731271D62423080

### Backend version

V1.0.1

### Frontend version

v1.26.2+12f0781e

### Elixir & Erlang/OTP versions

E0x7Da429be886bF30af431864C3731271D62423080

### Operating system

Android 

### Additional information

**User Agent:** Mozilla/5.0 (Linux; Android 11; Infinix X693 Build/RP1A.200720.011; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/122.0.6261.119 Mobile Safari/537.36

**Comment by sl1depengwyn** [comment]
This repo is for Blockscout-related questions. Blockscout is an open source blockchain explorer. Thus, your question is out of scope, where the Blockscout team can help, you better contact the chain support directly.
