### ISSUE TITLE
Crypto not received

### ISSUE THREAD

**Issue by Afsheen04** [blockscout/blockscout#9709]
### Description

I have made a withdraw which is yet to be confirmed and get deposited to the destination. 
My wallet address from which I have withdrawn my crypto is : 0x633164429b4795ecd6801d503772401d9b2ff06d

### Type of the installation

Docker-compose

### Type of the JSON RPC archive node

geth

### Type of the chain

L1

### Backend version

v5.3.3-beta

### Elixir & Erlang/OTP versions

Elixir 1.14.5 Erlang/OTP 24

### Operating system

unix linux

### Additional information

The issue happened at Andromeda Blockscout instance

**Comment by fedor-ivn** [comment]
Hello! This repository is specifically dedicated to Blockscout, an open-source blockchain explorer.

Unfortunately, your question appears to be outside the scope of Blockscout. We recommend reaching out directly to the support team of the specific blockchain and/or exchange you're inquiring about for more accurate assistance.
