### ISSUE TITLE
No function clause matching in EthereumJSONRPC.Geth.parse_call_tracer_calls

### ISSUE THREAD

**Issue by dennisloh95** [blockscout/blockscout#9712]
### Description

We have some debug_traceTransaction will return this format, 

```
{
    "jsonrpc": "2.0",
    "id": 1,
    "result": {
        "type": "CREATE",
        "from": "0x169dde50fe1b02ddf59eeb199ba4182d0893f42d",
        "to": "0x1e7037c6d6dceb1396b33b81781a1019e206381d",
        "value": "0x25789f5d600",
        "gas": "0x1e2b",
        "gasUsed": "0x1e2b",
        "input": "0x60806040526040516033380380603383398181016040526020811015602357600080fd5b5051806001600160a01b038116fffe000000000000000000000000ce09e22c121eaef5d23d057fb450c58e4648f135",
        "output": "0x",
        "time": "814.677µs",
        "calls": [
            {
                "type": "SELFDESTRUCT"
            }
        ]
    }
}
```

the indexer report with the log below, is this struct not support at the moment?

`{"time":"2024-03-24T02:31:36.282Z","severity":"error","message":"failed to fetch internal transactions for blocks: ** (FunctionClauseError) no function clause matching in EthereumJSONRPC.Geth.parse_call_tracer_calls/4\n    (ethereum_jsonrpc 6.3.0) lib/ethereum_jsonrpc/geth.ex:356: EthereumJSONRPC.Geth.parse_call_tracer_calls({%{\"type\" => \"SELFDESTRUCT\"}, 0}, [%{\"callType\" => \"create\", \"createdContractAddressHash\" => \"0x1e7037c6d6dceb1396b33b81781a1019e206381d\", \"createdContractCode\" => \"0x\", \"from\" => \"0x169dde50fe1b02ddf59eeb199ba4182d0893f42d\", \"gas\" => \"0x1e2b\", \"gasUsed\" => \"0x1e2b\", \"init\" => \"0x60806040526040516033380380603383398181016040526020811015602357600080fd5b5051806001600160a01b038116fffe000000000000000000000000ce09e22c121eaef5d23d057fb450c58e4648f135\", \"input\" => \"0x60806040526040516033380380603383398181016040526020811015602357600080fd5b5051806001600160a01b038116fffe000000000000000000000000ce09e22c121eaef5d23d057fb450c58e4648f135\", \"output\" => \"0x\", \"to\" => \"0x1e7037c6d6dceb1396b33b81781a1019e206381d\", \"traceAddress\" => [], \"type\" => \"create\", \"value\" => \"0x25789f5d600\"}], [], true)\n    (elixir 1.14.5) lib/enum.ex:4307: anonymous fn/3 in Enum.reduce/3\n    (elixir 1.14.5) lib/stream.ex:1801: anonymous fn/3 in Enumerable.Stream.reduce/3\n    (elixir 1.14.5) lib/stream.ex:1158: anonymous fn/3 in Stream.with_index/2\n    (elixir 1.14.5) lib/enum.ex:4751: Enumerable.List.reduce/3\n    (elixir 1.14.5) lib/stream.ex:1813: Enumerable.Stream.do_each/4\n    (elixir 1.14.5) lib/enum.ex:4307: Enum.reduce/3\n    (ethereum_jsonrpc 6.3.0) lib/ethereum_jsonrpc/geth.ex:350: EthereumJSONRPC.Geth.prepare_calls/1\n","metadata":{"count":100,"error_count":100,"fetcher":"internal_transaction"}}`

### Type of the installation

Docker-compose

### Type of the JSON RPC archive node

Geth

### Type of the chain

L2

### Backend version

v6.3.0

### Elixir & Erlang/OTP versions

1.14.5-otp-25

**Comment by phpmac** [comment]
我也遇到了

failed to fetch internal transactions for blocks

**Comment by yzh-d** [comment]
I also encountered a similar problem
`application=indexer fetcher=internal_transaction count=10 error_count=10 [error] failed to fetch internal transactions for blocks: ** (CaseClauseError) no case clause matching: []
blockscout-5.2.3         |     (hackney 1.20.1) /app/deps/hackney/src/hackney_url.erl:248: :hackney_url.parse_netloc/2
blockscout-5.2.3         |     (hackney 1.20.1) /app/deps/hackney/src/hackney.erl:351: :hackney.request/5
blockscout-5.2.3         |     (httpoison 2.1.0) lib/httpoison/base.ex:872: HTTPoison.Base.request/6
blockscout-5.2.3         |     (ethereum_jsonrpc 5.2.3) lib/ethereum_jsonrpc/http/httpoison.ex:12: EthereumJSONRPC.HTTP.HTTPoison.json_rpc/4
blockscout-5.2.3         |     (ethereum_jsonrpc 5.2.3) lib/ethereum_jsonrpc/http.ex:73: EthereumJSONRPC.HTTP.chunked_json_rpc/3
blockscout-5.2.3         |     (ethereum_jsonrpc 5.2.3) lib/ethereum_jsonrpc/request_coordinator.ex:87: anonymous fn/3 in EthereumJSONRPC.RequestCoordinator.perform/4
blockscout-5.2.3         |     (ethereum_jsonrpc 5.2.3) lib/ethereum_jsonrpc/request_coordinator.ex:107: EthereumJSONRPC.RequestCoordinator.trace_request/2
blockscout-5.2.3         |     (ethereum_jsonrpc 5.2.3) lib/ethereum_jsonrpc.ex:448: EthereumJSONRPC.json_rpc/2`

**Comment by GimluCom** [comment]
@dennisloh95 This was patched in the Geth client about four years ago.

https://github.com/ethereum/go-ethereum/releases/tag/v1.9.22

> Extend the call tracer to include additional contextual fields for `SELFDESTRUCT`

**Comment by vbaranov** [comment]
I am closing this issue. @dennisloh95 please let us know, if you have further requests.
