### ISSUE TITLE
Zetachain Coin Balance History amount dismatch

### ISSUE THREAD

**Issue by Freshield** [blockscout/blockscout#9717]
### Description

There seems to be a bug in the Blockscout coin balance history, as evidenced by the transaction below. The user deposited 6 zeta on ZetaEarn, and the transaction page correctly displays the zeta value as 6. However, the coin history incorrectly indicates a transfer of 56 zeta.
0xbe032c73986fa129d0d7608dd8023cf3ee4a933fa905ac9d1149048a25f5fc9e
![image](https://github.com/blockscout/blockscout/assets/15166014/e03cee49-7a75-4e2d-bb73-8f5cf22a48a6)

### Type of the installation

Docker-compose

### Type of the JSON RPC archive node

Geth

### Type of the chain

L1

### Link to the page

https://zetachain.blockscout.com/address/0xEdAD923F54AB4423ADb66FB286ad52d2b49A482c?tab=coin_balance_history&page=2&next_page_params=%257B%2522block_number%2522%253A2230922%252C%2522items_count%2522%253A50%257D

### Steps to reproduce

Check the second page of coin balance history

### Backend version

v6.1.0

### Frontend version

v1.11.1

### Elixir & Erlang/OTP versions

Elixir 1.14.5

### Operating system

macOS

**Comment by sl1depengwyn** [comment]
Probably, this happens because not all internal transactions are indexed and blockscout cannot detect balance change between block 2072490 and 2083196
