### ISSUE TITLE
NFT realtime fetcher: Add retry with cooldown on 404 error

### ISSUE THREAD

**Issue by nikitosing** [blockscout/blockscout#9719]

**Comment by Kneva** [comment]
When registering domains or stamps Galxe - BTC Halving NFT (zBTCNFT), there is a problem with obtaining the metadata of the NFT, and this also applies to other NFTs. In the absence of metadata, there are often issues with counting tasks or the Guild does not see that the user has it. I also think there are issues with other NFTs with missing metadata.
https://zetachain.blockscout.com/token/0xfCD0DF2D5B1023C3cE210bEd17c3BcF40D4eD5cd/instance/26773095061492332890277059165253577489871385443637265683178984391113708048685 
https://zetachain.blockscout.com/token/0x2881e29dd9E4B14F187c7bF571F0Db9AF81F5B41
