### ISSUE TITLE
Error: Query deserialize error: missing field `service` on ports 8080 and 8083 from microservices

### ISSUE THREAD

**Issue by mrchipdev** [blockscout/blockscout#9721]
### Description

Hi everybody

I am a newbie, I have successfully installed blockscout-backend and blockscout-frontend, I installed both the latest versions manually.

with blockscout-frontend currently it doesn't work on Charts & stats

With blockscout-backend I am making queries to the api at port 8081 correctly. with port :8081/health the result is {"status":"SERVING"}

with port: 8082/api/v2/verifier/solidity/versions
The results returned are correct.

Private port: 8083/health
The returned result is: Query deserialize error: missing field `service`

and port: 8080/health
The returned result is: Query deserialize error: missing field `service`

because port 8080 is run for start and because it is inactive, in the frontend the graphs are not displayed with the return result being no data.

For example here is the API link from port 8080
http://IP:8080/api/v1/lines/newTxns?from=2024-02-25&to=2024-03-25
The result returned is
{"chart":[{"date":"2024-02-25","value":"0"}...]}

my problem is the error of not being able to connect to the api at port 8080 and 8083
Has anyone in the community encountered this error before, and can help me figure it out?

Thanks everyone 

### Type of the installation

Docker-compose

### Type of the JSON RPC archive node

Geth

### Backend version

v6.3.0

### Frontend version

v1.27.0

### Elixir & Erlang/OTP versions

Elixir 1.14.5

### Operating system

Linux

**Comment by mrchipdev** [comment]
Hi,

I tried using the command: docker-compose logs stats
in the docker-compose directory and the result is as follows

`stats            | 2024-03-27T03:24:42.651024Z  INFO blockscout_service_launcher::database: creating database 'stats'
stats            | 2024-03-27T03:24:42.681203Z  INFO blockscout_service_launcher::database: database 'stats' already exists
stats            | 2024-03-27T03:24:42.705557Z  INFO sqlx::postgres::notice: relation "seaql_migrations" already exists, skipping    
stats            | 2024-03-27T03:24:42.706953Z  INFO sea_orm_migration::migrator: Applying all pending migrations
stats            | 2024-03-27T03:24:42.707631Z  INFO sqlx::postgres::notice: relation "seaql_migrations" already exists, skipping    
stats            | 2024-03-27T03:24:42.716185Z  INFO sqlx::postgres::notice: relation "seaql_migrations" already exists, skipping    
stats            | 2024-03-27T03:24:42.716594Z  INFO sqlx::postgres::notice: relation "seaql_migrations" already exists, skipping    
stats            | 2024-03-27T03:24:42.719526Z  INFO sea_orm_migration::migrator: No pending migrations
stats            | 2024-03-27T03:24:42.849569Z  INFO blockscout_service_launcher::launcher::launch: starting http server on addr 0.0.0.0:8050
stats            | 2024-03-27T03:24:42.849586Z  INFO stats_server::update_service: updating chart chart="accountsGrowth"
stats            | 2024-03-27T03:24:42.850108Z  INFO stats_server::update_service: updating chart chart="activeAccounts"
stats            | 2024-03-27T03:24:42.850116Z  INFO actix_server::builder: Starting 6 workers
stats            | 2024-03-27T03:24:42.850278Z  INFO stats_server::update_service: updating chart chart="averageBlockRewards"
stats            | 2024-03-27T03:24:42.850518Z  INFO actix_server::server: Tokio runtime found; starting in existing Tokio runtime
stats            | 2024-03-27T03:24:42.854207Z ERROR stats_server::update_service: error during updating chart: blockscout database error: Query Error: error returned from database: relation "blocks" does not exist chart="averageBlockRewards"
stats            | 2024-03-27T03:24:42.855417Z  INFO stats_server::update_service: updating chart chart="averageBlockSize"
stats            | 2024-03-27T03:24:42.855648Z  INFO stats_server::update_service: scheduled next run of chart update in 59717.144390014s chart="averageBlockRewards"
stats            | 2024-03-27T03:24:42.860157Z ERROR stats_server::update_service: error during updating chart: blockscout database error: Query Error: error returned from database: relation "blocks" does not exist chart="averageBlockSize"
stats            | 2024-03-27T03:24:42.860599Z  INFO stats_server::update_service: updating chart chart="averageBlockTime"
stats            | 2024-03-27T03:24:42.860952Z  INFO stats_server::update_service: scheduled next run of chart update in 20117.139058379s chart="averageBlockSize"
stats            | 2024-03-27T03:24:42.867522Z ERROR stats_server::update_service: error during updating chart: blockscout database error: Query Error: error returned from database: relation "blocks" does not exist chart="activeAccounts"
stats            | 2024-03-27T03:24:42.867713Z  INFO stats_server::update_service: updating chart chart="averageGasLimit"
stats            | 2024-03-27T03:24:42.868034Z  INFO stats_server::update_service: scheduled next run of chart update in 2117.132095365s chart="activeAccounts"
stats            | 2024-03-27T03:24:42.868301Z ERROR stats_server::update_service: error during updating chart: blockscout database error: Query Error: error returned from database: relation "blocks" does not exist chart="averageBlockTime"
stats            | 2024-03-27T03:24:42.868344Z  INFO stats_server::update_service: updating chart chart="averageGasPrice"
stats            | 2024-03-27T03:24:42.868527Z  INFO stats_server::update_service: scheduled next run of chart update in 41717.131482701s chart="averageBlockTime"
stats            | 2024-03-27T03:24:42.869460Z ERROR stats_server::update_service: error during updating chart: blockscout database error: Query Error: error returned from database: relation "blocks" does not exist chart="averageGasPrice"
stats            | 2024-03-27T03:24:42.869500Z  INFO stats_server::update_service: updating chart chart="averageTxnFee"
stats            | 2024-03-27T03:24:42.869621Z  INFO stats_server::update_service: scheduled next run of chart update in 38117.130385419s chart="averageGasPrice"
stats            | 2024-03-27T03:24:42.871188Z ERROR stats_server::update_service: error during updating chart: blockscout database error: Query Error: error returned from database: relation "blocks" does not exist chart="averageGasLimit"
stats            | 2024-03-27T03:24:42.871322Z ERROR stats_server::update_service: error during updating chart: blockscout database error: Query Error: error returned from database: relation "transactions" does not exist chart="accountsGrowth"
stats            | 2024-03-27T03:24:42.871343Z  INFO stats_server::update_service: updating chart chart="completedTxns"
stats            | 2024-03-27T03:24:42.871397Z  INFO stats_server::update_service: scheduled next run of chart update in 30917.128621092s chart="averageGasLimit"
stats            | 2024-03-27T03:24:42.871732Z  INFO stats_server::update_service: scheduled next run of chart update in 5717.128274374s chart="accountsGrowth"
stats            | 2024-03-27T03:24:42.871780Z  INFO stats_server::update_service: updating chart chart="contractsGrowth"
stats            | 2024-03-27T03:24:42.873304Z ERROR stats_server::update_service: error during updating chart: blockscout database error: Query Error: error returned from database: relation "blocks" does not exist chart="averageTxnFee"
stats            | 2024-03-27T03:24:42.873354Z  INFO stats_server::update_service: updating chart chart="gasUsedGrowth"
stats            | 2024-03-27T03:24:42.873527Z  INFO stats_server::update_service: scheduled next run of chart update in 9317.12648026s chart="averageTxnFee"
stats            | 2024-03-27T03:24:42.873634Z ERROR stats_server::update_service: error during updating chart: blockscout database error: Query Error: error returned from database: relation "blocks" does not exist chart="contractsGrowth"
stats            | 2024-03-27T03:24:42.873664Z ERROR stats_server::update_service: error during updating chart: blockscout database error: Query Error: error returned from database: relation "transactions" does not exist chart="completedTxns"
stats            | 2024-03-27T03:24:42.873670Z  INFO stats_server::update_service: updating chart chart="lastNewContracts"
stats            | 2024-03-27T03:24:42.873773Z  INFO stats_server::update_service: updating chart chart="lastNewVerifiedContracts"
stats            | 2024-03-27T03:24:42.873743Z  INFO stats_server::update_service: scheduled next run of chart update in 16517.12627661s chart="contractsGrowth"
stats            | 2024-03-27T03:24:42.873871Z  INFO stats_server::update_service: scheduled next run of chart update in 9617.12613242s chart="completedTxns"
stats            | 2024-03-27T03:24:42.875112Z ERROR stats_server::update_service: error during updating chart: blockscout database error: Query Error: error returned from database: relation "blocks" does not exist chart="lastNewVerifiedContracts"
stats            | 2024-03-27T03:24:42.875158Z  INFO stats_server::update_service: updating chart chart="newAccounts"
stats            | 2024-03-27T03:24:42.875870Z  INFO stats_server::update_service: scheduled next run of chart update in 17.124139796s chart="lastNewVerifiedContracts"
stats            | 2024-03-27T03:24:42.875996Z ERROR stats_server::update_service: error during updating chart: blockscout database error: Query Error: error returned from database: relation "blocks" does not exist chart="gasUsedGrowth"
stats            | 2024-03-27T03:24:42.876057Z  INFO stats_server::update_service: updating chart chart="newBlocks"
stats            | 2024-03-27T03:24:42.877141Z ERROR stats_server::update_service: error during updating chart: blockscout database error: Query Error: error returned from database: relation "blocks" does not exist chart="lastNewContracts"
stats            | 2024-03-27T03:24:42.877256Z  INFO stats_server::update_service: updating chart chart="newContracts"
stats            | 2024-03-27T03:24:42.877199Z  INFO stats_server::update_service: scheduled next run of chart update in 34517.122809539s chart="gasUsedGrowth"
stats            | 2024-03-27T03:24:42.878202Z ERROR stats_server::update_service: error during updating chart: blockscout database error: Query Error: error returned from database: relation "blocks" does not exist chart="newContracts"
stats            | 2024-03-27T03:24:42.878289Z  INFO stats_server::update_service: updating chart chart="newNativeCoinTransfers"
stats            | 2024-03-27T03:24:42.878867Z  INFO stats_server::update_service: scheduled next run of chart update in 10217.121144117s chart="lastNewContracts"
stats            | 2024-03-27T03:24:42.879521Z  INFO stats_server::update_service: scheduled next run of chart update in 45317.120486387s chart="newContracts"
stats            | 2024-03-27T03:24:42.880721Z ERROR stats_server::update_service: error during updating chart: blockscout database error: Query Error: error returned from database: relation "blocks" does not exist chart="newBlocks"
stats            | 2024-03-27T03:24:42.880769Z  INFO stats_server::update_service: updating chart chart="newTxns"
stats            | 2024-03-27T03:24:42.880906Z  INFO stats_server::update_service: scheduled next run of chart update in 16517.11910218s chart="newBlocks"
stats            | 2024-03-27T03:24:42.882350Z ERROR stats_server::update_service: error during updating chart: blockscout database error: Query Error: error returned from database: relation "blocks" does not exist chart="newTxns"
stats            | 2024-03-27T03:24:42.882447Z  INFO stats_server::update_service: updating chart chart="newVerifiedContracts"
stats            | 2024-03-27T03:24:42.882625Z  INFO stats_server::update_service: scheduled next run of chart update in 77717.117383378s chart="newTxns"
stats            | 2024-03-27T03:24:42.883425Z ERROR stats_server::update_service: error during updating chart: blockscout database error: Query Error: error returned from database: relation "blocks" does not exist chart="newVerifiedContracts"
stats            | 2024-03-27T03:24:42.883498Z  INFO stats_server::update_service: updating chart chart="totalAccounts"
stats            | 2024-03-27T03:24:42.883647Z  INFO stats_server::update_service: scheduled next run of chart update in 41717.116358964s chart="newVerifiedContracts"
stats            | 2024-03-27T03:24:42.894075Z ERROR stats_server::update_service: error during updating chart: blockscout database error: Query Error: error returned from database: relation "transactions" does not exist chart="newAccounts"
stats            | 2024-03-27T03:24:42.894243Z  INFO stats_server::update_service: updating chart chart="totalAddresses"
stats            | 2024-03-27T03:24:42.894403Z  INFO stats_server::update_service: scheduled next run of chart update in 63317.105605835s chart="newAccounts"
stats            | 2024-03-27T03:24:42.895204Z ERROR stats_server::update_service: error during updating chart: blockscout database error: Query Error: error returned from database: relation "transactions" does not exist chart="totalAccounts"
stats            | 2024-03-27T03:24:42.895242Z  INFO stats_server::update_service: updating chart chart="totalBlocks"
stats            | 2024-03-27T03:24:42.895379Z  INFO stats_server::update_service: scheduled next run of chart update in 45317.104625714s chart="totalAccounts"
stats            | 2024-03-27T03:24:42.897594Z ERROR stats_server::update_service: error during updating chart: blockscout database error: Query Error: error returned from database: relation "blocks" does not exist chart="totalBlocks"
stats            | 2024-03-27T03:24:42.897780Z  INFO stats_server::update_service: updating chart chart="totalContracts"
stats            | 2024-03-27T03:24:42.899681Z  INFO stats_server::update_service: scheduled next run of chart update in 9317.100334774s chart="totalBlocks"
stats            | 2024-03-27T03:24:42.901183Z ERROR stats_server::update_service: error during updating chart: blockscout database error: Query Error: error returned from database: relation "blocks" does not exist chart="newNativeCoinTransfers"
stats            | 2024-03-27T03:24:42.901251Z  INFO stats_server::update_service: updating chart chart="totalNativeCoinTransfers"
stats            | 2024-03-27T03:24:42.902045Z  INFO stats_server::update_service: scheduled next run of chart update in 84917.09796788s chart="newNativeCoinTransfers"
stats            | 2024-03-27T03:24:42.904663Z ERROR stats_server::update_service: error during updating chart: blockscout database error: Query Error: error returned from database: relation "addresses" does not exist chart="totalAddresses"
stats            | 2024-03-27T03:24:42.904708Z  INFO stats_server::update_service: updating chart chart="totalTokens"
stats            | 2024-03-27T03:24:42.904836Z  INFO stats_server::update_service: scheduled next run of chart update in 9317.095172896s chart="totalAddresses"
stats            | 2024-03-27T03:24:42.905502Z ERROR stats_server::update_service: error during updating chart: blockscout database error: Query Error: error returned from database: relation "blocks" does not exist chart="totalContracts"
stats            | 2024-03-27T03:24:42.905612Z ERROR stats_server::update_service: error during updating chart: blockscout database error: Query Error: error returned from database: relation "blocks" does not exist chart="totalNativeCoinTransfers"
stats            | 2024-03-27T03:24:42.905627Z  INFO stats_server::update_service: updating chart chart="totalTxns"
stats            | 2024-03-27T03:24:42.905629Z  INFO stats_server::update_service: scheduled next run of chart update in 10517.094377509s chart="totalContracts"
stats            | 2024-03-27T03:24:42.905723Z  INFO stats_server::update_service: updating chart chart="totalVerifiedContracts"
stats            | 2024-03-27T03:24:42.906100Z  INFO stats_server::update_service: scheduled next run of chart update in 34517.093906218s chart="totalNativeCoinTransfers"
stats            | 2024-03-27T03:24:42.908084Z ERROR stats_server::update_service: error during updating chart: blockscout database error: Query Error: error returned from database: relation "blocks" does not exist chart="totalVerifiedContracts"
stats            | 2024-03-27T03:24:42.908123Z  INFO stats_server::update_service: updating chart chart="txnsFee"
stats            | 2024-03-27T03:24:42.908632Z ERROR stats_server::update_service: error during updating chart: blockscout database error: Query Error: error returned from database: relation "blocks" does not exist chart="totalTxns"
stats            | 2024-03-27T03:24:42.908654Z  INFO stats_server::update_service: updating chart chart="txnsGrowth"
stats            | 2024-03-27T03:24:42.909282Z  INFO stats_server::update_service: scheduled next run of chart update in 317.090727838s chart="totalVerifiedContracts"
stats            | 2024-03-27T03:24:42.909677Z  INFO stats_server::update_service: scheduled next run of chart update in 9917.090328762s chart="totalTxns"
stats            | 2024-03-27T03:24:42.909880Z ERROR stats_server::update_service: error during updating chart: blockscout database error: Query Error: error returned from database: relation "blocks" does not exist chart="txnsFee"
stats            | 2024-03-27T03:24:42.909913Z  INFO stats_server::update_service: updating chart chart="txnsSuccessRate"
stats            | 2024-03-27T03:24:42.910016Z  INFO stats_server::update_service: scheduled next run of chart update in 12917.089987535s chart="txnsFee"
stats            | 2024-03-27T03:24:42.910443Z ERROR stats_server::update_service: error during updating chart: blockscout database error: Query Error: error returned from database: relation "tokens" does not exist chart="totalTokens"
stats            | 2024-03-27T03:24:42.910466Z  INFO stats_server::update_service: updating chart chart="verifiedContractsGrowth"
stats            | 2024-03-27T03:24:42.911104Z  INFO stats_server::update_service: scheduled next run of chart update in 52517.088903368s chart="totalTokens"
stats            | 2024-03-27T03:24:42.911236Z ERROR stats_server::update_service: error during updating chart: blockscout database error: Query Error: error returned from database: relation "blocks" does not exist chart="txnsGrowth"
stats            | 2024-03-27T03:24:42.911290Z  INFO stats_server::update_service: scheduled next run of chart update in 81317.088713232s chart="txnsGrowth"
stats            | 2024-03-27T03:24:42.911648Z ERROR stats_server::update_service: error during updating chart: blockscout database error: Query Error: error returned from database: relation "blocks" does not exist chart="verifiedContractsGrowth"
stats            | 2024-03-27T03:24:42.911668Z  INFO stats_server::update_service: scheduled next run of chart update in 12917.088335436s chart="verifiedContractsGrowth"
stats            | 2024-03-27T03:24:42.914596Z ERROR stats_server::update_service: error during updating chart: blockscout database error: Query Error: error returned from database: relation "blocks" does not exist chart="txnsSuccessRate"
stats            | 2024-03-27T03:24:42.914740Z  INFO stats_server::update_service: initial updating is done
stats            | 2024-03-27T03:24:42.914809Z  INFO stats_server::update_service: scheduled next run of chart update in 56117.085201188s chart="txnsSuccessRate"
stats            | 2024-03-27T03:24:45.198414Z  INFO HTTP request{method=GET endpoint=/api/v1/lines/{name} client_ip=171.232.99.225 request_id=8845b567-cfab-451b-8f7b-076466226bf0}: blockscout_service_launcher::launcher::span_builder: new
stats            | 2024-03-27T03:24:45.198532Z  INFO HTTP request{method=GET endpoint=/api/v1/lines/{name} client_ip=171.232.99.225 request_id=8845b567-cfab-451b-8f7b-076466226bf0}: blockscout_tracing_actix_web::middleware: Started HTTP request processing
stats            | 2024-03-27T03:24:45.215628Z  INFO HTTP request{method=GET endpoint=/api/v1/lines/{name} client_ip=171.232.99.225 request_id=8845b567-cfab-451b-8f7b-076466226bf0 duration=17123 unit="microsecond"}: blockscout_tracing_actix_web::middleware: Finished HTTP request processing
stats            | 2024-03-27T03:24:45.215706Z  INFO HTTP request{method=GET endpoint=/api/v1/lines/{name} client_ip=171.232.99.225 request_id=8845b567-cfab-451b-8f7b-076466226bf0 duration=17123 unit="microsecond"}: blockscout_service_launcher::launcher::span_builder: close time.busy=6.12ms time.idle=11.2ms`

all services work fine except chart service
error warning: ERROR stats_server::update_service: error during updating chart

I tried a link as follows:
http://myip:8080/api/v1/lines/txnsFee?from=2024-02-27&to=2024-03-27
Result:
`{"chart":[{"date":"2024-02-26","value":"0"},{"date":"2024-02-27","value":"0"},{"date":"2024-02-28","value":"0"},{"date":"2024-02-29","value":"0"},{"date":"2024-03-01","value":"0"},{"date":"2024-03-02","value":"0"},{"date":"2024-03-03","value":"0"},{"date":"2024-03-04","value":"0"},{"date":"2024-03-05","value":"0"},{"date":"2024-03-06","value":"0"},{"date":"2024-03-07","value":"0"},{"date":"2024-03-08","value":"0"},{"date":"2024-03-09","value":"0"},{"date":"2024-03-10","value":"0"},{"date":"2024-03-11","value":"0"},{"date":"2024-03-12","value":"0"},{"date":"2024-03-13","value":"0"},{"date":"2024-03-14","value":"0"},{"date":"2024-03-15","value":"0"},{"date":"2024-03-16","value":"0"},{"date":"2024-03-17","value":"0"},{"date":"2024-03-18","value":"0"},{"date":"2024-03-19","value":"0"},{"date":"2024-03-20","value":"0"},{"date":"2024-03-21","value":"0"},{"date":"2024-03-22","value":"0"},{"date":"2024-03-23","value":"0"},{"date":"2024-03-24","value":"0"},{"date":"2024-03-25","value":"0"},{"date":"2024-03-26","value":"0"}]}`

Can anyone help me find this problem? How can chart data work?

Thank for all

**Comment by yasindce1998** [comment]
Same issue here

**Comment by yasindce1998** [comment]
If anyone can help, that would be better.

**Comment by yasindce1998** [comment]
@mrchipdev can I see your nginx config?

**Comment by vbaranov** [comment]
@mrchipdev those errors in the logs are related to initialization process of all components. Please ignore them. Since you're able to query stats service endpoints it is up & running.

**Comment by SorrawitRUNGRUJEE** [comment]
I am facing the issue as well after running the micro service of the manual deployment 
health check for localhost:8080/health for stats microservice, localhost:8083/health for sig-provider,  localhost:8082/health for sc-verifier
all return Query deserialize error: missing field `service`

the localhost:8081/health for Sc-visualizer return status:serving as expected

![image](https://github.com/blockscout/blockscout/assets/139847674/479b05de-508e-47ca-afed-93fea6b21ba8)

![image](https://github.com/blockscout/blockscout/assets/139847674/377bb3ac-2e72-4084-8849-17c72e104234)

![image](https://github.com/blockscout/blockscout/assets/139847674/fa358485-cfd4-4933-9e38-a5290bc544fd)

these are the error that shows up on the attached console. 

Any advice would be appreciated.
