### ISSUE TITLE
api/v2/smart-contracts/verification/config solidity_compiler_versions is an empty array

### ISSUE THREAD

**Issue by Jaycelv** [blockscout/blockscout#9727]
### Description

After deploying my code to the production environment, when I try to verify the contract, I encounter an issue where the data returned by the API endpoint api/v2/smart-contracts/verification/config contains errors. The fields solidity_compiler_versions and vyper_compiler_versions are empty arrays. This situation doesn't occur immediately after code deployment but rather after two or three days. Below are my environment variables. What could be the issue?
![image](https://github.com/blockscout/blockscout/assets/99306545/ca82c3c5-8f4c-4c2c-88e5-4350e68b4b0b)

export MICROSERVICE_SC_VERIFIER_URL=https://eth-bytecode-db.services.blockscout.com/
export MICROSERVICE_SC_VERIFIER_TYPE=eth_bytecode_db
export MICROSERVICE_ETH_BYTECODE_DB_INTERVAL_BETWEEN_LOOKUPS=10m

### Type of the installation

Docker-compose

### Type of the JSON RPC archive node

Geth

### Type of the chain

L2

### Link to the page

https://explorer-testnet.morphl2.io/address/0x2d47b5A23381aeFF14Cf793c10F1cF91e9B8Bd04/contract-verification

### Steps to reproduce

Deploying blockscout-end to the production environment, and then after two or three days, when you open this page again, you will find that this field of the interface is empty.

### Backend version

5.2.3-beta

### Frontend version

2.0.2

### Elixir & Erlang/OTP versions

Elixir 1.14.5 (compiled with Erlang/OTP 25)

### Operating system

Linux

**Comment by Jaycelv** [comment]
Type of the installation ： k8s , not docker-compose

**Comment by Jaycelv** [comment]
MICROSERVICE_SC_VERIFIER_API_KEY

I have not configured this environment variable. Does this have any impact? If it does, how should I apply for this variable?

**Comment by vbaranov** [comment]
> MICROSERVICE_SC_VERIFIER_API_KEY
> 
> I have not configured this environment variable. Does this have any impact? If it does, how should I apply for this variable?

Yes, you should configure alpha-numeric sequence in that env variable. Btw, I see currently compiler versions is not an empty array on the instance, right? Did you manage to resolve it? Can we close the issue?
