### ISSUE TITLE
Wrong address

### ISSUE THREAD

**Issue by omar200005** [blockscout/blockscout#9735]
### Description

I transferred ETC currencies from the kucoin platform to Bingx, but I did not notice that the Bingx platform does not support the ETC chain, and I transferred, unfortunately, and now I want to reverse the process to recover the currencies. Is that possible?  This is the hash of the transaction

0x5c291051e0bf9f748d1e364b7434caf4ed4d1a6890ee7546a42e6128191735a6

This is a picture of the transfer process on the Kucoin platform

![Screenshot_20240327_101759_com kubi kucoin]
(https://github.com/blockscout/blockscout/assets/165153536/47246369-c6c1-4ee6-8d79-d8b8273fc842)

### Type of the installation

Docker-compose

### Type of the JSON RPC archive node

ETC

### Link to the page

https://etc.blockscout.com/tx/0x5c291051e0bf9f748d1e364b7434caf4ed4d1a6890ee7546a42e6128191735a6

### Backend version

v6.3.0-beta

### Frontend version

v1.27.0+5a63649f

### Elixir & Erlang/OTP versions

I DO NOT NO 

### Additional information

**User Agent:** Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Mobile Safari/537.36

**Comment by vbaranov** [comment]
This chat is for Blockscout-related questions. Your question is out of scope, where the Blockscout team can help.
