### ISSUE TITLE
Return 'is_verified: true' for minimal proxy if implementation is verified

### ISSUE THREAD

**Issue by yvaskov** [blockscout/blockscout#9744]
## Description

We can safely return `"is_verified": true` in `/api/v2/addresses/` endpoint for EIP-1167 minimal proxy if the implementation is verified.
This way fronted displays verified icons on the proxy, but no verified message for the proxy contract itself.

Example proxy: https://eth.blockscout.com/api/v2/addresses/0x0650d780292142835F6ac58dd8E2a336e87b4393

**Comment by Mamu364014** [comment]
When will I be getting this to me. Still have not received nothing as of today.
