### ISSUE TITLE
Money not reflected on my wallet

### ISSUE THREAD

**Issue by Mdaghash1983** [blockscout/blockscout#9747]
### Description

I have not received the usdt on my wallet yet  0x224131Fee1F9fC60387E3ED3E793912F17832E29

### Type of the installation

Docker-compose

### Type of the JSON RPC archive node

geth

### Backend version

v5.3.3-kava

### Elixir & Erlang/OTP versions

Elixir 1.14.5 Erlang/OTP 25

### Operating system

unix linux

### Additional information

The issue happened at Kava 10 Blockscout instance

**Comment by sl1depengwyn** [comment]
This repo is for Blockscout-related questions. Blockscout is an open source blockchain explorer. Thus, your question is out of scope, where the Blockscout team can help, you better contact the chain support directly.
