### ISSUE TITLE
提币未到账需要检查

### ISSUE THREAD

**Issue by jh521314** [blockscout/blockscout#9750]
### Description

我的bone代币，从shibarium链到eth链，查询成功了，可是eth链的bone没有收到。
![11](https://github.com/blockscout/blockscout/assets/117247642/2279896e-ef9a-4982-a2cd-44461ddf0406)
![111](https://github.com/blockscout/blockscout/assets/117247642/52be0c9d-e62d-4381-a6e8-00d9478f5b46)
![1111](https://github.com/blockscout/blockscout/assets/117247642/110ae5a7-c60b-4cd3-84b5-40b987336e2b)

### Type of the installation

Docker-compose

### Type of the JSON RPC archive node

shibs

### Backend version

1

### Elixir & Erlang/OTP versions

1

**Comment by vbaranov** [comment]
Please describe your issue in english?
