### ISSUE TITLE
SWAP TRANSACTION TO THE WRONG ADDRESS

### ISSUE THREAD

**Issue by Alpella11** [blockscout/blockscout#9754]
### Description

I ACCIDENTALLY SWAPED ETH ON THE DEGEN NETWORK. BEFORE GOING TO MİNT.CLUB SITE

### Type of the installation

Docker

### Type of the JSON RPC archive node

Base / Degen

### Link to the page

https://explorer.degen.tips/tx/0x1abd6d6cdb1faef79a35367b834a30d028fe5313375be81d90478205196a1d3c

### Backend version

v6.3.0-beta

### Elixir & Erlang/OTP versions

I dont know 

### Operating system

iPhone İOS 

### Additional information

**User Agent:** Mozilla/5.0 (iPhone; CPU iPhone OS 17_3_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Mobile/15E148 WebView MetaMaskMobile

**Comment by sl1depengwyn** [comment]
This repo is for Blockscout-related questions. Blockscout is an open source blockchain explorer. Thus, your question is out of scope, where the Blockscout team can help, you better contact the chain support directly.
