### ISSUE TITLE
Haven't recieved transfered tokens

### ISSUE THREAD

**Issue by Kashefi007** [blockscout/blockscout#9757]
### Description

Hello
on March 13, 2024, I intended to make a transaction and send the amount of 1260 USDt from exchange to my wallet but I entered the destination address by mistake  (0x8AC9843692e0E9d1FA03E93487E1B2Ab836202A4) which belongs to Ethereum Classic in my wallet. Please consider that  destination address is also mine, and unfortunately the mentioned amount has not been added to the wallet. Please help me by recovering my lost USDt and follow up the transaction. If any other data is needed let me know.
Thanks

### Type of the installation

Docker-compose

### Type of the JSON RPC archive node

Erigon

### Type of the chain

L1

### Backend version

V6.1.0

### Elixir & Erlang/OTP versions

Elixir.1.14.5

**Comment by sl1depengwyn** [comment]
This repo is for Blockscout-related questions. Blockscout is an open source blockchain explorer. Thus, your question is out of scope, where the Blockscout team can help, you better contact the chain support directly.
