### ISSUE TITLE
Incomplete Mission L and Wrapped WUSDT on OEX Testnet

### ISSUE THREAD

**Issue by usmanfarooqi9t9** [blockscout/blockscout#9762]
### Description

Dear OEX Testnet Support Team,I hope this message finds you well. I am writing to report an issue regarding the completion of Mission L and the status of Wrapped WUSDT on the OEX Testnet.Incomplete Mission L: Despite my diligent efforts to fulfill the requirements of Mission L on the OEX Testnet, I have encountered a persistent issue where the mission remains incomplete, despite satisfying all outlined criteria. I have followed the necessary steps as per the mission instructions, yet the completion status has not been updated accordingly in my account.Wrapped WUSDT Status: Additionally, there seems to be a discrepancy or delay in the status of Wrapped WUSDT transactions on the OEX Testnet. Transactions involving Wrapped WUSDT are not reflecting accurately in my account or are experiencing prolonged pending periods.I kindly request your prompt assistance in resolving these issues. Your support in addressing these matters is crucial for enabling a seamless testing experience on the OEX Testnet platform.

### Type of the installation

Docker-compose

### Type of the JSON RPC archive node

PolygoneEdge

### Type of the chain

L1

### Link to the page

https://scan.long.openex.network/address/0x0f9F05cb9908b5DfAEdab5d0a85b1F6A19bEc852

### Steps to reproduce

To reproduce the issue of incomplete Mission L and the discrepancy in Wrapped WUSDT status on the OEX Testnet in a development environment, follow these steps:

1. **Access OEX Testnet Platform**: Log in to the OEX Testnet platform using your developer credentials.

2. **Navigate to Mission L**: Locate and navigate to Mission L within the platform's interface. This mission likely involves specific tasks or actions to be completed.

3. **Attempt Mission Completion**: Follow the outlined instructions and perform the required tasks to complete Mission L. Ensure that all steps are executed accurately according to the provided guidelines.

4. **Verify Mission Completion Status**: After completing the required tasks, check the mission completion status. If the issue persists, the completion status may not update as expected, indicating an issue with the mission tracking system.

5. **Perform Wrapped WUSDT Transactions**: Execute transactions involving Wrapped WUSDT tokens on the OEX Testnet platform. This could include transferring tokens, trading, or engaging in other activities involving Wrapped WUSDT.

6. **Monitor Transaction Status**: Keep track of the status of the Wrapped WUSDT transactions. Note any delays, discrepancies, or inaccuracies in the transaction records or balances.

7. **Document Observations**: Record any observations, errors, or unexpected behaviors encountered during the reproduction process. Include details such as error messages, transaction IDs, timestamps, and any other relevant information.

8. **Report the Issue**: Once the issue has been reproduced and documented, report it to the development team or platform administrators. Provide a detailed description of the steps taken, along with any relevant data or findings, to assist in troubleshooting and resolving the issue effectively.

By following these steps, developers can replicate the issue

### Backend version

V1.0.0

### Frontend version

v1.26.2+12f0781e

### Elixir & Erlang/OTP versions

Elixir 1.12.x & Erlang/OTP 24

### Operating system

Linux

### Additional information

**User Agent:** Mozilla/5.0 (Linux; Android 10; Infinix X680F Build/QP1A.190711.020; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/122.0.6261.119 Mobile Safari/537.36

**Comment by sl1depengwyn** [comment]
This repo is for Blockscout-related questions. Blockscout is an open source blockchain explorer. Thus, your question is out of scope, where the Blockscout team can help, you better contact the chain support directly.
