### ISSUE TITLE
I can't sell my memecoin, and no, it's not a honeypot/rug. 

### ISSUE THREAD

**Issue by YohaNft2** [blockscout/blockscout#9766]
### Description

Hello, i purchased Degen Saitama memecoin, CA : 0xaEDbaa7024EDf3630912C654520f3905f1e905E6
https://explorer.degen.tips/tx/0xa269858254daaf1b1a677c6c46e2b13af808fd1db330996abdf398bd74605da8
Together with 4 friends.
We all bought a different amount of tokens. 3 of us (me included) can't swap back from Saitama to Degen because saitama balance showing 0. Onchain, we are able to see the tokens, but balance on degenswap showing 0 constantly.
The fourth friend purchased at the same moment with us, and he is able to see Saitama balance. He even managed to sell it back for profit.

Why is that?

### Type of the installation

Docker-compose

### Type of the JSON RPC archive node

Degen chain

### Type of the chain

L3

### Link to the page

https://explorer.degen.tips/tx/0xa269858254daaf1b1a677c6c46e2b13af808fd1db330996abdf398bd74605da8

### Backend version

v6.3.0-beta

### Elixir & Erlang/OTP versions

??

### Operating system

Windows

### Additional information

**User Agent:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.0.0 Safari/537.36

**Comment by GimluCom** [comment]
> and no, it's not a honeypot/rug

The "owner" of the contract/token manually set your token balance to zero in [this transaction](https://explorer.degen.tips/tx/0x77a70296b09fe8b487a40f421eb2ce64226ee6ef185c50e87866e42ed1ae67df).

![image](https://github.com/blockscout/blockscout/assets/79271880/c5bb797f-650d-4be3-9404-1181a0a678d8)

The function appears to be an obfuscated method to arbitrarily alter the token balance of any address.

---

Disclaimer: While I decided to take the time to find the culprit for you, your issue has nothing to do with Blockscout. The Blockscout instance you are referencing is not run by the Blockscout team and we have no control over that instance nor the chain. Please close this issue.

**Comment by sl1depengwyn** [comment]
This repo is for Blockscout-related questions. Blockscout is an open source blockchain explorer. Thus, your question is out of scope, where the Blockscout team can help, you better contact the chain support directly.
