### ISSUE TITLE
Did not receive any USDT coins 

### ISSUE THREAD

**Issue by Lilwizbaby** [blockscout/blockscout#9772]
### Description

Did not receive any USDT 
![Screenshot_20240401-135725_MetaMask](https://github.com/blockscout/blockscout/assets/157798155/1227c0e0-014c-4c89-b108-716ce5e44007)

### Type of the installation

Docker-compose

### Type of the JSON RPC archive node

0x75160B1461B1b0CBD9c8E107463B0C252E967E2a

### Type of the chain

L1.12

### Link to the page

https://scan.long.openex.network/tx/0xc7e961e3f9c137fe9b44cb993359c947d1571f5c23481fba173ee3eb1e0f2f81

### Steps to reproduce

Return it or send it to my wallet address 

### Backend version

V6.10

### Frontend version

v1.26.2+12f0781e

### Elixir & Erlang/OTP versions

0x75160B1461B1b0CBD9c8E107463B0C252E967E2a

### Operating system

Lilwizbaby56@gmail.com

### Additional information

**User Agent:** Mozilla/5.0 (Linux; Android 9; SM-G950U Build/PPR1.180610.011; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/122.0.6261.105 Mobile Safari/537.36

**Comment by sl1depengwyn** [comment]
This repo is for Blockscout-related questions. Blockscout is an open source blockchain explorer. Thus, your question is out of scope, where the Blockscout team can help, you better contact the chain support directly.
