### ISSUE TITLE
Payment says it went through but the other wallet didn't got any payment!

### ISSUE THREAD

**Issue by Richardobitty** [blockscout/blockscout#9791]
### Description

So I just made a transaction to a wallet and they didn't got anything. I want the money back into my wallet or complete the transaction so I can go further please! It is the last time I'm using this.

### Type of the installation

Docker-compose

### Type of the JSON RPC archive node

My money

### Type of the chain

I don't know

### Steps to reproduce

Man just give me the money. 

### Backend version

Dunno

### Frontend version

You should know go to files man!

### Elixir & Erlang/OTP versions

Go to files

### Operating system

Andriod/Windows 

### Additional information

Just give me my money man what the hell is this?

**Comment by vbaranov** [comment]
This chat is for Blockscout-related questions. Your question is out of scope, where the Blockscout team can help.
