### ISSUE TITLE
log file taking too much space quickly

### ISSUE THREAD

**Issue by BlockgenStudio** [blockscout/blockscout#9793]
### Description

Is there a method to customize the logging storage settings, such as configuring the frequency and level of detail? Currently, the default logging mechanism is causing rapid growth, accumulating 70GB per week, which way exceeds my preferred rate.

### Type of the installation

Manual from the source code

### Type of the JSON RPC archive node

Geth

### Type of the chain

L2

### Backend version

v6.2

### Elixir & Erlang/OTP versions

1.14.5

### Operating system

linux

**Comment by GimluCom** [comment]
Are there any errors in your logs?

**Comment by BlockgenStudio** [comment]
maybe but not the error that is major. for time being, is there a way just reduce or turn off the log?

**Comment by GimluCom** [comment]
Why not correct the error? You may configure it in [`config/`](https://github.com/blockscout/blockscout/tree/master/config) or setup a cron job to delete logs every hour/day.

**Comment by vbaranov** [comment]
@BlockgenStudio you can re-configure log rotation in the codebase

Log rotation config looks like and it is configured for each file individually:
https://github.com/blockscout/blockscout/blob/81179f9459fc6a80944d8490a331c9160d85ecdd/apps/explorer/config/prod.exs#L16

There is no env var to manage log rotation config yet. If you use pre-built image of the Blockscout, you could configure log rotation outside the app via cron as Gimlu noticed.
