### ISSUE TITLE
cant find where my token went on a transaction

### ISSUE THREAD

**Issue by nato001** [blockscout/blockscout#9803]
### Description

i made a swap on degen chain and now have lost money can you help me to revese the transaction or find the money
this is the transaction hash 0x2baf4954b2d1a8965c3372c1b805fac99be25a709ca8631d13d27b8d0e824896

### Type of the installation

Docker

### Type of the JSON RPC archive node

degen chain

### Type of the chain

L3

### Link to the page

https://explorer.degen.tips/tx/0x2baf4954b2d1a8965c3372c1b805fac99be25a709ca8631d13d27b8d0e824896

### Backend version

0x2baf4954b2d1a8965c3372c1b805fac99be25a709ca8631d13d27b8d0e824896

### Elixir & Erlang/OTP versions

degen chain transaction

### Operating system

windows 10

### Additional information

0x2baf4954b2d1a8965c3372c1b805fac99be25a709ca8631d13d27b8d0e824896
this is the transaction hash

**Comment by sl1depengwyn** [comment]
This repo is for Blockscout-related questions. Blockscout is an open source blockchain explorer. Thus, your question is out of scope, where the Blockscout team can help, you better contact the chain support directly.
