### ISSUE TITLE
API not retrieving all transactions and blocks on Gnosis

### ISSUE THREAD

**Issue by JSmithOner** [blockscout/blockscout#9810]
### Description

I'm using google app script to retrieve transactions on gnosis chain. using:

`https://gnosis.blockscout.com/api/v2/addresses/${ walletAddress }/token-transfers?type=ERC-20&filter=to%20%7C%20from`;

if we take for example this wallet `https://gnosisscan.io/tokentxns?a=0x41c9e4464abe3ebef4ab484b8ff65a5dc1a0afd8`
gnosisscan shows 611 transactions but when using the API with `next_page_params` it only retrieves 609.

### Type of the installation

Manual from the source code

### Type of the JSON RPC archive node

no clue

### Type of the chain

Gnosis

### Steps to reproduce
You can:
- use the previously provided endpoint and loop through using `next_page_params`.
- count the number of items retrieved
or:
- try to find this transaction on gnosis scan `0x9a1e6cf69dfc33cf767a82d9d36a83c30e3b67a606708055f0e8b8e37e2ab2ec`
- try to find this same transaction using 
`https://gnosis.blockscout.com/api/v2/transactions/0x9a1e6cf69dfc33cf767a82d9d36a83c30e3b67a606708055f0e8b8e37e2ab2ec`
or:
-try to find this block `30659235` on gnosisscan
- try to find it using the API with endpoint `https://gnosis.blockscout.com/api/v2/blocks/30659235/transactions`

### Backend version

the one used for the gnosis network

### Elixir & Erlang/OTP versions

No clue

**Comment by vbaranov** [comment]
@JSmithOner there was a delay in indexing a part of the chain in the explorer. Currently, all missed blocks and their data have been successfully processed and should be available via API. If you have any issues with that please let me know. I am closing the issue for now.
