### ISSUE TITLE
Не пришли монеты

### ISSUE THREAD

**Issue by Xenon161** [blockscout/blockscout#9811]
### Description

Делал бридж монеты bnb из блокчейна bsc в блокчейн Xterio chain. Все получилось. А обратно из Xterio chain в bsc не получается. Транзакция прошла успешно. А монетки на счет не пришли. Прикрепляю ссылку на обозреватель - https://xterscan.io/tx/0x1614718a7a51420b1f39ff395124cd566b71a24791caa1c37cfaa4f2cc901ee9

### Type of the installation

Docker-compose

### Type of the JSON RPC archive node

-

### Link to the page

https://xterscan.io/tx/0x1614718a7a51420b1f39ff395124cd566b71a24791caa1c37cfaa4f2cc901ee9

### Backend version

v6.1.0-бета

### Elixir & Erlang/OTP versions

-

### Operating system

Windows 10

### Additional information

Google Chrome

**Comment by sl1depengwyn** [comment]
This repo is for Blockscout-related questions. Blockscout is an open source blockchain explorer. Thus, your question is out of scope, where the Blockscout team can help, you better contact the chain support directly.
