### ISSUE TITLE
Degen (Degen) to Degen (Base) swap not showing

### ISSUE THREAD

**Issue by jopark81** [blockscout/blockscout#9817]
### Description

Hello,

I have swapped Degen (Degen) for Degen (Base) and is not competing. Please review the following transaction hash and let me know what's going on. It seems like others encountering the same issue.

Transaction Hash:
0x5e70aaaf969b206c190a62989666712f2f73b800f70d110ffd01f127844e215a

Thank you,

JP

### Type of the installation

Docker-compose

### Type of the JSON RPC archive node

.

### Link to the page

https://explorer.degen.tips/tx/0x5e70aaaf969b206c190a62989666712f2f73b800f70d110ffd01f127844e215a

### Backend version

v6.3.0-beta

### Elixir & Erlang/OTP versions

.

### Operating system

windows 

### Additional information

**User Agent:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.0.0 Safari/537.36 Edg/123.0.0.0

**Comment by sl1depengwyn** [comment]
This repo is for Blockscout-related questions. Blockscout is an open source blockchain explorer. Thus, your question is out of scope, where the Blockscout team can help, you better contact the chain support directly.
