### ISSUE TITLE
My transaction is stuck

### ISSUE THREAD

**Issue by haball99** [blockscout/blockscout#9824]
### Description

My transaction is completed but it remains pending. I tried to cancel the transaction but it is stuck now. I was using Xterio chain and doing mission for palio. I was claiming the items and it get stuck. Can you please look into it? Thanks.
![image](https://github.com/blockscout/blockscout/assets/166069877/e4d18f0b-24f2-46c2-8218-512d14d1ec3a)
![image](https://github.com/blockscout/blockscout/assets/166069877/f533126e-f843-4910-9f7a-e867fce6e4c4)

### Type of the installation

Docker-compose

### Type of the JSON RPC archive node

Xterio

### Type of the chain

L2

### Link to the page

https://xterscan.io/tx/0x1a3e35ddd2feb8d04b04ea863f81cec3019c7218a20f3c1ed0f96aecc25d5bfa

### Steps to reproduce

I claimed the palio item, it was super slow. I cancelled the transaction, it then stuck.

### Backend version

v6.1.0-beta

### Elixir & Erlang/OTP versions

Elixir

### Additional information

**User Agent:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.0.0 Safari/537.36

**Comment by JSmithOner** [comment]
this has to do with metamask not with blockscout I guess

**Comment by sl1depengwyn** [comment]
This repo is for Blockscout-related questions. Blockscout is an open source blockchain explorer. Thus, your question is out of scope, where the Blockscout team can help, you better contact the chain support directly.
