### ISSUE TITLE
PROMtest coin transfer error.

### ISSUE THREAD

**Issue by valeriyyyyhot** [blockscout/blockscout#9831]
### Description

On April 6, as usual, I made a transfer from one wallet to another. the network was very slow all day yesterday, this transaction was no exception. but the PROM test coins did not arrive in the wallet.
there is a transaction hash: 0xc1eaad53d7a5489eb6f07acefdc014ab46dd032c887def7f8ccf49fa3781af22

the address of the wallet that did not reach here: 0x527C3dA087454eb14a6344b6aeA6e599d1F7909e.

it just looks very interesting, the hash of the transaction shows a successful operation, but the wallet is empty :))

### Type of the installation

Docker-compose

### Type of the JSON RPC archive node

prom

### Type of the chain

l1

### Link to the page

https://testnet.promscan.io/tx/0xc1eaad53d7a5489eb6f07acefdc014ab46dd032c887def7f8ccf49fa3781af22

### Backend version

v6.3.0-beta

### Elixir & Erlang/OTP versions

otp\erlang

### Operating system

windows

### Additional information

**User Agent:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.0.0 Safari/537.36

**Comment by valeriyyyyhot** [comment]
I apologize if I filled in some fields incorrectly. doing it for the first time

**Comment by sl1depengwyn** [comment]
This repo is for Blockscout-related questions. Blockscout is an open source blockchain explorer. Thus, your question is out of scope, where the Blockscout team can help, you better contact the chain support directly.
