### ISSUE TITLE
Couldn't update gas used gas_prices** (ArgumentError) implicit conversion of 18000.0 to Decimal is not allowed

### ISSUE THREAD

**Issue by mrchipdev** [blockscout/blockscout#9834]
### Description

Hello,

I run mix phx.server and get the following error when I access /api/v2/stats
And it doesn't show Gas tracker value. 
Please tell me what error this is and if we can fix it

> 2024-04-06T19:33:57.006 application=explorer [error] Couldn't update gas used gas_prices** (ArgumentError) implicit conversion of 18000.0 to Decimal is not allowed. Use Decimal.from_float/1
    (decimal 2.1.1) lib/decimal.ex:1915: Decimal.decimal/1
    (decimal 2.1.1) lib/decimal.ex:276: Decimal.add/2
    (elixir 1.14.5) lib/enum.ex:2468: Enum."-reduce/3-lists^foldl/2-0-"/3
    (explorer 6.4.0) lib/explorer/chain/cache/gas_price_oracle.ex:250: anonymous fn/1 in Explorer.Chain.Cache.GasPriceOracle.merge_fees/1
    (elixir 1.14.5) lib/map.ex:258: Map.do_map/2
    (elixir 1.14.5) lib/map.ex:258: Map.do_map/2
    (elixir 1.14.5) lib/map.ex:252: Map.new_from_map/2
    (explorer 6.4.0) lib/explorer/chain/cache/gas_price_oracle.ex:203: Explorer.Chain.Cache.GasPriceOracle.process_fee_data_from_db/1
    (explorer 6.4.0) lib/explorer/chain/cache/gas_price_oracle.ex:173: Explorer.Chain.Cache.GasPriceOracle.get_average_gas_price/4
    (explorer 6.4.0) lib/explorer/chain/cache/gas_price_oracle.ex:319: anonymous fn/0 in Explorer.Chain.Cache.GasPriceOracle.handle_fallback/1
    (elixir 1.14.5) lib/task/supervised.ex:89: Task.Supervised.invoke_mfa/2
    (stdlib 4.3) proc_lib.erl:240: :proc_lib.init_p_do_apply/3

### Type of the installation

Manual from the source code

### Type of the JSON RPC archive node

Geth

### Backend version

v6.4.0

### Frontend version

v1.28.0

### Elixir & Erlang/OTP versions

Elixir 1.14

### Operating system

Linux

**Comment by InoMurko** [comment]
```
{"time":"2024-08-03T08:51:21.050Z","severity":"error","message":"Couldn't update gas used gas_prices** (ArgumentError) implicit conversion of 7095.0 to Decimal is not allowed. Use Decimal.from_float/1\n    (decimal 2.1.1) lib/decimal.ex:1915: Decimal.decimal/1\n    (decimal 2.1.1) lib/decimal.ex:276: Decimal.add/2\n    (elixir 1.16.3) lib/enum.ex:2528: Enum.\"-reduce/3-lists^foldl/2-0-\"/3\n    (explorer 6.7.2) lib/explorer/chain/cache/gas_price_oracle.ex:254: anonymous fn/1 in Explorer.Chain.Cache.GasPriceOracle.merge_fees/1\n    (elixir 1.16.3) lib/map.ex:257: Map.do_map/2\n    (elixir 1.16.3) lib/map.ex:251: Map.new_from_map/2\n    (explorer 6.7.2) lib/explorer/chain/cache/gas_price_oracle.ex:207: Explorer.Chain.Cache.GasPriceOracle.process_fee_data_from_db/1\n    (explorer 6.7.2) lib/explorer/chain/cache/gas_price_oracle.ex:177: Explorer.Chain.Cache.GasPriceOracle.get_average_gas_price/4\n","metadata":{}}
```

still appearing
