### ISSUE TITLE
Transaction delay 

### ISSUE THREAD

**Issue by Mattie4dl** [blockscout/blockscout#9836]
### Description

Whenever a Over token is transferred to my wallet it doesn't come in on time and also whenever i sent out token it will show success but it take time to land. 

### Type of the installation

Manual from the source code

### Type of the JSON RPC archive node

Erigon

### Type of the chain

L1

### Link to the page

https://scan.long.openex.network/tokens

### Steps to reproduce

Decrease transaction delay to have fast transfer 

### Backend version

v6. 1.0

### Frontend version

v1.26.2+12f0781e

### Elixir & Erlang/OTP versions

Elixir 

### Operating system

Linux 

### Additional information

**User Agent:** Mozilla/5.0 (Linux; Android 7.0; Infinix X559C Build/NRD90M; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/119.0.6045.193 Mobile Safari/537.36

**Comment by vbaranov** [comment]
Blockscout team doesn't manage this instance of Blockscout. You should ask the question to the team, which supports this chain.
