### ISSUE TITLE
Bridge without a result after two hrs

### ISSUE THREAD

**Issue by Sanadakimu** [blockscout/blockscout#9839]
### Description

Hi there, I recently have breached some MATIC from POLYGON to DEGEN but it hasn`t being transferred to my wallet. what should I do?

### Type of the installation

Docker-compose

### Type of the JSON RPC archive node

bridge degen

### Type of the chain

L3

### Link to the page

https://explorer.degen.tips/address/0x72Af20f7F5dFd8fDD65afd8799251E728b5925a3

### Backend version

v6.3.0-beta

### Elixir & Erlang/OTP versions

no

### Additional information

**User Agent:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.0.0 Safari/537.36

**Comment by sl1depengwyn** [comment]
This repo is for Blockscout-related questions. Blockscout is an open source blockchain explorer. Thus, your question is out of scope, where the Blockscout team can help, you better contact the chain support directly.
