### ISSUE TITLE
Sent Funds to one of my own wrong address. 

### ISSUE THREAD

**Issue by keshgina8** [blockscout/blockscout#9845]
### Description

Transaction Hash
0x68be6117a7832b2f6d2f0cfe60135ee64f0a6e115b2d749ce85cd2273375f551
 Result
 Success
 Status
Confirmed Confirmed by 1,038
 Block
[9341330](https://kavascan.com/block/9341330)
 Timestamp
 2 hours ago | April-08-2024 04:36:58 PM +-4 UTC | Confirmed within <= 6.141 seconds
 From
[Kucoin (0xfb6a73–eb062d)](https://kavascan.com/address/0xfB6a733bf7eC9CE047c1c5199F18401052Eb062D)
 To
[0xB379D356fE43122738DcB3208649a57A0D175301](https://kavascan.com/address/0xB379D356fE43122738DcB3208649a57A0D175301)
 Value
314.5091 KAVA ($308.28 USD)
 Transaction Fee
0.000021 KAVA ($0.000021 USD)
 Gas Price
1 nanoKAVA
 Transaction Type
0
 Gas Limit
21,000
 Gas Used by Transaction
21,000 | 100%
 NoncePosition
184111

### Type of the installation

Docker-compose

### Type of the JSON RPC archive node

geth

### Backend version

v5.3.3-kava

### Elixir & Erlang/OTP versions

Elixir 1.14.5 Erlang/OTP 25

### Operating system

unix linux

### Additional information

The issue happened at Kava 10 Blockscout instance

**Comment by sl1depengwyn** [comment]
This repo is for Blockscout-related questions. Blockscout is an open source blockchain explorer. Thus, your question is out of scope, where the Blockscout team can help, you better contact the chain support directly.
