### ISSUE TITLE
Zeta not received 

### ISSUE THREAD

**Issue by WNAYSS** [blockscout/blockscout#9846]
### Description

I didn't receive my 8 zeta that's the hash
0x79dd2af9970f3388ab6aa1b234f48600bae25eeb1e71fbdb805dd29d795466af

### Type of the installation

Docker-compose

### Type of the JSON RPC archive node

0x79dd2af9970f3388ab6aa1b234f48600bae25eeb1e71fbdb805dd29d795466af

### Type of the chain

Zetachain

### Link to the page

https://zetachain.blockscout.com/tx/0x79dd2af9970f3388ab6aa1b234f48600bae25eeb1e71fbdb805dd29d795466af

### Steps to reproduce

I didn't receive my 8 zeta send from mexc to Coinbase hash is
0x79dd2af9970f3388ab6aa1b234f48600bae25eeb1e71fbdb805dd29d795466af

### Backend version

v6.3.0-beta.+commit.17fa9ef0

### Frontend version

v1.28.0+05301955

### Elixir & Erlang/OTP versions

Elixir

### Operating system

Windows 

### Additional information

**User Agent:** Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/118.0.0.0 Mobile Safari/537.36

**Comment by sl1depengwyn** [comment]
This repo is for Blockscout-related questions. Blockscout is an open source blockchain explorer. Thus, your question is out of scope, where the Blockscout team can help, you better contact the chain support directly.
