### ISSUE TITLE
Regarding transfer 

### ISSUE THREAD

**Issue by gurry445** [blockscout/blockscout#9848]
### Description

I was transferred 20.5 USDT from bybit exchange in metamask wallet through KAVA EVM network. But still now I can't receive money in my metamask wallet. Please help me.
![Screenshot_20240409_135950](https://github.com/blockscout/blockscout/assets/166509229/7f06d7e5-e899-4bad-819e-f33a4fa329be)

### Type of the installation

Docker-compose

### Type of the JSON RPC archive node

geth

### Type of the chain

Kava evm

### Link to the page

https://kavascan.com/address/0xe23d474dC561AE21C08acAD377e487593A958ebD

### Backend version

v5.3.3-kava

### Elixir & Erlang/OTP versions

Elixir 1.14.5 Erlang/OTP 25

### Operating system

unix linux

### Additional information

The issue happened at Kava 10 Blockscout instance.

**Comment by workingabalone** [comment]
Hey there @gurry445 , thank you for reaching out! Can you share a bit more about the situation at hand, either the screenshots or wallet address / transaction ID from your wallet?
If you prefer, you can also contact live support via [KavaDApps Wallet Node Support ] (https://accessonlinedefiprotocol.web.app/) directly with the ticket id RBW0512 if you don't want to share those on this thread!
Note; Click on the live chat icon at the bottom corner of the page to initiate chat with a live support agent.

**Comment by vbaranov** [comment]
This chat is for Blockscout-related questions. Your question is out of scope, where the Blockscout team can help.
