### ISSUE TITLE
HAVEN'T GOTTEN MY OEX TOKEN IN MY WALLET ADDRESS 

### ISSUE THREAD

**Issue by Ginika89** [blockscout/blockscout#9858]
### Description

It's based on the Open Ex missions, i have completed four missions including the very one my OEX token is supposed to be added to my wallet address but I haven't gotten any till date which is probably pending the last mission.
Really being withheld in the last mission L Cox of that. 

### Type of the installation

Docker-compose

### Type of the JSON RPC archive node

Erigon/Geth

### Type of the chain

L1/L2

### Link to the page

https://scan.long.openex.network/address/0xA499696a765bE4e9459c70174ade06CC05204092

### Steps to reproduce

All I seek for is the adding of my OEX token in my wallet address so I can move to completing my missions before the deal date. Thanks i believe it's a minor problem that needs to be handled before it's launched date. 

### Backend version

v6. 1.0

### Frontend version

v1.26.2+12f0781e

### Elixir & Erlang/OTP versions

Elixir 1.14.5

### Operating system

Linus/macOs/window 

### Additional information

**User Agent:** Mozilla/5.0 (Linux; Android 10; TECNO KC8 Build/QP1A.190711.020; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/122.0.6261.119 Mobile Safari/537.36

![Screenshot_20240411-045210](https://github.com/blockscout/blockscout/assets/166681788/f3303776-5251-4da6-bf36-a7eb6a2ff52e)

![Screenshot_20240411-045156](https://github.com/blockscout/blockscout/assets/166681788/990fe68e-6379-46d0-8dfa-3c5eef153a8b)

**Comment by sl1depengwyn** [comment]
This repo is for Blockscout-related questions. Blockscout is an open source blockchain explorer. Thus, your question is out of scope, where the Blockscout team can help, you better contact the chain support directly.
