### ISSUE TITLE
liquidity removal fund not arrive 

### ISSUE THREAD

**Issue by iamuneeb** [blockscout/blockscout#9875]
### Description

i provide liquidity 2 days before but now i remove it so the asset not recieve yet 
wallet address is 0xDF01fEF0658A123FAaFC86eC3483bB9b6C6f860C
tx hash 0x081dc1bf1d8882399a5cffa7e11f67e6f19ce0bd64d48b4f76259a14b286af12

### Type of the installation

Docker-compose

### Type of the JSON RPC archive node

kfmed

### Link to the page

https://explorer.mode.network/tx/0x081dc1bf1d8882399a5cffa7e11f67e6f19ce0bd64d48b4f76259a14b286af12

### Backend version

v6.3.0-beta

### Elixir & Erlang/OTP versions

erfd

### Additional information

**User Agent:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.0.0 Safari/537.36

**Comment by vbaranov** [comment]
This chat is for Blockscout-related questions. Your question is out of scope, where the Blockscout team can help.
