### ISSUE TITLE
A test usdt sent from trust wallet did not arrive to the oex platform what might be the problem?

### ISSUE THREAD

**Issue by Cmgichuki** [blockscout/blockscout#9876]
### Description

Hello I sent 1usdt to an account on the oex platform that has not yet reflected.

### Type of the installation

Docker

### Type of the JSON RPC archive node

Erigon

### Type of the chain

Long testnet

### Link to the page

https://scan.long.openex.network/address/0xb0C3F206e0a130Db52A0354cBC377e9FC54470eF

### Steps to reproduce

Text me back.

### Backend version

V alpha18

### Frontend version

v1.26.2+12f0781e

### Elixir & Erlang/OTP versions

Elixir &erlang

### Operating system

Android 13

### Additional information

**User Agent:** Mozilla/5.0 (Linux; Android 13; V2310 Build/TP1A.220624.014_NONFC; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/123.0.6312.99 Mobile Safari/537.36

**Comment by vbaranov** [comment]
This chat is for Blockscout-related questions. Your question is out of scope, where the Blockscout team can help. You should contact exchange support.
