### ISSUE TITLE
Have not received usdt transferred from kucoin 

### ISSUE THREAD

**Issue by Onyiisky2** [blockscout/blockscout#9882]
### Description

Yet to receive usdt transferred from kucoin community 

### Type of the installation

Docker-compose

### Type of the JSON RPC archive node

geth

### Backend version

v5.3.3-kava

### Elixir & Erlang/OTP versions

Elixir 1.14.5 Erlang/OTP 25

### Operating system

unix linux

### Additional information

The issue happened at Kava 10 Blockscout instance

**Comment by vbaranov** [comment]
This chat is for Blockscout-related questions. Your question is out of scope, where the Blockscout team can help.
