### ISSUE TITLE
Misidentifying non-ERC-20 contracts as ERC-20

### ISSUE THREAD

**Issue by lyfsn** [blockscout/blockscout#9901]
### Description

Due to this PR:
https://github.com/blockscout/blockscout/pull/7653/files#diff-f361e4f9074748318960424dc947ccec166d7630df1322526105b22749b7ac37R179

Blockscout will identify any contract that emits this event:
```
event Deposit(address indexed user, uint256 amount);
```

Blockscout will incorrectly identify a contract as ERC-20, although it is actually not an ERC-20 contract. This will result in many erroneous queries to the node, such as `balanceOf` requests.

This whole contract source code example:
```
// SPDX-License-Identifier: MIT
pragma solidity ^0.8.20;

import "@openzeppelin/contracts/access/Ownable.sol";

contract DepositETH is Ownable {
    event Deposit(address indexed user, uint256 amount);
    mapping(address => uint) public totalDeposits;
    uint256 public totalUniqueDepositors;

    constructor(address initialOwner) Ownable(initialOwner) {}

    receive() external payable {
        uint256 oldValue = totalDeposits[msg.sender];
        if (oldValue == 0) {
            totalUniqueDepositors++;
        }
        totalDeposits[msg.sender] += msg.value;
        emit Deposit(msg.sender, msg.value);
    }

    function getTotalDepositOf(address user) external view returns (uint256) {
        return totalDeposits[user];
    }

    function getTotalDepositFrom(
        address[] calldata users
    ) external view returns (uint256[] memory) {
        uint256[] memory result = new uint256[](users.length);
        for (uint256 i = 0; i < users.length; i++) {
            result[i] = totalDeposits[users[i]];
        }
        return result;
    }

    function withdraw() external onlyOwner {
        payable(owner()).transfer(address(this).balance);
    }
}
```
1. Deploy it to a network;
2. Send any amount to this contract.

You will get an "Unnamed token":

<img width="661" alt="Screenshot 2024-04-17 at 15 24 35" src="https://github.com/blockscout/blockscout/assets/141099829/8ac3537f-2ad4-4e5d-aec9-3691d6272b4c">

### Type of the installation

Docker-compose

### Type of the JSON RPC archive node

Geth

### Backend version

v6.3.0-beta

### Elixir & Erlang/OTP versions

Elixir

**Comment by abdouferraq** [comment]
![Screenshot_2024-05-25-04-44-14-976_com binance dev](https://github.com/blockscout/blockscout/assets/170783134/95cce997-6380-4b68-ac9c-e0b4f3eca970)
![Screenshot_2024-05-25-04-44-08-134_com binance dev](https://github.com/blockscout/blockscout/assets/170783134/ded38bb4-89c6-4d51-b4c0-7b78e20ba1ea)
![Screenshot_2024-05-25-04-43-33-663_com binance dev](https://github.com/blockscout/blockscout/assets/170783134/0223ed98-2aaa-407d-a86d-7cb3bcd88dd8)
![Screenshot_2024-05-25-04-42-43-798_com binance dev](https://github.com/blockscout/blockscout/assets/170783134/516652ad-3f83-40a9-a4dc-46826c57da0a)
![Screenshot_2024-05-25-04-42-38-046_com binance dev](https://github.com/blockscout/blockscout/assets/170783134/34a44c87-6b0e-48dc-96e5-26440eb2ba99)
![Screenshot_2024-05-25-04-27-00-530_com blockabc cctip](https://github.com/blockscout/blockscout/assets/170783134/d3ada12a-8f88-4052-aa0e-c7c957938dc4)

**Comment by lyfsn** [comment]
Fixed in https://github.com/blockscout/blockscout/pull/10018
