### ISSUE TITLE
after withdraw my token lost

### ISSUE THREAD

**Issue by yaowyaow83** [blockscout/blockscout#9918]
### Description

![Screenshot_2024-04-20-15-06-18-313_com binance dev](https://github.com/blockscout/blockscout/assets/21078590/d1c063a2-9f92-4299-b4db-47e6d0acc850)

i duno what happen after withdraw my token lost ya
0x2eeaf94cbb7cb4c5ac776c7fad5b3a07f4b2ba45

### Type of the installation

Docker-compose

### Type of the JSON RPC archive node

BEVM

### Type of the chain

L2

### Link to the page

https://scan-mainnet.bevm.io/address/0x2eeaf94cbb7cb4c5ac776c7fad5b3a07f4b2ba45

### Backend version

v6.4.0-beta

### Elixir & Erlang/OTP versions

duno

### Operating system

android

### Additional information

**User Agent:** Mozilla/5.0 (Linux; Android 13; 2109119DG Build/TKQ1.220829.002; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/123.0.6312.118 Mobile Safari/537.36 BNC/2.81.6 BMP/4.25.1 NetType/4G  Language/zh-CN

**Comment by sl1depengwyn** [comment]
This repo is for Blockscout-related questions. Blockscout is an open source blockchain explorer. Thus, your question is out of scope, where the Blockscout team can help, you better contact the chain support directly.
