### ISSUE TITLE
Reg: zkasinio not available in TRUST WALLET 

### ISSUE THREAD

**Issue by Dharmalingam369** [blockscout/blockscout#9920]
### Description

Dear sir I am using for bridge ETH deposit using TRUST WALLET. Still now i am not add our ZKasino chain. So many time tried, kindly solve this problem. And kindly help to me . My full funds in our bridge deposit process.kindly help to me

### Type of the installation

Docker-compose

### Type of the JSON RPC archive node

Erigon/Geth

### Type of the chain

L1

### Link to the page

https://explorer.zkasino.io/

### Backend version

V61.0

### Elixir & Erlang/OTP versions

Elixir

### Additional information

**User Agent:** Mozilla/5.0 (iPhone; CPU iPhone OS 17_4_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Mobile/15E148

**Comment by Dharmalingam369** [comment]
Sir kindly solve this issue

**Comment by sl1depengwyn** [comment]
This repo is for Blockscout-related questions. Blockscout is an open source blockchain explorer. Thus, your question is out of scope, where the Blockscout team can help, you better contact the chain support directly.
