### ISSUE TITLE
Did not receive ETH in Binance sent from Metamask.

### ISSUE THREAD

**Issue by KKRG1994** [blockscout/blockscout#9935]
### Description

I sent ETH (0.01838464 ETH) from my metamask wallet to Binance. But did not get it. its been over an hour now. Can you please check.

Metamask wallet: 0x04ff0838E7974068b579FCf61d0aEAdc9C33bbdD
Binance wallet: 0x5eF7892DcFDf652A9967Fb52E5C32df502359e17

Block #5396903
Hash: 0x1299e7821864e641637b20fbd1ec4677b7602aab9f31dfe72250f6b2347aa5be
Parent Hash: 0x3368d2231078ed6329075a8406100efcf5f2fef7956f99afe45401c92d8f9e98
Nonce: 0x0000000000001c30

Validated By: 0xA4b000000000000000000073657175656e636572

### Type of the installation

Docker-compose

### Type of the JSON RPC archive node

Etherium

### Link to the page

https://explorer.apex.proofofplay.com/tx/0x88d1a7cf846ded2e6550cb80ab1c8094d7ff44a57ae65b427e53ff8594896ea4?tab=state

### Backend version

v6.3.0-beta

### Elixir & Erlang/OTP versions

No idea

### Operating system

Windows

### Additional information

**User Agent:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.0.0 Safari/537.36

**Comment by sl1depengwyn** [comment]
This repo is for Blockscout-related questions. Blockscout is an open source blockchain explorer. Thus, your question is out of scope, where the Blockscout team can help, you better contact the chain support directly.
