### ISSUE TITLE
Funds send from wrong network

### ISSUE THREAD

**Issue by KKRG1994** [blockscout/blockscout#9936]
### Description

I accidentally sent ETH from Apex network to Binance. can you please help me revert this transaction. 

TXID: 0x88d1a7cf846ded2e6550cb80ab1c8094d7ff44a57ae65b427e53ff8594896ea4

### Type of the installation

Docker-compose

### Type of the JSON RPC archive node

Apex

### Link to the page

https://explorer.apex.proofofplay.com/tx/0x88d1a7cf846ded2e6550cb80ab1c8094d7ff44a57ae65b427e53ff8594896ea4

### Backend version

v6.3.0-beta

### Elixir & Erlang/OTP versions

No idea

### Additional information

**User Agent:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.0.0 Safari/537.36

**Comment by KKRG1994** [comment]
i already asked Binance about it, if they can reverse the transactions. but they cannot do anything about it as the token chain is unlisted there.

**Comment by vbaranov** [comment]
This chat is for Blockscout-related questions. Your question is out of scope, where the Blockscout team can help.
