### ISSUE TITLE
I didn’t get my amount in my Binance account 

### ISSUE THREAD

**Issue by kingrasel71** [blockscout/blockscout#9945]
### Description

I sent 1.8 Oex token to my Binance account more than 1 hour ago but didn’t get my price in my account. 

### Type of the installation

Docker-compose

### Type of the JSON RPC archive node

Binance 

### Type of the chain

L1

### Link to the page

https://scan.long.openex.network/tx/0x7d0740799cb903dd05b880bc1b26848acbf1f3816abf8ffc717258a8e529c681

### Backend version

None

### Frontend version

v1.26.2+12f0781e

### Elixir & Erlang/OTP versions

None 

### Operating system

Android 

### Additional information

**User Agent:** Mozilla/5.0 (Linux; Android 12; itel S665L Build/SP1A.210812.016; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/123.0.6312.118 Mobile Safari/537.36

**Comment by sl1depengwyn** [comment]
This repo is for Blockscout-related questions. Blockscout is an open source blockchain explorer. Thus, your question is out of scope, where the Blockscout team can help, you better contact the chain support directly.
