### ISSUE TITLE
I traded on runechain in the rsic-genesis token, my tokens disappeared

### ISSUE THREAD

**Issue by V3RNEX** [blockscout/blockscout#9966]
### Description

I traded on runechain in the rsic-genesis token, my tokens disappeared

Hash 0xf99daa95e3948a2e36f38481acdf0c4bcd93070aa5420111fc6c217c3f5daa62

### Type of the installation

Docker-compose

### Type of the JSON RPC archive node

geth

### Backend version

v6.2.2-beta.+commit.a2527887

### Elixir & Erlang/OTP versions

Elixir 1.14.5 Erlang/OTP 24

### Operating system

unix linux

### Additional information

The issue happened at RUNECHAIN Blockscout instance

**Comment by vbaranov** [comment]
This chat is for Blockscout-related questions. Your question is out of scope, where the Blockscout team can help.
