### ISSUE TITLE
Transaction not found 

### ISSUE THREAD

**Issue by mozumder390** [blockscout/blockscout#9967]
### Description

I was buying 2 nft from nft.vigorscan.com gas fee was deducted from my metamask wallet but but no any transactions found on vigor scan, my metamask wallet address is
0x67De31f3f6C290badcbB0795F60Bcb496659d18E
![Screenshot_20240427-073300_MetaMask](https://github.com/blockscout/blockscout/assets/79043796/e970b0be-969d-43b6-8718-e9016436a305)

### Type of the installation

Docker-compose

### Type of the JSON RPC archive node

geth

### Backend version

v5.3.1-beta.+commit.c472f7bb

### Elixir & Erlang/OTP versions

Elixir 1.14.5 Erlang/OTP 24

### Operating system

unix linux

### Additional information

The issue happened at Vigor Chain Mainnet Blockscout instance

**Comment by vbaranov** [comment]
Blockscout team doesn't manage this instance of Blockscout. You should ask the question to the team, which supports this chain.
