### ISSUE TITLE
Public tags: dedicated tag page API handle

### ISSUE THREAD

**Issue by NikitaSavik** [blockscout/blockscout#9976]
In order to enrich hashes returned from microservice with metadata (minimum - txn count + eth balance), we need new API handle to show the page content

[Frontend task](https://github.com/orgs/blockscout/projects/6/views/1?pane=issue&itemId=61324142)

**Comment by lok52** [comment]
API endpoint for getting paginated tag's addresses: `/api/v1/addresses`
Swagger: https://app.swaggerhub.com/apis/lok52/metadata/1.0.0#/
