### ISSUE TITLE
Unable to mint premium nft on vigor chain

### ISSUE THREAD

**Issue by Halarh01** [blockscout/blockscout#9981]
### Description

I'm unable to mint vigor token premium nft even after successfully minting 3 profile nfts. It keep saying I need to mint a profile nft first while I have done that already 
![Screenshot_20240430-065136](https://github.com/blockscout/blockscout/assets/168514046/495c030c-cd90-48dc-8035-3216aa1f6909)

### Type of the installation

Docker

### Type of the JSON RPC archive node

geth

### Backend version

v5.3.1-beta.+commit.c472f7bb

### Elixir & Erlang/OTP versions

Elixir 1.14.5 Erlang/OTP 24

### Operating system

unix linux

### Additional information

The issue happened at Vigor Chain Mainnet Blockscout instance

**Comment by vbaranov** [comment]
This chat is for Blockscout-related questions. Your question is out of scope, where the Blockscout team can help.
