### ISSUE TITLE
BNB is not accepted

### ISSUE THREAD

**Issue by SWAM794544** [blockscout/blockscout#9990]
### Description

![Image_20240430215450](https://github.com/blockscout/blockscout/assets/168559432/5b546e19-1e8d-47da-8e1e-62815a085d1c)

### Type of the installation

Docker-compose

### Type of the JSON RPC archive node

BNB

### Type of the chain

Xterio Chain

### Link to the page

https://xterscan.io/tx/0x85d67ab0d27e3627bbd5b6c9431249a6c398df9d8fbfb1013b9cc958764edbc0

### Steps to reproduce

https://xterscan.io/tx/0x85d67ab0d27e3627bbd5b6c9431249a6c398df9d8fbfb1013b9cc958764edbc0

### Backend version

v6.5.0-beta

### Frontend version

v1.11

### Elixir & Erlang/OTP versions

1.14

### Operating system

windows

### Additional information

**User Agent:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36

**Comment by SWAM794544** [comment]
![Image_20240430215450](https://github.com/blockscout/blockscout/assets/168559432/66a0e523-456c-4012-a174-5cfda49ccf78)
Why did it take so long?
https://xterscan.io/tx/0x85d67ab0d27e3627bbd5b6c9431249a6c398df9d8fbfb1013b9cc958764edbc0

Please Check

**Comment by vbaranov** [comment]
Blockscout team doesn't manage this instance of Blockscout. You should ask the question to the team, which supports this chain.
